### ISSUE TITLE
Add a README.md to `test/BaselineOutput`

### ISSUE THREAD

**Issue by markusweimer** [dotnet/machinelearning#100]
We should have a `README.md` to the `test/BaselineOutput` folder to explain its purpose.

(Updated on 2018-07-02 to reflect the new location of the folder)

**Comment by glebuk** [comment]
We should also consider moving the folder under /tests to make it less obvious.

**Comment by Ivanidzo4ka** [comment]
Does anyone remember why it's called ZBaselines instead of just baselines or TestBaselines?

**Comment by costin-eseanu** [comment]
Because it would be sorted last in the folder view, so it's easy to find. :)

**Comment by justinormont** [comment]
Agreed w / @glebuk & @Ivanidzo4ka (move+rename). Placing under /test/baselineOutput/ may be easier to understand its purpose.

**Comment by Ivanidzo4ka** [comment]
So if we call it Baselines inside test folder, it would be first, and it would be easy to find as well!
Should we create issue to move baselines to test folder and rename them?

**Comment by justinormont** [comment]
What do we think the best name for it is? Terse + understandable is my metric to optimize.

Also, welcome @costin-eseanu!

**Comment by TomFinley** [comment]
@justinormont I like your `/test/BaselineOutput` suggestion.

The intention of that directory is that it mirrors the `TestOutput` directory, produced by our tests. (In this way we can review any divergences between the *expected* output (in the baselines), and the *actual* output (as actually output by the test.

The test outputs used to be written just to the root directory, alongside `ZBaselines`. I *might* like them to be written to `/test/TestOutput`... that way, you get the two peer directories right next to each other.

Right now, as near as I can tell, the test output is not being written to a single directory, which makes tracking changes to baselines harder to find, and makes the practice of using diff tools to see all the test divergences at a glance now impossible (I have, for example, one `TestOutput` directory at `Microsoft.ML.Core.Tests\netcoreapp2.0\TestOutput` in my build, and another `TestOutput` directory at ``). Also it's being put in a very, very odd location: the `bin` directory right next to the test assemblies. I'm not sure the binary directory is really an appropriate location for test output.

I'm not sure why it was changed to this new system exactly, but we should revisit, maybe instead writing them to `test/TestOutput`, or something.

**Comment by Ivanidzo4ka** [comment]
DRI RESPONSE: yes, we probably should. Basically this is folder where we keep baseline files for our tests.
Marking this as up-for-grabs.
