### ISSUE TITLE
CDN Compression Needs to be Enabled

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning#1000]
Enable CDN content compression. Content sourced from our CDN arrives without gzip/deflate/brotli compression enabled. 

Larger content from our CDN (like the 6GB fastText word embedding) takes too long to download, and can hit the [10min timeout](https://github.com/dotnet/machinelearning/blob/1e7b8be855210f2bd8adbd532396a1840a20541d/src/Microsoft.ML.Transforms/Text/WordEmbeddingsTransform.cs#L149) before finishing. 

Our CDN content lacks the `Content-Encoding: ...` header:
```bash
$ curl -L -I --compress https://aka.ms/tlc-resources/WordVectors/wiki.en.vec
HTTP/1.1 301 Moved Permanently
Content-Length: 0
Location: https://express-tlcresources.azureedge.net/wordvectors/wiki.en.vec
Server: Kestrel
Request-Context: appId=cid-v1:26ef1154-5995-4d24-ad78-ef0b04f11587
X-Powered-By: ASP.NET
Expires: Mon, 24 Sep 2018 18:39:45 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 24 Sep 2018 18:39:45 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000 ; includeSubDomains

HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Type: application/octet-stream
Date: Mon, 24 Sep 2018 18:39:44 GMT
Etag: 0x8D5AEF4AA45D753
Expires: Mon, 24 Sep 2018 18:39:44 GMT
Last-Modified: Mon, 30 Apr 2018 23:46:59 GMT
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-blob-type: BlockBlob
x-ms-lease-status: unlocked
x-ms-request-id: ef682e2a-b01e-0113-2235-5442d7000000
x-ms-version: 2009-09-19
Content-Length: 6597238061
```

Compare to content from bing.com, which does have its `Content-Encoding: gzip` header:
```bash
$ curl -L -I --compress https://www.bing.com
HTTP/1.1 200 OK
Cache-Control: private, max-age=0
Content-Length: 0
Content-Type: text/html; charset=utf-8
Content-Encoding: gzip
Vary: Accept-Encoding
P3P: CP="NON UNI COM NAV STA LOC CURa DEVa PSAa PSDa OUR IND"
Set-Cookie: SRCHD=AF=NOFORM; domain=.bing.com; expires=Thu, 24-Sep-2020 18:41:32 GMT; path=/
  ... trimmed for brevity
```

**Comment by justinormont** [comment]
I enabled CDN compression as per instructions @ https://docs.microsoft.com/en-us/azure/cdn/cdn-improve-performance. I added `application/octet-stream` as a compressible content-type. 

It appears we will be affected by the 8 MB limit: 
> For Azure CDN Standard from Microsoft profiles, only eligible files are compressed. To be eligible for compression, a file must: 
> * Be of a MIME type that has been configured for compression.
> * Be larger than 1 KB 
> * **Be smaller than 8 MB**

The change will take some time to propagate, so we'll see if the 8 MB limit is still in place.

**Comment by codemzs** [comment]
Thanks but this is not on our roadmap for considerable future.
