### ISSUE TITLE
Another Update in KeyToVector's ONNX exporter

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#1010]
The key range should starts with zero. The following change fixes this bug with the latest runtime.
-`node.AddAttribute("cats_int64s", Enumerable.Range(1, info.TypeSrc.ItemType.KeyCount).Select(x => (long)x));`
+`node.AddAttribute("cats_int64s", Enumerable.Range(0, info.TypeSrc.ItemType.KeyCount).Select(x => (long)x));`

**Comment by codemzs** [comment]
Why does key range need to start from zero and not one?

**Comment by wschin** [comment]
Because TermTransform got converted into LabelEncoder with classes_strings=[terms learned from the training data], the first element is always mapped to 0, which is originally a key value in ML.NET. For example, if "classes_strings" is ["B", "A", "C"] and input is ["B", "B", "C"], then the expected output is [0, 0, 2].

**Comment by codemzs** [comment]
private void KeyMapper(ref ReadOnlyMemory<char> src, ref uint dst)
                {
                    var nstr = ReadOnlyMemoryUtils.FindInPool(src, _pool);
                    if (nstr == null)
                        dst = 0;
                    else
                        dst = (uint)nstr.Id + 1;
                }
