### ISSUE TITLE
How to build for netcoreapp3.0

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/machinelearning#1011]
We should document how to build to run on .NET Core 3.0 (so as to use the .NET hardware intrinsics)

I tried various ideas such as `build -- /p:targetframework=netcoreapp3.0` but didn't succeed yet.

@eerhardt  ?

**Comment by eerhardt** [comment]
Yes, there's a few fixes I am making as part of writing these instructions. Hope to have them out by EOD.
