### ISSUE TITLE
PredictionEngine benchmark test

### ISSUE THREAD

**Issue by najeeb-kazmi** [dotnet/machinelearning#1013]
Add benchmark test to measure performance of single predictions made by PredictionEngine.

**Comment by najeeb-kazmi** [comment]
Here are the before and after results from running PredictionEngineBench on the three prediction models in the benchmark. The benchmarks do a single prediction 10000 times on each model, and each benchmark is run 20 times, with the average runtimes reported in the tables below, along with the standard deviations. We see the following speedups in average runtime:
- 112x speedup on predictions on Iris data.
- 8.68x speedup on predictions on Sentiment data. This model contains a text featurizer, so it is not surprising that we see a smaller gain.
- 109x speed up on predictions on Breast Cancer data.



### Before:

|                      Method |     Mean |    Error |   StdDev |
|---------------------------- |---------|---------|---------|
|         MakeIrisPredictions | 338.0 ms | 4.951 ms | 4.389 ms |
|    MakeSentimentPredictions | 447.7 ms | 7.453 ms | 6.607 ms |
| MakeBreastCancerPredictions | 148.2 ms | 2.317 ms | 2.054 ms |


### After:

|                      Method |      Mean |     Error |    StdDev |
|---------------------------- |----------|----------|----------|
|        MakeIrisPredictions |  3.019 ms | 0.0388 ms | 0.0363 ms |
|    MakeSentimentPredictions | 51.575 ms | 0.3298 ms | 0.3085 ms |
| MakeBreastCancerPredictions |  1.353 ms | 0.0059 ms | 0.0055 ms |

cc: @GalOshri @TomFinley @Zruty0 @justinormont

**Comment by Zruty0** [comment]
@najeeb-kazmi , is this `LearningPipeline` vs. `PredictionFunction`, or is it old `PredictionFunction` vs. new?

**Comment by najeeb-kazmi** [comment]
This is old `PredictionFunction` vs new.

**Comment by najeeb-kazmi** [comment]
@Zruty0 @GalOshri @shauheen @TomFinley @justinormont I've updated the numbers with prediction runtimes with the `LearningPipeline` API. The speedups are even more impressive when compared to how slow things were in 0.5.

**Comment by TomFinley** [comment]
Um wow.

Still, 1.353 ms per 10k on BC means, 135 nanoseconds per cycle, which will correspond on a typical machine to around a few hundred CPU cycles. A few hundred CPU cycles for 9 multiplies, followed by 9 multiply-adds, followed by the application of a logistic function, is at least somewhat understandable, but suggests to me that there may be some additional speedups here and there to be had.

But at least the situation is not *ridiculous*.

**Comment by danmosemsft** [comment]
@adamsitnik curious whether the traces you shared earlier are of the fast case above.

@TomFinley dowe have profile evidence that the time spent is dominated by "9 multiplies, followed by 9 multiply-adds, followed by the application of a logistic function"? If so that seems like something that may be amenable to eg @tannergooding 	looking at such factors as code gen and whether there is possibly another intrinsic we could use.
