### ISSUE TITLE
substitute AlignedArray with a regular array

### ISSUE THREAD

**Issue by Anipik** [dotnet/machinelearning#1018]
This issue tracks the progress with removing the aligned array.

The aligned array wont make much difference here as we do a lot of move operation.

More Discussion https://github.com/dotnet/machinelearning/pull/383

Rough Implementation :- https://github.com/Anipik/machinelearning/tree/temp

This branch removes all the aligned array code from src as well as implementation. All the tests are passing
Will update the issue with performance numbers soon

cc @danmosemsft @tannergooding @TomFinley @eerhardt

**Comment by wschin** [comment]
What kind of perf do you want to have? How large the data sets are being targeted? For large-scale ML, one representative example is training FFM (a user of AlignedArray) on Criteo. Could you give it a try with your changes? Thanks.

**Comment by artidoro** [comment]
@Anipik was this issue solved with #1274?

**Comment by Anipik** [comment]
no its yet to be completed
