### ISSUE TITLE
Microsoft.ML.TensorFlow is currently broken

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#1027]
### System information

- **OS version/distro**: all
- **.NET Version (eg., dotnet --info)**:  any

### Issue

- **What did you do?**
Create a .NET Core console project that references the latest version of `Microsoft.ML.TensorFlow`.
- **What happened?**
I don't get a reference to the `Microsoft.ML.TensorFlow.dll`. I only get a reference to `DnnAnalyzer.dll`
![image](https://user-images.githubusercontent.com/8291187/46039356-1f444380-c0d3-11e8-8e69-3e1ade0a9dc8.png)

- **What did you expect?**
I expected to get a reference to `Microsoft.ML.TensorFlow.dll` so I could call methods in it.

### Notes

The reason this happens is because we are including the `DnnAnalyzer.dll` in the `lib\netcoreapp2.0` directory of the `Microsoft.ML.TensorFlow` nuget package:

![image](https://user-images.githubusercontent.com/8291187/46039442-5dd9fe00-c0d3-11e8-965d-da3080f91a41.png)

NuGet only picks assets from 1 of these folders. And since my app is .NET Core, it only picks the assemblies from the `lib\netcoreapp2.0` directory.

/cc @ericstj @yaeldekel @abgoswam

**Comment by ericstj** [comment]
We shouldn't be putting DnnAnalyzer in the lib folder at the least.  Perhaps we should consider a better place for tooling to get this info.  Does ML.NET have any other command-line tools?  Have we considered a CLI extension?

**Comment by eerhardt** [comment]
We have the `Maml.exe` command line tool, which currently doesn't ship publicly. We've discussed making it a "global tool", but haven't executed on that plan.

**Comment by TomFinley** [comment]
The problem, as I understand it, is that we are instantiating the loader in this fashion.

```csharp
var data = env.CreateLoader("Text{col=ImagePath:TX:0 col=Name:TX:1}", new MultiFileSource(dataFile));
```

Using the command line to instantiate things programmatically is bad. Instead please just change this code to `new TextLoader(...)`.

Secondary point is, we do not want components being instantiated in this fashion. It should be written in the `IEstimator`/`ITransformer`/`IDataView` paradigm of #581 that we've been spending the last while attempting to do. If possible, if we could conform to the new idioms, that would be nice. But for now let's just unblock the test through direct instantiation.

**Comment by eerhardt** [comment]
@tomfinley - I think you may have been mistaken. This isn’t the test break that just occurred. This is a problem with the assets in our NuGet packages. Specifically in the TensorFlow package.

**Comment by TomFinley** [comment]
Whoops you're right sorry, got confused about the builds breaking.

**Comment by TomFinley** [comment]
Anyway, `DnnAnalyzer` should not be shipped in the nugets. It should have been rewritten as a command.
