### ISSUE TITLE
Need to be able to hash most column types

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#1031]
Previously, we relied on HashJoin transform to hash all kinds of column types, and this was our story for 'stratification column' functionality: any stratification column is first hashed, then it's a legal input to `RangeFilter`.

I feel that we shouldn't have *two* hashing operations, but instead we should have *one*, call it 'hashing', and make it capable of computing a hash of
- any primitive type
- any key type (that's currently the case)
- any vector of the above.

**Comment by Zruty0** [comment]
Of course an easy way to implement this is to port the existing HashJoin functionality into Hash. The existing HashJoin converts to string and then hashes the result.

**Comment by TomFinley** [comment]
Working via `HashJoin` is not a great idea. That implementation would be impossible to ever make efficient, and given backwards compatibility requirements, if we do it once we will have to support it forever. The implementation of `HashJoin` is not acceptable. Also the `Hashing` methods for processing `int` and `int`-like structures is right there already, we're just not calling it, so I'd argue there's not really much point.

The problem of sparsity preservation will be the same as it was for `float` and `double` in #684.

**Comment by markusweimer** [comment]
Is there a canonical implementation of [MurMurHash](https://en.wikipedia.org/wiki/MurmurHash) in .NET? I've used that in the past and found it fast enough.

**Comment by TomFinley** [comment]
Hi @markusweimer , we use murmur hash of course, so I'm guessing you're suggesting we use something in nuget to save the 200 lines or so in `Hashing.cs`? If we survey the libraries available for use in .NET by putting `murmur` into the search field of nuget, while my search was not exhaustive (I only looked at about 5 of the most popular ones) they don't really do what we need.

To be clear, the primary thing we use it for is for doing *many independent* hashes of *small* things rapidly. (Most commonly, short word-length strings, and fixed width individual numbers.) The libraries I saw had interfaces for hashing `byte[]`, and sometimes `Stream`, but not things like, say, `ulong` `uint`, and whatnot, and were optimized with the expectation that they'd be applied to large amounts of data to produce a single hash. So they don't do what we want. Maybe there's something in the long tail of unpopular ones I didn't see, but, probably not.

There's also the question of quality of those libraries, but given that they don't do what we want anyway this is a moot point I suppose.

**Comment by markusweimer** [comment]
@TomFinley Do you think it would be useful to release our implementation by itself, then?

**Comment by TomFinley** [comment]
Hi @markusweimer , potentially, but I don't know that this would be my first choice. We have lots of "little" things that are potentially useful little utilities, but I would certainly find it annoying if we were to hypothetically uplift them. Especially since this is being done to save, what, 200 lines of code.

**Comment by TomFinley** [comment]
Actually @Zruty0 this issue about vectors to scalars is surprisingly thorny -- I hope you don't mind but I think this actually deserves its own issue.

**Comment by Zruty0** [comment]
Do you mean its own PR?

**Comment by TomFinley** [comment]
I mean both its own PR and its own issue. The issues are hardly insoluable, but they merit their own discussion. There are several decisions to be made there.
