### ISSUE TITLE
Tensorflow documentation issues

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#1038]
https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.TensorFlow/doc.xml

A) Look in example: ```var pipeline = new LearningPipeline(seed: 1);``` LearningPiepline actually don't have seed parameter

B) ```OutputColumns = "Output"``` OutputColumns is actually array, so you can't pass just string to it.

C) ```This transform requires the <a href="https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.ML.TensorFlow/0.5.0-preview-26830-5">Microsoft.ML.TensorFlow</a> nuget to be installed.```
I'm not sure we should include links to preview nuget package

D)  ```The transform currently accepts the <a href="https://www.tensorflow.org/mobile/prepare_models">frozen TensorFlow model</a> file as input.```
I think we support frozen and non frozen models.

**Comment by abgoswam** [comment]
Issue #637 would enable the capability of automatically testing the code examples in our documentation
