### ISSUE TITLE
ConcatWith and AsVector need to be more restrictive regarding types they can be applicable.

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#1043]
```
var pipe = data.MakeNewEstimator().Append(row => (label: row.label.ToKey(), features: row.image.LoadAsImage()));
```
I'm loading images. As soon as I hit dot after LoadAsImage I get suggestions to Resize and  AsGreyscale 
which make sense. But I also got suggestion from intellisence to apply AsVector and ConcatWith. Which doesn't make much sense for me.

**Comment by TomFinley** [comment]
Hmmm. Perhaps `Scalar<>` and `Vector<>` and the like should be reserved for primitive types, and there should be another subclass out of `PipelineColumn` for non-vector structural types.
