### ISSUE TITLE
The Trainers list for any training context is empty

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#1054]
nuget: 0.6.0-preview-26926-9

Import the NuGet package. 
Instantiate any training context. 
Ctrl+Space after context.Trainers 

Bug: notice that the list of trainers is empty. 

  var ctx = new Microsoft.ML.RegressionContext(env).Trainers.  <= no trainers display.

**Comment by TomFinley** [comment]
Hmmm... Maybe the pigstentions for trainers should be on a single namespace, shared with that of the contexts? And this would be a namespace that would be shared no matter *what* assembly it had actually come from?

**Comment by sfilipi** [comment]
Yes, including manually the "Microsoft.ML.Trainers" namespace makes the trainers appear.

**Comment by Zruty0** [comment]
We agreed to move the contexts to `Microsoft.ML.Trainers`

**Comment by shauheen** [comment]
I think we should mention this as known issue for the release.

**Comment by shauheen** [comment]
Please refer to #1162

**Comment by sfilipi** [comment]
Closing since the extensions are all moved to the Microsoft.ML.StaticPipe namespace, that needs to get used to write statically typed pipelines.
