### ISSUE TITLE
TensorFlowTransform does not work on Scalar column...

### ISSUE THREAD

**Issue by zeahmed** [dotnet/machinelearning#1060]
The following line throws exception when using with scalar columns (non-pigsty case).

https://github.com/dotnet/machinelearning/blob/759ac33ef064c75cb977bfd6e6081186b295c6f5/src/Microsoft.ML.TensorFlow/TensorflowTransform.cs#L419

[I will add a concrete example here.]

**Comment by abgoswam** [comment]
DRI RESPONSE :  Could you kindly provide an example where we hit this ?

**Comment by codemzs** [comment]
closing this as tensflow transform is being changed to use TF.NEt as the backend.
