### ISSUE TITLE
SDCA (LinearClassificationTrainer) should be called SDCA in the codebase

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning#1069]
For historic reasons, `SDCA` is named [`LinearClassificationTrainer`](https://github.com/dotnet/machinelearning/blob/044a6d3cf35a8076ecbbcca5cdb61b2f722f94e1/src/Microsoft.ML.StandardLearners/Standard/LinearClassificationTrainer.cs#L1359) in the codebase.

SDCA (Stochastic Dual Coordinate Ascent), while quite good at many datasets, isn't the final answer for linear classification tasks as implied by the `LinearClassificationTrainer` moniker. For example, [`AveragedPerceptron`](https://github.com/dotnet/machinelearning/blob/b88d3460398c5b95745b476e40dd836f8f788cf6/src/Microsoft.ML.StandardLearners/Standard/Online/AveragedPerceptron.cs) tends to win on NLP tasks (ngrams and/or chargrams). 

Now is a great time to break with history and call SDCA, simply, `SDCA`.

**Comment by markusweimer** [comment]
We could also call it `StochasticDualCoordinateAscent` :)

**Comment by cTxplorer** [comment]
@justinormont 
As a beginner, what do I need to know and how can I contribution to this solve this issue?

**Comment by girishbaviskar** [comment]
@justinormont can I try this?

**Comment by justinormont** [comment]
@girishbaviskar: yes, certainly. There's a couple of comments on your pull request (#1213)

**Comment by artidoro** [comment]
We are still looking for some help on this :)
