### ISSUE TITLE
The new API does not work on .NET Framework < 4.7.1

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#1072]
It relies on the extension method in System.Linq "Append" that was added only in 4.7.1.

**Comment by eerhardt** [comment]
Unfortunately there are a few methods in .NET Standard 2.0 which aren't available in .NET Framework 4.6.1, but 4.6.1 "claims" it supports .NET Standard 2.0.

Here is the list:  https://github.com/dotnet/standard/blob/205332796a9a0f869ff698402c3496f14cc71f50/netstandard/src/ApiCompatBaseline.net461.txt

/cc @ericstj @terrajobst @weshaggard

**Comment by markusweimer** [comment]
Does this mean we'd have to raise the min version of .NET Framework required for ML.NET 0.6?

**Comment by eerhardt** [comment]
> Does this mean we'd have to raise the min version of .NET Framework required for ML.NET 0.6?

If we don't fix this issue for 0.6, Yes. If someone tries running the new API on an older .NET Framework, they will an exception.

**Comment by markusweimer** [comment]
@TomFinley how strong is our dependency on the method mentioned by Yael? Can we code around this? Maybe for 0.7?

**Comment by Zruty0** [comment]
umm, I think we could just add our implementation of `Append` to TLC until we upgrade the .NET version?

`Append(x)` is the same as `Concat(new[] {x})`

**Comment by markusweimer** [comment]
> umm, I think we could just add our implementation of Append to TLC until we upgrade the .NET version?

Sounds good. Can we make it conditional on the version of .NET a user has?

**Comment by Zruty0** [comment]
Also, I'm not too strongly attached to `Append`. I only used it because my C# was rusty, and I forgot that 'there is no Append in LINQ'. And sure enough, it appeared while I was not looking.

**Comment by markusweimer** [comment]
@Zruty0, is this fixable between now and 0.6?

**Comment by yaeldekel** [comment]
I can create a PR today.

**Comment by yaeldekel** [comment]
I looked at the list that @eerhardt posted, and Append looks like the only API that we use in there.

**Comment by markusweimer** [comment]
Cool! Unless you have a *bug* to fix for 0.6, it would be great to get this done before the release.
