### ISSUE TITLE
Command-line tool to script ML.NET training and inference

### ISSUE THREAD

**Issue by glebuk** [dotnet/machinelearning#108]
## Why Command Line?
While C# is a great language to build services and apps, it is not a scripting language.  As a result, it is difficult sometimes to quickly experiment, play and test different ML approaches.  
In many situations, it is highly useful to script, parametrize and automate ML program execution.  This also might help end users operationalize model creation, maintenance, and deployment.

## What should it do?
We need a command line tool that runs with ML.NET libraries and exposes a command line interface to the framework.  Such an EXE would:
* Run training, inference, and evaluation against data files
* Show list of available components and their arguments
* Allow ability to run specific scripts files to run specific pipelines that can be used in benchmarking
* Inspect models and binary data sources
* Import and export models from ONNX
* Autogenerate CS inference classes from trained models
* Sweep hyper parameters
* Moreover, we can define an interface for all of the actions so that it would be extended with developers to create additional commands

What do you think?

**Comment by voltcode** [comment]
Whatever the API surface of the tool is going to be, it would be beneficial if it could be consumed in other scripts and tools with a more convenient interface than std out and in piping. I'm thinking about potential powershell and c# script Integrations.

It all can be done under separate issues, much later, however it's good to think about it whendesigning the architecture for this functionality implementation.

**Comment by dotChris90** [comment]
Sorry for asking. Why so many developer forget powershell as .NET language? Its as u said. C# is great for apps server etc. But I feel Powershell isbetter for quick interaktive stuff and automation. I used Accord.NET with powershell and it felt great. I think powershell with ML.NET would be great too
