### ISSUE TITLE
BaseLine Mismatching for various tests when run against Release-Intrinsics

### ISSUE THREAD

**Issue by Anipik** [dotnet/machinelearning#1096]
The List of the tests that fail are

- [x] TestCrossValidationMacro
- [x] BinaryClassifierLogisticRegressionBinNormTest
- [x] BinaryClassifierLogisticRegressionGaussianNormTest
- [x] BinaryClassifierLogisticRegressionNonNegativeTest
- [x] BinaryClassifierLogisticRegressionNormTest
- [x] BinaryClassifierTesterThresholdingTest
- [x] BinaryClassifierSymSgdTest
- [x] BinaryClassifierLogisticRegressionTest
- [x] BinaryClassifierPerceptronTest
- [ ] MulticlassLRNonNegativeTest
- [ ] DefaultCalibratorPerceptronTest
- [ ] PAVCalibratorPerceptronTest
- [ ] FastTreeBinaryClassificationCategoricalSplitTest
- [x] LinearClassifierTest
- [x] NoCalibratorLinearSvmTest
- [x] PAVCalibratorLinearSvmTest
- [x] PcaAnomalyTest
- [x] RandomCalibratorPerceptronTest
- [x] RegressorOlsTestOne
- [x] LpGcNormAndWhiteningWorkout
- [x] MultiClassificationLRSaveModelToOnnxTest
- [x] BinaryClassificationLRSaveModelToOnnxTest
- [x] EntryPointLinearPredictorSummary
- [x] EntryPointPcaPredictorSummary
- [x] BinaryClassifierFieldAwareFactorizationMachineTest
- [x] PcaWorkout
- [x] RffWorkout
- [x] SavePipeSsaSpikeNoData // unhandled exception
- [x] ChangePointDetectionWithSeasonality
- [ ] EntryPointPipelineEnsemble
All of these tests fail because the baseline numbers are different on netcoreapp3.0

cc @danmosemsft @eerhardt @shauheen @Ivanidzo4ka

**Comment by Anipik** [comment]
Some of the tests that don't complete or  fail
- [ ]
- [ ]
- [ ]

**Comment by Anipik** [comment]
@shauheen can you assign some one to look into following failures 
 RffWorkout
 SavePipeSsaSpikeNoData // unhandled exception
 ChangePointDetectionWithSeasonality
 EntryPointPipelineEnsemble

These are not caused by mismatching in baseline files

**Comment by Anipik** [comment]
Tests Disabled For Netcoreapp3.0 

- [ ] TestCrossValidationMacro
- [ ] MulticlassLRTest
- [ ] MulticlassLRNonNegativeTest
- [ ] BinaryClassifierLogisticRegressionNonNegativeTest
- [ ] BinaryClassifierLogisticRegressionBinNormTest
- [ ] DefaultCalibratorPerceptronTest
- [ ] PAVCalibratorPerceptronTest
- [ ] RandomCalibratorPerceptronTest
- [ ] MatrixFactorization
- [ ] CommandTrainMlrWithStats
- [ ] KmeansTest
- [ ] GcnWorkout
- [ ] RffWorkout
- [ ] SavePipeSsaSpikeNoData
- [ ] ChangePointDetectionWithSeasonality
- [ ] TestSsaChangePointEstimator
- [ ] TestSsaSpikeEstimator

**Comment by glebuk** [comment]
@Anipik - please investigate and summarize root causes

**Comment by frank-dong-ms** [comment]
The difference comes from CPUMath using different instruction set:
  1. net framework and net core 2.1 uses CpuMathUtils.netstandard that uses SSE instruction set;
   2. net core 3.1 uses CpuMathUtils.netcoreapp that uses AVX, SSE or direct floating point calculation depending on hardward avaibility.
AVX and SSE generates slightly different result due to nature of floating point math.
Use below issue to track: https://github.com/dotnet/machinelearning/issues/5044

**Comment by frank-dong-ms** [comment]
created separate baseline for netcore app 31
