### ISSUE TITLE
Static pipe doesn't validate sufficiently

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#1097]
Here is an example:
https://github.com/dotnet/machinelearning/blob/master/test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamples.cs#L657

If I change the line to be `PredictedLabel: c.KeyU4.TextValues.Vector` , I will essentially (wrongly) claim that the model's `PredictedLabel` is a vector of keys. But `Fit` will work just fine, although even the basic `GetOutputSchema` call would verify that this is an invalid pipeline.

/cc @TomFinley

**Comment by codemzs** [comment]
closing this as static API is no longer being developed.
