### ISSUE TITLE
Getting SDCA multiclass weights requires using a MulticlassLogisticRegressionPredictor, which is strange

### ISSUE THREAD

**Issue by GalOshri** [dotnet/machinelearning#1100]
As shown [here](https://github.com/dotnet/machinelearning/blob/3cdd3c8b32705e91dcf46c429ee34196163af6da/test/Microsoft.ML.StaticPipelineTesting/Training.cs#L268), getting the predictor weights from multiclass-SDCA requires using `MulticlassLogisticRegressionPredictor`. This is counter-intuitive as I would expect that predictor to be used just for Logistic Regression. Perhaps something more general like `MulticlassLinearPredictor` should be created/used?

**Comment by wschin** [comment]
Looks like `MulticlassLogisticRegressionPredictor` should be split into two classes, `MulticlassLogisticRegressionPredictor` and `MulticlassLinearPredictor`. SDCA always producing MLRP is obvious wrong because multi-class support vector machine is not multi-class logistic regression. cc @TomFinley.
