### ISSUE TITLE
All Last names are Scottish ? :)

### ISSUE THREAD

**Issue by binaryfog** [dotnet/machinelearning#1101]
### System information

- **OS version/distro**: Win 10
- **.NET Version (eg., dotnet --info)**: .Net Core 2.1
- **ML.NET Version**: 0.5

### Issue

- **What did I do?**
Used SDCA to classify last names

- **What happened?**
No matter what last name I gave , it is predicted to be Scottish

- **What did you expect?**
Correct classification

### Source code / logs
Here is an excerpt from the output:

Last Name: Abbracciabene
Predicted probability: Arabic.txt:      0
Predicted probability: Chinese.txt:      0
Predicted probability: Czech.txt:      0
Predicted probability: Dutch.txt:      0.0025
Predicted probability: English.txt:      0.0001
Predicted probability: French.txt:      0.0036
Predicted probability: German.txt:      0.0015
Predicted probability: Greek.txt:      0.0012
Predicted probability: Irish.txt:      0.0113
Predicted probability: Italian.txt:      0.0013
Predicted probability: Japanese.txt:      0.0038
Predicted probability: Korean.txt:      0.0001
Predicted probability: Polish.txt:      0
Predicted probability: Portuguese.txt:      0.0002
Predicted probability: Russian.txt:      0
Predicted probability: Scottish.txt:      0.9737
Predicted probability: Spanish.txt:      0
Predicted probability: Vietnamese.txt:      0.0006
Predicted probability: :      0

See the attached source code for more details.
[LastNamePlay.zip](https://github.com/dotnet/machinelearning/files/2431123/LastNamePlay.zip)

**Comment by justinormont** [comment]
You'll want to use a Text Transform to create n-grams & char-grams:
https://github.com/dotnet/machinelearning/blob/d13b415fe58d773e4431984486b89d83d91c043c/test/Microsoft.ML.Tests/Scenarios/Api/AspirationalExamples.cs#L184-L197

For more in-depth options:
https://github.com/dotnet/machinelearning/blob/3cdd3c8b32705e91dcf46c429ee34196163af6da/test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamples.cs#L439-L455

I merged your dataset into one file, and shuffled the rows:
```
Arabic	Antar
Russian	Nosach
Russian	Yakutin
English	Bell
Italian	Di pasqua
Russian	Zheltoukhov
Russian	Rahmilovich
Czech	Chilar
Italian	Sgro
Russian	Davletshin
...
```

Using a similar pipeline to first example above, though w/ no n-grams, and using tri-char-grams, I get:
```fortran
Accuracy(micro-avg): 0.833191 (0.0062)
Accuracy(macro-avg): 0.467147 (0.0140)
Log-loss:           0.579616 (0.0147)
Log-loss reduction: 68.524054 (0.6206)
```
Word embeddings likely can add quite a bit of accuracy, though at the cost of speed. You'll also want to explore the various learners available besides `SDCA multi-class`, OVA-AveragedPerceptron generally is the winner on text datasets.

**Comment by binaryfog** [comment]
Thank you Justin for suggestions! Do you mind sharing the code, especially the one for which you get 0.83 accuracy ?

**Comment by justinormont** [comment]
I assume you want to train your model within C#, so I'd recommend modifying the above examples to suit your dataset.

As a quick test, I was using the command-line interface: 
```bash
git clone https://github.com/dotnet/machinelearning.git
cd machinelearning
./build.sh --cleanallprojects # Windows: buld.cmd --cleanallprojects 
./build.sh --release # Windows: buld.cmd --release 
dotnet ./bin/AnyCPU.Release/Microsoft.ML.Console/netcoreapp*/MML.dll cv k=5 loader=TextLoader{col=Label:TX:0 col=text:TX:1 header=-} data=/tmp/lastNames.shuf.tsv xf=Term{col=Label} xf=TextTransform{ col=Features:text wordExtractor=NgramExtractorTransform{ngram=2} charExtractor=NgramExtractorTransform{ngram=3 all=+} } tr=OVA{p=AveragedPerceptron{iter=10}} eval=MultiClassClassifierEvaluator{nccf=30}
```

Last name classification is a task where the transfer learning approach of word embeddings should be quite useful. I'd recommend trying out various word embeddings; a pipeline w/ dual use of word embeddings and the char-grams should show value.
