### ISSUE TITLE
The MlNetMklDeps nuget package should include exports used by the time series code

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#1103]
As part of the #977 work, the custom DLL for MKL that we package on the MlNetMklDeps nuget should include the following functions:

LAPACKE_shseqr
LAPACKE_dhseqr
LAPACKE_ssytrd
LAPACKE_dsytrd
LAPACKE_ssteqr
LAPACKE_dsteqr
LAPACKE_sorgtr
LAPACKE_dorgtr

**Comment by Ivanidzo4ka** [comment]
If I correctly remember _s and _d means work with single and double arrays, and we usually use one of them but not both, are you sure _d and _s needed?

**Comment by sfilipi** [comment]
assigning to @codemzs  to update the package version in the PR that needs it.

**Comment by codemzs** [comment]
Thanks @sfilipi for updating the mkl binary with the new exports for time series. I have updated the mkl version in my time series PR.
