### ISSUE TITLE
How to use EntryPoint saved .zip files with the "new API"?

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#1104]
### System information

- **OS version/distro**: all
- **.NET Version (eg., dotnet --info)**:  
```
> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-alpha1-009622
 Commit:    5a14412a49

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-alpha1-009622\

Host (useful for support):
  Version: 3.0.0-preview1-26924-01
  Commit:  4b8641b848
```

### Issue

- **What did you do?**
Attempt to load a .zip file that was created by EntryPoints using `TransformerChain.LoadFrom`.

- **What happened?**
```
An unhandled exception was thrown by the application.
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Function1 ---> System.FormatException: Corrupt model file
   at Microsoft.ML.Runtime.Model.ModelLoadContext.LoadModel[TRes,TSig](IHostEnvironment env, TRes& result, RepositoryReader rep, String dir, Object[] extra)
   at Microsoft.ML.Runtime.Data.TransformerChain.LoadFrom(IHostEnvironment env, Stream stream)
   at MLFunction.Predictor.PredictAsync(GitHubIssue issue, TraceWriter log) in F:\git\MLFunction\Predictor.cs:line 69
```

- **What did you expect?**
I expected to be able to use a .zip file that was created using the EntryPoints API with the "new API".

### Notes

If we are keeping the EntryPoints API, users will be creating model files using EntryPoints. We need to have an API that allows C#/.NET developers to use those model files.

**Comment by GalOshri** [comment]
Let's investigate to see if one of the new APIs solve this.

**Comment by Zruty0** [comment]
As far as I know, our model formats slightly diverge at this point. We plan to fix that soon.

**Comment by Zruty0** [comment]
@Ivanidzo4ka could you quickly look into that? If this is a 4-hour fix, we should make it before the upcoming release.

**Comment by Ivanidzo4ka** [comment]
Can we get clear what we want?
Entry points right now can still use functionality which didn't get converted to IEstimator/ITransformer. 
So it's impossible to always save entry points model as transformer chain (although it's possible sometimes)
`TransformerChain.LoadFrom` expects model to have only chain of ITransformers.

So I doubt I can modify TransformerChain to load old models.
I can try to modify current entry point pipeline and check can I compose TransformerChain out of it, but it wouldn't work in 100% cases.

**Comment by Zruty0** [comment]
I think we should have a polymorphic behavior in `MLContext.Model.Load`
