### ISSUE TITLE
Issue with WordEmbeddings using service accounts. 

### ISSUE THREAD

**Issue by abidur** [dotnet/machinelearning#1109]
### System information

- **Windows Server**:
- **.NET Version - Core 2.1**: 

### Issue
I built a demo web application that runs locally but breaks on the server. I am using WordEmbeddings. The error message is:

"Error downloading resource: Error trying to create directory : Path cannot be the empty string or all whitespace.
Parameter name: path.
Please fix your filesystem permissions, or try setting the 'MICROSOFTML_RESOURCE_PATH' environment variable to a writable folder"

I am using a service account on the IIS server and the GetFilePath method is is getting an empty string for "Environment.SpecialFolder.LocalApplicationData". I have the Environment Variable set to the appropriate folder. The issue is that the GetFilePath method is not checking for the Environment variable path at the right time and throwing the error reaching before that part of the code.
```csharp
            if (!Directory.Exists(appDataBaseDir))
            {
                try
                {
                   //**for service accounts, appDataBaseDir is empty and this through the error that is caught. Perhaps need to check for empty string here?** 
                    Directory.CreateDirectory(appDataBaseDir);

                    // On unix, create with 0700 perms as per XDG base dir spec
                    if (Environment.OSVersion.Platform == PlatformID.Unix)
                        chmod(appDataBaseDir, 448);
                }
                catch (Exception e)
                {
                    error = $"Error trying to create directory {appDataBaseDir}: {e.Message}.\nPlease fix your " +
                        "filesystem permissions, or try setting the " +
                        $"'{Utils.CustomSearchDirEnvVariable}' environment variable to a writable folder";
                    return filePath;
                }
            }

           
            if (!Directory.Exists(absDir))
            {
                try
                {
                    Directory.CreateDirectory(absDir);
                }
                catch (Exception e)
                {
                    error = $"Error trying to create directory {absDir}: {e.Message}.\nPlease try setting the " +
                        $"'{Utils.CustomSearchDirEnvVariable}' environment variable to a writable folder";
                }
            }
            return filePath;
        }
```

**Comment by ddobric** [comment]
Any update on this?
The same issue happen when running ML inside of a Linux container.

**Comment by halllo** [comment]
I am having the same problem. Any updates?

**Comment by halllo** [comment]
I found the this workaround for my linux docker container: 
Setting the environment varibale `XDG_DATA_HOME` to a an existing(!) folder will result in that folder being returned from `Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData)`.

**Comment by michaelgsharp** [comment]
Alright, This is now fixed. I ran into this issue while working on adding more support for arm/arm64 and testing on containers.

You will still have to set the `MICROSOFTML_RESOURCE_PATH` environment variable in this situation, but it now only tries to create the `appDataBaseDir` if the environment variable isn't specified.

I am going to close this issue, but if its not fixed for your specific case please let me know.
