### ISSUE TITLE
EntryPointGraph,GraphRunner and ComponentCatalog

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#1113]
as example:
https://github.com/dotnet/machinelearning/blob/59a90e7b2974ac857d3fd62c2f9a3dba9384eb85/src/Microsoft.ML.Legacy/Runtime/EntryPoints/JsonUtils/GraphRunner.cs#L26

Constructor accepts IHostEnvironment, and ComponentCatalog, but recently we made changes where ComponentCatalog become part of IHostEnvironment.

I think we should simplify our constructors and just accept IHostEnviroment.

**Comment by beneyal** [comment]
Mind if I take this one?

**Comment by Ivanidzo4ka** [comment]
Feel free to :)
