### ISSUE TITLE
Quickstart Tutorial is out of date (version 0.4.0)

### ISSUE THREAD

**Issue by montebhoover** [dotnet/machinelearning#1128]
The first tutorial mentioned on the docs site (https://docs.microsoft.com/en-us/dotnet/machine-learning/) uses ML.NET version 0.4.0, as does the example on main GitHub readme page.  These examples require the Microsoft.ML.Legacy namespace.

Snippet from example:
`var pipeline = new LearningPipeline();
pipeline.Add(new TextLoader(dataPath).CreateFrom<SentimentData>(separator: ','));
`

**Comment by JRAlexander** [comment]
All the docs tutorials have been updated to use the Microsoft.ML.Legacy namespace. We are working on updating them to the new API right now.
