### ISSUE TITLE
Build errors involving `Microsoft.ML.InternalCodeAnalyzer`

### ISSUE THREAD

**Issue by markusweimer** [dotnet/machinelearning#1129]
There seems to be an issue with how the build treats `Microsoft.ML.InternalCodeAnalyzer.dll`. After `build` from the command line, I did a rebuild in VS 2017. This results in many copies of this message in the error list:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	IDE1001	The analyzer assembly 'C:\src\machinelearning\bin\AnyCPU.Debug\Microsoft.ML.InternalCodeAnalyzer\netstandard1.3\Microsoft.ML.InternalCodeAnalyzer.dll' has changed. Diagnostics may be incorrect until Visual Studio is restarted.	Microsoft.ML.Core		1	Active
```

After restarting VS and doing a mere Build instead of Rebuild, I don't get this error. Rebuilding recreates the issue.

I also get some weird behavior when trying to build in Ryder, which might illuminate the issue in VS. As far as I know, Ryder uses `msbuild` directly to issue a build. When I select Build (or Rebuild) in its UI, I get this error, involving the same `Microsoft.ML.InternalCodeAnalyzer.dll`:

```
  Microsoft.Common.CurrentVersion.targets(4187, 5): [MSB3021] Unable to copy file "C:\src\machinelearning\bin/obj/AnyCPU.Debug\Microsoft.ML.InternalCodeAnalyzer\netstandard1.3\Microsoft.ML.InternalCodeAnalyzer.dll" to "C:\src\machinelearning\bin/AnyCPU.Debug\Microsoft.ML.InternalCodeAnalyzer\netstandard1.3\Microsoft.ML.InternalCodeAnalyzer.dll". The process cannot access the file 'C:\src\machinelearning\bin/AnyCPU.Debug\Microsoft.ML.InternalCodeAnalyzer\netstandard1.3\Microsoft.ML.InternalCodeAnalyzer.dll' because it is being used by another process.
```

I'd assume Ryder itself loads that DLL on solution load. Hence, this might be a bug in it as opposed to the ML.NET build.

That being said, the VS issue is a nuisance we should investigate.

**Comment by markusweimer** [comment]
@TomFinley, I believe you recently worked on the analyzers. Any idea what is happening here?

**Comment by markusweimer** [comment]
As a workaround, one can disable Roslyn Analyzers in Ryder while building. Not sure what the workaround for VS is.

**Comment by codemzs** [comment]
don't seem to be happening.
