### ISSUE TITLE
Investigate and fix test failures

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#1131]
Our commit success rate is below 50% at this point. 

We no longer have the annoying deadlock plaguing the builds, but somehow the builds are still failing quite often. Let's spend some time and improve that story.

From casual look, there is no single culprit: we seem to randomly fail to initialize build environment, and random tests seem to fail in random places. I guess this may have to do with resource-constrained runs: maybe we should actually try running xUnit tests sequentially and see if the sporadic failures go away?

**Comment by Ivanidzo4ka** [comment]
Should we at least create list of failing tests?
Let me start it:
MulticlassTreeFeaturizedLRTest
System.InvalidOperationException : MTA thread failed
---- Assert.InRange() Failure
Range: (74.9925 - 75.0075)
Actual: 72

**Comment by Zruty0** [comment]
@montebhoover , would you mind taking a look?

**Comment by frank-dong-ms** [comment]
These issues are fixed recently, some race condition issues.
