### ISSUE TITLE
Better error message for non-existing columns when executing graph

### ISSUE THREAD

**Issue by zyw400** [dotnet/machinelearning#1136]
### System information

- **OS version/distro**: Windows
- **.NET Version (eg., dotnet --info)**: Latest master branch 

### Issue

Executing a graph with wrong LabelColumn name, the error messages is not very clear:

Message: System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: Column

If the FeatureColumn name is wrong, the error message indicates Column not found, which is better.
[infert.txt](https://github.com/dotnet/machinelearning/files/2443223/infert.txt)
[graph_1.txt](https://github.com/dotnet/machinelearning/files/2443224/graph_1.txt)

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by Zruty0** [comment]
@zyw400 , thanks for your report. 

The `LearningPipeline` API is on deprecation path. 
In the new API, when you specify the label column which doesn't exist, the error message will look something like:
```
System.ArgumentOutOfRangeException : Could not find label column 'MisspelledLabel'.
Parameter name: Schema
```
Or, if the type of the label is not correct:
```
System.ArgumentOutOfRangeException : Schema mismatch for label column 'WrongTypeLabel': expected BL, R8, R4 or a Key, got U4.
Parameter name: Schema
```

I will close this issue. Feel free to reopen if you want to continue the conversation.

**Comment by Zruty0** [comment]
Actually, I realize now that this is not about `LearningPipeline`, but about the entry point graph runner. I believe eventually this fix will also propagate there, but I'm not 100% positive that it already has.
Could you please double-check with 0.6 ?

**Comment by zyw400** [comment]
I tried on the build based on the latest master branch.
