### ISSUE TITLE
Package the datasets needed for the samples in a nuget

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#1137]
The samples in docs.microsoft.com need to be fully self-contained like other MSDN code samples, so the users can copy-paste and run them. 

For this we could either package the datasets needed for the samples in a NuGet, or download them from this repo, via aka.ms links. 
I prefer the NuGet option, since the package creation and its updates are on the repository, and we can track history. We can't do the same for the links, afaik, and it is a separate system. 

This issue will be considered complete when we publish the NuGet containing one dataset that we can reference from the samples.

**Comment by shauheen** [comment]
@Zruty0 , @TomFinley

**Comment by sfilipi** [comment]
The decision is to not package and redistribute the datasets, but download them directly from github. 
Closing the issue.
