### ISSUE TITLE
Regression learning with constrains 

### ISSUE THREAD

**Issue by dotChris90** [dotnet/machinelearning#1146]
Hello Team, 

I just was thinking about the follow scenario and questions:

- you have a normal regression Problem with n features 
- you build a Model based on this known features 
- **how does ML.NET handle constrains like "feature 1 and 2 always must satisfy a equation"?**  
- **Is there an easy way to fit non-linear function based models without feature transform?** (something like f(x) = sin(p_1*x_1) * p_2 * exp(P_3 * x_2) * x_3, here are my data and what are the parameters?) 

I am from automotive engineering area and unfortunately we always facing this issues and unfortunately again most here are old school and MATLAB users. 

So most engineers expect something MATLAB like, e.g. Regression.Fit(sin(p_1*x_1) * p_2 * exp(P_3 * x_2) * x_3, x_vector, y_vector) . 

So this ML.NET have already something like this? I could image a model class could have something like constrains fields ... :D

**Comment by codemzs** [comment]
we have ~200 samples that demonstrate this stuff https://github.com/dotnet/machinelearning/tree/master/docs/samples/Microsoft.ML.Samples/Dynamic
