### ISSUE TITLE
Saving of Prediction Function

### ISSUE THREAD

**Issue by ArieJones** [dotnet/machinelearning#1148]
We are currently working with the 0.50 release and looking to move to the new API. One of the questions that has surfaced is in regards to the new PredictionFunction 

`// Use the model for one-time prediction.
// Make the prediction function object. Note that, on average, this call takes around 200x longer
// than one prediction, so you might want to cache and reuse the prediction function, instead of
// creating one per prediction.
var predictionFunc = model.MakePredictionFunction<IrisInput, IrisPrediction>(env);`

We are currently working with a set of models that we are saving/restoring from in order to get predictions. Sometimes these models are taking up a large amount of memory … on the order of ~8GB for some of the more complicated ones that are using various ngram lengths. 

So the question would be … Would there be any reason we could not save off the PredictionFunction in addition to the model in order to possibly shave off memory consumption or should we expect that the PredictionFunction created by a model with a given memory footprint will be relatively the same size? 

Thanks!

**Comment by Zruty0** [comment]
The `PredictionFunction` is a lightweight object that will hold a reference of model. There is no reason to save it, nor is it possible.

If you create multiple prediction functions, the memory consumption will remain the same as it is for one model (give or take the memory for the internal buffers, which I assume should be small).
