### ISSUE TITLE
Rename Microsoft.ML.StaticPipe.Vector<T> type

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#1153]
We currently have:

https://github.com/dotnet/machinelearning/blob/161b450a68a3f47eaf8abd4ce4778e417814b20f/src/Microsoft.ML.Data/StaticPipe/PipelineColumn.cs#L48-L52

Which is more of a schema type that says "the column I represent is a vector type". Which means this type isn't actually a "vector", but more of a "vector column".

We should rename this type (and the other XXColumn types), so we can "make room" for an actual `Vector<T>` type, which really does represent a "vector" object.

/cc @TomFinley

**Comment by Zruty0** [comment]
@TomFinley ping .

I think it's OK to have `VectorColumn<T>` (as well as `ScalarColumn<T>`, `VarVectorColumn<T>` etc.

**Comment by codemzs** [comment]
Closing this as no development is being done on static API
