### ISSUE TITLE
OVA and PKPD don't have pigsty extensions.

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#1159]
Not sure was it intentional, or we just forgot to add them

**Comment by Ivanidzo4ka** [comment]
@Zruty0 , @sfilipi  can you comment?

**Comment by sfilipi** [comment]
not intentional. The trainingContext object came in after the conversions were done, so we added as many extensions as we could fit.

**Comment by codemzs** [comment]
static API is not being developed anymore.
