### ISSUE TITLE
Solution file don't have references for all package projects

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#1168]
https://github.com/dotnet/machinelearning/tree/master/pkg
we have quite a lot of packages, but solution file has reference only for 3 of them
https://github.com/dotnet/machinelearning/blob/d5175899b604d852dab08107e583c78cbe5d6948/Microsoft.ML.sln#L52

Should we update solution and have policy to add new packages into it, or should we just remove them from solution?

Any thoughts?

**Comment by danmosemsft** [comment]
If you add them, you can drag them all into a single "solution folder" (a virtual folder defined in the sln file) the advantage being that when you open the solution you can quickly unload the folder if you don't care about them.
