### ISSUE TITLE
Add 3.0 to CI

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/machinelearning#1170]
We plan to ship codepaths that are specific to .NET Core 3.0, which will presumably be out in previews when we ship. We have some tests (albeit [incomplete](https://github.com/dotnet/machinelearning/issues/1156)) but they do not run unless the special build is performed locally.

It is too early to require contributors to have any build of 3.0 on their machines but it is not too early to add protection for the build and tests at the point of checkin. We should install some version of 3.0 on the CI machines, and add a leg to CI that builds and tests for 3.0. 

cc @eerhardt

**Comment by Anipik** [comment]
this was added a little while back
