### ISSUE TITLE
Unable to Install Microsoft.ML on target framework .NET Framework 4.6.1

### ISSUE THREAD

**Issue by Rammohan91** [dotnet/machinelearning#1181]
### System information

- **OS version/distro**: Windows 7
- **.NET Version (eg., dotnet --info)**:  4.6.1
- **Studio Version**: Visual Studio 2015

### Issue

- **What did you do?**
Attempt to install Microsoft.ML v0.6.0.

- **What happened?**
Error message was thrown as: Could not install package 'Microsoft.ML 0.6.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

- **What did you expect?**
Package should have been installed successfully.

Note: I have already installed Latest NuGet VSIX for VS 2015 & NET Standard Build Support.

###Error		Could not install package 'Microsoft.ML 0.6.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by Ivanidzo4ka** [comment]
https://github.com/dotnet/machinelearning/issues/366#issuecomment-398104951
would this comment solve your problem?

**Comment by Rammohan91** [comment]
@Ivanidzo4ka  Thanks for the reply. I did installed them but with no success.

**Comment by Ivanidzo4ka** [comment]
Well, all I can do, is to try to summon @eerhardt to this thread. Maybe he can help. If you don't mind to share information about your VS (Help-> About) and your project file, that would be helpful I guess.

**Comment by Rammohan91** [comment]
Here is the studio info,
![image](https://user-images.githubusercontent.com/21082865/46646511-2e81c180-cba8-11e8-8add-55805113d7b3.png)

Also, I don't have any specific configuration in my project. I just created a new console application project and was trying to install the ML.Net to play with it. I did try changing the framework to 4.5.1, 4.5.2,4.6 and 4.6.1 and also setting the Platform to x64 but was getting this error for all the changes.

Thanks,
Rammohan B.

**Comment by eerhardt** [comment]
Hey @Rammohan91, I just tried installing `v0.6` on my VS 2015 machine.

Before installing the two links in https://github.com/dotnet/machinelearning/issues/366#issuecomment-398104951, I got the exact same error as you. After I installed those 2 links, I was able to successfully install the NuGet package.
Maybe you need to restart VS or your computer in between?

Please ensure your Help -> About contains:

![image](https://user-images.githubusercontent.com/8291187/46682608-a1446a00-cbb3-11e8-87e6-f0ed8a938aa5.png)

**Comment by Rammohan91** [comment]
Thank you so much @eerhardt Appreciated. :)

Not sure why but i had an older version of the Nuget Package Manager even though i remember installing it. I just installed it again, restarted and it worked. Thanks again.
