### ISSUE TITLE
What should be our strategy to handle failure in transformer

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#1190]
So pretty much every transformer has a GetGetter delegate which looks on source column, get value from that column and handles it.
```cs
 var getSrc = input.GetGetter<TSrc>(colIndex);
ValueGetter<TDst> retVal =
     (ref TDst dst) =>
     {
      getSrc(ref src);
      DoMagic(ref src, ref dst);
    };
```
In ideal world, that DoMagic procedure would always give us proper results, but unfortunately in real world some cases can't be handled and if we rely on code written by 3rd party we can't even fix it.

My question is following, what should be our strategy for that cases?
I see few options:

1.   Just throw exception if you can't handle it. This is quite straightforward, but in same time I think it not user friendly, especially during scoring for huge file.

2. Force each transform to handle src ==null case and just set dst to null as well (i'm talking mostly about src is VBuffer<T> class) and in learner/ scorer ignore such rows. I would also add threshold to learner/ scorer to throw in case if percentage/absolute values of such rows exceed it. For me this feels like more user friendly approach. 

Any one willing to discuss? @Zruty0 @TomFinley @markusweimer @shauheen @eerhardt @CESARDELATORRE  @GalOshri @justinormont

**Comment by Ivanidzo4ka** [comment]
@Zruty0 @TomFinley @markusweimer @shauheen @eerhardt @CESARDELATORRE  @GalOshri

**Comment by Zruty0** [comment]
`VBuffer` is a struct, so there's no `null` in that. 
I think throwing an exceptions is the most consistent and explainable way.

Note that most operations are defined for any valid input. It's the more peculiar ones, like image transformation etc., that we have to worry about.

Enforcing ANY kind of consistent behavior (if it's not throwing) is very hard once you open up to running other components. For instance, what do we do if LightGBM throws, or ONNX, or TensorFlow? Can we even recover safely?

**Comment by markusweimer** [comment]
> I think throwing an exceptions is the most consistent and explainable way.

Would it be useful to define Exception classes to be used for various errors? I imagine that to be useful in a UI, but know nothing about UIs :)
