### ISSUE TITLE
Fix duplicate params in entrypoints

### ISSUE THREAD

**Issue by ganik** [dotnet/machinelearning#1197]
Following entrypoints have duplicate param names:
Data.DataViewReference 
Models.CrossValidator
Models.CrossValidationResultsCombiner
Models.PipelineSweeper
Models.PipelineSweeper
Models.SweepResultExtractor
Models.TrainTestEvaluator
Transforms.TwoHeterogeneousModelCombiner
Transforms.ManyHeterogeneousModelCombiner

This is not a bug per se. This is about how to make entrypoint API easy to use by 3rd parties/clients. Since I have been implementing such a client, I can share my experience. We have viewed "entrypoint" as a function, sort of RPC that you can call. All the parameters for "entrypoint" are parameters of such a function. 
On example of TensorFlowScorer (fixed by #1169 ) : even though Model is set as "Output" param, its actually required to set this param to a filepath so ML.NET can output zipped model there. Therefore entrypoint needs 2 model params: one to specify filepath for input model, another one to specify path for output model. I am not sure if I know any programming language where function can accept parameters with the same name.
Of course its possible to view "entrypoint" not as a method but some sort of class, or break up params into separate Input and Output structs and populate separately, but in the end, on a highest level, what is going to surface to user is a function with params to specify input and output model paths. It would be easier to avoid intermediates and being able to have that high level function built right on top of manifest.json specs.

**Comment by Ivanidzo4ka** [comment]
I believe you fix this issue in PR #1169 so I'm closing this issue.
