### ISSUE TITLE
Is Estimator a good enough name?

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#1201]
As @CESARDELATORRE pointed out, the term `Estimator` means two different things in Spark and in sklearn. 

Our terminology is in line with Spark one: the `Estimator` is a 'factory for a `Transformer`', or 'a components that trains a `Transformer` based on the data.

However, it would be even better if we avoided the naming clash with sklearn. So far, the other alternative names for `Estimator` have been taken from generic .NET architecture: `TransformerBuilder`, `TransformerFactory` etc.

I am personally not a big fan of either of the above, but they do have the benefit of mapping the behavior to other known .NET concepts. 

In any case, let's see if there are better suggestions, or if there is strong preference to the existing names.

**Comment by CESARDELATORRE** [comment]
I guess we can also go to the root and see the [definition of an ESTIMATOR in in statistics](https://en.wikipedia.org/wiki/Estimator):
_An "estimator" or "point estimate" is a statistic (that is, **a function of the data**) that is **used to infer** the value of an unknown parameter in a statistical model._
 
But to me, that definition sounds much closer to a **model** than to a `TransformerFactory `which is in reality our Estimator.

In **Python with Scikit-Learn**, an `Estimator `might look similar when training or calling Fit():

`estimator.fit(data)`

That looks pretty similar to the way we do it in ML.NET. However, the big difference here is that in Scikit-Learn the Estimator has a 1:1 relationship with the algorithm to use. It is in fact "the algorithm" you use surfaced with an Estimator API.
See: http://scikit-learn.org/stable/tutorial/machine_learning_map/index.html for a map of algorithms/estimators in Scikit-Learn.

But in ML.NET our current Estimator is a broader concept, it can be used simply to create a Transformer that might not even have any ML algorithm and it's being used only to transform data. Of course, in the case that the ML.NET estimator *also* has and algorithm, then when calling to Fit() it returns a transformer which is also the model... That looks more similar, but it is still not the same concept.
 
Therefore, from a .NET developer point of view (most of them don't know much about [APACHE SPARK](https://spark.apache.org/)) I'd say that something like `TransformerFactory `or `TransformerBuilder `would be clearer for me.
And if you are coming from Scikit-Learn, it might be confusing to see an artifact called Estimator that is a different concept than an Estimator in Scikit-Learn...

Therefore, from a .NET developer point of view I'd say that something like `TransformerFactory `or `TransformerBuilder `would be clearer for me.

Additional thoughts?

**Comment by eerhardt** [comment]
Adding to `Project 13` to decide if we should make a change here or close this issue. We will not be able to change this after `v1.0`.

**Comment by eerhardt** [comment]
@TomFinley - I think this can be closed. We are past the tipping point of changing this name.

Thoughts?

**Comment by CESARDELATORRE** [comment]
Yeah, I questioned this point in early October. Now (March) it is very late to even think about it. ;)
I agree, let's close it. 👍
