### ISSUE TITLE
Classification stratificationColumn not supported for boolean column

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning#1204]
For not balanced datasets, with stratified splitting, the data is divided in such a way that a percentage of each target column value is put in both training and test dataset.

However, the following line of code throws an error if the column 'Label' is Boolean, which is very common for binary classification.

`(trainData, testData) = classification.TrainTestSplit(data, testFraction: 0.2, stratificationColumn: "Label");`

It would work if the Label column would be float or other types.

I might be missing something, but why is Boolean not supported for the `stratificationColumn`?
Can we support it since it can be a common scenario for binary classifications?

**Comment by Zruty0** [comment]
Stratification column is not what you think. Actually, if you read the documentation, it [states](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Data/Training/TrainingStaticExtensions.cs#L31) that 

>If two examples share the same value of the `stratificationColumn` (if provided), they are guaranteed to appear in the same subset (train or test). Use this to make sure there is no label leakage from train to the test set

As you can see, it is ALWAYS a bad idea to use `Label` as a stratification column, and ALWAYS a bad idea to use a Boolean column as a stratification column.

That said, currently we only support float, key and string values for stratification (and I'm not sure about key). We should expand the coverage of Hash estimator (see #1031)

**Comment by CESARDELATORRE** [comment]
Just highlighting that this issue still applies. 
The stratification column parameter was renamed to 'samplingKeyColumn' because stratification column means a very different thing:
**Stratification Column**: A Stratification column is important if the rows in the dataset should be divided evenly by some key column when sampling or producing split datasets, so it is a very different concept.

On the other hand, 'samplingKeyColumn' is used for grouping rows. If two examples share the same value of the samplingKeyColumn, they are guaranteed to appear in the same subset (train or test). This can be used to ensure no label leakage from the train to the test set. If null no row grouping will be performed.

So, the usage is very different. But that is not the issue/limitation.

The BUG/ISSUE is that looks like if I have a dataset where the Label is Boolean and there are few "True" rows, I'm finding that the test/train split is not stratifying as I'm getting a test dataset with all labels=false. That means it is not divided evenly by the label key column when sampling or producing split datasets.

Additionally, looks like we have no parameter to specify the "stratification column"?

**Comment by codemzs** [comment]
I agree with Pete. Closing this.
