### ISSUE TITLE
Logistic Regression doesn't work with training stats

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#1205]
Stats that are being computed at training time aren't passed to the predictor.

**Comment by Zruty0** [comment]
#1006 is related?

**Comment by montebhoover** [comment]
Yes, this looks the same as #1006.

**Comment by montebhoover** [comment]
@yael, from the comment on #1006 below, it sounds like we are both not passing training-time stats to the predictor, and there are more stats for us to calculate. Does that ring true?

"If I do [pass _stats to the predictor], then predictor.Statistics.GetCoefficientStatistics still returns null. It appears that you calculate the inverted Hessian, but then do not use it to calculate standard errors (and pass these in the constructor of `LinearModelStatistics')"

**Comment by Ivanidzo4ka** [comment]
what about https://github.com/dotnet/machinelearning/issues/612 ?
I would assume you fix it because you working on one not-allowed-to-mention repository, and even if you bring stats, you wouldn't bring whole old version since this one doesn't have standard errors.
