### ISSUE TITLE
FastTreeBinaryClassificationCategoricalSplitTest taking very long to execute...

### ISSUE THREAD

**Issue by zeahmed** [dotnet/machinelearning#1207]
The following test is taking 15-25mins (depending on system) alone to execute.

https://github.com/dotnet/machinelearning/blob/8ca1c9386587aa4ef77c56f605f8244debefce93/test/Microsoft.ML.Predictor.Tests/TestPredictors.cs#L711

Is there any policy for test execution time in ML.Net build system?

**Comment by zeahmed** [comment]
Thanks @eerhardt! I was expecting someone already filed it but I was not able to search it.

I am fine closing it however #924 seems bit broad. As @artidoro is already investigating it, may be this can be assign to him. What do you think?

**Comment by artidoro** [comment]
@Ivanidzo4ka  has solved the issue with the PR #1388. Now this test takes less than 30 seconds.
