### ISSUE TITLE
Is there a way to train my model with multiple coaches?

### ISSUE THREAD

**Issue by pictos** [dotnet/machinelearning#1214]
### System information
Is there a way to train my model with multiple coaches?

So, for example, i want to create a model to calculate a salary based in years of experience. To do this i used Regression, but has more than one trainers. I want to test all of this trainers and compare the results. 
I researched a lot, but i don't finded one way to do this with the ML.NET.

- **What did you do?**
For did that  I execute one time, change the trainers and execute again... It's not very good.

- **What did you expect?**

Create a way to initialize a array of ILearningPipelineItem and train my model with each one and show the results

### Source code / logs
I do some experiments using the version 0.3, and I think this could be something native to this api, if it does not already exist.
https://github.com/pictos/MLParalel

**Comment by codemzs** [comment]
please specify more details, what is coaches? closing this but feel free to reopen after reviewing our samples here https://github.com/dotnet/machinelearning/tree/master/docs/samples/Microsoft.ML.Samples/Dynamic
