### ISSUE TITLE
Investigate and deal with the remaining x86 baseline differences

### ISSUE THREAD

**Issue by tannergooding** [dotnet/machinelearning#1215]
The x86 build of ML.NET has some remaining baseline differences that need investigation and fixing.

From initial investigation, the remaining differences have fewer than 4 matching significant digits and this may be caused by known bugs in the double parsing code (which have already been fixed or are actively being fixed in .NET Core). Other differences are due to the implementation (between x86 and x64) of some floating-point Math functions that the tests depend on.

**Comment by tannergooding** [comment]
The tests disabled for x86 can be identified by: `[ConditionalFact(typeof(Environment), nameof(Environment.Is64BitProcess))]`. Many of them have an additional comment on the same line of `// x86 output differs from Baseline`

**Comment by frank-dong-ms** [comment]
Created separate baseline for x86 tests: https://github.com/dotnet/machinelearning/pull/5057

Some of the difference from x64 and x86 is due to MKL is generating different results.
