### ISSUE TITLE
Investigate why two predictor tests fail with "Unknown command: 'train'" on x86

### ISSUE THREAD

**Issue by tannergooding** [dotnet/machinelearning#1216]
There are currently two `TestPredictors` tests disabled on x86 due to: `[ConditionalFact(typeof(Environment), nameof(Environment.Is64BitProcess))] // x86 fails with "Unknown command: 'train'; Format error at (83,3)-(83,4011): Illegal quoting"`.

This issue needs further investigation.

**Comment by artidoro** [comment]
@tannergooding are you looking into this?

**Comment by frank-dong-ms** [comment]
Following test are marking with this issue but they appear to have different reason of fail:
1. TestMulticlassEnsembleCombiner: this is lightgbm test and should be marked as LightGBMFact and only runs on x64
2. TestTreeEnsembleCombiner: Heap corruption
3. TestTreeEnsembleCombinerWithCategoricalSplits: Heap corruption
4. TestEnsembleCombiner: Heap corruption
