### ISSUE TITLE
Clean up `[ConditionalFact(typeof(Environment), nameof(Environment.Is64BitProcess))]`

### ISSUE THREAD

**Issue by tannergooding** [dotnet/machinelearning#1220]
It was suggested that creating explicit attributes for the various cases (Such as Onnx, TensorFlow, LightGBM, etc) may be a better long term solution to manage these tests across the various platforms.

See https://github.com/dotnet/machinelearning/pull/1008#discussion_r221985876 for more details.

**Comment by mareklinka** [comment]
Hi there. I started looking into this and came up with the following list of attributes that would be necessary:

1. TensorFlow
2. Onnx
3. LightGBM
4. .NET Core < 3.0 || not Core
5. MatrixFactorization
6. Environment = x64 (e.g. where x86 output differs from expected baseline, [TestCommandBase:841](https://github.com/dotnet/machinelearning/blob/7fc7e50ce6f8fed24fc0b9528839a0ac8d0ed320/test/Microsoft.ML.TestFramework/TestCommandBase.cs#L841))
7. x64 && (.NET Core < 3.0 || not Core)

There is also two usages of a conditional on `BaseTestBaseline.NotFullFramework`. However, this seems to always be `true`. Does this do something I'm missing or can this be removed?
