### ISSUE TITLE
Debugger views of estimators

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#1222]
We are already committed to improving how our data looks like in the debugger.

For instance, #1167 will turn the schema into an 'eagerly computed' object, so you can look at it in the debugger:
![schema](https://user-images.githubusercontent.com/41337831/46771152-2c525c80-cca7-11e8-949e-b728eda5b5b3.PNG)

Now a different question is: how do we make `Estimators` somehow 'debugger-inspectable'?

We cannot really inspect 'the algorithm'. But we can inspect 'how the algorithm will transform data'. In the world of `LearningPipeline`, every pipeline was 'duct-taped' to a specific data file. That was a mistake, of course, but it did allow for nice debugger views of pipeline steps.

With the new API, the pipeline is no longer bound to any data. It can be 'fitted' on any data of 'reasonable' shape. But now the debugger view is useless.

One possible suggestion is to add an extension method to our estimators, called something along the lines of `Preview`. It would have a signature `IDataView Preview(IDataView data)` in case of a transformer or an estimator, or `IDataView Preview(T source)` in case of an `IDataReader<T>`.

This method would return some form 'lazy approximation of `Fit`':
```csharp
IDataView Preview(IDataView data) => Fit(data.Take(100)).Transform(data.Take(100))
```

Then, at least, we can have the watch window experience more or less palatable: you just add `pipeline.Preview(trainData)` and you can see an approximation of how the pipeline would transform `trainData`.

cc: @GalOshri @CESARDELATORRE @TomFinley @eerhardt

**Comment by Zruty0** [comment]
#985 is the issue that talks about `IDataView` inspectability

**Comment by codemzs** [comment]
I believe we already have this.
