### ISSUE TITLE
Error MSB4019 when adding package Microsoft.ML

### ISSUE THREAD

**Issue by mjannet** [dotnet/machinelearning#1223]
### System information

- **Windows 10**:
- **MS Visual Studio Community 2017 Preview**: 

### error MSB4019: The imported project "C:\Users\Owner\source\repos\machinelearning\tools\clean.target" was not found.

- **Clone package from github: https://github.com/dotnet/machinelearning.git using Visual Studio Preview
- **From CLI executed: dotnet add package Microsoft.ML**
- **Got the error message referenced above**
- **This is one of my first projects I am trying to download from github, and I am not sure where to find information to be able to download this project correctly.  I appreciate any assistance I could get.  Thank you**

**Comment by Ivanidzo4ka** [comment]
we have [developer guide](https://github.com/dotnet/machinelearning/blob/master/docs/project-docs/developer-guide.md) which explains how to build project locally.
