### ISSUE TITLE
ONNX Transform Crashing or Freezing

### ISSUE THREAD

**Issue by vaeksare** [dotnet/machinelearning#1228]
ONNX Transform occasionally crashes or freezes when running certain onnx models (currently found with the Split operator). 

- The error is non deterministic and varies based on different machines
- On some machines, the ML.NET process will freeze, while on others it will simply silently crash without producing any output
- The larger the input, the more likely the issue seems to occur - almost never happens with <100 inputs, sometimes happens with 100-300 inputs, and almost always happens with >300 inputs
- When ML.NET is built in debug mode, the error will never occur. It only happens if it is built in release mode
- The issue is not tied to any specific input. Smaller inputs will never produce an error, while larger ones almost always will (in release mode)

**Comment by Zruty0** [comment]
Could you give an update please? Is it actively worked on?

**Comment by vaeksare** [comment]
@Zruty0 Jignesh is currently investigating this issue.

**Comment by shauheen** [comment]
This issue is not fixed only avoided by #1310
