### ISSUE TITLE
Sweep command doesn't work

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#1237]
The method "GetFullExePath" on line 91 in ConfigRunner.cs sets the default executable to be "maml.exe", which doesn't exist.

**Comment by justinormont** [comment]
Some background...

As seen in the ConfigRunner, the Sweeper is expecting the command-line executable to be named `maml.exe` (on Windows) or `maml` (on OSX/Linux):
https://github.com/dotnet/machinelearning/blob/978681d5d82929318d8248c09cb1fe557b3a6743/src/Microsoft.ML.Sweeper/ConfigRunner.cs#L91-L103

I see two solutions:
* Upgrade the command-line tool to a first-class citizen and have it produce the expected binary (see #1203)
* Modify the code to also look for MML.dll and run as `dotnet ./bin/AnyCPU.Release/Microsoft.ML.Console/netcoreapp2.1/MML.dll sweep ...`

**Comment by Zruty0** [comment]
@yaeldekel , what is the suggested fix?

**Comment by justinormont** [comment]
I would suggest fixing this issue by having issue #1203 (ML.NET command line tool) create the `maml.exe` and `./maml` binaries.

**Comment by shmoradims** [comment]
@yaeldekel @Zruty0 @justinormont, could you please finalize the suggested fix?

**Comment by codemzs** [comment]
sweep command does not exist in ML.NET as of today.
