### ISSUE TITLE
Native build failed with CLI

### ISSUE THREAD

**Issue by malek8** [dotnet/machinelearning#124]
Trying to build on Windows using CLI first, ran build.cmd in root folder
build started and was looking fine, until it started building native components.

### Error Message

machinelearning-master\src\Native\build.proj(47,5): error MSB3073
machinelearning-master\src\Native\build.cmd Debug x64" exited with code 255.

Build FAILED.

Time Elapsed 00:00:02.03
Command execution failed with exit code 1.

any ideas?

**Comment by veikkoeeva** [comment]
@malek8 Do you have the native toolchain installed? Either via VS 2017 or perhaps http://landinghub.visualstudio.com/visual-cpp-build-tools ? Other one I can imagine of is [Cmake](https://cmake.org/) (the tools do not use the private one VS C++ tools installs).

**Comment by veikkoeeva** [comment]
@malek8 Indeed, those error message do not tell much. Can you increase build logging to maximum? The setting is something like
> Tools -> Options -> Build and Run Change -> MsBuild project build output verbosity  | "Diagnostic". 

A hunch is that something isn't found on the path, but I haven't taken a look at the build files. Maybe adding quotes around path name or some other measure would help. Additional option could be to switch to the new [binary logging](https://github.com/Microsoft/msbuild/wiki/Binary-Log) (probably should be done in any case).

As an aside, the MSBuild could check if the toolchain has run so opening VS would be enough, maybe something to do a PR later. :)

**Comment by malek8** [comment]
Mystery solved!
I had a wrong entry in environment path prior to CMake entry, and it wasn't leading to a valid directory. @veikkoeeva thanks for the insight
