### ISSUE TITLE
Add property to Environment class which would indicate can we use disk operations or not

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#1244]
In some environments we can be limited by access to disk, so we need to perform all operations in memory. We already has code which specify should we use file system or not for loading/unloading model
https://github.com/dotnet/machinelearning/blob/f8f3873958a0a8114df49bb6d8dc292dc071820b/src/Microsoft.ML.Data/Model/Repository.cs#L438

or HybridMemoryStream should respect that parameter as well.

Any temporary file creations need to respect this property and create memory streams instead.

**Comment by artidoro** [comment]
Hey Ivan could you add some more details to the above? What are some places where this is not done in code?

**Comment by codemzs** [comment]
closing due to lack of details. feel free to reopen once details have been added.
