### ISSUE TITLE
Dead Add Flag in Matrix Multiplication

### ISSUE THREAD

**Issue by Anipik** [dotnet/machinelearning#1245]
we are not using the ```Add``` Flag in Matrix multiplication.

Should we go ahead and remove it ?

```public static void MatTimesSrc(bool tran, bool add, AlignedArray mat, AlignedArray src, AlignedArray dst, int crun)```

cc @danmosemsft @eerhardt @tannergooding @TomFinley

**Comment by eerhardt** [comment]
Yes - if there is dead code, feel free to delete it.
