### ISSUE TITLE
Remove unnecessary JIT SBCG workaround

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/machinelearning#1247]
```c#
        public static uint GetLo(ulong uu)
        {
            // REVIEW: Work around Dev10 Bug 884217: JIT64  -Silent bad codegen for accessing 4-byte parts of 8-byte locals
            // http://vstfdevdiv:8080/WorkItemTracking/WorkItem.aspx?artifactMoniker=884217
            // return (uint)uu;
            return (uint)(uu & 0xFFFFFFFF);
        }
```

I dug up this bug, it was fixed in a dev branch in 4/2010 and it looks like it reached 4.0 - certainly would be fixed in 4.5.0 which shipped in 8/2012. Although we don't explicitly state what .NET Framework versions we support, is probably reasonable for us to expect 4.5 or later and safe for us to remove this workaround.

**Comment by artidoro** [comment]
@danmosemsft would you suggest that we state in our documentation that we support .NET Framework 4.5.0 and higher?

**Comment by danmosemsft** [comment]
Actually we implicitly support only 4.6.1 and higher because we compile against the .NET Standard 2.0 surface area and that was first supported in 4.6.1. That escaped my mind when I wrote the above comment. So you can confidently remove this, I think.
