### ISSUE TITLE
Which format does exported model use?

### ISSUE THREAD

**Issue by ChangweiZhang** [dotnet/machinelearning#125]
can I get a onnx model by using ML.NET?

**Comment by GalOshri** [comment]
Not yet, but exporting ML.NET models to ONNX is on the [roadmap](https://github.com/dotnet/machinelearning/blob/e9cd4bc3310ca4e09ce99f02f67d9549790644fc/ROADMAP.md). Is there a particular model/pipeline that you need to export to ONNX?

**Comment by ChangweiZhang** [comment]
According to the API reference, the class PredictionModel have a WriteAsync method and I can write model to file in binary format. What is the format?

**Comment by justinormont** [comment]
The format is a binary descriptor of the transforms and learner for the trained pipeline; create one and unzip it. As @GalOshri  says, the ONNX output format is on the [roadmap](https://github.com/dotnet/machinelearning/blob/master/ROADMAP.md). We're always interested in what folks are looking for; any particular interest in ONNX? Or mainly just want to explore the output formats?

**Comment by GalOshri** [comment]
Adding to what @justinormont mentioned: the WriteAsync method saves the model as a zip file. You can then use ReadAsync to use the model in a different project.

**Comment by turowicz** [comment]
Interoperability with models trained in on different stack?

**Comment by enghch** [comment]
I'd like onnx to make it easy to consume my model with Windows ML to get the automatic hardware acceleration detection.
