### ISSUE TITLE
Improve testing on ONNX exporting

### ISSUE THREAD

**Issue by vaeksare** [dotnet/machinelearning#1250]
Currently, tests for saving models as ONNX just check to make sure the ONNX models themselves are as expected by comparing them to a pre-saved version of that ONNX model. These tests do not actually check that these models are runnable or that they produce the same results as the original transform. With the new ONNXTransform, this testing framework could be improved to ensure correct exportability.

**Comment by wschin** [comment]
Why did you close it?
