### ISSUE TITLE
Make Binary classification evaluator configurable

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#1251]
The following method:
```csharp
        public BinaryClassifierEvaluator.CalibratedResult Evaluate(IDataView data, string label = DefaultColumnNames.Label, string score = DefaultColumnNames.Score,
            string probability = DefaultColumnNames.Probability, string predictedLabel = DefaultColumnNames.PredictedLabel)
```
needs to expose additional parameters from `BinaryClassifierEvaluator.Arguments`, or a delegate to set them.

**Comment by SebHel** [comment]
I would like to have a go at this. So the relevant `Evaluate ` method should have a `BinaryClassifierEvaluator.Arguments` as an additional parameter and we use it to set the private fields 

`private readonly Single _threshold;
        private readonly bool _useRaw;
        private readonly int _prCount;
        private readonly int _aucCount;
        private readonly int _auPrcCount;` ?

In this case we might want to get rid of the `Arguments args` parameter in the constructor of `BinaryClassifierEvaluator`?

**Comment by artidoro** [comment]
We have internalized that method so I think we can close this issue.
