### ISSUE TITLE
Documentation snippets for regressor trainers

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#1256]
Similar to the sample code for [SDCA regression](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Trainers.cs#L19), we need samples for the other regressors:
[FastTreeRegression](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.FastTree/FastTreeStatic.cs#L39)
[LightGBM](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.LightGBM/LightGbmStatic.cs#L38)

So there are two things to do, to resolve this issue:
1. Add a sample for LightGBM and FastTree in [Microsoft.ML.Samples/Trainers.cs](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Trainers.cs#L1)
The samples can look exactly as the [SDCA one](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Trainers.cs#L19), but substituting [the trainer](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Trainers.cs#L48) with FastTree or LightGBM. 
2. Add a documentaiton link to 

2. Add a link to the xml documentaiton of [FastTreeRegression](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.FastTree/FastTreeStatic.cs#L39)
[LightGBM](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.LightGBM/LightGbmStatic.cs#L38) to reference the new sample methods, like the one [SDCA](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs#L38) has.

**Comment by timitoc** [comment]
Working on this.

**Comment by justinormont** [comment]
Removing `up-for-grabs` and `help wanted` tags as the issue is claimed by @timitoc.
