### ISSUE TITLE
Documentation samples for binary classifiers

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#1257]
Similar to the sample code for [SDCA regression](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Trainers.cs#L19), we need samples for the binary classifiers:
[SDCA](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs#L97)
[AveragedPerceptron](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.StandardLearners/Standard/Online/OnlineLearnerStatic.cs#L40)
[FastTree](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.FastTree/FastTreeStatic.cs#L87)
[LightGBM](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.LightGBM/LightGbmStatic.cs#L87)

There are two things to do, to resolve this issue:
1. Add a sample for each of the trainers in [Microsoft.ML.Samples/Trainers.cs](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Trainers.cs#L1)
The samples can look similar to the [cookbook example](https://github.com/dotnet/machinelearning/blob/master/test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamples.cs#L369)
Download the [adult dataset](https://raw.githubusercontent.com/dotnet/machinelearning/master/test/data/adult.train) for the data to use. 
Take a look at the  [SDCA example](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Trainers.cs#L19), for reference.

2. Add a link to the xml documentation of [SDCA](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs#L97)
[AveragedPerceptron](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.StandardLearners/Standard/Online/OnlineLearnerStatic.cs#L40)
[FastTree](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.FastTree/FastTreeStatic.cs#L87)
[LightGBM](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.LightGBM/LightGbmStatic.cs#L87)
 to reference the new sample methods, like the one in [SDCA](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs#L38) has.

**Comment by bojanmisic** [comment]
I'd like to work on this one, but wouldn't want to enter in a collision with someone. Is it possible to be assigned to this one?

**Comment by sfilipi** [comment]
Thanks @bojanmisic.  It doesn't look like we can assign it, but claiming it on the comments might be good enough. Tag me if you have questions.

**Comment by wschin** [comment]
Maybe add a new label "assigned"?

**Comment by justinormont** [comment]
Well, once someone claims it, we can simply remove the `help wanted` and `up-for-grabs` tags.

**Comment by bojanmisic** [comment]
@sfilipi, thanks! I believe the link to the cookbook examples has shifted, since the file has been changed recently. Would you like me to use static or dynamic API?

**Comment by sfilipi** [comment]
Dynamic is fine; I was going to log another bug for the static examples, after arranging the structure of that project. 
Thanks for picking this up.

**Comment by sfilipi** [comment]
@bojanmisic checking: are you still planning to work on this?

**Comment by bojanmisic** [comment]
@sfilipi, yes! I plan to work on that during the weekend. I have a strong will to contribute, just been crushed with work last two weeks. Sorry for the inconvenience, if you think someone can get it earlier, feel free to reassign.

**Comment by sfilipi** [comment]
@bojanmisic just checking, before putting the Assigned label and removing the other labels. It is yours, take your time.

**Comment by shmoradims** [comment]
@bojanmisic / @rekhakodali could you please help out with some documentation and samples?
I have a table of BinaryClassification trainers that need work in #2522. You can claim StochasticDualCoordinateAscent or SymbolicStochasticGradientDescent and add yourself (removed me) as the owner on the table. You can replicate #2688 for those trainers.

**Comment by bojanmisic** [comment]
@shmoradims, I'll be glad to contribute. Feel free to add me to the table for 1 or more (you can add me to both above) trainers, and I'll start working on those asap. I don't have edit permissions for the issue.

**Comment by jwood803** [comment]
@shmoradims @bojanmisic I'll be glad to take a couple of those, as well, if it helps out.

**Comment by sfilipi** [comment]
Closing, as most samples for binary classifiers are complete, and issue #2522 captures the broader work of trainer samples.
