### ISSUE TITLE
Add xml summary comments and argument validation to CpuMathUtils

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#1265]
Our `CpuMathUtils` class is public with public methods, but we don't have any xml summary comments, and only use `asserts` for argument checking.

Since these are public members, we should have xml doc comments and real argument checking.

See example:
https://github.com/dotnet/machinelearning/blob/7e9e4687284786ae241b2e8c8457a02686e639e9/src/Microsoft.ML.CpuMath/CpuMathUtils.netcoreapp.cs#L198-L207

Also, see PR comment here: https://github.com/dotnet/machinelearning/pull/1229#discussion_r224550873

**Comment by codemzs** [comment]
I see XML comments now 
https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.CpuMath/CpuMathUtils.netcoreapp.cs
