### ISSUE TITLE
Exception messages with TLC references in ModelHeader.cs

### ISSUE THREAD

**Issue by artidoro** [dotnet/machinelearning#1273]
The exception messages in ModelHeader.cs have TLC references. We have to remove references to TLC and replace them with corresponding ML.NET references.

In this, I think it should be sufficient to replace 'TLC' with 'ML.NET' in the string. 

https://github.com/dotnet/machinelearning/blob/a02807c7a805b72ef12970a37279c8cec4ea667d/src/Microsoft.ML.Data/Model/ModelHeader.cs#L352-L365

**Comment by justinormont** [comment]
Closed by #1277
