### ISSUE TITLE
Doc: PredictionEngine.Predict claims it creates a new object for each call.

### ISSUE THREAD

**Issue by rauhs** [dotnet/machinelearning#1279]
In:

https://github.com/dotnet/machinelearning/blob/8e77d0f0ce74cdb8b10fa545830972a4525d5dab/src/Microsoft.ML.Api/PredictionEngine.cs#L201-L205

> "<returns>The result of prediction. A new object is created for every call.</returns>"

Shouldn't this be the exact opposite? It's very confusing. IMO the docs & classes could need some more explanations.

Also, regarding: https://github.com/dotnet/machinelearning/blob/8cfa2ed503c1cca78972d79b393fbffe13bde173/docs/code/SchemaComprehension.md#predictionengine-and-predictormodel

This could probably use some guidlines. When to use PredictionEngine? When PredictionFunction? How to actually use BatchPredictionEngine? At first one thinks it's the same as PredictionEngine except that you can pass an IEnumerable. But not so. Very different API.

Is there anything in the pipeline to clarify all this? Also how this all plays together with saving/loading a model would be nice.

**Comment by Zruty0** [comment]
First of all, the comment is correct, it's the behavior that is not correct. #1138 is the related bug.

`PredictionEngine` and `BatchPredictionEngine` are probably going away altogether. First is supplanted with `PredictionFunction` and the second one is a glorified `Transform(...).AsEnumerable`. The only reason `BatchPredictionEngine` existed was that `PredictionEngine` was very slow. But we made it fast now

So, in the end, the guidance is: do not use any flavor of `PredictionEngine`. For one-time predictions, use `PredictionFunction`. For batch prediction, use `model.Transform`

**Comment by rauhs** [comment]
Got it. Thanks for the explanation. That helps.
