### ISSUE TITLE
Evaluation result classes shouldn't be nested under the Evaluator classes

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#1280]
When using our evaluation API:

```C#
BinaryClassificationContext binClassificationCtx = new BinaryClassificationContext(env);
BinaryClassifierEvaluator.CalibratedResult metrics = binClassificationCtx.Evaluate(predictions, "Label");
```

It is quite odd for the `metrics` object to be a nested class in the `BinaryClassifierEvaluator`. I didn't even use the `BinaryClassifierEvaluator` class at all, why am I dealing with a nested class inside of it?

I think these result classes should be moved to no longer be nested classes. Instead we should just have a `BinaryClassifierEvaluationResult` class.

/cc @Zruty0 @TomFinley @KrzysztofCwalina @terrajobst

**Comment by Zruty0** [comment]
I'm OK with the suggestion, although I would probably call it `BinaryClassificationMetrics` instead.

**Comment by eerhardt** [comment]
Good point. That's what we called it in the Legacy LearningPipeline API.

https://github.com/dotnet/machinelearning/blob/65c3c7c14b5da2655cce2c393a5b85546e5091fc/src/Microsoft.ML.Legacy/Models/BinaryClassificationMetrics.cs#L14-L17
