### ISSUE TITLE
Support Key Types in Input Data Structures of Prediction Function

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#1283]
Key types currently are not supported in input data structure of a prediction function ([an example](https://github.com/dotnet/machinelearning/blob/23659b013eb2d0233cd92072f32a6daddfe613e3/test/Microsoft.ML.Benchmarks/PredictionEngineBench.cs#L19) of prediction function). However, for recommender systems like matrix factorization, we have user and item IDs which are input keys. Do you have any plan to support key-typed input data structures?

**Comment by Zruty0** [comment]
Why do you think they are not supported? You can annotate a `uint` property with `KeyType` attribute and it will be interpreted as a key.

**Comment by wschin** [comment]
@TomFinley, looks like it's supported!
