### ISSUE TITLE
`MLContext.Model.Save` should accept statically typed models too

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#1286]
Add an extension method in `Microsoft.ML.StaticPipe` for that

**Comment by TomFinley** [comment]
I'm not altogether certain I agree. My general attitude is that the static API should be confined to things that specifically benefit from static typing of APIs (e.g., discoverability of what transforms can be applied to what data, and suchlike), and that if we enter a world where we don't it's totally acceptable (indeed desirable) to "drop down" to the dynamic API. But this is a more philosophical point, and I view the convenience proposed in this issue as inherently harmless in itself.

**Comment by codemzs** [comment]
Static API is not being developed on.
