### ISSUE TITLE
Improve constructor for TextLoader

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#1288]
We currently have 
```csharp
public TextLoader(IHostEnvironment env, Column[] columns, Action<Arguments> advancedSettings, IMultiStreamSource dataSample = null)
public TextLoader(IHostEnvironment env, Arguments args, IMultiStreamSource dataSample = null)
```
We need to:
1) Make the second constructor internal or private (it's used only by cmdline/dependency injection.
2) Add 'separator chars' and 'has header' as non-advanced parameters

The first change will naturally trigger a lot of changes in the code that creates the `TextLoader`, this is by design.

**Comment by Prsna23** [comment]
I would like to work on this issue.

**Comment by artidoro** [comment]
Will close this issue as it was taken care of in #1784.
