### ISSUE TITLE
Functions needed to be changed to use our new algorithm for aligned and unaligned loads

### ISSUE THREAD

**Issue by Anipik** [dotnet/machinelearning#1302]
Currently these functions are just using Unaligned Loads, we can make them after by aligning the data and doing aligned loads.

- [ ] AddScalerU
- [ ] ScaleSrcU
- [ ] AddScaleU
- [ ] ScaleAddU
- [ ] AddU
- [ ] AddScaleCopyU
- [ ] AddSU
- [ ]  MulElementWiseU
- [ ] SumU
- [ ] SumSqU
- [ ] SumSqDiffU
- [ ] SumAbsU
- [ ] SumAbsDiffU
- [ ] MaxAbsU
- [ ] MaxAbsDiffU
- [ ] DotU
- [ ] DotSU
- [ ] Dist2
- [ ] SdcaL1UpdateU
- [ ] SdcaL1UpdateSU

Reference for algorithm https://github.com/dotnet/machinelearning/pull/1143

cc @danmosemsft @tannergooding @eerhardt

**Comment by eerhardt** [comment]
What's the difference between this issue and https://github.com/dotnet/machinelearning/issues/830?  Aren't they they same and this one can be closed, and the remaining list be moved to #830?

**Comment by Anipik** [comment]
they are the same , I will update the issue with the list of functions
