### ISSUE TITLE
LightGBM 2.1.2.2 can not be installed on .net 4.6 ,LightGBM 2.2.1.1 can be installed ,but it does not work in ML.Net

### ISSUE THREAD

**Issue by sharpwood** [dotnet/machinelearning#1308]

**Comment by Ivanidzo4ka** [comment]
Hi @sharpwood  is it related to 0.6 release or current bits? We switch to 2.2.1.1 in https://github.com/dotnet/machinelearning/pull/1234 and it looks like it's passing our tests. Can you be more specific?

**Comment by artidoro** [comment]
Please reopen this issue with more details if you keep having this error. I will close this one for the moment.
