### ISSUE TITLE
Hyperparameter suggestions in Visual Studio

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning#1312]
Is it possible to have Visual Studio's IntelliSense/HelpText for each learner's hyperparameters inform the user of the `max` (absolute limits) and `good` (generally useful) ranges for the hyperparameter?

Currently we show nothing: _(though we can show the added text)_
> > >    ![image](https://user-images.githubusercontent.com/4080826/47199065-7c26c880-d324-11e8-80c2-13f05586d68a.png)

We do note the good ranges in the code for each component: 
https://github.com/dotnet/machinelearning/blob/b270b4d6b774a37e08321ba766aa8c15e81dfe77/src/Microsoft.ML.FastTree/FastTreeArguments.cs#L375

Why
----
Showing the `max` and `good` ranges/values for hyperparameters encourages the users to explore the ranges. While our defaults are good (honed on many datasets), the user will see gains on any particular dataset by exploring other values.

How
----
One way to accomplish this is generating the XML param comments from the attributes automatically, eg: `/// <param name="l2Const">The L2 regularization hyperparameter. A useful range is 0.025f–0.4f</param>`. Another option is hand maintaining both locations and some sort of static analysis of our code that checks that the attribute and the XML param comments match, and gives a build error if they didn't.

Thanks to @eerhardt for ideas on how to accomplish.

**Comment by artidoro** [comment]
@sfilipi might also have some ideas on how to best integrate them with our documentation.

**Comment by justinormont** [comment]
@TomFinley: Do you have ideas how to show hyperparameter ranges to users? Or a guess on the difficulty of implementing?

**Comment by sfilipi** [comment]
One idea is to put them in the XML comments. Do we want to use the values we have in the TGui attribute?
