### ISSUE TITLE
MLContext extensions for trainers

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#1319]
Go over all the trainers and ensure that:
- They are named according to #1318 
- Appropriate extensions are present
- The predictor classes are available in non-`Runtime` namespaces.

I anticipate that there's going to be some naming or interface decisions here, let's discuss them in this issue.

**Comment by sfilipi** [comment]
Is the Microsoft.Ml.Trainers a good namespace for them, or we want to keep them in something like Microsoft.Ml.Models? 

cc @wschin

**Comment by sfilipi** [comment]
This is complete through #1524, #1682, #1739
