### ISSUE TITLE
v0.6 Simple ONNX model initialization failed

### ISSUE THREAD

**Issue by little-eyes** [dotnet/machinelearning#1323]
### System information

- **OS version/distro**: Windows 10 17134.345
- **.NET Version (eg., dotnet --info)**: 2.1.402

### Issue

- **What did you do?** I tried to load a ONNX model that generated by Python onnxmltools and want to load the onnx model file, then apply to my test data.
- **What happened?** I got exceptions **System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'**
- **What did you expect?** The model could be loaded and scored.

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

```csharp
public class OnnxRunner
    {
        public class InputData
        {
            [VectorType(10)]
            public float[] data_0;
        }

        public class PredictionOutput
        {
            [ColumnName("label")]
            public uint Label { get; set; }
            [ColumnName("probabilities")]
            public float[] Probabilities { get; set; }
        }

        public void Run()
        {
            using (var env = new ConsoleEnvironment(null, false, 0, 1, null, null))
            {
                var dataPath = Path.Combine(Environment.CurrentDirectory, "sample_test_data.csv");
                var modelPath = Path.Combine(Environment.CurrentDirectory, "sample.onnx");
                var outputPath = Path.Combine(Environment.CurrentDirectory, "output.txt");

                var inputData = File.ReadLines(dataPath).Skip(1).Select(row => new InputData
                {
                    data_0 = row.Split(new char[] {  '\t' }).Select(token => float.Parse(token)).ToArray()
                }).ToList();

                var inputName = "data_0";
                var outputName = "label";

                var data = ComponentCreation.CreateDataView<InputData>(env, inputData);
                var pipeline = new OnnxEstimator(env, modelPath, inputName, outputName);
                var transformer = pipeline.Fit(data);
                var result = transformer.Transform(data);
            }
        }
    }
```

Sample ONNX file and data are here:
[sample.zip](https://github.com/dotnet/machinelearning/files/2497637/sample.zip)

I tracked the exception that it throws from here:
https://github.com/dotnet/machinelearning/blob/06b5ea6252e2c2766045d5f1436c55c1ccd8929d/src/Microsoft.ML.OnnxTransform/OnnxUtils.cs#L178

The ONNX file is generated by Python onnxmltools 1.2.2.129, the classifier in the model is lightgbm multi class classifier (v2.2.1)

**Comment by Ivanidzo4ka** [comment]
+ @jignparm @vaeksare

**Comment by Zruty0** [comment]
@jignparm , could you please look at this bug? It looks well defined.

**Comment by jignparm** [comment]
This is a limitation of the Microsoft.ML.Scoring underlying library – currently the API only supports graphs where the inputs and outputs are Tensor types. 

One of the  outputs  of the model is of type = ‘Sequence’, and there’s no API in the library to process this type yet. 

The upcoming release of the OnnxTransform depend on the newer OnnxRuntime library, which will have better error messages, so you’ll get a clearer message if something is not supported.  If you can switch the output to tensor instead of sequence, the model should run fine. 




![outputpic](https://user-images.githubusercontent.com/13698702/48243331-afdd9700-e394-11e8-9cd5-860f7c47c05c.png)

**Comment by jignparm** [comment]
This is a design question -- "how to consume complex sequences and maps in MLNet?".  Tensor types have fixed dimensions, and therefore we can determine the output schema accurately. If a transform emits sequence<map<type_A, type_B>>, where types A or B can again be sequences or maps, then what does the MLNet schema look like? Also, which elements are rows, which are columns -- those semantics need to be auto-inferred. 

There's a separate issue for  basic OnnxRuntime library functionality here https://github.com/Microsoft/onnxruntime/issues/156.

**Comment by Ivanidzo4ka** [comment]
What people usually do with this map?
Without knowing answer I and for simple plain case I would suggest to map it to following column:
ColumnType: R4 and it contains values.
Column has metadata SlotNames which is array of casted to string keys.

**Comment by jignparm** [comment]
> Column has metadata SlotNames which is array of casted to string keys.

The solution above works if the values are primitive types (such as 'float' or 'int'). This is less likely to work when the values are complex types (e.g. another map, or sequence of maps).  For example, if we had **Sequence<Map<int, float>>**, where the sequence can be arbitrarily long (in the case of this particular model, the length of the Sequence was 1, but another model have been longer), which values should be converted to columns (and which ones should be rows)? 

It seems like we need an algorithm (or a language) which can map an N-dimensional data structure into a 2-D sparse matrix (which is what MLNET is able to consume easily).

**Comment by shauheen** [comment]
@jignparm can you please update the issue with progress.

**Comment by jignparm** [comment]
Tracking here -> https://github.com/Microsoft/onnxruntime/issues/156
