### ISSUE TITLE
ML Tutorial does not compile on Mac 

### ISSUE THREAD

**Issue by bjorn-lundin** [dotnet/machinelearning#1329]
### System information

- **OS version/distro**:
macOS High Sierra (10.13.6)
tests-iMac:myApp bnl$ uname -a
Darwin tests-iMac.lan 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
tests-iMac:myApp bnl$ 

- **.NET Version (eg., dotnet --info)**: 
tests-iMac:myApp bnl$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.302 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

### Issue

- **What did you do?**
Following https://www.microsoft.com/net/learn/machinelearning-ai/ml-dotnet-get-started-tutorial

- **What happened?**
Code does not compile
Missing assembly references to
LearningPipeLine
TextLoader
Dictionarizer
and a couple of others detailed below

- **What did you expect?**
The tutorial to be fusional  - thus having compilable examples

I found a similar issue #309, says it is fixed - but no.

### Source code / logs
tests-iMac:ml bnl$ dotnet new console -o myApp
Getting ready...
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on myApp/myApp.csproj...
  Restoring packages for /Users/bnl/Projects/ml/myApp/myApp.csproj...
  Generating MSBuild file /Users/bnl/Projects/ml/myApp/obj/myApp.csproj.nuget.g.props.
  Generating MSBuild file /Users/bnl/Projects/ml/myApp/obj/myApp.csproj.nuget.g.targets.
  Restore completed in 1,14 sec for /Users/bnl/Projects/ml/myApp/myApp.csproj.

Restore succeeded.

tests-iMac:ml bnl$ cd myApp/
tests-iMac:myApp bnl$ dotnet add package Microsoft.ML
  Writing /var/folders/rw/3tm8flcx2z14g2dzd8y5vpl80000gp/T/tmpQsMyRD.tmp
info : Adding PackageReference for package 'Microsoft.ML' into project '/Users/bnl/Projects/ml/myApp/myApp.csproj'.
log  : Restoring packages for /Users/bnl/Projects/ml/myApp/myApp.csproj...
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.ml/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.ml/index.json 718ms
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.ml/0.6.0/microsoft.ml.0.6.0.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.ml/0.6.0/microsoft.ml.0.6.0.nupkg 524ms
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.ml.cpumath/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/newtonsoft.json/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/system.codedom/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.ml.cpumath/index.json 515ms
info :   GET https://api.nuget.org/v3-flatcontainer/system.threading.tasks.dataflow/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.ml.cpumath/0.6.0/microsoft.ml.cpumath.0.6.0.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/newtonsoft.json/index.json 684ms
info :   OK https://api.nuget.org/v3-flatcontainer/system.codedom/index.json 689ms
info :   GET https://api.nuget.org/v3-flatcontainer/system.codedom/4.4.0/system.codedom.4.4.0.nupkg
info :   GET https://api.nuget.org/v3-flatcontainer/newtonsoft.json/10.0.3/newtonsoft.json.10.0.3.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/system.threading.tasks.dataflow/index.json 554ms
info :   GET https://api.nuget.org/v3-flatcontainer/system.threading.tasks.dataflow/4.8.0/system.threading.tasks.dataflow.4.8.0.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.ml.cpumath/0.6.0/microsoft.ml.cpumath.0.6.0.nupkg 586ms
info :   OK https://api.nuget.org/v3-flatcontainer/newtonsoft.json/10.0.3/newtonsoft.json.10.0.3.nupkg 492ms
info :   OK https://api.nuget.org/v3-flatcontainer/system.codedom/4.4.0/system.codedom.4.4.0.nupkg 532ms
info :   OK https://api.nuget.org/v3-flatcontainer/system.threading.tasks.dataflow/4.8.0/system.threading.tasks.dataflow.4.8.0.nupkg 524ms
log  : Installing Newtonsoft.Json 10.0.3.
log  : Installing System.Threading.Tasks.Dataflow 4.8.0.
log  : Installing System.CodeDom 4.4.0.
log  : Installing Microsoft.ML.CpuMath 0.6.0.
log  : Installing Microsoft.ML 0.6.0.
info : Package 'Microsoft.ML' is compatible with all the specified frameworks in project '/Users/bnl/Projects/ml/myApp/myApp.csproj'.
info : PackageReference for package 'Microsoft.ML' version '0.6.0' added to file '/Users/bnl/Projects/ml/myApp/myApp.csproj'.
tests-iMac:myApp bnl$ nano iris-data.txt
tests-iMac:myApp bnl$ nano 
Program.cs     iris-data.txt  myApp.csproj   obj/           
tests-iMac:myApp bnl$ nano Program.cs 
tests-iMac:myApp bnl$ dotnet run
CSC : warning CS8032: An instance of analyzer Microsoft.ML.Analyzer.TypeIsSchemaShapeAnalyzer cannot be created from /Users/bnl/.nuget/packages/microsoft.ml/0.6.0/analyzers/dotnet/cs/Microsoft.ML.Analyzer.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/Users/bnl/Projects/ml/myApp/myApp.csproj]
Program.cs(47,32): error CS0246: The type or namespace name 'LearningPipeline' could not be found (are you missing a using directive or an assembly reference?) [/Users/bnl/Projects/ml/myApp/myApp.csproj]
Program.cs(52,30): error CS0246: The type or namespace name 'TextLoader' could not be found (are you missing a using directive or an assembly reference?) [/Users/bnl/Projects/ml/myApp/myApp.csproj]
Program.cs(57,30): error CS0246: The type or namespace name 'Dictionarizer' could not be found (are you missing a using directive or an assembly reference?) [/Users/bnl/Projects/ml/myApp/myApp.csproj]
Program.cs(60,30): error CS0246: The type or namespace name 'ColumnConcatenator' could not be found (are you missing a using directive or an assembly reference?) [/Users/bnl/Projects/ml/myApp/myApp.csproj]
Program.cs(65,30): error CS0246: The type or namespace name 'StochasticDualCoordinateAscentClassifier' could not be found (are you missing a using directive or an assembly reference?) [/Users/bnl/Projects/ml/myApp/myApp.csproj]
Program.cs(68,30): error CS0246: The type or namespace name 'PredictedLabelColumnOriginalValueConverter' could not be found (are you missing a using directive or an assembly reference?) [/Users/bnl/Projects/ml/myApp/myApp.csproj]
Program.cs(34,27): warning CS0649: Field 'Program.IrisData.Label' is never assigned to, and will always have its default value null [/Users/bnl/Projects/ml/myApp/myApp.csproj]
Program.cs(41,27): warning CS0649: Field 'Program.IrisPrediction.PredictedLabels' is never assigned to, and will always have its default value null [/Users/bnl/Projects/ml/myApp/myApp.csproj]

The build failed. Please fix the build errors and run again.
tests-iMac:myApp bnl$

**Comment by Ivanidzo4ka** [comment]
Hello @bjorn-lundin . I've clicked on getting started link and it doesn't have LearningPIpeline class or any calls to Dictionarizer.

Can you share your zipped project? Or maybe getting started got updated between your report and me looking into it.

**Comment by bjorn-lundin** [comment]
> 22 okt. 2018 kl. 22:57 skrev Ivan Matantsev <notifications@github.com>:
> 
> Hello @bjorn-lundin <https://github.com/bjorn-lundin> . I've clicked on getting started link and it doesn't have LearningPIpeline class or any calls to Dictionarizer.
> 

Strange. 

> Can you share your zipped project? Or maybe getting started got updated between your report and me looking into it.
> 

Ah, I see now. It is updated.
It does compile and run now.
I pasted t he version from yesterday below, that will make more sense 
When looking at the errors.
But Nevermind - I t is as you say fixed now.
Will you close my ticket?

(Thanks for a fast reply)

/Björn



This is from yesterday - 2018-10-21

using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Runtime.Api;
using Microsoft.ML.Trainers;
using Microsoft.ML.Transforms;
using System;

namespace myApp
{
    class Program
    {
        // STEP 1: Define your data structures

        // IrisData is used to provide training data, and as 
        // input for prediction operations
        // - First 4 properties are inputs/features used to predict the label
        // - Label is what you are predicting, and is only set when training
        public class IrisData
        {
            [Column("0")]
            public float SepalLength;

            [Column("1")]
            public float SepalWidth;

            [Column("2")]
            public float PetalLength;

            [Column("3")]
            public float PetalWidth;

            [Column("4")]
            [ColumnName("Label")]
            public string Label;
        }

        // IrisPrediction is the result returned from prediction operations
        public class IrisPrediction
        {
            [ColumnName("PredictedLabel")]
            public string PredictedLabels;
        }

        static void Main(string[] args)
        {
            // STEP 2: Create a pipeline and load your data
            var pipeline = new LearningPipeline();

            // If working in Visual Studio, make sure the 'Copy to Output Directory' 
            // property of iris-data.txt is set to 'Copy always'
            string dataPath = "iris-data.txt";
            pipeline.Add(new TextLoader(dataPath).CreateFrom<IrisData>(separator: ','));

            // STEP 3: Transform your data
            // Assign numeric values to text in the "Label" column, because only
            // numbers can be processed during model training
            pipeline.Add(new Dictionarizer("Label"));

            // Puts all features into a vector
            pipeline.Add(new ColumnConcatenator("Features", "SepalLength", "SepalWidth", "PetalLength", "PetalWidth"));

            // STEP 4: Add learner
            // Add a learning algorithm to the pipeline. 
            // This is a classification scenario (What type of iris is this?)
            pipeline.Add(new StochasticDualCoordinateAscentClassifier());

            // Convert the Label back into original text (after converting to number in step 3)
            pipeline.Add(new PredictedLabelColumnOriginalValueConverter() { PredictedLabelColumn = "PredictedLabel" });

            // STEP 5: Train your model based on the data set
            var model = pipeline.Train<IrisData, IrisPrediction>();

            // STEP 6: Use your model to make a prediction
            // You can change these numbers to test different predictions
            var prediction = model.Predict(new IrisData()
            {
                SepalLength = 3.3f,
                SepalWidth = 1.6f,
                PetalLength = 0.2f,
                PetalWidth = 5.1f,
            });

            Console.WriteLine($"Predicted flower type is: {prediction.PredictedLabels}");
        }
    }
}
