### ISSUE TITLE
Sepearting Platforms will ease development

### ISSUE THREAD

**Issue by reader-man** [dotnet/machinelearning#1331]
Thanks for the great work.
I suggest you make an interface, e.g. IVectorManupulation.
Then make three classes for each platform:
VectorManupulationIntel
VectorManupulationAMD
VectorManupulationSoftware

Then on first initializing the library, you make a check on the current hardware, and based on that you return the correct implementation:
VectorManupulationFactory.getVectorManup()

this will help u in separating the code for each platform, plus it will make the checking of the platform in one place or lesser places.

the factory pattern:
http://www.blackwasp.co.uk/FactoryMethod.aspx
https://sourcemaking.com/design_patterns/factory_method

in C#:
https://www.dofactory.com/net/abstract-factory-design-pattern
https://www.dofactory.com/net/factory-method-design-pattern

**Comment by Zruty0** [comment]
Thanks for your suggestion @reader-man !

Generally speaking, we are aware that factory method and abstract factory are useful design patterns.

The issue as filed seems to be overly general: there is no specific change, fix or enhancement that we can make to address it. Therefore, I will close the issue.

If you suggest to change a specific part of ML.NET library to take advantage of the above design patterns, please open separate issues about them.
