### ISSUE TITLE
Unhelpful warning "Term map for output column '#Temp_3' contains no entries

### ISSUE THREAD

**Issue by rauhs** [dotnet/machinelearning#1335]
For some data sets I've been getting:

> "Warning: Term map for output column '#Temp_3' contains no entries."

Which is not very helpful. Is there a chance derived/processes columns get a more meaningful name than "Temp_"?

**Comment by Ivanidzo4ka** [comment]
https://github.com/dotnet/machinelearning/blob/2d306ba1f7a7e8f4625e336c4c05212fca5de406/src/Microsoft.ML.Data/StaticPipe/StaticPipeUtils.cs#L149
I would suggest to replace it to something more meaningul

**Comment by Zruty0** [comment]
What's the suggestion? Would something like `#CategoricalEstimator_Temp_3` be any better? 

We are also somewhat limited on what we know when constructing these columns. @TomFinley  may have a comment.

**Comment by rauhs** [comment]
> Would be nice of course if there was a repro attached.

It's an intermittent warning I get on and off on some data-sets (we train models for each customer, on-premise) but not on others. It only happens like 10% of the time.

**Comment by codemzs** [comment]
is this from static api? that is no longer being developed. closing but feel free to reopen if you see this with stable api.

**Comment by antoniovs1029** [comment]
Hi, @rauhs , I was wondering: do you still get this warning message occasionally? If so, had you found any pattern or reason as to why you get it?

Our CI pipelines are failing and giving this warning message before aborting the test runs, so it might be helpful to get your insight about this warning message, if you have any. Thanks!

**Comment by rauhs** [comment]
@antoniovs1029 I'm not seeing this anymore. I don't use the static pipe anymore. It might be because the (categorical) feature was of cardinality 1.
