### ISSUE TITLE
LightGBM load model generated by python

### ISSUE THREAD

**Issue by little-eyes** [dotnet/machinelearning#1339]
I have a LightGBM binary classifier trained by Python package, I want to use ML.NET to serve the model and run prediction. So is there a sample that I can follow?

**Comment by artidoro** [comment]
Hello Jilong, could you tell us some more about the specific scenario that you are describing? In particular, are you tied to training in python? Are you interested in using ML.NET/C# for scoring?

**Comment by little-eyes** [comment]
> Hello Jilong, could you tell us some more about the specific scenario that you are describing? In particular, are you tied to training in python? Are you interested in using ML.NET/C# for scoring?

@artidoro Yes, I'm training my model in python and think of using ML.NET/C# for scoring. So I plan to export a train model from LightGBM, then use ml.net to load the model to score the results from a REST API.

**Comment by little-eyes** [comment]
> Thank you @little-eyes for letting us know about this scenario. I agree that what you describe is an important feature to add in ML.NET. We will keep this thread open and will let you know if there is any progress on this front in the near future.

Sounds good. thank you @artidoro

**Comment by artidoro** [comment]
I have very good news @little-eyes, we have just released [NimbusML](https://github.com/Microsoft/NimbusML)! This project provides experimental Python bindings for ML.NET. It has a pythonic api for all of ML.NET functionalities and integrates with scikit learn. 

If I understand your scenario correctly, this should solve your issue! You can now train a LightGBM model in python through NimbusML, and save your trained model directly in the ML.NET format. You'll be able to load and run your model in ML.NET in C#. 

For more information on getting started with NimbusML I would advise to look at the github page of [NimbusML](https://github.com/Microsoft/NimbusML). Let me know if this answers your initial question!
