### ISSUE TITLE
Microsoft.ML.FastTree project set to DisableDefaultCompileItems 

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#1351]
https://github.com/dotnet/machinelearning/blob/63a74bbb81753a2a6c0d73acc83fbbdd886f1a28/src/Microsoft.ML.FastTree/Microsoft.ML.FastTree.csproj#L7
this line basically force us to enumerate all files in project through <CompileItem>
I don't see any reason why we doing so, and it's uncommon for our projects.
So I suggest to delete that conditions, all CompileItems.

**Comment by Pielgrin** [comment]
Can I do it ?
