### ISSUE TITLE
ML.Net Bad value at line 7 in column Label

### ISSUE THREAD

**Issue by SandeepBhutani** [dotnet/machinelearning#1354]
### System information

- **OS version/distro**:
- **.NET Version (eg., dotnet --info)**: 

### Issue
ml.net sentiment analysis warning about format errors & bad values But still getting following errors. Most of training is going in errors

- **What did you do?**
Went through the sample provided as it is at:
[https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis)
- **What happened?**
Errors reading the input text
- **What did you expect?**
Code should read all input sample text

### Source code / logs
Issue asked origionally at:
[https://stackoverflow.com/questions/52837792/ml-net-bad-value-at-line-7-in-column-label](https://stackoverflow.com/questions/52837792/ml-net-bad-value-at-line-7-in-column-label)

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by feiyun0112** [comment]
please check tsv file content,  it should be like this:
```
Sentiment	SentimentText
1	  ==RUDE== Dude, you are rude upload that carl picture back, or else.
1	  == OK! ==  IM GOING TO VANDALIZE WILD ONES WIKI THEN!!!  
```
you can download tsv files on github
