### ISSUE TITLE
"Can't re-use trainer!" message on CV with AveragePerceptron. 

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#1358]
Running CV with Average Perceptron throws: "Can't re-use trainer":

Dataset: [wikiDetox](https://github.com/dotnet/machinelearning/blob/76cb2cdf5cc8b6c88ca44b8969153836e589df04/test/data/wikipedia-detox-250-line-data.tsv)

Code:
```
var data= mlContext.Data.TextReader(new TextLoader.Arguments()
                {
                    Separator = "tab",
                    HasHeader = true,
                    Column = new[]
                    {
                        new TextLoader.Column("Sentiment", DataKind.BL, 0),
                        new TextLoader.Column("SentimentText", DataKind.Text, 1)
                    }
                }).Read(dataFile);

var pipeline = mlContext.Transforms.Text.FeaturizeText("SentimentText", "Features")
                    .Append(mlContext.BinaryClassification.Trainers.AveragedPerceptron(label: "Sentiment", features: "Features"));
```

**Comment by Zruty0** [comment]
Actually, upon cursory look it seems that our `OnlineLinearTrainer` is stateful. This is horrible, the estimators are not supposed to be stateful. We will need to rewrite `OnlineLinearTrainer`.

**Comment by Zruty0** [comment]
@GalOshri you also hit this bug

**Comment by sfilipi** [comment]
@TomFinley do you want to close this with pr #1455
