### ISSUE TITLE
Need to add PackageReference to System.Memory from ML.CpuMath nuget

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#1359]
With #1229, we added a new dependency from the ML.CpuMath.csproj to `System.Memory`, however we didn't add the dependency to the nuget package.

In the .csproj:

https://github.com/dotnet/machinelearning/blob/d63e21ea1e3f6b950a48deb36045747d67dd02fa/src/Microsoft.ML.CpuMath/Microsoft.ML.CpuMath.csproj#L27-L33

but in the .nupkgproj:

https://github.com/dotnet/machinelearning/blob/d63e21ea1e3f6b950a48deb36045747d67dd02fa/pkg/Microsoft.ML.CpuMath/Microsoft.ML.CpuMath.nupkgproj#L3-L16

NOTE: We should also remove the `<PackageReference Include="System.Runtime.Intrinsics.Experimental" Version="4.6.0-preview1-26708-04" />` as well, as this is no longer needed.

**Comment by Niladri24dutta** [comment]
@eerhardt Hi , I have added the new reference and removed the `System.Runtime.Intrinsics.Experimental` reference from `Microsoft.ML.CpuMath.nupkgproj` file. But what should be the version number in this file for `System.Memory` as it's referring to a variable `SystemMemoryVersion` in this line of `csproj` `<PackageReference Include="System.Memory" Version="$(SystemMemoryVersion)" />` . I am working on branch of my fork,

**Comment by Niladri24dutta** [comment]
@eerhardt Thanks a lot , I will submit a PR

**Comment by Niladri24dutta** [comment]
@eerhardt created PR #1368
