### ISSUE TITLE
Add documentation samples for binary classifiers using the dynamic API 

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#1362]
Similar to PR #1361 we need code samples to reference from the new MLContext catalog extensions for all binary learners. 

Reference to the sample in PR #1361 and add samples for the following binary trainers. 
Cross reference those samples from the respective extensions on the catalog files.

Trainers:
[SGD](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.StandardLearners/Standard/SgdCatalog.cs)
[LogisticRegression](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsCatalog.cs#L33)
[FFM](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.StandardLearners/FactorizationMachine/FactorizationMachineCatalog.cs#L26)
[FastTree](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.FastTree/FastTreeCatalog.cs#L60)
[LightGBM](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.LightGBM/LightGbmCatalog.cs#L63)

**Comment by jwood803** [comment]
@sfilipi Not sure if this is exactly what is needed, but I have [this example](https://github.com/jwood803/MLNetExamples/blob/master/MLNetExamples/BinaryClassification/Program.cs) using Logistic Regression if it helps.

**Comment by sfilipi** [comment]
@jwood803  that example is perfect. DO you have interest/time to contribute it to the repo here, under the Microsoft.M.Samples project, and reference it from the LogisticRegression catalog? Unfortunately, it would have to be a different dataset, maybe the "adult" one, as we don't have permission to use the Titanic data.

**Comment by jwood803** [comment]
@sfilipi I'll be glad to put it under the samples project. Just to make sure, I should use [this](https://archive.ics.uci.edu/ml/datasets/adult) dataset, correct?

**Comment by sfilipi** [comment]
Anyone of the datasets in [this folder](https://github.com/dotnet/machinelearning/tree/master/test/data) should do. We can't use datasets outside of this repo...

Look at [this PR](https://github.com/dotnet/machinelearning/pull/1361), for a guide on how to link the sample back to the code it illustrates. 

Thanks for taking this @jwood803 ! Let's leave the issue open, since there are another 4 trainer estimators to illustrate.

**Comment by sfilipi** [comment]
This is now complete. Progress was also tracked through: #2522
