### ISSUE TITLE
CountFeatureSelection transform doesn't work with text

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#1364]
It uses a generic CountAggregator class which requires the type to be IEquatable, and ReadOnlyMemory<char> is not IEquatable. It doesn't seem like Equals() is used anywhere though, so I think this constraint can be removed.

**Comment by justinormont** [comment]
Is this new? I've used CountFeatureSelection (in MAML) very often.

**Comment by yaeldekel** [comment]
This is a regression caused by the switch from DvText to ReadOnlyMemory<char>.
