### ISSUE TITLE
.NET 4.7 CpuMathNative.dll not found

### ISSUE THREAD

**Issue by DaisyDave** [dotnet/machinelearning#137]
- Windows 10 Pro x64
- .NET Framework 4.7 Console App in Visual Studio 2017 15.7.1 

I followed the steps on the 'Get Started' page (https://www.microsoft.com/net/learn/apps/machine-learning-and-ai/ml-dotnet/get-started/windows). But I created a .NET 4.7 console app.

When I run the application the following exception is thrown on line 70 of Program.cs

I have located the missing DLL in the packages folder. If I manually copy the file into the output folder of my project the application runs as expected.

============== Exception Information ==============
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=mscorlib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.ML.Runtime.EntryPoints.EntryPointNode.Run()
   at Microsoft.ML.Runtime.EntryPoints.EntryPointGraph.RunNode(EntryPointNode node)
   at Microsoft.ML.Runtime.EntryPoints.JsonUtils.GraphRunner.RunAllNonMacros()
   at Microsoft.ML.Runtime.EntryPoints.JsonUtils.GraphRunner.RunAll()
   at Microsoft.ML.LearningPipeline.Train[TInput,TOutput]()
   at myApp.Program.Main(String[] args) in C:\Users\Dave\Documents\Visual Studio 2017\Projects\MLTests\Iris\Program.cs:line 70

Inner Exception 1:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 2:
DllNotFoundException: Unable to load DLL 'CpuMathNative': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by pareion** [comment]
I followed some of the suggetions from this page and got it to work with that tutorial
https://github.com/dotnet/machinelearning/issues/93

**Comment by aklcraigc** [comment]
@pareion I'm getting the same problem, what specifically do you think fixed the problem.

**Comment by tobiasw2** [comment]
I can confirm this issue. Besides the mentioned workaround (manually copying the missing file) it also works to switch the "TargetFramework" property from "net47" to "netcoreapp2.0". Therefore it seems to be related with using .NET Framework.

**Comment by eerhardt** [comment]
I've seen 2 cases where this error happens:

1. When you use packages.config instead of `<PackageReference>` in your .csproj.  This issue is tracked by #93, and a fix should be made soon to the daily builds.
2. On .NET Framework, if you are targeting `Any CPU`.  ML.NET only supports x64, so if you are using the desktop/full .NET Framework, ensure you change `Any CPU` to `x64`, since there are only x64 native assemblies.

**Comment by pareion** [comment]
@aklcraigc I manually changed the .csproj file by adding the line 
<PackageReference Include="Microsoft.ML" Version="0.1.0" /> 
And then changed the targeting to x64

**Comment by aklcraigc** [comment]
@pareion Thanks, that did the trick.

**Comment by DaisyDave** [comment]
@markusweimer Sorry for the lack of updates. The suggestions solved that error but there was a minor issue with the solutiion, I'm not sure whether this was because I didn't start from scratch and still had things in my packages folder. Below are the steps I took.

* I removed the packages added via NuGet from the solution.
* Switched VS Tools->Options to use 'PackageReference' for package management. 
* I then re-added Microsoft.ML from NuGet. 

There was one minor issue, it did not add any of the dependancies it had during the initial attempt. I ended up having to manual add the json package to get the app to run. As I said at the top I'm not sure if this was because I didn't start totally from scratch.

You can close this issue for me but if you are not going to or can't fix the package.config issue perhaps adding something to the getting started page would be an idea.

**Comment by claudiobottari** [comment]
I just tried the afortmentioned "PackageReference" workaround but I still getting the error. I had to switch to <TargetFramework>net462</TargetFramework> which I assume is the source of the issue.

**Comment by eerhardt** [comment]
@claudiobottari - are you using VS 2015 or VS 2017?  Would it be possible to share your .csproj so I can take a look?

**Comment by claudiobottari** [comment]
VS 2017

Here's the csproj:

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VersionPrefix>1.0</VersionPrefix>
    <TargetFramework>net471</TargetFramework>
    <RuntimeIdentifier>AnyCPU</RuntimeIdentifier>
    <Authors>Claudio Bottari</Authors>
    <Product>xxx</Product>
    <RootNamespace>xxx</RootNamespace>
    <ApplicationIcon />
    <OutputType>Exe</OutputType>
    <StartupObject>xxx</StartupObject>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <LangVersion>7.2</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <LangVersion>7.2</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="models\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML" Version="0.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="data\iris-data.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>

**Comment by claudiobottari** [comment]
Thank you, my project works now

**Comment by DaisyDave** [comment]
I'm going to close my issue.

**Comment by Dineshkumar-Ponnusamy** [comment]
Adding, 	`<PackageReference Include="Microsoft.ML" Version="0.1.0" />` inside the `<ItemGroup>` of *.csproj worked for me.

**Comment by pjmelvin** [comment]
I had to copy the file from the reference location in the ML download to the bin directory after the build to get this to work... bother.
