### ISSUE TITLE
Data.Schema.Column should get a DebuggerDisplay

### ISSUE THREAD

**Issue by rauhs** [dotnet/machinelearning#1379]
Background: I'm trying to write something like `TryGetScoreColumnNames` for a `Key<uint, string>` type. I noticed a that a schema in the debugger will just give me a long list of `Data.Schema.Column` (in my case ~60 of them). In the debugger it'd be nice to have the column name displayed and possibly even the data type.

**Comment by artidoro** [comment]
This is the issue where the work is being outlined #1242.

**Comment by Zruty0** [comment]
This was on my list indeed, but thanks @rauhs for making a request. I hope I will have something in a PR soon. Or feel free to take a stab at it: in #1242 I was just suggesting overriding `ToString()` for `Schema.Column`, should be an easy incremental improvement.

**Comment by rauhs** [comment]
Sorry for the noise. I will better search for existing issues next time. I will eventually try to contribute, but I'm currently a little swamped. Thanks for the quick response.
