### ISSUE TITLE
Need predictedLabel in binary classification as original string value (not bool)

### ISSUE THREAD

**Issue by GalOshri** [dotnet/machinelearning#1380]
Using ML.NET NuGet 0.7.0-preview-27025-1.

I have a binary classification dataset with string labels: "Spam", "Not Spam". 
I need to use the TermEstimator to turn the label into a key for the training to work. 
One output in the prediction from the binary classifier (let's say SDCA), is predictedLabel, which is a bool. 

How do I map the bool back to "Spam" or "Not Spam"? 

Thank you!

**Comment by artidoro** [comment]
@TomFinley should the predictedLabel in the output of a binary classifier be a bool, or should it be a key?

**Comment by Ivanidzo4ka** [comment]
You should use MapKeyToValue on "PredictedLabelColumn"
