### ISSUE TITLE
CI build failing due to timeout errors

### ISSUE THREAD

**Issue by Anipik** [dotnet/machinelearning#1382]
Some of the tests are taking really long time to run which cause the build to run for more than 60 mins and are then declared as failure. Some of tests that Run for a lot of time are

Microsoft.ML.Runtime.RunTests.TestPredictors takes 33mins and it only executes 59 tests
TestHyperparameterFreezing -24min
FastTreeBinaryClassificationCategoricalSplitTest -18min
SavePipeWithHeader -4min

Maybe we should fix those tests. We can try running the tests in parallel using helix rather than in a chain.

cc @eerhardt @safern

**Comment by eerhardt** [comment]
FYI - `Helix` is the "cloud test" platform that is used to run the large number of unit tests we have in `dotnet/corefx` and `dotnet/coreclr`.  https://github.com/dotnet/arcade/blob/master/Documentation/VSTS/SendingJobsToHelix.md

**Comment by Ivanidzo4ka** [comment]
Still looking into this.
One thing for sure: 
this should be static, create regex on each comparison of lines for all files, is CRAZY.
https://github.com/dotnet/machinelearning/blob/dddb5c134771a85132f919cd1cf32a9ff8836e10/test/Microsoft.ML.TestFramework/BaseTestBaseline.cs#L509
