### ISSUE TITLE
Need to simplify Data Types to simpler/less common .NET types

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning#1386]
In the dynamic API we have too many and not .NET "standard types" you need to use when creating the file columns schema for loading data. The list of types is not very "dotnetty":

![image](https://user-images.githubusercontent.com/1712635/47534500-6e190080-d86c-11e8-9553-535625943d47.png)

This is what you see in intellisense:

![image](https://user-images.githubusercontent.com/1712635/47534520-7bce8600-d86c-11e8-811a-55c1c4030a61.png)

For instance for text you have Text, TX, and TXT, many types not very clear like R4, etc.

We need to have a simpler and more standard list of data types.

**Comment by Zruty0** [comment]
Do you have a suggestion in mind @CESARDELATORRE  ?

**Comment by CESARDELATORRE** [comment]
Maybe something like the following:

```
    public enum ValueTypes : byte
    {
	//...
	Float = 9,
        String = 11,
        Bool = 12,
        TimeSpan = 13,
        DateTime = 14,
        TimeZoneInfo = 15,
	//etc.
    }
```

The closer it can be to data types in C#, the better:
https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/types-and-variables

https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo?view=netframework-4.7.2

**Comment by Zruty0** [comment]
I think mapping to .NET types is positive. In the past, we chose to have 2-character descriptions of our types, but I was never a big fan. Maybe @TomFinley was? He was the creator of `UG` after all :)

The one type I am suspicious about is `String` (since we use `ROM<char>`). Maybe `Text` is OK in that particular case?

**Comment by GalOshri** [comment]
This looks good to me. What purpose do the current granular types play after the work done in #673?

**Comment by CESARDELATORRE** [comment]
Sound good! Thank you guys! 👍

**Comment by jwood803** [comment]
Is there currently a way to map these to their respective .NET types? 

I mainly ask since quite a few examples use the `context.Data.TextReader` and set the columns with the `new TextLoader.Column` where the `DataKind` gets passed in. I also ask in case this is something I can possibly help with. 😄

**Comment by jwood803** [comment]
I'd be glad to help but I'm not sure how to map the current Data Kind types to .NET types.


________________________________

**Comment by eerhardt** [comment]
> I'd be glad to help 

Great! We could really use some help here.

The overall goal (as I understand it) is that we want to remove the `DataKind` enum. Checkout the discussion in #2006 (and related links).

So basically, if you could search for usages of DataKind and remove them and instead use things like [`ColumnType.RawType`](https://github.com/dotnet/machinelearning/blob/312f9e4c71953bee701ea2a63be3cb4d2d276d20/src/Microsoft.ML.Core/Data/ColumnType.cs#L57-L64) or other APIs.  I'd start with usages of `DataKind RawKind` on ColumnType.

Maybe do a file/class at a time and send a PR. Once I'm done doing my current work I was going to start in this area. So it would be good to do small incremental chunks, so we don't overlap too much.

> but I'm not sure how to map the current Data Kind types to .NET types

Check out https://github.com/dotnet/machinelearning/blob/312f9e4c71953bee701ea2a63be3cb4d2d276d20/src/Microsoft.ML.Core/Data/DataKind.cs#L136-L175

**Comment by singlis** [comment]
I wanted to ping the thread as I see this is in 0.11. After reading #2006, what is this issue tracking for 0.11? Is it to remove DataKind all up or is it to internalize DataKind (which mainly looks to be on TextLoader).

**Comment by eerhardt** [comment]
I would say we should internalize/remove usages of `DataKind` in as many places as possible. I see public usages by `TextLoader`, `PartitionedFileLoader`, and `TypeConvertingTransformer` so far... I also see some code that writes the `byte` value of the `DataKind` into the model file...

If we decide that `DataKind` has to be a public enum for the above public usages, then we should also do some renaming, as outlined by this issue.

Note - the names we should use should match the `System.XXX` type names in .NET.  So `System.Single` instead of `Float`. `System.Boolean` instead of `Bool`.  etc.

**Comment by DevLob-zz** [comment]
one point to mention here when read from IEnumerable 

if i have int , double , float , bool data types always map it to Float DataKind.R4

so when try to generate model it throw exception for mismatch as he expected to find  R4 and find some else 

i worked around and convert every type to be float which in not fine to do that is there ability to Explicitly set this or some attributes that load correct type for numeric variable 

best regards

**Comment by wschin** [comment]
This is the current `DataKind` in ML.NET. Would it close this thread?
```csharp
    public enum DataKind : byte
    {
        /// <summary>1-byte integer, type of <see cref="System.SByte"/>.</summary>
        SByte = 1,
        /// <summary>1-byte unsigned integer, type of <see cref="System.Byte"/>.</summary>
        Byte = 2,
        /// <summary>2-byte integer, type of <see cref="System.Int16"/>.</summary>
        Int16 = 3,
        /// <summary>2-byte usigned integer, type of <see cref="System.UInt16"/>.</summary>
        UInt16 = 4,
        /// <summary>4-byte integer, type of <see cref="System.Int32"/>.</summary>
        Int32 = 5,
        /// <summary>4-byte usigned integer, type of <see cref="System.UInt32"/>.</summary>
        UInt32 = 6,
        /// <summary>8-byte integer, type of <see cref="System.Int64"/>.</summary>
        Int64 = 7,
        /// <summary>8-byte usigned integer, type of <see cref="System.UInt64"/>.</summary>
        UInt64 = 8,
        /// <summary>4-byte floating-point number, type of <see cref="System.Single"/>.</summary>
        Single = 9,
        /// <summary>8-byte floating-point number, type of <see cref="System.Double"/>.</summary>
        Double = 10,
        /// <summary>string, type of <see cref="System.String"/>.</summary>
        String = 11,
        /// <summary>boolean variable type, type of <see cref="System.Boolean"/>.</summary>
        Boolean = 12,
        /// <summary>type of <see cref="System.TimeSpan"/>.</summary>
        TimeSpan = 13,
        /// <summary>type of <see cref="System.DateTime"/>.</summary>
        DateTime = 14,
        /// <summary>type of <see cref="System.DateTimeOffset"/>.</summary>
        DateTimeOffset = 15,
    }
```

**Comment by eerhardt** [comment]
Yes - I believe our change to the public DataKind enum closing this issue. Please re-open if this isn't the case.

**Comment by eerhardt** [comment]
Fixed by https://github.com/dotnet/machinelearning/pull/2661

**Comment by CESARDELATORRE** [comment]
The additional issue is that error messages are still showing those internal data types.. ;)
