### ISSUE TITLE
Q: ML Model Builder

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/machinelearning#1397]
Is there any update with regards the VisualStudio ML Model Builder prototype; is/will this available as a preview ?

**Comment by artidoro** [comment]
@GalOshri do you know the plans regarding the above?

**Comment by GalOshri** [comment]
@rustd would have the latest details about this.

**Comment by shmoradims** [comment]
ping @rustd

**Comment by wickedlizerd** [comment]
Any updates on this?

**Comment by javageek68** [comment]
Is this tool open source as well?

**Comment by grahamehorner** [comment]
Is @rustd recovering pings?

**Comment by rustd** [comment]
My apologies. We are still working on the tool. It's not released yet and will be available as a preview in the future. We don't have a specific date yet.

**Comment by grahamehorner** [comment]
@rustd I’m assuming that this development is not getting done on github it is not going to be open source?

**Comment by hansmbakker** [comment]
See https://github.com/dotnet/machinelearning-samples/tree/master/modelbuilder. This can close the issue.

**Comment by justinormont** [comment]
@javageek68, @grahamehorner: The AutoML code behind the ML Model Builder (not MB itself) is in a branch and will be merged in to main as time allows. The AutoML code was forked in to its own repo for development and is coming back. 

Branch: 
https://github.com/dotnet/machinelearning/tree/features/automl/src/Microsoft.ML.AutoML

**Comment by kdcllc** [comment]
@justinormont I also recommend this spec doc with instruction on how to install dotnet cli tool [Specs for the ML.NET CLI with AutoML](https://github.com/dotnet/machinelearning/blob/7b7a2bc182cde58ccd65ed1a215d320374649a08/docs/specs/mlnet-cli/MLNET-CLI-Specs.md#tool-name)

**Comment by rustd** [comment]
Closing this issue as ML.NET Model Builder is now available and can be downloaded [here](https://aka.ms/mlnettemplates)
