### ISSUE TITLE
Improve error message for missing LightGBM dependencies at runtime.

### ISSUE THREAD

**Issue by montebhoover** [dotnet/machinelearning#1403]
### System information

- **macOS 10.13**:
- **.NET Core 2.1.4**: 

### Source code / logs

`Error: *** System.DllNotFoundException: 'Unable to load DLL 'lib_lightgbm': The specified module or one of its dependencies could not be found.`

### Issue

Using LightGBM on a Mac requires OpenMP as a runtime dependency (libomp.dylib or libgomp.dylib).  The error message does not make it clear that this is the problem.  The user would have to search and determine whether lib_lightgbm.dylib actually does exist, and then use `otool -L lib_lightgbm.dylib` to discover it's dependent libs and then search for them.  Some versions of LightGBM require libgomp (the GCC implementation) while others require libomp.

@TomFinley, in relation to https://github.com/Microsoft/NimbusML/issues/18 can we do a `dlopen` check in [LightGbmTrainerBase](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.LightGBM/LightGbmTrainerBase.cs) to verify runtime dependencies and print a more helpful error message?  Or should I open an issue in https://github.com/Microsoft/LightGBM?

**Comment by artidoro** [comment]
I think we are already tracking this issue at #1282.

**Comment by montebhoover** [comment]
Thanks!
