### ISSUE TITLE
Convenient way of providing LDA topic summary

### ISSUE THREAD

**Issue by abgoswam** [dotnet/machinelearning#1411]
In the `LdaTransform`,  the details of the learnt model are contained in the `LdaState` object.  When the user wants to introspect the LDA model learnt during the transformation, we return a topic summary vector .

We need to find a proper way of returning topic summary information to the user. Specifically the words that map to the topic summary vector 

For this we need to figure out how to extract details from the `LdaState` object using C#.  Currently  `LdaState` invokes native code behind the scenes to get model info.

**Comment by abgoswam** [comment]
It turns out this can be handled by mapping slot names from the input schema during training. I have taken care of this in PR #1410

**Comment by abgoswam** [comment]
PR #1410  took care of this

**Comment by najeeb-kazmi** [comment]
This is again an issue since the PigSty API was removed. This functionality is no longer available in the Dynamic API. #4322 tracks all the issues filed for LDA topic summary.
