### ISSUE TITLE
Need a state of evaluation result after each epoch during training.

### ISSUE THREAD

**Issue by saqw3r** [dotnet/machinelearning#1419]
### Issue

- **I'm training my model. But I have no idea how good my model architecture is. And how much pretraining additional efforts required**
- **In some cases it is trained ok, and in others, I cannot go out of 1 % (I'm seeing only final results), but anyway I don't see how right is the evaluation process during the timeline (after each epoch of training). Maybe it has been overfitted after few first epochs? I can't analyze it - too little data.**
- **I would expect to have some object to store this state (I believe it is on a private level, but I don't see it in public API) after each epoch and I suppose to be able to iterate forward until I reach some level of percentile. See how Keras from Python world do it.**

**Comment by codemzs** [comment]
please refer to our samples and see how elevators are used 
https://github.com/dotnet/machinelearning/tree/master/docs/samples/Microsoft.ML.Samples/Dynamic
