### ISSUE TITLE
LightGBM tests fails in x86 build, but that doesn't stop build

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#1421]
So let's take this build:
https://dnceng.visualstudio.com/public/_build/results?buildId=36379&view=logs
It fails on MacOS and @wschin  working on it https://github.com/dotnet/machinelearning/issues/1395

![image](https://user-images.githubusercontent.com/1523833/47623415-6eb0d180-dace-11e8-9ba0-654270a11be9.png)
but if you look into failed tests tab:
![image](https://user-images.githubusercontent.com/1523833/47623417-8425fb80-dace-11e8-9b20-d8eca458e92d.png)
it show you what x86 windows builds also failed, but that didn't affected their successful status.

**Comment by artidoro** [comment]
Yes I'll take a look!
