### ISSUE TITLE
Local build fails on master 

### ISSUE THREAD

**Issue by ganik** [dotnet/machinelearning#1423]
On Windows 10 machine

> git clone https://github.com/dotnet/machinelearning.git
> cd machinelearning
> build 

Build Failed.
CMake Error at MatrixFactorizationNative/CMakeLists.txt:14 (add_library):
    No SOURCES given to target: MatrixFactorizationNative

**Comment by shauheen** [comment]
Hi @ganik , I think you need to do what is described in #1412
