### ISSUE TITLE
Rename 'Documentation' folder to 'Docs' for consistency

### ISSUE THREAD

**Issue by asthana86** [dotnet/machinelearning#143]
There is a mix of lowercase and capitalization e.g. (Documentation vs. src, pkg, test) and usage of short vs. long names (e.g. Documentation vs. src, pkg, test). 

Would propose renaming to the following:
Documentation -> docs

Thoughts?

**Comment by justinormont** [comment]
There is a related discussion for moving ZBaselines under the tests folder: https://github.com/dotnet/machinelearning/issues/100

**Comment by asthana86** [comment]
Updated this to be specifically about docs.
