### ISSUE TITLE
Optimize FastTreeNative

### ISSUE THREAD

**Issue by helloguo** [dotnet/machinelearning#1451]
It seems FastTree uses native code or managed code based on the config `USE_FASTTREENATIVE`. Currently FastTreeNative uses SSE instructions. It could be optimized with 256 bits AVX/AVX2 instructions. It can be done either using native cpp intrinsics or C# HW intrinsics.

**Comment by helloguo** [comment]
@codemzs any thoughts on this?

**Comment by codemzs** [comment]
hey @helloguo do we know how much perf improvement this will give us? closing this issue until then but please feel free to reopen if you have a reasonable estimate.
