### ISSUE TITLE
LIBMF prediction varys on Mac

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#1459]
The `MatrixFactorizationSimpleTrainAndPredict` test frequently fails on Mac with the following message. We need to figure out the reason to reduce the number of rebuilds.

Error message

Assert.InRange() Failure
Range: (0.60692207960271 - 0.61692207960271)
Actual: 0.592577526427063
Stack trace at Microsoft.ML.Tests.TrainerEstimators.TrainerEstimators.MatrixFactorizationSimpleTrainAndPredict() in /Users/buildagent/agent/agent/_work/1/s/test/Microsoft.ML.Tests/TrainerEstimators/MatrixFactorizationTests.cs:line 118

**Comment by codemzs** [comment]
i believe the tests are passing on all flavors now. @ws please reopen if you feel this issue has not been addressed.

**Comment by antoniovs1029** [comment]
This test was disabled in #1455 for Mac, but I believe the problem was never addressed.

Right now it's also failing in other platforms, and in fact it's the 2nd test that fails the most in our build pipelines.

**Comment by frank-dong-ms** [comment]
fixed in https://github.com/dotnet/machinelearning/pull/5121, close this issue
