### ISSUE TITLE
Q: Retrieving DataView Schema from a Saved Model

### ISSUE THREAD

**Issue by kwefah** [dotnet/machinelearning#1466]
Using the new ML.Net API, say I want to fit an Estimator chain to a DataView to produce a model i.e TransformerChain. After saving the model to a Zip and then reloading from another process, is it possible to retrieve details about the schema of the DataView that the model was initialy fit to?

Basically, I'd like to use the DataView schema to aid in construction of the Training class, and would preferably want to avoid persisting both the IDataView metadata and the TransformerChain to disk separately.

**Comment by Zruty0** [comment]
Hi @kwefah . The model does not retain any information about the schema of the data it was 'fitted on'. 
Only the information that is essential for the transformer to function is saved to the model file.

Sometimes, there is no need to actually retain the schema of the training data: for instance, the `KeyValues` metadata for the `PredictedLabel` of a multiclass predictor contains the original label names, so you don't need to retain metadata of your label column.

However, if you still want to retain the schema of the original data, my best suggestion would be to save an empty data view to disk using binary saver:

Create an empty data view:
```csharp
var empty = new EmptyDataView(mlContext, trainingData.Schema);
```

Save a data view to a binary file (we still haven't added the MLContext API for that, it's coming):
https://github.com/dotnet/machinelearning/blob/master/test/Microsoft.ML.Tests/Scenarios/Api/Estimators/FileBasedSavingOfData.cs#L37

**Comment by kwefah** [comment]
Thanks for the suggestions.
