### ISSUE TITLE
Investigate the build issues, focusing on tests

### ISSUE THREAD

**Issue by TomFinley** [dotnet/machinelearning#1471]
At the time of writing our build system is plagued by a large number of failing tests and other build issues. This impacts our agility since an otherwise valid PR can not pass the test checks for spurious reasons that have nothing to do with the change. It also in turn leads to significant wastage of resources. The goal would be to improve the test error rate.

However, we are vexed somewhat by a lack of information on why these test failures are occurring. In particular, trying to reproduce test failures locally has, at least in my experience, very limited success. For example, in my own investigation into the random failures of `MulticlassTreeFeaturizedLRTest` on MacOS debug, I was only able to achieve a test failure twice out of some hundreds of runs on a Macbook, and what information I was able to gather was limited.

In the seeming absence of the ability to reliably produce test failures outside of the build machines, we need more information.

1. Publish the tests logs as an artifact of the build so that we can gather more information. #1473.

2. Make the error messages from tests, when they do occur, contain some actually useful information. #1477.

3. Create a catalog of failures that occur in builds that in principle *should* have succeeded. (E.g., builds of `master`.) This is partially to validate the assumption that tests are the primary problem, as well as to get a sense of what tests are problematic. #1474.

The preceding is purely information gathering, but at the same time there are some positive steps that can be taken, pending the above.

1. We already know of some troublesome tests. These should be investigated for the "usual suspects," e.g., failure to set random seeds to a fixed value, having a variable number of threads in training processes, etc. (Which are known, but innocent, sources of run to run variance.)

2. That the tests seem to fail so readily on the build machines yet are vexingly difficult to make fail locally suggests that there is something about the build environment that is different -- perhaps a different architecture or performance characteristics raise issues or race conditions that are simply not observed on our more performant developer machines. It may therefore be worthwhile to try to get the test environment machines reproduced exactly (down to the environment, processor, memory, everything) to see if that shows any clues.

3. Most vague, but still useful, the nature of the failures, while mysterious, have not been entirely devoid of clues as to potential causes. I may write more about them in a comment later.

/cc @Zruty0 @eerhardt

**Comment by eerhardt** [comment]
Note for

> 3. Create a catalog of failures that occur in builds that in principle should have succeeded. (E.g., builds of master.) This is partially to validate the assumption that tests are the primary problem, as well as to get a sense of what tests are problematic.

We do have a set of builds that should in principle always succeed. After every merge into the `master` branch, we run a "CI" build that just takes what is now in `master` and runs the validation build against it.  These builds are called "CI Build"s in Azure DevOps:

https://dnceng.visualstudio.com/public/_build?definitionId=104&_a=completed&view=buildsHistory&showFilters=true

![image](https://user-images.githubusercontent.com/8291187/47815759-466be180-dd1f-11e8-82af-58ddce4732f6.png)

You can see the above filters (not sure how to provide a link to the query). ALL of these runs "should" have passed, but didn't for one reason or another. These runs weren't against a PR that had failures. These runs were against the current `master` branch.

There is also an "Analytics" tab where you can see which tests fail the most:

![image](https://user-images.githubusercontent.com/8291187/47815943-b4180d80-dd1f-11e8-879b-0b1ad28b202f.png)

I assume anything less than 90% pass rate is not acceptable (looking at you LightGBM tests).

**Comment by Ivanidzo4ka** [comment]
Is this a thread about timeouts on Mac? If not, I'm hijacking it right now.


I'm a simple man. I wrote code which parse test outputs and looking for Starting test to add something to hashset and Finished test to remove it from hashset
so far:
![image](https://user-images.githubusercontent.com/1523833/47823890-89ca4e00-dd27-11e8-9a34-9562a7ded6f8.png)
or this:
![image](https://user-images.githubusercontent.com/1523833/47824055-520fd600-dd28-11e8-8575-2ce09ab526d9.png)


I've check about 10 different test logs which resulted in timeout on mac and in all cases I have this triplet of ImageSmoke, CopyColumns and OnlineGradient present.

**Comment by sfilipi** [comment]
Starting to take note of tests that hug up:
I am seeing a hung up after: Microsoft.ML.Scenarios.ScenariosTests.TensorFlowTransformCifar

**Comment by montebhoover** [comment]
Here are instructions for reproducing the Hosted Mac environment for debugging test failures locally: https://dev.azure.com/aifx/public/_settings/agentqueues?queueId=5&_a=agents 

![image](https://user-images.githubusercontent.com/37886197/47931523-40474380-de8c-11e8-98c4-3d6681505204.png)

Might be helpful with #1506

**Comment by codemzs** [comment]
we did improve tests last year to improve pass rate. closing this.
