### ISSUE TITLE
Random build failures: Publish the test logs

### ISSUE THREAD

**Issue by TomFinley** [dotnet/machinelearning#1473]
Companion issue to #1471. As mentioned there we are currently lacking information about test failures.

Our tests actually do produce sizable logs that could *conceivably* be of help, if we were only able to access them. This includes most notable output files that are compared against baseline files, as well as in many cases the trained models themselves. For example, for a `Debug` build, and the `Microsoft.ML.Core.Tests` test, we would want to publish `bin/AnyCPU.Debug/Microsoft.ML.Core.Tests/netcoreapp2.1/TestOutput` as an artifact of the build. (The same for all tests.) We would of course want the test artifacts for *all* test assemblies to be published, as well as for either debug and release, as well as for all of the currently supported platform.

We of course used to do this, but this capability was somehow lost when we moved to the new build infrastructure a few months ago I believe.

So for example, if we [view this build](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2162533&view=results) (note that some will not be able to access this!), we have published this artifact named `PackageAssets`, as seen below.

![image](https://user-images.githubusercontent.com/8295757/47815258-1adffb80-dd0d-11e8-8d3e-7d11bc3ff79b.png)

This appears at least at first glance to be controlled from this in our repo.

https://github.com/dotnet/machinelearning/blob/a26eca7e9dbec1cb8311db2e8dac7fc11bbf54ea/build/vsts-ci.yml#L30-L35

@eerhardt has already provided some assistance in this area, though as of yet I have been unable to find time to follow up on his hints.

* [Documentation on publishing build artifacts.](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/artifacts?view=vsts)
* [A specific example, from Roslyn (not our repo of course), of doing just that.](https://github.com/dotnet/roslyn/blob/master/.vsts-ci.yml#L56-L72)

Our specific `.yml` configuration files for doing the continuous integration are at the following locations:

* [.vsts-dotnet-ci.yml](https://github.com/dotnet/machinelearning/blob/master/.vsts-dotnet-ci.yml)
* [build/ci/phase-template.yml](https://github.com/dotnet/machinelearning/blob/master/build/ci/phase-template.yml)
* [build/vsts-ci.yml](https://github.com/dotnet/machinelearning/blob/master/build/vsts-ci.yml)

It may be as simple as following Roslyn's example and modifying `build/vsts-ci.yml` to just publish a few more things, but I'm not altogether confident of this.

This may be a task best suited to someone with some experience mucking about in these configuration files.

**Comment by montebhoover** [comment]
Tom, you are exactly right, this will be as simple as modifying `build/vsts-ci.yml`.  I'll make a quick PR to update that and we'll start having access to the build logs produced by the VSTS agents.
