### ISSUE TITLE
Transform categories in intellisense are missing descriptions 

### ISSUE THREAD

**Issue by GalOshri** [dotnet/machinelearning#1478]
Testing latest 0.7 release candidate: [0.7.0-preview-27031-8](https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.ML/0.7.0-preview-27031-8).

It is not clear what is the difference between categorical and conversion transforms (as categorical transforms convert categorical features to numeric vectors). Descriptions are needed to explain these different categories so a user knows what to expect.

<img width="945" alt="image" src="https://user-images.githubusercontent.com/2601900/47821157-f8ee7500-dd1c-11e8-8521-8d8b07911c12.png">

**Comment by codemzs** [comment]
with stable release this should have been fixed. please reopen if you still this with stable release nuget.
