### ISSUE TITLE
Update the Getting Started with ML.NET tutorial to 0.7

### ISSUE THREAD

**Issue by artidoro** [dotnet/machinelearning#1481]
We should update the tutorial, as it does not work with 0.7. That is the starting point for many people, so we should make sure it is ready and up to date for when we release 0.7. @CESARDELATORRE If you show me how to do it, I can help with that.

**Comment by rekhakodali** [comment]
Can I contribute please

**Comment by shmoradims** [comment]
@CESARDELATORRE / @shauheen , are 0.7 samples / tutorials still used? Isn't everything updated to 0.8 already? If so, we can close this issue.

**Comment by shmoradims** [comment]
Closing this issue, as we've now moved to 0.8+.
