### ISSUE TITLE
Matrix Factorization Dependencies

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#1482]
For matrix factorization, we need to mention all its dependencies. For example, MatrixFactorization's core part is packed in a Nuget, which is not mentioned anywhere.

**Comment by shmoradims** [comment]
@wschin is this already fixed during documentation project?

**Comment by wschin** [comment]
The required NuGet in addition to `Microsoft.ML` is `Microsoft.ML.Recommender` as mentioned [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.matrixfactorizationtrainer?view=ml-dotnet-preview#trainer-characteristics).

**Comment by shmoradims** [comment]
Already fixed as part of the work before //build.
