### ISSUE TITLE
MatrixFactorizationTrainer should include Estimator in its name

### ISSUE THREAD

**Issue by artidoro** [dotnet/machinelearning#1484]
MatrixFactorizationTrainer implements IEstimator, and should therefore include "estimator" in its name. 
It should be named something like ActionPerformingEstimator as per #1318.

**Comment by Zruty0** [comment]
Actually, #1318 says that trainers should be called `AlgorithmNameTrainer`, so I don't think there's any violation here.

**Comment by artidoro** [comment]
@Zruty0, sorry about that. I misread the post! Thank you for replying.
