### ISSUE TITLE
Support for LSTM / RNN (Time Series)

### ISSUE THREAD

**Issue by OneCyrus** [dotnet/machinelearning#149]
Great project and i really love the classifiers so far! Are there any short term plans to support LSTM / RNN for time series type of predictions? Or may be i just overlooked it.

**Comment by glebuk** [comment]
Thanks for your question, Daniel.
Indeed DNNs are not yet available.  However, we do plan to add support for DNN learners, such as [Cognitive Toolkit](https://github.com/Microsoft/CNTK) or [Tensorflow](https://github.com/tensorflow/tensorflow) in our [ROADMAP.md](blob/master/ROADMAP.md).

**Comment by GhostTyper** [comment]
Are LSTM / RNN supported meanwhile?

**Comment by harishsk** [comment]
Sorry, there is no support for LSTM / RNN either as of yet.

**Comment by kerohero** [comment]
Are  LSTM / RNN supported now?
