### ISSUE TITLE
Cross-Validation experiment needs more parameters and info

### ISSUE THREAD

**Issue by AleMiguelMicrosoft** [dotnet/machinelearning#1492]
When defining a cross validating experiment, I'd like to be able to define the proportion of records in the input set that are used in training vs testing. A common practice is specifying the % of records that need to go in the training set vs the testing set. Then use a random method of picking indexes from the data frame to form the training set based on the percentage defined before. And create a disjoint set (all indexes not picked during the first sweep) for testing.

In addition, the output of cross validation should show the size of the training set & fold sets after run.

**Comment by artidoro** [comment]
Could you be more specific on where this functionality is missing? If possible, could you give an code example of what you are looking for?

**Comment by AleMiguelMicrosoft** [comment]
@artidoro this makes sense. Please close the issue. But consider using your explanation for documentation. Thank you.
