### ISSUE TITLE
Final interface of Schema

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#1500]
As we have agreed on the API reviews, we will make the following modifications to `Schema`:
- Make it an `ICollection<Schema.Column>`
- Expand `Column` class to contain 2 fields: `IsHidden` and `Index`.
- Remove all methods except those exposed by collections, `this` accessors and `GetColumnOrNull`.
- Make constructors internal. Create a `SchemaBuilder` (in a different namespace `Microsoft.ML.Schema`) that would be responsible to building the schema. 
  - This is to make it more obvious that columns are NOT reused by different schemas.
- Move `Schema.Metadata.Builder` into a separate class `MetadataBuilder` in namespace `Microsoft.ML.Schema`.
- Finally, probably rename to `DataSchema`

**Comment by TomFinley** [comment]
Pursuant to [API review notes](https://github.com/dotnet/apireviews/pull/74/files#diff-8b410ccce45654bbddc866aafa3eec50R10), this `Column` structure should probably be a struct.

**Comment by sfilipi** [comment]
The only part that remains in this, is cleaning up usages of TryGetColumnIndex; which is not user-facing anymore; and renaming Schema to DataSchema.

**Comment by sfilipi** [comment]
All the work for this is done. 
The only thing left atm, the renaming, is covered in #2297.
