### ISSUE TITLE
LpGcNormAndWhiteningWorkout test fails only on VSTS Hosted macOS

### ISSUE THREAD

**Issue by montebhoover** [dotnet/machinelearning#1506]
### Issue

The test [LpGcNormAndWhiteningWorkout](https://github.com/dotnet/machinelearning/blob/c2b5e76c699b740e874a9db218828296a23b2ad8/test/Microsoft.ML.Tests/Transformers/NormalizerTests.cs#L123) is failing on VSTS Hosted Mac build agents, but not on DotNetCore build agents or any local Mac machines.  This currently prevents us from being able to switch to Hosted Mac agents which we want to do.

This comes out of PR #1240.

The test is failing inside WhiteningTransform.cs TrainModels() with ` System.InvalidOperationException : Invalid arguments to LAPACK gesvd, error: -6`.  This is due to `Mkl.Svd` returning -6 and we expected that it would return 0.

@TomFinley do you have any insights into why we might get this result from MKL? 

### Source code / logs
From https://dnceng.visualstudio.com/public/_build/results?buildId=38033&view=logs:

```
Failed   Microsoft.ML.Tests.Transformers.NormalizerTests.LpGcNormAndWhiteningWorkout
Error Message:
 System.InvalidOperationException : Invalid arguments to LAPACK gesvd, error: -6
Stack Trace:
   at Microsoft.ML.Transforms.WhiteningTransform.TrainModels(Single[][] columnData, Int32[] rowCounts, IChannel ch) in /Users/vsts/agent/2.141.1/work/1/s/src/Microsoft.ML.Transforms/WhiteningTransform.cs:line 327
   at Microsoft.ML.Transforms.WhiteningTransform..ctor(IHostEnvironment env, Arguments args, IDataView input) in /Users/vsts/agent/2.141.1/work/1/s/src/Microsoft.ML.Transforms/WhiteningTransform.cs:line 253
   at Microsoft.ML.Transforms.Whitening.Fit(IDataView input) in /Users/vsts/agent/2.141.1/work/1/s/src/Microsoft.ML.Transforms/WrappedWhiteningTransformer.cs:line 89
   at Microsoft.ML.Runtime.Data.TrainedWrapperEstimatorBase.GetOutputSchema(SchemaShape inputSchema) in /Users/vsts/agent/2.141.1/work/1/s/src/Microsoft.ML.Data/DataLoadSave/TransformWrapper.cs:line 163
   at Microsoft.ML.Runtime.Data.EstimatorChain`1.GetOutputSchema(SchemaShape inputSchema) in /Users/vsts/agent/2.141.1/work/1/s/src/Microsoft.ML.Data/DataLoadSave/EstimatorChain.cs:line 67
   at Microsoft.ML.Runtime.RunTests.TestDataPipeBase.TestEstimatorCore(IEstimator`1 estimator, IDataView validFitInput, IDataView validTransformInput, IDataView invalidInput, IDataView validForFitNotValidForTransformInput) in /Users/vsts/agent/2.141.1/work/1/s/test/Microsoft.ML.TestFramework/DataPipe/TestDataPipeBase.cs:line 79
   at Microsoft.ML.Tests.Transformers.NormalizerTests.LpGcNormAndWhiteningWorkout() in /Users/vsts/agent/2.141.1/work/1/s/test/Microsoft.ML.Tests/Transformers/NormalizerTests.cs:line 142
Standard Output Messages:
 Test LpGcNormAndWhiteningWorkout: aborted: passed
```

From [WhiteningTransform.cs, TrainModels()](https://github.com/dotnet/machinelearning/blob/d68388a1c9994a5b429b194b64b2b0782834cb78/src/Microsoft.ML.Transforms/WhiteningTransform.cs#L322)
```
ch.Info("Computing SVD...");
var eigValues = new Float[ccol]; // Eigenvalues.
var unconv = new Float[ccol]; // Superdiagonal unconverged values (if any). Not used but seems to be required by MKL.
// After the next call, values in U will be ovewritten by left eigenvectors.
// Each column in U will be an eigenvector.
int r = Mkl.Svd(Layout, Mkl.SvdJob.MinOvr, Mkl.SvdJob.None,
    ccol, ccol, u, ccol, eigValues, null, ccol, null, ccol, unconv);
ch.Assert(r == 0);
if (r > 0)
    throw ch.Except("SVD did not converge.");
if (r < 0)
    throw ch.Except("Invalid arguments to LAPACK gesvd, error: {0}", r);
```

### System information

* VSTS Hosted macOS agent: **fails**
```
VSTS Version: 2.141.1
BenchmarkDotNet=v0.11.1, OS=macOS High Sierra 10.13.6 (17G65) [Darwin 17.7.0]
Intel Xeon CPU E5-1650 v2 3.50GHz (Max: 3.34GHz), 2 CPU, 4 logical and 4 physical cores
.NET Core SDK=2.1.401
  [Host] : .NET Core 2.1.3 (CoreCLR 4.6.26725.06, CoreFX 4.6.26725.05), 64bit RyuJIT
  Dry    : .NET Core 2.1.3 (CoreCLR 4.6.26725.06, CoreFX 4.6.26725.05), 64bit RyuJIT
```

* DotNetCore macOS agent: **passes**
```
VSTS Version: 2.142.1
BenchmarkDotNet=v0.11.1, OS=macOS Sierra 10.12.6 (16G1510) [Darwin 16.7.0]
Intel Core i7-4578U CPU 3.00GHz (Haswell), 1 CPU, 4 logical and 2 physical cores
.NET Core SDK=2.1.401
  [Host] : .NET Core 2.1.3 (CoreCLR 4.6.26725.06, CoreFX 4.6.26725.05), 64bit RyuJIT
  Dry    : .NET Core 2.1.3 (CoreCLR 4.6.26725.06, CoreFX 4.6.26725.05), 64bit RyuJIT
```

* Monte's Macbook Pro: **passes**
```
VSTS Version: <N/A>
BenchmarkDotNet= <N/A> OS=macOS Sierra 10.13.1
Intel Core i7 CPU 2.9GHz, 1 CPU, 4 physical cores
.NET Core SDK=2.1.401
```

* Monte's Mac Mini: **passes**
```
VSTS Version: <N/A>
BenchmarkDotNet= <N/A> OS=macOS Sierra 10.13.6
Intel Core i5 CPU 2.8GHz, 1 CPU, 2 physical cores
.NET Core SDK=2.1.401
```

Let me know if there are more details on the hardware that would be helpful.

**Comment by Ivanidzo4ka** [comment]
So I’m looking into failure of that whitening test
https://dnceng.visualstudio.com/public/_build/results?buildId=38622&view=ms.vss-test-web.test-result-details

Invalid arguments to LAPACK gesvd, error: -6

Let’s look on definition of error:
https://software.intel.com/en-us/node/520973

If info = -i, parameter i had an illegal value.

I think 6th parameter is lda.

https://github.com/dotnet/machinelearning/blob/d68388a1c9994a5b429b194b64b2b0782834cb78/src/Microsoft.ML.Transforms/WhiteningTransform.cs#L345
looking into our code I think it would be nice to implement all asserts on parameters we send.


matrix_layout | Specifies whether matrix   storage layout is row major (LAPACK_ROW_MAJOR) or column major (LAPACK_COL_MAJOR).
-- | --
n | The number of linear   equations, that is, the order of the matrix A; n≥ 0.
nrhs | The number of right-hand   sides, that is, the number of columns of the matrix B; nrhs≥ 0.
a | The array a(size   max(1, lda*n)) contains the n-by-n coefficient   matrix A.
b | The array bof   size max(1, ldb*nrhs) for column major layout and max(1, ldb*n)   for row major layout contains the n-by-nrhs matrix   of right hand side matrix B.
lda | The leading dimension of   the array a; lda≥ max(1, n).
ldb | The leading dimension of   the array b; ldb≥ max(1, n)   for column major layout and ldb≥nrhs for   row major layout.
ldx | The leading dimension of   the array x; ldx≥ max(1, n)   for column major layout and ldx≥nrhs for   row major layout.

**Comment by Ivanidzo4ka** [comment]
Can we do following:
Print out into console content of matrix u after we done with Gemm routine.
Print out all other parameters we pass to Svd routine.

This way you at least can check what results you get on your build machine.

I have high faith what problem actually in Gemm routine, and since it's happening only on new hosted environment, it's probably related to dependencies.  (we do use cblas routines in symsgd, but it's doti which stated as BLAS level 1 routine, and Gemm is level 3)
