### ISSUE TITLE
ONNX dlls appearing in VS at the project's root folder

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning#1514]
Right after compiling a sample which is scoring with an ONNX model, a bunch of "low level" DLLs related to ONNX appear in VS at the project's root folder.

Is there a way not to show all these .DLLs here?
(Ignore the list of image files, of course..)

![image](https://user-images.githubusercontent.com/1712635/47931063-fc077380-de8a-11e8-8c2b-d1a02b5e8d09.png)

**Comment by chris-lauren** [comment]
@jignparm please look into this. note the dlls get copied to main project folder witih "copy if newer" instead of just getting copied to the bin output folder
![onnxtransformdlls](https://user-images.githubusercontent.com/27871925/47936689-bacb8f80-de9b-11e8-9a3d-c652b7cae3a5.gif)

**Comment by jignparm** [comment]
Thanks for the video. The targets file for the nuget will need to updated so that the dlls do not show up in the windows explorer window. We'll add this fix to the upcoming onnxruntime library (and in ml.scoring as well).
