### ISSUE TITLE
Minor consistency issue: MLContext.MulticlassClassification has first "c" letter as lowercase, but MultiClassClassifierEvaluator.Result has it as uppercase

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning#1525]
Minor consistency issue, this class has first "c" as lowercase:
MLContext.Multi**c**lassClassification.Evaluate()

Then, the Evaluate method returns the following type which has the first "C" as uppercase:

Multi**C**lassClassifierEvaluator.Result

**Comment by Ivanidzo4ka** [comment]
I don't think this is a case anymore.
