### ISSUE TITLE
IDataView Cleanup: IDataView as an abstract class, not interface

### ISSUE THREAD

**Issue by TomFinley** [dotnet/machinelearning#1528]
Let us not have `IDataView` as an interface, but instead just an abstract base class `DataView`. Then instead of implementing this interface, we descend from the base class. This is in line with .NET guidelines preferring abstract classes to interfaces where possible and reasonable.

At least internal to ML.NET things that are `IDataView` are primarily that (or some subcase of that).

For various reason this *may* have to wait until the `IDataTransform` conversion into the `IEstimator`/`ITransformer` idioms is complete, but we can investigate doing it now, or even temporarily making *that* itself a base class. Nonetheless it woudl be easiest done once `IDataTransform` is disentangled from many of the existing `IDataView` implementations.

/cc @Zruty0 @shauheen @terrajobst

**Comment by wschin** [comment]
@eerhardt, do we still need this change?

**Comment by eerhardt** [comment]
I'm not entirely sure if we should make `IDataView` an abstract base class or an interface.

With #1860, we plan on extracting the type out of ML.NET to make it available for more libraries to implement and consume. If we made it a base class, I'm afraid other potential producing libraries (Apache Arrow, Spark, etc.) wouldn't want to "burn" their base class by inheriting from `abstract class DataView`, and instead have adapters like `ToDataView()`.

In my opinion, it feels like `IDataView` should be an interface, just like `ICollection` or `IReadOnlyList<T>`.

**Comment by TomFinley** [comment]
FYI we have now pretty much settled on `IDataView` being appropriately an interface.
