### ISSUE TITLE
IDataView Cleanup: Rename `UInt128`

### ISSUE THREAD

**Issue by TomFinley** [dotnet/machinelearning#1534]
The row cursor IDs serve a purpose as described here.

https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Core/Data/ICursor.md#getidgetter

These IDs are represented as 128-bit numbers. Correspondingly, I named them `UInt128` back in the long vanished past. However, this is a troubling name: this first of all conflicts with any name .NET would use in the future to represent 128-bit unsigned integers (assuming they ever did so), which is reason enough not to use it. But even without this reason, this type just doesn't *quite* act like a number.

On the other hand, I am not certain what a good name would be. Something like `RowId`, `RecordId`, or something like that?

/cc @Zruty0 @shauheen @terrajobst

**Comment by Zruty0** [comment]
I like `RowId` better. Or even `UniqueId`.

**Comment by TomFinley** [comment]
I like `RowId`. `UniqueId` is bad since they are only probabilistically unique, and people might get confused between that and GUIDs (which go further and are globally unique), which this definitely is not.
