### ISSUE TITLE
Please support autodifferentiation

### ISSUE THREAD

**Issue by AceHack** [dotnet/machinelearning#1541]
This would be a great feature to have.

**Comment by artidoro** [comment]
Hello @AceHack could you give us some example scenarios that you are considering, and what exactly you think would be useful in terms of autodifferentiation?
Note that ML.NET already has tensorflow bindings which allow you to train and score tensorflow models directly from the library.

**Comment by codemzs** [comment]
not on our roapmap for near future, also please provide details as artidoro has requested. closing but feel free to reopen.
