### ISSUE TITLE
TensorFlow transform would throw on non-vector input

### ISSUE THREAD

**Issue by TomFinley** [dotnet/machinelearning#1542]
In the process of working on #1533, I found the following code in the tensorflow transform.

https://github.com/dotnet/machinelearning/blob/73762a8d8f23d27f3c15b4382c0bc374934ccad5/src/Microsoft.ML.TensorFlow/TensorflowTransform.cs#L834-L844

Consider the above code. We have at line 834 this assignment to a boolean value depending on whether the input is of type vector, or not. This strongly suggests that the transform can accomodate non-vector types. However at lines 841 and 844, we have this `type.AsVector.DimCount`. Now, `AsVector` will be `null` in the case where the type is not a vector of course, so this would throw a null reference exception if we were to ever feed this transform a non-vector value.

So, there's something wrong here. Unfortunately the intent of what the author *meant* to write is somewhat hidden from me, so perhaps whoever wrote this code could check this out. Maybe even write a test to test this condition.

**Comment by najeeb-kazmi** [comment]
@abgoswam @yaeldekel Can you provide details on the original intent of this code?
