### ISSUE TITLE
Please support Keras

### ISSUE THREAD

**Issue by AceHack** [dotnet/machinelearning#1562]
Tensor flow is really nice but Keras support would be great!!  We would then get Theano and CNTK.

**Comment by najeeb-kazmi** [comment]
Hi @AceHack, let me move it to triage and out triage team can decide if this is something we want to invest in before v1.0 or if it should be moved to our backlog. I agree having Keras support in ML.NET would be nice, as would PyTorch.

In the meantime, it is currently possible to score ONNX models in ML.NET, so models from any framework that is supported in ONNX can be converted to ONNX and used in ML.NET pipelines.

**Comment by codemzs** [comment]
this is not on our roadmap. thanks.

**Comment by AceHack** [comment]
I am very sorry to hear that, it would really be a very useful addition as @najeeb-kazmi pointed out as well.

**Comment by codemzs** [comment]
Yep. I’ll make a note. Thanks! We do plan to bring in tensorflow training support very soon.
