### ISSUE TITLE
Organize the folder structure

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#1581]
We should make sure that the namespaces and folders are matching each other, especially for public components.

- All our assemblies should have DefaultNamespace be equal to `Microsoft.ML`
- All other public types should be located in files that match their namespace.

@TomFinley do you want to comment?

**Comment by eerhardt** [comment]
This work isn't changing any public API, it is just rearranging how our files live on disk in our repo. Removing it from `Project 13`.

**Comment by codemzs** [comment]
We plan to organize the folders and create layering where components like automl, cli will not be in the same folders as core components. That work item will entail this kind of folder structure. closing this.
