### ISSUE TITLE
TensorFlow Integration

### ISSUE THREAD

**Issue by Sorrien** [dotnet/machinelearning#159]
I thought it might be beneficial to add an issue just for the integration of TensorFlow into ML.Net to allow for discussions specific to this topic. I would also like to point out that there is an existing C# wrapper called TensorFlowSharp that might be good to look at as a point of reference for using TensorFlow in ML.Net. TensforFlowSharp repo: https://github.com/migueldeicaza/TensorFlowSharp The project is a wrapper around the TensorFlow C library, and works with C# and F#.

**Comment by GalOshri** [comment]
Thanks for adding this! 

What kind of scenarios are you looking to enable first? Is evaluating TensorFlow models the top priority, or also training them through ML.NET?

**Comment by Sorrien** [comment]
I would like to be able to work from start to finish in .Net utilizing various neural networks. If evaluating models comes first that would be fine too, because I could still use models trained by Google to do some pretty interesting things. My ultimate goal is to see C# become a first class machine learning language like Python.

**Comment by markusweimer** [comment]
> My ultimate goal is to see C# become a first class machine learning language like Python.

You came to the right project :)

**Comment by lionel-mani** [comment]
I am a fresher working in cap Gemini India on .net, I am more fascinated
towards machine learning. Could you please suggest me the right part to
learn and to join with you

**Comment by lionel-mani** [comment]
Kindly guide me with the right path sir.

Thanks in advance

**Comment by Ivanidzo4ka** [comment]
DRI RESPONSE: Starting from 0.6 version we support TensorFlow and Onnx. So I'm closing this issue.
