### ISSUE TITLE
Sentiment Analysis on Uwp - MissingMethodException

### ISSUE THREAD

**Issue by neven10** [dotnet/machinelearning#1595]
### System information

- **OS version/distro**: Windows 10 UWP app,   ML 0.7.0
- **.NET Version (eg., dotnet --info)**:  Net standard / Targeting min Fall Creator Update

### Issue

- **What did you do?**
Was trying to run  binary classification example on Uwp.

- **What happened?**

System.MissingMethodException: Method not found: 'System.ComponentModel.Composition.Hosting.CompositionContainer Microsoft.ML.Runtime.IHostEnvironment.GetCompositionContainer()'.

It works fine with  .Net Core Console .

**Comment by Zruty0** [comment]
@eerhardt I assume this has to do with the fact we started using MEF 1.0 in ML.NET? Are these UWP apps not compatible with MEF?

**Comment by eerhardt** [comment]
I've opened https://github.com/dotnet/corefx/issues/33434 for this issue. It appears to either be an issue with the NuGet package, or UWP itself.
