### ISSUE TITLE
Provide Scenario Sample Code for All Scenarios

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/machinelearning#16]
_From @KrzysztofCwalina on Apr 16, 2018, 9:07 AM PDT_

Currently, we have only one scenario code sample (house price prediction). We should have top 5 scenario samples.

**Comment by shauheen** [comment]
@KrzysztofCwalina is this issue still valid? We also have #198 to address Samples.

**Comment by KrzysztofCwalina** [comment]
No, I think we now have a critical mass of intro samples. At some point we might have more, but this issue was about covering the basics.
