### ISSUE TITLE
Make schema comprehension aware of images

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#1610]
Image columns are backed by `Bitmap` objects under the hood. However, our standard schema comprehension is not capable of turning `Bitmap` fields into data view columns and vice versa.

We want to be able to add this capability, but without making Core assembly aware of the image type. This potentially calls for another application of MEF: being able to inject custom 'peek/poke generators' for schema comprehension. 

@TomFinley , do you think this is even a reasonable idea?

@CESARDELATORRE ran into this need for some of the demos they were building. 
cc @yaeldekel

**Comment by shmoradims** [comment]
ping @TomFinley @yaeldekel

**Comment by codemzs** [comment]
I believe @wschin 's change has fixed this issue by making images load in-memory. closing but if I'm wrong please reopen.
