### ISSUE TITLE
TextLoader should have only one constructor, that doesn't take Arguments as a parameter

### ISSUE THREAD

**Issue by markusweimer** [dotnet/machinelearning#1611]
`TextLoader` needs to hide the constructor that has `Arguments`, and also expose the `HasHeader` and `SeparatorChars` to be non-advanced parameters.

-- old description --
`TextLoader` presently accepts a parameter called `column` for the array of columns to read. That seems odd, given that almost always, multiple columns are passed. Hence, it would be more natural to call that parameter `columns`.

**Comment by eerhardt** [comment]
See https://github.com/dotnet/apireviews/pull/81 for some notes from the API design discussion on this API. In the end, we decided to have 2 constructor/factories:

1. With the simple/common options as direct parameters.
2. If a component needed to have public "advanced" options, have another constructor/factory that took only the Options instance.
