### ISSUE TITLE
Rocket AutoML engine stops very early

### ISSUE THREAD

**Issue by daholste** [dotnet/machinelearning#1615]
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: .NET Core 2.1

### Issue
The Rocket AutoML engine stops very early for numerical datasets. For a numerical binary classification problem, the engine always stops after 14 iterations.
The Rocket engine makes it successfully thru its first stage, running all 12 landmark algorithms. Then, the engine makes it into its second stage, and runs thru one batch of the top 2 two algorithms. After that, the engine stops, never making it to stage 3, 4, etc.

**Comment by najeeb-kazmi** [comment]
This is a long standing bug with Rocket. It runs with defaults only and silently stops, after exhausting the 14 binary classification learners we have. Do you see the same behavior with UniformRandom?

**Comment by daholste** [comment]
This is good to know, thanks!
Unfortunately, I rather not use UniformRandom engine, b/c am trying to Bayesian sweep

**Comment by rogancarr** [comment]
Closing: `Microsoft.ML.PipelineInference` has been removed from the repository.
