### ISSUE TITLE
How to get data from IDataView

### ISSUE THREAD

**Issue by nsulikowski** [dotnet/machinelearning#1617]
How can I get data from IDataView without a class for the record?
For instance convert IDataView to object[,] just by querying the Schema
Thanks,
Nestor

**Comment by artidoro** [comment]
If I understand your question, you are looking for ways to inspect IDataView. There are some examples of how to do that in the ml.net cookbook: https://github.com/dotnet/machinelearning/blob/899ddc434b6c0aca72e86641b55730a1382e23c5/docs/code/MlNetCookBook.md#how-do-i-look-at-the-intermediate-data

Does that answer your question?

**Comment by nsulikowski** [comment]
Ultimately that cookbook link needs the class InspectedRow to query IDataView.
I'm actually wondering if there is a way to query IDataView without a defined class (like InspectedRow).

**Comment by artidoro** [comment]
We recently added visualization for debugging. So you can inspect the IDataView in the VS debugger.

You can also use GetColumn as shown in the cookbook link. You will need to know what the column type is however.

What scenario were you thinking about?

**Comment by nsulikowskijeff** [comment]
I was trying to convert IDataView into some kind of HTML view, to understand the structure.
I looked at the way you wrote the VS debugger classes.. and that helped. It's not easy to do without knowing the types at compile time!

**Comment by shmoradims** [comment]
This is a the new debugging feature that can help:
https://github.com/dotnet/machinelearning/blob/master/docs/code/MlNetCookBook.md#how-do-i-debug-my-experiment-or-preview-my-pipeline

Did this help?

**Comment by nsulikowski** [comment]
Yes. Thanks. 
It could be useful to have a non-generic method that returns objects....

object data.GetColumn(mlContext, "AllFeatures")

**Comment by nsulikowski** [comment]
Yes. Thanks.

**Comment by sfilipi** [comment]
Closing the issue, based on the last answer from @nsulikowski.
