### ISSUE TITLE
Normalization option, FixZero, is not available in high-level APIs

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#1634]
When I perform minmax normalization on dense datasets, I like to turn off "fixzero". This option is not available in the high-level APIs, e.g. `mlContext.Transforms.Normalize()`.

To use this, you need to go back and create `AffineColumn` and `MinMaxArguments` objects and use the old-style `Create` API:
```
var column = new NormalizeTransform.AffineColumn() { Name = "Index0", FixZero = false };
var minMaxArgs = new NormalizeTransform.MinMaxArguments() { FixZero = false, Column = new NormalizeTransform.AffineColumn[1] { column } };
IDataView transform = NormalizeTransform.Create(mlContext, minMaxArgs, loader);
```

I think these old-style APIs are very confusing to use, especially since there are two ways to specify `FixZero`, and it's unclear which one is used and if there is precedence between them.

**Comment by Ivanidzo4ka** [comment]
I believe you can do something like this:
`mlContext.Transforms.Normalize(new Transforms.Normalizers.NormalizingEstimator.MinMaxColumn("Features", fixZero:false);`

Do you want me to update cookbook example?

**Comment by Ivanidzo4ka** [comment]
https://github.com/dotnet/machinelearning/blob/master/docs/code/MlNetCookBook.md#what-is-normalization-and-why-do-i-need-to-care contain examples of how to turn on/turn off fixZero so I'm closing this issue.
