### ISSUE TITLE
Recovering ITransformers from Predictor Objects

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#1636]
Oftentimes it is necessary to have an actual object of a predictor, such as a `RegressionGAMPredictor` or `LinearRegressionPredictor` to access methods particular to the predictor. However, it is a bit cumbersome to get back to the `ITransformer` interface. One must manually create a `RegressionPredictionTransformer` like so:

```
var linearTransformer = new RegressionPredictionTransformer<LinearRegressionPredictor>(mlContext, linearPredictor, trainSet.Schema, "Features");
```

I'd like to see all the predictor objects support a method like `AsTransformer()` to return an `ITransformer`. It seems like the predictor objects have enough information to automate the process, and it would make the APIs much easier to use.

**Comment by Zruty0** [comment]
I don't think the predictor objects have enough information to do it.
Specifically, they don't know the feature column mapping, the schema of the train set and the scorer settings (the latter one is irrelevance for regression, but relevant for classification).
