### ISSUE TITLE
Precedence between main arguments and advancedSettings

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#1639]
In some learnings, for example [GAM](https://github.com/dotnet/machinelearning/blob/8a45f37cf87e380a93146d08acac19f215648f9a/src/Microsoft.ML.FastTree/GamTrainer.cs#L135), the [APIs specify a set of default values](https://github.com/dotnet/machinelearning/blob/8a45f37cf87e380a93146d08acac19f215648f9a/src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs#L110), with an optional advanced settings argument.

Oftentimes, as is the case with GAMs, this means that there are two ways to specify the value for a parameter -- as a main line item, or in the advanced settings. In the GAM code, the main line items are applied, followed by the advanced settings. There is no normalization that occurs., meaning that options in the advanced settings can override options set in the main line items.

Is there supposed to be precedence here, or is there any way to make the APIs simpler so that there is only one way to specify a parameter? I'd love to hear people's thoughts on this.

I don't know of any bugs caused by this, but this seems like the kind of thing that can cause unintentional behavior.

**Comment by TomFinley** [comment]
Hi @rogancarr , sorry this somehow got missed. I ran across this issue while searching for another issue. FYI we are trying to fix this in #1798, so it should be fixed for v1, I hope. (As linked in this issue, the problem you note was also feedback we received from .NET team.)

**Comment by rogancarr** [comment]
Hi @TomFinley ! Great. I'll close this issue for now, then if it's being tracked elsewhere.
