### ISSUE TITLE
Tensorflow Transform Doesn't Accept Key-typed Labels

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#1649]
In the current Tensorflow tests, I tried changing its label type from I8 to U4[0:9] but then I couldn't retrain Tensorflow anymore.

**Comment by shmoradims** [comment]
@wschin could you please provide more detailed repro code? Which test exactly?

**Comment by codemzs** [comment]
closing due to lack of details, please feel free to reopen.
