### ISSUE TITLE
RandomUtils.NextFloat(this Random) can return exactly 1

### ISSUE THREAD

**Issue by skyoxZ** [dotnet/machinelearning#166]
https://github.com/dotnet/machinelearning/blob/436700aadf615e7f05a22925476cc441c63a919d/src/Microsoft.ML.Core/Utilities/Random.cs#L52

It seems `RandomUtils.NextFloat(this Random)` has a possibility of returning exactly 1.

**Comment by TomFinley** [comment]
Thanks @skyoxZ !

To whoever works on this, I'd prefer to address this problem just by removing this extension method and the `IRandom` extension method above. Ideally we could perhaps get rid of `RandomUtils` altogether; I don't see that it serves any purpose. (Indeed the offending method is not used anywhere, near as I can tell. I'd think anyone outside utilizing this should use something else.)
