### ISSUE TITLE
AutoML seeks to minimize RSquared, instead of maximize it

### ISSUE THREAD

**Issue by daholste** [dotnet/machinelearning#1665]
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: .NET Core 2.1

### Issue

AutoML seeks to minimize RSquared, instead of maximize it --
https://github.com/dotnet/machinelearning/blob/e0906608ca0d37ad0c10ba647e83b45990afde43/src/Microsoft.ML.PipelineInference/PipelineSweeperSupportedMetrics.cs#L84

**Comment by rogancarr** [comment]
Closing: `Microsoft.ML.PipelineInference` has been removed from `ML.NET`
