### ISSUE TITLE
Low discrepancy random 

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning#1672]
Low discrepancy random sweeper (LDRand) should be moved to the external repo. 

LDRand was held back in the internal repo due to a dependence on the MKL library. This issue has been resolved, and I think we are now able to move this code.

**Comment by glebuk** [comment]
@justinormont,
Please update with:  1. Why is this needed.  2. Do it need to move to ML.NET or another repo?

**Comment by codemzs** [comment]
I don't see this in the current repo. please provide more details but closing for now.
