### ISSUE TITLE
SysRandom.NextSigned()

### ISSUE THREAD

**Issue by skyoxZ** [dotnet/machinelearning#169]
https://github.com/dotnet/machinelearning/blob/436700aadf615e7f05a22925476cc441c63a919d/src/Microsoft.ML.Core/Utilities/Random.cs#L154

Should be `return _rnd.Next(int.MinValue, int.MaxValue);`

**Comment by TomFinley** [comment]
Oh that is nasty. Thanks @skyoxZ .

Fortunately, at least in this codebase, it's used in exactly one place:
https://github.com/dotnet/machinelearning/blob/c023727b76970ab913ec1ce38276508835c17bcf/src/Microsoft.ML.Data/Transforms/ShuffleTransform.cs#L99
That is, it derive a random seed for some other PRNG. If I think about how that class is used the effects will be limited, but we should definitely fix it.

**Comment by Ivanidzo4ka** [comment]
Address in PR #172
