### ISSUE TITLE
Remove "Runtime" from all namespace reference, sort namespaces as per .net convention and enforce the same.

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#1697]
Remove "Runtime" from all namespace reference, sort namespaces as per .net convention listed below and enforce the same.

**SA1210:** Using directives must be ordered alphabetically by namespace.
**SA1208:** System using directives must be placed before other using directives.

**Comment by codemzs** [comment]
@TomFinley As part of this change we will be sorting and removing unused namespaces. For sorting is it ok if we list System.* namespaces first in sorted order followed by remaining namespaces also in sorted order.

**Comment by justinormont** [comment]
I created a sub-issue (#1964) to update the example code.

**Comment by codemzs** [comment]
Thanks @justinormont !

**Comment by glebuk** [comment]
@codemzs please verify that this is complete and close if it is.

**Comment by codemzs** [comment]
This task is complete and checked-in as part of 0.9 release. We decided during API scrum to separate out moving of namespaces into its own issue since it will require feedback from other stakeholders. I have opened issue #2075 that tracks the moving of namespaces.
