### ISSUE TITLE
Final public API for predictor classes

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#1698]
1. All predictor classes should be named `SoAndSoModelParameters` (like `KMeansModelParameters`, `LinearBinaryModelParameters` etc. 

2. Strive to remove unnecessary interfaces from the public API: thinks like `IPredictor`, `IPredictorProducing<float>` etc. should not be public. 

3. Review the public surface of `ModelParameters` to enable ONLY parameter introspection. For example:
  - `KMeans` should only expose centroid coordinates.
  - `Linear` should only expose weights/biases.

4. If possible, try to add public constructors. For example:
  - Make it possible to create `KMeansModelParameters` from centroid coordinates
  - Make it possible to create `LinearBinaryModelParameters` from weights and biases

**Comment by glebuk** [comment]
@sfilipi ensure that it's all done and close.
