### ISSUE TITLE
Make members of Data and Transforms assemblies internal

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#1704]
Similar to #1602, let's make as many members of these assemblies internal as possible

**Comment by eerhardt** [comment]
@TomFinley - what's left to do on this issue?  I think we are done with the `Data` assembly, right? Have we gone through the `Transforms` assembly?

**Comment by sfilipi** [comment]
The only things that I could spot are:

Microsoft.ML.Data:

* Make [NormalizeOption ](https://github.com/dotnet/machinelearning/blob/b861b5d64841cbe0f2c866ee7586872aac450a51/src/Microsoft.ML.Data/Commands/TrainCommand.cs#L28) internal. 
* Internalize [MetricColumn ](https://github.com/dotnet/machinelearning/blob/b861b5d64841cbe0f2c866ee7586872aac450a51/src/Microsoft.ML.Data/Commands/EvaluateCommand.cs#L30). 
* Can [TransformerScope ](https://github.com/dotnet/machinelearning/blob/e2464f606c69357898572aac8e4d8d3c1451c92f/src/Microsoft.ML.Data/DataLoadSave/TransformerChain.cs#L29)be internalized. I believe StaticPipe uses it though.. 
* Should OneToOneTransformerBase and RowToRowTransformerBase be in ML.Data or ML.Transforms namespace? I think they can stay in Data. 

Microsoft.ML.Transforms does not contain anything besides transformers and estimators, and they are being scrubbed on separate issues. 

/cc @TomFinley @Ivanidzo4ka

**Comment by eerhardt** [comment]
> Can TransformerScope be internalized. I believe StaticPipe uses it though..

I don't think so. It is used in the `Append` method and in the `GetModelFor` method on `TransformerChain`.

https://github.com/dotnet/machinelearning/blob/b861b5d64841cbe0f2c866ee7586872aac450a51/src/Microsoft.ML.Data/DataLoadSave/EstimatorChain.cs#L88-L90

https://github.com/dotnet/machinelearning/blob/e2464f606c69357898572aac8e4d8d3c1451c92f/src/Microsoft.ML.Data/DataLoadSave/TransformerChain.cs#L146
