### ISSUE TITLE
Final interface of SchemaShape

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#1706]
1. Move to `Microsoft.ML.Data`
2. `internal-best-friend` all methods that are not accessing columns.
3. Make `SchemaShape` be a `IReadOnlyList<SchemaShape.Column>`
4. Add an accessor by name, and `GetColumnOrNull`, like `Schema` has.
5. Make `SchemaShape.Column` a `struct`.
6. Remove `SchemaException`.

**Comment by sfilipi** [comment]
3. Make SchemaShape be a IReadOnlyList<SchemaShape.Column>

Do you mean the Column[] Columns inside the SchemaShape should convert toIReadOnlyList<SchemaShape.Column> ?

**Comment by Zruty0** [comment]
No, I mean the class itself should be `IReadOnlyList<SchemaShape.Column>`. This is to be more parallel to `Schema` class, which it resembles.
