### ISSUE TITLE
Add MLContext.Data extensions for schema comprehension

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#1708]
- Move `AsEnumerable<T>` to `Microsoft.ML` (move AsEnumerable into an isolated file and make it an extension to MLContext). #2182.
- Move `AsCursorable<T>` to `Microsoft.ML.Data`: I'm not sure if it's ever useful, so let's at least get it out of people's faces. Maybe `internal-best-friend` it. Working item: #2182
- Add `MLContext.Data.ReadFromCollection<T>` (And make `env.CreateDataView` and `env.CreateStreamingDataView` internal. Their uses should be replaced with the new ReadFromCollection<T>.). The new signature of `ReadFromCollections<T>` should look like
```csharp
public static IDataView ReadFromTextFile<TInput>(this DataOperations catalog, IEnumerable<TInput> collection)
```
- Add `MLContext.Model.MakePredictionFunction` as an alternative to `model.MakePredictionFunction`. Maybe still turn it into `Create`? @TomFinley ? [Update]: it has been done in `ModelOperationsCatelog.cs`

**Comment by sfilipi** [comment]
@Zruty0 @TomFinley afa naming, is there a distinction between the Make and Create prefixes?

**Comment by Zruty0** [comment]
No. It's like tabs and spaces :)

**Comment by wschin** [comment]
What does it mean to move `AsEnumerable<T>` to `Microsoft.ML`? I know its namespace needs to be changed but which file it should move to? I have the same question to `AsCursorable<T>`.

**Comment by Zruty0** [comment]
#1761 suggests that we rename it to `CreatePredictionEngine`. I think the `PredictionFunction<T1, T2>` itself needs to go, and the underlying `PredictionEngine<T1, T2>` should be made public instead.

The other bullet points above still apply
