### ISSUE TITLE
Does ML.Net support KNN?

### ISSUE THREAD

**Issue by sharpwood** [dotnet/machinelearning#1712]
https://github.com/markdregan/K-Nearest-Neighbors-with-Dynamic-Time-Warping

I suggest adding the algorithm of this article to the function of time series.

**Comment by rogancarr** [comment]
Hi @sharpwood ,

Thanks for reaching out! We do not currently have an algorithm available for K-Nearest-Neighbors. I've added the KNN-with-dynamic-time-warping algorithm as a feature-request for time series.

**Comment by rogancarr** [comment]
(Leaving open until triaged.)

**Comment by shmoradims** [comment]
@rogancarr is the feature request on github? if so, could you please reference the issue here?

**Comment by rogancarr** [comment]
Sorry if that last post of mine wasn't clear. Let's treat this issue as the feature request.

**Comment by turowicz** [comment]
I would very much like to see this as we're trying to port our facial recognition system from python/dlib/opencv/scikit to c#/dotnet/ml.net/dlib/opencv.

**Comment by turowicz** [comment]
@rogancarr is it as simple as this?

https://msdn.microsoft.com/en-us/magazine/mt814421.aspx

**Comment by Nozziel** [comment]
Here is a sample dataset ["Predicting Check Ins"](https://www.kaggle.com/c/facebook-v-predicting-check-ins/data). It has 4 features, 8.9 million rows and 100,000 labels. 
KNN would be good for this dataset, 100k labels is hard on most of the currently supported multi-class algo's.

**Comment by codemzs** [comment]
not on our roadmap for near future.

**Comment by justinormont** [comment]
Possible faster implementation:
https://github.com/microsoft/SPTAG

We have an old PR for a brute-force implementation of KNN:  
https://github.com/dotnet/machinelearning/pull/1889 (Bruteforce implementation for KNN)

We could drop in SPTAG to augment the KNN, which will give us a nice speed boost.

**Comment by KristianHolsheimer** [comment]
If may ask, what is the reason that kNN is not on the road map? Is it not sexy enough?

IMO it's an absolute must-have for any ML library that supports classification.

Just a simple KD-tree based implementation should be enough for a minimal viable product.
