### ISSUE TITLE
How to use Feature selection 

### ISSUE THREAD

**Issue by Vijay27anand** [dotnet/machinelearning#1713]
I want to use FeatureSelectorByMutualInformation feature selection, can you please provide me a sample code snippet how to use it with a dataset,  i could not able find in the samples provided.

**Comment by shmoradims** [comment]
That transform is changed to MutualInformationFeatureSelector. The documentation for is not rendering properly. I've added issue #1725 to fix it.

**Comment by glebuk** [comment]
@Vijay27anand,
Thanks for reporting this issue!
Please track it via #1725 
closing.
