### ISSUE TITLE
Docs rendered incorrectly

### ISSUE THREAD

**Issue by shmoradims** [dotnet/machinelearning#1725]
These pages don't have correct docs rendered:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.selectfeatures.countselect?view=ml-dotnet
https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.selectfeatures.mutualinformationselect?view=ml-dotnet

It's rendering like this:
![image](https://user-images.githubusercontent.com/15950225/49046677-c3a53d80-f189-11e8-8218-d42580a46da7.png)

**Comment by TomFinley** [comment]
Hi @shmoradims , the PR where these things were added was literally committed yesterday #1683 , so it assuredly would not be in the documents compiled here which I think were for 0.7 (which was a month ago).

**Comment by glebuk** [comment]
@shmoradims, please verify if this has been fixed, then close

**Comment by shmoradims** [comment]
The documentation is saying ML.NET 0.9, but those pages I mentioned still look incorrect. 
@TomFinley is this malformed documentation on ml.net or do you think the rendering can't format it? This seem to be the only transform that's saying Microsoft.ML.Runtime.Entrypoints.TlcModule.

**Comment by shmoradims** [comment]
Solution is discussed in #2288.
Fixed by #2300.
