### ISSUE TITLE
Add Random Forest support

### ISSUE THREAD

**Issue by gilnahmias** [dotnet/machinelearning#1729]
To ease the transition from Azure ML Studio to ML.NET, please add an equivalent of https://docs.microsoft.com/en-us/azure/machine-learning/studio-module-reference/multiclass-decision-forest to ML.NET

**Comment by Ivanidzo4ka** [comment]
For DRI person we a talking about thing internally know as Gemini.
AFAIK these trees we provided by Microsoft Research, and they are not open sourced. Also internally we never saw them perform better than LightGBM or OVA + FastTree, so I'm not sure it's worth effort to bring them to ML.NET.

**Comment by sfilipi** [comment]
Checking on clearance to open source that trainer.

**Comment by dlong11** [comment]
@sfilipi Any update on this?  Just curious...

**Comment by justinormont** [comment]
I might recommend exposing our LightGBM's random forest -- tracking issue: https://github.com/dotnet/machinelearning/issues/1992

**Comment by michaelgsharp** [comment]
@briacht I think that @justinormont is right that we should expose LightGBM's one, #1992. You fine with us closing this issue and leaving it tracked there?

**Comment by briacht** [comment]
Sounds good to me!
