### ISSUE TITLE
F# api issues

### ISSUE THREAD

**Issue by Lanayx** [dotnet/machinelearning#1737]
Hi, wanted to point out the generic problems of "new" api from fsharp perspective.
First of all, what is really missing is the Pipeline itself, instead we see is context, set of objects and extensions.

Expected to see:
```
data
|> Clean Cleaners.RemoveRow
|> Normalize Normalizers.Median
|> Split Splitters.Random
|> Train Learners.BoostedDecisionTree
|> CrossValidate
|> Evaluate
```

Secondly, as most of logic is implemented as extension methods on interfaces, in fsharp we need to to unsafe double cast sometimes:
```
let dynamicPipeline =
        mlContext.Transforms.Categorical.OneHotEncoding("CategoricalFeatures", "CategoricalOneHot")
        :> IEstimator<CategoricalTransform>
        :?> IEstimator<ITransformer>
```

**Comment by sfilipi** [comment]
cc @CESARDELATORRE @Zruty0

**Comment by CESARDELATORRE** [comment]
cc  @dsyme @mariuszwojcik @kunjee17 
From an F# perspective, what are your thoughts about this issue raised by @Lanayx ?

Thanks,

**Comment by dsyme** [comment]
The first issue is not something we would do.  In general we do not expect .NET APIs to provide curried or pipeline-friendly versions of their functionality, nor indeed F#-specific APIs.  The F# programmer can should be able to work with the API well enough.

The second issue is however more interesting and I wasn't aware of it.  

@Lanayx I'd like to see a longer sample where this occurs and understand what we can do about it?  Could you provide a longer version for us?  Many thanks

**Comment by Lanayx** [comment]
@dsyme Thank you for your response, here is the repo with C# and F# code where this casts are required for compilation.
https://github.com/Lanayx/MlBootcamp2

My preferences are coming from AzureML which I find beautiful and convenient to use. The more ML.NET api is similar to it the better. Overall impression about "new" api is that "old" one easier to use and understand, I spent around 3-4 days just to understand how to use new api after knowing both AzureML and old one. So I'm not even sure if it is benefitial to write the wrapper around it or better to wait for the 3d version of api. Here is the list of some issues all coming from AzureML where I don't have them.

- You need to specify column names and internal data types which are not even documented and they are nullable
- You need to manually calculate column indexes
- You need to manually vectorize features
- There is still no such class as DataSet, even for inspecting data you need to select specific columns

**Comment by kunjee17** [comment]
@Lanayx I guess @mariuszwojcik already wrote a wrapper for this. You can find code for wrapper here https://github.com/dotnet/machinelearning-samples/blob/master/samples/fsharp/common/ModelBuilder.fs and implementation here https://github.com/dotnet/machinelearning-samples/blob/master/samples/fsharp/getting-started/Regression_TaxiFarePrediction/TaxiFarePrediction/TaxiFarePredictionConsoleApp/Program.fs#L55

if this may solve your issue. 

And yes discussion was going on some other issue page to refactor separate code to provide F# specific support but things on halt until ML.net API is not finalized

**Comment by Lanayx** [comment]
@kunjee17 Yes, it hides the two-casts issue into separate module, which is not part of the library. But even with this implementation you need to add hack `(|> Common.ConsoleHelper.downcastPipeline)` at the end

**Comment by muehlhaus** [comment]
For a recent bioinformatic project, we needed a thin API for a friendlier F# usage (nuget and fsi) around the ML.NET machine learning framework. Therefore, we separated the wrapper code from the machinelearning-samples and started FSharpML (https://github.com/CSBiology/FSharpML). Although still in an experimental phase, we plan to refine and complete it for our bioinformatic projects.  
Currently, we are porting the machinelearning-samples to get more familiar with the framework and demonstrate the usage of FSharpML. 
@dsyme If this is interesting as community project, we would be happy to host it wherever it is most useful.
@ML.NET-team: Thanks for this amazing project and your great work.

**Comment by Lanayx** [comment]
@muehlhaus As the issue starter, I want to thank you for this great initiative that I was unable to do on my own. [Your example](https://csbiology.github.io/FSharpML/) looks beautiful for me, I would like to see this project evolving

**Comment by kunjee17** [comment]
@muehlhaus things looks good in example. I guess @dsyme would be better judge if this project can be moved to fsprojects. cc/ @mariuszwojcik @CESARDELATORRE

**Comment by Lanayx** [comment]
@codemzs Can you please explain why this issue was closed? What is your official advice for F# developers?
