### ISSUE TITLE
Language improvements

### ISSUE THREAD

**Issue by PGTBoos** [dotnet/machinelearning#174]
I'm sorry to say but on every line i see PipeLine.Add
It sounds actually to me like the language isnt ready.
Like Basic code having line numbers, telling it to write a line number first.
as in :
30 Gosub 150

Just imagine psudo code from here below 
```
using ( ML.Net  ) new net.dataSource FlightData= 
{ 
 .DataSource.File.LoadCSV(@"C:\Data\flights.csv", tabs);
 .DataColumnsNormalize("1,2,3,4,8,9");
 .DataColum[4].type = .DataType.TimeDayLightSaving.12Hours
 .DataColum[8].type = .DataType.TimeSpan.Between.Minutes
 .DataSource.MySQL.Add(dburl, tabel, user ="test,password ="trythis", prompt = prompt.OnLoginFail);
 .DataSource.MySQL.removeNullEntries;
 .DataSource.MySQL[tabel].DataColumnsNormalize("7,8")
 .DataSource.MySQL.removeNonComplete;
 .DataSource.Http(http://airportlivedata/arrivals)
 .DataSource.HttpFilter ("Flight number","time",....etc);
  // .DataSource.StoreAll.File.Compressed(....

 //Or 
  Add.Using (ML.Datasources.SQL(dburl,tabel,user,pass) 
   { 
      .removeNullEntries
   }
 } 

ML.Network PredictFlights using FlightData
{
.predict =[1,4,7,8]
.Regression
.Layer[6].FeedBackLoop => Layer[1]
.AnalyzeLayer[4].Debug.DisplayHeatMap.RGB24 =>DumpToFileAsWell
}

FlightData.Train
FlightData.Request(input columns[]as new ML.userInput(columns[1,3,5,69,12])
```

[formatting added by @danmosemsft]

**Comment by danmosemsft** [comment]
If you're looking for a more "literate programming" experience - would it help if `LearningPipeline.Add()` returned the learning pipeline object instead of void?

**Comment by PGTBoos** [comment]
Well i think we shouldnt see "LearningPipelLine.", i'm thinking semantics. Perhaps .net needs some expansions.
As compared to plain C# i see .net core web development has added a lot to original C# semantics and ideology
And ML.Net, could do that too, to ease the coding of neural nets.
Pipeline.Add,  reminded me on how it was required to write down line numbers in a old basic version.
It was quite clear that each new line was a new line of code in basic still you had to write a number first  (MSX basic).
There was a option to AutoNumber lines, but well the language did not realy needed line numbers (as there was goto :label as well)


A neuralnet object should only require problem name i think, say "AirplaneDelay", each method would update info about the problem.
A collection of steps could be maintained, internally perhaps for input export of ML recepie, but a next line in editor or a " ; "
width another ".command;"  would have the same effect, or have it both ways.
So be able to import/export a xml/json reciepe, but also have VS be able to writedown auto generated code based upon a reciepe, in a more literate language.

It should be easy to define a data set, and get it width various connections, parsers, webscrappers , and reformat options.
Be able to store it, and re-load their datasets ( load from backups vs live data).
Be able to define the network, (or even have something that advices a network layout).
Be able to save export / encrypt trained nets.
Be able to define customized neurons / layers / methods /some matrix calculation extensions maybe .

Also add some debugging options in visual studio like returning a bitmap heatmaps, or values per nodes.
Visual studio wont show bitmaps in debug, but that might be really helpfull for this.
Perhaps have more options on that, ea return line and bar graph's as well.




________________________________
Van: Dan Moseley <notifications@github.com>
Verzonden: donderdag 17 mei 2018 02:15
Aan: dotnet/machinelearning
CC: PGTBoos; Author
Onderwerp: Re: [dotnet/machinelearning] Language improvements (#174)


If you're looking for a more "literate programming" experience - would it help if LearningPipeline.Add() returned the learning pipeline object instead of void?

**Comment by Sorrien** [comment]
All they added to .net core was a lot of extension methods and ease of use to the libraries you use. I wouldn't classify that as an expansion to .net itself. I find the functionality that currently exists to be relatively easy to use, although a lot of the features @PGTBoos mentions does not yet exist, like neural networks beyond basic perceptrons. It would seem to me that what you need is another layer of abstraction, but that is more of a "nice to have" than something that is necessary for the usefulness of ML.Net. It's something I definitely want down the road, but I think those kinds of things come with time. That's a big jump forward from where we are now.

**Comment by Ivanidzo4ka** [comment]
Considering what we moved from learning pipeline to IEstimators/ITransforms i'm closing this issue
