### ISSUE TITLE
WordTokenizeingTransformer need example of how to use it.

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#1746]
I am looking for examples for using `WordTokenizingTransformer`. The only resources I found is [its test](https://github.com/dotnet/machinelearning/blob/18d7ea306c480013f54674d92431386abccce64f/test/Microsoft.ML.Tests/Transformers/WordTokenizeTests.cs#L67), but after reading that, I still don't know how to print out its output using `Console.WriteLine`. As a C# library, we need more end-to-end examples which **feed C#** data structures and get the produced results **as native C#** objects.

**Comment by sfilipi** [comment]
@wschin what should we define as completion criteria for this bug: adding a sample for WordTokenizingTransformer?

**Comment by wschin** [comment]
@sfilipi, yes and in the future, every estimator should have some tests for native world. We need to demonstrate/test our ways to send something to the universe and get them back.

**Comment by Ivanidzo4ka** [comment]
@rogancarr @sfilipi  @shmoradims Do we have list of all required samples to our API, so we can link this issue to it?

**Comment by rogancarr** [comment]
We're adding samples & docs requirements to #1209

**Comment by jwood803** [comment]
Just curious as I was messing with this, is the `WordTokenizingEstimator` used for the older static API? Should the `context.Transforms.Text.TokenizeWords` transform be used instead for the newer dynamic API?

**Comment by rogancarr** [comment]
The `catalog` entries are helper functions for calling the Estimator API.

**Comment by shmoradims** [comment]
Already fixed: https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.textcatalog.tokenizeintowords?view=ml-dotnet#examples
