### ISSUE TITLE
Changing trainer makes application exit with STATUS_STACK_OVERFLOW 

### ISSUE THREAD

**Issue by pekspro** [dotnet/machinelearning#1752]
### System information

- Windows 10
-  Microsoft.ML 0.7.0
 - Dotnet.Core 2.1.403 

### Issue

I have created a .NET Core application that is using a lot of code of the GitHubLabeler sample. To be specific this file:

https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/end-to-end-apps/MulticlassClassification-GitHubLabeler/GitHubLabeler/GitHubLabelerConsoleApp/Program.cs

One major change I have done is to create a text file in memory with training data instead of reading from a file, otherwise it’s very similar. If I create my trainer with this code the application runs fine in all situations:

    var averagedPerceptronBinaryTrainer = mlContext.BinaryClassification.Trainers.AveragedPerceptron(DefaultColumnNames.Label,
        DefaultColumnNames.Features,
        numIterations: 10);

    IEstimator<ITransformer> trainer = new Ova(mlContext, averagedPerceptronBinaryTrainer);

But if I use this code instead:

    IEstimator<ITransformer> trainer = mlContext.MulticlassClassification.Trainers.StochasticDualCoordinateAscent(DefaultColumnNames.Label,
        DefaultColumnNames.Features);

My application exists with error code -1073741571, which I guess means STATUS_STACK_OVERFLOW (0xc00000fd). But it only does this when I run the application as a webjob in Azure, I can’t replicate the problem locally (yet).

If I reduce the number of training data, it also works fine (I’m changing the number of items from 10 000 to 1 000).

My guess it that the StochasticDualCoordinateAscent trainer makes evil things on the stack :-) Or could it be something else?

**Comment by sfilipi** [comment]
Some algorithms are more resource intensive than some others. Also the number of training data alone might not tell much. Is your data text, like the github sample? If so, the number of features created will be large, adding to the equation.

**Comment by pekspro** [comment]
Thanks for answering @sfilipi. Yes, my data is text like the GitHub sample. I’m having three columns in my data; Area, Title and Description just like the GitHub sample

I’m totally fine that the algorithms are using different amount of resources. I do expect that they use a lot of CPU and memory on the heap. But I am surprised that a lot of memory is used on the stack as the error message I get indicates. I don’t understand why that should be necessary.

**Comment by pekspro** [comment]
Update: I can replicate this with the original GitHubLabeler sample. I just changed a path, modified corefx-issues-train.tsv so that it contained 30 000 lines. Then when I run this in Azure as a web job on an app service with 14 GB of RAM it crashes with these lines:

	[11/29/2018 10:28:29 > 432ef3: INFO] =============== Cross-validating to get model's accuracy metrics ===============
	[11/29/2018 10:29:02 > 432ef3: ERR ] 
	[11/29/2018 10:29:02 > 432ef3: ERR ] Process is terminating due to StackOverflowException.
	[11/29/2018 10:29:03 > 432ef3: SYS INFO] Status changed to Failed
	[11/29/2018 10:29:03 > 432ef3: SYS ERR ] Job failed due to exit code -1073741571

I get the same problem with smaller instances. But I can’t get the error on my local machine even if I use a lot larger corefx-issues-train.tsv file. It’s very confusing :-/

**Comment by sfilipi** [comment]
Thanks for the added info @pekspro. Moved to the current project for traige.

**Comment by pekspro** [comment]
Update: I get the same problem in Microsoft.ML 0.8.0.

**Comment by codemzs** [comment]
please try with stable release 1.0. closing but feel free to reopen.
