### ISSUE TITLE
MLContext extension naming mismatch with dynamic API

### ISSUE THREAD

**Issue by artidoro** [dotnet/machinelearning#1754]
Extensions to MLContext don't consistently match either the static API names, or the dynamic API names for estimators. This leads users that directly instantiate the dynamic API to find different names for the same estimators than when finding them through MLContext. 

Since the estimators obtained through MLContext use the dynamic API, I would suggest that their names match the dynamic API names.

**Comment by sfilipi** [comment]
CC: @Zruty0, @CESARDELATORRE 

@artidoro I would suggest closing this, and adding to the naming discussion in #1690
