### ISSUE TITLE
The ColumnInfo structure should live in the estimators, rather than transformers

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#1760]
For OneHotEncoding estimator/transformer, ColumnInfo lives in the estimator. 
For most other pairs, ColumnInfo lives in the transformer. 

Standardize their location. 

I think they should live in the estimator, since they are mostly used on Estimator definition.

**Comment by sfilipi** [comment]
@Zruty0, @CESARDELATORRE  moving them to the estimator sounds good? it would be another breaking change.

**Comment by TomFinley** [comment]
Hi @sfilipi I just ran into this wile trying to use `ValueToKeyMappingEstimator`... it's `ColumnInfo` is for some reason off in the transformer, not the estimator. Yes should fix.

**Comment by artidoro** [comment]
We have completed this work for all public `ColumnInfo` objects.
