### ISSUE TITLE
Need XML doc string for each public field

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#1768]
At ML.NET doc site, there are a lot of fields with empty description, for example, see [this](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.matrixfactorizationtrainer.arguments?view=ml-dotnet). To make users' life easier, it'd be better to fill them with meaningful information.

**Comment by sfilipi** [comment]
@wschin i totally agree with this, but as is, this bug is hard to action on, as a one shot PR to document every public field is inefficient. Maybe we can tackle this by being more picky in code reviews?

**Comment by rekhakodali** [comment]
Can I help please

**Comment by shauheen** [comment]
@wschin can we close this issue and track this with #1209 instead?

**Comment by shmoradims** [comment]
Already addressed by #1209 and #2522.
