### ISSUE TITLE
PFI should work for multi class classification, clustering and recommendation

### ISSUE THREAD

**Issue by artidoro** [dotnet/machinelearning#1771]
PFI currently only works for binary classification and regression. It should be extended to multi class classification, clustering and recommendation to provide explainability functionalities in other experiment categories.

The PFI approach works for all the above training scenarios, and it is natural for users that use the tool for binary classification/regression to also want to use it for other scenarios.

cc: @rogancarr

**Comment by rogancarr** [comment]
And `Ranking`.

**Comment by rogancarr** [comment]
We are not going to support `Recommendation` in PFI for the time being, as we only have Matrix Factorization.
