### ISSUE TITLE
Official build can fail due to copying of the same redist assets

### ISSUE THREAD

**Issue by vaeksare** [dotnet/machinelearning#1773]
Currently, all of the files under Redist are assumed to be RID specific, and get built/executed by every leg of the official build script. This is not the case for the DNNImageFeaturizer models, which means the same models get copied over from each RID leg (MacOS, Linux, etc) into the same destination container. This can cause issues if this happens at the exact same time.

**Comment by artidoro** [comment]
@vaeksare did you fix this issue with your PR?

**Comment by vaeksare** [comment]
Woops, you are right, thanks. Forgot to add the fixes tag to that PR.
