### ISSUE TITLE
Regression in Rff Code due to OVA + AveragedPerceptron

### ISSUE THREAD

**Issue by Anipik** [dotnet/machinelearning#1774]
I ran a benchmark provided to me By @justinormont  that uses Rff Transformer.
I ran it too on  master as well as on https://github.com/dotnet/machinelearning/commit/7d9660a3e3881e444f7a4212b175856aaa9bdbe0
and https://github.com/dotnet/machinelearning/commit/8b19930c3413b578b1b9603633f0e9ec30cd8acd

The time taken by the benchmark for both of the last two commit was around 850 ms for both netstandard as well as netcoreapp 3.0 implementation where as it was around 1.3 sec for the master branch.

I am working on adding the benchmark into the repo.
The rsp being used here is 
![image](https://user-images.githubusercontent.com/10516582/49246698-651ad200-f3ca-11e8-8f1e-4d4275a1aa98.png)

cc @adamsitnik @eerhardt @danmosemsft @shauheen

**Comment by sfilipi** [comment]
Has any of the default parameters changed?

**Comment by Anipik** [comment]
The rsp being used here 
![image](https://user-images.githubusercontent.com/10516582/49246721-74018480-f3ca-11e8-83a0-1fd66a36b1d6.png)

**Comment by justinormont** [comment]
Do we currently have a dashboard of the runtimes of the current benchmarks?

Perhaps we should add check-in gating based on performance tests? @markusweimer

**Comment by adamsitnik** [comment]
@Anipik you can use the [EtwProfiler](https://adamsitnik.com/ETW-Profiler/) to profile before and after and then use PerfView to compare both trace files for regressions.

1. Run the benchmark without the changes with `--profiler ETW`, save the path to the trace file
2. Run the benchmark with the changes with `--profiler ETW`, save the path to the trace file
3. Open both trace files in PerfView
4. Filter both trace files to single benchmark iteration like described [here](https://adamsitnik.com/ETW-Profiler/#using-perfview-to-work-with-trace-files) to have apples-to-apples comparison
5. Disable the module grouping (GroupPats = [no grouping])
6. Load the symbols: go to the By name tab, and press Ctrl+A (select all) and then Alt+S (load symbols).
7. Once you have more than one trace file opened in PerfView, a new menu item appears in the "Regression".
![image](https://user-images.githubusercontent.com/6011991/49307376-4bb27c80-f4d5-11e8-8c0f-55c4cf6d2d76.png)
8. Go to the Window with the trace file for the slower result, choose Regression => With Baseline (it should point to the faster result)
9. You should get a table with regressions
![image](https://user-images.githubusercontent.com/6011991/49307847-b87a4680-f4d6-11e8-8836-5eb0858ca45f.png)
10. To get better understaning of what all these numbers mean go to Help->User guide and hit Ctrl+F and search for "Regression Investigation with Overweight Analysis "

**Comment by Anipik** [comment]
The regression here is mostly caused by https://github.com/dotnet/machinelearning/commit/cb9effcd091c60fa291aad96cc18c14ddf841b6f

The regression diff report before and after this change is 

// after change

Name | Base | Test | Delta | Responsibility % | Overweight % | Interest Level
-- | -- | -- | -- | -- | -- | --
coreclr!COMDouble::Log | 5.0 | 9072.0 | 9067.0 | 20.56 | 496035.50 | 5
microsoft.ml.data!Microsoft.ML.Runtime.Data.DataViewUtils+Splitter+InPipe+Impl`1[Microsoft.ML.Runtime.Data.VBuffer`1[System.Single]].Fill() | 240.0 | 37565.0 | 37325.0 | 84.65 | 42541.00 | 5
microsoft.ml.standardlearners!Microsoft.ML.Runtime.Learners.Ova.TrainOne(class   Microsoft.ML.Runtime.IChannel,class Microsoft.ML.Runtime.Training.ITrainerEstimator`2>,class   Microsoft.ML.Runtime.IPredictorProducing`1>,class   Microsoft.ML.Runtime.Data.RoleMappedData,int32) | 27425.0 | 63490.0 | 36065.0 | 81.79 | 359.71 | 5

// before commit

Name | Base | Test | Delta | Responsibility % | Overweight % | Interest Level
-- | -- | -- | -- | -- | -- | --
ucrtbase!log | 2.0 | 8529.0 | 8527.0 | 20.66 | 1246124.00 | 5
coreclr!COMDouble::Log | 5.0 | 9108.0 | 9103.0 | 22.06 | 532120.10 | 5
microsoft.ml.standardlearners!Microsoft.ML.Runtime.Learners.Ova.TrainOne(class   Microsoft.ML.Runtime.IChannel,class   Microsoft.ML.Runtime.Training.ITrainerEstimator`2>,class   Microsoft.ML.Runtime.IPredictorProducing`1>,class Microsoft.ML.Runtime.Data.RoleMappedData,int32) | 27425.0 | 63155.0 | 35730.0 | 86.58 | 380.79 | 5

**Comment by Anipik** [comment]
The regresstion report between master and 8b19930c3413b578b1b9603633f0e9ec30cd8acd 

Name | Base | Test | Delta | Responsibility % | Overweight % | Interest Level
-- | -- | -- | -- | -- | -- | --
system.private.corelib!System.Buffer.Memmove(System.ByReference`1,   System.ByReference`1, UInt64) | 5 | 12809 | 12804 | 112,13 | 2704929 | 6
microsoft.ml.data!Microsoft.ML.Runtime.Data.DataViewUtils+Splitter+InPipe+Impl`1[Microsoft.ML.Runtime.Data.VBuffer`1[System.Single]].Fill() | 240 | 34324 | 34084 | 298,49 | 150009,8 | 6
coreclr!ArrayNative::ArrayCopy | 16452 | 4221 | -12231 | -107,11 | -785,28 | 6

**Comment by adamsitnik** [comment]
@Anipik great job on finding the root cause of the regressions!

**Comment by abgoswam** [comment]
@Anipik  There is one more bug fix for the OVA + AveragedPerceptron scenario.  Please check out #1805

**Comment by Anipik** [comment]
@abgoswam I ran the benchmark for #1805 The particular commit actually decreased the time from 1.3sec to 900 ms. which is almost same as 850ms. The regression due is about 6% due to this.

@danmosemsft @eerhardt should we keep this open ? or is it okay to close them. I have opend the separate issue for the cache mechanism.

cc @yaeldekel
