### ISSUE TITLE
Extra Spaces in Baseline file for Netcoreapp3.0

### ISSUE THREAD

**Issue by Anipik** [dotnet/machinelearning#1776]
TestName EntryPointPipelineEnsembleGetSummary

The original baseline file contains ```"Features.bare_nuclei\t%Number%  \t%Number% \t%Number%  \t%Number% ***"```
file - machinelearning\\test\\BaselineOutput\\Common\\EntryPoints\\ensemble-summary.txt"

baseline - "Features.bare_nuclei\t%Number%   \t%Number% \t%Number%  \t%Number% ***"
output -   "Features.bare_nuclei\t%Number%  \t%Number% \t%Number%  \t%Number% ***"

cc @eerhardt @danmosemsft @shauheen

**Comment by shauheen** [comment]
@Anipik can you please explain if a fix is needed here, or this issue is resolved already as the core 3 builds seem to be working fine.

**Comment by codemzs** [comment]
agree with Shauheen
