### ISSUE TITLE
Consider adding convenience functions to load / save models from / to files

### ISSUE THREAD

**Issue by markusweimer** [dotnet/machinelearning#1778]
In order to load a model from disk, one currently has to do something like this:

```cs
ITransformer trainedModel;
using (var stream = new FileStream(ModelPath, FileMode.Open, FileAccess.Read, FileShare.Read))
{
  trainedModel = mlContext.Model.Load(stream);
}
```

(Code taken from our sample [here](https://github.com/dotnet/machinelearning-samples/blob/ff0ae26e3bd2366c1fe55e8e8fbee17b4596cc61/samples/csharp/getting-started/BinaryClassification_SentimentAnalysis/SentimentAnalysis/SentimentAnalysisConsoleApp/Program.cs#L101)

We should consider adding convenience methods for this common case to allow for code like this:

```cs
ITransformer trainedModel = mlContext.Model.LoadFromFile(ModelPath);
```

Similarly, we could consider adding a convenience method to save to a file to allow for code like this:

```cs
mlContext.Model.SaveToFile(trainedModel, ModelPath);
```

Of course, we might also want the `*Async` variants thereof.

**Comment by TomFinley** [comment]
Hi @markusweimer thanks for the comment... This appears to be a duplicate of #1689, unless I miss something? (Though admittedly the title of that issue isn't *great* so this was probably easy to miss.)

**Comment by markusweimer** [comment]
Yepp. And here I was, even searching our issues for a while. Closing as it is a duplicate.
