### ISSUE TITLE
Change the <a> tags to <image> tags

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#1783]
In the RankerMetrics the `<a>`  tags for images will need to get converted to `<image>` tags, so the images display. 

https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Data/Evaluators/Metrics/RankerMetrics.cs#L23

**Comment by jpbrandl** [comment]
I will take a look at this one, if it is still available.
