### ISSUE TITLE
Delete the Legacy API

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#1787]
Before shipping v1.0, we need to delete all the APIs that are marked "legacy" and "obsolete". Specifically, after this work is completed https://github.com/dotnet/machinelearning/tree/master/src/Microsoft.ML.Legacy should be completely removed, and any assets in it that need to remain should be migrated elsewhere. For example #1565 is for migrating the entry-points that we still need.

**Comment by sfilipi** [comment]
When deleting the Legacy API, also remove the Start field from the LoadColumAttribute.cs (link coming soon. File is not checked in yet.)

**Comment by eerhardt** [comment]
This was completed with #2043
