### ISSUE TITLE
Support scoring on ARM

### ISSUE THREAD

**Issue by shmoradims** [dotnet/machinelearning#1790]
This issue is a concrete work item from question #1662.

Motivation:
We need ARM for scoring models on IoT devices and for mobile devices running Xamarin apps on iOS or Android. All those workloads are important for .NET.

**Comment by codemzs** [comment]
Yep, ARM scoring would be great. I believe dotnet is working on something around it.

**Comment by CESARDELATORRE** [comment]
@codemzs - Why was this issue closed?
.NET already supports ARM such as on Xamarin apps for iOS and Android or on IoT ARM devices. 

What's not supported is ML.NET on ARM. 
ARM scoring would allow additional scenarios/environments for ML.NET hence increasing ML.NET usage, for instance:

**POSSIBLE ENVIRONMENTS:**

-	Xamarin apps (requires ARM support when deploying to iOS or Android devices)
-	Linux IoT ARM devices able to run .NET Core: https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-csharp-module
-	Azure IoT EDGE devices
    o	Related to Azure IoT SDK CSharp (https://github.com/Azure/azure-iot-sdk-csharp)
    o	Related to Azure Stream Analytics on IoT Edge with UDF in C# (https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-edge) 
-	Windows IoT devices (Requires ARM or x86 supporting TensorFlow, etc.): https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-csharp-module-windows

**Comment by codemzs** [comment]
@CESARDELATORRE this is not something we are doing in the short term hence I’m closing this issue. Thanks!

**Comment by hernandoz** [comment]
Hi, this would be a great addition / feature for mobile devices (Android & iOS), just imagined to be able to analysed input data/images on the device on the fly and offline. @CESARDELATORRE  @jamesmontemagno

**Comment by Goldenstarc** [comment]
It looks like we have to deploy MLNET on server using ASP.Net (Core!) and use HTTP service in Xamarin
Is there any better news?

**Comment by BlueCode2019** [comment]
I recently encountered a demand for this cross-platform application, and I look forward to an example
