### ISSUE TITLE
Evaluator of one-class matrix factorizaition is missing

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#1795]
One class matrix factorization is solved as a regression problem but common metrics in practices are top-k accuracy, nDCG, etc.

**Comment by wschin** [comment]
My plan is first convert `GroupTransform` to `Transformers` because we need it to convert
| User        | Item           | Score  |
| ------------- |:-------------:| -----:|
| 0      | 1 | 0 |
| 3    | 1      |   1 |
| 0 | 3      |    1 |
to

**Comment by codemzs** [comment]
@wschin do we still need this? I'm closing but feel free to reopen.
