### ISSUE TITLE
Rename types inside MLContext as Catalogs

### ISSUE THREAD

**Issue by TomFinley** [dotnet/machinelearning#1796]
We had an idea in #949 to have "context" objects that enabled the easy and convenient creation of training algorithms. We eventually came to like this idea so much that it expanded considerably, until we came to think it actually a good idea that *most* components (whether trainers or not) could work through this object, to the point where eventually in in #1098, there was a "master" context, of which the formerly independent contexts became properties of that master context.

The newer things that were added were then called "catalogs," for example:

https://github.com/dotnet/machinelearning/blob/cb37c7e7f1e1b29b5608a2755db793c5435d10b1/src/Microsoft.ML.Data/MLContext.cs#L47

https://github.com/dotnet/machinelearning/blob/cb37c7e7f1e1b29b5608a2755db793c5435d10b1/src/Microsoft.ML.Data/MLContext.cs#L52

However the old objects retained the type names they had back when they were independent.

https://github.com/dotnet/machinelearning/blob/cb37c7e7f1e1b29b5608a2755db793c5435d10b1/src/Microsoft.ML.Data/MLContext.cs#L25

We ought to probably standardize the name of these things as being "catalogs." E.g., things in here with the type name suffix `Context` should change that to `Catalog`, things that are catalogs but aren't named that yet (`DataOperations`) should be standardized as well.

**Comment by mareklinka** [comment]
Would the rename also apply to base classes? E.g. `TrainContextBase` in `public sealed class BinaryClassificationCatalog : TrainContextBase`? I would think that yes, those should be made consistent as well, just want to make sure.

The same thing then of course applies to method parameters (`ctx` -> `catalog`) and any mention in the documentation comments.
