### ISSUE TITLE
System.MachineLearning.Runtime namespaces cleanup

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/machinelearning#18]
_From @KrzysztofCwalina on Apr 16, 2018, 9:11 AM PDT_

There are several problems with System.MachineLearning.Runtime namespaces. We should clean these problems out:

- [ ] There are too many System.MachineLearning.Runtime subnamepsaces. This will overwhelm users browsing the documentation on MSDN, IDE browsers, etc. We should combine the APIs in fewer subnamespaces.
- [ ] We should not use "Api" in namespace or project names. All public things are "APIs" as far as .NET developers are concerned.

- [ ] We have "EntryPoints" namespace. We should rename it. All "entry point" APIs should simply be in the root namespace (or subnamesapce of the root..

- [ ] We should not have "tools" APIs in the main assmebly. Remove/rename Microsoft.MachineLearning.Runtime.Internal.Tools

**Comment by shauheen** [comment]
This work may need more hashing specially in light of the API work. I will keep the issue for now. we will revisit after 0.4.

**Comment by abgoswam** [comment]
DRI RESPONSE : moving to 0.7 (awaiting triage) probably requires splitting into multiple issues

**Comment by shauheen** [comment]
With the API plans runtime will be removed, so this should not be valid anymore.
