### ISSUE TITLE
SSE bug when scaling a vector by a negative number

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#1802]
When the number of elements is not divisible by 4, the sign of the result sometimes wrong.
Here is an explanation from @eerhardt .

We are “double computing” at the end of the vector when there are remaining elements (1, 2, or 3 hanging elements). We then mask out the “double computed” elements in temp (which should have all 0s for the ‘double computed’ elements).

However, when doing `temp = _mm_mul_ps(temp, x1);`, since ‘x1’ is negative, multiplying the 0s in temp against a negative number is turning them into -0 (negative zero).

We then `_mm_or_ps(temp, result);` which then switches the sign of the ‘double computed’ elements – which is incorrect.

So that’s why some of the elements are getting the wrong sign. Because we are OR’ing them with negative zero, which changes the sign.

**Comment by Anipik** [comment]
yes it is right, i faced the similar problem while writing matrix multiplication. the solution that worked for me was replacing ```or``` operation with ```Add operation```.
The behaviour will be same as one of them is always zero. eg if temp is [0 -0 1 1] the result will be [0 1 0 0]
No index is one simultaneously.
