### ISSUE TITLE
Can I use TimeSeries prediction with Vec<R4, N> input data?

### ISSUE THREAD

**Issue by NektoDron** [dotnet/machinelearning#1818]
Is it possible in the future?
Now it makes an exception "The feature column has  type 'Vec<R4, 3>', but must be a float."

**Comment by codemzs** [comment]
Are you wanting multi variate time series?

**Comment by singlis** [comment]
Hello-
Thank you for bringing this up. The multivariate time series is not supported at this time, however it is something that we are tracking here:
#1696

**Comment by Zruty0** [comment]
@NektoDron , predicting the next value is not something we have on the immediate plans. However, you can simulate these 'auto-regression' models by taking a sliding window of the original time series and training a regression model to predict the next value in the series.

Of course care should be taken to make sure seasonality and trends are captured properly, but I think this is a well-known area of research.

**Comment by NektoDron** [comment]
@Zruty0 , I've tried to do this. But it's too slow, because I should always retrain many models to simulate how prediction works on the history data.

**Comment by shauheen** [comment]
@zeahmed can you please provide a sample.

**Comment by codemzs** [comment]
multi-variate time series is on the roadmap but in the meantime refer to samples herehttps://github.com/dotnet/machinelearning/tree/master/docs/samples/Microsoft.ML.Samples/Dynamic
