### ISSUE TITLE
Cannot use ML.NET in a Windows nano container

### ISSUE THREAD

**Issue by swesonga** [dotnet/machinelearning#1823]
### System information

Base image: microsoft/dotnet:2.1-aspnetcore-runtime-nanoserver-1803

Microsoft Windows [Version 10.0.17134.345]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\app>dotnet --info

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

### Issue
Repro: Install the Visual Studio Service Fabric Mesh tools from https://blogs.msdn.microsoft.com/azureservicefabric/2018/12/04/service-fabric-mesh-preview-refresh-release/ then follow the tutorial at https://docs.microsoft.com/en-us/azure/service-fabric-mesh/service-fabric-mesh-tutorial-create-dotnetcore and install the ML.NET package to try training an ML model.

When the web project starts, a System.InvalidOperationException is thrown.
Inner Exception
DllNotFoundException: Unable to load DLL 'CpuMathNative' or one of its dependencies: The specified module could not be found.

**Comment by singlis** [comment]
@swesonga Thank you for reporting this. I am not familiar the Windows Nano image. Is this by chance a 32-bit or ARM based? We currently only support 64-bit, but do have plans to support other platforms.

**Comment by eerhardt** [comment]
I investigated this today. It appears the issue is that we are dynamically linking to the VC++ Runtime, which is not available on Windows Nano (and it isn't installed on "normal" users machines either).

The fix is simple (once you know what to do). We should be statically linking against the VC++ Runtime (using the `/MT` compile flag). I missed this when I first set up the native build code.

**Comment by eerhardt** [comment]
@singlis - FYI we do now support 32-bit on Windows.

Windows Nano is the "small" Windows docker container technology: https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10
