### ISSUE TITLE
RffWorkout test is not stable and randomy fails during the build.

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#1825]
As title. I failed multiple times for some unknown reasons. It needs to be improved for a more smooth merging process.

**Comment by singlis** [comment]
@wschin Is there a specific platform this is failing on?

**Comment by Ivanidzo4ka** [comment]
I download RffStatic test output file and it looks like we have error in 7th digit or so. So easy solution is to just change precision.
For RffWorkout, it's kinda mystery. It fails in Done method which shouldn't happen. Done checks certain variable which we set to true during initialization, and never changed in test.

**Comment by Zruty0** [comment]
I believe that we actually set the 'passed' field during `CheckSameSchema` and `CheckSameValues`, which is consistent with the assumption that RFF is not deterministic.

**Comment by singlis** [comment]
Please see this PR:
https://github.com/dotnet/machinelearning/pull/1829

**Comment by singlis** [comment]
@Zruty0  - I will check the passed field as well.

**Comment by singlis** [comment]
From the thread on #1829, the intermittent failures were due to change #1657, which was reverted in #1838. I have also not seen it repro in the build since the revert, so marking this as closed.
