### ISSUE TITLE
 Deprecate documentation topics migrated to docs.microsoft.com

### ISSUE THREAD

**Issue by JRAlexander** [dotnet/machinelearning#1831]
The ML.NET Cookbook and ML.NET High-Level Concepts documents have been migrated to docs.microsoft.com as agreed upon. The current documents need to be updated to point to the migrated ones.

**Comment by JRAlexander** [comment]
@shauheen, I'll follow up offlline, as I just saw your email.  Thanks.

**Comment by shmoradims** [comment]
@JRAlexander @shauheen , what did you guys end up deciding? Is this a duplicate of #1830?

**Comment by natke** [comment]
We can close this. We are creating topics on docs.microsoft.com as needed, and if there is redundancy between the two sources, we can handle those on a case by case basis.

**Comment by shmoradims** [comment]
Great. I'll close this uber issue.
