### ISSUE TITLE
Schema.Metadata needs a better name

### ISSUE THREAD

**Issue by TomFinley** [dotnet/machinelearning#1843]
"Metadata" is perhaps not the best name for what we currently call metadata.

First, what is it: what we call Metadata is meant to suggest not just any metadata, but that data that we consider auxiliary, or at *most* ancillary. (So for example, slot names are in metadata, because not everything will have names for each slot. But sometimes they will, and we need a place to keep that.)

The trouble with the name "metadata" is that it means literally everything but the data. But this is inaccurate: there are lots of things that are data about the data (e.g., the types, the vector sizes, the names of columns) that we definitely do not want to keep in the metadata structure (since they're absolutely required information), but that is "metadata" in the strict linguistic sense of the word.

The only name suggested as an alternative that I am aware of is "annotations." I am fine with the name annotations. Perhaps we could come up with a better name. I'll leave this open for a bit, and unless people object we can rename metadata annotations.

**Comment by Zruty0** [comment]
I am fine with 'annotations' as a property name (as in, `schema[column].Annotations.GetValue("foo", ref foo)`).

As for the class name, I think neither `Metadata` nor `Annotations` are good names: they reflect what the object is **used for**, not what it **is**. And the metadata is, essentially, 'almost a row', or 'a property bag'.

So, maybe `PropertyBag`, or `ValueCollection` or something like that?..
