### ISSUE TITLE
Schema Equtable

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#1857]
Sometime, we have code like
```csharp
            public Cursor(IChannelProvider provider, RowToRowScorerBase parent, RowCursor input, bool[] active, Func<int, bool> predicateMapper)
                : base(provider, input)
            {
                Ch.AssertValue(parent);
                Ch.AssertValue(active);
                Ch.AssertValue(predicateMapper);

                _bindings = parent.GetBindings();
                Schema = parent.OutputSchema;
                Ch.Assert(active.Length == _bindings.ColumnCount);
                _active = active;

                _output = _bindings.RowMapper.GetRow(input, predicateMapper);
                try
                {
                    Ch.Assert(_output.Schema == _bindings.RowMapper.OutputSchema);
                    _getters = parent.GetGetters(_output, iinfo => active[_bindings.MapIinfoToCol(iinfo)]);
                }
                catch (Exception)
                {
                    _output.Dispose();
                    throw;
                }
            }
```
where the equivalence between two `Schema` objects is enforced by using things like
```
_output.Schema == _bindings.RowMapper.OutputSchema
```
. This implies that we need to implement proper comparison function for `Schema`.

**Comment by wschin** [comment]
With two identical `Schema`, `Schema A` and `Schema B`, is it possible to have `false = A==B`?

**Comment by TomFinley** [comment]
It depends what you mean by identical @wschin . Are two distinct schema objects with the same columns named, in the same order, with the same types, same metadata, etc., the same schema? Currently the answer is no, and we have a lot of code that depends on the answer there being no.

As @Zruty0 says, we don't actually want in depth comparisons beyond those offered by the default object comparison (which is a reference comparison). We are here in the example you show checking that they simply are the same object, and that is all we should be doing here. If we were to try to apply this method to another schema object, this would imply a misuse.

That the comparison is a reference comparison is absolutely deliberate, and not a bug to be fixed.

**Comment by wschin** [comment]
Thanks a lot for all your answers!
