### ISSUE TITLE
Follow up on Calibrator estimators

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#1871]
There are a few follow ups to the work to create calibrator estimators:

1- The public classes in Microsoft.ML.Core/Prediction/Calibrator.cs need to have descriptive XML documentation. 
2- The Calibrators need to be added as property to the BinaryClassificationContext
3- Some of the Calibrators have a public constructor, that allows initializing the parameters. Does  it make sense to expose and  wire those parameters to the CalibratorEstimators, and set them from there? 
So they will all look like [FixedPalttCalibratorEstimator](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Data/Prediction/CalibratorCatalog.cs#L319)

cc @Zruty0

**Comment by Zruty0** [comment]
There are 2 cases of calibrators: one where we set the parameters (slope, offset) manually, and one where we learn them. 

Both cases will need an estimator: first one will just be a regular trainer, and the second will be a trivial estimator. I world prefer these 2 cases to be invoked via 2 different methods, instead of a single overload.

**Comment by TomFinley** [comment]
It seems to me that these when fit, given that they're parameterized with model parameters, should be producing a model with `CalibratedModelParametersBase`, with the sub-model being the input model. I do not see that the estimators currently are doing this. Instead what I see is that.

I am at least confident we should not have *two* mechanisms for doing this. Right now we have two, and I'm not sure why:

1. `CalibratorTransformer<TCalibrator>`, and

2. `BinaryPredictionTransformer<CalibratedModelParametersBase<TModel, TCalibrator>>`

**Comment by Ivanidzo4ka** [comment]
I can be wrong, but for me it looks like done issue.
https://github.com/dotnet/machinelearning/pull/2601 does 1) and 3) and I believe @wschin  is done with  making sure we return calibrated or not calibrated model.

**Comment by TomFinley** [comment]
> I can be wrong, but for me it looks like done issue.
> #2601 does 1) and 3)

Hi @Ivanidzo4ka , you are omitting 2 I think. The estimator for calibration is still not accessible through `MLContext`, the `IHostEnvironment` constructor is still public at the present time, as we see below.

https://github.com/dotnet/machinelearning/blob/eb60021712a729bbcd19abd28ef8e4669d7ee85b/src/Microsoft.ML.Data/Prediction/CalibratorCatalog.cs#L279-L282

There is still not `Calibrator`'s property that is some sort of `CalibratorsCatalog` accessible through `BinaryClassification`.

**Comment by Ivanidzo4ka** [comment]
Ok, let's at least add it to Project 13, otherwise it has chance to be missed.

**Comment by Ivanidzo4ka** [comment]
Just to make clear.
We want something like this:
```
            var pipeline = mlContext.BinaryClassification.Trainers.StochasticDualCoordinateAscentNonCalibrated(
                labelColumn: "Label", featureColumn: "Features", loss: new HingeLoss(), l2Const: 0.001f)
                .Append(mlContext.BinaryClassification.Calibrators.PairAdjacentViolators("Label"));

            // Step 3: Train the pipeline created.
            var model = pipeline.Fit(data);
           // Get submodel and calibrator.
            var subModel = model.LastTransformer.Model.SubModel;
            var calibrator = model.LastTransformer.Model.Calibrator;

```
Or something else?

Right now CalibratorEstimator returns https://github.com/dotnet/machinelearning/blob/412e1f904c9cd25b80e62bb01390e09360b5b50c/src/Microsoft.ML.Data/Prediction/CalibratorCatalog.cs#L150 
which is quite blank. 
![image](https://user-images.githubusercontent.com/1523833/53216681-42373d00-360a-11e9-9b1a-4c587b862885.png)
