### ISSUE TITLE
GPU-powered KNN

### ISSUE THREAD

**Issue by turowicz** [dotnet/machinelearning#1880]
I'm aware that there is an issue already #1712, I'm just looking for guidance. I've migrated the dlib based face recognition to a c# project using DlibDotNet project. The final missing piece is a fast way of processing 1000s of candidates for a closest match.

Can anyone point me in the right direction?

**Comment by wschin** [comment]
ML.NET currently doesn't have a direct implementation. If you can provide more context about your scenario, we will be able to find if there is any alternative solutions (such as doing clustering using Kmeans).

**Comment by Ivanidzo4ka** [comment]
Hello.
First, I'm not sure you can actually power KNN with GPU. GPU is really power in running bunch of matrix multiplications in parallel, and theoretically you can probably load all you data as matrix, and treat distance calculation as as matrix multiplication, but, it's looks like lot of work, and this is only for bruteforce algorithm, I doubt it's possible to have benefit out of GPU for K-DTrees and BallTrees.

Second, I've create [PR](https://github.com/dotnet/machinelearning/pull/1889) to introduce KNN in their dumb form (no K-D or ball trees, yet (weekends are too short)). I'll try to get it to decent state before 1.0 release, but it's just my side project (unless someone else will contribute, this is open source project after all :) )

**Comment by turowicz** [comment]
@ivanbasov the way DLib works in python/cpp, it allows me to use ball trees and I'm pretty sure (but not 100% certain) its GPU powered, as majority of things in OpenCV and DLib are matrix based.

**Comment by turowicz** [comment]
@wschin its about finding the best match very efficiently. Imagine you have 1000 identities and each of them has 10 face encodings. There can be multiple persons on the input photo. I need KNN-like performance in order to churn through the video in real time. I have it working in python but would very much love to have it working adequately in C#.

**Comment by turowicz** [comment]
This is an example that you can use as a reference implementation:
https://github.com/ageitgey/face_recognition/blob/master/examples/face_recognition_knn.py

**Comment by turowicz** [comment]
paging @takuya-takeuchi, author of DlibDotNet

**Comment by Ivanidzo4ka** [comment]
@turowicz  I'm not saying it's impossible. It just I don't see anything cuda specific in scikit and you want to have GPU speed during prediction.

I actually found some nice CUDA implementations on github https://github.com/src-d/kmcuda/blob/master/src/knn.cu

But there is  one trick. It utilize CUDA heavily, but it's during tree construction, and by running multiple threads for multiple quires.  Our framework separate loading time and scoring time, and also scores one object per request (we do it in parallel threads, so we not slow) but we don't have access to all examples to benefit out of it.
