### ISSUE TITLE
Multi classification - Probability

### ISSUE THREAD

**Issue by mgolois** [dotnet/machinelearning#1881]
Hello,
I have an application that use using ml.net multiclassification trainer to predict a category. However, it seems as though we remove the TryGetScoreLabelNames() method from the library. Basically, the application would like to output as well how confident (in percentage) is the predicted label. How can I achieve that in ML.NET 0.8?

**Comment by wschin** [comment]
You can access `Score` column in the output.

**Comment by mgolois** [comment]
Yes, @wschin , I have the `Score` column. How can I use it to get the probability, or is there away to calculate it with `Score` ?

**Comment by mgolois** [comment]
@wschin Here is my sample code:

`
static void Main(string[] args)
        {
            MLContext mlContext = new MLContext();
            string dataPath = Path.Combine(Environment.CurrentDirectory, "Data", "all.csv");

            TextLoader textLoader = mlContext.Data.TextReader(new TextLoader.Arguments()
            {
                Separator = ",",
                HasHeader = false,
                Column = new[]
                {
                    new TextLoader.Column("Description", DataKind.Text, 1),
                    new TextLoader.Column("Type", DataKind.Text, 2),
                    new TextLoader.Column("Category", DataKind.Text, 3),
                }
            });

            var data = textLoader.Read(dataPath);
            var (trainData, testData) = mlContext.MulticlassClassification.TrainTestSplit(data, testFraction: 0.2);

         
            var dataProcessingPipeline = mlContext.Transforms.Categorical.OneHotEncoding("Type", "TypeEncoded")
                 .Append(mlContext.Transforms.Text.FeaturizeText("Description", "DescriptionEncoded"))
                 .Append(mlContext.Transforms.Concatenate("Features", "Encoded", "DescriptionEncoded"))
                 .Append(mlContext.Transforms.Conversion.MapValueToKey("Category", "Label"))
                 .Append(mlContext.MulticlassClassification.Trainers.StochasticDualCoordinateAscent())
                 .Append(mlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel"));

       

            var model = dataProcessingPipeline.Fit(trainData);

            var metrics = mlContext.MulticlassClassification.Evaluate(model.Transform(testData));
            Console.WriteLine($"Accuracy Micro: {metrics.AccuracyMicro}");
            Console.WriteLine($"Accuracy Micro: {metrics.AccuracyMacro}");
          
            var predictionFunction = model.MakePredictionFunction<CategoryDetail, CategoryPrediction>(mlContext);
            var cat = predictionFunction.Predict(new CategoryDetail
                                                {
                                                    Description = "this is a great jacket",
                                                    Type = "Women"
                                                });

           //Now I need to output to the user the prediction cat.Prediction as well as the probability of that prediction

            Console.ReadKey();
        }


    public class CategoryDetail
    {
        [Column("1")]
        public string Description;
        [Column("2")]
        public string Type;
        [Column("3")]
        public string Category;
    }

    public class CategoryPrediction
    {
        [ColumnName("PredictedLabel")]
        public string Prediction { get; set; }

        [ColumnName("Score")]
        public float[] Score { get; set; }
    }


`

**Comment by wschin** [comment]
Can you access Score field in `cat`?

**Comment by mgolois** [comment]
yes I can, it's just array for float. how to do I get a percentage out of it?

**Comment by wschin** [comment]
`Scores[i]` stores the probability of being the i-th class.

**Comment by mgolois** [comment]
Ok, how do I get the list of labels from model. There used to be an extension method from the model in 0.7. 
If I have the list of label names from the model, I can do
 index = labelNames.indexOf(predictedLabel) then I can confidently do 
Scores[index]

OR

is it safe to assume that the maximum score was the predicted label?
scores.Max()

**Comment by wschin** [comment]
I'd expect that `PredictedLabel` field is there too, `Prediction` in `CategoryPrediction`.

**Comment by polymorp** [comment]
I would love to know how to do this too.
I can see the array of scores, but cannot be sure which label each Scores[index] relates to so whilst I know the percentage for the PredictedLabel result as that is the scores.max, I want to know the percentages for what came 2nd / 3rd etc. sometimes.

**Comment by karllarssonusawest** [comment]
Just jumping in to agree that returning the top N predictions with matching score is vital, something we've lost with the removal of 'TryGetScoreLabelNames'.

I'm able to do it when training the model and have all the data to hand (IDataView dataView parameter below) :

```
private static bool TryGetScoreLabelNames(TransformerChain<KeyToValueMappingTransformer> model, IDataView dataView, out string[] names, string scoreColumnName = DefaultColumnNames.Score)
        {
            names = (string[])null;
            Schema outputSchema = model.GetOutputSchema(dataView.Schema);
            int col = -1;
            if (!outputSchema.TryGetColumnIndex(scoreColumnName, out col))
            {
                return false;
            } 
VectorType valueCount = (VectorType)outputSchema.GetColumnType(col);

            if (!outputSchema.HasSlotNames(col, valueCount.Size))
            {
                return false;
            }

            VBuffer<ReadOnlyMemory<char>> vbuffer = new VBuffer<ReadOnlyMemory<char>>();
            outputSchema.GetMetadata<VBuffer<ReadOnlyMemory<char>>>("SlotNames", col, ref vbuffer);
            if (vbuffer.Length != valueCount.Size)
            {
                return false;
            }
            names = new string[valueCount.Size];
            int num = 0;
            foreach (ReadOnlyMemory<char> denseValue in vbuffer.DenseValues())
            {
                names[num++] = denseValue.ToString();
            }
            return true;
        }
```

However, I haven't figured out how to do that when I'm loading the model later on, to make a single prediction. At that point, I don't have an IDataView object I can pass into the function,

**Comment by karllarssonusawest** [comment]
Thanks, wschin - I couldn't translate your example into something that would work for me without a lot of retrofitting, but I did stumble on my own solution, I think. I keep the 'TryGetScoreLabelNames' function as is, but instead of using model.MakePredictionFunction to make my prediction, I broke that back down into its individual steps:

```
var inputData = mlContext.CreateDataView(new ClassOfItemToPredict[] { itemToPredict});
var outputData = _trainedModel.Transform(inputData);
var prediction = outputData.AsEnumerable<PredictionClass>(mlContext, reuseRowObject: false).Single();

 //Get labels
string[] scoresLabels;
if (TryGetScoreLabelNames(_trainedModel, outputData, out scoresLabels)) { };
```

That then gives me the IDataView I can pass into TryGetScoreLabelNames to get the schema etc...

**Comment by Ivanidzo4ka** [comment]
Just a heads up.
It's still a bit complicated and required work with metadata which you already do, but in 0.10 prediction function will contain OutputSchema.
https://github.com/dotnet/machinelearning/blob/master/test/Microsoft.ML.Tests/Scenarios/Api/Estimators/PredictAndMetadata.cs
So that would slightly ease process of getting information. Work with metadata is still a mess, and we need to come up with more user friendly way to access it. But at least now, you don't need to do extra steps to access schema.

**Comment by biztechprogramming** [comment]
I looked at the sample code that supposedly closes this issue.  It is extremely ugly code.  This issue should not be closed.

**Comment by tangbinbinyes** [comment]
> `Scores[i]` 存储成为第i类的概率。

Thanks.But how do I know which type of category "i" is?
