### ISSUE TITLE
Regression due to removal of autoCache

### ISSUE THREAD

**Issue by Anipik** [dotnet/machinelearning#1882]
The Auto-cache was removed in https://github.com/dotnet/machinelearning/commit/435a63b9db7464ec0400eb4be8ecc362f0d33dcc

I added new benchmark https://github.com/dotnet/machinelearning/pull/1855
Before the change the time taken by this benchmark was 2.8sec (after converting to api version and making label as key instead of R4)

After the removal of the cache The time went upto 10s. But after the adding the cache check point me and @wschin was able to reduce it to 3.8s which is still regressed from 2.8s.

**Comment by danmosemsft** [comment]
@glebuk do you use a particular label or github project to keep together bugs for perf issues? thiat might be handy.

**Comment by Ivanidzo4ka** [comment]
This is not regression, this is expected behavior see: https://github.com/dotnet/machinelearning/issues/1604

**Comment by Zruty0** [comment]
Well, @Ivanidzo4ka , I believe that 3.8 vs 2.8 is still some sort of bug: I would expect manual caching to work the same way as the auto-caching used to work.

**Comment by codemzs** [comment]
agree with Ivan here, please provide more details but closing for now.
