### ISSUE TITLE
Confusion parameter options in Dictionarizer, ColumnCopier etc.

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#189]
The following transform can operate on multiple columns either by using tuple [(input, output), (input2,output2), ... , (input_n,output_n)] or string array [col1,col2....coln]

There is no error for the following option. Both work fine. However, no.1 is actually not correct. Can we simplify it? or at least flag error because "Label" column is not yet there in the pipeline.

1. pipeline.Add(new Dictionarizer("Area", "Label"));
2. pipeline.Add(new Dictionarizer( ("Area", "Label") ));

**Comment by zeahmed** [comment]
This seems to be fixed by some other update. For case no.1 above, an error is thrown regrading missing "Label" column.
