### ISSUE TITLE
Improve discoverability of components not in the main nuget

### ISSUE THREAD

**Issue by markusweimer** [dotnet/machinelearning#1899]
ML.NET is split into multiple nugets, mostly motivated by the dependency structure of the components: Things that have native code are not in the main nuget, neither are things that pull in other OSS packages such as LightGBM or TensorFlow.

The benefit of this approach is that it allows apps to depend on the smallest possible and most portable subset of ML.NET with ease.

The major downside is that components in this other nugets aren't easily discovered, as they will only show up on `MLContext` after they have been installed. And there is no way to discover that they could be installed from e.g. IntelliSense.

Let's use this issue to discuss ideas and strategies to improve this situation.

**Comment by markusweimer** [comment]
cc @justinormont who brought this issue up offline

**Comment by justinormont** [comment]
Thanks @markusweimer. 

Some musings: 
* Increase visability
  * Create a nuget `Microsoft.ML.Full`, which includes all nugets; then for production, users can use minimal nuget sets 
  * Modify `MLContext` to show missing components, but warn in VS to install the missing nuget (e.g. IntelliSense)
* Minimize prediction stack
  * Create a specific `Microsoft.ML.Inferencing` nuget which contains only the prediction code paths -- should be much smaller than training code. E.g. all trees reduce to a common [trained tree ensemble](https://github.com/dotnet/machinelearning/blob/017fb09ad7b18f6cee1d51d85f5c48cf8af89259/src/Microsoft.ML.FastTree/TreeEnsemble/TreeEnsemble.cs#L21) no longer requiring the original code references like LightGBM (or any native code), and all linear models reduce to a simple [linear predictor](https://github.com/dotnet/machinelearning/blob/a01cacada95235318d42762def0153ada62ff3cd/src/Microsoft.ML.StandardLearners/Standard/LinearModelParameters.cs#L114).
  * Rely on ONNX for an optimized prediction framework

The trade-off is, we would like users to be able to naturally discover and easily explore all components in ML.NET, but placing all components in a single nuget causes users to create overly large apps (both for training & productionization of trained models). 

Please post additional ideas.

**Comment by Zruty0** [comment]
I don't have additional ideas, but I would like to point out issues with @justinormont 's suggestions.

1) `Microsoft.ML.Full` will be a multi-hundred-megabyte package (and maybe more if we choose to include all the DNN featurizer in it). I don't think this is sustainable.

2) We cannot have `MLContext` show 'missing' components. If anything, we could push for editor functionality to 'look for NuGets that may have this method': it is actually a feature available in some IDEs. But trying to mimic this feature via a library is dangerous.

3) A special nuget for prediction is a useful idea. However, it just so happens that our code is generally organized in such a way that training and inferencing code is not separated. So, creating such a split is a tremendous work, which I would rather not commit to. In addition, it alone doesn't help with the component discoverability, it could work only in the presence of `Microsoft.ML.Full` or something like that.

In addition, the prediction code may not be all that much smaller: all of the large binary assets (MKL, TensorFlow runtime, ONNX runtime, pre-trained embedding models etc.) are needed at prediction time, so we are only going to save up on the trainer code, and it is comparatively small.

**Comment by singlis** [comment]
@zruty0 @justinormont In regards to the Micorsoft.ML.Full package: 

We should be able to create a Microsoft.ML.Full package that contains dependencies of all of the ML.net packages. This would be sustainable because this would be done via nuget package references rather than having one large package.
