### ISSUE TITLE
Need a sample for multiclass classification in docs

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#1903]
In the ML.NET docs, we have a [collection of samples](https://github.com/dotnet/machinelearning/tree/master/docs/samples/Microsoft.ML.Samples) but there are no samples for Multiclass classification. There has already been an issue (#459) where someone wanted to use a multiclass classifier to get the predictions across the top-K classes, but wasn't able to understand the APIs as is. It would be super helpful to have a simple sample for multiclass classification that prints out the results for a few examples and then discusses the overall evaluation metrics.

**Comment by JRAlexander** [comment]
@rogancarr, Working on the GitHub Labeler Multiclass now. Hoping to have a PR by EOD.

**Comment by JRAlexander** [comment]
I mean today :)

**Comment by rogancarr** [comment]
@rekhakodali Yes, definitely!

**Comment by rekhakodali** [comment]
Hi Rogan,
 I will work on the below:
A simple sample for multiclass classification that prints out the results for a few examples and then discusses the overall evaluation metrics.

**Comment by JRAlexander** [comment]
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/github-issue-classification

**Comment by rogancarr** [comment]
Awesome! Closing this issue. I'll read over and file an issue on the docs repo if I have any comments.
