### ISSUE TITLE
LDA transform ignores per-column arguments

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#1904]
The constructor that instantiates the transform from the Arguments object ignores the arguments defined per column and just uses the global values defined in the args.

**Comment by justinormont** [comment]
Also I think LDA ignores the `summary` parameter.

Currently we don't have a method of getting the text topics back from the transform.

When we ask for the summary: `xf=LdaTransform{col=TextUnigramTF summary=+}`, the summary is not produced as a column. I think it may be retreivable afterwards via the rather opaque location in the model's .zip file.

Given the parameter's description, I would expect a new output column having the topic-word summary: 
https://github.com/dotnet/machinelearning/blob/f55f840526bffcb86bbbd92bdb2f156eff5ed02a/src/Microsoft.ML.Transforms/Text/LdaTransform.cs#L105-L106

**Comment by abgoswam** [comment]
@justinormont .  [Here](https://github.com/dotnet/machinelearning/blob/f55f840526bffcb86bbbd92bdb2f156eff5ed02a/test/Microsoft.ML.StaticPipelineTesting/StaticPipeTests.cs#L663) is an example of how you can get the `LdaSummary`, using the Static API paradigm.    Kindly take a look.

However, I am not sure how to expose the `LdaSummary`  using the Dynamic API paradigm.
