### ISSUE TITLE
Include confidence intervals for non-probabilistic scores

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#1906]
For probabilistic classifiers, we get a sense for the confidence of a model's output from the probability. For other types of scorers (e.g. regression), we just get a raw score out. Oftentimes, consumers of ML models want to know how confident a model is in its prediction. Thus, it would be nice to output confidence intervals for predictions.

There are methods to generate confidence intervals for ML models, but those usually require a lot of hand tuning and a background in statistics. It would be nice to automate such techniques so that anybody could use them.

Related to #511

**Comment by rogancarr** [comment]
(And of course, we may want confidence intervals on the predicted probabilities too....)

**Comment by codemzs** [comment]
not on the roadmap for near future.
