### ISSUE TITLE
One-time prediction without PredictionFunction

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#1907]
This question has been asked a number of times now (recently in https://stackoverflow.com/questions/53837654/ml-net-makepredictionfunction-dynamic-type )

Essentially, the users will sometimes need to perform the prediction without the ability to use schema comprehension to define the input/output classes. 

In the API we have `IRowToRowMapper` that is performing the work under the hood: it takes a `Row` as an input, and outputs a `Row` with predictions. However, we don't have a good 'easy' way to 'make a `Row`'. Maybe we should have something public and similar to `SimpleRow` for this purpose?

cc @TomFinley @yaeldekel

**Comment by shauheen** [comment]
Thanks @Zruty0 , can you please provide a sample for your proposed solution?

**Comment by codemzs** [comment]
please provide more details, closing until then.
