### ISSUE TITLE
Add metadata of evaluation metrics to models

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#1908]
Currently, we can use ML.NET to evaluate the performance of a model. However, when the model is passed to a third party, the evaluation metrics must be passed separately.

If you consider the evaluation metrics** to be properties of the model, then it makes sense to include them in the model. I expect this to be helpful in deployment, productionization, debugging, etc. Plus it would be nice to have properties of the model visible in an IDE and accessible programatically. 

Related to #511 

** e.g. over a dataset representative of the expected distribution of data to be seen by the model

**Comment by codemzs** [comment]
thanks but not on the roadmap for the near future.
