### ISSUE TITLE
Project will not build because of space in build path

### ISSUE THREAD

**Issue by atotalnoob** [dotnet/machinelearning#191]
### System information

- **OS version/distro**: Windows 10 Home
- **.NET Version (eg., dotnet --info)**: 2.1.200, concerning ML .net V0.1.0

### Issue

- **What did you do?** Try to build from source
- **What happened?** When trying to build, I have a space in my user profile, for example let's say "John Smith".  So when I cloned to C:/users/John Smith/source/repo/machinelearning/ and tried to build using a command prompt (in the before directory) using command `start build.cmd -Release -TargetArchitecture:x64` 

Another window opened (expected) and it said `'C:\Users\John' is not recognized as an internal or external command, operable program or batch file`

Moving the folder up to C:/ it builds just fine. 
- **What did you expect?** To build

### Source code / logs

Its probably caused by %~dp0 in the build.cmd file.

**Comment by danmosemsft** [comment]
@atotalnoob I'm surprised this wasn't reported in older repos like CoreFX that seem to have the same issue. But this requires both that you have a space in your profile and you clone your repo into your user profile. 

Could you try putting quotes around the `%~dp0...` in build.cmd, run.cmd, and native\build.cmd and see whether that is enough?
