### ISSUE TITLE
Add an evaluator for Bias and Fairness metrics

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#1911]
We currently have model evaluators that produce metrics on the predicted label. For practical use of machine learning, it is necessary to have a sense for any biases the model may propagate and any fairness issues the mode has. In this way, it would be great to have a standard evaluators for bias and fairness metrics.

Related to #511

**Comment by tauheedul** [comment]
@rogancarr If you need ideas on how this could be tackled in ML.NET, you may find it useful to research [Pymetrics Open Source Audit AI](https://www.infoq.com/news/2018/07/Pymetrics-Fair-Machine-Learning) 

Source: https://github.com/pymetrics/audit-ai

**Comment by codemzs** [comment]
thanks but not on the roadmap for the near future.
