### ISSUE TITLE
Add metadata of bias and fairness metrics to models

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#1912]
Currently, we can use ML.NET to evaluate the performance of a model. However, when the model is passed to a third party, any metrics must be passed separately.

If you consider the bias and fairness metrics** to be properties of the model, then it makes sense to include them in the model. I expect this to be helpful in deployment, productionization, debugging, etc. Plus it would be nice to have properties of the model visible in an IDE and accessible programatically.

Related to #511
Related to #1911 
Related to #1908

** e.g. over a dataset representative of the expected distribution of data to be seen by the model

**Comment by tauheedul** [comment]
Thank you, this is an important feature.
You may be interested to learn Microsoft published a paper in ICML 2018 covering [Machine Learning for Fair Decisions](https://www.microsoft.com/en-us/research/blog/machine-learning-for-fair-decisions/)

Please check out: [A Reductions Approach to Fair Classification](https://www.microsoft.com/en-us/research/publication/a-reductions-approach-to-fair-classification/)

arXiv: https://arxiv.org/abs/1803.02453
Source: https://github.com/Microsoft/fairlearn

**Comment by codemzs** [comment]
thanks but not on the roadmap for the near future.
