### ISSUE TITLE
Add tooling to measure bias metrics over datasets

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#1913]
Bias and fairness in predictions are big concerns with deploying ML models, and bias can work its way into ML models through the datasets they are trained on**. It would be helpful for modelers to have tools to assist in calculating standard metrics for bias over training data.

** Bias in the training data doesn't always translate evenly to the bias and fairness of the model's predictions, so we need separate evaluation metrics of bias and fairness for the model predictions (captured in #1911).

Related to #511 
Related to #1911 
Related to #1912

**Comment by codemzs** [comment]
thanks but not on the roadmap for the near future.
