### ISSUE TITLE
Support adding metadata to models

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#1915]
When a model is passed to a third party, information about the model, like the evaluation metrics, must be passed separately. It would be nice to have a supported way to encode metadata into models such that they can be visualized in an IDE and programatically extracted.

Related to #511 
Related to #1908 
Related to #1912

**Comment by rogancarr** [comment]
One specific ask in issue #511 is to allow VS to pull out metadata from the model and display it in the IDE. I'll add that to this issue; if we add metadata to the model format, then we can start a new issue to visualize that metadata.

**Comment by rogancarr** [comment]
@markusweimer @glebuk

**Comment by markusweimer** [comment]
Getting this into VS might take some time. How about we consider a `dotnet ML` command or such first?

Also, what metadata are you thinking about?

**Comment by rogancarr** [comment]
@markusweimer I agree about VS and I think it would be first good to have it available through a `dotnet ML` command and through `public` properties on the model.

For explainability, I think it would be useful to add metadata for model metrics:
- **Evaluation metrics**: I hand you a model, and you can see what the expected evaluation metrics (e.g. `AUC`) on the test distribution are.
- **Bias and fairness metrics**: I hand you a model, and you can see what the expected bias and fairness metrics (e.g. `FPR` for different protected-class-labels) on the test distribution are.

**Comment by codemzs** [comment]
thanks but not on the roadmap for the near future.
