### ISSUE TITLE
Adding Multiple Training Files to the Pipeline?

### ISSUE THREAD

**Issue by cflint987** [dotnet/machinelearning#192]
System information
    OS version/distro: Windows 7 Home
    .NET Version (eg., dotnet --info): ML .net V0.1.0

Issue:
What is the correct way to add multiple training files to a Learning Pipeline?

In the Taxi Fare example, just adding another textloader and/or ColumnCopier, etc seems to not be correct.

Example:
pipeline.Add(new TextLoader<TaxiTrip>(DataPath, useHeader: true, separator: ","));
pipeline.Add(new TextLoader<TaxiTrip>(DataPath2, useHeader: true, separator: ","));

**Comment by GalOshri** [comment]
Thanks for asking! This is not currently possible, but let's use this issue to track enabling multiple inputs in a pipeline.

Just to clarify: is your intention to concatenate the two files as soon as they are loaded, or to apply different transforms/trainers to them? 

A potential workaround for now is to read in the examples from both files into memory and use the `CollectionDataSource` (see example usage [here](https://github.com/dotnet/machinelearning/blob/6d5a41d39face9e98c242d3db3ff10ea8e233cc1/test/Microsoft.ML.Tests/CollectionDataSourceTests.cs)). You could also concatenate the two files into one CSV outside of the ML.NET pipeline.

**Comment by cflint987** [comment]
My intention is for creating and testing ML structures with large datasets to be modular and less taxing on file transfers to/from servers. For example, moving 100GB is to a server is easier if split by time or another parameter. It also allows ML structures to be updated as new data comes in without having to concat onto what are already are/is a large file.

Reducing the memory footprint by loading subsets of the data would be nice, but as I understand it, that is not possible for all ML structures.

I have concated the files and it works properly but this would be a nice feature to have.

Thanks for the answer.

**Comment by glebuk** [comment]
@cflint987, 
We have a work item to address your exact scenario. Please take a look at PR #61.   Feel free to comment and ask @tyclintw.
