### ISSUE TITLE
The demo code in ML.NET cookbook is incorrectly in the latest version v0.8.

### ISSUE THREAD

**Issue by sheng-jie** [dotnet/machinelearning#1935]
### System information

- **WIN 10**:
- **.NET Core V2.2**: 

### Issue

- The demo code in ML.NET cookbook is incorrectly  in the latest version v0.8.

### Source code / logs
```
// Create the reader: define the data columns and where to find them in the text file.
var reader = mlContext.Data.CreateTextReader(ctx => (
        // A boolean column depicting the 'target label'.
        IsOver50K: ctx.LoadBool(0),
        // Three text columns.
        Workclass: ctx.LoadText(1),
        Education: ctx.LoadText(2),
        MaritalStatus: ctx.LoadText(3)),
    hasHeader: true);
```
The `mlContext.Data.CreateTextReader` method is no longer exists in the latest version.

**Comment by Ivanidzo4ka** [comment]
CreateTextReader is extension method. Please make sure you have 
`using Microsoft.ML` 
and Microsoft.ML.Data project in references.

**Comment by sheng-jie** [comment]
@Ivanidzo4ka Yes, I am sure I have added the references. Are you sure your ML.NET version is v0.8?

**Comment by sfilipi** [comment]
The cookbook examples are actual tests, in the code. You can look at them [here](https://github.com/dotnet/machinelearning/blob/7faa46c41fcd1a214fac7bfbdc8a9d1adbcc8d41/test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamples.cs) and the [dynamic ones](test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs).

The example you reference is calling into [this](https://github.com/dotnet/machinelearning/blob/14c7a472579afa3ce98bad2e3495e4c0524471b9/src/Microsoft.ML.Data/StaticPipe/DataLoadSaveOperationsExtensions.cs#L36)

If ok, I am going to close the issue. Feel free to reopen, or open a new one if additional questions.

**Comment by gregmulvihill** [comment]
I think the issue may be that v0.8.0 on Nuget was compiled with mlContext.Data.TextReader (from 3bf74ed 11/27) vs mlContext.Data.CreateTextReader (14c7a47 12/7 forward).

References:
https://www.nuget.org/packages/Microsoft.ML/0.8.0
https://github.com/dotnet/machinelearning/blob/v0.8.0/test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs
