### ISSUE TITLE
Public constructors for GamModelParameters

### ISSUE THREAD

**Issue by najeeb-kazmi** [dotnet/machinelearning#1948]
Part of #1698 

Right now, in `BinaryClassificationGamModelParameters` and `RegressionGamModelParameters` we have constructors that look like the following;

```csharp
internal BinaryClassificationGamModelParameters(IHostEnvironment env, int inputLength, Dataset trainset,
            double meanEffect, double[][] binEffects, int[] featureMap)
            : base(env, LoaderSignature, inputLength, trainset, meanEffect, binEffects, featureMap) { }
```

We want to make public constructors for all `ModelParameters` (previously `predictors`). However, for GAMs, this requires the user to pass in a training set, which is a `Dataset` object in `Microsoft.ML.FastTree.Internal`. This is not something we should expect the end user of the API to be aware of, so the constructor was not made public. Currently, `Dataset` is needed in `GamModelParametersBase` to map features to flocks and get bin upper bounds. We should rewrite GAMs so that this information is passed on from the Trainer rather than be computed when constructing the `GamModelParameters`.

**Comment by rogancarr** [comment]
A lot of the information that the trainer passes to the `GAMPredictor` is internal training information. I'd like to separate this out so that GAM preprocesses this. We would also get a `GAMPredictor` object that we could then use with different methods of training, which is fun.

**Comment by glebuk** [comment]
@najeeb-kazmi - please verify that is done and close.
