### ISSUE TITLE
How to get ComponentCatalog from MLContext?

### ISSUE THREAD

**Issue by montebhoover** [dotnet/machinelearning#1949]
For NimbusML we have a "ManifestGenerator" that creates the EntryPoint manifest.json from a given set of ML.NET assemblies.  Currently we implement this the same way it is implemented in [TestEntryPoints.cs](https://github.com/dotnet/machinelearning/blob/337cc551f1a4fb45b5efc9797803c06bd451ee29/test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs#L349), but ConsoleEnvironment has been made internal, and ML.Context doesn't have a ComponentCatalog.  What are ways I could get access to a ComponentCatalog and use JsonManifestUtils to build a new manifest.json?

@Ivanidzo4ka @yaeldekel @ganik

**Comment by montebhoover** [comment]
#2063 addresses this.

**Comment by eerhardt** [comment]
> How to get ComponentCatalog from MLContext?

Cast it to an `IHostEnvironment` and use the `ComponentCatalog` property:

```C#
((IHostEnvironment)new MLContext()).ComponentCatalog
```

**Comment by montebhoover** [comment]
Thanks Eric!
