### ISSUE TITLE
List Loader

### ISSUE THREAD

**Issue by Sorrien** [dotnet/machinelearning#195]
I was looking through the ml.net api for a generalized data loader, and I could not find one. So here is my proposal:

Take the following example for the TextLoader:
```
var dataPath = "intents.txt";
pipeline.Add(new TextLoader<IntentData>(dataPath, separator: "tab"));
```

I would like to have something like this:
```
var intents = new List<IntentData();
intents.Add(new IntentData());
pipeline.Add(new ListLoader<IntentData>(intents));
```
With a generalized loader like this I would have a wider range of sources for my data.

**Comment by danmosemsft** [comment]
We are considering a broader set of loaders. What sources are you interested in using?

**Comment by GalOshri** [comment]
Would something like the `CollectionDataSource` work for this? See example usage [here](https://github.com/dotnet/machinelearning/blob/6d5a41d39face9e98c242d3db3ff10ea8e233cc1/test/Microsoft.ML.Tests/CollectionDataSourceTests.cs). 

This is not in the docs yet as it was added after the v0.1 release, but it will be added there soon.

**Comment by dotChris90** [comment]
I just saw it - what are your ideas about this loaders? Will they all implement the same Interface? In my opinion thats quite important. Just like in EF Core the SQL connectors implement totally the same Interface.

**Comment by Sorrien** [comment]
I would like to use JSON, SQL, and Entity Framework Core primarily.

**Comment by Sorrien** [comment]
@GalOshri That does look a lot like what i want, and I was not aware of that. I look forward to that being added.

**Comment by veikkoeeva** [comment]
For relational I'd like to use just plain ADO.NET, possibly Dapper or something alike. In other words, do not make EF a required dependency. :)

**Comment by Sorrien** [comment]
I'd prefer to be able to pass in data objects as a list to prevent exactly that. So you can use the database wrapper you want to use and then avoid any dependencies.

**Comment by veikkoeeva** [comment]
@Sorrien It's a good point. Maybe we should consider `IEnumerable`, `IAsyncEnumerable` `IObservable` (TPL, what have you, just to make sure the design adapts) also and if it were possibly so the pipeline could drain the source if needed. I'm not sure about `Stream`. I could imagine there'd be performance issues with larger data sets if it all would be needed in memory up-front.

**Comment by Sorrien** [comment]
I have now tested CollectionDataSource with the latest build of the project and it is exactly what I was looking for.
