### ISSUE TITLE
Update/Add Documentation for Ml.Net Dependencies 

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning#1952]
Trying to use existing samples on my Mac failed because I wasn't aware there were pre-reqs for the samples. (Most tutorials actually say "Prereq: None")

### System information

- **OS version/distro**: Mac
- **.NET Version (eg., dotnet --info)**:  Ml.Net 0.8.0

.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.101/

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.2.101 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

### Issue

- **What did you do?** 
Tried to use the example: https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ImageClassification_TensorFlow on a Mac

- **What happened?** 
Image /Users/jakeradzikowski/dev/experiment/mlNet/GitHubExample/ImageClassification/assets/inputs/images/broccoli.jpg was not found.

- **What did you expect?**
The above path does exist ... So I expected the image to be found and loaded. Does mlContext.Transforms.LoadImages work on a MacOS?

### Source code / logs

See the example referenced above.

**Comment by JakeRadMSFT** [comment]
Works fine on Windows.

**Comment by JakeRadMSFT** [comment]
Ping! Any updates?

**Comment by rustd** [comment]
This issue currently blocks the UI tooling for ML.NET. Can this issue be addressed sooner to unblock tooling work.?

**Comment by asthana86** [comment]
@codemzs @yaeldekel @shauheen anyone who can help us triage this further.

**Comment by Ivanidzo4ka** [comment]
We use System.Drawing.Common to load and process images.
https://github.com/dotnet/machinelearning/blob/master/docs/building/unix-instructions.md#user-content-macos please make sure you have all required dependencies especially mono-libgdiplus.

All we do internally is we call  `new Bitmap(path)`.
We run tests for images on every checking and it works all across our build systems.

**Comment by JakeRadMSFT** [comment]
@Ivanidzo4ka Is it expected that a developer would know that? The page you referenced is for building Ml.Net ... I'm just using it.

Does Ml.Net have documentation for pre-reqs for developers using Ml.net?

**Comment by Ivanidzo4ka** [comment]
>The page you referenced is for building Ml.Net ... I'm just using it.
Does Ml.Net have documentation for pre-reqs for developers using Ml.net?

Sorry, I don't have answer on that question. But I can always ask people who suppose to  know.

@eerhardt, @danmosemsft  Where dotnet specifies pre-required dependencies? ? Do you state that in nuget package, is it some documentation file or it's part of build instructions?

**Comment by rustd** [comment]
@jralexander can you please follow-up to the update the getting started tutorials for mac/windows/ linux per Eric's comment above?

**Comment by JRAlexander** [comment]
What would the differences be from the current .net core prereqs topics?

**Comment by JRAlexander** [comment]
What differences are there for ML.NET Package Windows/Linux/MacOS pre-reqs  vs the documented Windows/Linux/MacOS pre-reqs for .NET Core?

**Comment by JRAlexander** [comment]
@rustd -- I think this needs to be reassigned

**Comment by Ivanidzo4ka** [comment]
also libomp for LightGBM https://github.com/dotnet/machinelearning/issues/1282

**Comment by natke** [comment]
@codemzs We need a list of the runtime dependencies so that we can document them. Can you please ask someone on your team to provide this list? Thanks!

**Comment by harishsk** [comment]
The extra dependencies for ML.NET can be found here:

https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-extra-dependencies

Please reopen this issue if you find missing dependencies.
