### ISSUE TITLE
 internal static partial class Utils is not accessible anymore from NimbusML

### ISSUE THREAD

**Issue by ganik** [dotnet/machinelearning#1959]
This is a breaking changes in ML.NET 0.8 or later for NimbusML
Pls advise

**Comment by TomFinley** [comment]
Advice same as #1958.

**Comment by ganik** [comment]
There is a .net core component in NimbusML called DotNetBridge. It tightly integrates with ML.NET as it :
* Provides a IDataView over python data structures to ML.NET
* Implements IRowCursor over this IDataView
* Implements special RunGraph engine 
* Implements its own HostEnvironmentBase<T>
* Processes IDataView from ML.NET and sends it back to python

To specifically pinpoint why Utils is necessary, here is a piece of code that has been working till ML.NET 0.8 for cursor implementation:

            public IRowCursor[] GetRowCursorSet(out IRowCursorConsolidator consolidator, Func<int, bool> needCol, int n, IRandom rand = null)
            {
                _host.CheckValue(needCol, nameof(needCol));
                _host.CheckValueOrNull(rand);

                consolidator = null;
                var active = **Utils.BuildArray**(_columns.Length, needCol);
                return RowCursor.CreateSet(out consolidator, _host, this, active, n, rand);
            }

**Comment by TomFinley** [comment]
All right. External implementations of `IDataView` should be entirely possible. Indeed, my possibly incomplete understanding from @eerhardt is that `IDataView` is being considered to be generalized outside of ML.NET, so it better be. (Otherwise ML.NET itself could not work at all.)

`IHostEnvironment` is likewise a public interface, though our implementations of it are deliberately internal. Perhaps you can explain your needs here.

Regarding our little `Utils.BuildArray` convenience, I'm glad you found it useful, but because it has nothing to do with machine learning we will never make that part of the public surface of our API. Luckily what it does is trivial.

https://github.com/dotnet/machinelearning/blob/00577c06ff99ad07006ca8c58cf974943cb1971f/src/Microsoft.ML.Core/Utilities/Utils.cs#L716-L719

Your other scenarios, I don't understand. Again, possibly a candidate for my original advice. Think about it.

**Comment by TomFinley** [comment]
Hi @justinormont. Using our commands is fine, using entry-points is fine. However: if you had instead taken our implementation (which of course might utilize our internal code), copied the code over, slightly modified it, and expect *that* to work, which seems to be the state of NimbusML, then, like with NimbusML, you're going to have to find another way.

**Comment by montebhoover** [comment]
@TomFinley, thanks for the feedback on this and #1958. It sounds like refactoring the bridge code in NimbusML is the right answer for most of the cases listed above.  I'll be starting work on that along with @shmoradims.  Here is what I understand from your advice so far:

1. [`IRowCursor`](https://github.com/Microsoft/NimbusML/blob/80ce48f0505eba1564dafd2dfd249905ee7b6143/src/DotNetBridge/NativeDataView.cs#L221)
    1. Implement without [`Utils.BuildArray`](https://github.com/dotnet/machinelearning/blob/00577c06ff99ad07006ca8c58cf974943cb1971f/src/Microsoft.ML.Core/Utilities/Utils.cs#L711).
2. [`RunGraph`](https://github.com/Microsoft/NimbusML/blob/80ce48f0505eba1564dafd2dfd249905ee7b6143/src/DotNetBridge/RunGraph.cs#L88)
    1. *Either* change the way we do native data interop [`BytesToText`](https://github.com/Microsoft/NimbusML/blob/80ce48f0505eba1564dafd2dfd249905ee7b6143/src/DotNetBridge/Bridge.cs#L345) or continue using the `BytesToText` interop but implement parsing without ML.NET's [CmdParser](https://github.com/dotnet/machinelearning/blob/0c62e30b4d9eabb60322b2a3e75bc90e20007889/src/Microsoft.ML.Core/CommandLine/CmdParser.cs#L204).
3. [`HostEnvironmentBase`](https://github.com/Microsoft/NimbusML/blob/e1004720ec0c252ba87f02c190c33739d9c00f20/src/DotNetBridge/RmlEnvironment.cs#L13)
    1. Instead of inheriting from ML.NET's [`HostEnvironmentBase`](https://github.com/dotnet/machinelearning/blob/0c62e30b4d9eabb60322b2a3e75bc90e20007889/src/Microsoft.ML.Core/Environment/HostEnvironmentBase.cs#L98), NimbusML should implement it's own [`IHostEnvironment`](https://github.com/dotnet/machinelearning/blob/0c62e30b4d9eabb60322b2a3e75bc90e20007889/src/Microsoft.ML.Core/Data/IHostEnvironment.cs#L31).
    2. @yaeldekel how much work do you think it would take?  I particularly want to be able to implement [ComponentCatalog.RegisterAssembly](https://github.com/dotnet/machinelearning/blob/0c62e30b4d9eabb60322b2a3e75bc90e20007889/src/Microsoft.ML.Core/ComponentModel/ComponentCatalog.cs#L589).

@yaeldekel, @shmoradims, @ganik, are there any other areas of refactoring that I need to add?

**Comment by montebhoover** [comment]
4. [`ISchema`](https://github.com/Microsoft/NimbusML/blob/80ce48f0505eba1564dafd2dfd249905ee7b6143/src/DotNetBridge/NativeDataView.cs#L23)
    1. Replace with Schema.
5. [`Contracts`](https://github.com/Microsoft/NimbusML/blob/80ce48f0505eba1564dafd2dfd249905ee7b6143/src/DotNetBridge/NativeDataView.cs#L40)
    1. Implement own version of parameter checking.

**Comment by montebhoover** [comment]
ComponentCatalog.RegisterAssembly is addressed in #2063
