### ISSUE TITLE
Sort namespaces in source files as per Microsoft .NET convention

### ISSUE THREAD

**Issue by codemzs** [dotnet/machinelearning#1961]
Parent issue #1697 

StyleCop rules:
**SA1210:** Using directives must be ordered alphabetically by namespace.
**SA1208:** System using directives must be placed before other using directives.

**Comment by justinormont** [comment]
This is great; we should get ML.NET further into the conventions of .NET. Is there a list of them, or do they just follow StyleCop defaults?

cc: @danmosemsft
