### ISSUE TITLE
Remove `runtime` namespace from example code

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning#1964]
In #1956, we removed `runtime` from the namespaces. 

Now we have to update the example code.

For example, we moved:
* `Microsoft.ML.Runtime.Data` to `Microsoft.ML.Data`
* `Microsoft.ML.Runtime.TimeSeriesProcessing` to `using Microsoft.ML.TimeSeriesProcessing`
* `Microsoft.ML.Runtime.Learners` to `Microsoft.ML.Learners`

cc: @JRAlexander, @codemzs

**Comment by codemzs** [comment]
We should also remove Runtime references from the docs folder.

**Comment by codemzs** [comment]
Hi @justinormont which example code are you referring to? May be if you can provide a link to it from the repo?

**Comment by justinormont** [comment]
You're right. After your PR, I only see one additional reference to the removed `Runtime` namespace in the dotnet/machinelearning repo, which is in `ResultProcessor.cs`. 

I currently see [81 hits](https://github.com/dotnet/machinelearning-samples/search?q=%22ML.Runtime%22&unscoped_q=%22ML.Runtime%22) to `ML.Runtime` in the `machinelearning-samples` repo, so it seems the changes are needed there.

I created a new issue in the machinelearning-sample repo: https://github.com/dotnet/machinelearning-samples/issues/188

Feel free to close this issue; or keep it open to remind us to update the `machinelearning-samples` repo before the next release.

**Comment by codemzs** [comment]
@justinormont thanks for opening the issue for the sample’s repo. Out of curiosity where in resultprocessor.cs do you see a reference to Microsoft.ML.Runtime?

**Comment by Ivanidzo4ka** [comment]
@justinormont is this issue still relevant?

**Comment by justinormont** [comment]
@Ivanidzo4ka : I see [8 references](https://github.com/dotnet/machinelearning/search?q=%22ML.Runtime%22&unscoped_q=%22ML.Runtime%22) to the removed Microsoft.ML.Runtime namespace in this repo. Perhaps we need to propagate the removal of the Microsoft.ML.Runtime to the internal build.

**Comment by shmoradims** [comment]
All API reference samples have been cleaned up during API reference work. Please re-open if you still see issues.
