### ISSUE TITLE
wikipedia-detox-250-line-data.tsv: Unclosed quoted field on line 83.

### ISSUE THREAD

**Issue by djary** [dotnet/machinelearning#1970]
https://github.com/dotnet/machinelearning/blob/master/test/data/wikipedia-detox-250-line-data.tsv

We can make this file beautiful and searchable if this error is corrected: Unclosed quoted field on line 83.
pls fixit

**Comment by justinormont** [comment]
This appears to be a duplicate...

https://github.com/dotnet/machinelearning/pull/730
https://github.com/dotnet/machinelearning/issues/245

In previous discussion, it was decided that the file should stay as is, and the loader function should be updated to better suit the format for the file. I'm unsure if the the last step was completed.
