### ISSUE TITLE
Internalize signature delegates in Core and Data assemblies

### ISSUE THREAD

**Issue by TomFinley** [dotnet/machinelearning#1974]
We have these "signature" delegates throughout the codebase, used for purposes of entry-points and other dependency injection style things.

Many are public, as we see here.

https://github.com/dotnet/machinelearning/blob/7e21afa4612ddca53bbf9d67b84df2b58d4636c2/src/Microsoft.ML.Data/Dirty/ILoss.cs#L49

Yet there is no need for them to be public, and many of these have already been "internalized," e.g.:

https://github.com/dotnet/machinelearning/blob/7e21afa4612ddca53bbf9d67b84df2b58d4636c2/src/Microsoft.ML.Core/Prediction/ITrainer.cs#L20

We should complete this work, since we do not want these as part of the public surface of the API.

**Comment by abgoswam** [comment]
@TomFinley . Can I assign this to myself and start working on this ?  (I don't see the up-for-grabs label, hence asking)

**Comment by Ivanidzo4ka** [comment]
We have plenty of `Lockdown assembly ` issues, and I assume internalization of delegates in that assemblies would happen automatically. But we don't have "lockdown" issues for Core and Data assembly, so I'm renaming this issue to reflect scope of work.
