### ISSUE TITLE
EvaluatorBase and IEvaluator internalization

### ISSUE THREAD

**Issue by TomFinley** [dotnet/machinelearning#1976]
We should consider internalizing `IEvaluator` and all implementations of it. The reason we might be able to do so is that while the code to do evaluation must exist somewhere, we are currently exposing the way we compute metrics via `MLContext`, as we see here:

https://github.com/dotnet/machinelearning/blob/7e21afa4612ddca53bbf9d67b84df2b58d4636c2/src/Microsoft.ML.Data/TrainContext.cs#L232

So it is not clear to me that `IEvaluator` needs to be part of our public API.

If this for some reason proves impractical for reasons I do not appreciate yet, we must then refactor the evaluators so that they are engineered so that they expose fewer of their guts for everyone to see. For example:

`public sealed class AnomalyDetectionEvaluator : EvaluatorBase<AnomalyDetectionEvaluator.Aggregator>`

That we might have an `IEvaluator` and a convenience class is fine, but the generic parameter describes something that the user should not need to know about, e.g., how it collates and computes the metrics.

**Comment by TomFinley** [comment]
This also includes especially the MamlEvaluator stuff, in case it was not clear.

**Comment by wschin** [comment]
I will do this before working on #1795 which depends on this issue.
