### ISSUE TITLE
Missing Values (from a CSV file) and how TextLoader processes them

### ISSUE THREAD

**Issue by MagicMaxxx** [dotnet/machinelearning#1980]
### System information
- **OS version/distro**:
Windows 10 Home
- **.NET Version (eg., dotnet --info)**: 
.NET Core 2.1.5
ML.NET 0.8

### Issue
When I read the Titanic data set from Kaggle and TextLoader reads missing numeric values as ZEROES. 

- **What did you do?**
I removed a data from AGE column and I tried to use context.Transforms.IndicateMissingValues and/or context.Transforms.ReplaceMissingValues in order to process the missing values but got no luck as TextLoader processes empty/missing values as ZEROES so there are no NaN values in the Data View processed by IndicateMissingValues/ReplaceMissingValues 

- **What happened?**
Data sample:

PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,0,3,"Braund, Mr. Owen Harris",male,,1,0,A/5 21171,7.25,,S
Take a look - there is no age (it goes after "male") but TextLoader reads the data like that passenger's age == 0

- **What did you expect?**
I expected to see something like NaN or similar value in the data when there is an empty space in the file in the cell/position related to the related portion of the data

### Source code / logs
Here is how I create the TextLoader, BTW when I use AllowQuoting = false it can't read names even if I use Separator = "," - it uses " " (the very first space in the name) as a separator
            return context.Data.TextReader(new TextLoader.Arguments()
            {
                HasHeader = true, Separator = ",", TrimWhitespace = true, AllowSparse = false, AllowQuoting = true, 
                Column = [...columns array...]
            });
I'd prefer to have some kind of one more settings for the TextLoader - something like NanIfEmpty (?) true/false

Thank you!

**Comment by Zruty0** [comment]
We don't have a 'faithful' CSV reader (the one that reads the file strictly according to the CSV spec).
What we do have is an ability to tweak our `TextLoader` to be able to recognize `,` as a separator. This will result in *most* CSV files being readable, but yours is an exception.

ML.NET generally expects missing values to be encoded as `?`. I don't recall what we do with an empty string, but I suspect that it depends on `AllowQuoting`.

The only thing I can recommend is to read this value as a text column, and then use custom mapping (or value mapping, if you wait till 0.9) to perform the `v == "" ? float.NaN : float.Parse(v)` operation over that specific column.

As for the ML.NET team, I am not sure if we should clean up the story about empty strings (that sometimes `TextLoader` parses them as missing values, and sometimes as NAs). 

I would probably have consistent behavior here:
- For NA-capable types, empty string is parsed as NA
- For text, empty string is a legal value
- For non-NA-capable types, empty string causes an exception to be thrown. (this last one is probably the most controversial).

**Comment by shmoradims** [comment]
@TomFinley / @shauheen, do we want to clean up the story about empty strings as Pete mentioned above?

**Comment by shmoradims** [comment]
@MagicMaxxx did @Zruty0's suggestion above work for you? If so, could you please close this issue?

**Comment by MagicMaxxx** [comment]
Hello

Sorry for the delay but I can't close the issue as even if I update ML.NET up to version 0.9 I can see that nothing changes - I still can see "0" if there is no value for the particular column (AGE in our example). I can place "?" to the row into the AGE column but what about other rows - do you want me to place "?" to all the rows in the file?! For example, in the Titanic TRAIN file/dataset I found 705 ",," matches for 892 rows, so - bad Idea...

About suggestion to read that column as a text column - in this case, in order to process the missing values for the whole file in the correct way, I have to use that approach for THE ALL columns in the file (and for the all files I want to process with ML.NET in the future), not just for the AGE column, and I don't think that this is the correct approach. 

From my point of view, ML.NET should handle NULL values as is described here: https://github.com/dotnet/machinelearning/blob/master/docs/code/IDataViewTypeSystem.md#missing-value (see "converting a text NA value to R4 produces a NaN"), so - to produce NaN values but not zeroes. In order to give a developer ability to choose how to process missing values (as I already suggested), it would be great to have some other settings for the TextLoader.Arguments class, like NanIfEmpty (?) true/false

Thank you!
