### ISSUE TITLE
LightGBM Random Forest

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning#1992]
LightGBM added [random forest support](https://github.com/Microsoft/LightGBM/pull/678) in July 2017. ML.NET should expose this functionality. 

This is exposed as another booster type. Currently we support { Tree Booster, Dropout Tree Booster, and Gradient-based One-Size Sampling } ([src](https://github.com/dotnet/machinelearning/blob/c5a18ef512ecf880eeba41483e4e300c9e0cf8e7/src/Microsoft.ML.LightGbm/LightGbmArguments.cs#L201-L352)) boosters of LightGBM.

For our defaults for the new booster type we could copy the test:
https://github.com/Microsoft/LightGBM/blob/fb28070e1daa500b087d3102145ae48988030195/tests/python_package_test/test_engine.py#L53-L62

I don't see that LightGBM provides a default for these parameters. So we need to provide reasonable defaults for the user; without ff/bagfrac set to <1.0, LightGBM throws an error. I think `ff=0.5` & `bagfrac=0.5` may be a bit low; perhaps 0.7? As always benchmarks on representative datasets speak louder than I.

This adds to our existing FastTree Random Forest implementation, and is another implementation that could be use for #1729.

**Comment by yaeldekel** [comment]
Hi @justinormont , thanks for the suggestion! I am not sure if we can add new features before 1.0, but we should definitely triage this.

**Comment by Ivanidzo4ka** [comment]
I notice some work by @singlis regarding LightGBM and bringing monotonic support. Do you have time to look on random forest support?
