### ISSUE TITLE
CreateStreamingDataView does not exist in MLContext

### ISSUE THREAD

**Issue by zish82** [dotnet/machinelearning#1993]
### System information

- **All**:
- **All**: 

### Issue

- **What did you do?** Tried to access CreateStreamingDataView method
- **What happened?** It does not exits in MLContext, has it moved or should i be using something else?
- **What did you expect?** i expected to be able to load data using CreateStreamingDataView

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by sfilipi** [comment]
Hi @zish82. [CreateStreamingDataView ](https://github.com/dotnet/machinelearning/blob/a570da14a41f2870eb8f61d84496a58422398253/src/Microsoft.ML.Data/Utilities/ComponentCreation.cs#L104)has not moved. (follow the link to the source, to see the method on the HostEnvironment). 

It is also in several of our tests, that run on every build. 

If you don't see it, please add the 'Microsoft.ML.Data' namepaces.

**Comment by yaeldekel** [comment]
Thank you @sfilipi  for your reply. @zish82 , could you confirm that when using the Microsoft.ML.Data namespace you could use CreateStreamingDataView?

**Comment by TomFinley** [comment]
Hi @sfilipi and @yaeldekel , this is an old style extension that operates over `IHostEnvironment`, I might expect that we'd make this an extension over `DataOperationsCatalog` instead (but also make it in `Microsoft.ML` namespace), since operating over `MLContext` directly is a bit *too* high level.

**Comment by zish82** [comment]
Hi Guys,
It worked as you suggested by adding ML.Data namespace. For some reason my VS was not suggesting that!

**Comment by ziad-akiki** [comment]
With the latest ML.net 0.10.0 `CreateStreamingDataView` went missing (I have Microsoft.ML.Data namespace included). What's the replacement?

**Comment by doghappy** [comment]
@ziad-akiki I didn't find the method **[CreateStreamingDataView](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Data/Utilities/ComponentCreation.cs)**,  but `AsEnumerable()` doesn't exist too.

code from [ms docs](https://docs.microsoft.com/zh-cn/dotnet/machine-learning/tutorials/sentiment-analysis#predict-the-test-data-outcomes-with-the-saved-model)

```cs
// Create prediction engine
var sentimentStreamingDataView = mlContext.CreateStreamingDataView(sentiments);
var predictions = loadedModel.Transform(sentimentStreamingDataView);

// Use the model to predict whether comment data is toxic (1) or nice (0).
var predictedResults = predictions.AsEnumerable<SentimentPrediction>(mlContext, reuseRowObject: false);
```
