### ISSUE TITLE
StopwordsRemovingEstimator direct instantiation tests/samples?

### ISSUE THREAD

**Issue by TomFinley** [dotnet/machinelearning#1996]
We have #1646 introduced the estimator for stopwords removal, and the estimator, as `StopwordsRemovingEstimator` and transform. Howeve,r we did not directly test it, though it is being tested through the text transform. We should probably have direct tests for it, as well as an extension emthod for the text transformation catalog through `MLContext`.

This also makes me wonder if we've added other text featurizing things. That should be checked as well.

**Comment by TomFinley** [comment]
Also I see the constructor for some of these takes value-tuples, which may make this method somewhat difficult to use from, say, F#, perhaps.

**Comment by TomFinley** [comment]
Also it is unclear to me how to use one of our pre-defined lists of stopwords if someone uses this directly. Surely that is functionality we want to expose? I guess people could use the text featurizing estimator, but surely this should be exposed through this as well. So it seems like this whole pathway needs some polish.

**Comment by shauheen** [comment]
addressed in #2236
