### ISSUE TITLE
DataKind Enum is not well documented

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#2006]
This issue was initially logged in the dotnet/docs repo [9278](https://github.com/dotnet/docs/issues/9278) and [9184](https://github.com/dotnet/docs/issues/9184). 

@TomFinley, @CESARDELATORRE, @eerhardt Is the DataKind Enum something that will remain user facing, or will it get behind the .net types?

Should we document the DataKind or cleanup our error messages, and usage to not contain references to the DataKind anymore like #1943 suggest?

cc @mairaw @JRAlexander

**Comment by TomFinley** [comment]
We do not want `DataKind` visible anywhere. This is why `ColumnType` now has it as private. It ought to be deleted. Anywhere currently using `DataKind` should use some other mechanism. The only place we *might* want something like it is a place like `TextLoader` or whatever, to describe what type of item should be loaded from whatever fields of the text file we are reading, but even then it is questionable. It should not be a first class citizen in dataview land.

**Comment by JRAlexander** [comment]
@TomFinley - What should be used in place of DataKind for TextLoader field definition? Is there a best practice that you would recommend as you've said that use case is questionable?

**Comment by sfilipi** [comment]
Since I opened this, to make this issue actionable, and not just a discussion placeholder: 

1- I'll rename this issue to: Substitute internal usage of DataKind by the actual .net respective System.Type. IMO that can be done post Project 13 but please review its pri.  

2- There is already an issue to cleanup the error messages from mentioning `DataKind`.
This is already in Project 13. 

3- Open an issue about investigating the TextLoader to potentially using the respective System.Type to load. Address backwards compatibility.  

cc @shauheen @glebuk @CESARDELATORRE to arrange priorities.

**Comment by TomFinley** [comment]
> 3- Open an issue about investigating the TextLoader to potentially using the respective System.Type to load. Address backwards compatibility.

See, *that* I might like even less than an enum, because it's less restrictive in a bad way. The set of types that the text loader can load is certainly finite. So, it should be somehow enumerated in a finite set, either in a finite set of an enum, or a finite set of calls with specific names (with the suggestion they are associated with specific types -- that type not being one provided by the user). Just clarifying, that while I don't like an enum, there are some things I might like even less than that. :)
