### ISSUE TITLE
Bring back support for `ConfusionMatrix`  in the new API

### ISSUE THREAD

**Issue by abgoswam** [dotnet/machinelearning#2009]
While updating tests from the old AP to the new API, we found that  the new API does not support  `ConfusionMatrix`  in the evaluation output.

https://github.com/dotnet/machinelearning/blob/21d64aa5781750bfaddad262100c54989e8901f8/src/Microsoft.ML.Data/Evaluators/MultiClassClassifierEvaluator.cs#L506-L520

In the Legacy API,  there was support for  `ConfusionMatrix`

https://github.com/dotnet/machinelearning/blob/21d64aa5781750bfaddad262100c54989e8901f8/src/Microsoft.ML.Data/Evaluators/MultiClassClassifierEvaluator.cs#L1031-L1049

We should add back the  checks for `ConfusionMatrix`  in the following tests : 
- TrainAndPredictIrisModelTest
- TrainAndPredictIrisModelWithStringLabelTest

@codemzs  @Ivanidzo4ka

**Comment by bartczernicki** [comment]
+1 this is really silly that we don't have a Confusion Matrix output.  I realize this can be calculated on your own, but this one of the fundamental performance constructs that get reported in most ML software/libraries.

**Comment by Ivanidzo4ka** [comment]
We have one month before we lock our code in preparation for 1.0 release. It's a nice thing to have, but we just don't have time to focus on this right now. 
Unless you think it's a game changer and necessary to have.

**Comment by bartczernicki** [comment]
@Ivanidzo4ka I completely understand there is 1.0 pressure.  I think having core performance conventions and explain-ability aligned with basic ML software should be prioritized for post 1.0.
