### ISSUE TITLE
how could i add some extra fields to the "IrisDataWithStringLabel" as features?

### ISSUE THREAD

**Issue by BeanHsiang** [dotnet/machinelearning#201]
e.g.   class IrisDataWithStringLabel in “/Scenarios/IrisPlantClassificationWithStringLabelTests.cs”
If i want to add some other fields to the "IrisDataWithStringLabel “ as extra features as below after "TextLoad" step ,  but these extra fields won' t be loaded from data file(maybe calculate in runtime), how could i define step and set value of that in pipline?

```csharp
public class IrisData
 {
            [Column("0")]
            public float SepalLength;

            public float SepalLength;

            [Column("1")]
            public float SepalWidth;

            [Column("2")]
            public float PetalLength;

            [Column("3")]
            public float PetalWidth;

            [Column("4")]
            [ColumnName("Label")]
            public string Labe;

            public float Color;  // -> here is my issue
}
```

Any help please?

**Comment by GalOshri** [comment]
The `IrisData` class in this case defines the schema of input to the `TextLoader` (which columns to read from the file). It does not need to include features that are added within the `LearningPipeline`. In the Iris example [here](https://github.com/dotnet/machinelearning/blob/86f5ee663611f6c97ddb87be1150601018d74b4b/test/Microsoft.ML.Tests/Scenarios/IrisPlantClassificationWithStringLabelTests.cs#L27), `ColumnConcatenator` creates a new column called "Features" which combines several other columns.

If you are augmenting the data before adding it to the `LearningPipeline`, take a look at `CollectionDataSource` (sample usage [here](https://github.com/dotnet/machinelearning/blob/6d5a41d39face9e98c242d3db3ff10ea8e233cc1/test/Microsoft.ML.Tests/CollectionDataSourceTests.cs)).

How are you calculating these additional features?

**Comment by BeanHsiang** [comment]
@GalOshri 
that's what exactly i want! but the “CollectionDataSource” class hasn't been contained in v0.1 yet.
is there an alternative one?

**Comment by GalOshri** [comment]
That's great to hear. While waiting for v0.2, you could try to build from source by following the instructions [here](https://github.com/dotnet/machinelearning/blob/3012428bdf2629c991f1dd90eac7d424b20a2fcf/docs/project-docs/developer-guide.md). After the initial build, running `build.cmd -BuildPackages` will create a NuGet package you can use.

**Comment by BeanHsiang** [comment]
@GalOshri
thx a lot, that works fine for me now. but waiting for v0.2 release.
