### ISSUE TITLE
Recommendation as a method on MLContext object

### ISSUE THREAD

**Issue by zeahmed** [dotnet/machinelearning#2014]
Regression, BinaryClassification and MulticlassClassifcation context appear as properties on MLContext object while Recommendation context appear as method. Also tooltip is showing incorrect help.

![image](https://user-images.githubusercontent.com/38438266/50666493-d15c9880-0f69-11e9-8c58-fcc593e477ec.png)

**Comment by Ivanidzo4ka** [comment]
duplicate https://github.com/dotnet/machinelearning/issues/1827
