### ISSUE TITLE
Add a method in DataOperationsCatalog that creates an IDataView from an IEnumerable<T>

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#2025]
Currently we have an extension method CreateStreamingDataView in ComponentCreation that operates over IHostEnvironment. We should add an extension over DataOperations instead, and consider making the current one internal.
Related to #1993 .

**Comment by TomFinley** [comment]
> and consider making the current one internal.
> Related to #1993 .

Yes, or, probably actually deleting outright. Similar for other things in ComponentCreation, since that is part of the "old world" of the APIs that is no longer relevant in ML.NET land.
