### ISSUE TITLE
Internalization of CacheDataView and IRowSeekable

### ISSUE THREAD

**Issue by TomFinley** [dotnet/machinelearning#2028]
One thing we may want to consider is that, while having caching is nice and necessary, and we should expose some ability to *perform* caching if we want (as we do with the, exposing `AppendCacheCheckpoint`, as seen here:

https://github.com/dotnet/machinelearning/blob/5c00980abeae594161d0b9ee748d7d0b959962b5/src/Microsoft.ML.Data/DataLoadSave/EstimatorChain.cs#L99

This itself *uses* `CacheDataView`, but does not expose it. I am somewhat uncomfortable exposing the cache data view as part of our public API in a way that makes it a first class citizen of the API, at least, in v1.0 of the API. Its particular interface is a bit odd (possibly for good reasons, but odd nonetheless), and most of the reasons for its oddness have to do with how components might want to behave "specially" with it, and component authoring scenarios are not a target for v1.0. So hiding it, and `IRowSeekable` (which is a useful but, again, somewhat odd interface), might be good.

**Comment by wschin** [comment]
Hello Tom,
I don't see `CacheDataView` explicitly used in `AppendCacheCheckPoint`. Do you mean this
```csharp
        public DataView<TShape> Cache()
        {
            // Generate all column indexes in the source data.
            var prefetched = Enumerable.Range(0, AsDynamic.Schema.Count).ToArray();
            // Create a cached version of the source data by caching all columns.
            return new DataView<TShape>(Env, new CacheDataView(Env, AsDynamic, prefetched), Shape);
        }
```
? But anyway, I will make CacheDataView internal. Many thanks for those detailed instructions.

**Comment by TomFinley** [comment]
> Hello Tom,
> I don't see `CacheDataView` explicitly used in `AppendCacheCheckPoint`. Do you mean this
> 
> ```cs
>         public DataView<TShape> Cache()
```

Hmmm. Not sure. Maybe I misspoke. But, yes, you have the right idea, the idea is that from an external user's perspective, the APIs we do have around caching never make use of anything except the public idioms like estimator, transformer, data views...
