### ISSUE TITLE
ML.NET repo does not have a place to showcase community examples

### ISSUE THREAD

**Issue by shauheen** [dotnet/machinelearning#203]
- I expect the repo to have a .md file such as GALLERY.md to showcase the examples that the community does with ML.NET

- Currently we are missing this.

**Comment by justinormont** [comment]
Where in the repo should it be?

Perhaps the showcase can be included in main samples: 
```
Samples
├── README.md 
│   ├── img            <-- images if the sample warrants  
```

The README.md can have a summary of each Sample, both for the ones which we provide source code, and ones we only summarize and link to.

Samples are being added in pull request https://github.com/dotnet/machinelearning/pull/198.

Examples of github showcases:
* https://github.com/mui-org/material-ui/blob/master/docs/src/pages/discover-more/showcase/showcase.md
* https://github.com/botui/botui/blob/master/Showcase.md
* https://github.com/louisdh/panelkit/blob/master/SHOWCASE.md
* https://github.com/AsyncDisplayKit/Documentation/blob/master/docs/showcase.md
* https://github.com/airbnb/lottie/blob/master/docs/community-showcase.md
* https://github.com/material-next/material-next/blob/master/docs/src/pages/discover-more/showcase.md

**Comment by mitevpi** [comment]
Is there currently a place for the community to submit code samples? I'm just discovering this work (great stuff by the way), and may have an opportunity to submit samples and accompanying documentation/data sets. Wondering if a place already exists for that or if I should set that up as part of my work.

**Comment by jwood803** [comment]
I would think the community can add a PR for their samples in the [samples repo](https://github.com/dotnet/machinelearning-samples). I'm wondering if we should have a link in the README here to have an easier access point to it.

**Comment by whatevergeek** [comment]
i agree with @jwood803 
would be good if we keep the main machinelearning repo lightweight
and have community samples on the [samples repo](https://github.com/dotnet/machinelearning-samples)

**Comment by aadithpm** [comment]
Is this issue still open? If it is, would it be possible to assign it to me?

**Comment by artidoro** [comment]
@GalOshri @CESARDELATORRE, do you guys have a suggestion on where this should be?

Personally, I like the idea of having the samples in the samples repo. We should however make sure it is visible from the README, and invite the community to send PRs for those.

**Comment by CESARDELATORRE** [comment]
This is a good idea, we can create an additional page in the ML.NET-Samples repo with links pointing to samples from the community and keep evolving it and updating it when any of us identifies any good sample from the community or anyone in the community can also submit a PR adding a link for his sample so we can review it and add it, too.
It’ll be segregated from our own official samples but we can put a link from the main page at ML.NET samples repo to the .MD we’ll use for this. 
:) great idea to bump the community further! :)
I’ll reply to this thread when I create the first version of that .MD page at the samples repo, ok? :)

**Comment by CESARDELATORRE** [comment]
I have created the first draft version of this page: COMMUNITY SAMPLES, here:

https://github.com/dotnet/machinelearning-samples/blob/master/docs/COMMUNITY-SAMPLES.md

Please, add/answer to [this thread](https://github.com/dotnet/machinelearning-samples/issues/86) with any cool ML.NET sample you might know about and once we have a good list, we'll promote it from the home page of the ML.NET Samples repo, ok? 👍

**Comment by CESARDELATORRE** [comment]
Please, if you guys have cool ML.NET samples in your personal repose, add them here so we'll point to them from that page.

Provide info about your samples here: https://github.com/dotnet/machinelearning-samples/issues/86
