### ISSUE TITLE
When in debug loading ML model fails with "Unknown file type"

### ISSUE THREAD

**Issue by mikaelm12** [dotnet/machinelearning#2034]
When in debug, I get an exception, "Unknown file type", when I try to load an already trained ML model. The weird thing is that this only happens in debug. Any idea as to why this is failing? Thanks

**Comment by Ivanidzo4ka** [comment]
Can you share your model for better investigation?

**Comment by fantaclaus** [comment]
**In fact, it is not a failure.** It's an internal exception that is catched and handled inside the library. 

Just click `Continue` or press `F5` when you get stopped in the debugger.

Or if you don't want to stop each time in the debugger just uncheck "Break when `Common Language Exceptions` is thrown" in the debugger's Exception settings.

**Comment by codemzs** [comment]
please provide more details with model and repro steps. closing until then.
