### ISSUE TITLE
ReplaceMissingValues' input argument type

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#2038]
Most transforms use string as column names but in the function below, users need to create `ColumnInfo` first.
```
        public static MissingValueReplacingEstimator ReplaceMissingValues(this TransformsCatalog catalog, params MissingValueReplacingTransformer.ColumnInfo[] columns)
```
Is it appropriate to use
```
        public static MissingValueReplacingEstimator ReplaceMissingValues(this TransformsCatalog catalog, string[] inputs, string[] outputs)
```
or
```
        public static MissingValueReplacingEstimator ReplaceMissingValues(this TransformsCatalog catalog, params (string, string) inputOutputColumnPairs)
```
?

**Comment by yaeldekel** [comment]
Hi @wschin , thanks for looking into this issue. I think the reason that the input for ReplaceMissingValues is an array of ColumnInfo, as opposed to, for instance, the input for IndicateMissingValues, is that there are additional arguments that can be specified per column (bool ImputeBySlot and ReplacementMode Replacement). There is also a convenience constructor that takes one input column name, one output column name and an optional ReplacementMode value. This seems to me like the most common use case, with the other constructor being used for advanced scenarios. Do you think a third constructor would be useful in this case?

**Comment by wschin** [comment]
For convenience constructor, do you mean
```
            public ColumnInfo(string input, string output = null, ReplacementMode replacementMode = MissingValueReplacingEstimator.Defaults.ReplacementMode,
                bool imputeBySlot = MissingValueReplacingEstimator.Defaults.ImputeBySlot)
            {
                Contracts.CheckNonWhiteSpace(input, nameof(input));
                Input = input;
                Output = output ?? input;
                ImputeBySlot = imputeBySlot;
                Replacement = replacementMode;
            }
```?
I don't see such a constructor to `MissingValueReplacingTransformer`. Because no constructor of `MissingValueReplacingTransformer` takes column names as input columns, it was a bit odd at my first use of it (most transformers/estimators can work with column names directly).
