### ISSUE TITLE
Code in Documentation Not Working

### ISSUE THREAD

**Issue by daholste** [dotnet/machinelearning#2039]
### Issue

- **What did you do?**
Navigated to https://github.com/dotnet/machinelearning/blob/80f5720438d544b1c9cf019a889479d8e67d5837/docs/code/SchemaComprehension.md

Noticed that the code uses Microsoft.ML.Data.TlcEnvironment that no longer exists

@justinormont had a great suggestion -- perhaps wrap each documentation code sample in a unit test to prevent breakage?

**Comment by shmoradims** [comment]
Already closed by #2845.
