### ISSUE TITLE
CSharpApi.cs is autogenerated file which I have no idea how to generate

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#204]
We used to have instruction inside https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML/CSharpApi.cs how to regenerate it in case of changes and new entrypoints. Now it's unclear, at least for me.

**Comment by Ivanidzo4ka** [comment]
@codemzs  @glebuk  do you guys knew answer?

**Comment by GalOshri** [comment]
I believe you need to run the test [GenerateCSharpAPI](https://github.com/dotnet/machinelearning/blob/c023727b76970ab913ec1ce38276508835c17bcf/test/Microsoft.ML.Tests/CSharpCodeGen.cs#L19). 

It would be great to document this somewhere.

**Comment by codemzs** [comment]
This is a temporary solution until we get command line working via dotnet.exe. @Ivanidzo4ka please run that test and put Fact skip back when you are done generating the APIs.

**Comment by Ivanidzo4ka** [comment]
https://github.com/dotnet/machinelearning/blob/9e0a4bad5819de1ecafb8df5f4d82fd6dda22c2d/test/Microsoft.ML.Tests/CSharpCodeGen.cs#L20
RegenerateCSharpApi will do a trick.

**Comment by jwood803** [comment]
#371 will get rid of the need for this, though, correct?
