### ISSUE TITLE
MLContext.Log to become event?

### ISSUE THREAD

**Issue by TomFinley** [dotnet/machinelearning#2042]
Consider this:

https://github.com/dotnet/machinelearning/blob/faffd179c961f120ec4e6babb06bbfb2cca6a6ea/src/Microsoft.ML.Data/MLContext.cs#L64

If that were instead an event, we would gain some benefits, specifically, some measure of protection again line X registering some logging, then line X+N in some way registering more logging that in some way undoes the original logging. (It is linguistically simpler to perform this "wrong" action in C#, so some guard against it may certainly be worthwhile.)

/cc @stephentoub

**Comment by mareklinka** [comment]
I'd like to get involved with this, seems like a nice and easy starting point.
