### ISSUE TITLE
Update broken documentation code

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#2054]
For example: https://github.com/dotnet/machinelearning/blob/80f5720438d544b1c9cf019a889479d8e67d5837/docs/code/SchemaComprehension.md.

Related to #2039 .

**Comment by zeahmed** [comment]
@yaeldekel, It seems like duplicate of #2039. Do you want to keep it? Can you please add more detail if its not duplicate? Thanks!
