### ISSUE TITLE
Roadmap needs updating

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning#2074]
Our [READMAP.md](https://github.com/dotnet/machinelearning/blob/master/ROADMAP.md) has gotten rather out-of-date. 

The current roadmap should reflect the progress we made.

It may also be helpful to have a CHANGELOG.md at the root folder which links to each of the detailed [release notes](https://github.com/dotnet/machinelearning/tree/master/docs/release-notes), and provides a few-line summary in a unified location. Currently it would be difficult to scroll though the releases for the last few months (which is overly optimistic for how often I update packages). There is a [releases tab](https://github.com/dotnet/machinelearning/releases) for GitHub, which is very similar, though I'm uncertain if this content is under version control which would cause it (possibly) not follow forks.

**Comment by jwood803** [comment]
@justinormont Would it be best to update the roadmap where it crosses out each of the items that are now implemented and has a link to the appropriate release where it went in?
