### ISSUE TITLE
Move public facing classes used in Samples into appropriate namespaces.

### ISSUE THREAD

**Issue by codemzs** [dotnet/machinelearning#2075]
As part of the grand rename of namespaces, let's finalize the set of namespaces of public-facing components.

| Class/Interface/Enum/Delegate                           | Current Namespace      | New Namespace                                                 | Current Path                                                              |
|---------------------------------------------------------|------------------------|---------------------------------------------------------------|---------------------------------------------------------------------------|
| TransformerScope                                        | Microsoft.ML.Data      | Microsoft.ML                                                  | E:\machinelearning\src\Microsoft.ML.Data\DataLoadSave\TransformerChain.cs |
| ITransformerChainAccessor                               | Microsoft.ML.Data      | Microsoft.ML                                                  | E:\machinelearning\src\Microsoft.ML.Data\DataLoadSave\TransformerChain.cs |
| TransformerChain                                        | Microsoft.ML.Data      | Microsoft.ML                                                  | E:\machinelearning\src\Microsoft.ML.Data\DataLoadSave\TransformerChain.cs |
| IDataView                                               | Microsoft.ML.Data      | Microsoft.ML                                                  | E:\machinelearning\src\Microsoft.ML.Core\Data\IDataView.cs                |
| ISchema                                                 | Microsoft.ML.Data      | ?                                                             | E:\machinelearning\src\Microsoft.ML.Core\Data\IDataView.cs                |
| delegate void ValueGetter<TValue>(ref TValue value);    | Microsoft.ML.Data      | ?                                                             | E:\machinelearning\src\Microsoft.ML.Core\Data\IDataView.cs                |
| abstract class Row                                      | Microsoft.ML.Data      | ?                                                             | E:\machinelearning\src\Microsoft.ML.Core\Data\IDataView.cs                |
| CursorState                                             | Microsoft.ML.Data      | ?                                                             | E:\machinelearning\src\Microsoft.ML.Core\Data\IDataView.cs                |
| abstract class RowCursor                                | Microsoft.ML.Data      | ?                                                             | E:\machinelearning\src\Microsoft.ML.Core\Data\IDataView.cs                |
| interface IRowReadableAs<TRow>                          | Microsoft.ML.Data      | ?                                                             | E:\machinelearning\src\Microsoft.ML.Data\DataView\TypedCursor.cs          |
| class RowCursor<TRow>                                   | Microsoft.ML.Data      | ?                                                             | E:\machinelearning\src\Microsoft.ML.Data\DataView\TypedCursor.cs          |
| interface ICursorable<TRow>                             | Microsoft.ML.Data      | ?                                                             | E:\machinelearning\src\Microsoft.ML.Data\DataView\TypedCursor.cs          |
| class TypedCursorable<TRow>                             | Microsoft.ML.Data      | ?                                                             | E:\machinelearning\src\Microsoft.ML.Data\DataView\TypedCursor.cs          |
| static class CursoringUtils                             | Microsoft.ML.Data      | ?                                                             | E:\machinelearning\src\Microsoft.ML.Data\DataView\TypedCursor.cs          |
| MultiFileSource                                         | Microsoft.ML.Data      | ?                                                             | E:\machinelearning\src\Microsoft.ML.Data\DataLoadSave\MultiFileSource.cs  |
| VBuffer<T>                                              | Microsoft.ML.Data      | ?                                                             | E:\machinelearning\src\Microsoft.ML.Core\Data\VBuffer.cs                  |
| BinaryPredictionTransformer<TModel>                     | Microsoft.ML.Data      | Make a catalog entry in ML namespace? Or move to ML namespace | E:\machinelearning\src\Microsoft.ML.Data\Scorers\PredictionTransformer.cs |
| PredictionTransformerBase<TModel, TScorer>              | Microsoft.ML.Data      | Make a catalog entry in ML namespace? Or move to ML namespace | E:\machinelearning\src\Microsoft.ML.Data\Scorers\PredictionTransformer.cs |
| SingleFeaturePredictionTransformerBase<TModel, TScorer> | Microsoft.ML.Data      | Make a catalog entry in ML namespace? Or move to ML namespace | E:\machinelearning\src\Microsoft.ML.Data\Scorers\PredictionTransformer.cs |
| AnomalyPredictionTransformer<TModel>                    | Microsoft.ML.Data      | Make a catalog entry in ML namespace? Or move to ML namespace | E:\machinelearning\src\Microsoft.ML.Data\Scorers\PredictionTransformer.cs |
| MulticlassPredictionTransformer<TModel>                 | Microsoft.ML.Data      | Make a catalog entry in ML namespace? Or move to ML namespace | E:\machinelearning\src\Microsoft.ML.Data\Scorers\PredictionTransformer.cs |
| RegressionPredictionTransformer<TModel>                 | Microsoft.ML.Data      | Make a catalog entry in ML namespace? Or move to ML namespace | E:\machinelearning\src\Microsoft.ML.Data\Scorers\PredictionTransformer.cs |
| RankingPredictionTransformer<TModel>                    | Microsoft.ML.Data      | Make a catalog entry in ML namespace? Or move to ML namespace | E:\machinelearning\src\Microsoft.ML.Data\Scorers\PredictionTransformer.cs |
| interface Itransformer                                  | Microsoft.ML.Core.Data | ?                                                             | E:\machinelearning\src\Microsoft.ML.Core\Data\IEstimator.cs               |
| interface IEstimator<out TTransformer>                  | Microsoft.ML.Core.Data | ?                                                             | E:\machinelearning\src\Microsoft.ML.Core\Data\IEstimator.cs               |
| interface IDataReaderEstimator<in TSource, out TReader> | Microsoft.ML.Core.Data | ?                                                             | E:\machinelearning\src\Microsoft.ML.Core\Data\IEstimator.cs               |
| interface IDataReader<in TSource>                       | Microsoft.ML.Core.Data | ?                                                             | E:\machinelearning\src\Microsoft.ML.Core\Data\IEstimator.cs               |
| class SchemaShape                                       | Microsoft.ML.Core.Data | ?                                                             | E:\machinelearning\src\Microsoft.ML.Core\Data\IEstimator.cs               |
| RoleMappedData                                          | Microsoft.ML.Data      | ?                                                             | E:\machinelearning\src\Microsoft.ML.Core\Data\RoleMappedSchema.cs         |
| RoleMappedSchema                                        | Microsoft.ML.Data      | ?                                                             | E:\machinelearning\src\Microsoft.ML.Core\Data\RoleMappedSchema.cs         |
| ColumnCursorExtensions                                  | Microsoft.ML.Data      | ?                                                             | E:\machinelearning\src\Microsoft.ML.Data\Utilities\ColumnCursor.cs        |

CC: @TomFinley

**Comment by codemzs** [comment]
@sfilipi Do we care about this anymore?

**Comment by sfilipi** [comment]
I believe this has been addressed from the other angles, of checking the namespaces directly to see what types they expose. 

I'd just skim over the user facing samples, like the cookbook, Microsoft.ML.Samples and the Microsoft.ML.FunctionalTests before closing it.
