### ISSUE TITLE
MatrixFactorization nuget package should have a dependency on Microsoft.ML

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#2077]
Since the `Microsoft.ML.Recommender.dll` library references types from the core NuGet package (`Microsoft.ML`), the `Microsoft.ML.MatrixFactorization` needs to have a dependency on `Microsoft.ML`.

To fix this, add a ProjectReference in 

https://github.com/dotnet/machinelearning/blob/master/pkg/Microsoft.ML.MatrixFactorization/Microsoft.ML.MatrixFactorization.nupkgproj

See this for an example:

https://github.com/dotnet/machinelearning/blob/8cf259639cc3f77feec5d87db1a4e4429b5c9936/pkg/Microsoft.ML.Parquet/Microsoft.ML.Parquet.nupkgproj#L9

Also, while we are in here - we should synchronize the names between the NuGet package and the assembly. It is super confusing that the assembly is named `Microsoft.ML.Recommender` and the package is named `Microsoft.ML.MatrixFactorization`.

/cc @wschin

**Comment by wschin** [comment]
@eerhardt , there are multiple ways of doing recommendation (for example, SAR in our internal repo), so I didn't use 'Microsoft.ML.Recommender` as my package name. That assembly is called `Microsoft.ML.Recommender` because I hope that can be the home to other recommendation algorithms.

**Comment by eerhardt** [comment]
> That assembly is called `Microsoft.ML.Recommender` because I hope that can be the home to other recommendation algorithms.

Then it makes even less sense to name the nuget package `Microsoft.ML.MatrixFactorization`.

NuGet packages are a super-set of assemblies (they contain assemblies). So if you add something to `AssemblyA` that is contained in `PackageB`, that something will automatically be in `PackageB` as well.
So if the `Recommender` assembly is going to contain other recommendation algorithms, then the package that the `Recommender` assembly is in shouldn't be named after a single algorithm.

**Comment by wschin** [comment]
I am not quite following. `Microsoft.ML.MatrixFactorization` is a home to all assemblies around matrix factorization algorithms while `Microsoft.ML.Recommender` is an assembly which references to other back-end recommendatioon algorithms such as those in `Microsoft.ML.MatrixFactorization` and provides a unified interface to all recommender systems. Is it not good?

**Comment by shauheen** [comment]
@wschin is there another issue where you are tracking the progress of the work? Why was this closed?
