### ISSUE TITLE
Making IDataView TrainingData inside LearnerInputBase internal.

### ISSUE THREAD

**Issue by abgoswam** [dotnet/machinelearning#2079]
One of the fields in the  `Arguments`  class  for `FastTree`  is `public IDataView TrainingData`

https://github.com/dotnet/machinelearning/blob/8cf259639cc3f77feec5d87db1a4e4429b5c9936/src/Microsoft.ML.Data/EntryPoints/InputBase.cs#L35-L40

This is currently being used by the Entrypoint infrastructure. We should consider making this field `internal`

However, this needs to be done with caution. 

Here is explanation by @TomFinley : 

" Anything relating to entry-points specifically should be internal, but we must do so carefully, since currently entry-points and command line processing relies on processing of fields which is currently done on public fields only, whereas it should be over public or internal fields. Once that is done, any fields that are relevant to entry-points only should be internal.

(This is a problem for all the settings objects, that they are exposing things that should not be in the public API in some cases. (Indeed entry-points will need a lot of work to make them work for estimators and transformers. Estimator graphs are sort of a "lightweight" estimator chain as they stand right now that performs absolutely no validation. But for now, anything relating to entry-points should just be hidden.)

@TomFinley @artidoro

**Comment by TomFinley** [comment]
Closely related to #2041 in terms of the issues of the internal fields on the `Options`/`Arguments` objects.

**Comment by artidoro** [comment]
This issue has been resolved by #2300 .
