### ISSUE TITLE
How can I use the topic mode trained by LightLDA to infer a new doc?

### ISSUE THREAD

**Issue by SilentCC** [dotnet/machinelearning#2089]
Hi,
as far as I see there is currently no implementation for inferencing new/unseen documents. Is that correct? Do you have any pointers on how to accomplish that and contribute?

**Comment by najeeb-kazmi** [comment]
@SilentCC you can do this by fitting a pipeline where the last transformer is `mlContext.Transforms.Text.LatentDirichletAllocation`. You can then do inferencing on a new document with this fitted pipeline. The result of this prediction will be a score vector of length `numberOfTopis`, where each slot will give the probability of the new document belonging to the respective topic.

You can see more in [this sample](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Text/LatentDirichletAllocation.cs).

I think this answers your question, so I'm closing this issue. Please feel free to reopen if you need more info or if this does not satisfy your use case.
