### ISSUE TITLE
Add ML.NET samples to https://github.com/dotnet/samples

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/machinelearning#21]
_From @KrzysztofCwalina on Apr 23, 2018, 8:38 AM PDT_

_No description provided_

**Comment by Niladri24dutta** [comment]
it seems that they have been added already here https://github.com/dotnet/samples/tree/master/machine-learning/tutorials , is there any PR required for this?

**Comment by shauheen** [comment]
Awesome, We should be able to close this then, @KrzysztofCwalina any objections?

**Comment by KrzysztofCwalina** [comment]
Thanks!
