### ISSUE TITLE
GetModelNodes not compatible with multi-file saved models

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning#2102]
### System information

- **OS version/distro**: Windows
- **.NET Version (eg., dotnet --info)**: ML.Net 0.8.0

### Issue

- **What did you do?**
Tried to call GetModelNodes on a Tensor Flow model that was successfully able to be loaded using ScoreTensorFlowModel. 
- **What happened?**
Received Exception:  Access Denied Error
- **What did you expect?**
Successfully load model and enumerate model nodes.
### Source code / logs

I believe it's because it's trying to load my folder path as a file:

https://github.com/dotnet/machinelearning/blob/bdc9a9e1348abfdd2287d43e2633089e9eba36c7/src/Microsoft.ML.TensorFlow/TensorFlow/TensorflowUtils.cs#L83

**Comment by JakeRadMSFT** [comment]
@yaeldekel

**Comment by Ivanidzo4ka** [comment]
So I think it tensor flow terminology it's called unfrozen model, and you are absolutely right, GetModelNodes was written before we start support it, and it hasn't been updated.
For now you can do this:
`var tensorFlowModel = TensorFlowUtils.LoadTensorFlowModel(mlContext, modelLocation);`
`var schema = tensorFlowModel.GetInputSchema();`
and it should handle frozen and unfrozen models properly. (it wouldn't give you nodes, but it would give you schema)

Also+ @abgoswam
