### ISSUE TITLE
New StaticPipe nuget should be mentioned in release notes

### ISSUE THREAD

**Issue by rauhs** [dotnet/machinelearning#2122]
Title says it all. I just spend way too much time on this issue.

**Comment by shauheen** [comment]
Thanks @rauhs for your feedback. This new NuGet was a very [last minute cherry pick](https://github.com/dotnet/machinelearning/commits/release/preview) into 0.9. Going into 1.0 Static API will be experimental and not the main API for the package. @CESARDELATORRE can add a mention in the blog post perhaps to highlight the new NuGet,

**Comment by rauhs** [comment]
Obsolete
