### ISSUE TITLE
Allow multiple numeric data types in pipeline and estimators, plus allow different datatypes in the Concat estimator

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning#2127]
Related to this issue at the ML.NET Samples repo with feedback from a customer: https://github.com/dotnet/machinelearning-samples/issues/198

Most of our algorithms expect floating point values as input. You need to either read your input as floats (DataKind.R4 or DataKind.R8) or convert ints to floats later in the pipeline.

This is a typical problem that customers might have when starting with new datasets where data could initially be Integer, etc. and since DataKind enum has more than just float and double it can be misleading and create trouble when getting started.

It's definitely unclear to beginners why integer only wouldn't work, etc. 

PROPOSALS:

- 1. Expand API so it'd accept additional numeric data types like Integer. Do conversions/cast internally?

- 2. Expand Concat estimator API to accept multiple/different numeric column types for the multiple columns being being concatenated. So I could concatenate an integer column with a double column and so forth. Again, it might need conversions, but it probably could be done internally?

**Comment by wschin** [comment]
The limitations on acceptable types to Transformers/Estimators are reasonable and by-designed. User can do a `Cast` if this problem happens, so let me close this issue for now. Thanks.
