### ISSUE TITLE
Command-line oriented arguments, that have more suitable alternatives for the API should be made internal

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#2133]
In the arguments classes there are several arguments that get translated to the same parameter for the estimators/transforms. 

One of the variant is  a convenience for the command line version of ML.Net. 

I think those can be made internal, and kept away from the user for v1. 

Example:

[ValueToKeyMappingTransformer.ArgumentsBase](https://github.com/dotnet/machinelearning/blob/312f9e4c71953bee701ea2a63be3cb4d2d276d20/src/Microsoft.ML.Data/Transforms/ValueToKeyMappingTransformer.cs#L53)

```csharp
public abstract class ArgumentsBase : TransformInputBase
{
     [Argument(ArgumentType.AtMostOnce, HelpText = "Maximum number of terms to keep per column when auto-training", ShortName = "max", SortOrder = 5)]
      public int MaxNumTerms = ValueToKeyMappingEstimator.Defaults.MaxNumTerms;

      [Argument(ArgumentType.AtMostOnce, HelpText = "Comma separated list of terms", SortOrder = 105, Visibility = ArgumentAttribute.VisibilityType.CmdLineOnly)]
      public string Terms;

      [Argument(ArgumentType.AtMostOnce, HelpText = "List of terms", SortOrder = 106, Visibility = ArgumentAttribute.VisibilityType.EntryPointsOnly)]
      public string[] Term;
```

I don't think our API users should see the first 

`public string Terms`

**Comment by najeeb-kazmi** [comment]
The other two occurrences of this are:

[CustomStopWordsRemovingTransformer.ArgumentsBase](https://github.com/dotnet/machinelearning/blob/312f9e4c71953bee701ea2a63be3cb4d2d276d20/src/Microsoft.ML.Transforms/Text/StopWordsRemovingTransformer.cs#L617-L623)
```csharp
        public abstract class ArgumentsBase
        {
            [Argument(ArgumentType.AtMostOnce, HelpText = "Comma separated list of stopwords", Visibility = ArgumentAttribute.VisibilityType.CmdLineOnly)]
            public string Stopwords;

            [Argument(ArgumentType.AtMostOnce, HelpText = "List of stopwords", Visibility = ArgumentAttribute.VisibilityType.EntryPointsOnly)]
            public string[] Stopword;
```

and

[TermLoaderArguments](https://github.com/dotnet/machinelearning/blob/312f9e4c71953bee701ea2a63be3cb4d2d276d20/src/Microsoft.ML.Transforms/Text/WordBagTransform.cs#L414-L420)
```csharp
    public sealed class TermLoaderArguments
    {
        [Argument(ArgumentType.AtMostOnce, HelpText = "Comma separated list of terms", SortOrder = 1, Visibility = ArgumentAttribute.VisibilityType.CmdLineOnly)]
        public string Terms;


        [Argument(ArgumentType.AtMostOnce, HelpText = "List of terms", SortOrder = 1, Visibility = ArgumentAttribute.VisibilityType.EntryPointsOnly)]
        public string[] Term;
```

**Comment by Zruty0** [comment]
I would say that the name `Term` for a 'list of terms' is not ideal either.

**Comment by glebuk** [comment]
Related to #2079  and  #2041

**Comment by artidoro** [comment]
After further investigating, it seems that the above Arguments classes should be made internal. They are only used by the entrypoints API. We are using other objects to set the parameters of the estimators (either direct definition of the parameters in the constructors, or through a ColumnInfo object).

**Comment by artidoro** [comment]
The only transform that still has public Options class (former Arguments class) is the `TensorFlowTransformer` and it does not have command line oriented arguments.

The remaining transform either use the `ColumnInfo` object or don't have advanced settings that cannot be set from the constructor directly. So we have made the Options class internal in those cases.

This issue can therefore be considered closed.
