### ISSUE TITLE
Change TextLoader synchronization to not use exceptions

### ISSUE THREAD

**Issue by TomFinley** [dotnet/machinelearning#2137]
The `TextLoader` code in its current form uses multithreading in its parsing. While reading the raw data from the file is in a single thread, the work of interpreting that data, putting it into buffers, etc. etc., is done in separate threads as that was the bottleneck in parsing. It uses blocking collections to synchronize this work, as we do in many other places. So far, so good.

Now, unfortunately, unlike our other usages of blocking collections, this implementation uses exception catching simply as a matter of course, to detect and react to empty buffers, etc. While this always seemed to me to have at least a bad code smell, apparently it is detrimental from a perf perspective as well, being needlessly slow compared to the other exception free mechanisms of using blocking collections, according to @stephentoub, whose diagnosis I quote directly below:

> I believe the problem is that the demo is throwing ~110,000 exceptions (which are caught internally).  Adding the AppendCacheCheckpoint drops that to 50.  Exception throwing/catching is expensive, and there’s a noticeable difference in throughput even without the debugger attached, but exceptions are even more expensive when a debugger is attached, hence F5 being super slow.
> 
> Almost all of the exceptions are InvalidOperationExceptions stemming from invalid use of a BlockingCollection:
> System.InvalidOperationException: The collection argument is empty and has been marked as complete with regards to additions.
> 
> Coming from:
> 
> ```
> System.Collections.Concurrent.dll!System.Collections.Concurrent.BlockingCollection<Microsoft.ML.Data.TextLoader.Cursor.LineBatch>.Take() Line 545     C#
> Microsoft.ML.Data.dll!Microsoft.ML.Data.TextLoader.Cursor.LineReader.GetBatch() Line 451     C#
> Microsoft.ML.Data.dll!Microsoft.ML.Data.TextLoader.Cursor.GetSomeLines(Microsoft.ML.Data.IMultiStreamSource source, int count, ref System.Collections.Generic.List<System.ReadOnlyMemory<char>> lines = null) Line 221    C#
> Microsoft.ML.Data.dll!Microsoft.ML.Data.TextLoader.Bindings.Bindings(Microsoft.ML.Data.TextLoader parent = {Microsoft.ML.Data.TextLoader}, Microsoft.ML.Data.TextLoader.Column[] cols = {Microsoft.ML.Data.TextLoader.Column[5]}, Microsoft.ML.Data.IMultiStreamSource headerFile = null, Microsoft.ML.Data.IMultiStreamSource dataSample) Line 570      C#
> Microsoft.ML.Data.dll!Microsoft.ML.Data.TextLoader.TextLoader(Microsoft.ML.IHostEnvironment env, Microsoft.ML.Data.TextLoader.Arguments args, Microsoft.ML.Data.IMultiStreamSource dataSample) Line 1135     C#
> Microsoft.ML.Data.dll!Microsoft.ML.TextLoaderSaverCatalog.CreateTextReader(Microsoft.ML.DataOperations catalog, Microsoft.ML.Data.TextLoader.Arguments args, Microsoft.ML.Data.IMultiStreamSource dataSample) Line 37 C#
> MulticlassClassification_Iris.dll!MulticlassClassification_Iris.Program.BuildTrainEvaluateAndSaveModel(Microsoft.ML.MLContext mlContext = {Microsoft.ML.MLContext}) Line 51 C#
> MulticlassClassification_Iris.dll!MulticlassClassification_Iris.Program.Main(string[] args = {string[0]}) Line 38      C#
> ```
> 
> Whether or not that’s the only issue, I don’t know, but my guess is if you fix that issue, the perf will get a lot better.

Tangentially related to #2099, insofar as it sprang from the same discussion.

**Comment by justinormont** [comment]
At what point would adding multithreading to the reader be helpful? (in addition to the multithreaded parser)

If I recall the recitation of lore, the current reader was implemented as single-threaded since spinning disks dominated at the time and therefore linear scans of the file was optimal. SSDs are now the rule instead of the exception, which removes one of the reasons for a single threaded reader.
