### ISSUE TITLE
Check range of ScalePosWeight in LightGBM

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning#2147]
Our recommendation seems to be (0,Inf) for `ScalePosWeight`, but we then restrict it to (0,1].

https://github.com/dotnet/machinelearning/blob/a570da14a41f2870eb8f61d84496a58422398253/src/Microsoft.ML.LightGBM/LightGbmArguments.cs#L155-L158

https://github.com/dotnet/machinelearning/blob/a570da14a41f2870eb8f61d84496a58422398253/src/Microsoft.ML.LightGBM/LightGbmArguments.cs#L170

This likely should be:
```C#
Contracts.CheckUserArg(Args.ScalePosWeight > 0, nameof(Args.ScalePosWeight), "must be > 0.");
```

**Comment by singlis** [comment]
Fixed with #2948, its been renamed to WeightOfPositiveExamples.
