### ISSUE TITLE
OnnxTransfrom - onnxruntime.dll - ReleaseOrtAllocatorInfo- System.EntryPointNotFoundException:

### ISSUE THREAD

**Issue by shaykels** [dotnet/machinelearning#2149]
### System information

- **OS version/distro**: Win 10, 64-bit, 10.0.17763
- **.NET Version (eg., dotnet --info)**:  4.6.2

### Issue

Added OnnxTransformSample.cs + nugets to a console app, trying to run the example.

1. Exception onnxruntime.dll is not found, probably similar to this https://github.com/dotnet/machinelearning/issues/2106

2. Copied onnxruntime.dll from ..\packages\Microsoft.ML.OnnxRuntime.Gpu.0.1.5\runtimes\win10-x64\native to my app directory. The example works find, but when I close the console app, there is an exception 

System.EntryPointNotFoundException: 'Unable to find an entry point named 'ReleaseOrtAllocatorInfo' in DLL 'onnxruntime.dll'.'

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by jignparm** [comment]
@yaeldekel  -- does a similar issue occur for .NetCore, or only for .NetFramework?

**Comment by jignparm** [comment]
For the second, the API changed name to "OrtReleaseAllocatorInfo". Will need to add an explicit unit test for memory de-allocation to prevent future API changes.

https://github.com/Microsoft/onnxruntime/commit/773114a4f125d0cb515526351f5e3defffbca034#diff-6f015c4247fcb82b2124bf3afaf688a8R39

Will be fixed in next release of Onnxruntime.

**Comment by jignparm** [comment]
Tracking on onnxruntime repo using the following:
Issue= https://github.com/Microsoft/onnxruntime/issues/338
PR = https://github.com/Microsoft/onnxruntime/pull/337

**Comment by jignparm** [comment]
The DLL copy issue is resolved by https://github.com/Microsoft/onnxruntime/pull/325, so the manual copy will no longer be required for .NetFramework projects.

**Comment by jignparm** [comment]
Fixed via https://github.com/dotnet/machinelearning/pull/2085
