### ISSUE TITLE
The ProposeSweeps method, in sweepers should return uniqie entries

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#215]
public virtual ParameterSet[] ProposeSweeps(int maxSweeps, IEnumerable<IRunResult> previousRuns) in ISweeper implementations should not return duplicate ParameterSet entries in the array it returns. 

Duplicate entries are ParameterSet elements that have the same IparameterValue Name and ValueText field values. 

Since the ParameterSet class also calculates the hash, for each entry in the ParameterSet[], it wouldn't be hard to disambiguate. 

I can't think of a case where consuming the output of this method would not follow up by cleaning up duplicates. It should be built in the system.

**Comment by ross-p-smith** [comment]
@shauheen 
#358 is a fix with no tests
#365 is pretty much the same fix with tests
#368 is a more elegant fix (IMO) with tests

**Comment by shauheen** [comment]
Thanks @ross-p-smith , closing this issue as #368 has fixed it.
