### ISSUE TITLE
TreeEnsembleFeaturizerTransform has no Transformer derivative

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#2151]
As title. Please see [TreeEnsembleFeaturizerTransform](https://github.com/dotnet/machinelearning/blob/2e5612c029583185c10044fb1b665c5d308676d7/src/Microsoft.ML.FastTree/TreeEnsembleFeaturizer.cs#L540). As most transforms have become transformers, maybe this one should do as well.

**Comment by Ivanidzo4ka** [comment]
this one was first, but it looks like all discussion going on here: https://github.com/dotnet/machinelearning/issues/2482
