### ISSUE TITLE
Add XML summary comments to fields in Options class

### ISSUE THREAD

**Issue by abgoswam** [dotnet/machinelearning#2154]
We need to add XML summary comments to fields in `Options` class.

Learners where its missing:

- SdcaBinaryTrainer
- SdcaMultiClassTrainer
- SdcaRegressionTrainer
- StochasticGradientDescentClassificationTrainer
- MulticlassLogisticRegression  + related LR learners
- Online learners

Also, in XML help for `options` we should say something consistent (right now there is inconsistency in  the help text for `options`) 
e.g.  

`/// <param name="options">Advanced **options** to the algorithm.</param>`

**Comment by wschin** [comment]
I think we have finished this during our API season.
