### ISSUE TITLE
C# samples should probably use C# and not Python naming conventions

### ISSUE THREAD

**Issue by TomFinley** [dotnet/machinelearning#2155]
I was reading a PR when suddenly I saw something a bit odd.

https://github.com/dotnet/machinelearning/blob/6b9f5893ea6830481a8779f81f2b723e9b5cd6cd/docs/samples/Microsoft.ML.Samples/Dynamic/KeyToValue_Term.cs#L42-L47

Note the underscores in the middle of a variable name. While in private we might elect to bend the rules a little bit, in our public API and also probably our samples, we probably ought to write them with [consideration of standard practices](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions). This does not seem to be a justifiable or explainable diversion from the recommended practice, and I'm guessing it was added by mistake.

Each individual renaming is probably not huge, but might span several files, since the example listed above is just one of many examples I see in our samples project. So not a "hard" change, except possibly in scale?

**Comment by daniel-loudon** [comment]
This would be a good first issue for me, can I take this?

**Comment by artidoro** [comment]
Sure! We would welcome your contribution and that looks like a good first issue.

**Comment by daniel-loudon** [comment]
Thanks, you can assign me this and I am happy to do this issue

**Comment by sfilipi** [comment]
This is completed with PR #2303

**Comment by sfilipi** [comment]
reopening, just noticed that those PRs, didn't get merge..

**Comment by shmoradims** [comment]
Samples were cleaned up as part of 1.0 API reference documentation. Please re-open with any wring naming instance you find.
