### ISSUE TITLE
Trained model does not contain information about Loader...

### ISSUE THREAD

**Issue by zeahmed** [dotnet/machinelearning#216]
This issue is a blocker for issue #5 

When model is trained in ML.Net using TextLoader (or any other loader in general), the loader information is not saved in the model. This is a blocker to issue #5 where evaluator needs to know how to load test file based on the loader information in the training pipeline.

Please look at https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Data/EntryPoints/TransformModel.cs

**Comment by TomFinley** [comment]
Related to #119?

**Comment by zeahmed** [comment]
Yes, its pretty much covered in #119.

**Comment by TomFinley** [comment]
Hi @shauheen just going to switch the tags a little. :) Writing models that aren't broken doesn't really come under the "enhancement" umbrella. This is a full on bug.

**Comment by zeahmed** [comment]
This is no longer valid. API changed a lot since this bug was filed. I am closing it.
