### ISSUE TITLE
Loading TensorFlow Models with unsupported Node types throws confusing Exception

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning#2164]
### System information

- **OS version/distro**: Windows
- **.NET Version (eg., dotnet --info)**: ML.Net 0.8.0

### Issue

- **What did you do?**
Tried to load a TensorFlow model with an input of type String.
- **What happened?**
Exception thrown saying that the node with the given input name didn't exist.
- **What did you expect?**
I would expect this to work but if it's unsupported ... I would expect an Exception thrown saying that the node is an unsupported type instead of saying it doesn't exist.

### Source code / logs

https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.TensorFlow/TensorFlow/TensorflowUtils.cs#L43

This should throw an exception or log something to inform developers that there is an unsupported  node.

**Comment by Ivanidzo4ka** [comment]
@zeahmed  Any chance you can comment on that?
https://github.com/dotnet/machinelearning/blob/a04dbf8ef3a2ffc57188f3d2f3eff7f72b47b77a/src/Microsoft.ML.TensorFlow/TensorFlow/Tensor.cs#L651

**Comment by zeahmed** [comment]
Strings are currently not supported. This is the limitation right now. I am in the process of investigating how it can be supported. I haven't created an issue for this but I take this one for my investigation.

**Comment by JakeRadMSFT** [comment]
String support is sort of half the issue here. 

The other half is that unsupported tensor types result in "tensor doesn't exist" error messages ... when in reality they are unsupported. Even if String support is added ... the bad error messages still exist for other unsupported tensors.

**Comment by Ivanidzo4ka** [comment]
String support https://github.com/dotnet/machinelearning/issues/2545

**Comment by zeahmed** [comment]
The error message has been added at the following line.
https://github.com/dotnet/machinelearning/blob/51b10fc6a004b08b3a07d046db10fa277a8cffac/src/Microsoft.ML.TensorFlow/TensorflowTransform.cs#L573
