### ISSUE TITLE
Number of feature columns

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#2179]
It has been a while that ML.NET assumes only one feature column can exist in a training pipeline. Recently, we have added field-aware factorization machine so that argument becomes not 100% correct. We will only have only two public APIs per trainer (please see #2047 as an example). To make our public APIs consistent, we need to determine if feature column name should be an array or a scalar. Or we can introduce another API which accepts multiple feature (even label) columns. @TomFinley, @eerhardt, any comments please?

**Comment by abgoswam** [comment]
Currently the public API of Field-aware factorization machine accepts a string[]  as features:

https://github.com/dotnet/machinelearning/blob/bafd40cb555184d57a482a6b6434124d4715172e/src/Microsoft.ML.StandardLearners/FactorizationMachine/FactorizationMachineCatalog.cs#L27-L33

However, the advanced arguments for FFM `FieldAwareFactorizationMachineTrainer.Arguments`  take a `string FeatureColumn`

This leads to inconsistency in the public API of FieldAwareFactorizationMachine,  when we separate  out the  advanced arguments  in a separate API   (Related to the work we are doing in #1798)

@glebuk @sfilipi

**Comment by eerhardt** [comment]
If one algorithm (say field-aware factorization machine) can accept multiple feature columns, and other algorithms (say SDCA) can only accept a single feature column, I don't see a reason why the APIs across the two need to be consistent.

Why limit FFM to only allow one column when it can support many?
Why have SDCA allow multiple columns when it can only support one?

**Comment by glebuk** [comment]
I'd expect to be consistency between "basic" and "advanced" arguments.  Different functionality between different trainers require different type for features.   Having string[] featureColumns in both method and arg class seems reasonable.

**Comment by wschin** [comment]
Single-feature assumption doesn't sound great to me. By searching for references of FFM, we can find some advances are using multiple feature columns.

**Comment by abgoswam** [comment]
Closing out this issue. PR #2205 fixed it.
