### ISSUE TITLE
Load Http

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning#2181]
### System information

- **OS version/distro**:
- **.NET Version (eg., dotnet --info)**: 

### Issue

- **What did you do?**
- **What happened?**
- **What did you expect?**

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by Ivanidzo4ka** [comment]
Looks like duplicate of https://github.com/dotnet/machinelearning/issues/2183
