### ISSUE TITLE
failed when adding ML.NET package

### ISSUE THREAD

**Issue by Dandjinh** [dotnet/machinelearning#2184]
### System information
D:\Works\Codes\CSharpPrjs\dotNetPrjs\myApp>dotnet --info
.NET Core SDK（反映任何 global.json）:
 Version:   2.2.103
 Commit:    8edbc2570a

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.103\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.2.103 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

### Issue

I just followed [ML.NET Tutorial](https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial) but failed when adding ML.NET package.

### Source code / logs

D:\Works\Codes\CSharpPrjs\dotNetPrjs\myApp>dotnet add package Microsoft.ML --version 0.9.0
  Writing C:\Users\34460\AppData\Local\Temp\tmp40CD.tmp
info : 正在将包“Microsoft.ML”的 PackageReference 添加到项目“D:\Works\Codes\CSharpPrjs\dotNetPrjs\myApp\myApp.csproj”。
log  : 正在还原 D:\Works\Codes\CSharpPrjs\dotNetPrjs\myApp\myApp.csproj 的包...
error: 无法解析 .NETCoreApp,Version=v2.2 的“Microsoft.ML (>= 0.9.0)”。
error: 包“Microsoft.ML”与项目“D:\Works\Codes\CSharpPrjs\dotNetPrjs\myApp\myApp.csproj”中的“all”框架不兼容。

**Comment by glebuk** [comment]
Based on limited understanding of Chinese using bing translator, the error says that .NET framework is not compatible with that of the Ml.NET package.  Can you please check the version of .NET specified in the project -> Properties -> Target Framework.  What is it?  PLease ensure it is .NET Core 2.1?

**Comment by Dandjinh** [comment]
I just installed the lastest .Net Core 2.2 and the "dotnet new console -o myApp"created a myApp.csproj file which writes 
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

</Project>
```
Do I need install another .Net Core 2.1 and change this file?

**Comment by antoniovs1029** [comment]
Yes, I believe that you should have targeted .NET Core 2.1.

Since ML.NET has changed a lot since this question was opened a year ago, and it seemed the question was answered then, I will close this issue.
