### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by codemzs** [dotnet/machinelearning#2193]
Integrate coverlet to get coverage files and upload them to codecov.io. Enable code coverage for Windows x64 Debug and later enable for all debug legs when covertlet releases a more performant version. Display code coverage report for every commit in every PR.

**Comment by CESARDELATORRE** [comment]
Reopening this issue just to ask this:
What is the reason why it was decided to use https://codecov.io instead code coverage in Azure DevOps?

https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-code-coverage-results?view=azure-devops

**Comment by sharwell** [comment]
@Ivanidzo4ka let's talk about this in a meeting

**Comment by najeeb-kazmi** [comment]
I guess this was talked about in a meeting. Closing since no action was taken on changing code coverage in the last year.
