### ISSUE TITLE
NEAT and HYPERNEAT algorithm support.

### ISSUE THREAD

**Issue by chrisevans9629** [dotnet/machinelearning#2198]
### Feature Request

NEAT is an unsupervised learning method that evolves neural networks as it learns.  Is this something that is on the roadmap for features to implement?  I saw that ANN is on the roadmap, however I wasn't sure if that includes methods like NEAT.

**Comment by artidoro** [comment]
I will close this issue as we don't have any plans for unsupervised deep learning on our roadmap. However, we do have plans for supervised DNN training in the coming semester.
