### ISSUE TITLE
Build.sh fails due to clang does not exist

### ISSUE THREAD

**Issue by MahmoudYounes** [dotnet/machinelearning#2201]
### System information

- OS Distro: ubuntu 18.04
- dotnet version: Version  : 2.0.9  Build    : 1632fa1589b0eee3277a8841ce1770e554ece037

### Issue

- **What did you do?**
I tried to build ML.net on my machine. had to run build.sh
- **What happened?**
build.sh failed because clang compiler does not exist. see attached exact error

When I tried to install clang I had lot's of unmet dependencies which I could not resolve (I really do now know what was the problem here, I followed the dependencies everywhere for a couple of days but no luck)
- **What did you expect?**
I expected that the script uses gcc or g++ to build which comes packaged with Ubuntu.

### Source code / logs

 Unable to find Clang Compiler
  Install clang-3.5 or clang3.6 or clang3.9
/home/usr/machinelearning/src/Native/build.proj(47,5): error MSB3073: The command /home/usr/machinelearning/src/Native/build.sh" --configuration Debug --arch x64  --mkllibpath /home/usr/machinelearning/packages/mlnetmkldeps/0.0.0.6/runtimes/linux-x64/native exited with code 1.
Build FAILED.
/home/usr/machinelearning/src/Native/build.proj(47,5): error MSB3073: The command /home/usr/machinelearning/src/Native/build.sh" --configuration Debug --arch x64  --mkllibpath /home/usr/machinelearning/packages/mlnetmkldeps/0.0.0.6/runtimes/linux-x64/native exited with code 1.

### Did you manage to solve this issue? How?
I just replaced clang with gcc and the solution was built successfully which made me think about opening this issue to ask if submitting a PR here makes sense.

**Comment by Ivanidzo4ka** [comment]
@eerhardt @safern are build experts, maybe they can provide more regarding choice of compiler.

**Comment by eerhardt** [comment]
We are using `clang` in this repo for the simple reason that it is what the other repos inside the `dotnet` organization use. That way we can share infrastructure/settings/etc.

If you are having issues installing clang, check out:

https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md#toolchain-setup

For instructions.

That being said, if someone wanted to add an unsupported build option to use `gcc` to the build scripts, I don't think there would be a problem with that (assuming it doesn't destabilize the real build, and isn't a lot of new code). However, it would be unsupported, and there would be no CI infrastructure set up to ensure it was always working. Thus it could break in the future without the promise that it would be fixed.
