### ISSUE TITLE
Re-build the MKL binaries together with OpenMP and update SymSGD to make use of parallelism

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#2211]
The current binaries for MlNetMKLDeps are build with sequential threading, and SymSgd has parallelism turned off. 

Now that the legal issues around packaging and re-distributing Open MP are clarified, re-build the ML bits with threading=parallel and update SymSGD.

**Comment by singlis** [comment]
So when enabling OpenMP for mac this hit multiple issues as MKL uses Intel's OpenMP implementation and we are linking against default OpenMP (installed via brew install libomp).

While this does build, there is an error that comes up during tests that we are mixing two implementations of OpenMP:

> The active test run was aborted. Reason: OMP: Error #15: Initializing libiomp5.dylib, but found libomp.dylib already initialized.
> OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
> 

I am following up with Intel for guidance on how to resolve this.
