### ISSUE TITLE
Array checks in Utils return true for null arrays

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#2223]
`Microsoft.ML.Internal.Utilities.Utils` has a couple of array checks that return `true` when a `null` array is passed in. Is this the expected behavior?

Here are the culprits:

```cs
public static bool IsSorted(IList<float> values);
public static bool IsSorted(int[] values);
```

```cs
public static bool IsIncreasing(int min, ReadOnlySpan<int> values, int lim);
```

Note that `IsIncreasing` is typically used for checking `int[]` arrays because `ReadOnlySpan` performs an implicit cast and null arrays are set to a 0-length `ReadOnlySpan`.

In a similar vein, `IsSorted` uses a null-safe `Utils.Size()` to check the input length of the array.

Does this make sense that we say that `null` arrays are sorted, and that they are decreasing?

**Comment by rogancarr** [comment]
@TomFinley  What do you think?

**Comment by artidoro** [comment]
I think this is expected behavior, especially if it is consistent across the methods mentioned above.
