### ISSUE TITLE
Need more details

### ISSUE THREAD

**Issue by mairaw** [dotnet/machinelearning#223]
@abidur commented on [Wed May 23 2018](https://github.com/dotnet/docs/issues/5574)

It would be nice to have more details on this beyond, "Number of weak hypotheses in the ensemble"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12f802b4-7e85-f280-316a-8c0f026f7276
* Version Independent ID: a6ae94b0-5d3e-0d89-1c2b-802b55f79a1b
* Content: [FastTreeBinaryClassifier.NumTrees Property (Microsoft.ML.Trainers)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.fasttreebinaryclassifier.numtrees?view=ml-dotnet#Microsoft_ML_Trainers_FastTreeBinaryClassifier_NumTrees)
* Content Source: [dotnet/xml/Microsoft.ML.Trainers/FastTreeBinaryClassifier.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Trainers/FastTreeBinaryClassifier.xml)
* Service: **unspecified**
* Product: **unspecified**
* GitHub Login: @dotnet-bot

**Comment by shauheen** [comment]
Thanks for filling, I think this is somewhat related to #160. We will publish more documentation as we go.

**Comment by justinormont** [comment]
This string originates from: https://github.com/dotnet/machinelearning/blob/c023727b76970ab913ec1ce38276508835c17bcf/src/Microsoft.ML.FastTree/FastTreeArguments.cs#L241

We should modify it to say something more user friendly. Perhaps, "Total number of boosted trees to create in the ensemble". 

@codemzs: Is this parameter (and string value) inherited by other learners, like FastForest? The current wording seems oddly non-specific to boosted trees.

**Comment by mitevpi** [comment]
I couldn't find any references to the parameter in other learners. Also judging by the documentation of the arguments around it, it seems like this may have just missed a legibility update.

**Comment by shauheen** [comment]
Thanks @jwood803 for #372 . @mairaw do you think we can close this issue now?

**Comment by mairaw** [comment]
@abidur was the one who originally opened this issue in our repo.

**Comment by shauheen** [comment]
Closing the issue, please file a new issue if the enhancements are not enough.
