### ISSUE TITLE
Remove learningRate argument from FastForest constructor

### ISSUE THREAD

**Issue by singlis** [dotnet/machinelearning#2237]
Started from issue #1983 where there is a comment about learningRate is accessible from the FastForest constructor but not accessible from the FastForest Arguments (now Options) class. After investigating, learningRate is not an argument for FastForest and that it was added to the constructor by mistake. 

For this issue, the fix is to remove learningRate from the constructor for FastForest and update the code/tests as needed:

https://github.com/dotnet/machinelearning/blob/1baaec31e0477cb17032b8a9a8a8488acb3606af/src/Microsoft.ML.FastTree/RandomForestClassification.cs#L155

**Comment by Ivanidzo4ka** [comment]
related to https://github.com/dotnet/machinelearning/issues/2617
