### ISSUE TITLE
Code Snippet Language Options Visible for Languages Not Yet Available

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#2238]
On the top toolbar there is a dropdown to select the language to display the code snippet in with options for F# and VB. However, when either F# or VB are selected, the code in the code snipped remains the default C# implementation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 209d151a-38b8-5ef8-57b9-bbdb0fcdef55
* Version Independent ID: 0dbd3424-7e4e-8189-5f6b-f46767cc7554
* Content: [OnnxTransform Class (Microsoft.ML.Transforms)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.onnxtransform?view=ml-dotnet#feedback)
* Content Source: [dotnet/xml/Microsoft.ML.Transforms/OnnxTransform.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Transforms/OnnxTransform.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by Ivanidzo4ka** [comment]
Update to 0.10 version link: https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.onnxtransformer?view=ml-dotnet

**Comment by shmoradims** [comment]
We don't have any F# samples in API reference so changing the language selector will only change the API signature and not the sample code.

This is tracked by #3100. Closing this issue as duplicate.
