### ISSUE TITLE
FastTreeBinaryClassificiationTrainer class declaration is incorrect

### ISSUE THREAD

**Issue by erustin-ln** [dotnet/machinelearning#2242]
Using ML.Net 0.9 an error is given when attempting the following - 
`var pipeline = mlContext.Transforms.Concatenate("Features", featureNames)
        .Append(mlContext.Transforms.Normalize("Features"))
        .Append(mlContext.BinaryClassification.Trainers.FastTree(numLeaves: 50, numTrees: 50, minDatapointsInLeaves: 20));

      var model = pipeline.Fit(dataView);
            
      var m = model.LastTransformer.Model;
`

where the error given is - `'TNewTrans' does not contain a definition for 'Model' and no accessible extension method 'Model' accepting a first argument of type 'TNewTrans' could be found (are you missing a using directive or an assembly reference?)`

Advise given on gitter is that this is due to the class declaration for FastTreeBinaryClassification (FastTreeClassification.cs : line 106) being incorrect and that in that declaration BinaryPredictionTransformer<IPredictorWithFeatureWeights<float>> should be changed to RegressionPredictionTransformer<FastTreeBinaryModelParameters>

**Comment by loflet** [comment]
Should I pick this up?

**Comment by Ivanidzo4ka** [comment]
I'm trying to reproduce your problem, and I can't.
```
            MLContext mlContext = new MLContext();
            var _dataPath = @"D:\src\fork-machinelearning\test\data\breast-cancer.txt";
            TextLoader textLoader = mlContext.Data.CreateTextReader(new TextLoader.Arguments()
            {
                Separator = "\t",
                HasHeader = false,
                Column = new[]
            {
                new TextLoader.Column("Feature1", DataKind.R4, 1),
                new TextLoader.Column("Feature2", DataKind.R4, 2),
                new TextLoader.Column("FeatureRest", DataKind.R4, 3,9),
                new TextLoader.Column("Label", DataKind.Bool, 0)
            }
            });

            IDataView dataView = textLoader.Read(_dataPath);


            var pipeline =
                mlContext.Transforms.Concatenate("Features", "Feature1", "Feature2", "FeatureRest")
                .Append(mlContext.Transforms.Normalize("Features"))
            .Append(mlContext.BinaryClassification.Trainers.FastTree(numLeaves: 50, numTrees: 50, minDatapointsInLeaves: 20));

            // Train the model.
            var model = pipeline.Fit(dataView);
            var m = model.LastTransformer.Model;
            // Compute quality metrics
            var metrics = mlContext.BinaryClassification.Evaluate(model.Transform(dataView));
            Console.WriteLine(metrics.Accuracy);
```

Here is my code, I'm using clean .net core console app with Microsoft.ML 0.9 nuget.
Any chance you can provide more information?

**Comment by Ivanidzo4ka** [comment]
Also I'm not quite sure it's a good suggestion to change 

> BinaryPredictionTransformer<IPredictorWithFeatureWeights> should be changed to RegressionPredictionTransformer

It's a binary trainer, why it should return Regression stuff?

**Comment by wschin** [comment]
It looks like this issue is not update-to-date. The current `FastTreeBinaryTrainer` returns `BinaryPredictionTransformer<CalibratedModelParametersBase<FastTreeBinaryModelParameters, PlattCalibrator>>`. In addition, this looks like a misuse of classifier and regressor according to @Ivanidzo4ka's comment. Consequently, please allow me to close issue and feel free to reopen it. Thanks.
