### ISSUE TITLE
Adding ModelParameters concept in the ML.NET documentation

### ISSUE THREAD

**Issue by abgoswam** [dotnet/machinelearning#2247]
We should probably consider adding ModelParameters concept in the ML.NET documentation  
(albeit one of the low-priority concepts)

Related to #1866 

@eerhardt  @TomFinley  @sfilipi

**Comment by shmoradims** [comment]
I think this is already covered by [this conceptual doc](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/retrain-model-ml-net) specifically [here](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/retrain-model-ml-net#extract-pre-trained-model-parameters).
