### ISSUE TITLE
AvxIntrinsics.DotU is Slower than the native version

### ISSUE THREAD

**Issue by Anipik** [dotnet/machinelearning#2253]
We can verify this by running the benchmark https://github.com/dotnet/machinelearning/blob/master/test/Microsoft.ML.Benchmarks/StochasticDualCoordinateAscentClassifierBench.cs#L157

``` ini

BenchmarkDotNet=v0.11.3, OS=Windows 10.0.17763.253 (1809/October2018Update/Redstone5)
Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=3.0.100-preview-009812
  [Host]     : .NET Core 2.1.6 (CoreCLR 4.6.27019.06, CoreFX 4.6.27019.05), 64bit RyuJIT
  Job-RQXZIO : .NET Core 2.1.6 (CoreCLR 4.6.27019.06, CoreFX 4.6.27019.05), 64bit RyuJIT

Arguments=/p:Configuration=Release  Toolchain=netcoreapp2.1  MaxIterationCount=20  
WarmupCount=1  

```
|      Method |     (netcoreapp2.1)Mean |    Error |   StdDev |        netcoreapp3.0 |
|------------ |--------------:|---------:|---------:|--------------------:|
| PredictIris | 515.6 ns | 3.097 ns | 2.745 ns | 620.3ns |

if we use ```UseIntrinsics=false``` Then we get the same performance for netcoreapp3.0

I verified using the perfview that the cause of regression is DotU. The Inclusive time fot DotU on netcoreapp3.0  is 95ns and on native version of cpumath is 11 ns

cc @danmosemsft @adamsitnik @tannergooding @eerhardt

**Comment by adamsitnik** [comment]
@Anipik great job finding this regression!

the reason is most probably the fact that ML.NET typically has a very small input for all the CpuMath operations, something like an array of 7 or 14 floats. Our managed implementation is not optimized for that, IMHO the best would be to change the architecture/data flow in ML.NET

**Comment by Anipik** [comment]
Same is the case with ```MakeIrisPredictions``` Benchmark
old - netcoreapp2.1
new - netcoreapp3.0

Base (old) Time: | 707.5
-- | --
Test (new) Time: | 786.9
Delta: | 79.4
Delta %: | 11.2


I verified using the perfview that the cause of regression is DotU. The Inclusive time fot DotU on netcoreapp3.0 is 192ms and on native version of cpumath is 106 ms

**Comment by danmosemsft** [comment]
> Our managed implementation is not optimized for that, IMHO the best would be to change the architecture/data flow in ML.NET

Until then, can we go down the software path when the input is short?  

cc @tannergooding
