### ISSUE TITLE
Rename `weights` parameter in ML.NET Public API

### ISSUE THREAD

**Issue by abgoswam** [dotnet/machinelearning#2257]
Couple of conventions to follow for `weights` parameter in ML.NET Public API

- Name of the `weight` argument in trainer API should be consistent with the other column names i.e it should end on *Column.
- Proposal to disambiguate this by calling it exampleWeightColumn.

@glebuk

**Comment by daniel-loudon** [comment]
Hi is this up for grabs?

**Comment by abgoswam** [comment]
@daniel-loudon . I am currently working on this and will have a PR out for this shortly. There are a few other issues related to the `weights` column that we want to address for V 1.0
