### ISSUE TITLE
Lockdown Microsoft.ML.Ensemble public surface, or isolate it

### ISSUE THREAD

**Issue by TomFinley** [dotnet/machinelearning#2268]
We ought to internalize as much of that assembly to those things we want to be public. The trouble with this one is that the API for ensembling, it is unclear what a good public version would look like and we don't have time to develop it. So it may be that at least for now internalizing the *whole thing* is the answer.

Complicating matters, FastTree depends on this assembly; it may do so for good or bad reasons, I am not sure. That should be investigated. If it is not doing so for important reasons, we could break that dependency in some fashion, and then put Ensemble in a separate Nuget that we will keep in a sub-v1 version even as much of the API becomes v1.

**Comment by acqs** [comment]
Understandable given resource constraints and the need to focus on expanding algorithm support and infrastructure.  That said, ensembles have become mainstream, and are a necessity to realizing the full potential of the amazing work you guys have done constructing the tool thus far.  Keep up it up!  First class software architecture is hard to come by in data science.  Having evaluated hundreds of open source and vendor solutions, this is the first I’ve seen.
