### ISSUE TITLE
ONNXML.cs needs to be generated at BUILD

### ISSUE THREAD

**Issue by codemzs** [dotnet/machinelearning#2291]
Currently ONNXML.cs is generated manually using protobuf definition. It is also included as part of code coverage which should not happen and PR #2290 will remove it. We need to make it such that it is clear that file is not authored by ML.NET team and is coming from an external source. 

CC: @wschin , @shauheen , @TomFinley

**Comment by eerhardt** [comment]
I don't agree that this file needs to be generated during the build. Using the same code generation tool and the same version of the protobuf definition, the same C# file will be generated. There is no reason to do that generation on every build.

Another reason to not take this approach is [Source Link debugging](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink). If someone was trying to debug into this code, it wouldn't be possible if we didn't have it checked into our source control.

> We need to make it such that it is clear that file is not authored by ML.NET team and is coming from an external source.

This is usually done by the following header in the .cs file:

https://github.com/dotnet/machinelearning/blob/22ea6d101d049a47ddf125a1e96924b754454016/src/Microsoft.ML.Onnx/OnnxMl.cs#L1-L4

**Comment by harishsk** [comment]
I agree with @eerhardt. The format that ML.NET requires this file to be in is different from the generated version. We can choose to wrap the generated code, but that would be a lot of needless abstraction.
