### ISSUE TITLE
AvxIntrinsics.DotSU is Slower than the native version 

### ISSUE THREAD

**Issue by Anipik** [dotnet/machinelearning#2298]
We can verify this by running the benchmark https://github.com/dotnet/machinelearning/blob/master/test/Microsoft.ML.Benchmarks/Text/MultiClassClassification.cs#L62

``` ini


```
|      Method |     (netcoreapp2.1)Mean |    Error |   StdDev |        netcoreapp3.0 |
|------------ |--------------:|---------:|---------:|--------------------:|
| CV_Multiclass_WikiDetox_WordEmbeddings_OVAAveragedPerceptron| 148.84s | 28.107 s | 1.5 s | 158.3s |

I verified using the perfview that the cause of regression is DotSU. The exclusive time fot DotSU on netcoreapp3.0  is 70s and on native version of cpumath is 47 s

This failure is not due to small array size. The size of the arrays involved is in thousands

cc @danmosemsft @adamsitnik @tannergooding @eerhardt

**Comment by helloguo** [comment]
@Anipik which machine does this benchmark run on? Does the machine support AVX2 instructions?

**Comment by danmosemsft** [comment]
@Anipik ? 

We should fix this and #2253 one way or another - such as possibly going down a non SIMD path if the input is not appropriate. It's important that if you move to 3.0, everything is faster (or at least not slower) without exception.

**Comment by Anipik** [comment]
Yes this is on my to-do list.  I will correct this regression

**Comment by Anipik** [comment]
@helloguo yes the machine supports avx2. It runs on a windows machine with an intel processor.

**Comment by Anipik** [comment]
This regression is not caused by this, it is mostly caused by ```SequencePool.GetCore```
The rest is just flakiness. I verified by using the netcoreapp2.1 implementation of dotproductSparse with netcoreapp3.0

**Comment by Anipik** [comment]
This function is tracked by https://github.com/dotnet/machinelearning/issues/2293
