### ISSUE TITLE
Add Evaluate overload that takes IDataView

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/machinelearning#23]
_From @eerhardt on May 1, 2018, 9:52 AM PDT_

See comment _From @glebuk created May 1, 2018, 8:52 AM PDT_ for file `src/Microsoft.ML/Models/BinaryClassificationEvaluator.cs` on line below:

```
public BinaryClassificationMetrics Evaluate(PredictionModel model, ILearningPipelineLoader testData)
```

>Evaluate [](start = 43, length = 8)

We should add another overload to evaluate against a scored IDV.  There you'd need to specify columns for actual, predicted labels and score. (ok to ship after build) #Closed

**Comment by bartczernicki** [comment]
+1 this would be a big step up.

**Comment by shauheen** [comment]
With #371 this will not be needed anymore. Closing this issue.
