### ISSUE TITLE
All namespaces should have a top-level description

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#2310]
Currently none of our namespaces has a top-level description, causing the description column to be completely empty at [the docs site](https://docs.microsoft.com/en-us/dotnet/api/index?view=ml-dotnet)

**Comment by eerhardt** [comment]
Is it like one of these?

https://stackoverflow.com/questions/793210/xml-documentation-for-a-namespace

**Comment by JRAlexander** [comment]
Yes. Here is the guidance: https://review.docs.microsoft.com/en-us/help/onboard/admin/reference/dotnet/documenting-api?branch=master - Here's a couple of examples as well: https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.server?view=netcore-2.2 https://docs.microsoft.com/en-us/dotnet/api/system?view=netcore-2.2

**Comment by eerhardt** [comment]
It looks like the .xml file is checked in (at least for `System.Linq.Expressions`):

https://github.com/dotnet/dotnet-api-docs/blob/4f841e404d68e8b6a440b10af721d8868ec99776/xml/ns-System.Linq.Expressions.xml#L3

**Comment by sfilipi** [comment]
sorry, just noticed this discussion. The work is actually happening in the docs repo: https://github.com/dotnet/ml-api-docs/pull/81

**Comment by sfilipi** [comment]
closed through https://github.com/dotnet/ml-api-docs/pull/81
