### ISSUE TITLE
Clean up the XmlInclude EntryPoint attribute annotations

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#2325]
The `XmlInclude` EntryPoint annotation attribute was created when we needed to simultaneously document the so called runtime classes, and the autogenerated CSharpApi.cs classes. 

Now that the auto-generated C#api is gone, there is no need to have the `XmlInclude` EntryPoint annotation attribute.

So searching for `XmlInclude ` and deleting it everywhere would consider this work item complete.

**Comment by mareklinka** [comment]
I can take a look at this, get it sorted out.
