### ISSUE TITLE
Finalize documentation for ValueToKeyMapping (aka TermTransform)

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#2332]
The documentation and samples for the `ValueToKeyMapping` is almost in place, but the documentation could use more remarks, like answering the "what is this / why would you use this?" questions, and links to the samples.

**Comment by singlis** [comment]
Do you mean the ValueMappingTransform? This was formerly the TermTransform.

**Comment by rogancarr** [comment]
Yes -- it looks like you're drawing up samples for this, so I'll assign this to you! You'll just need to add links to the documentation from the catalog.

**Comment by shmoradims** [comment]
@abgoswam please confirm that we addressed this already.

**Comment by abgoswam** [comment]
Closed. Verified that we have added docs for the MapValue transform
