### ISSUE TITLE
KeyType missing documentation for a few methods/parameters

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#2333]
The following properties of KeyType are missing documentation
- Contiguous
- Equals(ColumnType)
- Equals(Object)
- GetHashCode()
- ToString()

**Comment by TomFinley** [comment]
Contiguous should have been gone. Indeed I am surprised to see that it is still there. Maybe @artidoro has more info.

The others, I wonder if there's something like inheritdoc or something for implementations of common methods and overrides from stuff already in .NET standard library.

**Comment by artidoro** [comment]
It's gone in the current version of the code. 
However, if you are looking at the MDocs it will probably still be there at least until we update it with the new nuget.
