### ISSUE TITLE
MultiClassClassifier.Evaluate calculates the confusion matrix, but doesn't make it accessible to the user

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#2335]
The [Evaluate](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Data/Evaluators/MultiClassClassifierEvaluator.cs#L519) method in the MultiClassClassifierEvaluator, calculates the overall metrics, and the confusionTable, but makes no use of the confusion table. 

The confusion table should be part of the MultiClassClassifierMetrics.

**Comment by eerhardt** [comment]
Can this API be added after v1.0 without a breaking change? If so, it might not qualify for Project 13.

**Comment by Ivanidzo4ka** [comment]
duplicate of https://github.com/dotnet/machinelearning/issues/2009
