### ISSUE TITLE
TrainTestSplit should be inside MLContext.Data 

### ISSUE THREAD

**Issue by artidoro** [dotnet/machinelearning#2337]
Currently `TrainTestSplit` can be found in the various training tasks in `MLContext`:

https://github.com/dotnet/machinelearning/blob/533171a430063c5db234aff20e6d39e6673d3c4d/test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamples.cs#L604-L605 

Since that is a data operation that only involves splitting data and since it is independent on the training task, it would make more sense to have it in `mlContext.Data`. The previous line would look like:

```csharp
var (trainData, testData) = mlContext.Data.TrainTestSplit(data, testFraction: 0.1);
```

**Comment by TomFinley** [comment]
> since it is independent on the training task,

Well, not exactly. In the case of ranking, for example, it is critical that the split be stratified on a sort of group ID. But we might consider that we expect that having the stratification is an *option*, and if someone doesn't realize stratification is important for a task like ranking, well... that's just too bad.

But I would at least be aware of this issue.

Also this *does* imply a breaking change, so I'm adding it to Project 13.
