### ISSUE TITLE
Make SweepableParamAttribute and related classes public

### ISSUE THREAD

**Issue by daholste** [dotnet/machinelearning#2338]
If SweepableParamAttribute and related classes were public, AutoML could leverage them :). As AutoML iterates to recommend improvements in sweep ranges, the main repo could benefit

**Comment by TomFinley** [comment]
This is deliberate. Machinery relating to entry-points and command-line parsing is not part of our public API surface. As discussed in other contexts, I suggest you make AutoML, not auto-AutoML. Thanks.

**Comment by TomFinley** [comment]
I think this has been sufficiently addressed, so closing for now, thanks all.
