### ISSUE TITLE
Trying to add and run OrdinaryLeastSquaresRegressor throwing not supported error and missing Mkl libary.

### ISSUE THREAD

**Issue by jbursey** [dotnet/machinelearning#234]
### System information

- Windows 10 Pro
- dotnet core 2.0

### Issue

- Tried to run taxi fare prediction example using ordinary least squares instead of fast tree
- Library error missing Mkl libary.
- Model created.

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

![image](https://user-images.githubusercontent.com/17802262/40496707-0944c482-5f40-11e8-935a-e1f45a40474a.png)

![image](https://user-images.githubusercontent.com/17802262/40496735-18ebc282-5f40-11e8-853d-6ffa89ea0a26.png)

**Comment by shauheen** [comment]
@jbursey I will close this issue as OLS was disabled. We will continue working on enabling them and track this with #497 .
