### ISSUE TITLE
DataView.GetColumn<T> returns incorrect data for vector columns

### ISSUE THREAD

**Issue by daholste** [dotnet/machinelearning#2341]
Ran the C# code:
```C#
var values = data.GetColumn<VBuffer<float>>(new MLContext(), "col");
```
All the returned values were identical, and equal to the last value in the column.
I think the bug is that this code
https://github.com/dotnet/machinelearning/blob/7fc7e50ce6f8fed24fc0b9528839a0ac8d0ed320/src/Microsoft.ML.Data/Utilities/ColumnCursor.cs#L90-L95
should be
```C#
while (cursor.MoveNext())
{
   T curValue = default;
   getter(ref curValue);
   yield return curValue;
}
```

Also, it would be really helpful if you could override the Equals & GetHashCode methods on VBuffer, for use cases like values.Distinct().Count(), etc. Thanks!

**Comment by Ivanidzo4ka** [comment]
https://github.com/dotnet/machinelearning/blob/46efb8ed90d90d6e444394c3e3f5fbe16214109a/docs/samples/Microsoft.ML.Samples/Dynamic/LdaTransform.cs#L40
I played with it today, and it worked fine.
Can you provide more information? Some steps to reproduce problem?
You code would just force value to be default before we call getter, and getter should replace default value anyway, so i'm not sure you proposal make sense.

I would also suggest to take a look on our documentation for VBuffer https://github.com/dotnet/machinelearning/blob/80f5720438d544b1c9cf019a889479d8e67d5837/docs/code/VBufferCareFeeding.md#why-buffer-reuse

**Comment by daholste** [comment]
Hey, Ivan!
Try out this code -- I played with it today as well!
```C#
            var dataBuilder = new ArrayDataViewBuilder(new MLContext());
            var colNames = new[] { "Col1", "Col2" };
            var colValues = new List<float[]>
            {
                new float[] { 0, 0 },
                new float[] { 1, 1 },
                new float[] { 1, 1 },
                new float[] { 0, 0 },
                new float[] { 2, 2 },
                new float[] { 1, 1 },
            };
            dataBuilder.AddColumn("0", GetKeyValueGetter(colNames), NumberType.R4, colValues.ToArray());
            var data = dataBuilder.GetDataView();

            var values1 = new List<VBuffer<float>>();
            var cursor = data.GetRowCursor(data.Schema[0]);
            var getter = cursor.GetGetter<VBuffer<float>>(0);
            while (cursor.MoveNext())
            {
                var value = default(VBuffer<float>);
                getter(ref value);
                values1.Add(value);
            }
            var p = values1.Distinct().Count();

            var values2 = data.GetColumn<VBuffer<float>>(new MLContext(), "0");
            var values2Copy = new List<object>();
            foreach(var x in values2)
            {
                values2Copy.Add(x);
            }
            var q = values2Copy.Distinct().Count();
```

Note how p = 1, and q = 6

**Comment by daholste** [comment]
Also, the issue with the current code is that it returns a long list of identical pointers to a single VBuffer

**Comment by Ivanidzo4ka** [comment]
Our cursor reuses VBuffers. All our code rely on fact what you can reuse VBuffers, this is our way you avoid garbage collection. 
Yes, GetColumn for VBuffer basically use one pointer all the time and you suggest to create new pointer for every yield. This is intended.
Good news, you can just use array of floats instead of VBuffer of floats.
`var values = data.GetColumn<floa[]>(new MLContext(), "col");`
It should help you with identical results, and you don't have to use VBuffer.
Isn't this great?

**Comment by daholste** [comment]
Awesome! In that case, with the example you posted in your first reply, I think it's still buggy:
https://github.com/dotnet/machinelearning/blob/46efb8ed90d90d6e444394c3e3f5fbe16214109a/docs/samples/Microsoft.ML.Samples/Dynamic/LdaTransform.cs#L40
In this example code, GetColumn<VBuffer<float>> will return all identical values?
Thanks for the float[] fix!

**Comment by Ivanidzo4ka** [comment]
>In this example code, GetColumn<VBuffer> will return all identical values?

Idea behind VBuffer is to reuse memory. If you enumerate over that ldaFeaturesColumn and print results, it will give you different results. But each time we will use same allocated memory. So if you decide to do your
```
var values2 = data.GetColumn<VBuffer<float>>(new MLContext(), "0");
 var values2Copy = new List<object>();
            foreach(var x in values2)
            {
                values2Copy.Add(x);
            }
```
You will get same pointer all the time. Content in that pointer would be different during each yield, but pointer would be same.

**Comment by daholste** [comment]
Ah, got it! Thanks for bearing with me & the explanations, Ivan! And for opening https://github.com/dotnet/machinelearning/issues/2352!
