### ISSUE TITLE
Tests in CpuMathUtilsUnitTests are culture sensitive

### ISSUE THREAD

**Issue by mareklinka** [dotnet/machinelearning#2342]
Hello all. While working on #2325 I noticed that tests in class `CpuMathUtilsUnitTests` seem to be locale-sensitive. My computer uses Slovak locale, which uses comma (`,`) as a decimal separator. Simply running these tests leads to failures with exception message `Input string was not in a correct format.` This is coming from `float.Parse` calls.

Setting `CultureInfo.CurrentCulture = CultureInfo.InvariantCulture;` in the class constructor resolves the failures.

This should probably be resolved to lower friction for non-English contributors.

**Comment by sfilipi** [comment]
@mareklinka thanks for reporting. Feel free to submit a PR, if you have the fix locally.
