### ISSUE TITLE
ValueMappingEstimator in the Conversions catalog is missing the treatAsKeys parameter

### ISSUE THREAD

**Issue by singlis** [dotnet/machinelearning#2346]
When adding samples, I noticed that the treatValuesAsKeys parameter is not available as part of the Conversions catalog. Therefore I am not able to do this:
```
         var pipeline = ml.Transforms.Conversions.ValueMap(educationKeys, educationValues, true, ("EducationKeyType", "Education"));
```

And instead have to do this:
```
            var pipeline = new ValueMappingEstimator<string, string>(ml, educationKeys, educationValues, true, ("EducationKeyType", "Education"));
```

Therefore we should add another function to the Conversions Catalog to handle this.

**Comment by Ivanidzo4ka** [comment]
Is it still relevant? If yes, would you have time to fix it?

**Comment by singlis** [comment]
Note this was added by @artidoro, #2959
