### ISSUE TITLE
ValueToKeyEstimator constructors should be cleaned and documented better

### ISSUE THREAD

**Issue by artidoro** [dotnet/machinelearning#2358]
There 3 problems in the constructors/catalog of the ValueToKey estimator:
1. The `ColumnInfo` object has two fields: `Terms`  and `Term`,  that are meant to serve the same function. 
2. Futhermore, it would probably make more sense to break the constructor in two. Providing `KeyData` should be in alternative to a list of terms. Right now it can be quite confusing to be able to set all of them together.
3. Lastly, what happens when we specify several columns in `ColumnInfo[]` and also `KeyData` does `keyData` apply to all the columns?

https://github.com/dotnet/machinelearning/blob/e3830910531f00013c27391914233a085a1394a4/src/Microsoft.ML.Data/Transforms/ValueToKeyMappingEstimator.cs#L34-L39

**Comment by shmoradims** [comment]
@yaeldekel, could you please check if this is already fixed.

**Comment by artidoro** [comment]
We have fixed all these problems already in our various cleanups of the API. Now we have convenience constructors in `MLContext`.
