### ISSUE TITLE
Natural language generation from structured data

### ISSUE THREAD

**Issue by anirudhsamudrala** [dotnet/machinelearning#237]
does ML.NET have a capability to extract text out of structured data ? Say for example , we have a stock data of a company over some years. I want to generate text based on a template for YoY Analysis.

**Comment by zeahmed** [comment]
Thanks for the question. Can you please elaborate more on this?
I don't understand if you want to do text extraction or generation?

**Comment by anirudhsamudrala** [comment]
Its text generation, I am talking about. Say I have sales for 2017 as 4M $ and 2018 its 5M$. I want to be able to generate text based on a template some think like this. " The sales increased from 4M $ to 5M $ by xyz percentage.".

**Comment by codemzs** [comment]
closing as more info has not been provided since last year. Also as @zeahmed points this does not need ML. You seem to want to do some intelligent text generation using ML which can be achieved by using our transforms, trainers and some custom code that uses predictions results to generate text.
