### ISSUE TITLE
SelectColumns handles input string arrays differently than other schema transformations

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#2371]
`SelectColumns` has a different input contract than related schema manipulation transforms. Look at the difference:

```cs
mlContext.Transforms.DropColumns("Column1", "Column2");
mlContext.Transforms.SelectColumns(new string[] { "Column1", "Column2" })
```

**Comment by rogancarr** [comment]
I think this happens because there is an optional parameter that comes after `keepColumns`, which means we can't use it as a `params` parameter.

**Comment by TomFinley** [comment]
Yes. You could potentially introduce an overload:

```csharp
public static ColumnSelectingEstimator SelectColumns(this TransformsCatalog catalog,
            params string[] keepColumns) => catalog.SelectColumns(keepColumns, false);
```

Or something along these lines.

As you've observed, it is due to (1) the presence of multiple parameters and (2) the preference that we like to put column names towards-ish the front, even if there are multiple of them.
