### ISSUE TITLE
Parameter name Consistency in FastTree

### ISSUE THREAD

**Issue by srsaggam** [dotnet/machinelearning#2375]
https://github.com/dotnet/machinelearning/blob/4bb3e0006c656387ec96dc7e5878e204e1710f50/src/Microsoft.ML.FastTree/FastTreeArguments.cs#L528

Should this be LearningRate? The Options have it named wrongly.

The named parameter for the FastTree is named correctly as learningRate.
https://github.com/dotnet/machinelearning/blob/4bb3e0006c656387ec96dc7e5878e204e1710f50/src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs#L34

It would be great if you can check the same with all the trainers and transforms. i.e the named parameters(in the method) resemble the Actual Property name(in the options). In my opinion these all should be consistent. In case of named params (camel case) and for actual Property (of course is pascal case)

**Comment by srsaggam** [comment]
@justinormont @vinodshanbhag  @daholste

**Comment by srsaggam** [comment]
@abgoswam Can you please take a look at this?

**Comment by justinormont** [comment]
We should go one step further and take up the larger task of verifying a unified naming scheme for all parameters across all components before the v1.0 release. After the release renaming parameters will be difficult.
/cc @glebuk

**Comment by abgoswam** [comment]
Also related to #2172   to bring consistency in naming convention.

**Comment by wschin** [comment]
It will be a part of #2617.
