### ISSUE TITLE
Add Ubuntu CI leg

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/machinelearning#2381]
Right now we build and test for Linux on only one distro -- Centos 7 (a container hosted on Ubuntu 1804). We use .NET Core 2.1.

We maybe should add a leg to test on a Debian/Ubuntu family distro (Centos is in the RedHat family). That should be able to use all the same binaries. If we did that it would probably be good to use .NET Core 3.0 instead of 2.1 to get Linux coverage with that.

.NET Core also supports Alpine, which some people use to minimise the size and security surface of their containers. It would be more "interesting" (takes= more work to support) because as well as having few default packages it is musl not glibc based so it needs a special build. We probably have to defer support for Alpine.

@eerhardt thoughts?

**Comment by eerhardt** [comment]
We've also discussed adding an Ubuntu leg for the OnnxTransform tests, since the OnnxRuntime doesn't support CentOS/RedHat 7.

/cc @jignparm

**Comment by jignparm** [comment]
PR #2516 adds an Ubuntu CI leg. 

It's still using .NET Core 2.1, but it looks like the upgrade to .Net Core 3.0 can be done after the buildtool changes mentioned on the PR.
