### ISSUE TITLE
ValueMapping: Write test for schema propagation for all types of inputs.

### ISSUE THREAD

**Issue by zeahmed** [dotnet/machinelearning#2410]
There is a ValueMapping test that test for the schema propagation for `ValueMapperEstimator` and `ValueMapperTransformer`
https://github.com/dotnet/machinelearning/blob/2dfc51aa7172199c1b2145e48ecb9eb855bb87f1/test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs#L506

This test is not complete in a sense that it does not test all the possible inputs that can be provided to `ValueMapperEstimator`. It should test the ValueMapperEstimator on all possible data type the estimator can take as input and on all possible maps types.  

CC: @artidoro, @singlis

**Comment by Ivanidzo4ka** [comment]
Is this one done or not? I can see two merged PRs. Can we close this one?
