### ISSUE TITLE
Unable to find TensorFlow dll

### ISSUE THREAD

**Issue by ileve** [dotnet/machinelearning#2423]
### System information

- **OS version/distro**: Win7-x64
- **.NET Version (eg., dotnet --info)**: NET.Core SDK 2.1.502 and project target NET.Core 2.1
Visual Studio version 15.9.4

### **Unable to find TensorFlow DLL**

- **What did you do?**
I tried to run the example [TensorFlowTransform](https://github.com/dotnet/machinelearning/blob/e3830910531f00013c27391914233a085a1394a4/docs/samples/Microsoft.ML.Samples/Dynamic/TensorFlowTransform.cs)

- **What happened?**

When the method `ScoreTensorFlowModel` is invoked, I receive the following runtime exception:

`Unable to load DLL 'tensorflow' or one of its dependencies: Exception from HRESULT: 0xC000001D`

- **What did you expect?**

### Source code / logs

I used version `0.11.0-preview-27405-2`. I also tried to set build target to x64 but didn't work.
I also notice that the static extension method `ApplyTensorFlowGraph` is not available in nuget package.

**Comment by Ivanidzo4ka** [comment]
Do you have same behavior on official 0.10 nuget?
Do you have [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) on your machine?

**Comment by ileve** [comment]
Thanks for the response. I have installed `Visual C++ Redistributable for Visual Studio 2015 x64 and x86`. I also tested in version `0.10.0`. Same result.

And `ApplyTensorFlowGraph` is not part of `StaticPipe` nuget. I tested it too.

**Comment by ileve** [comment]
I tested on a Win10-x64 installation and it works. Thus it has to do with Windows 7. The installation is `Win7-x64 SP1`. The GPU is `AMD Radeon HD 5670`.

**Comment by Ivanidzo4ka** [comment]
@zeahmed can you help us? Is where any limitation on windows version?

**Comment by zeahmed** [comment]
There is no known restriction on windows version till now.  [TensorFlow C-API ](https://www.tensorflow.org/install/lang_c) also does not state any windows version issue. So, I think its related to some missing dependency on win7.

@ileve, can you please check if these dependency are install on win7?
[`Microsoft Visual C++ 2015 Redistributable Update 3`](https://www.tensorflow.org/install/source_windows#install_visual_c_build_tools_2015)
specifically Update 3?

**Comment by ericstj** [comment]
`0xC000001D` is STATUS_ILLEGAL_INSTRUCTION

Is it possible the TF version is relying on CPU instructions not supported on your processor?  Does your processor support AVX?

**Comment by danmosemsft** [comment]
Is this coming from LoadLibrary? If so then enabling loader snaps might provide useful information, such as which Dll in the closure.

https://blogs.msdn.microsoft.com/junfeng/2006/11/20/debugging-loadlibrary-failures/

**Comment by ileve** [comment]
I installed `C++ 2015 Update 3` and it didn't work. The CPU on my `Win7-x64` PC is first generation `i7 930` which does not support `AVX`. I guess there is no need for further investigation with a window debugger.

As already mentioned, the successful test was on a `Win10-x64` laptop with a CPU that supports `AVX`.

**Comment by ileve** [comment]
Well I have to reconsider the situation. When i successfully run on `Win10-x64` I receive the message:

`I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2`

Thus the compiled `TensorFlow.dll` in `ML.NET 0.10.0` does not use `AVX` instructions.

**Comment by zeahmed** [comment]
ML.NET directly uses the pre-compiled dlls from https://www.tensorflow.org/install/lang_c.

These binaries are not built for every instruction set. If you want to make use of your CPU instruction set you will have to built it yourself by setting appropirate build flags.

Maybe the following stack-overflow discussion will be helpful in this regard.
https://stackoverflow.com/questions/47068709/your-cpu-supports-instructions-that-this-tensorflow-binary-was-not-compiled-to-u

**Comment by ericstj** [comment]
> Thus the compiled `TensorFlow.dll` in `ML.NET 0.10.0` does not use `AVX` instructions.

AVX and AVX2 are different instruction sets.  That message is just telling you that you could have a more performant TF dll if you recompiled it to use AVX2.  I wonder if the TF folks could do runtime light-up for this stuff rather than cross-compiling.  Cross-compiling is not very "portable" for things like this.  That would fix the illegal instruction problem and avoid the annoying log.  Of course its a size/complexity tradeoff, but naively I would imagine it's somewhere less than 2x since not all instructions / codepaths would need to be different.

**Comment by ericstj** [comment]
I've opened https://github.com/tensorflow/tensorflow/issues/25590 on TF to see if this can be improved.

**Comment by najeeb-kazmi** [comment]
@ileve sounds like this issue is resolved. Summary: The CPU on Win7-x64 does not support AVX, and the warning about AVX2 is just saying that you could have better performance if TF dll was recompiled to AVX2.

Please reopen if this is still an issue.
