### ISSUE TITLE
Some micro optimizations for performance are possible.

### ISSUE THREAD

**Issue by Oxoron** [dotnet/machinelearning#243]
### Some micro optimizations for performance are possible.

For.ex. in the PerLabelL1 property ( [see link](https://github.com/dotnet/machinelearning/blob/33c8364032570003bbdc0bee3c4546df35661c49/src/Microsoft.ML.Data/Evaluators/MultiOutputRegressionEvaluator.cs#L194)) we divide all array's elements onto the single _sumWeight value, in the loop. If we compute 1/_sumWeight division before a loop, we can multiply all element on computed value, that speeds up an execution time 4 times (see example below and in the attach).

### Source code / logs

```
        private static int _sumWeights = 14;        

        public static double[] OriginDivideArray(this double[] _l1Loss)
        {
            var res = new double[_l1Loss.Length];
            if (_sumWeights == 0)
                return res;
            for (int i = 0; i < _l1Loss.Length; i++)
                res[i] = _l1Loss[i] / _sumWeights;
            return res;
        }

        public static double[] OptimizedDivideArray(this double[] _l1Loss)
        {
            var res = new double[_l1Loss.Length];
            if (_sumWeights == 0)
                return res;

            var revSumWeights = 1 / _sumWeights; // Cache division result here

            for (int i = 0; i < _l1Loss.Length; i++)
                res[i] = _l1Loss[i] * revSumWeights; // Update division to mult here
            return res;
        }
```

The question is: do we need these optimizations? On a 1000 elements array it saves us just some microseconds.

![image](https://user-images.githubusercontent.com/6274989/40575161-2fa1a52e-60e8-11e8-97b0-f96e2e28f2bb.png)
[PointsToImprove.txt](https://github.com/dotnet/machinelearning/files/2041529/PointsToImprove.txt)
[Program.zip](https://github.com/dotnet/machinelearning/files/2041531/Program.zip)

**Comment by codemzs** [comment]
thanks but in practice this won't add a lot of perf improvement and the math is easier to understand with the current setup.
