### ISSUE TITLE
Very scanty documentation - 

### ISSUE THREAD

**Issue by sdg002** [dotnet/machinelearning#2443]
No sample code. What value is this page providing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c4f07b9-e625-aa2e-940a-69bedbe67a3b
* Version Independent ID: 1f4fe341-3c68-bc18-06d2-480c6283a609
* Content: [LightGbm Class (Microsoft.ML.LightGBM)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.lightgbm.lightgbm?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML.LightGBM/LightGbm.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.LightGBM/LightGbm.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by shmoradims** [comment]
We have improved API reference documentation for ML.NET 1.0. For e.g. [LightGbmBinaryTrainer](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.lightgbm.lightgbmbinarytrainer?view=ml-dotnet) contains all the trainer details. The examples are only added to the extension method that are mentioned throughout the page above (images below). This pattern is used for all of our trainers as discussed in #3218.

![image](https://user-images.githubusercontent.com/15950225/58123697-4222eb00-7bc1-11e9-8b5e-991d9473843d.png)

![image](https://user-images.githubusercontent.com/15950225/58123714-51099d80-7bc1-11e9-9fec-f7eb642aec1b.png)
