### ISSUE TITLE
Issue with training data

### ISSUE THREAD

**Issue by atotalnoob** [dotnet/machinelearning#245]
https://github.com/dotnet/machinelearning/blob/master/test/data/wikipedia-detox-250-line-data.tsv

"We can make this file beautiful and searchable if this error is corrected: Unclosed quoted field on line 83."

Needs a quote on line 83.

**Comment by justinormont** [comment]
Yep. Looks like line 83 could use an end quote. We should check if the original dataset has the same issue, or if it was introduced by when we created the shorter (250 line) form of the dataset.

https://github.com/dotnet/machinelearning/blob/ca8d46a0ca667225194cf1c86ae6fa3b72869b69/test/data/wikipedia-detox-250-line-data.tsv#L83

If it's in the original dataset in the current form, I'd be more inclined to leave it. Dirty data is expected in the ML process. As a separate issue, our TextLoader (much like GitHub's) should be improved to handle dirty data more elegantly.

**Comment by atotalnoob** [comment]
Hey Justin,

It runs just fine with the dirty data. I didn't even think of using "dirty"
data as testing. Maybe a "clean" and "dirty" data set both? One for just
playing around with, one for testing the "hardiness" of the pipeline.

**Comment by Ivanidzo4ka** [comment]
DRI RESPONSE:
We had attempt to change wiki dataset, but in the end we decide what we don't want to do that.
https://github.com/dotnet/machinelearning/pull/730 see discussion.
I'm intent to close this issue, if no one reply within next few days.
