### ISSUE TITLE
TensorFlowTransformer is not properly matching the input dimensions

### ISSUE THREAD

**Issue by LucasFievet** [dotnet/machinelearning#2458]
### System information

- **OS version/distro**: Windows 10/Pro
- **.NET Version (eg., dotnet --info)**: .NET Version 2.1.202
- ML.TensorFlow Version 0.10

### Issue

- **What did you do?**: Executed a TensorFlow model using TensorFlowEstimator
- **What happened?**: Mapper does not properly match the input dimensions to the TensorFlow model dimensions
- **What did you expect?**: Properly matched dimensions

### Source code / logs

TensorFlowTransform.cs, Lines 810 - 875

Line 853:

var d = originalShape.NumDimensions > 2 ? Math.Pow(typeValueCount / valCount, 1.0 / (originalShape.NumDimensions - 2)) : 1;

The case with 2 dimensions, where the originalShape is [1, ?] is not matched properly.

**Comment by Ivanidzo4ka** [comment]
@yaeldekel https://github.com/dotnet/machinelearning/blob/453f19191d9a7492030829fc1890fe68c41a3bcf/src/Microsoft.ML.TensorFlow/TensorflowTransform.cs#L853
do you know why we setting variable length only for tensors with size more than 2?
@zeahmed do we have tests with variable length? If yes, I believe it's probably for images, can we have test for two dimensional model?

**Comment by zeahmed** [comment]
No, this is the bug and I am going to make a fix for it.
