### ISSUE TITLE
Is there any end to end C# sample code using LightGBM  ?

### ISSUE THREAD

**Issue by sdg002** [dotnet/machinelearning#2459]
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**:  4.6

### Issue

- **What did you do?**
- **What happened?**
- **What did you expect?**

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by sfilipi** [comment]
Hi @sdg002, 
we are working on samples and API documentations for the next release. 
In the meantime, for reading text (your other question) you can see this sample:

https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/ImageAnalytics/ConvertToGrayScale.cs#L33

What task do you need LightGBM for: binary classification, regression etc. so I can point you to the right sample?

**Comment by sdg002** [comment]
Hi @sfilipi ,
Thanks for the quick reply.
I was looking for a "hello world" style sample using LightGBM for binary classification.  A sample that is easy to copy over or download as a ZIP, does not deal with too much data but helps in explaining the API.

If you remember the older MSDN style documentation of .NET Framework , you would know what I am referring to.  I never had to look anywhere else. 
The  SQL Server books online is a classic example:
https://docs.microsoft.com/en-us/sql/2014-toc/books-online-for-sql-server-2014?view=sql-server-2014


thank you,
Saurabh
