### ISSUE TITLE
The method Read of TextLoader does not check for the presence of the file.

### ISSUE THREAD

**Issue by sdg002** [dotnet/machinelearning#2461]
### System information

- **OS version/distro**:Windows 10
- **.NET Version (eg., dotnet --info)**: .NET 4.6

### Issue

- **What did you do?**
- **What happened?**
- **What did you expect?**

### Source code / logs
The method Read of the class TextLoader does not validate the presence of the input file. I understand that there is an element of lazy loading here. But, it would help to get feedback earlier in the form of System.IO.FileNotFoundException

**Comment by nextnode-managedcode** [comment]
I would like to work on this issue.

**Comment by mstfbl** [comment]
Hi @sdg002 , can you please specify which exact method of TextLoader you are talking about? I can find a function "Read" of TextLoader.

**Comment by mstfbl** [comment]
Update: I believe the "Read" method @sdg002 is referring to was the ReadFromTextFile function, that is now renamed LoadFromTextFile:

https://github.com/dotnet/machinelearning/blob/a072b5e720409ba593c94b9e76e3daa05662f6ac/src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderSaverCatalog.cs#L148-L154
