### ISSUE TITLE
ConvertToOnnx throws Protobuf exception

### ISSUE THREAD

**Issue by XamlBrewer** [dotnet/machinelearning#2463]
### System information

- **OS version/distro**: Windows 10 Pro 1809 17763.253
- **.NET Version (eg., dotnet --info)**: .NET Core 2.0 and 2.1

### Issue

- **What did you do?** Added ML.NET.Onnx NuGet package to any official sample, and a call to ConvertToOnnx.
- **What happened?** Exception: Sequence contained null element / Parameter: values / Google.Protobuf

- **What did you expect?** A successful conversion in at least one of the samples

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

Example from the Clustering_CustomerSegmentation sample (inserted after step 6):
var onnx = mlContext.Model.ConvertToOnnx(trainedModel, pivotDataView);

Same behavior is experienced in all the samples that I opened (and downgraded to v0.9).

![onnxexception](https://user-images.githubusercontent.com/9828352/52436561-e69e8700-2b14-11e9-8851-324dfc95dbef.png)

**Comment by Ivanidzo4ka** [comment]
We currently support very limited subset of trainers/transforms which can be converted to ONNX.
PCA transformation is not one of them. 

In 0.10 we would provide slightly better error, but we still don't provide which transformer/trainer not supported in pipeline.

**Comment by harishsk** [comment]
@XamlBrewer  All the estimators aren't yet convertible to onnx. But we support a much larger set than before and this issue isn't present now. If you still see it, please reopen with additional repro steps.
