### ISSUE TITLE
BinaryPredictionTransformer has a public constructor

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#2464]
`BinaryPredictionTransformer` has a `public` constructor of the form:
```cs
BinaryPredictionTransformer(IHostEnvironment env, ModelLoadContext ctx)
```

Since the usable constructor
```cs
BinaryPredictionTransformer(IHostEnvironment env, TModel model, Schema inputSchema, string featureColumn, float threshold = 0f, string thresholdColumn = DefaultColumnNames.Score)
```
is marked `internal`, it seems like the one taking a `ModelLoadContext` should be too.

**Comment by TomFinley** [comment]
Hi @rogancarr , could you clarify? This is the code as it stands right now.

https://github.com/dotnet/machinelearning/blob/56ae4eb9a566023a69419ac2b3be8cb3f3e5e905/src/Microsoft.ML.Data/Scorers/PredictionTransformer.cs#L340

**Comment by TomFinley** [comment]
Also, usually we mark things as "bugs" if they have incorrect behavior. As the description says, "something isn't working." Even if this constructor happened to be public, which AFAIK it is not, that is not something not working -- that means it's working too much! 😉

**Comment by rogancarr** [comment]
@TomFinley ! Weird. I have a version of the repo from 7 this morning. Maybe someone updated it in the meantime?

Wait, it was you, two hours ago!

I'll close the issue.
