### ISSUE TITLE
Remove the dead code inside the FastTree assembly

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#2468]
The code inside src/Microsoft.ML.FastTree/Application is not in use. 

Delete the Folder.

**Comment by codemzs** [comment]
Have you confirmed this is not used by internal repo? If it is we should make sure we move these files there after they are removed from here.

**Comment by Ivanidzo4ka** [comment]
They are used, but I don't see huge issues in restoring this files internally. 
I'm closing issue, since files and catalog no longer part of this repository.
