### ISSUE TITLE
How to normalize 2 columns simultaneously?

### ISSUE THREAD

**Issue by sdg002** [dotnet/machinelearning#2479]
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**:  .NET 4.6

### Issue

- **What did you do?**
I have loaded sample data from a text file and I am trying to normalize and print the normalized data
- **What happened?**
The max normalized value was 1.0 which is expected. The min normalized value should have been 0 or -1 but it was another positive number < 1 and > 0
- **What did you expect?**

- The minimum of the normalized values should be between 0 and 1, or -1 and +1.  **Solved using fixZero=false**
- I am confused whether I have taken the right programmatic approach

### Source code / logs
        [TestMethod]
        public void Normalize_MultipleColumn()
        {
            string pathFull = System.IO.Path.Combine(Util.GetProjectDir2(), _datafile);
            var mlContext = new Microsoft.ML.MLContext();
            Microsoft.Data.DataView.IDataView dataView = LoadDummy2(mlContext, pathFull);
            Trace.WriteLine("Before normalization");
            EnumerOverData(mlContext, dataView);
            var schema = dataView.Schema;

            var pipeline_Ht_And_Wt = mlContext.Transforms.Normalize(
                new Microsoft.ML.Transforms.Normalizers.NormalizingEstimator.MinMaxColumn("Height"),
                new Microsoft.ML.Transforms.Normalizers.NormalizingEstimator.MinMaxColumn("Weight")
                );

            var normalizedData = pipeline_Ht_And_Wt.Fit(dataView).Transform(dataView);
            Trace.WriteLine("After normalization");
            EnumerOverData(mlContext, normalizedData);
        }
        private IDataView LoadDummy2(MLContext mlContext, string pathFull)
        {
            var argsLoader = new Microsoft.ML.Data.TextLoader.Arguments();
            argsLoader.HasHeader = true;
            argsLoader.Separators = new char[] { '|' };
            argsLoader.Column = new Microsoft.ML.Data.TextLoader.Column[]
            {
                new Microsoft.ML.Data.TextLoader.Column("Id", Microsoft.ML.Data.DataKind.I4,0),
                new Microsoft.ML.Data.TextLoader.Column("Height", Microsoft.ML.Data.DataKind.R8,1),
                new Microsoft.ML.Data.TextLoader.Column("Weight", Microsoft.ML.Data.DataKind.R8,2),
                new Microsoft.ML.Data.TextLoader.Column("IsOverWeight", Microsoft.ML.Data.DataKind.Bool,3)
            };

            var loader = mlContext.Data.CreateTextLoader(argsLoader);
            Microsoft.Data.DataView.IDataView dataView = loader.Read(pathFull);
            return dataView;
        }
        private void EnumerOverData(MLContext mlContext, IDataView dataView)
        {
            var someRows = mlContext.CreateEnumerable<entity.Dummy2>(dataView, false);
            foreach (var oRow in someRows)
            {
                System.Diagnostics.Trace.WriteLine($"id={oRow.Id}    wt={oRow.Weight}   ht={oRow.Height}  isOverWt={oRow.IsOverWeight}");
            }
        }
      
### Before normalization
    id|wt|ht|overwt
    01|30.0|4.0|False
    02|35.0|4.5|False
    03|40.0|5.0|False
    10|33.0|4.0|True
    11|38.0|4.5|True
    12|43.0|5.0|True

### After normalization (fixZero=true)
    id=1    wt=0.8   ht=0.697674418604651  
    id=2    wt=0.9   ht=0.813953488372093  
    id=3    wt=1   ht=0.930232558139535  
    id=10    wt=0.8   ht=0.767441860465116  
    id=11    wt=0.9   ht=0.883720930232558  
    id=12    wt=1   ht=1  

### After normalization (fixZero=false)
    id=1    wt=0   ht=0  
    id=2    wt=0.5   ht=0.384615384615385  
    id=3    wt=1   ht=0.769230769230769  
    id=10    wt=0   ht=0.230769230769231 
    id=11    wt=0.5   ht=0.615384615384615  
    id=12    wt=1   ht=1 

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by sdg002** [comment]
Similar observation with IRIS data. I have attached the outcome of normalization. I was surprised to find that the smallest value is **0.08**. I was expecting  **0.00** . Quite possible that I am not on the right track. Please advise.
[IrisiNormalized.txt](https://github.com/dotnet/machinelearning/files/2845394/IrisiNormalized.txt)

###
        [TestMethod]
        public void NormalizeIrisData()
        {
            var mlContext = new MLContext(seed: 0);
            Microsoft.Data.DataView.IDataView dataViewTrain = LoadIris(mlContext, "data\\Iris.train.data");
            Trace.WriteLine($"Before normalizing");
            EnumerOverData(mlContext, dataViewTrain);

            var pipelineNormalized=mlContext.Transforms.Normalize(
                            new Microsoft.ML.Transforms.Normalizers.NormalizingEstimator.MinMaxColumn("SepalLength"),
                            new Microsoft.ML.Transforms.Normalizers.NormalizingEstimator.MinMaxColumn("SepalWidth"),
                            new Microsoft.ML.Transforms.Normalizers.NormalizingEstimator.MinMaxColumn("PetalLength"),
                            new Microsoft.ML.Transforms.Normalizers.NormalizingEstimator.MinMaxColumn("PetalWidth")
                            );

            var normalizedData = pipelineNormalized.Fit(dataViewTrain).Transform(dataViewTrain);
            Trace.WriteLine($"After normalizing");
            EnumerOverData(mlContext, normalizedData);

        }
        private Microsoft.Data.DataView.IDataView LoadIris(MLContext mlContext, string filename)
        {
            string pathFull = System.IO.Path.Combine(Util.GetProjectDir2(), filename);
            var argsLoader = new Microsoft.ML.Data.TextLoader.Arguments
            {
                HasHeader = false,
                Separators = new char[] { ',' },
                Column = new[]
                            {
                    new TextLoader.Column("SepalLength", DataKind.R4, 0),
                    new TextLoader.Column("SepalWidth", DataKind.R4, 1),
                    new TextLoader.Column("PetalLength", DataKind.R4, 2),
                    new TextLoader.Column("PetalWidth", DataKind.R4, 3)
                }
            };
            var textLoader = mlContext.Data.CreateTextLoader(argsLoader);
            Microsoft.Data.DataView.IDataView dataView = textLoader.Read(pathFull);
            return dataView;
        }
        private void EnumerOverData(MLContext mlContext, IDataView dataView)
        {
            var someRows = mlContext.CreateEnumerable<entity.IrisData>(dataView, false);
            System.Diagnostics.Trace.WriteLine($"SepalLength     SepalWidth      PetalLength      PetalWidth");
            foreach (var oRow in someRows)
            {
                System.Diagnostics.Trace.WriteLine($"{oRow.SepalLength}     {oRow.SepalWidth}      {oRow.PetalLength}      {oRow.PetalWidth}");
            }
        }

**Comment by sdg002** [comment]
I wasn't aware about the significance of the parameter **fixZero** . Setting to **False** does a neat 0-1 normalization.

regards

**Comment by Ivanidzo4ka** [comment]
>How to normalize 2 columns simultaneously
to answer on your question in header of the issue -> Concat them!

**Comment by TomFinley** [comment]
> I wasn't aware about the significance of the parameter **fixZero** . Setting to **False** does a neat 0-1 normalization.

It also potentially densifies, so be careful.

**Comment by rogancarr** [comment]
@sdg002 Yes, `FixZero` is kind of a tricky one. Super useful with sparse data, but can throw you off if you expect a strict 0-1 mapping!

**Comment by wschin** [comment]
Since this issue was solved, I am going to close it now!
