### ISSUE TITLE
Microsoft.ML.InternalCodeAnalyzer should use Microsoft.CodeAnalysis.Testing for harness setup

### ISSUE THREAD

**Issue by mareklinka** [dotnet/machinelearning#2480]
As discussed in [in this PR](https://github.com/dotnet/machinelearning/pull/2434#discussion_r254508809), the tests for the internal code analyzer should make use of the facilities provided in `Microsoft.CodeAnalysis.Testing`.

That would make the test project more best-practice compliant and easier to maintain.

**Comment by sharwell** [comment]
@shauheen This says assigned but I'm not sure who it's assigned to. I'm happy to work with the assignee to set up the tests and understand why things fail when they do. Some of the failure messages that appear are not at all helpful, so it's better to ask early when something fails. I'm working to update the messages for these situations but we have a long way to go.

**Comment by shauheen** [comment]
@sharwell , I had assumed that @mareklinka was interested in working on this, but as I don't see a PR. Please feel free to take it away. Please let me know so that I put assigned back.

**Comment by mareklinka** [comment]
@shauheen yes, sorry, I don't think I'll have the time to work on this in the near future.

**Comment by shauheen** [comment]
Thanks @mareklinka , no worries.
