### ISSUE TITLE
TreeEnsembleFeaturizer is not a Transformer yet

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#2482]
[TreeEnsembleFeaturizer](
https://github.com/dotnet/machinelearning/blob/6b1a0d337f74274509cfd439974dca2305a6bfbb/src/Microsoft.ML.FastTree/TreeEnsembleFeaturizer.cs#L44) is a very useful tool in many applications. Do we have a plan to make it publicly available?

cc @shauheen, @Ivanidzo4ka, @TomFinley, @yaeldekel.

**Comment by TomFinley** [comment]
This strikes me as being quite conceptually similar to #2465 -- that is, in both cases, we have a "default" way of scoring given a trained model, but we want to expose a way in which to reconfigure how that scoring happens... in that other issue, we want to set a different threshold, in this issue, we want to enable more parameters.

One place we "solve" this "changed outputs" problem for models is what we did for permutation feature importance:

https://github.com/dotnet/machinelearning/blob/834e4715afa070f5e5c3628693682943b3f0bd6d/src/Microsoft.ML.Transforms/PermutationFeatureImportanceExtensions.cs#L58-L60

If people agree this is a good idiom, we could conceivably do something similar here.

**Comment by TomFinley** [comment]
I might however identify this as work that could easily be completed post v1, since it represents new functionality, and as useful as it may be, we did after all at least internally survive *years* without having it, so maybe a month or two without it for v1 won't kill us? 😄

**Comment by rogancarr** [comment]
For thresholds, that's in our core "I cans" for v1.

If we can't guarantee that we'll get to it, maybe we can add a "dearly hoped for v1 features" stretch goals.

**Comment by TomFinley** [comment]
> For thresholds, that's in our core "I cans" for v1.
> If we can't guarantee that we'll get to it, maybe we can add a "dearly hoped for v1 features" stretch goals.

Sure @rogancarr. However, this issue isn't about thresholds, it's about tree featurization I think. You have a separate issue #2465 for that work. What I'm doing though, is identifying that the two might benefit from a similar approach.
