### ISSUE TITLE
ProductRecommander sample - System.AccessViolationException

### ISSUE THREAD

**Issue by Ikaer** [dotnet/machinelearning#2488]
### System information

- **OS version/distro**: Win10
- **.NET Version (eg., dotnet --info)**: .Net Core 2.1

### Issue

- **What did you do?** I tried the sample Product recommander with my own sample of product IDs. I first try it with the provided data (Amazon0302) and it works fine. Then I try a different file (which is attached).
- **What happened?** An exception is throw at ITransformer model = est.Fit(traindata); System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'
- **What did you expect?** To not have this kind of exception at least (this is scary) and to be able to use a different sample than the one provided.
I have the same error if, for example, I truncate the file Amazon0302 to only keep the first 10 lines.

### Source code / logs
[test_sample.txt](https://github.com/dotnet/machinelearning/files/2848725/test_sample.txt)
I just downloaded the ProductRecommander sample and replace the variable TrainingDataLocation with my own file. I reproduced the problem on two machines (one with Win10, another one with Windows Server 2016, both with .net core 2.1)

**Comment by Ivanidzo4ka** [comment]
Thank you for reporting this. I'll investigate this issue.

**Comment by Ivanidzo4ka** [comment]
If you look into sample all across it we use magic number 262111. This number is basically maximum ID +1 you have in your file. Everything above that number would be ignored.
You can put 375092 for your sample and it will work.

But that's not excuse for us to throw exception.
@wschin  I can see how matrix factorization throw exception on https://github.com/cjlin1/libmf/blob/dac39ab92d61b54806fbb214a8ccd1c3aa6eb9ee/mf.cpp#L3608 this line
If I set `u=262109` it works fine, if I set `u = 262110` it I get  `ptr` equal to null and `ptr->v` leads to exception (or b[v])

**Comment by Ikaer** [comment]
Thanks to have check it out 👍 . Really nice of you.

Just a last question, I've provided a fix sample, so I can determine this maximum ID + 1 and set the KeyCount. But ultimately, I would like to provide a dynamic sample, so I can still determine this maximum ID + 1, and I can through code set it on this line:
![image](https://user-images.githubusercontent.com/7936075/52610105-ffde6500-2e7f-11e9-9ead-241b7efecd5d.png)
But I don't know how to dynamically set it on those lines:
![image](https://user-images.githubusercontent.com/7936075/52610129-15ec2580-2e80-11e9-9a3a-79471a90e3c7.png)
