### ISSUE TITLE
Microsoft.ML.Scenarios.ScenariosTests.PredictClusters fails intermittently.

### ISSUE THREAD

**Issue by codemzs** [dotnet/machinelearning#249]
https://ci2.dot.net/job/dotnet_machinelearning/job/master/job/windows_nt_debug_prtest/277/testReport/junit/(root)/(empty)/Microsoft_ML_Scenarios_ScenariosTests_PredictClusters/

In addition I have seen it failing sporadically on my local machine.

**Comment by TomFinley** [comment]
Not setting the random seed correctly?

**Comment by Ivanidzo4ka** [comment]
or number of threads is different on different machines from the pool and we get different initial clusters

**Comment by Ivanidzo4ka** [comment]
#135 #9 related

**Comment by Ivanidzo4ka** [comment]
I'll close it for now, feel free to reopen if it's still the case.
