### ISSUE TITLE
"UnbalancedSets" not available on FastTree in v0.10

### ISSUE THREAD

**Issue by fwaris** [dotnet/machinelearning#2496]
Somehow the ability to set UnbalancedSets flag on FastTree (at least) is gone from v 0.10 API.

It was available (via a delegate) in v0.90.

**Comment by Ivanidzo4ka** [comment]
We have two constructors for trainers, one with "most important options" and one with ALL options.
we moved UnbalancedSets from "most important" constructor, but you can still access it via second constructor:
```
mlContext.BinaryClassification.Trainers.FastTree(new Trainers.FastTree.FastTreeBinaryClassificationTrainer.Options()
                {
                    UnbalancedSets=true,
                    AllOtherOptionsYouWantToSet....
                }
```

**Comment by fwaris** [comment]
got it. Thanks!
