### ISSUE TITLE
OnlineLinear trainer InitialWeights option is not user friendly

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#2519]
```
        [Argument(ArgumentType.AtMostOnce, HelpText = "Initial Weights and bias, comma-separated", ShortName = "initweights")]
        [TGUI(NoSweep = true)]
        public string InitialWeights;
```
It need to be replaced with two fields Bias and Weights and they should be float and array of floats instead of just string

**Comment by TomFinley** [comment]
I have never seen anyone use this. Not saying they can't, just, never seen it. Also I think the proper API might be a bit more involved than just this... How about we just make `internal` for now so it is retained for command line, and fix API later?
