### ISSUE TITLE
FastTree EarlyStoppingMetric is an `int` but only accepts specific values

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#2521]
In the current `Options` for `FastTree` (and `GAMs`), `EarlyStoppingMetric` is an `int`, but only specific values are accepted (e.g. 1 or 2 for regression, 1 or 3 for ranking).

It would be much cleaner if this was an enum.

**Comment by Ivanidzo4ka** [comment]
I believe this one was closed in https://github.com/dotnet/machinelearning/pull/2753
