### ISSUE TITLE
Registering subhosts when creating new catalog entries advances the pseudo random number generator

### ISSUE THREAD

**Issue by abgoswam** [dotnet/machinelearning#2523]
For creating a new catalog entry in MLContext, the existing pattern is to register subhosts i.e. create a new Host out of the environment. This advances the pseudo random number generator. 

https://github.com/dotnet/machinelearning/blob/5c442a96edc3ac7a03bc10ef668310647f16db9a/src/Microsoft.ML.Data/TrainCatalog.cs#L195-L200

This means that if we add a new catalog entry in MLContext, the baseline tests would start failing.  (In fact this is the exact behaviour observed in PR #2390 when we try to add a AnomalyDetectionCatalog entry to MLContext)

Instead of *forking* the environment we can just *store* the environment passed in.

@TomFinley

**Comment by TomFinley** [comment]
Thanks @abgoswam!!

Historical note as point of interest, this was side effect of the world pre #1098... there were separate instantiated contexts for each type of task, but then we realized "hey this idea is pretty useful" and decided to instantiate everything through that. 😛 But we forgot to stop forking the environments when we changed what had been separate contexts to catalogs within the master context.

**Comment by TomFinley** [comment]
Also not *technically* project 13 since it doesn't really change the public surface (just some minor behavior here and there), but we'll let that slide. 😄
