### ISSUE TITLE
Renaming .Train to .Fit in TrainerEstimators

### ISSUE THREAD

**Issue by artidoro** [dotnet/machinelearning#2527]
Some trainers allow training with an initial predictor, or with a validation data set. The initial predictor is used as a starting point for further training. However, the method that allows this is usually named:

```csharp
ITransformer Train(IDataView trainData, IPredictor initialPredictor = null)
```
or 
```csharp
ITransformer Train(IDataView trainData, IDataView validationData = null, IPredictor initialPredictor = null)
```

This could lead to quite a bit of confusion as the TrainerEstimators will have two methods for training -  `Fit()` and `.Train()` - that achieve pretty much the same result. In the above `initialPredictor` can be `null` so `.Fit(data)` does the same as `.Train(data)`.

As it was suggested in the issue #2502 in one of @TomFinley's comments https://github.com/dotnet/machinelearning/issues/2502#issuecomment-462493936, I think we should rename the `Train` method to `Fit`.

The result is that there will be a single method name `Fit` to train a model with an overload to perform training with an initial predictor. 

/cc: @TomFinley, @Ivanidzo4ka

**Comment by Ivanidzo4ka** [comment]
Just in case, it's not only initialPredictor, it's also validationDataset and combination of both.
Best way to find them is to search for .Train in Microsoft.ML.Tests project :)

**Comment by Ivanidzo4ka** [comment]
Actually, I lied.
https://github.com/dotnet/machinelearning/blob/a254bf58c47c1a00348fcc628f48e26dca959ee6/src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs#L134
Just look for whoever calls this method.

**Comment by artidoro** [comment]
Will do that thank you @Ivanidzo4ka!
