### ISSUE TITLE
Create Samples for LightGbm Ranker.

### ISSUE THREAD

**Issue by zeahmed** [dotnet/machinelearning#2530]
Need doc samples for lightgbm ranker. 
Reference the samples in the xml docs for the two public lightgbm ranker methods.

https://github.com/dotnet/machinelearning/blob/f8e58dd4327f4c5013abbd7f691d835bdd377909/src/Microsoft.ML.LightGBM/LightGbmCatalog.cs#L104

**Comment by Ivanidzo4ka** [comment]
if you close this one, please also close this one: https://github.com/dotnet/machinelearning/issues/776
