### ISSUE TITLE
lib_lightgbm.dll isn't published to Azure App Service

### ISSUE THREAD

**Issue by gilnahmias** [dotnet/machinelearning#2533]
Using `Microsoft.ML.LightGBM (0.9.0)` NuGet package to train locally. This succeeds.
Trying to right click | Publish the solution directly from Visual Studio to Azure App Service succeeds. When trying to train a LightGBM model on the deployed Azure App Service, I get:
```
Unable to load DLL 'lib_lightgbm' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

Examining the published files via Kudo (Azure Portal | My Service | Console | dir) shows that `lib_lightgbm.dll` isn't there.

Any special steps I should take to publish this DLL and its dependencies to Azure?

Maybe related to #1945 
cc @eerhardt @sfilipi

**Comment by eerhardt** [comment]
Are you running on `.NET Core`? If you are, it will normally be in a `runtimes\win-x64` folder.

What happens if you publish to a folder on your machine? Does the file get copied to the publish folder then?

**Comment by gilnahmias** [comment]
1. Yes I'm using `.NET Core 2.1`. 
2. When I publish to a local folder I don't see there `lib_lightgbm.dll`.
3. There is no `lib_lightgbm.dll` anywhere under  `.\bin\Debug\netcoreapp2.1\win-x64`.
4. I can find `.\obj\{Release|Debug}\netcoreapp2.1\PubTm[\Out\runtimes\win-x64\native\lib_lightgbm.dll`. However, trying to copy it directly to the Azure App Service and train, I get `An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)`

**Comment by eerhardt** [comment]
> An attempt was made to load a program with an incorrect format.

So that's a hint. Are you publishing for `x64` or `x86`?  LightGBM only supports `x64`.

**Comment by gilnahmias** [comment]
Thanks @eerhardt!
The config combo that got it training on Azure was:

_To publish:_
1. Configuration = `Release - x64`
2. Deployment Mode = `Self-Contained`
3. Target Runtime: `win-x64`

The Azure App Service itself has Platform=`32bit`.

Thanks!
