### ISSUE TITLE
Regression evaluate throws ArgumentOutOfRangeException with named parameters

### ISSUE THREAD

**Issue by ermirbeqiraj** [dotnet/machinelearning#2535]
### System information

- **OS version/distro**: win10
- **.NET Version (eg., dotnet --info)**: 2.2.0

### Issue

- **What did you do?**
[taxi fare prediction](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/taxi-fare) sample, Evaluate method:
// this throws sys.argumentexception
var metrics = mlContext.Regression.Evaluate(dataView, label: "Label", score: "Score");
// this works:
var metrics = mlContext.Regression.Evaluate(predictions, "Label", "Score");
- **What happened?**
System.ArgumentOutOfRangeException: 'Label column 'Label' not found
Parameter name: schema'

### Source code / logs

![image](https://user-images.githubusercontent.com/7790756/52741979-fc112680-2fd6-11e9-80a0-c4ba4466be10.png)

**Comment by Ivanidzo4ka** [comment]
So you have your textLoader which loads data, and it has `FareAmount` column in it which you use for prediction.
```
var pipeline = mlContext.Transforms.CopyColumns(inputColumnName:"FareAmount", outputColumnName:"Label")
```
We start pipeline by creating column Label.
So your model contains that step, and during `var predictions = model.Transform(dataView);` we create Label column.
So it works fine if you apply it for `predictions`.
Your `dataView` doesn't have such column. This is why we throw that exception. You can inspect `dataView.Schema` object.

Evaluate doesn't do any magic and predictions, it just scan data for columns `Score` and `Label` and calculate metrics on them.

What do you expect form `* var metrics = mlContext.Regression.Evaluate(dataView, label: "Label", score: "Score"` code?

**Comment by ermirbeqiraj** [comment]
Just getting started with this area, now I see while writing this sample I've passed `dataView` instead of `predictions` argument, so `Evaluate` is working with data without/before transformation.
totally my mistake.
thankyou @Ivanidzo4ka !
