### ISSUE TITLE
Transforms.Resize has a vague name

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#2550]
The `ImageResizingEstimator` is in the catalog as `Resize`. By it's name, it isn't clear that this is intended for images. It could easily refer to a transform that resizes vectors. I suggest naming it to something more specific, such as `ResizeImages` (e.g. parallel language to `LoadImages`).

**Comment by rogancarr** [comment]
@sfilipi @zeahmed  What do you think?

**Comment by Ivanidzo4ka** [comment]
Considering what `Resize` is part of common transforms catalog and not image specific one, I think we should rename it. Otherwise it's too confusing.
