### ISSUE TITLE
Returns true for null array 

### ISSUE THREAD

**Issue by ameet20** [dotnet/machinelearning#2551]
Hi,

`Microsoft.ML.Internal.Utilities.Utils` has a couple of array checks that return `true` when a `null` array is passed in. Is this the expected behavior?

Here are the culprits:

```cs
public static bool IsSorted(IList<float> values);
public static bool IsSorted(int[] values);
```

```cs
public static bool IsIncreasing(int min, ReadOnlySpan<int> values, int lim);
```

Note that `IsIncreasing` is typically used for checking `int[]` arrays because `ReadOnlySpan` performs an implicit cast and null arrays are set to a 0-length `ReadOnlySpan`.

In a similar vein, `IsSorted` uses a null-safe `Utils.Size()` to check the input length of the array.

Does this make sense that we say that `null` arrays are sorted, and that they are decreasing?

**Comment by TomFinley** [comment]
Whether it's desirable or not is an open question, but it is definitely as designed.

We often in our internal code (which is the only thing using these utilities), if a sequence or array *would* be empty, we often say, "don't bother storing it, just keep it as `null`, we'll consider that an empty sequence." Hence why other utilities like `Utils.Size` and whatnot return 0 on `null` inputs.

If we extend this reasoning to `IsSorted` specifically, is an empty sequence sorted? Sure. Certainly no items are out of order... that this is true by there simply being no items to *be* out of order is not really relevant.

**Comment by TomFinley** [comment]
It could be though that when we updated our code to work from arrays to spans we didn
