### ISSUE TITLE
ColumnInfo as an API parameter

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#2554]
The use of `ColumnInfo` in the public API can be rather jarring. I'd like to clarify when we should use it in the catalog API, and if the parameter name could be made to be more consistent with the API, such as `ColumnOptions` or `Options`.

**Comment by Ivanidzo4ka** [comment]
Whatever we decide to call it, we also have `MeanVarColumn`, `LogMeanVarColumn`, `BinningColumn`, `SupervisedBinningColumn` and `MinMaxColumn` in `NormalizingEstimator` so they should be renamed to same thing. (Easy to miss if we sweep just ColumnInfo).

**Comment by artidoro** [comment]
I think the suggestion `ColumnOptions` could work. It relates to the naming convention that we use for trainers, and it also indicates that this is column-specific compared to the trainers.

I would like however to hear @TomFinley 's opinion on this.

**Comment by TomFinley** [comment]
I could definitely get behind `ColumnOptions`. It seems a far superior choice, so, let me say I agree wholeheartedly.
