### ISSUE TITLE
Example in README.md does not compile

### ISSUE THREAD

**Issue by duzenko** [dotnet/machinelearning#2565]
### System information

- Windows 10.0.17134
- 2.2.200-preview-009813

### Issue

- Copy-pasted code from readme.md to a new console project in Microsoft.ML.sln
- Build failed with error CS0117: 'TextLoader.Arguments' does not contain a definition for 'Column', etc
- Expected: The example code compiles successfully

### Source code / logs

```
using System;
using Microsoft.ML;
using Microsoft.ML.Data;

namespace ConsoleApp1 {
    class Program {
        static void Main( string[] args ) {
            Console.WriteLine( "Hello World!" );

            var mlContext = new MLContext();
            var reader = mlContext.Data.CreateTextLoader( new TextLoader.Arguments {
                Column = new[] {
                    new TextLoader.Column("SentimentText", DataKind.Text, 1),
                    new TextLoader.Column("Label", DataKind.Bool, 0),
                },
                HasHeader = true,
                Separator = ","
            } );
            var data = reader.Read( dataPath );
            var learningPipeline = mlContext.Transforms.Text.FeaturizeText( "Features", "SentimentText" )
                    .Append( mlContext.BinaryClassification.Trainers.FastTree() );
            var model = learningPipeline.Fit( data );

            Console.ReadLine();
        }
    }
}
```

**Comment by duzenko** [comment]
#2059

**Comment by jwood803** [comment]
Just tried this and, for v0.10, the only thing that didn't compile was the `Separator` property as it now needs to be `Separators`. I update the README if that sounds correct.

**Comment by duzenko** [comment]
Using the master branch source (i.e. not the nugets) I get more than that
```
1>Program.cs(12,17,12,23): error CS0117: 'TextLoader.Arguments' does not contain a definition for 'Column'
1>Program.cs(17,17,17,26): error CS0117: 'TextLoader.Arguments' does not contain a definition for 'Separator'
1>Program.cs(19,37,19,45): error CS0103: The name 'dataPath' does not exist in the current context
1>Program.cs(20,62,20,75): error CS1061: 'TransformsCatalog.TextTransforms' does not contain a definition for 'FeaturizeText' and no accessible extension method 'FeaturizeText' accepting a first argument of type 'TransformsCatalog.TextTransforms' could be found (are you missing a using directive or an assembly reference?)
1>Program.cs(21,70,21,78): error CS1061: 'BinaryClassificationCatalog.BinaryClassificationTrainers' does not contain a definition for 'FastTree' and no accessible extension method 'FastTree' accepting a first argument of type 'BinaryClassificationCatalog.BinaryClassificationTrainers' could be found (are you missing a using directive or an assembly reference?)
```

**Comment by ganik** [comment]
Hi @duzenko ,

I just tried and fixed issues with 'TextLoader.Arguments' and dataPath
Rest 2 of the issues should go away once you make your project dependent on 
Microsoft.ML.Transforms
Microsoft.ML.FastTree
Microsoft.ML.Data

I ll update the Readme.txt

Below is the code that compiles and runs:

using System;
using Microsoft.ML;
using Microsoft.ML.Data;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            // Path to your training tsv file. You can use machinelearning/test/data/wikipedia-detox-250-line-data.tsv
            var dataPath = "wikipedia-detox-250-line-data.tsv";

            var mlContext = new MLContext();
            var reader = mlContext.Data.CreateTextLoader(new TextLoader.Options
            {
                Columns = new[] {
                    new TextLoader.Column("SentimentText", DataKind.String, 1),
                    new TextLoader.Column("Label", DataKind.Boolean, 0),
                },
                HasHeader = true,
                Separators = new[] { ',' }
            });

            var data = reader.Load(dataPath);
            
            var learningPipeline = mlContext.Transforms.Text.FeaturizeText("Features", "SentimentText")
                    .Append(mlContext.BinaryClassification.Trainers.FastTree());
            var model = learningPipeline.Fit(data);

            Console.ReadLine();
        }
    }
}
