### ISSUE TITLE
TensorFlowUtils doesn't really fit with the 1.0 API

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#2572]
One of the scenarios we want to support in ML.NET 1.0 is the ability to examine the schema of a TensorFlow model (see example below [1]). To do this, we currently use helper methods in the `TensorFlowUtils` class [2].

Right now, this class and these methods are `public` and can be used as part of an ML.NET program, but that doesn't seem like the way we want to go in v1.0. What do you all think? Does it make sense to add these methods to mlContext and make them internal/BestFriend? If we add them to a catalog, where should they go?

[1] Example of why you would want to examine the schema before loading. Here, we want to get the layer names and their sizes before specifying them as outputs in our `IDataView`:
```cs
// Get the output size of a layer
var schema = TensorFlowUtils.GetModelSchema(mlContext, model_location);
var outputColumn = schema.GetColumnOrNull("Output");
if (outputColumn.HasValue)
    outputLength = ((VectorType)outputColumn.Value.Type).Dimensions[0];
```

[2] Helper Methods
```cs
public static Schema GetModelSchema(IHostEnvironment env, string modelPath);
public static IEnumerable<(string, string, ColumnType, string[])> GetModelNodes(IHostEnvironment env, string modelPath);
public static TensorFlowModelInfo LoadTensorFlowModel(IHostEnvironment env, string modelPath);
```
where `LoadTensorFlowModel` is already in the Transforms catalog.

Would `GetModelSchema` and `GetModelNodes` go in the `DataOperations` catalog?

And to pile on, `GetModelNodes` (which may not be necessary to expose) returns a list of returns, instead of an object, which we definitely can't have in V1.

Related to #2498

**Comment by Ivanidzo4ka** [comment]
Related to https://github.com/dotnet/machinelearning/issues/2552.
I think main discussion is going on in that issue.
