### ISSUE TITLE
Remove value tuples from TransformsCatalog methods

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#2581]
Many of the methods in TransformsCatalog create estimators using a params array of (string outputColumnName, string inputColumnName). As mentioned in #2501, we should change all these to not use value tuples.

**Comment by Ivanidzo4ka** [comment]
What would be your solution?
Do you plan to introduce `ColumnInfoBase` class (or some other name) and derive all other `ColumnInfo` from it?

**Comment by yaeldekel** [comment]
I would rather add a `SimpleColumnInfo` class (or some other name), so estimators that don't have a `ColumnInfo` class (for instance, `ColumnCopyingEstimator`) can use it. Does this make sense?
