### ISSUE TITLE
Mark EntryPoints classes and APIs as internal

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#2582]
We have a few classes in `Microsoft.ML.Core` that are public, but they shouldn't be.

https://github.com/dotnet/machinelearning/blob/13b33392dd3fbffc0922b2af72c8236b74c95fc0/src/Microsoft.ML.Core/EntryPoints/TransformModel.cs#L14

https://github.com/dotnet/machinelearning/blob/13b33392dd3fbffc0922b2af72c8236b74c95fc0/src/Microsoft.ML.Core/EntryPoints/PredictorModel.cs#L14

Basically, anything under the `Microsoft.ML.EntryPoints` namespace should be internal.

This is OK, because anything that uses EntryPoints already has `InternalsVisibleTo`.

@TomFinley @glebuk @ganik @shauheen

**Comment by ganik** [comment]
Would we allow third parties to develop against Entrypoints ? If yes then it cant be internal.

**Comment by eerhardt** [comment]
My opinion is that Entry Points are not part of ML.NET's `v1.0` public API. We can make them public later, when necessary. But for `v1.0`, the Estimator/Transformer APIs are the public APIs that third parties should develop against.

**Comment by eerhardt** [comment]
There are still public types in this namespace in the core package:

```C#
namespace Microsoft.ML.EntryPoints {
    public abstract class EvaluateInputBase {
        public IDataView Data;
        public string NameColumn;
        protected EvaluateInputBase();
    }
    public abstract class LearnerInputBase {
        public string FeatureColumn;
        protected LearnerInputBase();
    }
    public abstract class LearnerInputBaseWithGroupId : LearnerInputBaseWithWeight {
        public string GroupIdColumn;
        protected LearnerInputBaseWithGroupId();
    }
    public abstract class LearnerInputBaseWithLabel : LearnerInputBase {
        public string LabelColumn;
        protected LearnerInputBaseWithLabel();
    }
    public abstract class LearnerInputBaseWithWeight : LearnerInputBaseWithLabel {
        public string WeightColumn;
        protected LearnerInputBaseWithWeight();
    }
    public abstract class TransformInputBase {
        protected TransformInputBase();
    }
    public abstract class UnsupervisedLearnerInputBaseWithWeight : LearnerInputBase {
        public string WeightColumn;
        protected UnsupervisedLearnerInputBaseWithWeight();
    }
}
```

https://github.com/dotnet/machinelearning/blob/a16eb309820af6205d7a5e804ddbd5d995c879d2/src/Microsoft.ML.Data/EntryPoints/InputBase.cs#L15-L121

**Comment by Ivanidzo4ka** [comment]
We can't make them not public.
Don't you think this is more a issue of correct namespace?
We have separate issue regarding fixing namespaces, can we handle that in that issue rather than in this one?

**Comment by Ivanidzo4ka** [comment]
Actually, i think `EvaluateInputBase` can be make internal. Everything related to `LearnerInputBase` probably not.

**Comment by eerhardt** [comment]
My main concern with this issue is:

`Basically, anything under the `Microsoft.ML.EntryPoints` namespace should be internal.`

If there are types that cannot be made internal in this namespace, then they should not be in this namespace.
