### ISSUE TITLE
IChannelProvider should become internal

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#2585]
towards #1602

**Comment by TomFinley** [comment]
Unless you have a plan to make `IHostEnvironment` internal, I don't see how that is possible. Similar comment on your issue #2586.

**Comment by Ivanidzo4ka** [comment]
Do you want to keep `IHostEnviroment` public?

**Comment by TomFinley** [comment]
Not necessarily. Yet at one point it was viewed as inevitable. Do you view such a change as feasible pre-v1? If so, how?
