### ISSUE TITLE
Documentation: ML.NET Algo Cheat Sheet/Bot

### ISSUE THREAD

**Issue by endintiers** [dotnet/machinelearning#2591]
### System information

All

### Issue

Documentation Suggestion.

Create an algorithm cheat sheet along the lines of https://docs.microsoft.com/en-us/azure/machine-learning/studio/algorithm-cheat-sheet for ML.NET. Add options each time an AI library is added/changes.

A chart is nice/easy but a) too small for all the possibilities in all libraries?, b) hard to update.

How about an algo-picker bot? Some better/easier idea? I guess a chart with really really small writing might work for V1.0.

The point is: "If you build it, they won't necessarily come - unless you make it stoopidly easy for them to get there".

### Source code / logs

N/A

**Comment by artidoro** [comment]
I am adding @CESARDELATORRE @JRAlexander to the conversation as they are following the documentation project more closely.

**Comment by JRAlexander** [comment]
Thanks, we have a cheatsheet scheduled on the docs backlog.

**Comment by endintiers** [comment]
I really like the ML studio doc at https://docs.microsoft.com/en-us/azure/machine-learning/studio/algorithm-choice and pretty much all of that applies. Even when you go deeper the info about the Microsoft algorithms is equally valid whether they are called from ML Studio or ML.NET. Maybe that could be generalised/shared somehow? Just adding some words to point out it is equally applicable in ML.NET?

ML.NET though allows the choice of algorithms from other libraries. The table at https://github.com/dotnet/machinelearning-samples is also a great idea, especially because the audience for ML.NET is much more 'code first, ask questions later'. Programmers learn by by reading code and writing code. 

So maybe the shortcut to a cheatsheet for ML.NET is: 
- Concentrate on creating and maintaining sample code for the most useful algorithms in all the libraries that ML.NET interfaces to. 
- Build a cheatsheet (online/living?) that indexes and organises the samples. I really like the 'Start' and follow the arrows idea. The first time people come they will have no idea even what type of algorithm they should use. Classifying samples as 'clustering', 'regression' etc. is fine. For the newbies though we need to explain even which type of algorithm they should be looking to use for their specific problem.

**Comment by Oceania2018** [comment]
You might get what you want from BotSharp https://github.com/SciSharp/BotSharp

**Comment by shmoradims** [comment]
Related to #2943.

**Comment by natke** [comment]
This is what we have so far: https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-choose-an-ml-net-algorithm

**Comment by shmoradims** [comment]
> This is what we have so far: https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-choose-an-ml-net-algorithm

@endintiers , the link above contains the information you need. If you have any additional feedback or question, please comment on that page, or create a new issue, or re-open this one. Thanks!
