### ISSUE TITLE
Missing DLL tensorflow.dll when targeting .NET 472

### ISSUE THREAD

**Issue by LucasFievet** [dotnet/machinelearning#2596]
### System information

- **OS version/distro**: Windows 10 Pro
- **.NET Version (eg., dotnet --info)**: .NET 472

### Issue

- **What did you do?** Added Microsoft.ML.TensorFlow nuget package to .NET 472 project
- **What happened?** Nuget package was added but the tensorflow.dll was missing in the bin folder and tests would fail with the missing dll exception. Unit tests are passing when targeting .netcoreapp 2.0.
- **What did you expect?** The tensorflow.dll to be found when targeting .net 472

### Source code / logs

`<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Include="model\saved_model.pb">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Project.Core\Project.Core.fsproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.ML.TensorFlow" Version="0.10.0" />
    </ItemGroup>

</Project>
`

Comment: dll is still missing even when explicitly adding the nuget package Microsft.ML.TensorFlow.Redist.

**Comment by Ivanidzo4ka** [comment]
So if I go to Visial Studio and create .Net Framework project with 4.7.2 and import TensorFlow it works fine. 
If I go to Visual studio and create .Net Standard project and import TensorFlow it also works fine.
That problem appears only if I create .Net Standard project and then go and change target framework to net472. In that case tensorflow (and probably any other native dll) couldn't be found.


+ @eerhardt do you have any thoughts?

**Comment by LucasFievet** [comment]
@Ivanidzo4ka : exactly, creating a netstandard project and then changing to net472 target fails. Sorry, should have been more precise.

**Comment by eerhardt** [comment]
Add

```
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
```

to a `PropertyGroup` in your .csproj.

Using native assemblies (like TensorFlow, or the other architecture-specific assemblies we have in ML.NET) doesn't work very well out of the box with .NET Framework. By default, .NET Framework tries to build for `AnyCPU`, which means the build system doesn't know which native assemblies to copy to the output folder - x86 or x64? You need to tell it which ones to use by using the `RuntimeIdentifier` property. And since TensorFlow support is only on `x64` processes, use `win-x64`.

**Comment by Ivanidzo4ka** [comment]
@LucasFievet  can you confirm what adding win-x64 solves your issue?
>64 bit is supported on all platforms. 32 bit is supported on Windows, except for TensorFlow, LightGBM, and ONNX related functionality.

We specify what tensorflow is 64bits only, so I would like to close this issue

**Comment by LucasFievet** [comment]
@Ivanidzo4ka yes, adding the x64 identifier solved the issue. Thanks a lot!
