### ISSUE TITLE
How to use the sample project “Microsoft.ML.samples” code for predicting from sql server db as input?

### ISSUE THREAD

**Issue by Hiren161** [dotnet/machinelearning#2598]
I have tried to understand Microsoft.ML.samples code. 
So how can I use this sample for predicting the output from giving input from one of my SQL server databases?

### Ex: 
    var enumerableOfData = SamplesUtils.DatasetUtils.GetSampleTemperatureData(10);
    var data = mlContext.Data.ReadFromEnumerable(enumerableOfData);

- **we want to use MSSQL for getting record to fill “Data”. So how can i use MSSQL?**
- **which method or which assembly do I need to refer to fulfill my requirement?**

**Comment by jwood803** [comment]
Hey @Hiren161, not sure if this helps out any but I have [sample code](https://github.com/jwood803/MLNetExamples/blob/master/MLNetExamples/DatabaseData/Program.cs) in which I load data to a database, read it, and use that data to build an ML.NET model.

**Comment by glebuk** [comment]
@Hiren161, please take a look at an EShop Example for more [extensive sample](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/Regression-SalesForecast) on using ML.NET with SQL server

**Comment by glebuk** [comment]
Closing, if you have more questions, feel free to reopen
