### ISSUE TITLE
Internalization of Microsoft.ML.Data Dataview folder

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#2606]
https://github.com/dotnet/machinelearning/blob/b881fdc2eab55e184eb0856d4c10c732a58e0887/src/Microsoft.ML.Data/DataView/AppendRowsDataView.cs#L30

https://github.com/dotnet/machinelearning/blob/b881fdc2eab55e184eb0856d4c10c732a58e0887/src/Microsoft.ML.Data/DataView/CompositeRowToRowMapper.cs#L14

https://github.com/dotnet/machinelearning/blob/b881fdc2eab55e184eb0856d4c10c732a58e0887/src/Microsoft.ML.Data/DataView/DataViewConstructionUtils.cs#L727

https://github.com/dotnet/machinelearning/blob/b881fdc2eab55e184eb0856d4c10c732a58e0887/src/Microsoft.ML.Data/DataView/DataViewConstructionUtils.cs#L755

https://github.com/dotnet/machinelearning/blob/b881fdc2eab55e184eb0856d4c10c732a58e0887/src/Microsoft.ML.Data/DataView/EmptyDataView.cs#L15

https://github.com/dotnet/machinelearning/blob/b881fdc2eab55e184eb0856d4c10c732a58e0887/src/Microsoft.ML.Data/DataView/OpaqueDataView.cs#L15

https://github.com/dotnet/machinelearning/blob/b881fdc2eab55e184eb0856d4c10c732a58e0887/src/Microsoft.ML.Data/DataView/ZipDataView.cs#L17

need to be moved to somewhere else (We probably already have schema utils):
https://github.com/dotnet/machinelearning/blob/b881fdc2eab55e184eb0856d4c10c732a58e0887/src/Microsoft.ML.Data/DataView/SimpleRow.cs#L73

I don't see any usages, need to check is it still relevant:
https://github.com/dotnet/machinelearning/blob/b881fdc2eab55e184eb0856d4c10c732a58e0887/src/Microsoft.ML.Data/DataView/LambdaFilter.cs#L19 

not sure about this:

https://github.com/dotnet/machinelearning/blob/b881fdc2eab55e184eb0856d4c10c732a58e0887/src/Microsoft.ML.Data/DataView/ArrayDataViewBuilder.cs#L17

https://github.com/dotnet/machinelearning/blob/b881fdc2eab55e184eb0856d4c10c732a58e0887/src/Microsoft.ML.Data/DataView/TypedCursor.cs#L35

https://github.com/dotnet/machinelearning/blob/b881fdc2eab55e184eb0856d4c10c732a58e0887/src/Microsoft.ML.Data/DataView/TypedCursor.cs#L45

**Comment by Ivanidzo4ka** [comment]
@codemzs you have 16 issues assign on you (I know bunch of them are irrelevant right now) 6 of them already related to internalization.
Can you focus your time on closing you PRs first (pinging people takes time, replying on comments in PR also takes time) rather than assign all internalization tasks to yourself?
Unless of course you already working on this, and you plan to publish PR today/tomorrow.

**Comment by codemzs** [comment]
@Ivanidzo4ka I have closed most of my internalization PRs except for the two on which I have pinged you a few times :) I will have the PR out for this issue and other Data folder issue shortly.
