### ISSUE TITLE
Scrubbing learners (Meta issue)

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#2613]
We need to clean our API for learners.
This includes following things:

1. No protected fields/members/method in public classes. Only private protected.

2. Learner class is sealed.

3. The trainer name types should follow the names used in the contexts (see https://github.com/dotnet/machinelearning/issues/2172)

4. ModelPameters for this Learner is also clean. (sealed, public documentation, no public constructor)

5. Options cleaning:
- They should be named Options, and all their base classes (except `LearnerInputBase*`)
- Option should have meaning and proper way it initialize it self. We shouldn't accept int if in reality we use enum (https://github.com/dotnet/machinelearning/issues/2521) or accept array of ints as a string separated by comma `public string CustomGains = "0,3,7,15,31";`
- No short names.
- Standard names like:
`/// <param   name="labelColumnName">The name of the label   column.</param>`
`/// <param   name="featureColumnName">The name of the feature   column.</param>`
`NumberOfIterations`, `NumberOfThreads`, `LearningRate`,`L2Regularization`, `L1Regularization`
no (`MaxIterations`,`NumIterations`, `NumThreads`, `L2Weight`, `L1Weight`)

6. If we communicate with user (exceptions, channel messages), don't use DataKind values. No R4, U4, and so on, it should be float, uint, etc.

ignore for now:

1. Everything public has proper documentation.

7. We have samples of how use base call to trainer (no options) and call with options.

8. We have baseline tests for learner.

https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/general-naming-conventions#using-abbreviations-and-acronyms

`

**Comment by rogancarr** [comment]
9. There should be consistency within `Tasks` (e.g. `BinaryClassification`, `Regression`) on how labels are specified (e.g. `R4`, `bool`, `KeyType`).

For instance, many learners accept R4 values and helpfully convert them to `bool` or `KeyType`, while some learners only accept `KeyType`. (see #2628 for a multiclass example). This inconsistency is confusing from a user perspective because you can't hot-swap Trainers in a pipeline.

**Comment by wschin** [comment]
We also have `rowGroupColumnName` to replace `groupIdColumn`.

**Comment by rogancarr** [comment]
The classnames themselves come in many different styles and they are surfaced through options:

For example, `SDCA` and `FastTree` have very different class names for binary classification:
```cs
var sdca = mlContext.BinaryClassification.Trainers.StochasticDualCoordinateAscent(
    new SdcaBinaryTrainer.Options { NumberOfThreads = 1 });

var fastTree = mlContext.BinaryClassification.Trainers.FastTree(
    new FastTreeBinaryClassificationTrainer.Options { NumberOfThreads = 1 });
```

These class names should have a standard grammar.
