### ISSUE TITLE
PipelineInference\RocketEngine bug fix for taking top k items.

### ISSUE THREAD

**Issue by george-microsoft** [dotnet/machinelearning#262]
There is a bug in the RocketEngine GetTopLearners() method which potentially allows for duplicated pipelines to show up in the results. Bug found and diagnosed by @yaeldekel. Fix should be easy.

More detail: The logic in GetTopLearners() looped through two arrays, and compared the items in the second array to the items in the first, replacing them if some criterion was met (had higher weights). The way it was written could allow for a learner to replace more than one item in the first list, leading to two or more copies of the learner in our Top K array (which is a bug).

**Comment by TomFinley** [comment]
I wonder if the nature of this bug could be added to the issue so I don't have to ask @yaeldekel .

**Comment by george-microsoft** [comment]
Bug description updated with a bit more detail.
