### ISSUE TITLE
Cleaning up metric classes

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#2624]
We need to clean our metrics classes:

All classes are sealed.
All constructors are internal.
Everything has proper documentation. Including class itself.
No short names (Dbi is awful name, DCG not great as well, L1, L2, Rms, etc)

List of metrics:
`AnomalyDetectionMetrics`
`BinaryClassificationMetrics`
`CalibratedBinaryClassificationMetrics`
`ClusteringMetrics`
`MultiClassClassifierMetrics`
`RankerMetrics`
`RegressionMetrics`

**Comment by rogancarr** [comment]
@Ivanidzo4ka I just filed a few related issues for ranking:

#2637
#2634
#2633
