### ISSUE TITLE
Mismatch in Label expectations for Multiclass Learners

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#2628]
When training a multiclass classifier, the label must be converted to `KeyType`. Some learners, such as `SDCA`, do the conversion from `R4` automatically, while some, like `LogisticRegression` do not. This behavior   is confusing from an end-user perspective, as one cannot simply interchange learners without modifying the input pipeline.

I suggest adding auto-label-conversion for all multiclass learners in ML.NET.

**Comment by Ivanidzo4ka** [comment]
I can be wrong, but it looks like our decision making regarding auto-working-magically workflow for API is quite opposite. We no longer have auto cache, no auto normalization.
Maybe we should remove auto conversion to R4 as well from SDCA.

**Comment by Ivanidzo4ka** [comment]
I have list of things I want to do to all learners https://github.com/dotnet/machinelearning/issues/2613 if you during your discovery find something which doesn't fit into your list, can you extend it?

**Comment by TomFinley** [comment]
SDCA in fact does not convert from float automatically. It was instead written at a time years ago when the only type of label supported was float. Now that we have a more specific type we should shift to using it. It does not convert at all, it just supports both types.

If you prefer it to be consistent, it should be consistent in the other direction, that is, SDCA should stop doing its internal magic.

**Comment by rogancarr** [comment]
I like having consistency. Let's consider this a bug on SDCA for supporting `floats` instead of only `KeyTypes` as multiclass labels.

**Comment by Ivanidzo4ka** [comment]
Just to make it clear, are we fixing this now or post v1?

**Comment by rogancarr** [comment]
We should fix now, as it breaks a key training scenario that any trainer for a task can substituted in a training pipeline.

**Comment by TomFinley** [comment]
Correct, we must fix now.
