### ISSUE TITLE
AnomalyDetection Evaluator returns NaNs

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#2644]
The `Evaluator` for `AnomalyDetection` returns NaNs for all metrics under some conditions.

The individual metrics shouldn't be returned as a NaN. If something is wrong with the input data, the evaluator should throw an error instead.

Reproduction: Use the MNIST One Class dataset from `tests/data/`, train with default RandomizedPCA parameters, then evaluate the predictions on the training dataset. Observe that the metrics come back as NaN.
```cs
var data = mlContext.Data.ReadFromTextFile<MnistOneClass>(GetDataPath(TestDatasets.mnistOneClass.trainFilename),
    hasHeader: TestDatasets.mnistOneClass.fileHasHeader,
    separatorChar: TestDatasets.mnistOneClass.fileSeparator);

// Create a training pipeline.
var pipeline = mlContext.AnomalyDetection.Trainers.RandomizedPca();

// Train the model.
var model = pipeline.Fit(data);

// Evaulate the model.
var scoredData = model.Transform(data);
var preview = scoredData.Preview();
var metrics = mlContext.AnomalyDetection.Evaluate(scoredData);
```

**Comment by rogancarr** [comment]
This is most likely a divide-by-zero somewhere.

**Comment by abgoswam** [comment]
Interesting find.  The internal repo also shows this behavior when the train dataset (`mnistOneClass.trainFilename`) is used  as the test dataset. So it seems this bug has been around for a while.
