### ISSUE TITLE
samples look to be repetitive

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/machinelearning#2653]
Hi,

I think that a Copy & Past issue duplicated the samples

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7238dac-834a-09ec-15e2-aa35ced93ffd
* Version Independent ID: f7a23c72-3335-a0dc-2858-dbb88defa132
* Content: [ConversionsExtensionsCatalog.ValueMap Method (Microsoft.ML)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.conversionsextensionscatalog.valuemap?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML/ConversionsExtensionsCatalog.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML/ConversionsExtensionsCatalog.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by singlis** [comment]
Hi @PeterPann23, 

So the samples for ValueMapping show 4 different use cases. We can trim down if that is causing confusion, what are you throughts?

Here are the cases: 
1) Mapping a key that is a string to a value that is a string
2) Mapping a key that is a string to a value that is a KeyType (which look identical to Sample 1, but the difference is that we are passing treatAsKeyTypes as true then applying a MapKeyToValue transformer to demonstrate we can convert back to the original  value). 
3) Mapping a key that is a float to a value that is a string (this maybe redundant)
4) Mapping a key that is a string to a value that is an array of ints

**Comment by PeterPann23** [comment]
Hi,

Yes, cool I agree the 3 is «duplicate» also this will let users map it to a true enum, love it

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Scott Inglis <notifications@github.com>
Gesendet: Tuesday, April 2, 2019 1:13:27 AM
An: dotnet/machinelearning
Cc: PeterPann23; Mention
Betreff: Re: [dotnet/machinelearning] samples look to be repetitive (#2653)


Hi @PeterPann23<https://github.com/PeterPann23>,

So the samples for ValueMapping show 4 different use cases. We can trim down if that is causing confusion, what are you throughts?

Here are the cases:

  1.  Mapping a key that is a string to a value that is a string
  2.  Mapping a key that is a string to a value that is a KeyType (which look identical to Sample 1, but the difference is that we are passing treatAsKeyTypes as true then applying a MapKeyToValue transformer to demonstrate we can convert back to the original value).
  3.  Mapping a key that is a float to a value that is a string (this maybe redundant)
  4.  Mapping a key that is a string to a value that is an array of ints
