### ISSUE TITLE
Predicting an enum value is getting harder then expected

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/machinelearning#2654]
### System information

- **Windows 10 64 bit**:
- **ml.net 0.10.0**: 
[Model.zip](https://github.com/dotnet/machinelearning/files/2884674/Model.zip)

### Issue

- **What did you do?**
Trained a model from a text file that contains a integer for the values of an enum. The model contains a property named Label with a data type of uint 

- **What happened?**
Got an error message generating prediction engine from model after it trained, the error:
Could not apply a map over type 'U4' to column 'Label' since it has type 'Key<U4, 0-37>'

   at Microsoft.ML.Transforms.Conversions.ValueToKeyMappingTransformer.Bind(IHostEnvironment env, Schema schema, TermMap unbound, ColInfo[] infos, Boolean[] textMetadata, Int32 iinfo)
   at Microsoft.ML.Transforms.Conversions.ValueToKeyMappingTransformer.Mapper..ctor(ValueToKeyMappingTransformer parent, Schema inputSchema)
   at Microsoft.ML.Transforms.Conversions.ValueToKeyMappingTransformer.MakeRowMapper(Schema schema)
   at Microsoft.ML.Data.RowToRowTransformerBase.GetRowToRowMapper(Schema inputSchema)
   at Microsoft.ML.Data.TransformerChain`1.GetRowToRowMapper(Schema inputSchema)
   at Microsoft.ML.Data.TransformerChain`1.GetRowToRowMapper(Schema inputSchema)
   at Microsoft.ML.Data.TransformerChain`1.GetRowToRowMapper(Schema inputSchema)
   at Microsoft.ML.PredictionEngineBase`2..ctor(IHostEnvironment env, ITransformer transformer, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition)
   at Microsoft.ML.PredictionEngineExtensions.CreatePredictionEngine[TSrc,TDst](ITransformer transformer, IHostEnvironment env, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition)
- **What did you expect?**
I would expect this to work. 

### Source code / logs
```
var dataProcessPipeline = mlContext.Transforms.Conversion.MapValueToKey(outputColumnName: DefaultColumnNames.Label, inputColumnName:nameof(MSBar2.Label))                                            
                            .Append(mlContext.Transforms.Concatenate(DefaultColumnNames.Features, MSBar2.GetColumnNames(DataKind.R4)))
                            ;
var trainer = mlContext.MulticlassClassification.Trainers.StochasticDualCoordinateAscent(DefaultColumnNames.Label,DefaultColumnNames.Features);
var trainingPipeline = dataProcessPipeline.Append(trainer)
                                          .Append(mlContext.Transforms.Conversion.MapKeyToValue(DefaultColumnNames.PredictedLabel));
var model = trainingPipeline.Fit(trainingDataView);
var engine= model.CreatePredictionEngine<MSBar2, TrendPrediction>(mlContext);
```
The class TrendPrediction looks like this:
```
public class TrendPrediction
{
        /// <summary>
        /// Initializes a new instance of the <see cref="TrendPrediction"/> class.
        /// </summary>
        public TrendPrediction()
        {
        }

        /// <summary>
        /// The predicted labels
        /// </summary>
        [ColumnName("PredictedLabel")]
        public uint PredictedLabels;

        /// <summary>
        /// The scores
        /// </summary>
        [ColumnName("Score")]
        public float[] Scores;
}
```
I have decorated my Label property like this:
```
[ColumnName("Label"), LoadColumn(0) , Column("0", "Label"),KeyType(Count =38)]
public uint Label;
```

[Model.zip](https://github.com/dotnet/machinelearning/files/2884678/Model.zip)

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by PeterPann23** [comment]
Altering the MSBar2 class **AFTER** training and removing the key annotation seems to cause the error to go away. Training with MSBar2 and train evaluation with a new class call it  "MSBarPostTrain" just to remove the annotation is not nice.

**Comment by Ivanidzo4ka** [comment]
We have `KeyType` in our `DataView` system.  So we can have columns of such type.
You have two ways how you can create them:
- Directly via attributes. 

- By applying transforms to other columns, like `MapValueToKey` or `ValueMap`.

In your example you have trying to do both.
You define column Label of key type and then run pipeline on top of it which applies `MapValueToKey`. In our exception we just trying to tell you: "You already have key type, why should we cast it to key again?"

I expect during your training you read your data like this:
```
 var reader = ml.Data.CreateTextLoader(
                columns: new[]
                    {
                        new TextLoader.Column("Label", DataKind.I4, 0),
                    },
                hasHeader: true
            );
```

If not, and you actually specified  `new TextLoader.Column("Label", DataKind.U4, new TextLoader.Range[1]{ new  TextLoader.Range(0) },new KeyCount(38)` please let me know, that sound like a bug.

**Comment by PeterPann23** [comment]
okey, removed the annotation.
