### ISSUE TITLE
Enhance CustomMapping documentation

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#2657]
See discussion https://github.com/dotnet/machinelearning/pull/2569#discussion_r257425931

> this is definitely something we'll want to document very carefully. It is a bit odd, this pattern of mutable input as a return value. (I of course know exactly why we do it, but a user will not.)

We should ensure we explain (in the cookbook, docs.microsoft.com, or otherwise) how this pattern works, and give the reasons why we do it like this.

/cc @TomFinley

**Comment by eerhardt** [comment]
Also, we should add some `<see` tags to and from `CustomMappingEstimator`.

See https://github.com/dotnet/machinelearning/pull/2569#discussion_r257426593 for the suggestion.

**Comment by artidoro** [comment]
We added samples for the custom mapping estimator and improved the documentation.
If you feel that this should be improved further please reopen the issue and specify what we should add.
