### ISSUE TITLE
What to do with IFourierDistributionSampler and friends

### ISSUE THREAD

**Issue by TomFinley** [dotnet/machinelearning#2659]
This interface is related to random Fourier features projection. We may want this functionality as part of our public surface, but the specific API right now is still very command-line and entry-points centric. This should change.

Somewhat similar in spirit to the problem of loss functions as discussed in #1973, and has many of the same problems, and should probably have a similar resolution to whatever we choose to do with loss functions.

**Comment by TomFinley** [comment]
One area where it may differ from loss function si that due to their multi-inheritance and multi-appllication nature it kind of makes sense for loss functions to be interfaces, whereas I don't think these samplers should be interfaces; at least, nothing about this strikes me as being "interface-y."

**Comment by eerhardt** [comment]
See also #699.
