### ISSUE TITLE
Rename GroupId column to RowGroup 

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#2660]
https://github.com/dotnet/machinelearning/blob/4a71e501f09846974e550f817f3f8f1243054c1b/src/Microsoft.ML.LightGBM/LightGbmCatalog.cs#L127

Conversation can be found here:
https://github.com/dotnet/machinelearning/issues/2536

**Comment by abgoswam** [comment]
For the sake of consistency (as mentioned in issue #2177 )  should we call it 

- rowGroup**ColumnName**

**Comment by abgoswam** [comment]
Fixed by PR #2665
