### ISSUE TITLE
Enable TextFeaturization Test

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#2668]
Test was skipped in v0.10 but does not work in v0.10. 

It passes on v0.11 preview. 

Test should be enabled. If it runs longer than expected, consider reducing data/sample size but test should not be skipped.

**Comment by Ivanidzo4ka** [comment]
https://github.com/dotnet/machinelearning/blob/master/test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs
We talking about this one.
On my machine in debug version it runs 7sec which sound acceptable for me.
