### ISSUE TITLE
How to debug ML.NET internals.

### ISSUE THREAD

**Issue by rauhs** [dotnet/machinelearning#2677]
Hi,

this might be a more general question but I couldn't find anything in the developer-guide.

In the past months I've continously seen issues (or at least unintuitive exceptions thrown deep inside ML.NET) that I couldn't figure out.

Coming from a Java background we usually get the Java sources in our Jar and can just step into any code without any effort.
Though, I'm having a really tough time to debug any errors.

1. How can I step into the ML.NET code? I'm using the myget daily builds.

Currently I'm seeing an IndexOutOfRangeException somewhere deep inside the `KeyToVectorMappingTransformer`.

2. Are there plans to offer a synchronous version of `Fit/Transform()` that avoids the whole threading problems?

Any guidance on this would be greatly appreciated.

**Comment by glebuk** [comment]
Excellent question, @rauhs !
As a matter of fact, it is quite easy to do so. All ML.NET NuGet packages have symbols published, and source code is on this GitHub repo.
To step into ML.NET packages, you need to do the following
1. Enable [NuGet.Org symbol download](https://blog.nuget.org/20181116/Improved-debugging-experience-with-the-NuGet-org-symbol-server-and-snupkg.html for details)
2. Disable JustMyCode debugging (Visual Studio -> Options -> Debugging -> Just My Code [ ]  (disable))
Following those steps, I was able to step into ML.NET code in our [samples ](https://GitHub.com/dotnet/machinelearning-samples) project
