### ISSUE TITLE
Make trainer input arguments' names consistent

### ISSUE THREAD

**Issue by shmoradims** [dotnet/machinelearning#2680]
Just by looking at [StandardLearnersCatalog.cs](https://github.com/dotnet/machinelearning/blob/1f90f50f813ecd152e46e92deb4a7827c7f24e31/src/Microsoft.ML.StandardLearners/StandardLearnersCatalog.cs) I found a lot of inconsistent naming for the binary classification trainer arguments. 

Below are the many naming variations that need to be conflated (both in extension method signatures and the Options properties):
* labelColumnName, labelColumn
* featureColumnName, featureColumn
* weightColumnName, weights
* initLearningRate, learningRate
* l2Weight, l2Const, l2RegularizerWeight
* l1Threshold, l1Weight
* numIterations, maxIterations
* lossFunction, loss
* numIterations, NumberOfIterations

I haven't checked yet, but it's probably the case for other trainers. There's probably more of these inconsistencies.

**Comment by Ivanidzo4ka** [comment]
https://github.com/dotnet/machinelearning/issues/2613 feel free to contribute to that issue.

**Comment by singlis** [comment]
@shmoradims, @Ivanidzo4ka  can this be closed since its tracked under #2613?

**Comment by wschin** [comment]
Related to #2873 about weight column's name in trainers.
