### ISSUE TITLE
ImagePixelExtractingEstimator do not applied scale and offset for image

### ISSUE THREAD

**Issue by knpoklonski** [dotnet/machinelearning#2683]
### System information

- **Windows 10**:
- **.NET Core 2.1 ML.NET v0.10.0**: 

### Issue

- **Try to use ImagePixelExtractingEstimator with scale and offset**
- **sclae and offset do not applied for pixels data**
- **sclale and offset should successfully applied**

### Source code / logs
This code below doesn't work correctly
```
var pipeline = new ImageLoadingEstimator(_mlContext, string.Empty, ("ImageData", "ImagePath"))
                    .Append(new ImageResizingEstimator(_mlContext, "ImageResized", ImageWidth, ImageHeight, "ImageData"))
                    .Append(new ImagePixelExtractingEstimator(_mlContext, "input", "ImageResized", colors: ImagePixelExtractorTransformer.ColorBits.Rgb, interleave:true, asFloat: true, offset: 128f, scale: 1/255f))
```

Sample below works correctly, but here is shouldn't be difference, right?
```
var pipeline = new ImageLoadingEstimator(_mlContext, string.Empty, ("ImageData", "ImagePath"))
                    .Append(_mlContext.Transforms.Resize("ImageResized", imageWidth: ImageWidth, imageHeight: ImageHeight, inputColumnName: "ImageData"))
                    .Append(_mlContext.Transforms.ExtractPixels(new ColumnInfo("input", "ImageResized", colors: ColorBits.Rgb, interleave:true, asFloat: true, offset: 128f, scale: 1 /255f)))
```
[Commit with changes in sample app](https://github.com/knpoklonski/image-recognition-onnx-sample/commit/79930119725e6981cab3f948a8e442cac0f7e9b6)

**Comment by glebuk** [comment]
@knpoklonski,
The example below is correct.  We have already removed  the public constructors for Estimators from the public interface in the master after .10 was released.
