### ISSUE TITLE
Need to remove FastTree/Utils/MD5Hasher class

### ISSUE THREAD

**Issue by glebuk** [dotnet/machinelearning#2696]
Currently FastTree uses a 16byte MD5 hash to ensure uniqueness of content. 

### There are several issues with this:
- The MD5 hash is a (weak) cryptographic hash, resulting in additional work for the release process with regards to export controls.
- MD5 hash is quite slow and memory intensive

### Suggested Fix:
- Rename MD5Hash to ContentHash or similar. 
- Same goes to MD5Hasher
- Update all Hash(,,,) methods to not use MD5CryptoServiceProvider but murmur hash or equivalent instead.
- Ensure no reference to System.Security.Cryptography namespace exists in the codebase afterwards.
- Alternatively, we can extend the murmurhash class to return

**Comment by codemzs** [comment]
@glebuk It seems MD5Hasher was used to detected duplicate features and @TomFinley feels this functionality was not useful in practice, he recommends we delete MD5Hasher altogether without replacing it with any other hashing algorithm.
