### ISSUE TITLE
Enumerable over IDataView cannot be Zip'ped

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#2719]
When an enumerator over an `IDataView` is `zip`ped with Linq, the following error is thrown:

"**System.InvalidOperationException**: Collection was modified; enumeration operation may not execute."

Here is an example:
```cs
var myEnumerable = mlContext.CreateEnumerable<MyClass>(data, true);
foreach (var rowAndNumber in myEnumerable.Zip(numbers, (row, number) => new { row, number }))
{
    Console.WriteLine($"{rowAndNumber.row.Column}\t{rowAndNumber.number}");
}
```

I marked this as a bug, but is this expected behavior?

**Comment by Ivanidzo4ka** [comment]
Can you post bigger sample?
I'm struggle to reproduce.

**Comment by rogancarr** [comment]
@Ivanidzo4ka Use the sample from #2723 in the Functional.Tests/ project.

**Comment by Ivanidzo4ka** [comment]
I've tried.
It doesn't have `numbers` and `MyClass` is unclear.

**Comment by rogancarr** [comment]
`numbers` => `randomNumbers`
`MyClass` => `IrisWithGroup`

**Comment by Ivanidzo4ka** [comment]
Ok, so you do following:
```
    Action<Iris, IrisWithGroup> generateGroupId = (input, output) =>
            {
                var randomNumber = rng.Next(0, 30);
                randomNumbers.Add(randomNumber);
```
You have `transformedData` dataview and it's lazy. It wouldn't touch any data processing unless you start consume your dataview.
Which you attempt to do in zip.
Zip looks like this:
```
  using (IEnumerator<TFirst> e1 = first.GetEnumerator())
            using (IEnumerator<TSecond> e2 = second.GetEnumerator())
            {
                while (e1.MoveNext() && e2.MoveNext())
                {
                    yield return resultSelector(e1.Current, e2.Current);
                }
            }
```
second iterator is your `randomNumbers`, and they are empty before you start iterate over dataview, so Ienumerable for them should be empty.
You call MoveNext() for dataview and it populated `randomNumbers` collection, so this is why you get:
`Collection was modified; enumeration operation may not execute."`

Does my explanation make sense?

**Comment by rogancarr** [comment]
Oh, gotcha :)
