### ISSUE TITLE
Can speech recognition be done in ML.NET?

### ISSUE THREAD

**Issue by Neeraj-Kashyap-Harman** [dotnet/machinelearning#2732]
### System information

- **OS version/distro**:  Windows
- **.NET Version (eg., dotnet --info)**:  .NET Framework 4.6

### Issue

I am new to Machine Learning. I came across ML.NET (Machine Learning framework by Microsoft). Can we use this framework for speech recognition? What all things you should know if you want to do a speech recognition in ML.NET?

**Comment by 840900649** [comment]
Excuse me, how to do face recognition and character recognition, speech recognition, voice to text, text to speech, etc.

**Comment by Lynx1820** [comment]
Hi Neeraj,

At the moment, ML.NET doesn't support speech recognition. You can however, create a TensorFlow model and consume it with ML.NET. You can find more info here: https://devblogs.microsoft.com/cesardelatorre/run-with-ml-net-c-code-a-tensorflow-model-exported-from-azure-cognitive-services-custom-vision/

**Comment by yaeldekel** [comment]
@Neeraj-Kashyap-Harman , I am closing the issue given @Lynx1820 's answer. If you have additional questions please re-open or create a new issue.
