### ISSUE TITLE
Rms is Too High

### ISSUE THREAD

**Issue by Husseinbeygi** [dotnet/machinelearning#2739]
Hi 
I use the Taxi Fair Code Sample and i changed it to predict  the LAST Price of a Stock in Market 
nothing too big.....
Rms is on 40 and Predict is wrong

My question  is what can i do to reduce the Rms?
and why Rms is too high?

**Comment by najeeb-kazmi** [comment]
@Husseinbeygi RMS is dependent on the model and the problem you are applying it to. The model in the sample gives good predictions on the taxi fare prediction, but the same training pipeline will not give you the same RMS on a different problem entirely.

Also, the RMS calculation is affected by the scale of the target label. For example, the taxi fare amounts are in the range of ~0-20. Suppose you have three fares 5, 10, and 20, and the predictions are 6, 12, and 16. (20% off from actual value). The RMS would be `sqrt{(1 + 2^2 + 4^2)/3} = 2.65`. If the stock prices are 50, 100, 200 and the predictions are 60, 120, 160 (again 20% off from actual value), the rms would be `sqrt{(10^2 + 20^2 + 40^2)/3} = 26.5`.

To improve your model, you can try different featurization techniques for your data, appropriate to predicting stock prices, try different trainers and their hyperparameters, evaluating each model using [cross validation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.regressioncatalog.crossvalidate?view=ml-dotnet#Microsoft_ML_RegressionCatalog_CrossValidate_Microsoft_ML_IDataView_Microsoft_ML_IEstimator_Microsoft_ML_ITransformer__System_Int32_System_String_System_String_System_Nullable_System_Int32__) [[example](https://github.com/dotnet/machinelearning/blob/master/docs/code/MlNetCookBook.md#how-do-i-train-using-cross-validation)].

You can also try [time series forecasting](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.timeseriescatalog.forecastbyssa?view=ml-dotnet#Microsoft_ML_TimeSeriesCatalog_ForecastBySsa_Microsoft_ML_ForecastingCatalog_System_String_System_String_System_Int32_System_Int32_System_Int32_System_Int32_System_Boolean_System_Single_Microsoft_ML_Transforms_TimeSeries_RankSelectionMethod_System_Nullable_System_Int32__System_Nullable_System_Int32__System_Boolean_System_Boolean_System_Nullable_Microsoft_ML_Transforms_TimeSeries_GrowthRatio__System_String_System_String_System_Single_System_Boolean_).

Please feel free to reopen if this is still an issue.
