### ISSUE TITLE
Should the Microsoft.ML.*.StaticPipe namespaces fold into the Microsoft.ML.StaticPipe?

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#2746]
As we are aligning the namespaces of the trainers and transforms main package, `Microsoft.ML`; and moving them from subcategories to the main root, we should probably do the same for the StaticPipe assembly and namespaces. 

So potentially move things like: 
Microsoft.ML.StaticPipe.Runtime
Microsoft.ML.HalLearners.StaticPipe
Microsoft.ML.Transforms.StaticPipe
Microsoft.ML.LightGBM.StaticPipe

to 
Microsoft.ML.StaticPipe

**Comment by TomFinley** [comment]
Well, given that they're based on extension methods, I'd say so for everytthing but `Runtime`.

`Runtime` though deals with structures for *writing* the static extensions. I might prefer to keep them in a separate nuget so they're not in people's faces.

However (and i know you know this as you've already put it in backlog) this deals with experimental code so it is not essential for v1 release.

**Comment by wschin** [comment]
Static APIs will be deprecated soon, so I think this issue can be closed.
