### ISSUE TITLE
Need to rename HalLearners assembly and nuget

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#2756]
The name `HalLearners` isn't a great public name. We should come up with a better name.

Current issues:

1. What does `Hal` mean?
2. We are using the term "trainers" instead of "learners" everywhere else.
3. This assembly contains more than just learners/trainers. It also has vector whitening, which isn't a trainer.

Possible suggestions to get the naming started:

1. `Microsoft.ML.HardwareAccelerated`
2. `Microsoft.ML.HardwareAccelerated.Components`
3. `Microsoft.ML.Mkl`
    - (we already have `Microsoft.ML.Mkl.Redist`. this would be an analog to `ML.TensorFlow` and `ML.TensorFlow.Redist`)
4. `Microsoft.ML.Mkl.Components`

@TomFinley @sfilipi @Ivanidzo4ka @shauheen @yaeldekel

**Comment by TomFinley** [comment]
I think it was a joke to refer to those learners that had this relatively heavyweight MKL library as a dependency for one reason or another.

I like ``Microsoft.ML.MklTrainers` or `Microsoft.ML.MklComponents` or `Microsoft.ML.Mkl` or something like this. (If possible `Trainers` would be good, but there's more in there that depends on MKL than merely trainer estimators -- so maybe the more general name would be good).

The word "hardware accelerated" by itself is far too loaded of a term, the potential for misunderstandings way too high. Without knowing what I know, I think if I were to look at this library, and I saw, "hardware accelerated," my natural thought would be "OK, so, they are saying the rest the stuff *isn't* hardware accelerated." And, that would be incorrect while also making us look kind of silly.

**Comment by codemzs** [comment]
Even `Microsoft.ML.MKLTrainers` is a bit controversial because `TimeSeries` for example uses `MK`L but is not in this nuget.

**Comment by TomFinley** [comment]
I see. Well, I'm not sure that's a blocker. We have after all the "transforms" assembly without the suggestion that it refers to all transforms. (Indeed it does not.) How about `Microsoft.ML.Mkl.Components` then, anyway?

**Comment by codemzs** [comment]
`Microsoft.ML.Mkl.Components` it is! :)
