### ISSUE TITLE
LinearModelParameters have two ways to get Weights, should be one

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#2763]
we have this:
https://github.com/dotnet/machinelearning/blob/a0edc5c5724ed2895fd0c2fa5c2525d03de13455/src/Microsoft.ML.StandardLearners/Standard/LinearModelParameters.cs#L93
and we have this:
https://github.com/dotnet/machinelearning/blob/a0edc5c5724ed2895fd0c2fa5c2525d03de13455/src/Microsoft.ML.StandardLearners/Standard/LinearModelParameters.cs#L387

I would prefer to hide second one (and `IHaveFeatureWeights` interface) but it's up to discussion

**Comment by TomFinley** [comment]
I might actually prefer the opposite. It more closely resembles how `IDataView` and its schema and annotations are used. I also am unclear on the benefits of exposing ``IHaveFeatureWeights`, which is as an interface, AFAIK, not terribly well designed or thought out. (Does a multi-class logistic regression classifier have weights? How about OVA? How about an ensemble? How about a calibrated predictor.)

So I feel we must hide that interface. Whether or not we have one of these accessors or the other, I am slightly more indifferent. Either is fine I think. The latter is more in line with how we generally ask people to access data out of our core structures, so there is a consistency argument. The `IReadOnlyList` is easier to understand, and the performance reasons that lead us to prefer buffer reuse in `IDataView` itself are less important here.

**Comment by Ivanidzo4ka** [comment]
Sorry, I'm a bit confuse. I suggest to hide `IHaveFeatureWeights` and `GetFeatureWeights` method.
It looks like you prefer same thing, but you start your sentence with 
>I might actually prefer the opposite

**Comment by TomFinley** [comment]
Whoops, sorry @Ivanidzo4ka !! For some reason, I don't know why, I read what you wrote and my brain thought it said, "I would prefer to *have*" as opposed to "I would prefer to *hide*," which is what you actually wrote!!

Yes I agree with you. 😄 Sorry about the confusion.
