### ISSUE TITLE
One of the FeaturizeText extensions has the inputColumnNames as required

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#2768]
The are two extensions for Featurize text. 

        public static TextFeaturizingEstimator FeaturizeText(this TransformsCatalog.TextTransforms catalog, string outputColumnName, string inputColumnName = null);

        public static TextFeaturizingEstimator FeaturizeText(this TransformsCatalog.TextTransforms catalog, string outputColumnName, IEnumerable<string> inputColumnNames, TextFeaturizingEstimator.Options options);

IMO,
- On the first one, TextFeaturizingEstimator.Options options should exist as optional. 
- On the second one, TextFeaturizingEstimator.Options options should exist as optional. 

ATM, if i want to use the TextFeaturizingEstimator.Options, i have to create an IEnumerable<string> for inputColumnNames and give it the output column name. 

    mlContext.Transforms.Text.FeaturizeText("CarrierName",
        Enumerable.Repeat("CarrierName", 1),
        new TextFeaturizingEstimator.Options
        {
                  KeepDiacritics = false,
                  KeepPunctuations = false,
                  TextCase =TextNormalizingEstimator.CaseNormalizationMode.Lower,
                  OutputTokens = true,
                  VectorNormalizer = TextFeaturizingEstimator.TextNormKind.L2
         }))

**Comment by TomFinley** [comment]
Interesting find, thank you @sfilipi. As far as I can see, elsewhere when we have options, we have *only* those options, and they are non-optional. This pursuant to #1798. So it seems like the second signature should not take `inputColumnNames`, but it should instead have an input column names on its options. (Which as far as I can tell it does.) By having both, we are inviting the potential of the question "who wins" on these two settings. (See again #1798.)

So I would prefer to solve this in another way:

1. The first one stays as is.
2. The second one does not accept `IEnumerable`, but instead takes an option.

If we find that some advanced options are in fact valuable, we should consider adding them as (probably) optional parameters to the first one.

**Comment by sfilipi** [comment]
Completed in #2815
