### ISSUE TITLE
Possible Bug Tensorflow in v0.11 - Invalid argument: input must be 4-dimensional[224,224,3]

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning#2778]
Starting from [a working ML.NET sample](https://github.com/dotnet/machinelearning-samples/tree/migration/v.11/samples/csharp/getting-started/DeepLearning_ImageClassification_TensorFlow/ImageClassification) scoring the standard TensorFlow Inception v3 model (it was working on 0.9 and 0.10) after migrating to 0.11 (I just needed to fix a couple of breaking changes in the API) the model is now throwing the following exception: 

Exception from TensorFlow:

```
2019-02-27 14:56:18.800272: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at conv_ops.cc:437 : Invalid argument: input must be 4-dimensional[224,224,3]

EXCEPTION
#########
input must be 4-dimensional[224,224,3]
         [[{{node conv2d0_pre_relu/conv}} = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_input_0_0, conv2d0_w)]]
```

**Comment by CESARDELATORRE** [comment]
This other [TensorFlow sample using the Estimator for training](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_TensorFlowEstimator/ImageClassification.Train) is having the same issue/exception coming from TensorFlow.

**Comment by prathyusha12345** [comment]
@zeahmed, @CESARDELATORRE  @yaeldekel  I am still getting the same error after migrating to Ml.Net v1.0.0-preview.

```
input must be 4-dimensional[3,224,224]
	 [[{{node conv2d0_pre_relu/conv}} = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_input_0_0, conv2d0_w)]]
```

The pipeline is below

```
var pipeline = mlContext.Transforms.LoadImages(outputColumnName: "input", imageFolder: imagesFolder, inputColumnName: nameof(ImageNetData.ImagePath))
                            .Append(mlContext.Transforms.ResizeImages(outputColumnName: "input", imageWidth: ImageNetSettings.imageWidth, imageHeight: ImageNetSettings.imageHeight, inputColumnName: "input"))
                            .Append(mlContext.Transforms.ExtractPixels(outputColumnName: "input"))
                            .Append(mlContext.Model.LoadTensorFlowModel(modelLocation).
                            ScoreTensorFlowModel(outputColumnNames: new[] { "softmax2" },
                                                inputColumnNames: new[] { "input" }));
```

Could anyone help

**Comment by zeahmed** [comment]
You need to set `addBatchDimensionInput = true` in `ScoreTensorFlowModel` as described here.
https://github.com/dotnet/machinelearning/blob/7e0cc46d5aba7d6464106293082ab87344ad24b1/src/Microsoft.ML.TensorFlow/TensorFlowModel.cs#L57

**Comment by prathyusha12345** [comment]
I set this to true. But When I am getting the below exception when predicting.

Exception:

```
input depth must be evenly divisible by filter depth: 224 vs 3
	 [[{{node conv2d0_pre_relu/conv}} = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_input_0_0, conv2d0_w)]]
```

Code:

` var probs = model.Predict(sample).PredictedLabels;`

**Comment by zeahmed** [comment]
My guess is you are passing data as `NCHW [3,224,224]` while your model expect `NHWC`.
> [[{{node conv2d0_pre_relu/conv}} = Conv2D[T=DT_FLOAT, data_format="NHWC"

see if you can solve it by setting `bool interleavePixelColors = true` in `ExtractPixels`

**Comment by prathyusha12345** [comment]
Yes its working fine after adding the settings  interleavePixelColors: true, offsetImage: 117

mlContext.Transforms.ExtractPixels(outputColumnName: "input", interleavePixelColors: ImageNetSettings.channelsLast, offsetImage: ImageNetSettings.mean)

Thanks @zeahmed  for helping.

**Comment by prathyusha12345** [comment]
@zeahmed @yaeldekel I am getting the same exception as shown below in other sample i.e TenosrFlow Estimator sample  while predicting using the model [here](https://github.com/dotnet/machinelearning-samples/blob/migration/1.0.0-preview/samples/csharp/getting-started/DeepLearning_TensorFlowEstimator/ImageClassification.Predict/Model/ModelScorer.cs) even though I have set up interleavePixelColors = true in ExtractPixels, and adding addBatchDimensionInput: true while building the model pipeline as below. 

**Model Pipeline:**
```
   var pipeline = mlContext.Transforms.Conversion.MapValueToKey(outputColumnName: LabelTokey,inputColumnName:"Label")
                            .Append(mlContext.Transforms.LoadImages(outputColumnName: "input", imageFolder: imagesFolder, inputColumnName: nameof(ImageNetData.ImagePath)))
                            .Append(mlContext.Transforms.ResizeImages(outputColumnName: "input", imageWidth: ImageNetSettings.imageWidth, imageHeight: ImageNetSettings.imageHeight, inputColumnName: "input"))
                            .Append(mlContext.Transforms.ExtractPixels(outputColumnName: "input", interleavePixelColors: ImageNetSettings.channelsLast, offsetImage: ImageNetSettings.mean))
                            .Append(mlContext.Model.LoadTensorFlowModel(featurizerModelLocation).
                                 ScoreTensorFlowModel(outputColumnNames: new[] { "softmax2_pre_activation" }, inputColumnNames: new[] { "input" }, addBatchDimensionInput: true))
                            .Append(mlContext.MulticlassClassification.Trainers.LbfgsMaximumEntropy(labelColumnName:LabelTokey, featureColumnName:"softmax2_pre_activation"))
                            .Append(mlContext.Transforms.Conversion.MapKeyToValue(PredictedLabelValue,"PredictedLabel"))
                            .AppendCacheCheckpoint(mlContext);
```

**Exception:**

`2019-04-09 11:11:10.709759: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at conv_ops.cc:437 : Invalid argument: input must be 4-dimensional[224,224,3]`

The sample is available here https://github.com/dotnet/machinelearning-samples/tree/migration/1.0.0-preview/samples/csharp/getting-started/DeepLearning_TensorFlowEstimator    

Adding @CESARDELATORRE  for reference.
Could anyone help

**Comment by CESARDELATORRE** [comment]
Closing this issue. @prathyusha12345 was not trying the right serialized ML.NET model (.ZIP file) but the old .ZIP file when scoring on the other project. Not a problem then! :)

When trying with the right .ZIP file, it is working properly.

There's another issue related to the algorithm for multi-class classification where it works with `LbfgsMaximumEntropy` but doesn't work with `SdcaMaximumEntropy`. We'll open a different issue for that.
