### ISSUE TITLE
GetExecutingAssemblyLocation in the DNNImageFeaturizers composes the wrong path

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#2785]
Create a console project, add the MIcrosoft.ML, the Microsoft.Ml.OnnxTransformer and one of the Microsoft.ML.DnnImageFeaturizer packages. 

Try running the following snippet:

             // Downloading a few images, and an images.tsv file, which contains a list of the files from the dotnet/machinelearning/test/data/images/.
            // If you inspect the fileSystem, after running this line, an "images" folder will be created, containing 4 images, and a .tsv file
            // enumerating the images. 
            var imagesDataFile = Microsoft.ML.SamplesUtils.DatasetUtils.DownloadImages();

            // Preview of the content of the images.tsv file
            //
            // imagePath    imageType
            // tomato.bmp   tomato
            // banana.jpg   banana
            // hotdog.jpg   hotdog
            // tomato.jpg   tomato

            var data = mlContext.Data.CreateTextLoader(new TextLoader.Options()
            {
                Columns = new[]
                {
                        new TextLoader.Column("ImagePath", DataKind.String, 0),
                        new TextLoader.Column("Name", DataKind.String, 1),
                }
            }).Load(imagesDataFile);

            string codeBaseUri = typeof(Program).Assembly.CodeBase;
            string path = new Uri(codeBaseUri).AbsolutePath;
            var f =  Directory.GetParent(path).FullName;

            var imagesFolder = Path.GetDirectoryName(imagesDataFile);
            // Image loading pipeline. 
            var pipeline = mlContext.Transforms.LoadImages(imagesFolder, ("ImageObject", "ImagePath"))
                          .Append(mlContext.Transforms.ResizeImages("ImageObject", imageWidth: 224, imageHeight: 224))
                          .Append(mlContext.Transforms.ExtractPixels("Pixels", "ImageObject"))
                           //.Append(mlContext.Transforms.DnnFeaturizeImage("FeaturizedImage", m => m.ModelSelector.ResNet18(mlContext, m.OutputColumn, m.InputColumn, @"C:\Code\mlnet2\machinelearning-1\bin\AnyCPU.Debug\Microsoft.ML.Samples\netcoreapp2.1\DnnImageModels"), "Pixels"));
                           .Append(mlContext.Transforms.DnnFeaturizeImage("FeaturizedImage", m => m.ModelSelector.ResNet18(mlContext, m.OutputColumn, m.InputColumn), "Pixels"));

            var transformedData = pipeline.Fit(data).Transform(data);

            var preview = transformedData.Preview();

You'll notice that the program will fail with message:

`System.ArgumentOutOfRangeException: 'Specified argument was out of the range of valid values. Parameter name: ModelFile'`

That is because the Resnet18 extension is looking for the model in the path created by [AssemblyPathHelper](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.DnnImageFeaturizer.AlexNet/AssemblyPathHelpers.cs)

The path created points to the  **lib\netstandard2.0\DnnImageModels\**
the packages actually get downloaded in the  **\tools\DnnImageModels**  folder. 

Full path of the folders, inside the downloaded nuget packages. 
- constructed:  **microsoft.ml.dnnimagefeaturizer.resnet18\<version>\lib\netstandard2.0\DnnImageModels\**
- actual location of the DnnImageModels folder:  **microsoft.ml.dnnimagefeaturizer.resnet18\<version>\tools\DnnImageModels**

Need to construct the correct path.

**Comment by eerhardt** [comment]
@Anipik - FYI. I think you’ve recently worked in this area.

**Comment by Anipik** [comment]
I will take a look at it tomorrow
