### ISSUE TITLE
Rename Microsoft.ML.StandardLearners to Microsoft.ML.StandardTrainers.

### ISSUE THREAD

**Issue by codemzs** [dotnet/machinelearning#2786]
CC: @TomFinley , @eerhardt

**Comment by TomFinley** [comment]
Is the issue confined strictly to just the assembly name? I wonder if it is the intent of this issue to also change, say, things like `StandardLearners` in code to `StandardTrainers`. (E.g., `StandardLearnersCatalog`.)
