### ISSUE TITLE
FastForest - Add Probability for predictions

### ISSUE THREAD

**Issue by bartczernicki** [dotnet/machinelearning#2787]
Add probability response for inference to the Fast Forest algorithm.

**Comment by wschin** [comment]
FastForest doesn't naturally support probability. Please use `Calibrator` to convert its raw score to probability following [this example](https://github.com/dotnet/machinelearning/blob/7e280d59211bbe99d9132f76509b7ca6c6a1ed1c/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/Calibrators/Platt.cs#L42).
