### ISSUE TITLE
What is the relationship between this project and the Windows ML project?

### ISSUE THREAD

**Issue by sharpwood** [dotnet/machinelearning#2789]

**Comment by rogancarr** [comment]
@shauheen @asthana86 Perhaps one of you could speak to this?

**Comment by najeeb-kazmi** [comment]
@sharpwood [WinMLTools](https://docs.microsoft.com/en-us/windows/ai/windows-ml/convert-model-winmltools) can convert ML models trained with different frameworks into ONNX. [Windows ML](https://docs.microsoft.com/en-us/windows/ai/windows-ml/) is an inferencing API and runtime for using ONNX models in Windows apps.

ML.NET is one such training framework. Many ML.NET components are exportable to ONNX and used in inferencing in Windows apps with Windows ML.
