### ISSUE TITLE
SupportedMetric.ByName() method no longer functions

### ISSUE THREAD

**Issue by george-microsoft** [dotnet/machinelearning#279]
PipelineInference/AutoInference.cs/SupportedMetric.ByName() method no longer works as expected, since names of fields in SupportedMetric no longer match their values. Need to change method to work with latest commits fixing the names of the metric values, comparing the values and not the field names themselves.

**Comment by Ivanidzo4ka** [comment]
Can we close this one?

**Comment by george-microsoft** [comment]
Yes, the fix should be merged.

**Comment by Ivanidzo4ka** [comment]
But it's merged already

**Comment by george-microsoft** [comment]
Yes, I meant that it should already be in there. Closing the issue.
