### ISSUE TITLE
Refactor cancellation mechanism and make it internal, accessible via experimental nuget.

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#2795]
Some time ago I added `StopExecution` method and `IsCancelled` flag to IHost.
https://github.com/dotnet/machinelearning/blob/fbf282d982223a51cf6e4a9ad9f3f036e0f150ca/src/Microsoft.ML.Core/Data/IHostEnvironment.cs#L98

https://github.com/dotnet/machinelearning/blob/fbf282d982223a51cf6e4a9ad9f3f036e0f150ca/src/Microsoft.ML.Core/Data/IHostEnvironment.cs#L74

It was quick solution to make certain algorithms react to stop signal from user. I doubt in long run it's proper way to do it. And it probably required lengthy discussion how to expose stopping functionality (method, or `CancellationToken`, or something else).

But for now I think it's a good idea to remove method and flag from our public API. Especially considering what no code actually checking `IsCancelled` flag.

EDIT: We decided to keep this functionality but make it internal and still be accessible via experimental nuget.

**Comment by codemzs** [comment]
From my experience this kind of work is done via `CancellationToken`

**Comment by Ivanidzo4ka** [comment]
As I said above, functionality like this deserve proper discussion, and it's not v1 priority.
Let's focus right now on code cleaning.

**Comment by codemzs** [comment]
@Ivanidzo4ka I wasn't suggesting we do the design work of proper cancellation mechanism now. Anyways PR to clean the cancellation mess is out ...
