### ISSUE TITLE
TextFeaturizer API is non-standard

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#2801]
When specifying the input columns, `TextFeaturizer` specifies an `IEnumerable<string>`. The standard in the API is to specify a `string[]`.

This API should be updated to be consistent with the others. If we prefer `IEnumerable`, then we should switch all the other APIs.

**Comment by Ivanidzo4ka** [comment]
https://github.com/dotnet/machinelearning/issues/2460 duplicate?

**Comment by wschin** [comment]
@Ivanidzo4ka, #2801 and #2460 are different.
In #2460, a suggestion is to replace `IEnumerable<string>` with `params`. Here @rogancarr wants to replace `IEnumerable<string>` with `string[]`.

**Comment by Ivanidzo4ka** [comment]
That's why it has question mark in the end!
They about same thing right? how to make that API right. They just propose different things.

**Comment by rogancarr** [comment]
My main concern is consistency across the APIs, and I don't have strong feelings about the solution we pick. That said, I agree with @TomFinley in the linked PR that it would be nice to have `params` overloads, as these are way easier to write out when you're using your APIs.
