### ISSUE TITLE
StochasticDualCoordinateAscent not work For Multi-class after migrate to 0.10.0 Gives different Evaluation result Compare to 0.6.0

### ISSUE THREAD

**Issue by gouravbhatt** [dotnet/machinelearning#2813]
**### System information**
* **OS version/distro**: W7
* **.NET Version (eg., dotnet --info)**:  4.7.2

### Issue
* **What did you do?** Migrated my code from 0.6.0 to 0.10.0
* **What happened?** StochasticDualCoordinateAscentClassifire Algorithm is giving different Evaluation result with same train and test data.

* **What did you expect?**
  it should work fine

### Source code / logs
**version 0.6.0 Code**
            string trainingDataLocation = "Data/VendortrainData.csv";
            string testDataLocation = "Data/VendortestData.csv";

var pipeline = new LearningPipeline();
            pipeline.Add(new TextLoader(_trainingDataLocation).CreateFrom<VendorData>(useHeader: true, separator: ','));
            pipeline.Add(new ColumnConcatenator(
                            "Features",
                            "VendorID",
                            "Item",
                            "TooEarly",
                            "OnTime",
                            "TooLate",
                            "TooLittle",
                            "Right",
                            "TooMuch"
                          ));
            pipeline.Add(new StochasticDualCoordinateAscentClassifier());
            var model= pipeline.Train<VendorData, VendorPrediction>();
            var SDCAMetrics = modelEvaluator.EvaluateClass(perceptronSDCA, testDataLocation);
           **RESULT**
           **AccuracyMacro** : 1
           **AccuracyMacro** : 1

**version 0.10.0 Code**
      var dataProcessPipeline = mlContext.Transforms.Concatenate(outputColumnName: DefaultColumnNames.Features, "VendorID",
                            "Item",
                            "TooEarly",
                            "OnTime",
                            "TooLate",
                            "TooLittle",
                            "Right",
                            "TooMuch")
                .Append(mlContext.MulticlassClassification.Trainers.StochasticDualCoordinateAscent(DefaultColumnNames.Label, DefaultColumnNames.Features));

ITransformer trainedModel = dataProcessPipeline.Fit(trainingDataView);

 var predictions = trainedModel.Transform(testDataView);
 var metrics = mlContext.MulticlassClassification.Evaluate(data: predictions, label: DefaultColumnNames.Label, score: DefaultColumnNames.Score);

ConsoleHelper.PrintMultiClassClassificationMetrics("StochasticDualCoordinateAscent", metrics);
 **RESULT**
           **AccuracyMacro** : 0.11
           **AccuracyMacro** : 0.25

**Comment by rogancarr** [comment]
Hi @gouravbhatt!

This may not necessarily be a bug in ML.NET. For one thing, your learner using the 0.6 version is getting an unrealistic performance (perfect Micro & Macro Accuracy), while the 0.10 version looks more reasonable. One other thing to keep in mind is that the `StochasticDualCoordinateAscent` (aka `SDCA`) algorithm is random and you aren't guaranteed to get the same results with multiple runs if you are using multiple threads.

To debug this, can you
1. Set a `seed` and concurrency `conc` in MLContext?
```cs
var mlContext = new MLContext(seed: 1, conc: 1); 
```
2. Using this `MlContext`, can you please rerun your 0.6 and 0.10 calculations using the same train and test datasets and share the results?

That should give us a better sense for what the issue may be.

**Comment by gouravbhatt** [comment]
Hi @rogancarr 

I have attached  sample code for both 0.6 and 0.10 version along with the data.
and it gives the same result on multiple run.

The underlying logic for predicting the target column/Feature is very simple with shared data-set. Hence, it might be giving the accuracy nearly 100%..
we have tried the same thing in **R** also and give accuracy near 0.98-0.99


[SCDA.zip](https://github.com/dotnet/machinelearning/files/2924499/SCDA.zip)

**Comment by gouravbhatt** [comment]
@rogancarr @radical @shanselman @AArnott 
any update on the above query

**Comment by rogancarr** [comment]
@gouravbhatt I think I see what happened here.

We've made a bunch of changes between 0.6 and 0.10 (now 0.11). The version you were using in 0.6 was our "Legacy API" and has a lot of "convenience" functions built in, like auto-caching and auto-normalization. In addition, we've changed a few things about `SDCA` along similar lines.

In your case, you can reconstruct the original behavior by explicitly normalizing your data in the pipeline. By default, we use the `MinMax` normalization mode. It's also useful to cache the data after normalization, as `SDCA` will want to roll through the data quite a few times, and in random order.
```cs
 var dataProcessPipeline = mlContext.Transforms.Concatenate(DefaultColumnNames.Features,
        new string[] { "VendorID", "Item", "TooEarly", "OnTime", "TooLate", "TooLittle", "Right", "TooMuch" })
    .Append(mlContext.Transforms.Normalize("Features"))
    .AppendCacheCheckpoint(mlContext)
    .Append(mlContext.MulticlassClassification.Trainers.StochasticDualCoordinateAscent(DefaultColumnNames.Label, DefaultColumnNames.Features));
```

In general, we do expect model behavior to change from release to release -- but for the better ;) !

**Comment by gouravbhatt** [comment]
@rogancarr Thank you :)

Is there any link or document where we can find the list of changes like above.

**Comment by rogancarr** [comment]
@gouravbhatt Check out the release notes here: https://github.com/dotnet/machinelearning/tree/master/docs/release-notes

Please note that right now the APIs are unstable, but once we ship V1.0 (very soon), we will have stable APIs. I would suggest switching to the V1.0 release candidate once we have it.

That said, v0.12 (end of March) will be the last of the big breaking changes. V0.11, which we released last week, is very close to the APIs that we will release for V1.0.

**Comment by gouravbhatt** [comment]
Thank you :)
