### ISSUE TITLE
can not register

### ISSUE THREAD

**Issue by leecow** [dotnet/machinelearning#2823]
@Emmagrabergs commented on [Sat Mar 02 2019](https://github.com/dotnet/core/issues/2361)

Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant..

---

@leecow commented on [Sat Mar 02 2019](https://github.com/dotnet/core/issues/2361#issuecomment-468941055)

Moving to the ML repo. @Emmagrabergs - chances are they will need additional details on what you were doing and the errors you see.

**Comment by Ivanidzo4ka** [comment]
Can you provide more information. I'm not quite sure what this issue about.

**Comment by artidoro** [comment]
Closing since no more details were provided.
