### ISSUE TITLE
Scrubbing transformers (Meta issue)

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#2827]
We need to make sure our transforms are in good shape.

1. No protected fields/members/method in public classes. Only private protected.

2. Transformer class is sealed.

3. Transformer/Estimator should and catalog method names should be sensible (#2853 fine if slightly different).

4. Column options cleaning:
- Option should have meaning and proper way it initialize it self. 
- No short names.
5. `public IReadOnlyCollection<(string outputColumnName, string inputColumnName)> Columns => ColumnPairs.AsReadOnly(); ` 
I don't think that public thing make sense to me, I would prefer to get rid of it.

6. No public value tuples (especially in catalog methods) (#2881)

List still in progress.

**Comment by shauheen** [comment]
Thanks @Ivanidzo4ka , Please make sure that the transforms that are not going 1.0 are not in the scope of this work for now. We can file other issues outside Project 13 for those.
