### ISSUE TITLE
Scrubbing `Projection` transformers

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#2831]
Sub task of #2827
RFF, LpNorm, GcNorm, PCA, Whiten, Normalize.
Projection catalog is bad name, and we probably should toss around this transforms across other catalogs.

**Comment by wschin** [comment]
They are in `projection` because they all map feature vectors to a low-rank space. Why do you think this name is bad?

**Comment by Ivanidzo4ka** [comment]
Well, for example LpNorm and GcNorm doesn't lower rank at all AFAIK.
And if I correctly remember @TomFinley comment: "What is transformer if not projection of data?"
Maybe DimensionalityReduction is a better catalog name than Projection

**Comment by wschin** [comment]
Just updated/created some catalogs. We now create `Normalization` for all normalizer, `DimensionReduction` for PCA and VectorWhiten, `Kernel` for RFF kernel approximation.
