### ISSUE TITLE
Scrubbing Text related transformers

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#2832]
Sub task of #2827

- [x] WordEmbedding #2891 
- [x] FeaturizeText #2944 
- [x] LDA #2890
- [x] NormalizeText #2918
- [x] ProduceHashedNGrams #2898
- [x] ProduceHashedWordBag #2898
- [x] ProduceNgrams #2898
- [x] ProduceWordBag #2898
- [x] RemoveStopWords #2916
- [x] RemoveCustomStopWords #2916
- [x] TokenizeChar #2916
- [x] TokenizeWords #2916

**Comment by shauheen** [comment]
@Ivanidzo4ka , @wschin can this issue be closed now?

**Comment by wschin** [comment]
Yes. Let me close it.
