### ISSUE TITLE
GAM parameter names are non-standard

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#2857]
The trained `Generalized Additive Models` (aka `GAMs`) methods for obtaining trained model parameters have non-standard names and various inconsistencies.

These are the properties:
```cs
var shapeFunctionsBins = gamModel.GetBinUpperBounds();
var shapeFunctionsValues = gamModel.GetBinEffects();
var numShapeFunctions = gamModel.NumShapeFunctions;
var intercept = gamModel.Intercept;
```

There are a few issues here:
1. Nonstandard names
I propose `BinUpperBounds` and `BinEffects` be renamed `ShapeFunctionsBins` and `ShapeFunctionsBinValues`.
2. Inconsistent names
Sometimes we say `ShapeFunctions`, sometimes we done. Same solution proposed as No. 1.
3. Inconsistency in `Get` methods vs. properties
e.g. `Intercept` vs. `GetBinUpperBounds`.
I propose we move all the methods to be properties.
e.g. `model.ShapeFunctionsBins`.
4. Names leak implementation
`BinUpperBounds` vs. `Bins`.
Question: should we just say `Bins` rather than `BinUpperBounds` and say that they are the upper bounds for the bin in the documentation? `BinUpperBounds` is very verbose, and speaks to how we bin.

**Comment by Ivanidzo4ka** [comment]
https://github.com/dotnet/machinelearning/pull/2753 You can tell this to @wschin since he is doing scrubbing of fast tree learners.

**Comment by rogancarr** [comment]
@wschin Re-assigned this to you!

**Comment by wschin** [comment]
> The trained Generalized Additive Models (aka GAMs) methods for obtaining trained model parameters have non-standard names and various inconsistencies.
> These are the properties:
> var shapeFunctionsBins = gamModel.GetBinUpperBounds();
> var shapeFunctionsValues = gamModel.GetBinEffects();
> var numShapeFunctions = gamModel.NumShapeFunctions;
> var intercept = gamModel.Intercept;
> There are a few issues here:
> 
> Nonstandard names
> I propose BinUpperBounds and BinEffects be renamed ShapeFunctionsBins and ShapeFunctionsBinValues.
They look a bit long and the name `GamModelParameters.ShapeFunctionBins` doesn't look more informative than `GamModelParameters.BinUpperBounds` because `ShapeFunction` is rarely used elsewhere.
> Inconsistent names
> Sometimes we say ShapeFunctions, sometimes we done. Same solution proposed as No. 1.
> Inconsistency in Get methods vs. properties
> e.g. Intercept vs. GetBinUpperBounds.
> I propose we move all the methods to be properties.
> e.g. model.ShapeFunctionsBins.
It's consistent. For jagged 2-D array, we already return `IReadOnlyList` over one of its slice in FastTree's APIs.
> Names leak implementation
> BinUpperBounds vs. Bins.
> Question: should we just say Bins rather than BinUpperBounds and say that they are the upper bounds for the bin in the documentation? BinUpperBounds is very verbose, and speaks to how we bin.
I am hesitating to have
``csharp
var bound = Bins[5];
```
while the following looks clearer.
```csharp
var bound = BinUpperBounds[5];
```
Cleaning of GAM family is also a part of #2753.
