### ISSUE TITLE
NumberOfIterations vs. MaxIterations

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#2871]
The recent naming changes to K-Means and SDCA (and perhaps others?) resulted in `MaxIterations` being renamed to `NumberOfIterations`. Since this parameter specifies the worst-case bound and not the actual number of iterations taken in most cases, I think we should keep it named `MaxIterations`. 

Whatever we call it, `NumberOfIterations` is not what this parameter specifies &mdash; this is a stopping criterion, not a guaranteed execution parameter.

**Comment by wschin** [comment]
Maybe `MaximumNumberOfIteration` or `MaximumIterationCount`?

**Comment by rogancarr** [comment]
`MaximumNumberOfIterations`
