### ISSUE TITLE
exampleWeightColumnName v.s. weightColumnName

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#2873]
In trainers like
```csharp
        internal RandomizedPcaTrainer(IHostEnvironment env,
            string features,
            string weights = null,
            string featureColumnName,
            string exampleWeightColumnName = null,
            int rank = Options.Defaults.NumComponents,
            int oversampling = Options.Defaults.OversamplingParameters,
            bool center = Options.Defaults.IsCenteredZeroMean,
            bool ensureZeroMean = Options.Defaults.EnsureZeroMean,
            int? seed = null)
```
we have `exampleWeightColumnName` but it seems `weightColumnName` is clear enough under this context. Can we switch to `weightColumnName`?

**Comment by Ivanidzo4ka** [comment]
origin of current name: https://github.com/dotnet/machinelearning/issues/2257

**Comment by Ivanidzo4ka** [comment]
actually https://github.com/dotnet/machinelearning/issues/2177#issuecomment-455395698

**Comment by wschin** [comment]
Now, I feel `exampleWeightColumnName` is actually a good name. There are too many places where `Weight` is included in a variable names. Having `example` can clarify those cases.
