### ISSUE TITLE
Splitting datasets to train and test sets?

### ISSUE THREAD

**Issue by jwood803** [dotnet/machinelearning#288]
Is there a way to do this with the current release? 

I noticed there's a [`TrainTestSplitter`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.traintestdatasetsplitter?view=ml-dotnet), but there doesn't seem to be any documentation on how to use it and have been unsuccessful when I was messing with it. 

Thanks!

**Comment by zeahmed** [comment]
Do you mean CrossValidation (CV)? or you just want to split data? CV will be available in the next release. You can have a look at the following CrossValidation test for more details.https://github.com/dotnet/machinelearning/blob/465b123f53cb56a4e6d3c355ed35373a19b88329/test/Microsoft.ML.Tests/Scenarios/SentimentPredictionTests.cs#L52

**Comment by Ivanidzo4ka** [comment]
If you use myget, or bits from fresh github (this is part of v0.2 which we will release in few days) you can use CollectionDataSource on top of enumerable and just apply any LINQ filters on top of your collection to split it into two halves.

Another option is to replicate CrossValidation behavior.
Create your pipeline, add RandomNumberGenerator  to it and then apply RowRangeFilter, first step will generate you column with value [0..1) and second step let you filter out by this column so you can randomly split data into two different sets (one set with range filter greater or equal than certain value, other set with range filter less than certain value)

**Comment by TomFinley** [comment]
In addition to what @Ivanidzo4ka says about replicating what the code does with the generator and filter, there is also the bootstrap sample transform to consider. In particular: you can generate a partition using default settings of that transform (typically would be used as the trainining set), and alternately with the "compliment" setting enabled (which generates the out-of-bag sample, typically used as test or validation dataset). It would depend on whether you wanted sampling with or without replacement, basically.

**Comment by jwood803** [comment]
I looked through the source and saw that `TestTrainSplit.Split` was used, so I tried that out and it seems to split the data nicely.

```
var env = new TlcEnvironment(42);
var inputFile = new SimpleFileHandle(env, dataPath, false, false);

var dataView = ImportTextData.TextLoader(env, new ImportTextData.LoaderInput()
{
  Arguments =
  {
      HasHeader = true,
      Separator = ","
  },
  InputFile = inputFile
});

var data = TrainTestSplit.Split(env, new TrainTestSplit.Input { Data = dataView.Data, Fraction = 0.8f });
```
Is this valid to use in applications? I also don't think this can be added to a pipeline, either.

**Comment by zeahmed** [comment]
Yes, you can use it this way as well. Currently, you won't be able to use it in the pipeline. However, with major revamp in API #371, this will be possible too.

**Comment by svickers** [comment]
@jwood803 Thanks for the code sample, what do you do with the IDataView once you have it?  Having trouble figuring out how to use it with my pipeline like the TextLoader.

**Comment by Ivanidzo4ka** [comment]
DRI RESPONSE:
This is an old thread about now legacy API.
How to split data into train test in new API you can find from cookbook:
https://github.com/dotnet/machinelearning/blob/master/docs/code/MlNetCookBook.md#how-do-i-train-using-cross-validation
I'm intent to close this issue within few next day if no one reply.
