### ISSUE TITLE
Unify way of setting random seed

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#2917]
I can understand why we use nullable seed in one place and defaults in another, but why it's uint in one places and int in others is beyond my understanding.

**UInt:**
https://github.com/dotnet/machinelearning/blob/b861b5d64841cbe0f2c866ee7586872aac450a51/src/Microsoft.ML.Data/Transforms/Hashing.cs#L1164

https://github.com/dotnet/machinelearning/blob/b861b5d64841cbe0f2c866ee7586872aac450a51/src/Microsoft.ML.Transforms/Text/NgramHashingTransformer.cs#L892

https://github.com/dotnet/machinelearning/blob/24f782d306f58d31778eddde181c16939be17292/src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs#L377

https://github.com/dotnet/machinelearning/blob/b861b5d64841cbe0f2c866ee7586872aac450a51/src/Microsoft.ML.Transforms/Text/WrappedTextTransformers.cs#L184

https://github.com/dotnet/machinelearning/blob/b861b5d64841cbe0f2c866ee7586872aac450a51/src/Microsoft.ML.Transforms/OneHotHashEncoding.cs#L241

**Int:**

https://github.com/dotnet/machinelearning/blob/24f782d306f58d31778eddde181c16939be17292/src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs#L135

https://github.com/dotnet/machinelearning/blob/24f782d306f58d31778eddde181c16939be17292/src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs#L293

https://github.com/dotnet/machinelearning/blob/b861b5d64841cbe0f2c866ee7586872aac450a51/src/Microsoft.ML.Transforms/RandomFourierFeaturizing.cs#L659

https://github.com/dotnet/machinelearning/blob/b861b5d64841cbe0f2c866ee7586872aac450a51/src/Microsoft.ML.PCA/PCACatalog.cs#L31

https://github.com/dotnet/machinelearning/blob/b861b5d64841cbe0f2c866ee7586872aac450a51/src/Microsoft.ML.Data/MLContext.cs#L79

**Comment by Ivanidzo4ka** [comment]
@wschin  prefers `uint`
I personally leaning towards `int` mostly because of I can see example of seed as `int` https://docs.microsoft.com/en-us/dotnet/api/system.random.-ctor?view=netframework-4.7.2
@TomFinley  @eerhardt  Do you have any preferences?

**Comment by Ivanidzo4ka** [comment]
Per offline discussion.
If it's hashing seed it should be `uint` if it's random seed it should be `int`

**Comment by TomFinley** [comment]
So this is a little funny, but it has its roots in some practical consideration. There is an unfortunate collision of the term "seed" to mean two separate things. In the case of PRNGs (most relevant is `System.Random`) the seed is given out as `int`. So we should adhere to that. But there is a separate sense of the word "seed" to mean the starting point of the hash function -- that is, all our hashing based featurization and whatnot is based off Murmur3, which uses a `uint` seed in [all the literature and code I see surrouding it](https://en.wikipedia.org/wiki/MurmurHash#MurmurHash3). So I think this distinction between the two "senses" of seed are appropriate. If it is genuinely confusing, we might consider renaming one or two of them, but hopefully the context makes clear which we're talking about (as I think it does, but I could be wrong about that). I'd rather keep the types "right" and rename one of them if people do find it confusing though.
