### ISSUE TITLE
OVA Multiclass Classification can be instantiated for variety of sub-trainer training tasks

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#2920]
In writing a test for #2859, I have found that it is possible to create an `OVA` (aka "One-Versus-All") multiclass classification trainer learners other than a binary classifier as an input.

One of our V1 Goals is:
- Metacomponents smartly restrict their use to compatible components.   Example: "When specifying what trainer OVA should use, a user will be able to specify any binary classifier. If they specify a regression or multi-class classifier ideally that should be a compile error."

For all types
- **Anomaly Detection** throws on `Fit()` due to data mismatch. Suggests that this could work under ideal conditions.
- **Binary classification** works, as expected.
- **Clustering** is a runtime error upon pipeline construction (OVA checks the model type produced).
- **Multiclass classification** is a runtime error upon pipeline construction (OVA checks the model type produced).
- **Ranking** pipeline can be instantiated, but `Fit()` fails on "mismatch for label column".
- **Regression** pipeline can be instantiated, but `Fit()` fails on "mismatch for label column".

(Note that I didn't run a recommender check because this needs to be coded x64-only at this point.)

**Updated**: With the recent change to one-label-type-per task, Ranking and Regression now fail on the `Fit()`. I've updated the title to reflect that we can no longer train working models, but we can instantiate the pipeline.

**Comment by ganik** [comment]
@rogancarr can you pls share your tests code you used for repro?

**Comment by rogancarr** [comment]
@ganik Check out this PR for the test cases: https://github.com/dotnet/machinelearning/pull/2921
