### ISSUE TITLE
Scrubbing normalization transforms

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#2928]
Sub task of #2827 
`LpNormalize`
`GlobalContrastNormalize`
(since `LpNormColumnOptions` and `GcnColumnOptions` are nested classes we can just call them `ColumnOptions`)
`Normalize `
stuff like: `public TData Stddev`
or  `public readonly ImmutableArray<NormalizingTransformer.ColumnOptions> Columns;`
or `public readonly int NumBins;`

**Comment by wschin** [comment]
Is this covered by #2888?
