### ISSUE TITLE
More trainer related naming alignment

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#2938]
Take another pass over the trainers and the model parameter types, and align them, because now we have:

`LogisticRegressionMulticlassClassificationTrainer` but `MulticlassLogisticRegressionModelParameters`. 

I think following the same principles on the ModelParams might make them more relatable; so change `MulticlassLogisticRegressionModelParameters` to `LogisticRegressionMulticlassModelParameters`

**Comment by sfilipi** [comment]
@shauheen would this be a candidate for Project 13?

**Comment by abgoswam** [comment]
Following #2919 .. should we call it : 

- LogisticRegressionMulticlass**Classification**ModelParameters

That way it would be consistent across the convention we are following across the codebase now. This looks a bit long, but we can treat this as a special case.

**Comment by abgoswam** [comment]
In general, it seems there isn't a 1:1  mapping between trainer and model parameter types. e.g `SdcaNonCalibratedBinaryClassificationTrainer`  uses `LinearBinaryModelParameters`  . 

However, whenever possible we should string to align the names. 

Listing some of the trainers where we can fix this :
 
- MulticlassLogisticRegressionModelParameters
- BinaryClassificationGamModelParameters
- MultiClassNaiveBayesModelParameters

**Comment by abgoswam** [comment]
Update:
- To keep consistency between **Class** names of Trainers and ModelParameters,  we will **not** use the word "Classification"  in either the Trainer class or the  ModelParameter class

- We feel its OK to drop the word "Classification" for 2 main reasons : 
  - we have sufficient context  to just use **suffix**  :  BinaryTrainer ,  BinaryModelParameters etc. without using the word "Classification"
  - adding the word "Classification" leads to long names 

Here is a summary of the **Trainer** and **ModelParameter**  class names

| Updated Trainer Class Name |
| ------------------------ | 
| FastTreeBinaryTrainer   |
| FastTreeRegressionTrainer |
| FastTreeRankingTrainer |
| FastTreeTweedieTrainer |
| FastForestRegressionTrainer   |
| FastForestBinaryTrainer  |
| MatrixFactorizationTrainer | 
| GamBinaryTrainer |
| GamRegressionTrainer |
| LogisticRegressionBinaryTrainer |
| LogisticRegressionMulticlassTrainer |  
| AveragedPerceptronTrainer  |
| OnlineGradientDescentTrainer |
| PoissonRegressionTrainer |   
| KMeansTrainer |
| OlsTrainer |
| PriorTrainer |
| PairwiseCouplingTrainer |
| OneVersusAllTrainer | 
| NaiveBayesMulticlassTrainer |
| SgdCalibratedTrainer |
| SgdNonCalibratedTrainer |
| FieldAwareFactorizationMachineTrainer |
| SymbolicSgdTrainer  |
| LightGbmRegressionTrainer |
| LightGbmBinaryTrainer |
| LightGbmRankingTrainer |
| LightGbmMulticlassTrainer |
| LinearSvmTrainer  |
| RandomizedPcaTrainer |
| SdcaCalibratedBinaryTrainer |
| SdcaNonCalibratedBinaryTrainer |
| SdcaMulticlassTrainer  |
| SdcaRegressionTrainer | 
| SdcaTrainerBase | 
| LbfgsTrainerBase |
| GamTrainerBase  |




| Updated ModelParameter Class Name |
| ------------------------------------------ |
| GamBinaryModelParameters |
| GamRegressionModelParameters |
| LightGbmBinaryModelParameters |
| LightGbmRankingModelParameters |
| LightGbmRegressionModelParameters |
| FastTreeBinaryModelParameters |
| FastTreeRegressionModelParameters |
| FastTreeRankingModelParameters |
| FastTreeTweedieModelParameters |
| FastForestBinaryModelParameters |
| FastForestRegressionModelParameters |
| NaiveBayesMulticlassModelParameters |
| OlsModelParameters  |
| OlsLinearRegressionModelParameters | 
| PcaModelParameters |
| FieldAwareFactorizationMachineModelParameters |
| KMeansModelParameters |
| PoissonRegressionModelParameters |
| MatrixFactorizationModelParameters |
| OneVersusAllModelParameters |
| PairwiseCouplingModelParameters |
| PriorModelParameters |
| LinearRegressionModelParameters |
| RegressionModelParameters |
| LinearBinaryModelParameters |
| CalibratedModelParametersBase |
| GamModelParametersBase |
| TreeEnsembleModelParameters | 
| TreeEnsembleModelParametersBasedOnQuantileRegressionTree |
| TreeEnsembleModelParametersBasedOnRegressionTree |

**Comment by wschin** [comment]
For multi-class LR trainer and its model, we have different names now. Looks like they don't need `multiclass`.
- (rename) LogisticRegressionMulticlassClassificationTrainer ---> LbfgsMaximumEntropyTrainer
- (rename) MulticlassLogisticRegressionModelParameters ---> MaximumEntropyModelParameters
