### ISSUE TITLE
need documentation: handling varvect

### ISSUE THREAD

**Issue by fabsenet** [dotnet/machinelearning#2940]
### System information

- windows 10, fast ring
- .net 4.7.1

### Issue

- **What did you do?**
i have a data input class:
```cs
        class NightLightDataRow
        {
            public bool IsActive { get; }
            public byte[] Data { get; }

            [Microsoft.ML.Data.VectorType(38)]
            public float[] Data2 { get; }

            public NightLightDataRow() {}

            public NightLightDataRow(byte[] data, bool isActive)
            {
                Data = data;
                Data2 = Data.Select(d => (float)d).Take(38).ToArray();
                IsActive = isActive;
            }
        }
```

I train it using `mlContext.BinaryClassification.Trainers.StochasticDualCoordinateAscent`.

I got it somehow working using `Data2`, but my real data are `Data` and have 38..43 elements. If I try to train it on that directly, it throws with

> System.ArgumentOutOfRangeException: 'Schema mismatch for feature column 'Data': expected Vector<R4>, got VarVector<R4>
Parametername: inputSchema'`

this is the pipeline:

```cs
var trainingPipeLine = 
                mlContext.Transforms.Conversion.ConvertType("Data")
                .AppendCacheCheckpoint(mlContext)
                .Append(
                mlContext.BinaryClassification.Trainers.StochasticDualCoordinateAscent(
                            labelColumnName: nameof(NightLightDataRow.IsActive)
                            , featureColumnName: nameof(NightLightDataRow.Data)
                            ));
```

I understand why it is throwing, but I have no idea how to fix it. What could I do and what would be the correct piece of documentation?

Also as a side question: how do I start my trainingPipeline with a CacheCheckpoint? (If i would want to do cache=>StochasticDualCoordinateAscent directly without any transforms)

**Comment by TomFinley** [comment]
Hi @fabsenet, thanks for your question.

Without knowledge about what that `Data` is, it's difficult to me to say how you should be preparing it. I can at least tell you what SDCA will do with your `Data2` composed of 38 floats ... it will fit a separate coefficient for each of the 38, and the predictions will encode it. Whether that's appropriate for your problem, I doubt -- usually when people have variable sized `byte[]` vectors incoming, they're usually structured in *some way*. But knowing as I do nothing about it, I can't really give specific advice on which of our transforms (if any) would be able to help you with that. If you described it a bit more I might be able to help a bit more.

Your second question about caching is a bit more straightforward. The `AppendCacheCheckpoint` is a convenience for when you're forming a pipeline. You seem to have no interest in forming a pipeline, so I'd just use the `Cache` utility directly.

https://github.com/dotnet/machinelearning/blob/b455174cb848be054f8a800dbe76e7deb28c699e/docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/Cache.cs#L24

`AppendCacheCheckpoint` is used for something else: sometimes you want to apply some data transformation operations, *then* cache prior to an especially data intensive operation (like learning a machine learning model), *then* continue the pipeline. Prior to that utility existing our advice was, you'd do `Fit`/`Transform` on all operations prior to whenever you wanted to cache, then apply the `Cache` utility method, then continue by doing `Fit`/`Transform` on the remaining data. But this scenario was common enough that we decided it was helpful to have this convenience utility.

But in your case, that situation does not apply. You can just use `Cache` directly, as in the sample linked above.

I hasten to point out that depending on the source of your data, `Cache` may be pointless: if it comes from, say, a `List<NightLightDataRow>` or an array `NightLightDataRow[]`, for example, it's already in memory. No benefit to caching then. On the other hand if it was coming from, say, examples read off disk, or cursoring over a database, then there may be benefit to caching. You'll know your situation best, so I'll leave you to experiment and judge.

**Comment by fabsenet** [comment]
Okay I got the caching usage, thanks for the link. After using the ml.net api for a day, it feels so different from starting a pipeline to appending to it. Just some feedback I guess.

The data is actually taken from the windows registry and contains the current state of the night light feature of windows ([source](https://stackoverflow.com/a/43953978/513213)). I am interested in whether it is on or off, so BinaryClassification makes sense to me. The data might be encoded with some special Microsoft encoding where you have to know the structure in advance but the structure is not publicly documented. That is why I thought, it might be possible to just use this as an excuse to dive into machine learning.
 
So it would make sense to me, to preprocess them to represent each individual bit. On the other hand Data2 yielded a working result so for the start, I would like to know how to transform this VarVect to a Vect of either the first 38 values or 43 values where shorter arrays are filled with zeros or some markers. How does StochasticDualCoordinateAscent decide on the number of neurons and layers and so on? Or actually, it does not use nerons at all?

I really do not want to take **your** time to solve **my** task. What I really miss is some guidance to work through so I know myself what would be right here?! Yes there is documentation for all classes but it does not feel helpful at all.

**Comment by fabsenet** [comment]
how am I supposed to learn about the ML.net data types and the existing transformation? I think you miss the **learn** part on the project website?

**Comment by fabsenet** [comment]
sad
