### ISSUE TITLE
Unity 3d Compatiblity

### ISSUE THREAD

**Issue by paulallenbright** [dotnet/machinelearning#2941]
### System information
Windows Development Unity project
4.x or standard 2.x

### Issue
Can you make a future release compatible with the latest version of Unity 3D.   Now that Unity 3d supports framework 4.x and .net standard 2.0 this would be a great platform to build the next generation of ml.net applications.

https://unity3d.com/

Unity projects now supports Nuget for package pull down:

https://github.com/GlitchEnzo/NuGetForUnity

Thank you so much for taking the time to consider this new compatibility feature

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by singlis** [comment]
Hi @paulallenbright, 

Thank you for opening this issue.

ML.NET does support .NET Standard 2.0 and we have a HelloMLNet application that demonstrates the Unity integration (see #1886 for more information)
https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/Unity-HelloMLNET

Does this help? Or do you have something specific in mind?

@asthana86  and @eerhardt

**Comment by paulallenbright** [comment]
thanks.. however that project will not run out of the box on a pull down.
This does NOT work...

[image: image.png]

**Comment by paulallenbright** [comment]
[image: image.png]
Downloading and bringing the project into unity.. latest version gives you
this when trying to run it..   It does not work out of the box...

Assembly 'Assets/Plugins/Microsoft.ML.Data.dll' will not be loaded due to
errors:
Unable to resolve reference 'System.Threading.Tasks.Dataflow'. Is the
assembly missing or incompatible with the current platform?

Assembly 'Assets/Plugins/Microsoft.ML.Ensemble.dll' will not be loaded due
to errors:
Reference has errors 'Microsoft.ML.Data'.

Assembly 'Assets/Plugins/Microsoft.ML.FastTree.dll' will not be loaded due
to errors:
Reference has errors 'Microsoft.ML.Data'.

Assembly 'Assets/Plugins/Microsoft.ML.KMeansClustering.dll' will not be
loaded due to errors:
Reference has errors 'Microsoft.ML.Data'.

Assembly 'Assets/Plugins/Microsoft.ML.PCA.dll' will not be loaded due to
errors:
Reference has errors 'Microsoft.ML.Data'.

Assembly 'Assets/Plugins/Microsoft.ML.ResultProcessor.dll' will not be
loaded due to errors:
Reference has errors 'Microsoft.ML.Data'.

Assembly 'Assets/Plugins/Microsoft.ML.SamplesUtils.dll' will not be loaded
due to errors:
Reference has errors 'Microsoft.ML.Data'.

Assembly 'Assets/Plugins/Microsoft.ML.StandardLearners.dll' will not be
loaded due to errors:
Reference has errors 'Microsoft.ML.Data'.

Assembly 'Assets/Plugins/Microsoft.ML.Sweeper.dll' will not be loaded due
to errors:
Unable to resolve reference 'System.Threading.Tasks.Dataflow'. Is the
assembly missing or incompatible with the current platform?

Assembly 'Assets/Plugins/Microsoft.ML.Transforms.dll' will not be loaded
due to errors:
Reference has errors 'Microsoft.ML.Data'.

**Comment by EricIsInTheHausCAP** [comment]
Has this issue been resolved or is it still being worked on?

**Comment by mstfbl** [comment]
Closing this issue as no further updates on the issue have been given. @paulallenbright feel free to reopen the issue if you can provide more information. Thanks.

**Comment by justinvirtualitics** [comment]
Has anyone made any progress on this issue? I am encountering the same errors as above on Unity 2019.3.15f1.
