### ISSUE TITLE
Create the Binary Classification With Array float values

### ISSUE THREAD

**Issue by vrjesus** [dotnet/machinelearning#2952]
### Binary classification

I want create a Machine Learning, but I need use a vector (array) of floats values (through of a sensor). My question is this, each value must be a Column or I must create a single Column with all values separate with a the comma?

**Comment by rogancarr** [comment]
@vrjesus You can keep your data as an array of floats. You can define a class with a float array and read them into an `IDataView`.

Define a class like this:
```cs
public class MyClass
{
   public float[] MyVector {get; set;}
}
```

and read it from an `Enumerable` like this:
```cs
var mlContext = new MLContext(seed: 1);
var data = mlContext.Data.LoadFromEnumerable<MyClass>(myStream);
```
If you have data in a text file, you can look at [this sample](https://github.com/dotnet/machinelearning/blob/master/test/Microsoft.ML.Functional.Tests/Datasets/TypeTestData.cs) for how to specify the class such that you can read it in with `mlContext.Data.LoadFromTextFile<MyClass>`.

**Comment by singlis** [comment]
@vrjesus  I am closing this issue. If this is not resolved, please re-open.
