### ISSUE TITLE
The samples that are part of the Microsoft.ML.Samples project need to have a corresponding baseline test

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#2954]
The samples currently have compile time checks, by being part of the solution, but not runtime validation. 
Create a baseline test for each sample, to verify the output of their execution has not changed.

**Comment by shmoradims** [comment]
At the very lease we should make sure they samples are runnable. Full blown baseline might be too costly. We already have those for unit tests.

**Comment by codemzs** [comment]
@sfilipi As per our conversation at lunch, I'm assigning this to myself.

**Comment by sfilipi** [comment]
@codemzs i think this is complete? should we reference the PR and close it?

**Comment by najeeb-kazmi** [comment]
Closed in #3309. Created a stand alone app that will run all samples.
