### ISSUE TITLE
Move IDataView into Microsoft.ML namespace

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#2974]
We've received feedback that having `IDataView` in the `Microsoft.Data` namespace (which was done in #2220) is confusing to users. Traditionally, the `System.Data` namespace has been populated with "database" specific technologies. `Microsoft.Data` isn't all that different from `System.Data`, and one could argue they are basically the "same thing", with the `System.Data` technologies being inside of the BCL and/or `netstandard` definition while `Microsoft.Data` being built outside of the BCL/`netstandard` definition. There are already "database" specific APIs in `Microsoft.Data`, for example https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqlite.

`System.Data` even already has a [`DataView` class](https://docs.microsoft.com/en-us/dotnet/api/system.data.dataview), and `IDataView` and `DataView` are drastically different.

To solve this confusion, we should rename the `Microsoft.Data.DataView` NuGet package to `Microsoft.ML.DataView` and move the `Microsoft.Data.DataView` namespace under `Microsoft.ML`. The NuGet package will still be separated from the algorithms and transforms in the larger `Microsoft.ML` NuGet package. So the value of #1860 can still be realized. The separate package will just be branded `ML` instead of `Data`.

/cc @TomFinley @shauheen @markusweimer @glebuk

**Comment by eerhardt** [comment]
With solving this, I think it would be safe to reconcile one more issue: the separation of the base DataViewTypes (like `Int32`, `Single`, etc) and the `Vector` and `Key` types that happened with #2220. Since all the types are under `Microsoft.ML`, it doesn't make sense for these types to be separated anymore. We can bring `VectorType` and `KeyType` into the same assembly as the base DataViewTypes.

Note: this means that `VBuffer` would also need to come with, since `VectorType` has a hard reference to `VBuffer`.

**Comment by markusweimer** [comment]
@shauheen Shall we make this part of Project 13? This seems like the sort of thing we must solve before 1.0.

**Comment by shauheen** [comment]
Should this proceed as proposed it certainly will be Project 13.
