### ISSUE TITLE
Public API for SchemaDefinition class

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#2978]
There are no samples/tests in the code that make use of this class, even though it is part of the public API.

**Comment by yaeldekel** [comment]
Also, I think this class should be cleaned up. For example:
The property `IsComputed` - should it be internalized/removed?
The property `ReturnType` - looks like it should be internal.
`GetAnnotationTypes` is a property, so should be renamed.

**Comment by TomFinley** [comment]
Yes, I agree with that strongly... we previously used it I think for two purposes, this before we were writing ML.NET, one was something for the user to "talk to" to tell it what it wanted done, the second was for the `PredictionEngine` itself to inspect to figure out what should be done, and I don't think we were, at the time, *terribly* discriminating about whether something was in the public or internal surface w.r.t. "external" and "interface" code.

**Comment by singlis** [comment]
@yaeldekel this sounds like multiple issues relating to API, documentation and tests. Want me to create an issue for each case?

**Comment by yaeldekel** [comment]
Hi @singlis , yes, that would be great. I already have a PR for cleaning up the API for this class that references this issue, so adding an issue for doc/samples is a great idea.
