### ISSUE TITLE
It would be helpful to have a ML.NET symbol package 

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#298]
For debugging, it would be great to publish symbol package.

**Comment by Ivanidzo4ka** [comment]
We have them. But for some reason myget contains only 0.2.0-preview, while I can see 0.3.0.-preview for Microsoft.ML. Did we need to update something in our build system @eerhardt ? 
I also don't see Microsoft.ML.Parquet.symbols in myget.

**Comment by eerhardt** [comment]
In our offiical builds, we use the symbols package that we produce to upload the symbols to the "Microsoft Symbol Servers" (checkbox in VS -> Tools -> Options -> Debugging -> Symbols).  It was an accident that we published a few versions to myget.  I'll take them down.

If you are looking for the direct URL to the symbols, you can find them at: https://msdl.microsoft.com/download/symbols

**Comment by sfilipi** [comment]
thanks @eerhardt
