### ISSUE TITLE
Cannot fit an Onnx Transform as part of a pipeline

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#2981]
It is possible to fit an ONNX model by itself:

```cs
var onnxEstimator = mlContext.Transforms.ApplyOnnxModel(modelPath)
var onnxModel = onnxEstimator.Fit(data);
```

But it throws when it is part of a pipeline:
```cs
var onnxEstimator = mlContext.Transforms.ApplyOnnxModel(modelPath)
    // TODO #2980: ONNX outputs don't match the outputs of the model, so we must hand-correct this for now.
    .Append(mlContext.Transforms.CopyColumns("Score", "Score0"));
    .Append(mlContext.Transforms.CopyColumns("Label", "Fable"));
    .Append(mlContext.Transforms.NormalizeLpNorm("Features2", "Features", LpNormNormalizingEstimatorBase.NormFunction.L2));
var onnxModel = onnxEstimator.Fit(data);
```
Any of these `Append` statements cause a throw. They do not affect the ONNX model at all, and use either the result of the calculation (`Score0`), rows unused by the model (`Label`) or rows also used by the transform (`Features`).

In this case, the error message is:
`System.ArgumentOutOfRangeException : Schema mismatch for input column 'Label': expected vector, got R4
Parameter name: inputSchema`

**Comment by rogancarr** [comment]
Must be related to #2982, that the type changes when passed through ONNX.

**Comment by singlis** [comment]
Based on #2982 and #2980, I was able to get this to work by specifying a custom score class: 
```
    internal sealed class OnnxScoreColumn
    {
        [ColumnName("Score0")]
        public float[] Score { get; set; }
    }
...

var onnxPredictionEngine = mlContext.Model.CreatePredictionEngine<HousingRegression, OnnxScoreColumn>(onnxModel);
```

@rogancarr  - I will post a PR with the changes and then close these three issues.

**Comment by singlis** [comment]
@rogancarr  - sorry I misunderstood the bug. I see what you are describing and will post a fix.
