### ISSUE TITLE
ONNX Transform changes output types

### ISSUE THREAD

**Issue by rogancarr** [dotnet/machinelearning#2982]
Serializing and deserializing a model to and from ONNX not only changes the names of the output (#2980) but also changes the types of the output. For example, a `Score` column produced by a model (`R4`/`float`) becomes a `Vec<R4, 1, 1>`.

**Comment by singlis** [comment]
See #2980, this is also by design as ONNX does deal with vector types and will create a float[1] for a ML.Net floating point output.

**Comment by rogancarr** [comment]
Thanks for investigating @singlis ! I'll close the issue now. We can just add a comments to the text and samples so that people will know what to expect.
