### ISSUE TITLE
Add MLContext.Model.Load overload that takes a file path

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#2983]
Today, the only way to load a model is by using a `Stream`:

https://github.com/dotnet/machinelearning/blob/e2464f606c69357898572aac8e4d8d3c1451c92f/src/Microsoft.ML.Data/Model/ModelOperationsCatalog.cs#L36-L41

We should add an overload that takes a `string filePath` as a convenience API over top of this. That way all the callers don't need to open a `FileStream` and dispose of it, etc, just to load a model.

@TomFinley @CESARDELATORRE @sfilipi @shauheen

**Comment by codemzs** [comment]
You have my full support!

**Comment by CESARDELATORRE** [comment]
And of course you have my full support, too. :)
I opened an issue related to this topic in Nov. 2018:

https://github.com/dotnet/machinelearning/issues/1689

 This change will make the code a lot cleaner! 
:)

**Comment by glebuk** [comment]
Sounds great.   Also todo in this issue:
- Ensure to make save and load symmetrical
- Update samples to use the overload when loading/saving from file.
