### ISSUE TITLE
Macro outputs should not be required

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#299]
### System information

- windows
- version 0.3.0-preview-26604-1 

### Issue
The CV macro outputs (and any graph outputs) should not be mandatory. 
Currently the CV macro is not checking for presence of the metrics, before  adding the metrics node to the outputs, and throwing if they are missing. 

I don't think any output should be required, and especially some metrics like 'Confusion Matrix' don't make sense for every kinds of task. 

To reproduce, compose an entry points graph with the CV  macro present, and don't specify outputs for it. Run this graph. 
### Source code / logs

{System.InvalidOperationException: Invalid parameter 'ConfusionMatrix': parameter does not exist.
   at Microsoft.ML.Runtime.EntryPoints.EntryPointNode.GetOutputVariableName(String paramName)
   at Microsoft.ML.Runtime.EntryPoints.CrossValidationMacro.CrossValidate(IHostEnvironment env, Arguments input, EntryPointNode node)}

**Comment by Zruty0** [comment]
We are not planning to maintain the CV macro (or other macros). So, closing this.
