### ISSUE TITLE
Perf: Optimization for MatrixFactorization

### ISSUE THREAD

**Issue by glebuk** [dotnet/machinelearning#3001]
Benchmarking using VTune has found several bottlenecks in Matrix Factorization training algorithm.
-Experiment to find potential gain with AVX & SSE & Intrinsics  in matrixfactorizationnative.dll module
-Based on result of above experiment, take a look at implementing this in the product [fat binary vs dynamic dispatch]

**Comment by wschin** [comment]
Matrix factorization itself has SSE and AVX. I believe enabling this feature might not cost a lot.

**Comment by wschin** [comment]
We have been compiling matrix factorization with OpenMP and SSE, so I think this issue can be closed.
