### ISSUE TITLE
Enum Name --- OneHotEncodingEstimator.OutputKind

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#3005]
I personally prefer `OneHotEncodingEstimator.Representation` than `OneHotEncodingEstimator.OutputKind`. @sfilipi, @TomFinley, @rogancarr, any comment please?

**Comment by sfilipi** [comment]
No strong opinion. Representation sounds good to me.

**Comment by rogancarr** [comment]
+1 for `Representation`

**Comment by artidoro** [comment]
We have already released so we cannot make changes to this at this point.
