### ISSUE TITLE
Can't find the constructor for MulticlassClassificationTrainers(ctx) (v0.10)

### ISSUE THREAD

**Issue by rudi3999** [dotnet/machinelearning#3009]
Hello 

where is the constructor for a call like:

var sdcaContext = new MulticlassClassificationCatalog(ctx);

been moved in 0.11?

**Comment by sfilipi** [comment]
Thanks for asking, @rudi3999. 
The API has been rapidly changing this past months, but we're reaching code-complete next week, and it should be a lot more stable. 
The constructors for the tasks can be accessed directly through MLContext. 

Instantiate MLContext once, for your program, and that should help you access the rest. 
Small pipeline example. 

`var estimator = mlContext.Transforms.Categorical.MapValueToKey("Label")
    .Append(mlContext.MulticlassClassification.Trainers.Sdca())
    .Append(mlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel"));
`

The cookbook might be a good doc to skim through, for concepts and how's this shaping. 
https://github.com/dotnet/machinelearning/blob/master/docs/code/MlNetCookBook.md

**Comment by rudi3999** [comment]
Thank you Senja,

with a call to:
var sdcaContext = ctx.MulticlassClassification.Trainers.StochasticDualCoordinateAscent();
it worked, but then the call to: sdcaContext.Evaluate(trainData,...) isn't found anymore (worked in v0.10)

**Comment by sfilipi** [comment]
Closing since the question got answered.
