### ISSUE TITLE
The "Binary" in "LogisticRegressionBInaryTrainer" Looks Redundant

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#3016]
As title. Logistic regression is clearly a binary classifier, so we can consider dropping "Binary" among "LogisticRegressionBinaryTrainer". In addition, as L-BFGS is outperformed by SDCA and SymSGD, I feel we should not call this class `LogisticRegressionTrainer`. A suggested solution is to prepend `Lbfgs` to this class' name.

**Comment by sfilipi** [comment]
I would suggest to make an exception and leave the Binary in the name of LR for two reasons:
1- The userbase is not proficient in ML. I think the "regression" on the trainer name might easily confuse people. 
2- We have MulticlassLR

**Comment by wschin** [comment]
> I would suggest to make an exception and leave the Binary in the name of LR for two reasons:
> 1- The userbase is not proficient in ML. I think the "regression" on the trainer name might easily confuse people.
If someone doesn't know LR is a binary classifier, I don't think they can use `LogisticRegressionBinaryTrainer` properly.
> 2- We have MulticlassLR
Not anymore. We have LbfgsMaximumEntropyTrainer now.

**Comment by rogancarr** [comment]
So what do we have?

*binary*
`LogisticRegressionBinaryTrainer`
*multiclass*
`LogisticRegression`
`MulticlassLogisticRegression`
(yes, two!)
*regression*
`PoissonRegression`

First, we should only have _one_ name for multiclass.

Second, I think that `LogisticRegression` is clearly binary classification. It's one of the most standard names out there.

Third, I'm even okay with `LogisticRegression` as the name for the multiclass version.

Fourth, I think that `PoissonRegression` should stay as-is.

**Comment by rogancarr** [comment]
`LbfgsMaximumEntropyTrainer` is fine for the multiclass version, but it *does* seem a bit technical. Are we sure the trainer catalog has this name, and not just the internal classes?

**Comment by artidoro** [comment]
I would prefer that we stick to the name `LogisticRegression`. 

I also agree with @sfilipi that probably it's a good idea to keep Binary in the end of `LogisticRegressionBinaryTrainer` so that people don't get confused on whether it is a regression task.

I would settle for `LbfgsLogisticRegressionBinaryTrainer`. We have longer names in other parts of the code base and this has all the characteristics that we need if I am not wrong.

**Comment by eerhardt** [comment]
Adding to Project 13 to track as this is an API breaking request.

**Comment by TomFinley** [comment]
To be honest I am somewhat skeptical about renaming it. To be honest, when I was a new PhD student just learning about machine learning for the first time, I was earnestly confused about the fact the logistic *regression* had nothing to do with regression (as elsewhere defined), but binary classification.

**Comment by glebuk** [comment]
Note that if we rename LR to LbfgsLogisticRegression, then perhaps we should consider also SymSGD and SDCA as they also can do LR, I believe.

**Comment by wschin** [comment]
@TomFinley, I am ok with `LbfgsLogisticRegressionBinary` the part I want to most is `Lbfgs` because L-BFGS doesn't look like the default trainer of logistic regression (we should use SDCA or SymSGD).

@glebuk, I will try to rename them and possibly drop `Calibrated` or `NonCalibrated` in trainer APIs. But if I feel it causes more confusions, I might skip this.

**Comment by rogancarr** [comment]
@wschin @abgoswam Would one of you mind putting the results of the offline conversation in this Issue? Then we can close on the PR.

**Comment by wschin** [comment]
@rogancarr, sure!

API name changes:
LogisticRegression --> LbfgsLogisticRegression
SymbolicSgd --> SymbolicSgdLogisticRegression
LogisticRegression --> LbfgsLogisticRegression
PoissonRegression --> LbfgsPoissonRegression
SdcaCalibrated --> SdcaLogisticRegression
SdcaCalibrated ---> SdcaMaximumEntropy

Trainer classes' name changes:
LbfgsLogisticRegressionTrainer ---> LbfgsLogisticRegressionBinaryTrainer
LbfgsMaximumEntropyTrainer ---> LbfgsMaximumEntropyMulticlassTrainer
SymbolicSgdTrainer --> SymbolicSgdLogisticRegressionBinaryTrainer
SdcaCalibratedBinaryTrainer => SdcaLogisticRegressionBinaryTrainer
SdcaCalibratedMulticlassTrainer => SdcaMaximumEntropyMulticlassTrainer
SdcaMulticlassClassificationTrainerBase => SdcaMulticlassTrainerBase
MetaMulticlassClassificationTrainer => MetaMulticlassTrainer
