### ISSUE TITLE
Enable setting NormalizingEstimator options

### ISSUE THREAD

**Issue by artidoro** [dotnet/machinelearning#3047]
In PR #2959 we hid the NormalizingEstimator `ColumnOptions`. Currently users cannot set advanced parameters for the estimator.

The reason for not doing that was that `NormalizingEstimator` has 5 `ColumnOptions` classes and would have required at least that many overloads. So we opted for **waiting for the full `Options`** object to be made accessible and make sure that **no breaking API change** was going to be required. 

However, as per further discussion in #2884 and offline we decided that we would not make `Options` available before v1. We therefore need another solution.

One possible approach would be to add five new extensions to MLContext each presenting all the settings in one of the NormalizingEstiamtor `ColumnOptions`. The extensions could indicate in their name the type of normalization to perform.

Note that this is not a breaking API change.

**Comment by abgoswam** [comment]
It seems to expose the advanced settings for each of the 5  normalizing estimators we have {MinMax, MeanVariance, LogMeanVariance, Binning, SupervisedBinning}  we need to add  5 APIs  to our public surface  as shown in PR #3052 

Adding these APIs will also enable to scenario @codemzs highlighted,  whereby currently users of ML.NET have no way to set the advanced options for the individual normalizing estimators

@shauheen , @TomFinley  should we consider adding these for V1.0 ?

**Comment by artidoro** [comment]
Note that `NormalizingEstimator` is on the list of transforms specified by @TomFinley  in https://github.com/dotnet/machinelearning/issues/2884#issuecomment-475066720 where we should enable multi-column mapping. If we do that, we need to double the number of new extensions. 

From 5 we would now go to 10 new extensions.

**Comment by TomFinley** [comment]
> Note that `NormalizingEstimator` is on the list of transforms specified by @TomFinley in [#2884 (comment)](https://github.com/dotnet/machinelearning/issues/2884#issuecomment-475066720) where we should enable multi-column mapping. If we do that, we need to double the number of new extensions.
> 
> From 5 we would now go to 10 new extensions.

I'm honestly less convinced of that than you all are, since you can always concatenate *then* normalize (and it's probably clearer to do so).
