### ISSUE TITLE
CSharpApiGenerator doesn't assign default values to Optional<> type.

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#305]
The code generated for an argument that is defined as
string LabelColumn = "Label";

is:
            /// <summary>
            /// Column to use for labels
            /// </summary>
            public string LabelColumn { get; set; } = "Label";

but the code generate for an argument that is defined as
public Optional<string> GroupColumn = Optional<string>.Implicit("GroupId");

is:

            /// <summary>
            /// Column to use for grouping
            /// </summary>
            public Microsoft.ML.Runtime.EntryPoints.Optional<string> GroupColumn { get; set; }

**Comment by Ivanidzo4ka** [comment]
I can enable that, but as soon as I do it, bunch of test starts to fail with expected column not found. It looks like currently we don't have code which would handle absence of optional column

**Comment by shauheen** [comment]
@yaeldekel is this issue resolved?
