### ISSUE TITLE
Add code analyzer support for IDataView Preview method

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#3057]
We should write a code analyzer that checks to see if people are calling the `IDataView.Preview()` extension method, and if so it gives them an error/warning to not do that. It is only for debugging purposes.

@TomFinley @shauheen

**Comment by TomFinley** [comment]
This seems related to #2977.

**Comment by eerhardt** [comment]
This is a dupe of #2977. Closing.
