### ISSUE TITLE
Simple model error, conflicting annotations should cause an error or work

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/machinelearning#3065]
### System information

- **Windows 10 64 bit**:
- **.NET 3.0. ML.Net 0.11**: 

### Issue

- **What did you do?**
Loaded Textfile with label and array of float values

```
var dataView = mlContext.Data.LoadFromTextFile<DataBase>(trainingFile.FullName, separatorChar: '|', hasHeader: false);
var dataset = mlContext.MulticlassClassification.TrainTestSplit(dataView, testFraction: 0.1);

var pipeline = mlContext.Transforms.Conversion.MapValueToKey(nameof(DataBase.Label),sort:ValueToKeyMappingEstimator.SortOrder.Value)
                    .Append(mlContext.Transforms.Normalize(new NormalizingEstimator.SupervisedBinningColumOptions(inputColumnName: nameof(DataBase.Features), outputColumnName: DefaultColumnNames.Features)))
                    .Append(mlContext.MulticlassClassification.Trainers.StochasticDualCoordinateAscent(labelColumnName: DefaultColumnNames.Label, featureColumnName: DefaultColumnNames.Features))
                    .Append(mlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel"));



//crashes here
var model = pipeline.Fit(dataset.TrainSet);
var predictions = model.Transform(dataset.TestSet);
metrics = mlContext.MulticlassClassification.Evaluate(predictions,DefaultColumnNames.Label,DefaultColumnNames.Score);
[Sample.zip](https://github.com/dotnet/machinelearning/files/2997016/Sample.zip)

```

- **What happened?**
Got error: Schema mismatch for feature column 'Features': expected Vector<R4>, got R4
Parameter name: inputSchema
- **What did you expect?**
No error as my class is a vector of float  

### Source code / logs
```
    public class DataBase
    {
        [LoadColumn(0)]     
        public string Label { get; set; }

         //error in column definition
        [LoadColumn(1),VectorType(220)]  
        public float[] Features { get; set; }

        public DataBase()
        {
            Features = new float[220];
        }
    }
```

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by sfilipi** [comment]
Hi @PeterPann23 

I just tried the example you provided with some random data, and using ML.Net 0.11 it is working fine. 
What version are you using? Can you inspect that your data is loaded correctly, using the dataView .Preview()?

Also can you inspect the train and test splits, make sure they have data in them etc?

This is my working example:

```

    public class DataBase
    {
        [LoadColumn(0)]
        public string Label { get; set; }

        [LoadColumn(1), VectorType(4)]
        public float[] Features { get; set; }

        public DataBase()
        {
            Features = new float[4];
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            MLContext mlContext = new MLContext();
            var examples = new List<DataBase>()
            {
                 new DataBase(){ Label = "TMN", Features = new float[] {0,1,2,3 } },
                 new DataBase(){ Label = "LKM", Features = new float[] {11, 12, 13, 14 } },
                 new DataBase(){ Label = "TMN", Features = new float[] {0,1,2,3 } },
                 new DataBase(){ Label = "TMN", Features = new float[] {3, 4, 5, 6 } },
                 new DataBase(){ Label = "LKM", Features = new float[] {11, 12, 13, 14 } },
            };



            // Convert the examples list to an IDataView object, which is consumable by ML.NET API.
            var dataView = mlContext.Data.LoadFromEnumerable(examples);

            var pipeline = mlContext.Transforms.Conversion.MapValueToKey(nameof(DataBase.Label), sort: ValueToKeyMappingEstimator.SortOrder.Value)
                     .Append(mlContext.Transforms.Normalize(new NormalizingEstimator.SupervisedBinningColumOptions(inputColumnName: nameof(DataBase.Features), outputColumnName: DefaultColumnNames.Features)))
                     .Append(mlContext.MulticlassClassification.Trainers.StochasticDualCoordinateAscent(labelColumnName: "Label", featureColumnName: "Features", maxIterations: 1))
                     .Append(mlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel"));

            var model = pipeline.Fit(dataView);
            var predictions = model.Transform(dataView);
            var metrics = mlContext.MulticlassClassification.Evaluate(predictions, "Label", "Score");

            // AccuracyMacro   0.5
            // AccuracyMicro   0.6
            // LogLoss 0.68826964211143549

            // LogLossReduction - 2.2671189594651149
            // TopK    0 
            // TopKAccuracy    0 
        }
}
```

**Comment by PeterPann23** [comment]
Hi 

I would expect that 
`[LoadColumn(1),VectorType(220)] `

would cause and error as it should be configured as
`[LoadColumn(1,221),VectorType(220)] `

when you load the file the code complains that it gets the above-mentioned error.
When having a vector type the load column should match the fields correct? I would generate a different error. at runtime, the mistake can obvious as it has a vector of N length and loads _one_ field in the file. 
Either it's a vector and has several fields or it's not... right?

**Comment by sfilipi** [comment]
Thanks for being more specific @PeterPann23. 

The LoadColumn attribute and the Vector attribute are orthogonal. 
if you specify a start and an end in the arguments of the LoadColumn, the data will be loaded in a vector/array; there is no need to add the additional Vector attribute. 

TBD for this issue: add the above information to the summary of the LoadColumn attribute. 
I am not sure if we should throw if the VectorType is also specified and the length does not match, that seem unnecessary to me. 

@eerhardt, @CESARDELATORRE what do you think?

**Comment by eerhardt** [comment]
I think throwing an exception in this case would probably make sense. The user did something wrong and we should let them know as soon as we can detect it.

**Comment by PeterPann23** [comment]
Hi,

I just noted another issue with the Loader, see error 1 in issue [3290](https://github.com/dotnet/machinelearning/issues/3290), I generated a training file with a label and a in the code that would look something like this. Works like a charm, trains then when it comes to creating the evaluator live becomes a problem and one needs to mess with the vector size as it looks like it takes the size based on the maximum field value from the LoadColumn definition as it's off by 1. 

I have included source code that allows you to reproduce the issue in 3190. them being similar and the 3190 having 2 bugs in 1 issue I thought perhaps to mention it here

 ```
       [LoadColumn(1,Featurizer.FEATURE_SIZE+1)]
        [VectorType(Featurizer.FEATURE_SIZE)]
        public float[] Features { get; }
```

**Comment by eerhardt** [comment]
@PeterPann23 - did you intend to close this issue?

**Comment by PeterPann23** [comment]
Not sure what to do with it however who is the owner of the issue?

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Eric Erhardt <notifications@github.com>
Gesendet: Monday, April 29, 2019 4:57:14 PM
An: dotnet/machinelearning
Cc: PeterPann23; Mention
Betreff: Re: [dotnet/machinelearning] Simple model error, conflicting annotations should cause an error or work (#3065)


@PeterPann23<https://github.com/PeterPann23> - did you intend to close this issue?
