### ISSUE TITLE
Schema comprehension in ML.NET needs more detailed document

### ISSUE THREAD

**Issue by 1amirjalai** [dotnet/machinelearning#3075]
Areas that need to be covered in schema comprehension in ML.NET

1. LoadFromEnumerable is not covered very well. for example how should huge amount of data be read from elasticsearh or sql ? 

- should that huge amount be converted to csv and then read it from csv using textloader?
- should all of that data be presented in the memory? for example write a code like this:
```
  var dataAsList = GetAllDataFromSQLAndPutItIntoAList();

  var trainingDataView= mlContext.Data.LoadFromEnumerable<dataType>(dataAsList);

  trainingDataView = mlContext.Data.Cache(trainingDataView);

  var pipeline = mlContext.Transforms.CreatePipeLine();

  ITransformer model = pipeline.Fit(trainingDataView);
```
[Microsoft doc](GetChurnInfo) has an sql example. should all the data be loaded into a list at GetChurnInfo()?

```
// Create a new context for ML.NET operations. It can be used for exception tracking and logging,
// as a catalog of available operations and as the source of randomness.
var mlContext = new MLContext();

// Step one: read the data as an IDataView.
// Let's assume that 'GetChurnData()' fetches and returns the training data from somewhere.
IEnumerable<CustomerChurnInfo> churnData = GetChurnInfo();

// Turn the data into the ML.NET data view.
// We can use CreateDataView or CreateStreamingDataView, depending on whether 'churnData' is an IList,
// or merely an IEnumerable.
var trainData = mlContext.Data.LoadFromEnumerable(churnData);
```

- is there any solution for large amounts of data that are not in text file format?

2. streaming data. as 

> CreateStreamingDataView 

is out dated so it should be replaced with new detail [here](https://github.com/dotnet/machinelearning/blob/master/docs/code/SchemaComprehension.md)

**Comment by shmoradims** [comment]
In ML.NET 1.0, we have the following APIs:
* [LoadFromEnumerable](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.dataoperationscatalog.loadfromenumerable?view=ml-dotnet#Microsoft_ML_DataOperationsCatalog_LoadFromEnumerable__1_System_Collections_Generic_IEnumerable___0__Microsoft_ML_Data_SchemaDefinition_) converts IEnumerable to IDataView
* [CreateEnumerable](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.dataoperationscatalog.createenumerable?view=ml-dotnet#Microsoft_ML_DataOperationsCatalog_CreateEnumerable__1_Microsoft_ML_IDataView_System_Boolean_System_Boolean_Microsoft_ML_Data_SchemaDefinition_) converts IDataView to IEnumerable.

Both links have an example. CreateDataView and CreateStreamingDataView are not public APIs anymore. For huge amount of data, as long as your data source gives you an IEnumerable of your data, you can use `LoadFromEnumerable()` to load the data. The loading is *lazy*, so it doesn't load the full data into memory. It streams the data during `Fit()`, so data size can be larger than memory. Most of the trainer examples, like [this](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.lightgbmextensions.lightgbm?view=ml-dotnet#Microsoft_ML_LightGbmExtensions_LightGbm_Microsoft_ML_BinaryClassificationCatalog_BinaryClassificationTrainers_Microsoft_ML_Trainers_LightGbm_LightGbmBinaryTrainer_Options_), use `LoadFromEnumerable()` so you can have a look at those also.

Closing the issue for now. If you still have questions, please reopen or start a new issue. Thanks.
