### ISSUE TITLE
Setting Epoch & Batch Size Hyper Parameters

### ISSUE THREAD

**Issue by matnatx** [dotnet/machinelearning#3076]
Hi,

Is there a way to set Hyper Parameters such as EPOCH numbers and Batch Size for the LogisticRegression Trainer? What is the default if these aren't set?

Thanks!

**Comment by sfilipi** [comment]
Hi @matnatx 

There are no epoch and batch size parameters for LogisticRegression. 
You can look at the options of LogisticRegression when you initialize the trainer:

```
     var trainer = mlContext.BinaryClassification.Trainers.LogisticRegression(
                new LogisticRegressionBinaryTrainer.Options {
                    NumberOfThreads = 1,
                    MaximumNumberOfIterations = int.MaxValue,
                    DenseOptimizer = false,
                    EnforceNonNegativity = false,
                    HistorySize = 10, 
                    L1Regularization = 1,
                    L2Regularization = 0.1f

                });
```

We are still working on our documentation, but those are some links that should help:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.logisticregression?view=ml-dotnet

https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.lbfgstrainerbase-3.optionsbase?view=ml-dotnet

**Comment by zeahmed** [comment]
@matnatx, the `LogisticRegression` trainer in ML.NET uses L-BFGS optimizer so there is no batch option. However, `MaximumNumberOfIterations` can be thought of equivalent to EPOCH. You will have to use the overloaded version of `LogisticRegression` API to use this parameter.

https://github.com/dotnet/machinelearning/blob/0a783206277618164ef432ba2439eda6c8d2b7b6/src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs#L539

**Comment by shmoradims** [comment]
In ML.NET 1.0, this trainer is renamed to `LbfgsLogisticRegression`. Please use [`LbfgsLogisticRegression(Options)`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.standardtrainerscatalog.lbfgslogisticregression?view=ml-dotnet#Microsoft_ML_StandardTrainersCatalog_LbfgsLogisticRegression_Microsoft_ML_BinaryClassificationCatalog_BinaryClassificationTrainers_Microsoft_ML_Trainers_LbfgsLogisticRegressionBinaryTrainer_Options_) to set `MaximumNumberOfIterations` in [`Options`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.lbfgslogisticregressionbinarytrainer.options?view=ml-dotnet). All the available options for are in that class.

Closing this issue for now. If you still have questions, please reopen this issue or create a new one. Thanks!
