### ISSUE TITLE
.NET Core OneHotEncoding Error

### ISSUE THREAD

**Issue by jappenzeller** [dotnet/machinelearning#3077]
### System information
.Net Core 2.1
Microsoft.ML v0.11.0

### Issue

OneHotEncoding that works in the non core version was fine.  Now I get a type error.
Preview of the data seems correct.

### Source code / logs
Relevant code snippets and error message.

Loader
new TextLoader.Column("RECORDTYPEID",DataKind.String,3),

Pipeline
.Append(mlContext.Transforms.Categorical.OneHotEncoding("RECORDTYPEID"))

.Append(mlContext.Transforms.Concatenate("Features",
...
"RECORDTYPEID",

Error Message on this line of code,
var model = pipeline.Fit(trainingDataView);

System.InvalidOperationException: 'Column 'RECORDTYPEID' has values of R4which is not the same as earlier observed type of R8.'

**Comment by sfilipi** [comment]
Hi @jappenzeller 

Thanks for reaching out. We are still working on making our error messages more user friendly. 
I believe the first column that you are passing to Concatenate might be a double, which set us the requirement to follow with doubles. Try changing those columns to float, as 'RECORDTYPEID' is and it should work. 

R4 is the internal name for float, and R8 for double. As i mentioned, those are getting streamlined.

**Comment by jappenzeller** [comment]
Yep, changing to DataKing.Single did the trick.  This got me a little confused as well since the .net core and .net standard enum names are not the same.

**Comment by sfilipi** [comment]
Good. Closing this issue then. Feel free to reopen, or open a new one for other issues.
