### ISSUE TITLE
Cannot access leaf nodes of trained trees

### ISSUE THREAD

**Issue by daholste** [dotnet/machinelearning#3083]
In this review https://github.com/dotnet/machinelearning/pull/2753, I notice the methods to traverse thru trained tree ensembles have been removed from the public API

@wschin @TomFinley 

I understand the logic for removing.

However, in our forked copy of SMAC, we require / have been using this functionality. Any advice on how to proceed?

**Comment by sfilipi** [comment]
@wschin  @abgoswam @TomFinley is this is good candidate for the Experimental nuget?

**Comment by TomFinley** [comment]
> @wschin @abgoswam @TomFinley is this is good candidate for the Experimental nuget?
> 
> cc @shauheen

I suppose, for the short term. In the more medium term, it looks like [this code](https://github.com/dotnet/machinelearning/blob/366332047340bdb12cf5fe2a11f9a6e257af9b84/src/Microsoft.ML.Sweeper/Algorithms/SmacSweeper.cs#L334-L350) is duplicating much of the same logic that exists in tree featurization, specifically, getting the leaf values for an example. Once we make tree featurziation part of the public API, then perhaps we could use that instead. (This would also probably simplify SMAC. I think SMAC's writing by @george-microsoft predates @yaeldekel's introduction of the tree featurizer, so presumably that was not an option at the time.)

Presumably we want tree featurization exposed in our public API at some point. It was a useful embedding. But, [currently it appears to adhere to the old `IDataTransform` idiom](https://github.com/dotnet/machinelearning/blob/366332047340bdb12cf5fe2a11f9a6e257af9b84/src/Microsoft.ML.FastTree/TreeEnsembleFeaturizer.cs#L483) (and so must be hidden), not the new `IEstimator`/`ITransformer` idioms.

**Comment by artidoro** [comment]
We have reintroduced the tree featurizer and we have an API to access the trained tree ensemble parameters (leaves and other things). See:
https://github.com/dotnet/machinelearning/blob/4fecfb200d270810b2f556e1f4fc0f349a606284/src/Microsoft.ML.FastTree/FastTree.cs#L3370

I am closing this issue, but feel free to reopen it in case we are still missing some functionality.
