### ISSUE TITLE
TextLoader is not identified

### ISSUE THREAD

**Issue by Amine-Smahi** [dotnet/machinelearning#309]
### System information
.NET Command Line Tools (2.1.200)

Product Information:
 Version:            2.1.200
 Commit SHA-1 hash:  2edba8d7f1

Runtime Environment:
 OS Name:     deepin
 OS Version:  15.5
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/amine-smahi/dotnet/sdk/2.1.200/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

### Issue

When following all Getting started with ML.NET guides or using the samples , i get a missing reference message saying that TextLoader is missing are you missing assemblies

### Source code / logs
for example 
`  var testData = new TextLoader<SentimentData>(_testDataPath, useHeader: true, separator: "tab"); `

**Comment by codemzs** [comment]
link to the getting started please? The Text Loader API has been changed and you can see an example [here](https://github.com/dotnet/machinelearning/blob/master/README.md)

**Comment by shauheen** [comment]
Thanks @Amine-Smahi for trying ML.NET on Linux, can you please let us know which version of the ML.NET nuget you are using? As @codemzs mentioned you can find the installation and example info in the readme.

**Comment by basvedder** [comment]
That link would probably be: 
https://www.microsoft.com/net/learn/apps/machine-learning-and-ai/ml-dotnet/get-started/windows

**Comment by codemzs** [comment]
Thanks, @basvedder ! Getting started page needs to be updated.

**Comment by Ivanidzo4ka** [comment]
DRI RESPONSE:
As far as I can see, starting page got updated with required code.
