### ISSUE TITLE
out of memory exception

### ISSUE THREAD

**Issue by 1amirjalai** [dotnet/machinelearning#3093]
I'm using fasttree to train my model but the program always crashes with the low on memory exception.
I have an hp dl380 gen 8 with 64gig of ram and 2x 2620 xenon and windows server 2016.
why the program crashes?
shouldn't it handles low on memory?
is there anything i can do so it limits memory usage?

**Comment by WaldiTUD** [comment]
Did you try [this](https://social.msdn.microsoft.com/Forums/vstudio/en-US/5850560d-a4a3-4cf5-be9e-b71026d1e175/systemoutofmemoryexception-array-dimensions-exceeded-supported-range-on-dataset?forum=vbgeneral)?

Check your Build Properties. "Prefer 32-bit" should be unchecked.

[link](https://stackoverflow.com/questions/8563933/c-sharp-out-of-memory-exception)

**Comment by 1amirjalai** [comment]
@WaldiTUD yes, it's a simple 64bit .net core app published for win64

**Comment by WaldiTUD** [comment]
I don't think, that it has to with ML.NET.

For .net Core you have to set the environment variable
[Try this](https://github.com/dotnet/coreclr/issues/8847)

Or try it with Framework

**Comment by sfilipi** [comment]
Hi @1amirjalai. 
How big is your dataset, how many features? 
What does the rest of the pipeline looks like?

It is hard to say where is the memory consumption from without more informations. 
If it is truly FastTree taking up a lot of memory you can try to turn on the DiskTranspose option. 

```
var ap2 = mlContext.BinaryClassification.Trainers.FastTree(new FastTreeBinaryTrainer.Options
{
   DiskTranspose = true
 });
```

**Comment by 1amirjalai** [comment]
@sfilipi 
How big ? it's not that big it's 4 gig csv file withe 132 feature.
What does the rest of the pipeline looks like? csv file features are all in the correct format so there is no need for further transformation only three features have textfeaturizing transformation.

Today i'm gonna reduce the features to see what will happen.

**Comment by mstfbl** [comment]
Closing this issue as no further updates on the issue have been given. @1amirjalai feel free to reopen the issue if you can provide more information. Thanks.

**Comment by Jahanaray** [comment]
this issue is happening for me too. sometimes by removing package from UWP project and installing again it work perfectly but other times it's really painful to get a build! Please fix it!
