### ISSUE TITLE
 var idv = mlContext.Data.LoadFromEnumerable(data); is not working in v0.11

### ISSUE THREAD

**Issue by prathyusha12345** [dotnet/machinelearning#3094]
this statement is not working in v0.11. There is no LoadFromEnumerable() method available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 476efb73-09c2-46dd-a567-91ad879bb3e7
* Version Independent ID: 5dba3671-2591-409b-26b8-4abd8a5a3001
* Content: [OnnxTransformer Class (Microsoft.ML.Transforms)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.onnxtransformer?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML.Transforms/OnnxTransformer.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Transforms/OnnxTransformer.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by jwood803** [comment]
That may need to be updated. I think `LoadFromEnumerable` resides in the `Microsoft.ML` namespace now.

**Comment by prathyusha12345** [comment]
Sorry I was trying in v0.10. That's why it is not showing.
