### ISSUE TITLE
Code documentation: Updating existing code documents

### ISSUE THREAD

**Issue by TomFinley** [dotnet/machinelearning#3095]
Many of the [documents describing the code and the principles that make it work](https://github.com/dotnet/machinelearning/tree/366332047340bdb12cf5fe2a11f9a6e257af9b84/docs/code) need to be updated. Sometimes this updating will take the form of just updating the type names (e.g., what we used to call `ColumnType` is not `DataViewType`, `ICursor` interface has been subsumed by the `RowCursor` abstract class), and sometimes will take the form of changing the content rather entirely (e.g., we used to consider throwing in cursors bad practice, now we need to explain why we changed our mind, also, we've restricted key-types so that they are explicitly enumerations over sets rather than trying to do a bunch of additional things we never once found useful).

Note that this is distinct from #2054, which is more about user-facing documentation and samples. This is more about the documentation of the principles upon which our code relies.

**Comment by shmoradims** [comment]
Seems like most of the issues are addressed by Tom's 4 PRs above. @TomFinley if there's any topic that's not covered by your recent PRs above, please let us know and I'll create a separate issue for it. Closing for now.
