### ISSUE TITLE
Data kind R4, R8, etc. were removed, but errors still show up with those internal types

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning#3097]
Data Kind 'R4', 'R8, 'etc. were removed in the new version. However trainer still validates against old type, which does not exist anymore "externally", for a user, so when getting errors it is very confusing.

For example:

```
   var trainData = mLContext.Data.LoadFromTextFile(path: trainDataPath,
                     columns: new[]
                     {
                            new TextLoader.Column(nameof(InputData.PixelValues), DataKind.Double, 1, numSparseBits),
                            new TextLoader.Column("Number", DataKind.Int16, 0)
                     },
                     hasHeader: false,
                     separatorChar: ','
                     );
```

![image](https://user-images.githubusercontent.com/1756871/54972539-4a2d2880-4f8c-11e9-8ba7-a9c73d328150.png)

**Comment by singlis** [comment]
Thanks @CESARDELATORRE  for reporting -- this should definitely be treated as a bug.

**Comment by Ivanidzo4ka** [comment]
I thought I clean it up in recent PR https://github.com/dotnet/machinelearning/pull/3046
What nuget are you using? And if it's fresh, what trainer gives you troubles?
I've just try with OVA, LbfgsMaximumEntropy, LightGBM
and I got:
`System.ArgumentOutOfRangeException: 'Schema mismatch for feature column 'Features': expected Vector<Single>, got Vector<Double>`

**Comment by TomFinley** [comment]
Thanks @Ivanidzo4ka. Fine if we close @CESARDELATORRE?

**Comment by CESARDELATORRE** [comment]
Sure! I'm closing it. We'll re-open in case a similar exception with the old types surface again. Hopefully not.
Thanks a lot @Ivanidzo4ka! :)
