### ISSUE TITLE
Intellisense is not helpful with filling in pipeline components.

### ISSUE THREAD

**Issue by zeahmed** [dotnet/machinelearning#31]
When adding transforms/trainers into the "LearningPipeline" object. There is no info/docs/help available through the intellisense. It would be nice to add docs to explain what to add.

**Comment by markusweimer** [comment]
@zeahmed Given that PRs were merged for this, can this issue be closed?

**Comment by zeahmed** [comment]
@markusweimer, Thanks for pointing it out.
Yes, it should be closed now.
