### ISSUE TITLE
Not able to execute object detection sample

### ISSUE THREAD

**Issue by prathyusha12345** [dotnet/machinelearning#3105]
As part of creating ONNX Object detection sample to our MachineLearning Samples Repo, I am trying to execute  ONNX object detection sample by using the unit tests given [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fmachinelearning%2Fblob%2Fmaster%2Ftest%2FMicrosoft.ML.OnnxTransformerTest%2FOnnxTransformTests.cs&data=02%7C01%7Cv-prkor%40microsoft.com%7C9376cba2abc84a9ac5e208d6b22f6acf%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636892314038104547&sdata=jERmHMMiVkUKe%2B0pV3OKP7es4Mdkc6%2BuW4txhB2%2FHqc%3D&reserved=0) .Referring **OnnxStatic()** method in the link.
 
When I am trying to execute the sample by pressing **F5** or **ctrl+F5**, I am getting the below exception.
 
**System.TypeLoadException
  HResult=0x80131522
  Message=Method 'GetOutputSchema' in type 'Microsoft.ML.Transforms.OnnxScoringEstimator' from assembly 'Microsoft.ML.OnnxTransform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' does not have an implementation.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>**
 
The installed nuget packages are as below
 
```
<Project Sdk="Microsoft.NET.Sdk">
 
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>
 
  <ItemGroup>
    <PackageReference Include="Microsoft.ML" Version="0.11.0" />
    <PackageReference Include="Microsoft.ML.ImageAnalytics" Version="0.11.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="0.3.0" />
    <PackageReference Include="Microsoft.ML.OnnxTransform" Version="0.10.0" />
  </ItemGroup>
</Project>
```
 
I have pushed the sample in my repository [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fprathyusha12345%2Fmachinelearning-samples%2Ftree%2Fmaster%2Fsamples%2Fcsharp%2Fgetting-started%2FONNXModel_ObjectDetection%2FONNXModel_ObjectDetection&data=02%7C01%7Cv-prkor%40microsoft.com%7C9376cba2abc84a9ac5e208d6b22f6acf%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636892314038114541&sdata=7%2ByNauaS0cpkFReVM5GUcUOGMq4wOYhB27IItacoIYQ%3D&reserved=0)

**Comment by prathyusha12345** [comment]
and I am not able to run the sample program given in the link  https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/OnnxTransform.cs

It gives me an error as below.
![image](https://user-images.githubusercontent.com/22335043/55104862-7201b680-5088-11e9-9843-ffee98aa17b0.png)

@sfilipi do you have any idea?

**Comment by yaeldekel** [comment]
Hi @prathyusha12345 , thank you for raising this issue. I will look into your issue and get back to you when I figure out the problem.

**Comment by yaeldekel** [comment]
Hi @prathyusha12345 . I did some investigating, and I think your issue might be caused by a version mismatch. The version of the `Microsoft.ML` nuget you are using is 0.11.0, but the version of `Microsoft.ML.OnnxTransform` is 0.10.0. Starting with version 0.11.0 this nuget was renamed to `Microsoft.ML.OnnxTransformer`. Can you try installing version 0.11.0 of this nuget and see if that works?

**Comment by prathyusha12345** [comment]
@yaeldekel Thanks for updating info. Jignesh also helped me before with the same solution. I have did the changes as you mentioned and the sample is working fine.

Closing the issue. Thanks.
