### ISSUE TITLE
`LossFunction` in regression metric is confusing

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#3108]
The regression evaluator reports the following metrics: `MeanAbsoluteError`, `MeanSquaredError`, `RootMeanSquaredError`, `RSquared` and `LossFunction`.

`LossFunction` reports a loss that can theoretically be specified by the user, but there is no public API that exposes this.
I think we should either remove `LossFunction` from the `RegressionMetrics` class, or rename it to be its default value (`SquaredLoss`). Actually, it seems that `SquaredLoss` is identical to `MeanSquaredError`, so we should probably remove (or internalize) this field.

**Comment by TomFinley** [comment]
Hmmm. Good point, should probably hide for now. The idea of providing metric(s) for a set of loss functions is appealing, but I wouldn't want to "rush" into anything. Internalize this then?

https://github.com/dotnet/machinelearning/blob/366332047340bdb12cf5fe2a11f9a6e257af9b84/src/Microsoft.ML.Data/Evaluators/Metrics/RegressionMetrics.cs#L50

**Comment by TomFinley** [comment]
It's also super weird, looking at it from an API perspective, that we have the ability to specify *only one*, and that it is specific to regression metrics -- like loss functions are an alien concept to binary classification, multiclass classification, ranking, etc.

**Comment by wschin** [comment]
It's too late to hide it. We have passed v 1.0 release.
