### ISSUE TITLE
Microsoft.ML nuget package no longer has a way to specify number of bins for binning normalization

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#3109]
In `v0.11.0`, it was possible to write code like the following:

```C#
var normalizer = mLContext.Transforms.Normalize(
    new NormalizingEstimator.BinningColumnOptions(outputColumnName: "Label", numBins: 2));
```

This allowed you to create a `binning` normalizer with the number of bins set to `2`.

However, this API is no longer public in `Microsoft.ML`. There is a public API where you can specify `mode: NormalizingEstimator.NormalizationMode.Binning`, but there is no way to set the number of bins. So when you use this mode, you always `MaximumBinCount` set to the default `1024`.

**Comment by codemzs** [comment]
@eerhardt You set max bins via experimental nuget, more [here](https://github.com/dotnet/machinelearning/blob/366332047340bdb12cf5fe2a11f9a6e257af9b84/src/Microsoft.ML.Experimental/TransformsCatalogExtensions.cs#L82)

**Comment by eerhardt** [comment]
I don't understand why I would have to use an experimental nuget package in order to use binning normalization. Especially since in the "stable" API there exists a `Binning` mode, but that mode is virtually useless if I can't specify how many bins I want.

**Comment by codemzs** [comment]
I'll let @artidoro comment on why this change was made.

**Comment by TomFinley** [comment]
At first glance this seems like an oversight we should correct. It seems like if you want nothing else out of your bin normalizer, you'd want to configure the number of discretization points. Add back in, maybe write somethign in the functional tests to cover it?

**Comment by TomFinley** [comment]
It seems like this is insufficient:

https://github.com/dotnet/machinelearning/blob/366332047340bdb12cf5fe2a11f9a6e257af9b84/src/Microsoft.ML.Transforms/NormalizerCatalog.cs#L26-L29

The reason why we had in other contexts separate configuration options is that there are very few "global" options. So maybe there should be one method for minmax, another for GCN, another for bin. Right now we just have a single method with an `enum` to control the mode, and while that might suffice for some circumstnaces I'm not sure it's the best API for things that require more configuration.

Also I see we don't have the fix-zero configuration option settable, just an FYI, and that's pretty important.

**Comment by codemzs** [comment]
@TomFinley What do you feel about [this](https://github.com/dotnet/machinelearning/pull/3118/files)?

**Comment by TomFinley** [comment]
> @TomFinley What do you feel about [this](https://github.com/dotnet/machinelearning/pull/3118/files)?

Looks good at first glance. Might need some input-output column pair overloads for the multicolumn mapping, but I don't insist on it. The people I view as having the most relevant feedback on this though are @artidoro (since he introduced it I believe) and @eerhardt (since he's the one that raised this issue).
