### ISSUE TITLE
Simplification of experiment methods

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#311]
Few things so far:
A) We have this pattern in our code:
```
var importInput = new ML.Data.TextLoader(dataPath);
...
experiment.SetInput(importInput.InputFile, new SimpleFileHandle(env, dataPath, false, false));
```
And I'm not sure why I have to specify same file twice.
B) We have this pattern everywhere in our code:
```
experiment.Compile();
experiment.SetInput(importInput.InputFile, new SimpleFileHandle(env, dataPath, false, false));
experiment.Run();
```
Can we simplify this into one method instead of  3 different calls?

**Comment by glebuk** [comment]
Sounds like this might get addressed in #371

**Comment by Ivanidzo4ka** [comment]
It's more about EntryPoints rather than new API.

**Comment by codemzs** [comment]
With the new API in place this is not relevant anymore.
