### ISSUE TITLE
Prior binary trainer requires float label column, but all other binary trainers require bool

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#3119]
Build a pipeline like:

```C#
            IEstimator<ITransformer> pipeline =
                MLContext.Transforms.ReplaceMissingValues("FixedAcidity", replacementMode: MissingValueReplacingEstimator.ReplacementMode.Mean)
                .Append(MLContext.FloatToBoolLabelNormalizer())
                .Append(MLContext.Transforms.Concatenate("Features",
                    new[]
                    {
                        "FixedAcidity",
                        "VolatileAcidity",
                        "CitricAcid",
                        "ResidualSugar",
                        "Chlorides",
                        "FreeSulfurDioxide",
                        "TotalSulfurDioxide",
                        "Density",
                        "Ph",
                        "Sulphates",
                        "Alcohol"}))
                .Append(MLContext.BinaryClassification.Trainers.Prior());
```

Scenario taken from [XamlBrewer.Uwp.MachineLearningSample](https://github.com/XamlBrewer/UWP-MachineLearning-Sample/blob/b7337d6e49e2109d9f028c1942aa2b409d3bfb9c/XamlBrewer.Uwp.MachineLearningSample/Models/BinaryClassification/BinaryClassificationModel.cs#L18-L35) with the "Random" trainer changed to the "Prior" trainer.

When you try to fit this pipeline, you get an exception:

```
{System.ArgumentOutOfRangeException: Invalid type for Label column
Parameter name: data
 	Microsoft.ML.Core.dll!Microsoft.ML.Runtime.Contracts.CheckParam(Microsoft.ML.Runtime.IExceptionContext ctx, bool f, string paramName, string msg) Line 542	C#
 	Microsoft.ML.StandardTrainers.dll!Microsoft.ML.Trainers.PriorTrainer.Train(Microsoft.ML.TrainContext context) Line 235	C#
 	Microsoft.ML.StandardTrainers.dll!Microsoft.ML.Trainers.PriorTrainer.Microsoft.ML.ITrainer<Microsoft.ML.Trainers.PriorModelParameters>.Train(Microsoft.ML.TrainContext context) Line 274	C#
 	Microsoft.ML.StandardTrainers.dll!Microsoft.ML.Trainers.PriorTrainer.Fit(Microsoft.ML.IDataView input) Line 222	C#
 	Microsoft.ML.Data.dll!Microsoft.ML.Data.EstimatorChain<Microsoft.ML.ITransformer>.Fit(Microsoft.ML.IDataView input) Line 67	C#
>	XamlBrewer.Uwp.MachineLearningSample.exe!XamlBrewer.Uwp.MachineLearningSample.Models.BinaryClassificationModel.BuildAndTrain(string trainingDataPath, Microsoft.ML.IEstimator<Microsoft.ML.ITransformer> algorithm) Line 46	C#
````

It appears the `Prior` binary trainer can only take `float` labels:

https://github.com/dotnet/machinelearning/blob/45b6c43387294d19cad843a21e87539213e8d34c/src/Microsoft.ML.StandardTrainers/Standard/Simple/SimpleTrainers.cs#L233

However, all other binary trainers require the label column to be a `boolean`.

cc @TomFinley

**Comment by codemzs** [comment]
@eerhardt FastTree seems to be recognizing more than just bool:

public static void CheckBinaryLabel(this RoleMappedData data)
        {
            Contracts.CheckValue(data, nameof(data));

            if (!data.Schema.Label.HasValue)
                throw Contracts.ExceptParam(nameof(data), "Training data must specify a label column.");
            var col = data.Schema.Label.Value;
            Contracts.Assert(!col.IsHidden);
            if (col.Type != BooleanDataViewType.Instance && col.Type != NumberDataViewType.Single && col.Type != NumberDataViewType.Double && !(col.Type is KeyDataViewType keyType && keyType.Count == 2))
            {
                KeyDataViewType colKeyType = col.Type as KeyDataViewType;
                if (colKeyType != null)
                {
                    if (colKeyType.Count == 1)
                    {
                        throw Contracts.ExceptParam(nameof(data),
                            "The label column '{0}' of the training data has only one class. Two classes are required for binary classification.",
                            col.Name);
                    }
                    else if (colKeyType.Count > 2)
                    {
                        throw Contracts.ExceptParam(nameof(data),
                            "The label column '{0}' of the training data has more than two classes. Only two classes are allowed for binary classification.",
                            col.Name);
                    }
                }
                throw Contracts.ExceptParam(nameof(data),
                    "The label column '{0}' of the training data has a data type not suitable for binary classification: {1}. Type must be Boolean, Single, Double or Key with two classes.",
                    col.Name, col.Type);
            }
        }

**Comment by TomFinley** [comment]
Interesting @codemzs. Some of the trainers don't use our "conveniences" for ingesting labels, due to them having unusual patterns of access of the data. FastTree in particular does a "transpose" of the data, so I can easily imagine this being the case, that it was missed, just as prior trainer was. (Prior trainer is likewise unusual, in that unlike other trainers it does not try to fetch a feature vector *at all*.)

**Comment by eerhardt** [comment]
I thought @Ivanidzo4ka made all binary trainers only accept booleans with https://github.com/dotnet/machinelearning/pull/2804.

However, looking through that PR I see https://github.com/dotnet/machinelearning/pull/2804#issuecomment-469443560
