### ISSUE TITLE
DataKind U4 in error message with Matrix Factorization

### ISSUE THREAD

**Issue by singlis** [dotnet/machinelearning#3121]
### System information

Windows 10
Microsoft.ML.Recommenders 0.12.0-preview-27526-3

### Issue

- **What did you do?**
Ran through the Movie Lens recommendation pipeline. 
Dataset can be found from AzureML gallery:
https://gallery.azure.ai/Experiment/Recommender-Movie-recommendation-3

- **What happened?**
The UserId was set to Int32 - so when running the training, I get an error:

> System.InvalidOperationException: 'Column 'UserId' with role MatrixColumnIndex should be a known cardinality U4 key, but is instead 'Int32''

- **What did you expect?**
Not to see U4 in the description as this tells me nothing. The error should say must be of KeyDataViewType. 

### Source code / logs
Here is the sample code to reproduce:
```
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using System;

namespace ConsoleApp36
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            var mlContext = new MLContext();
            var loader = mlContext.Data.CreateTextLoader(new TextLoader.Options()
            {
                Columns = new TextLoader.Column[]
                {
                    new TextLoader.Column("UserId", DataKind.Int32, 0),
                    new TextLoader.Column("MovieId", DataKind.Int32, 1),
                    new TextLoader.Column("Rating", DataKind.Int32, 2),
                    new TextLoader.Column("Timestamp", DataKind.Int64, 3)
                },
                HasHeader = true,
                Separators = new char[] { ',' }
            });

            var data = loader.Load("{path to data}/Movie Ratings.csv");
            var pipeline = mlContext.Recommendation().Trainers.MatrixFactorization(new MatrixFactorizationTrainer.Options()
            {
                MatrixColumnIndexColumnName = "UserId",
                MatrixRowIndexColumnName = "MovieId",
                LabelColumnName = "Rating"
            });

            var model = pipeline.Fit(data);
            
        }
    }
}
```

Here is the line of code where this is occurring:
https://github.com/dotnet/machinelearning/blob/366332047340bdb12cf5fe2a11f9a6e257af9b84/src/Microsoft.ML.Recommender/RecommenderUtils.cs#L65

**Comment by MacchiFilippo** [comment]
You will got the same error if you try to load a dataview with text column:
**Column 'ProductID' with role MatrixColumnIndex should be a known cardinality U4 key, but is instead 'Text'**

**Comment by RileyAtWork** [comment]
I am getting the same error on 0.11. I have no clue what to do to work around this or what I am even missing. I have a csv with 2 columns example below. my POCO has two uint properties.  
123456,654321

**Comment by wschin** [comment]
@RileyAtWork, if your data is in-memory, maybe you can take a look at a sample athttps://github.com/dotnet/machinelearning/blob/b8d1b501ab4f5b3557dc4d5ae83bf9a7cf1bfe1b/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Recommendation/MatrixFactorization.cs#L85.

**Comment by wschin** [comment]
@singlis, I can't find your data set on AzureML Gallery, so I will try to reproduce your error using the data file https://raw.githubusercontent.com/dotnet/machinelearning-samples/master/samples/csharp/end-to-end-apps/Recommendation-MovieRecommender/MovieRecommender_Model/Data/ratings.csv as your `Movie Rating.csv`.

**Comment by wschin** [comment]
It turns out that this problem is not a bug. Because matrix factorization expects key type of `uint`, you need to tell `TextLoader` to parse those numbers in the file as `key`s. I just modified your original file and made it working below.
```csharp
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using System;

namespace ConsoleApp36
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            var mlContext = new MLContext();
            var loader = mlContext.Data.CreateTextLoader(new TextLoader.Options()
            {
                Columns = new TextLoader.Column[]
                {
                    new TextLoader.Column("UserId", DataKind.UInt32, new[] { new TextLoader.Range(0) }, new KeyCount(100000)),
                    new TextLoader.Column("MovieId", DataKind.UInt32, new[] { new TextLoader.Range(1) }, new KeyCount(100000)),
                    new TextLoader.Column("Rating", DataKind.Single, 2),
                    // new TextLoader.Column("UserId", DataKind.Int32, 0),
                    // new TextLoader.Column("MovieId", DataKind.Int32, 1),
                    // new TextLoader.Column("Rating", DataKind.Int32, 2),
                    // new TextLoader.Column("Timestamp", DataKind.Int64, 3)
                },
                HasHeader = true,
                Separators = new char[] { ',' }
            });

            var data = loader.Load("D:\\ratings.csv");
            var pipeline = mlContext.Recommendation().Trainers.MatrixFactorization(new MatrixFactorizationTrainer.Options()
            {
                MatrixColumnIndexColumnName = "UserId",
                MatrixRowIndexColumnName = "MovieId",
                LabelColumnName = "Rating"
            });

            var model = pipeline.Fit(data);

        }
    }
}
```
