### ISSUE TITLE
API Reference needs to include expected column types

### ISSUE THREAD

**Issue by singlis** [dotnet/machinelearning#3127]
## Issue
Our API documentation for trainers, evaluate and cross validate need to specify the expected column types. 

For example:
```
Parameters
labelColumn
String
The name of the label column.

matrixColumnIndexColumnName
String
The name of the column hosting the matrix's column IDs.

matrixRowIndexColumnName
String
The name of the column hosting the matrix's row IDs.
```
Taken from here:
[Matrix Factorization Help](url)
[](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.recommendationcatalog.recommendationtrainers.matrixfactorization?view=ml-dotnet#Microsoft_ML_RecommendationCatalog_RecommendationTrainers_MatrixFactorization_System_String_System_String_System_String_System_Int32_System_Double_System_Int32_)

Note that this takes:
* Label Column (really name of the label column) and that the type is string
* MatrixIndexColumnName -- also string
* MatrixRowIndexColumnName - also string

The type string provides no information on the actual expected/supported column type. 

## Expected
There needs to be more documentation regarding the column types that trainers are expecting and if that trainer will add additional columns as a result of the transformation.

## Suggestion
This can be added to the parameter description, for example:
`The name of the label column. The label column must be one of the following ColumnType: DataKind.Int64, DataKind.Float,...</param>
`
Additional content regarding if columns are added and what those columns are should be added in the Remarks section. Columns that are added should also include their ColumnType as well.

**Comment by singlis** [comment]
Note that this also applies to Evaluate and CrossValidate api references.

**Comment by sfilipi** [comment]
I think we should put the label type in the summary of the trainer extensions documentation, since that is the string that intellisense displays when it gets added.

**Comment by singlis** [comment]
I flushed out an example with the FieldAwareFactorizationMachine. I put this on the extension method. The FieldAwareFactorizationMachine takes in a featureColumnName, labelColumnName and exampleWeightColumnName -- for each parameter that is a column name, these now have additional text in the param reference that explains the expected column type. 

The FieldAwareFactorizationMachine also adds columns to the transformed data. In order to document the added columns, I added this to remarks using the xml docs table (really as a list with the type set as table). The table has the column name, expected column type, and a description of what the column is @wschin - this could be on the GetOutputSchema instead, but if we document the extension method rather than the class, this would be harder to find.
@sfilipi  the parameter reference for label column can be dupped in the summary if needed. 

Here is the sample:
```
        /// <summary>
        /// Predict a target using a field-aware factorization machine algorithm.
        /// </summary>
        /// <remarks>
        /// Note that because there is only one feature column, the underlying model is equivalent to standard factorization machine.
        /// The following columns will be added to the <see cref="IDataView"/> after transform:
        /// <list type="table">
        ///     <listheader>
        ///         <term>Column Name</term>
        ///         <term>Column Type</term>
        ///         <term>Description</term>
        ///     </listheader>
        ///     <item>
        ///         <term>Score</term>
        ///         <term><see cref="DataKind.Single"/></term>
        ///         <term>The unbounded score that was calculated by the trainer to determine the prediction.</term>
        ///     </item>
        ///     <item>
        ///         <term>PredictedLabel</term>
        ///         <term><see cref="DataKind.Boolean"/></term>
        ///         <term>The predicted label made by the trainer.</term>
        ///     </item>
        ///     <item>
        ///         <term>Probability</term>
        ///         <term><see cref="DataKind.Single"/></term>
        ///         <term>The probability of the score, this is used to determine the final predicted label.</term>
        ///     </item>
        /// </list>
        /// </remarks>
        /// <param name="catalog">The binary classification catalog trainer object.</param>
        /// <param name="featureColumnName">The name of the feature column. The <paramref name="featureColumnName"/> must refer to a column of type <see cref="DataKind.Single"/></param>
        /// <param name="labelColumnName">The name of the label column. The <paramref name="labelColumnName"/> must refer to a column of type <see cref="DataKind.Boolean"/></param>
        /// <param name="exampleWeightColumnName">The name of the example weight column (optional). The <paramref name="exampleWeightColumnName"/> must refer to a column of type <see cref="DataKind.Single"/></param>

```

**Comment by singlis** [comment]
cc @shmoradims @glebuk as well.

**Comment by singlis** [comment]
I've broken down the items that need to be updated based upon the catalogs:
| Catalog | APIs | Issue Reference |
|---|---|---|
| AnomalyDetection | | |

**Comment by shmoradims** [comment]
I believe the input/output types were addressed for all trainers and transforms during the API reference project. Here's an example for FFM with input/output sub-section in remarks:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.fieldawarefactorizationmachinetrainer?view=ml-dotnet
