### ISSUE TITLE
The trainer entry points don't contain sufficient information about the algorithm type (linear, tree etc)

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#313]
### System information

- **.NET Version (eg., dotnet --info)**: 0.3.0-preview-26604-1

### Issue
The trainer entry points don't contain any information about their algorithm type ( tree, linear)
Systems interfacing with ML.NET in this fashion might need to present to their users the information classified based on this criteria.

**Comment by shauheen** [comment]
Can this and #314 perhaps be addressed in the same PR?

**Comment by sfilipi** [comment]
We could place the information in the same entry point property, potentially another entry in IInputType. Logged them separately since they are parallel workitems. We could combine the PRs.

**Comment by Zruty0** [comment]
I will be closing this issue, since it has never been discussed for 1/2 year.
Also, the API now suggests somewhat better classification of components via `MLContext`.
