### ISSUE TITLE
ColumnAttribute gone in 0.11

### ISSUE THREAD

**Issue by ericjohannsen** [dotnet/machinelearning#3137]
### System information

- Windows 10
- .NET Core 2.2.104

### Issue

- Updated ML.Net 0.10 to 0.11 using NuGet
- ColumnAttribute no longer defined
- The change be documented in breaking change notes, specifically whether you now use the similar attribute from `System.ComponentModel.DataAnnotations.Schema` or if you defined a differently-named attribute.

### Source code / logs

        [Column(ordinal: "0", name: "Label")]
        public float Sentiment;

**Comment by Ivanidzo4ka** [comment]
If you want to change column name, switch to ColumnNameAttribute class. If you need to specify position of field in text file: use LoadColumnAttribute.

**Comment by eerhardt** [comment]
FYI - you can use both `ColumnNameAttribute` and `LoadColumnAttribute` together on the same field/property.
