### ISSUE TITLE
CreateEnumerable gone in 0.11

### ISSUE THREAD

**Issue by ericjohannsen** [dotnet/machinelearning#3138]
### System information

- Windows 10
- .NET Core 2.2.104

### Issue

- Updated ML.Net 0.10 to 0.11 using NuGet
- MLContext.CreateEnumerable no longer available
- Document the new way to create an `IEnumerable<T>` from an `IDataView`

### Source code / logs

`var nativePredictions = mlContext.CreateEnumerable<TP>(dataWithPredictions, false)`

**Comment by Ivanidzo4ka** [comment]
it was moved to `mlContext.Data.CreateEnumerable`
