### ISSUE TITLE
The transforms entry points don't contain function information 

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#314]
### System information

- **.NET Version (eg., dotnet --info)**: 0.3.0-preview-26604-1

### Issue

The transforms entry point should contain information about the way in which they manipulate the data: schema manipulation, featurizer, pre-processing etc. 

Systems interfacing with ML.NET through entry points might need to classify the transforms based on the function their perform over the dataset, and present them to their users in that fashion.

**Comment by Zruty0** [comment]
I don't think this is necessary work.
