### ISSUE TITLE
Problem with GloVe100D and GloVe200D files...

### ISSUE THREAD

**Issue by zeahmed** [dotnet/machinelearning#3141]
GloVe200D word embedding file contains 100D embedding vector and GloVe100D contains 200D embedding vector for each token. The file names look fine. It seems like contents of the file or filename got interchanged.
https://github.com/dotnet/machinelearning/blob/e95f31d2417a58103f70fe06b212d31ac5963dff/src/Microsoft.ML.Transforms/Text/WordEmbeddingsExtractor.cs#L603

https://github.com/dotnet/machinelearning/blob/e95f31d2417a58103f70fe06b212d31ac5963dff/src/Microsoft.ML.Transforms/Text/WordEmbeddingsExtractor.cs#L604

**Comment by najeeb-kazmi** [comment]
https://aka.ms/mlnet-resources/wordvectors/glove.6b.100d.txt

and 

https://aka.ms/mlnet-resources/wordvectors/glove.6b.200d.txt

were pointing to the incorrect files in Azure storage.

Fixed the target URLs to be the correct files.
