### ISSUE TITLE
K-means clustering getting centroid coordinates

### ISSUE THREAD

**Issue by hobbsa** [dotnet/machinelearning#3144]
### System information

- Windows 10
- .NET 4.6.1, ML.NET .11

### Issue

I am using the KMeans clustering trainer but is there anyway to get the actual centroid locations as X,Y (trying to plot the results on a graph for visual representation).  I see the CentroidL2S private property on the KMeansParms class but those seem to be vector based.  Has anyone plotted the results of a cluster or have a good way to generate X,Y coords for plotting purposes?

Thanks

**Comment by sfilipi** [comment]
Hi @hobbsa 

Check out this sample, for how to get the coordinates of the centroids: https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Clustering/KMeansWithOptions.cs#L49

**Comment by sfilipi** [comment]
I am closing the issue, since it is answered. Please feel free to reopen if you have further questions.
