### ISSUE TITLE
Error when using ConvertToOnnx

### ISSUE THREAD

**Issue by jwood803** [dotnet/machinelearning#3146]
When trying to use the `context.Model.ConvertToOnnx` method it shows an error saying `Reference to type 'ITransformer' claims to be defined in 'Microsoft.ML.Core', but it could not be found`.

Below is the code when trying to access it.

```csharp
var context = new MLContext();

var textLoader = context.Data.CreateTextLoader(new[]
{
    new TextLoader.Column("YearsExperience", DataKind.Single, 0),
    new TextLoader.Column("Label", DataKind.Single, 1),
},
hasHeader: true,
separatorChar: ',');

var data = textLoader.Load("./SalaryData.csv");

var trainTestData = context.Regression.TrainTestSplit(data);

var pipeline = context.Transforms.Concatenate("Features", "YearsExperience")
    .Append(context.Regression.Trainers.FastTree());

ITransformer model = pipeline.Fit(trainTestData.TrainSet);

context.Model.ConvertToOnnx(model, data);
```

Using version v.11. I have the `Microsoft.ML.Onnx` package installed, but I'm not sure if it's needed.

**Comment by eerhardt** [comment]
Can you list your .csproj?

I believe the ONNX package got renamed recently - I think it is called Microsoft.ML.OnnxTransformer instead of just Transform.

**Comment by jwood803** [comment]
Sure, here it is below. Looks like it's `Microsoft.ML.Onnx`

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML" Version="0.11.0" />
    <PackageReference Include="Microsoft.ML.Onnx" Version="0.10.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="SalaryData.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
```

**Comment by eerhardt** [comment]
>  <PackageReference Include="Microsoft.ML.Onnx" Version="0.10.0" />

That’s the issue. Change that to OnnxConverter and version “0.11.0”

**Comment by jwood803** [comment]
That looks to be it! Thanks, @eerhardt! If it sounds useful I can update the cookbook to include samples with using this.
