### ISSUE TITLE
Linear Regression using ML.NET

### ISSUE THREAD

**Issue by sethreidnz** [dotnet/machinelearning#3147]
I am trying to do simple linear regression with ML.NET and am struggling to figure out how you would do this. Is it possible and if so what is your recommendation? It's not clear from the documentation if a simple linear regression is possible with ML.NET.

**Comment by sfilipi** [comment]
Hi @sethreidnz 

Check out this samples:

Full tutorial on regression: https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/taxi-fare 

Samples on linear regressors in ML.NET:

* https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Regression/StochasticDualCoordinateAscent.cs
* https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Regression/StochasticDualCoordinateAscentWithOptions.cs

* https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Regression/PoissonRegression.cs

* https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Regression/PoissonRegressionWithOptions.cs

**Comment by sfilipi** [comment]
Closing the issue, as I believe has been answered. Please feel free to reopen, or open a new one if further questions.

**Comment by adamshakhabov** [comment]
Link https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Regression/StochasticDualCoordinateAscent.cs is invalid (404 Page not found).
