### ISSUE TITLE
Time Series forecasting

### ISSUE THREAD

**Issue by byQ96** [dotnet/machinelearning#3151]
### System information

- **OS version/distro Windows 10:
- **.NET Version (eg., dotnet --info) Core 2.0 - 2.2: 

### Issue

I am looking for time series prediction possibility, but can't find one example. There are a lot of posts about forecasting - all from 2018. So my question is: Is time series forecasting included into ml.net 0.11 or do you plan to add it in the future versions?

**Comment by wschin** [comment]
The public API to time series in ML.NET doesn't support forecasting yet. If you are looking for anomaly detection, maybe those [example ](https://github.com/dotnet/machinelearning/tree/master/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/TimeSeries)could be helpful.

**Comment by byQ96** [comment]
Accidentally I found that there is a nuget package named Microsoft.ML.TimeSeries in 0.11 version. Do you know where can I find its code?

**Comment by codemzs** [comment]
https://github.com/dotnet/machinelearning/tree/master/src/Microsoft.ML.TimeSeries

**Comment by rdzidziguri** [comment]
@byQ96 despite your finding, unfortunate for now ML.NET does not support TS forecasting and does not have things like long short term memory time series. this is something we need on our side as well but i can not even find any sign of this features being planed so it is definitely wanted but not available feature inside ML.NET for noe.

**Comment by codemzs** [comment]
@rdzidziguri @byQ96 It does now: https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/TimeSeries/Forecasting.cs and will be part of 1.1 release

**Comment by rdzidziguri** [comment]
@codemzs Thank you very much for providing this to us. ML.NET is moving really fast good job team!!!. 

I have one question regarding API surface for example https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/TimeSeries/Forecasting.cs#L53

we can see that method is named train while in all other areas we call it Fit. so what is the difference here? I do not mean it is extremely hard to remember to use the train instead of fit, but i though approach here would be to follow same conventions across all API surfaces. does not this break the core philosophy behind ML.NET **Load -> Transform -> Train**

**Comment by byQ96** [comment]
@codemzs Thank You for this information. Also do You plan to add another forecasting methods in the future?

**Comment by codemzs** [comment]
@byQ96 Np, what do you mean another forecasting method? did you mean model? We may refine the API but we plan to make time series nuget a release nuget end of this month.

**Comment by byQ96** [comment]
I was thinking about Moving Average or ARMA implementation. It could be also helpful to fill the gaps in the dataseries before SSA model training.

**Comment by byQ96** [comment]
@codemzs  Also, do You plan to add multivariate SSA?

**Comment by codemzs** [comment]
@byQ96 Multi-variate and moving average are both definitely on the short-term plan. If it is ok to ask may I know the scenario you are using time series for?

CC: @mengaims @ganik

**Comment by byQ96** [comment]
@codemzs 
Yes of course. I want to use number of customer appointments in each day for a specific clinic and predict future values and possible peaks. Of course the characteristic should have specific Seasonality and Trend. The gaps in the timeseries are the result of for example the period of time when the clinic is closed. 
About Multivariate - thats more experimental and I want to take into consideration other time series which can have impact on the one to be predicted.

**Comment by prvit** [comment]
@codemzs you mentioned that 

> Multi-variate and moving average are both definitely on the short-term plan.
I saw that issue tracking Multivariate support for time series anomaly detection #1696 was moved to priority 2.
My question is if a multivariate time series prediction/forecast is still on a short-term plan?
