### ISSUE TITLE
API reference - Finalize the template for trainer samples

### ISSUE THREAD

**Issue by shmoradims** [dotnet/machinelearning#3160]
Our current template for trainer API reference samples is as follows:

1) Create in-memory random training data (as discussed in #2726 we're avoiding complex datasets and text-loader).
2) Create a pipeline with just the trainer (i.e. focusing only on the API that this sample is about without getting into complex featurization pipeline).
3) Fit the trainer.
4) Generate 5 predictions and output results.
5) Evaluate with in-memory test data and output metrics.

Below are some examples:
* Binary classification: [FastTree](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/FastTree.cs), [FastTreeWithOptions](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/FastTreeWithOptions.cs)
* Regression: [PoissonRegression](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Regression/PoissonRegression.cs), [PoissonRegressionWithOptions](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Regression/PoissonRegressionWithOptions.cs).

Other samples will be added using this template. If you want to make any changes please mention them here so that we can finalize the sample.

/cc @shauheen @glebuk

**Comment by wschin** [comment]
What's the desired position of in-memory data structures? Before `Example()` or after `Example()`?

**Comment by shmoradims** [comment]
I added the position to the template:
// Add the data structures and helper classes below Example()

For reference papers, please add a snippet so that I know what you mean.

**Comment by sfilipi** [comment]
I think we should also add reading the model parameters. There has been asks for it.

**Comment by shmoradims** [comment]
Are model parameters available for all trainers or just some? Do they change per ML task, or trainer family (linear, tree, etc). Could you please post a snippet here?

**Comment by wschin** [comment]
Here is some reference paper of matrix factorization in ML.NET: https://github.com/dotnet/machinelearning/blob/b8a70ac494ea8dae832621c782ba30887d0b9cc4/src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs#L69. My motivation is to make ML.NET a place for entry-level ML users to become senior-level scientists.

**Comment by wschin** [comment]
Showing model parameters will be too much for a trainer's first example. However, inspecting models is definitely important, so I'd suggest to have at least two example files per trainer.

**Comment by shmoradims** [comment]
@wschin could you please provide snippets for the second example you want?

**Comment by wschin** [comment]
Sure. I got one from a test.
```chsarp
        /// <summary>
        /// Introspective Training: Linear model parameters may be inspected.
        /// </summary>
        [Fact]
        public void InpsectLinearModelParameters()
        {
            // ...
            // Prepare a linear model and data by reusing code in the first example.
            // ...

            // Train the model.
            var model = pipeline.Fit(data);

            // Extract the linear model from the pipeline.
            var linearModel = model.Model;

            // Get the model bias and weights.
            var bias = linearModel.Bias;
            var weights = linearModel.Weights;

            //  Print coefficient of each feature and show the computation of score using bias and weights.
            //  ...
        }
```
