### ISSUE TITLE
Schema comprehension fails for type System.Drawing.Bitmap

### ISSUE THREAD

**Issue by abgoswam** [dotnet/machinelearning#3162]
Several of the image transforms in ML.NET produce intermediate columns of type System.Drawing.Bitmap

https://github.com/dotnet/machinelearning/blob/e5cbca78683e3c1036966e07b7fd7d1b180c1562/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/ImageAnalytics/ConvertToGrayScale.cs#L39-L42

If we try to use  schema comprehension to  map some intermediate data (e.g. `transformedData`) to an IEnumerable,  we  hit an exception  when  dealing with  a column of type ` System.Drawing.Bitmap`

**Error**: Unhandled Exception: System.ArgumentOutOfRangeException: Could not determine an IDataView type for member ImageObject

@Ivanidzo4ka

**Comment by wschin** [comment]
We need to extend two places to support Image.
- Add Image to `InternalDataKind`
- Fix other places to recognize `InternalDataKind`.
