### ISSUE TITLE
KeyType in example is invalid

### ISSUE THREAD

**Issue by RileyAtWork** [dotnet/machinelearning#3169]
[Enter feedback here]
In 0.11 KeyType only takes 1 parameter -  'ulong count' 
class MatrixElement
       {
           // Matrix column index starts from firstColumnIndex and is at most firstColumnIndex+n-1.
           // Contieuous=true means that all values from firstColumnIndex to firstColumnIndex+n-1 are allowed keys.
           // [KeyType(Contiguous = true, Count = n, Min = firstColumnIndex)]
           // public uint MatrixColumnIndex;
           // Matrix row index starts from firstRowIndex and is at most firstRowIndex+m-1.
           // Contieuous=true means that all values from firstRowIndex to firstRowIndex+m-1 are allowed keys.
           [KeyType(Contiguous = true, Count = m, Min = firstRowIndex)]
           public uint MatrixRowIndex;
           // The rating at the MatrixColumnIndex-th column and the MatrixRowIndex-th row.
           public float Value;
       }
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 335e2f1c-de96-9963-8edc-c45bc5d31105
* Version Independent ID: 571d5df2-bce7-9fdf-c123-5c932d7935ce
* Content: [MatrixFactorizationTrainer Class (Microsoft.ML.Trainers)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.matrixfactorizationtrainer?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML.Trainers/MatrixFactorizationTrainer.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Trainers/MatrixFactorizationTrainer.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by wschin** [comment]
You're right. It should become something like [this](https://github.com/dotnet/machinelearning/blob/fde1ab718bcf0da10293e5ca32245373e4669e2a/src/Microsoft.ML.SamplesUtils/SamplesDatasetUtils.cs#L736).
```csharp
       // The following variables defines the shape of a m-by-n matrix. The variable firstRowIndex indicates the integer that
       // would be mapped to the first row index. If user data uses 0-based indices for rows, firstRowIndex can be set to 0.
       // Similarly, for 1-based indices, firstRowIndex could be 1.
       const int firstRowIndex = 1;
       const int firstColumnIndex = 1;
       const int m = 60;
       const int n = 100;

       // A tuple of row index, column index, and rating. It specifies a value in the rating matrix.
       class MatrixElement
       {
           // Matrix column index starts from 0 and is at most firstColumnIndex+n-1.
           // [KeyType(n + firstColumnIndex)]
           // public uint MatrixColumnIndex;
           // Matrix row index starts from 0 and is at most firstRowIndex+m-1.
           [KeyType(m + firstRowIndex)]
           public uint MatrixRowIndex;
           // The rating at the MatrixColumnIndex-th column and the MatrixRowIndex-th row.
           public float Value;
       }
```
Basically, we now assume `Contiguous` is always true and `Min` is always zero.
