### ISSUE TITLE
Question: How to get accuracy in predicted label

### ISSUE THREAD

**Issue by epignosisx** [dotnet/machinelearning#317]
Is it possible to get the accuracy/precision of a predicted label? Is there an attribute I can use the extract it? Basically some thing like:

```cs
public class EmployeePrediction
{
    [ColumnName("PredictedLabel")]
    public bool Outcome;

    [SomeAttribute]
    public float Accuracy;
}
```

**Comment by zeahmed** [comment]
Accuracy is a cumulative measure. It is computed on all the predictions in the dataset. You would like to see the following sample to know how to compute metrics for binary classification task.

https://github.com/dotnet/machinelearning-samples/tree/master/samples/getting-started/BinaryClassification_SentimentAnalysis

Basically, this what you would like to do after the model is trained. ``` C#
var testData = new TextLoader(TestDataPath).CreateFrom<SentimentData>();
var evaluator = new BinaryClassificationEvaluator();
var metrics = evaluator.Evaluate(model, testData);
```
Variable `metrics` will contain all the computed metrics relevant to binary classification task.

**Comment by epignosisx** [comment]
Got it! Thanks.

**Comment by ridj87** [comment]
Is there a way to bring the metric data into the model.zip file ? Can I add it to the predictionmodel in some way? The scenario is that when the prediction comes as a response from, let say an api that uses my trained model,  I want to tell the user the certain percentage that the prediction is correct.
