### ISSUE TITLE
Exception Swallowing issues

### ISSUE THREAD

**Issue by najeeb-kazmi** [dotnet/machinelearning#3193]
Related to: VSO Task [799764](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/799764)

Security guidelines for release include the following for exception handling.

Exception Handlers
All new product code must be free of "swallow everything" exception handlers:

- C code must not catch and dismiss all SEH exceptions or SEH exceptions that your application cannot responsibly handle.
- In unmanaged C++ code, do not enable asynchronous exception handling [/EHa flag] in combination with catching and "swallowing" all exceptions.
/Eha has the side-effect of swallowing all exceptions from hardware (ex. floating point exceptions, division by zero, and access violations) when catch(…) is used.
- In managed code do not use HandleProcessCorruptedStateExceptionsAttribute in combination with catching and "swallowing" all exceptions.
- Recover only on exceptions that your application can handle safely, and let all other exceptions pass through.

Reviewing the repo, I found the following cases that looked questionable to me in src folder (ignoring test folder).  Please see if any of these requires more adequate handling.

https://github.com/dotnet/machinelearning/blob/ac53748721939024d85e984c0b8911dbb1af3339/src/Microsoft.ML.Core/CommandLine/CmdParser.cs#L1895-L1898

Should we inform user what the exception is here and then return null?
https://github.com/dotnet/machinelearning/blob/ac53748721939024d85e984c0b8911dbb1af3339/src/Microsoft.ML.Core/ComponentModel/AssemblyLoadingUtils.cs#L213-L216

Should we raise the actual error instead of just saying that Action xyz failed in IFileHandle?
https://github.com/dotnet/machinelearning/blob/ac53748721939024d85e984c0b8911dbb1af3339/src/Microsoft.ML.Core/Data/IFileHandle.cs#L110-L114
https://github.com/dotnet/machinelearning/blob/ac53748721939024d85e984c0b8911dbb1af3339/src/Microsoft.ML.Core/Data/IFileHandle.cs#L125-L129
https://github.com/dotnet/machinelearning/blob/ac53748721939024d85e984c0b8911dbb1af3339/src/Microsoft.ML.Core/Data/IFileHandle.cs#L142-L146

A comment explaining that this should not throw.
https://github.com/dotnet/machinelearning/blob/ac53748721939024d85e984c0b8911dbb1af3339/src/Microsoft.ML.Core/Data/Repository.cs#L181-L183
https://github.com/dotnet/machinelearning/blob/ac53748721939024d85e984c0b8911dbb1af3339/src/Microsoft.ML.Core/Data/Repository.cs#L381-L383

See the review comment here.
https://github.com/dotnet/machinelearning/blob/ac53748721939024d85e984c0b8911dbb1af3339/src/Microsoft.ML.Data/DataLoadSave/Binary/BinaryLoader.cs#L1384-L1393

An error message here?
https://github.com/dotnet/machinelearning/blob/ac53748721939024d85e984c0b8911dbb1af3339/src/Microsoft.ML.TensorFlow/TensorFlow/TensorflowUtils.cs#L206-L207

cc: @glebuk @TomFinley

**Comment by eerhardt** [comment]
Note that the `machinelearning/src/Microsoft.ML.Core/ComponentModel/AssemblyLoadingUtils.cs` instance cannot be reached from our public API. It is only used by the MAML and EntryPoints components.

**Comment by glebuk** [comment]
IT depends, 
- cmdparser, can be fixed by just specifying the types of exceptions that parse*() can through
-loadassembly also calls one method and should be able to catch more specific exceptions
- IFileHandle - should be left alone as we are in a dispose() method
-  machinelearning/src/Microsoft.ML.Core/Data/Repository.cs should be more specific as they call a single BCL method that has well-known list of exceptins.
- BinaryLoader.cs is fine as is.
- TensorflowUtils.cs seems to catch a very specific exception and shoudl be fine as well,

**Comment by najeeb-kazmi** [comment]
Reviewing this code, found it doesn't violate the guidelines.

No C code. `/Eha` flag is not used.`HandleProcessCorruptedStateExceptionsAttribute` is not used. 

As far as the last point is concerned (Recover only on exceptions that your application can handle safely, and let all other exceptions pass through.):

- `CmdParser` reports bad value and returns `false` after the catch block.
- `AssemblyLoadingUtils` return null if there is an exception in loading an assembly.
- Lines in `IFileHandle` and `Repository` are inside a `Dispose()` method.
- `BinaryLoader` and `TensorFlowUtils` are fine as they catch very specific exceptions.
