### ISSUE TITLE
Normalize Transform on In-Memory Data Returns Zero

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#3201]
Given the code below:

```csharp
static void RunNormalizeExample()
{
    MLContext mlContext = new MLContext();

    SampleData[] inMemoryCollection = new SampleData[]
    {
        new SampleData {Features = new float[] {5.1f,3.5f,1.4f}}
    };

    IDataView data = mlContext.Data.LoadFromEnumerable<SampleData>(inMemoryCollection);

    IEstimator<ITransformer> dataPrep = mlContext.Transforms.Normalize("Features");
        
    ITransformer dataPrepTransformer = dataPrep.Fit(data);

    IDataView transformedDataView = dataPrepTransformer.Transform(data);

    var transformedFeatures = transformedDataView.GetColumn<float[]>(mlContext, "Features").ToList();
}
```

Where the schema for `SampleData` is the following:

```csharp
public class SampleData
{
    [VectorType(3)]
    public float[] Features { get; set; }
    public float Label { get; set; }
}
```

The values in `transformedFeatures` which are the normalized values using the default (MinMax) implementation of `Normalize` are all zero.

![image](https://user-images.githubusercontent.com/46974588/55562853-cf1ded80-56c2-11e9-8ee4-d178168d7876.png)

**Comment by luisquintanilla** [comment]
Changed Title (removed v0.11). Tested with `1.0.0-preview` and got the same result. This is the updated code

```csharp
static void RunNormalizeExample()
{
    MLContext mlContext = new MLContext();

    SampleData[] inMemoryCollection = new SampleData[]
    {
        new SampleData {Features = new float[] {5.1f,3.5f,1.4f}}
    };

    IDataView data = mlContext.Data.LoadFromEnumerable<SampleData>(inMemoryCollection);

    IEstimator<ITransformer> dataPrep = mlContext.Transforms.NormalizeMinMax("Features");
        
    ITransformer dataPrepTransformer = dataPrep.Fit(data);

    IDataView transformedDataView = dataPrepTransformer.Transform(data);

    var transformedFeatures = transformedDataView.GetColumn<float[]>("Features").ToList();
}
```

**Comment by Ivanidzo4ka** [comment]
Well, NormalizeMinMax suppose to convert your features to range for [0;1].
And it's a transform which observe all data, and build boundaries based on observation and picks proper scale and offset for each slot in your vector.
Since your data contains only one vector, it's hard to build boundaries, so we just scale everything to 0.

Maybe we should change behavior and instead of mapping it to zero, map it to one, since current behavior is not super helpful. In same time, I'm not sure what is expectation for normalization of one row.

**Comment by luisquintanilla** [comment]
Thanks for the clarification @Ivanidzo4ka. That makes sense given what the expected output range is.

**Comment by sfilipi** [comment]
Closing since the question got answered.
