### ISSUE TITLE
LoadColumn Attribute Inconsistent Behavior for Vector Properties Between File and In-Memory Sources

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#3202]
Given the following data model / schema where `Features` is a float vector:

```csharp
public class IrisData
{
    [LoadColumn(0,2)]
    public float Features { get; set; }
    [LoadColumn(3)]
    public float Label { get; set; }
}
```

When loading data from a file and applying transformations, there are no errors and transforms work as expected. However, when trying to use the same data model / schema to create and score with in-memory data, there are errors as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/46974588/55563915-caf2cf80-56c4-11e9-92e6-016c4932b9d7.png)

Workarounds both involve the use of the `VectorType` attribute on the property that loads columns together. Two suggestions are:

a) Add the `VectorType` attribute to the original model and change property type to `float[]`

```csharp
public class IrisData
{
    [LoadColumn(0,2)]
    [VectorType(3)]
    public float[] Features { get; set; }
    [LoadColumn(3)]
    public float Label { get; set; }
}
```

a) In addition to the original input class `IrisData` that was used to load from a file and train the model, create a new input class (IrisDataFlotArrayValues) to define the data model / schema for in-memory data. This new class adds the `VectorType` attribute to the property that loads columns together and changes the property type from a `float` to `float[]`.

```csharp
public class IrisDataFloatArrayFeatures{
    [LoadColumn(0,2)]
    [VectorType(3)]
    public float[] Features { get; set; }
    [LoadColumn(3)]
    public float Label { get; set; }
}
```

Since `LoadColumn` works for file data, it would be preferable to reuse the same data model / schema for in-memory data. Additionally, simply converting the property type to `float[]` without the `VectorType` attribute does not work when trying to apply transforms since the framework does not automatically pick up that the `float[]` property is a vector like it otherwise would with `LoadColumn` annotation leaving it to the user to manually convert the property to a vector.

**Comment by sfilipi** [comment]
Seems related to #3065

**Comment by luisquintanilla** [comment]
Adding @codemzs

**Comment by frank-dong-ms** [comment]
VectorType is not necessary in this case, change the Class to below will work for both cases:

public class IrisData
{
    [LoadColumn(0,2)]
    public float[] Features { get; set; }
    [LoadColumn(3)]
    public float Label { get; set; }
}

I'm not sure why we allow below definition when using text loader at first place, to me the definition itself is contradiction (can't be float and vector at same time):
[LoadColumn(0,2)]
public float Features { get; set; }

below logic for text loader seems exists since we create this repro:
https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs#L660-L681

**Comment by frank-dong-ms** [comment]
I think we should encourage user to use pattern that works in both text loader and in memory data with consistent definition like below:

```csharp
public class IrisData
{
    [LoadColumn(0,2)]
    public float[] Features { get; set; }
    [LoadColumn(3)]
    public float Label { get; set; }
}
```

**Comment by frank-dong-ms** [comment]
At current stage I prefer not to change the behavior of text loader as we might break user's code in similar case. 

Close this issue now as seems no further action required. CC @harishsk
