### ISSUE TITLE
API reference - XML documentation template for transforms

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#3204]
The XML documentation for the transforms should contain information about the schema: requirements about the type of the columns to work on, and information about the type of the columns produced. 

@shmoradims

**Comment by wschin** [comment]
I'd suggest to document `GetOutputSchema` function and transformer's XML can reference `GetOutputSchema`'s document.

**Comment by singlis** [comment]
Referencing #3127 as this feels same or related, maybe we could track this work under one issue? I think there are going to be a number of subsections that will need to be tracked. And should this go on the transforms? Or the extensions?

**Comment by sfilipi** [comment]
> I'd suggest to document `GetOutputSchema` function and transformer's XML can reference `GetOutputSchema`'s document.

It won't work, because GetOutputSchema is on the base class, and is calling GetOutputSchemaCore of every class, which is internal. 
Also the types of the columns for the input columns need to be documented.

**Comment by sfilipi** [comment]
Proposal for the transforms XML template, mirroring the trainers template from issue: #3218, 

1- XML  on Transform extension method:
- **Summary** - One line description of what the transform does. 
- **Remarks** - See cref the estimator for more details. 

- **Parameters**: 
inputColumnName - Name of column to transform. If set to <see langword="null"/>, the value of the <paramref name="outputColumnName"/> will be used as source. 
The data type on this column should be `<ref required data type.>` | The data type on this column can be any type.
- **Example**

2 - XML of the Estimator, Transformer 
- **Summary** - One line description of what the transform does.
- **Remarks** - More details about the transform and its implementation.
Does it do a pass through the data? Yes/No
Is convertible to Onnx format? Yes/No
Additional NuGet: "Link to NuGet" OR None of all that are included already in Microsoft.ML
- SeeAlso cref the extension method for an example usage.

**Comment by natke** [comment]
Looks good @sfilipi. One small comment: for the summary of the extension method, would we want to say: "Create an xxx transform ..."?

**Comment by artidoro** [comment]
Shouldn't it say "Create an xxx **estimator**" instead of "transform"?
@sfilipi

**Comment by sfilipi** [comment]
> Shouldn't it say "Create an xxx **estimator**" instead of "transform"?
> @sfilipi

Updated, thanks @Artidoro.

**Comment by shmoradims** [comment]
* Do we need the remarks? Can the summary just say: "Create an <cref the estimator>"?
* Let's add a short description of the transform in the summary, similar to trainers.

**Comment by sfilipi** [comment]
List of transforms to sign up for:

| MLContext.Transforms (root) |  API Owner |
| --------------------------------  | ----- |
CopyColumns|  |
Concatenate|   |
DropColumns|   |
SelectColumns|   |
Normalize|  |
CustomMapping |   |
IndicateMissingValues |    | 
ReplaceMissingValues  |  | 
ConvertToGrayscale  |   | 
LoadImages  |   | 
ExtractPixels |   | 
ResizeImages |    |
ConvertToImage  |    | 
IidChangePointEstimator  |  | 
IidSpikeEstimator |   | 
SsaChangePointEstimator  |   | 
SsaSpikeEstimator  |  | 
ApplyOnnxModel |    | 
DnnFeaturizeImage |   | 
NormalizeGlobalContrast|  | 
NormalizeLpNorm|   | 
ApproximatedKernelMap|   | 
CalculateFeatureContribution | |

**Comment by sfilipi** [comment]
Other catalogs:

| MLContext.Transforms.Categorical |  API Owner |
| --------------------------------  |  ----- |
| OneHotEncoding |   |
| OneHotHashEncoding |   |

| MLContext.Transforms.Conversion |  API Owner |
| --------------------------------  |  ----- |
| Hash |  |
| ConvertType |  |
| MapKeyToValue |   |
| MapKeyToVector |  |
| MapValueToKey |  |
| MapKeyToBinaryVector |  |

| MLContext.Transforms.FeatureSelection | API Owner |
| --------------------------------  |  ----- |
| SelectFeaturesBasedOnMutualInformation  | need a better example to show MI computation. something like [this  ](https://www.researchgate.net/post/How_can_i_calculate_Mutual_Information_theory_from_a_simple_dataset)| Senja |
| SelectFeaturesBasedOnCount |  Senja |

| MLContext.Transforms.Text| API Owner |
| --------------------------------  |  ----- |
| FeaturizeText |    |
| TokenizeCharacters |    |
| NormalizeText |    |
| ExtractWordEmbeddings |    |
| TokenizeWords |    |
| ProduceNgrams |    |
| RemoveDefaultStopWords |   |
| RemoveStopWords |    |
| ProduceWordBags |    |
| ProduceHashedWordBags |   |
| ProduceHashedNgrams |    |
| LatentDirichletAllocation | Senja   |

For the Data catalog, all API's documentations needs to be augmented with suggestions for when would one use this API.

| MLContext.Data |  API Owner |
| --------------------------------  | ----- |
| LoadFromEnumerable | Senja  |
| CreateEnumerable | The second overload of this API is a P4 scenario. the use case for that API would be: users has a model which has slot names preserved for the features, and when they load the models, they also get the schema out of the loaded model and pass that schema, together with the TRow type they want to load the data to this API. This API will then populate the Annotations (former metadata) for the feature column. |   |
| BootstrapSample |   |
| Cache |   |
| FilterRowsByColumn |   |
| FilterRowsByKeyColumnFraction |   | 
| FilterRowsByMissingValues |   | 
| ShuffleRows |   | 
| SkipRows |   | 
| TakeRows |  | 

| Other | API Owner |
| --------------------------------  | ----- |
| Permutation Feature Importance |  |

**Comment by shmoradims** [comment]
Finished 4/21 9:29pm. Great team work.
