### ISSUE TITLE
API reference - Remove Microsoft.ML prefix from samples' namespace

### ISSUE THREAD

**Issue by shmoradims** [dotnet/machinelearning#3205]
Currently the samples are written like this:

```csharp
namespace **Microsoft.ML**.Samples.Dynamic.*
{ 
}
```
This is causing the samples to not require `using Microsoft.ML`. We want to drop the Microsoft.ML prefix from samples and write them like this:

```csharp
namespace Samples.Dynamic.*
{ 
}
```

**Comment by codemzs** [comment]
I fixed for all the samples and checked-in my change.
