### ISSUE TITLE
NaiveBayes doesnt produce meaningful result on simple dataset

### ISSUE THREAD

**Issue by ganik** [dotnet/machinelearning#3226]
Use the same dataset as in  PR #3159 for NB but get garbage results no matter how good is separation among classes

**Comment by codemzs** [comment]
This is not a bug. Naive Bayes considers features to be binary in our implementation, that is how features are binned. In this sample pipeline all your features are greater than equal to zero that means the feature histogram for each class will be of the same size hence you are seeing this behavior. Please modify your code to have feature values take either negative or positive values.

When we were implementing Naive Bayes we thought about this case of features taking continuous values and for that we would need to implement Gaussian distribution to bin the features. However it wasn't a requirement at the time.
