### ISSUE TITLE
Overflow in MultiClassNaiveBayes

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning#3228]
We're storing the count of rows in an `int`. This causes an overflow for large datasets. In my case, Criteo 1TB w/ 4.4B rows. Recommend changing to a `long`.

https://github.com/dotnet/machinelearning/blob/d2bf3e72fa935b12644b0a695ad0d044a8077a83/src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs#L242

Error:
```
Unexpected exception: Arithmetic operation resulted in an overflow., 'System.OverflowException'
   at System.Linq.Enumerable.Sum(IEnumerable`1 source)
```

**Comment by Sandy4321** [comment]
can you share code for this NB for 1TB data
if somebody tried to run locally ?
like
https://github.com/rambler-digital-solutions/criteo-1tb-benchmark

**Comment by Lynx1820** [comment]
@justinormont  Can you share your data?

**Comment by justinormont** [comment]
@Lynx1820: This is the Criteo 1TB dataset. I sent you a link internally.

@Sandy4321: You can use the AutoML․NET CLI to create the ML․NET C# code & project (data loaders, pipeline, learner) for the dataset by running on a smaller sample of the dataset. Then change the learner to Naive Bayes. I have run the Criteo 1TB dataset using the CLI; it works well; for a full run you'll want to add `--cache off` to disable in-memory caching.

**Comment by Sandy4321** [comment]
Do you mean that classifier model will be built only on small data
And under running on full data you mean only prediction?

**Comment by justinormont** [comment]
@Sandy4321: You'll  train on the subsample, just to have it produce the C# code for a pipeline for the dataset. After switching the trainer to Naive Bayes, you can then use the generated C# code to train a model from the pipeline on full 1TB dataset.

As a side note, the Target Encoding (dracula) transform works well on the Criteo 1TB dataset: https://docs.microsoft.com/en-us/archive/blogs/machinelearning/now-available-on-azure-ml-criteos-1tb-click-prediction-dataset ([slides](https://www.slideshare.net/SessionsEvents/misha-bilenko-principal-researcher-microsoft))

This is being added in PR by @yaeldekel: https://github.com/dotnet/machinelearning/pull/4514.

Also, ML․NET has many strong trainers which the AutoML will try for you; Naive Bayes is rarely the winning algo.

**Comment by justinormont** [comment]
@Lynx1820: For fixing this issue, it may be as easy as moving a set of variables from `int` to `long`:
https://github.com/dotnet/machinelearning/blob/77e7f98c48a692bba0c0316e6c2c54139e4e62d9/src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs#L241-L246 

And a few other `int` variables:
https://github.com/dotnet/machinelearning/blob/77e7f98c48a692bba0c0316e6c2c54139e4e62d9/src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs#L149

**Comment by mstfbl** [comment]
Here are the min/max values for int, uint and long:

> int.MaxValue:    2,147,483,647
> int.MinValue:   -2,147,483,648
> long.MaxValue:   9,223,372,036,854,775,807
> long.MinValue:  -9,223,372,036,854,775,808

As the aforomentioned Criteo 1 TB database has around ~4.4 billion rows, it makes sense to utilize long arrays and matrices for storing labels and features in their respective histograms.

**Comment by Sandy4321** [comment]
Good idea
