### ISSUE TITLE
Deep Learning with ML.NET

### ISSUE THREAD

**Issue by premingiet** [dotnet/machinelearning#3229]
I checked available documentation for ML.NET and didn't find any help regarding Deep Learning Framework. Is Deep Learning possible with ML.NET ? Like CAFFE deep learning framework ? I need Deep learning framework for Dot Net. Is it possible with ML.NET ?

**Comment by jwood803** [comment]
You can in the sense of using existing deep learning models in ML.NET to make predictions. The [samples repository](https://github.com/dotnet/machinelearning-samples#deep-learning) has quite a few samples that use deep learning. Hope that helps!

**Comment by premingiet** [comment]
Well i looked through sample repository, but it consumes existing tensorflow models. What i needed was to be able to create my own deep learning model using ML.NET and then train and deploy that model as and when needed. I guess currently creating tensorflow deep learning model is not possible with ML.NET

**Comment by Gregor959** [comment]
if that is the case it should not state  "Classify images (e.g. broccoli vs pizza) using a TensorFlow deep learning algorithm."    The wording "using a learning library" is incorrect... it can only uses the "output data from software that uses the tensor flow library" .  I am afraid this library will detract from current efforts like [TensorFlow.NET](https://github.com/SciSharp/TensorFlow.NET) and [TensorFlow.Fsharp](https://github.com/fsprojects/TensorFlow.FSharp) .

**Comment by harishsk** [comment]
ML.NET is not a generic deep learning framework. But the latest version has apis for image classification. You can find details [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.vision?view=ml-dotnet)
Please reopen the issue if you need more information.
