### ISSUE TITLE
Return Centroids for KMeansPlusPlusClusterer After Training

### ISSUE THREAD

**Issue by lqdev** [dotnet/machinelearning#323]
### Issue

Once training is complete on a KMeansPlusPlusClusterer algorithm in the `LearningPipeline`, provide a method of accessing the centroids.

**Comment by Ivanidzo4ka** [comment]
DRI RESPONSE: This is question about legacy API.
In new API this is possible: see https://github.com/dotnet/machinelearning/blob/a285f8d5db15cd8bf77f3c03763bce16642f902b/test/Microsoft.ML.StaticPipelineTesting/Training.cs#L661
I'm intent to close this issue within few days if no one objects.

**Comment by lqdev** [comment]
That works. Thanks @Ivanidzo4ka
