### ISSUE TITLE
Expected vector<R4> Got R4

### ISSUE THREAD

**Issue by Pieter-1337** [dotnet/machinelearning#3270]
Hi, I am currently trying to create a Model with a regression trainer

However it seems I am loading my data incorrectly how should I proceed to load my "YearsExperience" as a Vector<R4> instead of a regular R4

Sample of data: 
YearsExperience;Salary
1.1;39343.00

The way I load the data as an IDataView object
`   IDataView trainingDataView = mlContext.Data.LoadFromTextFile<SalaryData>
               (
                   path: "Data/SalaryData.csv", hasHeader: true, separatorChar: ';'
               );
`

Also I wonder is my pipeline correctly built? I am not sure about the mlContext.Transforms.Normalize("YearsOfExperience") at the start

`var pipeline = mlContext.Transforms.Normalize("YearsExperience")
                    .Append(mlContext.Transforms.Concatenate
                    (
                      "Features", "YearsExperience"  
                    ))
                    .AppendCacheCheckpoint(mlContext)
                    .Append(mlContext.Regression.Trainers.StochasticDualCoordinateAscent(labelColumnName: "Salary", featureColumnName: "YearsExperience"));
`

**Comment by rauhs** [comment]
> featureColumnName: "YearsExperience"

=> Should be "Features"

**Comment by Pieter-1337** [comment]
Ha yes It seems I am blind thank you good sir!

**Comment by rogancarr** [comment]
Closing this, as it seems to be resolved. Please re-open if you wish to discuss more.
