### ISSUE TITLE
Default NuGet page goes to older preview instead the latest version (RC)

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning#3271]
At the NuGet site, when you try to go to https://www.nuget.org/packages/Microsoft.ML/
it redirects to an older version (0.11) instead of the latest version (1.0.0-preview).

![image](https://user-images.githubusercontent.com/1712635/55897527-8a3c0000-5b75-11e9-8b22-e68206f393b2.png)

**Comment by CESARDELATORRE** [comment]
@terrajobst - Immo, any idea on how this could be fixed at the NuGet page?
Can you add the right folks focusing on the NuGet site?

**Comment by terrajobst** [comment]
I think the view defaults to latest stable. I don't think you can change that. /cc @anangaur @rrelyea

**Comment by CESARDELATORRE** [comment]
@shauheen, @eerhardt  - Then, we should probably mark 1.0.0-preview the same way than previous released versions such as 0.11 (stable)?

**Comment by eerhardt** [comment]
Maybe we can just unlist all the versions before `1.0.0-preview`? No one should be using those anymore.

We will probably want them to be unlisted once we ship `1.0.0` anyway.

**Comment by CESARDELATORRE** [comment]
@eerhardt - Many folks and even customers with code in production might still be using older versions for some time. I think we should maintain the olde versions at least for some time?

**Comment by eerhardt** [comment]
Oh, you can never actually delete a NuGet package from nuget.org.  They will always be there forever.

"Unlisting" a version is just so it doesn't show up on the default page, or in search results.

https://docs.microsoft.com/en-us/nuget/policies/deleting-packages
