### ISSUE TITLE
IDataView Type system needs to be extensible to properly support image, date, and other types

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#3274]
To support loading `Image` from `IDataView` (as shown in #3263), user must modify ML.NET code, which means our type system is not extensive. Do we want to invest on the extensibility of ML.NET type system?

**Comment by TomFinley** [comment]
Perhaps we ought to change this to, the reflection based mechanism by which things like prediction engine *specifically* are not extensible to new types -- a problem that would not exist but for the fact that the DataView type system *is* extensible, which makes the title a bit misleading? What you think?

I also I have a possibly workable solution to that specific problem in #3263, let me know your reactions.

**Comment by glebuk** [comment]
There are a few issues that are all related to this problem:
#3369, #3460, #3582, #2121, #2495, #3582
The fundamental problem is that in several places in our system,  our types are hardcoded and are not extensible.  For example, if we need to add full support of images, we would need to update:

- converters between IEnumerable<T> <-> IDataView, 
- PredictionEngine<> 
- API Utils, 
- Schema utils 
- etc.

What we need is a dependency-injection mechanism to allow component developers to inject definitions of types supported by the system.  For an example of hard-coded implementation, check out PR #3263.  Note @TomFinley's comment on different options on how to do this properly



limited to

**Comment by CESARDELATORRE** [comment]
Agree. I think this is "a must" feature (pre-requisite) in ML.NET (support for in-memory images) in order to be able to release the TensorFlow and ONNX packages as v1.0 (Currently 0.12).

Note that this implementation would be centralized (not specific within the TensorFlow or ONNX packages), though, so it'll need a new version for ML.NET itself, too? Minor version?
