### ISSUE TITLE
Tokenizer option for Wordbag Transforms

### ISSUE THREAD

**Issue by bsoman3** [dotnet/machinelearning#3276]
### Issue
Trying to import the following functionality from TLC:
~~~~
xf=WordBagTransform{    
    col=Features:CatFeatures    
    tok=WordTokenizeTransform{      sep=comma    }    
    max=1000000000    
    weighting=TfIdf  } 
~~~~

I would have expected this to work:
~~~~
var pipeline =
    mlContext.Transforms.Text.TokenizeWords("CatTokens", "CatFeatures", separator) //comma only
    .Append(mlContext.Transforms.Text.ProduceWordBags("Features", "CatFeatures", 
        ngramLength: 1, allLengths: true, maxNumTerms: 1000000000, 
        weighting: NgramExtractingEstimator.WeightingCriteria.TfIdf))
    ;
~~~~
### What Happened 
It seems that ProduceWordBags is tokenizing under the hood. [link] (https://github.com/dotnet/machinelearning/blob/fc89745fd9d5d7dcca875570bd3b9ffc981f2184/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Text/ProduceWordBags.cs)
The user does not have any option to specify the separator. TLC uses space by default, but provides the option to change that.

### Expected Behavior
The user should be able to produce bag of counts of ngrams on tokens such that they select how the tokenization is done.

I would expect either TokenizeCharacters() + ProduceNgrams() or TokenizeWords + ProduceWordbags to provide this functionality

**System information**
* Product: dotnet-ml-api
* GitHub Login: @bsoman3
* Microsoft Alias: bhsoman

- **OS version/distro**:Windows 10 Enterprise
- **.NET Version (eg., dotnet --info)**: 4.6.1

**Comment by zeahmed** [comment]
You can follow the following example which does exactly what you are trying to achieve.

https://github.com/dotnet/machinelearning/blob/51b10fc6a004b08b3a07d046db10fa277a8cffac/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Text/ProduceNgrams.cs#L37

**Comment by zeahmed** [comment]
I am assuming this is sufficient for you need. I am closing it. Reopen it if necessary.
