### ISSUE TITLE
Prior Trainer does not accept bool label column

### ISSUE THREAD

**Issue by artidoro** [dotnet/machinelearning#3283]
The template for our binary classification samples uses a bool label column. This template is used by a number of our binary classification trainers.

`PrriorTrainer` does not however accept a boolean label column. It only accepts a float label column. Here is the code that checks that the label column is of type float:
https://github.com/dotnet/machinelearning/blob/55d911dc5f50bf45bfffe50bf9f0ee3ffb14c369/src/Microsoft.ML.StandardTrainers/Standard/Simple/SimpleTrainers.cs#L233

In order to be consistent with the rest of the binary classification trainers, we should allow the label column to be of boolean type for `PriorTrainer`.

**Comment by TomFinley** [comment]
Unfortunate. This seems to be a duplicate of #3119, currently open and assigned to @codemzs. Maybe you can check on his status, and see if he's actually working on a fix?

**Comment by codemzs** [comment]
Yep, I’m working on the fix. Been fixing bugs one by one lately. Will have a PR today.

**Comment by TomFinley** [comment]
Great. Going to mark this one as provisionally duplicate, maybe close if you agree @artidoro ?
