### ISSUE TITLE
Async Main is not taken as entrypoint in c# 7.0

### ISSUE THREAD

**Issue by prisar** [dotnet/machinelearning#331]
### System information

- **OS version/distro**: Windows Server 2016 
- **.NET Version (eg., dotnet --info)**: Core 2.0

### Issue

- **What did you do?**
Tried to use static async Main
- **What happened?**
Couldn't build
- **What did you expect?**
Build without error
### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by lqdev** [comment]
I think this is more of a C# language version number. I want to say it won't work with anything under 7.1. I had the same issue, but if you call `async` methods synchronously by accessing the `.Result` property from `Main` you should be okay. The training and model building work just fine.

**Comment by prisar** [comment]
okay @lqdev, thanks
