### ISSUE TITLE
TextLoader is different in 0.1.0 and 0.2.0

### ISSUE THREAD

**Issue by prisar** [dotnet/machinelearning#332]
### System information

- **OS version/distro**: 2016
- **.NET Version (eg., dotnet --info)**: 2.0

### Issue

- **What did you do?**
Trying to use `new TextLoader<IrisData>(dataPath, separator: ",")` in 0.2.0
- **What happened?**
Shows error
- **What did you expect?**
Please give a documentation for new changes in 0.2.0
### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by helloguo** [comment]
Maybe this is what you want?
https://github.com/dotnet/machinelearning/blob/master/docs/release-notes/0.2/release-0.2.md
https://github.com/dotnet/machinelearning-samples/tree/master/samples.

`new TextLoader(TrainDataPath).CreateFrom<IrisData>()`

**Comment by codemzs** [comment]
The text loader API has changed in 0.2.

**Comment by Saibamen** [comment]
Should be closed
