### ISSUE TITLE
AutoML feature request: Provide hooks to enable more usable APIs

### ISSUE THREAD

**Issue by vinodshanbhag** [dotnet/machinelearning#3320]
Current AutoML APIs look like this
mlContext.Auto.CreateRegressionExperiment() 
mlContext.Auto.InferColumns() 

This makes us like we are shipping organization boundaries!
So we propose we ship the following.
mlContext.Regression.CreateAutoExperiment()
mlContext.Data.AutoInferColumns()

The problem with implementing this is that an extension method needs to be implemented on RegressionCatalog and not MLContext -- this means that automl code cant have have access to mlContext - but it needs access to mlContext. Please enable same.

**Comment by luisquintanilla** [comment]
Thanks for the feedback. We've recently updated our AutoML implementation based on FLAML.

For more information, see the [blog post](https://devblogs.microsoft.com/dotnet/whats-new-with-mldotnet-automl/#automl-updates) and [sample notebooks](https://github.com/dotnet/csharp-notebooks/blob/main/machine-learning/03-Training%20and%20AutoML.ipynb) 

Closing this issue.
