### ISSUE TITLE
Image transfomers don't dispose source image.

### ISSUE THREAD

**Issue by codemzs** [dotnet/machinelearning#3327]
Image transformers such as grayscale and resize have images as input. After they process input images to produce output image they should dispose the input image because if they don't then we are at mercy of garbage collector cleaning the bitmap objects and if the GC has not done that and some code in the same process tries to open the same image referenced by the bitmap object that is not disposed then we get file in use exception.

**Comment by glebuk** [comment]
Ensure that also we are opening image in read-only mode so that this is not an exclusive lock.
