### ISSUE TITLE
System.DllNotFoundException: Unable to load DLL 'CpuMathNative'

### ISSUE THREAD

**Issue by prisar** [dotnet/machinelearning#333]
### System information

- **OS version/distro**: Windows Server 2016 Standard
- **.NET Version (eg., dotnet --info)**: Core 2.0

### Issue

- **What did you do?**
When trying to load model from a file `var model = PredictionModel.ReadAsync<IrisData, IrisPrediction>(modelPath).Result;` gives DllNotFoundException while running in windows container.
- **What happened?**
Internal Server Error
- **What did you expect?**
Model should be loaded in model variable.
### Source code / logs
```
System.DllNotFoundException: Unable to load DLL 'CpuMathNative': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.ML.Runtime.Internal.CpuMath.Thunk.DotU(Single* pa, Single* pb, Int32 c)
   at Microsoft.ML.Runtime.Internal
1000
.CpuMath.SseUtils.DotProductDense(Single[] a, Single[] b, Int32 count)
   at Microsoft.ML.Runtime.Learners.MulticlassLogisticRegressionPredictor.PredictCore(VBuffer`1& src, Single[]& dst)
   at Microsoft.ML.Runtime.Learners.MulticlassLogisticRegressionPredictor.<GetMapper>b__30_0[TSrc,TDst](VBuffer`1& src, VBuffer`1& dst)
   at Microsoft.ML.Runtime.Data.PredictedLabelScorerBase.EnsureCachedPosition[TScore](Int64& cachedPosition, TScore& score, IRow boundRow, ValueGetter`1 scoreGetter)
   at Microsoft.ML.Runtime.Data.MultiClassClassifierScorer.<>c__DisplayClass14_0.<GetPredictedLabelGetter>b__0(UInt32& dst)
   at Microsoft.ML.Runtime.Data.KeyToValueTransform.KeyToValueMap`2.<>c__DisplayClass7_0.<GetMappingGetter>b__0(TValue& dst)
   at Microsoft.ML.Runtime.Data.DataViewUtils.Splitter.Consolidator.<>c__DisplayClass4_1.<ConsolidateCore>b__2()

```Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by jusso-dev** [comment]
Change your project to compile to 64x, CpuMathNative is a 64x run time dependant library

**Comment by chrismckelt** [comment]
Did you run build.cmd before running it?  I got this issue & needed to pull the solution down again & rerun build.cmd to be able to correctly build the solution

**Comment by jusso-dev** [comment]
That's probably solving the same issue. If building the project outside of a 64x runtime it won't work, point blank.

**Comment by chrismckelt** [comment]
An AnyCPU assembly will JIT to 64 bit code when loaded into a 64 bit process and 32 bit when loaded into a 32 bit process so no need to change I think - I had this on Windows Server 2016 Standard & reinstalled the tools & all was good

**Comment by PaulDMendoza** [comment]
Actually, this issue solved/comment my problem. Had to install the Visual Studio C++ update. 

https://github.com/dotnet/machinelearning/issues/605#issuecomment-408947401

**Comment by Ivanidzo4ka** [comment]
DRI RESPONSE: This issue looks like answered. I'm planning to close it within few days, if no one object to that.

**Comment by Finansnet** [comment]
In my case problem was on some particular machines. The same application was working fine on development ones, but did not work on production environment. Problem was solved by installing Visual C++ Redistributable 2017 on production server.

Marek

**Comment by samcode22** [comment]
Exception thrown: 'System.DllNotFoundException' in Microsoft.ML.CpuMath.dll
An exception of type 'System.DllNotFoundException' occurred in Microsoft.ML.CpuMath.dll but was not handled in user code
Unable to load DLL 'CpuMathNative': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Trying to implement sentimental analysis on comments in ASP.NET MVC Web Application(.NET Framework)  although it is seen in solution explorer..and have kept solution platform as AnyCPU.Also tried x86 and x64 but no change.
The error is pointing at this line:
            ModelOutput result = predEngine.Predict(input);

**Comment by ArnieBerg** [comment]
See https://github.com/dotnet/machinelearning/issues/4870.
