### ISSUE TITLE
Documentation enhancement on the pipeline's impack on output schema

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/machinelearning#3334]
I am looking over the various samples provided in the Cookbook as well as the sample projects. 
none of them are actually going into the detail of how powerful the creation of the training pipeline is when it comes to generating and populating a prediction.

Perhaps one could add some Dokumentation as to the differences between the networks as well as the population and addressing the naming. One could, with a multiclass state the accuracy of the predicted class as one does now, one could also show the nearest neighbour and the combined weight of both. The patient could have both diseases, the client could like both products with a "likely hood" in "that order" with that "accuracy".  

I'd think that the [Cookbook ](https://github.com/dotnet/machinelearning/blob/master/docs/code/MlNetCookBook.md)would be an ideal location for this. in a section with a title say "**how do I Interpret a generated single prediction**"

**Comment by sfilipi** [comment]
Thanks for the suggestion @PeterPann23. I believe some of those ideas should go towards creating more samples in the [machinelearning-samples](https://github.com/dotnet/machinelearning-samples) repo.

**Comment by PeterPann23** [comment]
Not sure if I am the right person to make that sample...
