### ISSUE TITLE
Splitter/consolidator worker encountered exception

### ISSUE THREAD

**Issue by martasp** [dotnet/machinelearning#3335]
### System information

OS version/distro: Windows 10
.NET Version (eg., dotnet --info):  dotnet core 2.2
Version : ML.NET v1.0.0-preview

### Issue

- **What did you do?** 
I used tensorflow model + SDCA sample to train my own data
- **What happened?**
 when i have 800 labels it gives this error, but work when there are 100 labels in tags.tsv file.

### Source code / logs
Training classification model
#############################

EXCEPTION
#########
Splitter/consolidator worker encountered exception while consuming source data

Press any key to finish.

**Comment by martasp** [comment]
Found more info  than images cant be indexed pixel format
EXCEPTION
#########
A Graphics object cannot be created from an image that has an indexed pixel format.
Parameter name: image

**Comment by sfilipi** [comment]
@martasp thanks for reporting. Is it possible to share your pipeline, and the data that causes the exception?

**Comment by codemzs** [comment]
@martasp If you have tensorflow transfomer please make sure to have `addBatchDimensionInput: true` as an argument. See below for an example:

```chsarpcode 
var pipeline = mlContext.Model.LoadTensorFlowModel(modelLocation).ScoreTensorFlowModel(
                new[] { nameof(OutputScores.output) },
                new[] { nameof(TensorData.input) }, addBatchDimensionInput: true);
```

**Comment by sefatanam** [comment]
same issue but `addBatchDimensionInput:true` after doing not solve my problem
