### ISSUE TITLE
Cannot build the source code using Visual Studio 2019

### ISSUE THREAD

**Issue by bhrnjica** [dotnet/machinelearning#3336]
### System information

- **OS version/distro**: Windows 10 1809
- **.NET Version (eg., dotnet --info)**: .NET Core 2.1
- **Visual Studio version** VS2019

### Issue

- I am trying to build the source code using Visual Studio 2019. I have downloaded the source code and followed the [developer guide ](https://github.com/dotnet/machinelearning/blob/master/docs/project-docs/developer-guide.md), and run the following ``build.cmd -Release -TargetArchitecture:x64``, the following errors appeared:
```
  **********************************************************************
  ** Visual Studio 2019 Developer Command Prompt v16.0.1
  ** Copyright (c) 2019 Microsoft Corporation
  **********************************************************************
  [vcvarsall.bat] Environment initialized for: 'x86_x64'
  Commencing native build of dotnet/machinelearning

  Calling "C:\sc\github\machinelearning\src\Native\\gen-buildsys-win.bat" "C:\sc\github\machinelearning\src\Native\" "15
 2017" x64
  CMake Error in CMakeLists.txt:
  -- Configuring incomplete, errors occurred!
  See also "C:/sc/github/machinelearning/bin/obj/x64.Release/Native/CMakeFiles/CMakeOutput.log".
  Failed to generate native component build project!
    Generator

      Visual Studio 15 2017 Win64

    could not find any instance of Visual Studio.

C:\sc\github\machinelearning\src\Native\build.proj(67,5): error MSB3073: The command ""C:\sc\github\machinelearning\src\
Native\build.cmd" Release x64 --mkllibpath C:\sc\github\machinelearning\packages/mlnetmkldeps\0.0.0.9\runtimes\win-x64\n
ative" exited with code 1.

Build FAILED.

C:\sc\github\machinelearning\src\Native\build.proj(67,5): error MSB3073: The command ""C:\sc\github\machinelearning\src\
Native\build.cmd" Release x64 --mkllibpath C:\sc\github\machinelearning\packages/mlnetmkldeps\0.0.0.9\runtimes\win-x64\n
ative" exited with code 1.
    0 Warning(s)
    1 Error(s)
```
Seems the build scripts are not updated in order to support Visual Studio 2019

**Comment by codemzs** [comment]
Quick unblock solution:

Please open the VS 2017/2015 developer command prompt and run build.cmd from there. Once native code is built you can open the sln file in VS 2019 and build managed code from there too.

**Comment by PeterPann23** [comment]
Hi, 

When I do that it seems to not find the directory that I have started it from.

***logs***
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.11
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86_x64'
Commencing native build of dotnet/machinelearning

Calling "D:\GIT\machinelearning\src\Native\\gen-buildsys-win.bat" "D:\GIT\machinelearning\src\Native\" "15 2017" x64
CMake Error: The source directory "D:/GIT/machinelearning/bin/obj/x64.Debug/Native/Win64 -B. -HD:/GIT/machinelearning/src/Native"" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Failed to generate native component build project!

D:\GIT\machinelearning\src\Native>

**Comment by codemzs** [comment]
Are you running build.cmd from the root? And what version of cmake do you have installed? Can you please paste anymore logs that you may have?

**Comment by bhrnjica** [comment]
Once I installed Visual Studio 2017 Community Edition along with currently installed Visual Studio 2019, I could successfully run ``build.cmd``, and then compile solution file using VS 2019.

Please, update build scripts to support VS2019.

**Comment by wschin** [comment]
I have the same problem honestly.

**Comment by wschin** [comment]
@bhrnjica, we recently added some fixes for supporting VS 2019, and I can build ML.NET using VS 2019 using my clean laptop (without VS 2017, 2015, etc installed). Thus, I believe this issue can be closed.
