### ISSUE TITLE
Math equations in docs

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#3337]
We need a formal way to write equations used in trainers and transforms. I personally like [Latex syntax](https://www.overleaf.com/learn/latex/Aligning_equations_with_amsmath). Any other comments please?

Example:
```latex
\sum_{i=1}^{\infty} \frac{1}{n^s}
```

[Example where this is needed in docs](https://github.com/dotnet/machinelearning/blob/059c761ca3b4f46a40d36c434c32733f063e7dab/src/Microsoft.ML.StandardTrainers/Standard/Online/AveragedPerceptron.cs#L46)

**Comment by natke** [comment]
@wschin, I've enabled latex formatting in the ml-api-docs repo. You can write latex format in markdown sections by enclosing the latex between `$  $` 

e.g. $\sum_{i=1}^{\infty} \frac{1}{n^s}$
