### ISSUE TITLE
RowGroupColumnName of ranking trainers options class defaults to null

### ISSUE THREAD

**Issue by artidoro** [dotnet/machinelearning#3365]
The `Options` class of the ranking trainers (`FastTree` and `LightGbm`) defaults to `RowGroupColumnName = null`.

This is:
1. Inconsistent with the simple constructor where `RowGroupColumnName` defaults to `GroupId`
2. Not desirable as in ranking the row group is very important for correct training

Here are the lines where the row group column name is set:
https://github.com/dotnet/machinelearning/blob/738e5d5a5b90f8c3a93c391bb8b2e0bcdad35cd0/src/Microsoft.ML.Data/Training/TrainerInputBase.cs#L106-L110

We need to update the default and align it with the simple constructor.

**Comment by artidoro** [comment]
I am afraid that this will require a breaking API change which at this point we can't do. This would be something that we should consider changing for 2.0.

**Comment by justinormont** [comment]
I would expect the ranking trainer to throw if it doesn't have a `RowGroupColumnName` defined.

Hence, I don't see this as a breaking change, since without it the user's pipeline (even if it runs) is broken as the result won't have utility. This questions our definition of a breaking API change.

**Comment by najeeb-kazmi** [comment]
Tracking in #4749.
