### ISSUE TITLE
No readme / guidance in Microsoft.ML.Samples

### ISSUE THREAD

**Issue by clauren42** [dotnet/machinelearning#3381]
Samples in https://github.com/dotnet/machinelearning/tree/master/docs/samples/Microsoft.ML.Samples
should have readme explaining available samples and how to use

**Comment by shmoradims** [comment]
@clauren42 Microsoft.ML.Samples is different from Cesar's samples repo. They are meant to be used through examples in [ML.NET API reference](https://docs.microsoft.com/en-us/dotnet/api/?view=ml-dotnet) like [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.binaryclassificationcatalog.calibratorscatalog.isotonic?view=ml-dotnet#examples), not through github. So, I don't think a readme file is necessary here.

**Comment by wschin** [comment]
@shmoradims is right. Those samples are organized on ML.NET's document site. They are API samples which appeares in associated APIs' docs (please see @shmoradims's links).
