### ISSUE TITLE
Documentation missing on prepairing training data

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/machinelearning#3382]
### Issue

The cookbook has plenty of samples of how to do steps, there is however no documentation that I found on how to approach the configuring a pipeline. 
There is no mention on the the choices of:
- Is it better to load all columns of a csv in separate named fields or in a single vector
- Should one normalize each field, when should one normalize it
- Should one combine all in one vector and normalize the whole vector
- how many fields are supported, 

**Error:**
I tried and played a Little with it and found that  when loading data as a vector or when loading the data via individual fieldnames one gets different metrics on the same data (tested against 1.6m rows).
When loading via a vector. no issue
when loading via fields, no issue
when loading it via properties the frameworks complains at the loader with a message stating that there are to many properties and it's not supported. 

**Expect**
I expect that all 3 would cause the same error, or all 3 would work as the resulting vector has the same size (35,630 elements). 

I would hope that the documentation gets updated reflecting the above points.

**Code*

```
IDataView GetDataView(MLContext mlContext, FileInfo trainingFile)
{
    var loader = mlContext.Data.CreateTextLoader<Mapper>(separatorChar:'|',hasHeader:false);
    return loader.Load(trainingFile.FullName);
}


public void ExecuteSDCA()
{
    var file = new FileInfo(@"data\Rows_100_.data");
    var dataView = GetDataView(mlContext, file);           


    var pipeline = mlContext.Transforms.Conversion.MapValueToKey(outputColumnName: KeyColumn, inputColumnName: Label)
            .Append(mlContext.Transforms.Concatenate(Features, Mapper.GetFieldNames()))
            //.Append(mlContext.Transforms.NormalizeMinMax(outputColumnName:Features, inputColumnName:RawFeatures))
            .Append(mlContext.MulticlassClassification.Trainers.SdcaMaximumEntropy(labelColumnName: KeyColumn, featureColumnName: Features, maximumNumberOfIterations:1))
            .Append(mlContext.Transforms.Conversion.MapKeyToValue(inputColumnName: KeyColumn, outputColumnName: PredictedLabel))
            .Append(mlContext.Transforms.CopyColumns(outputColumnName: Scores, inputColumnName: Score));
    //.AppendCacheCheckpoint(mlContext);

    var model = pipeline.Fit(dataView);           

}         

```
I have added the data and auto-generated class as well

[Mapper.zip](https://github.com/dotnet/machinelearning/files/3091256/Mapper.zip)

[Rows_100_.zip](https://github.com/dotnet/machinelearning/files/3091223/Rows_100_.zip)

**Comment by sfilipi** [comment]
Hi @PeterPann23 
thanks for the good feedback. We are currently working on updating the documentation of our components. We are marking the trainers that need normalization, in their API reference documentation, but your suggestion about adding it to the cookbook or a tutorial page on docs.microsoft.com  is a good one. 

cc @natke @JRAlexander @luisquintanilla

**Comment by PeterPann23** [comment]
do I close it?

**Comment by glebuk** [comment]
@PeterPann23 ,
The current approach would result in a very slow pipeline.  You need to load all features that are treaded the same as a single vector. that would speed up your training tremendously, as I mentioned before.
For a sample on how to read vector data, take a look at [multi-class sample](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/MulticlassClassification_mnist )
What you should do instead, is load the data as vector directly in the loader. the mapper class should look something like this:

      [LoadColumn(0),
      ColumnName("Label")]
      public string Label;
      [LoadColumn(1, 35630)]
      ColumnName("Features")]
      public float [] Features;

So that would allow you to remove the concatenate step. Otherwise it is fine.

**Comment by PeterPann23** [comment]
Hi Gleb

Yes, I did this in the beginning and works ok however I am then not able to eliminate the fields that are not having a positive effect on the prediction. This way I can “reverse orm“ it to get to an ideal Vector and load the Vector from disk in one go. I have some posts where I write on chalanges in regards to this option.




Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Gleb K <notifications@github.com>
Gesendet: Monday, April 22, 2019 3:54:17 AM
An: dotnet/machinelearning
Cc: PeterPann23; Mention
Betreff: Re: [dotnet/machinelearning] Documentation missing on prepairing training data (#3382)


@PeterPann23<https://github.com/PeterPann23> ,
The current approach would result in a very slow pipeline. You need to load all features that are treaded the same as a single vector. that would speed up your training tremendously, as I mentioned before.
For a sample on how to read vector data, take a look at multi-class sample<https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/MulticlassClassification_mnist>
What you should do instead, is load the data as vector directly in the loader. the mapper class should look something like this:

  [LoadColumn(0),
  ColumnName("Label")]
  public string Label;
  [LoadColumn(1, 35630)]
  ColumnName("Features")]
  public float [] Features;


So that would allow you to remove the concatenate step. Otherwise it is fine.

**Comment by glebuk** [comment]
In general, you want the learning algorithms to make that selection of what data is useful and what are not, unless you know that some leak label or are harmful in some other other.  
The typical approaches  to eliminate non-informative fields are:
1. [Feature Selection transforms ](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Transforms/FeatureSelectionCatalog.cs)
2. L1 and L2 regularization option on the learner
Also, note that once vectorized, the most efficient way to save and load data is via Binary Loaderand Reader..

Note that the IDataView is lazy, so that only the vector slots that end up being are the one that flow thorough the pipeline.

**Comment by shmoradims** [comment]
As a general rule of thumb, working with vectors is more efficient than working with elements separately. So favor vectorization, whenever possible.

As part of 1.0, we've added a lot of [how-to guides](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/load-data-ml-net) that address data prep. Also we added extensive remarks sections for trainers and transforms, including input/output columns, characteristics, algo details, and examples (e.g. [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.averagedperceptrontrainer?view=ml-dotnet#remarks) and [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.standardtrainerscatalog.averagedperceptron?view=ml-dotnet#Microsoft_ML_StandardTrainersCatalog_AveragedPerceptron_Microsoft_ML_BinaryClassificationCatalog_BinaryClassificationTrainers_System_String_System_String_Microsoft_ML_Trainers_IClassificationLoss_System_Single_System_Boolean_System_Single_System_Int32_)).

I'm closing this issue for now. If there's any other specific question, please feel free to reopen this one or open a new issue.

**Comment by PeterPann23** [comment]
Hi,

Yes, I noticed the documentation, starts to look good! 

As per your efficiency comment, I agree it's faster, however when you're not sure how the trainer will respond to the data you are not going to get the best predictions.
 
Feel free to do the following test in a MultiClass, 
Create a vector with say 1000 elements fill them with a generic value, add one column with the to be predicted class. In my tests the "noise" in the vector causes the model not to pick up the element that contains the key feature and your score will be "sub optimal".  Especially when you do a unbalanced MutliClass label, you may even see negative LogLoss values 

iterating over the PFI score's enables a developer to help the trainer pick a more efficient vector and increase accuracy. That's the theory at-least behind PFI.
