### ISSUE TITLE
Increase Native build warning level to W3 and fix build warnings 

### ISSUE THREAD

**Issue by glebuk** [dotnet/machinelearning#3390]
Before, we actually only reported W1 warning level during native build.
Now we warn on L3 warnings
Fixed three warnings from downcasting variables. In all cases the downcasting was deemed safe and replaced with static_cast<>
Note that all those warnings were deemed required to fix for compliance criteria.

**Comment by glebuk** [comment]
PR: #3370

**Comment by shauheen** [comment]
I am assuming this issue is now resolved with #3370
