### ISSUE TITLE
Will this work with PCL Projects? 

### ISSUE THREAD

**Issue by rlingineni** [dotnet/machinelearning#340]
### System information

- **OS version/distro**: iOS/Android

### Issue
- **What did you do?**
I was experimenting running this on a Xamarin Mobile app (Xam.Forms). I was able to install the nuget package into my project, which targets PCL. However, no luck in getting it to work.

- **What happened?**
Entry point 'Trainers.StochasticDualCoordinateAscentClassifier' not found

- **What did you expect?**
I expected the program to run.

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

```
var pipeline = new LearningPipeline();
var data = new List<TranscriptionData>() {
    new TranscriptionData { Transcription="This is a Happy presnetation!!" , clicked=1},
    new TranscriptionData { Transcription="Very sad now" , clicked=0},
    new TranscriptionData { Transcription="This is sad also" , clicked=0}
 };

     var collection = CollectionDataSource.Create(data);
     pipeline.Add(collection);
     pipeline.Add(new ColumnConcatenator("Features", "Transcription"));
     pipeline.Add(new StochasticDualCoordinateAscentClassifier()); //ERROR: any classifier here fails with entry point
     PredictionModel<TranscriptionData, TranscriptionPrediction> model = pipeline.Train<TranscriptionData,TranscriptionPrediction>();

```

**Comment by Ivanidzo4ka** [comment]
DRI RESPONSE: We currently support only x64 and working on x86 build. Maybe in future we will add support for ARM (or whatever architecture Xamarin on iOS uses), but not for v1.0

**Comment by codemzs** [comment]
we don't support on Xamarin today, it may be supported in the future.
