### ISSUE TITLE
Add API for shuffling to MLContext

### ISSUE THREAD

**Issue by BeanHsiang** [dotnet/machinelearning#342]
the class "TrainTestSplit" only support "Fraction" in TrainTestSplit.Input current, "Shuffle" is other important attribute. 
Could ML.NET support "Shuffle & Split" next version?

**Comment by glebuk** [comment]
ApproximateBootstrapSampler should also do shuffle.  Also there is a ShuffleTransform that can be added before the split.   It will become available once we change the API in #371.  Alternatively you can shuffle data prior to feeding it to ML.NET externally.

**Comment by Ivanidzo4ka** [comment]
@Zruty0  do we plan to add Shuffle function to MlContext object?

**Comment by Zruty0** [comment]
We do want to have shuffling available via MLContext, but not as an estimator/transformer. It'll be something like `IDataView Shuffle(IDataView input, ....)`

**Comment by rogancarr** [comment]
I actually am working on this as part of the `DataOperations` catalog and just found this issue. I'll push a PR shortly.
