### ISSUE TITLE
CSharpApiGenerator.cs does not generate compile-able code...

### ISSUE THREAD

**Issue by zeahmed** [dotnet/machinelearning#345]
CSharpApiGenerator.cs does not generate compile-able code. Some types have been moved around in different namespaces which are causing error during compilation.

This happened after the PR #61 was merged.

**Comment by Ivanidzo4ka** [comment]
I'm working on PR #339 to address that.

**Comment by zeahmed** [comment]
Thanks @Ivanidzo4ka!
