### ISSUE TITLE
I always get null when calling IDataView.GetRowCount()

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/machinelearning#3450]
[Enter feedback here]
The documentation states that the value sometimes returns null, well, in my case it always returns null. My code:
```

var dataset = mlContext.Data.TrainTestSplit(dataView, testFraction: 0.1);
//create pipeline
var pipeline = mlContext.Transforms.Conversion.MapValueToKey(outputColumnName: KeyColumn, inputColumnName: Label)
//... more stuff
.Append(mlContext.Transforms.CopyColumns(outputColumnName: Scores, inputColumnName: Score));

// Train the model.
var model = pipeline.Fit(dataset.TrainSet);

//get rations for coverage
(long? training, long? validating) montecarlo = ( dataset.TrainSet.GetRowCount(), dataset.TestSet.GetRowCount());

```
Is there no way to validate how much data was in the data based on the split in each of the datasets
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4406a379-022a-e834-8e40-886c28ea39b8
* Version Independent ID: afb85da3-f749-2f1b-668a-ae33b5df97f8
* Content: [IDataView.GetRowCount Method (Microsoft.ML)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.idataview.getrowcount?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML/IDataView.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML/IDataView.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by glebuk** [comment]
Note that IDataView is designed for streaming.  The Rowcount is available only on some occasions, when rowcount can be computed statically, for example when reading from an Idataview BinaryFile.  If you would like to get a true count, you can always, do it via a transform: select a single column via a transform (for speed) and then just convert the IDataView into  ane IEnumerable<> and run LINQ Count() on it
