### ISSUE TITLE
ParallelTraining API

### ISSUE THREAD

**Issue by helloguo** [dotnet/machinelearning#346]
Can anyone explain what `ParallelTraining` is and how to use it? And what's the difference between `ParallelTraining` and `SingleParallelTraining`?

**Comment by rogancarr** [comment]
Hi @helloguo !

I assume that you are referring to this line
`public ParallelTraining ParallelTrainer { get; set; } = new SingleParallelTraining();` in [CSharpApi.cs](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML/CSharpApi.cs#L3849).

In this case, it is referring to an optional parameter to `FastTree`, specifying which component to use to satisfy the [`IParallelTraining`](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.FastTree/Training/Parallel/IParallelTraining.cs) interface. [`SingleParallelTraining()`](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.FastTree/Training/Parallel/SingleTrainer.cs) is simply the non-parallel implementation.

As to what it is and why it exists, in our [RoadMap](https://github.com/dotnet/machinelearning/blob/master/ROADMAP.md#training-improvements-1) we have called out the desire for releasing distributed training. The `IParallelTraining` interface in `FastTree` allows one to parallelize the calculation by implementing a parallel solution this interface. Unfortunately, I am not able to give an example of this, but you can refer to [`SingleParallelTraining()`](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.FastTree/Training/Parallel/SingleTrainer.cs) to see what an implementation looks like.

**Comment by Ivanidzo4ka** [comment]
DRI RESPONSE: I consider this question as answered and plan to close issue within next few days unless someone objects to that.
