### ISSUE TITLE
Unable to load the Model by Stream

### ISSUE THREAD

**Issue by arafattehsin** [dotnet/machinelearning#3462]
### System information

I have used my model as an embedded resource in one of my projects.

### Issue

I tried to load the model using Stream and it gives me an error below;

System.ArgumentOutOfRangeException: 'filePath cannot be null or empty
Parameter name: filePath'

### Source code / logs

My below code snippet;

 var assembly = Assembly.GetExecutingAssembly();
            using (var stream = assembly.GetManifestResourceStream("SentimentAnalyzer.MLModels.SentimentModel.zip"))
            {
                //Create MLContext to be shared across the model creation workflow objects 
                //Set a random seed for repeatable/deterministic results across multiple trainings.
                var mlContext = new MLContext(seed: 1);
                Sentiment sampleStatement = new Sentiment { Text = text };
                ITransformer trainedModel = mlContext.Model.Load(stream, out var modelInputSchema);
...
...
}

**Comment by arafattehsin** [comment]
Just an update on this! 

If I try to use without **using** then it works fine. I had to explicitly close the stream.

**Comment by sfilipi** [comment]
Glad you can move forward @arafattehsin. 
Closing the issue since it seems resolved.
