### ISSUE TITLE
InputOutputColumnPair is confusing

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#3463]
So I'm looking on this class and it's constructor

InputOutputColumnPair(String, String) | Specifies input and output column names for a transformation.
-- | --

And I automatically assume it's Input column first, and output column second.
Which we all know not the true.

Shall we rename it to `OutputInputColumnPair`?

**Comment by wschin** [comment]
We probably can't do that because it can breaks BC.

**Comment by artidoro** [comment]
Closing as we have already released with InputOutputColumnPair.
