### ISSUE TITLE
Issues with KeyToVectorMappingEstimator 

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#3476]
https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.keytovectormappingestimator?view=ml-dotnet&branch=smoke-test-preview

>Input column data type | key

I would prefer capital Key.

>Estimator for KeyToVectorMappingTransformer. Converts the key types back to their original vectors.

I don't think this is good description. It implies my original value was vector, which not always the true.

>The input and output columns. The new column's data type is a vector of Single representing the original value.

It's not original value. 

in sample we have following:
>mlContext.Transforms.Conversion.MapKeyToVector("CategoryVector", "Category", outputCountVector: true
Whether to combine multiple indicator vectors into a single vector of counts instead of concatenating them. This is only relevant when the input column is a vector of keys.

Why we turn this option if it's pointless for single key which Category column contains?

**Comment by sfilipi** [comment]
Hmmm i thought i changed all of them to: "Convert the key types to a vector representing the original value". Good catch..
