### ISSUE TITLE
Fixes for the documentation of the TextCatalog 

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#3491]
**TokenizeIntoCharactersAsKeys**:
* [x] The description of TokenizingByCharactersEstimator should be corrected to:
  "Create a TokenizingByCharactersEstimator, which tokenizes **words** by splitting text into sequences of 
 characters using a sliding window."
* [x] outputColumnName description should state that the outputs are Uints rather than keys? I think it might confuse the users that those are KeyDataViewTypes. Or should the name of this method be changed? @artidoro @Ivanidzo4ka @zeahmed ? 
  "Name of the column resulting from the transformation of inputColumnName. This column's data type will be a variable-sized vector of **Uint**".
* [x] useMarkerCharacters needs a better description. 

**RemoveStopWords**
* [x] inputColumnName,:
  "This estimator operates over **a** vector of text.

**CustomStopWordsRemovingEstimator**
* [x] Output column data type
  "Variable-sized vector of Text"
   Replace Unknown-sized vector with Variable-sized vector. 
* [x] xref not resolving:
  <xref:Microsoft.ML.Transforms.Text.CustomStopWordsRemovingTransformer/> 

**WordHashBagEstimator**
* [x] Output column data type
    **Known-size** vector of  of Single
* [x] Replace metadata with annotations in the documentation references. 

**NgramHashingEstimator**
* [x] broken <xref:Microsoft.ML.Transforms.Text.NgramHashingTransformer/> link. 
* [x] casing: "in a way that **t**he former takes "

**NormalizeText** 
* [x] outputColumnName
   "This column's data type **is a** scalar of text or "

WordEmbeddingEstimator
* [ ] Add links for Glove50D, dimensionality of the embedding model used. 
* [x] Re-phrasehere and everywhere: See the See Also section for links to **usage example**s.

**Comment by Ivanidzo4ka** [comment]
>outputColumnName description should state that the outputs are Uints rather than keys? I think it might confuse the users that those are KeyDataViewTypes. Or should the name of this method be changed? @artidoro @Ivanidzo4ka @zeahmed ?

`TokenizeIntoCharactersAsKeys` It has keys in the name, and Key is not always `UInt`, it can be any unsign type. This is not the only transform which has Keys and I don't have problem with `Key` type. Still better than `UInt`.

**Comment by sfilipi** [comment]
Closed wit #3570
