### ISSUE TITLE
xref link in some Options classes isn't displayed correctly

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#3492]
AveragedPerceptronTrainer.Options:
Options for the AveragedPerceptronTrainer as used in [AveragedPerceptron(Options)](xref:Microsoft.ML.StandardTrainersCatalog.AveragedPerceptron(Microsoft.ML.BinaryClassificationCatalog.BinaryClassificationTrainers,Microsoft.ML.Trainers.AveragedPerceptronTrainer.Options)

**Comment by yaeldekel** [comment]
KMeansTrainer.Options:
Options for the KMeansTrainer as used in [KMeansTrainer(Options)](xref:"Microsoft.ML.KMeansClusteringExtensions.KMeans(Microsoft.ML.ClusteringCatalog.ClusteringTrainers,Microsoft.ML.Trainers.KMeansTrainer.Options)"

**Comment by yaeldekel** [comment]
FieldAwareFactorizationMachineTrainer.Options doesn't use 'xref' at all:
FieldAwareFactorizationMachineTrainer.Options for FieldAwareFactorizationMachineTrainer as used in FieldAwareFactorizationMachine(BinaryClassificationCatalog+BinaryClassificationTrainers, FieldAwareFactorizationMachineTrainer+Options)

**Comment by yaeldekel** [comment]
LbfgsLogisticRegressionBinaryTrainer doesn't use 'xref':
Options for the LbfgsLogisticRegressionBinaryTrainer as used in LbfgsLogisticRegression(BinaryClassificationCatalog+BinaryClassificationTrainers, LbfgsLogisticRegressionBinaryTrainer+Options)

**Comment by wschin** [comment]
Xref is used in markdown so I will change them to cref.
