### ISSUE TITLE
SdcaLogisticRegressionBinaryTrainer documentation is hard to read

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#3501]
The discussion of algorithm and regularization are mixed into a big paragraph. It'd nicer to split them into different sections.

![image](https://user-images.githubusercontent.com/3524474/56527695-e5211000-6502-11e9-99a2-4d42e039f14a.png)

**Comment by codemzs** [comment]
I wrote this and can split it in multiple sections but can you please clarify why this is a bug?

**Comment by wschin** [comment]
`boldsymbol` is a bug fixed in https://github.com/dotnet/machinelearning/pull/3497/files
