### ISSUE TITLE
Inheritance of LbfgsLogisticRegressionBinaryTrainer.Options class doesn't have links

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#3507]
Inheritance
Microsoft.ML.Trainers.LbfgsTrainerBase`3+OptionsBaseLbfgsLogisticRegressionBinaryTrainer.Options

**Comment by yaeldekel** [comment]
Same for LbfgsPoissonRegressionTrainer.Options.

**Comment by yaeldekel** [comment]
Same for SdcaBinaryTrainerBase<TModelParameters>.BinaryOptionsBase.

**Comment by wschin** [comment]
Some options don't have API references because they are not used to create trainers. For example, we cannot create `SdcaMulticlassTrainerBase` because it's a base class.
