### ISSUE TITLE
SDCA Regression Documentation Misses Type of Input Feature Vector

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#3513]
I am not sure if we need to mention input feature type, vector of Single, in that document.

![image](https://user-images.githubusercontent.com/3524474/56535123-e6a50500-650f-11e9-8a8f-dbb9a632c1f6.png)

**Comment by codemzs** [comment]
@yaeldekel Stealing this from you since we need to finish this today.

CC: @shmoradims

**Comment by codemzs** [comment]
### Input and Output Columns
The input label column data must be <xref:System.Single>.
The input features column data must be a known-sized vector of <xref:System.Single>.

This trainer outputs the following columns:

| Output Column Name | Column Type | Description|
| -- | -- | -- |
| `Score` | <xref:System.Single> | The unbounded score that was predicted by the model.|


Seems to have been fixed already.

CC: @shmoradims
