### ISSUE TITLE
Need better support for using JSON files as a training dataset

### ISSUE THREAD

**Issue by atotalnoob** [dotnet/machinelearning#353]
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: Version 2.1.200 

### Issue

- **What did you do?** I want to use a JSON file as my training data. 
- **What happened?** Throws error `System.ArgumentOutOfRangeException: 'Could not determine an IDataView type for member Patterns'`
- **What did you expect?** To be able to use my json file to train a ML model. 

### Source code / logs

JSON File (Abbreviated here for brevity, but its all the same):
```
[
    {
      "Label": "greeting",
      "Patterns": [ "Hi", "How are you", "Is anyone there?", "Hello", "Good day" ]
    },
    {
      "Label": "goodbye",
      "Patterns": [ "Bye", "See you later", "Goodbye" ]
    }
]

```

Class I am deserializing into: 

```
  public class Intent
    {
        [Column("0")]
        [ColumnName("Label")]
        public string Label;
        [Column("1")]
        public List<string> Patterns = new List<string>();
    }
```

Loading in the data using:
```
    public static class IntentLoader
    {

        public static List<Intent> LoadIntentData()
        {
            var fileContents = System.IO.File.ReadAllText("intents.json");

            try
            {
               var intents = JsonConvert.DeserializeObject<List<Intent>>(fileContents);
                return intents;
            }
            catch (Exception e)
            {

                throw e;
            }
            
        }
    }
```
pipeline:
```
 public LearningPipeline GetPipeline()
        {
            var intents = IntentLoader.LoadIntentData();
            var collection = CollectionDataSource.Create(intents);
            var pipeline = new LearningPipeline();
            pipeline.Add(collection);
            pipeline.Add(new ColumnConcatenator(outputColumn: "Features", "Patterns"));
            pipeline.Add(new Dictionarizer("Label"));
            pipeline.Add(new StochasticDualCoordinateAscentClassifier());
            pipeline.Add(new PredictedLabelColumnOriginalValueConverter() { PredictedLabelColumn = "PredictedLabel" });

            return pipeline;
        }
```
Model training (exception happens here):
```
 public PredictionModel<Intent, IntentPrediction> Train()
        {
            var pipeline = GetPipeline();
            var model = pipeline.Train<Intent, IntentPrediction>(); //exception thrown here
            return model;
        }
```

**Comment by lqdev** [comment]
@atotalnoob took a stab at it. Tried as much as possible to get it close to your code.

[My Solution](https://github.com/lqdev/mlnetserializedemo)

**Comment by atotalnoob** [comment]
@lqdev Okay, that looks good. I'll give it a try and report back. 

I don't mind having to create unique examples for each one of my NLU intents, instead of using a string list. I'd just suggest that you add support for lists. 

I have large NLU datasets built in JSON already, (been using rasa_NLU + dotnet core MVC. Now trying to develop ML.net into my backend, it would be much easier to have all the code as c#, rather than python + C#) and they have one entry per example end up being very large files in length. Example: https://github.com/RasaHQ/rasa_nlu/blob/master/data/examples/rasa/demo-rasa.json

It'd be easier if I could do something like my JSON above than what Rasa NLU has. 

Being able to use a list would shorten file size/length and I think it is a worthwhile new feature to support lists.

**Comment by atotalnoob** [comment]
Hey, 

Exception: 
ArgumentOutOfRangeException: Source column 'Features' has invalid type ('Vec<Text, 1>'): Expected R4 or R8 item type.

json:
```
[
  {
    "Label": "greeting",
    "text": "Hi"
  },
  {
    "Label": "greeting",
    "text": "How are you"
  },
  {
    "Label": "greeting",
    "text": "Is anyone there?"
  },
  {
    "Label": "greeting",
    "text": "Hello"
  },
  {
    "Label": "greeting",
    "text": "Good day"
  },
  {
    "Label": "goodbye",
    "text": "Bye"
  },
  {
    "Label": "goodbye",
    "text": "goodbye"
  },
  {
    "Label": "goodbye",
    "text": "later"
  }
]
```
trainer:
```
  public class IntentTrainer
    {

        public PredictionModel<IntentData, IntentPrediction> Train()
        {
            var pipeline = GetPipeline();
            var model = pipeline.Train<IntentData, IntentPrediction>(); //exception throw here
            return model;
        }

        public LearningPipeline GetPipeline()
        {
            var intents = IntentLoader.LoadIntentData();
            var collection = CollectionDataSource.Create(intents);
            var pipeline = new LearningPipeline();
            pipeline.Add(collection);
            pipeline.Add(new ColumnConcatenator("Features", "text"));
            pipeline.Add(new Dictionarizer("Label"));
            pipeline.Add(new StochasticDualCoordinateAscentClassifier());
            pipeline.Add(new PredictedLabelColumnOriginalValueConverter() { PredictedLabelColumn = "PredictedLabel" });

            return pipeline;
        }
    }

```

Data class + loader:

```
  public class IntentData
    {
        [Column("0")]
        [ColumnName("Label")]
        public string Label;
        [Column("1")]
        public string text;
    }
  
    public static class IntentLoader
    {

        public static List<IntentData> LoadIntentData()
        {
            var fileContents = System.IO.File.ReadAllText("intents.json");

            try
            {
               var intents = JsonConvert.DeserializeObject<List<IntentData>>(fileContents);
                return intents;
            }
            catch (Exception e)
            {

                throw e;
            }
            
        }
    }
```
Prediction: 
```
 public class IntentPrediction
    {
        [ColumnName("PredictedLabel")]
        public string PredictedLabel;
    }
```


Any suggestions?

**Comment by Ivanidzo4ka** [comment]
DRI RESPONSE: 
Speaking regarding json loader(or reader) we don't plan to add this in v1.0 version. But as pointed above we allow you to work with any IEnumerable as long as you do reading on your side.
For your second question, it fails because we expect "Features" column to be vector of floats.
You need to do some transformation of you text data into vector of floats and it depends on your domain, it's either Text transform or Term transform, or something else.

**Comment by codemzs** [comment]
We don't support JSON as a file format for loader. Currently we have text based loader where you separate out the fields using a character. We also don't plan on supporting JSON based loader in the short-term. As Ivan pointed out please use in-memory based IEnumerable to create your data from a C# type and load it into the pipeline.
