### ISSUE TITLE
Prediction does not match score and is always en empty string while score gets filled. Like CopyColumns isn't working

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/machinelearning#3531]
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: 
Core 3.0, 

### Issue
The pipeline is mis configured somehow as it doesn't perform a CopyColumns eventhough I defined it.

- **What did you do?**
Added following packages
![Packages](https://user-images.githubusercontent.com/44400822/56603692-7c1fc200-6600-11e9-87fc-73eb15bb9832.PNG)
interestingly it does not directly contain Microsoft.ML 1.0.0-preview, nor can I add the package. the output directory however does contain it.

I then used the following pipeline :
```
//create pipeline
var pipeline = mlContext.Transforms.Conversion.MapValueToKey(outputColumnName: KeyColumn, inputColumnName: Label)
        .Append(mlContext.Transforms.Concatenate(outputColumnName:RawFeatures,inputColumnNames: Mapper.GetFieldNames()))
        .Append(mlContext.Transforms.Normalize(outputColumnName:Features,inputColumnName:RawFeatures,mode: NormalizingEstimator.NormalizationMode.MinMax))
        .Append(mlContext.MulticlassClassification.Trainers.LightGbm(labelColumnName: KeyColumn, featureColumnName: Features))
        .Append(mlContext.Transforms.Conversion.MapKeyToValue(inputColumnName: KeyColumn, outputColumnName: PredictedLabel))
        .Append(mlContext.Transforms.CopyColumns(inputColumnName:KeyColumn, outputColumnName:"PredictedLabelIndex"))
        .Append(mlContext.Transforms.CopyColumns(outputColumnName: Scores, inputColumnName: Score));


// Train the model.
var model = pipeline.Fit(dataset.TrainSet);
```
- **What happened?**
When I call 
`predictor.Predict(poco, ref prediction);`
The only value that get's populated with meaning full values when calling Predict is my Scores array of floats. 

The PredictedLabelIndex always gets assigned 0 the `default` as well as the PredictedLabel who gets an empty string, again the default.

It's sets them just not with meaning full data..

- **What did you expect?**
I expect that the output columns get populated with the uint of KeyColum as well as the string label that is the class that was supposed to be predicted.

After the training I call:
```
var dataWithPredictions = model.Transform(dataset.TestSet);
var metrics = mlContext.MulticlassClassification.Evaluate(dataWithPredictions, KeyColumn, Scores);
```
and I get back:
```
{
  "LogLoss": 0.5089806627554087,
  "LogLossReduction": 0.06001707470227809,
  "MacroAccuracy": 0.14749680832299408,
  "MicroAccuracy": 0.8824768437255273,
  "TopKAccuracy": 0.0,
  "TopKPredictionCount": 0,
  "PerClassLogLoss": [ 0.10911017602616903
                                 , 6.4401884370896285
                                , 3.159759951705061
                                , 3.5237513486559044
                                , 3.183197354861199
                                , 3.5517723122073446
                               , 6.775013273027178 ]
}
```
I have 7 classes in the training file so that adds up…. 

### Source code / logs
the Log event doesn't get triggered on the MLContext when predicting so I can't add that.
It does however add different scores each time...

```
/*Data structure used for the prediction*/
class DataPrediction
{    
    public string PredictedLabel { get; set;}
    public uint PredictedLabelIndex { get; set;}    
    public float[] Scores { get; set;}
}
[sample input schema.txt](https://github.com/dotnet/machinelearning/files/3108984/sample.input.schema.txt)

```

[Training_log.txt](https://github.com/dotnet/machinelearning/files/3108988/Training_log.txt)

**Comment by PeterPann23** [comment]
![snip](https://user-images.githubusercontent.com/44400822/56609059-847dfa00-660c-11e9-977a-ed89e1bdf541.png)
Here is what the prediction looks like, English is not my first language… and a picture is a 1000 words

**Comment by PeterPann23** [comment]
I noticed that the above pipeline creates a TransformerChain<ColumnCopyingTransformer> if I remove the 2 CopyColums at the end, I get a  TransformerChain<KeyToValueMappingTransformer>. is there a compatibility issue or an order in how to place them? If so, is this documented?

**Comment by yaeldekel** [comment]
Hi @PeterPann23 , can I have some more details about your scenario? For example, when you call this line
```
predictor.Predict(poco, ref prediction);
```
what is `poco`?

There is one issue I see in your pipeline: The `MapKeyToValue` transformer and the `CopyColumns` transformer applied to the label column use the input `Label` column to compute their output. At scoring time, if the label is not present, these two transformers would always output the default value, so you cannot use them to extract the predicted class.

However, the transformer trained from `LightGbm` outputs a `Score` column as well as a `PredictedLabel` column. The `PredictedLabel` column would correspond to the `PredictedLabelIndex` property in your `DataPrediction` class, and if you apply `MapKeyToValue` to it, the output column would correspond to the `PredictedLabel` property in the `DataPrediction` class.

Does this solve the problem?

**Comment by PeterPann23** [comment]
Hi,
I have tried 2 ways with the poco, 
1. Have a lable and a vector with all fields, I then provide the poko with only the vector at time of the prediction and train the model on that.
2. Have a auto generated class with property F0, F1, F2, F3..F[N]. and set the values based on the same underlying vector to see the array elements that matter in the prediction.

at no time did **any other field** that the scores array (length of my 7 labels) get returned on a prediction.

I have stripped down the pipeline and commented out some transformations
```
var pipeline = mlContext.Transforms.Conversion.MapValueToKey(outputColumnName: KeyColumn, inputColumnName: Label)
        //  .Append(mlContext.Transforms.Concatenate(outputColumnName: RawFeatures, inputColumnNames: Mapper.GetFieldNames()))
        //  .Append(mlContext.Transforms.Normalize(outputColumnName: Features, inputColumnName: RawFeatures, mode: NormalizingEstimator.NormalizationMode.MinMax))

        .Append(mlContext.MulticlassClassification.Trainers.LightGbm(labelColumnName: KeyColumn, featureColumnName: Features))
        .Append(mlContext.Transforms.Conversion.MapKeyToValue(inputColumnName: KeyColumn, outputColumnName: PredictedLabel));
        //.Append(mlContext.Transforms.CopyColumns(inputColumnName:KeyColumn, outputColumnName:"PredictedLabelIndex"))
        //.Append(mlContext.Transforms.CopyColumns(outputColumnName: Scores, inputColumnName: Score));
```
And train it using:
```
public static IDataView GetDataViewWithFields(MLContext mlContext, FileInfo trainingFile, long? maxRows= null)
{
    var binFile = new FileInfo(trainingFile.FullName.Replace(trainingFile.Extension, ".bin"));
    if (binFile.Exists)
        return mlContext.Data.LoadFromBinary(binFile.FullName);
    var loader = mlContext.Data.CreateTextLoader(options: new TextLoader.Options()
    {
        Columns = new[] {
            new TextLoader.Column(name:"Label", dataKind: DataKind.String, index: 0),
            new TextLoader.Column(name:"Features",dataKind:DataKind.Single,minIndex:1,maxIndex: 35631),                  
                   
        },
        HasHeader = false,
        Separators = new[] { '|' },
        UseThreads = true,
               
    });
    var dv= loader.Load(trainingFile.FullName);
           
    using (var stream = new FileStream(binFile.FullName, access: FileAccess.ReadWrite, mode: FileMode.OpenOrCreate))
        mlContext.Data.SaveAsBinary(dv, stream, true);
    return mlContext.Data.LoadFromBinary(binFile.FullName);
}

```
I'm not sure as to what the problem is, might be that I have a to big a vector and that 35,630 items are not supported....

**Comment by PeterPann23** [comment]
I have provided the model that maps the array to fields. 
[model.zip](https://github.com/dotnet/machinelearning/files/3111243/model.zip)
I also add the Mapper used to make a preduction
[Mapper.zip](https://github.com/dotnet/machinelearning/files/3111251/Mapper.zip)

**Comment by yaeldekel** [comment]
Hi @PeterPann23 .
A few comments about your code:

1. The input data: As you specified in your code snippet above, when you use `TextLoader`, you can load all the features into a single column, so you don't need the `Concatenate` transformer. I would apply the `MapValueToKey` transformer to the input data, without adding it to the pipeline, since you don't need the serialized model to contain it (at prediction time you may not have a label).
```
  IDataView dv= loader.Load(trainingFile.FullName);
  dv = mlContext.Transforms.Conversion.MapValueToKey(outputColumnName: KeyColumn, inputColumnName: Label).Fit(dv).Transform(dv);
```
2. The training pipeline: I would create the following pipeline:
```
  var pipeline = mlContext.Transforms.Normalize(outputColumnName: Features, inputColumnName: RawFeatures, mode: NormalizingEstimator.NormalizationMode.MinMax)
       .Append(mlContext.MulticlassClassification.Trainers.LightGbm(labelColumnName: KeyColumn, featureColumnName: Features))
       .Append(mlContext.Transforms.CopyColumns(inputColumnName:"PredictedLabel", outputColumnName:"PredictedLabelIndex"))
       .Append(mlContext.Transforms.Conversion.MapKeyToValue(inputColumnName: "PredictedLabel", outputColumnName: "PredictedLabel"));
       .Append(mlContext.Transforms.CopyColumns(outputColumnName: Scores, inputColumnName: Score));
```
  The output schema of the second step in the pipeline (`LightGbm`) has a column named `Score` containing a vector of floats (one for each class), and a column named `PredictedLabel` of type key containing the id of the label with the highest score. Since the class you use for predictions has a property `PredictedLabelIndex` you need to copy that column to a new column with that name (this is done as the third step in the pipeline). Since the class you are using for predictions has a property `PredictedLabel` of type string, you need to apply the `MapKeyToValue` transform to the output of the second step in the pipeline (this is done as the fourth step in the pipeline). Finally, since the property containing the scores is called `Scores`, you need to copy the column named `Score` to a new column named `Scores (this is done as the fifth step in the pipeline).

3. At prediction time: You did not mention how you create the prediction engine `predictor`. Prediction engines have two generic types, `TSrc` and `TDst`. `TDst` is the class `DataPrediction`, and `TSrc` should contain properties matching the input schema of the pipeline. In your case, if you use the `TextLoader` as specified for training, and don't apply any transforms to the label column in the pipeline, the class you use for `TSrc` only has to contain a float[] called `Features`, with a `VectorType` attribute specifying the length of the features vector.

**Comment by PeterPann23** [comment]
Interesting, I did not know one could do that transformation to the loader. Did not see any of this in the documentation. I will give this a spin
