### ISSUE TITLE
Realtime image classification using pretrained onnx model

### ISSUE THREAD

**Issue by musab1234** [dotnet/machinelearning#3582]
i am using this sample https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx, but its loading images from folder , is there way/api to load image directly from memory and apply preprocess transformation?

**Comment by yaeldekel** [comment]
Hi @musab1234, please take a look at issue #3460, it has some information about what you are trying to do.
