### ISSUE TITLE
Fast Tree Nuget 1.0.0-preview doesn't set PackageReference

### ISSUE THREAD

**Issue by dckorben** [dotnet/machinelearning#3587]
### System information

- **OS version/distro**: Win 10
- **.NET Version (eg., dotnet --info)**:  Dot Net 4.7.2

### Issue

- **What did you do?** Added Fast Tree NUGET
- **What happened?** DLL Not Found Error On Execute
- **What did you expect?** No DLL Not Found Error

### Source code / logs

To use Fast Tree you must manually add `<PackageReference Include="Microsoft.ML.FastTree" Version="1.0.0-preview" />` to the project file otherwise it won't copy the fast tree dll to the output folder.

**Comment by frank-dong-ms** [comment]
@dckorben thanks for using ML.NET, I'm not able to repro the issue you described. As soon as I add NuGet package "ML.NET.FastTree", a package reference was added automatically to my project file. Could you please share more details like which version of visual studio are you using?

**Comment by dckorben** [comment]
Such an out of date version it doesn't apply anymore.
