### ISSUE TITLE
Problem with ColumnCopier

### ISSUE THREAD

**Issue by nsulikowski** [dotnet/machinelearning#360]
I wrapped ML.NET as Excel functions using ExcelDNA.
Everything works except ColumnCopier (for some strange reason).
May be ColumnCopier tries to emit code which might now work in that context?
It'll take me too long to create a replication example... but hopefully this general comment is enough to find the problem.

**Comment by shauheen** [comment]
Thanks @nsulikowski for filing this issue, is it possible for you to put your code on a git repo. Can you give some more detail on what error you are receiving?

**Comment by Ivanidzo4ka** [comment]
DRI RESPONSE: @nsulikowski  can you provide more information (something we can debug and reproduce problem). If not, I'm intent to close this issue within next few days.
