### ISSUE TITLE
ImageLoader loader transform should not hold the lock on image

### ISSUE THREAD

**Issue by codemzs** [dotnet/machinelearning#3630]
Currently ImageLoader transformer holds the lock on the image by opening it using Bitmap(string filepath) and this causes bitmap class to take a lock that prevents writing to image location since Bitmap class also has a Save function. We can instead open the image using Bitmap(stream) and create stream in Read only mode. Since bitmap class expects us to keep the stream open until the lifetime of the bitmap class so we will first create a file stream, copy the contents over to in memory and pass the reference to in memory stream to the bitmap class. Whenever bitmap object is disposed GC will clean up the in memory image data. This is of course not a great solution as it will increase GC pressure but this is the best we can do given the limitations of bitmap class. This will prevent ML.NET code creating a lock over the input image files because there is no good reason to do that and instead it creates issues if another process wants to rewrite to that image location.

**Comment by eerhardt** [comment]
I'm not sure I get the full scenario here. Can you provide a list of steps that illustrate what the issue is? What does a user do, and what do they expect to happen vs. what actually happens?

In general - if we are training on a set of data, I don't expect someone else to be able to write to that data at the same time. Say you are using the TextLoader - should it allow for people writing to the text file at the same time and modify its contents? Probably not. This would "mess" training up, wouldn't it?

cc @TomFinley

**Comment by codemzs** [comment]
Hi @eerhardt ,

You make a fair point if we are using data and don't mutate it then it doesn't matter if we have the lock on the data from the training pipeline's perspective. However consider the scenario where you ran two training pipelines one after the other and both of these pipelines were training on the same set of image data that is downloaded from the network on each training run. The first pipeline will hold the lock on an image and won't release the lock unless the bitmap object is disposed by the user. When the second pipeline starts it will try to download the same image again on which there is a lock held by the bitmap object produced in the first pipeline and this will cause file in use exception because download operations are write operations. Does this make sense?

**Comment by eerhardt** [comment]
Why would you download the same images again? You already have them locally.

Also, when the first pipeline is done, it should be disposing the resources it has been using.

**Comment by codemzs** [comment]
The pipeline disposes images that it can but some images it cannot dispose like ones that user retrieves from output schema, here the ownership stays with the user. In ML.NET when a transform gets an image from an underlying transform using a getter it claims that image's ownership and disposes it, however the image a transform produces, it does not have its ownership.

To answer your question about why would you download the same images again? This is not ideal but no one is preventing you from doing this. The bigger question is why hold the lock on an image if I'm just using it for READ and not for WRITE.

**Comment by codemzs** [comment]
We spoke offline and decided it is ok to open images with write lock since IDataView does not mutate them and hence it will not interfere with reading images for training and inference purposes. The burden is on the user to dispose the Bitmap object to free up write lock that may interfere with any write operations on an image returned by ML.NET bitmap object. Even though taking a write lock is not good in principle when images are just used for READ but currently there is no good way to use Bitmap object just for reading images without causing any performance hits.
