### ISSUE TITLE
Add AVX intrinsics implementation for Factorization Machine

### ISSUE THREAD

**Issue by pkumar07** [dotnet/machinelearning#3654]
### System information

- **OS version/distro**: Windows 10 version 1709
- **.NET Version (eg., dotnet --info)**: 3.0.100-preview-010184

### Issue

I'm trying to add C++ AVX intrinsics implementation for Factorization Machine and doing a dynamic dispatch from `FactorizationMachineInterface.cs`. I'm using `Avx.IsSupported` to check for AVX support and then call the `CalculateGradientAndUpdateNativeAVX/SSE` function declared as an extern.

The build fails with the following error for netcoreapp3.0. Would appreciate your suggestions to fix this.

![buildfail](https://user-images.githubusercontent.com/22417834/57106643-cd0b7680-6ce2-11e9-855a-3d763580a535.PNG)

### Source code / logs

Here is the Microsoft.ML.StandardTrainers.csproj snippet I'm using:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework Condition="'$(UseIntrinsics)' != 'true'">netstandard2.0</TargetFramework>
    <TargetFrameworks Condition="'$(UseIntrinsics)' == 'true'">netstandard2.0;netcoreapp3.0</TargetFrameworks>
    <IncludeInPackage>Microsoft.ML</IncludeInPackage>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>7.3</LangVersion>
    <DebugType>pdbonly</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.ML.Core\Microsoft.ML.Core.csproj" />
    <ProjectReference Include="..\Microsoft.ML.CpuMath\Microsoft.ML.CpuMath.csproj" />
    <ProjectReference Include="..\Microsoft.ML.Data\Microsoft.ML.Data.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp3.0'">
    <Compile Remove="FactorizationMachine/FactorizationMachineInterface.netstandard.cs" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.5.2" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <Compile Remove="FactorizationMachine/FactorizationMachineInterface.netcoreapp.cs" />
    <PackageReference Include="System.Memory" Version="$(SystemMemoryVersion)" />
  </ItemGroup>

</Project>
```
FYI: 
The build fails when targeting to netcoreapp3.0 even with no modifications to the source code. i.e. 
```<TargetFramework>netstandard2.0</TargetFramework>```
to
``` <TargetFrameworks>netstandard2.0;netcoreapp3.0</TargetFrameworks>```

@glebuk @singlis

**Comment by singlis** [comment]
Hi @pkumar07, netcoreapp is targeted for executables. StandardTrainers should be a library. Are AVX instructions only available in netcoreapp3?

**Comment by pkumar07** [comment]
@singlis 
I have made use of C# hardware intrinsics only to check hardware support (Avx.isSupported) which is available only in netcoreapp3. The AVX implementation is itself in native code.
For netstandard support, I am using the existing code (without any C# hardware intrinsics).

**Comment by singlis** [comment]
@pkumar07 ok got it figured out. So it looks like we already do this for CpuMath, so I followed what is there. In the StandardTrainers csproj, replace the current TargetFramework line with the following
```
<TargetFramework Condition="'$(UseIntrinsics)' != 'true'">netstandard2.0</TargetFramework>
<TargetFrameworks Condition="'$(UseIntrinsics)' == 'true'">netstandard2.0;netcoreapp3.0</TargetFrameworks>
```
Also add this as once you make the TargetFramework conditional, VS will fail to load the files in the project:
```
<ItemGroup>
    <!-- Workaround https://github.com/dotnet/project-system/issues/935 -->
    <None Include="**/*.cs" />
</ItemGroup>
```

After doing this, I still hit the same error you encountered. To fix this, you will want to add the [BestFriend] attribute to the CpuMathUtils defined in the CpuMathUtils.netcoreapp.cs file (to mirror what we do in the CpuMathUtils.netstandard.cs file):
```
     [BestFriend]
     internal static partial class CpuMathUtils
```

NOTE: You do have to build the Intrinsic build. Therefore if you delete the .\Tools directory and execute

> .\build.cmd -Debug-Intrinsics

That will download the .net core3.0 compiler for building.

**Comment by pkumar07** [comment]
Thanks @singlis 
It worked! I will make a PR for adding AVX instructions in Factorization Machine.
