### ISSUE TITLE
.NET Framework 4.6.1 - ML.NET package does't show up in references, thus can't use its assembly references. 

### ISSUE THREAD

**Issue by SharPiy** [dotnet/machinelearning#366]
### System information

- Windows 7/ 64 bit OS
- .NET Framework 4.6.1 

### Issue

- I created a console App to use Microsoft.ML. I tried to install ML.NET package -  the package manager successfully installed it but it never shows up in references. 
- I am not able to use ML.NET libraries, as even after successfully installing it the using statements gives me red lines to show missing assembly reference error.
![capture](https://user-images.githubusercontent.com/39928473/41513174-d9a50140-724c-11e8-9ec4-8a297304b014.PNG)
![image](https://user-images.githubusercontent.com/39928473/41513187-084c47e2-724d-11e8-8b42-1d248c98ad7b.png)
![image](https://user-images.githubusercontent.com/39928473/41513204-3986b1ee-724d-11e8-9435-c1bb66003d72.png)

**Comment by jwood803** [comment]
This may be similar to #357?

**Comment by eerhardt** [comment]
What version of Visual Studio are you using? Can you paste the information from the Help -> About dialog using the `Copy Info` button on the right?

**Comment by SharPiy** [comment]
Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.02558

Installed Version: Professional

Visual C# 2015   00322-40000-00000-AA122
Microsoft Visual C# 2015

**Comment by eerhardt** [comment]
Since you are using VS 2015, and Microsoft.ML is a `netstandard2.0` package, you need to be sure to install:

1.	The latest NuGet VSIX for VS 2015 (v3.6.0 as of this writing) from https://www.nuget.org/downloads
2.	The .NET Standard Build Support extension from https://aka.ms/netstandard-build-support-netfx

Does that help resolve the problem?

**Comment by SharPiy** [comment]
Does updating VS to 2017 would fix this?

**Comment by eerhardt** [comment]
Yes, it works with the VS 2017 out of the box.

But you can use VS 2015 with the above 2 extensions installed (they shouldn't take more than 5-10 minutes to install - they are pretty small).

**Comment by SharPiy** [comment]
I installed(both links) as suggested. I can now see packages in References but still cant use it in code. Also, System.ValueTuple shows exclamation mark weirdly. 
![image](https://user-images.githubusercontent.com/39928473/41550339-4e6618a8-72dd-11e8-8851-8380619e02ed.png)
![image](https://user-images.githubusercontent.com/39928473/41550354-5913c520-72dd-11e8-8774-c2cfe3d1e6f0.png)

**Comment by eerhardt** [comment]
Did you re-install the package after you installed the extensions?

**Comment by SharPiy** [comment]
Yes. I did.

**Comment by eerhardt** [comment]
Hmm, I'm not quite sure what is happening. Can you zip up your project (without the `bin` and `obj` folders) and attach it to this issue?

**Comment by SharPiy** [comment]
[MachineLearningProj.zip](https://github.com/dotnet/machinelearning/files/2116804/MachineLearningProj.zip)

Please find attached

**Comment by eerhardt** [comment]
My apologies, @SharPiy, I had been busy doing other things and finally got back to looking into this.

Can you try manually editing the .csproj and add the line `<ImplicitlyExpandDesignTimeFacades>false</ImplicitlyExpandDesignTimeFacades>` in the first `<PropertyGroup>`?  I was forced to do this in order to workaround https://github.com/dotnet/sdk/issues/1539.

Also, can you trying building the project, and listing any errors that occur?  That may also give some idea as to what is going wrong.

**Comment by eerhardt** [comment]
@carldupreez111 can you show your .csproj file? Also, make sure you target x64. You can’t use AnyCPU.

**Comment by carldupreez111** [comment]
If I use F5 it does the same thing as if I run dotnet run in the command line. 

Below is my .csproj file contents

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
	<ImplicitlyExpandDesignTimeFacades>false</ImplicitlyExpandDesignTimeFacades>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML" Version="0.4.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="iris.data.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>

This is from the command line "dotnet --info".

.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

I did change the solution platform to x64 and pushed F5 and seems to run. Thanks, I was aware that you need to make sure its set to x64.

Thanks for the assistance.

**Comment by eerhardt** [comment]
Closing as I believe the original issue/questions have been addressed.

**Comment by dharminnwa** [comment]
> 
> 
> Yes, it works with the VS 2017 out of the box.
> 
> But you can use VS 2015 with the above 2 extensions installed (they shouldn't take more than 5-10 minutes to install - they are pretty small).

Hello,

I am trying to install "MLNET_Model_Builder" but its not installing

VS Info
visual studio community 2017
Version 15.9.13
Framework version 4.7.03190

It's returning Error Log 

Searching for applicable products...
18-Jun-19 11:28:07 AM - Found installed product - Microsoft Visual Studio Ultimate 2013
18-Jun-19 11:28:07 AM - Found installed product - Microsoft Visual Studio Premium 2013 
18-Jun-19 11:28:07 AM - Found installed product - Microsoft Visual Studio Professional 2013
18-Jun-19 11:28:07 AM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
18-Jun-19 11:28:07 AM - Found installed product - Global Location
18-Jun-19 11:28:07 AM - Found installed product - ssms
18-Jun-19 11:28:07 AM - Found installed product - Visual Studio Build Tools 2017 (2)
18-Jun-19 11:28:07 AM - Found installed product - Visual Studio Community 2017
18-Jun-19 11:28:07 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)



Can you help me with this?

Thank you.
