### ISSUE TITLE
No Wiki. Lack of documentation.

### ISSUE THREAD

**Issue by dbaechtel** [dotnet/machinelearning#3660]
### System information

any

### Issue

No Wiki. 
Lack of documentation.

**Comment by jwood803** [comment]
What documentation do you need? There's quite a lot in the [docs folder](https://github.com/dotnet/machinelearning/tree/master/docs) and a lot of [samples](https://github.com/dotnet/machinelearning/tree/master/docs/samples/Microsoft.ML.Samples).

**Comment by codemzs** [comment]
@dbaechtel https://docs.microsoft.com/en-us/dotnet/api/?view=ml-dotnet

**Comment by najeeb-kazmi** [comment]
Closing this as there seems to be a resolution. @dbaechtel please feel free to reopen if you want more discussion on this.
