### ISSUE TITLE
How can I use FaceNet Tensorflow model with ML.Net?

### ISSUE THREAD

**Issue by nilay-kothari** [dotnet/machinelearning#3664]
I studied the sample code to use TensorFlow model to classsify image. Now I am trying to use FaceNet model created at https://github.com/davidsandberg/facenet, but I am not clear on how to proceed.

Any suggestions?

**Comment by sfilipi** [comment]
Is the sample on [Text Classification ](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/TensorFlow/TextClassification.cs)more helpful:

1- you can [load the model](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/TensorFlow/TextClassification.cs#L48)

2- Knowing the schema, you can [score ](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/TensorFlow/TextClassification.cs#L76)with that model.

**Comment by nilay-kothari** [comment]
Yes, looks like this should do i. I will update if I run into an issue :).

Thanks :)

**Comment by najeeb-kazmi** [comment]
@nilay-kothari can this issue be considered closed? Please let us know if you have additional follow ups.

**Comment by nilay-kothari** [comment]
yes, close this please. I will start a new thread if required.
