### ISSUE TITLE
Shuffle input cursor reader failed with an exception

### ISSUE THREAD

**Issue by samueleresca** [dotnet/machinelearning#3670]
### System information

- **OS version/distro**: Mac OS Mojave 10.14.4 (18E226)
- **.NET Version (eg., dotnet --info)**:  
```
Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview3-010431/

Host (useful for support):
  Version: 3.0.0-preview5-27606-03
  Commit:  39eb528ff8

```

### Issue

- **What did you do?**
I'm loading my dataset using the 'CsvLoad' in the following way: [CsvFile.Load](https://github.com/samueleresca/LyricsClassifier/blob/76143426e515be5a5cb6808cb4fa599325b9ddd2/LyricsClassifier/Program.fs#L143)

The data pass through the following features engineering process:  [dataProcessPipeline](https://github.com/samueleresca/LyricsClassifier/blob/76143426e515be5a5cb6808cb4fa599325b9ddd2/LyricsClassifier/Program.fs#L69)

The runtime throws an exception at the [Fit step](https://github.com/samueleresca/LyricsClassifier/blob/76143426e515be5a5cb6808cb4fa599325b9ddd2/LyricsClassifier/Program.fs#L110)

- **What happened?**
The runtime throws the following exception:
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Shuffle input cursor reader failed with an exception) (Shuffle input cursor reader failed with an exception) ---> System.InvalidOperationException: Shuffle input cursor reader failed with an exception ---> System.InvalidOperationException: Splitter/consolidator worker encountered exception while consuming source data ---> System.InvalidOperationException: Splitter/consolidator worker encountered exception while consuming source data ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
```

- **What did you expect?**

The runtime throws a `System.FormatException`, but Is not clear which specific input refers.

### Source code / logs

[LyricsClassifier/LyricsClassifier/Program.fs](https://github.com/samueleresca/LyricsClassifier/blob/76143426e515be5a5cb6808cb4fa599325b9ddd2/LyricsClassifier/Program.fs)

**Comment by najeeb-kazmi** [comment]
@samueleresca you need to load the data using ML.NET's text loader. Please see [this F# sample](https://github.com/dotnet/machinelearning-samples/blob/master/samples/fsharp/end-to-end-apps/MulticlassClassification-GitHubLabeler/GitHubLabeler/GitHubLabelerConsoleApp/Program.fs). 

Specifically these lines:
https://github.com/dotnet/machinelearning-samples/blob/cb3159560df1bff0e2cf2ec701c7249f776da719/samples/fsharp/end-to-end-apps/MulticlassClassification-GitHubLabeler/GitHubLabeler/GitHubLabelerConsoleApp/Program.fs#L43-L59

**Comment by samueleresca** [comment]
Hi @najeeb-kazmi, thanks for the answer. The `MLContext` exposes the `LoadFromEnumerable` method. I suppose it can be used as a replacement for the `CreateTextLoader` to load collections of strongly typed data, am I missing something?

**Comment by najeeb-kazmi** [comment]
@samueleresca That's correct. You can create an ML.NET DataView with the `LoadFromEnumerable` method. I couldn't find an F# sample, but here is a [C# sample](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/DataViewEnumerable.cs) that might help.

**Comment by najeeb-kazmi** [comment]
Closing since it seems to be resolved. 

@samueleresca please feel free to reopen this issue if you want to continue the discussion.
