### ISSUE TITLE
Permutation Feature Importance on Text Data

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#3674]
This question/issue is related to dotnet/docs#12216

Using data that looks like the following (ignore accuracy, this was generated data for demo purposes):

AudienceReview|CriticReview|Rating
|---|---|---|
It was a true masterpiece|I hated it |2
Worst movie ever|I did not like it|1
It was nice|It was nice|1

I created the data model `InputData`:

```csharp
public class InputData
{
    [LoadColumn(0)]
    public string AudienceReview { get; set; }
    [LoadColumn(1)]
    public string CriticReview { get; set; }
    [LoadColumn(2)]
    [ColumnName("Label")]
    public float Rating { get; set; }
}
```

And used the following pipeline:

```csharp
DataOperationsCatalog.TrainTestData dataSplit = mlContext.Data.TrainTestSplit(data);
IDataView trainData = dataSplit.TrainSet;
IDataView testSet = dataSplit.TestSet;

var trainingPipeline = mlContext.Transforms.Text.FeaturizeText("AudienceReview")
    .Append(mlContext.Transforms.Text.FeaturizeText("CriticReview"))
    .Append(mlContext.Transforms.Concatenate("Features", new string[] { "AudienceReview", "CriticReview" }))
    .Append(mlContext.Regression.Trainers.Sdca());

var trainedModel = trainingPipeline.Fit(trainData);

var pfi = mlContext.Regression.PermutationFeatureImportance(trainedModel.LastTransformer, trainedModel.Transform(testSet), permutationCount: 3);
```

I would expect the result of using PFI to contain metrics for two features, `AudienceReview` and `CriticReview`. Instead, I get 268 features.  I believe this is because it is taking the result of `FeaturizeText` and treating each element in the vector as a feature as opposed to the entire vector. Is that the intent?

**Comment by najeeb-kazmi** [comment]
hi @luisquintanilla - this is indeed expected. The feature importance is calculated on the final features that the model trains on. You can inspect the output tokens to see which slot in the Features vector corresponds to which token. See [this example](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Text/FeaturizeTextWithOptions.cs) for more.

**Comment by abgoswam** [comment]
Closing this issue . This is the expected behaviour as @najeeb-kazmi explains above.
