### ISSUE TITLE
Predict() cannot find file on disk even though it exists

### ISSUE THREAD

**Issue by greenygh0st** [dotnet/machinelearning#3675]
### System information

- **OS version/distro**: macOS
- **.NET Version (eg., dotnet --info)**: 2.2.2

### Issue

- **What did you do?**
Ran the ObjectDetection example from https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx

- **What happened?**
The Predict() method of the model produced an IO error that the file could not be found

- **What did you expect?**
For the sample to properly classify the images.

---
I also confirmed that the file does exist on disk and that the file is readable. I did this by passing sample.ImagePath to File.ReadAllText() in an additional line I added above the Predict() line.

![image](https://user-images.githubusercontent.com/1551020/57320674-0e29cf00-70c5-11e9-8d45-5ee2b655560b.png)

### Source code / logs

![image](https://user-images.githubusercontent.com/1551020/57320303-37962b00-70c4-11e9-8d25-be019e95dd98.png)

**Comment by zeahmed** [comment]
@greenygh0st, Thanks for reporting this.

I got the latest version from the github and it worked fine for me. Can you please confirm that you did not modify the project?

**Comment by glebuk** [comment]
The path is relative the running exe.  Can you figure out the path of the running process and see if the path given by predict is valid from that location?

**Comment by greenygh0st** [comment]
I did not modify the project except to add the test line. I will try a re-D\L this afternoon and I will take another look.

**Comment by greenygh0st** [comment]
So I did a hard reset on my handful of changes and pulled down the latest commits. Unfortunately, my results were the same.

![image](https://user-images.githubusercontent.com/1551020/57484142-e9249000-726d-11e9-9ea9-76b9a15b957f.png)

The strange thing using the directory provided in the console output I can cd in and list all of the expected files.

**Comment by tarnow74** [comment]
I hava the same issue with the tensorflow image classification samples. Happens only when I try to predict an image that is just created (If I poll a directory for new images every 50ms and then try to to call Predict). File.Exists returns true in these cases.

**Comment by harishsk** [comment]
This specific bug doesn't repro if you make sure libgdiplus is installed on the Mac.
However, there was another crash on both Windows and Mac because GetImagesData was trying to load the wikimedia.md file in the assets folder as if it was an image. 
I checked in a fix for that, but another large refactor made it in just before I submitted my PR and that fixes the bug on both Windows and Mac.
Please pull the latest code and try again.

**Comment by greenygh0st** [comment]
Ok I will take a look later tonight and get back with you. 👍

**Comment by greenygh0st** [comment]
After installing mono-libgdiplus via brew 🍺the project builds and runs correctly on macOS. 👍
