### ISSUE TITLE
Cannot load a trained model: "A local file header is corrupt"

### ISSUE THREAD

**Issue by larsbeck** [dotnet/machinelearning#3678]
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: Microsoft.NETCore.App 3.0.0-preview4-27615-11

### Issue
Cannot load a trained model.

- **What did you do?**
Trained a model with AutoML, saved it to "model.zip" (see attached) and then I tried to load it via:
`
var mlContext = new MLContext();
var mlModel = mlContext.Model.Load("model.zip", out _);
`
- **What happened?**
An exception is thrown: "A local file header is corrupt"
- **What did you expect?**
The model to be loaded so I can make a prediction.
### Source code / logs
[model.zip](https://github.com/dotnet/machinelearning/files/3155902/model.zip)

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by sfilipi** [comment]
@justinormont is this a supported scenario to your knowledge?

**Comment by justinormont** [comment]
The model.zip should be a complete standard ML.NET model file once it's trained. 

@vinodshanbhag, @daholste: any thoughts?

**Comment by larsbeck** [comment]
In case it is of any help. I can reproduce the error with a model I trained with "SdcaLogisticRegression" too (not only AutoML). Training and saving the model works fine, but loading it results in the same error.

**Comment by glebuk** [comment]
Hmm.. what overload do you use the save the model?  If you use stream, make sure the stream is flushed and disposed properly (within using(){} statement).  
 Can you check to see if the zip file can be opened by the explorer or other zip file reader?  Is it corrupt?

**Comment by larsbeck** [comment]
@glebuk Yes, the stream is flushed. It is encapsulated in a using block. The zip can be opened fine (see attached).

**Comment by larsbeck** [comment]
I found the issue when I tried to make a minimal sample. The stream was flushed and I was able to open the zip file (the first time), but then after restarting that didn't work anymore, because I was accidentally appending to the zip instead of creating a new file everytime. Closing this issue.
