### ISSUE TITLE
CategoricalSmoothing & Fitting model data

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/machinelearning#3683]
[Enter feedback here]

Is this a feature that helps with solving the issue of unbalanced data in regards to class occurrence (under-fitting)? if so than it would help in high-lighting this. explaining this a bit more would help.

usefull for the user of the documentation is categorizing the properties so that those new to the topic understand what to look for and where to look for it
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3179776-5939-ad12-68ae-0f3bd489bae0
* Version Independent ID: 0f25c6ac-d961-87c0-029a-8303211acc6c
* Content: [LightGbmTrainerBase&lt;TOptions,TOutput,TTransformer,TModel&gt;.OptionsBase.CategoricalSmoothing Field (Microsoft.ML.Trainers.LightGbm)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.lightgbm.lightgbmtrainerbase-4.optionsbase.categoricalsmoothing?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML.Trainers.LightGbm/LightGbmTrainerBase`4+OptionsBase.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Trainers.LightGbm/LightGbmTrainerBase`4+OptionsBase.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by glebuk** [comment]
No, this feature is for ensuring that categories where there there are only few examples per category values are not creating too much impact.   For unbalanced set use the [unbalancedsets](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.lightgbm.lightgbmbinarytrainer.options.unbalancedsets?view=ml-dotnet) instead

**Comment by PeterPann23** [comment]
LightGbmMulticlassTrainer.Options does not seem to have that property or am I missing a namespace?

**Comment by rauhs** [comment]
See #3688. Not available for MC.
