### ISSUE TITLE
LightGBM option MaximumCategoricalSplitPointCount has wrong doc

### ISSUE THREAD

**Issue by rauhs** [dotnet/machinelearning#3687]
See:

https://github.com/dotnet/machinelearning/blob/8b1b14f916428967dc0066b956485c35a0090fe3/src/Microsoft.ML.LightGbm/LightGbmTrainerBase.cs#L189-L196

and

https://github.com/dotnet/machinelearning/blob/8b1b14f916428967dc0066b956485c35a0090fe3/src/Microsoft.ML.LightGbm/LightGbmTrainerBase.cs#L49-L59

and
https://lightgbm.readthedocs.io/en/latest/Parameters.html#max_cat_threshold :

```
max_cat_threshold, default = 32, type = int, constraints: max_cat_threshold > 0
- used for the categorical features
- limit the max threshold points in categorical features
```

It got mixed up with:

https://lightgbm.readthedocs.io/en/latest/Parameters.html#max_cat_to_onehot

```
when number of categories of one feature smaller than or equal to max_cat_to_onehot, one-vs-other split algorithm will be used
```

**Comment by najeeb-kazmi** [comment]
Interestingly, the helptext has the correct description but we somehow mixed it up in the xml doc
