### ISSUE TITLE
[CLI] auto-generated file by Microsoft ML.NET CLI (Command-Line Interface) tool seems to be of not recomended format

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/machinelearning#3697]
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: ML.Net Model Builder (Preview) version 16.0.1905.641

### Issue
- **What did you do?**
Gave the model a csv file with 600 floats and a  header with a label column and some random names
- **What happened?**
Model got build and a Model input file got generated
- **What did you expect?**
The model input file could load all fields but the label field in a single vector but it did not it made a class with single properties and not a features column with a single vector as is recommended here in the issues comments.

Wich is it, what's best practice?
 
### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by justinormont** [comment]
Greetings @PeterPann23: Are you asking why the AutoML didn't join the various feature columns into a single vectored Feature column? 

We debated this a bit. The downside to joining the columns to a single vector column is we won't be able to explore individual feature engineering techniques per column in AutoML. For instance, if we recognize a Latitude / Longitude column, we may want to featurize these two column by binning, merging, and categorical-hash encoding to build 2D squares of locations. In addition, there is pedagogical concerns that a user better understands the column if they are named the same, and individually to match their input dataset. This also encourages users to explore their own feature engineering on the columns. 

This said, when you get to (perhaps) millions of input column, vector column become completely required. Somewhere in between is the right number of column to auto-merge columns into vector columns.

**Comment by PeterPann23** [comment]
ok, makes sense, I also feel like it hinders effective normalisation… not sure if the wizard looks at the values for this. I gave it a few spins and notice that when getting wider the wizard crashes after selecting the csv file. I have added the [Sec.zip](https://github.com/dotnet/machinelearning/files/3165945/Sec.zip) file here so you can have a look. 

I tried the wizard by "Right click" and selecting "Add machine Learning" on the project (probably should be on the solution as it creates a new exe for the dll),

At first I tried it with a 960MB file and gradually wend down smaller and smaller until I got to 50 mb (attached) and it still crashed on me. It writes a WER error log that I have added here as 
[Report.txt](https://github.com/dotnet/machinelearning/files/3165971/Report.txt) I also add the 
[Crash related eventlog events.zip](https://github.com/dotnet/machinelearning/files/3165980/Crash.related.eventlog.events.zip)

Easy to reproduce if you like me to test it with something

**Comment by justinormont** [comment]
Looks like an OOM error in Visual Studio. My guess is that the VS Extension (Model Builder) has issues with the large number of columns. (/cc @rustd) You dataset has 40,731 columns.  

When running directly in the CLI, I don't run out of memory, but it doesn't parse the dataset. Aside from only having one class, "Down", likely from sampling the top of the dataset, the dataset looks well formed.

@glebuk: Is there any in-built limit to the number of columns? I was thinking we could handle ~`int.MaxValue` columns. 

@vinodshanbhag, @daholste, @Dmitry-A:  [Sec.zip](https://github.com/dotnet/machinelearning/files/3165945/Sec.zip) gives me a error of `Microsoft.ML.AutoML.InferenceException: Unable to infer column types of the file provided` in the CLI. Any guesses why?

CLI command:
> `mlnet auto-train --task multiclass-classification --dataset ~/Downloads/Sec.csv  --label-column-name Label --has-header true --name "SEC" --output-path /tmp/blah  --max-exploration-time 10
`

**Comment by PeterPann23** [comment]
Hi, I have only 1 label in it as it's a subset, I just looped over my source data 3TB, not ideal.
I generated the file using the below code, can give you a grater set if you have where I can drop it into
 
        ```
static async Task Main(string[] args)
        {
            var desitnation = new FileInfo(@"H:\MLData\Training\DeepBook\TrainingDataSec.csv");
            var csv = new FileInfo(@"H:\MLData\Training\DeepBook\Sec.csv");
            var sb = new StringBuilder("Label");
            
            for (var i = 0; i < 40_730; i++)
                sb.Append( $",F{i}");

            using var fs= csv.OpenWrite();
            using var sw = new StreamWriter(fs);
            sw.WriteLine(sb.ToString());
            using var sr = new StreamReader(desitnation.OpenRead());

            string line = null;
            do
            {
                line = await sr.ReadLineAsync();
                await sw.WriteLineAsync(line);
                sw.Flush();
            } while (sw.BaseStream.Length / 1048576 < 50);
```
        }

**Comment by CESARDELATORRE** [comment]
In any case, there should be some heuristics in AutoML so when the number of columns is, let's say less than 50 or 100 (TBD number) we generate multiple columns for the reasons explained above (feature engineering) but if there are many hundreds of thousands of columns, then it should load many columns as a single vector. 

An additional approach could be to check for any special post-fix on the column names the user wants to load at the same time into a single vector.. i.e. `col1_vector1, col2_vector1, col3_vector1`, `col1_vector2, col2_vector2, col3_vector2`, etc.

This is a topic being discussed by us for next versions, in any cae. Thanks for the feedback! 👍 

About Model Builder (VS) it is currently limited to number of columns and other limitations due to UI.
The CLI and AutoML API should handle up to any limit in ML.NET.

**Comment by PeterPann23** [comment]
any suggestions on how to alter the dataset now to use the command line
`mlnet auto-train --task multiclass-classification --dataset "H:\MLData\Training\DeepBook\TrainingDataMain.csv" --label-column-index 0 -H false`

Generates:
```
An Error occured during inferring columns
Unable to infer column types of the file provided.
Please see the log file for more info.
Exiting 
```

**Comment by srsaggam** [comment]
Looks like it may be  happening because of the following check .
```
 private const int SmartColumnsLim = 10000;
......
......
......

if (args.ColumnCount >= SmartColumnsLim)
            {
                // too many columns for automatic inference
                return InferenceResult.Fail();
            }
```

@daholste  @vinodshanbhag  Do we know why we are limiting to 10000 column limit?

**Comment by srsaggam** [comment]
Created an issue for this.
https://github.com/dotnet/machinelearning/issues/3703

**Comment by PeterPann23** [comment]
cool, I will close this then
