### ISSUE TITLE
DataViewSchema not validated for null on training, but is required for creating PredictionEngine

### ISSUE THREAD

**Issue by Deucem** [dotnet/machinelearning#3698]
### System information

- **OS version/distro**:
Windows 10 Pro 1806 (also happens in Azure web app)
- **.NET Version (eg., dotnet --info)**: 
2.2.104

### Issue

- **What did you do?**
Saved a model passing null for the DataViewSchema.

- **What happened?**
When you save a model with a using mlContext.Model.Save and pass null for the DataViewSchema, the model trains fine, but when you attempt to consume the model, a null reference exception is thrown:

"at Microsoft.ML.Data.DataViewConstructionUtils.GetSchemaDefinition[TRow](IHostEnvironment env, DataViewSchema schema)"

- **What did you expect?**
The mlContext.Model.Save method should throw on null DataViewSchema input parameter.

### Source code / logs

"at Microsoft.ML.Data.DataViewConstructionUtils.GetSchemaDefinition[TRow](IHostEnvironment env, DataViewSchema schema)"

**Comment by PranovD** [comment]
mlContext.Model.Save method purposefully allows for null input parameter for DataViewSchema therefore this is not a bug
See src/Microsoft.ML.Data/Model/MOdelOperationsCatalog.cs line 103:
`/// <param name="inputSchema">The schema of the input to the transformer. This can be <see langword="null"/>.</param>`
