### ISSUE TITLE
TransfromWrapper should only apply the last transform in some cases

### ISSUE THREAD

**Issue by codemzs** [dotnet/machinelearning#3699]
Consider the pipeline generated from NimbusML that adds OptionalColumnTransform automatically to make sure label column is of correct type, i.e key type. When this model is loaded in ML.NET, OptionalColumnTransform is executed as TransformWrapper that is instantiated with an IDataView containing the entire pipeline until that point. Unfortunately transform wrapper applies the entire chain of transforms when it should just apply the last transformer in the chain, this holds true if we had a IDataTransform preceded by RowToRowMapperTransfom.

CC: @yaeldekel

**Comment by wschin** [comment]
I don't understand the desired behavior here. 
- Do you mean that `OptionalColumnTransform` should not be mapped to a `TransformWrapper`?
- Why can we only execute the last step? I expect that for doing a prediction, user needs to run the entire pipeline.

**Comment by codemzs** [comment]
OptionalColumnTransform is mapped to TransformWrapper.
You will run the whole pipeline but transform wrapper should just execute the last transform.
