### ISSUE TITLE
Question: Timeseries analysis

### ISSUE THREAD

**Issue by lefig** [dotnet/machinelearning#3714]
Hi all,

I wish to reach out to you concerning the best approach to use for time series based analysis. 

I appreciate that the platform at present does not have support for many deep learning features such as LSTM. But with release 1.0 in mind, are there any examples or resources to illustrate an approach to analysis?

If not it would be great to see this on the future release roadmap.

Ta, best wishes

**Comment by najeeb-kazmi** [comment]
Hi @lefig - we currently have a [PCA anomaly detection trainer](https://github.com/dotnet/machinelearning/tree/master/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/AnomalyDetection) in ML.NET, as well as some transforms for spike and change point detection. See the [transforms samples](https://github.com/dotnet/machinelearning/tree/master/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/TimeSeries) for more.

**Comment by lefig** [comment]
Hi @najeeb-kazmi , thank you for kindly advising further. 

Yes, I have taken a look and this looks like being the way to go. Much appreciated.

Fig
