### ISSUE TITLE
Exception: When previewing data

### ISSUE THREAD

**Issue by lefig** [dotnet/machinelearning#3718]
An exception is generated within the following function:

`public static void PeekDataViewInConsole(MLContext mlContext, IDataView dataView, IEstimator<ITransformer> pipeline, int numberOfRows = 4)
        {
          
            var transformer = pipeline.Fit(dataView);
            var transformedData = transformer.Transform(dataView);

            // 'transformedData' is a 'promise' of data, lazy-loading. call Preview  
            //and iterate through the returned collection from preview.

Exception:
            var preViewTransformedData = transformedData.Preview(maxRows: numberOfRows);

This is because the data that is read contains a Datatime format column. Is there a way to remove this column from the Preview call?

Thanks

**Comment by najeeb-kazmi** [comment]
Hi @lefig - you can exclude the Datetime column from transformedDate by applying the `DropColumns` transform. You can do this either in your `pipeline` before calling `pileline.Fit(dataView)`, or you can add this to another pipeline and fit it on `transformedDate`. The second option would look something like the following:

```csharp
var dropPipeline = mlContext.Transforms.DropColumns("Datetime_column_name");

var dataWithoutDatetime = dropPipeline.Fit(transformedData).Transform(transformedData);
```

Here's a [sample](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/DropColumns.cs) that does this as well.

**Comment by lefig** [comment]
Hi @najeeb-kazmi,

That is perfect! I appreciate your help with this one after a long struggle trying to figure out the best approach.

Many thanks

Fig

**Comment by lefig** [comment]
Question kindly answered
