### ISSUE TITLE
Sse math doesn't contain `Div64` and `TryMulDiv64Core`

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#3720]
These are used in `IntUtils.cs` [here](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.CpuMath/IntUtils.cs#L76) and [here](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.CpuMath/IntUtils.cs#L314), but they are not in the native code.

**Comment by codemzs** [comment]
@yaeldekel is this needed for TLC?

**Comment by codemzs** [comment]
CC: @eerhardt @tannergooding any idea?

**Comment by tannergooding** [comment]
Could you clarify what you are expecting?

`Div64` and `TryMulDiv64Core` are not SSE instructions and so I wouldn't expect them to be exposed as part of any SSE library (and we don't have any existing intrinsics for them).

Those definitions look to have been introduced as part of the initial population of the `dotnet/machinelearning` repo, so I imagine they were only used by the internal repo.

**Comment by yaeldekel** [comment]
`TryMulDiv64` is not used anywhere, so it can be removed. `Div64` is used in two methods in `MissingValueReplacingTransformer`, but these two methods are not used either.

The `DllImport`s of these functions should be removed from the `IntUtils` class.
