### ISSUE TITLE
documentation for the correct implmementation ExperimentResult progress handler for Multiclass

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/machinelearning#3728]
Haling a look at the AutoML API I have noted that documentation for [Multiclass experiment](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.automl.multiclassclassificationexperiment?view=automl-dotnet) does not document a progress handler. 

Would be nice if there is a way to get this documented as I feel that this can be usefull

**Comment by PeterPann23** [comment]
I like the implementation in the AutoML samles solution a lot, perhaps simplyfy it a litle inbeding it in the documentation online. 

With simplifying it I mean remove ConsoleHelper so that it can be used as ab basis in the code of those that would like to use it/ test it

```
public class MulticlassExperimentProgressHandler : IProgress<RunDetail<MulticlassClassificationMetrics>>
    {
        private int _iterationIndex;

        public void Report(RunDetail<MulticlassClassificationMetrics> iterationResult)
        {
            if (_iterationIndex++ == 0)
            {
                ConsoleHelper.PrintMulticlassClassificationMetricsHeader();
            }

            if (iterationResult.Exception != null)
            {
                ConsoleHelper.PrintIterationException(iterationResult.Exception);
            }
            else
            {
                ConsoleHelper.PrintIterationMetrics(_iterationIndex, iterationResult.TrainerName,
                    iterationResult.ValidationMetrics, iterationResult.RuntimeInSeconds);
            }
        }
    }

```

**Comment by luisquintanilla** [comment]
Thanks for the feedback. We've recently updated our AutoML implementation based on FLAML.

For more information, see the [blog post](https://devblogs.microsoft.com/dotnet/whats-new-with-mldotnet-automl/#automl-updates) and [sample notebooks](https://github.com/dotnet/csharp-notebooks/blob/main/machine-learning/03-Training%20and%20AutoML.ipynb) 

Closing this issue.
