### ISSUE TITLE
CLI does not support other cultures besides en-US

### ISSUE THREAD

**Issue by tbombach** [dotnet/machinelearning#3729]
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: 3.0.100-preview-5-011568

### Issue

- **What did you do?**
Ran CLI auto-train on a TSV file with culture set to Finnish.
1. Set Windows Regional format to Finnish.
    - Download the Finnish language pack from the Microsoft store (it's called suomi): https://www.microsoft.com/store/productId/9MW3PQ7SD3QK
    - Change the format to "Finnish (Finland)" in `Windows settings -> Time & Language -> Region -> Regional format`
2. Run CLI:
    - `mlnet auto-train --task regression --dataset taxi-fare-train.csv --label-column-name fare_amount -- max-exploration-time 10`
    - File: https://github.com/dotnet/machinelearning-samples/blob/master/samples/CLI/Regression_CLI/taxi-fare-train.csv

- **What happened?**
Error:
```
Exception occured while exploring pipelines:
Provided label column 'fare_amount' was of type String, but only type Single is allowed.
Please see the log file for more info.
Exiting ...
```
- **What did you expect?**
Successful model training. Switching the regional format back to "English (United States)" allows training to complete successfully.

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by rustd** [comment]
This was reported by customers using Model Builder. Adding automl and gui labels to highlight that.

**Comment by srsaggam** [comment]
Thank you for filing this issue. Looks like we missed out on culture info on some of the places in AutoML API. This shall be fixed in coming versions.

Please note that this bug is different from #3677 
It is the same issue but happened in the code generation engine of CLI.

**Comment by justinormont** [comment]
Closed by https://github.com/dotnet/machinelearning/pull/3731
