### ISSUE TITLE
[Model Builder] Best accuracy not found in Top 5 models

### ISSUE THREAD

**Issue by Doggie52** [dotnet/machinelearning#3734]
### System information

- **OS version/distro**: Windows 10.0.18362 x64
- **.NET Version (eg., dotnet --info)**:  2.1.507
- **ML.NET Model Builder version**: 16.0.1905.641
- **Visual Studio 2017 version**: 15.9.12

### Issue

- **What did you do?** Ran ML.NET Model Builder in Visual Studio and trained a binary classification model for 120 seconds
- **What happened?** The _Best Model Accuracy_ was given as 80.65% but the best model in the Top 5 models was listed as having 75.00% accuracy. See picture below for an example
- **What did you expect?** I would expect the _Best Model Accuracy_ to match the best model's  accuracy perfectly.

### Source code / logs

![image](https://user-images.githubusercontent.com/4928988/57849473-4a4ee500-77d3-11e9-988a-8bbcfe73b88c.png)

Do let me know if you need any logs or otherwise.

**Comment by rustd** [comment]
Thank you for reporting this. This is a known issue and we are fixing it for our next update which will be soon.

**Comment by whitmark** [comment]
Similar issue with regression ML Task using the Price Prediction Scenario in VS 2019.

![image](https://user-images.githubusercontent.com/8396992/58746801-84092800-8430-11e9-8849-4ea3286d1844.png)

**Comment by rustd** [comment]
This was fixed in the last update to Model Builder. Please update your Model Builder extension and open a new issue if this can still be reproduced.

**Comment by whitmark** [comment]
@rustd, thanks . . . seems to work fine now.

![image](https://user-images.githubusercontent.com/8396992/60832171-3eefb880-a189-11e9-91f6-c6c00906cc82.png)

**Comment by rustd** [comment]
Great. Thank you for confirming!
