### ISSUE TITLE
StochasticDualCoordinateAscentClassifier

### ISSUE THREAD

**Issue by bs6523** [dotnet/machinelearning#374]
anyone know how is "StochasticDualCoordinateAscentClassifier()" working? is there any explanation for that? I cant understand how it's working in the background.
Is it a neural net model or some other model?

**Comment by jwood803** [comment]
I take it from [this paper](https://www.csie.ntu.edu.tw/~cjlin/papers/cddual.pdf) that it looks like it's a way to perform a Support Vector Machines (SVM) algorithm.

**Comment by TomFinley** [comment]
Hi @jwood803 and @bs6523 .

The method certainly can be applied as an SVM if you apply the method on the binary classifier with the `HingeLossSDCAClassificationLossFunction`. However by default it is logistic loss, that is, `LogLossSDCAClassificationLossFunction`.

There's a [paper here about this method in particular](https://www.microsoft.com/en-us/research/publication/scaling-up-stochastic-dual-coordinate-ascent/).

...aaaand despite the fact that my name is right there in the paper and all they had to do was copy-paste it, I see whoever put this page together still managed to misspelled my name "Finely." That's a great start to my day. :smile:

**Comment by glebuk** [comment]
@bs6523,
Simply put, SDCA is a fast, scalable, multicore  linear classifier with support for L1 and L2 regularization.

**Comment by abgoswam** [comment]
DRI RESPONSE: Questions seems to have been answered. I plan to close the issue withing the next few days.
