### ISSUE TITLE
Question: Deep Learning and Doc2Vec

### ISSUE THREAD

**Issue by larsbeck** [dotnet/machinelearning#3743]
Hi, 

I was wondering if there are any plans to allow modeling deep neural networks. I know that it is possible to consume Tensorflow models. I am interested in creating and training models directly in ml.net

Unrelated to the first question: Are there any plans to implement Doc2vec as an alternative to the current FeaturizeText feature.

In case this issue tracker is the wrong place to ask questions, please point me to the site you might be using for questions.

Thanks, 

Lars

**Comment by yaeldekel** [comment]
Hi Lars,
Thank you for your interest in ML.NET. We do have plans to support training of deep neural networks. Currently, we have partial support of re-training an existing Tensorflow model, and we plan to expand this capability in the future.

Regarding Doc2vec, I am not aware of any plans regarding this, but I will open a new issue for this so it can be tracked separately.

**Comment by larsbeck** [comment]
Thanks! I'll check out new versions then. Keep up the great work!
