### ISSUE TITLE
"The following inputs are missing..." error message

### ISSUE THREAD

**Issue by korzh** [dotnet/machinelearning#375]
### Issue

I changed my testing application from loading training data from file (using TextLoader) to loading them from the data objects in memory using CollectionDataSource.    
At the very first attempt I forgot to include my training collection to the pipeline (`pipline.Add(collection)` were missed) and got a very strange error message:
```
System.InvalidOperationException: 'The following inputs are missing: Var_b9ec7864fc3943e9b9ab9d9b38020e3c'
```

I guess the error message must be more understandable. Like "No training collection" or something similar.

**Comment by glebuk** [comment]
#371 Should address this. The error message is from the Entrypoint compiler.  Next  version of API will change this mechanism.

**Comment by Ivanidzo4ka** [comment]
DRI RESPONSE: This issue about our legacy API. I'm intent to close this issue within next few days, unless someone objects.

**Comment by korzh** [comment]
Agree. New API resolves this issue.
