### ISSUE TITLE
AutoML Code generation generates failing code if the CSV provided have a header named Label

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/machinelearning#3750]
### System information

- **OS version/distro**:
windows 10
- **.NET Version (eg., dotnet --info)**: 
AutoMl Wizard Rel 0.3.0
### Issue

- **What did you do?**
Created a CSV file for the wizard with a column that it needed to predict with the name Label
- **What happened?**
The code generation created a KeyValue mapper with Label =>Label and PredictedLabel=>PredictedLabel 

```
public static IEstimator<ITransformer> BuildTrainingPipeline(MLContext mlContext)
{
	// Data process configuration with pipeline data transformations 
	var dataProcessPipeline = mlContext.Transforms.Conversion.MapValueToKey("Label", "Label")
							  .Append(mlContext.Transforms.Concatenate("Features", new[] { "F1", "F2", "F3"}));

	// Set the training algorithm 
	var trainer = mlContext.MulticlassClassification.Trainers.LightGbm(labelColumnName: "Label", featureColumnName: "Features")
							  .Append(mlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel", "PredictedLabel"));
	var trainingPipeline = dataProcessPipeline.Append(trainer);

	return trainingPipeline;
}
```
When executing the training the code fails here

![sample fails](https://user-images.githubusercontent.com/44400822/58049408-15cd8700-7b4d-11e9-989c-5d7c430f581c.PNG)

- **What did you expect?**
Writing code that covers all possible issues is hard however as MapValueToKey goes to an internal field and MapKeyToValue cpmes from that internal field it might help not using the same name.
Would be nice if the starter project would work, gives those that give the project a spin a positive vibe.

Perhaps warn the user that he may needs to change the code, if this occurs, better would be if the issue doesn't happen.

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by justinormont** [comment]
@srsaggam: Any ideas?

**Comment by luisquintanilla** [comment]
Closing this issue since it relates to an old implementation.
