### ISSUE TITLE
OneHotEncoder on array of strings

### ISSUE THREAD

**Issue by huy302** [dotnet/machinelearning#3767]
I couldn't find an example to run OneHotEncoder on an array of strings. From the sample code at https://github.com/dotnet/machinelearning/issues/2678 is it just as simple as ctx.Transforms.Categorical.OneHotEncoding("A")? Preview function is yet to be fixed in ml.net 1.0.0 so I can't tell if it gives the desired result.

Thanks

**Comment by najeeb-kazmi** [comment]
@huy302 yes, if you have a column in your input class that is an array of `string`, this column will be a Vector column of type `string` in the loaded `IDataView`, and you can apply OneHotEncoding to it as described in #2678. 

If you want to apply OneHotEncoding to multiple columns, you can use the `InputOutputColumnPair` class as described in [this sample](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Categorical/OneHotEncodingMultiColumn.cs).
https://github.com/dotnet/machinelearning/blob/ea16019ac987e3260e665326ef7cce4b23d1ac0f/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Categorical/OneHotEncodingMultiColumn.cs#L29-L35
