### ISSUE TITLE
AutoML feature request for TensorFlow

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/machinelearning#3770]
Would be nice to see some TensorFlow integration in AutoML.
One find nice Multiclass Iris prediction with TensorFlow in Python in the web. 
Would be nice to see it implemented in AutoMl as I guess it's a good _bootstrap'er_  for those that would like to implement it.

**Comment by justinormont** [comment]
We are expecting to add Image support to AutoML. 

I was anticipating making use of the [DnnImageFeaturizer](https://github.com/dotnet/machinelearning/blob/a5f09772279b1f947072ff5ca28e27c76726e156/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/ImageAnalytics/DnnFeaturizeImage.cs#L40-L46) so the user won't have to keep track of a custom TF/ONNX model, which makes productionization one step easier.

--

In the meantime, feel free to design a sample project feeding a TF model into AutoML. 

You can use the preFeaturizer input to the AutoML API, which ensures data doesn't leak between Train/Test or CV folds ([example](https://github.com/dotnet/machinelearning-samples/blob/5831bdd9bea8e42e1d3e4967486653a5df1abe4c/samples/csharp/getting-started/AdvancedExperiment_AutoML/AdvancedTaxiFarePrediction/Program.cs#L104-L105)). The images transforms are non-trainable so won't leak data, but other transforms will, so it's safer to teach the use of the preFeaturizer.

In the preFeaturizer chain, you can can run a TF model and the image loader/resizing/etc.

**Comment by PeterPann23** [comment]
I'd like to do something with TF that's not related to images, TF has a lot of potential for several problem domains and it'l be nice to show that .net rocks at doing this.

**Comment by CESARDELATORRE** [comment]
Can you suggest those scenarios? Note that currently with ML.NET you can just score TF models or do transfer learning in the final layer only..

**Comment by PeterPann23** [comment]
The limitation is part of the issue I guess, "we" state we do TF but do we.... 
Doing a search on the internet one can see nice samples using TF to analyse audio, text, price prediction housing  etc. The most interesting I guess as it allows comparison is if we would be able to demonstrate the [Iris sample](https://www.kaggle.com/pierrek20/multiclass-iris-prediction-with-tensorflow-keras)
