### ISSUE TITLE
Bitmap data

### ISSUE THREAD

**Issue by nfnpmc** [dotnet/machinelearning#3784]
What is (I assume a variable) Enumerable and how do you get it from a Bitmap or Image, neither of which is Enumerable? Two loops to examine the pixels and put it into a linear array?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b9c0132-7901-8114-b8bc-faa09ad74797
* Version Independent ID: 8274abb2-6952-674b-e8bc-1e314aeee4cc
* Content: [TensorFlowModel.ScoreTensorFlowModel Method (Microsoft.ML.Transforms)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.tensorflowmodel.scoretensorflowmodel?view=ml-dotnet-preview#feedback)
* Content Source: [dotnet/xml/Microsoft.ML.Transforms/TensorFlowModel.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Transforms/TensorFlowModel.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by yaeldekel** [comment]
Hi @nfnpmc ,

The data in ML.NET is always passed as an `IDataView`. We have a convenience method to convert an enumerable of objects of a given type to an `IDataView` by converting each field in the given type to a column in the `IDataView`. Currently, this method does not yet support classes with `Bitmap` fields, but there is a PR #3263 to add this support.

Does this answer your question?

**Comment by wschin** [comment]
Yes, as you can see [here](https://github.com/dotnet/machinelearning/blob/b4e5a618d775df17228c5d73c86820429a062408/test/Microsoft.ML.Tests/ImagesTests.cs#L191), after merging #3263, this issue can be closed.

**Comment by nfnpmc** [comment]
Yes, but, the loading from a filename generates, AFAIK, a bitmap for input, which is then Transformed by ExtractPixels.Is there any way to miss out the text loading and pass the bitmap to ResizeImages then ExtractPixels?Someone suggested converting the Image to a tensor and passing that as a vector (of unknown length), is this a viable option?
Kind regards, nfnpmc 

    On Tuesday, 28 May 2019, 17:08:31 BST, Yael Dekel <notifications@github.com> wrote:  
 
 
Hi @nfnpmc ,

The data in ML.NET is always passed as an IDataView. We have a convenience method to convert an enumerable of objects of a given type to an IDataView by converting each field in the given type to a column in the IDataView. Currently, this method does not yet support classes with Bitmap fields, but there is a PR #3263 to add this support.

Does this answer your question?

**Comment by nfnpmc** [comment]
How, when, will this be available to update Visual Studio, please?
Regards, Peter 

    On Tuesday, 28 May 2019, 18:01:03 BST, Wei-Sheng Chin <notifications@github.com> wrote:  
 
 
Yes, as you can see here, after merging #3263, this issue can be closed.

**Comment by Lelelo1** [comment]
I am also looking for this update, I think? In my data structure model  I would like to have a column of Bitmap:
```
[ColumnName("Bitmap")]
        public Bitmap bitmap; // https://github.com/dotnet/machinelearning/issues/3784
        
```
