### ISSUE TITLE
Prediction multiclass only transmit score Label and label index are "" and 0

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/machinelearning#3787]
### System information

- **OS version/distro**: 
Windows 10
- **.NET Version (eg., dotnet --info)**: 
.Net Core 3.0, Microsoft.ML 1.0.0

### Issue

- **What did you do?**
I created a pipline like so:
```
var sdcaPipeline = mlContext.Transforms.Conversion.MapValueToKey(outputColumnName: DefaultColumnNames.KeyColumn, inputColumnName: DefaultColumnNames.Label,keyOrdinality:ValueToKeyMappingEstimator.KeyOrdinality.ByOccurrence)
    .Append(mlContext.Transforms.Concatenate(DefaultColumnNames.RawFeatures, MSBar2.GetColumnNames(DataKind.Single)))
    .Append(mlContext.Transforms.NormalizeMinMax(outputColumnName: DefaultColumnNames.Features,inputColumnName:DefaultColumnNames.RawFeatures))
    .AppendCacheCheckpoint(mlContext)
    .Append(mlContext.MulticlassClassification.Trainers.SdcaMaximumEntropy(labelColumnName : DefaultColumnNames.KeyColumn ,featureColumnName: DefaultColumnNames.Features))
    .Append(mlContext.Transforms.CopyColumns(inputColumnName: KeyColumn, outputColumnName: DefaultColumnNames.PredictedLabelIndex))
    .Append(mlContext.Transforms.Conversion.MapKeyToValue(inputColumnName: DefaultColumnNames.KeyColumn ,outputColumnName: DefaultColumnNames.PredictedLabel));                      

var model=  sdcaPipeline.Fit(trainingDataView);
```

- **What happened?**
When performing a single prediction the score property is placed. However the DefaultColumnNames.PredictedLabel and DefaultColumnNames.PredictedLabelIndex are always populated with the .net default values of empty string and 0

- **What did you expect?**
I'd expect the values to be mapped as it is configured in the pipeline

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by PeterPann23** [comment]
closing as no one picks up on it

**Comment by magicdict** [comment]
var model=  sdcaPipeline.Fit(trainingDataView);
I think you should transform your test data by the model.
A Score Column is need to get the result.
I think this framework is not ready.........Try python.....

**Comment by PeterPann23** [comment]
Score column gets generated by the framework, no need to define it.
