### ISSUE TITLE
What data to be fed into PermutationFeatureImportance?

### ISSUE THREAD

**Issue by huy302** [dotnet/machinelearning#3791]
In general I know that the data should be transformed by the trained model before being fed into PermutationFeatureImportance, but should it be transformed training data or test data, assuming I have both? and why?
I've been reading documents and related issues but couldn't find the answer. Thanks

**Comment by PeterPann23** [comment]
var transformedData = model.Transform(data);

Have a look at the [Cookbook](https://github.com/dotnet/machinelearning/blob/master/docs/code/MlNetCookBook.md#how-do-i-get-a-models-weights-to-look-at-the-global-feature-importance)
```
var featureImportance = context.Regression.PermutationFeatureImportance(model.LastTransformer, transformedData);

for (int i = 0; i < featureImportance.Count(); i++)
{
    Console.WriteLine($"Feature {i}: Difference in RMS - {featureImportance[i].RootMeanSquaredError.Mean}");
}
```

**Comment by huy302** [comment]
I found this article where it clearly says it should be transformed training data 
https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/explain-machine-learning-model-permutation-feature-importance-ml-net
