### ISSUE TITLE
LearningPipeline was not found

### ISSUE THREAD

**Issue by Traijan1** [dotnet/machinelearning#3806]
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**:  2.1.602
### Issue

Hello,
my issue is that when I want to use "var pipeline = new LearningPipeline();" I get an error by "LearningPipeline()"

A picture: http://prntscr.com/nx29zl

The error says: "The type or namespace name "LearningPipeline" was not found"
Code: CS0246

- **What did you do?**
I found nothing.
- **What happened?**
- **What did you expect?**

### Source code / logs

```csharp
using System;
using Microsoft.ML;
using Microsoft.ML.Data;

using System.Threading.Tasks;

namespace Test {
    class Program {
        static void Main(string[] args) {
            var pipeline = new LearningPipeline(); 
        }
    }
}
```

**Comment by PeterPann23** [comment]
Hi,
Normally you'd start the Pipeline a bit different, Have a look at the [CookBook](https://github.com/dotnet/machinelearning/blob/master/docs/code/MlNetCookBook.md)

**Comment by eerhardt** [comment]
`LearningPipeline` was a concept in ML.NET's old API. 

Check out the tutorials on https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/ for how to use the `1.0` stable APIs.

**Comment by yaeldekel** [comment]
Hi @Traijan1, as @eerhardt mentioned, the `LearningPipeline` API is old and does not exist anymore. I am closing this issue, please feel free to reopen it, or submit new issues if you have any questions about the new API.
