### ISSUE TITLE
System.ArgumentException: 'Length of memory  must match product of dimensions.

### ISSUE THREAD

**Issue by cemicel** [dotnet/machinelearning#3816]
- windows 10
- 4.7.NET Version  
- ML dotnet 1.0
- Visual Studio 15.9.12

Issue:

I'm quite new to .net, however I'm trying to replicate CRNN model developed on keras to ML dotnet. I successfully converted the model to onnx format. But when I try to make a prediction I'm getting this:
 _System.ArgumentException: 'Length of memory (9600) must match product of dimensions (3200).'_
I didn't find any issue or something so that is way I'm writing here.

I can assume that the problem might be somewhere in image transformation. My model is built for grayscale images with the shape of (1, 1, 32, 100) and there I have this conflict between:
1x32x100 = 3200 (should be)  vs  3x32x100 = 9600 (actually is)

I've tried to transform images to grayscale, but it doesn't work (perhaps I do it in a wrong way).

This is my snipped code for building the pipeline:

`

        int imageHeight = 32;
        int imageWidth = 100;
        bool ChannelsLast = false;
        string ModelInput = "conv2d_1_input_01";
        string ModelOutput = "dense_1_add_0";

        var pipeline = mLContext.Transforms.LoadImages(outputColumnName: "conv2d_1_input_01",
                                                           imageFolder: imagesLocation,
                                                           inputColumnName: nameof(ImageData.ImagePath))
            .Append(mLContext.Transforms.ResizeImages(outputColumnName: "conv2d_1_input_01",
                                                            imageWidth: imageWidth,
                                                            imageHeight: imageHeight))
            .Append(mLContext.Transforms.ConvertToGrayscale(outputColumnName:
                                                            "conv2d_1_input_01"))
            .Append(mLContext.Transforms.ExtractPixels(outputColumnName: "conv2d_1_input_01", interleavePixelColors: ImageSettings.ChannelsLast))
            .Append(mLContext.Transforms.ApplyOnnxModel(modelFile: modelLocation,
                                                            outputColumnNames: new[] { ModelOutput },
                                                            inputColumnNames: new[] { ModelInput }));
`

I would appreciate any help or comments.

**Comment by cemicel** [comment]
I was able to omit the problem by changing model's input shape to consume 3-channel images.
It is not the solution.

**Comment by yaeldekel** [comment]
Hi @cemicel, thank you for your question. The `ConvetToGrayscale` transform converts the image to gray scale, but it keeps all the channels (alpha, R, G and B). the `ExtractPixels` transform has an option called `colorsToExtract`, where you can specify that you would only like to extract the alpha channel:
```
mLContext.Transforms.ExtractPixels(outputColumnName: "conv2d_1_input_01", colorsToExtract: ImagePixelExtractingEstimator.ColorBits.Alpha)
```

**Comment by cemicel** [comment]
Hello @yaeldekel,
Thank you for your explanation, now it make sense for me.
