### ISSUE TITLE
how will you know this at the time of coding...

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/machinelearning#3817]
I guess it would be appropriate to set this value at runtime as a developer can hardly know what runtime value will be in effect without knowing the data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d7b6ec7-078a-9f61-3250-ceba1a3a1846
* Version Independent ID: 13902a2a-592f-a075-a68e-b09002f8e714
* Content: [LightGbmBinaryTrainer.Options.WeightOfPositiveExamples Field (Microsoft.ML.Trainers.LightGbm)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.lightgbm.lightgbmbinarytrainer.options.weightofpositiveexamples?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML.Trainers.LightGbm/LightGbmBinaryTrainer+Options.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Trainers.LightGbm/LightGbmBinaryTrainer+Options.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by yaeldekel** [comment]
Hi @PeterPann23, the `WeightOfPositiveExamples` option is passed directly to `LightGbm`, so it may be a better question to ask on the `LightGbm` GitHub page: https://github.com/microsoft/LightGBM.
Thank you!
