### ISSUE TITLE
ML.NET support for CNTK

### ISSUE THREAD

**Issue by deepakkumar1984** [dotnet/machinelearning#3846]
Does ML.NET support CNTK? I see support for Tensorflow, what about the MS initiative for CNTK. Is that abandon now?

**Comment by CESARDELATORRE** [comment]
ML.NET doesn't directly support CNTK but you can run any ONNX model with ML.NET, so if you export a CNTK model to ONNX, you could do it.

You can read about ONNX support in CNTK here and about CNTK's future here:

https://docs.microsoft.com/en-us/cognitive-toolkit/releasenotes/cntk_2_7_release_notes 

But basically, this is what's said in there:

"CNTK 2.7 release will be the last main release of CNTK. We may have some subsequent minor releases for bug fixes, but these will be evaluated on a case-by-case basis. There are no plans for new feature development post this release.".

From Microsoft, there's significant investment on TensorFlow and Torch, as open source projects, though.

**Comment by deepakkumar1984** [comment]
Thanks, the last statement makes it all clear for the future of CNTK :)
