### ISSUE TITLE
Sanity check APIs from Microsoft.ML.Tensorflow nuget

### ISSUE THREAD

**Issue by codemzs** [dotnet/machinelearning#3863]
We plan to GA Microsoft.ML.Tensorflow nuget in 1.2 release. Lets do a final pass on the binary and make sure we are only exposing relevant API.

**Comment by eerhardt** [comment]
Looking myself, I see the following places that require attention. There may be more, but these popped out to me.

1. `TensorFlowUtils` is a public class, but it doesn't have any externally visible members:

https://github.com/dotnet/machinelearning/blob/f0f34ac37c4aa7fbe6f2df332aaa8c6c0083f632/src/Microsoft.ML.TensorFlow/TensorFlow/TensorflowUtils.cs#L17

We should make it `internal`.

2. `TensorFlowModel` contains the most important method of the component - `ScoreTensorFlowModel`. However, it also contains a `RetrainTensorFlowModel` whose documentation say it is "experimental":

https://github.com/dotnet/machinelearning/blob/f0f34ac37c4aa7fbe6f2df332aaa8c6c0083f632/src/Microsoft.ML.TensorFlow/TensorFlowModel.cs#L105-L108

I think it is confusing to have an "experimental" API on the same class as a stable API.

**Comment by codemzs** [comment]
Thanks @eerhardt, below is the APIsurface after hiding necessary stuff. Retrain can wait, we are planning to expose more advance TF scenarios and retrain will come there with TF.NET backend.

![image](https://user-images.githubusercontent.com/1211949/60436263-8cd05380-9bc0-11e9-950c-c3b46da77c34.png)
