### ISSUE TITLE
Document what's supported in "ONNX-ML.NET"

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning#3866]
@wschin, @codemzs 
Related to ONNX. Can we have documented what is supported when using ONNX from ML.NET? - Either for both scenarios: 1. Export/convert model scenario and 2. Load ONNX model scenario.

For instance:

- 1. When exporting ML.NET models to ONNX with [ConvertToOnnx()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.onnxexportextensions.converttoonnx?view=ml-dotnet-preview), will any type of ML.NET model work as ONNX model executed later on by the ONNX runtime from any other framework? **In ML.NET preview versions only certain ML.NET models could be exported to the ONNX-ML format. Is that still the case?** 

- 2. Can any type of loaded ONNX model run on ML.NET?

For instance, in the reference for [ConvertToOnnx()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.onnxexportextensions.converttoonnx?view=ml-dotnet-preview) it doesn't say what's supported and what's not.

**Do we have any documentation stating what's supported and what's not supported in "ONNX-ML.NET"?**

In addition to that, performance/accuracy comparison should also be covered due to issues like this:
[ONNX Exports are Lossy](https://github.com/dotnet/machinelearning/issues/3206)

**Comment by harishsk** [comment]
This has already been added to the docs.
