### ISSUE TITLE
Improve the documentation on the trainer classes. 

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#388]
The documentation describing the trainers on [docs.microsoft.com ](https://docs.microsoft.com) needs to be expanded.

**Comment by pkulikov** [comment]
Is it going to be a large overlap of the remarks in API with the topic that is under construction in dotnet/docs#5698?

**Comment by shauheen** [comment]
Closing this as the main PRs are merged and issue #477 is open to make further enhancements
