### ISSUE TITLE
Why does using statement need to be included?

### ISSUE THREAD

**Issue by isaacwalkercox** [dotnet/machinelearning#3901]
I was struggling to use the instance of MLContext to create a trainer by writing context.MulticlassClassification.Trainers because the methods were not appearing at the end of Trainers. As soon as I put "using Microsoft.ML" at the top of my code after loads of fiddling about, it worked. Can someone please explain why?

**Comment by jwood803** [comment]
Those methods are [extensions methods](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods) which allow you to add methods to existing types. However, when using an extension method the `using` statement where the extension methods are located needs to be included so the compiler knows where they are.

Hope that helps!

**Comment by isaacwalkercox** [comment]
Thank you for the clarification. I don't think I have used extension
methods before! You learn something new every day! :)
