### ISSUE TITLE
AutoML: Misspelling in user-visible error...

### ISSUE THREAD

**Issue by greazer** [dotnet/machinelearning#3906]
Not a huge deal, but an external customer did see this.  

In \machinelearning\src\Microsoft.ML.Data\Evaluators\AucAggregator.cs...

Contracts.CheckParam(PosSample.Any(), nameof(PosSample), "AUC is not definied when there is no positive class in the data");
Contracts.CheckParam(NegSample.Any(), nameof(NegSample), "AUC is not definied when there is no negative class in the data");

"defined" is misspelled.

**Comment by mstfbl** [comment]
[PR #3613](https://github.com/dotnet/machinelearning/pull/3613) has fixed this issue.
