### ISSUE TITLE
PredictionEngine.Predict returns null

### ISSUE THREAD

**Issue by isaacwalkercox** [dotnet/machinelearning#3907]
Is there any reason that my PredictionEngine would be returning a null result when trying to predict a value in a multi-class classification smiliar to the GitHub Labeler? That sample works perfectly, by the way, because I tested it. I cannot release the code at this time, I understand this will not be helpful to you and I am sorry.

**Comment by isaacwalkercox** [comment]
PredictedLabel that I got directly from the sample didn't work in my code and yet in worked in the version of the sample I built and I am confused. Anyway, it's fixed but I am leaving this open for further comments as to the root cause.

**Comment by isaacwalkercox** [comment]
OK so removing the PredictedLabel lines only works when I am not loading the model having saved it externally, I think it's due to the Schema of the training data but I don't know why that would be....

**Comment by wschin** [comment]
If your class fields are not named correctly, it's possible. Say, if your model's output are "Label" and "Probability", your class might look like
```c#
class PredictionResult
{
  public int Label;
  public float[] Probability;
}
```

**Comment by isaacwalkercox** [comment]
Thanks for your help but having done further research I think it's because
I am not giving it enough data lol 😅

Isaac

**Comment by wschin** [comment]
Sounds good. Let me close this issue. Please reopen it if I miss something.
