### ISSUE TITLE
AutoML TextLoader should Sweep TrimWhiteSpace

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning#3917]
We should iterate over the options for TrimWhitespace in the TextLoader.

As diagnosed by @daholste, the MSLR-WEB10K dataset ([train](https://aka.ms/mlnet-resources/benchmarks/MSLRWeb10KTrain720kRows.tsv), [validate](https://aka.ms/mlnet-resources/benchmarks/MSLRWeb10KValidate240kRows.tsv), [test](https://aka.ms/mlnet-resources/benchmarks/MSLRWeb10KTest240kRows.tsv), [zip](https://express-tlcresources.azureedge.net/datasets/MSLR-WEB10K/MSLR-WEB10K.zip), [README](https://express-tlcresources.azureedge.net/datasets/MSLR-WEB10K/README.md), [LICENSE](https://express-tlcresources.azureedge.net/datasets/MSLR-WEB10K/LICENSE.md)) has an extra tab at the end of each data row, though not the header row. 

This causes the AutoML TextLoader to fail w/ the following error: 
```
An Error occured during inferring columns
Unable to split the file provided into multiple, consistent columns.
Please see the log file for more info.
Exiting ...
```

Work:
* Have AutoML sweep over the [TrimWhitespace](https://github.com/dotnet/machinelearning/blob/429f8cc7764769fcf8c7f3668cc0a27619ec9531/src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs#L1449) option
* Fix above error message -- spelling of "occured"

**Comment by luisquintanilla** [comment]
Closing this issue since AutoML implementation has been updated and PR had been already merged to address the original issue.
