### ISSUE TITLE
Exception has been thrown by the target of an invocation on loading saved model

### ISSUE THREAD

**Issue by CyberFranck** [dotnet/machinelearning#3921]
When loading a saved model it throw the exception `Exception has been thrown by the target of an invocation` on the `Load` method. This method is simply wrapped into a separated library so it's easy to move around. Depending on the project i use it, it either works all the time with no exception, or never works. Here my current testing code :

   ```
public void TestLoadSolver(Stream solverStream)
{
    // create context
    var context = new MLContext();

    // temp schema
    DataViewSchema sch;

    try
    {
        // load context,schema and transformation
        var transformer = context.Model.Load(solverStream, out sch);

        // store schema
        var schema = sch;
    }
    catch (Exception ex)
    {

    }
}
```

The stream is simply a read from the zip file on the disk.
The error happen on the line `var transformer = context.Model.Load(solverStream, out sch);`
All projects are on .Net 4.8, 64 bits debug, using NuGet for packages which are the same as the DLL that has this code uses. The DLL are all the same in the bin folders and i verified for the bug with Lightgbm that doesn't copy and the DLL and EXE are there is all projects.

What could be the cause of failure but only in some project.

**Comment by CyberFranck** [comment]
We figured it out. The main starting project must have directly the ML.NET nuget packages added to work. The DLL themselves in the bin folder are not enough.

**Comment by nsulikowski** [comment]
I'm having the same issue...
