### ISSUE TITLE
Distinguish between Calibrated and NonCalibrated methods

### ISSUE THREAD

**Issue by natke** [dotnet/machinelearning#3927]
When would I use one versus the other?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b147624e-e01f-679a-900c-37f48f9d9e15
* Version Independent ID: 55d26134-c3a9-3a4f-5833-2f9b1dc8e0b1
* Content: [BinaryClassificationCatalog.CrossValidateNonCalibrated(IDataView, IEstimator&lt;ITransformer&gt;, Int32, String, String, Nullable&lt;Int32&gt;) Method (Microsoft.ML)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.binaryclassificationcatalog.crossvalidatenoncalibrated?view=ml-dotnet#feedback)
* Content Source: [dotnet/xml/Microsoft.ML/BinaryClassificationCatalog.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML/BinaryClassificationCatalog.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by wschin** [comment]
Calibrated means you want to see probabilities. Noncalibrated doesn't provide probability.

**Comment by natke** [comment]
Yep @wschin. Can we clarify that in the method documentation please

**Comment by wschin** [comment]
I guess we can add a new markdown file and include it in all calibrated/uncalibrated estimators?
