### ISSUE TITLE
Requisites of the data set used in recommendation task with matrixfactorization trainer?

### ISSUE THREAD

**Issue by Lelelo1** [dotnet/machinelearning#3934]
I have a question regarding the data used in recommendation task with matrixfactorization.
Here the data used in the examples consists of `userId` and `productId`.

Can I use recommendation task when the users in my data all have purchased 1 unique product each - so they are mapped `1 - 1`, `2 - 2`, `3 - 3` - (userId - productId)? Or do it have to be mapped differently - like in the examples where one user might have bought the same product as someone else? And one user have bought N products: `1 - 2`, `2 - 2` ,`3 - (3, 1, 4, 5, 1)` (user 1  bought product 2 which also user 2 bought. user 4 bought 5 products in total)?

Will I get unreliable and unusefull recommendation score with my original data setup?

**Comment by wschin** [comment]
In this case, matrix factorization will give you some unreliable results. Not only matrix factorization, deep learning, gradient boosting trees, and whatnot won't help too. You need to add, for example, user profile (age, country, etc) and item profile (e.g., short text description) to enrich your data set.

**Comment by wschin** [comment]
Looks like this issue is answered, please still feel free to reopen it if I miss something. Thanks.
