### ISSUE TITLE
ML.NET Features column 'Feature' not found 如何将预训数据模型 转化为 预测数据模型

### ISSUE THREAD

**Issue by jiaguoxinzhi** [dotnet/machinelearning#3935]
### System information

- **OS version/distro**:Win10
- **.NET Version (eg., dotnet --info)**: .net core 3.0 preview-6

### Issue

- **What did you do?**
https://social.msdn.microsoft.com/Forums/en-US/a9a45553-d26f-4964-9b84-81a6f1806754/mlnet-features-column-feature-not-found?forum=2212
- **What happened?**
https://social.msdn.microsoft.com/Forums/en-US/a9a45553-d26f-4964-9b84-81a6f1806754/mlnet-features-column-feature-not-found?forum=2212
- **What did you expect?**
ML.NET Features column 'Feature' not found 如何将预训数据模型 转化为 预测数据模型

怎么使用单独的数据准备和模型管道进行预测 On ML.NET, how to use eparate data preparation and model pipelines Predict(forcast)

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

class Program
    {

        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            HousingData[] housingData = new HousingData[]
            {
                new HousingData
                {
                    Size = 600f,
                    HistoricalPrices = new float[] { 100000f ,125000f ,122000f },
                    CurrentPrice = 170000f
                },
                new HousingData
                {
                    Size = 1000f,
                    HistoricalPrices = new float[] { 200000f, 250000f, 230000f },
                    CurrentPrice = 225000f
                },
                new HousingData
                {
                    Size = 1000f,
                    HistoricalPrices = new float[] { 126000f, 130000f, 200000f },
                    CurrentPrice = 195000f
                }
            };

            // Create MLContext
            MLContext mlContext = new MLContext();

            // Load Data
            IDataView data = mlContext.Data.LoadFromEnumerable<HousingData>(housingData);

            //使用单独的数据准备和模型管道
            {
                // Define data preparation estimator
                IEstimator<ITransformer> dataPrepEstimator =
                    mlContext.Transforms.Concatenate("Features", new string[] { "Size", "HistoricalPrices" })
                        .Append(mlContext.Transforms.NormalizeMinMax("Features"))
                        ;
                // Create data preparation transformer
                ITransformer dataPrepTransformer = dataPrepEstimator.Fit(data);
                // Pre-process data using data prep operations
                IDataView transformedData = dataPrepTransformer.Transform(data);
 
                // Define StochasticDualCoordinateAscent regression algorithm estimator
                var sdcaEstimator = mlContext.Regression.Trainers.Sdca();//labelColumnName: "Label", featureColumnName: "Features"

                //Console.WriteLine("正在训练");
                // Train regression model
                RegressionPredictionTransformer<LinearRegressionModelParameters> trainedModel = sdcaEstimator.Fit(transformedData);

                // Save Data Prep transformer
                mlContext.Model.Save(dataPrepTransformer, data.Schema, "data_preparation_pipeline.zip");

                // Save Trained Model
                mlContext.Model.Save(trainedModel, transformedData.Schema, "model11.zip");
                //Console.WriteLine("保存完成");

                // Define data preparation and trained model schemas
                DataViewSchema dataPrepPipelineSchema, modelSchema;

                // Load data preparation pipeline and trained model
                ITransformer dataPrepPipeline = mlContext.Model.Load("data_preparation_pipeline.zip", out dataPrepPipelineSchema);
                ITransformer predictionPipeline = mlContext.Model.Load("model11.zip", out modelSchema);

                // Create PredictionEngines
                PredictionEngine<HousingData, HousingPrediction> predictionEngine = mlContext.Model.CreatePredictionEngine<HousingData, HousingPrediction>(predictionPipeline);
                // Input Data
                HousingData inputData = new HousingData
                {
                    Size = 900f,
                    HistoricalPrices = new float[] { 155000f, 190000f, 220000f }
                };

                // Get Prediction
                HousingPrediction prediction = predictionEngine.Predict(inputData);
                Console.WriteLine($"Size={inputData.Size} and HistoricalPrices= {inputData.HistoricalPrices} Predict-> PredictedPrice={prediction.PredictedPrice}");
            }

            while (true)
            {
                Console.Write("按任意键退出！");
                Console.ReadKey();
                break;
            }
        }
    }

-error log:ML.NET Features column 'Feature' not found

**Comment by wschin** [comment]
Here
```c#
                PredictionEngine<HousingData, HousingPrediction> predictionEngine = mlContext.Model.CreatePredictionEngine<HousingData, HousingPrediction>(predictionPipeline);
```
you fed `HousingData` directly input the `predictionPipeline` which expects `transformedData`. However, `HousingData` is not `transformedData`, so you got that error.

**Comment by jiaguoxinzhi** [comment]
`    /// <summary>
    /// 预训数据模型
    /// </summary>    
    public class TransformedHousingData: HousingData
    {
        /// <summary>
        /// 特征列 根据 mlContext.Transforms.Concatenate 而定
        /// 参考 modelSchema 输出
        /// </summary>
        [VectorType(4)]
        public float[] Features { get; set; }
        //public float Label { get; set; }
    }

    class Program
    {


        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");


            HousingData[] housingData = new HousingData[]
            {
                new HousingData
                {
                    Size = 600f,
                    HistoricalPrices = new float[] { 100000f ,125000f ,122000f },
                    CurrentPrice = 170000f
                },
                new HousingData
                {
                    Size = 1000f,
                    HistoricalPrices = new float[] { 200000f, 250000f, 230000f },
                    CurrentPrice = 225000f
                },
                new HousingData
                {
                    Size = 1000f,
                    HistoricalPrices = new float[] { 126000f, 130000f, 200000f },
                    CurrentPrice = 195000f
                }
            };

            // Create MLContext
            MLContext mlContext = new MLContext();

            {

                //// Load Data
                //IDataView data = mlContext.Data.LoadFromEnumerable<HousingData>(housingData);

                //// Define data preparation estimator
                //EstimatorChain<RegressionPredictionTransformer<LinearRegressionModelParameters>> pipelineEstimator =
                //    mlContext.Transforms.Concatenate("Features", new string[] { "Size", "HistoricalPrices" })
                //        .Append(mlContext.Transforms.NormalizeMinMax("Features"))
                //        .Append(mlContext.Regression.Trainers.Sdca());

                //// Train model
                //ITransformer trainedModel = pipelineEstimator.Fit(data);

                //// Save model
                //mlContext.Model.Save(trainedModel, data.Schema, "model10.zip");
                //Console.WriteLine("直用数据 保存完成");

                //
                DataViewSchema predictionPipelineSchema;
                ITransformer predictionPipeline = mlContext.Model.Load("model10.zip", out predictionPipelineSchema);

                // Create PredictionEngines
                PredictionEngine<HousingData, HousingPrediction> predictionEngine = mlContext.Model.CreatePredictionEngine<HousingData, HousingPrediction>(predictionPipeline);
                // Input Data
                HousingData inputData = new HousingData
                {
                    Size = 900f,
                    HistoricalPrices = new float[] { 155000f, 190000f, 220000f }
                };

                // Get Prediction
                HousingPrediction prediction = predictionEngine.Predict(inputData);
                Console.WriteLine($"Size={inputData.Size} and HistoricalPrices= {inputData.HistoricalPrices} Predict-> PredictedPrice={prediction.PredictedPrice}");
            }

            //使用单独的数据准备和模型管道
            {

                //// Load Data
                //IDataView data = mlContext.Data.LoadFromEnumerable<HousingData>(housingData);

                //// Define data preparation estimator
                //IEstimator<ITransformer> dataPrepEstimator =
                //    mlContext.Transforms.Concatenate("Features", new string[] { "Size", "HistoricalPrices" })
                //        .Append(mlContext.Transforms.NormalizeMinMax("Features"))
                //        ;
                //// Create data preparation transformer
                //ITransformer dataPrepTransformer = dataPrepEstimator.Fit(data);
                //Console.WriteLine("数据准备 填充完成");
                //// Pre-process data using data prep operations
                //IDataView transformedData = dataPrepTransformer.Transform(data);
                ////Console.WriteLine($"数据数据： {Newtonsoft.Json.JsonConvert.SerializeObject(transformedData)}");

                //// Define StochasticDualCoordinateAscent regression algorithm estimator
                //var sdcaEstimator = mlContext.Regression.Trainers.Sdca();//labelColumnName: "Label", featureColumnName: "Features"
                ////var sdcaEstimator = mlContext.Regression.Trainers.Sdca(labelColumnName: "Label", featureColumnName: "Features");

                //Console.WriteLine("正在训练");
                //// Train regression model
                //RegressionPredictionTransformer<LinearRegressionModelParameters> trainedModel = sdcaEstimator.Fit(transformedData);
                //Console.WriteLine("训练完成");

                //// Save Data Prep transformer
                //mlContext.Model.Save(dataPrepTransformer, data.Schema, "data_preparation_pipeline.zip");

                //// Save Trained Model
                //mlContext.Model.Save(trainedModel, transformedData.Schema, "model11.zip");
                //Console.WriteLine("预训数据 保存完成");

                // Define data preparation and trained model schemas
                DataViewSchema dataPrepPipelineSchema=null, modelSchema=null;
                // Load data preparation pipeline and trained model
                ITransformer dataPrepPipeline = mlContext.Model.Load("data_preparation_pipeline.zip", out dataPrepPipelineSchema);
                var jsetting = new Newtonsoft.Json.JsonSerializerSettings();
                jsetting.TypeNameHandling = Newtonsoft.Json.TypeNameHandling.None;
                Console.WriteLine($"数据管道结构：{Newtonsoft.Json.JsonConvert.SerializeObject(modelSchema)}");
                ITransformer trainedPrepModel = mlContext.Model.Load("model11.zip", out modelSchema);
                Console.WriteLine($"预训模型结构：{Newtonsoft.Json.JsonConvert.SerializeObject(modelSchema.Select(p =>$"{p.Name} IsHidden={p.IsHidden} {p.Type}"))}");

                // Create PredictionEngines
                //PredictionEngine<HousingData, HousingPrediction> dataPredictionEngine = mlContext.Model.CreatePredictionEngine<HousingData, HousingPrediction>(dataPrepPipeline);
                //// Input Data
                //HousingData inputData = new HousingData
                //{
                //    Size = 900f,
                //    HistoricalPrices = new float[] { 155000f, 190000f, 220000f }
                //};

                //// Get Prediction
                //HousingPrediction dataPrediction = dataPredictionEngine.Predict(inputData);
                //Console.WriteLine($"Size={inputData.Size} and HistoricalPrices= {inputData.HistoricalPrices} Predict-> PredictedPrice={dataPrediction.PredictedPrice}");

                PredictionEngine<TransformedHousingData, HousingPrediction> predictionEngine = mlContext.Model.CreatePredictionEngine<TransformedHousingData, HousingPrediction>(trainedPrepModel);
                // Get Prediction
                HousingPrediction prediction = predictionEngine.Predict(new TransformedHousingData() {  Features= new float[] { 900f,155000f, 190000f, 220000f } });
                Console.WriteLine($"Size=900f and HistoricalPrices=155000f, 190000f, 220000f Predict-> PredictedPrice={prediction.PredictedPrice}");
            }

            while (true)
            {
                Console.Write("按任意键退出！");
                Console.ReadKey();
                break;
            }
        }
    }
`
是的，，这样处理后，，可以正确执行了。。但它的预测结果变得很奇怪，，是否哪里理解错了，，没有写对？

Yes, so that after processing, and can be executed correctly. But its predicted results, a strange,, where is wrong, and didn't write to?

**Comment by jiaguoxinzhi** [comment]
`                DataViewSchema dataPrepPipelineSchema =null, modelSchema=null;
                // Load data preparation pipeline and trained model
                ITransformer dataPrepPipeline = mlContext.Model.Load("data_preparation_pipeline.zip", out dataPrepPipelineSchema);
                //Console.WriteLine($"数据管道结构：{Newtonsoft.Json.JsonConvert.SerializeObject(dataPrepPipelineSchema.Select(p => $"{p.Name} IsHidden={p.IsHidden} {p.Type}"))}");
                ITransformer trainedPrepModel = mlContext.Model.Load("model11.zip", out modelSchema);
                //Console.WriteLine($"预训模型结构：{Newtonsoft.Json.JsonConvert.SerializeObject(modelSchema.Select(p =>$"{p.Name} IsHidden={p.IsHidden} {p.Type}"))}");

                //Create PredictionEngines
                PredictionEngine<TransformedHousingData, HousingPrediction> predictionEngine = mlContext.Model.CreatePredictionEngine<TransformedHousingData, HousingPrediction>(trainedPrepModel);
                HousingData inputData = new HousingData
                {
                    Size = 900f,
                    HistoricalPrices = new float[] { 155000f, 190000f, 220000f }
                };

                HousingData[] inputDatas= new HousingData[] { inputData };
                IDataView idata = mlContext.Data.LoadFromEnumerable<HousingData>(inputDatas);
                // Define data preparation estimator
                IEstimator<ITransformer> dataPrepEstimator =
                    mlContext.Transforms.Concatenate("Features", new string[] { "Size", "HistoricalPrices" })
                        .Append(mlContext.Transforms.NormalizeMinMax("Features"))
                        ;
                // Create data preparation transformer
                ITransformer dataPrepTransformer = dataPrepPipeline;
                IDataView transformedData = dataPrepTransformer.Transform(idata);
                var trans = mlContext.Data.CreateEnumerable<TransformedHousingData>(transformedData, true);

                Console.WriteLine($"数据视图： {Newtonsoft.Json.JsonConvert.SerializeObject(trans)}");
                var lastinput = trans.FirstOrDefault();

                // Get Prediction
                HousingPrediction prediction = predictionEngine.Predict(lastinput);
                Console.WriteLine($"{Newtonsoft.Json.JsonConvert.SerializeObject(lastinput)} Predict-> PredictedPrice={prediction.PredictedPrice}");
`

可以了，，我已经找到了正确的姿势。。
谢谢！！

Ok,, I have found the right position.
Thank you very much!!
