### ISSUE TITLE
EvaluatorUtils should handle key label columns with non-text key values

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#395]
When CV needs to concatenate the per-instance data views, it needs to reconcile the key values from the different folds, even if the key values are not text.

**Comment by TomFinley** [comment]
Hi @yaeldekel , when does this issue occur? In particular it may not be clear what the key-values from the different folds actually are. Labels, or something else? Is there a repro?

**Comment by yaeldekel** [comment]
When the different folds contain different sets of labels, and the label column is of type key, in order to concatenate the per-instance data views we need to create a new key type that includes the union of the key values. This is currently only done correctly when the key values are of type text, but it should be done for other types of the KeyValues metadata as well.
