### ISSUE TITLE
Remove Static API code

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#3952]
Since we are closing Static API issues with "no development is being done on static API" (ex. https://github.com/dotnet/machinelearning/issues/1153#issuecomment-507014868), we should just remove the Static API code from the repo. If we need it again in the future, we can get it out of source control history. But there is no reason to build and maintain this code anymore.

**Comment by rauhs** [comment]
I read those comments a few days ago and I had no clue it was discontinued. FWIW, we actually shipped this API. When was this decision done?

It would've been nice if Microsoft had communicated this to us developers as soon as it made this decision. Just a quick "Announcement" issue here on GitHub would've been enough.

**Comment by codemzs** [comment]
We just did. Static API was always under preview. Thank you for your interest.

**Comment by artidoro** [comment]
I plan to do the following:

1. Internalize the Static API
2. Migrate the tests that use the Static API to use the dynamic API
3. Remove the Static API code from the code base

Thanks for the feedback @rauhs we will include this in the next ML.NET blog post and release notes to make sure it is communicated to the community.

**Comment by wschin** [comment]
@rauhs, this is very unfortunate and I personally like static APIs as well. However, we really don't have enough resource to maintain two sets of APIs and most people tend to user dynamic ones. We really appreciate your feedback. To prevernt it from happening again, all `preview` things should be marked with `obsolete` attribute to explicitly conduct a warning.

**Comment by codemzs** [comment]
@rauhs The fact that API is preview is enough of a warning that it could change, or be removed, at any time. This is not a question of resource but principle, we need a good reason to maintain two sets of API doing the same thing. The feedback we got from customers was that static API was too complicated and we stopped development based on the very low demand. Hope this helps.
