### ISSUE TITLE
Temp path created for model loading is too long

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#396]
In some environments access to the file system is restricted, so when we deserialize a model file first extract the entries in the zip repository to temporary files. The path for the temporary file contains the system's temporary folder name, followed by "TLC_" and a guid. Sometimes this creates a path that is too long because Windows doesn't allow paths that are over 260 characters.

**Comment by TomFinley** [comment]
Hi @yaeldekel ! Is more comprehensive description possible? What is the problem with the current situation? What problem is occurring as a result of it? These would help also with determining whether the current proposed fix is appropriate, or perhaps whether some other fix would be appropriate.

**Comment by Ivanidzo4ka** [comment]
This is for .net framework 4.6.2 but....
https://blogs.msdn.microsoft.com/dotnet/2016/08/02/announcing-net-framework-4-6-2/#bcl

Long Path Support (MAXPATH)
We fixed the 260 character (MAXPATH) file name length limitation in the System.IO APIs. Over 4500 of you voted for this issue on UserVoice!

I actually wonder is it even a case for .net standard...
