### ISSUE TITLE
Version mismatch for Microsoft.ML.TensorFlow.Redist

### ISSUE THREAD

**Issue by Oceania2018** [dotnet/machinelearning#3962]
The NuGet shows v0.14.0. But when I download and install, it actually v0.13.1.

![image](https://user-images.githubusercontent.com/1705364/60590780-811c9280-9d62-11e9-9ef9-4930a047b281.png)

https://github.com/dotnet/machinelearning/tree/master/src/Redist/Microsoft.ML.TensorFlow.Redist.

![image](https://user-images.githubusercontent.com/1705364/60590824-9ee9f780-9d62-11e9-8a7a-8f8cbdafac45.png)

**Comment by codemzs** [comment]
@Oceania2018 do you mean the TF version is 1.13.1? That is expected because the TF version upgrade to 1.14 is still in PR. @harishsk is working on it.

**Comment by Oceania2018** [comment]
Yes, but why the NuGet package Microsoft.ML.TensorFlow.Redist is released?

**Comment by codemzs** [comment]
Because we release all our packages everyone month. You make a good point that there is no need to release a package if nothing has changed but as we do a release we increment our releases and preview versions. 

CC:  @eerhardt

**Comment by harishsk** [comment]
@Oceania2018 The change is still in PR. It will make the next release. I am now beginning to look at how to move this to TensorFlow.NET. 

With respect to this release, I agree we should not be releasing or updating versions if nothing has changed. @codemzs Do we already have the flexibility to release only selected packages?

**Comment by codemzs** [comment]
@Oceania2018 @harishsk We always release all the packages because with every release we increment release and preview version numbers. Why we release packages even though nothing might be changed, may be, @eerhardt can answer but yes we have the option to release selected packages if we knew what what packages actually were changed from the commit history in that month.

**Comment by eerhardt** [comment]
#2311 falls into the same category.

**Comment by Oceania2018** [comment]
Resolved by lastest commit. Thanks.

**Comment by codemzs** [comment]
@Oceania2018 I couldn’t upload this to nuget.org because the package size is greater than 250MB. Will update once I figure out what to do.
