### ISSUE TITLE
LightGbm Warning after upgrading to LightGBM v1.2 ([LightGBM] [Warning] Unknown parameter metric=)

### ISSUE THREAD

**Issue by bartczernicki** [dotnet/machinelearning#3965]
### System information

- **OS version/distro**: Windows Server 2016
- **.NET Version (eg., dotnet --info)**: .NET Core 2.1

### Issue

- **What did you do?** Updated to ML.NET/LightGBM v1.2
- **What happened?** Warning started appearing.
- **What did you expect?** No warning

### Source code / logs

Source code is located here:
https://github.com/bartczernicki/MLDotNet-BaseballClassification

Fit method that throws the warning...
https://github.com/bartczernicki/MLDotNet-BaseballClassification/blob/28143bb71d962bcb919393db258e7e458480f071/MLDotNet-BaseballClassification/Program.cs#L113

_Error: [LightGBM] [Warning] Unknown parameter metric=_

**Comment by codemzs** [comment]
@najeeb-kazmi this seems related to your metric change. Can you please take a look?
