### ISSUE TITLE
Converting from ml.net pipeline to ONNX fails.

### ISSUE THREAD

**Issue by pieths** [dotnet/machinelearning#3973]
### System information

- **OS version/distro**: Windows 10

### Issue

I created an ml.net pipeline using onnx exportable transforms and a logistic regression node. It trains and predicts as expected but exporting the pipeline using `ConvertToOnnxProtobuf` fails with the following error:

```console
System.InvalidOperationException : The targeted pipeline can not be fully converted into
a well-defined ONNX model. Please check if all steps in that pipeline are convertible
to ONNX and all necessary variables are not dropped (via command line arguments).
```

### Source code / logs

See [here](https://github.com/pieths/dotnet_machinelearning/commit/5335349756c50e54b8cb221484f6c56fd9805d49) for an ml.net test which demonstrates the issue.

**Comment by wschin** [comment]
It fails for multiple reasons.

	1. ValueToKeyMapping should support float, int, and string keys.    
            private bool SaveAsOnnxCore(OnnxContext ctx, int iinfo, ColInfo info, string srcVariableName, string dstVariableName)
            {
                if (!(info.TypeSrc.GetItemType() is TextDataViewType))
                    return false;

                var terms = default(VBuffer<ReadOnlyMemory<char>>);
                TermMap<ReadOnlyMemory<char>> map = (TermMap<ReadOnlyMemory<char>>)_termMap[iinfo].Map;
                map.GetTerms(ref terms);
                string opType = "LabelEncoder";
                var node = ctx.CreateNode(opType, srcVariableName, dstVariableName, ctx.GetNodeName(opType));
                node.AddAttribute("classes_strings", terms.DenseValues());
                node.AddAttribute("default_int64", -1);
                //default_string needs to be an empty string but there is a BUG in Lotus that
                //throws a validation error when default_string is empty. As a work around, set
                //default_string to a space.
                node.AddAttribute("default_string", " ");
                return true;
            }
_mapper = {Microsoft.ML.Transforms.TypeConvertingTransformer.Mapper} doesn't implement "ISaveAsOnnx".

**Comment by pieths** [comment]
`KeyToValueMappingTransformer` does not support saving to ONNX as well. This transformer is added by `FeatureCombiner` and is preventing the other transforms after it in the chain from getting converted to ONNX.

The test example which was used to uncover this issue used `LogisticRegressionBinaryClassifier`  from NimbusML.

**Comment by Lynx1820** [comment]
After the recent onnx support work, this issue has been fixed.
