### ISSUE TITLE
SaveOnnxCommand appears to ignore predictors when saving a model to ONNX format.

### ISSUE THREAD

**Issue by pieths** [dotnet/machinelearning#3974]
### System information

- **OS version/distro**: Windows 10

### Steps To Recreate The Issue

1. Create and save a PredictorModel to disk using the entry point api.
2. Try and convert the model to ONNX format using the entry point api.
3. Notice that `SaveOnnxCommand.GetPipe` only cycles through the transforms and never encounters the logistic regression node.

    This might be happening because `ExecuteGraphCommand.GetOutputToPath` saves a `TlcModule.DataKind.PredictorModel` to disk in step (1). And then, `ExecuteGraphCommand.SetInputFromPath` loads a `TlcModule.DataKind.TransformModel` from disk in step (2) (apparently a consequence of `SaveOnnxCommand.Arguments.Model` being of type `TransformModel`). `PredictorModelImpl` and `TransformModelImpl` don't appear to be compatible from a serialization point of view.

### Source code / logs

See [here](https://github.com/pieths/dotnet_machinelearning/commit/1058abc7086d58a76000717b284a5b115931c70e) for an ml.net test which demonstrates the issue.

**Comment by wschin** [comment]
Thanks a lot for pointing this out. I just made a solution based on your finding.
