### ISSUE TITLE
Need More Detail regarding feature

### ISSUE THREAD

**Issue by nighotatul** [dotnet/machinelearning#3982]
is feature columns consider as complex variable that means all are consider as object when processes in ml.net?

ex.
if consider label is Purchased Bike
and feature are Commute Distance,Gender,Age,Cars.

so all feature columns consider as object in ml.net?

means like all column data convert into vector array.

**Comment by Oceania2018** [comment]
@nighotatul It's not object, the feed data should be typed.

Define data model:
```csharp
public class SentimentData
{
    [LoadColumn(0)]
    public string SentimentText;

    [LoadColumn(1), ColumnName("Label")]
    public bool Sentiment;
}
```

Load data:
```csharp
MLContext mlContext = new MLContext();
IDataView dataView = mlContext.Data.LoadFromTextFile<SentimentData>(_dataPath, hasHeader: false);
```

**Comment by yaeldekel** [comment]
@nighotatul ,
an `IDataView` is composed of columns, each one strongly typed with one of the types supported by ML.NET (integers, singles, doubles, strings, etc.). As @Oceania2018  mentioned, you can use a class to create the schema of an `IDataView`, and an enumerable of objects of that type to create an `IDataView`.

**Comment by yaeldekel** [comment]
Closing this issue for now, please feel free to open more issues if you have additional questions.
