### ISSUE TITLE
FeaturizeText should allow only outputColumnName to be defined

### ISSUE THREAD

**Issue by artidoro** [dotnet/machinelearning#3992]
One of the extension methods for `FeaturizeText` needs both the `outputColumnName` and the `inputColumnNames` to be provided.

There is no compile error if `inputColumnNames` is not provided, only a runtime error.

We should fix the error so that when `inputColumnNames` is not provided, it is set to `new[] { outputColumnName }` as we do everywhere else in the code base.

https://github.com/dotnet/machinelearning/blob/c3bdaaa2a29f88a85dd91cde3fbb805001011903/src/Microsoft.ML.Transforms/Text/TextCatalog.cs#L60-L65

**Comment by SnakyBeaky** [comment]
The only similar case I've seen, is when `inputColumnName` is a single `string` and not a `string[]`. In those cases, the null-coalescing operator is used.

For example, in [Microsoft.ML.Transforms/Text/TokenizingByCharacters.cs#L595](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Transforms/Text/TokenizingByCharacters.cs#L595) :

```csharp
new[] { (outputColumnName, inputColumnName ?? outputColumnName)
```

But I have not seen this done when the input column names is an array and not a single string.
