### ISSUE TITLE
Possibility to specify the algorithm in AutoML

### ISSUE THREAD

**Issue by Suriman** [dotnet/machinelearning#3999]
There are scenarios where you know in advance the algorithms that will work better under certain data. In these cases, it would be very useful to specify through parameters what algorithms we want to test AutoML with different configuration parameters, so the time spent would be used to find better configurations of the specified algorithms, instead of trying algorithms that are known in advance to be to give worse results.

**Comment by jakobt** [comment]
On ExperimentSettings you can remove the algorithms you don't want to experiment with from the Trainers collection, for instance for MultiClassExperimentSettings:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.automl.multiclassexperimentsettings.trainers?view=automl-dotnet

**Comment by Suriman** [comment]
From what I understand, what you propose is to use the ML.NET API, but is it possible to select the algorithm using the ML.NET CLI command: mlnet auto-train ...?

**Comment by jakobt** [comment]
Sorry, i didn't understand from your question that you were referring to doint auto-traing using the CLI  auto-train command, to my knowledge it is not possible to exclude algorithms using the cli.

**Comment by Suriman** [comment]
Don't worry. Would it be possible to use this issue as a request to improve the CLI? If not, I could close this issue and create a more specific and clear one.

**Comment by jakobt** [comment]
I'm not involved in the project so if you want it as a feature request i guess you should just leave this open, but might i suggest that you meanwhile add it yourself, the steps would be pretty simple, these 3 steps:

1. Add a list of excluded trainers to the input
https://github.com/dotnet/machinelearning/blob/features/automl/src/mlnet/Commands/New/NewCommandSettings.cs

2. And make sure its initialized and defined in:
https://github.com/dotnet/machinelearning/blob/features/automl/src/mlnet/Commands/CommandDefinitions.cs

3. Use the new flag (available in _settings) to exclude the trainers when initializing the experiment:
https://github.com/dotnet/machinelearning/blob/features/automl/src/mlnet/AutoML/AutoMLEngine.cs#L50
https://github.com/dotnet/machinelearning/blob/features/automl/src/mlnet/AutoML/AutoMLEngine.cs#L63
https://github.com/dotnet/machinelearning/blob/features/automl/src/mlnet/AutoML/AutoMLEngine.cs#L77

**Comment by Suriman** [comment]
Thank you very much for the information. We will leave this issue open in case the corresponding team considers incorporating it in a future version of the product.

**Comment by Suriman** [comment]
Thank you very much for the information. We will leave this petition open in case the corresponding team considers incorporating it in a future version of the product.

**Comment by Suriman** [comment]
Any news about this?

**Comment by mentorfloat** [comment]
> On ExperimentSettings you can remove the algorithms you don't want to experiment with from the Trainers collection, for instance for MultiClassExperimentSettings:
> 
> https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.automl.multiclassexperimentsettings.trainers?view=automl-dotnet

@jakobt is it normal that `set;` is missing? I can't set my List<> of algorithms.

https://github.com/dotnet/machinelearning/blob/5dbfd8acac0bf798957eea122f1413209cdf07dc/src/Microsoft.ML.AutoML/API/MulticlassClassificationExperiment.cs#L32

**Comment by luisquintanilla** [comment]
Thanks all for the discussion and feedback. We've recently updated our implementation of AutoML based on FLAML, which supports the requirements listed here.

For more information, see the [blog post](https://devblogs.microsoft.com/dotnet/whats-new-with-mldotnet-automl/#automl-updates) and [sample notebooks](https://github.com/dotnet/csharp-notebooks/blob/main/machine-learning/03-Training%20and%20AutoML.ipynb)

Closing this issue.
