### ISSUE TITLE
Move Samples/UCI and ZBaseline Folders to Test/Data Folder

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/machinelearning#4]
These folders should not be in the root of the repo.

**Comment by Niladri24dutta** [comment]
I can take up this task, should I create a PR for this?

**Comment by shauheen** [comment]
Thanks @Niladri24dutta, that would be great. Please also take a look at the discussion in #100 where the Baseline folder was discussed by @TomFinley and others, and let us know if you have any questions. I think we would want to move ZBaseline to /test/BaselineOutput. @KrzysztofCwalina any objections?

**Comment by KrzysztofCwalina** [comment]
No objections

**Comment by rantri** [comment]
Hi,
Can I take this issue?
I already moved the files in "ZBaselines" to "test/BaselineOutput".
Should I move the files in "Samples/UCI" to "test/data" or "test/data/UCI" or "test/data/Samples/UCI"?

**Comment by shauheen** [comment]
Hi @rantri, that would be great. I think it should be moved to "test/data" for now.
