### ISSUE TITLE
Create from enumerable after registering new type

### ISSUE THREAD

**Issue by baruchiro** [dotnet/machinelearning#4003]
I think I'm missing something.

We have the Type System in `DataViewTypeManager`, and we can register a new type to map it to one of the system types. But even I register a new type to the system, when I try to load from enumerable I getting exception because the next `if`:

https://github.com/dotnet/machinelearning/blob/02a857a7646188fec2d1cba5e187a6c9d0838e23/src/Microsoft.ML.Data/DataView/InternalSchemaDefinition.cs#L194-L195

Even if I add a new type, the first condition `!itemType.TryGetDataKind(out _)` will return `!false` = `true` because my type will never be in the next code:

https://github.com/dotnet/machinelearning/blob/c3bdaaa2a29f88a85dd91cde3fbb805001011903/src/Microsoft.ML.Core/Data/DataKind.cs#L293-L337

**Comment by najeeb-kazmi** [comment]
@baruchiro these classes are not exposed in the API. You have to register a custom type with the `DataViewTypeManager` as in this example:
https://github.com/dotnet/machinelearning/blob/7db00a18a222ab5bc1de7d7e65ce4588e4aab211/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/CustomMappingWithInMemoryCustomType.cs#L84-L88
