### ISSUE TITLE
Add an expression transformer

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#4015]
The expression transformer takes the expression in the form of text using syntax of a simple expression language, and performs the operation defined in the expression on the input columns in each row of the data. The transformer supports having a vector input column, in which case it applies the expression to each slot of the vector independently. The expression language is extendable to user defined operations.

**Comment by justinormont** [comment]
I certainly would appreciate this addition. Mainly for its simplicity.
