### ISSUE TITLE
Setting Threshold for Predict

### ISSUE THREAD

**Issue by korzh** [dotnet/machinelearning#403]
Suppose we have some binary classification task and train the model using any of binary classifier available (LogisticRegressionBinaryClassifier or FastTreeBinaryClassifier or anything else).

Then we evaluate our model on a testing set  using BinaryClassificationEvaluator. During this evaluation we can set a threshold using `Threshold` property of the evaluator. 

The question is: how can we set the threshold for prediction?

**Comment by Ivanidzo4ka** [comment]
+ @Zruty0  I can't find way to do that in new API as well, is it supported?

**Comment by Zruty0** [comment]
This is the closest: https://github.com/dotnet/machinelearning/blob/a285f8d5db15cd8bf77f3c03763bce16642f902b/test/Microsoft.ML.Tests/Scenarios/Api/Estimators/ReconfigurablePrediction.cs#L41

**Comment by Ivanidzo4ka** [comment]
Marking as up-for-grabs and good first issue, in case someone want to update cook book examples.
