### ISSUE TITLE
Add a Local Deep Kernel Learning trainer

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#4031]
http://manikvarma.org/pubs/jose13.pdf

**Comment by justinormont** [comment]
Great idea! I have seen LDSVM perform well on text (ngram based featurization).

Background:
LDSVM uses trees as its SVM kernel to create a non-linear binary learner which is fast at prediction time. 

Slides:
http://manikvarma.org/talks/ICML13.pdf

**Comment by codemzs** [comment]
Please do not start working on this until this is triaged.
