### ISSUE TITLE
Onnx Support for String Tensors?

### ISSUE THREAD

**Issue by hobbsa** [dotnet/machinelearning#4034]
### System information

Windows 10 - 
.NET Core 2 - ML.NET 1.2

### Issue

Is there any timeline for allowing string tensors to be used in Onnx models within ML.NET?  Tried both InferenceSession and pipeline ApplyOnnxModel and keep hitting in the 

public static NamedOnnxValue CreateNamedOnnxValue<T>(string name, ReadOnlySpan<T> data, OnnxShape shape)
        {
            if (!_onnxTypeMap.Contains(typeof(T)))
                throw new NotImplementedException($"Not implemented type {typeof(T)}");
            return NamedOnnxValue.CreateFromTensor<T>(name, new DenseTensor<T>(data.ToArray(), shape.Select(x => (int)x).ToArray()));
        }

Because onnxTypeMap does not support string.

My OnnxModel takes input of string and output of long+float.

**Comment by Lynx1820** [comment]
Hi @hobbsa, 

This issue was resolved with this [PR](https://github.com/dotnet/machinelearning/pull/4416).
