### ISSUE TITLE
Need to explicitly call out that the IEnumerable needs to be thread-safe

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#4036]
See the conversation starting at https://github.com/dotnet/machinelearning/issues/2159#issuecomment-513271843 and continuing from there.

ML.NET supports multiple threads reading from the same IDataView instance. For example, when using an SDCA trainer, by default it will train on multiple threads on a machine with more than 2 processors. When using `LoadFromEnumerable` on an IEnumerable that doesn't support multiple threads (like in the issue - using an EF query), ML.NET will still try to access the IDataView from multiple threads, and the underlying IEnumerable can throw, or have some other undefined behavior.

We should explicitly call this limitation out in the docs, and inform users of this method that the IEnumerable being returned needs to be thread-safe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10e8d5aa-2038-a382-ec86-cf8ad031f996
* Version Independent ID: 81198dc9-ddf4-cef1-c178-82f50f0e7a46
* Content: [DataOperationsCatalog.LoadFromEnumerable Method (Microsoft.ML)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.dataoperationscatalog.loadfromenumerable?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML/DataOperationsCatalog.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML/DataOperationsCatalog.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by CESARDELATORRE** [comment]
@eerhardt - Agree on that. I'll talk to the docs team and we'll also update  the README.MD for the sample highlighting this issue.

However, I think that documenting it and pointing to a sample is just a short term workaround.

The fact that ML.NET makes the assumption that IEnumerable<T> instances are thread safe feels completely like a bug. The way to fix a bug is by fixing the API implementation not making possible that users will get into trouble. Documenting a workaround for a bug is only a short term workaround.

See my additional details in the other original issue: https://github.com/dotnet/machinelearning/issues/2159#issuecomment-515126667

**Comment by frank-dong-ms** [comment]
documentation work is done at below PR, close this issue:

https://github.com/dotnet/docs/pull/13663
