### ISSUE TITLE
Common issue Only supported feature column types are Boolean, Single, and String. 

### ISSUE THREAD

**Issue by acrigney** [dotnet/machinelearning#4045]
### System information

- **OS version Windows 10 /distro**:
- **.NET Version (.NET Core 2.1)**: 

### Issue
I have removed the unsupported column types in my data but I am still getting this message

Message: System.ArgumentException : Only supported feature column types are Boolean, Single, and String. Please change the feature column IntMonth of type Int32 to one of the supported types.
Parameter name: trainData
The problem is that the conversions and drop columns are not converting and dropping the columns as they are not operating on the correct object.
How can I get the int32 and double columns removed?
How can I do this please?
Here is some example code that 
### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

private void TransformData()
        {
            var dataProcessPipeline = _mlContext.Transforms.DropColumns(_modelInput.KeyFeatureToIgnore);
            PropertyInfo propertyInfo;

            foreach (string feature in _includedFeatureNames)
            {
                propertyInfo = _allFeaturesPropertyInfo.Find(x => x.Name == feature);
                if (typeof(Double) == propertyInfo.PropertyType)
                {
                    dataProcessPipeline.Append(_mlContext.Transforms.Conversion.ConvertType(feature, feature, DataKind.Single));
                }
else if (typeof(Int32) == propertyInfo.PropertyType)
                {
                    dataProcessPipeline.Append(_mlContext.Transforms.Conversion.ConvertType(feature, feature, DataKind.Single));
                }
                dataProcessPipeline.Append(_mlContext.Transforms.NormalizeMeanVariance(feature, useCdf: false));
            }

            // Now we can transform the data and look at the output to confirm the
            // behavior of the estimator. This operation doesn't actually evaluate
            // data until we read the data below.
            var tansformer = dataProcessPipeline.Fit(_trainDataView);

            _trainDataView = tansformer.Transform(_trainDataView);

            var trainDataViewSchemaTest = _trainDataView.Schema;
            
            
        }

**Comment by acrigney** [comment]
As adding a normalization adds a new column I tried this code to remove the extra column but it still does not actually remove the extra column at the end.
Please can you fix this! As commented in other issues adding normalization, one hot encoding etc adds new columns that should not be added.

private void TransformData()
        {
            EstimatorChain<NormalizingTransformer> estimatorChain = new EstimatorChain<NormalizingTransformer>();
            EstimatorChain<ColumnSelectingTransformer> columnSelectingChain = new EstimatorChain<ColumnSelectingTransformer>();
            EstimatorChain<ColumnCopyingTransformer> copyColumnChain = new EstimatorChain<ColumnCopyingTransformer>();

            PropertyInfo propertyInfo;

            foreach (string feature in _includedFeatureNames.Where(x => x != _modelInput.KeyFeatureToIgnore))
            {
                propertyInfo = _allFeaturesPropertyInfo.Find(x => x.Name == feature);
                estimatorChain = estimatorChain.Append(_mlContext.Transforms.NormalizeMeanVariance("X" + feature, feature, useCdf: false));              
                columnSelectingChain = columnSelectingChain.Append(_mlContext.Transforms.DropColumns(feature));
                copyColumnChain = copyColumnChain.Append(_mlContext.Transforms.CopyColumns(feature, "X" + feature));
            }

            columnSelectingChain = columnSelectingChain
                .Append(_mlContext.Transforms.DropColumns(_modelInput.KeyFeatureToIgnore))
                .AppendCacheCheckpoint(_mlContext);

            // Now we can transform the data and look at the output to confirm the
            // behavior of the estimator. This operation doesn't actually evaluate
            // data until we read the data below.

            _tansformer = estimatorChain.Fit(_trainDataView);
           
            _trainDataView = _tansformer.Transform(_trainDataView);


            _tansformer = columnSelectingChain.Fit(_trainDataView);

            _trainDataView = _tansformer.Transform(_trainDataView);

            _tansformer = copyColumnChain.Fit(_trainDataView);

            _trainDataView = _tansformer.Transform(_trainDataView);

        }

**Comment by yaeldekel** [comment]
@acrigney ,
I am not sure whether this solves the problem, but in the top code snippet, you have:
```
dataProcessPipeline.Append(_mlContext.Transforms.Conversion.ConvertType(feature, feature, DataKind.Single));
```
It should instead be 
```
dataProcessPipeline = dataProcessPipeline.Append(_mlContext.Transforms.Conversion.ConvertType(feature, feature, DataKind.Single));
```

**Comment by frank-dong-ms** [comment]
@acrigney does yael's suggestion work for you? 
Close this now as we don't hear back for a while, feel free to reopen the issue if you have further questions, thanks.

**Comment by acrigney** [comment]
Kool mate I will try when I get a chance but my whole ML stack is built now, I have abstracted the ML.NET into a framework that anyone can use without any real knowledge of ML
