### ISSUE TITLE
System.ArgumentOutOfRangeException : Could not find input column 'SamplingKeyColumn'

### ISSUE THREAD

**Issue by acrigney** [dotnet/machinelearning#4048]
### System information

- **Win10/distro**:
- **.NET Version Core 2.1**: 

### Issue

When I am running my RefitBestPipeline function. i.e my function to run my model over the entire data I got this error.

Message: System.ArgumentOutOfRangeException : Could not find input column 'SamplingKeyColumn'
Parameter name: inputSchema

This is some internal error I am calling the same load and transfer function that I used to build my model.

### Source code / logs
private ITransformer RefitBestPipeline(ExperimentResult<RegressionMetrics> experimentResult)
        {
            DebugHelper.WriteHeader("=============== Re-fitting best pipeline ===============");
            //var textLoader = mlContext.Data.CreateTextLoader(columnInference.TextLoaderOptions);
            //_trainDataView = _mlContext.Data.LoadFromEnumerable<T>(trainingCollection);
            //_testDataView = _mlContext.Data.LoadFromEnumerable<T>(testCollection);

            //IEnumerable<T> allData = trainingCollection.Concat(testCollection);
            //IDataView allDataView = _mlContext.Data.LoadFromEnumerable<T>(testCollection);          
            // Generate the dataview for all of the data
            LoadData(_modelInput.TrainingCollection);
            TransformData();

            //var combinedDataView = textLoader.Load(new MultiFileSource(TrainDataPath, TestDataPath));
            RunDetail<RegressionMetrics> bestRun = experimentResult.BestRun;

            return bestRun.Estimator.Fit(_trainDataView); // pass in the data view for all of the data.
        }

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by famschopman** [comment]
I triggered this one recently. https://github.com/dotnet/machinelearning/issues/4029

I solved it by defining a sampling column for the time being myself.

```
[ColumnName("SamplingKeyColumn"), LoadColumn(35)]
public float SamplingKeyColumn { get; set; }
```

**Comment by acrigney** [comment]
I changed my code to reuse my transformer object between the fit and refit and I still get the error.
Looks like I need to debug with the framework but the framework is not building for me.
There is an error in the CMAKE included here.

CMAKE_C_FLAGS_DEBUG is /MDd /Zi /Ob0 /Od /RTC1
  In a future version, if the CMake that ships with VS2019 no longer contains the /ZI flag, delete this message block and the two lines below.
  -- Found OpenMP_C: -openmp (found version "2.0")
  -- Found OpenMP_CXX: -openmp (found version "2.0")
  -- Found OpenMP: TRUE (found version "2.0")
  -- Configuring done
  **CMake Error at MatrixFactorizationNative/CMakeLists.txt:28 (add_library):
    Cannot find source file:

      libmf/mf.cpp**

    Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
    .hpp .hxx .in .txx


  CMake Error at MatrixFactorizationNative/CMakeLists.txt:28 (add_library):
    No SOURCES given to target: MatrixFactorizationNative


  CMake Generate step failed.  Build files cannot be regenerated correctly.
  Failed to generate native component build project!
C:\Projects\machinelearning-masterLatest\machinelearning-master\src\Native\build.proj(67,5): error MSB3073: The command ""C:\Projects\machinelearning-masterLatest\machinelearning-master\src\Native\build.cmd" Debug x64 --mkllibpath C:\Projects\machinelearning-masterLatest\machinelearning-master\packages/mlnetmkldeps\0.0.0.9\runtimes\win-x64\native" exited with code 1.

**Comment by acrigney** [comment]
I hacked a fix for this like this
ModelForPrediction ModelForPrediction  = new ModelForPrediction();

                var properties = typeof(Model).GetRuntimeProperties();
                var destProperties = typeof(ModelForPrediction).GetRuntimeProperties();

                foreach (var property in properties)
                {
                    var dest = destProperties.FirstOrDefault(x => x.Name == property.Name);
                    if (dest != null)
                        if (dest.CanWrite)
                            dest.SetValue(ModelForPrediction, property.GetValue(test, null), null);
                }
                DoublePrediction prediction = predictorGenerator.GetSinglePrediction(ModelForPrediction);
            }

**Comment by StefanLundmark** [comment]
For me, this only happens when I've used TrainTestSplit() in DataOperationsCatalog on my data. If I split the sets myself then this error never shows up.

**Comment by SkyQuant** [comment]
Fake properties don't work for _FastForest_, but for another kind of trees it could serve as temporary solution.

```
        [ColumnName("SamplingKeyColumn"), LoadColumn(333)]
        public float SamplingKeyColumn { get; set; }

        [ColumnName("temp_SamplingKeyColumn_000"), LoadColumn(300)]
        public float SamplingKeyColumnTemp0 { get; set; }

        [ColumnName("temp_SamplingKeyColumn_001"), LoadColumn(301)]
        public float SamplingKeyColumnTemp1 { get; set; }

        [ColumnName("temp_SamplingKeyColumn_002"), LoadColumn(302)]
        public float SamplingKeyColumnTemp2 { get; set; }
```

**Comment by frank-dong-ms** [comment]
@acrigney could you please provide a repro project so we can investigate further?

**Comment by DiegoStefanon** [comment]
Also to me the same problem spitting data 👍 

 mlContext.Model.CreatePredictionEngine<>();
=> error 
"Could not find input column 'SamplingKeyColumn' (Parameter 'inputSchema')"

**Comment by frank-dong-ms** [comment]
@DiegoStefanon could you please provide a repro project as well as your data?

**Comment by frank-dong-ms** [comment]
Close this issue for now as not hearing back with required info to repro and investigate this issue. Feel free to reopen the issue if necessary, thanks.

**Comment by ladodc** [comment]
Hi, I have the same Problem. 
I get the following Error on this line **var predictor = mlContext.Model.CreatePredictionEngine<TSrc, TDst>(model);**:
System.ArgumentOutOfRangeException: 'Could not find input column 'SamplingKeyColumn' (Parameter 'inputSchema')'
Hier ist the Code to reproduce this error:


`
using Microsoft.ML;
using Microsoft.ML.AutoML;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using System;
using System.Collections.Generic;
using System.Linq;
using static Microsoft.ML.DataOperationsCatalog;

namespace AutoML
{
    class Program
    {
        static void Main(string[] args)
        {
            var mlContext = new MLContext(seed: 0);
            var examples = GenerateData(100);
            var dataview = mlContext.Data.LoadFromEnumerable(examples);

            TrainTestData trainTestSplit = mlContext.Data.TrainTestSplit(dataview, testFraction: 0.1, samplingKeyColumnName: null);
            IDataView trainingData = trainTestSplit.TrainSet;
            IDataView testData = trainTestSplit.TestSet;

            ITransformer model = TrainRegresionAutoML(trainingData);
            ReportOnFeatureImportance(mlContext, model, dataview);            

            OutputData prediction = PredictRegresinAutoML<InputData,OutputData>(model, new InputData(){A = 6, B = 6});          
        }

        static ITransformer TrainRegresionAutoML(IDataView trainData)
        {
            var mlContext = new MLContext(seed: 0);

            var settings = new RegressionExperimentSettings
            {
                MaxExperimentTimeInSeconds = 10, // In Second
                OptimizingMetric = RegressionMetric.RSquared,
                CacheDirectory = null
            };

            var experiment = mlContext.Auto().CreateRegressionExperiment(settings);
            
            var model = experiment.Execute(trainData);            


            return model.BestRun.Model;
        }

        private static void ReportOnFeatureImportance(MLContext context, ITransformer model, IDataView data)
        {            
            // Need to cast from the ITransformer interface to gain access to the LastTransformer property.
            var typedModel = (TransformerChain<IPredictionTransformer<object>>)model;
            var modelParams = typedModel.LastTransformer.Model as FastTreeRegressionModelParameters;
            var weights = new VBuffer<float>();
            modelParams.GetFeatureWeights(ref weights);            
        }

        static TDst PredictRegresinAutoML<TSrc, TDst>(ITransformer model, TSrc inputData) 
            where TSrc : class
            where TDst : class, new()
        {
            var mlContext = new MLContext(seed: 0);

            var predictor = mlContext.Model.CreatePredictionEngine<TSrc, TDst>(model);
            return predictor.Predict(inputData);
        }      

        private static IEnumerable<InputData> GenerateData(int count,
            int seed = 0)

        {
            for (int i = 0; i < count; i++)
            {
                for (int ii = 0; ii < count; ii++)
                {
                    yield return new InputData
                    {
                        A = i,
                        B = ii,
                        Value = i * ii
                    };
                }
            }
        }       
    }

    public class InputData
    {     
        public float A { get; set; }
        
        public float B { get; set; }

        [ColumnName("Label")]
        public float Value { get; set; }
    }

    public class OutputData
    {
        [ColumnName("Score")]
        public float Result;
    }

    public class FeatureImportance
    {
        public string Name { get; set; }

        public double RSquaredMean { get; set; }

        public double CorrelationCoefficient { get; set; }
    }
}
`

I hope it helps:

**Comment by antoniovs1029** [comment]
For the record, I believe this is an issue on `mlContext.Data.TrainTestSplit()` and `mlContext.Data.CrossValidationSplit()`, as I explain here:

https://github.com/dotnet/machinelearning/issues/5256#issuecomment-649883054

There I also provide some workarounds, but they would vary depending on the case of each user.
