### ISSUE TITLE
Torch support in ML.NET

### ISSUE THREAD

**Issue by artidoro** [dotnet/machinelearning#4053]
As ML.NET increases it's support for deep learning, we should add support for PyTorch models.
[TorchSharp](https://github.com/xamarin/TorchSharp) has bindings for LibTorch (PyTorch's C++ frontend) and offers the following functionality:

- Score models that were previously defined and trained in PyTorch's python API
- Define and train models directly in C#

We could have a scoring functionality similar to the TensorFlow scoring. We could also add training of Torch models defined in C#.

**Comment by GeorgeS2019** [comment]
Now we have the official [Microsoft.ML.TorchSharp](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.torchsharp) namespace.

We could close this issue now :-)

**Comment by GeorgeS2019** [comment]
@michaelgsharp 
> it currently only has a single TextClassification API.

Based on the Single example, it seems to me that it is doable to port [TorchAudio](https://github.com/dotnet/TorchSharp/discussions/651#discussioncomment-3125915) and TorchVision examples from TorchSharp to ML.NET using the same way how the TexTclassification API is set up.  This is just a thought, not sure if this is that straight forwards?
