### ISSUE TITLE
DetectSpikeBy(Ssa|Iid) confidence param should be double

### ISSUE THREAD

**Issue by esso23** [dotnet/machinelearning#4058]
This one is pretty simple. Confidence parameter in `DetectIidSpike` & `DetectSpikeBySsa` should be of type `double`. It makes no sense that it is of type `Int32` since it is being cast to `double` when creating `SsaSpikeDetector.Options()` anyway.

Same thing goes for `DetectChangePointBySsa`, `DetectIidChangePoint` and possibly others.

Right now it is not possible to search only for "extreme spikes" (confidence = ~99.9 or even more) using these extension methods.

Thanks
Esso

**Comment by esso23** [comment]
I would recommend raising the priority to highest possible because this renders all the ChangePoint/Spike detection algorithms useless. We had to modify the ML.NET library and recompile it to be able to use them. We are regularly using confidences like 99.9999999 etc. 99.0 is just waaaay too low for many cases and produces unwanted outputs.

**Comment by codemzs** [comment]
@esso23 looking into it now

**Comment by esso23** [comment]
Honesly I can't believe that such an important thing is still not fixed.
This really makes the entire TimeSeries library unusable in so many real-world scenarios.
