### ISSUE TITLE
Tensorflow Input Shape Mismatch

### ISSUE THREAD

**Issue by RamazanM** [dotnet/machinelearning#4062]
### System information

- **OS version/distro**: Linux Mint 19.1 Cinnamon
- **.NET Version (eg., dotnet --info)**: 2.2.401

### Issue

- **What did you do?**
I am trying to run tensorflow image detection model which retrained by "faster_rcnn" or "ssd_mobilenet_v2".

- **What happened?**
 But i got "Input Shape Mismatch" error. I considered this error is about PixelExtractor and i tried changing some parameters of it.

- **What did you expect?**
I expected get a float array of predicted boxes, or number of detection.

### Source code / logs
- My code:
```c#             
var pipeline =mlContext.Transforms.ResizeImages(outputColumnName: TensorFlowModelSettings.inputTensorName, imageWidth: ImageSettings.imageWidth, imageHeight: ImageSettings.imageHeight, inputColumnName: nameof(ImageInputData.Image))
.Append(mlContext.Transforms.ExtractPixels(outputColumnName: TensorFlowModelSettings.inputTensorName, interleavePixelColors: ImageSettings.channelsLast, offsetImage: ImageSettings.mean,outputAsFloatArray:false,colorsToExtract: ImagePixelExtractingEstimator.ColorBits.All))
.Append(mlContext.Model.LoadTensorFlowModel(modelPath).
ScoreTensorFlowModel(outputColumnNames: new[] { TensorFlowModelSettings.outputTensorName },
                     inputColumnNames: new[] { TensorFlowModelSettings.inputTensorName }, addBatchDimensionInput: false));


            var model = pipeline.Fit(CreateEmptyDataView());
            return model;
```
- The error message:
> System.InvalidOperationException: Input shape mismatch: Input 'image_tensor' has shape [?, ?, ?, 3], but input data is of length 206116.
   at Microsoft.ML.Transforms.TensorFlowTransformer.Mapper..ctor(TensorFlowTransformer parent, DataViewSchema inputSchema)
   at Microsoft.ML.Transforms.TensorFlowTransformer.MakeRowMapper(DataViewSchema inputSchema)
   at Microsoft.ML.Data.RowToRowTransformerBase.GetOutputSchema(DataViewSchema inputSchema)
   at Microsoft.ML.Transforms.TensorFlowEstimator.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)

> ### Annotation: When i was try an image classification model,  got an output successfully.

**Comment by huanbd** [comment]
I think you can try this, I was used with mobilenet_v2/ inception_v3
```
var pipeline =mlContext.Transforms.ResizeImages(outputColumnName: "image_obj", imageWidth: ImageSettings.imageWidth, imageHeight: ImageSettings.imageHeight, inputColumnName: nameof(ImageInputData.Image))
.Append(mlContext.Transforms.ExtractPixels(outputColumnName: TensorFlowModelSettings.inputTensorName,inputColumnName:"image_obj", interleavePixelColors: ImageSettings.channelsLast, offsetImage: ImageSettings.mean,outputAsFloatArray:false,colorsToExtract: ImagePixelExtractingEstimator.ColorBits.All))
.Append(mlContext.Model.LoadTensorFlowModel(modelPath).
ScoreTensorFlowModel(outputColumnNames: new[] { TensorFlowModelSettings.outputTensorName },
                     inputColumnNames: new[] { TensorFlowModelSettings.inputTensorName }, addBatchDimensionInput: false));
```
`inputeTensorName `should put be to model in step ExtractPixels. In step ResizeImages, `outputColumnName  `you can name it as you like

**Comment by ashbhandare** [comment]
@RamazanM Your model expects an input of shape [?,?,?,3], but your actual input is of length 206116, which is not divisible by 3(which is the known dimension in the input placeholder shape). There is no way where your actual input data can be fit into your placeholder. Consider using different image height and width for resizing your image.
