### ISSUE TITLE
TensorFlow exception triggered while loading model

### ISSUE THREAD

**Issue by xtremertx** [dotnet/machinelearning#4065]
### System information

- **OS version/distro**:
Windows 10.0.17763 Enterprise (version: 1809) (x64)
- **.NET Version (eg., dotnet --info)**: 
.NET Framework 4.7.2 (.NET Core 3.0.0-preview3-27503-5)

### Issue

- **What did you do?**
I have tried to load the custom tensorflow model of YoloV2 full.
- **What happened?**
Loading of tensorflow model failed with an generic error.
- **What did you expect?**
Model to be succesfully loaded and used for object detection. As my model was converted via DarkFlow without any errors.

### Source code / logs
 ```
      // Create IDataView from empty list to obtain input data schema
      var data = mlContext.Data.LoadFromEnumerable(new List<ImageNetData>());

      // Define scoring pipeline
      var pipeline = mlContext.Transforms.LoadImages(outputColumnName: "input", imageFolder: imagesFolder, inputColumnName: nameof(ImageNetData.ImagePath))
                      .Append(mlContext.Transforms.ResizeImages(outputColumnName: "input", imageWidth: ImageNetSettings.imageWidth, imageHeight: ImageNetSettings.imageHeight, inputColumnName: "input"))
                      .Append(mlContext.Transforms.ExtractPixels(outputColumnName: "input"))
                      .Append(mlContext.Model.LoadTensorFlowModel(modelLocation)
                      .ScoreTensorFlowModel(outputColumnNames: new[] { "output" }, inputColumnNames: new[] { "input" }, addBatchDimensionInput: true));

      // Fit scoring pipeline
      var model = pipeline.Fit(data);
```

TensorFlow exception triggered while loading model from 'C:\Users\Peter\source\repos\NeuralLink\NeuralLink\bin\Debug\XXXX.pb'

   at Microsoft.ML.Transforms.TensorFlow.TensorFlowUtils.LoadTFSession(IExceptionContext ectx, Byte[] modelBytes, String modelFile)
   at Microsoft.ML.TensorflowCatalog.LoadTensorFlowModel(ModelOperationsCatalog catalog, String modelLocation)
   at NeuralLink.Core.TensorFlowModelScorer.LoadModel() in C:\Users\Peter\source\repos\NeuralLink\NeuralLink\Core\TensorFlowModelScorer.cs:line 46
   at NeuralLink.Pages.Analyze.<UserControl_Initialized>d__7.MoveNext() in C:\Users\Peter\source\repos\NeuralLink\NeuralLink\Pages\Analyze.xaml.cs:line 156

_This is a seriouse flaw in ML.NET, I was expecting that it can load any VALID tensorflow model. I can post my model and some training images in case you want to investigate._

**Comment by Oceania2018** [comment]
Where can I download the on file?

**Comment by codemzs** [comment]
@xtremertx which version of Microsoft.ML.Tensorflow nuget are you using?

**Comment by xtremertx** [comment]
@codemzs I was using the latest nuget package (1.3.1) for .NETStandard 2.0 as I was using .NET Framework.

**Comment by xtremertx** [comment]
Will upload *.pb file and post links here..

**Comment by PanwarParamveer** [comment]
Error getting while rurring project System.FormatException
  HResult=0x80131537
  Message=Tensorflow exception triggered while loading model.
  Source=Microsoft.ML.TensorFlow
  StackTrace:
   at Microsoft.ML.TensorFlow.TensorFlowUtils.LoadTFSessionByModelFilePath(IExceptionContext ectx, String modelFile, Boolean metaGraph)
   at Microsoft.ML.TensorflowCatalog.LoadTensorFlowModel(ModelOperationsCatalog catalog, String modelLocation)
   at TransferLearning.Program.Main(String[] args) in X:\MLProject\MLNetExamples\TransferLearning\Program.cs:line 18

Inner Exception 1:
DllNotFoundException: Unable to load DLL 'tensorflow' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by Oceania2018** [comment]
@PanwarParamveer Have you installed [TensorFlow Binary](https://www.nuget.org/packages/SciSharp.TensorFlow.Redist/)?

**Comment by codemzs** [comment]
@PanwarParamveer https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.vision.imageclassificationtrainer?view=ml-dotnet

**Comment by xtremertx** [comment]
Did anyone tried my posted model and got same error? Any feedback?

**Comment by mehtanilay10** [comment]
I also faced the same exception. And I found that has dependancy on `SciSharp.TensorFlow.Redist`. 
So, after installing version `1.14.0` of this package I am able to perform Image classification.

**Comment by xtremertx** [comment]
Gonna to try that and give you some feedback.

**Comment by Atulkumargupta17** [comment]
I also experienced the same issue,
After installing the `SciSharp.TensorFlow.Redist`  version `1.14.0` , I am allowed to execute the Image classification.

**Comment by mstfbl** [comment]
Hi @xtremertx ,

I downloaded `XXXX.pb` and the training photos mentioned, and wrote the following test code to diagnose this issue. I also uninstalled the `SciSharp.TensorFlow.Redist` NuGet package from my build:

```csharp
        public void TensorFlowTempTest()
        {
            var mlContext = new MLContext(seed: 1);

            string modelLocation = @"C:\Users\mubal\Downloads\XXXX.pb";

            // Create IDataView from empty list to obtain input data schema
            var data = mlContext.Data.LoadFromEnumerable(new List<ImageNetData>());

            // Define scoring pipeline
            var pipeline = mlContext.Transforms.LoadImages(outputColumnName: "input", imageFolder: @"C:\Users\mubal\Desktop\temp\tmpPics", inputColumnName: nameof(ImageNetData.ImagePath))
                            .Append(mlContext.Transforms.ResizeImages(outputColumnName: "input", imageWidth: 416, imageHeight: 416, inputColumnName: "input"))
                            .Append(mlContext.Transforms.ExtractPixels(outputColumnName: "input"))
                            .Append(mlContext.Model.LoadTensorFlowModel(modelLocation)
                            .ScoreTensorFlowModel(outputColumnNames: new[] { "output" }, inputColumnNames: new[] { "input" }, addBatchDimensionInput: true));

            // Fit scoring pipeline
            var model = pipeline.Fit(data);
        }

```

With these, I obtained the following same error that has been reported here:

> System.FormatException : Tensorflow exception triggered while loading model.
        ---- System.DllNotFoundException : Unable to load DLL 'tensorflow' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
      Stack Trace: 
        TensorFlowUtils.LoadTFSessionByModelFilePath(IExceptionContext ectx, String modelFile, Boolean metaGraph) line 223
        TensorFlowUtils.GetSession(IHostEnvironment env, String modelPath, Boolean metaGraph) line 377
        TensorFlowUtils.LoadTensorFlowModel(IHostEnvironment env, String modelPath) line 113
        TensorflowCatalog.LoadTensorFlowModel(ModelOperationsCatalog catalog, String modelLocation) line 37
        TensorFlowScenariosTests.TensorFlowTempTest() line 146
        ----- Inner Stack Trace -----
        c_api.TF_NewGraph()
        Graph.ctor()
        TensorFlowUtils.LoadTFSessionByModelFilePath(IExceptionContext ectx, String modelFile, Boolean metaGraph) line 216

I fixed this issue by adding `SciSharp.TensorFlow.Redist` as a dependency to `Microsoft.ML.TensorFlow.csproj`, so that manual installation of this NuGet package isn't necessary. Thank you all for your contribution on this issue. :D

**Comment by codemzs** [comment]
@mstfbl What you are suggesting is not correct because it would limit our TensorFlow based APIs to CPU. I have already addressed this issue in my prior [reply](https://github.com/dotnet/machinelearning/issues/4065#issuecomment-552215881)

**Comment by xtremertx** [comment]
If I understant correctly, in some cases you need `SciSharp.TensorFlow.Redist` because some instructions are not implemented on GPU? It would be enough to just mention this in MS docs.

**Comment by codemzs** [comment]
@xtremertx That is not correct, you need `SciSharp.TensorFlow.Redist` if you want training to happen on the CPU. There is no instruction from training that works on CPU but not GPU, it is just a question of performance. These instructions(on which nuget to use and when) are mentioned in detail in the [docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.vision.imageclassificationtrainer?view=ml-dotnet) and I have also pasted the relevant snapshot below. Let me know if anything is not clear.

![image](https://user-images.githubusercontent.com/1211949/80944843-4d096800-8d9f-11ea-9b3a-b3ffdcc010ab.png)

**Comment by mstfbl** [comment]
In summary, a manual installation of the appropriate `SciSharp.TensorFlow.Redist` NuGet package is required. This is also stated in [docs/api-reference/tensorflow-usage.md](https://github.com/dotnet/machinelearning/blob/34b5e55ea143f7fc3a4acb33b9368f633819a845/docs/api-reference/tensorflow-usage.md). As such, I am closing this issue.

**Comment by rsazor12** [comment]
I had the same issue which I tried to solve a lot of time - I downgraded version of SciSharp.TensorFlow.Redist to 1.14.1 and It is working in my case :)

Previously I've used 2.3.0 version
