### ISSUE TITLE
French stopword "les" is misspelled

### ISSUE THREAD

**Issue by bleroy** [dotnet/machinelearning#4074]
The word "les" is a stopword in French, but it is misspelled "lès" in the [French.txt](https://github.com/dotnet/machinelearning/blob/a802127883c0020516aa573436029cabed65d591/src/Microsoft.ML.Transforms/Text/StopWords/French.txt#L27) file. I'd have fixed it directly there, but the repo is configured to only take changes on a branch.

**Comment by justinormont** [comment]
@bleroy: Do you think we should have both words? Translation (as best as I can tell) is "the" and "near".

These stop word lists have only "les": 
* https://www.ranks.nl/stopwords/french
* http://snowball.tartarus.org/algorithms/french/stop.txt

These stop word lists have both "lès" and "les": 
* https://github.com/stopwords-iso/stopwords-fr/blob/master/stopwords-fr.txt
* https://countwordsfree.com/stopwords/french
* https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnxrZXZpbmJvdWdlfGd4OjFlYTQxN2JkNmY1MTQ1NWE
* https://www.kaggle.com/rtatman/stopword-lists-for-19-languages#frenchST.txt

If you're up for it: 
To push in a fix, fork the repo then send a pull request.

**Comment by bleroy** [comment]
Sure, you can have both, but "lès" is extremely outdated (to the point where as a native French speaker, I had forgotten that word even existed). I could make a PR, yes, but I don't have a clone of this repo yet, and since it's such a small change, I thought an existing contributor could easily pick this up. If not, then fine, I'll do it.
