### ISSUE TITLE
alexnet fails with exception

### ISSUE THREAD

**Issue by ranigb** [dotnet/machinelearning#4075]
I am using ML.NET to get features for images using AlexNet. It was working a few month back but when I try it with the latest ML.NET bits it fails . There were some API changes that I tried to address but the most recent error I am getting is:

>  '[ErrorCode:Fail] Load model from ...\DnnImageModels\AlexNetOnnx\AlexNet.onnx failed:[ShapeInferenceError] Attribute pads has incorrect size'

Here is the code snippet:

```
        static string _Run(string imagesCatalog, string imagesFolder)
        {
            var mlContext = new MLContext();

 

            var cols = new[] {
                        new TextLoader.Column("ImagePath", DataKind.String, 0),
                        new TextLoader.Column("Label", DataKind.Int32, 1),
                };

 

            var data = mlContext.Data.CreateTextLoader(new TextLoader.Options()
            {
                Columns = cols
            }).Load(imagesCatalog);

 

            var pipeline = mlContext.Transforms.LoadImages(imageFolder:imagesFolder, outputColumnName: "ImageReal", inputColumnName: "ImagePath")
            .Append(mlContext.Transforms.ResizeImages(outputColumnName:"ImageObject", inputColumnName:"ImageReal", imageWidth: 227, imageHeight: 227))
            .Append(mlContext.Transforms.ExtractPixels("Pixels", "ImageObject"))
            .Append(mlContext.Transforms.DnnFeaturizeImage("FeaturizedImage", m => m.ModelSelector.AlexNet(mlContext, m.OutputColumn, m.InputColumn), "Pixels"));

      var transformedData = pipeline.Fit(data).Transform(data);

```
     the exception is fired in     

> AlexNet(mlContext, m.OutputColumn, m.InputColumn), "Pixels"))   

 

       

### System information
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by yaeldekel** [comment]
Hi @ranigb , thanks for reporting this issue. 
After investigating the problem, we found out that there is a bug in one of the layers in the Alexnet model. The easiest fix is probably to start using the models from the [model zoo](https://github.com/onnx/models). I have opened issue #4177 to track this, so I am closing this issue.
