### ISSUE TITLE
YOLOv3 ApplyOnnxModel throws Protobuf exception

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#4085]
### System information

-  .NET Version: 2.2
-  ML.NET Version: 1.2

### Issue

Given the following pipeline for the YOLOv3 full ONNX model downloaded from the Model Zoo:

```
var pipeline = _mlContext.Transforms.LoadImages("input_1:01", dataPath, "ImagePath")
                .Append(_mlContext.Transforms.ResizeImages("input_1:01", 416, 416))
                .Append(_mlContext.Transforms.ExtractPixels("input_1:01"))
                .Append(_mlContext.Transforms.ApplyOnnxModel("concat_2:0", "input_1:01", model
```

The exception below is raised:

```
Google.Protobuf.InvalidProtocolBufferException: 'Protocol message was too large.  May be malicious.  Use CodedInputStream.SetSizeLimit() to increase the size limit.'
```

**Comment by CESARDELATORRE** [comment]
Yeah, I remember having this exception when we tried the full YOLO3 model weeks ago. Thanks for creating this issue for ONNX support in ML.NET. 👍

**Comment by xtremertx** [comment]
Same error when trying the ONNX model created from tensorflow model....

**Comment by toras9000** [comment]
I think this problem may be the same as #4027.

**Comment by xtremertx** [comment]
> 
> 
> I think this problem may be the same as #4027.

Looks to be same.

**Comment by harishsk** [comment]
I tested loading the above pipeline in the latest ML.NET and the bug does not occur anymore. ML.NET now takes a dependency on v3.10.1 of google protobuf which has increased buffer size.

**Comment by luisquintanilla** [comment]
Confirmed. I no longer get the error reported on this issue.

**Comment by xtremertx** [comment]
Awesome work, gonna to try it! 👍

**Comment by phanxuanduc1996** [comment]
What is your full Yolov3 output? "grid" or "output" + "classLabel".
Can someone show me how to convert .weights -> .onnx with the output as "grid"?
