### ISSUE TITLE
Sparse

### ISSUE THREAD

**Issue by nfnpmc** [dotnet/machinelearning#4094]
No detail or example. 
What happens here? 
predictions = contextML.Data.CreateEnumerable&lt;DataBlobPrediction&gt;(
                T.Transform(contextML.Data.LoadFromEnumerable(blobsList, schemaML)), false, true);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09dc1ab7-401c-68e7-3ab9-38f5afbc4fc6
* Version Independent ID: c740981e-1bcd-c738-ad77-7dede76ed32b
* Content: [ITransformer.Transform(IDataView) Method (Microsoft.ML)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.itransformer.transform?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML/ITransformer.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML/ITransformer.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by najeeb-kazmi** [comment]
Unclear what the question is. `ITransformer.Transform` does not have an option for sparse, nor do `LoadFromEnumerable` or `CreateEnumerable`. 

Please feel free to reopen if there is still an isssue.
