### ISSUE TITLE
cannot extract MaximumEntropyModelParameters from pre-trained model, for using LbfgsMaximumEntropyMulticlassTrainer.Fit(IDataView, MaximumEntropyModelParameters) Method

### ISSUE THREAD

**Issue by jaehyok** [dotnet/machinelearning#4099]
### System information

- **OS version/distro**: windows 10 enterprise
- **.NET Version (eg., dotnet --info)**:  .Net Core 2.2
- **Microsoft.ML Version**:  1.3.1

### Issue

- **What did you do?**
I want to re-train multi-class (`LbfgsMaximumEntropyMulticlassTrainer`).
- **What happened?**
so, I train and load model, but i cannot extract `MaximumEntropyModelParameters`.
- **What did you expect?**
I want to extract `MaximumEntropyModelParameters` my pre-trained model.
I want to sample code using `LbfgsMaximumEntropyMulticlassTrainer.Fit(IDataView, MaximumEntropyModelParameters)` method.

### Source code / logs
Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.
**code:**
```c#
MLContext _mlContext = new MLContext(seed: 0);
var pipeline = _mlContext.Transforms.Conversion.MapValueToKey(inputColumnName: "Area", outputColumnName: "Label")
    .Append(_mlContext.Transforms.Text.FeaturizeText(inputColumnName: "Keyword", outputColumnName: "KeywordFeaturized"))
    .Append(_mlContext.Transforms.Concatenate("Features", "KeywordFeaturized"));
var trainingPipeline_LbfgsMaximumEntropy = pipeline
    .Append(_mlContext.MulticlassClassification.Trainers.LbfgsMaximumEntropy("Label", "Features"))
    .Append(_mlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel"));
var trainingPipeline_LbfgsMaximumEntropy = pipeline
    .Append(_mlContext.MulticlassClassification.Trainers.LbfgsMaximumEntropy("Label", "Features"))
    .Append(_mlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel"));

TrainTestData dataSplit = _mlContext.Data.TrainTestSplit(data, testFraction: 0.1);
IDataView _trainingDataView = dataSplit.TrainSet;
IDataView _testDataView = dataSplit.TestSet;
ITransformer _trainedModel2 = trainingPipeline_LbfgsMaximumEntropy.Fit(trainingDataView);
_mlContext.Model.Save(_trainedModel2, _trainingDataView.Schema, _modelPath);

DataViewSchema dataPrepPipelineSchema;
var dataPrepPipeline = _mlContext.Model.Load(_modelPath2, out dataPrepPipelineSchema);
var loadedModel2 = _mlContext.Model.Load(_modelPath2, out DataViewSchema modelInputSchema2);
MaximumEntropyModelParameters originalModelParameters = ((IPredictionTransformer<object>)loadedModel2).Model as MaximumEntropyModelParameters;
```

**log:**
```log
System.InvalidCastException: Unable to cast object of type 'Microsoft.ML.Data.TransformerChain`1[Microsoft.ML.ITransformer]' to type 'Microsoft.ML.Data.TransformerChain`1[Microsoft.ML.Transforms.KeyToValueMappingTransformer]'.
```

**Comment by najeeb-kazmi** [comment]
@jaehyok You will first have to separate out the `MapKeyToValue` in a separate pipeline and save two models:
```csharp
var trainingPipeline_LbfgsMaximumEntropy = pipeline
    .Append(_mlContext.MulticlassClassification.Trainers.LbfgsMaximumEntropy("Label", "Features"));
var keyToValuePipeline = _mlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel");

ITransformer _trainedModel2 = trainingPipeline_LbfgsMaximumEntropy.Fit(trainingDataView);
ITransformer _keyToValueModel = keyToValuePipeline.Fit(_trainedModel2.Transform(trainingDataView));

_mlContext.Model.Save(_trainedModel2, _trainingDataView.Schema, _modelPath);
_mlContext.Model.Save(_keyToValueModel, _trainedModel2.Transform(trainingDataView).Schema, _keyToValueModelPath);
```

you can extract `MaximumEntropyModelParameters` from a loaded model like this:
```csharp
var loadedModel2 = _mlContext.Model.Load(_modelPath2, out DataViewSchema modelInputSchema2);
var predictor = (loadedModel2 as TransformerChain<ITransformer>).LastTransformer as MulticlassPredictionTransformer<MaximumEntropyModelParameters>;
MaximumEntropyModelParameters parameters = predictor.Model;
```
You need two separate pipelines in order for `(loadedModel2 as TransformerChain<ITransformer>).LastTransformer` to be the `MulticlassPredictionTransformer` rather than the `KeyToValueMappingTransformer`.

Please let us know and reopen if this is still an issue.

**Comment by minhnguyen484** [comment]
Hi Najeeb
I followed your code, and I can extract MaximumEntropyModelParameters. But, now I got 2 problem.
1. When I use trained model to predict with code:
    var predictionEngine = mlContext.Model.CreatePredictionEngine<EngineerPredictModel, EngineerRegressionPredictionModel>(trainedModel);
=> this code not work.

2. When I retrain the model:
   IDataView transformedNewData = dataPrepPipeline.Transform(newData);
=> this code not work too.

Can you give me a full example about retrain the model that it used LbfgsMaximumEntropy algorithms?
Thanks and best regards.

Ps: This is my function I create to train the model
public static void BuildAndTrainModelFromDbV2(MLContext mlContext, IEnumerable<PredictModel> modelList, string modelPath)
        {
            // STEP 1: Common data loading configuration
            var data = mlContext.Data.LoadFromEnumerable(modelList);

            // STEP 2: Common data process configuration with pipeline data transformations
            var dataPrepEstimator = mlContext.Transforms.Conversion.MapValueToKey(outputColumnName: "Label", inputColumnName: nameof(PredictModel.EngineerId))
                    .Append(mlContext.Transforms.Text.FeaturizeText(outputColumnName: "JobTypeIdFeaturized", inputColumnName: nameof(PredictModel.JobTypeId)))
                    .Append(mlContext.Transforms.Text.FeaturizeText(outputColumnName: "CustomerIdFeaturized", inputColumnName: nameof(PredictModel.CustomerId)))
                    .Append(mlContext.Transforms.Text.FeaturizeText(outputColumnName: "CustomerTypeIdFeaturized", inputColumnName: nameof(PredictModel.CustomerTypeId)))
                    .Append(mlContext.Transforms.Text.FeaturizeText(outputColumnName: "SiteIdFeaturized", inputColumnName: nameof(PredictModel.SiteId)))
                    .Append(mlContext.Transforms.Text.FeaturizeText(outputColumnName: "TenantIdFeaturized", inputColumnName: nameof(PredictModel.TenantId)))
                    .Append(mlContext.Transforms.Concatenate(outputColumnName: "Features", "JobTypeIdFeaturized", "CustomerIdFeaturized",
                                                                                           "CustomerTypeIdFeaturized", "SiteIdFeaturized", "TenantIdFeaturized"));

            var lbfgsTrainingPipeLine = dataPrepEstimator.Append(mlContext.MulticlassClassification.Trainers.LbfgsMaximumEntropy("Label", "Features"));
            var keyToValuePipeLine = mlContext.Transforms.Conversion.MapValueToKey("PredictedLabel");

            ITransformer trainedModel = lbfgsTrainingPipeLine.Fit(data);
            ITransformer keyToValueModel = keyToValuePipeLine.Fit(trainedModel.Transform(data));

            mlContext.Model.Save(trainedModel, data.Schema, $"{modelPath}\\data_predict.zip");
            mlContext.Model.Save(keyToValueModel, trainedModel.Transform(data).Schema, $"{modelPath}\\data_prep_pipeline.zip");

            var predictionEngine = mlContext.Model.CreatePredictionEngine<EngineerPredictModel, EngineerRegressionPredictionModel>(trainedModel);
            var prediction = predictionEngine.Predict(new EngineerPredictModel { 
                JobTypeId = "15021"
            });
        }

**Comment by Nsankaradeva** [comment]
> Hi Najeeb
> I followed your code, and I can extract MaximumEntropyModelParameters. But, now I got 2 problem.
> 
> 1. When I use trained model to predict with code:
>    var predictionEngine = mlContext.Model.CreatePredictionEngine<EngineerPredictModel, EngineerRegressionPredictionModel>(trainedModel);
>    => this code not work.
> 2. When I retrain the model:
>    IDataView transformedNewData = dataPrepPipeline.Transform(newData);
>    => this code not work too.
> 
> Can you give me a full example about retrain the model that it used LbfgsMaximumEntropy algorithms?
> Thanks and best regards.
> 
> Ps: This is my function I create to train the model
> public static void BuildAndTrainModelFromDbV2(MLContext mlContext, IEnumerable modelList, string modelPath)
> {
> // STEP 1: Common data loading configuration
> var data = mlContext.Data.LoadFromEnumerable(modelList);
> 
> ```
>         // STEP 2: Common data process configuration with pipeline data transformations
>         var dataPrepEstimator = mlContext.Transforms.Conversion.MapValueToKey(outputColumnName: "Label", inputColumnName: nameof(PredictModel.EngineerId))
>                 .Append(mlContext.Transforms.Text.FeaturizeText(outputColumnName: "JobTypeIdFeaturized", inputColumnName: nameof(PredictModel.JobTypeId)))
>                 .Append(mlContext.Transforms.Text.FeaturizeText(outputColumnName: "CustomerIdFeaturized", inputColumnName: nameof(PredictModel.CustomerId)))
>                 .Append(mlContext.Transforms.Text.FeaturizeText(outputColumnName: "CustomerTypeIdFeaturized", inputColumnName: nameof(PredictModel.CustomerTypeId)))
>                 .Append(mlContext.Transforms.Text.FeaturizeText(outputColumnName: "SiteIdFeaturized", inputColumnName: nameof(PredictModel.SiteId)))
>                 .Append(mlContext.Transforms.Text.FeaturizeText(outputColumnName: "TenantIdFeaturized", inputColumnName: nameof(PredictModel.TenantId)))
>                 .Append(mlContext.Transforms.Concatenate(outputColumnName: "Features", "JobTypeIdFeaturized", "CustomerIdFeaturized",
>                                                                                        "CustomerTypeIdFeaturized", "SiteIdFeaturized", "TenantIdFeaturized"));
> 
>         var lbfgsTrainingPipeLine = dataPrepEstimator.Append(mlContext.MulticlassClassification.Trainers.LbfgsMaximumEntropy("Label", "Features"));
>         var keyToValuePipeLine = mlContext.Transforms.Conversion.MapValueToKey("PredictedLabel");
> 
>         ITransformer trainedModel = lbfgsTrainingPipeLine.Fit(data);
>         ITransformer keyToValueModel = keyToValuePipeLine.Fit(trainedModel.Transform(data));
> 
>         mlContext.Model.Save(trainedModel, data.Schema, $"{modelPath}\\data_predict.zip");
>         mlContext.Model.Save(keyToValueModel, trainedModel.Transform(data).Schema, $"{modelPath}\\data_prep_pipeline.zip");
> 
>         var predictionEngine = mlContext.Model.CreatePredictionEngine<EngineerPredictModel, EngineerRegressionPredictionModel>(trainedModel);
>         var prediction = predictionEngine.Predict(new EngineerPredictModel { 
>             JobTypeId = "15021"
>         });
>     }
> ```

Hi , 
You are using wrong model for prediction. Please refer below code for your example.

     var transformer = mlContext.Model.Load($"{modelPath}\\data_prep_pipeline.zip", out _);
     var retrainFile = $"{modelPath}\\data_predict.zip";

      if (File.Exists(retrainFile))
      {
          var retrainData = mlContext.Model.Load(retrainFile, out _);
          transformer.Append(retrainData);
      }
     var predictionEngine = mlContext.Model.CreatePredictionEngine<EngineerPredictModel, EngineerRegressionPredictionModel>(transformer);
