### ISSUE TITLE
Suggestion for test framework improvements.

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#410]
No reason to have same baselines for Debug and Release if they are same.

Currently we have /test/BaselineOutput folder which contains folders Common, SingleDebug and SingleRelease and they filled with pretty much same files. We need to modify our test framework so it will look first in Common folder and if file is not found then it should look in respectful folders.
Also word Single is legacy artifact and can be omitted. 

This would reduce size of repo, and simplify peoples life. Also it give more room to have platform specific tests since many of our tests disabled because we verify everything with windows output, which sometimes differ because of native code implementation.

**Comment by codemzs** [comment]
CC: @TomFinley

**Comment by Ivanidzo4ka** [comment]
So currently we have this structure of test\BaselineOutput and  and bin\{configuration}\{project}\{framework}\TestOutput folders. We pull files from same respective locations in both folders and compare them.

My proposal is to touch only test\BaselineOutput folder and in framework if we looking for file, first search in Common folder, then in Configuration specific folder, then in OS specific and then in combination of Configuration and OS. Everything we do with test output will continue to go to TestOutput folder, and you can run it for different Configurations and they would be inside respective Debug/Release folder. So you can compare them. It just during PR creation owner of PR can decide where he want's to put this files, if baselines are similar, he can put them into Common, if they different he can put them in respective folders. 

We also can have test similar AAACompareBaselines which would notify person what files are same, and should be moved to Common folder. 

Reason why I propose this solution is fact what currently and most of the time we have similar outputs (probably around 90% in our main solution and 100% in this repository so far) and in most cases all user need to do is to copy files into common folder.
