### ISSUE TITLE
Everything is a var type

### ISSUE THREAD

**Issue by nfnpmc** [dotnet/machinelearning#4100]
You are trying to explain what an IDataView is, but all the variable are of type var.
So is
var dataView = new InputObjectDataView(inputArray);
of type IDataView or what?
Given that VS easily converts to the correct type why is every example in the entire website filled with 'var's so we cannot determine what's going on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cebd0074-01d3-d048-305a-cfea8b4083de
* Version Independent ID: 7f1aaf72-e345-e334-6237-d92abd3aa6d3
* Content: [IDataView Interface (Microsoft.ML)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.idataview?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML/IDataView.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML/IDataView.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by SnakyBeaky** [comment]
I'm against abusing the `var` keyword as well... I can understand why it's used in obvious places (e.g. `var mlContext = new MLContext()`), but it makes code harder to read most of the time.

I guess you're free to make a PR changing var for the explicit types.

**Comment by harishsk** [comment]
Many of ML.NET's classes have fairly long names. Using the explicit type in every case instead of 'var' causes its own readability issues. With intellisense, I hope the type is still easily inferred when using var.
