### ISSUE TITLE
 DnnEstimator.Architecture.InceptionV3  classification incorrect.

### ISSUE THREAD

**Issue by time888** [dotnet/machinelearning#4102]
The tensorflow_inception_graph.pb classification correct。But image size only 224.
I tested. DnnEstimator.Architecture.InceptionV3
DrawString "0" to Graphics Save to file 0.gif, and The other is the same 1.gif,2.gif,3.gif .

       public static IEnumerable<ImageNetDigData> LoadImagesFromDirectory(string folder)
        {

            var files = Directory.GetFiles(folder, "*.gif",
    searchOption: SearchOption.TopDirectoryOnly);
            foreach (var file in files)
            {
                //0.gif,1.gif,2.gif.3.gif      a0.gif,a1.gif, x1.gif,x2.gif
                var name = Path.GetFileName(file).Split(new char[] { '.' })[0];
                var label = name.Substring(name.Length - 1, 1);

                var nd = new ImageNetDigData()
                {
                    ImagePath = file,
                    Label = label
                };
                yield return nd;
            }
        }

But classification incorrect。
How to configure parameters？
Give me a sample.Thanks.

**Comment by codemzs** [comment]
Please upgrade to preview-2 and refer to these [samples](https://github.com/dotnet/machinelearning/tree/master/docs/samples/Microsoft.ML.Samples/Dynamic/ImageClassification).
