### ISSUE TITLE
Cluster Documents

### ISSUE THREAD

**Issue by MaxAkbar** [dotnet/machinelearning#4106]
Is there a way to cluster documents\text. Looking at the documentation [KMeansTrainer Class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.kmeanstrainer?view=ml-dotnet) is using single as the input type. Is there a way to extend or perhaps something in a future version?

I know that I can use classification but that requires a lot of work as I have many documents.

**Comment by codemzs** [comment]
@MaxAkbar We have [text featurzier transform](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.textcatalog.featurizetext?view=ml-dotnet) that can convert your document to a vector of floats, you can also use word embedding and then feed in the vector of floats to k-means trainer and do unsupervised clustering.
