### ISSUE TITLE
ImageDataViewType produces different outputs

### ISSUE THREAD

**Issue by nfnpmc** [dotnet/machinelearning#4111]
In one program I have
```C#
var builder = new DataViewSchema.Builder();
                builder.AddColumn("Label", TextDataViewType.Instance);
                ImageDataViewType imDT = new ImageDataViewType();
                builder.AddColumn("Image", imDT);
                lSchema = builder.ToSchema();
```
and the imDT.Rawtype is {System.Drawing.Bitmap}. This works perfectly when the lSchema is used in  CreatePredictionEngine.
In another program I have
```C#
                DataViewSchema.Builder builder = new DataViewSchema.Builder();
                builder.AddColumn("Label", TextDataViewType.Instance);
                ImageDataViewType imDT = new ImageDataViewType();
                builder.AddColumn("Image", imDT);
                lSchema = builder.ToSchema();
```
where inDT RawType is {Name = "Bitmap" FullName = "System.Drawing.Bitmap"}
which preduces the error {"Could not determine an IDataView type for member Image\r\nParameter name: rawType"}.
I am trying to eliminate the original exception of {"Could not determine an IDataView type for member Image\r\nParameter name: rawType"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78deb193-fc79-6814-c8e8-30ab50febfa9
* Version Independent ID: 9c3da030-2aef-37b3-40da-c63ff9c85780
* Content: [ImageDataViewType Class (Microsoft.ML.Transforms.Image)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.image.imagedataviewtype?view=ml-dotnet-1.0.0)
* Content Source: [dotnet/xml/Microsoft.ML.Transforms.Image/ImageDataViewType.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Transforms.Image/ImageDataViewType.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by frank-dong-ms** [comment]
@nfnpmc Thanks for reporting this issue, could you please provide a repro project so we can investigate further?

**Comment by nfnpmc** [comment]
Not any longer. I cannot remember which project that was a part of. The question, is really, why are the two methods of specifying imDT returning different results when added to builder?

**Comment by frank-dong-ms** [comment]
I don't think these 2 methods should return different result otherwise it looks like a bug to me. I will try to repro the issue.

**Comment by frank-dong-ms** [comment]
I tried to repro but didn't find a way to repro it with just the code piece provided. The 2 piece of code is almost identical.

I find an similar issue with similar error message: https://github.com/dotnet/machinelearning/issues/4122 so the problem seems like be the schema in model and code didn't map correctly.

I will close this issue and feel free to reopen if necessary.
