### ISSUE TITLE
Re-using the same Dataview with Bitmaps in memory, breaks when fitting different models or run cross validation on it

### ISSUE THREAD

**Issue by ssaporito** [dotnet/machinelearning#4126]
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: .NET Core 2.2 

### Issue

- **What did you do?**
I had a working pipeline for training image classification with cross-validation on the previous ML.NET version, using file paths as input. Now, being able to load Bitmaps, I am trying to setup a similar pipeline, but allowing training and predictions from in-memory bitmaps.
- **What happened?**
The training works if I just Fit the data,
`ITransformer mlModel = pipeline.Fit(trainData);`
 but it fails if I try to use CrossValidate
`var cvResults = _mlContext.MulticlassClassification.CrossValidate(trainData, pipeline, numberOfFolds);`
- **What did you expect?**
I expected a pipeline that worked with Fit to work with CrossValidate, but it seems the internal multiple passes do something to the Bitmaps (they lose data).
### Source code / logs
My current pipeline, based on [this sample](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/DeepLearning_ImageClassification_TensorFlow) is this:
```C#
var pipeline = _mlContext.Transforms.Conversion.MapValueToKey("Label")               
                .Append(_mlContext.Transforms.ResizeImages(outputColumnName: TensorFlowModelSettings.inputTensorName, imageWidth: ImageSettings.imageWidth, imageHeight: ImageSettings.imageHeight, inputColumnName: nameof(ImageInputData.Image)))                
                .Append(_mlContext.Transforms.ExtractPixels(outputColumnName: TensorFlowModelSettings.inputTensorName, interleavePixelColors: ImageSettings.channelsLast, offsetImage: ImageSettings.mean/*, inputColumnName: nameof(ImageInputData.Image)*/))                
                .Append(_mlContext.Model.LoadTensorFlowModel(tensorFlowModelFilePath).
                ScoreTensorFlowModel(outputColumnNames: new[] { TensorFlowModelSettings.outputTensorName },
                                    inputColumnNames: new[] { TensorFlowModelSettings.inputTensorName }, addBatchDimensionInput: false))                
                .Append(_mlContext.MulticlassClassification.Trainers.LbfgsMaximumEntropy(labelColumnName: "Label", featureColumnName: TensorFlowModelSettings.outputTensorName))
                .Append(_mlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel"))
                .AppendCacheCheckpoint(_mlContext);
```

The error log includes the following exceptions:

```
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Image.get_Height()
   at Microsoft.ML.Transforms.Image.ImageResizingTransformer.Mapper.<>c__DisplayClass3_0.<MakeGetter>b__1(Bitmap& dst)
   at Microsoft.ML.Transforms.Image.ImagePixelExtractingTransformer.Mapper.<>c__DisplayClass5_0`1.<GetGetterCore>b__1(VBuffer`1& dst)
   at Microsoft.ML.Data.DataViewUtils.Splitter.InPipe.Impl`1.Fill()
   at Microsoft.ML.Data.DataViewUtils.Splitter.<>c__DisplayClass9_0.<SplitCore>b__1()
```

```
System.InvalidOperationException: Splitter/consolidator worker encountered exception while consuming source data ---> System.ArgumentException: Parameter is not valid.
   at System.Drawing.Image.get_Height()
   at Microsoft.ML.Transforms.Image.ImageResizingTransformer.Mapper.<>c__DisplayClass3_0.<MakeGetter>b__1(Bitmap& dst)
   at Microsoft.ML.Transforms.Image.ImagePixelExtractingTransformer.Mapper.<>c__DisplayClass5_0`1.<GetGetterCore>b__1(VBuffer`1& dst)
   at Microsoft.ML.Data.DataViewUtils.Splitter.InPipe.Impl`1.Fill()
   at Microsoft.ML.Data.DataViewUtils.Splitter.<>c__DisplayClass9_0.<SplitCore>b__1()
   --- End of inner exception stack trace ---
   at Microsoft.ML.Data.DataViewUtils.Splitter.Batch.SetAll(OutPipe[] pipes)
   at Microsoft.ML.Data.DataViewUtils.Splitter.Cursor.MoveNextCore()
   at Microsoft.ML.Data.RootCursorBase.MoveNext()
   at Microsoft.ML.Data.DataViewUtils.Splitter.<>c__DisplayClass5_1.<ConsolidateCore>b__2()
```

This is my first issue here, and I apologize if I overlooked something. I found no posts about this error anywhere.

**Comment by SnakyBeaky** [comment]
I ran into a similar issue a few weeks ago while using `CrossValidate()`, and my pipeline included loading and extracting pixels from bitmaps as well.

**Comment by ssaporito** [comment]
From what I've read, issue #4084 seems to be closely related to this problem. I'm not sure whether the suggestions there were fully implemented or not.

**Comment by ssaporito** [comment]
Was this addressed in the upcoming 1.4.0 version? I need to know in order to either wait or try another approach.

**Comment by SnakyBeaky** [comment]
@ssaporito I ended up implementing my own cross validation.

I split the data set into 5 different permutations train/test (80%/20%) sets, train a model on each of the permutations and average the resulting metrics of all 5 runs.

**Comment by antoniovs1029** [comment]
Hi, @SnakyBeaky and @ssaporito . Sorry for the late response. Are you still having this problem? Can you provide a repro to take a look into this?

I've written the code below (based on [this sample](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_TensorFlowEstimator) but modifying it to use images in memory, and using [its dataset](https://github.com/dotnet/machinelearning-samples/blob/8697bec3e9c78beb2c3c4d3f915551c85bcdcb39/samples/csharp/getting-started/DeepLearning_TensorFlowEstimator/ImageClassification.Train/Program.cs#L86-L103) and [tensorflow model](https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/getting-started/DeepLearning_TensorFlowEstimator/ImageClassification.Train/assets/inputs/tensorflow-pretrained-models/inception-v3/inception_v3_2016_08_28_frozen.pb)) and it ran without problems on ML.NET version 1.5.0-preview2 (which is the latest release). Am I missing something to reproduce your issue? Thanks!

```C#
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Transforms.Image;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;

namespace is4126CrossValidateInMemoryImages
{
    class Program
    {
        public class ImageData
        {
            public string ImagePath;

            public string Label;

            [ImageType(227, 227)]
            public Bitmap Image { get; set; }
        }

        static void Main(string[] args)
        {
            var inputTensorFlowModelFilePath = @"C:\Users\anvelazq\Desktop\is4126\inception_v3_2016_08_28_frozen.pb";
            var inputDataSetFolder = @"C:\Users\anvelazq\Desktop\is4126\flower_photos_small_set";
            // var outModelPath = @"C:\Users\anvelazq\Desktop\is4126\model.zip";

            var mlContext = new MLContext();
            var imageSet = LoadImagesFromDirectory(inputDataSetFolder);
            IDataView fullImagesDataset = mlContext.Data.LoadFromEnumerable(imageSet);
            IDataView trainDataset = fullImagesDataset;
            var pipeline =
                mlContext.Transforms.Conversion.MapValueToKey("Label")
                //.Append(mlContext.Transforms.LoadImages(outputColumnName: "image_object", imageFolder: null, "ImagePath"))
                //.Append(mlContext.Transforms.CopyColumns("image_object", "Image"))
                .Append(mlContext.Transforms.ResizeImages(outputColumnName: "image_object_resized", imageWidth: 299, imageHeight: 299, inputColumnName: "Image"))
                .Append(mlContext.Transforms.ExtractPixels(outputColumnName: "input", inputColumnName: "image_object_resized", interleavePixelColors: true, offsetImage: 117, scaleImage: 1 / 255f))
                .Append(mlContext.Model.LoadTensorFlowModel(inputTensorFlowModelFilePath).ScoreTensorFlowModel(outputColumnNames: new[] { "InceptionV3/Predictions/Reshape" }, inputColumnNames: new[] { "input" }, addBatchDimensionInput: false))
                .Append(mlContext.MulticlassClassification.Trainers.LbfgsMaximumEntropy(labelColumnName: "Label", featureColumnName: "input"))
            ;

            Console.WriteLine(DateTime.Now);

            var model = pipeline.Fit(trainDataset);
            // var x = model.Transform(trainDataset).Preview();

            Console.WriteLine(DateTime.Now);

            // mlContext.Model.Save(model, trainDataset.Schema, outModelPath);

            Console.WriteLine(DateTime.Now);
            var eval = mlContext.MulticlassClassification.CrossValidate(trainDataset, pipeline, 5);
            Console.WriteLine(DateTime.Now);
        }

        public static IEnumerable<ImageData> LoadImagesFromDirectory(string folder, bool useFolderNameasLabel = true)
        {
            var files = Directory.GetFiles(folder, "*",
                searchOption: SearchOption.AllDirectories);

            foreach (var file in files)
            {
                if ((Path.GetExtension(file) != ".jpg") && (Path.GetExtension(file) != ".png"))
                    continue;

                var label = Path.GetFileName(file);
                if (useFolderNameasLabel)
                    label = Directory.GetParent(file).Name;
                else
                {
                    for (int index = 0; index < label.Length; index++)
                    {
                        if (!char.IsLetter(label[index]))
                        {
                            label = label.Substring(0, index);
                            break;
                        }
                    }
                }

                yield return new ImageData()
                {
                    ImagePath = file,
                    Label = label,
                    Image = (Bitmap) Image.FromFile(file)
            };

            }
        }
    }
}
```

**Comment by antoniovs1029** [comment]
So I've ran the code I posted above both in ML.NET 1.5.0-preview2 and 1.3.1 (which was probably the version used by the original poster), both in .NET Core 3.1 and 2.1, and I didn't get any exception.

**Comment by antoniovs1029** [comment]
By changing the following line on my code above, I was actually able to reproduce this issue, and got a "System.ArgumentException: Parameter is not valid"; I got it even in version 1.5.0-preview2.

```C#
IDataView fullImagesDataset = mlContext.Data.LoadFromEnumerable(imageSet.ToList());
```

The difference is that by turning the imageSet enumerable into a List, now it's actually reusing the same objects, instead of yielding new objects as I did in my original code.

So I will look into this. Nonetheless, notice that a workaround would be to actually create an IEnumerable which yielded clones of the original images (I guess this wouldn't be as performant, but I guess it could be a valid workaround):

```C#
IDataView fullImagesDataset = mlContext.Data.LoadFromEnumerable(yieldImages(imageSet.ToList()));
```
with
```C#
        public static IEnumerable<ImageData> yieldImages(List<ImageData> imageSet)
        {
            foreach (var imageData in imageSet)
            {
                yield return new ImageData()
                {
                    ImagePath = imageData.ImagePath,
                    Label = imageData.Label,
                    Image = (Bitmap) imageData.Image.Clone()
                };
            }
        }
```

**Comment by antoniovs1029** [comment]
Also, this isn't a problem specifically with using CrossValidation. E.g. if I try to do the following

```C#
IDataView trainDataset = mlContext.Data.LoadFromEnumerable(imageSet.ToList());
var model = pipeline.Fit(trainDataset);
var model2 = pipeline.Fit(trainDataset);
```

I get the same exception when fitting the second model.

For this other case a workaround would be to simply create 2 DataViews (no need to clone the Image objects):
```C#
IDataView trainDataset = mlContext.Data.LoadFromEnumerable(imageSet.ToList());
var model = pipeline.Fit(trainDataset);

IDataView trainDataset2 = mlContext.Data.LoadFromEnumerable(imageSet.ToList());
var model2 = pipeline.Fit(trainDataset2);
```

This way I don't get any exception and it works as expected. Still, this other workaround wouldn't work with CrossValidate() because there the user can only pass 1 dataview which is internally splitted, and the bug seems related to how this split is done with DataViews that contain images in memory and that are meant to be reused.

**Comment by antoniovs1029** [comment]
The problem is in the disposer created in the `ImageResizerTransformer`, as it disposes the `src` Bitmap that it uses as input of the transformer:

https://github.com/dotnet/machinelearning/blob/919bc8b886a6bc20c5022e8dad00f84bc1248236/src/Microsoft.ML.ImageAnalytics/ImageResizer.cs#L283-L291

If I comment out the content of the disposer so that it's empty, then the exceptions go away in the repros I've provided (both when using cross validation, or when fitting twice a pipeline).

Still, I'd have to investigate if that disposer is truly necessary, and how to avoid using it in the case where a user wants to use in-memory images to train multiple pipelines and/or use cross validation with them.
