### ISSUE TITLE
How to analyze sentiment comment of other language not english?

### ISSUE THREAD

**Issue by huanbd** [dotnet/machinelearning#4128]
### Issue

- **What did you do?**
Learned an [example analyze comment](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis), data for train is English comment.
- **What happened?**
I want to know how to use ML.NET to analyze comment but data for train is other language not English (in my case is vietnamese).
With my knowledge, I think have to step to preprocess data before use ML.NET to train, but I don't know how to code use ML.NET.
- **What did you expect?**
Want to know step to resolve my problem or any plan to support to do that.

**Comment by SnakyBeaky** [comment]
You just need to train the model with a different data set. The trainer in the example (in this case, `SdcaLogisticRegression`) does not have a notion of language.

If you provide all your training data in vietnamese (instead of the english training data found in `yelp_labelled.txt` in the example), you'll the sentiment results for vietnamese text.

**Comment by huanbd** [comment]
Thank you, @SnakyBeaky. 
I'm still confused about that, cause I've read an basic about analyze sentiment in theory. It has two step pre-process data that is tokenization, and stop-word filter.
Can you help me to clear that when use ML.NET?

**Comment by justinormont** [comment]
Greetings @huanbd. 

@SnakyBeaky is correct. If you have a Vietnamese language dataset, with a label which indicates the sentiment of the row, simply follow the existing sentiment example.

The sentiment example has a tokenization step and bag-of-words both wrapped in to the singular text transform. You can run both steps independently; though it's much more straight forward and less error prone by using the text transform.

I wouldn't worry about the stop-word filter. While you can add one in ML.NET, it's generally not helpful as the trainer itself will automatically decide if a word is useful or not.
