### ISSUE TITLE
CodeCov stopped

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning#4133]
We link to the CodeCov report in the repo's main README.md. The CodeCov report seems to have stopped ~3mo ago.

https://codecov.io/gh/dotnet/machinelearning/commits:
> ![image](https://user-images.githubusercontent.com/4080826/63308479-ba27ac80-c2a7-11e9-9052-b4c69abe59f0.png)

Did we disable the CodeCov bot?

**Comment by codemzs** [comment]
It works now.  Fixed it recently.
