### ISSUE TITLE
Memory leak in the latest ML.NET 1.3.1

### ISSUE THREAD

**Issue by SnakyBeaky** [dotnet/machinelearning#4134]
### System information

- **OS version/distro**: Windows 10 Pro 10.0.17763
- **.NET Version (eg., dotnet --info)**:  .NET Core 2.2.203 e5bab63eca

### Issue

- **What did you do?** Update the NuGet references to Microsoft.ML.* from `1.2.0` to `1.3.1`.
- **What happened?** Memory leaking
- **What did you expect?** Same behaviour as before

### Source code / logs

The pipeline consists of a ValueToKey mapping, loading image, resizing and extracting pixels, input them into an tensorflow inception model and finally a LbfgsMaximumEntropy trainer.

This is a run training several models in `1.2.0`:
![image](https://user-images.githubusercontent.com/8410877/63354071-0e906200-c364-11e9-8f98-e2a386efe7f9.png)

The same exact code, running in `1.3.1`:
![image](https://user-images.githubusercontent.com/8410877/63354132-2a940380-c364-11e9-86be-1193457a6caa.png)

Object count and heap size are more or less stable, my guess is something related to the tensorflow model not being cleared up.
![image](https://user-images.githubusercontent.com/8410877/63354150-3253a800-c364-11e9-98eb-9fe0428c8528.png)

**Comment by codemzs** [comment]
Thanks! Looking at this.
