### ISSUE TITLE
How to optimize a machine learning model in ML.NET?

### ISSUE THREAD

**Issue by nishaesubhash** [dotnet/machinelearning#4136]
I have created a machine learning model using ML.NET. The learning algorithm used is multiclass classification algorithm. I have tried regression algorithms also. But output of the model is not acccurate. Is there any optimization techniques in ML.NET to make the model more accurate?

**Comment by codemzs** [comment]
Thanks @PeterPann23 . Using AutoML is one way to optimize models and other ways would be just through experience.

**Comment by PeterPann23** [comment]
experiences = trail and error as there is not enough documentation on the trainer options to get any working model. also the framework lacks visualisation.  I think it's more like "Guesstimating" now as one has no idea what its is going to do. You as a developer on the team may have a different opinion, but us consumers should think 2x before recommending this Framework as the TCO can't be estimated

**Comment by voodookoop** [comment]
I'd couple @PeterPann23 's ML model optimization structure with some kind of genetic algorithm framework for those cases where there are several input parameters for the training operation itself (like for binaries: NumberOfLeaves, MinimumExampleCountPerLeaf as said). Of course it'll take ages to optimize even one single model depending on available machine resources, but it might worth a shot.
