### ISSUE TITLE
Please focus on stabilizing and consistency before adding more features

### ISSUE THREAD

**Issue by famschopman** [dotnet/machinelearning#4148]
This is a general observation that I want to share in hope of boosting the quality and adoptability of ML.net because I really think it has great potential. 

In recent release I have seen various features being added while the basics are not there yet, e.g. not working correctly or operate in an inconsistent way. This becomes obvious once you go outside of the standard basic tutorials. 

The breaking changes into ML.net concepts in its earlier stage also had a domino effect on documentation, examples and learning code available online that in many cases have not yet been adjusted to reflect the new situation, and in many case are not compatible anymore. So it is even more important to release features that operate correctly and consistently to build trust.

Simple example, explainability of the model is crucial when you want to build confidence with end users of the analysis. However a feature like PFI does not work if you load the model from disk (you could mitigate by persisting the PFI outcome separately for future consumption but again, it is a workaround). It also doesn't work in combination with AutoML. 

Making sure these features are working from A-Z across the various ways of interacting with ML.Net is crucial. It would for sure allow for much faster adoption of ML.Net because right now because it prevents you from moving forward as everything still feels very fragile with loose ends. And that is a shame because the potential is huge.

**Comment by codemzs** [comment]
@famschopman We are trying our best to increase the stability of the repo while also add new features, that being said this is an opensource project so please feel free to make it better. The PFI issue you are describing has already been fixed as part of #4262
