### ISSUE TITLE
Optimize FactorizationMachinesNative.cpp

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#415]
Optimize the FactorizationMachinesNative.cpp, by:
1- switching the control variables of the for loops from post-increment to pre-increment, to avoid the extra storage 
2- Optimize the intermediate calculations on the current tight loops for better performance. 

Example: 
for (int fprime = 0; fprime < m; fprime++)
        {
            const int vBias = j * m * d + fprime * d;
            const int qBias = f * m * d + fprime * d;

3- Potentially substitute AlignedArray with a regular array. See the discussion on PR #383

**Comment by shauheen** [comment]
Thanks Senja, could you please explain in more details what is the issue?

**Comment by sfilipi** [comment]
Updated the description. Thanks for pointing out.

**Comment by bojanmisic** [comment]
@sfilipi, I believe it should state from _post-increment_ to pre-increment. Sorry for the annoyance.

**Comment by wschin** [comment]
Please do a comprehensive comparison if you need to do regular array. As computation cost is 200 times (for criteo)  more than memory copy cost, it is a bit risky...

**Comment by codemzs** [comment]
Closing this until @wschin deems this is useful. Also please do a comparison before suggesting a perf change to be definitive.
