### ISSUE TITLE
type and namespaces name "xxx" does not exist  in  Microsoft ML (1.3.0) 

### ISSUE THREAD

**Issue by gohlaysiong** [dotnet/machinelearning#4150]
### System information

- Win7 Prof  OS version/distro  :
- VS2017 NET Version (eg., dotnet --info)**: 

### Issue
he type or namespace name 'Api' does not exist in the namespace 'Microsoft.ML.Runtime' (are you missing an assembly reference?)

- **What did you do?**
update ML version
![ML v1 3](https://user-images.githubusercontent.com/16553358/63830128-f17c1480-c99d-11e9-9746-40069926d9b8.png)

- **What happened?**
update ML.net from 0.5 to 1.3 

- **What did you expect?**
Able to compile and run 

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.
![image](https://user-images.githubusercontent.com/16553358/63829656-ba593380-c99c-11e9-991b-c6fa06b6bdb8.png)

**Comment by codemzs** [comment]
@gohlaysiong as @jwood803 mentions it is because we have refactored our API for 1.0 release and hence you are seeing this. I suggest you upgrade to the release nuget (1.0+).
