### ISSUE TITLE
[Image Classification DNN] - Need to support additional image formats, not just JPEG

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning#4152]
The current implementation only supports JPEG images for the dataset since it only has `JpegDecoding `etc. internally.

Ideally, we need to support the same image formats than the ones supported by each Architecture (InceptionV3, ResNet, etc.)

See in PR: https://github.com/dotnet/machinelearning/pull/4151/files#diff-37f2285ba1483af56ae20862631502ecR177

**Comment by codemzs** [comment]
The current tf.net version we are using does not seem to have bindings for all image types. But the latest version seems to have we will upgrade to them latest next month

**Comment by codemzs** [comment]
@ashbhandare is looking into this.

**Comment by ashbhandare** [comment]
According to Tensorflow documentation for decode_jpeg (https://www.tensorflow.org/api_docs/python/tf/io/decode_jpeg), the function supports "decoding PNGs and non-animated GIFs". This implies that currently, there is support for JPEG, PNG and non-animated GIFs in the ImageClassification implementation.
