### ISSUE TITLE
Is there a way to use `CreatePredictionEngine` dynamically

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning#4154]
To use `CreatePredictionEngine`, I need to define input and output class first. But what if I don't want to do that. ( because my data has too many dimensions, it's just painful to put it as class), is there a way to call into that `CreatePredictionEngine` method using data format like dictionary or dynamic object?

**Comment by ittahad** [comment]
Hey!! did you find the solution to this? I am also wondering the same thing!!
