### ISSUE TITLE
Create a tests database for the DatabaseLoader tests on macOS and Linux

### ISSUE THREAD

**Issue by tannergooding** [dotnet/machinelearning#4156]
https://github.com/dotnet/machinelearning/pull/4138 added support for testing against an actual database by attaching a SQL mdf file. However, that functionality is only available on Windows.

A database file that is supported on Linux and macOS should be created (likely MySQL) so that the tests can successfully run there as well.

**Comment by veikkoeeva** [comment]
@tannergooding You could create the database programmatically on every vendor and populate it wth the desired data dynamically. Here's some ways of doing it

### SQL Server
``` return @"USE [Master];
                DECLARE @fileName AS NVARCHAR(255) = CONVERT(NVARCHAR(255), SERVERPROPERTY('instancedefaultdatapath')) + N'{0}';
                EXEC('CREATE DATABASE [{0}] ON PRIMARY 
                (
                    NAME = [{0}], 
                    FILENAME =''' + @fileName + ''', 
                    SIZE = 20MB, 
                    MAXSIZE = 100MB, 
                    FILEGROWTH = 5MB
                )')";
            }`
```

### MySQL

`"CREATE DATABASE `{0}`"`

### PostgreSQL
`"CREATE DATABASE ""{0}"" WITH ENCODING='UTF8' CONNECTION LIMIT=-1;"`

Likewise they can be dropped or "cloned" if needed. These are straight from Orleans project and could be improved.

**Comment by veikkoeeva** [comment]
Looking back at some of the PRs involving this, maybe I could add that if you have large datasets at hand and do not want to generate anything dynamically, you have options such as bulkloading, or returning a backup or a snapshot. These are very fast at least on SSDs, almost disk speed (if you don't do full logging to restore).

I'm not sure if this is handy tool for development time or something intended to production, but if also for production case, you may need a bit more machinery for testing, switch to asynchronous methods, likely expose streaming and so forth.
