### ISSUE TITLE
Example for parameter sweeping using pipeline

### ISSUE THREAD

**Issue by rauhs** [dotnet/machinelearning#416]
Hi,

quick question: Is there somewhere docs or an example for how to grid/random sweep a parameter using the pipeline API?

Thanks

**Comment by shauheen** [comment]
Hi, There are a few tests [here](https://github.com/dotnet/machinelearning/blob/master/test/Microsoft.ML.Predictor.Tests/TestAutoInference.cs) that might give you some ideas, however in the 0.4 release I expect that the API will be changed significantly. We will have more docs and samples added once the new proposed API gets implemented. (#371 for some details).
@OliaG it would be great to have examples for sweeping in the [samples](https://github.com/dotnet/machinelearning-samples) repo.

**Comment by codemzs** [comment]
Seems like Shauheen has already pointed out some examples and in the coming months we will see AutoML code in the master branch with samples in the samples project.
