### ISSUE TITLE
Please do an example

### ISSUE THREAD

**Issue by CBrauer** [dotnet/machinelearning#4165]
Please do an example of how the probability is computed and used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79a06280-21c8-0ae1-c5d0-17ef5d8d6774
* Version Independent ID: 4047f033-7557-9533-7626-2c8aeafce38b
* Content: [DatasetUtils.CalibratedBinaryClassifierOutput.Probability Field (Microsoft.ML.SamplesUtils)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.samplesutils.datasetutils.calibratedbinaryclassifieroutput.probability?view=ml-dotnet-preview)
* Content Source: [dotnet/xml/Microsoft.ML.SamplesUtils/DatasetUtils+CalibratedBinaryClassifierOutput.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.SamplesUtils/DatasetUtils+CalibratedBinaryClassifierOutput.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by bpstark** [comment]
Please take a look at the existing samples here:
https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/Calibrators/Platt.cs
https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/FastTree.cs
