### ISSUE TITLE
[Image Classification DNN Transfer Learning] - Use PredictedLabel as String/Value instead of an UInt32 (Index))

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning#4169]
I think it'd be simpler for users and also consistent with other ML.NET APIs if the returned PredictedLabel is a string/value (categorial value) instead UInt32 (Index).

That way, simply by having a .MapKeyToValue() at the end of the pipeline, the user will have it as the value being looked for instead of an index which is what we currently get:

```
//pipeline code
.Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName: "Label" , inputColumnName: "LabelAsKey"));
```

As currently implemented, when the user is simply predicting in an end-user app, you need to find out the real label value by using code based on the schema API, like this:

```
var prediction = predictionEngine.Predict(imageToPredict);

var index = prediction.PredictedLabel;

// Obtain the original label names to map through the predicted label-index
VBuffer<ReadOnlyMemory<char>> keys = default;
predictionEngine.OutputSchema["LabelAsKey"].GetKeyValues(ref keys);
var originalLabels = keys.DenseValues().ToArray();

Console.WriteLine($"ImageFile : [{Path.GetFileName(imageToPredict.ImagePath)}], " +
                    $"Scores : [{string.Join(",", prediction.Score)}], " +
                    $"Predicted Label : {originalLabels[index]}");
```

If the PredictedLabel was already the string/value, the user won't usually need to use the additional `VBuffer `and `OutputSchema `APIs above.

Also, this way would be consistent with other multi-class classification algorithms in ML.NET.

**Comment by codemzs** [comment]
@harshithapv is working on this.
