### ISSUE TITLE
TfIdf setting in ProduceNGrams throws Exception

### ISSUE THREAD

**Issue by larsbeck** [dotnet/machinelearning#4178]
### System information

- **OS version/distro**: Windows 10 Pro
- **.NET Version (eg., dotnet --info)**: 3.0.0-preview8-28405-07

### Issue
ProduceNGrams throws an InvalidOperationException "The specified documents are all empty in column 'Tokens'"

- **What did you do?**
Changed the parameter setting 'weighting' of type 'WeightingCriteria' from the standard 'WeightingCriteria.Tf' to 'WeightingCriteria.TfIdf' and then ran the code again.

- **What happened?**
The exception gets thrown as described above

- **What did you expect?**
The code, specifically the line 'var transformer = pipeline.Fit(dataview);' to run just as it did with setting WeightingCriteria.Tf.

### Source code / logs

```
var pipeline = _mlContext.Transforms.Text.NormalizeText(nameof(TransformedTextData.NormalizedText),
                nameof(Profile.Text))
                .Append(_mlContext.Transforms.Text.TokenizeIntoWords(nameof(TransformedTextData.Words),
                    nameof(TransformedTextData.NormalizedText)))
                .Append(_mlContext.Transforms.Text.RemoveDefaultStopWords(nameof(TransformedTextData.Words), nameof(TransformedTextData.Words), StopWordsRemovingEstimator.Language.German))
                .Append(_mlContext.Transforms.Text.RemoveStopWords(nameof(TransformedTextData.Words), null, "kontext", "&"))
                .Append(_mlContext.Transforms.Conversion.MapValueToKey(nameof(TransformedTextData.Tokens), nameof(TransformedTextData.Words)))
                .Append(_mlContext.Transforms.Text.ProduceNgrams(nameof(TransformedTextData.Tokens), weighting: NgramExtractingEstimator.WeightingCriteria.TfIdf))
                .Append(_mlContext.Transforms.Text.LatentDirichletAllocation(
                    nameof(TransformedTextData.Features), nameof(TransformedTextData.Tokens), numberOfTopics: 10, numberOfSummaryTermsPerTopic:10));

            // Fit to data.
            var transformer = pipeline.Fit(dataview);
```

Does ProduceNGrams not support the setting TfIdf as weighting? If it doesn't, which Transformer would one use to generate NGrams for LatentDirichletAllocation ?

**Comment by yaeldekel** [comment]
Hi @larsbeck, thank you for your question. The `ProduceNGrams` estimator does support TfIdf, but the `LatentDirichletAllocation` estimator doesn't. It uses the term frequencies as inputs. The exception you got is thrown when the LDA estimator checks to make sure that its input values are integers (I agree the error message can be improved).

**Comment by larsbeck** [comment]
Excellent, thanks for the explanation!

**Comment by larsbeck** [comment]
@yaeldekel Just a quick follow up question. Now that I think about it, I believe we might be able to feed LDA better "term frequencies", by scaling TfIdf frequencies normalized to integers. Their meaning might be better, maybe. If I understand the pipelines correctly, we' have to write our own transformer and possibly estimator to do such scaling. I couldn't find any good resource on how to implement your own ITransformer other than checking out the source code. Are there any HowTos on this topic that I didn't see?
