### ISSUE TITLE
Checkpoint method should be renamed to SaveCheckpoint

### ISSUE THREAD

**Issue by nicolehaugen** [dotnet/machinelearning#4185]
ML.NET 1.3

When working with Time Series\SSA Forecasting, the method that is used for saving a model is called "Checkpoint":

```Csharp
forecastEngine.CheckPoint(mlContext, outputModelPath);
```

Instead, this method would be more intuitive if it were named according to a verb\action - such as SaveCheckpoint().

Note that this is also feedback from Cesar.

**Comment by codemzs** [comment]
Thanks @nicolehaugen unfortunately it is already part of the release package and renaming it would be considered as breaking change but I agree with you that having a verb like "save" would have been better.
