### ISSUE TITLE
App Store

### ISSUE THREAD

**Issue by OmarJay1** [dotnet/machinelearning#4203]
Hello, I'm wondering if there's any intention of ML.NET working in Microsoft app store apps. I'm getting this error message when I run the App Cert Kit.

I believe that these DLLs have to do with ML.NET because the error goes away when I don't use ML.NET.  Thanks.

      <MESSAGES>
          <MESSAGE TEXT="File C:\Program Files\WindowsApps\AppName\CpuMathNative.dll has failed the AppContainerCheck check." />
          <MESSAGE TEXT="File C:\Program Files\WindowsApps\AppName\LdaNative.dll has failed the AppContainerCheck check." />
        </MESSAGES>

**Comment by CESARDELATORRE** [comment]
Do you mean UWP apps right? - Currently UWP is not officially supported in ML.NET, although you can run an UWP app in debugging mode under certain context. 

See this sample UWP/Store app using ML.NET, though:
https://github.com/XamlBrewer/UWP-MachineLearning-Sample 
(However, deployment to the Windows Store as native compilation won't probably be possible currently).

See the following related issues:
- https://github.com/dotnet/machinelearning/issues/2252
- https://github.com/dotnet/machinelearning/issues/2444

Feel free to provide further feedback about your scenario and why you think UWP support is important for you so it can influence our priorities in the roadmap, ok? 👍

**Comment by OmarJay1** [comment]
Yes, I was attempting to certify a UWP app.  There was a security issue that I imagine won't be an issue in a non-UWP desktop app. I'll try it on non-UWP.  Thanks.

    <REQUIREMENT NUMBER="14" TITLE="Windows security features test" RATIONALE="Applications must opt-into Windows security features.">
      <TEST INDEX="33" NAME="Binary analyzer" DESCRIPTION="Analysis of security features enabled on binaries" EXECUTIONTIME="00h:00m:01s.85ms" OPTIONAL="FALSE">
