### ISSUE TITLE
Graphs/Plots of Evaluation Metrics

### ISSUE THREAD

**Issue by aslotte** [dotnet/machinelearning#4206]
It would be beneficial to have some kind of plotting mechanism of sorts to display evaluation metrics after training.

- Confusion matrix
- ROC graph
- Precision-recall graph

It would also be neat to have a default ToString() method to output the metrics object to the console.

**Comment by aslotte** [comment]
@CESARDELATORRE - this made my day, thank you for sharing! :)

**Comment by harishsk** [comment]
@aslotte I am hoping your question has been answered. I am closing the issue. Please reopen if you need more investigation from our end.
