### ISSUE TITLE
Summary Statistics

### ISSUE THREAD

**Issue by aslotte** [dotnet/machinelearning#4207]
It would be great to have the possibility to add a data exploration API to quickly get a feel of the data, e.g.

- Shape of the date
- Do we have NaNs etc.
- How balanced is the data?

This can certainly be done through LinQ queries on the IDataView I'm sure, but would be cool to wrap some common methods as an extension method on the IDataView

**Comment by codemzs** [comment]
@aslotte The Shape of the data can be inferred by the schema of the DataView, for NaNs you can simple iterate over the DataView and count. We don't have anything as such for showing how balanced the dataset is but some of our  trainers like FastTree and LightGBM have option to take care with unbalanced datasets.
