### ISSUE TITLE
Question: Roadmap for JupyterNotebook + ML.NET

### ISSUE THREAD

**Issue by aslotte** [dotnet/machinelearning#4208]
This is a question/enhancement suggestion.

As there is now support for transfer learning of DNN's, that means training has become a lot more computational expensive. This may push users to have to provision a VM in Azure or other to be able to train their deep neural networks. 

**Question**: How does the road map look for adding support for ML.NET in a Jupyter Notebook? 
I know there is a C# kernel available to install, is it possible to use that in Azure Machine Learning Service? It would be neat to be able to run ML.NET in a Jupyter Notebook as we then can quickly provision a compute resource required. That would also open up the path to additional summary statistics and plotting etc. 

**If** Jupyter Notebooks are not in the plans, are there plans of creating a VM image or suggest other ways of training a deep neural network in ML.NET in the cloud, in case a user does not have a strong enough computer locally?

**Comment by eerhardt** [comment]
@aslotte - great question!

We are actively working on creating a notebook story for .NET. Check out https://github.com/dotnet/try/issues/408. The current notebook + ML.NET experience works for a few primitive scenarios, but there are a few things we need to fix before we broadly advertise it for people to use. You can try it today and give feedback by following the steps described in that link.

> That would also open up the path to additional summary statistics and plotting etc.

We've been prototyping with using [XPlot](http://github.com/fslaborg/XPlot) to show charts/graphs/plots in our current notebook experience. We have something like this working:

![image](https://user-images.githubusercontent.com/8291187/63031954-8b11d500-be7a-11e9-90eb-2f4c46ae0a03.png)

There are other .NET libraries that can be used for plotting as well. A great thing about the notebook experience we are building is that it allows for extensions to be loaded, which will enable other charting libraries to be able to be displayed inline, like we enabled with XPlot above.

/cc @jonsequitur @colombod @CESARDELATORRE @LadyNaggaga

**Comment by geffzhang** [comment]
SciSharp Stack already has a Jupyter book https://github.com/SciSharp/SciSharpCube

**Comment by eerhardt** [comment]
Correct. I proposed combining efforts between both notebook projects here: https://github.com/SciSharp/Plot.NET/issues/1#issuecomment-521286148. 
IMO - it would be great to create one great notebook experience instead of a few different ones. 

/cc @kerryjiang

**Comment by eerhardt** [comment]
Checkout https://github.com/dotnet/try/blob/master/NotebookExamples/csharp/Samples/HousingML.ipynb for an example of using ML.NET in a Jupyter Notebook, and some example plots.

https://github.com/dotnet/try/issues/408 has the instructions for how to install this experimental Jupyter kernel locally.

Closing as I believe this question has been answered.
