### ISSUE TITLE
exampleWeightColumn with separate weights for each feature

### ISSUE THREAD

**Issue by FedericoBinda** [dotnet/machinelearning#4217]
Hi

I have a model with 2 features. In my data, each of these features is a measurement with an uncertainty associated to it. I was hoping to be able to set the weights column so that each feature has its own weight based on the uncertainty, but it does not seem possible, since only 1 weight per data point is allowed. Is this something that could be possibly implemented?

**Comment by frank-dong-ms** [comment]
Hi,

This will not be supported in near future but we will definitely put this into our backlog, thanks.
