### ISSUE TITLE
ML.Net Source not building when build.cmd is executed

### ISSUE THREAD

**Issue by mohsinnasir** [dotnet/machinelearning#4221]
### System information

- **OS version/distro**:Windows 10
- **.NET Version (eg., dotnet --info)**: 3.0 Preview

### Issue

- **What did you do?**
Run Build.cmd
- **What happened?**
D:\SCM\machinelearning\src\Native>build.cmd
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.2.2
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86_x64'
Commencing native build of dotnet/machinelearning

Calling "D:\SCM\machinelearning\src\Native\\gen-buildsys-win.bat" "D:\SCM\machinelearning\src\Native\" "16 2019" x64
CMake Error: The source directory "D:/SCM/machinelearning/bin/obj/x64.Debug/Native/2019  -A x64 -B./ -HD:/SCM/machinelearning/src/Native"" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Failed to generate native component build project!
- **What did you expect?**
Successful completion of build

### Source code / log
Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by eerhardt** [comment]
Have you followed all instructions on https://github.com/dotnet/machinelearning/blob/master/docs/building/windows-instructions.md?

Also, after pulling the repo, did you initialize the submodule? `git submodule init`

**Comment by eerhardt** [comment]
Closing since we haven't received a response. Please ensure you have all the necessary things installed per the above instructions. Feel free to re-open if you have more information to help diagnose the issue.
