### ISSUE TITLE
Predict multiple rows

### ISSUE THREAD

**Issue by zHaytam** [dotnet/machinelearning#4222]
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: 3.0.100-preview9-014004

### Issue

- **What did you do?** Trained a simple K-Means model
- **What happened?** I wanted to predict multiple rows, but `Predict` only takes 1 instance
- **What did you expect?** An overload that gives this possiblity

### Source code / logs

```csharp
var pipeline = ...;
var model = pipeline.Fit(data);
var predictor = mlContext.Model.CreatePredictionEngine<PixelEntry, ClusterPrediction>(model);
```

**Comment by luisquintanilla** [comment]
Hi @zHaytam ,

Try using the `Transform` method.

API Docs:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.itransformer.transform?view=ml-dotnet#Microsoft_ML_ITransformer_Transform_Microsoft_ML_IDataView_

Example: 
https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/machine-learning-model-predictions-ml-net#batch-prediction

**Comment by codemzs** [comment]
@luisquintanilla  is correct. ITransformer.Transform(IDataView) is for batch predictions.
