### ISSUE TITLE
Error when retraining model

### ISSUE THREAD

**Issue by jwood803** [dotnet/machinelearning#4230]
### System information

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  2.2.101 [C:\Program Files\dotnet\sdk]
  3.0.100-alpha1-009632 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]

### Issue

- **What did you do?**
Attempted to retrain a linear regression model built in ML.NET
- **What happened?**
Received the below error:
```
Optimizer unable to proceed with loss function yielding Infinity
```

### Source code / logs
Error occurred on the below code:
```
var retrainedModel = context.Regression.Trainers.LbfgsPoissonRegression()
                .Fit(newDataTransformed, originalModelParams);
```

Full code sample is [here](https://github.com/jwood803/MLNetExamples/blob/master/MLNetExamples/RetrainModel/Program.cs).

**Comment by eerhardt** [comment]
@codemzs @yaeldekel @harishsk @ganik - any thoughts?

**Comment by bpstark** [comment]
@jwood803 I believe I have found the cause of this issue. It appears that you have a typo in your reading of the retraining data. Please take a look [here](https://github.com/jwood803/MLNetExamples/blob/master/MLNetExamples/RetrainModel/Program.cs#L67). You can see that you accidentally use 4 twice, which throws off the values for all columns after TotalBedrooms. This causes the Fit to fail as the values to not make sense in the new context. Once I corrected all of the numbers to be the correct column, I was able to fit the data fine.

Please let me know if this fixes your issue, and if so can you please close out the issue.

Thanks

**Comment by jwood803** [comment]
Thanks a lot @bpstark! I am dumb and just completely missed that issue! Thank you again for catching it. I fixed it and all looks good.
