### ISSUE TITLE
How to Draw Auto ML Statisctics Graph using XPlot.Plotly library in c#

### ISSUE THREAD

**Issue by nighotatul** [dotnet/machinelearning#4238]
Hi 

We are using AutoML tool

As we got statistics of binary classification of

AUC
Confusion Matrix
Roc

How we can draw the graph based on Matrix by using XPlot.plotly library in C#

we are not found any example in github in ML.net repository

Please provide sample

**Comment by eerhardt** [comment]
@nighotatul - check out https://github.com/dotnet/try/blob/master/NotebookExamples/csharp/Samples/HousingML.ipynb, which gives a nice "getting started" example of doing an ML experiment using AutoML in a notebook, and does some plotting. Specifically it is plotting a scatter graph with `RuntimeInSeconds` plotted against `MeanAbsoluteError`. But you should be able to modify it to graph whatever you'd like.

```C#
var mlContext = new MLContext();

var experiment = mlContext.Auto().CreateRegressionExperiment(maxExperimentTimeInSeconds: 15);
var result = experiment.Execute(housing_train, labelColumnName:"median_house_value");
```

```C#

var scatters = result.RunDetails.Where(d => d.ValidationMetrics != null).GroupBy(    
    r => r.TrainerName,
    (name, details) => new Graph.Scatter()
    {
        name = name,
        x = details.Select(r => r.RuntimeInSeconds),
        y = details.Select(r => r.ValidationMetrics.MeanAbsoluteError),
        mode = "markers",
        marker = new Graph.Marker() { size = 12 }
    });

var chart = Chart.Plot(scatters);
chart.WithXTitle("Training Time");
chart.WithYTitle("Error");
display(chart);
```

![image](https://user-images.githubusercontent.com/8291187/65718597-7c1d6580-e069-11e9-8352-67e79697841f.png)
