### ISSUE TITLE
ML.NET support in Azure Machine Learning Service

### ISSUE THREAD

**Issue by aslotte** [dotnet/machinelearning#4243]
First of all, big thanks for the initial support of ML.NET in Jupyter Notebooks. It's a fantastic addition.

Based on this, I'm wondering if, when and how it will be possible to install the .NET kernel in Azure Machine Learning Service to be able to take full advantage of the cloud?

**Comment by CESARDELATORRE** [comment]
@aslotte - Thanks for the feedback. We're still in experimental and early previews of the .NET kernel for Jupyter. 
Along with many other ML.NET integrations with Azure ML this will be something in the plan. 
Like I mentioned, it is early to say when it'll be directly supported by Azure ML. 
right now we're in a preview/experimental phase for Jupyter+.NET+ML.NET where we'd love to get feedback that will influence the way we'll shape it.
Thanks for the feedback! 👍

**Comment by aslotte** [comment]
Thanks @CESARDELATORRE - that makes total sense, just wanted to see if it was in the road map! :) I'm leading a full day workshop on ML.NET in October, and I'm planning on incorporating some Jupyter + ML.NET in there. I'll be happy to provide any feedback that I may get from participants!
