### ISSUE TITLE
Jupyter + ML.NET | DataFrame | Create a ToOutputFormat() function to output HTML table

### ISSUE THREAD

**Issue by aslotte** [dotnet/machinelearning#4249]
Registering the format of a DataFrame is currently a large code block that takes away from the ML problem we're trying to solve in the Notebook. 

What about creating a ToString() or ToOutputFormat() method that outputs the default table format which I believe most people would like to have from start.

**Comment by CESARDELATORRE** [comment]
We're working on that. Do you mean like the following? :)

![image](https://user-images.githubusercontent.com/1712635/65708189-d9ea8700-e042-11e9-842d-981d390b455a.png)

**Comment by aslotte** [comment]
Yes! Even better 👍
