### ISSUE TITLE
Jupyter + ML.NET | DataFrame | Identical to Pandas or more C# like?

### ISSUE THREAD

**Issue by aslotte** [dotnet/machinelearning#4250]
The DataFrame class currently bears a lot of resembles with the Python equivalent of Pandas. 

As I don't have any API documentation in front of me, it's difficult to know the answer to this, so I thought I would ask, are there any efforts to make it more "C# like"?

E.g., I would like to do the following for example:
```
var allFraudulentRowsByTransactionDate = dataFrame.Where(x => x.IsFraud).OrderBy(y => y.TransactionDate);
```

**or** 
```
var first10Rows = dataFrame.Take(10);
var first10Percent = dataFrame.Take(dataFrame.Count() * 0.1);
```
**or** 

```
var amountColumnForOnlyFraudulentCases = dataFrame.Where(y => y.IsFraud).Select(x => x.Amount);
```

**Comment by eerhardt** [comment]
The intention of the DataFrame library is to cover the main use cases that Pandas covers in Python, but with 2 big differences:

1. Have a .NET friendly API 
    - conforming to the [framework design guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/)
    - feel natural to .NET developers.
2. Be backed by an [Apache Arrow](https://arrow.apache.org) conforming memory layout.
    - columnar layout allows for SIMD operations
    - allow for zero copy read semantics with other systems that consume and produce Arrow data.

If you have specific feedback on the DataFrame library, feel free to open issues, API suggestions, or just general comments at https://github.com/dotnet/corefxlab, where the library lives. The library is still in "prototype" phase and hasn't been exercised much yet, so we'd love to get some real customer usage. Feedback now will really help shape where this library will go, so we are looking forward to receiving it.
Also, if anyone is interested in adding features, fixing bugs, etc. we would gladly accept PRs as well.

/cc @pgovind

**Comment by CESARDELATORRE** [comment]
The idea of DataFrame is precisely to be similar to the DataFrame in Pandas and the goal is to be able to access/preview data in a very straightforward and simple way, even without needing to declare/define a DataInput class matching the dataset columns.

Something like what you say would be probably IEnumerable precisely?
The line below that you mentioned is pretty much what IEnumerable supports.

`var allFraudulentRowsByTransactionDate = dataFrame.Where(x => x.IsFraud).OrderBy(y => y.TransactionDate);`

You can also use IEnumerable in C# and then finally load the IDataView from the IEnumerable with the .LoadFromEnumerable() API in ML.NET. 

Are you looking to have something like DataFrame+IEnumerable, perhaps?

**Comment by codemzs** [comment]
This issue seems to already have been answered but please feel free to reopen if needed.
