### ISSUE TITLE
Jupyter + ML.NET | Plotly

### ISSUE THREAD

**Issue by aslotte** [dotnet/machinelearning#4251]
This may not be the correct forum for this question, and if not, I'm happy to close it.

Plotly created very large graphs, greatly slowing down the browser, especially compared to it's Python counterparts. I created a simple Scatter plot based on a dataset of 30 Mb, and Google Chrome almost completely came to a halt. I've created similar plots in Python equivalents for 500+ Mb of data with the browser running smoothly. 

This means that XPlot.Plotly will not be a feasible option for any real-life datasets. Are there any other alternatives for the .NET community that we can recommend? Or should I reach out to Plotly to see if this is just a bug?

**Comment by CESARDELATORRE** [comment]
It'd be great if you can reach Plotly in parallel.
But this is great feedback. We should consider multiple options for plotting. 👍

**Comment by aslotte** [comment]
Will do, I'll add an issue in the Plotly Github repo. Would you know if there are any C# API docs for Plotly? So far I've only found them for F#

**Comment by CESARDELATORRE** [comment]
@eerhardt @jonsequitur Any observation on this issue related to lack of performance of XPlot using Plotly when plotting a significant data? - Comparable data could be plotted without issues with Python counterparts.

**Comment by eerhardt** [comment]
@colombod let me in on the secret: WebGL.

See https://plot.ly/python/webgl-vs-svg/

> Implement WebGL for increased speed, improved interactivity, and the ability to plot even more data!

In XPlot, certain charts have a `gl` suffix overload that will use WebGL instead of SVG.

I have updated the example notebook in dotnet/try to use `Scattergl` and the performance is now much better - https://github.com/dotnet/try/pull/496.

**Comment by aslotte** [comment]
Thanks for looking in to this @eerhardt!

**Comment by eerhardt** [comment]
No problem. I hope this helps unblock you.

Feel free to open issues like this directly in the XPlot repo (https://github.com/fslaborg/XPlot). Or if it is an issue with the C#/F# Jupyter kernel - .NET Try repo (https://github.com/dotnet/try).

ML.NET can't really do anything for issues like this.

Closing as this question was answered.
