### ISSUE TITLE
Incorrect constructor parameter type specified

### ISSUE THREAD

**Issue by IgnasZ** [dotnet/machinelearning#4256]
Constructor parameter 'columns' should be of type IEnumerable&lt;SchemaShape.Column&gt; instead of IEnumerable&lt;SchemaShape&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52902231-74e7-53a0-1974-ab96d7963da1
* Version Independent ID: ebf148b4-3861-d68a-33ca-f12d59e6e3ee
* Content: [SchemaShape Class (Microsoft.ML)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.schemashape?view=ml-dotnet#feedback)
* Content Source: [dotnet/xml/Microsoft.ML/SchemaShape.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML/SchemaShape.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by najeeb-kazmi** [comment]
@IgnasZ thanks for reporting this to us. We have fixed this in the docs.
