### ISSUE TITLE
What is the input format required by the LDA transform?

### ISSUE THREAD

**Issue by fwaris** [dotnet/machinelearning#4257]
Ideally I would like the output of ApplyWordEmbedding transform as input to LDA for topic modeling but apparently that is not the case.

So I am not sure how to format the input to LDA.

Documentation says it should be a vector of single - which it is with after applying the embedding transform but then I see an error message when running LDA:

The specified documents are all empty in column 'Features'.

Where "Features" is the output of the embedding.

**Comment by yaeldekel** [comment]
Hi @fwaris, thank you for opening this issue. The LDA transformer in ML.NET can be applied to the output of n-gram transformer, or bag of words (so even though the input is a vector of floats, it checks that the values are integers). Please see this related issue: #4178.

**Comment by antoniovs1029** [comment]
Since it seems this was answered, I am going to close it.
