### ISSUE TITLE
how we plot decision tree using fast tree Trainer?

### ISSUE THREAD

**Issue by nighotatul** [dotnet/machinelearning#4264]
@eerhardt -  we got score and metrics but how we plot decision tree using trainer.

**Comment by eerhardt** [comment]
I'm not sure what you are asking for here. LbfgsLogisticRegression is not a tree based algorithm. It uses logistic regression to make classifications.

In general, if you want to get the underlying information about a model, you use the `Model` property on the transformer that is returned from fitting a trainer.

```C#
// Define the trainer.
var pipeline = mlContext.BinaryClassification.Trainers.LbfgsLogisticRegression();

// Train the model.
var transformer = pipeline.Fit(trainingData);
IReadOnlyList<float> weights = transformer.Model.SubModel.Weights;
float bias = transformer.Model.SubModel.Bias;
```

These weights and bias numbers are what is used to make the decision in `LbfgsLogisticRegression`.

**Comment by nighotatul** [comment]
@eerhardt - i have prepared sample on this below link.
this is Visualize sickit-learn decision trees with d3.js
http://bl.ocks.org/fractalytics/raw/495b63cf671b4c487bc40801366384e0/

we do not know python script but we know C#. so that please helps us to draw above tree using ml.net using score,weights,bias.
if any sample is their please share with us.

**Comment by eerhardt** [comment]
So the part that still confuses me is that you are explicitly asking about `LbfgsLogisticRegression`, which is not a tree-based algorithm. So there is no way to create a tree structure like your example shows.

The way logistic regression works is it takes the `weights` from above, and multiplies them by the values being entered as the input, plus some `bias`. If that resulting number is greater than some threshold (like `0.5`), then it predicts `true`, if the result is less it predicts `false`.

Are you asking how to create a graphical representation of a tree using C#? Or are you specifically asking how to make a decision-tree out of a LbfgsLogisticRegression model?

If your question is the latter, I don't know. Like I said, LbfgsLogisticRegression isn't a tree-based algorithm. You would need to use a decision-tree algorithm (like LightGbm or FastTree) to get that information.

**Comment by nighotatul** [comment]
@eerhardt - Sorry for that confusion,then how we get visualization using fast tree algorithm?

**Comment by eerhardt** [comment]
To get the tree data from a decision-tree model you can use the `.Model` property on the Transformer. From there, you can grab `.TrainedTreeEnsemble` which has all the tree data.

![image](https://user-images.githubusercontent.com/8291187/65922364-a4c79700-e3aa-11e9-896c-e42655f999ce.png)

How to actually use that data to visualize the tree is beyond my knowledge. Maybe @codemzs, @ganik, or @yaeldekel can answer that question.

**Comment by nighotatul** [comment]
@yaeldekel -  i have prepared sample on this below link.
this is Visualize sickit-learn decision trees with d3.js
http://bl.ocks.org/fractalytics/raw/495b63cf671b4c487bc40801366384e0/

we do not know python script but we know C#. so that please helps us to draw above tree using ml.net using score,weights,bias.
if any sample is their please share with us.

**Comment by eerhardt** [comment]
Closing in favor of #4275.
