### ISSUE TITLE
we are getting more thane one score in spam detection?

### ISSUE THREAD

**Issue by nighotatul** [dotnet/machinelearning#4280]
@eerhardt - please see this code,

 var dataProcessPipeline = context.Transforms.Conversion.MapValueToKey("Label", "Label")
                                                  .Append(context.Transforms.Text.FeaturizeText("FeaturesText", new Microsoft.ML.Transforms.Text.TextFeaturizingEstimator.Options
                                                  {
                                                      WordFeatureExtractor = new Microsoft.ML.Transforms.Text.WordBagEstimator.Options { NgramLength = 2, UseAllLengths = true },
                                                      CharFeatureExtractor = new Microsoft.ML.Transforms.Text.WordBagEstimator.Options { NgramLength = 3, UseAllLengths = false },
                                                  }, "Message"))
                                                  .Append(context.Transforms.CopyColumns("Features", "FeaturesText"))
                                                  .Append(context.Transforms.NormalizeLpNorm("Features", "Features"))
                                                  .AppendCacheCheckpoint(context);

                        // Set the training algorithm 
                        var trainer = context.MulticlassClassification.Trainers.OneVersusAll(context.BinaryClassification.Trainers.AveragedPerceptron(labelColumnName: "Label", numberOfIterations: 10, featureColumnName: "Features"), labelColumnName: "Label")
                                                  .Append(context.Transforms.Conversion.MapKeyToValue("PredictedLabel", "PredictedLabel"));
                        var trainingPipeLine = dataProcessPipeline.Append(trainer);

                        //Console.WriteLine("=============== Cross-validating to get model's accuracy metrics ===============");
                        //var crossValidationResults = mlContext.MulticlassClassification.CrossValidate(data: data, estimator: trainingPipeLine, numberOfFolds: 5);
                        //ConsoleHelper.PrintMulticlassClassificationFoldsAverageMetrics(trainer.ToString(), crossValidationResults);

                        // Now let's train a model on the full dataset to help us get better results
                        var model = trainingPipeLine.Fit(trainData);

                        IDataView predictions = model.Transform(trainData);

                        List<SpamPrediction> predictedResults = context.Data.CreateEnumerable<SpamPrediction>(predictions, reuseRowObject: false).ToList();

we attached data also. then which one score we consider?
[spamdata.xlsx](https://github.com/dotnet/machinelearning/files/3686067/spamdata.xlsx)

**Comment by eerhardt** [comment]
> var trainer = context.MulticlassClassification.Trainers.OneVersusAll(context.BinaryClassification.Trainers.AveragedPerceptron(

Why are you using MulticlassClassification? This is for when you have more than 2 classes. But spam detection only has 2 classes, correct? Spam or not. You should use BinaryClassification.

**Comment by nighotatul** [comment]
@eerhardt 

if MulticlassClassification we are using for spam then can we calculate average score for that ?

**Comment by nighotatul** [comment]
as we are following ml.net samples and in that samples this process consider for spam

**Comment by eerhardt** [comment]
@CESARDELATORRE - can you answer the question? Why are we using MulticlassClassification in the [Spam Detection](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/BinaryClassification_SpamDetection) sample?

**Comment by CESARDELATORRE** [comment]
@eerhardt - I'm not sure the original reason, that sample was created by Gal. 
But the important point is the accuracy you get. Sometimes a multi-class trainer could have better accuracy and can be used for binary-classification, too.

**Comment by CESARDELATORRE** [comment]
As per Justin's comment:

You might be likely seeing the Scores column.

You should be looking at the `PredictedLabel `column using the `mlContext.Transforms.Conversion.MapKeyToValue` to convert from the Key type to the original Label values.

    The `Score `column lists the score for each class. In a binary problem run as multi-class (which is perfectly ok), there will be two scores, but the `PredictedLabel `column will tell you which is the prediction.

**Comment by yaeldekel** [comment]
Hi @nighotatul ,
Does @CESARDELATORRE 's comment answer your question?
I am closing the issue, if you are still experiencing problems, please feel free to re-open it or open a new issue.
