### ISSUE TITLE
after every execution recommendation result is continuously changes?

### ISSUE THREAD

**Issue by nighotatul** [dotnet/machinelearning#4281]
@eerhardt - after every execution of following code for Periodofstay-"Mar-May" and
traveler_type-"Families",recommendation result i.e. Score continuously changes.we need constant result not every time change score.

 var options = new Microsoft.ML.Trainers.FieldAwareFactorizationMachineTrainer.Options
                        {
                            // MatrixColumnIndexColumnName = "userIdEncoded",
                            // MatrixRowIndexColumnName = "movieIdEncoded",
                            FeatureColumnName = "Features",

                            NormalizeFeatures = false,
                            LabelColumnName ="Label",// labelColumnName,
                            LambdaLatent = 0.01f,
                            LambdaLinear = 0.001f,
                            LatentDimension = 16,
                            NumberOfIterations = 20,
                            LearningRate = 0.5f

                            // ApproximationRank = 100
                        };

                        //  context.ml.Trainers.MatrixFactorization(options);

                        // columnNames, columnTypes
                        IEstimator<ITransformer> datapipeLine = context.Transforms.CopyColumns(
                                       inputColumnName: labelColumnName,
                                       outputColumnName: "Label");
                        //                context.Transforms.Categorical.OneHotEncoding("TravelerTypeOneHot", "TravelerType")
                        //.Append(context.Transforms.Categorical.OneHotEncoding("HotelOneHot", "Hotel"))
                        //.Append(context.Transforms.Concatenate("Features", "TravelerTypeOneHot", "HotelOneHot"))
                        //.Append(context.BinaryClassification.Trainers.FieldAwareFactorizationMachine(new string[] { "Features" }));

                        List<string> featuresColumns = new List<string>();

                        for (int index = 0; index < columnNames.Count; ++index)
                        {

                            if (columnNames[index] == labelColumnName|| columnNames[index]=="Time"|| columnNames[index]=="TimeStamp"|| columnNames[index]== "IdPreservationColumn")
                                continue;

                            Type type = columnTypes[index];

                            if (type == typeof(string) || type == typeof(char) || type == typeof(byte[]) || type == typeof(bool))
                            {

                                if (datapipeLine == null)
                                {

                                    datapipeLine = context.Transforms.Categorical.OneHotEncoding(columnNames[index] + "OneHot", columnNames[index]);//"TravelerType"

                                }
                                else
                                {
                                    datapipeLine = datapipeLine.Append(context.Transforms.Categorical.OneHotEncoding(columnNames[index] + "OneHot", columnNames[index]));//"TravelerType"

                                }

                                featuresColumns.Add(columnNames[index] + "OneHot");
                            }
                            else
                            {
                                featuresColumns.Add(columnNames[index]);

                            }

                        }

                        datapipeLine = datapipeLine.Append(context.Transforms.Concatenate("Features", featuresColumns.ToArray()));
                        datapipeLine = datapipeLine.Append(context.BinaryClassification.Trainers.FieldAwareFactorizationMachine(options));// new string[] { "Features" }, labelColumnName));

                        //        foreach (string name in columnNames)
                        //{
                        //    if(columnTypes)
                        //    pipeline = context.Transforms.Categorical.OneHotEncoding("TravelerTypeOneHot", "TravelerType")

                        //}

                        //var pipeline = context.BinaryClassification.Trainers.FieldAwareFactorizationMachine(options);

                        //                    var pipeline = context.Transforms.Categorical.OneHotEncoding("TravelerTypeOneHot", "Traveler_type")
                        ////.Append(context.Transforms.Categorical.OneHotEncoding("SeasonOneHot", "Season"))
                        //.Append(context.Transforms.Categorical.OneHotEncoding("HotelOneHot", "Hotel_name"))
                        //.Append(context.Transforms.Concatenate("Features", "TravelerTypeOneHot", "HotelOneHot"))
                        //.Append(context.BinaryClassification.Trainers.FieldAwareFactorizationMachine(new string[] { "Features" },labelColumnName));

                        //                    var _model = pipeline.Fit(trainData);

                        //                    var _transformedTrainingData = _model.Transform(inputtestData);

                        // Train the model.
                        var model = datapipeLine.Fit(trainData);

                        // Run the model on training or test data set.
                        var transformedTrainingData = model.Transform(trainData);

                        // Measure the quality of the trained model.
                        // var metrics = context.BinaryClassification.Evaluate(transformedTrainingData,);

                        var metrics = context.BinaryClassification.Evaluate(transformedTrainingData,"Label" , "Score", "Probability", "PredictedLabel");//labelColumnName//Prediction Data send

                        //  _predictionEngine = context.Model.pr(FfmRecommendationData, FfmRecommendationPrediction>(_model);

                        var predictions2 = context.Data.CreateEnumerable<RecommendationResult>(transformedTrainingData, reuseRowObject: false).ToArray();

I have attached data also.
[hotelrecommandation.xlsx](https://github.com/dotnet/machinelearning/files/3686131/hotelrecommandation.xlsx)

**Comment by eerhardt** [comment]
@wschin @yaeldekel - can you answer this question?

@nighotatul - the one thing I would check is if you are setting the `seed` when you create your `MLContext`. If you want deterministic results, you need to set the seed for the random number generator used.

**Comment by nighotatul** [comment]
@eerhardt - we change seed value to 1 then fixed result is coming but when we apply to other example as seed is null then also fixed result is coming this strange behaviour.then what is value put for seed in mlcontext to get every example when filter we get fixed result.

**Comment by eerhardt** [comment]
Have you tried setting the `Shuffle` property to `false`?

https://github.com/dotnet/machinelearning/blob/5d90c11bf5d433f539d9c23bb20ebd9cc9cc4b4c/src/Microsoft.ML.StandardTrainers/FactorizationMachine/FactorizationMachineTrainer.cs#L157-L161

This will ensure the training iterations happen in a deterministic manner.

In general though, randomness in machine learning is a good thing. https://machinelearningmastery.com/randomness-in-machine-learning/

**Comment by nighotatul** [comment]
Thanks @eerhardt.
