### ISSUE TITLE
Model Builder | Selecting a file without file type crashes Visual Studio

### ISSUE THREAD

**Issue by aslotte** [dotnet/machinelearning#4287]
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: 

### Issue

- **What did you do?** I downloaded the data for spam detection (ML samples)
- **What happened?** When I opened the Model Builder in Visual studio and selected the training file, Visual Studio hangs and eventually crashes. Setting the file type to .tsv makes it work.
- **What did you expect?** A reasonable error message would be useful, e.g. "Please indicate if this file is tab- or comma-separated"

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by aslotte** [comment]
Same issue if selecting an Excel file. I would recommend to at least put a filter on the browser dialog to limit file options.

**Comment by aslotte** [comment]
I see the same issue occurring for a .csv file.
In this case when I'm trying to upload the `taxi-fare-train.csv` file found in the /machinelearning-samples/datasets folder

**Comment by aslotte** [comment]
This was due to the file being opened in Excel (duh...)
Visual Studio just crashes, and there is no warning message.

**Comment by mstfbl** [comment]
@aslotte It seems like you realized the source of the issue. Please close an issue next time when it no longer is one, thank you!
