### ISSUE TITLE
How do I use the newly added LightGBM classifier?

### ISSUE THREAD

**Issue by vivekpradhan** [dotnet/machinelearning#429]
### System information

.NET Core SDK:
Version: 2.1.301
Commit: 59524873d6

Runtime Environment:
OS Name: ubuntu
OS Version: 16.04

### Issue

- **What did you do?**
Cloned the master. 
Ran ./build.sh

- **What happened?**
The build was successful.

-**My Code**
```
<PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
  <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  <NoWarn>CS0649;CS0168;CS0219</NoWarn>
  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.ML" Version="0.2.0" />
  </ItemGroup>
...
```
I'm using the example on iris with my dataset. My code works with `FastTreeBinaryClassifier`, how do I replace this and use `LightGbmBinaryClassifier`, from the code that I just built.
```
            string dataPath = "../../../data/train.csv";
            string testPath = "../../../data/test.csv";
            pipeline.Add(new TextLoader(dataPath).CreateFrom<IrisData>(separator: ','));
            pipeline.Add(new ColumnConcatenator("Features", "NumericFeatures"));
            pipeline.Add(new FastTreeBinaryClassifier() { NumLeaves = 15, NumTrees = 10, MinDocumentsInLeafs = 100 });

```

**Comment by vivekpradhan** [comment]
A sample for this would be great. But my question is more basic than this. How do I use the code that I just built, since I can't use the nuget package to get LightGBM?

**Comment by codemzs** [comment]
Hi @vivekpradhan,

The below line adds LGBM.
pipeline.Add(new LightGbmBinaryClassifier() { NumLeaves = 5, NumBoostRound = 5, MinDataPerLeaf = 2 });

**Comment by vivekpradhan** [comment]
That worked for me thanks.

@codemzs I have a follow up question. I already knew what were the best params for my model since I was using the command line LightGBM. The parameter names are slightly different in ML.NET LightGBM vs. the command line LightGBM that I was using. Also some params gave me an error when I included them.

```
Program.cs(58,71): error CS0117: 'LightGbmBinaryClassifier' does not contain a definition for 'SubsampleFreq' [/home/vpradhan/Projects/lgbmcs/lgbmcs/lgbmcs.csproj]
Program.cs(58,89): error CS0117: 'LightGbmBinaryClassifier' does not contain a definition for 'FeatureFraction' [/home/vpradhan/Projects/lgbmcs/lgbmcs/lgbmcs.csproj]
Program.cs(58,193): error CS0117: 'LightGbmBinaryClassifier' does not contain a definition for 'MaxDepth' [/home/vpradhan/Projects/lgbmcs/lgbmcs/lgbmcs.csproj]

```

Another issue is that LightGBM command line implementation handles nan values (missing data) gracefully. On ML.NET the text loader seems to be dropping rows that contain nan values. This caused my entire dataset to be dropped since I have nan in every row of my data. 
I worked around this by preprocessing the data to replace all nan values with some numerical value.

**Comment by codemzs** [comment]
@vivekpradhan Its not the text loader that drops rows with missing values but it the Data Preparation step of decision in ML.NET that does that. You can use NAReplace or NAHandle transform in the pipeline to fill in missing values. The parameter list is a little different but if you look at the API XML documentation you will see a link that points to LightGBM parameter list and you will need to use that to specify the parameters. The CSharpAPI also lists every parameter that the trainer takes with documentation. We don't have a plan in the near future to converge the names of the two parameter lists but it will be good to do that at some point.

Parameters names comes from LightGBM library. See https://github.com/Microsoft/LightGBM/blob/master/docs/Parameters.rst.

**Comment by vivekpradhan** [comment]
Okay thanks I'll try that. Great work on adding LightGBM to ML.NET. This saved me from writing a lot of code :)
Should I close this issue now? Or should it be open until you guys decide if you want to add samples/documentation?

**Comment by vivekpradhan** [comment]
Just pinging you all on my question, if you have any insights that would be great.

**Comment by codemzs** [comment]
@vivekpradhan Sorry for the delay. You can instantiate booster parameter by doing

 pipeline.Add(new LightGbmBinaryClassifier() { NumLeaves = 5, NumBoostRound = 5, MinDataPerLeaf = 2, Booster = new GbdtBoosterParameterFunction { UnbalancedSets = true } });

We have three booster functions:
DartBoosterParameterFunction
GbdtBoosterParameterFunction
GossBoosterParameterFunction

[Here](https://github.com/dotnet/machinelearning/blob/5bbf7cf4c5728599d952200b21bdb5953893d3e4/src/Microsoft.ML/CSharpApi.cs#L15995) is the link to booster parameter functions.

**Comment by vivekpradhan** [comment]
This works for me. Thanks.
