### ISSUE TITLE
How to Convert Transform Result into DataTable by dynamically ?

### ISSUE THREAD

**Issue by nighotatul** [dotnet/machinelearning#4295]
@eerhardt - 

IDataView multiclassTransformer = model.Transform(trainTestData.TestSet);

DataViewSchema columns = multiclassTransformer.Schema;

DataViewSchema.Column? columnOrNull = multiclassTransformer.Schema.GetColumnOrNull("Features");
                            VBuffer<ReadOnlyMemory<char>> slotNames = new VBuffer<ReadOnlyMemory<char>>();
                            if (columnOrNull.HasValue)
                                columnOrNull.GetValueOrDefault().GetSlotNames(ref slotNames);

                            IList<string> featurenameCollection= (IList<string>)slotNames.Items(false).Select<KeyValuePair<int, ReadOnlyMemory<char>>, string>((Func<KeyValuePair<int, ReadOnlyMemory<char>>, string>)(kv => kv.Value.ToString())).ToList<string>();

How i can convert the output result into DataTable

As Many of example uses Hardcoded class like below example

public class MultiClassResultPrediction
        {
            // public uint GroupId { get; set; }

            // public uint Label { get; set; }

            // Prediction made by the model that is used to indicate the relative ranking of the candidate search results.
            public float Score { get; set; }

            // Values that are influential in determining the relevance of a data instance. This is a vector that contains concatenated columns from the underlying dataset.
            // public float[] Features { get; set; }
        }

List<MultiClassResultPrediction> predictedResult = context.Data.CreateEnumerable<MultiClassResultPrediction>(predictions, reuseRowObject: false).ToList();

or 

else dynamic class where we can access featurevalues,label values and output result schema
like PredictedLabel,Score
like below example :

where we can return output in web.

       IDictionary<string, object> flexibleJson = new ExpandoObject();
        for (int i = 0; i < length; i++)
        {
           
            flexibleJson.Add(colName, colValue);
        }

        var serialized = JsonConvert.SerializeObject(flexibleJson);

So my concern is how we can convert result into DataTable

is there any way we can achieve the desired result by dynamically into DataTabel?

**Comment by nighotatul** [comment]
or else dynamic class where we can access featurevalues,label values and output result schema
like PredictedLabel,Score

**Comment by nighotatul** [comment]
like below example :
 
where we can return output in web for end user

           IDictionary<string, object> flexibleJson = new ExpandoObject();
            for (int i = 0; i < length; i++)
            {
               
                flexibleJson.Add(colName, colValue);
            }

            var serialized = JsonConvert.SerializeObject(flexibleJson);

**Comment by eerhardt** [comment]
I know of a few ways to accomplish this without requiring a hard-coded class:

1. Use `IDataView` directly. There are a few documents spread around that explain how to do this.
    - https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.idataview?view=ml-dotnet
    - Files starting with `IDataView` in https://github.com/dotnet/machinelearning/tree/master/docs/code.
The general code looks like the Example in the first link. But you can find a great example in our code, which is used by the `IDataView.Preview()` method
https://github.com/dotnet/machinelearning/blob/24f1cca4c58bb7275c97c937edb0c2de5d2d6075/src/Microsoft.ML.Data/DataDebuggerPreview.cs#L28-L60
2. Use the `.GetColumn<T>` method for each column you care about. https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.data.columncursorextensions.getcolumn?view=ml-dotnet. This returns an `IEnumerable<T>`, which contains all the data for the specified column. But here you need to know the `T` type for each column, so you would need to do some generics-gymnastics, or use Reflection.

In the future, I hope to have a utility method that will turn an `IDataView` into a dotnet/corefxlab's `DataFrame` object. (See https://github.com/dotnet/corefxlab/issues/2741). This would make it super easy to consume any `IDataView` in a weakly typed fashion.

**Comment by eerhardt** [comment]
Closing as this question is answered. If you feel it hasn't been answered, please re-open.
