### ISSUE TITLE
DnnCatalog methods should use a public Options class

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#4307]
The two methods in `DnnCatalog`:

https://github.com/dotnet/machinelearning/blob/c9f616fdc5a144250535949fc8c8f9c971cbab88/src/Microsoft.ML.Dnn/DnnCatalog.cs#L49-L63

and

https://github.com/dotnet/machinelearning/blob/c9f616fdc5a144250535949fc8c8f9c971cbab88/src/Microsoft.ML.Dnn/DnnCatalog.cs#L120-L143

have a lot of optional parameters, and users may get confused on which ones are important, and which aren't.

I've seen comments from @terrajobst in the past saying:

> In UX studies we have seen that many developers struggle with methods that have many optional arguments.

In ML.NET, the pattern we have established is that we have 2 overloads:

1. An overload that takes the required parameters, and optionally the most important/common parameters to a method.
2. An overload that takes an `Options` object, which contains all the options to the method - simple and advanced.

We should follow this pattern with these DNN APIs as well. See the discussions and related PRs to https://github.com/dotnet/machinelearning/issues/1798.

/cc @ebarsoumMS @codemzs

**Comment by codemzs** [comment]
@eerhardt We are aware and already tracking this issue and it will be implemented before we go GA.

**Comment by ashbhandare** [comment]
I will be looking into this.

**Comment by codemzs** [comment]
Thanks @ashbhandare
