### ISSUE TITLE
New LightGBM test fails only when running on CI build

### ISSUE THREAD

**Issue by Lynx1820** [dotnet/machinelearning#4309]
### Issue
I tried adding a test case to test RankingEvaluator with Maml using the LightGBMRanking trainer. The testcase passed on my machine and other build configurations. However, it failed on those same configurations on the github build. The testcase was added in response to issue #4081. To unblock me, I used the FastRankRanking trainer instead, which does work as expected.   

### Source code / logs
The test case I added looks like this
```
        public void EvaluateRankingWithMaml()
        {
            string _mslrWeb10k_Train = GetDataPath(TestDatasets.MSLRWeb.trainFilename);
            string extraArgs = " tr=LightGBMRanking" +
                " eval=RankingEvaluator{t=10}" +
                " k=2";
            string loaderArgs = " loader=TextLoader{col=Label:R4:0 col=GroupId:TX:1 col=Features:R4:2-138 header=+}" +
                " xf = HashTransform{col=GroupId}" +
                " xf = NAHandleTransform{col=Features}";
            int digitsOfPrecision = 2;
            TestCore("cv", _mslrWeb10k_Train, loaderArgs, extraArgs, digitsOfPrecision);
            Done();

        }
```

**Comment by codemzs** [comment]
@Lynx1820 were you also planning on investigating this?

**Comment by Lynx1820** [comment]
Closing this issue, as it's not an issue anymore. #5249
