### ISSUE TITLE
What is the default value?

### ISSUE THREAD

**Issue by deiruch** [dotnet/machinelearning#4311]
Knowing the default value of this option would be nice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68ab420f-a92f-61a5-6457-4434ec28fa31
* Version Independent ID: c03e6492-9c30-c2bd-0014-7b9ab590864f
* Content: [MatrixFactorizationTrainer.Options.ApproximationRank Field (Microsoft.ML.Trainers)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.matrixfactorizationtrainer.options.approximationrank?view=ml-dotnet-preview#feedback)
* Content Source: [dotnet/xml/Microsoft.ML.Trainers/MatrixFactorizationTrainer+Options.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Trainers/MatrixFactorizationTrainer+Options.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by codemzs** [comment]
As per [source code](https://github.com/dotnet/machinelearning/blob/628db3c07ef828de253e7f74164467012b04cf32/src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs#L197), its 8. See also, [default for approximate rank](https://github.com/dotnet/machinelearning/blob/628db3c07ef828de253e7f74164467012b04cf32/src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs#L280).

**Comment by deiruch** [comment]
The suggestion was that the documentation should mention these default values.
