### ISSUE TITLE
Interop with C++ (from/to)

### ISSUE THREAD

**Issue by fradav** [dotnet/machinelearning#4318]
### System information

- **OS version/distro**:
Not relevant
- **.NET Version (eg., dotnet --info)**: 
.core 3.0

### Issue

Is there a way to interop from plain C++ with ml.net ? There is a lot of very useful ideas in ml.net (like DataView) and it would make sense to use them in a C++ project for example.  I know there is P/Invoke, but perhaps could we use a more streamlined way?

**Comment by codemzs** [comment]
Hi @fradav Yes it is possible, in fact we do something similar with python where we have python bindings for ML .NET called NimbusML. You can checkout more on the architecture of interop between python and C# [here ](https://arxiv.org/pdf/1905.05715.pdf) ... the same concept can also be applied to C++.
