### ISSUE TITLE
Export to ONNX

### ISSUE THREAD

**Issue by AceHack** [dotnet/machinelearning#4320]
What is the state of exporting to ONNX, I noticed it's missing from the latest documentation and only in the 0.15 docs.  Is it still supported?

Thanks.

**Comment by codemzs** [comment]
@harishsk is working on adding more ONNX exports, perhaps he can give an update here

**Comment by harishsk** [comment]
@AceHack  Thank you for your question.

The status of exporting pipelines to onnx is work in progress. As of this writing, (in the master branch) the following transformers are supported. 

* ColumnCopyingTransformer
* KeyToVectorMappingTransformer
* NormalizingTransformer
* TypeConvertingTransformer
* ValueToKeyMappingTransformer
* PrincipalComponentAnalysisTransformer
* LpNormNormalizingTransformer
* MissingValueIndicatorTransformer
* MissingValueReplacingTransformer
* WordEmbeddingTransformer
* OneHotEncodingTransformer
* ColumnConcatenatingTransformer

And the following learners are supported (for regression only):

* FastTree
* LightGbm
* Ols
* OnlineGradientDescent
* Sdca

Documentation will be updated in the next major release. This is work in progress to make sure that most, if not all ML.NET transformers and learners can be exported to Onnx.
