### ISSUE TITLE
Move DatabaseLoader from the Experimental package

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#4323]
We want to mark the DatabaseLoader as a "stable API" when we ship 1.4. However, it is currently in the Experimental package, which will never be marked as stable.

We should move the DatabaseLoader to a stable package.

If I get a vote, my vote would be to add it to the core `Microsoft.ML` package, next to TextLoader. DatabaseLoader adds no extra dependencies, so I think it is completely fine to add it to the `Microsoft.ML` package.

**Comment by eerhardt** [comment]
fyi - @codemzs @ebarsoumMS

**Comment by tannergooding** [comment]
If we can confirm where it should go, I'm happy to move it there.

**Comment by eerhardt** [comment]
If I was to do it, I would move it next to the `TextLoader`. I don't feel adding a new package for this is valuable since it doesn't add any new dependencies.

@CESARDELATORRE @codemzs @yaeldekel - thoughts? We need this in order to ship a stable `1.4` package with the DatabaseLoader in it.

**Comment by CESARDELATORRE** [comment]
I agree. It should be near the TextLoader type if ti is not adding any new dependencies.
It’d be a very small package if adding a new one.

**Comment by tannergooding** [comment]
Any other input I should wait for, or am I good to move the types and put up the PR?

**Comment by tannergooding** [comment]
Move the type into a new assembly and add a type forward at that point?

**Comment by codemzs** [comment]
Ok, sounds good. Let’s move it out of Experimental nuget. Thanks @eerhardt and @tannergooding
