### ISSUE TITLE
How do I convert topics to words?

### ISSUE THREAD

**Issue by PaulDMendoza** [dotnet/machinelearning#4328]
The example is missing the step where the topics identified are converted to a high level word that describes the topics for each document. Can you add that bit to the example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87b08415-641d-4246-280f-b19e3baa8857
* Version Independent ID: 30d278f5-27f7-eee4-141f-d05dc1d34bfa
* Content: [TextCatalog.LatentDirichletAllocation(TransformsCatalog+TextTransforms, String, String, Int32, Single, Single, Int32, Int32, Int32, Int32, Int32, Int32, Int32, Boolean) Method (Microsoft.ML)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.textcatalog.latentdirichletallocation?view=ml-dotnet#feedback)
* Content Source: [dotnet/xml/Microsoft.ML/TextCatalog.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML/TextCatalog.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by codemzs** [comment]
@justinormont can you please comment and close on this one?

**Comment by codemzs** [comment]
Hi @PaulDMendoza Thanks for the suggestion but this is a sample for LDA Transform and goal here is just to show how to use this particular API and not really how to do data science.

**Comment by PaulDMendoza** [comment]
@codemzs But 99% of people using this sample are going to have the same question. It's like you told a story but left off the ending. 

Is it more than a couple lines to get the topic names or even the words that make up each topic and their frequency? I've looked at this API a bunch and can't figure it out. It seems like the LDA Transform should output a list of words for each topic but I find the ML.NET API very confusing for how to get to that data.

**Comment by nukeandserve** [comment]
I have the same question. How can I see the summary terms for a topic. I have the default 10 summary terms per topic set, but after fitting I cannot find the terms.

**Comment by justinormont** [comment]
See more detail on LDA topics in https://github.com/dotnet/machinelearning/issues/4322
