### ISSUE TITLE
If normalisation is required why does the sample not do this

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/machinelearning#4329]
The trainer is stated to be needing normalisation, the sample does not show this in the pipeline, how is normalisation done?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98e5fc20-effa-58e7-0271-2380fdb73bd9
* Version Independent ID: 71cdb61f-ae25-9a4d-3c19-16d17ab81694
* Content: [StandardTrainersCatalog.LinearSvm Method (Microsoft.ML)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.standardtrainerscatalog.linearsvm?view=ml-dotnet#Microsoft_ML_StandardTrainersCatalog_LinearSvm_Microsoft_ML_BinaryClassificationCatalog_BinaryClassificationTrainers_Microsoft_ML_Trainers_LinearSvmTrainer_Options_)
* Content Source: [dotnet/xml/Microsoft.ML/StandardTrainersCatalog.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML/StandardTrainersCatalog.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by ebarsoumMS** [comment]
Which sample?

**Comment by PeterPann23** [comment]
dotnet/xml/Microsoft.ML/StandardTrainersCatalog.xml does not show a sample of how to user trainer.Fit(trainsorce, testsource)

**Comment by najeeb-kazmi** [comment]
@PeterPann23 you can add a normalization step using one of the methods from the [NormalizationCatalog](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.normalizationcatalog?view=ml-dotnet). For example, in order to MinMaxNormalize the "Features" column before passing it to the trainer, you can add a step in your pipeline like so:

```csharp
var pipeline = mlContext.Transforms.NormalizeMinMax("Features")
    .Append(mlContext.BinaryClassification.Trainers.LinearSvm());
```

**Comment by najeeb-kazmi** [comment]
@PeterPann23 closing this issue. Please feel free to reopen if something remains unanswered.
