### ISSUE TITLE
Not sample how to call this, also fit normaly takes only 1 argument...

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/machinelearning#4331]
The following code does not allow to call fit using the pipeline
            var dataProcessPipeline = GeneratePipelin(data, out var trainingDataView, out var testDataView );

            var options = new LightGbmBinaryTrainer.Options
            {
                NumberOfIterations=100
                , LearningRate=0.2281511
                , NumberOfLeaves=46
                , MinimumExampleCountPerLeaf=10
                , UseCategoricalSplit=false
                , HandleMissingValue=true
                , MinimumExampleCountPerGroup=200
                , MaximumCategoricalSplitPointCount=8
                , CategoricalSmoothing=10
                , L2CategoricalRegularization=0.5                
                , EvaluationMetric = LightGbmBinaryTrainer.Options.EvaluateMetricType.Error
                , LabelColumnName=nameof(BinaryModelInput.Trend)
            };

            var trainer = mlContext.BinaryClassification.Trainers.LightGbm(options);
            //.Append(mlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel", "PredictedLabel"));

            var trainingPipeline =dataProcessPipeline.Append(trainer);
            var model = trainingPipeline.Fit(trainingDataView,testDataView);
the training pipeline is of type 
 EstimatorChain&lt;BinaryPredictionTransformer&lt;Microsoft.ML.Calibrators.CalibratedModelParametersBase&lt;LightGbmBinaryModelParameters, Microsoft.ML.Calibrators.PlattCalibrator&gt;&gt;&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb3687e4-d6ed-52df-b362-de76c9c302c5
* Version Independent ID: cba9caf7-2b90-28c3-5cfe-ad1b34c3c5eb
* Content: [LightGbmBinaryTrainer.Fit(IDataView, IDataView) Method (Microsoft.ML.Trainers.LightGbm)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.lightgbm.lightgbmbinarytrainer.fit?view=ml-dotnet#Microsoft_ML_Trainers_LightGbm_LightGbmBinaryTrainer_Fit_Microsoft_ML_IDataView_Microsoft_ML_IDataView_)
* Content Source: [dotnet/xml/Microsoft.ML.Trainers.LightGbm/LightGbmBinaryTrainer.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Trainers.LightGbm/LightGbmBinaryTrainer.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by PeterPann23** [comment]
perhaps add a parameter to the options where to add the validation. calling the fit on the trainer directly without a pipeline world work however one looses the options provided by the pipeline.

**Comment by PeterPann23** [comment]
Sure, it's just a pipeline, a pipeline only has 1 dataview where the trainer has 2

```
protected EstimatorChain<ColumnConcatenatingTransformer> GeneratePipelin(IReadOnlyList<T> data, out IDataView trainingDataView, out IDataView testDataView)
{


    switch(Evaluates)
    {
        case Evaluates.Trade:

            if(data is null || File.Exists(Path.Combine(path.FullName, $"Stats{Evaluates}.csv")))
            {
                trainingDataView = mlContext.Data.LoadFromTextFile<BinaryModelInput>(
                                            path: Path.Combine(path.FullName, $"Stats{Evaluates}.csv"),
                                            hasHeader: true,
                                            separatorChar: ',',
                                            allowQuoting: true,
                                            allowSparse: false);

                testDataView = mlContext.Data.LoadFromTextFile<BinaryModelInput>(
                                            path: Path.Combine(path.FullName, $"Stats{Evaluates}_Validate.csv"),
                                            hasHeader: true,
                                            separatorChar: ',',
                                            allowQuoting: true,
                                            allowSparse: false);
            }
            else
            {
                var train= new  BinaryModelInput[data.Count];
                Parallel.For(0, train.Length, (i) => train[i] = new BinaryModelInput(data[i]));
                var r=(int)(data.Count*0.8);
                trainingDataView = mlContext.Data.LoadFromEnumerable<BinaryModelInput>(train.Take(r));
                testDataView = mlContext.Data.LoadFromEnumerable<BinaryModelInput>(train.Skip(r));
            }

            return mlContext.Transforms.Concatenate("Features", new[] { "MaxMovement", "MinMovement", "MeanMovement", "MedianMovement", "LastMovement", "MaxSpread", "MinSpread", "MedianSpread", "LastSpread", "DeepBookPatterns", "NeigboringPatterns", "BarPattern" })
                    .AppendCacheCheckpoint(mlContext);


        case Evaluates.Trend:
        default:

            if(data is null || File.Exists(Path.Combine(path.FullName, $"Stats{Evaluates}.csv")))
            {
                trainingDataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                            path: Path.Combine(path.FullName, $"Stats{Evaluates}.csv"),
                                            hasHeader: true,
                                            separatorChar: ',',
                                            allowQuoting: true,
                                            allowSparse: false);

                testDataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                            path: Path.Combine(path.FullName, $"Stats{Evaluates}_Validate.csv"),
                                            hasHeader: true,
                                            separatorChar: ',',
                                            allowQuoting: true,
                                            allowSparse: false);
            }
            else
            {
                var train= new  ModelInput[data.Count];
                Parallel.For(0, train.Length, (i) => train[i] = new ModelInput(data[i]));
                var r=(int)(data.Count*0.8);
                trainingDataView = mlContext.Data.LoadFromEnumerable<ModelInput>(train.Take(r));
                testDataView = mlContext.Data.LoadFromEnumerable<ModelInput>(train.Skip(r));
            }
            return mlContext.Transforms.Conversion.MapValueToKey("Trend", "Trend")
                                        .Append(mlContext.Transforms.Concatenate("Features", new[] { "MaxMovement", "MinMovement", "MeanMovement", "MedianMovement", "LastMovement", "MaxSpread", "MinSpread", "MedianSpread", "LastSpread", "DeepBookPatterns", "NeigboringPatterns", "BarPattern" }))
                                        .AppendCacheCheckpoint(mlContext);
    }
   // Data process configuration with pipeline data transformations 
}
```

**Comment by najeeb-kazmi** [comment]
@PeterPann23 Please see https://github.com/dotnet/machinelearning/issues/3890#issuecomment-579064690
