### ISSUE TITLE
How to update model in ml .net every day?

### ISSUE THREAD

**Issue by gagoole** [dotnet/machinelearning#4332]
Hi every body.
How to update model in ml .net every day to increase accuracy?

**Comment by codemzs** [comment]
Hi @gagoole Some of our trainers support online learning that you can use to update the model, example [OnlineGradientDescent](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.onlinegradientdescenttrainer?view=ml-dotnet).
