### ISSUE TITLE
[Microsoft.Extensions.ML] Update Microsoft.Extensions.ML from 0.16.0-preview2 to 1.4

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning#4352]
@eerhardt 

We need to update Microsoft.Extensions.ML from 0.16.0-preview2 to 1.4 so it'll be ready for 1.4 GA.

This is mostly related to the .NET Integration package implementing the PredictionEnginePool for multi-threaded apps such as ASP.NET Core apps/services.

**Comment by eerhardt** [comment]
FYI - @codemzs @ebarsoumMS. This package has been in 'preview' for 6 months, downloaded ~7k times, and hasn't received any negative API feedback. We believe it is time to mark it as 'stable'.
