### ISSUE TITLE
Recognise specific noise through Spectrogram images

### ISSUE THREAD

**Issue by rossbuggins** [dotnet/machinelearning#4353]
Hi,

Sorry if not best place to ask for a general pointer, but I recon someone could be able to quickly point me in the right direction re models/training etc.

I've got a audio files in the format of spectrograms (png files), each about 2 seconds long (overlapping windows about .5 second) for a 10 minute audio file.

There is one specific noise that I want to identify in audio files, and treat all other noises as "background" or not interested in.

I've looked at using TensorFlow and the sample Image Classification (https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification) and taking a few dozen spectrograms of what I want and classified as "true" and then a randoms selection of spectrogram images of "background" noise (i.e. anything i don't care about) and classified as "false".

Is this the best way to approach this with the .net ML libraries, or is there a better way to say, "this is all I want and I don't care about anything else", and not give it any samples of background noise images at all?

Thanks,

Ross

**Comment by antoniovs1029** [comment]
I think the approach you took is appropriate.

In any case, perhaps the only way to confirm this is to experiment with different approaches and see which one yields the best accuracy to your problem.
