### ISSUE TITLE
Folder and file names don't match Namespaces and Type names

### ISSUE THREAD

**Issue by markusweimer** [dotnet/machinelearning#436]
### System information

- **OS version/distro**: Windows 10 v1803
- **.NET Version (eg., dotnet --info)**: 2.1.201 

### Issue

- **What did you do?** Open the solution in Jetbrains Rider
- **What happened?** Rider pointed out many cases where type and file names differed, as well as cases where name spaces and folder names weren't in sync.

**Comment by danmosemsft** [comment]
In CoreFX generally type names match file names, but namespaces generally do not match folders. I suspect this is common to many/most C# code bases.

It might be best to defer cleaning this up for anything whose type name/namespace might be changed in API review.

**Comment by markusweimer** [comment]
@danmosemsft said:
> In CoreFX generally type names match file names, but namespaces generally do not match folders. I suspect this is common to many/most C# code bases.

Is there another file name convention we should adhere to?

**Comment by Ivanidzo4ka** [comment]
DRI RESPONSE: I'm intend to move this to backlog, unless anyone objects.

**Comment by codemzs** [comment]
As Dan pointed out this is common to many/most C# code bases
