### ISSUE TITLE
UWP: Compilation error - C:\Users\user\.nuget\packages\microsoft.net.uwpcoreruntimesdk\2.2.9\tools\CoreRuntime\Microsoft.Net.CoreRuntime.targets(195,9): error : Framework resource extraction failed. Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by Krusnik02** [dotnet/machinelearning#4366]
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: .NET Core 3.0

### Issue

- **What did you do?**
I have large UWP project:
[https://www.microsoft.com/ru-ru/p/spider-intelligence/9phw2smp1hl7?activetab=pivot:overviewtab](url)
I have added ML.NET and ML processing algorithms to the solution. 
Once I did "Clean solution" and “Rebuilt solution”....
- **What happened?**
Builder have given me following error: "C:\Users\user\.nuget\packages\microsoft.net.uwpcoreruntimesdk\2.2.9\tools\CoreRuntime\Microsoft.Net.CoreRuntime.targets(195,9): error : Framework resource extraction failed. Exception of type 'System.OutOfMemoryException' was thrown."

I have checked that the cause of the problem is ML.NET: I have removed ML.NET link and code from the solution, everything become fine. 

I have checked all versions of microsoft.net.uwpcoreruntimesdk, ML.NET, other libraries, building options. But error is still here. 
I have 48GB RAM so it is nor RAM issue.

- **What did you expect?**
Any way to build my UWP large enough project with ML.NET inside :) I think it is compiler or linker BUG somewhere.

### Source code / logs
Code is large... If it is needed, I can prepare code sample with error.

**Comment by mstfbl** [comment]
Hi @Krusnik02 , can you please provide sample code replicating this issue as you have offered to do so? Thanks!

**Comment by harishsk** [comment]
@Krusnik02 I am temporarily closing the issue for lack of enough information. Can you please reopen with additional details?

**Comment by theolivenbaum** [comment]
Someone reported this issue on our [Catalyst NLP](https://github.com/curiosity-ai/catalyst/) library, easy to reproduce:

> Just adding Catalyst to a UWP app (tried versions 17763, 18362) causes the error "Framework resource extraction failed. Exception of type 'System.OutOfMemoryException' was thrown." when compiling.
> 
> To Reproduce
> Create a UWP app in Visual Studio 2019, add Catalyst through NuGet. Add the using, and possibly a use of it. Build for either x64 or x86.
> 
> Expected behavior
> Compilation works.

**Comment by XeonKHJ** [comment]
Have the same problem here, add an .NET Standard lib that uses ML.NET to an UWP project. The same error came when I tried to build the UWP project.

**Comment by CarteKiwi** [comment]
Same here.
Using it inside a .NET Standard 2.0 class library project, referenced inside a UWP project (Build 19041).
Not occured first time, but now... occuring, I don't know why.
