### ISSUE TITLE
mlnet command not found

### ISSUE THREAD

**Issue by olejorgensen** [dotnet/machinelearning#4376]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: macos Catalina 10.15.1 Beta (19B77a)
dotnet version: 3.0.100

```
dev@iMac myMLApp % mlnet auto-train --task binary-classification --dataset "wikipedia-detox-250-line-data.tsv" --label-column-name "Sentiment" --max-exploration-time 10
zsh: command not found: mlnet
dev@iMac myMLApp % dotnet tool install -g mlnet         
Tool 'mlnet' is already installed.
```

**Comment by frank-dong-ms** [comment]
@olejorgensen Hi, is Cesar's suggestion work for your?

**Comment by frank-dong-ms** [comment]
Close this for now as no reply from user, please feel free to reopen if necessary
