### ISSUE TITLE
Incorrect header comments in CodeGen template files

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/machinelearning#4387]
The auto generated files under `src/Microsoft.ML.CodeGenerator/Templates/` directory are creating incorrect header comments and need to be modified.

Refer to:
https://github.com/dotnet/machinelearning/pull/4365#discussion_r338733805

cc: @JakeRadMSFT @LittleLittleCloud @rustd @eerhardt @sharwell

**Comment by mstfbl** [comment]
This issue was fixed as part of the changes in PR #4365 .
