### ISSUE TITLE
Image recognition rotation invariant

### ISSUE THREAD

**Issue by zubr1** [dotnet/machinelearning#4398]
After completing model training, prediction didn't recognize differences between rotated images. Let's assume I have an image of right hand and left hand. I'd like to classify it differently so right hand image should be classified as right hand, and left hand image respectively as left. Unfortunately my current model sees no differences between them and it constantly fluctuates between both labels. 
Is there any solution for this like turning off data augmentation, or changing some settings? Or maybe it's problem of insufficient data for training (I use around 33-35 images for one label)?

**Comment by ashbhandare** [comment]
Could you double check your training data that the 'right hand images' and 'left hand images' are indeed being fed correctly (meaning the images are correctly labeled)? Also, you might see a benefit in increasing the number of training images as ~35 for one label is a relatively small number.
