### ISSUE TITLE
Wrong Culture when passing arguments to LightGBM

### ISSUE THREAD

**Issue by hrkrx** [dotnet/machinelearning#440]
### System information

- Win 10
- dotnet core

### Issue

When calling the Train Method the arguments are parsed with the local culture instead of en or us, which leads to an Error:

![41993623-57553e14-7a4c-11e8-9d75-12d423f54f8e](https://user-images.githubusercontent.com/5176531/41993935-1bdfc5ec-7a4d-11e8-899c-7d4f62cc85f1.png)

**Comment by shauheen** [comment]
Thanks @hrkrx for filing the issue. @codemzs
