### ISSUE TITLE
Getting RegressionTree from ITransformer model

### ISSUE THREAD

**Issue by ThomasIE** [dotnet/machinelearning#4411]
### System information

Windows 10 & Visual Studio 2019

### Issue

Hi, I want to know how to get RegressionTree object from a FastTree regression model because the RegressionTree is private and not available to access. (For your information, I have attached my code below. I got it from **https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/predict-prices)**

Also, due to the combination of left and right nodes, is it allowed to use binary splits, not multiple splits per node?

Finally, how can I use the function in "SaveAsCode" in FastTree.cs? Is there any example to take a look at?

Thanks in advance.

Sincerely,

### Source code / logs
        static readonly string _trainDataPath = Path.Combine(Environment.CurrentDirectory, "Data", "taxi-fare-train.csv");
        static readonly string _testDataPath = Path.Combine(Environment.CurrentDirectory, "Data", "taxi-fare-test.csv");

        static void Main(string[] args)
        {
            MLContext mlContext = new MLContext(seed: 0);
            ITransformer model = Train(mlContext, _trainDataPath);
            
            
        }

        public static ITransformer Train(MLContext mlContext, string dataPath)
        {
            IDataView dataView = mlContext.Data.LoadFromTextFile<TaxiTrip>(dataPath, hasHeader: true, separatorChar: ',');
            var pipeline = mlContext.Transforms.CopyColumns(outputColumnName: "Label", inputColumnName: "FareAmount")
                .Append(mlContext.Transforms.Categorical.OneHotEncoding(outputColumnName: "VendorIdEncoded", inputColumnName: "VendorId"))
                .Append(mlContext.Transforms.Categorical.OneHotEncoding(outputColumnName: "RateCodeEncoded", inputColumnName: "RateCode"))
                .Append(mlContext.Transforms.Categorical.OneHotEncoding(outputColumnName: "PaymentTypeEncoded", inputColumnName: "PaymentType"))
                .Append(mlContext.Transforms.Concatenate("Features", "VendorIdEncoded", "RateCodeEncoded", "PassengerCount", "TripTime", "TripDistance", "PaymentTypeEncoded"))
                .Append(mlContext.Regression.Trainers.FastTree());

            var model = pipeline.Fit(dataView);

            return model;
        }

**Comment by eerhardt** [comment]
> I want to know how to get RegressionTree object from a FastTree regression model

See the last line below:

```C#
        IDataView dataView = mlContext.Data.LoadFromTextFile<TaxiTrip>(dataPath, hasHeader: true, separatorChar: ',');
        var pipeline = mlContext.Transforms.CopyColumns(outputColumnName: "Label", inputColumnName: "FareAmount")
            .Append(mlContext.Transforms.Categorical.OneHotEncoding(outputColumnName: "VendorIdEncoded", inputColumnName: "VendorId"))
            .Append(mlContext.Transforms.Categorical.OneHotEncoding(outputColumnName: "RateCodeEncoded", inputColumnName: "RateCode"))
            .Append(mlContext.Transforms.Categorical.OneHotEncoding(outputColumnName: "PaymentTypeEncoded", inputColumnName: "PaymentType"))
            .Append(mlContext.Transforms.Concatenate("Features", "VendorIdEncoded", "RateCodeEncoded", "PassengerCount", "TripTime", "TripDistance", "PaymentTypeEncoded"))
            .Append(mlContext.Regression.Trainers.FastTree());

        var model = pipeline.Fit(dataView);

        RegressionTreeEnsemble tree = model.LastTransformer.Model.TrainedTreeEnsemble;
```

> Also, due to the combination of left and right nodes, is it allowed to use binary splits, not multiple splits per node?

It is only a binary tree. Left and right child nodes.

>  how can I use the function in "SaveAsCode" in FastTree.cs?

There is no public API that allows you to call it. However, you could write it yourself, if you want. I have a little bit of code that inspects a fast tree and builds up a graphical tree here:

https://github.com/eerhardt/DotNetInteractiveExtension/blob/2124763e1aeb938203a2b493a3f5fde212aa4cd9/src/Microsoft.ML.DotNet.Interactive/DecisionTreeDataExtensions.cs#L20-L81

You can easily use this to write out `if ("featureName" > {splitThreashold}) { Use RightChild; } else { Use LeftChild; }`

**Comment by eerhardt** [comment]
Closing as I believe this question has been answered. Feel free to re-open if that is not the case.

**Comment by ThomasIE** [comment]
Thanks a lot!
