### ISSUE TITLE
Hotlinking to blob store

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning#4445]
We need aka.ms links to the CDN instead of direct links to blob store:
* https://github.com/dotnet/machinelearning/blob/cc0b7869d50df819783f30b3f7da4d5c3725bb8f/test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs#L1902-L1903
* https://github.com/dotnet/machinelearning/blob/9215ba9e0ee8caa1e97e2666743644baf8c8139c/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/ImageClassification/LearningRateSchedulingCifarResnetTransferLearning.cs#L263

~~The unit test and sample will stop working in a month as we close down that blob store.~~ (update: found out this is no longer the case -- https://github.com/dotnet/machinelearning/issues/4445#issuecomment-552034148)

We should add a check-in test to ensure that no blob-store links are added in the future. All links should be an aka.ms link to the CDN.

**Comment by justinormont** [comment]
These six should also follow the aka.ms to CDN route: _(consider factoring out this duplicate code)_
* https://github.com/dotnet/machinelearning/blob/cc0b7869d50df819783f30b3f7da4d5c3725bb8f/test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs#L1888-L1891
* https://github.com/dotnet/machinelearning/blob/0b9308e11b2d8e385339aa866a0aaf60f4fc54b2/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/ImageClassification/ResnetV2101TransferLearningTrainTestSplit.cs#L254-L257
* https://github.com/dotnet/machinelearning/blob/0b9308e11b2d8e385339aa866a0aaf60f4fc54b2/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/ImageClassification/ResnetV2101TransferLearningEarlyStopping.cs#L233-L236
* https://github.com/dotnet/machinelearning/blob/0b9308e11b2d8e385339aa866a0aaf60f4fc54b2/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/ImageClassification/ImageClassificationDefault.cs#L245-L248
* https://github.com/dotnet/machinelearning/blob/a40df8612b8f09946d59778c27f264cd043d657a/test/Microsoft.ML.Benchmarks/ImageClassificationBench.cs#L142-L145
* https://github.com/dotnet/machinelearning/blob/54b2b041da42b18f947b5833e64c9763108c7d32/test/Microsoft.ML.AutoML.Tests/DatasetUtil.cs#L143-L146

**Comment by gvashishtha** [comment]
@yaeldekel It turns out that our storage account will not be affected by US West upgrade, so the only work item is to turn the hotlinks into aka.ms short links. Does this make sense?
