### ISSUE TITLE
[Image Classification API] Bottleneck phase values always computed

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#4452]
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: 2.1
- **ML.NET Version (eg., dotnet --info)**: 1.4.0

### Issue

Setting `ReuseTrainSetBottleneckCachedValues` and `ReuseValidationSetBottleneckCachedValues` parameters in `ImageClassificationTrainer.Options` to `true`, does the bottleneck computation on subsequent runs. I believe once the bottleneck values are computed on the first run, by setting both of those parameters to `true`, bottleneck computation should be skipped and the model should go directly into the training phase.  Is this no longer the case?

### Source code / logs

See sample source code at this link: https://github.com/luisquintanilla/machinelearning-samples/blob/33f87d226f350fb36552dd8b1cee6a7c3f12da89/samples/csharp/getting-started/DeepLearning_ImageClassification_Binary/DeepLearning_ImageClassification_Binary/Program.cs#L53

**Comment by codemzs** [comment]
hi Luis, you need to specific a workspace path so that bottleneck files are not deleted else bottleneck files are created in a temporary folder that is deleted after training run.
