### ISSUE TITLE
FeatureContribution transformation currently returns vector of all feature and their contribution while calling PredictionEngine.Predict method 

### ISSUE THREAD

**Issue by vnarula** [dotnet/machinelearning#4468]
### System information

- **OS version/distro**:
- **.NET Version (eg., dotnet --info)**: 

### Issue

- **What did you do?**
FeatureContribution transformation currently returns vector of all feature and their contribution while calling PredictionEngine.Predict method

- **What happened?**
Returned vector of 8 million feature which degraded the overall service of prediction service
- **What did you expect?**
it should only return the feature contribution of feature top x or bottom y which were requested instead of returning contribution of all features.
### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by codemzs** [comment]
I’m working on this. Should have the PR shortly

**Comment by codemzs** [comment]
Closing this since we were able to get a workaround.
