### ISSUE TITLE
OnnxTransformer fails running on GPU

### ISSUE THREAD

**Issue by donaldhessing** [dotnet/machinelearning#4478]
I'm trying to detect objects in images by using an exported ONNX model from Custom Vision on GPU but getting the following exception:

System.EntryPointNotFoundException: 'Unable to find an entry point named 'OrtSessionOptionsAppendExecutionProvider_CUDA' in DLL 'onnxruntime'.'

Based on the documentation the ApplyOnnxModel method provides an overload for GPU:
public static Microsoft.ML.Transforms.Onnx.OnnxScoringEstimator ApplyOnnxModel (this Microsoft.ML.TransformsCatalog catalog, string modelFile, Nullable gpuDeviceId = null, bool fallbackToCpu = false);

The model works perfectly fine when using the CPU, but when the gpuDeviceID and fallbackToCpu parameters are provided it fails with the above execption. I understand that for the OnnxRuntime to support GPU you need to also install the ML.OnnxRuntime.GPU nuget package but i noticed that ML.OnnxTransformer has a dependency with ML.OnnxRuntime 0.5.1.

**Enviroment:**
OS Platform: Windows 10 professional build 1809
ONNX Runtime: 1.4.0 and has dependency with ML.OnnxRuntime 0.5.1, tried ML.OnnxRuntime.GPU 1.0.0 but need OnnxTransformer.
Platform: .NET Core 3.0
Visual Studio version (if applicable): 2019
CUDA/cuDNN version: CUDA 10.0.130, cuDNN 7.6.0.34
GPU model and memory: NVidia Quadro P1000

**Failing code:**
var pipeline = mlContext.Transforms.ResizeImages(resizing: ImageResizingEstimator.ResizingKind.Fill, outputColumnName: onnxModel.ModelInput, imageWidth: ImageSettings.imageWidth, imageHeight: ImageSettings.imageHeight, inputColumnName: nameof(ImageInputData.Image))
.Append(mlContext.Transforms.ExtractPixels(outputColumnName: onnxModel.ModelInput))
.Append(mlContext.Transforms.ApplyOnnxModel(onnxModel.ModelOutput, onnxModel.ModelInput, onnxModel.ModelPath, 1, true));

**Comment by harishsk** [comment]
Thank you for reporting the issue. 

The released version of ML.NET (v1.4) uses Microsoft.ML.OnnxRuntime v0.5.1. That version of Onnx runtime did not publicly support GPU execution. But the v1 release does support GPU execution through the Microsoft.ML.OnnxRuntime.GPU package. That version of the Onnx runtime is currently incompatible with the ML.NET v1.4.
It will likely remain so for the next couple of months. We are working with the Onnx runtime team to resolve this.

**Comment by Guawazii** [comment]
Hi Harishsk,

Thanks for your contribution on onnx. 

I am Timi ,one of the developers learning about Object Detecting.  I read your reply about OnnxTransformer GPU issue on https://github.com/dotnet/machinelearning/issues/4478. I recently got a problem similar. And I am curious about whether you've successfully solved the GPU compatible problem with Onnx runtime team. 

Looking forward to get your message!

Best,
Timi

**Comment by Guawazii** [comment]
nxruntime.dll
Microsoft (R) COFF/PE Dumper Version 14.29.30040.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\Users\xiangbao\Downloads\onnxruntime-master\csharp\FSUnitTest\bin\Debug\net5.0-windows\onnxruntime.dll

File Type: DLL

  Section contains the following exports for onnxruntime.dll

    00000000 characteristics
    FFFFFFFF time date stamp
        0.00 version
           1 ordinal base
           5 number of functions
           5 number of names

    ordinal hint RVA      name

          1    0 00017CE0 OrtGetApiBase
          2    1 001295B0 OrtGetWinMLAdapter
          3    2 00077D10 OrtSessionOptionsAppendExecutionProviderEx_DML
          4    3 001ADF60 OrtSessionOptionsAppendExecutionProvider_CPU
          5    4 00077C80 OrtSessionOptionsAppendExecutionProvider_DML
