### ISSUE TITLE
LoadColumn should not be required when loading from a file with headers

### ISSUE THREAD

**Issue by kevencarneiro** [dotnet/machinelearning#4480]
### System information

- **OS version/distro**: Windows 10 (10.0.18362)
- **.NET Version (eg., dotnet --info)**:  3.0.100

### Issue

- **What did you do?**
Created a type anottated with `LoadColumnName`
Created a `TextLoader` from this type and `useHeaders` set to `true` and called the `Load` method

- **What happened?**
System.InvalidOperationException: 'Property 'IESCode' is missing the LoadColumnAttribute attribute'

- **What did you expect?**
The Load method should map the properties from the file headers when available, not forcing the use of column index.

### Source code / logs

```fsharp
System.InvalidOperationException: 'Property 'IESCode' is missing the LoadColumnAttribute attribute'
```

```fsharp
type EnadeMicrodata =
    {
        [<LoadColumnName("CO_IES")>]
        IESCode: int

        [<LoadColumnName("CO_CATEGAD")>]
        AdministrativeCategory: int
    }

let mlContext = MLContext ()
let _textLoader = mlContext.Data.CreateTextLoader<EnadeMicrodata>(hasHeader = true).Load("MICRODADOS_ENADE_2017.txt")
```

**Comment by harishsk** [comment]
Thank you for raising the issue. 

Currently, the text loader only supports LoadColumn which only takes column indices as parameters. 
LoadColumnName is supported only in the database loader. We will consider this as a feature request for a future release. 

Please feel free to reopen the issue if you feel your question has not been answered.

**Comment by kevencarneiro** [comment]
Can I implement it and make a Pull Request?

**Comment by harishsk** [comment]
Absolutely! That would be great!

**Comment by eslamalix** [comment]
any solution for the current problem yet?
