### ISSUE TITLE
Replace usages of TPL DataFlow BufferBlock with Threading.Channels

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#4482]
There are 2 places we are using `BufferBlock<T>` today:

https://github.com/dotnet/machinelearning/blob/b7db4fa475ba4bd52824eb98bbf5f5bf4a0a6f7a/src/Microsoft.ML.Data/Transforms/RowShufflingTransformer.cs#L486-L487

https://github.com/dotnet/machinelearning/blob/b7db4fa475ba4bd52824eb98bbf5f5bf4a0a6f7a/src/Microsoft.ML.Sweeper/AsyncSweeper.cs#L171

We should consider replacing this dependency with https://www.nuget.org/packages/System.Threading.Channels/ instead. Channels are a bit simpler, and more performant than BufferBlock.

See:

* https://github.com/dotnet/machinelearning/pull/4479#discussion_r346845557
* https://github.com/dotnet/corefx/issues/24715

**Comment by mariombaltazar** [comment]
I, Can I try do this?

**Comment by eerhardt** [comment]
@mariombaltazar -Yes! Feel free.

**Comment by mariombaltazar** [comment]
I @eerhardt,
I can not do pull request. can you help me?

**Comment by eerhardt** [comment]
Here's the steps to create a pull request:

1. Fork the repo - https://help.github.com/en/github/getting-started-with-github/fork-a-repo
2. Push your changes to that fork
3. Create the PR from your fork - https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by mstfbl** [comment]
Hi @mariombaltazar , are you still interested in working on this issue?

**Comment by campiador** [comment]
@eerhardt @mstfbl Hi, can I start working on this?

**Comment by antoniovs1029** [comment]
Hi @campiador . It is still an unsolved issue, and it seems that @mariombaltazar isn't working on it, so you can go for it 😃

**Comment by frank-dong-ms** [comment]
Close this issue and this already been addressed.
