### ISSUE TITLE
Command Timeouts While Using The Database Loader

### ISSUE THREAD

**Issue by mayoatte** [dotnet/machinelearning#4484]
### System information

- **Windows 10**:
- **.NET Core 3.0**: 

### Issue

- Loaded training data from SQL Server (1m rows)
- SqlException Execution timeout in less than a minute
- The query should complete even if it's slow (based on volume). There should also be a way to modify the sql command timeout.

### Source code / logs

`          string connectionString = _config["Database.ConnectionString"];

            string sqlCommand = await GetSql("OrderHistory.sql");

            DatabaseSource dbSource = new DatabaseSource(SqlClientFactory.Instance, connectionString, sqlCommand);

            return dbSource;`

**Comment by ashbhandare** [comment]
From my initial investigation, looks like you can specify the Timeout in the connectionString. 
See https://github.com/dotnet/machinelearning/blob/36fab9b6806260e64e50992450a219e869c7f74a/test/Microsoft.ML.Tests/DatabaseLoaderTests.cs#L270

Closing for now, please re-open if this does not solve your issue.

**Comment by mayoatte** [comment]
@ashbhandare  Thanks for responding so quickly. I tried that already and it doesn't work in this case. AFAIK the Connect Timeout only affects how long it takes to connect to the database and not how long a single command can take (Command Timeout). 

The common scenario for ML (large dataset) will need a longer timeout than usual so we need a way to set this.
