### ISSUE TITLE
Error loading Tensorflow Session in Jupyter Notebooks

### ISSUE THREAD

**Issue by aslotte** [dotnet/machinelearning#4488]
### System information

- **OS version/distro**: Windows 10 Home
- **.NET Version (eg., dotnet --info)**:  .NET Core 3.0
- **ML.NET Version**: v1.4.0.0
### Issue

I wasn't sure if this issue belonged in `/dotnet/try` or here, but I figured I start here as I think it may be ML.NET related.

- **What did you do?** Ran a Transfer Learning sample in Jupyter Notebooks
- **What happened?** Got an exception from Tensorflow loading the TF model
- **What did you expect?** `.Fit()` to work as expected

### Source code / logs
Source code can be found here
https://github.com/aslotte/mlnet-jupyter/blob/master/src/image%20classification.ipynb

Exception:
![image](https://user-images.githubusercontent.com/30201569/69198007-45ac1600-0b01-11ea-8500-76e5d3e2764d.png)

**Comment by ashbhandare** [comment]
Hi @aslotte , was there an additional exception message? I see the call stack but cannot see what the exception was.

**Comment by aslotte** [comment]
@ashbhandare - no other exceptions as far as I could tell.

**Comment by ashbhandare** [comment]
Hi @aslotte , I took a look at your notebook, and looks like you have not installed the tensorflow nuget in the beginning. 
Could you retry after adding the line:
#r "nuget:SciSharp.TensorFlow.Redist,1.14.0"

**Comment by aslotte** [comment]
Thanks for the update @ashbhandare, I missed that.
I get another exception by doing that though:

![image](https://user-images.githubusercontent.com/30201569/69378139-c4c55980-0c7b-11ea-8c08-801f4624f24e.png)

**Comment by ashbhandare** [comment]
@aslotte I looked into your notebook, and looks like I am able to run the .fit() if I give the absolute path instead of relative. 
```
var imagePath = @"C:\Users\..\Datasets\Computer Vision\fashion-product-images-small\images";
```
Your ImageData object should get the absolute path for the "ImagePath" column.

**Comment by aslotte** [comment]
Thank you @ashbhandare - that was exactly the problem! Would there be any room for improvement in regard to this path? Having an absolute path for an image dataset makes the Jupyter Notebooks less sharable. Thanks!

**Comment by ashbhandare** [comment]
Hey @aslotte , you don't need to hard code the path, you just have to make sure that the 'ImageData' object has the absolute path. See https://github.com/dotnet/machinelearning/blob/9af92a4a430e5de17fa9cf07d9a393c0f0f8178e/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/ImageClassification/ImageClassificationDefault.cs#L305
