### ISSUE TITLE
Out of Memory Exception In Model Builder

### ISSUE THREAD

**Issue by mayoatte** [dotnet/machinelearning#4499]
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: .Net Core 3.0 

### Issue

- **What did you do?**

Tried to use a Model Builder (AutoML) with a 1 GB csv file. 

- **What happened?**

Out of Memory Exception

![image](https://user-images.githubusercontent.com/29760620/69455746-e840e080-0d1d-11ea-9932-4ea1ef8a1780.png)

- **What did you expect?**

The file would get loaded. It looks like the Model Builder is trying to use  a StringBuilder here. That's naturally going to fall down after a certain size of csv. Stream?

**Comment by justinormont** [comment]
Recommend using Microsoft.ML.AutoML api for inspecting the file, and creating the loader function. Then reading the file w/ the ML.NET text loader by feeding it the created loader parameters. 

This avoids incompatibilities between the two (and it streams nicely).

**Comment by mayoatte** [comment]
Sounds good.  I believe some of the csv columns in my data are also mucking up the larger csv (spaces!). Will close this for now and switch to using the AutoML API.

Thanks again for responding so fast.

**Comment by justinormont** [comment]
@mayoatte : My apologies, my comment was more for the Model Builder team as a way to fix your reported bug. 

Though, you can also use the AutoML API directly for the same reason. You can also try the ML.NET CLI: https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-ml-net-cli

**Comment by mayoatte** [comment]
@justinormont  No worries at all.

After looking at it again, i wasn't sure if my csv was in the right formt (I also have csv columns). And in case, the API is a better fit for me as i was able to reuse all the data loading and prep code I had already without going back to csv.

Please free to reopen the issue if you'd still like the Model Builder team to have a look.

Thanks again for all your help.
