### ISSUE TITLE
Multiclass classification - Prediction Output 

### ISSUE THREAD

**Issue by hahsm** [dotnet/machinelearning#4513]
Hi,

The following code helps to get the predicted label with score. Is there any way that I can get additional details (columns) of each prediction based on score. What are the columns that I could include as output in a multiclass prediction (other than Label and Score). Can I include additional columns from DataSet in my output?

`
private static Dictionary<string, float> GetScoresWithLabelsSorted(DataViewSchema schema, string name, float[] scores)
        {
            Dictionary<string, float> result = new Dictionary<string, float>();

            var column = schema.GetColumnOrNull(name);

            var slotNames = new VBuffer<ReadOnlyMemory<char>>();
            column.Value.GetSlotNames(ref slotNames);
            var x = slotNames.GetIndices();

            var num = 0;
            foreach (var denseValue in slotNames.DenseValues())
            {
                result.Add(denseValue.ToString(), scores[num++]);
            }

            return result.OrderByDescending(c => c.Value).ToDictionary(i => i.Key, i => i.Value);
        }`

**Comment by codemzs** [comment]
You can also get probabilities. Yes you can include columns from dataset in your output. Refer to this [example ](https://github.com/dotnet/machinelearning/blob/ce9b38bc59f40d6e7a5be4388de9664ff35448fe/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/Calibrators/FixedPlatt.cs)to see how to extract probabilities.
