### ISSUE TITLE
GPU Training doesn't work with AutoML on Surface Book 2

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning#4516]
- **What did you do?**
Tried to train with GPU on a Surface Book 2
- **What happened?**
Stalls after 3rd cross val ... I think
- **What did you expect?**
10 Cross Vals and best model.

### Source code / logs

[weather-small-train-logs-cpu.txt](https://github.com/dotnet/machinelearning/files/3914431/weather-small-train-logs-cpu.txt)
[weather-small-train-logs-gpu.txt](https://github.com/dotnet/machinelearning/files/3914432/weather-small-train-logs-gpu.txt)
[weather-small.zip](https://github.com/dotnet/machinelearning/files/3914434/weather-small.zip)

**Comment by JakeRadMSFT** [comment]
CPU works fine but GPU training fails. See logs.

**Comment by luisquintanilla** [comment]
I got the same issue when using a dataset that uses cross-validation.

**Comment by bpstark** [comment]
@luisquintanilla Can you provide the pipeline you are using to reproduce this issue?

**Comment by luisquintanilla** [comment]
@bpstark Here's the link to the pipeline.

https://github.com/luisquintanilla/ModelBuilderGPUTest/blob/c85d488a61acc52b47889f6dd4537f1160b023de/ModelBuilderGPUTestML.ConsoleApp/ModelBuilder.cs#L34

This pipeline is auto-generated by AutoML in Model Builder.

Using the attached data, you should be able to reproduce the issue.

[EuroSAT200.zip](https://github.com/dotnet/machinelearning/files/3947060/EuroSAT200.zip)

**Comment by bpstark** [comment]
@JakeRadMSFT I was able to get the API for AutoML which runs the cross validation. I ran that code in isolation both in Debug and in release, and in neither case was I able to produce the same hang as seen when running using model builder
` var context = new MLContext();
context.Log += MlContext_Log;
var datasetPath = @"PATH_TO_FILE.tsv";
var columnInference = context.Auto().InferColumns(datasetPath, "Label");
var textLoader = context.Data.CreateTextLoader(columnInference.TextLoaderOptions);
var trainData = textLoader.Load(datasetPath);
var result = context.Auto()
                            .CreateMulticlassClassificationExperiment(0)
                            .Execute(trainData, columnInference.ColumnInformation);

var scoredData = result.BestRun.Model.Transform(trainData);`

This may be a bug within model builder?

**Comment by gvashishtha** [comment]
@bpstark to confirm - you ran this on GPU?

**Comment by bpstark** [comment]
@gvashishtha yes I ran this on the GPU

**Comment by harishsk** [comment]
@JakeRadMSFT I am closing the issue. Please reopen if you think this still needs investigation at our end.
