### ISSUE TITLE
System.ArgumentOutOfRangeException in NimbusML's NGramFeaturizer2.py caused by CustomStopWordsRemover/Feature_extraction.text.stopwords in ML.NET

### ISSUE THREAD

**Issue by mstfbl** [dotnet/machinelearning#4518]
As addressed in this [issue ](https://github.com/microsoft/NimbusML/issues/365) in the NimbusML repo, there is a bug with the ML.NET bindings of CustomStopWordsRemover, which is StopWordsRemovingTransformer.cs. 

The specific error message is: 
RuntimeError: Error: *** System.ArgumentOutOfRangeException: 'dataFile is empty
The full error log can be found [here](https://dev.azure.com/aifx/public/_build/results?buildId=2089&view=logs&j=d0e8f4b8-2f67-5548-290c-4d6f15a1cbca&t=e5950cbb-cc45-5e54-16a6-7bfce2ad073d&l=8236).

**Comment by gvashishtha** [comment]
@frank-dong-ms

**Comment by frank-dong-ms** [comment]
Stop words are not passed properly to ml.net class - CustomStopWordsRemovingTransformer, Piet is helping take a look from NimbusML side
