### ISSUE TITLE
OneHotHashEncoding / OneHotEncoding transformer output

### ISSUE THREAD

**Issue by thezaza101** [dotnet/machinelearning#4519]
### System information

- **OS version/distro**: Win 10 
- **.NET Version (eg., dotnet --info)**:  .NET Core 3.0.100, ML.NET 1.4.0

### Issue

- **What did you do?**
Inspected output of OneHotHashEncoding / OneHotEncoding

- **What happened?**
Expected vector different representations for different categories, however they were the same.

If the first category is `[1, 0, 0, 0]` then the second category should be different (i.e. `[0, 1, 0, 0]`). however it appears to be the same when inspecting it.

Inspected `IDataView` using `data.Preview(numRows)`.

### Source code / logs

Code:
```csharp
using System;
using Microsoft.ML;
using Microsoft.ML.Data;
namespace cat
{
    class CatInput
    {
        [LoadColumn(0),ColumnName("input")]
        public string cat;
    }
    class Program
    {
        static MLContext _mlContext = new MLContext();
        static IDataView _data;
        static void Main(string[] args)
        {
            _data = _mlContext.Data.LoadFromTextFile<CatInput>(path: "cat", hasHeader: false, separatorChar: ',');
            IEstimator<ITransformer> _pipeline = _mlContext.Transforms.Categorical.OneHotHashEncoding(
                inputColumnName: "input",
                outputColumnName: "output");
            
            var model = _pipeline.Fit(_data);
            IDataView tData = model.Transform(_data);
            var previewObject = tData.Preview(10);
        }
    }
}
```

input data:
```
                input                 |
---------------------------------------
                 red                  |
                 red                  |
                 red                  |
                 blue                 |
                purple                |
                yellow                |
                 red                  |
                 blue                 |
                 blue                 |
                purple                |
```
Screenshots of inspection and where the values should be different.
Row 0 ("red"):
![PreviewRow0](https://user-images.githubusercontent.com/27200279/70109206-45824d80-169f-11ea-9bb2-af28522283fd.png)
Row 3 ("blue"):
![PreviewRow1](https://user-images.githubusercontent.com/27200279/70109207-45824d80-169f-11ea-911d-535808367adc.png)

**Comment by yaeldekel** [comment]
Hi @thezaza101 , thanks for your feedback.

Notice that the debugger preview says that the object is a "Sparse vector of size 4, 1 explicit value". The way sparse vectors are represented internally is with two arrays: `_indices` and `_values`. Notices that in the first example `_indices[0]` is 0, and in the second `_indices[0]` is 1, meaning that the vector is indeed `[0,1,0,0]` like you expected it to be.
