### ISSUE TITLE
[DNN Training] Cannot execute retrain DNN model(Tensorflow model) manually since ML.NET 1.4.0-stable

### ISSUE THREAD

**Issue by yamachu** [dotnet/machinelearning#4520]
ref: https://github.com/dotnet/machinelearning/issues/4307

We cannot call `RetrainDnnModel` method publicly and manually because  of this commit ( https://github.com/dotnet/machinelearning/pull/4362 ).

I think that regression tasks by TensorflowRetrain (RetrainDnnModel ) only can predict multiple-values.
So I think that Access-Modifiers of `RetrainDnnModel` should be public if no way for predicting multiple-values.

**Comment by gvashishtha** [comment]
@frank-dong-ms

**Comment by frank-dong-ms** [comment]
RetrainDnnModel is marked as internal because it is not tested enough, we will reopen this until further testing
