### ISSUE TITLE
Image links broken

### ISSUE THREAD

**Issue by natke** [dotnet/machinelearning#4525]
There are two broken image links on this page. One for each metric description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1784ca5-56a4-75ea-ae35-ad29872348cf
* Version Independent ID: 2084e039-fcb3-61b4-08ae-29f509b8cb30
* Content: [RankingMetrics Class (Microsoft.ML.Data)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.data.rankingmetrics?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML.Data/RankingMetrics.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Data/RankingMetrics.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by gvashishtha** [comment]
@frank-dong-ms

**Comment by justinormont** [comment]
We should check why my previous fix for this didn't work. Is there a build step for the docs that we missed?

Previous PR: https://github.com/dotnet/machinelearning/pull/3840

**Comment by natke** [comment]
Ah ok, those changes have not been published. You can see the fixes in the preview docs: https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.data.rankingmetrics?view=ml-dotnet-latest&branch=smoke-test-preview. The live docs are built from the published nugets, and will be updated next time we do a release. Or we can add your changes manually to the live docs.

One question I have is why these are images and no latex formulae?

**Comment by justinormont** [comment]
You're right, LaTeX would be a better solution.

**Comment by frank-dong-ms** [comment]
Synced with @natke , @justinormont 's fix is merged at 10/3 and this fix should released last month, Natalie will check further and get back with more details

**Comment by natke** [comment]
This is fixed now.
