### ISSUE TITLE
Missing C# doc string for ChnageModelThreshold

### ISSUE THREAD

**Issue by rauhs** [dotnet/machinelearning#4527]
Linky:

https://github.com/dotnet/machinelearning/blob/3f98485e887177f2082f027c22f46fd64ebbe246/src/Microsoft.ML.Data/TrainCatalog.cs#L261-L267

**Comment by gvashishtha** [comment]
@frank-dong-ms

**Comment by frank-dong-ms** [comment]
Fix has been checked in.
