### ISSUE TITLE
InvalidDataException: End of Central Directory record could not be found. Error when loading custom trained model from Azure Blob Storage in ASP.NET Core Web API 

### ISSUE THREAD

**Issue by willvelida** [dotnet/machinelearning#4541]
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: .NET Core 3.0.1

### Issue

- **What did you do?**

I have trained a regression model and I have uploaded it to a container in Blob Storage. This is the method that I use to upload the model to blob storage:

`public async Task TrainAndUploadModelAsync(MLContext mlContext, string dataPath, CloudBlobContainer container)
{
IDataView dataView = mlContext.Data.LoadFromTextFile(dataPath, hasHeader: true, separatorChar: ',');

        var pipeline = mlContext.Transforms.CopyColumns("Label", "FareAmount")
            .Append(mlContext.Transforms.Categorical.OneHotEncoding("VendorIdEncoded", "VendorId"))
            .Append(mlContext.Transforms.Categorical.OneHotEncoding("RateCodeEncoded", "RateCode"))
            .Append(mlContext.Transforms.Categorical.OneHotEncoding("PaymentTypeEncoded", "PaymentType"))
            .Append(mlContext.Transforms.Concatenate("Features", "VendorIdEncoded", "RateCodeEncoded", "PassengerCount", "TripTime", "TripDistance", "PaymentTypeEncoded"))
            .Append(mlContext.Regression.Trainers.FastTree());

        var model = pipeline.Fit(dataView);

        using (var stream = new MemoryStream())
        {
            mlContext.Model.Save(model, dataView.Schema, stream);
            stream.Position = 0;
            await _azureStorageHelpers.UploadBlobToStorage(container, "Model.zip", stream);
        }
    }`
Now I'm trying to consume that model via a ASP.NET Core Web API like so:

services.AddPredictionEnginePool<TaxiTrip, TaxiTripFarePrediction>() .FromUri( modelName: "TaxiTripFarePredictionModel", uri: "https://velidastorage.blob.core.windows.net/mlmodels/model.zip", period: TimeSpan.FromSeconds(15));

Then I'm calling a POST Method to make a prediction on the following JSON payload

{ "VendorId": "VTS", "RateCode": "1", "PassengerCount": 1, "TripTime": 1140, "TripDistance": 3.75, "PaymentType": "CRD", "FareAmount": 0 }

And the POST Method:

`[HttpPost]
public ActionResult Post([FromBody] TaxiTrip input)
{
if (!ModelState.IsValid)
{
return BadRequest();
}

        TaxiTripFarePrediction prediction = _predictionEnginePool.Predict(modelName: "TaxiTripFarePredictionModel", example: input);

        string predictedFareAmount = prediction.FareAmount.ToString();

        return Ok(predictedFareAmount);
    }`

- **What happened?**

However, when I call the PredictionEnginePool.Predict() method, I get the following error:

System.FormatException: 'Failed to open a zip archive'. Inner Exception InvalidDataException: End of Central Directory record could not be found.

- **What did you expect?**

Expected the model to be consumed to make a prediction

I'm not sure where I am going wrong here. I'm wondering whether or not the model has been uploaded correctly, or whether the Web API is having difficulty downloading the blob.

### Source code / logs

Source code for API and Model Trainer can be found here

https://github.com/willvelida/PricePredictor

**Comment by gvashishtha** [comment]
@frank-dong-ms

**Comment by frank-dong-ms** [comment]
The exception means the model file you trying to open is corrupted. I believe the blob Uri is case sensitive so please try uri: "https://velidastorage.blob.core.windows.net/mlmodels/**Model.zip**", when you download model file.

**Comment by frank-dong-ms** [comment]
@willvelida  Also, I tried to write you model file into my own test blob container at https://frdongtest.blob.core.windows.net/container1/model.zip and consume that model at a web API project without issue. 

So, please:
 1. verify if the Uri you used is correct
 2. download model file manually and verify the model file is not corrupted

Please reach out if you still have more issue on this.

**Comment by AbhishekSanthanam** [comment]
I'm facing the same issue and the Uri seems to be correct and the model file is not corrupted after downloading
