### ISSUE TITLE
Format error in GetFormattedConfusionTable"

### ISSUE THREAD

**Issue by CBrauer** [dotnet/machinelearning#4542]
Hey,

I'm trying to print a confusion matrix on a binary classification model using:

`Console.WriteLine("Confusion Matrix:\n{0}", metrics.ConfusionMatrix.GetFormattedConfusionTable());
`

I get:

![image](https://user-images.githubusercontent.com/1317234/70378656-e3f8f380-18d7-11ea-8e96-e96fea095059.png)

Shouldn’t there be a comma here instead of a space?

Charles

**Comment by gvashishtha** [comment]
This error is most likely coming from this line: https://github.com/dotnet/machinelearning/blob/610ffcb67083c2e5e6e1a14884ba24b1da0384c7/src/Microsoft.ML.Data/Evaluators/EvaluatorUtils.cs#L1660

@CBrauer it is unlikely we will be fixing this soon, as it doesn't seem to be a breaking issue for data science workflows. Closing it for now, but please feel free to reopen if this impression is inaccurate.
