### ISSUE TITLE
Expose EvaluateWithPRCurve in BinaryClassificationCatalog

### ISSUE THREAD

**Issue by rauhs** [dotnet/machinelearning#4553]
Version: 1.4.0

This was once available: 122c31952829338e9cfa91ca72246af6e572a618

But now there is no way to access `EvaluateWithPRCurve`.

**Comment by gvashishtha** [comment]
Hi @rauhs, this feature is not currently on our roadmap and will be closed. Feel free to recruit some additional support in Gitter and we can consider reopening it https://gitter.im/dotnet/mlnet
