### ISSUE TITLE
BinaryClassification.Evaluate completely ignores the predicted labels

### ISSUE THREAD

**Issue by rauhs** [dotnet/machinelearning#4554]
Version: 1.4.0

I'm training a Binary LightGBM classifier and want to change the threshold of the model. This will change my predictions accordingly. Though, `BinaryClassification.Evaluate` will always return me the same precision/recall.

```C#
        var newModel = ctx.BinaryClassification.ChangeModelThreshold(model, -100_000);
        var dataView = newModel.Transform(dv);
        var labels = dataView.GetColumn<bool>("PredictedLabel").ToArray();

        var numTrue = labels.Count(x => x == true); // All are true.
        var numFalse = labels.Count(x => x == false); // 0

        testPerformance = ctx.BinaryClassification.Evaluate(dataView);
```

With the above threshold the labels are all `true`.

**Comment by yaeldekel** [comment]
Hi @rauhs , unfortunately, you are correct. The evaluator does not use the `PredictedLabel` value computed by the model, but instead computes its own predicted label using the model's `Score` or `Probability` column. The evaluator has options to specify a threshold and whether to use the score or the probability column to compute the predicted label, but these options are not exposed in the public API.
The fix to this problem would be to add a public `BinaryClassification.Evaluate()` API that exposes these parameters.

**Comment by gvashishtha** [comment]
Thanks @yaeldekel for your answer. @rauhs I will close this for now but if you want to add any additional details on your issue or try to recruit some support for this feature request in Gitter, please do so. https://gitter.im/dotnet/mlnet

**Comment by rauhs** [comment]
Sigh, look at the code. Most people would consider this a bug.

I guess I'll just implement the evaluation for myself...
