### ISSUE TITLE
cache elapsedSeconds error

### ISSUE THREAD

**Issue by saltywu** [dotnet/machinelearning#4566]
Method：Samples.Dynamic.Cache.TimeToScanIDataView
Line81：return (lines, columnAverage, elapsed.Seconds);

Recommend to:return (lines, columnAverage, elapsed.TotalMilliseconds);

**Comment by gvashishtha** [comment]
Hi @saltywu thanks for making this issue and using ML.NET. As of right now, this error message seems to be working fine. 

Feel free to implement this enhancement yourself and we can take a look. Just make sure to follow our contribution guide. https://github.com/dotnet/machinelearning/blob/master/CONTRIBUTING.md
