### ISSUE TITLE
Enable ML.NET to support open access healthcare models

### ISSUE THREAD

**Issue by hybridware** [dotnet/machinelearning#457]
Please update ML.NET so it will support existing open access healthcare datasets and add tools that would easily enable comparison of genomic data and overlapping data (which could be used to detect cancer patterns) pythons bedtools is a good example of this 
http://bedtools.readthedocs.io/en/latest/

Allow us to train our models using open datasets e.g. this example with azure ml.
https://blogs.msdn.microsoft.com/cdndevs/2016/05/31/getting-started-with-machine-learningwisconsin-breast-cancer-dataset/

**Comment by justinormont** [comment]
Greetings @hybridware,

Do you have  a list of parts which the project needs to add to support your open access heathcare datasets and genomic data? Additional details for the components which are missing would be useful.

For the Wisconsin Breast Cancer dataset, this actually [redistributed](https://github.com/dotnet/machinelearning/blob/c023727b76970ab913ec1ce38276508835c17bcf/test/data/README.md#breast-cancer-wisconsin) in the ML.NET repo and is used in many of our [tests](https://github.com/dotnet/machinelearning/search?p=1&q=breast+cancer&unscoped_q=breast+cancer).

**Comment by justinormont** [comment]
Greetings @hybridware,

Do you have  a list of parts which the project needs to add to support your open access heathcare datasets and genomic data? Additional details for the components which are missing would be useful.

In the linked example, it's using the Wisconsin Breast Cancer dataset, which is [redistributed](https://github.com/dotnet/machinelearning/blob/c023727b76970ab913ec1ce38276508835c17bcf/test/data/README.md#breast-cancer-wisconsin) in the ML.NET repo and is used in many of our [tests](https://github.com/dotnet/machinelearning/search?p=1&q=breast+cancer&unscoped_q=breast+cancer). The linked example on Azure Machine Learning also uses ML.NET code in the background. Or are you referring to lack of ability to read in the dataset? I think the original distributed format is a TSV format which ML.NET reads rather well (caveats are dataset w/ newlines within quoted strings, and some forms of escaping). 

In general, you can bring in any dataset. Though the components you need for featurization, or scoring could be missing.

**Comment by hybridware** [comment]
Hello Justin, Thank you. Yes, I am referring to the lack of ability to read different file formats...
examples of formats it should support are suggested below...

BED
BEDPE
GFF
Genome
SAM/BAM
VCF

This describes what these formats are and how they work better
http://bedtools.readthedocs.io/en/latest/content/general-usage.html

Any Bioinformatics Programming analysis techniques we can do in Python should have an equivalent in ML.NET As demonstrated in Oreilly's publication on this topic http://shop.oreilly.com/product/9780596154516.do

Many Data Science researchers come from a Python background, if they want to use C# as the chosen language, there should be a way to achieve carry out similar tasks or better.

**Comment by Ivanidzo4ka** [comment]
DRI RESPONSE: Currently we focused on CSV format and in memory data through IEnumerable<T>. I doubt we have plans to release additional readers for different formats prior v1.0. So I'm moving this issue to backlog.

**Comment by codemzs** [comment]
We don't plan on supporting this file formats anytime soon. Closing this as this is not even on our long term road map (i.e within the next year). In the meantime feel free to convert the dataset to csv or IEnumerable. ALSO, please consider using ML.NET's python binding called NimbusML.
