### ISSUE TITLE
LightLda documentation should be more specific.

### ISSUE THREAD

**Issue by ganik** [dotnet/machinelearning#458]
Currently it doesn't explain how trainer works and don't provide example how to use it

**Comment by bojanmisic** [comment]
Is it ok to port the example from here: https://github.com/Microsoft/LightLDA/tree/master/example? If it is, I'd like to take on that one.

**Comment by shauheen** [comment]
Thanks @bojanmisic . Please create a separate issue for your proposed work. I assume that the work will include adapting that example to be applicable in ML.NET.
