### ISSUE TITLE
Cannot delete image file passsed to PredictionEngine for Image Classification after disposing the engine

### ISSUE THREAD

**Issue by giuseppe-terrasi** [dotnet/machinelearning#4585]
### System information

- **OS version/distro**: Windows 10 Pro 10.0.18363
- **.NET Version (eg., dotnet --info)**:   3.1.0

### Issue

- **What did you do?**: I've tried to delete an image file used by PredictionEngine after disposing the engine
- **What happened?**: An exception was thorwn: "The process cannot access the file  because it is being used by another process."
- **What did you expect?**: Image file deletion

### Source code / logs
```
private ImagePrediction ClassifySingleImage(MLContext mLContext, ITransformer model, string imagePath)
{
    var imageData = new ImageData()
    {
        ImagePath = imagePath
    };
    var predictor = mLContext.Model.CreatePredictionEngine<ImageData, ImagePrediction>(model);
    var prediction = predictor.Predict(imageData);
    predictor.Dispose();
    System.IO.File.Delete(imagePath);  // throws a FileIO exception
    return prediction;
}
```

**Comment by giuseppe-terrasi** [comment]
Are there any updates on this issue?

**Comment by ganik** [comment]
I ll take a look, thx

**Comment by ganik** [comment]
@giuseppe-terrasi  I am not able to repro this with the latest code from master branch. I can see in code that path is loaded with using{ .... } statement before actual prediction happens (in \machinelearning\src\Microsoft.ML.ImageAnalytics\ImageLoader.cs : TryLoadDataIntoBuffer(..) method).  Could you try your code with the latest ML.NET from master branch. thx

**Comment by giuseppe-terrasi** [comment]
@ganik Sorry for the delay. I created a test solution [here](https://drive.google.com/open?id=1_iVToRKzA-aNFPTGBpI1P6KrCMGoWydV).
I used both nuget versions 1.4.0 and 1.5.0-preview with the same result. I also tried to compile the source from master branch but I received a compilation error.

**Comment by giuseppe-terrasi** [comment]
Are there any updates on this issue? Due to it I have a lot of temporary images uses by this code that I must delete manually after restarting the process. I can give more information if needed. Thanks.

**Comment by crvkumar** [comment]
This is not a solution to this issue but I faced the similar issue and ended up using ITransformer.Transform as an workaround for the prediction. 

Using PredictionEngine is cleaner but ITransfomer does not seem to lock files.

**Comment by giuseppe-terrasi** [comment]
@ganik  Still no updates?

**Comment by konabuta** [comment]
@ganik  My customer also encountered this issue.  Any update on this ?

**Comment by konabuta** [comment]
@ganik  No updates on this ?

**Comment by ganik** [comment]
@giuseppe-terrasi  @konabuta  Hi, sorry for delay and thank you for repro solution. I was able to find the rootcause in machinelearning\src\Microsoft.ML.ImageAnalytics\ImageLoader.cs, line 238:
                            dst = new Bitmap(path) { Tag = path };
BitMap locks the file. There are various approaches how to handle this as per: https://stackoverflow.com/questions/4803935/free-file-locked-by-new-bitmapfilepath
I ll investigate various solutions and will submit a fix shortly. Thx.
