### ISSUE TITLE
pipeline.Fit Method not responding on after 1046th row in dataset

### ISSUE THREAD

**Issue by smoothumut** [dotnet/machinelearning#4595]
I have a dataset with 3000 (BrandId, price) rows. When I run sdca regression algorithm in ML.net, pipeline.Fit method get stuck, it doesnt go to the next row in code (it keeps running but with %0 cpu usage). I thought the data may have problem, then I reduced the data. But when I remove until 1046, it starts working, but when I add one more row, it stops responding. The data looks normal, nothing is abnormal in my opionion
you can find the issue in my question at stackoverflow
[you can find the code and dataset in this link](https://stackoverflow.com/questions/59404619/ml-net-pipeline-fit-not-responding-after-specific-row-number-in-d)

**Comment by mveeris** [comment]
Hi @smoothumut, I had the same issue but with image classification. When I had 1046 or less images then it all worked. Strange that the solution in my case was to use console application instead of WinForms. 
https://github.com/dotnet/machinelearning/issues/4558

**Comment by najeeb-kazmi** [comment]
Hi @smoothumut - I see that you removed your question on stackoverflow (page not found). Did @mveeris 's suggestion solve your issue?

**Comment by smoothumut** [comment]
Hi @najeeb-kazmi  , here I have undelete the post, you can find the issue in
https://stackoverflow.com/questions/59404619/ml-net-pipeline-fit-not-responding-after-specific-row-number-in-dataset

**Comment by frank-dong-ms** [comment]
@smoothumut Hi, I tried to create a console app project, using the code sample (made some modification to let code compile and running) and data you provided but don't have repro on the hanging. 
Could you please provide a repro project?

**Comment by frank-dong-ms** [comment]
Didn't hear back with more details, please reopen this issue if necessary.
