### ISSUE TITLE
SEE LINK https://dotnet.microsoft.com/learn/ml-dotnet/what-is-mldotnet

### ISSUE THREAD

**Issue by jigarhshah17** [dotnet/machinelearning#4599]
### System information

- **OS version/distro**:

- **.NET Version (eg., dotnet --info)**: 
ML.NET 1.4.0

### Issue
SEE LINK https://dotnet.microsoft.com/learn/ml-dotnet/what-is-mldotnet

in test code below line write wrong

var predEngine = mlContext.Model.CreatePredictionEngine(model); 

in framework CreatePredictionEngine definition not same as above line.
 

- **What did you do?**
- **What happened?**
- **What did you expect?**

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by yaeldekel** [comment]
Hi @jigarhshah17 ,
[This](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Data/Model/ModelOperationsCatalog.cs#L312-L318) is the API that is in the documentation you mentioned above. `model` is an `ITransformer`, so the call matches the signature (since all the other parameters are optional):

```
        public PredictionEngine<TSrc, TDst> CreatePredictionEngine<TSrc, TDst>(ITransformer transformer,
            bool ignoreMissingColumns = true, SchemaDefinition inputSchemaDefinition = null, SchemaDefinition outputSchemaDefinition = null)
```

**Comment by yaeldekel** [comment]
Hi @jigarhshah17 ,
I hope my comment above answers your question about the documentation. I am closing the issue, please feel free to re-open or to create a new issue if you are still experiencing problems.
