### ISSUE TITLE
Not finding assembly for Microsoft.ML 

### ISSUE THREAD

**Issue by webtrainingroom** [dotnet/machinelearning#4607]
### System information

- **OS version: Windows 10 (64)
- **.NET Version : .Net Core 3.1

### Issue
I have installed ML.Net, I am trying to build a simple ML app using default template in VS 2019, 
After completing all five steps (Scenario, Data, Train, Evaluate, Code) successfully when it generate some code, I am not able to compile the code because the assembly Microsoft.ML is missing
I tried to install the assembly using Nuget but not find the assembly, (though I see  ML.NET Model Builder is installed )

I need Microsoft.ML assembly version 1.4.0 , but not finding any. please guide 

### Source code / logs
Please take a look at the attached screenshot 
![ml-net-not-found](https://user-images.githubusercontent.com/37655243/71594028-3090c100-2b5c-11ea-84d1-062cfe89f96a.png)

**Comment by najeeb-kazmi** [comment]
Hi @webtrainingroom - thanks for reporting this to us. Unfortunately, I could not reproduce the issue on my end. I tried creating a console app on VS2019 using model builder, and the code generated for me compiles correctly. Can you provide more details on exactly what you tried to do, and the error message you are seeing?

**Comment by webtrainingroom** [comment]
Hello Najeeb, thanks for your response, please look at the attached ppt file with all details, I am also attaching the complete source code for you.  

[MLAppCsharp.zip](https://github.com/dotnet/machinelearning/files/4011889/MLAppCsharp.zip)

[ml--dotnet-issue.pptx](https://github.com/dotnet/machinelearning/files/4011883/ml--dotnet-issue.pptx)

**Comment by najeeb-kazmi** [comment]
@webtrainingroom I see on slide 9 that your package source "Microsoft Visual Studio Offline Packages", which is typically a local directory. If the nugets are not present there, VS will show the error that you're seeing.

Can you try adding another package source for nuget.org and try installing from there? The feed source is https://api.nuget.org/v3/index.json

**Comment by webtrainingroom** [comment]
Hello Najeeb, Thank you very much for rightly pointed out and your quick response!

Yes, after changing the package source to https://api.nuget.org/v3/index.json it worked, but this is something new in visual studio 2019, in earlier version all nuget packages used to be downloaded from live by default. 

Thanks again!

**Comment by najeeb-kazmi** [comment]
Glad to know it worked. I think you have to add a package source once for a new installation of VS. Subsequent VS 2019 projects would have this source configured already now that you have added this to VS.
