### ISSUE TITLE
[AutoML] the "Label" column was not found

### ISSUE THREAD

**Issue by karuzzo** [dotnet/machinelearning#4619]
System information

- **OS version/distro**: Win 10
- **.NET Version (eg., dotnet --info)**: .NET Framework 4.8

### Issue

- **What did you do?**
 i use this code:
`MLContext mlContext = new MLContext();
            ColumnInferenceResults columnInference = mlContext.Auto().InferColumns(fname_train, labelColumnIndex: 0, hasHeader: false, separatorChar: ';') ;
            TextLoader textLoader = mlContext.Data.CreateTextLoader(columnInference.TextLoaderOptions);
            IDataView trainDataView = textLoader.Load(fname_train);
            IDataView testDataView = textLoader.Load(fname_test);
            IDataView validDataView = textLoader.Load(fname_valid);
            
            ColumnInformation columnInformation = columnInference.ColumnInformation;
            
            var experimentSettings = new MulticlassExperimentSettings();
            experimentSettings.MaxExperimentTimeInSeconds = MyExperimentTime;
            experimentSettings.CancellationToken = cts.Token;          
            experimentSettings.OptimizingMetric = MulticlassClassificationMetric.MacroAccuracy;
            experimentSettings.CacheDirectory = null;
            
            var progressHandler = new MulticlassExperimentProgressHandler();
            progressHandler.EventUpdateMulticlassExperiment += TextBoxNewDataMulticlassExperiment;            
            
            ExperimentResult<MulticlassClassificationMetrics> experimentResult = mlContext.Auto()
                .CreateMulticlassClassificationExperiment(experimentSettings)
                .Execute(trainDataView, validDataView, columnInformation, progressHandler: progressHandler);`
to generate the model successfully
- **What happened?**
When I load the model by this code
`public ObservableCollection<MLmodel> MLmodels { get; set; }
        private MLContext mlContext = new MLContext();
        DataViewSchema modelInputSchema;

        private Dictionary<string, PredictionEngine<BarLoadBinary, BarLoadBinaryPrediction>> binaryDictionary = new Dictionary<string, PredictionEngine<BarLoadBinary, BarLoadBinaryPrediction>>();
        private Dictionary<string, PredictionEngine<BarLoadMulti, BarLoadMultiPrediction>> multiDictionary = new Dictionary<string, PredictionEngine<BarLoadMulti, BarLoadMultiPrediction>>();
        private Dictionary<string, PredictionEngine<BarLoadRegression, BarLoadRegressionPrediction>> regressionDictionary = new Dictionary<string, PredictionEngine<BarLoadRegression, BarLoadRegressionPrediction>>();

        public Listener (ObservableCollection<MLmodel> mlModels, string ip, string port)
        {
            MLmodels = mlModels;
            IPadress = ip;
            Port = port;

            try
            {
                foreach (var model in MLmodels)
                {
                    ITransformer loadedModel = mlContext.Model.Load(model.FileNameModel, out DataViewSchema modelInputSchema);

                    if (model.TitleModel == "Binary Classification")
                        binaryDictionary.Add(model.PostfixModel, mlContext.Model.CreatePredictionEngine<BarLoadBinary, BarLoadBinaryPrediction>(loadedModel));
                    if (model.TitleModel == "Multi-class Classification")
                        multiDictionary.Add(model.PostfixModel, mlContext.Model.CreatePredictionEngine<BarLoadMulti, BarLoadMultiPrediction>(loadedModel));
                    if (model.TitleModel == "Regression")
                        regressionDictionary.Add(model.PostfixModel, mlContext.Model.CreatePredictionEngine<BarLoadRegression, BarLoadRegressionPrediction>(loadedModel));
                }
            }
            catch (Exception ex) { MessageBox.Show(ex.ToString()); }

            ipPoint = new IPEndPoint(IPAddress.Parse(IPadress), Convert.ToInt32(Port));
            
        }`
, I get an error saying that the "Label" column was not found
- **What did you expect?**
I expected full application of models

![issue](https://user-images.githubusercontent.com/18124355/71646139-e6821980-2cda-11ea-9804-10bf533cac4d.PNG)
![issue2](https://user-images.githubusercontent.com/18124355/71646140-e6821980-2cda-11ea-8253-4e6c1307b94c.PNG)
![issue3](https://user-images.githubusercontent.com/18124355/71646142-e71ab000-2cda-11ea-9e0d-2f82f948f8fe.PNG)

**Comment by LittleLittleCloud** [comment]
In `ColumnInference` API, if a dataset has no header( or user set hasHeader flag to false )and a user uses label index to set label, the label will default to name "Label" and the other column name will be default to "col1", "col2" and so on. While when calling `PredictionEngine<ModelInput, ModelOutput>`, If `ModelInput` class doesn't have a `label` property, it will grumble about can't find the right input column. 

In your case, you can try to give dataset a header with which has the same property of `ModelInput`, . (`BarLoadBinary`) in your case, or if you want to make a "general" predict engine, you can also call model's `transform` method directly to get the prediction result.

Hope this can help you

**Comment by karuzzo** [comment]
Thanks a lot friend, this solved my problem
