### ISSUE TITLE
image classification needs cancel

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning#4632]
Hi, is there any plan to add cancel support for image classification API so that we can cancel an image classification training by passing in a cancellation token? 

[related issue](https://app.zenhub.com/workspaces/mlnet-tools-5cde1c97e3106e39e8ae08fc/issues/dotnet/machinelearning-modelbuilder/413)

**Comment by antoniovs1029** [comment]
Hi @LittleLittleCloud , so it's still not clear to me what is being asked, and so if it would be a quick fix or a major feature request.

Can you please share code (and perhaps a dataset) where you "cancel and switch to another scenario" (as mentioned in the issue you've linked to)? I would like to know how you're currently cancelling the training.

Particularly, it's strange that you mention that there's a lot of memory being used and that's not released after cancelling. Perhaps you are pointing to a memory leak?

Thanks.

**Comment by LittleLittleCloud** [comment]
It's not a memory leak, the thing is our program allows user to cancel training after it start, But we can't stop an image training after it starts because current Image Classification API doesn't support cancellation token.

The way we use Image Classification is through AutoML, there's a trainer in MulticlassificationExperiment call , and that's how it be called

**Comment by codemzs** [comment]
This should be an easy fix. Please refer to the below PRs where we have added cancellation mechanism in other trainers. You can invoke cancellation via mlcontext cancel function that is exposed in experimental nuget. First, someone needs go add cancellation checkpoints, test, verify with model builder, commit, ship.


https://github.com/dotnet/machinelearning/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+cancellation++

**Comment by antoniovs1029** [comment]
Would do what @codemzs has just said (to expose cancelation via [mlContext.CancelExecution()](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Experimental/MLContextExtensions.cs)) be enough for you, @LittleLittleCloud ?

**Comment by LittleLittleCloud** [comment]
If we can cancel using CancelExecution() that also works. ( As long as there's a way to cancel training)

**Comment by codemzs** [comment]
Yep, we will need to add a check point in the training loop, it’s just few lines of change plus testing.

**Comment by antoniovs1029** [comment]
Ok, so I will work on this. Thanks for your suggestions, @codemzs !
