### ISSUE TITLE
Misc misspellings

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning#4638]
Queries which bring up misspellings:
- (45) https://github.com/dotnet/machinelearning/search?q=occurence
- (9) https://github.com/dotnet/machinelearning/search?q=accomodate
- (7) https://github.com/dotnet/machinelearning/search?q=occured
- (6) https://github.com/dotnet/machinelearning/search?q=becuase
- (5) https://github.com/dotnet/machinelearning/search?q=begining
- (2) https://github.com/dotnet/machinelearning/search?q=neccessary
- (2) https://github.com/dotnet/machinelearning/search?q=publically
- (2) https://github.com/dotnet/machinelearning/search?q=accomodated
- (2) https://github.com/dotnet/machinelearning/search?q=preceeding
- (2) https://github.com/dotnet/machinelearning/search?q=acheived
- (2) https://github.com/dotnet/machinelearning/search?q=mantains 
- (2) https://github.com/dotnet/machinelearning/search?q=entrypy
- (1) https://github.com/dotnet/machinelearning/search?q=definitly
- (1) https://github.com/dotnet/machinelearning/search?q=realy
- (1) https://github.com/dotnet/machinelearning/search?q=seperate
- (1) https://github.com/dotnet/machinelearning/search?q=orignal
- (1) https://github.com/dotnet/machinelearning/search?q=diffrence
- (1) https://github.com/dotnet/machinelearning/search?q=untill
- (1) https://github.com/dotnet/machinelearning/search?q=sucessfully

Wikipedia [list](https://en.wikipedia.org/wiki/Commonly_misspelled_English_words) was used to create regex:
```bash
grep -nIiR --color=always --exclude-dir={packages,bin,Tools,./test/BaselineOutput/Common/Text,./test/BaselineOutput/SingleRelease/Text,./test/BaselineOutput/SingleDebug/Text,./test/data} -E "abcense|absance|acceptible|accidentaly|accomodate|acommodate|acheive|acknowlege|aknowledge|acquaintence|aquaintance|aquire|adquire|aquit|acrage|acerage|adultary|adviseable|advizable|agression|agressive|allegaince|allegience|alegiance|allmost|amatuer|amature|annualy|apparant|aparent|arguement|athiest|awfull|aweful|becuase|beatuful|becomeing|begining|beleive|bellweather|bouy/bouyant|buisness|calender|camoflage|camoflague|Carribean|catagory|cauhgt|caugt|cemetary|cematery|changable|collaegue|collegue|comming|commited|comitted|comparsion|conceed|congradulate|consciencious|concious|consious|concensus|contraversy|cooly|dacquiri|daquiri|decieve|definate|definitly|definately|defiantly|desparate|diffrence|dilema|dissapoint|disasterous|drunkeness|dumbell|embarass|equiptment|excede|exilerate|existance|experiance|extreem|facinating|firey|flourescent|foriegn|freind|gratefull|greatful|garantee|garentee|garanty|guidence|harrass|heighth|heigth|heirarchy|hors derves|ordeurves|humerous|hygene|hygine|hiygeine|higeine|hygeine|hipocrit|ignorence|immitate|imediately|independant|indispensible|innoculate|inteligence|intelligance|jewelery|kernal|liesure|liason|libary|liberry|lisence|lightening|maintainance|maintnance|mantain|medeval|medevil|mideval|millenium|milennium|miniture|miniscule|mischievious|mischevous|mischevious|mispell|misspel|neccessary|necessery|neice|nieghbor|noticable|occassion|occasionaly|occassionally|occurrance|occurence|occured|ommision|omision|orignal|outragous|parliment|passtime|pasttime|percieve|perseverence|personell|personel|plagerize|playright|playwrite|posession|possesion|potatos|preceed|presance|privelege|priviledge|professer|promiss|pronounciation|prufe|prophesy|publically|quarentine|questionaire|questionnair|readible|realy|recieve|reciept|recomend|reccommend|refered|referance|refrence|relevent|revelant|religous|religius|repitition|restarant|restaraunt|rythm|rythem|secratary|secretery|sieze|seperate|sargent|similer|skilfull|speach|speeche|succesful|sucessful|supercede|suprise|surprize|tomatos|tommorow|tommorrow|twelth|tyrany|underate|untill|upholstry|vaccuum|vaccum|vacume|vehical|visious|wether|wierd|wellfare|welfair|wether|wilfull|withold|writting|writeing" .
```

**Comment by justinormont** [comment]
@MaherJendoubi -- Your recent PRs for typos inspired me to make a more full list of misspellings. Thanks for putting all of those in. If you're up for it you're welcome to take on more, like the above list. Others are more than welcome too.

**Comment by MaherJendoubi** [comment]
@justinormont My pleasure, I start fixing them.

**Comment by MaherJendoubi** [comment]
@justinormont each time I run the grep I get grep: .`: No such file or directory

**Comment by MaherJendoubi** [comment]
Dear community, I am working on following item : 

- [ ] (45) https://github.com/dotnet/machinelearning/search?q=occurence

**Comment by justinormont** [comment]
I added:
* (2) https://github.com/dotnet/machinelearning/search?q=mantains

**Comment by MaherJendoubi** [comment]
@justinormont done

- [ ] (2) https://github.com/dotnet/machinelearning/search?q=mantains

- [ ] (2) https://github.com/dotnet/machinelearning/search?q=entrypy
