### ISSUE TITLE
FastTree doesnt support changing default calibrator .

### ISSUE THREAD

**Issue by vnarula** [dotnet/machinelearning#4643]
### System information

- **OS version/distro**: Windows 
- **.NET Version (eg., dotnet --info)**:  .NET core

### Issue

- **What did you do?** Using FastTree model for fraud protection.
- **What happened?** FastTree uses default calibrator FixedPlatCailberator and Data Scientist want to use different calibrator and additional calibrator is not same as using just one calibrator , 
- **What did you expect?**
so there must have requirement is to just able to use one calibrator .

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by antoniovs1029** [comment]
Hi, @vnarula . Thanks for opening this feature request.

As I suggested you offline, currently there's no way to change the calibrator returned by the FastTree trainer. You could only add one calibrator on top of the pipeline, like this:

`var pipeline = ML.BinaryClassification.Trainers.FastTree().Append(ML.BinaryClassification.Calibrators.Platt());`

As you mention here, adding ad "additional calibrator is not same as using just one calibrator". I still don't understand why is it the case for you that adding a new calibrator isn't desired. Can you please clarify this? Thanks!

**Comment by justinormont** [comment]
Adding another calibrator on top of an existing calibrator should work correctly. 

I would have to review the code, but my expectation is the calibrator doesn't modify the `Score` column, which is the input to a calibrator. The calibrator then produces a `Probability` column. Adding a second calibrator should only overwrite (hide) the existing `Probability` column.  -- I'd recommend verifying the `Score` column is untouched, as reality may not match my expectation.

**Comment by antoniovs1029** [comment]
Hi, @justinormont , I've tested this (adding another calibrator at the end of the pipeline) and what happens is what you've just said, that it adds another Probability column (hiding the previous one) and not modifying the Score column  That's why I still think that this should be enough.

**Comment by najeeb-kazmi** [comment]
@vnarula - as @antoniovs1029 has explained, you can add another calibrator in addition to the one already present. This new calibrator will take the `Score` column and produce a `Probability` column, while hiding the previous `Probability` column. If you want to see both Probability columns, you can rename the one produced by `FastTree` and then append a new calibrator like so:

```csharp
var mlContext = new MLContext();
var pipeline = 
    mlContext.BinaryClassification.Trainers.FastTree()
    // Copy the Probability column produced by FastTree. At this point, You have two identical
    // columns "ProbabilityFromFastTree" and "Probability"
    .Append(mlContext.Transforms.CopyColumns("ProbabilityFromFastTree", "Probability"))
    // Create a new "Probability" column with custom calibrator. This overwrites (hides) the previous
    // "Probability" column, giving you "ProbabilityFromFastTree" and the unhidden "Probability"
    // column with probabilities from the custom calibrator.
    .Append(mlContext.BinaryClassification.Calibrators.Platt());
```

Note that the default calibrator used in FastTree is consistent with the interpretation of probability in the LambdaMART algorithm implemented by `FastTree`, described in [this paper](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/MSR-TR-2010-82.pdf). Section 6, equation 13 describes the probability formulation as `1/{1 + exp[-2*sigma*F(x)]}`, where `F(x)` is the score produced by `FastTree`. In this sense, the default calibrator in `FastTree` is the "correct" way to obtain probabilities. Of course, it is up to you to add another calibrator.

I'm closing this issue as I believe your question on how to add custom calibrator has been answered. Please fee free to reopen the issue if you have any unresolved concerns.

cc: @justinormont
