### ISSUE TITLE
Q: Correct params for Timeseries analysis

### ISSUE THREAD

**Issue by lefig** [dotnet/machinelearning#4658]
Hi all,

I would appreciate checking my interpretation of the explanatory code comments for the following parameters used for time series analysis.

The example uses daily data and has:
var forecastingPipeline = mlContext.Forecasting.ForecastBySsa(
     windowSize: 7,
    seriesLength: 30,
    trainSize: 365,
    horizon: 7,
   
Is there a specific reason to use 30 (a month) and 7 (a week)? Also the trainSize is 365. Does this simply equate to the 365 samples used for training or represent days in a year?

Thanks!

Fig

**Comment by najeeb-kazmi** [comment]
@lefig can you please link the sample you are referring to?

**Comment by najeeb-kazmi** [comment]
@lefig I could not find a sample in this repo or the machinelearning-samples repo with this example. Without looking at a sample, here is what I can say:

- windowSize specifies how much lag to build lag vectors for. The lagged vectors make up the trajectory matrix which is decomposed by the SSA algorithm (parameter L in [section 2.1.1](https://arxiv.org/pdf/1206.6910.pdf)). This probably does not have anything to do with a week, just used to illustrate its use.
- `seriesLength` specifies an upper bound on the size of the largest seasonality in the input time series, and must satisfy 2 < `seriesLength` < `trainSize`/2. This is likely specifying a monthly seasonality.
- `trainSize` is most likely related to year. The SSA model is learned for the first n points in the time series, so this likely represents a year's worth of training data.
- `horizon` is just the number of points in future that you want to forecast. This is most likely demonstrating a use case to forecast for a week, but can be anything you want depending on your scenario.

Please reopen the issue if something remains unanswered.
