### ISSUE TITLE
Domain request for ML.net 

### ISSUE THREAD

**Issue by salmanmkc** [dotnet/machinelearning#4677]
Would be great if Microsoft has the domain ml.net to link to https://dotnet.microsoft.com/apps/machinelearning-ai/ml-dotnet because at the moment ml.net is unresolved, but asp.net redirects.

**Comment by yaeldekel** [comment]
Unfortunately this cannot be done, see issue #3686 ...

**Comment by salmanmkc** [comment]
Oh, I think it used to be used by someone, however, now the domain is unresolved

**Comment by codemzs** [comment]
![image](https://user-images.githubusercontent.com/1211949/72829034-c509b300-3c32-11ea-92d2-b5e4168bdbc6.jpg)

**Comment by salmanmkc** [comment]
Oh wow, I see, closing this.
