### ISSUE TITLE
How to load data from variable?

### ISSUE THREAD

**Issue by ErcinDedeoglu** [dotnet/machinelearning#469]
Hi,
I want to load data from memory, so I can connect it with sql server, webservice etc.

`pipeline.Add(new TextLoader(dataPath).CreateFrom<IrisData>(separator: ','));`
but this is only method that I can find! It only works with file on the disk!

I want to add data from variable like:
`string x = "116.76000,0.00000,116.76000,0.00000,116.76000,UP"`

I hope it is possible right now?

Thanks advance!

**Comment by jwood803** [comment]
If you're getting data from SQL or a web service and they are of `IList`, then the `CollectionDataSource` should be what you need.

There's an example in the [0.2 release blog post](https://blogs.msdn.microsoft.com/dotnet/2018/06/05/announcing-ml-net-0-2/):

```csharp
var pipeline = new LearningPipeline();
var data = new List() {
           new IrisData { SepalLength = 1f, SepalWidth = 1f 
                         ,PetalLength=0.3f, PetalWidth=5.1f, Label=1},
           new IrisData { SepalLength = 1f, SepalWidth = 1f 
                         ,PetalLength=0.3f, PetalWidth=5.1f, Label=1},
           new IrisData { SepalLength = 1.2f, SepalWidth = 0.5f 
                         ,PetalLength=0.3f, PetalWidth=5.1f, Label=0}
           };
var collection = CollectionDataSource.Create(data);
pipeline.Add(collection); 
```

Hope that helps!

**Comment by ErcinDedeoglu** [comment]
Thank you very much!
