### ISSUE TITLE
AutoML: Binary classification - AUC is not defined

### ISSUE THREAD

**Issue by lefig** [dotnet/machinelearning#4692]
Hi,

I am struggling with this baffling exception. My data label is binary and I have 1,0 in the csv. I am sure that I have enough data and the splitter is able training and testing data to include positive values.

Is there anything that I can try?

Thanks

=============== Running AutoML experiment ===============
#########################################################
Running AutoML bin classification experiment...
Press any key to stop the experiment run...
|     Trainer                              Accuracy      AUC    AUPRC  F1-score  Duration                        |
Exception during AutoML iteration: System.ArgumentOutOfRangeException: AUC is not defined when there is no positive class in the data
Parameter name: PosSample
   at Microsoft.ML.Data.EvaluatorBase`1.AucAggregatorBase`1.ComputeWeightedAuc(Double& unweighted)
   at Microsoft.ML.Data.BinaryClassifierEvaluator.Aggregator.Finish()
   at Microsoft.ML.Data.BinaryClassifierEvaluator.<>c__DisplayClass32_0.<GetAggregatorConsolidationFuncs>b__0(UInt32 stratColKey, ReadOnlyMemory`1 stratColVal, Aggregator agg)
   at Microsoft.ML.Data.EvaluatorBase`1.ProcessData(IDataView data, RoleMappedSchema schema, Func`2 activeColsIndices, TAgg aggregator, AggregatorDictionaryBase[] dictionaries)
   at Microsoft.ML.Data.EvaluatorBase`1.Microsoft.ML.Data.IEvaluator.Evaluate(RoleMappedData data)
   at Microsoft.ML.Data.BinaryClassifierEvaluator.Evaluate(IDataView data, String label, String score, String predictedLabel)
   at Microsoft.ML.AutoML.BinaryMetricsAgent.EvaluateMetrics(IDataView data, String labelColumn)
   at Microsoft.ML.AutoML.RunnerUtil.TrainAndScorePipeline[TMetrics](MLContext context, SuggestedPipeline pipeline, IDataView trainData, IDataView validData, String labelColumn, IMetricsAgent`1 metricsAgent, ITransformer preprocessorTransform, FileInfo modelFileInfo, DataViewSchema modelInputSchema, IChannel logger)

**Comment by yaeldekel** [comment]
Hi @lefig , would you be able to share your data so that we can investigate?

**Comment by lefig** [comment]
Hi @yaeldekel ,

Thank you for your kind help. I have a feeling that the problem could be with the Datetime field but am not sure. The binary label is Direction.


Date | Ticks | Close | Open | High | Low | Direction | STO_FastStoch | STO_StochK | STO_StochD | STO | CCI_TypicalPriceAvg | CCI_TypicalPriceMAD | CCI | RSIDown | RSIUp | RSI | MOM | ADX_PositiveDirectionalIndex | ADX_NegativeDirectionalIndex | ADX | CMO
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
11/10/2019 00:00:00 | 87264000000000 | 1.23264 | 1.225724 | 1.24687 | 1.21948 | 1 | 48.04673238 | 30.40186457 | 35.14956355 | 48.04673238 | 1.22981028 | 0.00264245 | 80.38964907 | 0.00140417 | 0.00128167 | 47.71951598 | -0.00147 | 22.54911993 | 16.87474601 | 15.66406838 | 0.8832388
12/10/2019 00:00:00 | 88128000000000 | 1.25476 | 1.229182 | 1.27061 | 1.24081 | 1 | 69.00058674 | 44.63254684 | 35.41053199 | 69.00058674 | 1.23174028 | 0.00455088 | 346.49792979 | 0.00119583 | 0.003125 | 72.32401157 | 0.02315 | 31.40814565 | 13.13496288 | 17.77736196 | 39.22025408


[GBPUSD-1440-Momentum_01061233_test.txt](https://github.com/dotnet/machinelearning/files/4105784/GBPUSD-1440-Momentum_01061233_test.txt)


Date | Ticks | Close | Open | High | Low | Direction | STO_FastStoch | STO_StochK | STO_StochD | STO | CCI_TypicalPriceAvg | CCI_TypicalPriceMAD | CCI | RSIDown | RSIUp | RSI | MOM | ADX_PositiveDirectionalIndex | ADX_NegativeDirectionalIndex | ADX | CMO
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
11/10/2019 00:00:00 | 87264000000000 | 1.23264 | 1.225724 | 1.24687 | 1.21948 | 1 | 48.04673238 | 30.40186457 | 35.14956355 | 48.04673238 | 1.22981028 | 0.00264245 | 80.38964907 | 0.00140417 | 0.00128167 | 47.71951598 | -0.00147 | 22.54911993 | 16.87474601 | 15.66406838 | 0.8832388
12/10/2019 00:00:00 | 88128000000000 | 1.25476 | 1.229182 | 1.27061 | 1.24081 | 1 | 69.00058674 | 44.63254684 | 35.41053199 | 69.00058674 | 1.23174028 | 0.00455088 | 346.49792979 | 0.00119583 | 0.003125 | 72.32401157 | 0.02315 | 31.40814565 | 13.13496288 | 17.77736196 | 39.22025408
14/10/2019 00:00:00 | 89856000000000 | 1.2594 | 1.241971 | 1.27061 | 1.24081 | 1 | 78.07549384 | 65.04093765 | 46.69178302 | 78.07549384 | 1.23409167 | 0.00735833 | 207.00641752 | 0.00096333 | 0.00351167 | 78.47299814 | 0.03058 | 26.39902697 | 11.04013727 | 19.71454773 | 44.16243966
15/10/2019 00:00:00 | 90720000000000 | 1.26028 | 1.250685 | 1.26494 | 1.25155 | 1 | 79.79659691 | 75.62422583 | 61.76590344 | 79.79659691 | 1.23644472 | 0.01032042 | 145.2048035 | 0.00096333 | 0.00348667 | 78.35205993 | 0.03028 | 24.48490208 | 10.23964558 | 21.49030136 | 45.08627448
16/10/2019 00:00:00 | 91584000000000 | 1.2693 | 1.255481 | 1.27992 | 1.26025 | 1 | 82.42885506 | 80.10031527 | 73.58849292 | 82.42885506 | 1.23995444 | 0.0135437 | 147.02472107 | 0.000805 | 0.00423833 | 84.03833443 | 0.0412 | 29.86396299 | 9.17369078 | 24.11617698 | 53.65944651
17/10/2019 00:00:00 | 92448000000000 | 1.27278 | 1.262392 | 1.28768 | 1.25155 | 1 | 78.15249267 | 80.12598155 | 78.61684088 | 78.15249267 | 1.24352889 | 0.01568426 | 115.36454336 | 0.000805 | 0.00450917 | 84.8518112 | 0.04445 | 24.70963197 | 11.74637573 | 25.06971458 | 56.51667296
18/10/2019 00:00:00 | 93312000000000 | 1.28571 | 1.267585 | 1.2989 | 1.27485 | 1 | 83.39209267 | 81.32448013 | 80.51692565 | 83.39209267 | 1.24794167 | 0.01843111 | 139.4200627 | 0.000805 | 0.00521333 | 86.62420382 | 0.0529 | 26.89568902 | 10.33903675 | 26.68604016 | 65.21095613
19/10/2019 00:00:00 | 94176000000000 | 1.28928 | 1.276646 | 1.2989 | 1.27485 | 1 | 87.88718207 | 83.14392247 | 81.53146138 | 87.88718207 | 1.25256444 | 0.01966037 | 119.06260008 | 0.00079667 | 0.00551083 | 87.36953362 | 0.05657 | 24.0066295 | 9.22844641 | 28.16767195 | 67.18707993
21/10/2019 00:00:00 | 95904000000000 | 1.29183 | 1.282961 | 1.29497 | 1.28732 | 1 | 87.8292305 | 86.36950175 | 83.61263478 | 87.8292305 | 1.25752222 | 0.01997 | 113.00654686 | 0.00072583 | 0.00572333 | 88.74531593 | 0.05997 | 23.14395626 | 8.8968241 | 29.52583442 | 68.57788907
22/10/2019 00:00:00 | 96768000000000 | 1.29419 | 1.287395 | 1.3012 | 1.28871 | 1 | 88.3921179 | 88.03617682 | 85.84986701 | 88.3921179 | 1.26283111 | 0.02062389 | 103.01609963 | 0.00065 | 0.00592 | 90.1065449 | 0.06324 | 24.75221963 | 8.36164815 | 31.19014864 | 69.86738468
23/10/2019 00:00:00 | 97632000000000 | 1.29311 | 1.290793 | 1.3012 | 1.28617 | 0 | 83.70594159 | 86.64243 | 87.01603619 | 83.70594159 | 1.26854111 | 0.01907259 | 87.21842473 | 0.00026167 | 0.00592 | 95.76705311 | 0.0679 | 22.94066013 | 8.9865169 | 32.23314963 | 66.45712683
24/10/2019 00:00:00 | 98496000000000 | 1.28928 | 1.29195 | 1.29213 | 1.28408 | 0 | 75.99194361 | 82.6966677 | 85.79175817 | 75.99194361 | 1.27391444 | 0.01645667 | 59.07321135 | 0.00040917 | 0.00592 | 93.53522054 | 0.06613 | 21.89060166 | 9.63459375 | 32.78679264 | 54.4605235
25/10/2019 00:00:00 | 99360000000000 | 1.28727 | 1.290615 | 1.29493 | 1.2788 | 0 | 71.94360524 | 77.21383014 | 82.18430928 | 71.94360524 | 1.27841472 | 0.01338727 | 42.75344526 | 0.00057667 | 0.00512917 | 89.89338396 | 0.05463 | 20.0979553 | 11.52623344 | 32.3133061 | 48.33984497
26/10/2019 00:00:00 | 100224000000000 | 1.28509 | 1.288943 | 1.29493 | 1.2788 | 0 | 38.86148008 | 62.26567631 | 74.05872472 | 38.86148008 | 1.28098806 | 0.01126593 | 31.27588928 | 0.00075833 | 0.00328583 | 81.24871214 | 0.03033 | 18.44973374 | 10.58097378 | 31.87927677 | 41.69645056



Date | Ticks | Close | Open | High | Low | Direction | STO_FastStoch | STO_StochK | STO_StochD | STO | CCI_TypicalPriceAvg | CCI_TypicalPriceMAD | CCI | RSIDown | RSIUp | RSI | MOM | ADX_PositiveDirectionalIndex | ADX_NegativeDirectionalIndex | ADX | CMO
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
11/10/2019 00:00:00 | 87264000000000 | 1.23264 | 1.225724 | 1.24687 | 1.21948 | 1 | 48.04673238 | 30.40186457 | 35.14956355 | 48.04673238 | 1.22981028 | 0.00264245 | 80.38964907 | 0.00140417 | 0.00128167 | 47.71951598 | -0.00147 | 22.54911993 | 16.87474601 | 15.66406838 | 0.8832388
12/10/2019 00:00:00 | 88128000000000 | 1.25476 | 1.229182 | 1.27061 | 1.24081 | 1 | 69.00058674 | 44.63254684 | 35.41053199 | 69.00058674 | 1.23174028 | 0.00455088 | 346.49792979 | 0.00119583 | 0.003125 | 72.32401157 | 0.02315 | 31.40814565 | 13.13496288 | 17.77736196 | 39.22025408
14/10/2019 00:00:00 | 89856000000000 | 1.2594 | 1.241971 | 1.27061 | 1.24081 | 1 | 78.07549384 | 65.04093765 | 46.69178302 | 78.07549384 | 1.23409167 | 0.00735833 | 207.00641752 | 0.00096333 | 0.00351167 | 78.47299814 | 0.03058 | 26.39902697 | 11.04013727 | 19.71454773 | 44.16243966
15/10/2019 00:00:00 | 90720000000000 | 1.26028 | 1.250685 | 1.26494 | 1.25155 | 1 | 79.79659691 | 75.62422583 | 61.76590344 | 79.79659691 | 1.23644472 | 0.01032042 | 145.2048035 | 0.00096333 | 0.00348667 | 78.35205993 | 0.03028 | 24.48490208 | 10.23964558 | 21.49030136 | 45.08627448
16/10/2019 00:00:00 | 91584000000000 | 1.2693 | 1.255481 | 1.27992 | 1.26025 | 1 | 82.42885506 | 80.10031527 | 73.58849292 | 82.42885506 | 1.23995444 | 0.0135437 | 147.02472107 | 0.000805 | 0.00423833 | 84.03833443 | 0.0412 | 29.86396299 | 9.17369078 | 24.11617698 | 53.65944651
17/10/2019 00:00:00 | 92448000000000 | 1.27278 | 1.262392 | 1.28768 | 1.25155 | 1 | 78.15249267 | 80.12598155 | 78.61684088 | 78.15249267 | 1.24352889 | 0.01568426 | 115.36454336 | 0.000805 | 0.00450917 | 84.8518112 | 0.04445 | 24.70963197 | 11.74637573 | 25.06971458 | 56.51667296
18/10/2019 00:00:00 | 93312000000000 | 1.28571 | 1.267585 | 1.2989 | 1.27485 | 1 | 83.39209267 | 81.32448013 | 80.51692565 | 83.39209267 | 1.24794167 | 0.01843111 | 139.4200627 | 0.000805 | 0.00521333 | 86.62420382 | 0.0529 | 26.89568902 | 10.33903675 | 26.68604016 | 65.21095613
19/10/2019 00:00:00 | 94176000000000 | 1.28928 | 1.276646 | 1.2989 | 1.27485 | 1 | 87.88718207 | 83.14392247 | 81.53146138 | 87.88718207 | 1.25256444 | 0.01966037 | 119.06260008 | 0.00079667 | 0.00551083 | 87.36953362 | 0.05657 | 24.0066295 | 9.22844641 | 28.16767195 | 67.18707993
21/10/2019 00:00:00 | 95904000000000 | 1.29183 | 1.282961 | 1.29497 | 1.28732 | 1 | 87.8292305 | 86.36950175 | 83.61263478 | 87.8292305 | 1.25752222 | 0.01997 | 113.00654686 | 0.00072583 | 0.00572333 | 88.74531593 | 0.05997 | 23.14395626 | 8.8968241 | 29.52583442 | 68.57788907
22/10/2019 00:00:00 | 96768000000000 | 1.29419 | 1.287395 | 1.3012 | 1.28871 | 1 | 88.3921179 | 88.03617682 | 85.84986701 | 88.3921179 | 1.26283111 | 0.02062389 | 103.01609963 | 0.00065 | 0.00592 | 90.1065449 | 0.06324 | 24.75221963 | 8.36164815 | 31.19014864 | 69.86738468
23/10/2019 00:00:00 | 97632000000000 | 1.29311 | 1.290793 | 1.3012 | 1.28617 | 0 | 83.70594159 | 86.64243 | 87.01603619 | 83.70594159 | 1.26854111 | 0.01907259 | 87.21842473 | 0.00026167 | 0.00592 | 95.76705311 | 0.0679 | 22.94066013 | 8.9865169 | 32.23314963 | 66.45712683
24/10/2019 00:00:00 | 98496000000000 | 1.28928 | 1.29195 | 1.29213 | 1.28408 | 0 | 75.99194361 | 82.6966677 | 85.79175817 | 75.99194361 | 1.27391444 | 0.01645667 | 59.07321135 | 0.00040917 | 0.00592 | 93.53522054 | 0.06613 | 21.89060166 | 9.63459375 | 32.78679264 | 54.4605235
25/10/2019 00:00:00 | 99360000000000 | 1.28727 | 1.290615 | 1.29493 | 1.2788 | 0 | 71.94360524 | 77.21383014 | 82.18430928 | 71.94360524 | 1.27841472 | 0.01338727 | 42.75344526 | 0.00057667 | 0.00512917 | 89.89338396 | 0.05463 | 20.0979553 | 11.52623344 | 32.3133061 | 48.33984497
26/10/2019 00:00:00 | 100224000000000 | 1.28509 | 1.288943 | 1.29493 | 1.2788 | 0 | 38.86148008 | 62.26567631 | 74.05872472 | 38.86148008 | 1.28098806 | 0.01126593 | 31.27588928 | 0.00075833 | 0.00328583 | 81.24871214 | 0.03033 | 18.44973374 | 10.58097378 | 31.87927677 | 41.69645056

**Comment by yaeldekel** [comment]
Hi @lefig ,
Thanks for sharing the data.
I don't have the code you ran, but from the stack trace I assume it is AutoML. Did you run it in cross-validation mode? How many folds? The more folds you use, there is more chance that one of the fold will not contain examples from both classes, especially if the data is not huge (although I assume what you shared is only a sample of your data, is this correct?).

For data that contains only one class, it may make more sense to return an AUC of NaN instead of throwing an exception, I will open a separate issue for that. In the mean time, as a workaround you can try splitting your data manually, and running an overload of `Execute` that runs train-test instead of cross-validation, such as [this](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.AutoML/API/ExperimentBase.cs#L137).

**Comment by justinormont** [comment]
There was a fix in for this on the AutoML side:
https://github.com/dotnet/machinelearning/pull/3820

That PR can be re-reinvigorated; it was closed when the author shifted focus away from AutoML.NET topics. If I recall, TLC's CV (and likely ML.NET's) handles the failing CV folds by averaging only the successful folds. This PR changed AutoML's CV to match this behavior.

**Comment by wangyems** [comment]
Hi @lefig , does the current release resolve your issues?

**Comment by wangyems** [comment]
Closing this issue for now. Please feel free to reopen it if there's still any issues.
