### ISSUE TITLE
SelectFeaturesBasedOn* Transformers are not outputing vectors of known size.

### ISSUE THREAD

**Issue by nsingal** [dotnet/machinelearning#4693]
### System information

- **OS version/distro**: Windows
- **.NET Version (eg., dotnet --info)**: 

**Code that failed:**

Context.Transforms.Text.TokenizeIntoWords("TextFeature")                                   .Append(Context.Transforms.FeatureSelection.SelectFeaturesBasedOnCount("TextFeature", "TextFeature", 10)).
Append(Context.Transforms.FeatureSelection.SelectFeaturesBasedOnMutualInformation("TextFeature", "TextFeature", "Label", 5000))
.Append(Context.Transforms.NormalizeLpNorm("TextFeature", "TextFeature", Microsoft.ML.Transforms.LpNormNormalizingEstimatorBase.NormFunction.L2, true));

**Error:**
At NormalizeLpNorm, it fails with
Schema mismatch for input column 'TextFeature': expected Expected Single or known-size vector of Single, got VarVector<Single>

**Comment by yaeldekel** [comment]
After investigating, I discovered that the bug is actually in the `WordBagEstimator`. In PR #4702 I am adding early checks for the input types in the feature selection estimators.

**Comment by mstfbl** [comment]
This issue is fixed by #4702 .
