### ISSUE TITLE
How to add new data to existing trained data model?

### ISSUE THREAD

**Issue by ErcinDedeoglu** [dotnet/machinelearning#470]
Hi,
I am very new to this subject. Maybe there might be a problem with my point of view. Thank you for all the reviews.

I have 10 million rows * 60 columns of data.
And every 1 minute new/fresh data coming. And it is really unstable. So I need to train all data every 1 minute.
I would like to learn if it is possible: I want to change trained data model with new data;
load it, change it and write it again.

Like:
```
            PredictionModel.ReadAsync(_modelpath).Wait();
            PredictionModel<IrisData, IrisPrediction> model = pipeline.Train<IrisData, IrisPrediction>();
            model.WriteAsync(_modelpath).Wait();
```

I'm not sure if it is working?

Thans advance!

**Comment by Ivanidzo4ka** [comment]
DRI RESPONSE: Some of our learners support continuation of training, but we currently don't have 

- Example of how to do that.

- list of trainers which support it.

**Comment by codemzs** [comment]
Only our linear learners support online learning.
