### ISSUE TITLE
Tensorflow.TensorflowException Can't copy 64064 bytes of a tensor into another with 32032 bytes buffer

### ISSUE THREAD

**Issue by mauryflag** [dotnet/machinelearning#4708]
### System information

- **Windows 10 pro**:
- **.NET Version .net core 3.1**: 

### Issue

- **I've generated model for image classification by using ML.Net Model builder , 2 labels (OK & NG) 10 images in total , model was correctly created together with the C# code **
- **I've checked that everything was working fine then i've added SciSharp.TensorFlow.Redist-Windows-GPU in order to check the behavior with GPU**
- **I was expecting that the model will be generated just simply more fast by using GPU , unfortunately it goes in error . attached source code and snip of the error .*

[ML.zip](https://github.com/dotnet/machinelearning/files/4111726/ML.zip)

**Comment by oorosh** [comment]
I have the same issue ;-( Trying to fix it for days but with out any luck. It's really disappointing to see that now resolved for more the two months.

I have reported issue on two place

[https://github.com/SciSharp/TensorFlow.NET/issues/536](url)
and
[https://github.com/dotnet/machinelearning-samples/issues/807](url)

**Comment by oorosh** [comment]
I have fix my issue by updating to at this moment latest version of nuget packages

![Capture](https://user-images.githubusercontent.com/4770675/80314729-7a7c7180-87f3-11ea-9442-b905d25c4053.PNG)

**Comment by mauryflag** [comment]
Hi ,
I did it.
It works , thank you.
Maurizio

Da: Uros Biberdzic <notifications@github.com>
Inviato: domenica 26 aprile 2020 19:25
A: dotnet/machinelearning <machinelearning@noreply.github.com>
Cc: mauryflag <maury.flag@hotmail.it>; Author <author@noreply.github.com>
Oggetto: Re: [dotnet/machinelearning] Tensorflow.TensorflowException Can't copy 64064 bytes of a tensor into another with 32032 bytes buffer (#4708)


I have fix my issue by updating to at this moment latest version of nuget packages

[Capture]<https://user-images.githubusercontent.com/4770675/80314729-7a7c7180-87f3-11ea-9442-b905d25c4053.PNG>

**Comment by oorosh** [comment]
Great, I'm glad to hear that :-)
