### ISSUE TITLE
Save method on asp.net core get an error that access denied path

### ISSUE THREAD

**Issue by Cyrus-Sushiant** [dotnet/machinelearning#4709]
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**:  .NetCore 3.1.1

### Issue

When I want save trained model with the Save Method on asp.net core, I get an error that access denied path. I used other way instead of it.
[Follow here](https://github.com/Cyrus-Sushiant/MLDotNetTitanic/blob/master/MLDotNetTitanic/ML/ModelBuilder.cs#L68).

### Source code / logs

`mlContext.Model.Save(mlModel, modelInputSchema, modelPath);`

**Comment by yaeldekel** [comment]
Hi @Cyrus-Sushiant ,
This is the code I see in the link you gave:
```
            // Save/persist the trained model to a .ZIP file
            //mlContext.Model.Save(mlModel, modelInputSchema, modelPath);

            var path = Path.Combine(modelPath, "MLModel.zip");
            using (var fs = new FileStream(path, FileMode.Create, FileAccess.Write))
            {
                mlContext.Model.Save(mlModel, modelInputSchema, fs);
                fs.Close();
            }
```
Did you mean that this line 
```
mlContext.Model.Save(mlModel, modelInputSchema, modelPath);
```
gave you an access denied error? Did you try the same API with `path` instead of `modelPath`?
```
            var path = Path.Combine(modelPath, "MLModel.zip");
            mlContext.Model.Save(mlModel, modelInputSchema, modelPath);
```

**Comment by harishsk** [comment]
I could not repro the bug you mentioned with your code. Can you please share some repro steps?
Also, since you are running this under a web server, can you please verify that your web server has been configured to save files locally and it has the permissions for the path in question?

**Comment by Cyrus-Sushiant** [comment]
In fact I got a wrong error, because I add name of my file in the Save Method, and solved my problem, but I got "access denied" error.

**Comment by maacpiash** [comment]
> Did you try the same API with `path` instead of `modelPath`?
> 
> ```
>             var path = Path.Combine(modelPath, "MLModel.zip");
>             mlContext.Model.Save(mlModel, modelInputSchema, modelPath);
> ```

I was having the same issue. Using `path` here instead of  `modelPath` did the job for me.

**Comment by harishsk** [comment]
@Cyrus-Sushiant Can you please try the recommendation above and reopen the issue if that doesn't work?
