### ISSUE TITLE
Q: PCA Anomaly Detection - Time series data possible?

### ISSUE THREAD

**Issue by lefig** [dotnet/machinelearning#4711]
Hi all,

I have been trying unsuccessfully to do PCA on time series based data to identify anomalies.

I see that the PCA credit card fraud example and scenario uses a bool and is credit card data (not time based).

My question is whether this is possible using time series data in principle or is the scenario inappropriate? I have floats, must they be transformed?

Thanks

Fig

**Comment by najeeb-kazmi** [comment]
@lefig can you please share a snippet of your training code?

Also, do [these samples](https://github.com/dotnet/machinelearning/tree/master/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/AnomalyDetection) help?

**Comment by najeeb-kazmi** [comment]
@lefig PCA anomaly detection is not intended for time series data. It approximates a subspace for the normal class using the top eigenvectors. It then projects a new example's raw feature vector onto that subspace. The anomaly score is then calculated as the difference between the L2-norm of the raw feature vector and the L2-norm of the projected vector. The larger this difference, the more likely the new example is to be an anomaly. 

Time series anomaly detection is supported via several methods exposed as transforms. See the examples [here](https://github.com/dotnet/machinelearning/tree/master/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/TimeSeries).

Please feel free to reopen this issue if something remains unanswered.
