### ISSUE TITLE
ExpressionEstimator Description Too Long

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#4719]
Most of this page is taken up by the ExpressionEstimator description. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881dc206-da7e-738d-4fb2-5f792163ab89
* Version Independent ID: a6456027-81b5-faa0-2d6a-d37099133234
* Content: [Microsoft.ML.Transforms Namespace](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms?view=ml-dotnet#feedback)
* Content Source: [dotnet/xml/ns-Microsoft.ML.Transforms.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/ns-Microsoft.ML.Transforms.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by natke** [comment]
This was fixed by #4614
