### ISSUE TITLE
Get cluster items

### ISSUE THREAD

**Issue by adamshakhabov** [dotnet/machinelearning#473]
_Sorry for my English :)_

I am using sample [Clustering Iris Data](https://github.com/dotnet/machinelearning-samples/tree/master/samples/getting-started/Clustering_Iris). Is there anyway except cluster Id also get items which were put in the same cluster?

That is, I got prediction:

`var prediction1 = model.Predict(TestIrisData.Setosa1);`

and I can get cluster Id by `prediction1.SelectedClusterId`. But I also need to know data about another items with their features SepalLength, SepalWidth, PetalLength, PetalWidth.

**Comment by pkulikov** [comment]
That sounds like a [MATLAB-like API](https://mathworks.com/help/stats/kmeans.html): clustering returns clusters ID of all data items in the given data set.

@adamshakhabov I don't know if ML.NET can return all the cluster IDs immediately after the call to the `Train` method, so let me to speculate how we can get cluster items ourselves.

First, it seems possible to add the feature fields to the prediction classes themselves and populate them from the feature columns. Then, to use LINQ's `Where` or `GroupBy` method.

Second, we can create mapping from data items to the cluster IDs. Use LINQ's [`ToDictionary` method](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.todictionary?view=netcore-2.1#System_Linq_Enumerable_ToDictionary__3_System_Collections_Generic_IEnumerable___0__System_Func___0___1__System_Func___0___2__). Something like that (syntax might be not correct):
```csharp
flowers.ToDictionary(
    keySelector: f => f,
    elementSelector: f => model.Predict(flower).SelectedClusterId)
```

Or, you may create the mapping in reverse: from cluster ID to the data items. Use LINQ's [`ToLookup` method](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.tolookup?view=netcore-2.1#System_Linq_Enumerable_ToLookup__3_System_Collections_Generic_IEnumerable___0__System_Func___0___1__System_Func___0___2__). Something like that (again, syntax might not compile):
```csharp
IEnumerable<IrisData> flowers = ...;
var lookup = flowers.ToLookup(
    keySelector: f => model.Predict(flower).SelectedClusterId,
    elementSelector: f => f);

IEnumerable<IrisData> flowersInClusterOne = lookup[1];
```

Hope that will help you.

**Comment by adamshakhabov** [comment]
Great, many thanks @pkulikov.

**Comment by subash774** [comment]
Somewhat similar to the topic. I'm testing ML.NET on Iris data as well for clustering. For K means, I want to find out the optimum number for K (3 in this dataset but for others we'd need somewhat of an optimisation algorithm). Is there a way to know how many clusters the data is separated into after it is trained? i.e. after 
` PredictionModel<IrisData, ClusterPrediction> model = Train();`

Thanks

**Comment by Ivanidzo4ka** [comment]
DRI RESPONSE: This issue looks like good candidate for cook book.

**Comment by shmoradims** [comment]
Here's how you can find the centeroids info:

```csharp
// Get the cluster centroids and the number of clusters k from
// KMeansModelParameters.
VBuffer<float>[] centroids = default;

var modelParams = model.Model;
modelParams.GetClusterCentroids(ref centroids, out int k);
Console.WriteLine(
    $"The first 3 coordinates of the first centroid are: " +
    string.Join(", ", centroids[0].GetValues().ToArray().Take(3)));

Console.WriteLine(
    $"The first 3 coordinates of the second centroid are: " +
    string.Join(", ", centroids[1].GetValues().ToArray().Take(3)));

// Expected output:
//   The first 3 coordinates of the first centroid are: (0.5840713, 0.5678288, 0.6221277)
//   The first 3 coordinates of the second centroid are: (0.3705794, 0.4289133, 0.4001645)
```

The full example is [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.kmeansclusteringextensions.kmeans?view=ml-dotnet#Microsoft_ML_KMeansClusteringExtensions_KMeans_Microsoft_ML_ClusteringCatalog_ClusteringTrainers_Microsoft_ML_Trainers_KMeansTrainer_Options_)
