### ISSUE TITLE
PredictionEngine.Predict locks file even after disposing and going out of context

### ISSUE THREAD

**Issue by crvkumar** [dotnet/machinelearning#4738]
### System information

- **OS version/distro**: Win10
- **.NET Version (eg., dotnet --info)**:  .NET 4.7.2
- **ML.NET**: 1.4.0

### Issue

Creating PredictionEngine and using Predict on an Image data locks the image file.
Disposing the prediction engine has no effect as well.

~~ImageLoadingEstimator locks the image file and does not release the lock even after going out of
context.~~

**Comment by harishsk** [comment]
Can you please share more details? Some sample code and perhaps some sample data would be very useful.

**Comment by antoniovs1029** [comment]
Perhaps the same problem as #4585 ?

**Comment by crvkumar** [comment]
Yes, it is the same. Sorry. Will close this issue.

For the time being worked around using ITransformer.Transform which does not seem to lock files.
