### ISSUE TITLE
how we show permutation slot associated with feature so end user easily identify?

### ISSUE THREAD

**Issue by nighotatul** [dotnet/machinelearning#4739]
@yaeldekel,@eerhardt,@najeeb-kazmi,@justinormont,@CESARDELATORRE 

we required deep PFI and FCC on feature of their values.
we calculate PFI as per below link-
https://devblogs.microsoft.com/premier-developer/permutation-implementation-with-ml-net/
following top 4 feature we got and we draw bar charts.

Top 4   Features | Comments of   this Observation
-- | --
Overtime | Higher reported   Overtime, employees are more likely to leave.
**Marital Status** | Certain group   of marital status is more likely to leave than the other group. As far as   which group, it could be identified through the debugging of each permutation   slot associated.
Department | Certain   department employees are more likely leave than other departments. Again, the   identification could have been done as well.
Years At   Company | Number   of years at the same company are factored. Again, is it more   years more likely to leave or less likely to leave?

now if you see comments on related Marital Status feature, we want to show permutation slot associated Marital Status so end user easily identify which Certain group of marital status is more likely to leave than the other group.

Thanks and Regards,
Atul
![PFI slot](https://user-images.githubusercontent.com/37444019/73481000-f1ef6000-43c0-11ea-9b4b-102a297c9ed7.png)
[attrition.xlsx](https://github.com/dotnet/machinelearning/files/4135819/attrition.xlsx)

**Comment by nighotatul** [comment]
@yaeldekel,@eerhardt,@najeeb-kazmi,@justinormont,@CESARDELATORRE

we required deep PFI and FCC on feature of their values.
we calculate PFI as per below link-
https://devblogs.microsoft.com/premier-developer/permutation-implementation-with-ml-net/
following top 4 feature we got and we draw bar charts.
Top 4 Features | Comments of this Observation
-- | --
Overtime | Higher reported Overtime, employees are more likely to leave.
Marital Status | Certain group of marital status is more likely to leave than the other group. As far as which group, it could be identified through the debugging of each permutation slot associated.
Department | Certain department employees are more likely leave than other departments. Again, the identification could have been done as well.
Years At Company | Number of years at the same company are factored. Again, is it more years more likely to leave or less likely to leave?

now if you see comments on related Marital Status feature, we want to show permutation slot associated Marital Status so end user easily identify which Certain group of marital status is more likely to leave than the other group.

Thanks and Regards,
Atul
PFI slot
attrition.xlsx

**Comment by najeeb-kazmi** [comment]
@nighotatul Do I understand your question correctly?

1. You have found your top 4 most important features. Some of them are categorical (MaritalStatus and Department). Now you want to find out which value of a categorical feature feature affects the prediction Attrition = true or false and in what direction (i.e. make it more or less likely that we have a true prediction).
2. You want to find out in which direction does a numerical feature (YearsAtCompany) affect the prediction (i.e. higher values make it more or less likely tht we have a true prediction).

**Comment by yaeldekel** [comment]
@nighotatul , the PFI API is applied to the feature set that is seen by the classification/regression model at the end of the pipeline (the "predictor" as we call it). For categorical features, this means that it sees the one-hot vector of features, where each element of the vector corresponds to one of the categories.
In this [PFI sample](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/PermutationFeatureImportance.cs#L50-L54) you can see how to sort the features by their importance according to PFI:
```
var sortedIndices = permutationMetrics
                .Select((metrics, index) => new { index, metrics.AreaUnderRocCurve})
                .OrderByDescending(
                feature => Math.Abs(feature.AreaUnderRocCurve.Mean))
                .Select(feature => feature.index);
```
In order to figure out which index corresponds to which feature, you can use the `SlotNames` annotation on the features column. [Here](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Text/ProduceWordBags.cs#L80-L94) is a sample showing how to get the slot names from the schema.
```
VBuffer<ReadOnlyMemory<char>> slotNames = default;
dataView.Schema["Features"].GetSlotNames(ref slotNames);
var slots = slotNames.GetValues();
```
`slots` is a `ReadOnlySpan<ReadOnlyMemory<char>>` so you can access the names by index.

**Comment by nighotatul** [comment]
Hi,

@yaeldekel,@eerhardt,@najeeb-kazmi,@justinormont,@CESARDELATORRE

when we click on feature bar say
if I click on Marital Status bar we should get **Single** **Married** **Divorced** bar how we get this

i.e how to find out model weights for Single,Married,Divorced of Marital status feature so we can generate graph for Single,Married & Divorced.

**Comment by najeeb-kazmi** [comment]
@nighotatul for a binary classification model, you would get the weights with this code:

```csharp
var modelParameters = trainedModel.LastTransformer.Model as CalibratedModelParametersBase<LinearBinaryModelParameters, Calibrators.PlattCalibrator>;
var weights = modelParameters.SubModel.Weights;
```

You can get the corresponding slot names with the code in the previous comment. The slot names would be something like `MaritalStatus.Single`, etc.

Please reopen this issue if something remains unanswered.
