### ISSUE TITLE
[Meta Issue] Changing defaults

### ISSUE THREAD

**Issue by najeeb-kazmi** [dotnet/machinelearning#4749]
First of all, is this a breaking change? @terrajobst suggested it is an acceptable breaking change https://github.com/dotnet/machinelearning/issues/2305#issuecomment-508197927, @eerhardt commented that is was decided that changing defaults is acceptable https://github.com/dotnet/machinelearning/issues/2305#issuecomment-509289908

- Change the following defaults based on results from @justinormont:

  - #2870 `FeatirizeText` default n-grams lengths to match default text recipe:
    - word: 1 -> 2
    - char: no change
    - @justinormont correct me if I am wrong: was the default weighting TF-IDF in TLC? It is currently TF

  - #2305 `AveragedPerceptron` default iterations from 1 to 10

- #3365 `RowGroupColumnName` in `FastTree` and `LightGbm` ranking trainer `Options` classes: `null` -> `'GroupId'`
  - This won't actually break anything since a ranking trainer would throw anyway if there was no group ID column specified https://github.com/dotnet/machinelearning/issues/3365#issuecomment-497775736
  - This would make it consistent with the API for the rankers without the `Options` class, where the default is `'GroupId'`
  - They should be consistent, at least. Either `null` everywhere or `'GroupId'` everywhere.

cc: @harishsk @justinormont @gvashishtha @eerhardt

**Comment by najeeb-kazmi** [comment]
Assigning @gvashishtha for triage.

**Comment by justinormont** [comment]
> @justinormont correct me if I am wrong: was the default weighting TF-IDF in TLC? It is currently TF

The default text recipe in TLC uses TF.  I believe the current default in ML․NET is also TF, so no changes needed for that.

**Comment by eerhardt** [comment]
Changing a default parameter value is an acceptable change. Just be sure you still support the old default value - for example if the old default was ‘null’ and you change it to a non-null default, you still should support ‘null’ values.

**Comment by michaelgsharp** [comment]
With the merging of PRs #5248, #5258, and #5290, this issue has been resolved. Closing this issue.
