### ISSUE TITLE
`sentiment_data.tsv` and `sentiment_test.tsv` are missing in the solution.

### ISSUE THREAD

**Issue by JoshuaLight** [dotnet/machinelearning#475]
### Issue

- **What did you do?**
Opened the solution.

- **What happened?**
I've found that `test\data` solution folder contains missing files: `sentiment_data.tsv` and `sentiment_test.tsv`.
As it looks in [Microsoft.ML.sln](https://github.com/dotnet/machinelearning/blob/master/Microsoft.ML.sln) it has:
```
// Starts at 37.
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "data", "data", "{FDA2FD2C-A708-43AC-A941-4D941B0853BF}"
	ProjectSection(SolutionItems) = preProject
	>>	test\data\sentiment_data.tsv = test\data\sentiment_data.tsv
	>>	test\data\sentiment_test.tsv = test\data\sentiment_test.tsv
	EndProjectSection
EndProject
```
While such data actually doesn't present in repository, as it looks [here](https://github.com/dotnet/machinelearning/tree/master/test/data).
- **What did you expect?**
I'd expect that there should be no missing files in solution.

**Comment by JoshuaLight** [comment]
I've done something like [#14cb62](https://github.com/JoshuaLight/machinelearning/commit/14cb62a73e4a175b938f990e63d2517bbdab0d94) because by #362 it seems like there was already a wave of non-source files removal.

Still not 100% (not even 80%) sure that I'm not wrong: maybe such data files for test should be in solution or maybe I just forgot to run some scripts (even if I tried to find `sentiment_test.csv` text-entries in whole repository and there were just one or two).

**Comment by TomFinley** [comment]
As in #362 my own preference would be to not have files like this that don't have some immediate bearing on the project's building to *not* be included. Certainly it is clear that no one has found the presence of these helpful (how could they?), nor found the absence of all other test files. So what you have in your fork looks good, were you thinking of creating a PR @JoshuaLight ?
