### ISSUE TITLE
there's an alternative to the TextLoader class?I would like to add the data to the pipeline without to use a file. Regards  

### ISSUE THREAD

**Issue by maxambrogi** [dotnet/machinelearning#481]
### System information

- **OS version/distro**:
- **.NET Version (eg., dotnet --info)**: 

### Issue

- **What did you do?**
- **What happened?**
- **What did you expect?**

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by jwood803** [comment]
Perhaps `CollectionDataSource` is what you need. Here's an example from the [0.2 release blog post](https://blogs.msdn.microsoft.com/dotnet/2018/06/05/announcing-ml-net-0-2/).

```csharp
var pipeline = new LearningPipeline();
var data = new List() {
           new IrisData { SepalLength = 1f, SepalWidth = 1f 
                         ,PetalLength=0.3f, PetalWidth=5.1f, Label=1},
           new IrisData { SepalLength = 1f, SepalWidth = 1f 
                         ,PetalLength=0.3f, PetalWidth=5.1f, Label=1},
           new IrisData { SepalLength = 1.2f, SepalWidth = 0.5f 
                         ,PetalLength=0.3f, PetalWidth=5.1f, Label=0}
           };
var collection = CollectionDataSource.Create(data);
pipeline.Add(collection); 
```

Hope that helps!

**Comment by maxambrogi** [comment]
Great, many thanks @jwood803
