### ISSUE TITLE
Shuffle input cursor reader failed with an exception in ml.net 1.4.0

### ISSUE THREAD

**Issue by Spocher** [dotnet/machinelearning#4819]
- Windows 10 x64
- NET Framework 4.7.2, ML.Net 1.4.0

I create project for multiclass classification, some code:
`var trainingDataView = mlContext.Data.LoadFromEnumerable(allTrainData);

var trainingPipeline = mlContext.Transforms.Conversion.MapValueToKey(inputColumnName: "IdCategory", outputColumnName: "Label")
	.Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName: "HeaderProduct", outputColumnName: "HeaderProductFeaturized"))
	.Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName: "DescriptionProduct", outputColumnName: "DescriptionProductFeaturized"))
	.Append(mlContext.Transforms.Concatenate("Features", "HeaderProductFeaturized", "DescriptionProductFeaturized"))
	.Append(mlContext.MulticlassClassification.Trainers.SdcaMaximumEntropy())
	.Append(mlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel"));

var trainedModel = trainingPipeline.Fit(trainingDataView);`

I try train model and have Exception:
 Shuffle input cursor reader failed with an exception, (   in Microsoft.ML.Transforms.RowShufflingTransformer.Cursor.MoveNextCore()
   in  Microsoft.ML.Data.RootCursorBase.MoveNext()
   in  Microsoft.ML.Trainers.TrainingCursorBase.MoveNext()
   in  Microsoft.ML.Trainers.SdcaTrainerBase`3.TrainCore(IChannel ch, RoleMappedData data, LinearModelParameters predictor, Int32 weightSetCount)
   in  Microsoft.ML.Trainers.StochasticTrainerBase`2.TrainModelCore(TrainContext context)
   in  Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   in  Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)

I downgraded the version ml.net to 1.3.1 an all worked fine.
a little later, I upgraded the version to 1.5.0-preview and all worked fine.

**Comment by frank-dong-ms** [comment]
Can you please provide a repro project and input data so we can look further?

**Comment by frank-dong-ms** [comment]
We didn't hear back for couple months now, so I will close the issue for now, @Spocher feel free to reopen this issue if you can provide more details on this issue, thanks.

**Comment by ScubaAddict1** [comment]
I had the same issue, fixed it by adding 
  _trainingDataView = _mlContext.Data.Cache(_trainingDataView);
Not sure if its ideal as am using a asp.net core (.net 5) website with ML 1.6 and loading the data from SQL.
