### ISSUE TITLE
AutoML throws several OperationCanceledExceptions

### ISSUE THREAD

**Issue by zeroskyx** [dotnet/machinelearning#4821]
Greetings,

when using any AutoML API project such as [Sentiment Analysis for User Reviews](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/BinaryClassification_AutoML), several exceptions are thrown in the background.

This is probably due to some internal cancellation and has no additional negative impacts but is pretty ugly in the debugger.

Would it be feasible to wrap this cancellation in a `Task.ContinueWith()` in order to keep the debugger clean?

Keep up the great work!

**Comment by frank-dong-ms** [comment]
Thanks for reporting this.
I tried run the BinaryClassification_AutoML sample project and below is my console output, no exceptions found:
![image](https://user-images.githubusercontent.com/55860649/74186376-5c916e80-4bff-11ea-9989-96bfe160b8ed.png)

Can you provide a screen of these exceptions and your system information?

**Comment by zeroskyx** [comment]
Thanks for the fast response -- the exceptions are **only visible with a debugger attached** and "Just my code" disabled.

I have a screenshot of the example using VSCode and with `"justMyCode": false,` in `launch.json`:

![image](https://user-images.githubusercontent.com/7782966/74189049-04cf2380-4c50-11ea-812e-a420407b1d3d.png)

**Comment by frank-dong-ms** [comment]
I debugged this issue a little bit, this exception is thrown by this line: https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Data/DataLoadSave/Binary/BinarySaver.cs#L219, this OperationCanceledException is an internal signalling mechanism of BlockingCollection so it is safe to ignore them. The exception is handled by the framework code and you wouldn't have noticed it if you hadn't had your debugger configured to intercept it.

You can reference to this post as more info: https://stackoverflow.com/questions/22967631/how-can-blockingcollectiont-getconsumingenumerable-throw-operationcanceledex/35848060

**Comment by frank-dong-ms** [comment]
Close this issue as this is expected behavior, thanks
