### ISSUE TITLE
We should set our PackageTags in the NuGet packages

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#484]
If we set the `$(PackageTags)` property in our NuGet package projects, the tags will automatically be defined in our .nupkg. And those values will be shown in nuget.org.

We are currently leaving this property blank in our packages.

/cc @shauheen

**Comment by TomFinley** [comment]
This sounds good. What tags did we have in mind? Not sure if there are guidelines or best practices in this space.

**Comment by eerhardt** [comment]
@shauheen - Any thoughts?

I could imagine at least adding `machine learning` as a tag.

https://www.nuget.org/packages/Microsoft.ML.Scoring/ has

![image](https://user-images.githubusercontent.com/8291187/42335720-e1e634ac-8046-11e8-8408-d1673bc2b713.png)

**Comment by shauheen** [comment]
The obvious ones would be Microsoft Machine Learning, I think we can add pipeline, train, classification, regression, Text, ML, Toolkit

**Comment by danmosemsft** [comment]
Seems simple, I"ll do it.
