### ISSUE TITLE
how to generate tensorflow inception-v1 model using ML.NET?

### ISSUE THREAD

**Issue by pardont** [dotnet/machinelearning#4842]
Hi, I am using ML.NET to classify image, both online and offline mode.
online mode:  app send image to web server, the server classify image.
offline mode: app download trained model, and classify image locally.

how to generate tensorflow inception-v1 model using ML.NET?

**Comment by frank-dong-ms** [comment]
Thanks for reaching out, please checkout this sample: https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_TensorFlowEstimator

**Comment by pardont** [comment]
@frank-dong-ms , Thank you for your help.

I downloaded the DeepLearning_TensorFlowEstimator sample, and trained the model, but only imageClassifier.zip generated in the output folder. I also need tensorflow inception-v1 model for the offline usage.  How can I get it? 

Thanks again.
![image](https://user-images.githubusercontent.com/2252587/74621661-ae467580-5178-11ea-9168-5479afe6cbc7.png)

**Comment by gvashishtha** [comment]
If by "offline usage," you mean you want to get predictions from your model, you should be able to do that with the zip file alone. See this section on [model consumption](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_TensorFlowEstimator#4-model-consumption-code)

**Comment by pardont** [comment]
Hi, @gvashishtha , I forgot to point out offline usage is on android and ios device. I think the solution is  tensorflow or tensorflow lite, is there any way to generate model for tensorflow or tensorflow lite?

**Comment by frank-dong-ms** [comment]
ML.NET not support export trained model as .pb format.

But why you train a model using ML.NET but want to consume the trained model as TF format?

**Comment by pardont** [comment]
This link said ML.NET trained both .pb(tensorflow) and .zip(ml.net) model, the .pb file generated in "WorkspacePath":
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification-api-transfer-learning

I test to set WorkspacePath and it works:
![image](https://user-images.githubusercontent.com/2252587/74793840-8849de00-52fc-11ea-826b-5b865a3d7500.png)

But the .pb file is not a inception-v1 version, how to change the .pb version in ml.net?

**Comment by gvashishtha** [comment]
OK, can you share your training code?

**Comment by codemzs** [comment]
@pardont we don’t support retraining last layer of inception v-1 but we do support the same for inception v3, mobilnet v2, resnet 50 and resnet 101, please change the architecture parameter to toggle between models.

**Comment by pardont** [comment]
@gvashishtha  , I just use the sample:
https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ImageClassification_Training

and set WorkspacePath in the ImageClassificationTrainer.Options

> var options = new ImageClassificationTrainer.Options()
            {
                FeatureColumnName = "Image",
                LabelColumnName = "LabelAsKey",
                // Just by changing/selecting InceptionV3/MobilenetV2/ResnetV250  
                // you can try a different DNN architecture (TensorFlow pre-trained model). 
                //Arch = ImageClassificationTrainer.Architecture.MobilenetV2,
                MetricsCallback = (metrics) => Console.WriteLine(metrics),
                ValidationSet = testDataView,
                WorkspacePath = imagesFolderPathForPredictions
            };

**Comment by pardont** [comment]
@codemzs thank you for your information, I will take a try to train mobile v2 model.

**Comment by tolokonnikov** [comment]
Hi! 
I downloaded your project from github and run him. But i did not find .pd file your picture.
Please help me.
I want *.pb file for next transforming to ONNX
Thanks!

**Comment by tolokonnikov** [comment]
Ok. I found it.
Need set FinalModelPrefix = outputMlNetModelFilePath or other patg in Options // 5.1 (OPTIONAL)
Thanks

**Comment by frank-dong-ms** [comment]
suggestion has been given, close this issue now. Feel free to reopen if necessary, thanks

**Comment by pardont** [comment]
hi, @tolokonnikov ,I tried to set FinalModelPrefix  but with noluck, would you mind send me your project code?

Thanks

**Comment by tolokonnikov** [comment]
Hi! This example works perfectly with saving *.pd model
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification-api-transfer-learning
