### ISSUE TITLE
Extract MaximumEntropyModelParameters from MulticlassPredictionTransformer ITransformer model

### ISSUE THREAD

**Issue by maximeozenne** [dotnet/machinelearning#4851]
### System information

- **OS version/distro**: Windows 10 Enterprise
- **.NET Version (eg., dotnet --info)**: .NET Framework 4.7.2

### Issue

- **What did you do?**
I want to re-train multi-class (`LbfgsMaximumEntropyMulticlassTrainer`).
- **What happened?**
I train and load model, but i cannot extract `MaximumEntropyModelParameters`.
- **What did you expect?**
I want to extract `MaximumEntropyModelParameters` my pre-trained model.
I want to retrain my model by using `LbfgsMaximumEntropyMulticlassTrainer.Fit(IDataView, MaximumEntropyModelParameters)` method.

Similar to #4099 but I'm using only one model

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

```
//Create a ITransformer from my IDataView
var pipeline = mlContext.Transforms.Conversion.MapValueToKey()
    .Append(mlContext.Transforms.Text.FeaturizeText())
    .AppendCacheCheckpoint(mlContext);
var trainingPipeline = pipeline.Append(mlContext.MulticlassClassification.Trainers.LbfgsMaximumEntropy())
    .Append(mlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel"));
ITransformer trainedModel = trainingPipeline.Fit(splitTrainSet);

//Try to retrain it by extracting the parameters
var originalModelParameters = ((MulticlassPredictionTransformer<object>)model).Model as MaximumEntropyModelParameters;
model = mlContext.MulticlassClassification.Trainers.LbfgsMaximumEntropy().Fit(transformedNewData, originalModelParameters);
```

### Logs

> System.InvalidCastException: 'Unable to cast object of type 'Microsoft.ML.Data.TransformerChain`1[Microsoft.ML.ITransformer]' to type 'Microsoft.ML.Data.MulticlassPredictionTransformer`1[System.Object]'.'

**Comment by gvashishtha** [comment]
Did you already try the solution given by @najeeb-kazmi in [this response](https://github.com/dotnet/machinelearning/issues/4099#issuecomment-580036499)?

**Comment by maximeozenne** [comment]
Actually no, I didn't try it yet, especially because I'm not sure why I need to use two model instead of one ?
I tried to adapt the code from the documentation which is using only one model, I was hoping I can do the same with the `LbfgsMaximumEntropyMulticlassTrainer`. Isn't it possible ? Why do I need to use two models here ?

**Comment by gvashishtha** [comment]
I believe Najeeb explained this:

> You need two separate pipelines in order for (loadedModel2 as TransformerChain<ITransformer>).LastTransformer to be the MulticlassPredictionTransformer rather than the KeyToValueMappingTransformer.

If this is still an issue, can you link to the part of the documentation you are following?

**Comment by maximeozenne** [comment]
Ok, it works like that. I was hoping to achieve it with only one model, because I'm already using 3 models on my application. Thanks for your help !
