### ISSUE TITLE
Is there a way to get individual metrics from a binaryclassifier in a multiclass scenario

### ISSUE THREAD

**Issue by srqdev** [dotnet/machinelearning#4864]
I'm using the averaged perceptron method in a mutliclas scenario. So my training data consists of predictions for more then one type, say types ABC, DEF and GHI. Once trained I can get the overall metrics but is there a way to get the metrics for ABC, DEF and GHI separately so that I can see where training was better or worse?

**Comment by najeeb-kazmi** [comment]
Hi @srqdev with the multiclass evaluator, you get back a `MulticlassClassificationMetrics` object, which gives you the `PerClassLogLoss` ([example](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/LogLossPerClass.cs), [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.data.multiclassclassificationmetrics?view=ml-dotnet)). It also contains a `ConfusionMatrix` object, which gives you the `PerClassPrecision` and `PerClassRecall` ([documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.data.confusionmatrix?view=ml-dotnet)). These are the only per class metrics available. With the `Counts` property of `ConfusionMatrix`, you can also manually calculate the per class accuracy.

**Comment by srqdev** [comment]
Hi Najeeb, this is what I was looking for. It would be handy to be able to get the class from the confusion matrix without having to parse the output GetFormattedCOnfusionTable method, but this gives me what the end users want.
