### ISSUE TITLE
How to get information about the model (number of hidden layer)?

### ISSUE THREAD

**Issue by actopozipc** [dotnet/machinelearning#4871]
Hi,  
I've trained and saved my model and everything is working fine. I just wonder if its possible to access information about the model like the number of nods in the different layers or the values of the weights?

**Comment by gvashishtha** [comment]
Assuming your model is saved as ONNX or .pb, try using a tool like [Netron](https://github.com/lutzroeder/Netron)

**Comment by actopozipc** [comment]
Its saved as zip

**Comment by gvashishtha** [comment]
OK, can you share your training code?

**Comment by actopozipc** [comment]
Its available at my [github](https://github.com/actopozipc/Telluz/tree/instabil), everything ML.NET related in the class ML.cs. I can also provide the saved zip if necessary. 
I tried Netron since it provides an experimental ML.NET support, but the visualization is barely accurate and doesnt provide the information I was looking for.
If it is possible to extract the network-information from properties of ML.NET objects in code or if I would be able to convert my model to ONNX, I would be happy too. Are there any possibilites towards this direction of model-details?

**Comment by gvashishtha** [comment]
Looks like you are using SDCA trainer, which is ONNX exportable. Try using [the convertToOnnx method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.onnxexportextensions.converttoonnx?view=ml-dotnet-preview) to export it.

**Comment by actopozipc** [comment]
I am sorry for the late response.
I tried the method, but it threw an exception that seems to be [its own issue](https://github.com/dotnet/machinelearning/issues/3973). All values used in my ML.NET model are float.  
Any alternatives?

**Comment by Lynx1820** [comment]
I've tried exporting a similar pipeline on my end, but I couldn't reproduce the error. Can you share the error you get and the code you used to export to onnx?

**Comment by frank-dong-ms** [comment]
@actopozipc thanks for using ML.NET, haven't heard back for a while so close this issue. Feel free to reopen if you can provide more details for us to investigate the issue.
