### ISSUE TITLE
Update docs to remove mentions of GPU support in ApplyOnnxModel

### ISSUE THREAD

**Issue by gvashishtha** [dotnet/machinelearning#4872]
When Onnxruntime released 1.0, they changed the API and broke the interface from 0.5 so that now it is not possible to ever exercise the GPU code path unless someone compiles ML.NET privately and links it to Microsoft.ML.OnnxRuntime.Gpu specifically.

Related to #4478 and #4656

**Comment by antoniovs1029** [comment]
PR #4919 has reenabled ONNX support for GPU. Now to use ApplyOnnxModel, users should install either Onnxruntime (for CPU) or Onnxruntime.Gpu.
