### ISSUE TITLE
AveragedPerceptron failure when used as a multiclass classifier with only one prediction specified in the input file

### ISSUE THREAD

**Issue by srqdev** [dotnet/machinelearning#4892]
When evaluating a model (MulticlassClassification.Evaluate) with testing data against a model created using the AveragedPerceptronTrainer in a multiclass scenario I get the failure shown below. This only occurs when the input data has a single prediction class and not multiple prediction classes.

_'Schema mismatch for score column 'Score': expected vector of two or more items of type Single, got Vector<Single, 1>_

If I supply 1 to 'n' classes it should be consistent,

**Comment by ganik** [comment]
@srqdev Please share your model and source code of evaluation so we could repro it.

**Comment by mstfbl** [comment]
Closing this issue as no further updates on the issue have been given. @srqdev feel free to reopen the issue if you can provide more information. Thanks.
