### ISSUE TITLE
how to add this option to LightGBM?

### ISSUE THREAD

**Issue by malterman** [dotnet/machinelearning#4894]
Is there a reference for how to add options (like below) to: mlContext.BinaryClassification.Trainers.LightGBM(...  ?

            var options = new LightGbmBinaryTrainer.Options
            {
                NumberOfThreads = 4,
                UnbalancedSets = true,
                EvaluationMetric = LightGbmBinaryTrainer.Options.EvaluateMetricType.AreaUnderCurve
            };

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c83c9a9-84be-c526-4e54-62930bc16974
* Version Independent ID: 63652672-e3bb-90c6-9f7d-470ed8dd32f5
* Content: [LightGbmMulticlassTrainer.Options.UnbalancedSets Field (Microsoft.ML.Trainers.LightGbm)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.lightgbm.lightgbmmulticlasstrainer.options.unbalancedsets?view=ml-dotnet#feedback)
* Content Source: [dotnet/xml/Microsoft.ML.Trainers.LightGbm/LightGbmMulticlassTrainer+Options.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Trainers.LightGbm/LightGbmMulticlassTrainer+Options.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by najeeb-kazmi** [comment]
@malterman here are samples for using options with LightGbm for [binary](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/LightGbmWithOptions.cs) and [multiclass](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/LightGbmWithOptions.cs) classification.
