### ISSUE TITLE
What is the exact behavior of CreateTextLoader<TInput> when dataSample is given?

### ISSUE THREAD

**Issue by najeeb-kazmi** [dotnet/machinelearning#4898]
We have this overload for `CreateTextLoader<TInput>`, where the schema is defined in `TInput`. 
https://github.com/dotnet/machinelearning/blob/c3d15927522ef9645dd335d9375fda15a2aaab34/src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderSaverCatalog.cs#L90-L98

The `dataSample` argument is meant to be used to infer schema. Since `TInput` must contain at least one field, there is always at least one column in the schema. Then, this condition is never hit, and consequently, `dataSample` is never used to infer the schema with the `CreateTextLoader<TInput>` overload.
https://github.com/dotnet/machinelearning/blob/c3d15927522ef9645dd335d9375fda15a2aaab34/src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs#L1118

~Presence of the `dataSample` argument is confusing here as it implies that a sample can be provided. In other places, this sample is used to infer schema, so the user would expect this to be the case here as well, but `dataSample` is ignored here.~

~I will update the documentation to reflect this, but this should be removed. Since this will be an API breaking change, this should be revisited for 2.0.~

**Comment by yaeldekel** [comment]
The data sample is also used here: https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs#L1191
```
_bindings = new Bindings(this, cols, headerFile, dataSample);
```
It is used to get slot names for the vector columns in case `hasHeader` is specified to be true.

**Comment by najeeb-kazmi** [comment]
@yaeldekel must the `dataSample` have the schema in the header for this to work? E.g.

#@ TextLoader{
#@   sep=tab
#@   col=Features:R4:0-5
#@ }

**Comment by yaeldekel** [comment]
No. The columns are taken either from the `TInput` class or from the `Options` if using the non-generic overload. The other arguments (such as the separator) are taken from the arguments to `CreateTextLoader`. The data sample is used for inferring the columns only if there are no columns specified, and I think even then it will work even when there is no schema in the header, by creating a default set of columns "Label" and "Features" (this is how it used to work, I'll have to look at the code to see if this is still what we do).

**Comment by najeeb-kazmi** [comment]
Yes, if no schema is present in the header, it will add col=Label:R4:0 col=Features:R4:1-*. If some features are text, they will be loaded as missing values.

For this particular overload, you are right, the columns are inferred from `TInput`, but for other overloads, if no columns are specified, either the schema is parsed from the header of the `dataSample` if present, or it defaults to first column label, and the rest all features. 

Am I right that if any other schema is needed, and no columns are specified, the `dataSample` must have it in the header?

**Comment by yaeldekel** [comment]
If the `dataSample` has the columns defined in it, it also has the rest of the `TextLoader` options in it (such as the separator, and whether or not there is a header). Is this what you mean by "any other schema needed"?

**Comment by najeeb-kazmi** [comment]
I mean let's say that the schema is NOT `col=Label:R4:0 col=Features:R4:1-*` but something like `col=Label:R4:0 col=Categories:TX:1-3 col=Features:R4:4-*`. Then the `dataSample` MUST contain this information in the header. If not, the loaded data has missing values. This means that if the user provides a data sample, that sample must be one that has previously been loaded with the right schema, and then saved to a text file with schema in the header. Otherwise, `dataSample` is of no use.
