### ISSUE TITLE
AppendCacheCheckpoint is ignored at the beginning of the pipeline

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#4909]
When an empty `EstimatorChain` is created, and `AppendCacheCheckpoint` is called before adding any estimators, then no caching occurs. 
The expected behavior should be to either cache the data before fitting the first estimator in the chain, or disallow calling `AppendCacheCheckpoint` on empty chains, so that the user knows to cache the data explicitly before fitting. (I think the first solution is preferable, but open to other opinions).

**Comment by artemiusgreat** [comment]
And this is the code to reproduce the issue :) 
https://github.com/dotnet/machinelearning/issues/4926#issuecomment-597418276

**Comment by frank-dong-ms** [comment]
This issue is different issue with issue #4926, issue #4926 is converting from EstimatorChain to IEstimator and lose information like need cache. This issue is when try to call AppendCacheCheckpoint after an empty EstimatorChain and no cache will happen.
