### ISSUE TITLE
Poor accuracy with non-US regional settings

### ISSUE THREAD

**Issue by ddobric** [dotnet/machinelearning#4910]
### System information

- **OS Windows 10**:
- **.NET Core 2.2**: 

### Issue
Getting poor accuracy running the training code on a system with non-US regional settings. The issue is number format. After replacing ',' as decimal symbol to '.' all works fine.

Accuracy with ',' decimal symbol:

![image](https://user-images.githubusercontent.com/1756871/75774084-754cfa00-5d4f-11ea-929e-891b85175b34.png)

Accuracy with '.' decimal symbol:

![image](https://user-images.githubusercontent.com/1756871/75774069-6bc39200-5d4f-11ea-9274-bafc5bb4789d.png)

Is there some way to take a control of localization in .NET ML?

Thanks
Damir

**Comment by mstfbl** [comment]
Hi Damir,

You bring up a very good edge case we shouldn't forget, which is that decimal points are represented with commas in a lot of regions outside the US, (For example, 3.5 * 10^1 is represented as 3.5 in the US and 3,5 in Europe, and 3.5 * 10^5 is represented as 350,000 in the US and 350.000 in Europe). We will look into this, thank you!

**Comment by justinormont** [comment]
We may want to setup a CI leg which tests another culture. Perhaps "de-DE" or "ru-RU".

**Comment by ddobric** [comment]
How about this or similar?

> MLContext ctx = new MLContext(.., culture: CultureInfo.InvariantCulure)

**Comment by mstfbl** [comment]
Hey @ddobric , can you provide sample code and data for which you've used to obtain the difference in your results above? It'll be helpful in testing the validity of a PR to fix this issue. Thanks!

**Comment by mstfbl** [comment]
Hi @ddobric, I'm reaching out again to ask if you can provide sample code and data with which you've encountered this issue. Thanks.
