### ISSUE TITLE
how we show score,probability associated with Permutation Feature Importance (PFI) so end user can easily identify?

### ISSUE THREAD

**Issue by nighotatul** [dotnet/machinelearning#4916]
@yaeldekel,@eerhardt,@najeeb-kazmi,@justinormont,@CESARDELATORRE
references link:
[how we show permutation slot associated with feature so end user easily identify? #4739](url)

how we can get score,probability of PFI?
we have get globally score and probability but we cannot get at PFI. how we can achieve this?

**Comment by mstfbl** [comment]
Same issue as #4915
