### ISSUE TITLE
How Transformer converts structured or custom data view type into a feature value?

### ISSUE THREAD

**Issue by artemiusgreat** [dotnet/machinelearning#4923]
### System information

- **OS version/distro**: Windows 10 Pro x64
- **.NET Version (eg., dotnet --info)**: .NET Core 3.0
- **ML.NET Version**: 1.5.0-preview

### Question

When implementing a custom data view type, how does transformer know what to use as a "value" of this type? Does it use `GetHashCode()` method for this?

### Source code 

Considering, we have this custom image type with properties Width and Height. 
https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.ImageAnalytics/ImageType.cs 

Then, we have this transformer code that merges several columns into one called `Features`. 
One of these columns has type `ImageType`. 

```C#
  var pipeline = Context
    .Transforms
    .Conversion
    .Append(Context.Transforms.Concatenate("Features", new[] { "ImageColumn", "Points" }));
```

As far as I understand, for ML engine to learn something from the provided data, `Features` should be an array of float values. So, the question is, how `ImageColumn` and `Points` will be converted to floats? 

Another example that I found is this test for custom type registration. 
It's also using GetHashCode method. 
https://github.com/dotnet/machinelearning/blob/release/1.5-preview/test/Microsoft.ML.Core.Tests/UnitTests/TestCustomTypeRegister.cs

**I'd like somebody to confirm that whatever is returned from GetHashCode method will be used in training the model.**

```C#
public override int GetHashCode() // unique value for ImageType
{
    return Hashing.CombineHash(Height.GetHashCode(), Width.GetHashCode());
}
```

I'm asking because, e.g. OnnxMapType or OnnxSequenceType are completely different animals, whose GetHashCode method returns value based on a data type, not its value.
https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.OnnxTransformer/OnnxMapType.cs

```C#
public override int GetHashCode() // uniquer value for OnnxMapType
{
    return RawType.GetHashCode();
}
```

**Does it mean that ONNX types cannot be used for training because their hash code is based on a System.Type instead of actual observation?**

**Comment by najeeb-kazmi** [comment]
@artemiusgreat the `ImageType` folder needs to be vectorized with transforms before being passed to the trainer. `MLContext.Transforms.ExtractPixels` extracts a vector of RGB values. Optionally, you can also use `MLContext.Transforms.DnnFeaturizeImage` to featurize the output of `ExtractPixels` by applying a pre-trained DNN model an using its second to last layer as features. See the relevant samples [here](https://github.com/dotnet/machinelearning/tree/master/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/ImageAnalytics). Note that for `DnnFeaturizeImage`, you will need to add `MLContext.Transforms.ResizeImage` to resize the image to the size expected by the DNN model.

You can also use a pre-trained TensorFlow image model to featurize, as in this example [here](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/DeepLearning_ImageClassification_TensorFlow).

**Comment by artemiusgreat** [comment]
Thank you for the explanation @najeeb-kazmi 
How about OnnxSequenceType, can it be used the same way as VectorDataViewType, or it also needs to pre-featurized with specific transformer?

**Comment by najeeb-kazmi** [comment]
@artemiusgreat this will be the output type produced by applying an ONNX model. See example usage in these tests:
https://github.com/dotnet/machinelearning/blob/c2429fabca8b2d6bc560f7552a2d2cf1c3498789/test/Microsoft.ML.OnnxTransformerTest/OnnxTransformTests.cs#L427-L544

Are you trying to produce output from an ONNX model and then consume it in ML.NET transforms or trainers downstream?

**Comment by najeeb-kazmi** [comment]
Closing this issue. Please feel free to reopen if something remains unanswered.
