### ISSUE TITLE
Concatenating a range of columns in the data class into the "Features" column will lead to exception thrown

### ISSUE THREAD

**Issue by hellothere33** [dotnet/machinelearning#493]
Hello!

I often have CSV files with more than 50 float columns, so it's not feasible to specify each of them individually. I've failed to load them in one shot using a range/sweep specifier. To test things out in smaller scale, I used the Iris example because it ends with 4 float columns.

Here's the data class, I only added 2 lines at the end:

```
    public class IrisData
    {
        [Column("0")]
        public float Label;

        [Column("1")]
        public float SepalLength;

        [Column("2")]
        public float SepalWidth;

        [Column("3")]
        public float PetalLength;

        [Column("4")]
        public float PetalWidth;

        [Column("1-*", name: "Features")] // New
        public float[] Features; // New
    }
```

Here's the simplified pipeline, I only commented out the normal way with ColumnConcatenator:
```
            var pipeline = new LearningPipeline();
            pipeline.Add(new TextLoader(DataPath).CreateFrom<IrisData>(useHeader: true, separator: '\t'));
            //pipeline.Add(new ColumnConcatenator("Features",
            //                                    "SepalLength",
            //                                    "SepalWidth",
            //                                    "PetalLength",
            //                                    "PetalWidth"));
            pipeline.Add(new KMeansPlusPlusClusterer() { K = 3 });
            var model = pipeline.Train<IrisData, ClusterPrediction>();
```

So it worked when I load each column individually and then concatenate them in the pipeline, like the sample code says. But it always throws an exception when I use my above code:

```
System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'
Inner Exception:
InvalidOperationException: Column 'Features' is a vector of variable size, which is not supported for normalizers
```

Please help! Thank you!

=============================================================
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: .Net Framework 4.7.1

### Issue

- **What did you do?**: trying to load a CSV's multiple float columns by specifying a range in the data class's declaration, for example: "1-4"
- **What happened?**: I got an exception on the Features' size. 
- **What did you expect?**: that concatenating columns by specifying a range would work the same as adding a ColumnConcatenator to the pipeline.

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by dan-drews** [comment]
Hi,
Just a hunch here: I think that the issue might be that you are trying to reuse the Features column. The first parameter in a ColumnConcatenator is the destination column. Maybe try changing your "Features" column on your IrisData model to be called MiscFeatures or something along those lines (update the ColumnName attribute and the field name), and update the ColumnConcatenator to take in "MiscFeatures" as well.

Now I'm not certain how that will work since you'll be concatenating 2 different types (most types are float, the last one is a vector) and hopefully #535 will get an answer to further explain how we could go about concatenating these together.

**Comment by hellothere33** [comment]
Thank you @dan-drews and @Zruty0 for your suggestions!

Using VectorType(4) indeed does work. Since my actual model has varying +80 columns (which is why I used Iris only as a simpler proxy example), I'm going to try the `SchemaDefinition` as suggested.

Would you like me to close this issue, or to change its title to be about missing documentation? Let me know.

**Comment by Zruty0** [comment]
I have discovered that the [API reference](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.runtime.api?view=ml-dotnet) doesn't have a documentation for `VectorTypeAttribute`, which looks like an issue with our xmldoc tooling.


@sfilipi , would you mind taking over this issue?

Separately, I think we would benefit from a longer doc describing exactly the mechanism behind schema comprehension that we currently do: how attributes are handled, why `SchemaDefinition` is sometimes needed, what are the limitations. I'll create a separate issue for this.

**Comment by sfilipi** [comment]
Opened an issue in the docs infrastructure to track:
https://github.com/dotnet/docs/issues/6542

**Comment by hellothere33** [comment]
I couldn't find examples of `SchemaDefinition` though in the samples repo, and there are no tests in the main repo using is either, or maybe I didn't find it. Could you point me to the right direction?
Thank you!

**Comment by Zruty0** [comment]
I am in the process of writing a doc on 'schema comprehension', and it'll include examples of `SchemaDefinition` use. I'll get back to you in 0-1 days.

**Comment by Zruty0** [comment]
@hellothere33 , I have written the [schema comprehension doc](https://github.com/dotnet/machinelearning/blob/master/docs/code/SchemaComprehension.md), which contains an example of handling runtime-known column sizes.

Unfortunately, in the process I discovered that `SchemaDefinition`-aware constructors didn't make it into the `LearningPipeline` helper API, so you won't be able to easily tweak your code to make it work, like I hoped.

As we are now contemplating replacing `LearningPipeline` with something more versatile, I don'ty think we should be adding new capabilities to it.

Would you be able to have a compile time 'upper bound' on the number of features you have? You mentioned 80+, so maybe 100 would suffice? This way you can still take advantage of `[VectorType]` compile-time attribute.

**Comment by AndySweetIQ** [comment]
Thanks for the doc @Zruty0!

Yes I've been using an hard-coded upper bound array length with in combination with [VectorType]. It works. So even if it's not the cleanest, at least I'm not blocked.

**Comment by Zruty0** [comment]
I suppose we should close the issue then. Feel free to reopen if you feel otherwise.

**Comment by AndySweetIQ** [comment]
Yes, thanks everyone!
