### ISSUE TITLE
TensorFlowEstimator initialization info is missing

### ISSUE THREAD

**Issue by vslynko** [dotnet/machinelearning#4932]
`TensorFlowEstimator` is not static and has no public constructors. Therefore the link to the documentation on how to initialize `TensorFlowEstimator` is essential.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7366dd71-3899-63fb-690e-5e0d11a5bf13
* Version Independent ID: 4e44da94-51eb-2617-135a-eb71186b4da9
* Content: [TensorFlowEstimator Class (Microsoft.ML.Transforms)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.tensorflowestimator?view=ml-dotnet#feedback)
* Content Source: [dotnet/xml/Microsoft.ML.Transforms/TensorFlowEstimator.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Transforms/TensorFlowEstimator.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by najeeb-kazmi** [comment]
Hi @vslynko - thanks for reporting this. `TensorFlowEstimator` can only be initialized through the `MLContext` API entry point. Usage samples are available [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.tensorflowmodel.scoretensorflowmodel?view=ml-dotnet).

You're right, this should be mentioned on the doc page for the estimator itself, in the see also section, just like other estimators. I'll mark this as a docs issue and put it on our backlog of work items.
