### ISSUE TITLE
Not able to use LightGBM in .NET Framework 4.6.1

### ISSUE THREAD

**Issue by petterton** [dotnet/machinelearning#494]
### System information

- **OS version/distro**:
Windows 10
- **.NET Version (eg., dotnet --info)**: 
.NET Framework 4.6.1
### Issue

- **What did you do?**
I am using the 0.3.0 version NuGet package.
I tried to replicate the example at https://www.microsoft.com/net/learn/apps/machine-learning-and-ai/ml-dotnet/get-started/windows, with the small change of replacing the classifier with a LightGbmClassifier. I was able to do this with a .NET Core application (after I understood I had to add the Microsoft.ML.LightGBM Nuget package). But I need to run this in a full .NET framework application. So I followed the same procedure for a .NET Framework 4.6.1 console application. But this failed when I tried to add the Microsoft.ML.LightGBM Nuget package.

- **What happened?**
Microsoft.ML.LightGBM depends on 'LightGBM 2.1.2.2', and I get the following error:

"Could not install package 'LightGBM 2.1.2.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

- **What did you expect?**
I expected this to work, ML.NET generally works on .NET Framework 4.6.1, right?

**Comment by sharpwood** [comment]
I also encountered the same problem. Can you give me a temporary solution before this bug is fixed? @TomFinley

**Comment by Nozziel** [comment]
identical problem with .NET Framework 4.7.1

**Comment by sharpwood** [comment]
Is there a way to solve? @codemzs

**Comment by sharpwood** [comment]
what？I don't seem to find a solution. @codemzs

**Comment by codemzs** [comment]
I meant I’m investigating the issue.

**Comment by codemzs** [comment]
@sharpwood I have opened https://github.com/Microsoft/LightGBM/issues/1566 to track this.

**Comment by eerhardt** [comment]
For anyone looking for a work around until https://github.com/Microsoft/LightGBM/issues/1566 gets fixed, see https://stackoverflow.com/a/51728825/3680432.

**Comment by Ivanidzo4ka** [comment]
Looks like this issue can be closed.
