### ISSUE TITLE
How to train model from image bitmap

### ISSUE THREAD

**Issue by huy-lv** [dotnet/machinelearning#4944]
### System information
Window 10

### Issue
- **What did you do?**
Hi everyone, I want to build a model from training data like this
```
class ModelInput {
    Bitmap image { get; set; }
}
```
I cant find any example with input data as bitmap. How do i do that?

**Comment by Lynx1820** [comment]
We have a samples repository here: [machinelearning-samples](https://github.com/dotnet/machinelearning-samples ).
Some of our examples use bitmaps, like [Image Classification - AspNet core Web/service Sample](https://github.com/dotnet/machinelearning-samples/tree/e43e429cce06f246a38053e01f1a8e9392f2d36f/samples/csharp/end-to-end-apps/DeepLearning_ImageClassification_TensorFlow). 
I'm closing this, but if you have additional questions please re-open or create a new issue.
