### ISSUE TITLE
Can't load type Microsoft.ML.IPredictorProducing`1[System.Single]

### ISSUE THREAD

**Issue by infiniteloopltd** [dotnet/machinelearning#4964]
### System information

- Windows 10 Home
- .NET : .NET Core 2.1
- ML.NET : 1.5-preview2
- ML.FastTree : 1.5-preview2

### Issue:

The following error occurs when reading from disk:

Can't load type Microsoft.ML.IPredictorProducing`1[System.Single], because it has both create and constructor methods with the same visibility. Please indicate which one should be used by changing either the signature or the visibility of one of them.

Model is available here: https://github.com/infiniteloopltd/ML-Problem

May be related to [PR4385](https://github.com/dotnet/machinelearning/issues/4385)

### Source code / logs

````
var mlContext = new MLContext();
var modelPath = @"MLModel.zip";
var mlModel = mlContext.Model.Load(modelPath, out var modelInputSchema);
````

**Comment by infiniteloopltd** [comment]
Found the solution 👍

Install-Package Microsoft.ML.LightGbm -Version 1.5.0-preview2

(On the <project>ML.Model project)

**Comment by harishsk** [comment]
Thank you for updating the issue with your resolution. :-)
