### ISSUE TITLE
GPU support for LightGBM wrapper

### ISSUE THREAD

**Issue by mjmckp** [dotnet/machinelearning#500]
The LightGBM wrapper currently only allows CPU based training, however it is possible to build an instance of the LightGBM dlls which [support GPU training.](https://github.com/Microsoft/LightGBM/blob/master/docs/Installation-Guide.rst#build-gpu-version).

**Comment by Ivanidzo4ka** [comment]
DRI RESPONSE: I'm considering to move this to backlog or close it, since it require changes on LightGBM side.

**Comment by codemzs** [comment]
Please contact Guolin Ke from the light gbm team to have them include GPU Binaries in the nuget. Once they do we can add the option.
