### ISSUE TITLE
Load data without a class?

### ISSUE THREAD

**Issue by nsulikowski** [dotnet/machinelearning#501]
Is there a way to load data without creating a c# class before?
In this case I had to create the class SentimentData ahead of time:

`...CreateFrom<SentimentData>(separator: ',')`

What if I want to determine the fields/data types at run time. E.g. From an excel range, or from a DataTable

**Comment by hrkrx** [comment]
I implemented this in my own project, but honestly it is a pain to deal with, since you have to use reflections for all the types and methods.

**Comment by codemzs** [comment]
You can either create a class ahead of time or you can create the loader by inserting columns at runtime as show in this [example](https://github.com/dotnet/machinelearning/blob/0f94a3b12be82f476037d4a4ab6be06bbdcadd57/test/Microsoft.ML.Tests/Scenarios/SentimentPredictionTests.cs#L292) 

pipeline.Add(new Data.TextLoader(dataPath)
            {
                Arguments = new TextLoaderArguments
                {
                    Separator = new[] { '\t' },
                    HasHeader = true,
                    Column = new[]
                    {
                        new TextLoaderColumn()
                        {
                            Name = "Label",
                            Source = new [] { new TextLoaderRange(0) },
                            Type = Data.DataKind.Num
                        },

                        new TextLoaderColumn()
                        {
                            Name = "SentimentText",
                            Source = new [] { new TextLoaderRange(1) },
                            Type = Data.DataKind.Text
                        }
                    }
                }
            });


That being said you will need to create the class anyways to use prediction engine. We are working on a new set of APIs where you can reuse the IDataView from the loader in prediction engine.

**Comment by MeTTaxa** [comment]
Any feedback on this? this is critical for us in operationalizing models
