### ISSUE TITLE
Example of multiclass classification with random forest?

### ISSUE THREAD

**Issue by gilnahmias** [dotnet/machinelearning#503]
Looking to train multiclass classification with random forest and hyperparameter tuning.

Tried (on dotnetcore with either the latest [LightGbm nuget](https://www.nuget.org/packages/Microsoft.ML.LightGBM/) or cloning the repo directly):
```C#
var pipeline = new LearningPipeline();

pipeline.Add(new TextLoader(_dataFilePath).CreateFrom<MyDataClass>());

 // for features
pipeline.Add(new TextFeaturizer("My_Feature1_Vectorized","My_Feature1"));
pipeline.Add(new TextFeaturizer("My_Feature2_Vectorized","My_Feature2"));

// for the label
pipeline.Add(new TextFeaturizer("Label_Vectorized", "Label"));

// ** CAN'T FIND FAST FOREST MULTI CLASS CLASSIFIER ** //
pipeline.Add(new LightGbmClassifier() { NumLeaves = 5, NumTrees = 5, MinDocumentsInLeafs = 2 });

var model = pipeline.Train<MyDataClass, MyPredictionClass>();
```

This code crashes with `System.InvalidOperationException: Entry point 'Trainers.LightGbmClassifier' not found`

Also, if I'm missing any crucial steps (say around conversion from numbers to text or vice versa), please point them out.

**Comment by sfilipi** [comment]
Thanks for reporting, gilnahmias. What version of ML.Net are you using?

**Comment by gilnahmias** [comment]
Nuget: Microsoft.ML.LightGBM 0.3.0

**Comment by codemzs** [comment]
Can you please do dotnet publish?

**Comment by gilnahmias** [comment]
Thanks for the prompt reply, folks! Just tried `dotnet publish` but the result hasn't changed :(

**Comment by codemzs** [comment]
How is your code even compiling? LightGBM does not have any parameter by name NumTrees, it’s called NumBoostRound.

**Comment by gilnahmias** [comment]
I'm sorry - you're right. The code does read:
```C#
pipeline.Add(new LightGbmClassifier() { NumLeaves = 5, NumBoostRound = 5, MinDataPerLeaf = 2 });
```

It was a copy error as I renamed classes to avoid IP leakage.

**Comment by codemzs** [comment]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.lightgbmclassifier?view=ml-dotnet#properties

**Comment by gilnahmias** [comment]
Exactly. The line I just posted was copied from this link (there's an [example at the top](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.lightgbmclassifier?view=ml-dotnet#examples)). Can you spot any errors?

**Comment by gilnahmias** [comment]
Forced load the assembly using your first suggestion. The following code runs for a few minutes but returns an empty `metrics` object from the `evaluator.Evaluate()` method. Still trying to find out why.

```C#
// Workaround to ensure assembly is loaded
new LightGbmArguments();

var pipeline = new LearningPipeline();

pipeline.Add(new TextLoader(_dataFilePath).CreateFrom<MyDataClass>());

 // for features
pipeline.Add(new TextFeaturizer("My_Feature1_Vectorized","My_Feature1"));
pipeline.Add(new TextFeaturizer("My_Feature2_Vectorized","My_Feature2"));

// for the label
pipeline.Add(new Dictionarizer("Label"));

// Puts all features into a vector
pipeline.Add(new ColumnConcatenator("Features", "My_Feature1_Vectorized", "My_Feature2_Vectorized"));

pipeline.Add(new LightGbmClassifier() { NumLeaves = 5, NumBoostRound = 5, MinDataPerLeaf = 2 });

// Convert the Label back into original text(after converting to number by the Dictionarizer)
pipeline.Add(new PredictedLabelColumnOriginalValueConverter() { PredictedLabelColumn = "PredictedLabel" });

// Train
var model = pipeline.Train<MyDataClass, MyPredictionClass>();

// Evaluate
var testData = new TextLoader(_testFile).CreateFrom<MyDataClass>();
var evaluator = new ClassificationEvaluator();
var metrics = evaluator.Evaluate(model, testData);
```

**Comment by codemzs** [comment]
Test dataset schema was different from train dataset.
