### ISSUE TITLE
Slots out of range

### ISSUE THREAD

**Issue by deviousasti** [dotnet/machinelearning#5049]
In the example, won't `item.Key` go up to the bit length specified.
If there's no matching slot, this will throw.

```
            foreach (var featureRow in NgramFeaturesColumn)
            {
                foreach (var item in featureRow.Items())
                    Console.Write($"{slots[item.Key]}  "); // out of range possible
                Console.WriteLine();
            }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da8a2391-a844-b431-0b36-992fcba2aeb4
* Version Independent ID: 19a18209-4127-4079-0e38-311b7de733bd
* Content: [TextCatalog.ProduceHashedNgrams Method (Microsoft.ML)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.textcatalog.producehashedngrams?view=ml-dotnet#feedback)
* Content Source: [dotnet/xml/Microsoft.ML/TextCatalog.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML/TextCatalog.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by mstfbl** [comment]
Hi @deviousasti , I believe in this case there will always be matching slots in `slots`, as `slots` and `NgramFeaturesColumn` (source of each given `item` from each `featureRow`) share the same source `transformedDataView`.

**Comment by deviousasti** [comment]
Will there still be matching slots if repeating trigrams, for example?

**How to reproduce:**
 1. Copy the example code
 2. Replace samples with simple text like:
```
    var samples = new List<TextData>()
            {
                new TextData { Text = "I'm eating steak for dinner" },
                new TextData { Text = "I really enjoy eating lunch" },
                new TextData { Text = "I like icecream" },
                new TextData { Text = "I'm eating steak with potatoes" },
                new TextData { Text = "I'm eating steak for lunch" },
                new TextData { Text = "I'm eating waffles for breakfast" }
            };
```
**Result:**

`IndexOutOfRangeException` is thrown when looking up slots by index.
