### ISSUE TITLE
AutoML silently fails on the training phase of a binary classification problem.

### ISSUE THREAD

**Issue by CBrauer** [dotnet/machinelearning#5050]
Hey guys,

### Problem
I am submitting a test project that demonstrates a bug.
AutoML silently fails on the training phase of a binary classification problem.

### Reproducible Code
My reproducible code can by downloaded from: https://github.com/CBrauer/Test_ML.NET

### My environment is:
  Microsoft Visual Studio Professional 2019 Preview
  Version 16.6.0 Preview 2.1
  VisualStudio.16.Preview/16.6.0-pre.2.1+30001.183
  Microsoft .NET Framework
  Version 4.8.03752
I am running on Windows 10 Enterprise, version 1909 (OS Build 18.363.815).
My project uses the latest preview2 code.

### Running the test program
When you run the program you will see output like:

Running AutoML binary classification experiment using: FastTree,F1Score
     Trainer                               Accuracy    AUC       AUPRC   F1-score  Duration
   1 FastTreeBinary                         0.8610    0.7071    0.3537    0.1346    1.5480
  11 FastTreeBinary                         0.8544    0.7357    0.3300    0.2445    2.8725
  16 FastTreeBinary                         0.8722    0.7520    0.4299    0.3119   10.6857
  33 FastTreeBinary                         0.8730    0.7357    0.4213    0.3188    3.0864
  40 FastTreeBinary                         0.8730    0.7421    0.4410    0.3407   10.6638
  50 FastTreeBinary                         0.8714    0.7496    0.4230    0.3584    9.2112
  73 FastTreeBinary                         0.8695    0.7426    0.4184    0.3717   10.4270
 118 FastTreeBinary                         0.8714    0.7307    0.4090    0.3822   10.6095
 244

Each experiment should last only one-hour.  I ran the program over-night, and it never finished. 

Charles

**Comment by mstfbl** [comment]
Hi @CBrauer ,

I'm currently investigating this, and will get back to you soon.

**Comment by justinormont** [comment]
Given that each of your printed times above are 10 to 11 seconds, it's not like that you're hitting a slow trainer, though a trainer might be getting stuck.

If time expires during the training of model, it waits for that model to finish:
https://github.com/dotnet/machinelearning/blob/ee8418a4ea7f64b97db06675855d5c6aa6bb72ba/src/Microsoft.ML.AutoML/API/AutoCatalog.cs#L24-L34

Highlight: _"may run for longer ... once AutoML starts training an ML.NET model, AutoML lets the model train to completion."_

Might want to print which model & hyperparameters are being worked on, similar to how the CLI & Model Builder log the next pipeline. Or inspect in a debugger.

**Comment by CBrauer** [comment]
Hi Justin,

You didn't tell me how to solve the problem.  I waited more than 8-hours and the experiment never stopped.  What should I do when this happens?

Charles

**Comment by justinormont** [comment]
Quite correct. The above is just to help diagnose the issue. It sounds like a bug, and my top guess is a trainer is not making progress or returning/throwing.

Your code is printing after a new best model is found. It would be helpful to print which model its about to try.

One workaround to try: running as multi-class classification instead of binary.

**Comment by mstfbl** [comment]
Hi @CBrauer , I ran the code you've provided locally. It ran succesfully in under 8 hours, and provided the output I've attached to this comment.

[Issue5050Output.txt](https://github.com/dotnet/machinelearning/files/4524068/Issue5050Output.txt)

Currently, I would recommend rebuilding your project and running `Program.cs` again.

**Comment by CBrauer** [comment]
Hi Mustafa,

I rebuilt the project, as you asked. 
Now, each experiment takes one hour, as I expected.
You do good work, Thank you,  I'm very happy.

Charles

**Comment by mstfbl** [comment]
Thank you Charles for you kind words! I learned from those who've tutored me lots here at Microsoft through @harishsk, @frank-dong-ms and @justinormont, who has also helped in this specific issue. :D
