### ISSUE TITLE
Can speech recognition be done in ML.NET?

### ISSUE THREAD

**Issue by behroozbc** [dotnet/machinelearning#5054]
### System information

- **OS version/distro**:Windows
- **.NET Version (eg., dotnet --info)**: 3.1.201

### Issue
hi 
i want to Speech recognition in ml .net i see issue list in #2732 is same but i want know now i can do it or not ??

**Comment by mstfbl** [comment]
Hi @behroozbc ,
As @Lynx1820 mentioned in Issue #2732 , ML.NET currently doesn't directly support speech recognition. However, you can create a TensorFlow model and consume it with ML.NET! More info can be found here: [Run with ML.NET C# code a TensorFlow model exported from Azure Cognitive Services Custom Vision](https://devblogs.microsoft.com/cesardelatorre/run-with-ml-net-c-code-a-tensorflow-model-exported-from-azure-cognitive-services-custom-vision/)
