### ISSUE TITLE
Converting Naive Bayes Scores to Probabilities

### ISSUE THREAD

**Issue by nathanlamplough-MeVitae** [dotnet/machinelearning#5061]
Hello,
What are the scores produced from the NaiveBayes classifier, are they log probabilities? As I seem to get very large minus values. Whereas I did something similar in sci-kit learns NaiveBayes and the log probabilities were much lower negative values. How do you suggest converting these scores to probabilities? Should I call an exponential function on them if they are in fact log probabilities?

Thanks

**Comment by mstfbl** [comment]
Hi @nathanlamplough-MeVitae,

Thank you for your question. The scores produced from the Multi-Class Naive Bayes trainer are log probabilities.
https://github.com/dotnet/machinelearning/blob/e1fe0a85c72ac010392a4f38f0037bec596513f2/src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs#L570-L633
It would be helpful if we can see your comparison between the ML.NET and Scikit versions of your Naive Bayes implementations. Please feel free to share your ML.NET and Scikit code so we can be of more help. Thanks!

**Comment by Lynx1820** [comment]
Hi @nathanlamplough-MeVitae , 

You should be able to take the exponent of the scores.  Do you know which type of Naive Bayes Scikit is using?

**Comment by nathanlamplough-MeVitae** [comment]
Hi @mstfbl and @Lynx1820 

I realized that the Naive Bayes in ML.net supports binary feature values and is not the multinomial variation I was using in scikit so I think that explains my big differences in size of log probabilities. Thanks for the help anyways.
