### ISSUE TITLE
deterministic result in ML.net | KmeansTrainer vs EstimatorChain<ClusteringPredictionTransformer<Microsoft.ML.Trainers.KMeansModelParameters>>

### ISSUE THREAD

**Issue by scorp-gitcontainer** [dotnet/machinelearning#5065]
### System information

- **OS version/distro**:
- **.NET Version (eg., dotnet --info)**: 

### Issue

- **What did you do?** 
Perform a clustering on some datas using ML.net and clustering based on the iris sample on docs.microsoft.com
- **What happened?**
We have noticed that the result are not deterministic for a specified feature vector when a non vector property of the class value changes.

- **What did you expect?**
We expected the ml.net clustering algorithm to issue always the same result in the same conditions if the feature array remains the same even if another property of the data class is modified.

### Source code / logs

string featuresColumnName = _featureColumnName;
            var pipeline = _mlContext.Transforms
                .Concatenate(featuresColumnName, featureArrayLabel)
                .Append(_mlContext.Clustering.Trainers.KMeans(featuresColumnName, numberOfClusters: _cluster));
           pipeline;
when pipeline is EstimatorChain<ClusteringPredictionTransformer<Microsoft.ML.Trainers.KMeansModelParameters>> 
the fit method is not derministic

**Comment by Lynx1820** [comment]
Hi @scorp-gitcontainer 
What do you mean by "non vector property of the class value changes"? The Kmeans algorithm performs random initialization, so it's expected to produce different results each time, unless you establish a seed on your MLContext, i.e.  `var mlContext = new MLContext(seed: 1);`

**Comment by scorp-gitcontainer** [comment]
say i have a class like following
public class DataBundle
{ 
    public float AM {get;set;}
   public float DJ  {get;set;}
public float LK {get;set;}
public float MP {get;set;}
public float V {get;set;}

public float[] Features { return new float[](AM,MP,LK,DJ )}
}

property "V" is what i call a non vector property. in my own example; we first implemented clustering base on iris sample on docs.microsoft.com. That sample uses EstimatorChain and even though seed is set to 0 (which is not null)
we figured out the result of prediction changes anytime V is modified although it is not specified as feature to take in account

**Comment by Lynx1820** [comment]
I tried replicating, but I did not get different results. Is possible that somewhere along the way you're forgetting to include the `_mlContext`? Can you check whether getting rid of the V features from Databundle produces different results on each run?

**Comment by Lynx1820** [comment]
Closing this issue. Feel free to reopen if you have a followup.
