### ISSUE TITLE
Update NumberOfThreads default value for MatrixFactorization trainer 

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning#5067]
The default value for MatrixFactorization will use all threads, which might trigger a warning in [libmf](https://github.com/cjlin1/libmf/blob/e70b9a32f7df32cce961bbbb997da074759a16fe/mf.cpp#L4024) when it exceeds two times of nr_bins.

**Comment by LittleLittleCloud** [comment]
https://github.com/dotnet/machinelearning/blob/5a30444f3c85dfafa1f6032813904fbc8e69eae7/src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs#L516

Just update `Math.Max(20, 2 * _threads)` to `Math.Max(20, 2 * _threads)-1` should work

**Comment by harishsk** [comment]
@LittleLittleCloud Can you please submit a PR?

**Comment by Lynx1820** [comment]
Thanks for the PR @LittleLittleCloud. Closing this issue.
