### ISSUE TITLE
Microsoft.ML with onnx can not get Column

### ISSUE THREAD

**Issue by strikene** [dotnet/machinelearning#5069]
### System information

- **OS version/distro**: win10 1909
- **.NET Version (eg., dotnet --info)**: Core 3.1

### Issue

An exception occurred while getting the inference result 
Exception:
System.ArgumentOutOfRangeException: 'Cannot map column (name: loss, type: Microsoft.ML.Transforms.Onnx.OnnxSequenceType) in data to the user-defined type, ConsoleApp1.OutPut. (Parameter 'column')'

### Source code / logs
Package 
    Microsoft.ML1.5.0-preview2
    Microsoft.ML.ImageAnalytics1.5.0-preview2
    Microsoft.ML.OnnxRuntime1.2.0
    Microsoft.ML.OnnxTransformer1.5.0-preview2

Code 
    Console.WriteLine("Hello World!");
            MLContext mlContext = new MLContext();
            var data = mlContext.Data.LoadFromEnumerable(new List<ApiInput>());
            var PIL = mlContext.Transforms.LoadImages(outputColumnName: "data",
                imageFolder: null,
                inputColumnName: "ImagePath")
                .Append(mlContext.Transforms.ResizeImages(outputColumnName: "data", imageWidth: 224, imageHeight: 224, inputColumnName: "data"))
                .Append(mlContext.Transforms.ExtractPixels(outputColumnName: "data"))
                .Append(mlContext.Transforms.ApplyOnnxModel(outputColumnName: "loss", inputColumnName:  "data" , modelFile: "model.onnx"));
            var model = PIL.Fit(data);
            var ss = new List<ApiInput>
            {
                new ApiInput() { ImagePath = "C:\\1.png" }
            };
            var data1 = mlContext.Data.LoadFromEnumerable(ss);
            var reml = model.Transform(data1);
            var re = reml.GetColumn<OutPut>("loss");

 public class ApiInput
    {
        public string ImagePath { get; set; }
    }

  public class OutPut
    {
        [OnnxSequenceType(typeof(string))]
        public string n;
        [OnnxSequenceType(typeof(float))]
        public float n1;

    }
The input and output of the model is shown below
![_(($TF0ZVX43WZD)O4E~WHX](https://user-images.githubusercontent.com/62022463/80564103-77fe5f80-8a1f-11ea-9c61-8d2e3ae1ec55.png)

There are two kinds of output in this model. I can get the result in classLabel normally, but for loss I have not found any method that can get it correctly

**Comment by Lynx1820** [comment]
Your output should look something like this: 
`        public class LossOutput
        {`
            `[OnnxSequenceType(typeof(IDictionary<string, float>))]`
            `public IEnumerable<IDictionary<string, float>> output { get; set; }`
       ` }`

**Comment by strikene** [comment]
> Your output should look something like this:
> ` public class LossOutput {`
> `[OnnxSequenceType(typeof(IDictionary<string, float>))]`
> `public IEnumerable<IDictionary<string, float>> output { get; set; }`
> ` }`

I will get the same error according to your suggestion 
if i change public IEnumerable<IDictionary<string, float>> output { get; set; }=>public IEnumerable<IDictionary<string, float>> output { get; set; }
This will also cause the same error

**Comment by Lynx1820** [comment]
Hi @strikene, 

You want to use `data.Schema["loss"]`. Take a look at how to use getColumn here: [GetColumnTests](https://github.com/dotnet/machinelearning/blob/master/test/Microsoft.ML.Tests/Scenarios/GetColumnTests.cs). Also, see this test to see how we use OnnxSequenceType in a test: [OnnxTransformTests](https://github.com/dotnet/machinelearning/blob/master/test/Microsoft.ML.OnnxTransformerTest/OnnxTransformTests.cs#L450).

**Comment by Lynx1820** [comment]
Hi @strikene, 

Take a look at the examples where we use OnnxSequenceTypes [OnnxTransformTests](https://github.com/dotnet/machinelearning/blob/master/test/Microsoft.ML.OnnxTransformerTest/OnnxTransformTests.cs#L450). For `getColumn()` you want to use `getColumn<IEnumerable<IDictionary<string, float>>>` instead of using LossOutput.

**Comment by Lynx1820** [comment]
Closing this issue. If you have further questions, please feel free to reopen.

**Comment by strikene** [comment]
> Hi @strikene,
> 
> Take a look at the examples where we use OnnxSequenceTypes [OnnxTransformTests](https://github.com/dotnet/machinelearning/blob/master/test/Microsoft.ML.OnnxTransformerTest/OnnxTransformTests.cs#L450). For you want to use instead of using LossOutput.`getColumn()``getColumn<IEnumerable<IDictionary<string, float>>>`

After I upgraded the package to version 1.5.2, the problem was resolved 

<PackageReference Include="Microsoft.ML.OnnxRuntime.Managed" Version="1.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="Microsoft.Extensions.ML" Version="1.5.2" />
    <PackageReference Include="Microsoft.ML" Version="1.5.2" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.4.0" />
    <PackageReference Include="Microsoft.ML.ImageAnalytics" Version="1.5.2" />
    <PackageReference Include="Microsoft.ML.OnnxTransformer" Version="1.5.2" />
    <PackageReference Include="Microsoft.ML.Vision" Version="1.5.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.ML" Version="1.5.2" />
