### ISSUE TITLE
PipelineInference creates invalid JSON

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning#507]
Currently, PipelineInference creates an EntryPoint JSON graph beginning with:
```json
{'Nodes' : [{
  "Name": "TextAnalytics.TextTransform",
  "Inputs": {
    "Column": {
      "Name": "text_tf",
      "Source": [
        "text"
      ]
    },
    
}}]}
```

The initial `'Nodes'` should have double-quotes like `"Nodes"`. JSON spec requires double quotes on keys. 

As is, this fails a JSON.parse(), which makes the created JSON difficult to work with in NodeJS.

Source of the issue:
https://github.com/dotnet/machinelearning/blob/9d19d0e7058e328ead93f549205e5c329324ec05/src/Microsoft.ML.PipelineInference/PipelinePattern.cs#L276

**Comment by jwood803** [comment]
@justinormont I added PR #516. I'm going to see about adding a test for this, but if there's anything else I need to add to it, just let me know.

**Comment by justinormont** [comment]
Closed by https://github.com/dotnet/machinelearning/pull/516
