### ISSUE TITLE
Run Evaluation on full test dataset

### ISSUE THREAD

**Issue by luistelmocosta** [dotnet/machinelearning#5073]
Hello, I would like to know how do I run the evaluation on the full test dataset instead of doing it in a single line.

I noticed that in `Program.cs` we are only running the prediction for one single line:

```
// Here (ModelInput object) you could provide new test data, hardcoded or from the end-user application, instead of the row from the file.
            ModelInput sampleForPrediction = mlContext.Data.CreateEnumerable<ModelInput>(dataView, false)
                                                                        .First();
```

Is there any other option to run on the full test set? 

Kind regards

**Comment by Lynx1820** [comment]
Hi @luistelmocosta , 

You can get rid of the `.First()` at the end, and then iterate through the results by using `sampleForPrediction.MoveNext().` Take a look at how we do it in our tests: [TimeSeriesSimpleApiTests](https://github.com/dotnet/machinelearning/blob/master/test/Microsoft.ML.TimeSeries.Tests/TimeSeriesSimpleApiTests.cs)

**Comment by Lynx1820** [comment]
Closing this issue. Feel free to reopen if you have a follow up.
