### ISSUE TITLE
Add new models in prediction pool during runtime

### ISSUE THREAD

**Issue by iluveu28** [dotnet/machinelearning#5096]
I have two separate .NET Core Web API projects deployed to Kubernetes as separate Docker containers. One for training and the other for predictions. The users can upload a training file into the training API to create a new model and the filename and path of the model.zip file are saved into a table in SQL Server DB and the model.zip file is saved in PersistentVolume. 

In the prediction service, I create the PredictionEnginePool in ConfigureServices in Startup.cs. 

How can I lookup a model by name to check if my models have been loaded into the pool and if not, how can I dynamically add the newly trained models that had just been created by the separate training API without having to restart the prediction API ? Is there any way I can do this outside of the Startup.cs e.g. in the controller so that I can take control of the pool at runtime?

Can you provide sample codes that dynamically read .zip files from a folder, check if they're already in the pool and if not then add it into the prediction pool, all done inside a controller?

**Comment by iluveu28** [comment]
I think if you make the AddPredictionEnginePool method available to an injected instance outside the startup.cs, it will solve my problem :-

predictionEnginePool.AddPredictionEnginePool<InputModel, MulticlassClassificationPrediction>()
                                .FromFile(modelName: modelName, filePath: $"MLModels/{modelName}.zip", watchForChanges: true);

**Comment by cricketthomas** [comment]
@iluveu28 were you able to find a work around in the meantime?

**Comment by iluveu28** [comment]
I decided not to use the pool anymore
