### ISSUE TITLE
Negative scores evalauate for LightGBMMulti model

### ISSUE THREAD

**Issue by kik3r** [dotnet/machinelearning#5101]
I have a multi class classification model trained to classify to 3 values (-1,0,1) looking at 26 feature columns which are RGB color values as float.
when predicting, score values returned are sometimes negative. From my basic understanding, the score values are confidence on each class and they should add up to 1 and each value should be between 0 and 1.

Model was created using AutoML.
MulticlassExperimentSettings settings = new MulticlassExperimentSettings
{
    MaxExperimentTimeInSeconds = (uint)(trainer.TrainingDuration * 60),
    CacheDirectory = new DirectoryInfo(ModelCache),
    OptimizingMetric = MulticlassClassificationMetric.MicroAccuracy
};

var experiment = mlContext.Auto().CreateMulticlassClassificationExperiment(settings);
var progress = new Progress<RunDetail<MulticlassClassificationMetrics>>(p =>{});
var result = experiment.Execute(trainSet, testSet, labelColumnName: "Classification", progressHandler: progress);

![vs](https://user-images.githubusercontent.com/31455766/81232882-eceb0f80-8fb2-11ea-9686-acba9c57b898.jpg)

**Comment by harishsk** [comment]
Is it possible for you to share the code and some sample data for this issue?

**Comment by harishsk** [comment]
As discussed offline, you may end up with negative scores when the underlying model is not capable of producing probabilities.
