### ISSUE TITLE
Issue with image classification trainer creating files (such as TrainingSetSize.txt) on WebJobs

### ISSUE THREAD

**Issue by ddobric** [dotnet/machinelearning#5111]
Running the ML.NET image classification inside of WebJob (windows platform/.NET Core 3.1)
All works fine when executed locally. Unfortunately, when running as job it fails with the following error: 

> 2020-05-09T19:30:04  PID[9552] Information       The building model process has failed.
> 2020-05-09T19:30:04  PID[9552] Information System.IO.FileNotFoundException: Could not find file 'C:\DWASFiles\Sites\#1prodidentweb-training-webjob\cache\TrainingSetSize.txt'.
> 2020-05-09T19:30:04  PID[9552] Information File name: 'C:\DWASFiles\Sites\#1prodidentweb-training-webjob\cache\TrainingSetSize.txt'
> 2020-05-09T19:30:04  PID[9552] Information    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
> 2020-05-09T19:30:04  PID[9552] Information    at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
> 2020-05-09T19:30:04  PID[9552] Information    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
> 2020-05-09T19:30:04  PID[9552] Information    at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
> 2020-05-09T19:30:04  PID[9552] Information    at System.IO.StreamReader..ctor(String path)
> 2020-05-09T19:30:04  PID[9552] Information    at System.IO.File.OpenText(String path)
> 2020-05-09T19:30:04  PID[9552] Information    at Microsoft.ML.Vision.ImageClassificationTrainer.GetNumSamples(String path)
> 2020-05-09T19:30:04  PID[9552] Information    at Microsoft.ML.Vision.ImageClassificationTrainer.TrainAndEvaluateClassificationLayer(String trainBottleneckFilePath, Options options, String validationSetBottleneckFilePath, Int32 trainingsetSize)
> 2020-05-09T19:30:04  PID[9552] Information    at Microsoft.ML.Vision.ImageClassificationTrainer.TrainModelCore(TrainContext trainContext)
> 2020-05-09T19:30:04  PID[9552] Information    at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
> 2020-05-09T19:30:04  PID[9552] Information    at Microsoft.ML.Trainers.TrainerEstimatorBase`2.Fit(IDataView input)
> 2020-05-09T19:30:04  PID[9552] Information    at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
> 2020-05-09T19:30:04  PID[9552] Information    at Microsoft.ML.TrainCatalogBase.CrossValidateTrain(IDataView data, IEstimator`1 estimator, Int32 numFolds, String samplingKeyColumn, Nullable`1 seed)
> 2020-05-09T19:30:04  PID[9552] Information    at Microsoft.ML.MulticlassClassificationCatalog.CrossValidate(IDataView data, IEstimator`1 estimator, Int32 numberOfFolds, String labelColumnName, String samplingKeyColumnName, Nullable`1 seed)

Creating of the text file seems not to be correctly implemented. If the path is not set to the permitted location, the required text file will not be created. In that case another error message should be created. 
For example, following path is in WebJob (hosted in IIS) not allowed:

`C:\DWASFiles\Sites\#1prodidentweb-training-webjob`

It corresponds to %AppData% of the local machine. It is the working folder of IIS in context of an Azure Job. By changing the path to following one, all will work fine:

`C:\DWASFiles\Sites\#1prodidentweb-training-webjob\Local`
 
In the code, this can be achieved by following:
~~~
WorkspacePath = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
~~~

### Recap
Trainer creates internally many files. One of them is *TrainingSetSize.txt*. If the *options.WorkspacePath* is set to location on which the process has no write permission, the correct exception should be thrown. 

This might also be a security issue is one chose path like "WorkspacePath = "..\..\xy". That would lead the job process to touch the path, which possibly belongs to the job owned by some other customer. At the moment of writing of this, I didn't see security issue here, but who know what might happen in the future.

**Comment by antoniovs1029** [comment]
Hi, @ddobric . Thanks for reporting this.

So, just to make sure, it looks to me you're describing 2 problems / suggestions:
1. Using the default path for `WorkspacePath `on an `ImageClassificationTrainer `leads to an exception when running on `WebJobs`.
2. The `ImageClassificationTrainer `should throw an exception if it doesn't have permissions to write on the `WorskpacePath`, and it shouldn't actually try to "touch" the path if it doesn't have permissions.

Problem 1. gets solved by simply changing the `WorkspacePath` on `ImageClassificationTrainer.Options` to be `Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData)`.

So problem 1 is not a bug, nor a real issue, and you don't have any problem training your model after changing the `WorskpacePath`. Am I right?

**Comment by frank-dong-ms** [comment]
@antoniovs1029 please follow up on this issue, if no more question from user you can close the issue, thanks

**Comment by antoniovs1029** [comment]
@frank-dong-ms I'm still waiting for the user response to see if I am understanding this issue correctly and decide if it's either a P1 or P2 (or perhaps P0).

**Comment by antoniovs1029** [comment]
Since we haven't received an answer from the user, I'm unable to assess if this is an actual bug or a feature request to handle exceptions better in the user's particular use case. Because of this I'll simply change the priority of this to P2.

**Comment by frank-dong-ms** [comment]
This has already been fixed in below PR: https://github.com/dotnet/machinelearning/pull/4522
We no longer save training set size to text file on file system. Close this issue.
