### ISSUE TITLE
Remove commented code

### ISSUE THREAD

**Issue by dan-drews** [dotnet/machinelearning#513]
While digging into the source code, I discovered a large amount of commented out code throughout the solution.

Unless there is a reason behind this that I am not aware of, I think it is best to remove this. In a worst-case scenario, we have the git history to take care of this.

One example is in UnbufferedStream.cs, the following code is all commented out:

    //}
    //if (checkStream == null)
    //{
    //    checkStream = new FileStream(fileName, FileMode.Open, FileAccess.Read, FileShare.Read);
    //}
    //byte[] cbuf = new byte[count];
    //int checkRead = checkStream.Read(cbuf, 0, cbuf.Length);
    //if (checkRead != read)
    //{
    //    Console.WriteLine("!!! bytes read mismatch at " + fileName + ": "  + checkStream.Position + " / " + Position + ": " +
    //        "read = " + read + "; checkRead = " + checkRead);
    //}
    //else
    //{
    //    Console.WriteLine(">>> bytes read match at " + fileName + ": " + checkStream.Position + " / " + Position + ": " +
    //        "read = " + read + "; checkRead = " + checkRead);
    //}

I haven't yet discovered the extent of this, but I think some work should be done on this.

**Comment by shauheen** [comment]
Thanks @dan-drews , this is great. I do not see a reason for keeping unnecessary commented out code.

**Comment by Ivanidzo4ka** [comment]
Can we just nuke [Microsoft.ML.InternalStreams](https://github.com/dotnet/machinelearning/tree/master/src/Microsoft.ML.InternalStreams)?
Not sure how they get leaked in this repo.

**Comment by dan-drews** [comment]
@Ivanidzo4ka I was curious about that too. Is there any background on that project?

There is a lot of code in there that just feels very old. I came across several properties that were not auto-properties, there are tons of #IF compiler directives that seem to have no use, etc...

**Comment by Ivanidzo4ka** [comment]
This is really old code which has nothing to do with ML.NET, and I'm not sure how it end up in this repository. Generally it's suppose to provide wrappers to access different types of streams (SQL tables for example) but again this is really old code, (pre dotnet CLR) which not suppose to be in this repository.
So feel free to delete whole project and any mentions of it.
