### ISSUE TITLE
Is it possible to avoid the runtimes folder in build output

### ISSUE THREAD

**Issue by ThomasArdal** [dotnet/machinelearning#5142]
I have included the `Microsoft.ML` and `Microsoft.ML.TimeSeries` packages in an ASP.NET Core 3.1 project. Things are working great. I noticed that when including those packages in my project, I get a `runtimes` folder (almost 300 MB) in my build output. Setting `--self-contained false` as a parameter for my `deploy` command still include this folder. I have been reading about this folder being included when project includes code generating assemblies. Do one of these packages include such assemblies and is it possible to avoid having this `runtimes` folder as part of the build output?

**Comment by frank-dong-ms** [comment]
Thanks for using ML.NET. 

No, it is not possible to avoid the runtimes folder. This runtimes folder contains native components that ML.NET is depending on for tasks like mathematical calculation.

There are 4 folders inside runtimes folder that contains 4 version of native components(Linux-x64, osx-x64, win-x64 and win-x86), you can manually delete some of these 4 folders if they are not required and disk space is big issue for you(delete osx-x64 if you know that your program will never run on mac os, although this is not recommended).

**Comment by ThomasArdal** [comment]
Thank you for that explanation. Makes total sense 👍

**Comment by frank-dong-ms** [comment]
Thanks, I will close the issue now, feel free to reopen or raise new issue if necessary.
