### ISSUE TITLE
CustomMappingEstimator Exportable to ONNX?

### ISSUE THREAD

**Issue by dcostea** [dotnet/machinelearning#5156]
### Question

- **Will be CustomMappingEstimator exportable to ONNX in the future?**

**Comment by antoniovs1029** [comment]
We have no immediate plans for exporting CustomMappingEstimator to onnx.

Still, we would love to hear more about your scenario to understand the usecase better. Thanks 😄

**Comment by dcostea** [comment]
> We have no immediate plans for exporting CustomMappingEstimator to onnx.
> 
> Still, we would love to hear more about your scenario to understand the usecase better. Thanks 😄

Sure. Thank you for your response.
I have used CustomMappingEstimator to extract hour and day from a DateTime feature and it seems the trained model cannot be saved in ONNX format because of this transformer.
This transformer not being convertible to ONNX stops me from building more complex pipelines like the aforementioned one.
The alternative would be:
- to make the changes in my dataset (yuck).
- to convert my DataView to IEnumerable, do the changes, and then converting it back to DataView (this is more like a workaround).
Did I miss another (maybe a more elegant) way to do the split of DateTime CreateAt feature into Hour and Day features?

This is the exception:
System.InvalidOperationException: The targeted pipeline can not be fully converted into a well-defined ONNX model. Please check if all steps in that pipeline are convertible to ONNX and all necessary variables are not dropped (via command line arguments).

```
// original features: "Temperature", "Luminosity", "Infrared", "Distance", "CreatedAt"
// CreatedAt -> Hour, Day
var featureColumns = new[] { "Temperature", "Luminosity", "Infrared", "Distance", "Hour", "Day" };
var preprocessingPipeline = mlContext.Transforms.Conversion.MapValueToKey("Label")
    .Append(mlContext.Transforms.CustomMapping<CustomInputRow, CustomOutputRow>
        (CustomMappings.IncomeMapping, nameof(CustomMappings.IncomeMapping)))
    .Append(mlContext.Transforms.Concatenate("Features", featureColumns))
    .Append(mlContext.Transforms.NormalizeMinMax("Features"));
```

these are the Mapping related classes:
```
public class CustomInputRow
{
    public string CreatedAt;
}

public class CustomOutputRow
{
    public float Hour;
    public float Day;
}

[CustomMappingFactoryAttribute(nameof(CustomMappings.IncomeMapping))]
public class CustomMappings : CustomMappingFactory<CustomInputRow, CustomOutputRow>
{
    public static void IncomeMapping(CustomInputRow input, CustomOutputRow output)
    {
        output.Hour = DateTime.Parse(input.CreatedAt).Hour;
        output.Day = DateTime.Parse(input.CreatedAt).DayOfYear;
    }

    // This factory method will be called when loading the model to get the mapping operation.
    public override Action<CustomInputRow, CustomOutputRow> GetMapping()
    {
        return IncomeMapping;
    }
}
```

**Comment by antoniovs1029** [comment]
Thanks for your quick response. I can see that not being able to export a CustomMappingTransformer is a problem in pipelines such as yours, that need it for preprocessing. Unfortunately, as mentioned above, it's not in our current plans to make it ONNX exportable 😕 .

Having said that, I think the workarounds you mentioned would work (albeit not being very user friendly). I am also wondering if the following workaround would work (I haven't tested it, but I think I have reasons to believe it might work, but I'm also concerned that it might not work for other reasons... so I'm unsure).

So the other workaround would be splitting your pipeline as this, so that the model that you export to Onnx doesn't include the custom mapping estimator you used while preprocessing. 

```C#
var customPipeline = mlContext.Transforms.CustomMapping<CustomInputRow, CustomOutputRow>
        (CustomMappings.IncomeMapping, nameof(CustomMappings.IncomeMapping)));

var customModel = customPipeline.Fit(inputDV);
var customDV = customModel.Transform(inputDV);

var restOfPipeline = ... // Add every other step of your pipeline which doesn't include custom mapping

var model = restOfPipeline.Fit(customDV);
ConvertToOnnx(model, customDV);
```

if that works, then maybe this could also be a valid workaround for your use case?

Of course, the inconvenience is that the exported Onnx model wouldn't contain the transformation to get the Hour and Day columns. So the workaround would also require you to save as a separate model the `customModel` created above, and then always apply that model before applying the Onnx model. So I don't know if that's good for your use case.

**Comment by justinormont** [comment]
@dcostea: Another route would be to use the `FeaturizeDateTime` transform. I think the outputs you're creating match the `DTCHour` and `DTCDayOfYear` columns.

Example usage:
https://github.com/dotnet/machinelearning/blob/290e0695b22cf9c6f49fcd222b10553b5a19a63a/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Featurizers/DateTimeTransformer.cs#L29-L54

**Comment by antoniovs1029** [comment]
@justinormont The problem with FeaturizeDateTime is that it requires the input column to have a long int:
https://github.com/dotnet/machinelearning/blob/85f8eaa8d52611fb4323036a5e16bc96c55cc3c5/src/Microsoft.ML.Featurizers/DateTimeTransformer.cs#L38-L50

whereas in the use case here the input is a string specifying a date.

**Comment by dcostea** [comment]
Thank you for your exhaustive response!
The second solution, using DateTimeTransformer, is a better fit for my use-case since I don't have to ignore the DateTime features.
For other types, I will try to preprocess.

You are doing great with ML.NET, keep up the good work!

**Comment by justinormont** [comment]
> @justinormont The problem with FeaturizeDateTime is that it requires the input column to have a long int:

@antoniovs1029: Do we have an issue logged to allow `FeaturizeDateTime` to take in a `DateTime` column?

@dcostea: `TypeConvertingEstimator` looks like it can convert from `DateTime` (`DT`) to `Long` (`I8`):
https://github.com/dotnet/machinelearning/blob/bc9abda576374340e2fa37f968ee1eb7eab90211/src/Microsoft.ML.Data/Data/Conversion.cs#L819

You'll want to read in your column w/ type `DateTime`: (then convert w/ `TypeConvertingEstimator`)
https://github.com/dotnet/machinelearning/blob/b861b5d64841cbe0f2c866ee7586872aac450a51/test/Microsoft.ML.Functional.Tests/Datasets/TypeTestData.cs#L61-L62

**Comment by justinormont** [comment]
It looks like `FeaturizeDateTime` will take in `DateTime` column directly:
https://github.com/dotnet/machinelearning/blob/d8cb431773915a59f2728e254a02536bb83ba387/test/Microsoft.ML.Tests/Transformers/DateTimeTransformerTests.cs#L137-L145

@dcostea: You should be able to just read in the column as a `DateTime` and transform it w/ `FeaturizeDateTime`. No conversion to a `Long` is needed.

**Comment by antoniovs1029** [comment]
The `date` field in the sample you've pointed to is long:
https://github.com/dotnet/machinelearning/blob/d8cb431773915a59f2728e254a02536bb83ba387/test/Microsoft.ML.Tests/Transformers/DateTimeTransformerTests.cs#L21-L25

So I guess the casting is done by C# when compiling that. Still, the FeaturizeDateTime does require a long input column. I don't know what would happen if a DateTime column is provided, but I wouldn't expect the casting to be done automatically.

**Comment by antoniovs1029** [comment]
> @antoniovs1029: Do we have an issue logged to allow FeaturizeDateTime to take in a DateTime column?

No, but as you pointed out, using the TypeConvertingEstimator should be a valid and easy workaround, so no need to add an issue for this, I guess?
