### ISSUE TITLE
InvalidOperationException - Invalid TValue in GetGetter: 'System.Collections.Generic.IEnumerable`1[System.Collections.Generic.IDictionary`2[System.Int64,System.Single]]'

### ISSUE THREAD

**Issue by marcmm** [dotnet/machinelearning#5181]
### System information
- Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 .Net Framework 4.7.2 x64

Libraries:
Microsoft.ML 1.5.0
Microsoft.ML.OnnxTransformer 1.5.0
Microsoft.ML.OnnxRuntime 1.3.0

- Issue:
The following code below fails with an InvalidOperationException - Invalid TValue in GetGetter: 'System.Collections.Generic.IEnumerable`1[System.Collections.Generic.IDictionary`2[System.Int64,System.Single]]'

- Repro steps below
- Trying to get the output_probability field (which is Sequence of Maps) from an sklearn RandomForestClassifier model converted to onnx using skl2onnx library.
- I expected ML.Net to support this scenario since I have seen other posts of users using similar fields as models outputs.

Call Stack:
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Invalid TValue in GetGetter: 'System.Collections.Generic.IEnumerable`1[System.Collections.Generic.IDictionary`2[System.Int64,System.Single]]'
   at Microsoft.ML.Data.RowToRowMapperTransform.Cursor.GetGetter[TValue](Column column)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.CreateDirectSetter[TDst](DataViewRow input, Int32 col, Delegate poke, Delegate peek)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.GenerateSetter(DataViewRow input, Int32 index, Column column, Delegate poke, Delegate peek)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase..ctor(TypedCursorable`1 parent, DataViewRow input, String channelMessage)
   at Microsoft.ML.Data.TypedCursorable`1.GetCursor(Func`2 additionalColumnsPredicate, Nullable`1 randomSeed)
   at Microsoft.ML.Data.TypedCursorable`1.GetCursor()
   at Microsoft.ML.PipeEngine`1.<RunPipe>d__3.MoveNext()
   at testonnx.Program.Main(String[] args)

### Source code Repro:
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Transforms.Onnx;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace testonnx
{
    public class OutputData
    {
        [ColumnName("output_probability")]
        [OnnxSequenceType(typeof(IDictionary<long, float>))]
        public IEnumerable<IDictionary<long, float>> OutputProbabilities;
    }

    public class InputData
    {
        [ColumnName("float_input")]
        [VectorType(4)]
        public float[] Input { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var outputSchemaDef = SchemaDefinition.Create(typeof(OutputData));
            var inputSchemaDef = SchemaDefinition.Create(typeof(InputData));
            var mlContext = new MLContext();
            var pipeline = mlContext.Transforms
               .ApplyOnnxModel(new string[] { "output_probability", "output_label" }, new string[] { "float_input" }, "rf_iris_new.onnx");

            var inputs = new List<InputData>() { new InputData() { Input = new float[] { 3.1f, 0.9f, 1.2f, 0.8f } } };

            var data = mlContext.Data.LoadFromEnumerable(inputs, inputSchemaDef);

            var model = pipeline.Fit(data);

            var transformedValues = model.Transform(data);

            var predictions = mlContext.Data.CreateEnumerable<OutputData>(
                transformedValues, reuseRowObject: false, true, outputSchemaDef);

            foreach (var pred in predictions) 
            {
                Console.WriteLine(pred.OutputProbabilities.First()[0].ToString());              
            }
        }
    }
}

[rf_iris_new.zip](https://github.com/dotnet/machinelearning/files/4705133/rf_iris_new.zip)

**Comment by marcmm** [comment]
Thanks Michael for unblocking me. I still think there's a bug in the code. I noticed that if the class only contains the  OutputProbabilities field and do not pass the "output_label" to the ApplyOnnxModel method, I also get the same exception.

**Comment by michaelgsharp** [comment]
@marcmm There is a bug in the code. I have found it and am about to create a PR to resolve it. The issue has to do with how the output column mapping was being handled. It was by name and index, but there were 2 different indexes being used, the index based on the original onnx model and the index based on the output order given, and when the indexs didn't match there was a problem. 

Honestly, the easiest way I think to handle this for now is to use the `ApplyOnnxModel` overload that only takes the model path. It will automatically get the correct input/output names and you wont have to worry about order of the columns. Even after the fix goes in you will have to wait until the next release for this fix unless you build a local copy yourself.
