### ISSUE TITLE
CI crash on mac os 

### ISSUE THREAD

**Issue by frank-dong-ms** [dotnet/machinelearning#5184]
Randomly see below 3 crash only on mac os:

https://dev.azure.com/dnceng/public/_build/results?buildId=637346&view=logs&jobId=23576d1c-355e-5d27-4c31-0725f923794b&j=23576d1c-355e-5d27-4c31-0725f923794b&t=5b5048ea-91bc-5d7d-fb0b-ace30192f432

The active Test Run was aborted because the host process exited unexpectedly while executing following test(s):
Microsoft.ML.RunTests.TestDataPipe.SavePipeTrainAndScoreFccTransformStr

https://dev.azure.com/dnceng/public/_build/results?buildId=662867&view=logs&jobId=23576d1c-355e-5d27-4c31-0725f923794b&j=23576d1c-355e-5d27-4c31-0725f923794b&t=bcab25d9-33c3-57fc-b368-7b48febf4d8a

The active Test Run was aborted because the host process exited unexpectedly while executing following test(s):
Microsoft.ML.RunTests.TestDataPipe.SavePipeNgramHash

https://dev.azure.com/dnceng/public/_build/results?buildId=653881&view=logs&j=23576d1c-355e-5d27-4c31-0725f923794b&t=bcab25d9-33c3-57fc-b368-7b48febf4d8a

The active Test Run was aborted because the host process exited unexpectedly while executing following test(s):
Microsoft.ML.Functional.Tests.Evaluation.TrainAndEvaluateWithPrecisionRecallCurves

**Comment by mstfbl** [comment]
Hi @frank-dong-ms,

I have tested both running these tests separately, and running these tests with others as part of our CI runs on my local Mac, and have not been able to reproduce these failures. I'm closing this issue for now, but we should re-activate if we can get a more stable reproduction.

**Comment by frank-dong-ms** [comment]
Thanks Muftafa, I would like to keep this issue open but we can work on other issues first until we see more similar failures.

**Comment by frank-dong-ms** [comment]
Close this issue as we haven't see similar crash in 2 months, will reopen this if we see more similar issues.
