### ISSUE TITLE
Add  a threshold parameter for root cause analysis

### ISSUE THREAD

**Issue by suxi-ms** [dotnet/machinelearning#5188]
### Issue

- **Users want a threshold to determin whether the selected is a root cause, so we add a new parameter in the interface. The default value is 0.95**

**Comment by lisahua** [comment]
https://github.com/dotnet/machinelearning/blob/3cbd97a0ebf55299a3e339a1f5a922738b32d79c/src/Microsoft.ML.TimeSeries/RootCauseAnalyzer.cs#L424

When `x.Value` is long, it throws Unable to cast exception. Probably change to Convert.ToString(..)
        private static string GetDicCode(Dictionary<string, Object> dic)
        {
            return string.Join(";", dic.Select(x => x.Key + "=" + **(string)x.Value)**.ToArray());
        }
