### ISSUE TITLE
Error running experiment when specifying validationDataSet that contains a vector

### ISSUE THREAD

**Issue by rjhornby2** [dotnet/machinelearning#5193]
### System information

- OS: Windows 10.0.18363
- .NET Version 3.1.101

### Issue

- Running classification experiment with training/validation datasets the same, but containing:

        [VectorType(10)]
        public float[] d_hist{ get; set; }

- Exception: Training data and validation data schemas do not match. Column 'd_hist' is of type Vector<Single, 10> in train data, and type Vector<Single, 10> in validation data. (Parameter 'validationData').
- When not specifying the validation dataset I can build the model and validate manually after but cannot pass the validation dataset directly to the experiment.

### Source code / logs
Seems to be failing in UserInputValidation:

```
if (trainCol.Type != validCol.Value.Type)
                {
                    throw new ArgumentException($"{schemaMismatchError} Column '{trainCol.Name}' is of type {trainCol.Type} in train data, and type " +
                        $"{validCol.Value.Type} in validation data.", nameof(validationData));
                }
```

I wonder if the comparison should be:

`trainCol.Type.Equals(validCol.Value.Type)`

**Comment by Lynx1820** [comment]
Hi @rjhornby2, 

Could you provide the full pipeline?

**Comment by Lynx1820** [comment]
Hi @rjhornby2, 

Closing this issue. Feel free to reopen if you would like us to investigate and can provide the pipeline. Thanks.

**Comment by raitpngman** [comment]
Having the same issue.
I have a dynamic length array for a feature column and I create a schema for the Idataview, set the float[] length to the proper length, and then load the IdataView. This is done according to this.
https://github.com/dotnet/machinelearning/issues/164#issuecomment-492938790
The training and testing dataview is loaded through the same method.
Then I do 
 var experimentSettings = new RegressionExperimentSettings();
ExperimentResult<RegressionMetrics> experimentResult = mlContext.Auto()
               .CreateRegressionExperiment(experimentSettings)
               .Execute(trainData, testData, labelColumnName: labelColumnNameClose);
and it throws the error.
If I do this,
 var estimator = mlContext.Regression.Trainers.FastTree(labelColumnNameClose, featureColumnName: "Features");
                var results = estimator.Fit(trainData, testData);
                var newResults = results.Transform(testData);
it does not throw an error.

**Comment by raitpngman** [comment]
Found a workaround: In my code I have a method that loads the data from a csv and does this:
var schemaDef = SchemaDefinition.Create(typeof(Data));
schemaDef["Features"].ColumnType = new VectorDataViewType(NumberDataViewType.Single, 5);
var trainingDataView = mlContext.Data.LoadFromEnumerable(dataArray, schemaDef);

This method is called twice, once for the training data load and once for the validation training load. The two schemas are identical, but throw the error.
If I save the schema after the training data loads, and then use that on the validation data load, then There is no error.

 public SchemaDefinition LastSchemaDef { get; set; }

public IDataView LoadData()
{
//Load the data to a class

//Save the schema the first time through
var schemaDef = SchemaDefinition.Create(typeof(Data));
schemaDef["Features"].ColumnType = new VectorDataViewType(NumberDataViewType.Single, 5);
if (LastSchemaDef == null)
{
LastSchemaDef = schemaDef;

var trainingDataView = mlContext.Data.LoadFromEnumerable(dataArray, LastSchemaDef );
}
