### ISSUE TITLE
Fitting model with array

### ISSUE THREAD

**Issue by Vya4ik003** [dotnet/machinelearning#5206]
### System information

- **OS Windows 7**:
- **.NET Version 3.1.300**: 

### Issue

- **What did you do?** - I try to fit pipeline with byte[ ] columns.
- **What happened?** - I get "System.ArgumentOutOfRangeException: "Schema mismatch for feature column 'Features': expected Vector<Single>, got VarVector<Single> "".
- **What did you expect?** - I expected my model fitting with non-float data. In general, I want to load some muscial files into a model. And I want to get some data from model in byte[ ] type.

### Source code / logs

```
    class Program
    {
        static void Main(string[] args)
        {
            var mlContext = new MLContext();

            var testData = new TestData { Values = new byte[] { 1, 2 }, PredictedLabel = new byte[] { 3 } };
            var dataView = mlContext.Data.LoadFromEnumerable(new TestData[] { testData });
            var pipeline = mlContext.Transforms
                .CopyColumns("Label", "PredictedLabel")
                .Append(mlContext.Transforms.Concatenate("Features", "Values"))
                .Append(mlContext.Regression.Trainers.FastTree());

            var model = pipeline.Fit(dataView);
        }
        class TestData
        {
            public byte[] Values;

            public byte[] PredictedLabel;
        }

        class PredictedData
        {
            public byte[] PredictedLabel;
        }
    }
```

**Comment by Lynx1820** [comment]
Hi  @Vya4ik003, 

Unfortunately, FastTree regression only supports Single features. Closing this issue, feel free to reopen if you have additional questions.
