### ISSUE TITLE
Make Microsoft.ML more developer friendly

### ISSUE THREAD

**Issue by IvanAntipov** [dotnet/machinelearning#5207]
Microsoft.ML team, thank you for you job, as I can see, Microsoft.ML is the main hope for dotnet in machine learning word.

I would like to express my concern about the closeness of Microsoft.ML from developer side.

Each time I try to dive in the  Microsoft.ML I have the same scenario:

1. I manage to run some standard code from samples

2. I fail when I try to tune or discover my solution
  - A year ago it was imposibility to get phi/theta matrixes https://github.com/dotnet/machinelearning/issues/3092

  - This time I run text classification task: FeaturizeText -> SdcaLogisticRegression
    - I try to plot ROC curve but Microsoft.ML.Data.BinaryClassifierEvaluator.EvaluateWithPRCurve   is not available (not yiet available from public API)
  
    - I try to get Vocabulary from FeaturizeTextExstimator to perform some sort of PFI analysis, this data is not available too.

3. I fight with this closeness several days, I'm losing this battle, I'm going back to use .py libraries

My opinion: **internal is always evil** if your can't leave inner imlementation of your class private/protected, if ohter classes of yout Library require asses this methods or properties, most likely this functionality must be available to consumers of your library.

I undestand, that internal classes reduce the amount of API yout should support. Maybe it makes sense to move all internall classes to '.*.Internal' namespace, with convention, that classes from this namespaces should be used 'without guarantee of compatibility between versions'

**Comment by IvanAntipov** [comment]
Just for illustration, the way I'm getting the vocabulary now

A lot of pain, a lot of reflection :(

```
#load @".paket\load\netcoreapp3.0\Microsoft.ML.fsx"
#load @".paket\load\netcoreapp3.0\Fasterflect.fsx"
open Microsoft.ML
open Microsoft.ML.Data
open Microsoft.ML.Transforms.Text
open System
open System.IO
open Newtonsoft.Json
open Fasterflect

let mlContext = MLContext(seed = Nullable 1)

type Example = {Text: string; LabelText: string}

let trainExamples = File.ReadAllLines @"c:\tmp\FraudSet\data.test.json" |> Seq.map JsonConvert.DeserializeObject<Example>

let dataReader = mlContext.Data.LoadFromEnumerable<Example>(trainExamples)


let estimator = 
    let labelNameRequiredBySdca = "Label"
    let wordBagOptions = WordBagEstimator.Options(MaximumNgramsCount = [|10000|]) 
    let textFeaturizeOptions =  
        TextFeaturizingEstimator.Options(
            OutputTokensColumnName = "OutputTokens",
            CaseMode = Microsoft.ML.Transforms.Text.TextNormalizingEstimator.CaseMode.Lower,
            KeepNumbers = false,
            KeepPunctuations = false,
            WordFeatureExtractor = wordBagOptions)
    EstimatorChain()
        .Append(mlContext.Transforms.Conversion.MapValue(outputColumnName = labelNameRequiredBySdca, keyValuePairs = dict ["normal", false; "fraud", true], inputColumnName = "LabelText"))
        .Append(mlContext.Transforms.Text.FeaturizeText(outputColumnName = "Features", options = textFeaturizeOptions, inputColumnNames =  [|"Text"|]))

let model = estimator.Fit(dataReader)

let getTerms(transformer: obj) =
    if not <| (transformer.GetType().FullName = "Microsoft.ML.Transforms.Text.TextFeaturizingEstimator+Transformer") then
        failwith "transformer should be of type 'Microsoft.ML.Transforms.Text.TextFeaturizingEstimator+Transformer'"

    let bowPipe = transformer.GetFieldValue("_chain") :?> obj seq |> Seq.item 2 :?> obj seq
    let valToKey = bowPipe |> Seq.item 0 :?> Microsoft.ML.Transforms.ValueToKeyMappingTransformer
    let maps = valToKey.GetFieldValue("_unboundMaps") :?> obj array
    maps
    |> Seq.map(fun termMap ->
            // let termMap = maps.[0]
            let mutable terms :VBuffer<ReadOnlyMemory<char>> = VBuffer<ReadOnlyMemory<char>> () 
            let mutable termsArr : obj array = [|terms|]
            termMap.GetType().Method("GetTerms").Invoke(termMap, termsArr) |> ignore
            let buffer = termsArr.[0] :?> VBuffer<ReadOnlyMemory<char>>
            
            // let valueGetter = termMap.CallMethod("GetKeyMapper") :?> (Func<ReadOnlyMemory<char>, uint32>)
            let valueGetter = termMap.GetType().Method("KeyMapper")

            buffer.DenseValues() 
            |> Seq.map(fun i -> 
                //let i = buffer.DenseValues() |> Seq.head 
                let key = i.Span.ToString()
                let mutable keyValDummy : uint32 = Unchecked.defaultof<uint32>
                let mutable getValueArr : obj array = [| key.AsMemory(); keyValDummy |]
                valueGetter.Invoke(termMap, getValueArr) |> ignore
                let keyVal = getValueArr.[1] :?> uint32
                key, keyVal) 
            |> Seq.toList)
    |> Seq.collect id
    |> Seq.toList


let vocab = model.LastTransformer |> getTerms
vocab.Length
```

**Comment by harishsk** [comment]
Hi @IvanAntipov Thank you very much for your thoughtful feedback. 

You have captured the heart of our dilemma in your feedback. Making more of the internal classes public would make a lot of capabilities available to developers but it also significantly increases our support cost and also seriously impacts our ability to fix bugs and refactor code without breaking existing code. 

In theory we may be able to move some of the internal classes to a *.Internal namespace and explicitly state that we don't guarantee compatibility. But historically we have seen that this code often ends up in production code and developers are not happy when things break.

Instead, I would like to request that you work with us. Please open a bug/feature request whenever you need a capability that is hidden in an internal class. We are very much open to discussing these on a case by case and making public those APIs after we have put in the due diligence to make sure we can support those changes going forward.

**Comment by mikhail-barg** [comment]
@harishsk thanks for the answer. While I understand your concerns of supporting extensive public interfaces, and it's great to know that you are open to discussions and feedback, still it's also true that during a prototyping phase it's important to be able to try and check many options quickly. And one can imagine that it's hardly viable to open an issue and wait for its resolution each time you want to check something during research phase.

Considering that Microsoft.ML is in general competing with wast world of pythonic ML libraries which are (sadly) de-facto standard for ML for a long time, ability to make quick prototypes is rather vital.

So maybe you could think of some other ways to make quick prototyping and investigations possible with Microsoft.ML?

**Comment by harishsk** [comment]
Yes, during prototyping you do want to move quickly and build fast. One other approach I can suggest during prototyping is to make private builds. If all you need is some internal class made public during prototyping, please do so in a private build of ML.NET.  If your prototype is successful the change is useful, there are two further approaches we can consider. 

- If the change fits in the existing architecture of ML.NET, please submit a PR. We do welcome PRs from the community.
- If the change is much more invasive, we would still request you to submit your PR and we can discuss how best incorporate your needs into ML.NET.

I would like to interpret the scope of your ask of "Make Microsoft.ML more developer friendly" as "Make all developers feel welcome to contribute to ML.NET"

**Comment by harishsk** [comment]
Hi @IvanAntipov, @mikhail-barg Thank you for the feedback and discussion above. Please do reach out if you have specific issues that we can act upon.
