### ISSUE TITLE
File already exists error when loading LightGbmBinaryTrainer from MemoryStream

### ISSUE THREAD

**Issue by dasokolo** [dotnet/machinelearning#5210]
### System information
os version Windows (not sure)
.net version 3.1.202
mlnet version 1.3.1

### Issue
I am loading LightGbmBinaryTrainer from memory stream 

                ITransformer model = null;
                using (MemoryStream ms = new MemoryStream(kv.Value))
                {
                    model = _mLContext.Model.Load(ms, out _inputSchema);
                }

Note, this code is executed in several threads in parallel over the same model. 

And I occasionally get the following exception: 

System.IO.IOException: The file 'D:\SvcFab\_App\AIBuilder.Platform.Host_App157\temp\TLC_1CBA6C2E\0' already exists. 

This happens occasionally and I can't reliably reproduce this 100%. 

- **What did you expect?**
1) I expected that no file operations are performed during loading from memory stream. My models are relatively small, but I can't guarantee that the filesystem is always available. I would appreciate to at least have some control over this behavior. 

2) But if file operations cannot be avoided, I expect to have no naming conflicts. 

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.IOException: The file 'D:\SvcFab\_App\AIBuilder.Platform.Host_App157\temp\TLC_1CBA6C2E\0' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at Microsoft.ML.RepositoryReader.OpenEntryOrNull(String dir, String name)
   at Microsoft.ML.ModelOperationsCatalog.Load(Stream stream, DataViewSchema& inputSchema)

**Comment by frank-dong-ms** [comment]
@dasokolo could you please provide a repro project and necessary dataset so we can investigate further? BTW, are you working on latest version of ML.NET (1.5.0)?

**Comment by frank-dong-ms** [comment]
@dasokolo I can't repro the issue with provided code piece either. Regarding the question, I believe the answer is no but let me check code and get back to you later, thanks.

**Comment by frank-dong-ms** [comment]
@dasokolo I have checked the code, currently there is no option that can user can set to avoid file operation when load model. I already open a PR to fix the issue you met.

**Comment by frank-dong-ms** [comment]
This issue should already fixed at below PR:
https://github.com/dotnet/machinelearning/pull/4645

please upgrade to latest version of ml.net.

**Comment by frank-dong-ms** [comment]
Close this issue now as this already fixed, feel free to reopen if necessary, thanks
