### ISSUE TITLE
ML.NET exports to ONNX v1.2.2 file which is not supported in current released Windows 10 RS4 but only in RS5

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning#523]
### System information
- **Windows RS4 vs. RS5**
- **ML.NET 0.3**

### Issue
The current released Windows (RS4) with WinML, supports only ONNX v1.0 models while Windows RS5 WinML supports only ONNX v1.2.2 models.

This is an issue since ML.NET exports ONNX 1.2.2 files which therefore don't work on current released Windows (RS4) with WinML, but only on the next version of Windows (RS5), which is still not publicly available.

Since this issue might be happening depending on the target platforms, it would be advisable to parametrize the ONNX version of the model to export/generate (ONNX v1.0, v1.2.2, etc.), so it can work on multiple target platforms depending on the version.

**Comment by shauheen** [comment]
Thank @CESARDELATORRE for filing the issue. We have no plans of supporting ONNX v1 anymore. I will close this issue and wait for RS5 to be available.

**Comment by CESARDELATORRE** [comment]
As per info confirmed by the Windows team, starting with Windows RS5, ONNX v1.2.2 is the minimum version supported by Windows ML **and ONNX v1.2.2 will be the minimum supported version in future Windows ML releases**.
Therefore, I agree. We don't need to support ONNX v1 anymore. 👍
