### ISSUE TITLE
Add description to convenience constructors.

### ISSUE THREAD

**Issue by zeahmed** [dotnet/machinelearning#524]
Recently, convenience constructors were added to different components to help easily create these components in the pipeline (cf. #380 #487 and #520).

It is also desirable to add helpful comments/description to these constructor to help user understand the components purpose and possible usage.

To be more precise, here is list of transforms that needs description for convenience constructors.

- BootstrapSampleTransform
- CategoricalHashTransform
- CategoricalTransform
- ConcatTransform
- CopyColumnsTransform
- CountFeatureSelection
- DropColumnsTransform
- LpNormNormalizerTransform
- NAFilter
- NormalizeTransform
- ChooseColumnsTransform.cs
- ConvertTransform.cs
- DropSlotsTransform.cs
- GenerateNumberTransform.cs
- HashTransform.cs
- KeyToValueTransform.cs
- KeyToVectorTransform.cs
- LabelConvertTransform.cs
- LabelIndicatorTransform.cs
- RangeFilter.cs
- ShuffleTransform.cs
- SkipTakeFilter.cs
- TermTransform.cs
- GroupTransform.cs
- HashJoinTransform.cs
- KeyToBinaryVectorTransform.cs
- LoadTransform.cs
- MissingValueIndicatorTransform.cs
- MutualInformationFeatureSelectionTransform.cs
- NADropTransform.cs
- NAHandleTransform.cs
- NAIndicatorTransform.cs
- NAReplaceTransform.cs
- OptionalColumnTransform.cs
- RffTransform.cs
- UngroupTransform.cs
- WhiteningTransform.cs

**Comment by Ivanidzo4ka** [comment]
@zeahmed  do you mind to close this one? Since we hiding all constructors this task doesn't feel relevant anymore?

**Comment by zeahmed** [comment]
No longer valid.
