### ISSUE TITLE
TensorFlowTransformCifar test crash

### ISSUE THREAD

**Issue by frank-dong-ms** [dotnet/machinelearning#5242]
Test crash: https://dev.azure.com/dnceng/public/_build/results?buildId=684811&view=logs&j=d1af5113-e574-5a31-f7f3-02fc40ea7b26&t=b03e2d69-ce1a-5899-6643-e9b6085777b9&s=d654deb9-056d-50a2-1717-90c08683d50a

error message: 
The active Test Run was aborted because the host process exited unexpectedly while executing following test(s):
Microsoft.ML.Scenarios.TensorFlowScenariosTests.TensorFlowTransformCifar

**Comment by mstfbl** [comment]
The following error statements occur with this test on this specific run:

> 2020-06-12T15:00:30.0736153Z The active test run was aborted. Reason: Test host process crashed : Warning: Term map for output column 'B' contains no entries.
> 
> 2020-06-12T15:00:30.0739464Z 2020-06-12 14:51:53.3972234 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer Label appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.

**Comment by frank-dong-ms** [comment]
Haven't see similar crash for past 2 months so close this for now, will reopen if see more similar issues.
