### ISSUE TITLE
Rename the NGramNgramExtractor class to a better name. 

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#525]
I think the NGramNgramExtractor class in the CSharpApi.cs should have a better name. 

Circa line 17990: 
`public sealed class NGramNgramExtractor : NgramExtractor`

**Comment by Ivanidzo4ka** [comment]
Don't forget about NGramHashNgramExtractor !

**Comment by shauheen** [comment]
While I agree with this, please keep in mind that #371 may change the mechanics of this completely.

**Comment by Ivanidzo4ka** [comment]
It's not only entry point API, it's also real names of the classes, which we will expose through proposed by Tom API.

**Comment by shauheen** [comment]
That is correct, that's why I said the mechanics of it would be changed.

**Comment by sarthak268** [comment]
Is this issue already assigned? If not please assign.

**Comment by justinormont** [comment]
Any proposals for new names for `NGramNgramExtractor` and `NGramHashNgramExtractor`?

**Comment by sfilipi** [comment]
The C#Api is no longer there, so this is not relevant anymore.
