### ISSUE TITLE
CreateEnumerable from key column

### ISSUE THREAD

**Issue by go2ready** [dotnet/machinelearning#5270]
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: 4.7

### Issue

- **What did you do?**
Trying to create Enumerable from IDataView which contains Column with Type Key<UInt32, 0-1059>, into a uint type.
- **What happened?**
Encountered error:
"Can't bind the IDataView column 'ImpressionIdKey' of type 'Key<UInt32, 0-1059>' to field or property 'ImpressionIdKey' of type 'System.UInt32'."
- **What did you expect?**
I want to be able to export key value in its uint format as enumerable

### Source code / logs

```
        var a = mlContext.Data.CreateEnumerable<ProcessedData>(
            colSelTrainingData, reuseRowObject: false);

...

        private class ProcessedData
        {
            public float[] Feature { get; set; }

            public float BackProClick { get; set; }

            public uint ImpressionIdKey { get; set; }
        }
```

**Comment by antoniovs1029** [comment]
Hi, @go2ready . It should be possible for you to create an enumerable from a key column. I don't know why you're getting that exception. Can you please provide a full stacktrace, and also a .zip containing code and data to reproduce your error so I can look closer? Thanks.

For reference, I've just ran this toy example, and it worked as expected:
<details>
<summary> Click to toggle toy example </summary>
<p>

```C#

using System;
using Microsoft.ML;
using Microsoft.ML.Data;
using System.Linq;

namespace TextLoaderSample
{
    class Program
    {
        public class ModelInput
        {
            public int Id { get; set; }

            public string Description { get; set; }

            public float Num1 { get; set; }

            public float Num2 { get; set; }

        }

        public class ModelOutput
        {
            public uint KeyDescription { get; set; }
        }

        static void Main(string[] args)
        {
            MLContext mlContext = new MLContext(seed: 1);

            var inputList = new[]
            {
                new ModelInput(){Id = 0, Description = "lion", Num1 = 12.333f, Num2 = 13.44f},
                new ModelInput(){Id = 1, Description = "house", Num1 = 12.333f, Num2 = 13.44f},
            };

            IDataView inputDV = mlContext.Data.LoadFromEnumerable(inputList);

            var pipeline = mlContext.Transforms.Conversion.Hash("KeyDescription", "Description");
            var outputDV = pipeline.Fit(inputDV).Transform(inputDV);

            var outputEnum = mlContext.Data.CreateEnumerable<ModelOutput>(outputDV, reuseRowObject: false);
            var outputArray = outputEnum.ToArray();
        }
    }
}

```

</p>

</details>

**Comment by go2ready** [comment]
Thanks @antoniovs1029 for providing the code snippet, I tired this morning it worked, must be something I have been doing wrong on the pipeline :) Really appreciated
