### ISSUE TITLE
Usabilla Feedback: User is facing dependency issue

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning#5278]
@v-mepa commented on [Tue Jun 30 2020](https://github.com/dotnet/machinelearning-modelbuilder/issues/874)

**User Comment:** There is a dependency problem with Microsoft.ML and Microsoft.ML.DataView needing System.Collections.Immutable 1.2.3.0. Not sure how System.Collections.Immutable 1.7 (newest version) got in the packages directory but I can't change it to the old version so can please update Microsoft.ML.DataView and Microsoft.ML to use any version higher than 1.2.3.0?
**URL:** https://dotnet.microsoft.com/apps/machinelearning-ai/ml-dotnet
**OS:** MacOSX
**Browser:** Safari 13.1
**Device:** Desktop

![image](https://user-images.githubusercontent.com/42360097/86171588-cbe5fd00-bad1-11ea-82ae-caddb4d5e322.png)

**Comment by antoniovs1029** [comment]
Hi @v-mepa . Thanks for reaching out.

I am confused about the issue you're reporting. As you can see on the nuget.org page, both [Microsoft.ML 1.5.0](https://www.nuget.org/packages/Microsoft.ML/) and [Microsoft.ML.DataView 1.5.0
](https://www.nuget.org/packages/Microsoft.ML.DataView/1.5.0) have a dependency on `System.Collections.Immutable (>= 1.5.0)
`. In fact, they've never had a dependency on `System.Collections.Immutable 1.2.3.0`, so I'm not sure: can you please clarify why you pointed to these two nugets as having that dependency? If possible, can you provide a .zip containing the project where this happened?

Also, I'm not sure what's the relation of the screen capture with the problem that is being reported.

Thanks.

**Comment by v-mepa** [comment]
Hey @antoniovs1029 this is the feedback we get on the .NET website through Usabilla. I logged an issue believing it's a valid product feedback and you might want to do something about it. The screenshot is also provided by the Usabilla stating that user was on this page when he reported the issue.
If there is no call to action then you can simply close the issue. I was not sure of this user feedback so created an issue.

**Comment by antoniovs1029** [comment]
I see. I think there must be some confusion on the user side since, as I've explained on my previous post, the dependencies pointed by the user aren't the actual ML.NET dependencies and so there doesn't seem to be an issue. Thus, I'll close this issue. Thanks for reporting this, anyway, @v-mepa  😄
