### ISSUE TITLE
Averaged Perceptron in MultiClass classification

### ISSUE THREAD

**Issue by darren-zdc** [dotnet/machinelearning#5283]
Hi,

I am trying to use the AveragedPerceptron trainer in a multiclass scenario with labeled columns like "1", "2" or "3", but I only found an example in a binary classification problem, which is not what I want.

Is there a document mentioned AveragedPerceptron in Multiclass problem? 
Or how can I approach it?

I originally used the ModelBuilder to training my multiclass data, and I got an AveragedPerceptron model. Now, I want to customize the training process.

Thanks

**Comment by justinormont** [comment]
`AveragedPerceptron` is a binary classification algorithm. You can use it within `OneVersesAll`, which allows binary classification algos to work on multiclass tasks. 

See example:
https://github.com/dotnet/machinelearning-samples/blob/5308cda61042f1182ff8e00e13b08dbb423c3696/samples/csharp/getting-started/BinaryClassification_SpamDetection/SpamDetectionConsoleApp/Program.cs#L52-L54

You can also modify the code which ModelBuilder produces. It produces the full training pipeline for your multiclass dataset including the `OneVersesAll` w/ `AveragedPerceptron`.
