### ISSUE TITLE
System.MissingMethodException: 'Method not found: 'System.Threading.Tasks.Task`1<ResourceDownloadResults> 

### ISSUE THREAD

**Issue by petropolitana** [dotnet/machinelearning#5285]
### System information

- **OS version/distro**:
Windows 10
- **.NET Version (eg., dotnet --info)**: 
.NET Framework 4.7

### Issue

- **What did you do?**
Tried to train a model with InceptionV3
- **What happened?**
Crashed with MissingMethod
- **What did you expect?**
Expected no errors

### Source code / logs

            var options = new ImageClassificationTrainer.Options()
            {
                FeatureColumnName = "Image",
                LabelColumnName = "LabelAsKey",
                Arch = ImageClassificationTrainer.Architecture.InceptionV3,
                Epoch = 50,       //100
                BatchSize = 10,
                LearningRate = 0.01f,
                MetricsCallback = (metrics) => Console.WriteLine(metrics),
                ValidationSet = testDataView
            };

System.MissingMethodException: 'Method not found: 'System.Threading.Tasks.Task`1 ResourceDownloadResults Microsoft.ML.Internal.Utilities.ResourceManagerUtils.EnsureResource(Microsoft.ML.Runtime.IHostEnvironment, Microsoft.ML.Runtime.IChannel, System.String, System.String, System.String, Int32)'.'

Hello, I was tring to train a model with ImageClassificationTrainer and tried to user InceptionV3 in .NetFramework4.7 and it gave me MissingMethodException. 
Tried the same code in .NetCore 3.1 and the problem wasn't there 
Is there a fast WA or a Fix for this kind of problem? Can someone advise?

**Comment by frank-dong-ms** [comment]
@petropolitana could you please provide a complete project for us to repro this issue? At the same time I will try to repro this issue with the code piece you provided.

**Comment by frank-dong-ms** [comment]
I tried but failed to repro this issue, I created console project with .NET Framework 4.7 and do image classification training things works fine.

**Comment by mstfbl** [comment]
Hi @petropolitana

We have not been able to reproduce your issue. Please provide a repro of your issue so that we can investigate. We will close this issue if we do not have a repro. Thanks!

**Comment by frank-dong-ms** [comment]
@petropolitana I will close this issue as we didn't hear back for several days, feel free to reopen with more info so we can investigate further, thanks.
