### ISSUE TITLE
"Could not find operation" Error When Scoring a Tensorflow Model

### ISSUE THREAD

**Issue by jwood803** [dotnet/machinelearning#5294]
### System information

- **OS version/distro**:
Windows 10 1909 Build 
- **.NET Version (eg., dotnet --info)**: 
.NET Core SDK (reflecting any global.json):
 Version:   3.1.400-preview-015178
 Commit:    60cb58d3b1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.400-preview-015178\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
  3.1.400-preview-015178 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.DesktopUI.App 3.0.0-alpha-26921-3 [C:\Program Files\dotnet\shared\Microsoft.DesktopUI.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### Issue

- **What did you do?**
Attempted to load and score a Tensorflow model.

- **What happened?**
When running it gave a 'Could not find operation "input" inside graph "grap-key-1/".' error.

### Source code / logs
Used [this Colab notebook](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb) locally and added the `model.save("mnist-model.h5", save_format="h5")` line to save the model to a local file.

The model as shown in Netron:
![image](https://user-images.githubusercontent.com/1578160/86899782-719ffa00-c0d8-11ea-9d9d-1363c88daaaa.png)

Used the below ML.NET code to load and score the model:

```csharp
public class DigitInput
{
    public float[] DigitData { get; set; }
}

var context = new MLContext();

var emptyData = new List<DigitInput>();

var data = context.Data.LoadFromEnumerable(emptyData);

var pipeline = context.Model.LoadTensorFlowModel("./mnist-model.h5")
  .ScoreTensorFlowModel(new[] { "dense_1" }, new[] { "input" }, addBatchDimensionInput: true)
  .Append(context.MulticlassClassification.Trainers.LbfgsMaximumEntropy("LabelKey", "dense_1"))
  .Append(context.Transforms.Conversion.MapKeyToValue("PredictedLabelValue", "PredictedLabel"));

pipeline.Fit(data);
```

I'm sure I'm missing something but not sure what that is. 😄

**Comment by frank-dong-ms** [comment]
@jwood803 seems you are trying to load a Keras model (.h5) with ML.NET's load tensorflow model functionality. I believe h5 model format is not valid tensorflow graph format, please try to save model as protocol buffers file (.pb) and try again, thanks.

**Comment by jwood803** [comment]
Thanks @frank-dong-ms! Was just wondering, is this only for Tensorflow 1 models and it doesn’t get support Tensorflow 2’s model format?

**Comment by frank-dong-ms** [comment]
As far as I know, we are developing TF functionality on an old version of TF.NET which only support TF 1 so I would say TF 1 models are supported for sure. We haven't tested on TF 2 models compatibility as far as I know.
 
But I checked the document of TF 2 and seems there are no significant compatibility concerns for saved models between TF 1 and TF 2 so worth trying:
https://www.tensorflow.org/guide/migrate#saved_models_compatibility

**Comment by frank-dong-ms** [comment]
I will close this issue if no further question, feel free to reopen, thanks @jwood803

**Comment by jwood803** [comment]
@frank-dong-ms I saved the model again and it generated a "pd" file along with a couple of folders.

![image](https://user-images.githubusercontent.com/1578160/87035954-16453900-c1b8-11ea-93e3-2fc65f443e47.png)

Here's what the model looks like in Netron which is different than what the h5 model had:

![image](https://user-images.githubusercontent.com/1578160/87036027-2fe68080-c1b8-11ea-86c1-36ebd1a60d95.png)

And reading this in ML.NET generates an error that just says "Invalid GraphDef".

![image](https://user-images.githubusercontent.com/1578160/87036154-5d332e80-c1b8-11ea-903f-ed3d3c2f62f4.png)

This "pd" file does seem different than others I've seen, so I'm thinking the model is being saved in a different way than it used to, but I'm not sure.

Thank you for helping me go through this! 😄

**Comment by frank-dong-ms** [comment]
@jwood803 You need to freeze your tensorflow keras model first then you should be able to load the model from ml.net:

https://devblogs.microsoft.com/cesardelatorre/run-with-ml-net-c-code-a-tensorflow-model-exported-from-azure-cognitive-services-custom-vision/
https://www.dlology.com/blog/how-to-convert-trained-keras-model-to-tensorflow-and-make-prediction/

Feel free to reach out if you have any further questions, thanks.
