### ISSUE TITLE
Error al llamar "ITransformer mlModel = mlContext.Model.Load(modelPath, out var modelInputSchema);"             

### ISSUE THREAD

**Issue by JuanJimenezR** [dotnet/machinelearning#5304]
### System information

- **OS Microsoft Win 10
- **.NET Version 2019: 

- **What did you do?**
Estoy generando código con ML.builder.  De hecho he logrado generar y ejecutar con exito un par de modelos donde el modelo propuesto por ML.Builder fue un fasttree.
Para este nuevo set de datos el modelo generado el  el  ML.Builder fue el OlsRegression . Fue agregado el código al proyecto.  
He a actualizado las librerias incluidas a la version 1.0.0 , pues me lo pidió igual que los casos anteriores.

Estoy cargando con exito los datos en el ModelInput
Estoy llamando a ConsumeModel.Predict ... dando el problema técnico mencionado  en la llamada

ITransformer mlModel = mlContext.Model.Load(modelPath, out var modelInputSchema);
            .
de la clase consumeModel.

He vuelto a iniciar de cero, para descartar que por alguna X razón el  modelo .zip estuviese corrupto, PERO tengo el mismo resultado.

- **What happened?**

- **What did you expect?**
aclaro ya he generado  y utilizado otros modelos, los cuales suelen funcionar luego de hacer las actualizaciones a las librerías y los amarres de código respectivos.  Pero  en este caso ... persiste el  error, en vez de poder hacer UNA prediccion 

### System.InvalidOperationException
  HResult=0x80131509
  Mensaje = Error during class instantiation
  Origen = Microsoft.ML.Core
  Seguimiento de la pila:
   at Microsoft.ML.Runtime.ComponentCatalog.LoadableClassInfo.CreateInstanceCore(Object[] ctorArgs)
   at Microsoft.ML.Runtime.ComponentCatalog.TryCreateInstance[TRes](IHostEnvironment env, Type signatureType, TRes& result, String name, String options, Object[] extra)
   at Microsoft.ML.Runtime.ComponentCatalog.TryCreateInstance[TRes,TSig](IHostEnvironment env, TRes& result, String name, String options, Object[] extra)
   at Microsoft.ML.ModelLoadContext.TryLoadModelCore[TRes,TSig](IHostEnvironment env, TRes& result, Object[] extra)
   at Microsoft.ML.ModelLoadContext.TryLoadModel[TRes,TSig](IHostEnvironment env, TRes& result, RepositoryReader rep, Entry ent, String dir, Object[] extra)
   at Microsoft.ML.ModelLoadContext.LoadModel[TRes,TSig](IHostEnvironment env, TRes& result, RepositoryReader rep, Entry ent, String dir, Object[] extra)
   at Microsoft.ML.ModelLoadContext.LoadModelOrNull[TRes,TSig](IHostEnvironment env, TRes& result, RepositoryReader rep, String dir, Object[] extra)
   at Microsoft.ML.ModelLoadContext.LoadModel[TRes,TSig](IHostEnvironment env, TRes& result, RepositoryReader rep, String dir, Object[] extra)
   at Microsoft.ML.ModelOperationsCatalog.Load(Stream stream, DataViewSchema& inputSchema)
   at Microsoft.ML.ModelOperationsCatalog.Load(String filePath, DataViewSchema& inputSchema)
   at PaLanteML.Model.ConsumeModel.CreatePredictionEngine() in D:\Toni\Soluciones\PaLante\PaLanteML.Model\ConsumeModel.cs:line 31
   at System.Lazy`1.CreateValue()

Esta excepción se generó originalmente en esta pila de llamadas:
    [Código externo]

Excepción interna 1:
TargetInvocationException: Se produjo una excepción en el destino de la invocación.

Excepción interna 2:
InvalidOperationException: Error during class instantiation

Excepción interna 3:
TargetInvocationException: Se produjo una excepción en el destino de la invocación.

Excepción interna 4:
FormatException: Uno de los elementos identificados tiene un formato no válido.

**Comment by antoniovs1029** [comment]
Hola, @JuanJimenezR .

Viendo solamente el stacktrace no puedo saber cuál es el problema con tu modelo. Es necesario que nos compartas el .zip con tu modelo para que lo podamos investigar. De ser posible, también nos sería útil tener el código generado por ModelBuilder. Gracias :smile: 

Así mismo, me pregunto: mencionaste que has tenido que actualizar tus librerías a la versión 1.0... ¿Te refieres a los nugets de ML.NET? ¿Qué versión usabas antes de actualizar? Es extraño ya que la versión 1.0 de ML.NET fue lanzada hace más de un año y actualmente está en la versión 1.5. Me parece que la versión más actualizada de ModelBuilder está usando 1.5.0-preview2... pero aún así lo recomendable sería que usaras la versión 1.5.0 de ML.NET.

De ser posible, también compártenos una captura mostrando las dependencias de ML.NET que tiene tu proyecto. Gracias.

**Comment by JuanJimenezR** [comment]
Muchas gracias Antonio!

He vuelto a generar desde 0 el proyecto, el cual adjunto para su revisión.
Para facilidad he agregado un Botón que ejecuta  un caso de prueba exitoso.

Para el proyecto enviado NO he cambiado ni actualizado ninguna de las librerías generadas por el constructor.

Es correcto su comentario, el constructor me genera los proyectos incluyendo librerías versión 1.5, PERO siempre al ejecutar,
 el primer error que obtengo es que  no puede encontrar la librería versión 1.0.0.  por esa razón proceso a actualizar.


[prediccion.zip](https://github.com/dotnet/machinelearning/files/4908382/prediccion.zip)

**Comment by antoniovs1029** [comment]
Hola, @JuanJimenezR . Gracias por compartir el `.zip` con nosotros. Una disculpa por la falta de acentos en este mensaje, pero te contesto rapidamente desde un teclado que no los tiene.

Al correr tu aplicacion, logre reproducir tu error, para corregirlo simplemente tuve que añadir los nugets the ML.NET directamente a tu proyecto llamado `Prediccion` (solamente instale los nugets de `Microsoft.ML` y `Microsoft.ML.Mkl.Components` y eso instalo todos los demas). Solo lo probe instalando la version v1.5.0-preview2, y con ello funciono tu app, y el valor de "425" fue correctamente predecido; deberia de funcionar igualmente en v1.5.0 o en v1.5.1 (que recien fue lanzada el viernes), asi que no hay necesidad de usar la version 1.0. Asi lucen las referencias de ese proyecto tras instalar los nugets mencionados:

![image](https://user-images.githubusercontent.com/38739674/87343700-246dbf00-c502-11ea-9667-cc84a3b07676.png)

**Notas:**
Al correr tu aplicacion por primera vez, sin hacer ningun cambio, recibi este mensaje de error:
![image](https://user-images.githubusercontent.com/38739674/87344173-d0170f00-c502-11ea-8844-1ca882c298d2.png)

Notar que esto _no_ significa que necesites instalar la version 1.0 de ML.NET, sino que el codigo intento encontrar _al menos_ la version 1.0, pero no la encontro. Lo que sucede es que aunque ML.NET ya este instalado en el proyecto de `PrediccionML.Model`, y el codigo de `ConsumeModel.Predict()` este en ese proyecto, el proyecto intenta encontrar tus nugets dentro del proyecto principal donde se realiza la ejecucion. En tu caso, ese proyecto es `Prediccion`, asi que es necesario contar con los nugets directamente instalados ahi.

De momento no se si hay una mejor manera de configurar tu app para que automaticamente encuentre los nugets dentro del proyecto de `PrediccionML.Model`, y asi no se necesite instalarlos en `Prediccion`. Pero en general mi recomendacion seria que no tengas los proyectos de `PrediccionML.Model` y `Prediccion` separados, sino que pongas el codigo encontrado dentro de `PrediccionML.Model` dentro del de `Prediccion`, para asi no necesitar el proyecto de `PrediccionML.Model` ni tener que preocuparte de instalar nugets en dos lugares a la vez.

**Comment by antoniovs1029** [comment]
Cerrare este issue, ya que fui capaz de correr tu app al seguir los pasos que te he recomendado en mi anterior comentario.

Si aun tienes problemas tras seguir mis recomendaciones, puedes reabrir el issue para que lo pueda atender. Gracias 😄

**Comment by JuanJimenezR** [comment]
Antonio, MUCHAS GRACIAS.

He validado sus observaciones, y me doy cuenta que el problema de contexto de desarrollo lo estaba generando yo mismo al llamar desde un tercer proyecto y agregar versiones anteriores (al mal interpretar los mensajes de error).  Todo queda claro y solucionado.
