### ISSUE TITLE
Entrypoints for RobustScaler, ToString removed

### ISSUE THREAD

**Issue by ganik** [dotnet/machinelearning#5309]
ML.NET 1.5.1 breaking changes for NimbusML.
Entrypoints RobustScaler, ToString and CategoryImputer removed.
The PR was #5209 
NimbusML can do changes for CategoryImputer to use ReplaceMissingValues entrypoint
We need to expose TypeConvertingTransformer  and NormalizingEstimator as entrypoints

**Comment by michaelgsharp** [comment]
I'll work on that today Gani. I thought they were already exposed.

**Comment by michaelgsharp** [comment]
@ganik @harishsk, TypeConvertingTransformer is exposed as `Transforms.ColumnTypeConverter`, it is already there.

NormalizingEstimator was exposed as different entrypoints for each type of normalizer. Not sure why it was done that way, I thought it was done the same way as the others where it was just one entry point with the different parameters. I'll have a PR out today for that entrypoint fix.
