### ISSUE TITLE
Async operation has not completed error

### ISSUE THREAD

**Issue by jwood803** [dotnet/machinelearning#5312]
It seems some scenarios cause this error after looking at this [StackOverflow question](https://stackoverflow.com/questions/62976568/system-invalidoperationexception-the-asynchronous-operation-has-not-completed).

```
at System.Threading.Channels.AsyncOperation.ThrowIncompleteOperationException() at System.Threading.Channels.AsyncOperation1.GetResult(Int16 token)   at Microsoft.ML.Transforms.RowShufflingTransformer.Cursor.MoveNextCore()
```

This seems to be caused by a change I added in #5123. 

Tagging @eerhardt @harishsk for visibility. I'll work on a fix for this.

**Comment by mstfbl** [comment]
Hi @jwood803 ,

Thank you for notifying us of this issue. I've assigned this issue to you as you've already opened a PR to fix this. Let us know if you need any additional help from our end. Thanks!

**Comment by antoniovs1029** [comment]
I imagine this is related to the issue reported here:
https://github.com/dotnet/machinelearning-samples/issues/833

**Comment by antoniovs1029** [comment]
I think this is related to the issue reported here:
https://github.com/dotnet/machinelearning-samples/issues/833
