### ISSUE TITLE
Load native LightGBM exported text file

### ISSUE THREAD

**Issue by klesouza** [dotnet/machinelearning#5315]
### Issue

- I would like to be able to load a LightGBM model exported from the native library in text format directly in ML.NET LightGBM implementation.

I noticed there are bindings to the save method here https://github.com/dotnet/machinelearning/blob/8631afaaaa60daa1bda734dc79d92433591f7917/src/Microsoft.ML.LightGbm/WrappedLightGbmInterface.cs#L190, but couldn't find a way to load the text file

**Comment by mstfbl** [comment]
Hi @klesouza,

Thank you for bringing up this issue/feature request. Unfortunately, ML.NET does not currently support nor have an API to load a LightGBM model exported from its native library in text. I am saving this issue as a feature request.

The `BoosterSaveModelToString` function you've pointed out is actually an internal function that is not exposed outside of ML.NET internal usage. This function is how we can obtain an ML.NET-LightGBM model by first taking in a LightGBM model into a buffer, and then parsing it to obtain its ML.NET version, and finally saving this model to string.

Thank you @antoniovs1029 for the additional help!

**Comment by mstfbl** [comment]
Closing this issue as no new response has been given. @klesouza please feel free to reopen the issue if you have additional inquiries. Thanks!

**Comment by klesouza** [comment]
Thanks @mstfbl . Just wondering if there's a way to track this feature request?
From what I saw in the code, it shouldn't be too hard to implement given that the logic to parse the model string is already in place, right? Or are there reasons why it was not implemented so far? 
I was thinking in giving it a try, but perhaps there are reasons why it's not implemented yet

Thanks!
