### ISSUE TITLE
Unable to load DLL 'MklImports' or one of its dependencies: The specified module could not be found. (0x8007007E)

### ISSUE THREAD

**Issue by LeoAlario** [dotnet/machinelearning#5316]
### System information

- **Windows server 2019 IIS / Docker Windows Container**:
- **.NET Version 3.1.3**: 

**Project references**
Microsoft.ML 1.5.0 - 1.5.1 
Microsoft.ML.TimeSeries 1.5.0 - 1.5.1
Microsoft.ML.Mkl.Components 1.5.0 - 1.5.1 

### Issue

- **What did you do?**

 I was trying to train the model in a .NET standard 2.0 library

 ITransformer trainedModel = dataProcessPipeline.Fit(trainingDataView);

It doesn't work on IIS production environment (VM on Azure)  as well in a Docker Windows Container used from my development machine.

I've performed several attempts in order to solve the  issue, including manual installation of the Intel Math Kernel Library through the installer.   

- **What happened?**
 Dll not found exception

- **What did you expect?**

It should work fine like on my development environment (IIS Express).

### Source code / logs

Unable to load DLL 'MklImports' or one of its dependencies: The specified module could not be found. (0x8007007E)    at Microsoft.ML.Transforms.TimeSeries.EigenUtils.Dsytrd(Layout matrixLayout, Uplo uplo, Int32 n, Double[] a, Int32 lda, Double[] d, Double[] e, Double[] tau)
   at Microsoft.ML.Transforms.TimeSeries.EigenUtils.MklSymmetricEigenDecomposition(Single[] input, Int32 size, Single[]& eigenValues, Single[]& eigenVectors)
   at Microsoft.ML.Transforms.TimeSeries.TrajectoryMatrix.ComputeSvd(Single[]& singularValues, Single[]& leftSingularvectors)
   at Microsoft.ML.Transforms.TimeSeries.AdaptiveSingularSpectrumSequenceModelerInternal.TrainCore(Single[] dataArray, Int32 originalSeriesLength)
   at Microsoft.ML.Transforms.TimeSeries.AdaptiveSingularSpectrumSequenceModelerInternal.Train(RoleMappedData data)
   at Microsoft.ML.Transforms.TimeSeries.SsaForecastingEstimator.Fit(IDataView input)

**Comment by mstfbl** [comment]
Hi @LeoAlario ,

This issue is usually caused by improperly installed libraries. Please make sure your Visual Studio installation has [these packages](https://github.com/dotnet/machinelearning/blob/master/docs/building/windows-instructions.md) installed correctly, and try re-building your project. Also, please delete your `\bin` and `\obj` folders during this process, so old files will not interfere. In addition, after these steps, can you manually check to see if `MklImports.dll` is in your specific `\bin` folder? Thanks.

**Comment by mstfbl** [comment]
Hey @LeoAlario,

In addition, can you provide us with a repro of your working folder where you are receiving this error? This will help us diagnose this issue better. Thanks!

**Comment by LeoAlario** [comment]
Hello @mstfbl ,

I've tried to follow your advises without success. 

It seems that in the app folder on Windows Docker Container the MklImports.dll is not in the main folder but available in the following path:

![Cattura](https://user-images.githubusercontent.com/24278853/88206587-cc942e00-cc4e-11ea-81ea-6370a2890ce4.PNG)

The same on the publish folder for IIS production environment:

![image](https://user-images.githubusercontent.com/24278853/88206782-21d03f80-cc4f-11ea-942c-29968a0ce30b.png)

I've tried also to force copy of the dependencies available in the folder "..runtimes\win-x64\native" in the main assembly folder but the result is the same (unable to ...). 

I would also report to you that in the IISExpress, where it works properly, I can see the same reported file system structure ,regarding dependencies.

Please let me know if you need additional details. 

Thank you for your support.

**Comment by LeoAlario** [comment]
Hello @mstfbl, 

I'm able to solve it by myself in the azure production environment, the solution for it is the installation of the following package:

https://support.microsoft.com/it-it/help/2977003/the-latest-supported-visual-c-downloads

I'll try also with a Docker Windows Container and I'll let you know.

Anyway thank you for your support.
