### ISSUE TITLE
Solicitud de guía para re-entrenar un modelo ya entrenado

### ISSUE THREAD

**Issue by JuanJimenezR** [dotnet/machinelearning#5317]
### System information
NA
### Issue

Estoy logrando con éxito incluir y utilizar el código de uso para mi modelo con el ML builder.

Busco por cargar un modelo ya entrenado, y volverlo a entrenar con un  adicional conjunto de datos (a fin que el aprendizaje de mi modelo sea escalable sobre lo que ya había aprendido).

El código generado por el ML builder,  cargar el modelo y entrena uno NUEVO para el conjunto de datos nuevo, remplazando el que ya existía, esto no me permite continuar "aprendiendo" sobre mi modelo previamente entrenado.

Las documentaciones que encuentro me dirigen al anterior workflow.

Pueden por favor indicarme alguna guía para implementar el work flow deseado:
Cargar modelo local ya entrenado.
llamar al entrenador para que entre más el modelo con nuevos datos.
evaluar y guardar localmente el modelo.

Muchas Gracias!

**Comment by antoniovs1029** [comment]
Hola, @JuanJimenezR .

El artículo que buscas es éste:
https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/retrain-model-ml-net

Como verás ahí, no es posible re-entrenar cualquier modelo de ML.NET, solamente es posible re-entrenar los entrenadores ahí enlistados 😄
