### ISSUE TITLE
ML.Net Invalid GraphDef - Object Detection Model

### ISSUE THREAD

**Issue by crazyoutlook** [dotnet/machinelearning#5322]
### System information

- **OS version/distro**: Windows 10 Pro
- **.NET Version (eg., dotnet --info)**: dotnet framework 4.7

### Issue

We are working on how to consume the tensorflow model in .Net using ML.NET. We are using below tutorial as reference :

Tutorial Link : https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification

We tested with model that is used in the Tutorial and it worked fine. But, when we replace tutorial model with our tensorflow model (object detection model which we have exported from Azure Custom Vision), it is throwing an Exception saying ‘Invalid GraphDef’, while loading the tensor flow model. The same custom vision model works fine when consumed in Python code.

### Source code / logs

Details:

Project Name : TransferLearningTF 
Class name : program.cs 
Method Name : GenerateModel 

Code : 
IEstimator<ITransformer> pipeline = mlContext.Transforms.LoadImages(outputColumnName: "input", imageFolder: _imagesFolder, inputColumnName: nameof(ImageData.ImagePath))
                                                                                              .Append(mlContext.Model.LoadTensorFlowModel(_inceptionTensorFlowModel)
                                                                                                                .ScoreTensorFlowModel(outputColumnNames: new[] { "softmax2_pre_activation" }, inputColumnNames: new[] { "input" }, addBatchDimensionInput: true))

Exception Details : 

Exception Message : Tensorflow exception triggered while loading model
Source : Microsoft.ML.TensorFlow
Stacktrace :  
   at Microsoft.ML.TensorFlow.TensorFlowUtils.LoadTFSessionByModelFilePath(IExceptionContext ectx, String modelFile, Boolean metaGraph)
   at Microsoft.ML.TensorFlow.TensorFlowUtils.GetSession(IHostEnvironment env, String modelPath, Boolean metaGraph)
   at Microsoft.ML.TensorFlow.TensorFlowUtils.LoadTensorFlowModel(IHostEnvironment env, String modelPath)
   at Microsoft.ML.TensorflowCatalog.LoadTensorFlowModel(ModelOperationsCatalog catalog, String modelLocation)
   at PredictionModel.Program.GenerateModel(MLContext mlContext) in D:\Cognitive-Samples-VideoFrameAnalysis-master\Windows\PredictionModel\Program.cs:line 35
   at PredictionModel.Program.Main(String[] args) in D:\Cognitive-Samples-VideoFrameAnalysis-master\Windows\PredictionModel\Program.cs:line 22

Inner Exception:

Exception  Message  : Invalid GraphDef
Source :  TensorFlow.NET
Stack trace : 
   at Tensorflow.Status.Check(Boolean throwException)
   at Tensorflow.Graph.Import(Byte[] bytes, String prefix)
   at Tensorflow.Graph.Import(String file_path, String prefix)
   at Microsoft.ML.TensorFlow.TensorFlowUtils.LoadTFSessionByModelFilePath(IExceptionContext ectx, String modelFile, Boolean metaGraph)

**Comment by mstfbl** [comment]
Hi @crazyoutlook ,

Thank you for notifying us of this issue. Can you please share this custom model? We will attempt to reproduce the issue on our end, and without a successful reproduction, we won't be able to diagnose your issue. Thanks.

**Comment by mstfbl** [comment]
Closing this issue as no repro has been provided.

**Comment by evgeny1984** [comment]
Hello @mstfbl,

I have the same issue as crazyoutlook.

Have created in Jupyter Notebook a very simple linear regression model and saved it. Then I placed the saved_model.pb file and variables folder into the project.

When I try to load the TensorFlowModel I get exact the same exception.

Here is the content of my project file.
`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.ML" Version="1.5.2" />
    <PackageReference Include="Microsoft.ML" Version="1.5.2" />
    <PackageReference Include="Microsoft.ML.DataView" Version="1.5.2" />
    <PackageReference Include="Microsoft.ML.FastTree" Version="1.5.2" />
    <PackageReference Include="Microsoft.ML.TensorFlow" Version="1.5.2" />
    <PackageReference Include="Microsoft.ML.TensorFlow.Redist" Version="0.14.0" />
    <PackageReference Include="Microsoft.ML.Vision" Version="1.5.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="regression\saved_model.pb">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="regression\variables\variables.data-00000-of-00001">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="regression\variables\variables.index">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
`

I also tried to load the model from this tutorial with the same result. (https://docs.microsoft.com/de-de/dotnet/machine-learning/tutorials/text-classification-tf)

Please help me to solve the problem.

Thank you in advance.

**Comment by hvilppu** [comment]
> Hello @mstfbl,
> 
> I have the same issue as crazyoutlook.
> 
> Have created in Jupyter Notebook a very simple linear regression model and saved it. Then I placed the saved_model.pb file and variables folder into the project.
> 
> When I try to load the TensorFlowModel I get exact the same exception.
> 
> In the attachments you can find my test project with my custom model.
> 
> * [TensorFlow.Net.Demo.zip](https://github.com/dotnet/machinelearning/files/5519039/TensorFlow.Net.Demo.zip)
> 
> I also tried to load the model from this tutorial with the same result. (https://docs.microsoft.com/de-de/dotnet/machine-learning/tutorials/text-classification-tf)
> 
> Please help me to solve the problem.
> 
> Thank you in advance.

Same problem here
