### ISSUE TITLE
: 'Schema mismatch for input column 'data': expected Vector<Byte, 45, 45, 3>, got Vector<Byte> '

### ISSUE THREAD

**Issue by Aleksey1555** [dotnet/machinelearning#5323]
### System information

- **OS version/distro**: Windows 10 64
- **.NET Version (eg., dotnet --info)**:  Net Core 3.1

### Issue

- **What did you do?** :  Try to load images from folder as byte [], then load data into Bitmap and then  createEnumareable
- **What happened?** : Error  Type 'System.Drawing.Bitmap' is not yet supported.   in ConvertToImage
- **What did you expect?** Expect to make array of abjects with Bitmap field

### Source code / logs
i Have class:
public class MyImage
    {
        public string Label { get; set; }
        public string path { get; set; }
        [VectorType(45, 45, 3)]
        public byte[] data { get; set; }
        [ImageType(3, 4)]
        public Bitmap im { get; set; }
    }

and the code:

```
MLContext ml = new MLContext();
 string folder = @"here my path to folder with images";

// Simple function to load images and populate MyImage class (Label and path properties)
 IEnumerable<MyImage> images = LoadImagesFromDirectory3(folder: folder, useFolderNameAsLabel: true);
 IDataView data = ml.Data.LoadFromEnumerable<MyImage>(images);
 IDataView data2 = ml.Transforms.LoadRawImageBytes("data", folder, "path")
                                    .Fit(data).Transform(data);
 
 // And here i want to from data2 make data3 ( with im field)
// but here i get error:'Schema mismatch for input column 'data': expected Vector<Byte, 45, 45, 3>, got Vector<Byte> '
  IDataView data3 = ml.Transforms.ConvertToImage(45, 45, "im", "data")
                                     .Fit(data2).Transform(data2);
  // And now i want to convert from data3 of type IDataView to List<MyImage>
  // And here
  IEnumerable<MyImage> res=ml.Data.CreateEnumerable<MyImage>(data3, false)
 // and after that, i want to save images to the disk
```
`

Please help.
What i do wrong?

**Comment by Lynx1820** [comment]
Hi @Aleksey1555, 

I can't see how you're loading your images in `LoadImagesFromDirectory3`, but I'm guessing you're not loading `[45,45,3]` vectors of Image bytes. This link gives example loading functions [Image Classification Example](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.visioncatalog.imageclassification?view=ml-dotnet). If you still have trouble, feel free to paste any other relevant code and your sample 45 by 45 pixel images.

**Comment by Aleksey1555** [comment]
`LoadImagesfromDirectory3` - simply return Enumeration<MyImage> and set only **Lebel** and **path** fields.

**Comment by Lynx1820** [comment]
Can you print the `IDataView data` to ensure that it's indeed 45 x 45?

**Comment by Aleksey1555** [comment]
how to do this?

**Comment by Aleksey1555** [comment]
![image](https://user-images.githubusercontent.com/32514002/88384498-31699880-cdb5-11ea-976d-9748214ffa5a.png)

**Comment by Aleksey1555** [comment]
maybe this

**Comment by Aleksey1555** [comment]
someone please help!

**Comment by Lynx1820** [comment]
Hi @Aleksey1555 , Try replacing `[VectorType(45, 45, 3)]` with` [VectorType(45*45*3)].`

**Comment by Lynx1820** [comment]
If you can, please post your zipped code and sample data, so I can take a close look.

**Comment by Aleksey1555** [comment]
changing with [VectorType(45*45*3)] - not helped

[ForGitHub.zip](https://github.com/dotnet/machinelearning/files/4974124/ForGitHub.zip)

**Comment by Aleksey1555** [comment]
Good morning!
I Solve problem!
![image](https://user-images.githubusercontent.com/32514002/88448338-75a47980-ce45-11ea-999b-1afcca195647.png)



After call
`IDataView data2 = ml.Transforms.LoadRawImageBytes("Data", folder, nameof(MyImage.path))// "path")`
The data2 has two columns "Data":
One -  Vector<Byte,45,45,3>
Second - Vector<Byte>
