### ISSUE TITLE
Transform Vector<Byte> to Vector<width,height,3>

### ISSUE THREAD

**Issue by Aleksey1555** [dotnet/machinelearning#5324]
### System information

- **OS version/distro**: Windows 10 x64
- **.NET Version (eg., dotnet --info)**: .Net Core 3.1

### Issue

- **What did you do?** Creating pipeline for image loading 
- **What happened?**  'Schema mismatch for input column 'Data': expected Vector<Byte, 45, 45, 3>, got Vector<Byte> 
- **What did you expect?** i don't , i want to known - how covert Vector's

### Source code / logs

How to Convert Vectors?

**Comment by Lynx1820** [comment]
Hi @Aleksey1555, is the code the same you provided on issue [#5323](https://github.com/dotnet/machinelearning/issues/5323#event-3586995383) ?
