### ISSUE TITLE
Pause the Training process?

### ISSUE THREAD

**Issue by Aleksey1555** [dotnet/machinelearning#5325]
### System information

- **OS version/distro**: Windows 10 x64
- **.NET Version (eg., dotnet --info)**:  .Net Core 3.1

### Issue

- **What did you do?**
- **What happened?**
- **What did you expect?**

### Source code / logs

Hello!
Question - Can I with ML.net  stop training process, save results to the disk and resume process of training later?
Task - Multiclass classification
Trainer - ImageClassificationTrainer

**Comment by Aleksey1555** [comment]
can anyone answer to this question?

**Comment by Lynx1820** [comment]
Hi @Aleksey1555, 
Unfortunately, it is not possible to re-train an Image Classifier. More info can be found here: [retrain-model-ml-net](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/retrain-model-ml-net). 

As an alternative, you could use another framework for training and then load your model via Onnx for inferencing.

**Comment by Aleksey1555** [comment]
(((
awfully
but thank's for the answer
