### ISSUE TITLE
[Documentation] LpNormNormalizingEstimator equations display as plain text

### ISSUE THREAD

**Issue by kanadaj** [dotnet/machinelearning#5326]
Equations don't seem to work as intended in the documentation. I assume this isn't meant to be how it's displayed:

![image](https://user-images.githubusercontent.com/3247357/88553903-b951db80-d01d-11ea-89fc-e32a4a5ac3fd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71dcdd76-b41e-d01e-3a03-e26415d0339a
* Version Independent ID: 1b166fb2-85e0-0378-a467-d84d7435f491
* Content: [LpNormNormalizingEstimator Class (Microsoft.ML.Transforms)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.lpnormnormalizingestimator?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML.Transforms/LpNormNormalizingEstimator.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Transforms/LpNormNormalizingEstimator.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by Lynx1820** [comment]
Closing, as this issue was fixed.
