### ISSUE TITLE
SerializationBinder must be set for BinaryFormatter

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning#5335]
https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.ResultProcessor/ResultProcessor.cs#L1150-L1151
https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Transforms/SerializableLambdaTransform.cs#L135
https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Transforms/SerializableLambdaTransform.cs#L142

Please see tracking bug for more details:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1110054

**Comment by antoniovs1029** [comment]
This is actually CA2301 mentioned in #5334
