### ISSUE TITLE
ML.Net CustomMapping with ONNX Model

### ISSUE THREAD

**Issue by ladodc** [dotnet/machinelearning#5346]
### System information

- **Win10
- ** .Net Core 3.1 

### Issue

I do not know how to define output_column with sequence in CustomMapping.
![Output_ONNX](https://user-images.githubusercontent.com/10833738/90246362-ca2f8900-de34-11ea-8f76-25b6c1f09414.PNG)
For output_label  it is simple Int64[] . But for output_probabilities I have no idea.
I have tried in my InputClass 
`IEnumerable<IDictionary<Int64, float>> output_probability { get; set; } `
or
`OnnxSequenceType output_probability { get; set; } `

But witout success. 

Hier ist fully functional sample. With dataset and onnx model.
[TestCustomMapping.zip](https://github.com/dotnet/machinelearning/files/5074415/TestCustomMapping.zip)
Or here is code :

### Source code

`using Microsoft.ML;
using Microsoft.ML.Transforms.Onnx;
using System;
using System.Collections.Generic;

namespace TestCustomMapping
{
    class Program
    {
        static void Main(string[] args)
        {
            var mlContext = new MLContext();

            var data = new List<InputDataLinear>() { new InputDataLinear() { day = 3, hour = 4, temperature = 15.4F, vibration = 5.6F, name = "Machine 1", worker = "Hans", Fehler = true } };
            var dataView = mlContext.Data.LoadFromEnumerable<InputDataLinear>(data);

            // Define the operation code.
            Action<InputRow, OutputRow> mapping = (input, output) => {                
                output.PredictedLabelSingle = input.output_label[0];
                output.ProbabilitySingle = 0/*input.output_probability*/;
            };

            var pipeline = mlContext.Transforms.ApplyOnnxModel(modelFile: @"../../../Model/model2.onnx", inputColumnNames: new string[] { "day", "hour", "name", "worker", "temperature", "vibration" },
                    outputColumnNames: new[] { "output_label", "output_probability"});

            IDataView predictions = pipeline.Fit(dataView).Transform(dataView);

            IDataView predictions2 = mlContext.Transforms.CustomMapping(mapping, null).Fit(predictions).Transform(predictions);
   
            var metrics = mlContext.BinaryClassification.Evaluate(predictions2, labelColumnName: "Fehler", scoreColumnName: "ScoreSingle", probabilityColumnName: "ProbabilitySingle", predictedLabelColumnName: "PredictedLabelSingle");            
        }
    }

    public class InputRow
    {
        //public IEnumerable<IDictionary<Int64, float>> output_probability { get; set; }
        public IEnumerable<IDictionary<Int64, float>> output_probability { get; set; }

        public Int64[] output_label { get; set; }

    }

    public class OutputRow
    {
        public float ScoreSingle { get; set; }

        public float ProbabilitySingle { get; set; }

        public bool PredictedLabelSingle { get; set; }

    }

    class InputDataLinear 
    {
        public float day { get; set; }

        public float hour { get; set; }

        public float temperature { get; set; }

        public float vibration { get; set; }

        public string name { get; set; }

        public string worker { get; set; }

        public bool Fehler { get; set; }

    }
}
`

**Comment by antoniovs1029** [comment]
We have `OnnxSequenceType` and `OnnxSequenceTypeAttribute` for this use case, defined here:
https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.OnnxTransformer/OnnxSequenceType.cs

Unfortunately, as of now, we don't have any public sample to let users know how to use it. Still, you can have a look into the following test to have an idea on how to use it:

https://github.com/dotnet/machinelearning/blob/a76936546f5e269fc1da61f33ab541389e445294/test/Microsoft.ML.Tests/OnnxSequenceTypeWithAttributesTest.cs#L22-L66

Notice that the `TestZipMapString.onnx` used on that test can be downloaded from [here ](https://github.com/dotnet/machinelearning-testdata/blob/master/Microsoft.ML.Onnx.TestModels/zipmap/TestZipMapString.onnx) and looks like this:

![image](https://user-images.githubusercontent.com/38739674/90272359-2339f580-de12-11ea-9cc1-9d1a507c3c1b.png)

So for your case I think something like this will work:

```C#
            [OnnxSequenceType(typeof(IDictionary<int, float>))]
            IEnumerable<IDictionary<Int64, float>> output_probability { get; set; }
```

Please, let us know if this works for you. Thanks.

**Comment by antoniovs1029** [comment]
Since it's been a couple of days since my last message, and I think this would solve your question, I'm closing this issue.
If you're still having problems with this, please feel free to re-open it. Thanks.
