### ISSUE TITLE
How would I concatenate columns of different types?

### ISSUE THREAD

**Issue by dan-drews** [dotnet/machinelearning#535]
### System information

- **OS version/distro**: Windows 10 x64
- **.NET Version (eg., dotnet --info)**:  .NET Framework 4.6.1

### Issue

- **What did you do?** Combined numeric columns with FeaturizedText Columns
- **What happened?** I received an exception about mismatched column Types
- **What did you expect?** I'm not 100% sure. I am hoping to find a way to combine a text featurizer with numeric values into the "Features" column to take multiple data types into account. I saw that we have the categorical vectorizers and Hash Transform Columns available, but I from what i understand, that is for a distinct number of categories.

What I am trying to accomplish is utilizing numeric and text values in the prediction. Maybe this is just a lack of understanding on my part for this and it is not possible, but I'm kind of hoping to post the pieces of my business object that that I think could impact the result, and I cannot figure out how to do that effectively.

Note: I am using a FastTreeRegressor predicting a float value.

**Comment by Zruty0** [comment]
@dan-drews , hi and thanks for your question!

It is a common desire among ML practitioners to take advantage of different feature sources, some of which may be textual and some numeric.

The idea is that, as an experimenter, you need to figure out how to 'digitize' the non-numeric feature 'channel', and then how to combine these numeric sources together.

For example, you could use `TextFeaturizer`'s output and then concatenate it with your numeric features together to form the final 'Features' column, which you then use to train the model.

Here is a picture of a slightly more involved featurization process.
![pipelinevis](https://user-images.githubusercontent.com/41337831/42906740-d0930f14-8a90-11e8-81b4-58dde9ea024a.jpg)

In this case, you never actually need to concatenate columns of different type. Instead, you turn everything into floats, and concatenate after.

I hope this answers your question.

**Comment by dan-drews** [comment]
Thanks @Zruty0 It really helps clarify. I think I now need to start digging into the different ways to digitize this stuff, and understand the difference between the different options.
