### ISSUE TITLE
ML Model is not reloaded if prediction was made before

### ISSUE THREAD

**Issue by alexandermujirishvili** [dotnet/machinelearning#5350]
### System information

- **OS version/distro**:  Windows 10 Pro, version 2004, OS Build: 19041.450
- **.NET Version (eg., dotnet --info)**: 3.1.302

### Issue

- **What did you do?**

     After new record is available, I add it to training data and retrain model.

- **What happened?**

     New model was generated, but not reloaded in app.

- **What did you expect?**

     Reloaded model and better (expected) prediction

### Source code / logs

I use this code to add prediction engine pool:

```
services.AddPredictionEnginePool<SentimentData, SentimentPrediction>()
                  .FromFile(
                  modelName: Constants.ModelName,
                  filePath: Constants.ModelFileName,
                  watchForChanges: true);
```
![image](https://user-images.githubusercontent.com/46314872/90320515-140e9100-df53-11ea-8392-f1f66364887b.png)

Sample project: https://github.com/alexandermujirishvili/DotnetMLWatchForChanges

**Comment by frank-dong-ms** [comment]
@alexandermujirishvili thanks for using ML.NET. I can't repro your issue with the provided project.
This is what I tried to repro the issue:
1. get data
2. check on existing data
3. add new data with  /api/data/add?sentimentText=ItsTooBad&sentiment=false
4. get and check data again

Could you please provide more info on how to repro this issue? 
1. the operation steps you are using to repro this issue
2. are you using in multiple threading/multiple user scenario? from the current implementation if some one is adding new sentiment and other user is call check api they are likely to race on model file

**Comment by alexandermujirishvili** [comment]
@frank-dong-ms Thanks for your response.

I have tried again and reproduced this issue. When I add new sentiment, check request is already finished, so they should not race on model file.

I have prepared 2 GIFs. First one demonstrates issue (I call check api before I add new sentiment). 

**I** 
![with pre check](https://user-images.githubusercontent.com/46314872/90434193-105b4580-e0de-11ea-888b-5a7b25b14438.gif)

**II** 

![without pre check](https://user-images.githubusercontent.com/46314872/90434281-37b21280-e0de-11ea-8c71-4936262ec4a4.gif)

**Comment by frank-dong-ms** [comment]
@alexandermujirishvili thanks for your information, I'm able to repro the issue now. Will update once we have any findings, thanks.

**Comment by frank-dong-ms** [comment]
I have opened PR to fix this issue, the issue here is when we try to reload new model file automatically the model file is still being locked, so I change the wait strategy a little bit to wait longer time and check the file lock status consistently.

@alexandermujirishvili  If you need this fix immediately I can send you the new Microsoft.Extensions.ML.dll and you can replace the dll manually from nuget package folder and that can potentially cause compatibility issue, thanks.

**Comment by alexandermujirishvili** [comment]
@frank-dong-ms When will the next release be available?

**Comment by frank-dong-ms** [comment]
@harishsk @natke add Harish and Natelie to answering the release question.

**Comment by frank-dong-ms** [comment]
Close this issue as the fix has been merged.
