### ISSUE TITLE
Is recognition supported on .NET Framework？

### ISSUE THREAD

**Issue by LiQIjie** [dotnet/machinelearning#5353]
### System information

- **OS version/distro**:Windows
- **.NET Version (eg., dotnet --info)**: .NET Framework 4.7.2

### Issue

- **I am new to ML.NET. I noted ML.NET can run on .NET Framework and I curious about if recognition also be supported on .NET Framework or not?**

**Comment by frank-dong-ms** [comment]
@LiQIjie Thanks for looking into ML.NET. Yes, ML.NET can run on .NET Framework and you can run all supported algorithm within ML.NET on .NET Framework to do recognition.

below are some posts about using ML.NET on image recognition task:
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification
https://medium.com/@flash2048/ml-net-handwriting-numbers-recognition-23461cec2451

also a discussion on how to do face recognition using ML.NET:
https://github.com/dotnet/machinelearning/issues/5062

**Comment by LiQIjie** [comment]
thank you very much. I'll try to use it in the windowform with vb.net

**Comment by frank-dong-ms** [comment]
I will close this issue for now, feel free to reopen or raise new issue if you have further questions, thanks.

**Comment by LiQIjie** [comment]
thank you
