### ISSUE TITLE
How to feed frames from live video to a trained ONNX model

### ISSUE THREAD

**Issue by asheesh1996** [dotnet/machinelearning#5359]
using System.Drawing classes I am able to read a .MP4 file and receive frames from it and store them as Bitmap,
this process is happening on a separate thread, simultaneously on another thread I want to feed this Bitmap data to my loaded pretrained .onnx model.
I am not able to find any documentation or support on how to achieve this.

Any suggestions will be helpful, thanks in advance

**Comment by luisquintanilla** [comment]
Hi @asheesh1996 

You can take a look at this sample which uses the YOLO ONNX model for object detection inside a UWP app  to analyze live video. Note that this sample is in the process of being upgraded to the latest version of 1.5, but the logic to process videos should not change.

https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/end-to-end-apps/ObjectDetection-Onnx/OnnxObjectDetectionApp/MainWindow.xaml.cs

**Comment by michaelgsharp** [comment]
@asheesh1996 I will be closing this issue for now. If you have any further issues or questions on this after reading through the sample code please re-open this issue. Thanks!
