### ISSUE TITLE
How to load python-trained LGB model file into  LightGbmBinaryTrainer  object, and use the trained model inside c#?

### ISSUE THREAD

**Issue by galeese** [dotnet/machinelearning#5360]
### System information

- **OS version/distro**: Windows 10 
- **.NET Version (eg., dotnet --info)**: 

### Issue

- **What did you do?**
I've trained a LGB-model from the python  lightgbm package.

- **What happened?**
I've obtained:
  model-file -  "model.txt"
  file of model-parameters:  "predict.conf" 
- **What did you expect?**
I expect to somehow to create a LightGbmBinaryTrainer  object   based on the two files:
   "model.txt" and "predict.conf" 

I don't want to run "./lightgbm"  config=predict.conf from c# each time in order to obtain the new prediciton inside the *.txt file.
I want to apply the created model inside the c# environment and get the prediction inside the c# and not to load it from the txt file.
### Source code / logs

The contents of the "model.txt":
tree
version=v3
num_class=1
num_tree_per_iteration=1
label_index=0
max_feature_idx=10307
objective=binary sigmoid:1
feature_names=Column_0 Column_1 Column_2 Column_3 Column_4

The contents of the "predict.conf" 
task = predict 

data = sharp_preds_string.csv

input_model =model.txt

output_result=  LightGBM_predict_result.txt

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by michaelgsharp** [comment]
ML.Net can only import models that are either ML.Net models or ONNX models, so you can't load the model generated by the python LBG package. I looked at the documentation for python LBG and didn't see a way to export an onnx model either, though its possible I missed it. Is there a reason you don't want to directly create the model with ML.Net?

**Comment by galeese** [comment]
" Is there a reason you don't want to directly create the model with ML.Net?"
Thank you Michael,  what you intend -  is the only thing left to do!)))

**Comment by michaelgsharp** [comment]
Sounds good. Since you have that answer I will be closing this issue for now. If you have any more questions about it please feel free to re-open this issue. Thanks!

**Comment by galeese** [comment]
agree to close

вт, 25 авг. 2020 г., 19:49 Michael Sharp <notifications@github.com>:
