### ISSUE TITLE
Enable access to preloaded data in primitive data types

### ISSUE THREAD

**Issue by barrybriggs** [dotnet/machinelearning#5369]
I have been using the Accord.Net framework for some time and would like to run it side-by-side with ML.NET in my application. In my application the data exists in memory as a 2D array ```double[,]```. Headings are kept as a separate 1D string array. It would be easy enough to convert to a jagged array or to a .NET DataTable (which I do in various instances for Accord). 

However, there does not appear to be any easy way to load the data to ML.NET this way. I've looked at ```mlContext.Data.LoadFromEnumerable``` but it appears that is looking for objects not raw data. It would be massively inefficient to convert the raw data to this approach.

I'm a newbie to ML.NET so if I'm missing something, my apologies.

**Comment by michaelgsharp** [comment]
Currently there is no built in way to do this. Have you tried creating objects for it and seeing if there really is a big performance hit (time/memory/cpu)? If your training is not being done in parallel, you should be able to use the same object memory for all the data (I'll put an example of what I mean) so it shouldn't impact memory basically at all. If you are doing training in parallel, then you will have to create 1 object for each row, but it would still be good to see what the actual performance impact would be.

If you really want to use the raw data directly, the only way would be to write a custom `IDataLoader` and `IDataView`. This would be more memory efficient, but would require a lot more developer effort than just making objects to use the built in methods. So unless the performance impact is noticeable, its probably not worth the extra effort.

Sample
```
// Class to hold the raw data.
public class Data
{
        public double Col1;
        public double Col2;
        public double Col3;
        public double Col4;
        public double Col5;
}

// Make sure your data is accessible to the method so you don't need to pass it.
double[,] rawData;

// Generator to turn raw data into object
IEnumerable<Data> GetData()
{
    // Create new object outside the loop so its only created once.
    // This works because ML.Net "streams" in the data 1 row at a time (unless running in parallel),
    // so we are safe to reuse the object.
    Data data = new Data();
    for (int i = 0; i < 100000; i++)
    {
        data.Col1 = rawData[i, 0];
        data.Col2 = rawData[i, 1];
        data.Col3 = rawData[i, 2];
        data.Col4 = rawData[i, 3];
        data.Col5 = rawData[i, 4];
        yield return data;
    }
}

// Then in your main function do the normal stuff.
var mlContext = new MLContext(0);
// An IDataView is lazy evaluated. It will only pull in the rows when it needs them, one at a time.
var dataview = mlContext.Data.LoadFromEnumerable<Data>(GetData());
```

Doing it like this should let you use the data as you have it already, with only a very small amount of extrahead.

Will that work for you?

**Comment by barrybriggs** [comment]
Yes, this is helpful, thanks. It's a little more complicated because I have to synthesize the class definitions at runtime, but this is doable.

**Comment by michaelgsharp** [comment]
Awesome, I'm glad it was able to work for you. I will go ahead and close the ticket for now then. If you have any further problems with this please feel free to re-open the ticket as needed.
