### ISSUE TITLE
PredictionEnginePool uses ObjectPool which is not supported on .Net Framework 4.6.2, can we get PredictionEnginePool support for .Net Framework 4.6.2 

### ISSUE THREAD

**Issue by sanketshah11** [dotnet/machinelearning#5370]
### System information

- **OS version/distro**:
- **.NET Version (eg., dotnet --info)**: 

### Issue

- **What did you do?**
- **What happened?**
- **What did you expect?**

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by michaelgsharp** [comment]
You should be able to get ObjectPool by installing the nuget package `Microsoft.Extensions.ObjectPool`. I just created a new .net 4.6.2 project and was able to import it successfully. I didn't try running a pipeline though, just tested the import to confirm the object is there and can be used.

Can you try installing that nuget and letting me know what happens? Thanks.

**Comment by sanketshah11** [comment]
Where how do I instantiate the PredictEnginePool ? I am using an ASP.NET MVC app.

**Comment by michaelgsharp** [comment]
This [link](github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/ScalableMLModelOnWebAPI-IntegrationPkg) has more info, but basically in your `Startup.cs` file you inject the PredictionPool:
```
services.AddPredictionEnginePool<InputData, Prediction>().FromFile(Configuration["MLModel:MLModelFilePath"]);
```
You should then be able to get your prediction pool:
```
 var predictionEnginePool = services.BuildServiceProvider().GetRequiredService<PredictionEnginePool<InputData, Prediction>>();
```
and then use that for predictions:
```
predictionEnginePool.Predict(InputData);
```

The blog post goes into a lot more detail, and there are other samples [here](https://github.com/dotnet/machinelearning-samples/search?p=1&q=PredictionEnginePool&unscoped_q=PredictionEnginePool) as well. Let me know how that goes.

**Comment by michaelgsharp** [comment]
I am going to close this issue for now as the blog post and samples should have all the info you need. If you run into any more issues please re-open the issue and reach back out.
Thanks!

**Comment by sanketshah11** [comment]
@michaelgsharp  the link to the blog you provided is broken. This question is specifically for  .Net Framework 4.6.2 and not .Net Core. So there is no startup.cs. I already have it working in .net core app, but this is not this question.

**Comment by michaelgsharp** [comment]
Per our offline discussion I am going to re-open this ticket so we can further discuss it.

**Comment by michaelgsharp** [comment]
@sanketshah11, from my understanding you have had a chance to sync with some of the people from my team. Is it alright with you if we close this issue?

**Comment by sanketshah11** [comment]
For projects which use ASP.NET 4.x, which doesn’t use Microsoft.Extensions, the suggestion was to **not** use Microsoft.Extensions.ML library.

Yes, we can close the issue.
