### ISSUE TITLE
Error NETSDK1032: The RuntimeIdentifier platform 'browser-wasm' and the PlatformTarget 'x64' must be compatible

### ISSUE THREAD

**Issue by marek-safar** [dotnet/machinelearning#5375]
---
**Issue moved from dotnet/runtime#41556**
- Please respond to @andersson09.

---

_From @andersson09 on Saturday, August 29, 2020 6:14:29 PM_

### Description

I want to run **Microsoft.ML 1.5.1** in Blazor. When running the application (dotnet run) I get:
"Microsoft.ML currently supports 'x64' and 'x86' processor architectures. Please ensure your application is targeting 'x64' or 'x86'". 

If I add <PlatformTarget>x64</PlatformTarget> to csproj to fix the above issue I receive:
"Error NETSDK1032: The RuntimeIdentifier platform 'browser-wasm' and the PlatformTarget 'x64' must be compatible."

### Configuration

5.0.100-preview.8.20417.9
Windows 10

### Regression?

This used to work fine with Blazor 3.2.1.

**Comment by marek-safar** [comment]
---
**Issue moved from dotnet/runtime#41556**
- Please respond to @Dotnet-GitSync-Bot.

---

_From @Dotnet-GitSync-Bot on Saturday, August 29, 2020 6:14:31 PM_

I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one [area label](https://github.com/dotnet/runtime/blob/master/docs/area-owners.md).

**Comment by marek-safar** [comment]
---
**Issue moved from dotnet/runtime#41556**
- Please respond to @msftbot[bot].

---

_From @msftbot[bot] on Sunday, August 30, 2020 2:37:34 PM_

Tagging subscribers to this area: @CoffeeFlux
See info in area-owners.md if you want to be subscribed.

**Comment by marek-safar** [comment]
---
**Issue moved from dotnet/runtime#41556**
- Please respond to @CoffeeFlux.

---

_From @CoffeeFlux on Sunday, August 30, 2020 4:22:00 PM_

cc: @lewing @steveisok

**Comment by marek-safar** [comment]
---
**Issue moved from dotnet/runtime#41556**
- Please respond to @marek-safar.

---

_From @marek-safar on Monday, August 31, 2020 9:52:47 AM_

This is ML.Net issue which could handle this architecture better. It supports only x64/x86 for its runtimes so it rejects wasm. You can skip the check by setting `EnableMLUnsupportedPlatformTargetCheck` to `false` which will probably break some functionality.

**Comment by mstfbl** [comment]
Hi @marek-safar ,

Thank you for letting us know about this issue. Can you please share a repro of this issue? We're not able to diagnose without a repro to analyze the issue. Thanks!

**Comment by CoffeeFlux** [comment]
Marek was the one who moved the issue from dotnet/runtime, but the person who opened it is @andersson09. See https://github.com/dotnet/runtime/issues/41556

**Comment by marek-safar** [comment]
@mstfbl the repro should be pretty simple. Create Blazor app using .NET5 preview 8 or newer, add ML.NET to the project and build/publish the app. You will hit this https://github.com/dotnet/machinelearning/blob/master/pkg/Microsoft.ML/build/netstandard2.0/Microsoft.ML.targets#L11-L20 check because Blazor WebAssembly uses `WASM` architecture.

**Comment by andersson09** [comment]
@mstfbl Just to add. It worked before on blazor 3.2.1 (netstandard2.1) because I could explicitly set x64 to target platform. I understand that ML.NET officially supports dotnetcore but since it is a netstandard library I assumed it should also work on blazor

**Comment by mstfbl** [comment]
@marek-safar @andersson09 I obtained the same error check at https://github.com/dotnet/machinelearning/blob/master/pkg/Microsoft.ML/build/netstandard2.0/Microsoft.ML.targets#L11-L20 with Blazor 3.2.1. As these checks were not recently changed, while ML.NET ran on Blazor prior to v3.2.1, this is no longer possible. As said before, ML.NET does not currently support WebAssembly, however this can be an enhancement request in the future.

**Comment by andersson09** [comment]
> @marek-safar @andersson09 I obtained the same error check at https://github.com/dotnet/machinelearning/blob/master/pkg/Microsoft.ML/build/netstandard2.0/Microsoft.ML.targets#L11-L20 with Blazor 3.2.1. As these checks were not recently changed, while ML.NET ran on Blazor prior to v3.2.1, this is no longer possible. As said before, ML.NET does not currently support WebAssembly, however this can be an enhancement request in the future.

Are you saying you tried to run 3.2.1 but it didn't work? Did you target x64 in Csproj?

**Comment by mstfbl** [comment]
Closing this issue as this has been addressed in #5393.
