### ISSUE TITLE
ApplyOnnxModel with parameter ONNX model as byte[] is missing, why?

### ISSUE THREAD

**Issue by ladodc** [dotnet/machinelearning#5376]
Hi, 

in ONNX Runtime exists possibility to create session from byte array like this. 
**public InferenceSession(byte[] model);**
Why is such a possibility missing in ML.Net OnnxCatalog.ApplyOnnxModel method.
ApplyOnnxModel allows only:
**ApplyOnnxModel ( ... string modelFile ...)**
I think it would make definitely sense. Becouse it would allow loading onnx model direct from database and not only from file system.
Is this planed for the future release? Or is there any workaround or some reason why is it not implemented?
I would be happy for any comments.

**Comment by mstfbl** [comment]
Hi @ladodc,

You are correct in that there is currently no public method to load an ONNX model directly from a `byte[]`, but rather a `string modelpath`, to return an `OnnxScoringEstimator`. However, there is a way to load an `OnnxModel` from a `byte array` as you request through the following `CreateFromBytes` functions:

https://github.com/dotnet/machinelearning/blob/293321628fe408255adb74dd6e718e7469bdbd85/src/Microsoft.ML.OnnxTransformer/OnnxUtils.cs#L314-L346

You can simply load an OnnxModel with the first `OnnxModel CreateFromBytes(byte[] modelBytes)` or use the second `CreateFromBytes` to specify the GPU device to run on, or option to continue running on CPU after a GPU error, and so on.

I'm closing this issue as I've provided a way to load an `OnnxModel` through a `byte[] array`. Feel free to post additional comments if you have further questions. Thanks!

**Comment by ladodc** [comment]
Hi Mustafa, 
thanks for your comments. But I would like to use ApplyOnnxModel  with byte[] in ML.NET Pipeline.
ApplyOnnxModel returns Estimator which after fit method returns Transfomrer. So I can use IDataView with input features and  transform these data with Onnx model to get IDataview with predictions.
Something like this:



	var dataView_model = mlContext.Transforms.ApplyOnnxModel(outputColumnNames: outputColumnNames, inputColumnNames: inputColumnNames, this.ModelFile).Fit(dataView_preprocessing).Transform(dataView_preprocessing);
                    
	var dataView_evaluation = this.ApplyCustomMapping(dataView_model);
                    
	///Standard binary evaluator for all models
	return mlContext.BinaryClassification.Evaluate(dataView_evaluation, labelColumnName: labelColumnName,
													scoreColumnName: "ScoreSingle",
													probabilityColumnName: "ProbabilitySingle",
													predictedLabelColumnName: "PredictedLabelSingle") as TMetrics;

But instead of the Parameter string modelFile I would like to use byte[].
I have no idea how to use your suggestion. Becouse OnnxModel with its CreateFromBytes is internal. So I cannot acces this method from my assembly. But maybe I have missed something.  Let me know if there is any way how to solve my problem.

**Comment by ladodc** [comment]
Hi, 
has anybody idea how to solve my problem?

**Comment by AliYildizoz909** [comment]
Hello @ladodc  
Did you solve the problem?
