### ISSUE TITLE
LoadFromTextFile<ModelInput>("./data/*") - System.ArgumentOutOfRangeException: File does not exist at path

### ISSUE THREAD

**Issue by rspaulino** [dotnet/machinelearning#5377]
### System information

- **OS version/distro**:macOS 10.15.6
- **.NET Version (eg., dotnet --info)**: 
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.8.20417.9
 Commit:    fc62663a35

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.100-preview.8.20417.9/

Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9

### Issue

- **What did you do?**
Follow this instruction: https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/load-data-ml-net#load-from-files-in-a-single-directory
- **What happened?**
`Unhandled exception. System.ArgumentOutOfRangeException: File does not exist at path: ./data/* (Parameter 'path')`
- **What did you expect?**
I expected to load the files from the directory.

### Source code / logs
```c#
var mlContext = new MLContext();

var loader = mlContext.Data.CreateTextLoader<ModelInput>();

//THIS WORK
var d = loader.Load("./data/*");

//THIS DOESN'T
var data = mlContext.Data.LoadFromTextFile<ModelInput>("./data/*");
```
Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by mstfbl** [comment]
Hi @rspaulino,

Thank you for notifying us of this issue. Can you please include a repro of your bug, with the exact code and data structure you are trying to load? I attempted to reproduce your bug, however both `Load` and `LoadFromTextFile` produce the expected result.

**Comment by rspaulino** [comment]
[data.zip](https://github.com/dotnet/machinelearning/files/5152698/data.zip) here are the folder with two simple .txt files

<img width="1347" alt="Screen Shot 2020-08-31 at 5 19 27 PM" src="https://user-images.githubusercontent.com/378671/91770166-b1520200-ebae-11ea-9bd2-8b78eb0a36da.png">

the structures is a simple folder (data) with two files adult.txt, adult1.txt
<img width="122" alt="Screen Shot 2020-08-31 at 5 26 06 PM" src="https://user-images.githubusercontent.com/378671/91770374-1574c600-ebaf-11ea-8c9c-2b7eafcf2547.png">


and here is the code:

```c#
using Microsoft.ML;
using Microsoft.ML.Data;

var mlContext = new MLContext();

var loader = mlContext.Data.CreateTextLoader<ModelInput>();

//THIS WORK
var d = loader.Load("./data/*");

//THIS DOESN'T
var data = mlContext.Data.LoadFromTextFile<ModelInput>("./data/*");

public class ModelInput
{
    [LoadColumn(0)]
    public bool Label { get; set; }
    [LoadColumn(1)]
    public string Workclass { get; set; }
}
```
let me know if there is anything else I can help. Thanks.

**Comment by mstfbl** [comment]
Thank you for the repro. There is a check that does not take into account paths that may contain a wildcard symbol such as "*":

https://github.com/dotnet/machinelearning/blob/4dcc6a827f1894f7bf70630a5893857d6c4d94d8/src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderSaverCatalog.cs#L249

I have opened PR #5380 to fix this. This issue will be closed when the PR is merged.
