### ISSUE TITLE
LightGbm System.InvalidOperationException after the latest update

### ISSUE THREAD

**Issue by evo11x** [dotnet/machinelearning#5382]
### System information

- Win10/x64
- .Net 4.8

### Issue

- It crashes in this line var model = pipeline.Fit(trainData); 
- I get this error: System.InvalidOperationException: 'LightGBM Error, code is -1, error message is 'Unknown importance type: only support split=0 and gain=1'.'

With the previous version everything worked fine and nothing was modified in my source code since it worked.

This is my gbm setting 
.Append(mlContext.Regression.Trainers.LightGbm("PercentPredict", "Features",null,null,null,null,200));

**Comment by mstfbl** [comment]
Hi @evo11x ,

Thank you for letting us know about this issue. Can you please attach a repro with your full code and dataset with which you obtained this error? We need to see these to fully debug your issue. Thanks.

**Comment by Lynx1820** [comment]
Hi @evo11x , 

Please reopen if you're able to provide us with more information.

**Comment by gharibkhani** [comment]
Hi @Lynx1820 ,

This error can be reproduced by any example. I just used the example in docs.microsoft.com and able to reproduce it.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.lightgbmextensions.lightgbm?view=ml-dotnet

I created a console app and you can access it from the link below:

https://drive.google.com/drive/folders/1-wc04CM75-IGoxjRAniDuhqI-zrHTWwM?usp=sharing
