### ISSUE TITLE
Question about predictor output: Score and PredictedLabel columns

### ISSUE THREAD

**Issue by AdamMcIntosh** [dotnet/machinelearning#5383]
Using the linear svm algorithm in ML.NET I am trying to get the probability that a prediction is in a certain class. However, probability is never outputted and according to this GitHub issue (https://github.com/dotnet/machinelearning/issues/376#issuecomment-399282699), a regression SVM doesn't output probability.

Is there something I am missing or is getting the probability of a linear svm prediction possible in ML.Net?

**Comment by mstfbl** [comment]
Hi @AdamMcIntosh ,

It is true that the `LinearSvmTrainer` does not output the probability of a Linear SVM prediction. Feel free to browse other trainers listed [here ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers?view=ml-dotnet)that may suit your needs. Thanks.
