### ISSUE TITLE
States that TextFeaturizingEstimator handles TF-IDF

### ISSUE THREAD

**Issue by rdorris** [dotnet/machinelearning#5384]
[Enter feedback here]
Not seeing any reference to how to set TF, IDF or TF-IDF options. Are you sure TextFeaturizingEstimator actually uses that algorithm?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deeb31e0-6843-e9ae-e6ad-028c4ec9121b
* Version Independent ID: bf1e4b11-7652-7da4-4791-aa2d9488971c
* Content: [TextFeaturizingEstimator Class (Microsoft.ML.Transforms.Text)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.text.textfeaturizingestimator?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML.Transforms.Text/TextFeaturizingEstimator.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Transforms.Text/TextFeaturizingEstimator.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by justinormont** [comment]
Good question. The use of [TF-IDF](https://en.wikipedia.org/wiki/Tf%E2%80%93idf) in the `FeaturizeText` transform is not documented, so I created a short sample for you.

Choices for the ngram weights: ([code](https://github.com/dotnet/machinelearning/blob/d1bf42551f0f47b220102f02de6b6c702e90b2e1/src/Microsoft.ML.Transforms/Text/NgramTransform.cs#L865-L890)) 
* Term-frequency (`WeightingCriteria.tf`) (default)
* Inverse-document frequency (`WeightingCriteria.Idf`).
* TF-IDF (`WeightingCriteria.TfIdf`)

```c#
var featurizeTextOptions = new TextFeaturizingEstimator.Options()
{
    // Produce cleaned up tokens for possible input to the word embedding transform
    OutputTokensColumnName = "OutputTokens", 

    // Text cleaning (not shown is stop word removal)
    KeepDiacritics = false,
    KeepPunctuations = false,
    KeepNumbers = true,
    CaseMode = TextNormalizingEstimator.CaseMode.Lower,

    // Row-wise normalization (see: NormalizeLpNorm)
    Norm = TextFeaturizingEstimator.NormFunction.L2,

    // ngram options
    WordFeatureExtractor = new WordBagEstimator.Options()
    {
        NgramLength = 2,
        UseAllLengths = true, // Produce both unigrams and bigrams
        Weighting = NgramExtractingEstimator.WeightingCriteria.TfIdf, // TF-IDF
    },

    // chargram options
    CharFeatureExtractor = new WordBagEstimator.Options()
    {
        NgramLength = 3,
        UseAllLengths = false, // Produce only tri-chargrams and not single/double characters
        Weighting = NgramExtractingEstimator.WeightingCriteria.TfIdf, // TF-IDF
    },
};

// Featurization pipeline
var pipeline = mlContext.Transforms.Conversion.MapValueToKey("Label", "Label") // Needed for multi-class to convert string labels to the Key type
                            .Append(mlContext.Transforms.Text.FeaturizeText("FeaturesText", featurizeTextOptions, new[] { "InputText" })) // Use above options object
                            .Append(mlContext.Transforms.Concatenate("Features", new[] { "FeaturesText" })) // Concat is incase there are additional columns
                            .Append(mlContext.Transforms.NormalizeMinMax("Features", "Features")) // Generally unneeded if only using the output from FeaturizeText as it's row-wise normalized w/ a L2-norm
                            .AppendCacheCheckpoint(mlContext); // Cache the featurized dataset in memory for added speed

// Trainer 
var trainer = mlContext.MulticlassClassification.Trainers.OneVersusAll(mlContext.BinaryClassification.Trainers.AveragedPerceptron(labelColumnName: "Label", numberOfIterations: 10, featureColumnName: "Features"), labelColumnName: "Label")
                            .Append(mlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel", "PredictedLabel"));
var trainingPipeline = pipeline.Append(trainer);
```

**Comment by rdorris** [comment]
Thank you very much for the code sample. I found the WeightingCriteria after searching around for a while yesterday, which is why I closed the issue.
