### ISSUE TITLE
Using OnnxTransformer throws TypeInitializationException

### ISSUE THREAD

**Issue by yousiftouma** [dotnet/machinelearning#5385]
This issue is a duplicate of https://github.com/dotnet/machinelearning/issues/5262 which was closed until further feedback was provided. Feedback was provided but haven't received any activity. I don't know how to notify properly to get it reopened. IMO, the best course of action is to reopen that issue and close this. Sorry for any inconvenience.

### System information

- **OS version/distro**: Windows 7
- **.NET Version (eg., dotnet --info)**: core 3.1

### Issue
When trying to use OnnxTransformer, the native libraries aren't loaded properly. I can see them under bin\Debug\netcoreapp3.1\runtimes\(platform)\native.
If I use package version 1.4.0 of OnnxTransformer, without installing the runtime myself, it works.
I couldn't find any docs regarding the requirement to install the runtime manually (I figured it out by browsing all over the place, but not through docs really). I suppose this should be clear when you're not using the onnxruntime package explicitly, but rather the higher level API of OnnxTransformer?

On a separate note: Is it sufficient to install the GPU natives and use the `fallbackToCpu` flag of `ApplyOnnxModel` to be able to run inferencing on both CPU and GPU? I'm having a hard time finding this documented.

- **What did you do?**
Installed `Microsoft.ML.OnnxTransformer` 1.5.0 and `Microsoft.ML.OnnxRuntime` 1.3.0 and used `ApplyOnnxModel` in a pipeline.

- **What happened?**
Calling `ApplyOnnxModel` throws `System.TypeInitializationException`.

- **What did you expect?**
That my ONNX model can be used.

### Source code / logs
Inner exception message:

"Unable to load DLL 'onnxruntime' or one of its dependencies: The specified module could not be found. (0x8007007E)"

**Comment by mstfbl** [comment]
Hi @yousiftouma ,

Can you please provide a repro? Without one, I won't be able to diagnose exactly why you're getting this error. As discussed in issue #5262 , as long as the proper NuGet packages are installed, you should not be getting this exception.

**Comment by yousiftouma** [comment]
Hello @mstfbl, and thanks for the response.

Here in lies the problem. I consistently get the exception on my machine with the package configuration specified in my previous issue. I consistently _do not_ get an exception if I go back to previous versions. That's why I was trying to figure out if it was OS-related. Not sure it would make sense but I'm really at a loss.

**Comment by harishsk** [comment]
Hi @yousiftouma Can you please confirm that you have added either `Microsoft.ML.OnnxRuntime.Cpu` or `Microsoft.ML.OnnxRuntime.GPU` as described [in the docs here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.onnx.onnxscoringestimator?view=ml-dotnet
)

**Comment by yousiftouma** [comment]
Hi @harishsk 
I suppose you mean `Microsoft.ML.OnnxRuntime` when you say `Microsoft.ML.OnnxRuntime.CPU`.

Since our project is supposed to run on GPU in prod, we have the GPU version of the OnnxRuntime nuget package installed (`1.3.0`), along with `Microsoft.ML.OnnxTransformer` (`1.5.0`). On my machine, I use the same package but set `gpuId` to `null` and `fallbackToCpu` to `true`, also per the docs you linked.
I have tried the CPU version of the package **as well** with the same result (of course replacing the GPU package, not installing both at the same time).

**Comment by antoniovs1029** [comment]
> That's why I was trying to figure out if it was OS-related. Not sure it would make sense but I'm really at a loss.
Have you tried running it on another version of Windows? As stated on the previous issue (#5262) I was able to run the sample you weren't able to run on my machine, so it was odd that you were getting this exception.

I've reached out to Onnxruntime team, asking if there are any known issues with Windows 7 and OnnxRuntime 1.3.0, and they've just replied saying that you need to make sure that you have these installed:

```
Windows 7 SP1 & Server 2008 R2:
Update KB3068708 (contains both ETW and UTC)
Update KB3080149 (Supersedes KB3068708)
```

if that doesn't work, can you please share your code, or the code of the sample that you weren't able tor un on last issue I pointed to? (I know the code of the sample is the same as found on the samples repo, but I'd like to see how are you configuring that project, and if the dependencies are correct).

Thanks

**Comment by yousiftouma** [comment]
> 
> Have you tried running it on another version of Windows? As stated on the previous issue (#5262) I was able to run the sample you weren't able to run on my machine, so it was odd that you were getting this exception.
> 

I have, our project currently works on Windows 10. I had situations previously where the same setup was failing on that too, but that could be attributed to the clean/rebuild issue you talked about earlier. Was a while ago now.

> I've reached out to Onnxruntime team, asking if there are any known issues with Windows 7 and OnnxRuntime 1.3.0, and they've just replied saying that you need to make sure that you have these installed:
> 
> ```
> Windows 7 SP1 & Server 2008 R2:
> Update KB3068708 (contains both ETW and UTC)
> Update KB3080149 (Supersedes KB3068708)
> ```
> 

Thanks, I will check it out on my machine tomorrow at work. My Win7 installation is rather a mess, so this could be why.

> if that doesn't work, can you please share your code, or the code of the sample that you weren't able to run on last issue I pointed to? (I know the code of the sample is the same as found on the samples repo, but I'd like to see how are you configuring that project, and if the dependencies are correct).
> 
> Thanks

Sure, I'll get back to you with that if needed.

**Comment by yousiftouma** [comment]
Both updates were installed on my computer.

Here is the sample: https://github.com/yousiftouma/onnx-sample

Still same issue. If i comment out the `OnnxRuntime` nuget in OnnxObjectDetectionWeb.csproj and change `OnnxTransformer` to 1.4.0, it works without the exception.

**Comment by yousiftouma** [comment]
Hi, thought I'd provide some feedback to this.

I've since gotten a new machine with Windows 10 and running the new updated existing sample that uses Microsoft.ML 1.5.0 and OnnxRuntime on 1.4.0, I don't get this exception anymore. Don't know what the issue was, probably something up with my machine. Even if it wasn't the updated sample seems to work fine. Guess this can be closed now.
