### ISSUE TITLE
Image preprocessing in pipeline results in different prediction value then manual preprocessing

### ISSUE THREAD

**Issue by PMGruber** [dotnet/machinelearning#5387]
### System information

- **OS version/distro**:
      Windows 10
- **.NET Version (eg., dotnet --info)**: 
      .net Core 3.1
- **ML.NET Version (eg., dotnet --info)**: 
      ML.NET 1.5.1
### Issue

- **What did you do?**
With my ML.NET code I load an existing TensorFlow Model for image classification and execute it for a single image. This I do in two different ways where the difference is how I generate the input data for the prediction.
V1: Load bitmap with "normal" C# code and manually create the float array that is used for prediction directly.
V2: Use ML.NET pipeline for preprocessing (Load image, resize, extract pixels) before it goes into prediction.

- **What happened?**
The two variants result in different prediction values.

- **What did you expect?**
The same prediction result for both variants.

### Source code / logs

The model uses an image in float representation as input (image count, image height, image width, image channels)
`Vector<Single, 275, 384, 3>`
and returns as result a list of probabilities.

The test bitmap is a grayscale image with the same size like expected from the model (384x275).

When the model is executed with python code following preprocessing is performed (load image, copy channel to generate a "RGB" image, extend the required 4th dimension)
```
img = plt.imread(path_image)
img = cv2.cvtColor(img,cv2.COLOR_GRAY2RGB)
img = np.expand_dims(img, axis=0)
```
When prediction is executed the best match is ~27,71%.

The same workflow I implemented with ML.NET. The classify method simply writes the results in console window.
```
var image = new Bitmap(_predictSingleImagePath);
var floatImage = VerySlowBitmapTo1dFloatArrayConverter(image);

MLContext mlContextV1 = new MLContext();
ITransformer modelV1 = GenerateModelV1(mlContextV1);
ClassifySingleImageV1(mlContextV1, modelV1, floatImage);
```

For preprocessing I extract pixel values in a very easy way and "convert and copy" them to my 1d float representation of the image.
```
private static float[] VerySlowBitmapTo1dFloatArrayConverter(Bitmap image)
{
    List<float> floatImage = new List<float>();

    for (int row = 0; row < image.Height; ++row)
    {
        for (int column = 0; column < image.Width; ++column)
        {
             var pixelValues = image.GetPixel(column, row);
             floatImage.Add(pixelValues.R / 255.0f);
             floatImage.Add(pixelValues.G / 255.0f);
             floatImage.Add(pixelValues.B / 255.0f);
        }
    }

    return floatImage.ToArray();
 }
```

After loading the model I create a pipeline that just contains the execution of the model.
```
public static ITransformer GenerateModelV1(MLContext mlContext)
{
    IDataView trainingData = mlContext.Data.LoadFromEnumerable(new List<ImageDataV1>());
           
    var tensorFlowModel = mlContext.Model.LoadTensorFlowModel(_TensorFlowModel);
           
    IEstimator<ITransformer> pipeline = tensorFlowModel.ScoreTensorFlowModel(outputColumnNames: new[] { "StatefulPartitionedCall" }, inputColumnNames: new[] { "serving_default_input_4" }, addBatchDimensionInput: false);
                                            
    ITransformer model = pipeline.Fit(trainingData);

    return model;
}
```

Finally I perform a prediction and write the result to console.
```
public static void ClassifySingleImageV1(MLContext mlContext, ITransformer model, float[] image)
{
    var imageData = new ImageDataV1()
    {
        Image = image
    };

    var predictor = mlContext.Model.CreatePredictionEngine<ImageDataV1, ImagePrediction>(model);
    var prediction = predictor.Predict(imageData);

    Console.WriteLine($"Image predicted with score: {prediction.Scores.Max()} ");

    foreach(var score in prediction.Scores)
    {
        Console.WriteLine(score.ToString());
    }
}

public class ImageDataV1
{
    [LoadColumn(0), ColumnName("serving_default_input_4"), VectorType(316800)]
    public float[] Image;
}

public class ImagePrediction
{
    [ColumnName("StatefulPartitionedCall")]
    public float[] Scores;
}
```
With this code I get as best match the value 0,27709773, so ~27,71% like the python version.

So far so good. Now I make the same but instead of the manual image handling I use pipeline methods.

Same workflow, just with different method calls.
```
MLContext mlContextV2 = new MLContext();
ITransformer modelV2 = GenerateModelV2(mlContextV2);
ClassifySingleImageV2(mlContextV1, modelV2);
```
Also model execution is quite the same.
```
public static void ClassifySingleImageV2(MLContext mlContext, ITransformer model)
{
    var imageData = new ImageDataV2()
    {
        ImagePath = _predictSingleImagePath
    };

    var predictor = mlContext.Model.CreatePredictionEngine<ImageDataV2, ImagePrediction>(model);
    var prediction = predictor.Predict(imageData);

    Console.WriteLine($"Image: {Path.GetFileName(imageData.ImagePath)} predicted with score: {prediction.Scores.Max()} ");

    foreach (var score in prediction.Scores)
    {
        Console.WriteLine(score.ToString());
    }
}
```
The difference is the used pipeline.
I load the image from the given path.
Then I "resize" the image the get a "known-size image".
Final preprocessing step is to get float values from the bitmap.
```
public static ITransformer GenerateModelV2(MLContext mlContext)
{
    IDataView trainingData = mlContext.Data.LoadFromEnumerable(new List<ImageDataV2>());

    var tensorFlowModel = mlContext.Model.LoadTensorFlowModel(_TensorFlowModel);

    IEstimator<ITransformer> pipeline = mlContext.Transforms.LoadImages(outputColumnName: "serving_default_input_4", imageFolder: _imagesFolder, inputColumnName: nameof(ImageDataV2.ImagePath));
    pipeline = pipeline.Append(mlContext.Transforms.ResizeImages(outputColumnName: "serving_default_input_4", imageWidth: ImageSettings.ImageWidth, imageHeight: ImageSettings.ImageHeight, inputColumnName: "serving_default_input_4"));
    pipeline = pipeline.Append(mlContext.Transforms.ExtractPixels(
                                                        outputColumnName: "serving_default_input_4",
                                                        inputColumnName: "serving_default_input_4",
                                                        interleavePixelColors: false,
                                                        offsetImage: 0,
                                                        colorsToExtract: ImagePixelExtractingEstimator.ColorBits.Rgb,
                                                        orderOfExtraction: ImagePixelExtractingEstimator.ColorsOrder.ARGB,
                                                        scaleImage: 1,
                                                        outputAsFloatArray: true));
    pipeline = pipeline.Append(tensorFlowModel.ScoreTensorFlowModel(outputColumnNames: new[] { "StatefulPartitionedCall" }, inputColumnNames: new[] { "serving_default_input_4" }, addBatchDimensionInput: false));                   
                    
    ITransformer model = pipeline.Fit(trainingData);

    return model;
}

public class ImagePrediction
{
    [ColumnName("StatefulPartitionedCall")]
    public float[] Scores;
}

public class ImageDataV2
{
    [LoadColumn(0)]
    public string ImagePath;
}
```
With this pipeline I get a best match of ~49,79%. Quite different from the other implementation. I played a little bit with parameters but was not even close to 27%.

Some suggestion what I'm doing wrong in preprocessing part of the pipeline?

I searched for information how I can check the interim results from the pipeline to further trace down the difference. Unforunately I didn't find something that helps me (only things about schemas). Does anybody know some useful documentation/tutorial regarding that topic?

Thanks and regards

**Comment by mstfbl** [comment]
Hi @PMGruber ,

Can you please share your repro and your TF model? It will be easier for us to find exactly what is going on differently.

For now, I can see that `ImageDataV2` has no `ColumnName("serving_default_input_4")`, and you're passing in `mlContextV1` and not `mlContextV2` in `ClassifySingleImageV2(mlContextV1, modelV2);`.

**Comment by PMGruber** [comment]
Hello @mstfbl 
thanks for your response.

You are right, there is a typo with the numbers. I chaged the line

ClassifySingleImageV2(mlContextV**1**, modelV2);
to
ClassifySingleImageV2(mlContextV**2**, modelV2);

unfortunately this does not change the result.

The TensorFlow model I cannot make public. So I invited you to a private repository to get access.

**Comment by mstfbl** [comment]
Hi @PMGruber ,

Thank you for your response and for your private repo access request. Please forward the invitation to @Lynx1820 , who will help you debug this issue.

**Comment by PMGruber** [comment]
Hi
@mstfbl Done. Thanks for support.
@Lynx1820 I send you an invitation to the repo.

**Comment by Lynx1820** [comment]
Hi @PMGruber, 

I found the issue. On your bitmap2float function, you're scaling each pixel by 1/255, so you need to specify that in `scaleImage`. In addition, you are interleaving the pixel values, so you're writing them as [R,G,B,R,G,B...] instead of [R,R...G,G...B,B], so you need to set the `interleavePixelColors` flag to `True`. 

Your `GenerateModelV2` should look as follows 
```        public static ITransformer GenerateModelV2(MLContext mlContext)
        {
            IDataView trainingData = mlContext.Data.LoadFromEnumerable(new List<ImageDataV2>());

            var tensorFlowModel = mlContext.Model.LoadTensorFlowModel(_tensorFlowModel);
            var schema = tensorFlowModel.GetModelSchema();
            var inputschema = tensorFlowModel.GetInputSchema();

            IEstimator<ITransformer> pipeline = mlContext.Transforms.LoadImages(outputColumnName: "serving_default_input_4", imageFolder: _imagesFolder, inputColumnName: nameof(ImageDataV2.ImagePath));
            pipeline = pipeline.Append(mlContext.Transforms.ResizeImages(outputColumnName: "serving_default_input_4", imageWidth: ImageSettings.ImageWidth, imageHeight: ImageSettings.ImageHeight, inputColumnName: "serving_default_input_4"));
            pipeline = pipeline.Append(mlContext.Transforms.ExtractPixels(
                                                                outputColumnName: "serving_default_input_4",
                                                                inputColumnName: "serving_default_input_4",
                                                                interleavePixelColors: true,
                                                                offsetImage: 0,
                                                                scaleImage:1f/255.0f,
                                                                colorsToExtract: ImagePixelExtractingEstimator.ColorBits.Rgb,
                                                                orderOfExtraction: ImagePixelExtractingEstimator.ColorsOrder.ARGB,
                                                                outputAsFloatArray: true));
            pipeline = pipeline.Append(tensorFlowModel.ScoreTensorFlowModel(outputColumnNames: new[] { "StatefulPartitionedCall" }, inputColumnNames: new[] { "serving_default_input_4" }, addBatchDimensionInput: false));                   
                    
            ITransformer model = pipeline.Fit(trainingData);

            return model;
        }
```

Closing this issue, feel free to follow up if you have any questions.
