### ISSUE TITLE
Typo - anMicrosoft

### ISSUE THREAD

**Issue by rspaulino** [dotnet/machinelearning#5388]
https://github.com/dotnet/machinelearning/blob/5370692f6d1e6f1f686596d530032b4226dc9e80/src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs#L66

Typo:
data: The enumerable data containing type TRow to convert to anMicrosoft.ML.IDataView .

Should be:
data: The enumerable data containing type TRow to convert to an Microsoft.ML.IDataView.

<img width="625" alt="Screen Shot 2020-09-04 at 4 22 45 PM" src="https://user-images.githubusercontent.com/378671/92282080-f33eb900-eeca-11ea-87aa-c4d00817aaaa.png">

**Comment by mstfbl** [comment]
Thank you for letting us know about this typo. It will be fixed as part of PR #5386.
