### ISSUE TITLE
Implement different algorithms 

### ISSUE THREAD

**Issue by attiqeurrehman** [dotnet/machinelearning#5390]
Hi,

I am student and looking to implement different algorithms regarding forecast to better understand the workings of it and later use them. Following are the algorithms: 

1. Linear Regression
2. Ensemble methods (Random Forest Regression)
3. XGBoost
4. Long Short-Term Memory (artificial recurrent neural network)
5. ARIMA Time Series Forecasting

Is there any document or guidelines that can help me get started. 

Thanks,
Attiqe

**Comment by Lynx1820** [comment]
Hi @attiqeurrehman, 

Checkout our documentation page [ML.NET trainers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers?view=ml-dotnet), [FastTree Trainers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.fasttree?view=ml-dotnet), [LightGBM Trainers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.fasttree?view=ml-dotnet). 
We do not support LSTMs. 

If you want to build the source repo, checkout [Developer-Guide](https://github.com/dotnet/machinelearning/blob/master/docs/project-docs/developer-guide.md).

Let me know if you have any questions.

**Comment by kerohero** [comment]
@Lynx1820 Is there will be a LSTM support in the future?

**Comment by Lynx1820** [comment]
@kerohero I'm not sure, but probably not in the next six months. However, you can always create and train a model in another framework and consume it in ML.NET through Onnx for inferencing.

**Comment by harishsk** [comment]
Hi @kerohero , As @Lynx1820 , We don't foresee implementing LSTMs specifically in the next six months. If we do add anything in this space, it will be in the form of high level tasks and not specifically in the form of low level techniques like LSTMs. 
I am closing this issue. Please feel free to reopen if you have more questions.
