### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by lyyblnl** [dotnet/machinelearning#5391]
### System information

- **.NET Version (eg., dotnet --info)**: 

### Issue
- **The program runtime class is not created,Can I use a dynamic collection to build a DataView.**

### Source code / logs
```C#
var values = ConvertJson.DeserializeObject<List<Dictionary<string,string>>>(str);
MLContext mlContext = new MLContext();
var builder = new DataViewSchema.Builder();
builder.AddColumn("Id", TextDataViewType.Instance);
builder.AddColumn(columns[1], NumberDataViewType.Int32);
builder.AddColumn(columns[0], NumberDataViewType.Single);
var schema = builder.ToSchema();
IDataView dataView = mlContext.Data.LoadFromEnumerable<Dictionary<string, string>>(values, schema);
```

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by Lynx1820** [comment]
Hi @lyyblnl, I don't think I quite understand your question. Does this help [ml-net-makepredictionfunction-dynamic-type](https://stackoverflow.com/questions/53837654/ml-net-makepredictionfunction-dynamic-type)? If not, could you elaborate on what you're trying to accomplish and what's your pipeline?

**Comment by lyyblnl** [comment]
Hi @Lynx1820 ,Thanks for your help. I have solved the problem.
