### ISSUE TITLE
Can't use GPU

### ISSUE THREAD

**Issue by kikipoulet** [dotnet/machinelearning#5397]
### System information

- Windows 10
- .NET Core 3.1

### Issue

- I tried to run the "DeepLearning_ImageClassification_Training" solution from the samples, the ImageClassification.Train project. Everything worked fine as expected. Then I tried to use the my GPU (Nvidia Quadro P400) to run it again. I did : 
     -> uninstalled the "SciSharp.TensorFlow.Redist Nuget" Package and installed the "Windows-GPU" one.
     -> Installed CUDA V10 (cuda_10.0.130_411.31_win10) and Cudnn (cudnn-10.0-windows10-x64-v7.6.4.38) and put the cudnn dll in the CUDA bin folder.

- The project still run correctly but does not use the Nvidia GPU at all and use the CPU.

### Source code / logs

Literally this project : https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ImageClassification_Training/ImageClassification.Train

Thanks for your help ! :)

**Comment by harishsk** [comment]
The version of TF.NET that ML.NET depends on, uses CUDA 10.0 which isn't supported by NVidia anymore. We are in the process of figuring out an upgrade path to Cuda 10.1 but in the meanwhile, please update your GPU drivers after installing CUDA 10.0.

**Comment by harishsk** [comment]
Also please see additional instructions here: https://github.com/dotnet/machinelearning-modelbuilder/issues/998

**Comment by kikipoulet** [comment]
Thanks for your reply ! 
So I followed your link and instructions. To try if my GPU works, I tried to use the "model builder extension" in Visual Studio, and I'm glad to say that it works !
![snipping](https://user-images.githubusercontent.com/19242427/93181293-95b33380-f738-11ea-9ca6-bc897e83f071.PNG)

Then the extension generates some code that I tried to run with the GPU. So I changed the Nuget packages : 
![snipping3](https://user-images.githubusercontent.com/19242427/93181420-bc716a00-f738-11ea-87ad-3a4f87582024.PNG)

And then I tried to run the generated code (in a simple loop of 100 predictions to make it run longer) but it come back on CPU and doesn't use the GPU anymore 
![snipping2](https://user-images.githubusercontent.com/19242427/93181668-00646f00-f739-11ea-89c4-20e813ed964c.PNG)
! 

What am I doing wrong ? 
Thanks for your time !

**Comment by harishsk** [comment]
Hi @kikipoulet Are both cases from the code generated from the Model Builder wizard? Can you please share the code differences between the case that works and the case that doesn't work?

**Comment by harishsk** [comment]
Hi @kikipoulet It looks like you may have updated your `Scisharp.Tensorflow.Redist-Windows-GPU` package as well. Can you please retain the version of that to the original codegen-ed version?

**Comment by harishsk** [comment]
Hi @kikipoulet Please re-activate the issue if the above doesn't answer your questions.
