### ISSUE TITLE
Plan for F# bug and testing

### ISSUE THREAD

**Issue by dsyme** [dotnet/machinelearning#540]
I've been asked to fix some issues related to F# in this repo, especially #180. This is a planning note regarding this work.

TODO:

* [ ] Add one F# compiled-project "smoke test" under `tests\FSharpProjects\SmokeTest` based around those done by @isaacabraham, see https://github.com/isaacabraham/ml-test-experiment.  

   * This test will run under CI on both Windows and Linux and only require .NET Core

* [ ] Add one F# scripting "smoke test" under `tests\FSharpScripting\SmokeTest` based around those done by @isaacabraham, see https://github.com/isaacabraham/ml-test-experiment.  

   * This test will run under CI on Windows. It will currently require .NET Framework or Mono.  

When futher API updates and re-designs are made it is up to the person doing the re-design to adjust these tests :) Ask for help if you need it, but the F# code will be simple and I'm sure all contributors are capable of adjusting trivial F# code, F# is dead simple to learn.

Then, when [this bug](https://github.com/dotnet/machinelearning/issues/180) is fixed, a test will be added to both tests\FSharpScripting\SmokeTest and tests\FSharpProjects\SmokeTest.

Separately I will propose updates for documentation for F#, and we can later look at more comprehensive documentation, samples and testing.

**Comment by dsyme** [comment]
Please Label with "F#", thanks

**Comment by asthana86** [comment]
LGTM

Adding @TomFinley and @shauheen

**Comment by dsyme** [comment]
I've submitted #600 and #616 (the latter WIP) so I will close this for now.

I decided not to submit a test for running ML.NET and F# Interactive until F# scripting for .NET Core is available, since this whole technology is very much oriented towards .NET Core.  However the test in #600 can be run manually with .NET Framework F# Scripting.
