### ISSUE TITLE
SrCnnEntireAnomalyDetectorOptions should support Non-seasonal cases

### ISSUE THREAD

**Issue by lisahua** [dotnet/machinelearning#5410]
### System information

- **OS version/distro**: .Net 4.8
- **.NET Version (eg., dotnet --info)**: Ml.Net 1.5.2

### Issue

- **What did you do?** Try to apply detect anomaly
- **What happened?** We expect to use the SrCnnEntireAnomalyDetectorOptions for non-seasonal data, yet it gives an assertion that period cannot be negative. Shouldn't we gracefully ignore deseasonalize if period < 0?

- **What did you expect?**  SrCnnEntireAnomalyDetectorOptions should support Non-seasonal cases

### Source code / logs

We expect to use the SrCnnEntireAnomalyDetectorOptions for non-seasonal data, yet it gives an assertion that period cannot be negative. **Shouldn't we gracefully ignore deseasonalize if period < 0?** 

```
       seasonalPeriod = mlContext.AnomalyDetection.DetectSeasonality(..)
            var anomalyDetectorOptions = new SrCnnEntireAnomalyDetectorOptions()
            {
                DetectMode = detectMode,
                Threshold = adjustThreshold,
                Sensitivity = this.inputMetadata.Sensitivity,
                Period =seasonalPeriod < 0  ? 0 : seasonalPeriod,
            };
```

**Comment by antoniovs1029** [comment]
Hi, @lisahua . Will your team take care of this issue? Thanks.

**Comment by guinao** [comment]
For non-seasonal data, set period to 0 would be just fine. Inside SrCnnEntireAnomalyDetector, there are separate logic to handle cases of period = 0 and period > 0. Please check  https://github.com/dotnet/machinelearning/blob/4960f9de83351b25874e58d1ca504c9a32aa1112/src/Microsoft.ML.TimeSeries/SrCnnEntireAnomalyDetector.cs#L458 for details.

**Comment by lisahua** [comment]
Thanks Yuanxiang.

**Comment by lisahua** [comment]
Confirmed with author for the workaround.
