### ISSUE TITLE
Issue with Graph.def invalid for a tensorflow model

### ISSUE THREAD

**Issue by eventxplore** [dotnet/machinelearning#5412]
Windows 10 latest
.NET Core 3.1

Opening savedmodel tensorflow pb file gives invalid Graph.def message.

The pb file is possible to open and view with this site:
https://lutzroeder.github.io/netron/

It warns about huge model and it is huge with a complex network.

When opening the file in ML.NET:
LoadTensorFlowModel(<path>)  I get the message.

I have opened another pb file ok so my environment is setup ok by this.

I would like to get more info about what is wrong with the model file, to verify it before it is opened.

Is there a verification tool or specification that could be matched to check the pb file, Thanks?

**Comment by eventxplore** [comment]
Rename the model file from .log to .pb.  This is huge but only 914kb.
[saved_model.log](https://github.com/dotnet/machinelearning/files/5293725/saved_model.log)

The other file is 52622 kb and used in example project.

**Comment by frank-dong-ms** [comment]
@eventxplore thanks for using ML.NET. I need several clarifications first to go into details of this issue:
1. How was your model file (saved_model.pb) generated, is it generated from ML.NET or other place? 
2. What is the model dong? Image classification?
3. We only support load frozen TensorFlow model, check below posts for more details:
https://devblogs.microsoft.com/cesardelatorre/run-with-ml-net-c-code-a-tensorflow-model-exported-from-azure-cognitive-services-custom-vision/
https://www.dlology.com/blog/how-to-convert-trained-keras-model-to-tensorflow-and-make-prediction/

**Comment by eventxplore** [comment]
Thanks for your prompt response:
1. Yes the model was generated in another tool, yet nondisclosed.
2. I setup a simple model for image classification with two classes just to confirm the error.
3. As I know the model is frozen.

In general this problem is interesting and would like to have info on all expectations and constraints that must be fulfilled to
not get this kind of error message from ML.net.  I would like to put together a third party pb model validator tool if not yet existing to confirm the model is valid for use in ML.net.

**Comment by frank-dong-ms** [comment]
@eventxplore are you sure the shared model file is frozen pb model file? I tried to use tensorflow sharp and tensorflow in python to load the model and both failed. Please check below post to get the right frozen model file:
https://github.com/tensorflow/models/issues/2133

**Comment by eventxplore** [comment]
I agree, I will have a look into that once more.  Most probably not frozen.  I did not find support for freezing a model in ML.net so I will look into that with some python .NET port.

**Comment by frank-dong-ms** [comment]
Yes, ML.NET only support load frozen tensorflow model but not to freeze a model. Please make sure your model is frozen, if you still face issue loading model with ML.NET, please let us know.

**Comment by frank-dong-ms** [comment]
I will close this issue for now, @eventxplore feel free to reopen it if you found issue loading frozen model from ML.NET, thanks.
