### ISSUE TITLE
Options for running ML.NET in Hyper-V

### ISSUE THREAD

**Issue by Anachostic** [dotnet/machinelearning#5421]
### System information

- **OS version/distro**: Windows 10 64-bit in Hyper-V
- **.NET Version (eg., dotnet --info)**: 4.8/Standard 2.0

### Issue

I have an application utilizing ML.NET image classification that works excellent on Windows 10 desktop, but does not load when run in a Hyper-V virtual machine.

The execution stops during initialization and 4 inner-exceptions-deep is the error:

Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.
Unable to load DLL 'tensorflow': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

I have read other postings online that this might have to do with the lack of GPU capabilities in the default Hyper-V video driver.  Does anyone have any workarounds or solutions for this?

**Comment by michaelgsharp** [comment]
Are you deploying the model to a Hyper-V virtual machine? Or trying to train there as well?

**Comment by Anachostic** [comment]
Yes, it is a existing model.  There is no training being done.  According to some logging I added, the exception happens on the line:

_Context.Model.Load(modelPath, schema)

Where _Context has been successfully instantiated.  The modelPath is on a mapped network drive, in the same folder as all the binaries.  However, I have tried copied everything to the VM's local drive and that doesn't change anything.

**Comment by michaelgsharp** [comment]
When you copy everything locally is the exception still with loading the model? Is tensorflow installed on the machine? How did you get the binaries on the hyper vm machine?

**Comment by Anachostic** [comment]
Your questions led me to believe this might be an environmental issue.  I copied the bin folder to another physical machine and after running the exe, got the same error.  So, something is different between my dev machine and a standard windows build that the bin folder is not compensating for.  The possibilities feel endless.

I looked through my install history at the time I did my original development with ML.NET and I didn't see anything out of the ordinary that was installed.  On my VM, I installed Python and used pip to install tensorflow.  Same error.  I do not know what other system dependencies need to be installed.

To answer your questions, the exception is still happening when loading the model.  Tensorflow is now installed on the computer and tensorflow.dll is present in the bin folder.  I can simply copy the bin folder to the desktop of the VM and run the exe from there or I can map a drive to the VM host and run the exe from there.  The result is the same.

**Comment by Anachostic** [comment]
I downloaded Dependencies (a dependency checker) and checked Tensorflow.dll to see what it wanted.  It turned out that it wanted the Microsoft Visual C++ 2015 runtime.  Downloaded and installed that and I do not get any error.  Obviously that runtime is something that is installed with Visual Studio at some point.

Thank you for your assistance and pointing me in the right direction!
