### ISSUE TITLE
Exception while inferencing ML.NET ONNX model that uses TextFeatures

### ISSUE THREAD

**Issue by ppampati** [dotnet/machinelearning#5426]
[###](url) System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**:  .NET Core 3.1

### Issue

- **What did you do?
     Trained a Fast tree model on text data.
     Saved the trained model to ONNX format
     Load the ONNX model and run Prediction
- **What happened?
      Prediction code threw an exception and application crashed.
- **What did you expect?**
      Prediction code to return score and predict label.
Sample code is attached
[MLNetONNXSample.zip](https://github.com/dotnet/machinelearning/files/5357598/MLNetONNXSample.zip)

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by Lynx1820** [comment]
This issue was resolved with PR [#5435](https://github.com/dotnet/machinelearning/pull/5435).
