### ISSUE TITLE
object detection on local ML

### ISSUE THREAD

**Issue by zjdandy99ge** [dotnet/machinelearning#5427]
there is object detect ml on Azure， I want to do that on local, anyone can give me some advice or demo?

thanks a  lot.

**Comment by justinormont** [comment]
There are two examples of using pre-trained object detection models in the sample repo: https://github.com/dotnet/machinelearning-samples/

These use a pre-trained ONNX model (not re-fit to your data). Docs: https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-onnx

**Comment by frank-dong-ms** [comment]
@zjdandy99ge Justin already give suggestions for your questions, close this issue. Feel free to reopen if you have any more questions.
