### ISSUE TITLE
System.InvalidOperationException: 'LightGBM Error, code is -1

### ISSUE THREAD

**Issue by gharibkhani** [dotnet/machinelearning#5431]
- Tested on Windows 10 and Server 2019:
- .NET 4.7: 

**Issue**
It crashes in this line 

- var model = pipeline.Fit(trainData);

- I get this error: System.InvalidOperationException: 'LightGBM Error, code is -1, error message is 'Unknown importance type: only support split=0 and gain=1'.'

This error can be reproduced by an example. I just used the example in docs.microsoft.com and able to reproduce it.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.lightgbmextensions.lightgbm?view=ml-dotnet

I created a console app and you can access it from the link below:

https://drive.google.com/drive/folders/1-wc04CM75-IGoxjRAniDuhqI-zrHTWwM?usp=sharing

I talked to the LightGBM team and they mentioned this issue exists in .Net code and not theirs.

**Comment by gharibkhani** [comment]
@Lynx1820 would you please look at this and let me know if there is any plan to fix this issue.

**Comment by mstfbl** [comment]
Hi @gharibkhani ,

Thank you for opening this Issue. I replicated the LightGBM code sample you linked in a fresh new .NET Console App project, and successfully ran the example given. I did not see any failures on the `var model = pipeline.Fit(trainData);` you said. I installed the `Microsoft.ML (1.5.2)` and `Microsoft.ML.LightGbm (1.5.2)` NuGet packages. I believe you may not have the latest `Microsoft.ML` and/or `Microsoft.ML.LightGbm` NuGet packages installed, please confirm you have v1.5.2 for both.

I have zipped the working repro I mention above here. Please unzip the repro I've attach and let me know whether or not it works.
[Issue5431.zip](https://github.com/dotnet/machinelearning/files/5405936/Issue5431.zip)

**Comment by gharibkhani** [comment]
I updated the comment. I am using Microsoft.ML (1.5.2) and Microsoft.ML.LightGbm (3.0.0)
