### ISSUE TITLE
Incompatible package sign on Ml 1.5.2 in Visual Studio

### ISSUE THREAD

**Issue by RaoHammas** [dotnet/machinelearning#5442]
### System information

- **OS version/distro**: Windows 10 Pro 1909 Build: 18363.1139
- **.NET Version (eg., dotnet --info)**: 3.1.401

### Issue

- **What did you do?**
Created new core console project and added `ML.Net` version `1.5.2` nuget package.
- **What happened?**
I'm seeing yellow incompatible package sign on package in dependency tree. Although everything works just fine.
- **What did you expect?**
Obviously, it shouldn't show this sign.
### Source code / logs

![image](https://user-images.githubusercontent.com/16499626/96347709-fb3e6b00-10bc-11eb-9878-c8d13dd781ca.png)

**Comment by mstfbl** [comment]
Hi @RaoHammas ,

I replicated the issue you've shared locally, where I made an empty .NET core console project, and added the `Microsoft.ML` v1.5.2 NuGet package. I have attached a screenshot below. I am not seeing the yellow incompatible package sign. You can also see the relavent .NET Core SDK and OS version specifications.

![bug_5442](https://user-images.githubusercontent.com/5262061/96526516-a886bf80-1232-11eb-8889-aa1421b0f813.PNG)

Can you please zip up and share your entire repository where you are getting this yellow sign? I would like to see if I am getting it locally too.

**Comment by RaoHammas** [comment]
Oh. Ok I'll share my repo.

**Comment by RaoHammas** [comment]
@mstfbl hey Mustafa. I actually restarted Visual Studio and it seems issue is gone now. When i created new project as above told the Yellow sign was shown. But now after restart it's no more. So, I guess some VS related issue it was.

**Comment by mstfbl** [comment]
Hi @RaoHammas ,

Good to hear! Thank you for letting us know. Closing this issue.
