### ISSUE TITLE
Unable to load DLL 'tensorflow' or one of its dependencies

### ISSUE THREAD

**Issue by Gaopeng-Bai** [dotnet/machinelearning#5449]
### System information

- **OS version/distro**: Azure windows app service
- **.NET Version (eg., dotnet --info)**:  3.1 
- **ASP.NET Version (eg., dotnet --info)**:  3.1.7
#### Packages
- Microsoft.ML                          1.5.2
- Microsoft.ML.ImageAnalytics 1.5.2
- Microsoft.ML.Vision               1.5.2
- Microsoft.ML.TensorFlow        1.5.2

- SciSharp.TensorFlow.Redist     2.3.0
- TensorFlow.NET                       0.21.0

### Issue
I create a web application with ML.Net. Everything works on my local machine,  But the Azure server catch the error when I debugged on app service.

`System.FormatException: Tensorflow exception triggered while loading model. ---> System.DllNotFoundException: Unable to load DLL 'tensorflow' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Tensorflow.c_api.TF_NewGraph()
   at Tensorflow.Graph..ctor()`

- **What did you do?**
Deploy a web application with ML.NET to azure.
- **What happened?**
System.DllNotFoundException: Unable to load DLL 'tensorflow' or one of its dependencies
- **What did you expect?**
The program can run the same as local.

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by mstfbl** [comment]
Hi @Gaopeng-Bai ,

Can you please share a repro of your Visual Studio Project where you're seeing this exception? That way we can see which exact packages are installed and whether or not they're working correctly. Can you please also share info on the Windows Azure Instance? Thanks.

**Comment by mstfbl** [comment]
Closing this issue for now as repro has not yet been shared. @Gaopeng-Bai please feel free to share your repro in this issue. Thanks.

**Comment by Gaopeng-Bai** [comment]
@mstfbl Sorry for the late reply. I don't allow to share this repository, but there may be compromised. 
Could you please tell me what kind of policy do you have?  I may get permission for this.

**Comment by Gaopeng-Bai** [comment]
@mstfbl  Thank you very much for your time. The problem is solved, I simply set the server 32-bit to 64.
