### ISSUE TITLE
how to use FastTextWikipedia300D

### ISSUE THREAD

**Issue by WEMAPP** [dotnet/machinelearning#5450]
Hi if I wanted to use a pre-trained file, for example Wiki word vectors by fasttext is it possible? and how?

**Comment by mstfbl** [comment]
Hi @WEMAPP ,

Thank you for your question. It is indeed possible to use pre-trained models for word-embedding tasks. Please take a look here:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.text.wordembeddingestimator.pretrainedmodelkind?view=ml-dotnet

To use FastTextWikipedia300D, you would do: `WordEmbeddingEstimator.PretrainedModelKind.FastTextWikipedia300D`.

**Comment by WEMAPP** [comment]
thanks for the reply, i can't understand how to specify the language
thank you
