### ISSUE TITLE
Parameter mapping betbeen python Booster model and ML.Trainers.LightGbm.GradientBooster object

### ISSUE THREAD

**Issue by galeese** [dotnet/machinelearning#5451]
### System information

- **OS version/distro**: Win10
- **.NET Version (eg., dotnet --info)**: 3.1.3

### Issue

- **What did you do?** I trained a model within python LGBM API via Byessian optimization
- **What happened?** I've received from the optimization a model file with the defined parameters. I want to train this optimized model within the ML.NET environment. The obstacle is: a confusion, that I can't make confindent matching between  parameters presented on the page https://lightgbm.readthedocs.io/en/latest/Parameters.html  and the properties of  the  ML.Trainers.LightGbm.GradientBooster object:
 
                    FeatureFraction  
                    L1Regularization  
                    L2Regularization  
                    MaximumTreeDepth 
                    MinimumChildWeight 
                    MinimumSplitGain  
                    SubsampleFraction   
                    SubsampleFrequency 
 
- **What did you expect?** So below is presented my matching between python parameters and GradientBooster object, I want you to verify whether my matching is correct , and point out how is the "SubsampleFraction " named in python parameters.

### Source code / logs

            var options = new LightGbmBinaryTrainer.Options
            {
                Booster = new Microsoft.ML.Trainers.LightGbm.GradientBooster.Options   
                {
                    FeatureFraction = 0.855937, //   -- > feature_fraction 
                    L1Regularization = 0.973817, // ---> lambda_l1 
                    L2Regularization = 2.27,    // ---> lambda_l2
                    MaximumTreeDepth = 8, //   -- > max_depth 
                    MinimumChildWeight = 17.9015, //    -- > min_sum_hessian_in_leaf 
                    MinimumSplitGain = 0.076047,  //    -- >  min_gain_to_split
                    SubsampleFraction =1,  // ???? can't determine the analoguos within https://lightgbm.readthedocs.io/en/latest/Parameters.html 
                    SubsampleFrequency = 10, //     -- > bagging_fraction
                }
            };

The criterion of the successful answer is: 
The two models give the same classification probabilities  trained in python and with GradientBooster object. Wen you present me the correct matching of the parameters, i run the two models, and check the output difference. 
Thank you!

**Comment by justinormont** [comment]
The ML․NET parameter names are mapped to LightGBM using a mapping table:
https://github.com/dotnet/machinelearning/blob/c5a18ef512ecf880eeba41483e4e300c9e0cf8e7/src/Microsoft.ML.LightGbm/LightGbmArguments.cs#L37-L46

There's additional mappings for specific components:
https://github.com/dotnet/machinelearning/blob/c5a18ef512ecf880eeba41483e4e300c9e0cf8e7/src/Microsoft.ML.LightGbm/LightGbmArguments.cs#L251-L253

https://github.com/dotnet/machinelearning/blob/770327a2074d8ab39a023bc9252a713a3afa8293/src/Microsoft.ML.LightGbm/LightGbmTrainerBase.cs#L52-L60

https://github.com/dotnet/machinelearning/blob/f87a3bbd8adb12934dae0a0060813ce9b7500664/src/Microsoft.ML.LightGbm/LightGbmRankingTrainer.cs#L151

https://github.com/dotnet/machinelearning/blob/4ec2f9c6dc08e8079338546b31f260d0715db45c/src/Microsoft.ML.LightGbm/LightGbmBinaryTrainer.cs#L176

Unlisted parameters use an `UpperCamelCase` to `snake_case` conversion: (e.g. `FeatureFraction` to `feature_fraction`)
https://github.com/dotnet/machinelearning/blob/212b5dfc3ba9341ea73867cdc495dbcada8ab660/src/Microsoft.ML.LightGbm/WrappedLightGbmInterface.cs#L258-L282

Full list of LightGBM parameters: 
https://lightgbm.readthedocs.io/en/latest/Parameters.html

**Comment by galeese** [comment]
thank you! have constructed the appropriate mapping due to your help

**Comment by justinormont** [comment]
@galeese: Quite welcome. I'm always happy to assist.

**Comment by galeese** [comment]
Then will you   kindly consider my next error described in the ticket: https://github.com/dotnet/machinelearning/issues/5452 Justin??
I can demonstrate you my screen via skype so that you do not spend your  time trying to reproduce the training model  and the error.

**Comment by mstfbl** [comment]
Thank you @justinormont for resolving this issue.
