### ISSUE TITLE
Error while loading yolov4 model 

### ISSUE THREAD

**Issue by karanjakhar** [dotnet/machinelearning#5458]
![Screenshot from 2020-10-27 00-56-53](https://user-images.githubusercontent.com/29913676/97219090-84594e80-17ef-11eb-923e-7e9dfda0d3f7.png)
I am new to this. I have experience with Python but with this, I have no idea. Please help. What is this error indicating?

**Comment by Lynx1820** [comment]
Hi @karanjakhar, 

Are you able to provide your code/data? I'm not sure what's wrong based on the error.

**Comment by karanjakhar** [comment]
https://github.com/jwood803/MLNetExamples/tree/master/MLNetExamples/CustomVisionOnnx 
I am using this example but with yolov4 model converted to onnx.

**Comment by karanjakhar** [comment]
model onnx file:
https://drive.google.com/file/d/1pzC7RYDqMrJDmYjZp_uMIJfLZpWdOERU/view?usp=sharing

**Comment by Lynx1820** [comment]
@karanjakhar, 

I ran the example without any problems. Did you change anything? What is your OS and machine?  Were you using a GPU? I would open this bug in [Onnxruntime](https://github.com/microsoft/onnxruntime), as your issue is likely coming from that library.

**Comment by karanjakhar** [comment]
The example run without any problem but when I use my own model (shared above) then I encounter this error.

**Comment by karanjakhar** [comment]
> model onnx file:
> https://drive.google.com/file/d/1pzC7RYDqMrJDmYjZp_uMIJfLZpWdOERU/view?usp=sharing

Did you use this model?

**Comment by Lynx1820** [comment]
Hi @karanjakhar, this issue seems related to [#2474](https://github.com/microsoft/onnxruntime/issues/2474). Could you open this issue there. I'm checking whether this project works with a previous Onnxruntime version.

**Comment by Lynx1820** [comment]
Hi @karanjakhar, after upgrading my Microsoft.ML nuggets from 1.4 to 1.5.2, the error went away. Can you try that?

**Comment by karanjakhar** [comment]
Thankyou so much @Lynx1820 
Upgrading worked. No error now.
Thank you :)
