### ISSUE TITLE
Bayesian Optimization with Gaussian Processes

### ISSUE THREAD

**Issue by pavel-rev** [dotnet/machinelearning#5465]
Are there any implementations of aforementioned methods with "same process space" interface to C# by Microsoft or Microsoft sponsored project or similar? Basically I am interested in anything solid/more or less ready to be used "out of the box". Tree-based regression under the hood will also work.

**Comment by Lynx1820** [comment]
Hi @pavel-rev, do you need this for hyper-parameter tuning? We have an automated ml API, which you can learn more about [here](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/how-to-use-the-automl-api).

**Comment by pavelnyaga** [comment]
@Lynx1820 this is for expensive function optimization.

**Comment by pavel-rev** [comment]
this is for optimization of expensive-to-compute function.

**Comment by Lynx1820** [comment]
Hi @pavel-rev, 

Checkout [fastforestregressiontrainer](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.fasttree.fastforestregressiontrainer?view=ml-dotnet). You can find the rest of the transformers we support [here. ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml?view=ml-dotnet)

**Comment by Lynx1820** [comment]
Closing this issue. Feel free to reopen if you have follow up questions.
