### ISSUE TITLE
No multinomial logistic regression algorithm

### ISSUE THREAD

**Issue by liugaocn** [dotnet/machinelearning#5470]
I didn't find multinomial logistic regression algorithm. Is it with a different name?

Multinomial logistic regression is used to predict probabilities for more than two classes.

**Comment by harishsk** [comment]
Hi @liugaocn 
You can use [LbfgsMaximumEntropy](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.standardtrainerscatalog.lbfgsmaximumentropy?view=ml-dotnet) for multi class logistic regression.

**Comment by harishsk** [comment]
I hope that answers your question. Please feel free to reopen the issue if you have more questions.

**Comment by jigarhshah17** [comment]
So, for 25 + regression model and I have need to 25+ regression prediction engine exe so adding new model I have create one more exe am I right?

**Comment by harishsk** [comment]
You can have multiple prediction engines in the same executable.
