### ISSUE TITLE
Is it possible to convert a ml.net model (.zip) to ONNX or tensorflow model?

### ISSUE THREAD

**Issue by fuomag9** [dotnet/machinelearning#5473]
### System information

- **Win 10 10.0.19041**:
- **.NET Version 3.1.402**: 

### Issue

Is it possible to convert a ml.net model (.zip) to ONNX or tensorflow model? I've found various APIs but they were either removed or I didn't know how to make them work.

**Comment by harishsk** [comment]
Yes, you can convert an ML.NET model to ONNX. [This sample](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/ModelOperations/OnnxConversion.cs) demonstrates how to do it.
