### ISSUE TITLE
How to use neural network in ML.NET?

### ISSUE THREAD

**Issue by xsoheilalizadeh** [dotnet/machinelearning#5483]
Is there any concept in ML.NET to imply the NN?

**Comment by antoniovs1029** [comment]
ML.NET doesn't have any component to create neural networks from scratch.

But if you already have a pretrained NN in tensorflow or onnx format, then ML.NET has components to run those. Also in ML.NET, the ImageClassificationTrainer uses pretrained NNs on the background, and allows for its fine tuning.

You can learn more about these components here:
[Run tensorflow model](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ImageClassification_TensorFlow)
[Run onnx model](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx)
[Run ImageClassificationTrainer](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ImageClassification_Training)
