### ISSUE TITLE
Unable to load DLL 'CpuMathNative': The specified module could not be found

### ISSUE THREAD

**Issue by BalsamIbrahim** [dotnet/machinelearning#5495]
salam all
I face this problem when I use Microsoft.ML to create clustering 
I hope to help me 
System.DllNotFoundException: 'Unable to load DLL 'CpuMathNative': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'
thank you 
![image](https://user-images.githubusercontent.com/34779906/99539707-39c68e80-29b7-11eb-8e28-88fdf3eed323.png)

**Comment by frank-dong-ms** [comment]
@BalsamIbrahim Thanks for using ML.NET, could you please provide a repro project so we can investigate further?

**Comment by BalsamIbrahim** [comment]
@frank-dong-ms  
**project type :** Class Library
**Target :** 4.6.1
**what I do :** I have list from Latitude and longitude and I need do clustering for them in my plugin

**Comment by BalsamIbrahim** [comment]
this my code 
        public void cluster (List<Entity> prescriptions , int total_seconds_allowed, int iteration)
        {
            try
            {
                var max = prescriptions.Count / 3;
                max = total_seconds_allowed > 3600 ? max * 2 : max;
                var max_clusters = max + iteration;
                max_clusters = max_clusters > prescriptions.Count ? prescriptions.Count : max_clusters;

                var listpoints = new List<InputDate>();
               //prescriptions.ForEach(item => listpoints.Add( new InputDate { Feature1 =item.GetAttributeValue<decimal>("new_latitude"), Feature2 = item.GetAttributeValue<decimal>("new_longitude") }));
               // listpoints = listpoints.Where(c => c.Feature1 != 0 && c.Feature2 != 0).ToList();
              
                List<InputDate> pointsValues = prescriptions
                    .Select(value => { return new InputDate(value.GetAttributeValue<decimal>("new_longitude"), value.GetAttributeValue<decimal>("new_latitude")); })
                    .ToList();
                var mlContext = new MLContext();
       
                IDataView dataView = mlContext.Data.LoadFromEnumerable(pointsValues);
                var options = new KMeansTrainer.Options
                {
                    NumberOfClusters = max_clusters,
                    OptimizationTolerance = 1e-6f,
                    NumberOfThreads = 1,InitializationAlgorithm = KMeansTrainer.InitializationAlgorithm.Random,FeatureColumnName = "Features"  
                };
                var pipeline = mlContext.Transforms.Concatenate(
                    "Features",
                    "Latitude", 
                    "Longitude")
                    .Append(mlContext.Clustering.Trainers.KMeans(options));

                var model = pipeline.Fit(dataView);
            }
            catch (Exception ex)
            {

                throw;
            }
            

        }
        public class InputDate
        {
            [LoadColumn(0)]
            public float Latitude;
            [LoadColumn(1)]
            public float Longitude;
            [LoadColumn(2)]
            public string Label;
            public InputDate(decimal longitude, decimal latitude)
            {
                Latitude = Convert.ToSingle(latitude) ;
                Longitude = Convert.ToSingle(longitude);
            }
        }

**Comment by frank-dong-ms** [comment]
@BalsamIbrahim Thanks, could you please provide a complete repro project or solution, and your repro steps? Previous code piece is not enough for me to investigate the issue. Also, the missing DLL 'CpuMathNative' is coming from nuget package 'Microsoft.ML.CpuMath', you can find this dll under path 'runtimes\win-x64\nativeassets\netstandard2.0\CpuMathNative.dll', could you verify if the nuget package contains that dll?

**Comment by BalsamIbrahim** [comment]
okay because I speak Arabic not English so please can you afford me ?? 
I'll upload some picture 
references 
![image](https://user-images.githubusercontent.com/34779906/99578479-95a80c00-29e5-11eb-9f94-44230d4c3d41.png)
packages 
![image](https://user-images.githubusercontent.com/34779906/99578562-ace6f980-29e5-11eb-93b2-27b4b030fba1.png)


I am now briefly clarifying the project
First I have a group of packages for people
They are receive through the driver
Objective: To give the driver the best route to deliver all packages to people
From points I create the best path using the microsoft.ML

**Comment by frank-dong-ms** [comment]
@BalsamIbrahim  are you able to provide the whole/complete project?

**Comment by BalsamIbrahim** [comment]
@frank-dong-ms YES I HAVE COMPLETE PROJECT 
I'LL COMPRESS PROJECT AND UPLOAD IT

**Comment by BalsamIbrahim** [comment]
[Plugin.zip](https://github.com/dotnet/machinelearning/files/5563138/Plugin.zip)

class name Scheduale

**Comment by frank-dong-ms** [comment]
@BalsamIbrahim Thanks I can reproduce your issue and I will start to work on a fix.

**Comment by frank-dong-ms** [comment]
@BalsamIbrahim If possible you can use dotnet core for your class library project Plugin and your issue will go away if you use dotnet core.

**Comment by BalsamIbrahim** [comment]
okay, I try use .net core but I face problem in this 
![image](https://user-images.githubusercontent.com/34779906/99606854-37921d80-2a13-11eb-874d-e21c7626a4fa.png)
this plugins use frame work

**Comment by frank-dong-ms** [comment]
@BalsamIbrahim is it possible to change the Plugin project to use .net core?

**Comment by frank-dong-ms** [comment]
@BalsamIbrahim another work around is to add package reference of Microsoft.ML.CpuMath to the project consuming the plugin project and set <PlatformTarget>x64</PlatformTarget> for both Debug and Release:
https://github.com/dotnet/machinelearning/issues/4870#issuecomment-599625498

**Comment by BalsamIbrahim** [comment]
> @BalsamIbrahim another work around is to add package reference of Microsoft.ML.CpuMath to the project consuming the plugin project and set x64 for both Debug and Release:
> [#4870 (comment)](https://github.com/dotnet/machinelearning/issues/4870#issuecomment-599625498)

it's work thanks

**Comment by frank-dong-ms** [comment]
Close this issue now, feel free to reopen if any necessary.
