### ISSUE TITLE
Score column is missing. Parameter name ScoreColumn.

### ISSUE THREAD

**Issue by StanislavChankov** [dotnet/machinelearning#551]
### Issue
Throws an exception 
- **What did you do?**
![image](https://user-images.githubusercontent.com/35253870/42866807-475cd2a8-8a76-11e8-9509-d8d147534fa7.png)

- **What happened?**
![image](https://user-images.githubusercontent.com/35253870/42866529-6e75a5d2-8a75-11e8-8aaf-b4a609affc96.png)

- **What did you expect?**
To train without errors or warnings that I have.
### Source code / logs
**ML.NET Version: 0.3.0**
![image](https://user-images.githubusercontent.com/35253870/42866497-59a16876-8a75-11e8-80c8-dfe0ca695d56.png)
![image](https://user-images.githubusercontent.com/35253870/42866716-0f85de24-8a76-11e8-8da4-8cd233d3f7d3.png)

![image](https://user-images.githubusercontent.com/35253870/42866191-96d304a8-8a74-11e8-99da-4eb762792eb0.png)

**Comment by shauheen** [comment]
Can you please confirm what is the size of your data, how many rows do you have? what is the structure of your data? do you have enough samples per tree? etc.

**Comment by StanislavChankov** [comment]
Yes, I am trying only with 2-3 samples, but I think that the exception comes by another reason. As far as I see in the source code, the warning comes from the very less samples, but I am not understanding the exception. 
I am applying the same code as taxi fare, because I am having **float** output parameter.

**Comment by shauheen** [comment]
10 samples is still very little for a model with default parameters. (In fact for almost any model). Do you have a way to get more data?

**Comment by StanislavChankov** [comment]
Yeah, now I am trying to prepare more data. The thing that concerns me is that some of the features are of type **boolean**, but I am trying to represent them as **float** with having values only 1 and 0. Is this going to be a problem?

**Comment by Ivanidzo4ka** [comment]
We have ColumnTypeConverter which let you convert from one type to another.
Any chance you can share your model / full code(or project)?

**Comment by StanislavChankov** [comment]
Yeah, sure, here is the code. The file is **.csv**, but I change it to **.xlsx** to be able to upload it.
public static async Task<PredictionModel<GameData, GamePrediction>> TrainAsync()
        {
            var pipeline = new LearningPipeline
            {
                new TextLoader(TrainDataPath).CreateFrom<GameData>(useHeader: true, separator: ','),
                new ColumnCopier(("MoveToSide", "Label")),
                new CategoricalOneHotVectorizer(
                    "PositionId",
                    "BiggestNumberX",
                    "BiggestNumberY",
                    "SecondBiggestNumberX",
                    "SecondBiggestNumberY"),
                new ColumnConcatenator(
                    "Features",
                    "PositionId",
                    "BiggestNumberX",
                    "BiggestNumberY",
                    "SecondBiggestNumberX",
                    "SecondBiggestNumberY",
                    "TilesCount",
                    "FreePlacesCount",
                    "BiggestNumber",
                    "HasBottomMerger",
                    "HasLeftMerger",
                    "HasRightMerger"),
                new FastTreeRegressor() { NumLeaves = 5, NumTrees = 5, MinDocumentsInLeafs = 3 }
            };
            Console.WriteLine("=============== Training model ===============");
            // The pipeline is trained on the dataset that has been loaded and transformed.
            var model = pipeline.Train<GameData, GamePrediction>();

            // Saving the model as a .zip file.
            await model.WriteAsync(ModelPath);

            Console.WriteLine("=============== End training ===============");
            Console.WriteLine("The model is saved to {0}", ModelPath);

            return model;
        }

        private static void Evaluate(PredictionModel<GameData, GamePrediction> model)
        {
            // To evaluate how good the model predicts values, the model is ran against new set
            // of data (test data) that was not involved in training.
            var testData = new TextLoader(TestDataPath).CreateFrom<GameData>(useHeader: true, separator: ',');

            // BinaryClassificationEvaluator performs evaluation for Binary Classification type of ML problems.
            var evaluator = new BinaryClassificationEvaluator();

            Console.WriteLine("=============== Evaluating model ===============");

            var metrics = evaluator.Evaluate(model, testData);
            // BinaryClassificationMetrics contains the overall metrics computed by binary classification evaluators
            // The Accuracy metric gets the accuracy of a classifier which is the proportion 
            //of correct predictions in the test set.

            // The Auc metric gets the area under the ROC curve.
            // The area under the ROC curve is equal to the probability that the classifier ranks
            // a randomly chosen positive instance higher than a randomly chosen negative one
            // (assuming 'positive' ranks higher than 'negative').

            // The F1Score metric gets the classifier's F1 score.
            // The F1 score is the harmonic mean of precision and recall:
            //  2 * precision * recall / (precision + recall).

            Console.WriteLine($"Accuracy: {metrics.Accuracy:P2}");
            Console.WriteLine($"Auc: {metrics.Auc:P2}");
            Console.WriteLine($"F1Score: {metrics.F1Score:P2}");
            Console.WriteLine("=============== End evaluating ===============");
            Console.WriteLine();
        }
    }

internal class TestGameData
    {
        internal static readonly GameData Passenger = new GameData()
        {
            PositionId = 5.ToString(),
            BiggestNumberX = 1.ToString(),
            BiggestNumberY = 1.ToString(),
            SecondBiggestNumberX = 2.ToString(),
            SecondBiggestNumberY = 1.ToString(),
            TilesCount = 8f,
            FreePlacesCount = 8f,
            BiggestNumber = 64f,
            HasBottomMerger = 0f,
            HasLeftMerger = 0f,
            HasRightMerger = 0f,
            MoveToSide = 1f
        };
    }

    public class GamePrediction
    {
        [ColumnName("Score")]
        public float MoveToSide;
    }

    public class GameData
    {
        [Column("11")]
        public float MoveToSide;

        [Column("0")]
        public string PositionId;

        [Column("1")]
        public string BiggestNumberX;

        [Column("2")]
        public string BiggestNumberY;

        [Column("3")]
        public string SecondBiggestNumberX;

        [Column("4")]
        public string SecondBiggestNumberY;

        [Column("5")]
        public float TilesCount;

        [Column("6")]
        public float FreePlacesCount;

        [Column("7")]
        public float BiggestNumber;

        [Column("8")]
        public float HasBottomMerger;

        [Column("9")]
        public float HasLeftMerger;

        [Column("10")]
        public float HasRightMerger;
    }

[game-train-data.xlsx](https://github.com/dotnet/machinelearning/files/2226685/game-train-data.xlsx)

**Comment by Zruty0** [comment]
@StanislavChankov, as far as I can tell, you have 10 examples in your data file, which is below the 'healthy' range for `FastTreeRegressor`. Of course, the normal behavior of the model should be to fail in this case, but it seems like it is instead 'silently failing' without producing the predictor (and therefore without producing the `Score` column).

May I suggest you to replace `FastTreeRegressor` with, say `OnlineGradientDescentRegressor`, to see if that would allow the training to complete? If it succeeds, then my hypothesis is correct: you need more training examples.

As for converting `bool` to `float`: you are doing the right thing. Our learners prefer the binary features to be encoded as floats.

**Comment by StanislavChankov** [comment]
@Zruty0 , thank you for the answer. I tried with `OnlineGradientDescentRegressor` and the training has completed, but it does in both cases.

**Comment by StanislavChankov** [comment]
@Zruty0 , @shauheen , @Ivanidzo4ka , do you guys have any new information about the issue?

**Comment by Zruty0** [comment]
Since August, we have updated the API, so this particular error message will not be thrown. I am going to close this issue. Please feel free to open another one if your scenario still doesn't work.
