### ISSUE TITLE
Is it possible to combine custom and default StopWordsRemoving options?

### ISSUE THREAD

**Issue by AniaBerthelot** [dotnet/machinelearning#5513]
Actually I use Regex to preclean text after pushing it to ML.NET but my list of stop words is growing, and also I think that if I can leverage on the StopWordsRemoving loop it will be faster to do it once rather than Regex then StopWordsRemoving (do you confirm that? If StopWordsRemoving options are combined one loop of cleaning will be done? or 2 (default and custom).
CustomStopWordsRemovingEstimator.Options StopWordsRemovingEstimator.Options

Do you provide any way to remove emojis, flags...?

Thank you for this amazing library

**Comment by justinormont** [comment]
### Speed

The `StopWordsRemoving` is rather efficient in that it minimizes the memory allocation during in the checking process. It uses a dictionary/map for checking for matching words:
https://github.com/dotnet/machinelearning/blob/7879849e9ae79f8f40bda65bf7fd7fa6131c454e/src/Microsoft.ML.Transforms/Text/StopWordsRemovingTransformer.cs#L1110-L1126

I can speculate on the speed of your regex vs. the stop word remover, but it's easy enough to test the two speeds. Generally stop word removal isn't the long bar in the ML training; hence it's likely within noise, especially if you have a [data cache](https://github.com/dotnet/machinelearning-samples/blob/109be9ed3a6634b3010e013ab140f8eb1ed2d6d0/samples/csharp/getting-started/Regression_BikeSharingDemand/BikeSharingDemand/BikeSharingDemandConsoleApp/Program.cs#L39-L41) added.

### Merging to one step
> If StopWordsRemoving options are combined one loop of cleaning will be done? or 2 (default and custom).
CustomStopWordsRemovingEstimator.Options StopWordsRemovingEstimator.Options

You can add the standard stop words to your custom list in the stop word remover to have it run once; or you can add two stop word remover steps. Or you can have your regex do all of the work by adding the standard stop words to it.

### Built-in emoji remover
> Do you provide any way to remove emojis, flags...?

The `FeaturizeText` transform has a sub-step to remove diacritics. You can remove emojis by adding to the stop word list, but it will require the emoji to be the whole word with spaces around it. You could make a stop word list of the common emojis, but the combinatorics of code points becomes large, for example `👩‍👩‍👧` is five code points of `{"👩", ZWJ, "👩", ZWJ, "👧"}`. 

For removing emojis, your regex solution would be a more clean method given the support for unicode ranges (e.g. `[\u1F300-\u1F5FF]`).

### Skipping stop word removal

As an aside, you may want to test if the stop word removal is helpful to your final metrics. In many cases, the model is pretty good about ignoring non-useful words, and may find value in keeping them.

---

> Thank you for this amazing library

Much appreciated. It's built by many hands, and I'm sure they also appreciate it.

**Comment by mstfbl** [comment]
Thanks @justinormont for your detailed answer. I'm closing this issue as sufficient suggestions have been provided.
