### ISSUE TITLE
Spelling: stopwrods

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning#5514]
Our stop word remover has a variable misspelt as `stopwrods` instead of `stopwords`:

https://github.com/dotnet/machinelearning/blob/7879849e9ae79f8f40bda65bf7fd7fa6131c454e/src/Microsoft.ML.Transforms/Text/StopWordsRemovingTransformer.cs#L987-L1015

**Comment by LeoGaunt** [comment]
I have created a pull request #5524 to fix this spelling error
