### ISSUE TITLE
When publish solution with ML.Net and Tensor Flow, Got error " ---> System.DllNotFoundException: Unable to load DLL 'tensorflow' or one of its dependencies"

### ISSUE THREAD

**Issue by gutosys** [dotnet/machinelearning#5551]
### System information

- **OS version/distro**:  Windows Server
- **.NET Version (eg., dotnet --info)**:  .Net Core 3.1

### Issue

- **What did you do?**

When publish, the application installed tensorflow.dll, Tensorflow.Keras.dll and TensorFlow.NET.dll, but this error persist.

For information the dll SciSharp.TensorFlow.Redist not installed.

- **What happened?**
- **What did you expect?**

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by mstfbl** [comment]
Hi @gutosys ,

I am a bit confused by this issue. Are you saying that your own TensorFlow .NET application installs or includes `tensorflow.dll`, `Tensorflow.Keras.dll` and `TensorFlow.NET.dll`, and you get the `System.DllNotFoundException` as you don't have the `SciSharp.TensorFlow.Redist` NuGet installed? Why don't you add the NuGet to your package, that will fix your `System.DllNotFoundException`. 

If possible, can you please share a repro of your project?

**Comment by mstfbl** [comment]
Hi @gutosys , I have not yet received a response from you on this issue. As such I will be closing it. Please feel free to respond to provide more information. Thanks.

**Comment by Tweekaz2018** [comment]
Hi.
I have same issue with using nuget package

**Comment by Tweekaz2018** [comment]
I have download another tensorflow.dll and it works. 
mb dll in nuget is broken?
