### ISSUE TITLE
IHost, IHostEnvironment and IChannel usage

### ISSUE THREAD

**Issue by minotru** [dotnet/machinelearning#5565]
Hello all,
Thank you for such a great framework as ML.NET.

I would like to know is there any documentation for IHost and Channels and how should I used them in custom algorithms.

Background:
* We have a custom algorithm on my project, I am trying to implement this algorithm as an ML.NET-compatible transformer so that it can be used inside ML.NET Pipelines.
* This algorithm is a variation of FastText/Glove with vectors stored in a database.
* I decided to investigate `WordEmbeddingExtractor` source code as a starting point for my implementation.
* And was surprised to see a lot of `Host`, `IHostEnvironment` and `Channel` calls.

There are a lot of parts like:
```cs
using (var ch = host.Start("step X"))
{
   //
}
```

Unfortunately, I have not found any comprehensive documentation on `IHost` and `IChannel`, why it is needed, how it is used.

Could you please explain in short what is `IChannel` and `IHost` and how to use them in custom code?

Thanks,
Simon

**Comment by mstfbl** [comment]
Hi @minotru ,

Thank you for reaching out, and for your kind words! You can find documentation on the [IHost ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihost?view=dotnet-plat-ext-5.0)and [IChannel ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.runtime.ichannel?view=ml-dotnet)interfaces in the links I have linked.

To my best knowledge, usage of `IHost` and `IChannel` interfaces are mostly meant for internal usage, meaning you shouldn't need to use the two interfaces for your own work. If you are looking instead to make use of the `IHostEnvironment` interface (more [info](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.runtime.ihostenvironment?view=ml-dotnet)), please note that [`MLContext`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.mlcontext?view=ml-dotnet) is derived from this interface, which is used as the common linking context for your given ML.NET usage. 

I am closing this issue, and I hope this answers your query. Feel free to pose follow-up questions and I will get back soon. Thanks.
