### ISSUE TITLE
AveragedPerceptron default iterations

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning#5568]
When changing AveragedPerceptron's default number of iterations from 1 to 10 in https://github.com/dotnet/machinelearning/pull/5258, we missed one.

The main interface continues to default to 1 iteration:
![image](https://user-images.githubusercontent.com/4080826/103145371-35943c00-46ee-11eb-99c8-3f44f0b27ee4.png)

Previous issues:
* https://github.com/dotnet/machinelearning/issues/4749
* https://github.com/dotnet/machinelearning/pull/5258

### Code location
Default is set here:
https://github.com/dotnet/machinelearning/blob/5dbfd8acac0bf798957eea122f1413209cdf07dc/src/Microsoft.ML.StandardTrainers/Standard/Online/AveragedPerceptron.cs#L172

Which originates from:
https://github.com/dotnet/machinelearning/blob/5dbfd8acac0bf798957eea122f1413209cdf07dc/src/Microsoft.ML.StandardTrainers/Standard/Online/AveragedLinear.cs#L108-L113

Which in-turn inherits its value from:
https://github.com/dotnet/machinelearning/blob/5dbfd8acac0bf798957eea122f1413209cdf07dc/src/Microsoft.ML.StandardTrainers/Standard/Online/OnlineLinear.cs#L62-L65

### Possible fix
We may want to make a new class within AveragedPerceptron to hold its overrides:
```c#
        internal class AveragedPerceptronDefault : AveragedDefault
        { 
            public const float NumberOfIterations = 10; 
        } 
```

/cc @michaelgsharp

**Comment by michaelgsharp** [comment]
I think your idea of making a new class for just the AveragedPerceptron overrides is a good idea. I'll get to this soon.
