### ISSUE TITLE
Deep learning and text recognition 

### ISSUE THREAD

**Issue by WEMAPP** [dotnet/machinelearning#5570]
Hi everyone.
could you help me understand how to use deep learning for text recognition in ml.net

**Comment by mstfbl** [comment]
Hi @WEMAPP,

ML.NET does not currently support deep learning, though we do have support for re-training an existing TensorFlow model through transfer learning. We do however have multiple samples for text recognition implementation for ML.NET. For example, check out [this ](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/MulticlassClassification_MNIST)sample in our dotnet/machinelearning-samples repo, where we demonstrate using the Stochastic Dual Coordinate Ascent algorithm on the MNIST dataset. There are also multiple tutorials online for using ML.NET for text recognition that you can check out, like [this ](https://medium.com/machinelearningadvantage/optical-character-recognition-with-c-ml-net-and-net-core-3cf71864b815)one and [this ](https://codeburst.io/handwriting-recognition-using-ml-net-3ce23a7369af)one.

I hope this can be of help!
