### ISSUE TITLE
Improve usability of AutoML column not found error

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning#5574]
Let's make the error message more actionable. 

**Error user sees:**
![image](https://user-images.githubusercontent.com/4080826/103501081-fe1a4380-4e01-11eb-9376-e41af9105813.png)

I would recommend adding similar named column(s):
```diff
- $"Provided {columnPurpose} column '{columnName}' not found in training data."
+ $"Provided {columnPurpose} column '{columnName}' not found in training data. Did you mean '{closestNamed}'."
```

For my current example, this would print: `Provided ignored column 'tagMaxTotalItem' not found in training data. Did you mean 'tagMaxTotalItems'.`

I'd recommend using Levenshtein distance to find the closest named column ([code](https://github.com/dotnet/command-line-api/blob/34a2df49f1dcf3fdc46d0c4a3daedf84b3057e05/src/System.CommandLine/Invocation/TypoCorrection.cs#L79-L146)).

**Code location:**
https://github.com/dotnet/machinelearning/blob/5dbfd8acac0bf798957eea122f1413209cdf07dc/src/Microsoft.ML.AutoML/Utils/UserInputValidationUtil.cs#L248-L252

**Background:**
It took me ~20min to debug why this error was occurring (obvious in retrospect). My column existed in the dataset, it existed in my loader function, it existed in my IDataView, ...; simply was just misspelt ("tagMaxTotalItem" instead of "tagMaxTotalItems"). 

Improving the usability of this error message will save future users' time.

**Comment by behroozbc** [comment]
hi
Is this issue solved ??

**Comment by woodya-coder** [comment]
I was going to try working on this as my first contribution to open source, but it looks already fixed to me in the code.  I don't see a test for it though.  I could add a test to confirm it.  I haven't seen any guidelines on writing tests. Are there any?

**Comment by michaelgsharp** [comment]
I dont think we have any official guidelines. I would just look at the other tests we have for AutoML and base it off of that. If you can throw the test in to an existing class that would probably be better, but if it doesn't fit anywhere than feel free to make a new test class too.

**Comment by abhinavjainn412** [comment]
We can use sequence matcher ,it compare the column typed by us with the existing columns like this-
from difflib import SequenceMatcher
s = SequenceMatcher(None, a, b)
s.ratio()
if we find s.ratio() >50 than we will print 
throw new ArgumentException($"Provided {columnPurpose} column '{columnName}' not found in training data.  And their may be spelling mistake typed by you"); 
so it will help us in identifying such type of bugs.

**Comment by bhargavsonagara** [comment]
Actually what we have to do now? I am new to it plz help me and I really want to contribute on any issue .

**Comment by the-programmer** [comment]
Hi, I wanted to try and fix this issue but it seems this issue is already fixed:
https://github.com/dotnet/machinelearning/blob/4bcb892a8443b86b6ba289209167e4490c7b2a38/src/Microsoft.ML.AutoML/Utils/UserInputValidationUtil.cs#L254-L258

Can someone close this?
