### ISSUE TITLE
Why `RecursionLimit = 10` in `OnnxTransformer`?

### ISSUE THREAD

**Issue by s-tory** [dotnet/machinelearning#5585]
What is the purpose that `Google.Protobuf.CodedInputStream.RecursionLimit` is set `10` at the following code?

https://github.com/dotnet/machinelearning/blob/2a6cf9d9c9655f9e7d8ab7332efb5e2a2b70ce7e/src/Microsoft.ML.OnnxTransformer/OnnxUtils.cs#L208

----
It is set `100` by default in protocol-buffers C#-wrapper.

https://github.com/protocolbuffers/protobuf/blob/10599e6c8dde8a9875258e03054a696d53cadebd/csharp/src/Google.Protobuf/CodedInputStream.cs#L83
```
        internal const int DefaultRecursionLimit = 100;
```

----
I could not load some network / `.onnx` file by the following exception be caused by `RecursionLimit = 10` without the monkey-patched `Microsoft.ML.OnnxTransformer.dll`.
```
Google.Protobuf.InvalidProtocolBufferException: Protocol message had too many levels of nesting.  May be malicious.  Use CodedInputStream.SetRecursionLimit() to increase the depth limit.
```

I think that the networks are including `Inception` construction especially.
(ex. [tensorflow/models`s Faster-RCNN-Inception-V2](https://github.com/tensorflow/models/blob/master/research/object_detection/models/faster_rcnn_inception_v2_feature_extractor.py) converted)

Thank you for coding great tools!

**Comment by michaelgsharp** [comment]
Thanks for bringing this up. Let me discuss this with my team and see if we can figure out why we were setting this to 10.

**Comment by s-tory** [comment]
@michaelgsharp 
Did you figure out anything?
