### ISSUE TITLE
[GPU] What is the required minimum version of CUDA?

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#5594]
Raising a question based on docs issue dotnet/docs#21251

Do the existing docs need to be updated with another CUDA version? https://github.com/dotnet/machinelearning/blob/master/docs/api-reference/tensorflow-usage.md

**Comment by michaelgsharp** [comment]
I am not sure. I know the version of tensorflow was updated. Let me see if I can figure out what version of CUDA tensorflow wants.

**Comment by michaelgsharp** [comment]
So {tensorflow.net](https://github.com/SciSharp/TensorFlow.NET/wiki/Using-GPU-with-Tensorflow.NET) claims they want 10.0, and [tensorflow](https://www.tensorflow.org/install/gpu) itself supports lots of versions. I'll try and run/install with the version we have listed and see what happens.

**Comment by michaelgsharp** [comment]
Ok, after looking into more detailed docs and testing it myself, it does require at least 10.1 for CUDA. Looking into cuDNN more now.

**Comment by michaelgsharp** [comment]
So I was able to get it to work with the updated CUDA version, 10.1, but still leaving cuDNN as the original version 7.6.4. 

I can't right now, but I'll get PR created that will update this documentation and the link.

**Comment by luisquintanilla** [comment]
Thanks for looking into this @michaelgsharp 

To confirm:

CUDA version: 10.1
cuDNN: 7.6.4

**Comment by michaelgsharp** [comment]
That is correct. On the nvidia website they have 10.1, 10.1 update 1, and 10.1 update 2. I tested with 10.1 update 2, but in theory they should all work.
