### ISSUE TITLE
SymSGD Excessively Verbose

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning#5598]
Remove logging line, or modify from `ch.Info` to `ch.Trace`:
https://github.com/dotnet/machinelearning/blob/5dbfd8acac0bf798957eea122f1413209cdf07dc/src/Microsoft.ML.Mkl.Components/SymSgdClassificationTrainer.cs#L813

For my text dataset, this logging line dumps ~100 pages of floats to my console. That level of verbosity is unneeded at the `Info` level.

I'd recommend just removing the logging line.

**Comment by rohittrimalle** [comment]
Can I solve this issue?

**Comment by bhargavsonagara** [comment]
hiii, I am new to it plz guide me where to start and what to do!

**Comment by michaelgsharp** [comment]
@rohittrimalle or @bhargavsonagara, feel free to tackle this issue if you would like. 

You will have to remove the line @justinormont says, but then you will also have to fix the SymSGD baseline test files. We can help walk you through that when you get to that point if you want.

**Comment by bhargavsonagara** [comment]
> @rohittrimalle or @bhargavsonagara, feel free to tackle this issue if you would like.
> 
> You will have to remove the line @justinormont says, but then you will also have to fix the SymSGD baseline test files. We can help walk you through that when you get to that point if you want.

SymSGD baseline test files means 
plz help

**Comment by ankitasankars** [comment]
Hello, Can I use this issue as my first contribution? I'm new so please can someone guide me?

**Comment by bhargavsonagara** [comment]
> Hello, Can I use this issue as my first contribution? I'm new so please can someone guide me?

You will have to remove the line @justinormont says, but then you will also have to fix the SymSGD baseline test files. We can help walk you through that when you get to that point if you want.
