### ISSUE TITLE
mint.nithiporn@gmail.com

### ISSUE THREAD

**Issue by mintninthiporn** [dotnet/machinelearning#5605]
mint.nithiporn@gmail.com

_Originally posted by @mintninthiporn in https://github.com/dotnet/installer/pull/9562#discussion_r565986960_

**Comment by mintninthiporn** [comment]
Mint Nithiporn2543

**Comment by mintninthiporn** [comment]
0943086602

**Comment by michaelgsharp** [comment]
There is no relevant information here, I am going to close this for now, if you do have a question or an issue please re-open this ticket.
