### ISSUE TITLE
API to create a TextLoader from class metadata

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#561]
In the `LearningPipeline` API, we have the ability to create a TextLoader object using metadata applied to a regular C# class:

```C#
pipeline.Add(new TextLoader(dataPath).CreateFrom<HousePriceData>(useHeader: true, separator: ','));

public class HousePriceData
{
    [Column(ordinal: "0")]
    public string Id;
    [Column(ordinal: "1")]
    public string Date;
    [Column(ordinal: "2", name: "Label")]
    public float Price;
    [Column(ordinal: "3")]
    public float Bedrooms;
    [Column(ordinal: "4")]
    public float Bathrooms;
    [Column(ordinal: "5")]
    public float SqftLiving;
    [Column(ordinal: "6")]
    public float SqftLot;
    ...
```

I find it more intuitive to have a class decorated with metadata to use to load data instead of imperatively building up a schema in code, like the following:

```C#
private static TextLoader.Column ScalarCol(string name, int ordinal, DataKind kind = DataKind.Num)
    => new TextLoader.Column() { Name = name, Type = kind, Source = new[] { new TextLoader.Range() { Min = ordinal, Max = ordinal } } };

var loader = new TextLoader(env, new TextLoader.Arguments()
{
    HasHeader = true,
    SeparatorChars = new char[] { ',' },
    // These column declarations are meant to mirror those that appear in HousePriceData.
    Column = new[] {
        ScalarCol("Id", 0, DataKind.Text),
        ScalarCol("Date", 1, DataKind.Text),
        ScalarCol("Label", 2),
        ScalarCol("Bedrooms", 3),
        ScalarCol("Bathrooms", 4),
        ScalarCol("SqftLiving", 5),
        ScalarCol("SqftLot", 6),
}, new MultiFileSource(dataPath));
```

This issue is being opened to ensure we preserve this behavior with the new direct access API design proposed in #371 (possibly using a different API design, but preserving the functionality).

/cc @ericstj @TomFinley @Zruty0 @terrajobst

**Comment by Zruty0** [comment]
I definitely think we should be able to do both. 

Declarative schema is shorter, but imperative schema allows to read the data without knowing its schema at compile time.

**Comment by eerhardt** [comment]
Agreed.  I wasn't proposing to remove the imperative API to build the columns up using code. That is definitely necessary.  I was proposing building a "convenience" API on top of it, which built up the objects from metadata.

**Comment by glebuk** [comment]
Done per Senja
