### ISSUE TITLE
MacOS fails to install libomp

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#5615]
Copying issue raised by user dotnet/docs#21225

```
Runnning brew update && brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/f5b1ac99a7fba27c19cee0bc4f036775c889b359/Formula/libomp.rb && brew link libomp --force fails with the error:

Error: Calling Installation of libomp from a GitHub commit URL is disabled! Use 'brew extract libomp' to stable tap on GitHub instead.

Homebrew 2.5.7-2-gc8fcd05
Homebrew/homebrew-core (git revision cba702; last commit 2020-10-26)
Homebrew/homebrew-cask (git revision 8de20; last commit 2020-10-26)

MacOS: 10.15.7
```

Please confirm that the Mac instructions in the doc are still valid:

https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-extra-dependencies

**Comment by michaelgsharp** [comment]
Let me check it out. The CI builds still pass, and I dont think they are doing anything different. I don't have a mac, so unfortunately all I can check is the CI process builds.

**Comment by frostythecodeman** [comment]
> Copying issue raised by user [dotnet/docs#21225](https://github.com/dotnet/docs/issues/21225)
> 
> ```
> Runnning brew update && brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/f5b1ac99a7fba27c19cee0bc4f036775c889b359/Formula/libomp.rb && brew link libomp --force fails with the error:
> 
> Error: Calling Installation of libomp from a GitHub commit URL is disabled! Use 'brew extract libomp' to stable tap on GitHub instead.
> 
> Homebrew 2.5.7-2-gc8fcd05
> Homebrew/homebrew-core (git revision cba702; last commit 2020-10-26)
> Homebrew/homebrew-cask (git revision 8de20; last commit 2020-10-26)
> 
> MacOS: 10.15.7
> ```
> 
> Please confirm that the Mac instructions in the doc are still valid:
> 
> https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-extra-dependencies

I have been  having this exact issue all week. I have searched all over the internet and am yet to find a solution. A complete showstopper as my SSAForecastingEstimator in ML.net simply will not run on my Mac without this install. Please assist. I am sure tons more people are having this issue.

**Comment by michaelgsharp** [comment]
I don't have a mac so its harder for me to test, but I am thinking maybe the version linked is having issues? We store a copy of libomp.rb in our repo and have no issues using that for an install.

Can you try 2 things for me?
1 - Try and install again with the link from the instructions and let me know how it goes?
2 - If that doesn't work, try using this link and let me know what happens. https://raw.githubusercontent.com/dotnet/machinelearning/master/build/libomp.rb

**Comment by michaelgsharp** [comment]
It actually looks like with the newer versions of homebrew that you can't use a github url to install from anymore. The code you shared has this:
```
Error: Calling Installation of libomp from a GitHub commit URL is disabled! Use 'brew extract libomp' to stable tap on GitHub instead.
```

Actually, an issue was created on the homebrew repo for this exact issue. https://github.com/Homebrew/brew/issues/8791. They are no longer supporting install by github url at all. They suggest though that you can download the .rb file and then just do the path to the local rb file as a workaround. Its also possible the latest version of libomp will work so you woudln't have to do that, but there is no guarantee for that.

What I would do for now is just download the .rb file manually and then use the local file path to install it.

I will update the docs saying to do that as well.
