### ISSUE TITLE
Infer.NET

### ISSUE THREAD

**Issue by HowardvanRooijen** [dotnet/machinelearning#563]
Are there any plans to include Infer.NET (from Microsoft Research) in ML.NET? http://infernet.azurewebsites.net/

**Comment by Ivanidzo4ka** [comment]
They actually alive! That's a great news. We have learner based on Infer.Net, but I was struggle to find fresh nuget to consume, (https://www.nuget.org/packages/Microsoft.Research.InferNET/ it's 3,5 years old). 

From what I can see, they haven't update nuget package, and they code is .net framework 4.5, which can or can't be compatible with .net standard 2.0, so this part required some investigation, plus I guess I need to contact them and convince them to update nuget package, rather than publishing zip file on website.

We currently have Binary Bayes point machine classification learner.
Is there are specific things you interested in?

**Comment by HowardvanRooijen** [comment]
There is a March 2018 update http://infernet.azurewebsites.net/download.aspx - but yes, it isn't using the latest and greatest. I've always just thought it was an excellent library - the biggest problem was that it had a non-commercial license, which really limited what you could do with it.

I love that we finally have a powerful ML framework for .NET - I'd just like to see older MS investments get a bit more love (and a commercial license).

**Comment by dsyme** [comment]
I've pinged Yordan Zaykov in the Infer.NET team to understand status.

**Comment by yordanz** [comment]
So great to see enthusiasm for Infer.NET. The framework is actually being actively developed, and it's personally my fault that the NuGet package hasn't been updated. 

As to the license, we can't go public with any news just yet. But I hope this changes in the near future. Give me a couple of months, and I'll get back to you.

-Y-

**Comment by CESARDELATORRE** [comment]
@yordanz - I see you guys have a download .ZIP file with the Infer.NET compiler and runtime, examples and tutorials, learners, and source code here:
http://infernet.azurewebsites.net/download.aspx

Do you have a GitHub repo with the source code as open source so you can also have PRs, related issues, etc.?

**Comment by yordanz** [comment]
Not yet (-:

**Comment by Ivanidzo4ka** [comment]
>>NuGet package hasn't been updated
So do you plan to or not?
If you update it, can we reference it in our project?

**Comment by yordanz** [comment]
Infer.NET is now open source under the MIT license! We moved the namespaces and package to Microsoft.ML.Probabilistic as a first step towards integration with ML.NET.

[Website](https://dotnet.github.io/infer/) | [GitHub](https://github.com/dotnet/infer) | [Announcement](https://www.microsoft.com/en-us/research/blog/the-microsoft-infer-net-machine-learning-framework-goes-open-source/)

-Y-

**Comment by HowardvanRooijen** [comment]
That is AMAZING news! So, so, so pleased this great project get some love and a license that means we can use it. What a fantastic bit of news to end the week on! Thanks everyone!

**Comment by roguetrainer** [comment]
Congratulations! This is amazing news. Thank you!
One question, Microsoft.ML.Probabilistic.FSharp will not be on nuget, yet, right? 
I'm just trying to get some examples working on Azure (Jupyter) notebooks.

**Comment by lefig** [comment]
Likewise. This is splendid news. 
Infer.Net is a fabulous piece of work and will now be under the same ML umbrella

**Comment by abgoswam** [comment]
DRI RESPONSE : Planning to close this issue, since original question is now answered. 

Congratulations Infer.NET !

**Comment by shauheen** [comment]
Thanks for the discussion. infer.net is now open sourced and published as a member of ML.NET family. We will continue to work towards closer integration, however our roadmap to v1.0 does not include further work on integration. I'm closing this issue, and hopefully we will revisit the subject later.
