### ISSUE TITLE
ml.net 1.5.2 not compiling on windows because missing dependencies

### ISSUE THREAD

**Issue by MichaelBetser** [dotnet/machinelearning#5643]
### System information

- **OS version/distro**: windows 10 x64 pro version 10.0.19042
- **.NET Version (eg., dotnet --info)**: 5.0.200

### Issue

- **What did you do?**
Tried to compile ml.net 1.5.2 on windows to get compatible maml.exe binary
- **What happened?**
compile is failing when resolving dependencies
- **What did you expect?**
to compile

### Source code / logs
E:\git\ml.net_1.5.2\machinelearning>.\build.cmd
Installing procdump.exe
Finish install procdump.exe
Installing dotnet runtime 2.1.12...
Installing dotnet cli 3.1.102...
Restoring BuildTools version 3.0.0-preview4-04926-01...
ERROR: Could not restore build tools correctly.
Please check the detailed log that follows.
Running "E:\git\ml.net_1.5.2\machinelearning\init-tools.cmd"
Installing 'https://dotnetcli.azureedge.net/dotnet/Runtime/2.1.12/dotnet-runtime-2.1.12-win-x64.zip' to 'E:\git\ml.net_1.5.2\machinelearning\Tools\dotnetcli\dotnet-runtime-2.1.12-win-x64.zip'
Installing 'https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.102/dotnet-sdk-3.1.102-win-x64.zip' to 'E:\git\ml.net_1.5.2\machinelearning\Tools\dotnetcli\dotnet-sdk-3.1.102-win-x64.zip'
Running: "E:\git\ml.net_1.5.2\machinelearning\Tools\dotnetcli\dotnet.exe" restore "E:\git\ml.net_1.5.2\machinelearning\init-tools.msbuild" --no-cache --packages "E:\git\ml.net_1.5.2\machinelearning\packages" --source "https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json" /p:BuildToolsPackageVersion=3.0.0-preview4-04926-01 /p:ToolsDir=E:\git\ml.net_1.5.2\machinelearning\Tools
E:\git\ml.net_1.5.2\machinelearning\init-tools.msbuild : error NU1101: Unable to find package Microsoft.SymbolUploader.Build.Task. No packages exist with this id in source(s): https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
E:\git\ml.net_1.5.2\machinelearning\init-tools.msbuild : error NU1101: Unable to find package Microsoft.DotNet.BuildTools. No packages exist with this id in source(s): https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
  Restore failed in 1.06 sec for E:\git\ml.net_1.5.2\machinelearning\init-tools.msbuild.

**Comment by michaelgsharp** [comment]
Closing this per offline discussion. A re-clone fixed the issue.
