### ISSUE TITLE
DateTime columns cause schema type lookups to fail in DataFrame

### ISSUE THREAD

**Issue by WalternativE** [dotnet/machinelearning#5698]
### System information

- **OS version/distro**:  Windows 10 20H2 19042.844
- **.NET Version (eg., dotnet --info)**:  5.0.200

### Issue

- **What did you do?**
  I tried to use the `Explore()` and `ExploreWithSandDance()` extension methods on the
  `IDataView` type of the underlying `DataFrame` which contained a column of the type
  `PrimitiveDataFrameColumn<DateTime>`.

- **What happened?**
  I received the following error
  ```
  Error: System.NotSupportedException: Specified method is not supported.
  at Microsoft.Data.Analysis.PrimitiveDataFrameColumn`1.GetDataViewType()
  at Microsoft.Data.Analysis.PrimitiveDataFrameColumn`1.AddDataViewColumn(Builder builder)
  at Microsoft.Data.Analysis.DataFrame.get_DataViewSchema()
  at Microsoft.ML.DataViewExtensions.ToTabularJsonString(IDataView source)
  at Microsoft.ML.DataViewExtensions.ExploreWithSandDance(IDataView source)
  at <StartupCode$FSI_0011>.$FSI_0011.main@()
  ``` 

- **What did you expect?**
  I expected the same behavior as when I tried the same procedure with a `DataFrame` which did not contain a
  `DateTime` column.

### Source code / logs

As explained above I received a `NotSupportedException`. I assume, that it is connected to the execution of this line
`source.Schema.ToDictionary(column => column.Name, column => column.Type.RawType);` in the extension method to create the `TabularJsonObject` [here](https://github.com/dotnet/interactive/blob/4f22e1b0cd1023ee8e4ddff30de6b7c845a674c4/src/Microsoft.DotNet.Interactive.ExtensionLab/DataFrameKernelExtension.cs#L178).

I created a [notebook](https://github.com/WalternativE/DotnetInteractiveExperiments/blob/main/notebooks/DataFrameDateTimeProblem.ipynb) which showcases how I stumbled upon the error. It should be possible to use the binder link in the readme for this, even though it botches up the last redirect for some reason.

**Comment by eerhardt** [comment]
cc @pgovind

**Comment by dazinator** [comment]
Just hit this exception trying to follow the sample here with my own csv file: https://github.com/dotnet/interactive/blob/main/samples/ExtensionLab/ExtensionLab-SandDance.ipynb

**Comment by eerhardt** [comment]
FYI - @dakersnar

**Comment by michaelgsharp** [comment]
@JakeRadMSFT is this something you guys are working on fixing?

**Comment by beccamc** [comment]
This is fixed. I've confirmed that with a `PrimitiveDataFrameColumn<DateTime>` you can ExploreWithSandDance()

![image](https://user-images.githubusercontent.com/9122518/220990669-796f0ac1-29ba-44ba-a927-d32dd1418781.png)
