### ISSUE TITLE
Unsupervised learning in ML.NET and association rules

### ISSUE THREAD

**Issue by MrCSharp22** [dotnet/machinelearning#571]
Hi All,
I was looking at the available trainers in ML.NET on the Microsoft docs website and couldn't find anything for unsupervised learning with association rules.
Is this currently available? If not, do you have plans of adding support for association rules as it is something very interesting to work with.

Thank you

**Comment by codemzs** [comment]
Kmeans trainer offers unsupervised learning. We also plan to add DNN support soon.

https://docs.microsoft.com/en-us/dotnet/api/?view=ml-dotnet

dot.net/ml
