### ISSUE TITLE
[Question] Microsoft.Data.Analysis

### ISSUE THREAD

**Issue by Hulkstance** [dotnet/machinelearning#5716]
I was waiting on `Microsoft.Data.Analysis` for a long time and more specifically `.Shift()`, `.Resample()` operations. I literally saw an issue about that, but not sure what happened. I recently saw that you moved the repo over here. What is the newest repo that I can use?

https://github.com/xadupre/machinelearning_dataframe doesn't seem to be maintained.

**Comment by pgovind** [comment]
The latest code is here in this repo. There will be a new version of DataFrame soon (shipped from this repo) that you should be able to get from https://www.nuget.org/packages/Microsoft.Data.Analysis/. 

`Shift` and `Resample` are both time series related functions right? Unfortunately we don't support that yet. However, if you are interested to contribute, let us know and we'll be happy to help/review PRs etc :)

**Comment by dharmatech** [comment]
I posted a question about `shift`-like functionality here:

https://stackoverflow.com/questions/70042849/equivalent-of-shift-from-pandas

Yup, built-in shift would be very nice. :-)

**Comment by dharmatech** [comment]
I added an issue specifically for `shift`:

https://github.com/dotnet/machinelearning/issues/6008

**Comment by michaelgsharp** [comment]
Since you created the issue specifically for `shift` and we have the other issue talking about `resample`, I am going to close this issue since we have it covered in other issues.
