### ISSUE TITLE
wikipedia-detox-250-line-data.tsv file has an error

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/machinelearning#5722]
![image](https://user-images.githubusercontent.com/31348972/111859793-0fc4af00-894c-11eb-977e-52752ecf4f46.png)

**Comment by justinormont** [comment]
This appears to be a duplicate...

https://github.com/dotnet/machinelearning/pull/730
https://github.com/dotnet/machinelearning/issues/245

In previous discussion, it was decided that the file should stay as is, and the loader function should be updated to better suit the format for the file. I'm unsure if the the last step was completed.
