### ISSUE TITLE
Why not newer than CUDA 10.0?

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#5726]
Transferring product question posted in .NET Docs repo from @zleepy

Original Issue (dotnet/docs#23312)

Why should i not install CUDA newer than v10.0? 10.0 does not support newer versions of VS 2019.
A newer version of CUDA 10 says it does support VS 2019, see: https://docs.nvidia.com/cuda/archive/10.2/cuda-installation-guide-microsoft-windows/index.html.

And even newer, CUDA 11.2.1 does also say it supports VS, see: https://docs.nvidia.com/cuda/archive/11.2.1/cuda-installation-guide-microsoft-windows/index.html

What is the reason this page explicit says that i should not install anything that Nvidia says is supported by newer versions of VS?

**Comment by michaelgsharp** [comment]
Its the version of CUDA that the version of Tensorflow we support uses. You can try and use later versions, but there is no guarantee of support for them. 

For example we use Tensorflow.net, and their recommendations are [here](https://github.com/SciSharp/TensorFlow.NET#how-to-use), which show 10.1 for the version we use. So feel free to try it, but its not officially supported.
