### ISSUE TITLE
Make sure custom predictors are possible to write using the API

### ISSUE THREAD

**Issue by taddison** [dotnet/machinelearning#573]
I'd like to leverage the evaluators with custom predictors (specifically a `PredictionModel` not built from ML.Net), though right now that isn't possible as `PredictionModel`'s constructor is internal.

## Scenario

We have a number of what I think are great scenario fits for ML.Net (lot of C# experience, a few models based on static rules currently deployed), but as both a pedagogical aid and a way of comparing any new work vs. existing work I'd like to plug some of our existing models into the ML.Net ecosystem, specifically doing something along the following lines:

- Model the input, predicted datasets
- Write the code to pull various sets of data
- Instantiate my own `PredictionModel` (with predict ranging from something as simple as returning a hardcoded value, to calling an existing prediction endpoint we have)
- Evaluate the model using one of the existing ML.Net validators, probably saving results
- Evaluate the model using a custom evaluator specific to our projects (though re-usable within the ML.Net ecosystem)

Iteration could then take place on building a model & training it with ML.Net components.

Is this a workflow that you think is best performed in some other manner, or is it a scenario you'd like to support with ML.Net?  We can evaluate models without using ML.Net, though the more we can keep things in the same ecosystem, the stronger the internal network effect is likely to be (particularly when targeting an engineering team almost exclusively comprised of devs and not data scientists).

**Comment by Zruty0** [comment]
@taddison , we absolutely want you to be able to create your own Predictors! In fact, the experiment you describe is already possible using the lower-level ML.NET code. 

This 'low-level API' has historically been written with efficiency in mind, at the expense of simplicity. So, we do not recommend diving into the guts of ML.NET right now. You can still do it of course, but we are not planning to document the current API any further than it is now.

Instead, an effort in https://github.com/dotnet/machinelearning/projects/4 is under way right now. Our aim is to produce a new user-facing API that is:
- Close enough to the low-level constructs that it doesn't require a lot of wrangling to expose new things.
- Powerful enough to allow creative usage of the system (like evaluate without training).
- Allowing easy extensibility: you should be able to create your own loaders, transformers, trainers, predictors, evaluators and mix and match them with existing ones.
- Keeping simple scenarios short and concise.

An aspirational goal would be to come up with an API that would allow you the following pseudocode:
```(csharp)
var data = new MyCustomSqlLoader(mySettings).LoadFromTable("TrainSet");
var myPredictor = new Microsoft.ML.CustomTransformer<CustomerData, CustomerPrediction>( (CustomerData x) => myWebService.GetPrediction(x));
var scoredData = myPredictor.Transform(data);
var metrics = new Microsoft.ML.BinaryClassificationEvaluator().Evaluate(scoredData, trueLabelColumn: "CorrectAnswer");
Microsoft.ML.TextSaver.SaveData(scoredData, "scored-data.txt");
```

You can see that we want the user to be able to add their own components to the pipeline, and mix and match them with the standard components.

**Comment by taddison** [comment]
Great - thanks for taking the time to share that context - the pseudocode tells me that what I've asked for is coming.  I guess this is part of the 'wild ride' to 1.0 😄.

My issue is really about tracking the state of custom predictors rather than something specific around the evaluator/predictor combo.  Let me know if you'd like me to close/rename the issue or leave as-is.

**Comment by Zruty0** [comment]
Yes, I think we can rename it to 'make sure custom predictors are possible to write using the API', and then we can add it to the API project.

**Comment by codemzs** [comment]
The current Stable API allows this.
