### ISSUE TITLE
AutoML binary experiment continues using poorly performing model

### ISSUE THREAD

**Issue by voges316** [dotnet/machinelearning#5730]
### System information

- **OS version/distro**: CentOS 7-9.2009
- **.NET Version (eg., dotnet --info)**:  3.1.112, Microsoft.ML v1.5.5, Microsoft.ML.AutoML v0.17.5

### Issue

Was using automl for sentiment analysis on the imdb dataset https://ai.stanford.edu/~amaas/data/sentiment/ . Created a binary classification experiment that would use all trainers (9 by default), optimize Accuracy (also default), and run for 2 hours. I also added a progress handler that would print metrics of the results as the experiment progressed.
After running for some time, the progress handler showed the experiment was switching between AveragedPerceptronBinary, LbfgsLogisticRegressionBinary, and SgdCalibratedBinary. The second two made some sense since the Accuracy results were higher (approx 0.90) and occasionally would increase, but the first one "AveragedPerceptronBinary" confused me, since it consistently had  low results (approx 0.5, 0.7, etc). 

I'm wondering if this is a bug in the Experiment Logic or not. I would expect the experiment to discard a poorly performing Model instead of continuing to come back to it again, which appears to be what it does for all the other models except for AveragedPerceptronBinary. For example, FastTreeBinary is only tried once and then ignored, but AveragedPerceptronBinary is tried all the way until the end.

### Source code / logs

```
Show data in DataView: Showing 1 rows with the columns
######################################################
Row--> | Review:I honestly don't understand how tripe like this gets made. The worst junior-high talent show skit you've ever seen is more entertaining than this film. Will Ferrell's wrestling fetish provides the only (briefly) humorous moments. Utterly horrible.| Label:False

AutoML RunExperiment (s): 7200
AutoML keeping Models in memory
AutoML Optizing Metric: Accuracy
AutoML Trainers being used:
        AveragedPerceptron
        FastForest
        FastTree
        LightGbm
        LinearSvm
        LbfgsLogisticRegression
        SdcaLogisticRegression
        SgdCalibrated
        SymbolicSgdLogisticRegression
     Trainer                               Accuracy    AUC       AUPRC   F1-score  Duration
   1 AveragedPerceptronBinary               0.8984    0.9591    0.9550    0.9003   33.5595 *
   2 SdcaLogisticRegressionBinary           0.8845    0.9539    0.9488    0.8870   42.0153
   3 LinearSvmBinary                        0.8806    0.9555    0.9504    0.8764   31.1247
   4 FastTreeBinary                         0.8706    0.9444    0.9424    0.8730  182.7707
   5 LbfgsLogisticRegressionBinary          0.8938    0.9579    0.9527    0.8960   63.6329
   6 FastForestBinary                       0.7451    0.8190    0.8076    0.7597  145.4131
   7 SgdCalibratedBinary                    0.9034    0.9606    0.9556    0.9044   33.7678 *
   8 AveragedPerceptronBinary               0.4983    0.7931    0.7769    0.0000   62.3400
   9 LbfgsLogisticRegressionBinary          0.8876    0.9558    0.9496    0.8893   53.2443
  10 SgdCalibratedBinary                    0.9031    0.9605    0.9556    0.9040   34.0770
  11 AveragedPerceptronBinary               0.4983    0.7759    0.7782    0.0000   70.6186
  12 LbfgsLogisticRegressionBinary          0.8980    0.9612    0.9563    0.9006   49.4685
  13 SgdCalibratedBinary                    0.8772    0.9493    0.9442    0.8743   30.8654
  14 AveragedPerceptronBinary               0.5048    0.8151    0.8021    0.0317   32.4597
  15 LbfgsLogisticRegressionBinary          0.8891    0.9563    0.9507    0.8912   94.6190
  16 SgdCalibratedBinary                    0.9034    0.9606    0.9556    0.9041   33.7996
  17 AveragedPerceptronBinary               0.5017    0.7522    0.7453    0.6682   32.2783
  18 LbfgsLogisticRegressionBinary          0.8946    0.9583    0.9527    0.8966   94.1862
  19 SgdCalibratedBinary                    0.8961    0.9587    0.9537    0.8957   31.7183
  20 AveragedPerceptronBinary               0.4986    0.8256    0.8027    0.0015   42.6899
  21 LbfgsLogisticRegressionBinary          0.8938    0.9586    0.9528    0.8963   43.6216
  22 SgdCalibratedBinary                    0.9031    0.9604    0.9555    0.9037   33.1641


 122 AveragedPerceptronBinary               0.4983    0.8266    0.8285    0.0000   51.6914
 123 LbfgsLogisticRegressionBinary          0.9019    0.9614    0.9564    0.9033   48.7525
 124 SgdCalibratedBinary                    0.9027    0.9604    0.9555    0.9033   33.3645
 125 AveragedPerceptronBinary               0.6771    0.8222    0.8145    0.7431   34.6309
 126 LbfgsLogisticRegressionBinary          0.9046    0.9618    0.9570    0.9063   68.3563 *
 127 SgdCalibratedBinary                    0.9034    0.9605    0.9556    0.9044   33.7517
 128 AveragedPerceptronBinary               0.7126    0.8588    0.8618    0.7650   39.4687
 129 LbfgsLogisticRegressionBinary          0.9023    0.9617    0.9569    0.9041   67.2922
 130 SgdCalibratedBinary                    0.9003    0.9599    0.9551    0.9009   31.9746
 131 AveragedPerceptronBinary               0.6829    0.8260    0.8218    0.7468   34.5324
 132 LbfgsLogisticRegressionBinary          0.9042    0.9620    0.9573    0.9059   62.4062
 133 SgdCalibratedBinary                    0.9031    0.9605    0.9556    0.9039   33.5832
 134 AveragedPerceptronBinary               0.7173    0.8573    0.8521    0.6398   31.4024
 135 LbfgsLogisticRegressionBinary          0.9027    0.9617    0.9568    0.9045   62.7962
 136 SgdCalibratedBinary                    0.9023    0.9605    0.9555    0.9030   33.3611
 137 AveragedPerceptronBinary               0.5342    0.8236    0.8271    0.6825   32.9347
 138 LbfgsLogisticRegressionBinary          0.8973    0.9605    0.9552    0.8993   80.9124
 139 SgdCalibratedBinary                    0.9031    0.9605    0.9556    0.9041   34.1757
 140 AveragedPerceptronBinary               0.7810    0.8643    0.8585    0.7861   32.6319
 141 LbfgsLogisticRegressionBinary          0.9038    0.9618    0.9570    0.9056   61.3063
 142 SgdCalibratedBinary                    0.9023    0.9605    0.9555    0.9031   34.0737
 143 AveragedPerceptronBinary               0.4990    0.8360    0.8169    0.0031   31.8536
 144 LbfgsLogisticRegressionBinary          0.9034    0.9611    0.9563    0.9049   50.3616
 145 SgdCalibratedBinary                    0.8810    0.9495    0.9447    0.8840   30.7382
 146 AveragedPerceptronBinary               0.7374    0.8331    0.8291    0.6962   31.7820
 147 LbfgsLogisticRegressionBinary          0.9046    0.9620    0.9573    0.9063   62.7225
 148 SgdCalibratedBinary                    0.9011    0.9588    0.9537    0.9016   31.6420
 149 AveragedPerceptronBinary               0.5280    0.8004    0.7997    0.6789   38.1294
 150 LbfgsLogisticRegressionBinary          0.9034    0.9620    0.9572    0.9052   59.0457
 151 SgdCalibratedBinary                    0.8980    0.9586    0.9537    0.8978   31.4805
 152 AveragedPerceptronBinary               0.7771    0.8568    0.8515    0.7761   31.2145

Total models produced: 154
Best model's trainer: LbfgsLogisticRegressionBinary
Metrics of best model from validation data --
Accuracy: 0.9045963692545385
AreaUnderPrecisionRecallCurve: 0.9570456314512586
```

**Comment by justinormont** [comment]
Explanation for the AutoML optimization strategy: https://github.com/dotnet/machinelearning/issues/5608

`AveragedPerceptronBinary` is chosen for optimization since it did well on its first run, which uses its defaults. 

Then in subsequent models, the hyperparameter optimization wasn't able to match the original run's accuracy; and _I'm not sure why._ 

Our defaults (in feature engineering and model hyperparameters) are good as we spent quite a bit of time optimizing them across many datasets. Generally given time, the initial run (using defaults), is exceeded as the search space ranges encompasses the default hyperparameter values.

**Paper comparison**
One bright point: if your run is comparable to the dataset authors' [paper](https://ai.stanford.edu/~amaas/papers/wvSent_acl2011.pdf), the first model AutoML creates beats the results in their paper. Granted ML has evolved, and ideally, ML․NET would include a transformer model like BERT which should exceed the current methods by a reasonable margin.

**Optimizing AUC**
You may want to try optimizing towards AUC. It tends to be more smooth of a metric value, lending itself to easier optimization. You can still choose your winning model based on accuracy. 

As an example of how this could help: `SgdCalibratedBinary` gets quickly to `0.9034`, and that (in the runs you posted) remained its highest accuracy, but its AUC values are greater in following iterations, indicating slightly better models were found even though the accuracy remains at `0.9034`. Accuracy is generally a closer match for the business metrics, though is a post thresholded metric, whereas AUC operates on the raw scores.

**Comment by voges316** [comment]
Thank you, that post on the optimization strategy helps explain what's going on. It's kind of odd that the AveragedPerceptronBinary accuracy drop off so fast, but I can see why it selected that one, and I can just specify different models if I want.

**Comment by justinormont** [comment]
Quite welcome.

**Comment by torronen** [comment]
"Our defaults (in feature engineering and model hyperparameters) are good as we spent quite a bit of time optimizing them across many datasets."

@justinormont How do you feel about if there would an overload to set custom set of defaults for the first stage? For example, I might have some good default values from earlier runs about public service recommendations. I could then set 3 defaults for each of the trainers to get more accurate first stage results for my datasets.

Related to this do you know can I get the hyperparameters for the best trained model, let's say to generate retraining code like Model Builder is doing, or storing for later use?

**Comment by luisquintanilla** [comment]
Thanks everyone for the discussion and feedback. We've recently updated our AutoML implementation based on FLAML which might help address some of the comments mentioned here. 

For more information, check out the [blog post](https://devblogs.microsoft.com/dotnet/whats-new-with-mldotnet-automl/#automl-updates) and [sample notebook](https://github.com/dotnet/csharp-notebooks/blob/main/machine-learning/03-Training%20and%20AutoML.ipynb). 

Closing this issue.
