### ISSUE TITLE
Order of rows affects results

### ISSUE THREAD

**Issue by nnoradie** [dotnet/machinelearning#5737]
### System information

- **OS version/distro**:
- **.NET Version (eg., dotnet --info)**: 

![image](https://user-images.githubusercontent.com/69877427/113660091-40009300-9658-11eb-9ddf-eb7f77bda83c.png)

### Issue

- **What did you do?**
Run key drivers on two datasets with a different row order

- **What happened?**
The scores returned for the same data with different row order differs

- **What did you expect?**
The same score to be returned for the same data no matter the row order

Original Data returns 
![image](https://user-images.githubusercontent.com/69877427/113658902-d089a400-9655-11eb-94f9-0911fea5062e.png)

ReorderdData returns
![image](https://user-images.githubusercontent.com/69877427/113658888-c4054b80-9655-11eb-9d04-f23f5e52259c.png)

The data is identical after reordering with excel custom sort left to right
![image](https://user-images.githubusercontent.com/69877427/113659813-b51f9880-9657-11eb-9b06-40cdeddb6d35.png)

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

The column names are slightly different. The data is the same, but reordered
[OrderAffectsResults.zip](https://github.com/dotnet/machinelearning/files/6262140/OrderAffectsResults.zip)
Contains two csv files: OriginalData.csv and ReorderedData.csv

Frieght is Discretized role
Weight is Continuous role
Subtotal is Continuous role
FreightBool is default role
![image](https://user-images.githubusercontent.com/69877427/113658459-f2cef200-9654-11eb-91ed-97fb92551d9f.png)

Original data options:
![image](https://user-images.githubusercontent.com/69877427/113660648-738fed00-9659-11eb-87d4-d7194586a9cd.png)

Reordered data options (The LabelColumnName is different, but has the same values):
![image](https://user-images.githubusercontent.com/69877427/113661238-9242b380-965a-11eb-98be-8c7af2f53129.png)

**Please let me know if you need any more information**

**Comment by nnoradie** [comment]
We've identified that this happens when we need to oversample. It may happen in other cases, but this specific case refers to oversampling.

**Comment by nnoradie** [comment]
Hi @michaelgsharp would you be able to help with this or tag someone who can?

**Comment by michaelgsharp** [comment]
@nnoradie I will take a look at it, but also @justinormont any thoughts?

I haven't looked through your code yet, but what trainer are you guys using?

**Comment by justinormont** [comment]
For a bit of clarity, are you scoring `OriginalData.csv` and `ReorderedData.csv` on an already trained model?

Can you post your training pipeline? Or full project?

**Comment by nnoradie** [comment]
Hi @michaelgsharp, we're using the LbfgsLogisticRegressionBinaryTrainer
@justinormont, I believe we are training a new model each time we get the data and using that to score. But we use a seed to our randomizer and receive the same results every time we train the same bit of data. I will see if I can get the training pipeline for you

**Comment by nnoradie** [comment]
Hi @michaelgsharp , I can no longer repro this issue in desktop after upgrading to MLNet 1.6.0
