### ISSUE TITLE
[Question] Model serialization and store in database

### ISSUE THREAD

**Issue by Lazar-source** [dotnet/machinelearning#5740]
### System information

- OS version/distro: Win x64
- .NET Version (eg., dotnet --info): netcore 3.1

### Issue

 I'm in a project and we are using mlnet. We are using a lot of models with different trainers. 
 I know there is a way to save it as a zip file, but i didnt like that solution. My question is:
 Is there a way to serialize the trained model(object) and store it in database? I havent found any information related to it, and i dont know a lot about serialization.

Thanks for answers!

**Comment by PeterKottas** [comment]
Simply save it to [stream ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.modeloperationscatalog.save?view=ml-dotnet#Microsoft_ML_ModelOperationsCatalog_Save_Microsoft_ML_ITransformer_Microsoft_ML_DataViewSchema_System_IO_Stream_)and you can do anything you want with the stream. Generally speaking, storing stuff like this in DB is not a good idea though, at least not in relational DB. I would recommend some blob storage or FTP.

**Comment by PeterKottas** [comment]
Sidenote, to avoid confusion, the stream will actually be in a "form" of zip. Therefore if you decide to for instance upload the stream to FTP, feel free to just add the zip extension. One way or another, you can just as easily load the model from the stream, so technically, you don't even have to worry about what format it is.

**Comment by Lazar-source** [comment]
Thanks for the answer and sorry for the late reply!

**Comment by PeterKottas** [comment]
No worries, happy to help.
