### ISSUE TITLE
Missing MatrixFactorizationTrainer In Current ML.Net (1.5.5)

### ISSUE THREAD

**Issue by AmirAliShokri** [dotnet/machinelearning#5748]
### System information

- **OS Windows 10 Pro**:
- **.NET Version (5.1)**: 
- **Last Visual Studio**: 

### Screen Shot 
https://pasteboard.co/JXt92l9.png

Hey Every One 
I Learn a Course About Ml.Net And In This Course My Master Add Matrix Factorization Trainer Into His Code but Is This Version Of Ml.Net I Cant Find This Class 

Please Help Me Thanks

**Comment by jwood803** [comment]
Hey @AmirAliShokri! That trainer was moved to the [Microsoft.ML.Recommender](https://www.nuget.org/packages/Microsoft.ML.Recommender/) package. 

Once that's installed you should be good to go. 😄

**Comment by AmirAliShokri** [comment]
@jwood803 Thank you so very much This Is Work 💯
