### ISSUE TITLE
Publish single-file does not include MklImports

### ISSUE THREAD

**Issue by francescomazzurco** [dotnet/machinelearning#5749]
Hi,

I just migrated a simple console application depending on `Microsoft.ML.AutoML` from .NET Core 3.1 to .NET 5.0
Everything builds fine, but the publishing behavior is different. 
In .NET Core 3.1, I used to get a large single file containing all Mkl dlls.
![image](https://user-images.githubusercontent.com/33526441/115021932-ef413380-9ebc-11eb-98b8-961345019cdc.png)

In .NET 5.0 I get many separated files where the main .exe is small (clearly too small to contain the large Mkl dlls).
![image](https://user-images.githubusercontent.com/33526441/115021737-a5f0e400-9ebc-11eb-84f9-bd18ee4aa18e.png)

Below my publish profile. Switching back to .NET Core 3.1 solves the problem.  

```
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <Platform>Any CPU</Platform>
    <PublishDir>bin\Release\net5.0\publish\</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <TargetFramework>net5.0</TargetFramework>
    <SelfContained>false</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>True</PublishSingleFile>
    <PublishReadyToRun>False</PublishReadyToRun>
  </PropertyGroup>
</Project>
```

This may not be the right place to post the issue, but `Microsoft.ML.AutoML` I experienced the problem with.

Thanks

**Comment by ericstj** [comment]
By default .NET5.0 does not include native binaries in the single-file bundle see to include them you can specify `/p:IncludeNativeLibrariesInSingleFile=true`.

See documentation here: https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file#output-differences-from-net-3x

**Comment by francescomazzurco** [comment]
Thanks, I didn't know that
