### ISSUE TITLE
Feature importance for LightGBM

### ISSUE THREAD

**Issue by sharpwood** [dotnet/machinelearning#576]
Is there a way to provide a LightGBM Feature importance demo code ?

**Comment by codemzs** [comment]
Hi @sharpwood , Currently feature importance is not available via API but we are planning on it in the near future.

**Comment by sharpwood** [comment]
This problem has not been resolved, why is it closed?

**Comment by Ivanidzo4ka** [comment]
@rogancarr  Do we have example of how run feature importance for Tree learners?

**Comment by rogancarr** [comment]
@sharpwood We have per-sample feature importance through the `FeatureContributionCalculator`. You can find a sample [here](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/FeatureContributionCalculationTransform.cs) that uses a linear model, but you can just swap in any of our tree learners, including LightGBM to get importance for those.

Similarly, you can use Permutation Feature Importance to look at global feature importance. You can find the sample [here](https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/PermutationFeatureImportance/PFIRegressionExample.cs).

Finally, you can also get the Feature Gains for each feature in our tree models through the `GetFeatureWeights()` method on the models (e.g. in `trainedPipeline.LastTransform.Model`).

For more explicit examples, I have a PR going through for functional tests that does this every which-way: https://github.com/dotnet/machinelearning/pull/2584
