### ISSUE TITLE
Temp ONNX model files not cleaned up if dispose is not called.

### ISSUE THREAD

**Issue by michaelgsharp** [dotnet/machinelearning#5764]
Right now when we use an ONNX model that is saved inside an ML.NET model, we create a new temp file for the ONNX model. This temp file is only cleaned up if the user manually calls dispose on the loaded ML.NET model. This is a problem because the base `ITransformer` that is loaded from `Model.Load` is not disposable. You need to know you have to manually cast it to `IDisposable` to dispose of it correctly. It also is a problem because the temp file name is not recorded anywhere (other than inside the class itself), so its hard to manually clean it up as well.

**Comment by ericstj** [comment]
Fixed in #5782
