### ISSUE TITLE
Mysterious System.NullReferenceException when attempting Cross Validation.

### ISSUE THREAD

**Issue by Latylus** [dotnet/machinelearning#577]
### System information

- **OS version/distro**: Windows 10 17134.167
- **.NET Version (eg., dotnet --info)**: 
```
Product Information:
 Version:  2.1.302
 Commit : 9048955601

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0
```

### Issue

- **What did you do?**
Attempted to run cross validation on a pipeline for multiclass classification (MNIST digit recognition dataset).
- **What happened?**
On the line where I call the `CrossValidate` method, I get a `System.NullReferenceException` exception whose source isn't obvious.
- **What did you expect?**
For the Cross Validation to take place without a hitch, or get a more explicit error.
If this is actually a simple fixable error on my part, I'll be glad to fix it.

### Source code / logs
```cs
var pipeline = new LearningPipeline();
pipeline.Add(new TextLoader(_dataPath)
{
    Arguments = new TextLoaderArguments
    {
        Separator = new[] { ',' },
        HasHeader = true,
        Column = new[]
        {
            new TextLoaderColumn()
            {
                Name = "Label",
                Source = new [] { new TextLoaderRange(0) },
                Type = DataKind.Num
            },

            new TextLoaderColumn()
            {
                Name = "Features",
                Source = new [] { new TextLoaderRange(1, 784) },
                Type = DataKind.Num
            }
        }
    }
});
pipeline.Add(OneVersusAll.With(  new FastForestBinaryClassifier() { MinDocumentsInLeafs = 1, NumTrees = 150})); 
            
var crossValidator = new CrossValidator()
{
    NumFolds = 5,
    Kind = MacroUtilsTrainerKinds.SignatureMultiClassClassifierTrainer
};
            
var crossValidatorOutput = crossValidator.CrossValidate<MNISTData, MNISTPrediction>(pipeline);
```
![image](https://user-images.githubusercontent.com/13185436/43144220-dc677106-8f5c-11e8-91f9-e7634a35eaf4.png)

I made sure both `pipeline` and `crossValidator` weren't `null`. I'm guessing it has something to do with some of the content of `pipeline` but the documentation and other examples I've seen of the usage of Cross Validation did not allow me to guess what the exact problem was.

**Comment by jwood803** [comment]
Hey, @Latylus! May I ask where I can get a sample of the data that you're using?

**Comment by Latylus** [comment]
Hello, @jwood803 . I used the data from [Kaggle](https://www.kaggle.com/c/digit-recognizer/data) as the format is pretty explicit.
I also want to add that these are the classes used for Data and Prediction (hope it helps).
```cs
public class MNISTData
{
    public float Label;

    [VectorType(784)]
    public float[] Features;
}

public class MNISTPrediction
{
    [ColumnName("PredictedLabel")]
    public uint ExpectedDigit;

    [ColumnName("Score")]
    public float[] PredictedLabels;
}

```

**Comment by Latylus** [comment]
For a quick look at the data format in the csv file, it looks something like this:
```
label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5, ----- , pixel784
2,0,0,0,0,0, ------------------------------------------------, 0
|                                                              |
|                                                              |
7,0,0,0,0,0,--------------------------------------------------,0
```

**Comment by rogancarr** [comment]
Adding `need info` tag until I repro it.

**Comment by codemzs** [comment]
please use the current stable API and let me know if this still repros.
