### ISSUE TITLE
Object Detection Bounding Box gone wrong

### ISSUE THREAD

**Issue by arafattehsin** [dotnet/machinelearning#5772]
### System information

- **Windows 10**:
- **.NET Core 3.1**: 

### Issue

- **I created an object detection model with fantastic accuracy**
- **All works good. However, when I try to map the bounding box coordinates, I see that the coordinates returned are not correct by the model (or may be I am totally wrong and I should know how to make it work)**
- **The bounding box should have been drawn correctly around the detected items.**

### Source code / logs

This is the Preview I get (before training)

![image](https://user-images.githubusercontent.com/16351038/116357509-ded77400-a83f-11eb-9005-a45b5c842e7e.png)

This is what I get after training.

![image](https://user-images.githubusercontent.com/16351038/116359271-f6176100-a841-11eb-8c0e-8e23c5d5ed58.png)

This is what I get for a different image (after training).

![image](https://user-images.githubusercontent.com/16351038/116359399-1a733d80-a842-11eb-8b52-ded9c563f7c1.png)

> Note: I know they are delicious. 🍩

However, after passing the same image to model, I get the coordinates which are mapped like this;

![trifle-5](https://user-images.githubusercontent.com/16351038/116357930-6cb35f00-a840-11eb-91a6-1e12464fbfaa.jpeg)

Nothing fancy in terms of code;

```
 var boundingBoxes = predictionResult.BoundingBoxes;

    foreach (BoundingBox box in boundingBoxes)
    {
      // read image file
      Image oldImg = Image.FromFile(destinationPath);
    
      using (Graphics g = Graphics.FromImage(oldImg))
      {
          // Create pen.
          Pen redPen = new Pen(Color.Red, 3);
    
          // Draw Rectangle
          Rectangle rectangle = Rectangle.FromLTRB(Convert.ToInt32(box.Left), Convert.ToInt32(box.Top), Convert.ToInt32(box.Right), Convert.ToInt32(box.Bottom));
    
          g.DrawRectangle(redPen, rectangle);
      }
    .
    .
    .
    .
    
    }
```

Please tell me that I am absolutely wrong by correcting me or posting a correct solution. Thanks! 🙏

**Comment by JakeRadMSFT** [comment]
Hello!
It looks like you're using Model Builder. Would you be up for trying out our preview build? I believe this issue is resolved there and a public release is coming soon.

**Comment by arafattehsin** [comment]
Hey @JakeRadMSFT thanks for your response. Do we have an update on the Model Builder lately? I can try in an hour and get back to you then.

**Comment by arafattehsin** [comment]
Hey @JakeRadMSFT - I just checked that I have the latest version:

![image](https://user-images.githubusercontent.com/16351038/117232501-a00b7480-ae64-11eb-9c02-18c3ef85020e.png)

It matches with the latest atom.xml;

![image](https://user-images.githubusercontent.com/16351038/117232892-6b4bed00-ae65-11eb-90d8-8a91ce9954d7.png)

May I know if I am doing anything wrong?

**Comment by LittleLittleCloud** [comment]
Hi @arafattehsin 

The coordinate values in `BoudingBox` are normalized to 800L * 600H dimension. This is because in the training pipeline all images are resized to 800 * 600. So you will need to do a re-mapping for `BoundingBox` coordinate values so they can match the custom image size. Specifically, for `BoundingBox.Left` and `BoundingBox.Right`, you need to divide it by 800 and multiply the width of the custom image. And for `BoundingBox.Top` and `BoundingBox.Bottom`, divide it by 600 and multiply the height of your image.

**Comment by LittleLittleCloud** [comment]
@JakeRadMSFT @briacht 
Looks like the normalized bounding boxes are mentioned nowhere so maybe we should add a comment to output class?

**Comment by arafattehsin** [comment]
Hey @LittleLittleCloud - you're the star. It works fine. Thanks a lot!
