### ISSUE TITLE
Error when downloading the file 'inception_v3.meta'

### ISSUE THREAD

**Issue by ddobric** [dotnet/machinelearning#5775]
Hi all,

we are using ML.NET in production for image classification. In our application, we also use TensorFlow inception model that is implicitly downloaded.

The problem happened last few days as the application in the production stopped working because the download URLhas changed:

> 2021-04-29T07:22:32
> System.InvalidOperationException: Error downloading a resource from 'https://aka.ms/mlnet-resources/inception_v3.meta': No such host is known. No such host is known.,

I guess there must be some smarter way to prevent this error in the future.

And, we still had posted a similar issue related to the inception file. See https://github.com/dotnet/machinelearning/issues/5083

**Comment by michaelgsharp** [comment]
Hey @ddobric, sorry for my delay. I should have this issue resolved today. I'll update this ticket again when its done.

**Comment by michaelgsharp** [comment]
Alright, its been fixed. Let me know if you run into any more of these.

**Comment by ddobric** [comment]
Thanks @michaelgsharp .
Would it be possible to get short documentation that describes the download process like when the download starts, from where, where the file will be downloaded, who is open it, under which permissions set,..  etc?
