### ISSUE TITLE
Customer reported: Image Classification API Fit() error

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning#5784]
From: https://twitter.com/kasozi39567299/status/1390069853214679042?s=20

![image](https://user-images.githubusercontent.com/10437687/117220420-0a1c0f00-adbc-11eb-9c43-f792688eace1.png)

**Comment by ericstj** [comment]
cc @michaelgsharp 
This works fine for me http://aka.ms/mlnet-resources/meta/resnet_v2_50_299.meta
Could it be something with the user's network that's preventing the download?

**Comment by michaelgsharp** [comment]
This is a transient error that happens when the network has a blip. A retry should fix the issue.

@briacht have you heard anything else about this? I am going to close the issue since a simple retry should have fixed it, but if you have heard that it is still happening please reopen the issue.
