### ISSUE TITLE
AutoML : Getting Empty Prediction Results

### ISSUE THREAD

**Issue by iluveu28** [dotnet/machinelearning#5785]
### System information

- **OS version/distro**: Linux
- **.NET Version (eg., dotnet --info)**: 3.1

This is a follow up to the issue that no one responded - https://github.com/dotnet/machinelearning/issues/5738

First of all, why does it group the columns in the first place ? It doesn't group the numerical columns for my other project which has only 5 columns in total. How does it determine when to group them?

So the missing Features column error is gone now after setting the flag to false, thank you. However, the results are empty. The predictions variable is returning a list of 0 values. What am I doing wrong below? Again, the same code works fine for my other project with 5 columns.

	var options = new TextLoader.Options
	{
		Separators = new[] { ',' },
		HasHeader = true,
		Columns = columns,
		AllowQuoting = true,
		AllowSparse = true
	};

	var loader = _mlContext.Data.CreateTextLoader(columns,
			hasHeader: true,
			separatorChar: ',');

            File.WriteAllText(testDataPath, content);

            var testData = loader.Load(testDataPath);

            ITransformer mlModel = _mlContext.Model.Load(modelPath, out var modelInputSchema);

            var output = mlModel.Transform(testData);

            var predictions = output.GetColumn<UInt32>(labelColumnName);

            var predictedLabel = output.GetColumn<ReadOnlyMemory<char>>("PredictedLabel");

            int count = predictedLabel.Count();

            string jsonResults = "";

            foreach (ReadOnlyMemory<char> result in predictedLabel)
	{
              jsonResults += "{ output: " + result.ToString() + "}";

	}

**Comment by michaelgsharp** [comment]
@justinormont do you think you could explain how the column groupings are done? I will go look through the code, but you are much more familiar with that part of the code than I am.

**Comment by justinormont** [comment]
Column grouping is designed to speed to the model training process. 

ML․NET is designed to handle vector columns efficiently, and is less efficient with a large number of independently named columns. Grouping also help make cleaner code by not listing 1M columns independently.

More info on efficiency:
https://github.com/dotnet/machinelearning/blob/04dda55ab0902982b16309c8e151f13a53e9366d/docs/code/IDataViewTypeSystem.md#vector-types

Columns of the same type/purpose can be merged into a single vector column.

If you're manually calling `InferColumns()`, you can directly control `groupColumns` true/false: 
https://github.com/dotnet/machinelearning/blob/04dda55ab0902982b16309c8e151f13a53e9366d/src/Microsoft.ML.AutoML/API/AutoCatalog.cs#L217-L218

Grouping code:
https://github.com/dotnet/machinelearning/blob/04dda55ab0902982b16309c8e151f13a53e9366d/src/Microsoft.ML.AutoML/ColumnInference/ColumnGroupingInference.cs#L45-L82

**Comment by iluveu28** [comment]
Thanks for the explanations for the grouping. So Ive turned grouping off by setting it to false and now there's no more errors thrown. However, the prediction results returned a list of integer values of zeros. What could be the issue here?

**Comment by justinormont** [comment]
@iluveu28: Are you able to post your dataset and code? If so, @michaelgsharp may have time to look find the cause.

What's the datatype of your label?

**Comment by justinormont** [comment]
> OK it's a kubernetes solution and uses DB so give me some time to port over only the necessary codes into a small console app. Where would you like me to upload them?

Posting in a new GitHub repo lets us easily look through the code/dataset, and link directly to the code. Some folks alternatively post a zip file to the issue.

**Comment by iluveu28** [comment]
So I ported the logics into a console app and they work just fine. I dont know why it doesnt work inside the Docker containers but I will troubleshoot and create a new ticket if I need further assistance. It would be good if ML.Net could throw a meaningful error rather than returning all empty results. Thanks for your help.

**Comment by michaelgsharp** [comment]
@iluveu28 if you can figure out the cause we can figure out where we need to add the meaningful error.
