### ISSUE TITLE
What are the differences between the FastTree and LightGBM algorithm used by ML.Net?

### ISSUE THREAD

**Issue by Glenn-jpg** [dotnet/machinelearning#5786]
I was referred to ask this question here by @justinormont and I was also wondering if @guolinke could assist in answering. 

For my master thesis, I am using the ML.Net library with the model builder to build machine learning models for regression / to predict values. My field of study is in constructional mechanics, so I'm rather new to machine learning.

For most of my models, tree-based regression algorithms seem to be the best performing, and of these LightGBM and FastTree are the best performing algorithms.

I've tried to read up on LightGBM here: https://www.microsoft.com/en-us/research/publication/lightgbm-a-highly-efficient-gradient-boosting-decision-tree/ And FastTree here: https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.fasttree.fasttreeregressiontrainer?view=ml-dotnet

However, I struggle to distinguish what the difference between these algorithms is. Could someone explain what the difference between LightGBM and FastTree is?

**Comment by luisquintanilla** [comment]
Thanks for the question. 

Here is some information on trainers that may be helpful. #5298 and https://learn.microsoft.com/dotnet/machine-learning/how-to-choose-an-ml-net-algorithm

Closing this issue.
