### ISSUE TITLE
IDataView for experiments with AutoML

### ISSUE THREAD

**Issue by ndgroth** [dotnet/machinelearning#5793]
### System information

- **OS version/distro**: Win10
- **.NET Version (eg., dotnet --info)**:  .NET Core 3.1

### Issue

- **What did you do?**
I am adapting the AutoML sample to fit my purpose. Everything works fine if I place my data in a CSV file, but in case, the data is already in memory as a List<DataPoint> because I am calculating Features. So instead of saving that to a CSV file and loading it back in again, I replaced this line:
**TrainDataView = textLoader.Load(TrainDataPath);**
with:
**TrainDataView = mlContext.Data.LoadFromEnumerable<DataPoint>(Data);**

Both are IDataViews, so I am guessing it should work. For the time being, I kept the ColumnInference working from the CSV file. But the regression fails.

Is there a way to avoid saving/loading data?

- **What happened?**
=============== Running AutoML experiment ===============
#########################################################
Running AutoML regression experiment...
Press any key to stop the experiment run...
|     Trainer                             RSquared Absolute-loss Squared-loss RMS-loss  Duration                 |
|1    SdcaRegression                           NaN          0.00         0.00     0.00      15.8                 |
1 models were returned after 15.92 seconds

- **What did you expect?**
=============== Running AutoML experiment ===============
#########################################################
Running AutoML regression experiment...
Press any key to stop the experiment run...
|     Trainer                             RSquared Absolute-loss Squared-loss RMS-loss  Duration                 |
|1    SdcaRegression                      -554.7830        460.07    368733.51   588.39       3.0                |
|2    LightGbmRegression                  -151.0080        436.38    625374.63   702.75       1.3                |
|3    FastTreeRegression                  -54.9780        267.71    287578.01   484.74       2.7                 |
|4    FastTreeTweedieRegression            -1.6479        215.75    278471.13   450.67       1.2                 |
|5    FastForestRegression                -32.4529        343.83    540098.80   627.91       1.8                 |
|6    LbfgsPoissonRegression              -20.8898       1102.84  50035704.04  3150.17       0.9

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by michaelgsharp** [comment]
Have you compared the schema of the 2 data frames?

**Comment by RGSCSolutions** [comment]
> 
> 
> Have you compared the schema of the 2 data frames?

Thank you @michaelgsharp, I had an issue with the schema. All good now.

**Comment by ndgroth** [comment]
> 
> 
> Have you compared the schema of the 2 data frames?

Thank you @michaelgsharp, I had an issue with the schema. All good now.
