### ISSUE TITLE
some symbols not found on symweb

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning#5817]
Use symchk to check if symbols are available on symweb and the check fails
> "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\symchk.exe" /v /s SRV*http://symweb /r \\MININT-DKPV3QG\Users\xiaoyuz\Desktop\PackageAssets\PackageAssets  

![image](https://user-images.githubusercontent.com/16876986/119903059-ff592380-befc-11eb-8c6a-0d28d83c65fe.png)

check this [link](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/using-symchk) to install symchk,

**Comment by michaelgsharp** [comment]
Closing now that #5816 is closed.
