### ISSUE TITLE
Support Parquet data format

### ISSUE THREAD

**Issue by cosmincatalin** [dotnet/machinelearning#582]
Is there a way to use [Apache Parquet](https://parquet.apache.org/) file format? If so, is there and example somewhere or can someone provide one?

**Comment by jwood803** [comment]
Hey, @cosmincatalin! There is the [ParquetLoader](https://github.com/dotnet/machinelearning/blob/5e0a40ed0e80b90fdcb42df474c146087499dc43/src/Microsoft.ML.Parquet/ParquetLoader.cs) that looks like it should do what you want. I'll mess with it some to try to get you an example 😄

**Comment by jwood803** [comment]
Sorry for the delay @cosmincatalin. I'm afraid the `ParquetLoader` seems to not be available in the current 0.3 version but I think it would be in the next release.

I did try to mess with it in a test project within the solution and I got the below. Apologies that it's a bit incomplete, but wanted to give a small update.

```csharp
string dataPath = GetDataPath("QuotingData.csv");

using (var enviornment = new TlcEnvironment())
{
    ParquetLoader.Create(enviornment, new ModelLoadContext(null), new MultiFileSource(dataPath));
}
```

I'm not sure yet what all I need to do to fill in the constructor for `ModelLoadContext` (or even if that's correct or best to use `ModelLoadContext.LoadModel`). 

I'll continue to play around with it, but hopefully one of the other folks can also chime in with a better response than what I have for you.

**Comment by jwood803** [comment]
@cosmincatalin, I think @codemzs beat me to adding an example with the `ParquetLoader` at https://github.com/dotnet/machinelearning/pull/757.

**Comment by cosmincatalin** [comment]
The test in the PR, does not make a lot of sense to me. I'm sure it's fine and great, it's only that I don't know how to make use of it. To make things more clear, what I'm looking for is an example where I replace this

```
pipeline.Add(new TextLoader(DataPath).CreateFrom<DataSchema>(useHeader: true, separator: ','));
```

with something like this:

```
pipeline.Add(new ParquetLoader(DataPath).CreateFrom<DataSchema>());
```

**Comment by Zruty0** [comment]
We already have the loader code, but we haven't promoted it to the public surface (samples, docs, tests etc.)

**Comment by aloneguid** [comment]
Hey everyone, I'm an author of Parquet.Net lib (the one you're using for loading parquet files). I can see you're still using version 2 whereas we've released v3 which is way faster (uses memory pools and Span<T>) consumes considerably less memory and CPU and has tons of bugfixes. I'd be really happy to contribute to mldotnet and make any fixes where appropriate.

**Comment by Ivanidzo4ka** [comment]
I'm not sure we have enough time to squeeze Parquet loader into our tight schedule before 1.0 release. Yes we have loader bits, and they work, but we don't have proper way to expose it right now as part of our API.

/cc @shauheen  and @glebuk  to correct me if I'm wrong regarding current schedule.

**Comment by MelnikovIG** [comment]
> I'm not sure we have enough time to squeeze Parquet loader into our tight schedule before 1.0 release. Yes we have loader bits, and they work, but we don't have proper way to expose it right now as part of our API.
> 
> /cc @shauheen and @glebuk to correct me if I'm wrong regarding current schedule.

Hello, so where can i find a simple example of loading data from parquet? Maybe there is some workaround with 3rd party parquet readers like https://github.com/elastacloud/parquet-dotnet

**Comment by MelnikovIG** [comment]
@aloneguid Hi, do you have a solution with sample how to use you new version as data source for ML.NET?

**Comment by codemzs** [comment]
https://github.com/dotnet/machinelearning/tree/master/src/Microsoft.ML.Parquet
