### ISSUE TITLE
Exponential Curve Fitting

### ISSUE THREAD

**Issue by absinghal** [dotnet/machinelearning#5841]
Have a set of XY data and would like to fit them on an exponential curve as below

a + b * Math.Exp(-x / c)

Which regression trainer class can be used to get the value of a,b,c ?

**Comment by absinghal** [comment]
Solved by #ChatGPT.

**Comment by absinghal** [comment]
Solved by #ChatGPT

**Comment by xiaomao0o0o0o** [comment]
Is it complex to solve the problem ?I meet the problem recently and hardly find answer with google . I just know GSL can solve it but the source code is too long and difficult to learn.
