### ISSUE TITLE
Error occurred when training the model

### ISSUE THREAD

**Issue by z2hteam** [dotnet/machinelearning#5862]
**System Information:**
 - OS & Version: Windows 10 v21H1 and Windows 11 v21H2
 - ML.NET Version: ML.NET v1.5.5, v1.3.1
 - .NET Version: NET 5.0

**Describe the bug**
I train ML to recognize images. After doing the training (the process may not be complete) the following error is encountered:

   ```
   at NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages(Project project)
   at Microsoft.ML.ModelBuilder.Utils.CodeGenerationUtilities.<InstallNugetPackageAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<UpdateNugetDependenciesAsync>d__109.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<GenerateCodeBehindFilesAsync>d__108.MoveNext()
```
![image](https://user-images.githubusercontent.com/78490340/123821259-72532100-d925-11eb-9093-3617598587c2.png)

I then close the error message window, and move on to the next step to test the results after training. The results achieved are expected, perfect.

![image](https://user-images.githubusercontent.com/78490340/123806692-619cae00-d919-11eb-9f4c-52615347b827.png)

But when I run the code, it gives an error
![image](https://user-images.githubusercontent.com/78490340/123821703-d5dd4e80-d925-11eb-95dc-0f0c90117c8a.png)

![image](https://user-images.githubusercontent.com/78490340/123821877-fad1c180-d925-11eb-8053-102415ca3a99.png)

![image](https://user-images.githubusercontent.com/78490340/123822279-569c4a80-d926-11eb-8a0a-797bcf215cca.png)

Then I downgraded "SciSharp.TensorFlow.Redist" version 2.5.0 to 2.3.1 then the following error occurs

![image](https://user-images.githubusercontent.com/78490340/123822480-89464300-d926-11eb-9676-46bc867fb91c.png)

There seems to be something wrong with the training of the model, I don't know where to start yet. Please tell me how to fix it

**Comment by nhannt201** [comment]
Try uninstalling the current version of SciSharp.TensorFlow.Redist and install a lower version. Specifically, 1.14.0 or 2.1 then proceed to Train again. You also need to make sure your data is valid and not null.

I'm not sure but I've glimpsed from the source that newer versions of SciSharp.TensorFlow.Redist has changed a few structures while VS's current ML.NET version hasn't updated the changes there.

I found an answer related to your problem on StackOverflow. You can watch it here: https://stackoverflow.com/questions/58549580/unable-to-load-dll-tensorflow-or-one-of-its-dependencies-ml-net

**Comment by michaelgsharp** [comment]
Thanks @nhannt201 for your comment. Since you found the answer I am going to close this issue.

@z2hteam if you have any more issues please feel free to re-open this issue or create a new one.
