### ISSUE TITLE
ML.Net and Video Recognition

### ISSUE THREAD

**Issue by T3rr0rByte13** [dotnet/machinelearning#5864]
I'm looking for a way to do on the fly video recognition, based on an image recognition NN from ML.Net

I would love to see a easy solution to this problem, I have explored the internet for a way to convert a frame of a video feed and have that passed into a byte array to generate a Bitmap, this would be at least a start to the solution. Even better is if I could feed a video into the NN using a small amount of code and then have the NN spit out a frame by frame evaluation of the video. I understand that the NN may not be able to keep up with the processing and would be satisfied if I could get 1 frame per second recognized.

My Application is to do on the fly car recognition, and have it spit out the make and model of the car as well as other technical statistics about the car it is recognizing.

**Comment by luisquintanilla** [comment]
Hi @T3rr0rByte13,

You can take a look at this sample for integrating object detection into .NET apps https://github.com/dotnet/machinelearning-samples/tree/main/samples/csharp/end-to-end-apps/ObjectDetection-Onnx

For training, you can use Model Builder https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder

https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification-api-transfer-learning

or the API for a code-first approach

https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-onnx

**Comment by T3rr0rByte13** [comment]
This is very helpful, especially the first link, should show me how to get frames to images... Thanks!!
