### ISSUE TITLE
Is Intel-Tensorflow supported in ML.NET?

### ISSUE THREAD

**Issue by peiwenhuang27** [dotnet/machinelearning#5875]
**Is your feature request related to a problem? Please describe.**
I have a model that is trained under native Tensorflow 2.4 Keras Python environment, and I used Intel® Low Precision Optimization Tool (https://github.com/intel/lpot) to quantize my model into a frozen pb model, which then will be put into ML.NET for real-time inference.
However, this model cannot be run in native Tensorflow environment, without **Intel-Tensorflow** being installed (https://github.com/Intel-tensorflow/tensorflow). This error, I suspect, is specifically because some quantization related nodes are deprecated by Tensorflow and yet still used by Intel.
So my guess is the model also can't be loaded in ML.NET with only Tensorflow support.
Is Intel-Tensorflow supported in ML.NET? If no, I think this feature should be added as more people are using quantization tools nowadays, and this use case is likely to become prevalent in the future. 

**Describe the solution you'd like**
As similar to how Tensorflow is supported, with additional functions supporting Intel-Tensorflow.

**Describe alternatives you've considered**
I tried to make the model compatible in pure Tensorflow environment without Intel-Tensorflow, so that it should be able to be run in ML.NET. But so far I haven't found a way to achieve that.

**Comment by justinormont** [comment]
Intel's LPOT looks to have strong ONNX support. 

A LPOT [example](https://github.com/intel/lpot/tree/master/examples/onnxrt/object_detection/ssd_mobilenet_v1) converts the TF model to ONNX, then LPOT runs on the ONNX model to try model compression techniques. The linked example seems to only try quantization. Working on a pre-trained (and ONNX converted) model precludes LPOT from trying quantization aware training, which I would prefer; it could try pruning, mixed precision, teacher-student model distillation, etc for a pre-trained model; perhaps other techniques could be enabled. 

Additional routes would be converting to ONNX after LPOT runs on the TensorFlow model; using the model compression techniques [built into](https://www.onnxruntime.ai/docs/how-to/quantization.html) ONNX; or using the model compression techniques [built into](https://www.tensorflow.org/lite/performance/model_optimization) TensorFlow.

ML․NET has an ONNX runner; assuming the versions are all compatible, the model should run. To run an ONNX model in ML․NET, see: [ApplyOnnxModel()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.onnxcatalog.applyonnxmodel?view=ml-dotnet).

**Comment by peiwenhuang27** [comment]
Thank you so much, I will look into the details further!

**Comment by luisquintanilla** [comment]
Closing this issue since an answer was provided.
