### ISSUE TITLE
Manually applying ColumnCopier to be able to use OnnxConverter

### ISSUE THREAD

**Issue by keeed** [dotnet/machinelearning#588]
How do I manually apply the ColumnCopier to the "taxi-fare-train.csv" test data from here [https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/taxi-fare](url) so that I can export the PredictionModel using the OnnxConverter?

**Comment by codemzs** [comment]
please see this sample https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/CopyColumns.cs
