### ISSUE TITLE
AutoMl.Net 0.18.0, Minor breaking change

### ISSUE THREAD

**Issue by aforoughi1** [dotnet/machinelearning#5880]
**System Information (please complete the following information):**
 - 
 - AutoML.NET Version: version 0.18.0
 
**Describe the bug**
 ExperimentSettings property CacheDirectory is renamed to CacheDirectoryName
The change is minor. The release notes, ML.Net version 1.6, doesn't lists enhancements for this component.
Could you please provide if available?

**Comment by ericstj** [comment]
I believe AutoML is still in preview and we reserve may still make breaking changes each release.  Is this correct @michaelgsharp @eerhardt?  If not, we should set up API Compat to catch these.

Change that introduced this: https://github.com/dotnet/machinelearning/pull/5782

**Comment by eerhardt** [comment]
> I believe AutoML is still in preview and we reserve may still make breaking changes each release.

Correct. The versioning scheme used for "unstable" APIs is `0.X.Y`, which `Microsoft.ML.AutoML` has.. AutoML hasn't been released as a "stable" API yet, like some of the other Microsoft.ML packages. The "stable" packages have a major version `>= 1`. You can see the list of stable packages here:

https://github.com/dotnet/machinelearning/blob/d6f79221007b34e4f257b338f750bb3fe9bc88e0/eng/BranchInfo.props#L3-L23

**Comment by ericstj** [comment]
Thanks @eerhardt in that case I will close this as by-design.
