### ISSUE TITLE
cant find version 1.6 document in Microsoft docs

### ISSUE THREAD

**Issue by behroozbc** [dotnet/machinelearning#5886]
**System Information (please complete the following information):**
 - OS & Version: Windows 10 
 - ML.NET Version:  ML.NET v1.6
 - .NET Version: .NET 5.0

**Describe the bug**
hi 
in [Microsoft docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml?view=ml-dotnet) site cant find version 1.6 in version selection and default is 1.5.5 
![image](https://user-images.githubusercontent.com/20381616/126855315-4686c988-4e92-474e-9032-cf0e0e1bec26.png)

**To Reproduce**
1. Open [this](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml?view=ml-dotnet) web page with edge 92
2. in version selection try to find version 1.6

**Expected behavior**

have version 1.6 and selected by default  

**Screenshots, Code, Sample Projects**
![image](https://user-images.githubusercontent.com/20381616/126855359-7b58dfaa-fe33-4d7e-9dc7-b1e73540b870.png)

**Comment by luisquintanilla** [comment]
Hi @behroozbc 

Thanks for raising this issue. We were still in the process of publishing them. You should be able to see them now. Let us know if you have any other issues.

https://docs.microsoft.com/en-us/dotnet/api/?view=ml-dotnet

**Comment by behroozbc** [comment]
Hi @luisquintanilla  
Thanks 
I see it
