### ISSUE TITLE
What is the future direction of ML.NET?

### ISSUE THREAD

**Issue by seabluescn** [dotnet/machinelearning#5904]
What is the future direction of ML.NET? Will it develop into a framework like Tensorflow or Torch? At present, it is still difficult to develop neural network-related programs through C#.

**Comment by ToKraTheSecond** [comment]
@seabluescn you can find some answers here https://github.com/dotnet/machinelearning/blob/main/ROADMAP.md

**Comment by ToKraTheSecond** [comment]
It is also discussed in #480
