### ISSUE TITLE
Possible Good First Issues

### ISSUE THREAD

**Issue by GFIGroup** [dotnet/machinelearning#5908]
Hello, we are a group of researchers developing machine learning techniques to locate issues suitable for newcomers, and our model consider the following issues as likely "good first issues"

#5890 #5894 #5898 #5899 #5906

May we recommend you to label them as "good first issue" so newcomers know where to choose?

Thank you!

**Comment by michaelgsharp** [comment]
Thanks for suggesting those. I have gone ahead and added the tag to 3 of the 5. One that I didn't already is a work in progress, the other is a deployment issue.

Closing this issue as the tag has been added. Thanks!
