### ISSUE TITLE
Error with Model Builder and ML.net 1.6.0

### ISSUE THREAD

**Issue by fhtino** [dotnet/machinelearning#5914]
**System Information (please complete the following information):**
 - OS & Version: Windows 10
 - ML.NET Version: ML.NET v1.6.0
 - .NET Version: .NET 3.1
 - VS2019: 16.11.2
 - Model Builder: 16.6.3.2136603 

**Describe the bug**
After training, Model Builder creates .consumption.cs and .training.cs files. 
If my project references ML.net 1.5.5 everything works fine.
If my project references ML.net 1.6.0, I get errors. It seems that Model Builder tries to install ML.NET 1.5.5 and fails doing that.
Perhaps Model Builder is not (still) compatible with ML 1.6.0?

**Expected behavior**
Model Builder should not try to install 1.5.5

**Screenshots**

![Capture_MB_issue_2](https://user-images.githubusercontent.com/637401/130934825-0e24195f-0366-4b11-98f5-41db8eb78450.PNG)

![Capture_MB_issue_3](https://user-images.githubusercontent.com/637401/130934839-6a66b839-e1db-42ce-9d13-ed61aa3b3db1.PNG)

**Comment by michaelgsharp** [comment]
I know the release of model builder is here pretty soon, so I will go ahead this issue and let it be tracked in the model builder repo.
