### ISSUE TITLE
Sliders doesn't start from min value in case of non-zero values

### ISSUE THREAD

**Issue by MiroslavKabat** [dotnet/machinelearning#5944]
**Describe the bug**
Slider doesn't start from minimum value in case of non-zero values. 

**To Reproduce**
Go to [Ant **Blazor** component page](https://antblazor.com/en-US/components/slider) and look at:
![image](https://user-images.githubusercontent.com/34449536/134791200-5aa6b3a4-d298-4582-bab2-e726661a4544.png)

**Expected behavior**
Go to [Ant **Design** component page](https://ant.design/components/slider/) and look at:
![image](https://user-images.githubusercontent.com/34449536/134791236-b12d2882-7844-4699-9f7e-d960d7171bb5.png)

**Additional context**
It should be nice to sync look of **Ant Blazor** & **Ant Design**. This behavior is little bit confusing.

**Comment by MiroslavKabat** [comment]
Pardon me. I put issue to wrong project.

**Comment by MiroslavKabat** [comment]
Please admin to permanently delete this issue if possible. Thank you.

**Comment by michaelgsharp** [comment]
@MiroslavKabat Deleting the issue per your request.
