### ISSUE TITLE
Not able to specify if a Feature is Categorical or Continuous

### ISSUE THREAD

**Issue by jjkcharles** [dotnet/machinelearning#5960]
### System information

- **OS version/distro**: Windows 
10
- **.NET Version (eg., dotnet --info)**: 
5 
- **Visual Studio Version**: 
Microsoft Visual Studio 2019

### Issue

- **What did you do?**
Trying to pull data through ML .Net Model Builder, and choosing the Labels and Features for building a Regression Model (Value Prediction Scenario).
- **What happened?**
I have evaluated ML.Net Model Builder in the past where it allowed me to choose a Data File, select the Label, and Features. And, as part of the Features, I remember selecting "Advanced" and choosing which Features are Categorical or which ones are Continuous values. This was at least 6 weeks ago. 
Now I am trying to do the same, but see the options have changed a little bit, and there is no option for me to specify which Features are categorical vs which ones are continuous values.
- **What did you expect?**
Expected to be able to specify which Features are categorical vs which ones are continuous values, at the time of configuring Data in Model Builder Wizard.

### Source code / logs
Screenshot below,
![image](https://user-images.githubusercontent.com/1765598/136334882-03fc185c-3233-4a31-9e3d-2565fd142e78.png)

**Comment by michaelgsharp** [comment]
@JakeRadMSFT are you able to move this to the model builder repo?

**Comment by JakeRadMSFT** [comment]
I'm not able to ...

@jjkcharles 

What version of  Model Builder do you have installed? It looks like you might have an old one.

Is the Advanced Options not showing up for you?

![image](https://user-images.githubusercontent.com/31937616/136471485-7d076088-6f88-49c6-878a-ab83ffcbec50.png)

**Comment by jjkcharles** [comment]
@JakeRadMSFT Below is my what I get in Individual components,

![image](https://user-images.githubusercontent.com/1765598/136633317-2584b704-f054-45ae-ba8f-3df215c38abe.png)

Strangely, the "Advanced " option works in Data Tab of Model Builder now. I did fiddle around with the Components multiple times trying to uninstall and reinstall already installed components. But none seemed to have worked last night. But, boom it all looks OK now. And, I haven't even rebooted Windows of Visual Studio since the last time I found Model Builder not working as expected.

For what its worth, I recently installed VS 2022 Preview on my machine (about 3 weeks back) - and have a feeling thats what might have caused this issue.

Also, can you elaborate on the in-box version vs Extension - I don't remember installing it any other way other than the VS installer.

One different I notice though is you have the Model Builder (under .NET) unchecked whereas mine is checked.

Thanks for taking the time to check on this!
