### ISSUE TITLE
Q: How to add a missing column to DataView?

### ISSUE THREAD

**Issue by torronen** [dotnet/machinelearning#5967]
I am reading to a DataView with TextLoader and column inference. My dataset is missing some columns (boolean, in my case) that are expected by the ML.NET model. I would like to add all 0's or false's for this column and then run the prediction. 

I can only find how to add missing values based on another column. In this case, I dont have any other column to copy with appended missing values. 

I can find DropColumn method, but not AddColumn method. Is there some way to add columns with constant values with transformers or other way to IDataView?

**Comment by eerhardt** [comment]
One option might be to use a `CustomMapping` which just always adds the `false` column.

See https://docs.microsoft.com/dotnet/api/microsoft.ml.custommappingcatalog.custommapping and  https://www.youtube.com/watch?v=TEnQp5qtopo for how to create one.

**Comment by michaelgsharp** [comment]
@torronen I'm going to close this for now at is seems you have the answer you need. If you have more questions feel free to reopen as needed.
