### ISSUE TITLE
AutoML.NET RegressionTrainer is missing RegressionTrainer.Gam  

### ISSUE THREAD

**Issue by BarryTaj** [dotnet/machinelearning#5969]
Looks like there's no (Gam Trainer) RegressionTrainer.Gam  in the Microsoft.ML.AutoML public enum RegressionTrainer as in Microsoft.ML.Trainers.FastTree;.

...
public static GamRegressionTrainer Gam(this RegressionCatalog.RegressionTrainers catalog, GamRegressionTrainer.Options options);
...

 

#region Assembly Microsoft.ML.AutoML, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
// C:\Users\*****\.nuget\packages\microsoft.ml.automl\0.18.0\lib\netstandard2.0\Microsoft.ML.AutoML.dll
#endregion

namespace Microsoft.ML.AutoML
{
    //
    // Summary:
    //     Enumeration of ML.NET multiclass classification trainers used by AutoML.
    public enum RegressionTrainer
    {
        //
        // Summary:
        //     See Microsoft.ML.Trainers.FastTree.FastForestRegressionTrainer.
        FastForest = 0,
        //
        // Summary:
        //     See Microsoft.ML.Trainers.FastTree.FastTreeRegressionTrainer.
        FastTree = 1,
        //
        // Summary:
        //     See Microsoft.ML.Trainers.FastTree.FastTreeTweedieTrainer.
        FastTreeTweedie = 2,
        //
        // Summary:
        //     See Microsoft.ML.Trainers.LightGbm.LightGbmRegressionTrainer.
        LightGbm = 3,
        //
        // Summary:
        //     See Microsoft.ML.Trainers.OnlineGradientDescentTrainer.
        OnlineGradientDescent = 4,
        //
        // Summary:
        //     See Microsoft.ML.Trainers.OlsTrainer.
        Ols = 5,
        //
        // Summary:
        //     See Microsoft.ML.Trainers.LbfgsPoissonRegressionTrainer.
        LbfgsPoissonRegression = 6,
        //
        // Summary:
        //     See Microsoft.ML.Trainers.SdcaRegressionTrainer.
        StochasticDualCoordinateAscent = 7
    }
}

**Comment by luisquintanilla** [comment]
Closing this issue since it relates to the old implementation of AutoML API
