### ISSUE TITLE
Loading pkl files?

### ISSUE THREAD

**Issue by agr** [dotnet/machinelearning#5973]
### System information

- **OS version/distro**: Windows 10 21H1
- **.NET Version (eg., dotnet --info)**: .NET 5

### Issue

- **What did you do?** Trained a text classification model using Azure AutoML. Trying to find a way to use it in ML.NET
- **What happened?** Azure AutoML produced a model and exports it as .pkl file (I don't see any other options), that I can't figure out how to make it usable in my .NET code. The model works fine in Python, but I need it in .NET.
- **What did you expect?** Some straightforward way of using the Azure AutoML output.

Any suggestions? Do I need to convert .pkl to something else first? How?

**Comment by JakeRadMSFT** [comment]
Converting to ONNX should be the way to go! If you have any difficulties we might be able to ask them to generate an ONNX model for you.

**Comment by agr** [comment]
OK, it is the `enable_onnx_compatible_models` option of `AutoMLConfig` and can only be set if I create an experiment manually using Python. Welp, thanks for looking into it, I'll go fiddle with Python then.
