### ISSUE TITLE
"zsh: killed ~/.dotnet/tools/mlnet" on M1 Mac

### ISSUE THREAD

**Issue by AlexChesser** [dotnet/machinelearning#5978]
**System Information (please complete the following information):**
 - OS & Version: macOS Big Sur 11.4. (Apple M1 chipset)
 - ML.NET Version: mlnet 16.2.0  
 - .NET Version: 6.0.100-preview.3.21202.5

**Describe the bug**
When I try to run command line MLNET on my M1 Mac it fails immediately with the message

`zsh: killed ~/.dotnet/tools/mlnet` 

example command: `~/.dotnet/tools/mlnet --version`

**To Reproduce**
1. install dotnet using package installer
2. install mlnet tools `dotnet tool install -g mlnet`
3. type `~/.dotnet/tools/mlnet --version` in a terminal window  
4. `zsh: killed ~/.dotnet/tools/mlnet` 

**Expected behavior**

Expected a report of the MLNET version.

Also expected: this functionality would generalize to the actual execution of an ML training protocol on the command line.

**Screenshots, Code, Sample Projects**
n/a

**Additional context**

Note that the goal of this is not necessarily to JUST fix the version, these failures also happen when trying to run a longer command like 

`~/.dotnet/tools/mlnet classification --dataset .\pre-cleaned-data.csv --has-header true --label-col 1 --train-time 60`

but debugging that would require a sample file be provided.

**Comment by AlexChesser** [comment]
Thanks so much for the quick response @briacht unfortunately it still doesn't seem to work.

the updated version of the tool installed as expected after I updated the command line to include a space.
I also upgraded the verbosity of the installation command to capture any useful information, but there were no errors, warnings or anything of issue.

```
alexchesser@Alexs-MBP ~ % dotnet tool install -g microsoft.ml.modelbuilder.cli.osx --version 16.8.3 --add-source https://mlnetcli.blob.core.windows.net/mlnetcli/index.json -v n
Build started 2021-10-18 10:11:14 PM.
     1>Project "/var/folders/r6/zrj0b9_15_v5y_hrkzmcvfrm0000gn/T/oq2bzavw.nsf/restore.csproj" on node 1 (Restore target(s)).
     1>_GetAllRestoreProjectPathItems:
         Determining projects to restore...
       Restore:
         Restoring packages for /var/folders/r6/zrj0b9_15_v5y_hrkzmcvfrm0000gn/T/oq2bzavw.nsf/restore.csproj...
           GET https://api.nuget.org/v3-flatcontainer/microsoft.ml.modelbuilder.cli.osx/index.json
           NotFound https://api.nuget.org/v3-flatcontainer/microsoft.ml.modelbuilder.cli.osx/index.json 41ms
           GET https://mlnetcli.blob.core.windows.net/mlnetcli/flatcontainer/microsoft.ml.modelbuilder.cli.osx/index.json
           OK https://mlnetcli.blob.core.windows.net/mlnetcli/flatcontainer/microsoft.ml.modelbuilder.cli.osx/index.json 119ms
           CACHE https://mlnetcli.blob.core.windows.net/mlnetcli/flatcontainer/microsoft.ml.modelbuilder.cli.osx/16.8.3/microsoft.ml.modelbuilder.cli.osx.16.8.3.nupkg
         Installed Microsoft.ML.ModelBuilder.CLI.OSX 16.8.3 from https://mlnetcli.blob.core.windows.net/mlnetcli/index.json with content hash T0PdDYc+GuTs3ivo6xE75iW+FyKodR6H9OEr0a7BAEn2HmYnCv+ayQ4BtDM15APQeY7AU+uxOHie5+ySODpVUg==.
         Committing restore...
         Generating MSBuild file /Users/alexchesser/.dotnet/tools/.store/.stage/5tn2siqj.npm/restore.csproj.nuget.g.props.
         Writing assets file to disk. Path: /Users/alexchesser/.dotnet/tools/.store/.stage/5tn2siqj.npm/project.assets.json
         Restored /var/folders/r6/zrj0b9_15_v5y_hrkzmcvfrm0000gn/T/oq2bzavw.nsf/restore.csproj (in 3.13 sec).
         
         NuGet Config files used:
             /Users/alexchesser/.nuget/NuGet/NuGet.Config
         
         Feeds used:
             https://api.nuget.org/v3/index.json
             https://mlnetcli.blob.core.windows.net/mlnetcli/index.json
         
         Installed:
             1 package(s) to /var/folders/r6/zrj0b9_15_v5y_hrkzmcvfrm0000gn/T/oq2bzavw.nsf/restore.csproj
     1>Done Building Project "/var/folders/r6/zrj0b9_15_v5y_hrkzmcvfrm0000gn/T/oq2bzavw.nsf/restore.csproj" (Restore target(s)).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:04.06
Tools directory '/Users/alexchesser/.dotnet/tools' is not currently on the PATH environment variable.
If you are using zsh, you can add it to your profile by running the following command:

cat << \EOF >> ~/.zprofile
# Add .NET Core SDK tools
export PATH="$PATH:/Users/alexchesser/.dotnet/tools"
EOF

And run `zsh -l` to make it available for current session.

You can only add it to the current session by running the following command:

export PATH="$PATH:/Users/alexchesser/.dotnet/tools"

You can invoke the tool using the following command: mlnet
Tool 'microsoft.ml.modelbuilder.cli.osx' (version '16.8.3') was successfully installed.
alexchesser@Alexs-MBP ~ % export PATH="$PATH:/Users/alexchesser/.dotnet/tools"
alexchesser@Alexs-MBP ~ % mlnet
zsh: killed     mlnet
alexchesser@Alexs-MBP ~ % mlnet --version
zsh: killed     mlnet --version
alexchesser@Alexs-MBP ~ % dotnet tool list -g
Package Id                             Version      Commands     
-----------------------------------------------------------------
amazon.lambda.tools                    5.1.4        dotnet-lambda
microsoft.ml.modelbuilder.cli.osx      16.8.3       mlnet        
alexchesser@Alexs-MBP ~ % 
```

**Comment by LittleLittleCloud** [comment]
Hmmm it works on my m1 mbp,,,  Maybe it's something wrong in global tool? Can you try install it as local tool instead?

You can follow the readme [here](https://github.com/LittleLittleCloud/MLNet-Benchmark) to install mlnet locally. (Before that you need to copy the nuget.config in that repo)

Or it might be the missing of dotnet runtime/SDK? This is what I have on my mbp

```
dotnet --list-sdks

```

**Comment by michaelgsharp** [comment]
On the M1 there isn't a version of .net 5 that is arm64. The only version of .net5 has to run through their rosetta translation. Not entirely sure of the reason why, but ML.NET doesn't work with their rosetta translation (I'm not sure if its a rosetta issue or c# issue or what).

When you run the tool with .net6 and it crashes, can you get the error logs for it?

**Comment by michaelgsharp** [comment]
@AlexChesser I'm wondering if your Rosetta issue is because you have .net6 arm64 installed and .net5 x64 installed. With .net6 installed globally, it going to try and find .net5 that matches its architecture, arm64, which doesn't exist. Would you be able to uninstall all versions of .net6 and try running it again?
