### ISSUE TITLE
Prediction Error: An attempt was made to keep iterating after the pipe has been reset.  

### ISSUE THREAD

**Issue by PaulDMendoza** [dotnet/machinelearning#598]
### System information

- **Windows version**: Windows 10 Pro 10.0.17134
- **.NET Version (eg., dotnet --info)**:  2.1.104
- **ML.NET version**: 0.3

### Issue

- **What did you do?**: Run a prediction by reusing a predictor model. 
![image](https://user-images.githubusercontent.com/1039795/43369838-a86aa910-9329-11e8-8ba6-b80f1d82e65c.png)

I use this code to get the predictor and cache it in the LanguageModel property. I don't want to open a stream every time I need it. 

- **What happened?**: I randomly get this error. I think it has something to do with multiple threads using the same predictor model object instance. 

![image](https://user-images.githubusercontent.com/1039795/43369851-e1a3ff2e-9329-11e8-87e2-21f9aeab85b2.png)

- **What did you expect?**: I expect it not to crash here. Not having to load the zip each time seems like it should make my code faster.

**Comment by alexdegroot** [comment]
Have you tried to do it non-blocking without the .Result?

**Comment by PaulDMendoza** [comment]
@Zruty0  I'm trying to do the prediction in a Kestrel web app where the requests can be processed in parallel. It would be nice if it could be thread safe.

**Comment by Zruty0** [comment]
Like I said, there are multiple strategies one can use to facilitate parallel prediction.
The low-effort ones, in my opinion, are 
1) Use `lock(predictorModel)` statement around `Predict` calls.
2) Make your `predictorModel` a `ThreadLocal` variable.

The first approach minimizes memory at cost of some latency, the second approach minimizes latency at cost of memory.

**Comment by PaulDMendoza** [comment]
Okay, thanks.
