### ISSUE TITLE
Following code fails in .Net Core 5.0 single file application ->Repository.cs ->FileVersionInfo.GetVersionInfo(typeof(RepositoryWriter).Assembly.Location) 

### ISSUE THREAD

**Issue by tankhar** [dotnet/machinelearning#5987]
https://github.com/dotnet/machinelearning/blob/1dfccca85d4ab87f1238b8554e0a49f8f6a20e8e/src/Microsoft.ML.Core/Data/Repository.cs#L288

We are using ML.Net API in our .Net Core Worker service project.
Everything works fine as long as we execute the worker "exe" manually.

In order to use the same as Windows Service, we are publishing the .Net Core exe to **single file** and then using sc.exe to convert this to windows service

When we run the same as windows service (pointing to single file exe)we get following exception when we try to "Save" our trained model:

**CoreCLR Version: 5.0.120.57516
.NET Version: 5.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at Microsoft.ML.RepositoryWriter.CreateNew(Stream stream, IExceptionContext ectx, Boolean useFileSystem)
   at Microsoft.ML.ModelOperationsCatalog.Save(ITransformer model, DataViewSchema inputSchema, Stream stream)**

We found that publishing an app as single file gives following warning(which one can easily miss reading!):
**warning IL3000: 'System.Reflection.Assembly.Location' always returns an empty string for assemblies embedded in a single-file app. If the path to the app directory is needed, consider calling 'System.AppContext.BaseDirectory'.**
  
Which means ModelOperationsCatalog.Save(ITransformer model, DataViewSchema inputSchema, Stream stream) will always fail in .Net Core single file app.

Please let look into and guide us next step, we want to run this as a single file and windows service

**Comment by tankhar** [comment]
Thank you!
I upgraded to to the 1.7.0 preview and the issue is no longer seen.

Thanks again

**Comment by michaelgsharp** [comment]
Glad it was able to resolve your issue! The full 1.7.0 release is out now if you want a full release.

Closing since its resolved.
