### ISSUE TITLE
Enable cross-validation for LearningPipeline

### ISSUE THREAD

**Issue by GalOshri** [dotnet/machinelearning#6]
Cross-validation would make it easier to validate models if the data is not already split into train and test files (and generally helps give more precise metrics). This is already exposed as an entrypoint [here](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML/Runtime/EntryPoints/CrossValidationMacro.cs), but needs to be enabled for LearningPipeline.

**Comment by codemzs** [comment]
@GalOshri This is more than enablement, here we need to extend the entrypoint to support models of type ITransformModel but currently entrypoint for CV only supports models of IPredictorModel. Please refer to PR #212 .
