### ISSUE TITLE
Investigate using ReadOnlySequence<T> to support large array indices.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/machinelearning#601]
The `ReadOnlySequence<T>` type is designed for working with native buffers with lengths greater than `int.MaxValue`. We should investigate using it to support large arrays.

**Comment by Zruty0** [comment]
We'll put it into the backlog for tracking. No action right now is being taken.

**Comment by codemzs** [comment]
I haven't seen scenarios or use cases or bugs where this becomes relevant.
