### ISSUE TITLE
LoadRawImageBytes does not load anything

### ISSUE THREAD

**Issue by atkinsonbg** [dotnet/machinelearning#6011]
**System Information (please complete the following information):**
 - OS & Version: [e.g. Windows 10] 
    - Tested on MacOS 11.6 Big Sur & Windows 11
 - ML.NET Version: [e.g. ML.NET v1.5.5]
    - ML.NET v1.7.0
 - .NET Version: [e.g. .NET 5.0]
    - .NET 6.0

**Describe the bug**
Following the tutorial list here, (https://docs.microsoft.com/en-us/samples/dotnet/machinelearning-samples/mlnet-image-classification-transfer-learning/) and the LoadRawImageBytes does not appear to load images from the directory.

**To Reproduce**

Code used:
```
IEnumerable<ImageData> images = LoadImagesFromCsv("Data/training_data.csv");

            IDataView imageData = mlContext.Data.LoadFromEnumerable(images);
            IDataView shuffledData = mlContext.Data.ShuffleRows(imageData, shuffleSource: true);

            var previewshuffledData = shuffledData.Preview();

            var preprocessingPipeline = mlContext.Transforms.Conversion
                                                .MapValueToKey(
                                                    inputColumnName: "Label",
                                                    outputColumnName: "LabelAsKey")
                                                .Append(mlContext.Transforms.LoadRawImageBytes(
                                                    outputColumnName: "Image",
                                                    imageFolder: "Data/LocalImages",
                                                    inputColumnName: "ImagePath"));

            IDataView preProcessedData = preprocessingPipeline
                    .Fit(shuffledData)
                    .Transform(shuffledData);

            var previewPreprocessedData = preProcessedData.Preview();
```
**previewshuffledData**:
<img width="520" alt="Screen Shot 2021-11-29 at 2 21 21 PM" src="https://user-images.githubusercontent.com/29587193/143929508-5492872f-e716-480f-b894-db5db2814e71.png">

<img width="351" alt="Screen Shot 2021-11-29 at 2 21 41 PM" src="https://user-images.githubusercontent.com/29587193/143929533-07f3190c-ebc3-4f7b-9773-ede190bba339.png">

**previewPreprocessedData**:
<img width="570" alt="Screen Shot 2021-11-29 at 2 21 50 PM" src="https://user-images.githubusercontent.com/29587193/143929573-e441ae02-3743-44c3-a407-c97280a669eb.png">

**Expected behavior**
Expecting to see a RowView after LoadRawImageBytes of 63, which matches the number of images in the dataset.

**Screenshots, Code, Sample Projects**
If applicable, add screenshots, code snippets, or sample projects to help explain your problem.

**Additional context**

**Comment by luisquintanilla** [comment]
@atkinsonbg instead of using the `Preview` method, can you try converting it to an `IEnumerable` and iterate over that?

`var previewPreprocessedData = mlContext.Data.CreateEnumerable(preProcessedData, reuseRowObject:false);`

**Comment by atkinsonbg** [comment]
@luisquintanilla I change it to: `var previewPreprocessedData = mlContext.Data.CreateEnumerable<ImagePredictionInput>(preProcessedData, reuseRowObject: false);`

**Result**
<img width="873" alt="Screen Shot 2021-11-29 at 3 20 13 PM" src="https://user-images.githubusercontent.com/29587193/143937188-9f11dba1-7568-446c-b718-27c89b81d300.png">
:

**Comment by atkinsonbg** [comment]
I pulled the sample code from here: https://github.com/dotnet/machinelearning-samples/tree/main/samples/csharp/getting-started/DeepLearning_ImageClassification_Binary

And that is finding the images just fine:
<img width="742" alt="Screen Shot 2021-11-29 at 3 25 40 PM" src="https://user-images.githubusercontent.com/29587193/143937925-1c474730-cce7-4256-befd-e7f79fc1801b.png">

But this code is so simple, I'm not sure where the breakdown is happening.

**Comment by luisquintanilla** [comment]
@atkinsonbg if you replace the images in the assets directory of the code sample with your own images, does it work?

**Comment by atkinsonbg** [comment]
@luisquintanilla I am so sorry, I have wasted your time today. I found the culprit after running your code, it was in the CSVHelper package found here: https://www.nuget.org/packages/CsvHelper/

Stripping that out and manually creating some input classes:

```
public static IEnumerable<ImageData> LoadImagesFromCsv(string csvPath)
        {
            //TextReader reader = new StreamReader(csvPath);
            //var csvReader = new CsvReader(reader, CultureInfo.CurrentCulture);
            //return csvReader.GetRecords<ImageData>();

            List<ImageData> list = new List<ImageData>();
            list.Add(new ImageData
            {
                ImagePath = "15970_2.jpg",
                Label = "Navy"
            });
            list.Add(new ImageData
            {
                ImagePath = "39386_2.jpg",
                Label = "Blue"
            });
            return list.AsEnumerable();
        }
```

Results in the images being processed:
<img width="766" alt="Screen Shot 2021-11-29 at 4 12 24 PM" src="https://user-images.githubusercontent.com/29587193/143943758-4aec51c7-ee76-40f9-85f5-d6cf100e0524.png">

That's what I get for trying to be fancy. Will parse the CSV another way. Thank you so much for jumping in and taking a look.

**Comment by luisquintanilla** [comment]
@atkinsonbg No problem. Thanks for closing the issue.

**Comment by atkinsonbg** [comment]
Just to follow-up, I was still able to use the CSVHelper package, but needed to change the implementation to the following:

```
public static IEnumerable<ImageData> LoadImagesFromCsv(string csvPath)
        {
            var records = new List<ImageData>();
            using (var reader = new StreamReader(csvPath))
            using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
            {
                csv.Read();
                csv.ReadHeader();
                while (csv.Read())
                {
                    var record = new ImageData
                    {
                        ImagePath = csv.GetField("ImagePath"),
                        Label = csv.GetField("Label")
                    };
                    records.Add(record);
                }
            }

            return records.AsEnumerable();
        }
        ```
        
        Working great now. Thanks again!
