### ISSUE TITLE
Investigate using `readonly struct` and `ref readonly` parameters

### ISSUE THREAD

**Issue by tannergooding** [dotnet/machinelearning#602]
C# added support for explicitly declaring structs as `readonly` and allowing you to pass them and return them while preserving the readonly semantic (`in` and `ref readonly`).

Investigate using this feature, where appropriate, in order to reduce allocations, increase maintainability, and potentially to improve perf.

**Comment by Ivanidzo4ka** [comment]
DRI RESPONSE: Is it still relevant?

**Comment by Zruty0** [comment]
It is. But I don't think we'll make a concerted push to use these language constructs whenever appropriate. Instead, we will be adding them opportunistically as we touch the code. I will close this issue.
