### ISSUE TITLE
TensorFlow/ONNX inference on ARM

### ISSUE THREAD

**Issue by cvergaray** [dotnet/machinelearning#6023]
**Is your feature request related to a problem? Please describe.**
I have a Xamarin, soon to be updated to MAUI, application that we are looking to enhance with some image classification capabilities using ML.Net. The intent is to aid our users in identifying domain-specific objects in photos using their Android or iOS phones. We do not, however, own or maintain the training pipeline and are instead provided with the model in TensorFlow pb format. Adding the ability to make inferences using TensorFlow models would allow us to add the computer vision components using ML.Net.

**Describe the solution you'd like**
Add support for inferencing with TensorFlow on ARM devices.

**Describe alternatives you've considered**
- TensorFlow Lite, but that only works with Xamarin.Android
- Converting the pb to ONNX and then using a custom cross-compiled binary. We haven't tried this, but I suspect it would work

**Comment by luisquintanilla** [comment]
Thanks for the suggestion. ORT introduced the ability to run on Xamarin. This should also work with ML.NET. 

https://devblogs.microsoft.com/xamarin/machine-learning-in-xamarin-forms-with-onnx-runtime/
