### ISSUE TITLE
Investigate using Span<T> and ReadOnlySpan<T>

### ISSUE THREAD

**Issue by tannergooding** [dotnet/machinelearning#604]
The framework recently added support for `Span<T>` and `ReadOnlySpan<T>`, which allow you to efficiently work with arrays, subsets of arrays, and unmanaged memory through a single interface. When working with subsets of arrays, it has the added benefit of not needing to create a copy of said data.

ML should investigate using these types where applicable in order to reduce complexity, improve maintainability, improve perf, and improve interop with other frameworks using these types.

**Comment by Zruty0** [comment]
I think we should close it.
