### ISSUE TITLE
ExperimentBase Execute method should take IProgress instead of Progress

### ISSUE THREAD

**Issue by xenoverse-us** [dotnet/machinelearning#6042]
**Describe the bug**
https://github.com/dotnet/machinelearning/blob/0577957256c296fdea2deb6b6e00e7be9b458167/src/Microsoft.ML.AutoML/API/ExperimentBase.cs#L250

I think the intention here is to take IProgress rather than the concrete implementation of System.Progress.

**Comment by michaelgsharp** [comment]
You are correct, good catch.
