### ISSUE TITLE
Dllnullexception

### ISSUE THREAD

**Issue by shiqiangz-git** [dotnet/machinelearning#6047]
Unab1e to 1oad DLL ' tensorf1ow or one of its dependencies: E);&fH E (DLL) fJx=

**Comment by shiqiangz-git** [comment]
How to solve this problem in the server machine?

**Comment by shiqiangz-git** [comment]
![Uploading 0FD26655-CC90-4C52-8571-3114703291FF.png…]()

**Comment by michaelgsharp** [comment]
You need to make sure that you also get the `SciSharp.TensorFlow.Redist version 2.3.1` (or the gpu version). That will resolve this issue.

Closing for now. Feel free to re-open if this doesn't resolve your issue.

**Comment by shiqiangz-git** [comment]
I installed SciSharp.TensorFlow.Redist version 2.3.1, but it still can't run. I understand that CPU doesn't support Ava instruction set. Is there any other way but to replace CPU?
