### ISSUE TITLE
Building with VS 2022

### ISSUE THREAD

**Issue by torronen** [dotnet/machinelearning#6048]
The build script fails to compile with Visual Studio 2022 (Native libraries). Because it seems upgrade to VS2022 is encouraged (for example, VS2019 Community edition no longer available) I think the build script should be updated to support VS2022.

**Comment by michaelgsharp** [comment]
@torronen the build script works with 2022, at least the latest in master does. I only have 2022 installed on my machine. What is the exact error you are getting.

**Comment by torronen** [comment]
`EXEC : error : Visual Studio 2015, 2017 or 2019 required [Q:\git-kwork-microsoft-ml\Microsoft.ML\src\Native\Native.proj] `

Sorry, might be my mistake, I will update the latest from main and re-try.

**Comment by michaelgsharp** [comment]
Sounds good. The code is found working for 2022 is [here](https://github.com/dotnet/machinelearning/blob/8eac93a0f999acb144478f1b39a321128861acc3/src/Native/build.cmd#L50). I'm going to close this issue for now, but feel free to reopen if needed.
