### ISSUE TITLE
ML Console application throwing native dll not found error

### ISSUE THREAD

**Issue by dev8546** [dotnet/machinelearning#605]
### System information

- **Windows Server 2016**:
- **Dotnet core
I created one Dotnet core application using VS 2017 and then published it and then copied the published folder having runtimes folder and my application dll to Windows server 2016 where I had installed the dotnet core framework.

Even time I run the application from command line I get the below error. (I found this dll is under the runtimes folder but somehow application is not able to load)

 Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.DllNotFoundException: Unable to load DLL 'CpuMathNative' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by tomwar** [comment]
I solved this issue by installing Microsoft Visual C++ 2015 Redistributable Update 3 RC (https://www.microsoft.com/en-us/download/details.aspx?id=52685)

I tried other solutions posted here regarding this problem but for my case my server was missing VCRUNTIME140.dll which is a dependency for CpuMathNative

**Comment by dev8546** [comment]
Yup I have just figured out and installed Microsoft Visual C++ Redistributable for Visual Studio 2017  and just came here and saw your comment @tomwar . 

My problem is solved Thanks a lot

**Comment by PaulDMendoza** [comment]
Oh, this solved my problem. Thanks!
