### ISSUE TITLE
Update Newtonsoft.json to latest version. Does not work in Unity (2021.2.7f1) anymore

### ISSUE THREAD

**Issue by Darth-Carrotpie** [dotnet/machinelearning#6053]
**System Information (please complete the following information):**
 - Windows 10]
 - ML.NET Version: current (via NuGet)
 - .NET Version: Unity (2021.2.7f1) - .NET Standard 2.1

**Describe the bug**
Assemblies throw up. Most cannot load due to errors somewhere.

**To Reproduce**
1. Get Unity (2021.2.7f1)
2. Install NuGet in Unity
3. Get ML.NET via NuGet
4. See errors

**Expected behavior**
Assemblies imported properly.

**Screenshots, Code, Sample Projects**
This is easily reproducible with all 2021 Unity versions.

**Additional context**
A big issue probably is a conflict between Newtonsoft.Json package versions. Unity uses newest, while ML.NET uses a heavily outdated version.
Please update dependencies of this package!

**Comment by michaelgsharp** [comment]
Good to know. I'll do a quick test to see what it would take to update. If its just a simple version update thats pretty easy. If it ends up breaking things though we will have to see what it will take to do.
