### ISSUE TITLE
Upgrade ONNXRuntime to v1.10

### ISSUE THREAD

**Issue by joaocc** [dotnet/machinelearning#6056]
ONNX Runtime has already reached v1.10, with improved opcode support, performance and other very useful features.
We are looking to implement some workloads on ml.net which use later opcodes (v1.6 is more than 2 years old already).
https://github.com/Microsoft/onnxruntime/blob/master/docs/Versioning.md

Upgrade ONNXRutime from v1.6 to v1.10

**Comment by developervariety** [comment]
Along with a possibility on using ONNXv4 exported models from Custom Vision.

**Comment by joaocc** [comment]
Submitted PR https://github.com/dotnet/machinelearning/pull/6057 but CI pipeline wasn't triggered. Anyone know what is required to get the CI to run on the PR? Thx

**Comment by michaelgsharp** [comment]
So I actually did this about 2 weeks ago. PR is already merged into main #6046. So chances are that the CI didn't run because there are no changes to actually go into main. I'll close this issue and the PR, but thanks for taking the time to do this.
