### ISSUE TITLE
NLP in voice /audio

### ISSUE THREAD

**Issue by papyr** [dotnet/machinelearning#6069]
Currently we have some alexa enabled customer care options.

We want to port that to ML.NET , do you have any native language parsers on a voice stream like google or Amazon

**Comment by michaelgsharp** [comment]
Currently we don't support any type of audio. This is something we have talked about though and are aware we need to add.

@luisquintanilla for visibility and triaging.

**Comment by papyr** [comment]
Thanks @michaelgsharp , is there a road map of which ML avenues you are planning.

The issue is that today we are getting deeper with Alexa or GOogle, while our backend is asp core, its hard to maintain all these skillsets. would be great if we could get one platform.

**Comment by michaelgsharp** [comment]
@luisquintanilla for road map info.

**Comment by luisquintanilla** [comment]
Hi @papyr 

Thanks for raising this issue. We are currently working on adding [TorchSharp](https://github.com/dotnet/TorchSharp) support in ML.NET as part of our [Deep Learning story](https://github.com/dotnet/machinelearning/issues/5918). As part of those efforts, although NLP is one of the tasks we're looking to support, we have no specific plans for voice/audio at this time. However, as we hear more requests for it and learn more about how users leverage these features in their apps, we'll take them into consideration as we plan new releases. 

I see you mentioned native language parsers. Do you mean having Speech-To-Text capabilities? Would it be possible to expand some more on your use case and needs?
