### ISSUE TITLE
Community Survey

### ISSUE THREAD

**Issue by michaelgsharp** [dotnet/machinelearning#6072]
A couple years ago we surveyed you the members of the community in this repo to learn how we were doing as maintainers.

It's time to repeat the same survey. Whether you've been involved for years or you're relatively new please tell us about your experience participating and contributing to the project. It should only take a few minutes, and you can answer for up to 3 repos:

https://www.surveymonkey.com/r/8QTQTGJ?Source=machinelearning

**Comment by ooples** [comment]
@michaelgsharp Which option is for the machine learning repo or is that not on the list?

**Comment by danmoseley** [comment]
@ooples it should have been there -- we got quite a few responses for this repo.

@michaelgsharp the survey is now closed -- could you please close and un-pin this issue? I really should get myself rights to do that..
