### ISSUE TITLE
What to do with VBuffer?

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#608]
`VBuffer` is a very critical, fundamental type in ML.NET. And as such, it has some critical performance considerations and characteristics it needs to adhere to.

However, it is not as intuitive of a type as it could be. We even wrote a [Care and Feeding doc](https://github.com/dotnet/machinelearning/blob/master/docs/code/VBufferCareFeeding.md) that describes some common pitfalls and other things to be aware of when using the type.

At its core, `VBuffer` has 2 responsibilities:

1. It is a vector that can be either dense or sparse.
2. It is a reusable/cached "buffer" to allow minimal allocations and garbage collections.

We should do some investigation into what types of improvements we can make to this type.
* Is there something "base class library"-ish that can be introduced in .NET that would make this type better?
    * Potentially can we use `ArrayPool` to take care of the "buffer"-ness?  (see https://github.com/dotnet/corefx/issues/4547)
    * Are there other BCL types we could use or introduce?
* Are there alternative API designs that we should consider/incorporate here to make the type more intuitive and less error prone by users?
    * i.e. should some members be encapsulated?
    * Should we split `VBuffer` into two types `SparseVector` and `DenseVector`?

/cc @TomFinley @Zruty0

**Comment by Zruty0** [comment]
As for the `ArrayPool`, there are some problems with this approach:
- Since a pair of buffers (VBuffer) is a struct, this could cloud the ownership problem. It's not a huge deal in our codebase, since cloning `VBuffer`s is always viewed as a coding mistake. 
- As of now, we don't really 'release' arrays, but just lake GC take them when it feels like.
- We would still have to keep track of 'logical size' of the array that we rented.

**Comment by Zruty0** [comment]
To recap an online discussion: we should separate the two concepts of VBuffer:
- Serving as a polymorphous 'dense or sparse' vector
- Retaining arrays if possible and tracking 'capacity' and 'logical length' of arrays.

For the first one, the plan is to get rid of polymorphous behavior, and formally separate into `SparseVector` and `DenseVector`

For the second one, the current approach is fine (i.e. `DenseVector<T>` will be a struct with two fields: `T[] Values` and `int Length`)

**Comment by markusweimer** [comment]
> Retaining arrays if possible and tracking 'capacity' and 'logical length' of arrays.

Isn't this something where `Span<T>` could help? That is also designed to reuse the memory of differently-sized, array-ish accessors, right?

> Serving as a polymorphous 'dense or sparse' vector

The closest thing to that in the BCL is `Tensor<T>`. Do we have ideas on how to merge `VBuffer` with that?

**Comment by ericstj** [comment]
You're `DenseVector<T>` actually sounds very much like [`Memory<T>`](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Memory.cs) except `Memory<T>` can also support an offset and be backed by a native pointer.

Another scenario we have for this is wrapping memory that's owned by someone else.  Consider the TensorFlow case.  TF will allocate tensors (and unfortunately doesn't seem to provide an hook for callback allocation or pre-allocation of output tensors) and the ownership of these tensors is transferred to the caller.  For Python they are able to wrap the output tensor in an ndarray since ndarray permits wrapping memory: https://docs.scipy.org/doc/numpy-1.13.0/user/c-info.how-to-extend.html#c.PyArray_SimpleNewFromData.  

Unfortunately since the tensor/vector type in ML.NET is `VBuffer<T>`, `VBuffer<T>` only exposes managed arrays, and managed arrays **must** be .net arrays on the managed heap we cannot do this.

To address this scenario consider changing the type that ML.NET exposes for tensor/vector data to something that can wrap a native pointer (like Memory/Span) or modify VBuffer itself so that it can represent data backed with a native pointer.  I started experimenting with this idea a few months back in with [Tensor](https://github.com/dotnet/corefxlab/blob/1c979fa6a95a5a84c37394200124d892d734617b/samples/System.Numerics.Tensors.Samples/TensorSamples/WrapNativeMemory.cs).

I do think we can try to merge the ideas of VBuffer with Tensor.  We may find that both have good ideas and we end up with a hybrid.

**Comment by KrzysztofCwalina** [comment]
I quickly searched through current ML.NET APIs and it does not seem like there are any APIs that return VBuffer (except some inconsequential factory methods). And so it seems like we could use `Span<T>` instead of `Memory<T>`. If we indeed could use `Span<T>`, I think it would be a non-trivial perf win. Not only because of `Span<T>` being faster than a wrapper over arrays, but also because it could allow us to avoid heap allocations and pooling in many cases, i.e. we would stackalloc `Span<T>`.

**Comment by eerhardt** [comment]
## Issues
Here are the problems with the current VBuffer design:

1. `Values` and `Indices` arrays may be null, which forces callers to be careful or else get a `NullReferenceException`.
    - Typically "collection" properties aren't supposed to return `null`.
    - https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections
        - DO NOT return null values from collection properties or from methods returning collections. Return an empty collection or an empty array instead.
2. `Length` and `Count` properties are confusing. They seem to mean the same thing, but don't.
3. The lengths of the `Values` and `Indices` arrays have no logical meaning to the vector, and should only be used when checking for capacity to reuse the arrays.
4. Since `Values` and `Indices` are arrays, there is no safety that passing a `VBuffer` into a method won't modify the values in it.
    - This is the reason we have `Span<T>` and `ReadOnlySpan<T>`.

See the [Golden Rules Section](https://github.com/dotnet/machinelearning/blob/v0.6.0/docs/code/VBufferCareFeeding.md#golden-rules) of the Care and Feeding doc as well. The below proposal will either fix or drastically reduce 4 out of the 5 rules listed there. (The exception is the "two distinct VBuffers sharing references to their internal arrays" rule.)

## Proposal
Here's the proposed design changes I've come up with. Please provide any feedback to the design/names/etc.

1. Rename `Length` => `LogicalLength`. `Count` => `ValuesCount`.
    - alternatively we could have `LogicalLength` and `ValuesLength`. But there is some inertia (existing variables/comments/etc) around the terms `Length` meaning the logical length and `Count` meaning the number of elements explicitly represented.
    - It is also easier to visually tell the difference in code when the names aren't similar.
2. Make VBuffer a `readonly struct`.
    - It was always designed as readonly, we just didn't have the C# capability before now.
3. In methods that only actually read values from a VBuffer, change that parameter from `ref` to `in`.
    - This guarantees that the method won't change the reference, as was always the intention. We just didn't have the C# capability before now.
4. Change the `public T[] Values` and `public int[] Indices` to `public ReadOnlySpan<T> GetValues()` and `public ReadOnlySpan<int> GetIndices()`.
    - This change fixes issues (3) and (4) above.
    - The `Length` of these spans will always be correct. For dense VBuffers, `GetIndices()` will be empty. For sparse VBuffers, `GetValues()` and `GetIndices()` will always return spans that have the same length.
5. The most drastic proposed change is how to actually mutate a VBuffer.

### VBuffer mutation

There are generally 2 types of VBuffer mutation:
1. Changing the individual elements of the VBuffer - for example, scaling a vector.
2. Reusing the underlying values and indices arrays to create a new VBuffer - for example, changing the LogicalLength or sparsity/density of the vector.

To solve both of these scenarios, we will introduce a new concept `VBufferMutationContext<T>`.

A `VBufferMutationContext<T>` is a lightweight, stack-only* structure that will:
1. Give access to `public Span<T> Values` and `public Span<int> Indices` so code can modify the individual elements in the buffers.
2. Ensure the `Values` and `Indices` buffers have the appropriate capactiy.
3. Create new VBuffer instances using its cached buffers.

* This is stack-only so (a) it can cache the Span properties and (b) no one can hold onto an instance of the mutation context outside of the stack. The full mutation must happen immediately.

The following is a listing of the proposed public API:

```C#
    public static class VBufferMutationContext
    {
        public static VBufferMutationContext<T> Create<T>(
            ref VBuffer<T> destination,
            int newLogicalLength,
            int? valuesCount = null,
            int? maxValuesCapacity = null,
            bool keepOldOnResize = false);

        public static VBufferMutationContext<T> Create<T>(
            ref VBuffer<T> destination,
            int newLogicalLength,
            out bool createdNewValues,
            out bool createdNewIndices,
            int? valuesCount = null,
            int? maxValuesCapacity = null,
            bool keepOldOnResize = false);
    }

    public ref struct VBufferMutationContext<T>
    {
        public readonly Span<T> Values;
        public readonly Span<int> Indices;

        public void CreateBuffer(ref VBuffer<T> destintation);
    }
```

Here are examples of the typical usages from above:

1. Changing the individual elements of the VBuffer
```C#
    public static void ScaleBy(ref VBuffer<Float> dst, Float c)
    {
        if (c == 1 || dst.ValuesCount == 0)
            return;
        var mutation = VBufferMutationContext.Create(ref dst, dst.LogicalLength, dst.ValuesCount);
        if (c != 0)
            CpuMathUtils.Scale(c, mutation.Values);
        else // Maintain density of dst.
            mutation.Values.Clear();
    }
```

2. Reusing the underlying values and indices arrays to create a new VBuffer
```C#

    public static void ScaleBy(in VBuffer<Float> src, ref VBuffer<Float> dst, Float c)
    {
...
        if (src.IsDense)
        {
            // Maintain the density of src to dst in order to avoid slow down of L-BFGS.
            var mutation = VBufferMutationContext.Create(ref dst, src.LogicalLength);
            if (c == 0)
                mutation.Values.Clear();
            else
                CpuMathUtils.Scale(c, src.GetValues(), mutation.Values, src.LogicalLength);
            mutation.CreateBuffer(ref dst);
        }
        else
        {
            var mutation = VBufferMutationContext.Create(ref dst, src.LogicalLength, src.ValuesCount);
            src.GetIndices().CopyTo(mutation.Indices);
            if (c == 0)
                mutation.Values.Clear();
            else
                CpuMathUtils.Scale(c, src.GetValues(), mutation.Values, src.ValuesCount);
            mutation.CreateBuffer(ref dst);
        }
    }
```

Notice that to create a VBufferMutationContext you need a `ref VBuffer`. If you have an `in VBuffer` parameter in your method, it won't be possible to create a VBufferMutationContext since you can't pass an `in` parameter to a `ref` parameter.
However, this isn't completely fool-proof becuase a method could copy the VBuffer to a local variable, and then use that as a `ref` to create a VBufferMutationContext. With this, the method could then modify the individual elements of the buffer. However, this is unlikely, and since the person writing the method has control of the method signature, if they really want to modify the buffer, they should change the signature to be a `ref` parameter.

## Alternative Approaches Considered

As part of my prototyping and investigation I considered the following approaches, but they were rejected:

1. Split VBuffer into DenseVector and SparseVector.
    - This was deemed as too much of an architectural re-design to too many parts of ML.NET. For example, `public interface IValueMapper` only allows for a single `InputType`. However, if vectors were represented by 2 different types, types like this would need to be changed to handle multiple input types (and output types).
2. Create a `ref struct ReadOnlyVBuffer` type that `VBuffer` is implicitly convertable to, and use it in methods that shouldn't modify the VBuffer in any way.
    - Because of the stack-only restrictions of `ref struct`, this is actually a poor performing solution because of how many times VBuffers are held onto in either arrays, member variables, or passed through lambda expressions. The VBuffer code is very performance optimized today - using `ref` parameters everywhere so the values aren't copied on method call. Doing the conversion to ReadOnly is cheap, but isn't free. The [KMeansAndLogisticRegressionBench](https://github.com/dotnet/machinelearning/blob/v0.6.0/test/Microsoft.ML.Benchmarks/KMeansAndLogisticRegressionBench.cs) benchmark showed up to a 10% perf loss with this solution.
3. Create a regular `readonly struct ReadOnlyVBuffer` that `VBuffer` is implicitly convertable to.
    - This solution can be made to work within the existing performance characteristics of VBuffer. But after giving it some thought, adding a completely new type didn't seem necessary now that we have `in` parameters. Adding a `ReadOnly` type is extra complexity that I'm not sure outweigh the benefits.

**Comment by TomFinley** [comment]
One thing that occurred to me -- might these pieces of auxiliary information like the `out bool` parameters happen just as fields on this mutating context? This would seem to obviate the need for the second overload, and those operators that do not care about this operation would just be able to simply ignore those fields.

**Comment by eerhardt** [comment]
Thanks for the comments, @TomFinley. They are appreciated. I've updated the propsoal above as appropriate, and am responding to your questions/comments below:

> It seems like keeping old on resize in the case of VBuffer specifically.

This option is important when expanding the buffer to make room for new elements. Here are two cases that do this:

https://github.com/dotnet/machinelearning/blob/5e08fa1ea7bfb54f28ed0815cb6413e0068e6dd1/src/Microsoft.ML.Core/Utilities/VBufferUtils.cs#L478-L481

https://github.com/dotnet/machinelearning/blob/bee7f171941007b29671b5435ad135608fcda930/src/Microsoft.ML.Data/Depricated/Vector/VBufferMathUtils.cs#L278-L291

That way the caller doesn't have to do the copying themselves. `Array.Resize` will do the copying underneath the covers. Notice that I explicitly choose a different default value from `Utils.EnsureSize`. VBufferMutationContext uses `keepOldOnResize = false`, since most of the scenarios don't need to preserve the old values, and it is faster to create a new array than resize, which copies the elements.

> The out bool created... parameters are a bit more tricky. I am supposing, but do not know, that it is meant to service this sort of scenario:

Correct.
There is another place that uses it:
https://github.com/dotnet/machinelearning/blob/bee7f171941007b29671b5435ad135608fcda930/src/Microsoft.ML.Data/Depricated/Vector/VBufferMathUtils.cs#L371-L372

So I thought it would be important to preserve this option, somehow.

I just looked, and I haven't gotten to a place yet where I have used `createdNewIndices`, but I haven't gotten through everything yet. It just seemed symmetrical to have both options.

>  might these pieces of auxiliary information like the out bool parameters happen just as fields on this mutating context?

Yes, I can totally make that change. It should clean the API up.

> maxValuesCapacity 

Yes, this gets passed into the `max` parameter of `Utils.EnsureSize`.

There appears to be a mix of usages here in the existing code.

Some specify the `LogicalLength` for the max capacity, ex:

https://github.com/dotnet/machinelearning/blob/bee7f171941007b29671b5435ad135608fcda930/src/Microsoft.ML.Data/Depricated/Vector/VBufferMathUtils.cs#L370

and some let it default to `Utils.ArrayMaxSize`, ex:

https://github.com/dotnet/machinelearning/blob/8e77d0f0ce74cdb8b10fa545830972a4525d5dab/src/Microsoft.ML.Data/Data/RowCursorUtils.cs#L448-L449

Part of me thinks keeping `newLogicalLength` as the `maxCapacity` makes sense, especially in the case where you aren't ever going to need to allocate again. That way, if you only need 1 more element, you aren't doubling the array size. But, in the opposite worst case scenario, where each mutation grows the vector by a single element, it will allocate a lot of new arrays, and you might as well have doubled it the first time you needed more capacity.

After some thinking, my gut is telling me to drop the parameter, and let the array double (your proposal above), for now. If we run into problems, we can add an overload/default parameter in the future.

Thoughts on that plan?

> Also how is a VBuffer created in the first place? 

I wasn't planning on changing the existing constructors to `VBuffer`. Let me know if you think that is a problem.

> VBufferMutationContext<T>.CreateBuffer

I think it makes sense to change this to return the buffer instead. After that, we can "poison" the mutation context, and throw an exception if someone calls `CreateBuffer` again.

> If we do set that object passed in to the default value

I'm still not convinced we should do that. I think it is surprising to a caller. And there are some cases where we'd like to still access the VBuffer after creating a mutation context, ex:

https://github.com/dotnet/machinelearning/blob/bee7f171941007b29671b5435ad135608fcda930/src/Microsoft.ML.Data/Depricated/Vector/VectorUtils.cs#L162

It also isn't fool-proof, because someone could copy the VBuffer on the stack, and even if we blanked out the `ref` being passed in, they would still have access to the buffer with the copy.

Would the above plan to have `CreateBuffer` return the created `VBuffer` work for now, or do you still think that we should be blanking out the `ref` being passed in?
