### ISSUE TITLE
How can perform percentage predication in ml.net? 

### ISSUE THREAD

**Issue by TusharMalap** [dotnet/machinelearning#6097]
I want my features percentage on targeted variable/label.
For example Movie -is my targeted variable and I want to predict genre of that movie like Romantic=99.98% Comedy=00.01% thriller=00.01
i.e.. Romantic + comedy + Thriller =100%

**Comment by michaelgsharp** [comment]
Take a look at #6087 and see the code sample there. It may be able to answer your question.
