### ISSUE TITLE
Protobuf Parsing Failed when loading Keras model with custom layer

### ISSUE THREAD

**Issue by gjiremadzeBECKMAN** [dotnet/machinelearning#6098]
Hey all I'm having an error when trying to load a keras model with a custom layer. When trying to call Transforms.ApplyOnnxModel(modelFile) I'm receiving an exception:

Microsoft.ML.OnnxRuntime.OnnxRuntimeException: '[ErrorCode:InvalidProtobuf] Protobuf parsing failed.'

Has anyone tried loading models with custom layers with onnxruntime and have you had any success?

Does anyone know which ONNX opsets are supported in the current ML.NET? Or where I can find this information?

**Comment by michaelgsharp** [comment]
Latest released version of ML.NET is using OnnxRuntime 1.6. The main branch has been updated to use 1.10. If you need a newer version than 1.6 you can directly reference a newer version in your project and it will overwrite the older version.

If its a custom layer created with Keras and only supported by Keras than this might be an issue. Please try the suggestion and let us know if you still have issues.

**Comment by gjiremadzeBECKMAN** [comment]
> Latest released version of ML.NET is using OnnxRuntime 1.6. The main branch has been updated to use 1.10. If you need a newer version than 1.6 you can directly reference a newer version in your project and it will overwrite the older version.
> 
> If its a custom layer created with Keras and only supported by Keras than this might be an issue. Please try the suggestion and let us know if you still have issues.


@michaelgsharp 
I went ahead and added the Microsoft.ML.Onnxruntime NuGet to my solution and made sure that the version was up to date 1.10 but am still receiving the same error.

I also took the 1.10 DLL and copied it over to the original solution to replace the Onnxruntime.DLL that's included in Microsoft.ML.Transforms.Onnx but still getting the same Protobuf Parsing error. 

Would there be a way to get a more descriptive error message to maybe understand what's going on better?

**Comment by gjiremadzeBECKMAN** [comment]
@michaelgsharp is there any way to get a more descriptive error from the exception?
