### ISSUE TITLE
Testing issue triage automation

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/machinelearning#6100]
This issue is being used to test the issue triage automation that has been added to the repository. Please ignore.

**Comment by jeffhandley** [comment]
This comment should result in the issue needing further triage.

**Comment by bartonjs** [comment]
Little known fact: I can write extremely eloquently... but only so long as I'm not actually writing anything.

**Comment by bartonjs** [comment]
From the Unix fortunes file:

> One Page Principle:
	A specification that will not fit on one page of 8.5x11 inch
	paper cannot be understood.
		-- Mark Ardis

I asked Mark (Dr. Ardis, if you prefer) about this once... and he told me he later came up with a counter-example.  But I don't remember it, just that it confused me, because it sounded more like it reinforced his principle.

Oh, well.
