### ISSUE TITLE
Hierarchical Classification in ml.net ? 

### ISSUE THREAD

**Issue by TusharMalap** [dotnet/machinelearning#6109]
Is there way to achieve Hierarchical Classification in [ml.net](http://ml.net/)?
Like Predict cat from animal category and then predict breed of that cat based on cat as a input? in multiclass-classification?

**Comment by michaelgsharp** [comment]
It sounds like you are wanting to use the output from a prediction as an input into the next prediction. Is that correct? If so, this is supported. You would have to create multiple trainers, 1 for each thing you want to predict, and feed the output from the first pipeline into the second one.

**Comment by TusharMalap** [comment]
Ok. Thank you for the suggestion. I'll try to implement . also is there way I can perform percentage prediction on data with multiple features. 
In multiclass classification where it predict language .

If I enter 'And' then it predicted as 97% English.
But I also want result like 97 % English then 2%italian ,1%Spanish
That is resulted percentage = 100%

I did achieve this using scores and foreach but total of score is over 100% such as 100.00025
