### ISSUE TITLE
Decision Tree Algorithm in ml.net  ?

### ISSUE THREAD

**Issue by TusharMalap** [dotnet/machinelearning#6113]
How I can  achieve that?

**Comment by luisquintanilla** [comment]
Hi @TusharMalap 

Here's a list of [decision-tree algorithms supported in ML.NET](https://docs.microsoft.com/dotnet/machine-learning/how-to-choose-an-ml-net-algorithm#decision-tree-algorithms). 

Here's general guidance on [how to build a training pipeline with ML.NET](https://docs.microsoft.com/dotnet/machine-learning/how-to-guides/train-machine-learning-model-ml-net).

Closing this issue for now. If you run into problems or have additional questions, please feel free to open another issue.
