### ISSUE TITLE
LBFGSLogisticRegression trainer probability distribution issue

### ISSUE THREAD

**Issue by maheshlokhande** [dotnet/machinelearning#6114]
We are using LBFGSLogisticRegression trainer for binary classification which seem to be working fine but in some cases (especially with larger training data) probability distribution isn't even. We are getting probability of above 90 and near 0 for positive and negative test samples respectively even though scores for these samples are quite apart. Is there a way to calculate probability which will linearly scale as per scores generated by transform operation.

**Comment by michaelgsharp** [comment]
Can you provide more context? Each trainer converts its score into a probability during its "Optimize" function. See (here)[https://github.com/dotnet/machinelearning-modelbuilder/issues/2042#issuecomment-1049119864] for a few more details. LBFGS specifically uses the function found [her](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.lbfgslogisticregressionbinarytrainer?view=ml-dotnet#scoring-function).
