### ISSUE TITLE
Training Statistics for linear learners.

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#612]
When trying to split OLS as a separate  learner, on PR #611, we noticed that LogisticRegression has a dependency on MKL to generate training stats. 

Since we don't want the core ML.Net package to have dependencies on other large packages, i am removing the stats generation through PR #611 and should introduce a Utility, in the AdditionalLearners package, (or the package that has a reference to Mkl) and produce those stats post training.

**Comment by montebhoover** [comment]
This will fix #1006.
