### ISSUE TITLE
Hyper-parameter tuning

### ISSUE THREAD

**Issue by xusun** [dotnet/machinelearning#613]
Is there a plan to support hyper-parameter tuning as pipeline step?

**Comment by rauhs** [comment]
See https://github.com/dotnet/machinelearning/issues/416

**Comment by Zruty0** [comment]
Hyper-parameter tuning (or 'sweeping', which is the term we use in the library) is definitely something we plan to support. 

I feel a little less confident that we should support it as a 'pipeline step' however.
For something as trivial as a grid search, I feel like we should enable a code snippet like this (currently this is not working code, but we will likely add this kind of constructor):
```c#
foreach (float l2param in new[] {0, 0.1, 0.01, 1e-3, 1e-3}) 
    foreach (float lr in new[] {0.1, 0.01, 1e-3})
    {
        var model = new AveragedPerceptronTrainer(l2param, learningRate: lr)
            .Train(trainingData);
        var metrics = BinaryClassificationMetrics.EvaluateModel(model, validationData);
        if (metrics.AUC > bestMetrics?.AUC ?? 0.5)
        {
            bestMetrics = metrics;
            bestModel = model;
        }
    }
```

For more complicated sweeping algorithms, we will likely provide a 'sweeper' component, which can be inserted into the 'training pipeline', or used standalone.

**Comment by abgoswam** [comment]
DRI RESPONSE : Assigning to Backlog project.  This is something we plan to support in future

**Comment by gilnahmias** [comment]
Need an equivalent of https://docs.microsoft.com/en-us/azure/machine-learning/studio-module-reference/tune-model-hyperparameters to ease transition from Azure ML Studio

**Comment by codemzs** [comment]
We plan to move AutoML to our master branch in the coming weeks, it is currently in a feature branch.
