### ISSUE TITLE
Fix Pixel Extraction ordering.

### ISSUE THREAD

**Issue by cvixxt** [dotnet/machinelearning#6130]
**System Information (please complete the following information):**
 - OS & Version: Windows 10
 - ML.NET Version: ML.NET v1.7.1
 - .NET Version: .NETCore 3.1

**Describe the bug**
Use Custom Vision to output .ONNX, the result on the local side is different from the result on the cloud

**To Reproduce**
1. Using Onnx Object Detection App (from dotnet/machine learning/sample)
2. Delete TinyYolo_model.onnx, put the onnx.zip downloaded by Custom Vision in the corresponding path to read the Model file.
3. Under the method of DetectObjectsUsingModel, the result of  "var boundingBoxes " is different from the result on cloud.

**Expected behavior**
As expected, it should be the same as the result on the cloud.

**Screenshots, Code, Sample Projects**
1. I confirmed that my output model is None x None2 x 13 x 13,  where None = variable number. Fg.1 
![image](https://user-images.githubusercontent.com/52907433/158550268-34890bbd-816a-4c39-81ef-e55c862c7d9e.png)

2. I confirmed that I have 6 labels and will return 5 parameters, plus 5 anchor boxes, so the output will be (6+5)*5 = 55.

3. In the code section, I also confirmed that my Label return array is 55x1x13x13 = btye[9295].  ->Fg.2
![image](https://user-images.githubusercontent.com/52907433/158551115-6e683a80-ab68-47c1-af48-4b3a1b8f0a28.png)

4. After reading the same image, I return a set of corresponding labels. Fg.3
![image](https://user-images.githubusercontent.com/52907433/158552225-80ad8360-23c5-473c-8e32-a71c81561ab1.png)

5. When I used Custom Vision's Web API to make predictions, I found that the results for the same image were completely inconsistent with the results on the local side. Fg.4
![image](https://user-images.githubusercontent.com/52907433/158552706-8c5568ee-2f35-4808-b320-90462cec2884.png)

6.The Label output on the local side is "綠膠囊" ("means green capsule"), while the result on the Web API is "橘膠囊" ("means orange capsule").

7.Not sure what I'm doing wrong, has anyone encountered a similar problem?

Thank you for reading this question.

**Comment by michaelgsharp** [comment]
Hey @cvixxt, I responded on the other issue where you commented this, but can you share a sample repro project so I can take a look? With the onnx model/code/data so we can get an easier repro. And also what results were you getting online so we know where the discrepancy is.

**Comment by cvixxt** [comment]
Hi @michaelgsharp ,

I am attaching the Sample and Onnx files available for download here, both of which are included in the .7z file and can be downloaded locally for testing via the link below. At ML\OnnxModels\new.ONNX, there are custom models that I downloaded from the Custom Vision.

https://drive.google.com/file/d/1716n7U_pY-twQGoo1O246SEyf_Bp1BPN/view?usp=sharing
(The Folder name is ObjectTracking_Microsoft)

In addition, the test image will be available for download in another link.
https://drive.google.com/file/d/1FVVfOBGbyJfEZKZyFLkbU2HbQaHWF6bW/view?usp=sharing
(The Folder name is Medicine)

Please help me understand the difference. 

Thanks.

**Comment by cvixxt** [comment]
Hi all,
Is there any progress?
@michaelgsharp

**Comment by cvixxt** [comment]
Anyone else can help this question,Please. 0.0?

**Comment by michaelgsharp** [comment]
@cvixxt sorry for my delay. This appears to be an issue dealing with how the image is being resized locally vs how it is being resized in Custom Vision. I have tried the 3 ways we do resizing locally and still can't get it to align. Its possible we need to add in the same type of image resizing they do.

@JakeRadMSFT @luisquintanilla do you know the type of image resizing that the Custom Vision API is doing?

**Comment by luisquintanilla** [comment]
@michaelgsharp I don't know how the internal resizing works but a few years ago this is what worked for the session we did at NDC. https://mlnet-workshop.azurewebsites.net/posts/11.4-define-scoring-pipeline. I believe the pre / post processing steps have changed since though so your mileage may vary. 

@jwood803 as part of the tutorial you're building, did you do any resizing? If so, what was it?

**Comment by michaelgsharp** [comment]
@cvixxt @luisquintanilla @JakeRadMSFT It looks like this is a bug that was introduced in the 1.7.0 release. Using version 1.6.0 fixes this issue. To resolve it here are the steps.
1 - Downgrade all ML.NET packages from 1.7.1 to 1.6.0
2 - In `OnnxModelConfigurator.cs` change line 25 from:
```            var pipeline = mlContext.Transforms.ResizeImages(resizing: ImageResizingEstimator.ResizingKind.Fill,```
to just
```            var pipeline = mlContext.Transforms.ResizeImages(```
3 - In `OnnxModelConfigurator.cs` change line 28 from:
```.Append(mlContext.Transforms.ExtractPixels(outputColumnName: onnxModel.ModelInput))```
to
```.Append(mlContext.Transforms.ExtractPixels(outputColumnName: onnxModel.ModelInput, orderOfExtraction:ImagePixelExtractingEstimator.ColorsOrder.ABGR))```

The percent is still slightly off compared to Cognitive services, but the label is correct. @JakeRadMSFT suggested the percent may need a small amount of calibration to get it to match exactly. @cvixxt I compared several other images and they seemed to work correctly. Can you test these changes and let me know if it works?

@luisquintanilla @JakeRadMSFT I know the PR that introduced this bug. We changed the pixel extraction code to make it WAY more efficient, it must just not be layering things 100% correctly now. We don't have any test cases using the Cognitive Services models, so we just didn't catch this I guess. I'll work on getting this fixed.

**Comment by cvixxt** [comment]
@michaelgsharp 
OK, no problem, I'll test it first. I will report the progress later, thank you for your help.

**Comment by cvixxt** [comment]
@michaelgsharp @luisquintanilla @radical 

Hi all,
I modified the ` OnnxModelConfigurator.cs ` file according to the above description and found
` var pipeline = mlContext.Transforms.ResizeImages(resizing: ImageResizingEstimator.ResizingKind.Fill,`
 -> `var pipeline = mlContext.Transforms.ResizeImages( , `
This situation will cause the XY coordinate system of the grab frame to shift.
As shown in the picture.
![image](https://user-images.githubusercontent.com/52907433/162149239-cde1f562-01ef-4ad9-bf87-a5743ae87ed5.png)


However
`.Append(mlContext.Transforms.ExtractPixels(outputColumnName: onnxModel.ModelInput, orderOfExtraction:ImagePixelExtractingEstimator.ColorsOrder.ABGR))`
This works great,
But adding the `ColorsOrder.ABGR` section would make the image's color channels more visible and better capture the feature analysis category?

**Comment by michaelgsharp** [comment]
Its not that it makes the color channels more visible, its that that is the order that your onnx model wants. This app can visual the onnx model, https://netron.app/. Using that you can read comments about the input data. In this case it says:
> Image(s) in BGR format. It is a [N, C, H, W]-tensor. The 1st/2nd/3rd slices along the C-axis are blue, green, and red channels, respectively.
So thats why I changed the pixel extraction to BGR format. I don't think any 1 way is better than another, you just have to match what the model is expecting.

**Comment by michaelgsharp** [comment]
Ok, Playing around with this some more, looks like 1.7.1 works fine (I must have just not tried the exact options that worked in 1.7.1 before I told you to use 1.6.0). So, there is no problem and things work as long as you do the right color extraction order. Closing this issue. If you have further issues feel free to open another issue.
