### ISSUE TITLE
Maximum number of collumns in DataFrame

### ISSUE THREAD

**Issue by 1kamma** [dotnet/machinelearning#6146]
**System Information (please complete the following information):**
 - OS & Version: Windows 11 
 - ML.NET Version: 1.17
 - .NET Version: 6.0

**Describe the bug**
When I'm trying to load a csv to a DataFrame, and the csv contains more than 12 collumns, I get the error massege:
'System.ArgumentException: Parameter.Count exceeds the number of columns(12) in the DataFrame'
I can create by my own, a DataFrame with more than 12 collumns, but cannot import it

**Comment by michaelgsharp** [comment]
Can you provide a repro please? I just tested a 27 column DataFrame, so there is something else that is causing your issue not related to the number of columns.

**Comment by 1kamma** [comment]
somehow, the problem has solved from itself. idk how. but thanks
