### ISSUE TITLE
Using ML.NET with Mono On Unity

### ISSUE THREAD

**Issue by IncentWang** [dotnet/machinelearning#6170]
**System Information (please complete the following information):**
 - OS & Version: Android (Compile code from Mono)
 - ML.NET Version: ML.NET 1.7.1
 - .NET Version: .NET Standard 2.0

**Describe the bug**
When I am trying to load model from my device, I will get "UnauthorizedAccessException: Access to the path "/tmp" is denied".

**To Reproduce**
1. Use Mono to Compile your code,
2. Run it on android,
3. Get the exception.

**Expected behavior**
I expected it to load the model correctly. I think this is because the Mono makes "Path.GetTempPath() " you used to return "/tmp/", but I cannot get the permission to access that because my device is not rooted. Is there any chance to skip the code which use the temp path? 

**Screenshots, Code, Sample Projects**
Here is the Exception Screenshot:
![image](https://user-images.githubusercontent.com/60191615/164879167-8525d5c7-f5eb-402e-aaf3-c83e1fe1f8ce.png)

And here is the Code:
```
            Debug.Log(Path.GetTempPath()); // This line will print "/tmp/"
            DirectoryInfo dirInfo = new DirectoryInfo(Application.persistentDataPath + "/MLModel");
            if (!dirInfo.Exists)
            {
                dirInfo.Create();
            }

            FileInfo info = new FileInfo(Application.persistentDataPath + ModelPath);
            if (!info.Exists)
            {
                info.Create().Dispose();
                InitializeModelFromStreamingData(Application.persistentDataPath + ModelPath);
            }

            Stream stream = info.OpenRead();
            _transformer = _context.Model.Load(stream, out _schema); // This line will throw the exception.
            _model = _context.Model.CreatePredictionEngine<ModelInput, ModelOutput>(_transformer);
            stream.Close();
```

**Additional context**
I am using Unity with C#. If this problem cannot be solved, is there any suggestion to make me load the model in Unity?

Thank you!

**Comment by michaelgsharp** [comment]
So we now have the ability to set the temp path to whatever you would like. Can you try setting `_context_.TempFilePath` to a location you do have write access to and let me know what happens?

**Comment by IncentWang** [comment]
Hi, Thank you for your replying.

Unfortunately, the `MLContext.Model.Load(stream)` function is still trying to access `/tmp/` path. I think this is caused by some functions are still using `System.IO.GetTempPath()` instead of using `_env.TempFilePath`. I am still looking for that, or do you got some hint for me?

I think I did it in right way, for the case I didn't, here is the code I used and this is the Log.

Code:
``` 
            Stream stream = info.OpenRead();
            Debug.Log("Preparing to load");
            Debug.Log("Changing Temp File Path");
            _context.TempFilePath = Application.persistentDataPath + TempFilePath;
            Debug.Log("Temp File Path is Changed, now is: " + _context.TempFilePath);
            Debug.Log("Loading Transformer");
            _transformer = _context.Model.Load(stream, out _schema);
            Debug.Log("Load Phase one");
            _model = _context.Model.CreatePredictionEngine<ModelInput, ModelOutput>(_transformer);
            stream.Close();
```
Log:

![c4288f6e0e03084b103b310089f6f1c](https://user-images.githubusercontent.com/60191615/165799356-7aa01db4-5a41-4130-91e1-e2f4f4bcc8be.png)

**Comment by IncentWang** [comment]
Hi, I solve this problem, I think this is because when the program is still trying to access `System.IO.TempPath()` when it is unzipping the model file. I made the following change in `Repository.cs` to solve this problem. I want to create a pull request, but I think I need to run the test on my computer first but I do not have enough time.

I will create a pull request ASAP, but if you got time and want to do that instead of me, thank you in advance.

![image](https://user-images.githubusercontent.com/60191615/166232306-848ad996-dc17-4895-8033-8b83f61be7ab.png)

BUT a new problem has appeared, the program seems not works well on `.NET Standard 2.0` platform, it will raise `Error: Operation is not supported on this platform` exception. But it works correctly on `.NET Framework 4.x`.

**Comment by michaelgsharp** [comment]
I made the changes and currently have created a Draft PR to make sure the tests pass. Thanks for finding this! #6180
