### ISSUE TITLE
DataFrame.LoadCsv can not load CSV with duplicate column names

### ISSUE THREAD

**Issue by torronen** [dotnet/machinelearning#6182]
Code:
IDataView trainData = DataFrame.LoadCsv(TrainDatasetPath, separator: ';', header: true, guessRows: 100);

Gives exception:
DataFrame already contains a column called Target20 (Parameter 'column')

Suggestion:
It would be nice if LoadCsv would have the option to ignore or auto-rename duplicate columns. 
For small CSV files it is not a big problem, but for huge CSV files renaming headers is a hassle.

**Comment by torronen** [comment]
If anyone has same problem renamed header names can put in the parameter. This solves my issue. I do not know if LoadCsv should have this functionality inbuilt or not (or, issue to be closed or not)

LoadCsv with renamed columns:
```
  string line1 = File.ReadLines(TrainDatasetPath).First();
                string[] arr = line1.Split(';');
                var duplicatedItems = arr.GroupBy(a => a)
                                       .Where(g => g.Count() > 0)
                                       .ToDictionary(g => g.Key, g => g.Count());

                for (int i = arr.Length - 1; i >= 0; i--)
                {
                    string item = arr[i];
                    if (!duplicatedItems.ContainsKey(item))
                    {
                        arr[i] = item;
                        continue;
                    }

                    if (duplicatedItems[item] > 1)
                    {
                        arr[i] = String.Format("{0}_{1}", item, duplicatedItems[item]);
                    }
                    
                    duplicatedItems[item]--;
                }

                IDataView trainData = DataFrame.LoadCsv(TrainDatasetPath, separator: ';', header: true, columnNames: arr, guessRows: 100);
```

**Comment by luisquintanilla** [comment]
@michaelgsharp by builtin do you mean duplicate columns are automatically renamed like the snippet @torronen shared?

**Comment by beccamc** [comment]
+1 - I also experienced pain around large data files with multiple columns sharing names. I only had less than 50 columns and it was still troublesome to deal with.
