### ISSUE TITLE
DataFrame.LoadCsv: Specific method is not supported

### ISSUE THREAD

**Issue by torronen** [dotnet/machinelearning#6184]
**System Information (please complete the following information):**
 - OS & Version: Windows 11
 - ML.NET Version:  ML.NET v1.6.0
 - .NET Version: NET 6.0

**Describe the bug**
I received  Specific method is not supported after trying to fit with data read with DataFrame.LoadCsv

```
Specified method is not supported.
   at Microsoft.Data.Analysis.PrimitiveDataFrameColumn`1.GetDataViewType()
   at Microsoft.Data.Analysis.PrimitiveDataFrameColumn`1.AddDataViewColumn(Builder builder)
   at Microsoft.Data.Analysis.DataFrame.get_DataViewSchema()
   at Microsoft.Data.Analysis.DataFrame.Microsoft.ML.IDataView.get_Schema()
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at WebRanking.Program.Main(String[] args) in L:\machinelearning-samples-main\samples\csharp\getting-started\Ranking_Web\WebRanking\Program.cs:line 78
```

**To Reproduce**
1. Download sample [machinelearning-samples\samples\csharp\getting-started\Ranking_Web\WebRanking\](https://github.com/dotnet/machinelearning-samples/tree/e8ce65961377e09ebe297cb3a2d609cd76f788db/samples/csharp/getting-started/Ranking_Web/WebRanking)
2. Change Loading of data to use DataFrame.LoadCsv
3. Observe the mentioned error when the schema is queried to get list of columns for Features. If you fix this error, then the same error happens in pipeline.Fit()

**Expected behavior**
Training should complete

**Additional data**
I am using DataFrame.LoadCsv so that I do not need to provide a class with 2900 properties, as per the sample, because my data has many more features
https://github.com/dotnet/machinelearning-samples/blob/e8ce65961377e09ebe297cb3a2d609cd76f788db/samples/csharp/getting-started/Ranking_Web/WebRanking/Program.cs#L37

I tried to use Model Builder to generate said class for reading the data but it is missing LoadColumn annotation so  mlContext.Data.LoadFromTextFile<ModelInput> does not work

**Workaround**
I am reading from IDV file to make it work for now. TextLoader could probably work, too.
IDataView trainData = mlContext.Data.LoadFromBinary(TrainDatasetPath + ".idv");

I can continue with these method in this task, but I would like to understand better why the exception is happening.

**Comment by LittleLittleCloud** [comment]
Did your dataset contains array-like column

**Comment by torronen** [comment]
@LittleLittleCloud No, it is just 1 number for column. It is possible I had some mistake in delimiters and it makes it seem like an array, but Model Builder was able to read the file and generate the ModelInput.cs.

**Comment by michaelgsharp** [comment]
Would you be able to provide a simple repro for it?
