### ISSUE TITLE
AutoML CV experiment does not release memory of enumerable underlying IDataView training data.

### ISSUE THREAD

**Issue by fischja** [dotnet/machinelearning#6188]
**System Information (please complete the following information):**
 - Windows 11 Home, 21H2,  22000.652
 - ML.NET 1.7.1
 - ML.AutoML 0.19.1
 - .NET 6.0 

**Describe the bug**
Auto ML cross-validation experiment retains reference to enumerable underlying training data IDataView, not allowing memory to be released. Makes multiple training episodes on large, in-memory enumerables impossible. 

**To Reproduce**
```
for (int i = 0; i < 5; i++)
{
    MLContext ml = new MLContext();

    List<MyData> trainingDataList = Enumerable.Range(0, 10000).Select(x => new MyData()).ToList();
    IDataView trainingData = ml.Data.LoadFromEnumerable(trainingDataList);

    var result = ml
        .Auto()
        .CreateRegressionExperiment(maxExperimentTimeInSeconds: 20)
        .Execute(trainData: trainingData, numberOfCVFolds: 3, labelColumnName: "Y");
}
```

```
class MyData
{
    public float X { get; set; }
    public float Y { get; set; }
}
```

After each loop, the memory increases steadily. 

**Expected behavior**
More or less constant memory usage. 

**Screenshots, Code, Sample Projects**
Memory profile at the end of each loop.
![image](https://user-images.githubusercontent.com/23638305/167169730-96e7cae9-dcd4-44ae-8a26-9cf7156bb9a7.png)

Object memory usage after 5 loops - you can see that the underlying enumerable from previous loops is still referenced.
![image](https://user-images.githubusercontent.com/23638305/167169909-86342a49-84f2-4f50-8040-3f0c890afee1.png)

**Additional context**
Maybe I am missing something on how to properly dispose objects, but was unable to find help in the docs/SO.

**Comment by michaelgsharp** [comment]
@LittleLittleCloud are you familiar with this behavior in AutoML. Is this something that may be fixed with your AutoML changes?

**Comment by LittleLittleCloud** [comment]
@fischja It could be the last trial still running even after automl experiment times out, could you try cancelling context and run again

```csharp
for (int i = 0; i < 5; i++)
{
    MLContext ml = new MLContext();

    List<MyData> trainingDataList = Enumerable.Range(0, 10000).Select(x => new MyData()).ToList();
    IDataView trainingData = ml.Data.LoadFromEnumerable(trainingDataList);

    var result = ml
        .Auto()
        .CreateRegressionExperiment(maxExperimentTimeInSeconds: 20)
        .Execute(trainData: trainingData, numberOfCVFolds: 3, labelColumnName: "Y");

    ml.CancelExecution();
}
```

**Comment by fischja** [comment]
@LittleLittleCloud yup, that seems to solves the problem! Are there any best practices for managing the lifecycle of a `MLContext`? E.g. should the same context be used for multiple training episodes or a new one created each time?

**Comment by LittleLittleCloud** [comment]
> @LittleLittleCloud yup, that seems to solves the problem! 

Glad to hear that! Although it's a bit wield to see that since Auto() also call that `CancelExecution` when training time is up. I would go take some investigation once I got time!

> Are there any best practices for managing the lifecycle of a MLContext? E.g. should the same context be used for multiple training episodes or a new one created each time?

That's what I usually do, although for more detail (and more auth) information @michaelgsharp and @ericstj and @eerhardt would know more

**Comment by ericstj** [comment]
The [docs](https://github.com/dotnet/machinelearning/blob/04dda55ab0902982b16309c8e151f13a53e9366d/docs/code/MlNetCookBook.md#general-questions-about-the-samples) say:
> You will need one MlContext object for all your pipelines or inference code.

Another [pointer](https://github.com/dotnet/machinelearning/blob/04dda55ab0902982b16309c8e151f13a53e9366d/docs/code/MlNetHighLevelConcepts.md#mlcontext)
> Create one MLContext for your entire application. 

Probably best to just create one.  If you were specifying different seeds I could see it being interesting to create more than one but here you aren't specifying anything so it seems like reuse would be better.
