### ISSUE TITLE
Unable to load DLL 'CpuMathNative' on published website

### ISSUE THREAD

**Issue by GuiOliv** [dotnet/machinelearning#6194]
- OS & Version: Windows 10 
 - ML.NET Version: ML.NET v1.7.1
 - .NET Version: NET 4.7.2

I just deployed my ASP.net website which uses ML.net on a free web host called Somee. Before deploying the solution, everything was working fine and all was published without struggle but the moment I clicked the button I have to submit the input to the MLModel, the website gave me the following error message:

> System.DllNotFoundException: Unable to load DLL 'CpuMathNative': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

I already verified if all the references in the Visual Studio project were on the bin folder of the website which they are.

**To Reproduce**
1. Go to ['This website'](http://boma.somee.com/)
2. Write anything on the textbox
3. Click enter

What it should do is activate post and scroll down to a container

Full error:

> [DllNotFoundException: Unable to load DLL 'CpuMathNative': The specified module could not be found. (Exception from HRESULT: 0x8007007E)] Microsoft.ML.Internal.CpuMath.Thunk.SumSqU(Single* ps, Int32 c) +0 Microsoft.ML.Internal.CpuMath.CpuMathUtils.SumSq(Single mean, ReadOnlySpan1 src) +183 Microsoft.ML.Transforms.Mapper.L2Norm(ReadOnlySpan1 values, Single mean) +39 Microsoft.ML.Transforms.<>c__DisplayClass8_0.b__5(VBuffer1& dst) +113 Microsoft.ML.Data.<>c__DisplayClass20_01.b__0(VBuffer1& dst) +182 Microsoft.ML.Data.<>c__DisplayClass19_02.b__0(TDst& dst) +22 Microsoft.ML.Data.PredictedLabelScorerBase.EnsureCachedPosition(Int64& cachedPosition, TScore& score, DataViewRow boundRow, ValueGetter1 scoreGetter) +45 Microsoft.ML.Data.<>c__DisplayClass16_0.<GetPredictedLabelGetter>b__0(UInt32& dst) +31 Microsoft.ML.Transforms.<>c__DisplayClass8_0.<GetMappingGetter>b__0(TValue& dst) +24 Microsoft.ML.Data.<>c__DisplayClass9_02.b__0(TRow row) +22 Microsoft.ML.Data.TypedRowBase.FillValues(TRow row) +37 Microsoft.ML.Data.RowImplementation.FillValues(TRow row) +13 Microsoft.ML.PredictionEngineBase2.FillValues(TDst prediction) +45 Microsoft.ML.PredictionEngine2.Predict(TSrc example, TDst& prediction) +89 Microsoft.ML.PredictionEngineBase`2.Predict(TSrc example) +64 SampleClassification.Model.ConsumeModel.Predict(ModelInput input) in C:\Users\pinky\source\repos\ProjetctBoMa\SampleClassification.Model\ConsumeModel.cs:30 ProjetctBoMa._Default.Button1_Click(Object sender, EventArgs e) in C:\Users\pinky\source\repos\ProjetctBoMa\ProjetctBoMa\Default.aspx.cs:28 System.Web.UI.WebControls.Button.OnClick(EventArgs e) +9796242 System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +211 System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument) +12 System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument) +15 System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData) +35 System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +1696

**Comment by trishorts** [comment]
plus one on this issue

**Comment by Kinco-dev** [comment]
Try to generate your project in x86, go to your bin folder and get the DLL that causes the problem.
Then generate your project in x64. And when it's finished, put in your bin folder the DDL you saved just before. 
It's a bit of a trick, but I was able to make my project work like this for several months.

**Comment by trishorts** [comment]
for me, i was able to solve the problem by making sure the folder name is "native" and not something else. Not sure where the code lies that tells the program where to look for the dll, but this worked:
![image](https://user-images.githubusercontent.com/16841846/169830994-07cbb606-849e-4081-80aa-08f3cb8cfa6c.png)

**Comment by michaelgsharp** [comment]
Thanks for the workaround @trishorts. Will that work for you @GuiOliv?

Not sure how hard this would be to change, but using .net core instead of framework should also fix this issue as that native component itself wont be there.
