### ISSUE TITLE
Dataframe.Arrow always throws NotImplemented 'Name' exception for all non implemented ArrowTypeIds

### ISSUE THREAD

**Issue by gi82** [dotnet/machinelearning#6198]
**System Information (please complete the following information):**
 - OS & Version: Windows 10
 - ML.NET Version: Microsoft.Data.Analysis 0.19.1
 - .NET Version: .NET 5.0

**Describe the bug**
System.NotImplemebtedException 'Name' thrown when converting arrow record batch to Dataframe
![image](https://user-images.githubusercontent.com/23099947/169234028-1220d168-5354-4889-97ba-d0f57d99e9b7.png)

**To Reproduce**
1. Try to create a dataframe from an arrow record batch containing a non implemented ArrowTypeId DataFrame.FromArrowRecordBatch(recordBatch);

**Expected behavior**
The name of the field type should be returned 
![image](https://user-images.githubusercontent.com/23099947/169236529-dcbc7827-565d-4e2d-b5a7-9aed7127d354.png)
**Screenshots, Code, Sample Projects**
Screenshot containing error

**Comment by gi82** [comment]
The implementation in DataFrame.Arrow.cs should be changed to: 
throw new NotImplementedException(fieldType.Name);

**Comment by FabianNet** [comment]
Good change !

**Comment by gi82** [comment]
@FabianNet you can maybe then take a look at the PR :-)
