### ISSUE TITLE
Typo in Definition of Calibrators Property

### ISSUE THREAD

**Issue by ghost** [dotnet/machinelearning#6210]
[Enter feedback here]
I believe the definition should say: "This list of calibrators...", not "trainers".  The next property is about Trainers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f5b0bf3-4da2-c89b-f98d-240c95a9ac1b
* Version Independent ID: 16bef152-3cf0-f76d-daa2-18f3f1fd9202
* Content: [BinaryClassificationCatalog.Calibrators Property (Microsoft.ML)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.binaryclassificationcatalog.calibrators?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML/BinaryClassificationCatalog.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML/BinaryClassificationCatalog.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by KKghub** [comment]
Added my PR for the fix
