### ISSUE TITLE
Dose Microsoft.ML support android?

### ISSUE THREAD

**Issue by Arthur-Lee** [dotnet/machinelearning#6231]
**System Information (please complete the following information):**
 - OS & Version: Android 11.0 (Simulator)
 - ML.NET Version:  ML.NET v1.7.1
 - .NET Version: [e.g. .NET 6.0]

**Describe the bug**
Build MUAI project to refer Microsoft.ML library, and the ApplyOnnxModel will product onnxruntime DLLNotFoundException
![image](https://user-images.githubusercontent.com/9337816/173799844-c7b08102-1e4f-4ee3-a41c-16c964b29bc3.png)

**To Reproduce**

**Expected behavior**
Loading Onnx model, and do the inference correctly.

**Screenshots, Code, Sample Projects**
If applicable, add screenshots, code snippets, or sample projects to help explain your problem.

**Additional context**
There seems to a big gap for me to use this library in mobile. Currently MAUI project recommends to use MauiAsset to include local resource and https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/storage/file-system-helpers?tabs=windows#bundled-files method to retrieve the content.

All the methods only accept model path as input, however it's a little bit difficult for me to get model path in Android. I did a trick to read the bundle stream and write those bytes to cache folder and use the cache path as input.

**Comment by michaelgsharp** [comment]
Let me take a look and see what I can figure out. I'm not super familiar with MAUI myself so I will reach out to some internal people about this.

Do the bundle stream give you back a stream of bytes? So if we had an API that took in a byte steam instead of a file path would that help in that regard?

**Comment by michaelgsharp** [comment]
Also, to use Onnx Runtime you also have to additionally reference Microsoft.ML.OnnxRuntime 1.6.0 (for CPU processing) or Microsoft.ML.OnnxRuntime.Gpu 1.6.0 (for GPU processing if GPU is available). Probably just the cpu one in this case. Did you reference that additional package?

**Comment by Arthur-Lee** [comment]
> Let me take a look and see what I can figure out. I'm not super familiar with MAUI myself so I will reach out to some internal people about this.
> 
> Do the bundle stream give you back a stream of bytes? So if we had an API that took in a byte steam instead of a file path would that help in that regard?

Yes the bundle stream gives exactly the steam of bytes of model data. I just found this. https://github.com/dotnet/machinelearning/issues/6170#issuecomment-1112410097

It seems that there is already one API to load ITransfrom from stream. And I can verify this works in windows.
![image](https://user-images.githubusercontent.com/9337816/173984940-5d8ce596-4230-41aa-9987-7d772a402dc1.png)

**Comment by Arthur-Lee** [comment]
> Also, to use Onnx Runtime you also have to additionally reference Microsoft.ML.OnnxRuntime 1.6.0 (for CPU processing) or Microsoft.ML.OnnxRuntime.Gpu 1.6.0 (for GPU processing if GPU is available). Probably just the cpu one in this case. Did you reference that additional package?

I just try to add Microsoft.ML.OnnxRuntime(1.11.0) into the project. I got build error for Android, thought it works in Windows.

The detail error:
![image](https://user-images.githubusercontent.com/9337816/173985228-fb79a45e-5bb4-44ca-91e0-e0a15c98e90f.png)

The generated Info property return MapInfo type, however IValueInfo is expected.
![image](https://user-images.githubusercontent.com/9337816/173985293-a59c87fc-670f-43a7-b94b-cba26912e4d8.png)

**Comment by michaelgsharp** [comment]
@yuslepukhin do you know, or can you point me to the right person, if the android bindings for ONNX are different than the windows ones?
