### ISSUE TITLE
[DataFrame] Allow quote escaping

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#6238]
Loading data from a column containing quotes inside a string shouldn't break. 

```text
"this is one column value which includes a "" character" 
```

**Comment by dakersnar** [comment]
I believe this issue has been solved already for LoadCsv (I added unit tests to confirm this). However, I found bugs related to this in WriteCsv. I have a fix that will go up as soon as https://github.com/dotnet/machinelearning/pull/6303 is merged.
