### ISSUE TITLE
load ONNX model(RNN[LSTM]) can not work 

### ISSUE THREAD

**Issue by zhangfeibao** [dotnet/machinelearning#6241]
**System Information**
 - OS & Version: Windows 10]
 - ML.NET Version: ML.NET v1.5.5
 - .NET Version: NET 6.0

I got the onnx model from tf2.
The model infomation is:
![image](https://user-images.githubusercontent.com/12379132/176447293-f3e6f9f2-cba6-4dfc-a53f-f3a6f7932c08.png)
I load the onnx model follow the [document.](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-use-automl-onnx-model-dotnet)

```c#
private static ITransformer GetPredictionPipeline(MLContext mlContext)
{
    var inputColumns = new string[]
    {
        "model"
    };

    var outputColumns = new string[] { "dense" };

    var onnxPredictionPipeline =
        mlContext
        .Transforms
        .ApplyOnnxModel(
        outputColumnNames: outputColumns,
        inputColumnNames: inputColumns,
        ONNX_MODEL_PATH);

    var emptyDv = mlContext.Data.LoadFromEnumerable(new OnnxInput[] {});    //the line will throw the exception

    return onnxPredictionPipeline.Fit(emptyDv);
}

```

when i ran the app,I got the exception at the line.
> **System.InvalidOperationException:“Input** shape mismatch: Input 'model' has shape 1,50,4, but input data is of length 1.”

I have tryed many time to resove the problem.but it just can't work!

**Comment by luisquintanilla** [comment]
@zhangfeibao what does your `ONNXInput` class look like?
