### ISSUE TITLE
Tensorflow's hardware CPu requirements, such as the minimum REQUIRED CPu configuration, do not use the GPU 

### ISSUE THREAD

**Issue by wangLinWuYing** [dotnet/machinelearning#6248]
Tensorflow's hardware CPu requirements, such as the minimum REQUIRED CPu configuration, do not use the GPU

**Comment by wangLinWuYing** [comment]
SciSharp.TensorFlow.Redist Are there any restrictions on CPU requirements, such as i3 CPU and J1900,

**Comment by michaelgsharp** [comment]
From my understanding there are no minimum CPU requirements.

If you want to use the CPU you need to get:
SciSharp.TensorFlow.Redist v1.14.0.

If you want to use the GPU you need to get:
* Windows -> SciSharp.TensorFlow.Redist-Windows-GPU
* Linux -> SciSharp.TensorFlow.Redist-Linux-GPU
 v1.14.0 based on your OS.
