### ISSUE TITLE
Prediction engine outputs only one class

### ISSUE THREAD

**Issue by elisaho** [dotnet/machinelearning#6250]
**System Information (please complete the following information):**
 - Windows 10 build 19044.1766
 - ML.NET v1.7.1
 - .NET 6.0

**Describe the bug**
For a given image input to the prediction engine, the output schema only allows for one output detected class (and a single corresponding score). However, I would like for all detected classes to be returned. 
I am working on consuming the tensorflow model for object detection (exported from Custom Vision as GeneralCompactS1) in .Net using ML.NET. I have closely referenced:  
[https://github.com/dotnet/machinelearning-samples/tree/main/samples/csharp/end-to-end-apps/DeepLearning_ImageClassification_TF/TFImageClassification ](url)
I know the model can return multiple detected classes as I have consumed the same tensorflow model with python, tensorflowsharp, and tensorflow.net. I have tried appending column names with ':0' and ':1'(e.g. detected_classes:0) and changing the output tensor types (e.g. for detected_classes, change long to long[]), both to no avail. 

**Expected behavior**
I expect all detected classes and their corresponding scores to be returned. 

**Screenshots, Code, Sample Projects**
![image](https://user-images.githubusercontent.com/82560572/178418379-6fa91a35-5518-47b6-af35-c5f2fc2c89f4.png)
![image](https://user-images.githubusercontent.com/82560572/178418911-2ffebbb3-aa80-48ca-890f-eec5362cc251.png)
![image](https://user-images.githubusercontent.com/82560572/178419006-30a660f7-0f7e-487b-b6a9-77b0ccc928ef.png)
![image](https://user-images.githubusercontent.com/82560572/178419132-3d1d4a47-7514-4b63-96ad-a63df6314c6b.png)
![image](https://user-images.githubusercontent.com/82560572/178419196-bf0bfe97-fd83-4dec-aa61-50f9beb13b61.png)
![image](https://user-images.githubusercontent.com/82560572/178419998-148f837e-8884-4643-9217-7101974259ea.png)
<img width="766" alt="Screenshot 2022-07-12 160630" src="https://user-images.githubusercontent.com/82560572/178420335-968c8ae3-6dbd-42b9-9507-027de7675011.png">

**Comment by michaelgsharp** [comment]
Would you be able to share sample code/data and especially the model so we can take a look?

**Comment by elisaho** [comment]
The model: 
[model.zip](https://github.com/dotnet/machinelearning/files/9106665/model.zip)

In startup.cs
`services.AddPredictionEnginePool<ImageInputData, ImageLabelPredictions>();
            services.AddOptions<PredictionEnginePoolOptions<ImageInputData, ImageLabelPredictions>>()
                .Configure(options =>
                {
                    options.ModelLoader = new InMemoryModelLoader(_mlnetModel);
                });
`

In ImageInputData.cs
`public class ImageInputData
    {
        [ImageType(320, 320)]
        public Bitmap? Image { get; set; }
    }
`

In ImageLabelPredictions.cs
`
public class ImageLabelPredictions
{
    [ColumnName("detected_boxes:0")]
    public float[]? PredictedBoxes;

    [ColumnName("detected_classes:0")]
    public long PredictedLabels;

    [ColumnName("detected_scores:0")]
    public float PredictedScores;
}
`

**Comment by elisaho** [comment]
Hi, thanks for getting back to me! Unfortunately I cannot share my model but you can generate a sample model of the same kind by training multiple object detected classes (e.g. orange, apple, pear) in Azure's custom vision with Object Detection General Compact s1.

**Comment by michaelgsharp** [comment]
We are looking into generating one so that we can investigate this further. While we are doing that, have you tried running this with `addBatchDimensionInput` set to true? I'm wondering if it has to do with the output shape are how we parse it.

**Comment by elisaho** [comment]
Running with addBatchDimensionsInput set to true yields the exception `InvalidArgumentError: The first dimension of paddings must be the rank of inputs[4,2] [1,1,320,320,3]`. I have moved away from using the tensorflow to using an ONNX model instead. Thanks for your help though!

**Comment by luisquintanilla** [comment]
@elisaho just want to confirm, for the export format, you were using TensorFlow? If so, which TF format?

**Comment by elisaho** [comment]
@luisquintanilla 
![image](https://user-images.githubusercontent.com/82560572/184578147-921aefbb-5448-45e3-bf83-867ab16a35a8.png)
