### ISSUE TITLE
Error in code on this web page

### ISSUE THREAD

**Issue by CBrauer** [dotnet/machinelearning#6253]
Why am I getting this error?
![error](https://user-images.githubusercontent.com/1317234/179406005-8a411a21-07a4-4c76-9bd2-edbaa9013e36.PNG)

**Comment by feiyun0112** [comment]
you need download Aduit dataset to app BaseDirectory

For more details,  please see [https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.samplesutils.datasetutils.loadfeaturizedadultdataset?view=ml-dotnet-preview#microsoft-ml-samplesutils-datasetutils-loadfeaturizedadultdataset(microsoft-ml-mlcontext)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.samplesutils.datasetutils.loadfeaturizedadultdataset?view=ml-dotnet-preview#microsoft-ml-samplesutils-datasetutils-loadfeaturizedadultdataset(microsoft-ml-mlcontext))

**Comment by CBrauer** [comment]
Obviously I did that!

**Comment by feiyun0112** [comment]
I read [the implementation code](https://github.com/dotnet/machinelearning/blob/main/src/Microsoft.ML.SamplesUtils/SamplesDatasetUtils.cs) and found that the logic is like this: 
- should exits `.git` folder
- dataset filename should be `test\data\adult.txt`

**like this:**
![image](https://user-images.githubusercontent.com/10190938/179888707-44d2b3a9-5e18-46e5-9d1f-bb66f486a76e.png)

**Comment by michaelgsharp** [comment]
Did putting it in the correct folder structure fix it?
