### ISSUE TITLE
Model.Transform returns results in different order than the input DataView

### ISSUE THREAD

**Issue by derekdiamond** [dotnet/machinelearning#6258]
**System Information (please complete the following information):**
Windows 11
ML.NET 1.70
.NET 4.8

**Describe the bug**

I have the following code:

                var res = Model.Transform(dataView);
                var resSchema = res.Schema;
                var resCsr = res.GetRowCursor(resSchema);

When stepping through the result cursor the order of the results does not match the input order of the dataview. I need them in order so that I can match with the original dataset.

As a work around I am doing the transform one by one, that is creating dataviews that return one row, so it can easily then match to the input dataset. However this is very very slow, taking half an hour to transform 2000 records.

I either need a mechanism to pass a key value per record that is passed through the transform, without it being used in the training process.
 
**To Reproduce**
Create a regression model on a simple set of data say some random values x,y, x + 2 * y.
Then create a test set of x,y's containing say 50 records. Then do a transform on the dataview and then traverse the result cursor and see that the x,y's are returned in a different order. However the first record always comes through first. Subsequent records come back in some random order.

**Expected behavior**

Returned records from the result cursor should come through in the same order as the input dataview, or have a way to identify what record in the source the result record comes from. Note: trying to match on the input record column values could possibly be done, but the floating point values may not match exactly due to conversions from double to float and if there are many columns this becomes a slow process.

**Comment by michaelgsharp** [comment]
Thanks for letting us know. We should be returning them in the same order, so if we aren't thats definitely a bug.

Can you share a whole sample pipeline so we can make sure we follow all the same steps you did to see the issue?

**Comment by dakersnar** [comment]
@derekdiamond tagging you directly for visibility, we need a bit more information to reproduce your issue. Thanks!
