### ISSUE TITLE
Dummy Estimator / Transformer ?

### ISSUE THREAD

**Issue by vpenades** [dotnet/machinelearning#6271]
When creating a pipeline, the common practice is to write this sort of spaguetti code:

```c#

var pipeline = mlContext.Transforms.Something( .... )
    .Append( mlContext.Transforms.SomethingElse(...) )
    .Append( mlContext.Transforms.SomethingElse(...) )
    .Append( mlContext.Transforms.SomethingElse(...) )
    .Append( mlContext.Transforms.SomethingElse(...) )
    .Append( mlContext.Transforms.SomethingElse(...) )
```

If I want to split this into separated functions, each funcion will usually return some variation of `EstimatorChain<SomeTransformer>`

The problem is every time I need to refactor which estimators I slice and move from one function to another, I need to continuosly change the returning type, because it depends on what was returned by the last .Append, and it's a complete pain.

**Describe the solution you'd like**

I was wondering if there's some sort of "does nothing" "NoOp", null, or Dummy Estimator/Transformer pair that does absolutely nothing, so it can always be returned by a function, by appending it as the last element, something like this:

```c#

public EstimatorChain<DummyTransformer> GetPipeline1()
{
    var pipeline = mlContext.Transforms.Something( .... )
      .Append( mlContext.Transforms.SomethingElse(...) )
      .Append( mlContext.Transforms.SomethingElse(...) )
      .Append( mlContext.Transforms.DummyEstimator() );
}

public EstimatorChain<DummyTransformer> GetPipeline1()
{
    var pipeline = mlContext.Transforms.Something( .... )
      .Append( mlContext.Transforms.SomethingElse(...) )
      .Append( mlContext.Transforms.DummyEstimator() );
}
```

So all the funcions will return the same type, which will help a lot in refactoring, and moving away from spaguetti code.

**Describe alternatives you've considered**

Right now I'm using a SelectColumns estimator, and selecting all current columns, which is the closest alternative I've found.

I also considered implementing my own "dummy" estimator, by deriving from TrivialEstimator, but I don't have the knowledge to dig so deep.

**Comment by dakersnar** [comment]
Unfortunately, we don't really have a dummy transformer, but you might be able to use the `CopyColumns` transformer for the same effect. Notably, it doesn't actually copy any memory, it just points from the new name to the old name. Additionally, you can copy from a name to itself, which would effectively be the no-op you are looking for.
