### ISSUE TITLE
[DataFrame] Head should return min(DF length, param)

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#6275]
## Problem

Given a DataFrame with 3 rows, calling `Head(5)` throws an error. 

![image](https://user-images.githubusercontent.com/46974588/183127094-cb6b8a88-b0b0-4412-a871-faa3f8691fcb.png)

## Suggested solution

Head should return the minimum of the number provided as a parameter and the length of a DataFrame

**Comment by luisquintanilla** [comment]
@tarekgh @dakersnar @tannergooding I think this one's open to discussion. The error message to me looks clear and tells users what the problem is. However, I'm not sure how other libraries handle this issues, whether they throw an error and expect the user to pass in the correct number of rows they want or if it's handled automatically and return the min(n,collectionLength) where n is the number of rows specified by the users.

**Comment by dakersnar** [comment]
I'm not super familiar with how this functionality is commonly used. Are there cases where users could benefit from asking for "up to X rows" instead of "exactly X rows"?

**Comment by luisquintanilla** [comment]
Nothing really comes to mind. The intent of Head is to do a quick check of your data to make sure it was loaded correctly or the operations you applied produced the expected result. Often times the number of rows requested by the user is <100. I wonder if some options here that would help are:

1. Define an overload where we select a default. When a user calls the `Head()` method without passing any parameters, we return the first min(5,collectionLength). However, if they provide the number of rows they want `Head(5)`, it's up to them to know whether they even have that much data.
2.  Maybe [Ranges / Indices](https://docs.microsoft.com/dotnet/csharp/whats-new/tutorials/ranges-indexes) can help here.

**Comment by tarekgh** [comment]
The current behavior looks right to me which is throwing OOR exception. This is how it works in general when trying to access data which does not exist in the current range.  Does DataFrame have any property to return the number of rows? if not, I think this will be good to add. so the call can be something like: `Head(DF.RowsCount)`.

> Maybe [Ranges / Indices](https://docs.microsoft.com/dotnet/csharp/whats-new/tutorials/ranges-indexes) can help here.

Note that Range/Index types are not supported in the netstandard 2.0 which will make some challenges to use it.

**Comment by luisquintanilla** [comment]
Thanks all for looking at this. I think we can leave as is. You can get the number of rows in a similar way like you've suggested @tarekgh. Closing this issue.
