### ISSUE TITLE
Native ML.NET notebook

### ISSUE THREAD

**Issue by papyr** [dotnet/machinelearning#6290]
Hello, can we get a native notebook inside Visual Studio or VS Code, since we already have a designer surface with all the drag and drop controls?

**Comment by luisquintanilla** [comment]
@papyr there is currently a notebook experience in VS and VS code powered by [.NET Interactive](https://github.com/dotnet/interactive). Here are some samples to get started. 

https://github.com/dotnet/csharp-notebooks

Is this what you're referring to?

**Comment by papyr** [comment]
yes thanks!
Does it work in VS 2022 community or pro

**Comment by luisquintanilla** [comment]
@papyr can you try cloning the repo and using VS Code instead of VS. 

Re:NER, we are actively working on that at the moment. We're tracking the discussion in #630 

Would you be able to share your scenario? Also, what does your data look like and what tools are you using today to tag your data?
