### ISSUE TITLE
NotebookMonitor doesn't display AutoML training progress.

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#6298]
**System Information (please complete the following information):**
 - OS & Version: Windows 11
 - ML.NET Version: 0.20.0-preview.22356.1
 - .NET Version: .NET 6.0

**Describe the bug**

NotebookMonitor displays gray box in output window instead of AutoML training progress

**To Reproduce**

Run the following notebook https://github.com/dotnet/csharp-notebooks/blob/main/machine-learning/03-Training%20and%20AutoML.ipynb

**Expected behavior**

NotebookMonitor displays AutoML training progress

**Screenshots, Code, Sample Projects**

![image](https://user-images.githubusercontent.com/46974588/185819923-6b2a31e5-0d2c-4050-a9bc-1373a568d03d.png)

**Comment by LittleLittleCloud** [comment]
dup of https://github.com/microsoft/VS-Notebook/issues/231

**Comment by luisquintanilla** [comment]
Closing since it's already being tracked in VS-Noteboook repo
