### ISSUE TITLE
ML.NET Github tagging example from MS Build

### ISSUE THREAD

**Issue by GKersten** [dotnet/machinelearning#63]
I just attended to the session on BUILD 2018 with Scott Hanselman who showed an example of ML.NET for tagging Github pull requests. Is this example available somewhere?

**Comment by justinormont** [comment]
@zeahmed

**Comment by zeahmed** [comment]
Thanks GKersten! I will update the thread once it is available.

**Comment by GalOshri** [comment]
The code for this is now available [here](https://github.com/dotnet/machinelearning-samples/tree/master/samples/end-to-end-apps/github-labeler).

**Comment by danmosemsft** [comment]
Seems resolved. Does it work for you @GKersten ? 
@Anipik could you point to the latest code you used?

**Comment by Anipik** [comment]
This is the most recent code https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/github-labeler
