### ISSUE TITLE
High vulnerability alert in Newtonsoft.Json v10.0.3

### ISSUE THREAD

**Issue by aswin-integration** [dotnet/machinelearning#6310]
**System Information :**
 - Windows 10
 - ML.NET v1.7.1
 - .NET 5.0

**Describe the bug**
The Microsoft.ML v1.7.1 library currently uses Newtonsoft.Json **v10.0.3** which have a ['high' level vulnerability reported](https://github.com/advisories/GHSA-5crp-9r3c-p9vr) . The vulnerability fix is available in Newtonsoft.Json **v13.0.1** (https://www.nuget.org/packages/Newtonsoft.Json/13.0.1). Is there going to be a official release fixing the dependency of Newtonsoft to the latest ? 

**Screenshots, Code, Sample Projects**
https://github.com/advisories/GHSA-5crp-9r3c-p9vr
https://www.nuget.org/packages/Microsoft.ML/1.7.1#dependencies-body-tab

**Additional context**

**Comment by dakersnar** [comment]
It looks like this has been done already, closing this issue:
https://github.com/dotnet/machinelearning/blob/9652e59c5d639cd30390fcfd47b525eb0bd8665e/eng/Versions.props#L45
https://github.com/dotnet/machinelearning/pull/6276
