### ISSUE TITLE
possible wrong value on example table

### ISSUE THREAD

**Issue by superichmann** [dotnet/machinelearning#6311]
The example described in the article consists of test data table value that does not exist in the output table.

`the output of applying this Estimator would keep the first and the third slots only `

In the table the value of the last line is
<html>
<body>

False | 0,5
-- | --

</body>
</html>

Which perhaps should be

<html>
<body>

False | 0,0
-- | --

</body>
</html>

Or maybe the last line of the input table is wrong?

<html>
<body>

False | 0,7,0
-- | --

</body>
</html>
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58a8434a-e5b9-a96f-e70a-c281f071d0c9
* Version Independent ID: 26f433a0-138d-54b4-86a8-6c1b0f7088f7
* Content: [MutualInformationFeatureSelectingEstimator Class (Microsoft.ML.Transforms)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.mutualinformationfeatureselectingestimator?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML.Transforms/MutualInformationFeatureSelectingEstimator.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Transforms/MutualInformationFeatureSelectingEstimator.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by dakersnar** [comment]
That does seem like a typo. @luisquintanilla where would this need to be updated?
