### ISSUE TITLE
Machine Learning for .NET Developers Survey - 2022

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#6322]
Every year we conduct a survey to gather feedback on pain points and feature requests that help shape the direction of Machine Learning in .NET.

This past year we have made major improvements to [ML.NET](https://dot.net/ml) tooling and APIs, and now we're investigating new areas to improve and grow, including documentation, data prep, notebooks, deep learning, MLOps, model explainability, and more.

Please take this ~10 minute survey to give your input on what you want to see next in ML.NET, and optionally leave your contact information at the end if you'd like to talk with the ML.NET team about your feedback.

## [Take the Survey](https://www.surveymonkey.com/r/mlnet-gh-2022)

**Comment by saint4eva** [comment]
Done.

**Comment by luisquintanilla** [comment]
Thanks all for the feedback. Closing this issue.
