### ISSUE TITLE
[ML.Net, c#]  LightGBM re-training and Importing LightGBM CLI/MPI model

### ISSUE THREAD

**Issue by wil70** [dotnet/machinelearning#6328]
1. Can I retrain LightGBM? 
    1.a. I tried via AutoML and it seems to start from scratch when I do a FIT or I call MLModel1.Training.cs " public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)" auto generated code.
    1.b. In the documentation ["Re-train a model"](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/retrain-model-ml-net), LightGBM is not listed as re-traine-able? 
           1.b.1. is it still true (asking as the documentation is 9 months old)? TY!
           1.b.2 I can see from Python or even XGBM c/c++ you can retrain? using init_model option of lightgbm.train
2. Can I use the model generated by [LightGBM CLI/MPI ](https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-mpi-version) in ML.net?
Thanks!

**Comment by wil70** [comment]
I think (2) ie "being able to import in ML.net a model trained by LightGBM" would be awesome. We would gain "ditributed training" via MPI + "retraining", buying time to ML.net to implement those features?

https://github.com/microsoft/LightGBM

**Comment by luisquintanilla** [comment]
Importing models is possible as of ML.NET 3.0. Tracking retraining in #6502.
