### ISSUE TITLE
Add FeaturizeDateTime transform to docs

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#6333]
Add [`FeaturizeDateTime`](https://github.com/dotnet/machinelearning/blob/0577957256c296fdea2deb6b6e00e7be9b458167/src/Microsoft.ML.Featurizers/DateTimeTransformer.cs) transform to API docs. Currently it doesn't show up for the latest 1.7.0 and 2.0.0-preview versions. 

[.NET API Browser](https://learn.microsoft.com/dotnet/api/?view=ml-dotnet-2.0.0&term=FeaturizeDateTime)

**Comment by michaelgsharp** [comment]
As discussed we won't be adding this as the library we get it from is no longer supported.
