### ISSUE TITLE
Add ReplaceMissingTimeSeriesValues to docs

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#6334]
Add [`ReplaceMissingTimeSeriesValues`](https://github.com/dotnet/machinelearning/blob/0577957256c296fdea2deb6b6e00e7be9b458167/src/Microsoft.ML.Featurizers/TimeSeriesImputer.cs) to reference API docs. It's missing from the latest 1.7.0 and 2.0.0 versions. 

[.NET API Browser](https://learn.microsoft.com/dotnet/api/?view=ml-dotnet&preserve-view=true&term=ReplaceMissingTimeSeriesValues)

**Comment by michaelgsharp** [comment]
As discussed we will not be adding this as the library we got that from is no longer supported.
