### ISSUE TITLE
LightGBM Tracking Issue

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#6337]
This work items is intended to track LightGBM related improvements to ML.NET.

## Work Items

- [x] #6500
- [x] #6501
- [ ] #6502
- [x] #6503

### Upgrade version

- [x] #5447

### Load LightGBM model

- [x] #6328
- [x] #6296

### Retrain LightGBM model

- [x] #6328

### Expose additional parameters / functionality

- [x] #1651
  - PR closed providing monotonic support #2330
- [x] #1992
- [x] #1997

### Bugs

- [x] #5549
- [x] #6426

### Discussions

#6065

**Comment by torronen** [comment]
@luisquintanilla  Could you consider adding the device_type switch for LightGBM when upgrading it? I know it has dependency on lightGBM team to publish pre-built GPU libraries, but adding the switch would allow users to compile the GPU binary and use it without editing Microsoft.ML library. 

For me, it has worked well on Windows 10/11, RTX 1080 and 3090, using these steps:
1) compile LightGBM  GPU (take note to use same version as Microsoft.ML)
2) update res["device_type"]="gpu" array in *.LightGBM
3) update library dll name in source to use your compiled version, mine is lightgbm_gpu, same file as above

The only exception when it does not work is sometimes I get errors of too many categories. The other point to note is that only second part of LightGBM algo can be run on GPU, so it is not as fast as some might expect. Biggest difference is in big datasets.

So, I would like to be able to change device type in LightGBM, and potentially the library filename, then one could use the default Microsoft.ML without modification. For my uses cases, I think this is the only remaining thing why I may need to edit the library source. Compiling the LightGBM binary is easy and I suppose unofficial versions of GPU binary could be easily shared.
