### ISSUE TITLE
Update paths for Text Classification API files

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#6368]
As part of the model training process, some files like *dict.txt*, *encoder.json*, and *vocab.bpe* are created and stored using absolute paths. For some scenarios like Model Builder, it breaks the experience. 

Update ML.NET to store these files using relative paths or allow users to set the path they want to store files in (similar to `workspacePath` in Image Classification trainer)

**Comment by zewditu** [comment]
Model builder expects the dict.txt in  the path of a host process `C:\Program Files\Microsoft Visual Studio\2022\Preview\common7\ServiceHub\Hosts\ServiceHub.Host.netfx.x64`
