### ISSUE TITLE
Examples in the documentation need  to reference code, rather than embedding C# in the XML

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#637]
Our examples in the documentation currently aren't very comprehensive, because they live in XML, and it is not easily maintainable to write longer code snippets embedded in XML. 

The infrastructure for docs.microsoft.com supports cross-referencing other files within the XML. 
Those other files can be C# files and have more fully fledged examples, that compile. 

Setup another folder within Microsoft.ML.Tests, similar to scenarios, that will contain examples for each components. More than one component can be used for the scenario, but they should be kept simple. 
Those methods can be reused by the tests.

This issue will be considered resolved after  setting up one such example end-to-end.

**Comment by JRAlexander** [comment]
You could create a tutorial or how to or other articles in the [dotnet/docs machinelearning repo](https://github.com/dotnet/docs/tree/master/docs/machine-learning). This would give you more flexibility. Also, any samples you'd like to reference can go in the [dotnet/samples machinelearning](https://github.com/dotnet/samples/tree/master/machine-learning).

**Comment by sfilipi** [comment]
I would prefer to keep the samples in the actual repo, actually. If new components are added, samples and doc can go at the same time.

**Comment by sfilipi** [comment]
Resolved with #1105
