### ISSUE TITLE
ML.Net not using Integrated Intel GPU

### ISSUE THREAD

**Issue by crazyoutlook** [dotnet/machinelearning#6372]
**System Information (please complete the following information):**
 - OS & Version: Windows 10
 - ML.NET Version: ML.NET v1.6, ML.OnnxRuntime v1.7, ML.OnnxRuntime.Gpu v1.13
 - .NET Version: NET 6.0
 - GPU: Integrated GPU
 -  
**Describe the bug**
ML.NET is NOT using my intel integrated graphics - Inter HD Graphics 620. I am running ONNX model with ML.NET
However, When I execute same code on a desktop which has dedicated graphics card (Nvidia), it uses GPU

**To Reproduce**
1. Run the ML.NET ONNX pipeline code on a machine which has integrated graphics card
2. Check GPU usage. It shows GPU not being used. Instead, it used CPU
3. Run the ML.NET ONNX pipeline code on a machine which has dedicated graphics card
4. Check GPU usage. It shows GPU being used.

**Expected behavior**
If the machine has integrated graphics card, then ML.NET should use it.

**Screenshots, Code, Sample Projects**
 var pipeline = mlContext.Transforms.ResizeImages(resizing: ImageResizingEstimator.ResizingKind.Fill, outputColumnName: "data", imageWidth: ImageSettings.imageWidth, imageHeight: ImageSettings.imageHeight, inputColumnName: nameof(ImageInput.Image))
                                .Append(mlContext.Transforms.ExtractPixels(outputColumnName: "data", orderOfExtraction: ImagePixelExtractingEstimator.ColorsOrder.AGRB))
                                .Append(mlContext.Transforms.ApplyOnnxModel(modelFile: modeltoInfer.ModelPath, outputColumnName: "model_outputs0", inputColumnName: "data", gpuDeviceId: 0, fallbackToCpu: true));

In above piece of code, I am using gpuDeviceId:0 and fallbackToCpu:True

**Additional context**
I am using value: gpuDeviceId:0 for integrated graphics card. Should I be using something else if I am using integrated card ?

![gpu](https://user-images.githubusercontent.com/67651625/195282925-d5e8364b-169b-42e6-92c2-44e641bdc64c.PNG)

**Comment by crazyoutlook** [comment]
Hello Team, kindly provide your inputs

**Comment by michaelgsharp** [comment]
Intel Integrated graphics is just another way of saying that the CPU is handling the graphics and that there isn't a dedicated card. Because its running on the CPU anyways, setting the `gpuDeviceId` won't actually change anything.

Unfortunately there is nothing we can do about this as its a hardware limitation, and so if you need to run on a GPU you have will to be on a machine with a dedicated card.
