### ISSUE TITLE
AutoML experiment.Execute DateTime problem Only supported feature column types are Boolean, Single, and String.

### ISSUE THREAD

**Issue by rzechu** [dotnet/machinelearning#6376]
**System Information (please complete the following information):**
 - OS & Version: Windows 10
 - ML.NET Version: ML.NET v1.7.0
 - .NET Version: NET 6

**Describe the bug**
I have auto generated IDataView using SQL Query Loader (not using predefined Class as InputType)
Sample SQL
SELECT cast(GETDATE() as datetime) as colDateTime, CAST(1 as real) as colInt

```
var loader = MLContext.Data.CreateDatabaseLoader(columns.ToArray());
var dbSource = new DatabaseSource(SqlClientFactory.Instance, connectionString, sqlQuery);
var iDataView = loader.Load(dbSource);
```

My query contains date/datetime column and model can't be trained.
I understand there's limitations and I am casting all ints to real etc.  SELECT CAST(colInt as real) colInt FROM xyz...
But how to deal with date/datetimes (use unix epoch format? / datetime.ticks ) or I found here on [github ](https://github.com/dotnet/machinelearning/issues/4045) (but not sure if its gonna work. I had issues) 
`dataProcessPipeline =dataProcessPipeline.Append(_mlContext.Transforms.Conversion.ConvertType(feature, feature, DataKind.Single));`
//Cannot implicitly convert type 'Microsoft.ML.Data.EstimatorChain<Microsoft.ML.Transforms.TypeConvertingTransformer>' to 'Microsoft.ML.Transforms.ColumnSelectingEstimator'	Intense.AI.AutoML	C:\_WorkGIT\Forms\Intense.AI\Intense.AI.AutoML\Trainers\MulticlassClassification.cs	46	Active

**To Reproduce**

```
var loader = MLContext.Data.CreateDatabaseLoader(columns.ToArray());
var dbSource = new DatabaseSource(SqlClientFactory.Instance, connectionString, sqlQuery);
var trainingDataView = loader.Load(dbSource);

var progressHandler = new MulticlassExperimentProgressHandler(this);
ExperimentSettings.MaxExperimentTimeInSeconds = (uint)maxExperimentTimeInSeconds;
MulticlassExperimentSettings multiClassExperimentSettings = (MulticlassExperimentSettings)ExperimentSettings;

var experiment = MLContext.Auto().CreateMulticlassClassificationExperiment(multiClassExperimentSettings);
var experimentResult = experiment.Execute(trainData: trainingDataView, labelColumnName: labelColumnName, progressHandler: progressHandler); //exception here Only supported feature column types are Boolean, Single, and String.

```

**Comment by luisquintanilla** [comment]
Hi @rzechu 

I believe you're using an older version of the AutoML API. I would recommend using the latest version.

https://github.com/dotnet/csharp-notebooks/blob/main/machine-learning/E2E-Classification%20with%20Iris%20Dataset.ipynb

**Comment by michaelgsharp** [comment]
Closing as this should be resolved in the latest version.
