### ISSUE TITLE
Outdated version of .NET Interactive breaks interactive extensions in notebooks

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#6381]
Installing components with interactive extensions `Microsoft.Data.Analysis` and `Microsoft.ML.AutoML` breaks in notebooks.

![image](https://user-images.githubusercontent.com/46974588/195719486-506e99c8-0f84-4aa2-aef7-c9d929df793e.png)

Update version to latest: 1.0.0-beta.22504.6

https://github.com/dotnet/machinelearning/blob/c5f03e2c42940b23ea3f9eed88f23807d9f26453/eng/Versions.props#L38

https://github.com/dotnet/machinelearning/blob/c5f03e2c42940b23ea3f9eed88f23807d9f26453/eng/Versions.props#L39

The version for formatting and interactive is always in sync, so it's recommended to use just one variable.

**Comment by luisquintanilla** [comment]
@ericstj as part of updating dependency versions can we make sure this one gets updated.

@colombod can you please confirm that I got the version that needs to be updated right.

**Comment by ericstj** [comment]
Looks like a breaking change was made in public surface area of `Microsoft.DotNet.Interactive`.  While we can continue to update this as we did here https://github.com/dotnet/machinelearning/pull/5710 these sorts of breaking changes should be avoided if possible.

@jonsequitur did you mean to break this with https://github.com/dotnet/interactive/commit/8dde5d88e859b3919614a6ebcdc981259ac6ffa7?  You could have kept the old extension method and have it call the instance method you added to preserve binary compatibility.

**Comment by ericstj** [comment]
Also, looks like @LittleLittleCloud already made this fix in https://github.com/dotnet/machinelearning/commit/febcb920e025270450c226a94a29473abf0e09d9.  I've opened an issue in dotnet/interactive to fix the breaking change : https://github.com/dotnet/interactive/issues/2357
