### ISSUE TITLE
Unable to find an entry point named TF_StringEncodedSize in DLL tensorflow

### ISSUE THREAD

**Issue by horczech** [dotnet/machinelearning#6404]
**System Information:**
 - OS & Version:  Windows 11
 - ML.NET Version: ML.NET v1.7.1
 - .NET Version: .NET 6.0
 - SciSharp.TensorFlow.Redist Version: v2.7.0

**Describe the bug**
When I try to learn `MobilenetV2` using the `mlContext.MulticlassClassification.Trainers
.ImageClassification` API on ML.NET version 1.7.1 and Redist version 2.7.0 I get the following error: `System.EntryPointNotFoundException: 'Unable to find an entry point named 'TF_StringEncodedSize' in DLL 'tensorflow'.'`

**To Reproduce**
Try to learn  `MobilenetV2` using the `SciSharp.TensorFlow.Redist  v2.7.0` or run the code on my [GIT](https://github.com/horczech/MLDotNetBug)

**Expected behavior**
The model will get successfully trained.

**Screenshot**
![image](https://user-images.githubusercontent.com/5252663/197462660-6814344a-7901-496d-9a35-0158be6dacd4.png)

**Comment by zdz72113** [comment]
you can try change the SciSharp.TensorFlow.Redist to 2.3.1,ref to https://github.com/dotnet/machinelearning/issues/6040

**Comment by horczech** [comment]
@zdz72113 I know, but that's only a temporary fix, not a solution.

**Comment by michaelgsharp** [comment]
@horczech right now we only support 2.3.1. We are tracking the upgrade issue here https://github.com/dotnet/machinelearning/issues/6028. Once the upgrade has been completed the version you are using will work fine. Closing this for now as we are tracking elsewhere.
