### ISSUE TITLE
How to build transform-only pipelines

### ISSUE THREAD

**Issue by aho81** [dotnet/machinelearning#642]
I found comments, that there should be a way to use transforms without the need of a trainer/learner (i.e., building a "processing / transform - pipeline instead of an LearningPipeline, cp.  https://github.com/dotnet/machinelearning/issues/259#issuecomment-393362342). Unfourtunately, I could not find out, how to achieve this.

In my usecase, I want to determine similarity of documents with n-gram vectorization and cosine distance. The functionalty for featurization is given by the TextFeaturizer (https://docs.microsoft.com/de-de/dotnet/api/microsoft.ml.transforms.textfeaturizer). In this usecase I don't want to do a training (yet), but am interessted in the output in the result of the TextFeaturizer itself.

Accessing the results of partial steps could be helpful for debugging LearningPipelines too (cp. discussion here: https://github.com/dotnet/machinelearning/issues/259).
@TomFinley

**Comment by Zruty0** [comment]
As far as I know, this is currently not possible. 

However, once we build the final API (see #583), you will be able to access the output of transforms without having to train a model.

In fact, the 'trained model' will be just one form of 'transformer', and you will be able to have as many of them chained together as you want (including 0), and mix and match them with other transformers, like TextFeaturizer.

**Comment by aho81** [comment]
Thanks! I'm looking forward to the final API.
