### ISSUE TITLE
Custom WordEmbeddingEstimator with ApplyWordEmbedding

### ISSUE THREAD

**Issue by greenpau** [dotnet/machinelearning#6432]
I am using  `WordEmbeddingEstimator.PretrainedModelKind.GloVe300D` that comes with `Microsoft.ML`.

```cs
            var gloVe300DPipeline = mlContext.Transforms.Text.NormalizeText("Text")
                .Append(mlContext.Transforms.Text.TokenizeIntoWords("Tokens", "Text"))
                .Append(mlContext.Transforms.Text.ApplyWordEmbedding(
                    "Features",
                    "Tokens",
                    WordEmbeddingEstimator.PretrainedModelKind.GloVe300D
                ));
```

There is a way to apply custom 

https://learn.microsoft.com/en-us/dotnet/api/microsoft.ml.textcatalog.applywordembedding?view=ml-dotnet#microsoft-ml-textcatalog-applywordembedding(microsoft-ml-transformscatalog-texttransforms-system-string-system-string-system-string)

```
            var pathToCustomModel = @".\custommodel.txt";
            using (StreamWriter file = new StreamWriter(pathToCustomModel, false))
            {
                file.WriteLine("great 1.0 2.0 3.0");
                file.WriteLine("product -1.0 -2.0 -3.0");
                file.WriteLine("like -1 100.0 -100");
                file.WriteLine("buy 0 0 20");
            }
            var textPipeline = mlContext.Transforms.Text.NormalizeText("Text")
                .Append(mlContext.Transforms.Text.TokenizeIntoWords("Tokens",
                    "Text"))
                .Append(mlContext.Transforms.Text.ApplyWordEmbedding("Features",
                    pathToCustomModel, "Tokens"));
```

Say I have MPNet model here: https://huggingface.co/microsoft/mpnet-base/tree/main

How do I convert it to be used with the `ApplyWordEmbedding`?

**Comment by michaelgsharp** [comment]
@luisquintanilla any thoughts on this?

@greenpau do you still need help on this?

**Comment by greenpau** [comment]
>  do you still need help on this?

@michaelgsharp , would be nice knowing how to do it.

**Comment by greenpau** [comment]
@luisquintanilla , thank you for the explanation! 👍 I helps!
