### ISSUE TITLE
R-squared calculated incorrectly for some FastTreeRegression trials

### ISSUE THREAD

**Issue by andrasfuchs** [dotnet/machinelearning#6437]
**System Information (please complete the following information):**
 - OS & Version: Windows 11 [Version 10.0.22621.675]
 - ML.NET Version: ML.NT v2.0.0-preview.22551.1
 - .NET Version: .NET 6.0.401

**Describe the bug**
I use Fast Tree and Fast Forest algorithms for regression training. My metric is set to R-squared. As far as I understand the value range of R-squared is between 0% and 100% by definition. ([see here](https://statisticsbyjim.com/regression/interpret-r-squared-regression/))
Sometimes I get strange values outside of this range, typically negative numbers. I might be wrong, but I think this should not happen.

**To Reproduce**
1. Create an regression experiment and set its metric to R-squared
2. Run a few trials until you get a metric score outside of the [0.00..1.00] range

**Expected behavior**
I would expect all metric values to be in the [0.00..1.00] range. Having values outside of this range indicates that something is calculated incorrectly, and it potentially mean that I lose a good trial just because of this miscalculation.

**Screenshots, Code, Sample Projects**
```
var pipeline =
  mlContext.Auto().Featurizer(trainTestData.TrainSet, numericColumns: new[] { "Features" })
      .Append(mlContext.Auto().Regression(useFastTree: true, useLbfgs: false, useSdca: false, useFastForest: true, useLgbm: false));

var experiment = mlContext.Auto().CreateExperiment();

experiment
    .SetPipeline(pipeline)
    .SetTrainingTimeInSeconds(trainingTimeInSeconds)
    .SetRegressionMetric(RegressionMetric.RSquared, labelColumn: "Label")
    .SetDataset(trainTestData.TrainSet, trainTestData.TestSet)
    .SetMonitor(monitor)
    .SetMaximumMemoryUsageInMegaByte(20 * 1024);
```

![image](https://user-images.githubusercontent.com/910321/200171214-2093a1e9-a829-42a0-aece-ecc467d8fa81.png)

**Additional context**
I can provide the source code and data on request, as usual.

**Comment by LittleLittleCloud** [comment]
R-Square can be negative. And here's [why](https://stats.stackexchange.com/questions/12900/when-is-r-squared-negative)

**Comment by andrasfuchs** [comment]
Thank you for the link, I didn't know that! 👍
