### ISSUE TITLE
Sample with face recognition and training?

### ISSUE THREAD

**Issue by johandanforth** [dotnet/machinelearning#6454]
I'm missing a sample for face recognition, with both training and consumption, implemented with ML.Net. It seems that @MatiKingloom had something going there, a couple of years ago.

**Comment by michaelgsharp** [comment]
@luisquintanilla do you know if we have a sample laying around somewhere?

**Comment by luisquintanilla** [comment]
Hi @johandanforth,

Thanks for your question.

We have some general [object detection tutorials](https://learn.microsoft.com/dotnet/machine-learning/tutorials/object-detection-model-builder) that can help get you started. 

As you develop your solutions, we encourage you to review some of the [Microsoft Responsible AI transparency notes on facial recognition](https://learn.microsoft.com/legal/cognitive-services/face/transparency-note#considerations-when-using-azure-face-service). While not specific to ML.NET, several of those considerations are still good to keep in mind.

**Comment by johandanforth** [comment]
Thanks @luisquintanilla but that doesn't really help much. Object detection isn't nearly as good as face recognition and identification, and I'm well aware of implications of use. This is for internal use, I'm building albums from old pictures taken from company events and travels, years and years back, where current and former employees can help identifying who's who on the pictures and I thought ML could help out. Nothing scary ☺️

**Comment by luisquintanilla** [comment]
@johandanforth hmm...in that case I don't believe there are any samples. At least none that I'm aware of. 

I found this [post](https://damselfly.info/face-recognition-in-net-the-good-the-bad-and-the-ugly/) which I suspect relates in part to #5062
