### ISSUE TITLE
Is there a deep neural network for tabular data (like TabNet)?

### ISSUE THREAD

**Issue by samliu319** [dotnet/machinelearning#6455]
I've just started machine learning, but I reject learning with python. I am interested in deep learning of tabular data, but I can't find .Net related resources. I hope I can get some guidance here, thanks!

**Comment by michaelgsharp** [comment]
I don't think we have anything like this currently.

@luisquintanilla is this something you are aware of or have looked into?

**Comment by luisquintanilla** [comment]
Hi @samliu319,

Thanks for your question.

I don't think I've seen requests like this before. In general, classical ML algorithms have worked well enough for training models on tabular data. These algorithms are often cheaper to train (time & compute resources) and sometimes more explainable than neural networks. Deep Learning has achieved promising results for unstructured data (text & images). While I wouldn't want to discourage you from exploring solutions, I would recommend first starting out with classical machine learning algorithms. 

If deep learning on tabular data is an option you want to pursue, there are a few things you might consider. However, almost none of them involve ML.NET. 

1. Import TorchScript model using TorchSharp. Convert a PyTorch implementation of TorchSharp. Here is a guide that shows you how to [use TorchScript with TorchSharp](https://github.com/dotnet/TorchSharp/wiki/TorchScript).
1. Develop TabNet model from scratch using TorchSharp. There is a [PyTorch implementation](https://github.com/dreamquark-ai/tabnet/tree/develop/pytorch_tabnet) of it available. 
1. Use an off-the-shelf ONNX version of TabNet for inferencing with ML.NET. There appears to have been attempts in the past to [create an ONNX version of the model](https://github.com/dreamquark-ai/tabnet/issues/277). Not sure what the status is though. 

There are currently no plans to add deep learning APIs for tabular data (like TabNet) to ML.NET. As we hear more feedback on the topic, we're open to considering it in the future.

Closing this issue.
