### ISSUE TITLE
Sentence Similarity for other languages

### ISSUE THREAD

**Issue by ADD-eNavarro** [dotnet/machinelearning#6456]
**Is your feature request related to a problem? Please describe.**
Sentence Similarity uses a pretrained NAS-BERT, which in my understanding has been trained in english, restricting the usage of this feature to this language.

**Describe the solution you'd like**
I'd love to be able to choose a different language when using Sentence Similarity.

**Comment by luisquintanilla** [comment]
Thanks for the feedback @ADD-eNavarro . We'll take this request into consideration as we iterate and introduce new scenarios.

**Comment by michaelgsharp** [comment]
Closing for now as we are tracking the deep learning tasks elsewhere.
