### ISSUE TITLE
Target .NET Framework 4.8 app unable to load one or more of the requested types 

### ISSUE THREAD

**Issue by whitmark** [dotnet/machinelearning#6460]
Under ML.Net 2.0.0-preview.22313.1, I was able to create a custom class library that targets the .NET Framework 4.8 to identify which dlls I need to use in a 3rd-party app that loaded just fine.  When I update to ML.Net 2.0.0 under .Net 7, I am getting several errors of the following kind where xxxxxx is the 3rd-party app.

Unable to retrieve type info for 'xxxxxx.AddOnBase' from assembly 'Microsoft.ML.Core': Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Failed load vendor assembly 'xxxxx\Microsoft.ML.Core.dll': The given key was not present in the dictionary.

Unable to retrieve type info for 'xxxxxx.AddOnBase' from assembly 'Microsoft.ML.Data': Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Failed load vendor assembly 'xxxxxx\Microsoft.ML.Data.dll': The given key was not present in the dictionary.

Unable to retrieve type info for 'xxxxxx.AddOnBase' from assembly 'Microsoft.ML.DataView': Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Failed load vendor assembly 'xxxxx\Microsoft.ML.DataView.dll': The given key was not present in the dictionary.

Unable to retrieve type info for 'xxxxxx.AddOnBase' from assembly 'Microsoft.ML.FastTree': Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Failed load vendor assembly 'xxxxxx\Microsoft.ML.FastTree.dll': The given key was not present in the dictionary.

Unable to retrieve type info for 'xxxxxx.AddOnBase' from assembly 'Microsoft.ML.StandardTrainers': Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Failed load vendor assembly 'xxxxxx\Microsoft.ML.StandardTrainers.dll': The given key was not present in the dictionary.

Unable to retrieve type info for 'xxxxxx.AddOnBase' from assembly 'Microsoft.ML.Transforms': Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Failed load vendor assembly 'xxxxx\Microsoft.ML.Transforms.dll': The given key was not present in the dictionary.

Although ML.Net 2.0.0 went GA with .Net 7, I don't believe my simple inference custom class library project is using anything beyond netstandard2.0 per the frameworks listed in NuGet .  The target app is a popular closed-code trading platform that links in dlls.  The tactic of creating a custom class that targets .Net 4.8 has worked well in the past to identify and output the necessary dlls to copy over and reference for this trading application.   It would seem since the ML.Net preview, these type are located elsewhere to be determined.

**Comment by whitmark** [comment]
\Documents\Visual Studio 2022\wdcMLTConsumeMLDNModelFrame48.zip\wdcMLTConsumeMLDNModelFrame48\bin\x64\Release

![image](https://user-images.githubusercontent.com/8396992/203175223-fa8de78a-4468-44fb-bb32-9b47ba3652e5.png)

**Comment by JakeRadMSFT** [comment]
@ericstj @michaelgsharp  - what are all the differences between old style nuget references (package.json) and the new package ref style?

I believe this issue is hitting an instance of this bug:
https://github.com/dotnet/machinelearning-modelbuilder/blob/main/troubleshooting/ModelBuilderTroubleshooting.md#runtime-error-in-code-systemiofilenotfoundexception-could-not-load-file-or-assembly-microsoftmldata

**Comment by JakeRadMSFT** [comment]
@whitmark when you're building are you targeting x64?

**Comment by whitmark** [comment]
![image](https://user-images.githubusercontent.com/8396992/203225199-324d8700-9d53-4a97-8981-d00fb7325bcb.png)

![image](https://user-images.githubusercontent.com/8396992/203225216-12df92ff-13f1-4bd2-a0a4-36ee906deef9.png)

**Comment by tarekgh** [comment]
Maybe @ViktorHofer or @ericstj can answer https://github.com/dotnet/machinelearning/issues/6460#issuecomment-1329643871 or point who can answer it.

**Comment by ericstj** [comment]
@JakeRadMSFT these are not FileNotFoundExceptions so I am not sure you're link applies.   I'm not sure what "The given key was not present in the dictionary." means here, but this almost looks to me like the host has implemented some custom assembly resolve hook and is hitting a KeyNotFoundException when evaluating that hook.

@whitmark it'd be great if you could provide more detail (exception stack traces, debug spew, or best: an isolated repro).  Could you share with us what framework your host application is running under?  It wasn't clear from your description if the host is running .NETFramework 4.8, .NET 7.0, or something different.

**Comment by whitmark** [comment]
@ericstj Thanks for responding.  I am going to take another run this week using the platform support's suggestion of referencing the host core.dll assembly in the build and report back.

**Comment by whitmark** [comment]
I saw a post on the trading platform's forum that suggested the hack of adding the Model Builder to the custom class .Net Framework 4.8 project (to match the platform) before building it to output the proper assembly versions and compatible class library.  This has appeared to solve my issues on my two inferencing projects.
