### ISSUE TITLE
Tag/Release for ML.NET 2.0.0

### ISSUE THREAD

**Issue by schmik** [dotnet/machinelearning#6461]
**Is your feature request related to a problem? Please describe.**
There is neither a [release](https://github.com/dotnet/machinelearning/releases) nor a [tag](https://github.com/dotnet/machinelearning/tags) for Version 2.0.0 (latest: 1.7.1)

**Describe the solution you'd like**
Unless this is deliberate: Continue flagging/tagging releases.

**Comment by michaelgsharp** [comment]
Good catch. It was not deliberate. The latest 2.0.1 servicing has been tagged correctly.
