### ISSUE TITLE
Is ARIMA time series modeling/forecasting on the ML.NET roadmap?

### ISSUE THREAD

**Issue by caseyeasterday** [dotnet/machinelearning#6462]
I feel very limited that SSA is the only method available for time series modeling. Of course, other parametric and non-parametric models are capable of forecasting, but a parametric approach like ARIMA that can incorporate MA, AR, seasonality is powerful, fast, and scalable.

I would like ML.NET to add ARIMA to be added to Model Builder. Ideally this would include support for ACF/PACF/EACF analysis, differencing, and auto-ARIMA.

The existing SSA algorithm and other parametric (e.g., linear regression, etc.) and non-parametric (e.g., trees, ensembles, etc.) models for forecasting.

**Comment by michaelgsharp** [comment]
Hi @caseyeasterday, ARIMA is on the ML.NET roadmap, actually for pretty soon. We already have an implementation of it done, we mostly just need to fine tune it for ML.NET itself. So it should be in the next couple of months depending on where finishing that tuning falls with the holidays.

Closing for now as we are tracking this elsewhere.
