### ISSUE TITLE
Is it really neccessary to annotate ImageSource with [Microsoft.ML.Transforms.Image.ImageType(x, x)] ?

### ISSUE THREAD

**Issue by kimhegg** [dotnet/machinelearning#6464]
**Is your feature request related to a problem? Please describe.**
It's very frustrating that we need to annotate the ModelInput imagesource with [Microsoft.ML.Transforms.Image.ImageType(800, 600)]. It should be possible to set these values in runtime.
I thought that Ml 2.0 would fix this, but unfortunately it doesn't seem so.

**Describe the solution you'd like**
Is it not possible to just remove the neccessity of the annotation and just get height and width from the image, or any other way?

**Comment by michaelgsharp** [comment]
@luisquintanilla this is something I have heard before. Just another one of those "verbose" things that seems unnecessary. Have you thought about this issue at all?

**Comment by bartonjs** [comment]
In a project where I had preloaded `Bitmap` objects I avoided the need for the attribute on those properties by

```C#
DataViewTypeManager.Register(new ImageDataViewType(), typeof(Bitmap));
```

Since my input objects didn't have a fixed dimensionality, applying the attribute didn't feel like the right answer.

**Comment by kimhegg** [comment]
@bartonjs solution worked like a charm. For MLImage aswell. 
DataViewTypeManager.Register(new ImageDataViewType(), typeof(MLImage));

**Comment by michaelgsharp** [comment]
Glad this worked. Closing since its resolved for now, but we will keep thinking about the ability to remove those tags.
