### ISSUE TITLE
ML.Net Support for YOLO v6

### ISSUE THREAD

**Issue by crazyoutlook** [dotnet/machinelearning#6478]
**Is your feature request related to a problem? Please describe.**
ML.Net support for Yolo v6 model

**Describe the solution you'd like**
ML.Net support for Yolo v6 model

**Describe alternatives you've considered**
I tried using ML.Net with Yolo v4

**Additional context**

**Comment by luisquintanilla** [comment]
Hi @crazyoutlook 

Thanks for your suggestion. We're looking into introducing object detection support into ML.NET in the coming months. However, there are no plans for it to be YOLO-based. 

If all you want is inferencing, you should be able to take an ONNX version of the model and use it to make predictions using ML.NET. While not specific to YOLO v6, here is a [sample using v2](https://learn.microsoft.com/dotnet/machine-learning/tutorials/object-detection-onnx)
