### ISSUE TITLE
Deep Learning Tracking Issue

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#6484]
## Work Items

- [x] #6485
- [ ] #6486
- [ ] #6487
- [x] #6488
- [x] #6489
- [ ] #6490

**Comment by GeorgeS2019** [comment]
@luisquintanilla 

We need ML.NET to support a **deep reinforcement learning** framework, preferably based on [**TorchSharp**](https://github.com/dotnet/TorchSharp/issues/981) for the entire .NET community, especially usable in game engine like e.g. Godot etc.

We need **FOR ONCE** a .NET only (without Python) ML.NET-based ML RL Agent usable in e.g. Godot (we now have many coming from Unity) and Unity. 

The Godot communities now have ONNX driven RL agent based on industry phython deep RL framework. This means thare are many Godot use cases.

Others are working on Unity ML Agent like concepts BUT in Godot. We are working to replace the python part to completely TorchSharp. 

A PPO TorchSharp using Open AI Gym .NET framework is also shared in the link above. 

We need a ML.NET Deep RL framework compatible with what the python communities are doing.

**Comment by asieradzk** [comment]
Sounds great. How can we get some financial support for this issue? I'm working on Godot plugin similar to unity's ML agents but I'll probably release it as a paid plugin. My electricity goes up by 20% and insurance 10% next year.

**Comment by GeorgeS2019** [comment]
@luisquintanilla 
The 2021 Survey clearly showed that the community clearly requested deep learning support. 
It would be great if the community see the significant progress in this aspect by more generously using labels such as deep-learning or torchsharp

Using TorchSharp label will remind clear commitment to this perhaps the most disruptive deep learning .NET attempt!

![image](https://github.com/dotnet/machinelearning/assets/49812372/f54579f1-ec9d-425b-9eec-90de67d22d62)

**Comment by luisquintanilla** [comment]
Closing this issue and tracking TF / Image API / BYO model separately.
