### ISSUE TITLE
Text- classification | Sentence Similarity cancellation does not work 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning#6525]
**System Information (please complete the following information):**
 - OS & Version: [e.g. Windows 10] 
 - ML.NET Version: [e.g. ML.NET v1.5.5]
 - .NET Version: [e.g. .NET 5.0]

**Describe the bug**
It seems that Text-classification cancellation does not cooperate with mlContext cancellation.
**To Reproduce**

**Expected behavior**

**Screenshots, Code, Sample Projects**
If applicable, add screenshots, code snippets, or sample projects to help explain your problem.

**Additional context**

**Comment by michaelgsharp** [comment]
Fixed by previous PR so closing.
