### ISSUE TITLE
Default value of sigmoid parameter for LightGBM

### ISSUE THREAD

**Issue by mjmckp** [dotnet/machinelearning#654]
[The default value of the `sigmoid` parameter for LightGBM is 1](https://github.com/Microsoft/LightGBM/blob/master/docs/Parameters.rst#sigmoid), however in the ML.Net wrapper it is hardwired to 0.5:
https://github.com/dotnet/machinelearning/blob/f9d3973a056ad26bc6cc15c2d7a09f8ae47e30da/src/Microsoft.ML.LightGBM/LightGbmArguments.cs#L404

Why is this the case? Shouldn't this parameter either be 1 or exposed on the ML.Net API instead?

**Comment by codemzs** [comment]
@guolinke were the default values updated recently? I can update this to 1 on ML.NET but just wanted to check.

**Comment by guolinke** [comment]
It is 1 in Lightgbm side.

**Comment by codemzs** [comment]
@guolinke Please take a look at the PR https://github.com/dotnet/machinelearning/pull/667
