### ISSUE TITLE
Limiting CPU usage for ML.NET using SSA for timeseries forecasting

### ISSUE THREAD

**Issue by zyw400** [dotnet/machinelearning#6548]
We are using the SSA Forecaster for our ML training pipeline in C#. However, we observe high CPU spikes in the front-end machine that executes this program periodically. We are looking for ways to limit CPU usage but are unable to find good solutions. Please kindly suggest any methods that we can reduce the CPU usage ideally by limiting the max number of vcores to use.

        /// <inheritdoc/>
        public override void Train(IEnumerable<DataPoint> trainData)
        {
            int trainSize = trainData.Count();
            var forecastingPipeline = this.BuildSSAForecaster(trainSize);
            this.forecaster = forecastingPipeline.Fit(this.GetDataViewForEnumerable(trainData));
        }

**Comment by michaelgsharp** [comment]
Since you want a global limit the easiest way (on windows and linux) is to set the processor afinity in your code. 
``` Process.GetCurrentProcess().ProcessAffinity = (IntPtr)(0x0000_0000);```
Where the actual mask is what cores you want to run on. https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.processoraffinity?view=net-7.0.
