### ISSUE TITLE
Survey: Repo contribution experience 2023

### ISSUE THREAD

**Issue by michaelgsharp** [dotnet/machinelearning#6568]
A couple years ago we surveyed you the members of the community in this repo to learn how we were doing as maintainers.

One of the things we learned is that we needed to be more responsive to issues and PR’s. Since we added community triagers, updated our area ownership and added automated workflows. To offer more visibility into product planning we developed an app to view our epics and stories. To make the experience of offering a PR easier, we have added documentation, worked to increase build performance and squashed flaky tests.

It's time to repeat the same survey. Whether you've been involved for years or you're relatively new please tell us about your experience participating and contributing to the project. It should only take a few minutes, and you can answer for up to 3 repos.

https://www.surveymonkey.com/r/8KTX9VT?Source=RepoLink

**Comment by JulieLeeMSFT** [comment]
@michaelgsharp, the survey has been closed. Please close this issue and unpin it. Thanks a lot!
