### ISSUE TITLE
Adding MP3 processing support porting pyAudioAnalysis library

### ISSUE THREAD

**Issue by kdcllc** [dotnet/machinelearning#657]
This is a feature request. Currently, I have to use Python libraryhttps://github.com/tyiannak/pyAudioAnalysis in order to process MP3 files and retrieve feature set. I would like to see this library ported to ML.NET functionality.

**Comment by Zruty0** [comment]
Hi @kdcllc . 
Support for audio processing is something that we definitely plan to add. Right now the vision is that it needs to wait until we have a good support for deep neural networks, and we will try to enable image processing first.

Once we have the above, we will probably be looking at various options for audio featurization. As far as I can tell, computing chromatogram or MFCC over an audio stream is quite a standard functionality, available in many libraries. I don't think we will port pyAudioAnalysis specifically.

**Comment by Zruty0** [comment]
@kdcllc , I'm going to close this issue, since we will probably not port this specific library. Feel free to reopen if you want to continue the discussion
