### ISSUE TITLE
Model keep learning....

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/machinelearning#6574]
**Is your feature request related to a problem? Please describe.**

I meet a problem. How does the MulticlassClassification-Model train new data continuously?
Take the old model as the starting point and train the new model.

I tried :
```c#
var newModel = pipeline.Fit(newData);
_ model = _ model.Append(newModel);
```
This doesn't work.

**Describe the solution you'd like**

```c#
_model = _model.Train(newData);
```

**Describe alternatives you've considered**

**Additional context**

**Comment by NMSAzulX** [comment]
If there is too much data, how to learn in batches?
I don't see the code of continuous learning in the example.

**Comment by LittleLittleCloud** [comment]
To continue training on new data, you need to call `Fit` on pipeline instead of models. That's basically the same with training a new model.

```
IDataView oldData, newData
var pipeline
var oldModel = pipeline.Fit(oldData)

// there's no way to re-train oldModel with newData
// to get a new model trained with newData
// you need to call Fit on pipeline instead

var newModel = pipeline.Fit(newData);
```

To learn several batches, I would suggest merging those batches as one `IDataView`.

**Comment by NMSAzulX** [comment]
@LittleLittleCloud Thank you!
