### ISSUE TITLE
There is a problem when using LbfgsMaximumEntropy to learn image classification. A continuous learning result that is not expected.

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/machinelearning#6582]
**System Information (please complete the following information):**
 - OS & Version: [Windows 11] 
 - ML.NET Version: [v2.0.1]
 - .NET Version: [.NET 6.0]
 - Other:  
       - [Microsoft.ML.ImageAnalytics 2.0.1]
       - [SciSharp.TensorFlow.Redist 2.3.1]

**Describe the bug**

I used LbfgsMaximumEntropy and kept it learning cat/dog pictures, but produced unexpected results.
All the results are cats.

**To Reproduce**

1. Learning 100 cat pictures amd 1 dog picture.
2. Learning 100 dog pictures.
3. Predict Result.

[Code ImageMulticlassTrainer](https://github.com/NMSAzulX/LbfgsMaximumEntropyTest/blob/main/ImageTest/ImageTest/ImageMulticlassTrainer.cs)

Reuslt:  all label is cat and score is 1.

**Screenshots, Code, Sample Projects**
If you need the complete code, I will fix the code.

**Comment by luisquintanilla** [comment]
Hi @NMSAzulX,

Thanks for this issue. Did @LittleLittleCloud suggestion resolve your issues?

**Comment by NMSAzulX** [comment]
@luisquintanilla Thank you for replay. I think I get it.
