### ISSUE TITLE
System.BadImageFormatException related to Microsoft.ML.CpuMath

### ISSUE THREAD

**Issue by ChickenOnBoard** [dotnet/machinelearning#6586]
**System Information:**
 - OS & Version: Windows 11 
 - ML.NET Version: ML.NET v2.0.1
 - .NET Version: .NET 4.7.2

**Describe the bug**
Getting System.BadImageFormatException when running my app. Screenshot below:

**Screenshots, Code, Sample Projects**
![image](https://user-images.githubusercontent.com/30071522/222420199-f5d0bd93-8878-48fd-8a20-bc99a5c38fb6.png)
![image](https://user-images.githubusercontent.com/30071522/222420678-5e5f81a8-37a2-439e-a1b8-94ed4a663c47.png)
![image](https://user-images.githubusercontent.com/30071522/222420710-b346d615-fc3b-4383-9c82-737856c8c849.png)

**Comment by michaelgsharp** [comment]
This only happens if you are doing 32 bit and reference a 64 bit binary. Please make sure you are using the right versions.
