### ISSUE TITLE
Cannot create entry point for a new learner in a package with depends on Microsoft.ML.

### ISSUE THREAD

**Issue by xadupre** [dotnet/machinelearning#659]
The Following instruction ``_jsonNodes.Add(Serialize("Data.DataViewReference", input, output));`` is automatocally generated for every entrypoint but _jsonNodes is private member. I did not find a way to add a custom learner in a package which takes Microsoft.ML as a dependency.

**Comment by codemzs** [comment]
#660 seems to have fixed this.
