### ISSUE TITLE
Load ONNX from in-memory binary instead of file path

### ISSUE THREAD

**Issue by RamType0** [dotnet/machinelearning#6591]
**Is your feature request related to a problem? Please describe.**

Currently, the only way to load ONNX model is to specify concrete file path.
But the usage of concrete file path is often impossible in some platforms.(e.g. UWP without permission)
Loading ONNX model from in-memory binary representation will solve this problem.

**Describe the solution you'd like**

Provide API to load ONNX model from `ReadOnlyMemory<byte>`, `Stream`.

**Additional context**

[`OnnxTransformer` has private constructor which accepts `byte[] modelBytes`.](https://github.com/dotnet/machinelearning/blob/db197154dcd924ae9a7e31074a835b86e34e33bb/src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs#L232)

**Comment by michaelgsharp** [comment]
@luisquintanilla I'm going to say we shoudl take this for the next major release. SHouldn't be hard to do. We already have a private constructor that essentially does this and I've already looked into it a bit. If you think we should plan on next year though please bump the milestone out.

**Comment by luisquintanilla** [comment]
This makes sense to me.

**Comment by maltempi** [comment]
This would be useful for a project I am working on.
