### ISSUE TITLE
AutoML experiment cannot be executed on Double type columns

### ISSUE THREAD

**Issue by superichmann** [dotnet/machinelearning#6595]
**System Information (please complete the following information):**
 - OS & Version: Windows 10
 - ML.NET Version: ML.NET v2.0.1
 - AutomL Version: ML.NET v0.20.1
 - .NET Version: .NET 6.0

**Describe the bug**
When loading data from db column types of double / double precision and using them to create a regression experiment the following error occurs:

```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Schema mismatch for feature column '__Features__': expected Vector<Single>, got Vector<Double> (Parameter 'inputSchema'))
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task'1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task'1.get_Result()
   at Microsoft.ML.AutoML.AutoMLExperiment.Run()
   at Microsoft.ML.AutoML.RegressionExperiment.Execute(IDataView trainData, IDataView validationData, ColumnInformation columnInformation, IEstimator'1 preFeaturizer, IProgress'1 progressHandler)
```

**To Reproduce**
1. Create a DB table with 3 double type columns
2. Load with `mlContext.Data.CreateDatabaseLoader`
3. call `mlContext.Auto().CreateRegressionExperiment().Execute` with the data

**Expected behavior**
The experiment should run

**Comment by LittleLittleCloud** [comment]
@superichmann most of trainers in ml.net accepts `vector<single>` and that's why AutoML converts features to `single` rather than `double`. To make it work on AutoML, you can apply a convert transformer as pre-featurizer which transforms double columns to single data type

**Comment by superichmann** [comment]
Thanks @LittleLittleCloud for the precise answer as usual :]

**Comment by superichmann** [comment]
I have tried this method according to [this ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.ml.conversionsextensionscatalog.converttype?view=ml-dotnet) and sending as a preFeaturizer.

Got the following error:
`System.AggregateException: One or more errors occurred. (Schema mismatch for feature column '__Features__': expected Vector<Single>, got Vector<Double> (Parameter 'inputSchema')) ---> System.ArgumentOutOfRangeException: Schema mismatch for feature column '__Features__': expected Vector<Single>, got Vector<Double> (Parameter 'inputSchema')`

creating the prefeaturizer:
```
        public static IEstimator<ITransformer> GetDoubleConverter(IDataView data)
        {
            var mlContext = new MLContext();

            var doubleColumns = data.Schema
                .Where(col => col.Type == NumberDataViewType.Double)
                .Select(col => new InputOutputColumnPair($"f_{col.Name}", col.Name));

            var pipeline = mlContext.Transforms.Conversion.ConvertType(doubleColumns.ToArray(), DataKind.Single);

            return pipeline;
        }
```

and sending it:
```
            var preFeaturizerrrrrrrrrrrrrr = GetDoubleConverter(t_train);
            ExperimentResult<RegressionMetrics> experimentResult = experiment.Execute(t_train, t_train_val,labelColumnName:targetColumn,preFeaturizer: preFeaturizerrrrrrrrrrrrrr);
```

What have I done wronggggggggggggg???? ;]

**Comment by justinormont** [comment]
@LittleLittleCloud: If I recall, the AutoML auto-added a convert transform from double to single. Is that no longer true? Great for usability.

**Comment by superichmann** [comment]
![image](https://user-images.githubusercontent.com/79865853/233829162-6d6b9167-f4d7-4337-a445-fd997164867e.png)
plzzz help I am failing my tests :[

**Comment by LittleLittleCloud** [comment]
> I have tried this method according to [this ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.ml.conversionsextensionscatalog.converttype?view=ml-dotnet) and sending as a preFeaturizer.
> 
> Got the following error: `System.AggregateException: One or more errors occurred. (Schema mismatch for feature column '__Features__': expected Vector<Single>, got Vector<Double> (Parameter 'inputSchema')) ---> System.ArgumentOutOfRangeException: Schema mismatch for feature column '__Features__': expected Vector<Single>, got Vector<Double> (Parameter 'inputSchema')`
> 
> creating the prefeaturizer:
> 
> ```
>         public static IEstimator<ITransformer> GetDoubleConverter(IDataView data)
>         {
>             var mlContext = new MLContext();
> 
>             var doubleColumns = data.Schema
>                 .Where(col => col.Type == NumberDataViewType.Double)
>                 .Select(col => new InputOutputColumnPair($"f_{col.Name}", col.Name));
> 
>             var pipeline = mlContext.Transforms.Conversion.ConvertType(doubleColumns.ToArray(), DataKind.Single);
> 
>             return pipeline;
>         }
> ```
> 
> and sending it:
> 
> ```
>             var preFeaturizerrrrrrrrrrrrrr = GetDoubleConverter(t_train);
>             ExperimentResult<RegressionMetrics> experimentResult = experiment.Execute(t_train, t_train_val,labelColumnName:targetColumn,preFeaturizer: preFeaturizerrrrrrrrrrrrrr);
> ```
> 
> What have I done wronggggggggggggg???? ;]

AutoML only collects columns from input dataset. In your case, your `GetDoubleConverter` saves the converted output column to `f_{inputcolumn}`, which is a column that doesn't exist in `t_train`. So AutoML won't collect that column as feature.

To fix that, you can simply override the original double column with converted float column in your `GetDoubleConverter`.

**Comment by superichmann** [comment]
ok I changed the code to `.Select(col => new InputOutputColumnPair(col.Name, col.Name));` and it seems to work.

Upon consumption, do I need to do anything with the data (another transformer) before consuming the model?
I am saving the `experimentResult.BestRun.Model` to the db and fetching it upon sonsumption. Do I need to save anything else to the db and use on consumption? such as `experimentResult.BestRun.Estimator`?

how should I handle pipelines that are executed before the experiment? just re-transform them before consumption?

**Comment by LittleLittleCloud** [comment]
> ok I changed the code to `.Select(col => new InputOutputColumnPair(col.Name, col.Name));` and it seems to work.
> 
> Upon consumption, do I need to do anything with the data (another transformer) before consuming the model? I am saving the `experimentResult.BestRun.Model` to the db and fetching it upon sonsumption. Do I need to save anything else to the db and use on consumption? such as `experimentResult.BestRun.Estimator`?
> 
> how should I handle pipelines that are executed before the experiment? just re-transform them before consumption?

The pre-featurizer will be saved as part of model so no you don't need to run extra transform

**Comment by superichmann** [comment]
Thanks again!

One more thing ;] I am trying to `mlContext.Regression.PermutationFeatureImportance` which does not have a `preFeaturizer` parameter. same error:
`System.ArgumentOutOfRangeException: Schema mismatch for feature column 'Features': expected Vector<Single>, got Vector<Double> (Parameter 'inputSchema')`
what should I do when sending IDataView to this function?

my code:
```
var mlContext = new MLContext();
IEstimator<ITransformer> dataPrepEstimator =mlContext.Transforms.Concatenate("Features", arrstrCols).Append(mlContext.Transforms.NormalizeMinMax("Features"));
ITransformer dataPrepTransformer = dataPrepEstimator.Fit(data);
IDataView preprocessedTrainData = dataPrepTransformer.Transform(data);
var ffEstimator = mlContext.Regression.Trainers.FastForest(labelColumnName: strColumn);
var ffaModel = ffEstimator.Fit(preprocessedTrainData);
ImmutableArray<RegressionMetricsStatistics> ffpermutationFeatureImportance = mlContext.Regression.PermutationFeatureImportance(sdcaModel, preprocessedTrainData, permutationCount: 3, labelColumnName: strColumn);
```

**Comment by LittleLittleCloud** [comment]
@superichmann I didn't see `dataPrepEstimator ` includes convert transformer, did you miss adding that

**Comment by superichmann** [comment]
I have updated it as follows:
```
var mlContext = new MLContext();
IEstimator<ITransformer> dataPrepEstimator =mlContext.Transforms.Concatenate("Features", arrstrCols).Append(mlContext.Transforms.NormalizeMinMax("Features"));
ITransformer dataPrepTransformer = dataPrepEstimator.Fit(data);
IDataView preprocessedTrainData = dataPrepTransformer.Transform(data);
var transSinglesToDoubles = AutoMLHelper.TransformDoubleToSingle(preprocessedTrainData);
preprocessedTrainData = transSinglesToDoubles.Fit(preprocessedTrainData).Transform(preprocessedTrainData);
var ffEstimator = mlContext.Regression.Trainers.FastForest(labelColumnName: strColumn);
var ffaModel = ffEstimator.Fit(preprocessedTrainData);
ImmutableArray<RegressionMetricsStatistics> ffpermutationFeatureImportance = mlContext.Regression.PermutationFeatureImportance(sdcaModel, preprocessedTrainData, permutationCount: 3, labelColumnName: strColumn);
```

Got back error `System.ArgumentOutOfRangeException: Schema mismatch for feature column 'Features': expected Vector<Single>, got Vector<Double> (Parameter 'inputSchema')` on line `var ffaModel = ffEstimator.Fit(preprocessedTrainData);`

StackTrace:
```
 TrainerEstimatorBase`2.CheckInputSchema(SchemaShape inputSchema)
TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
TrainerEstimatorBase`2.Fit(IDataView input)
```

My guess is that unlike the automl experiment which is using only the Single columns after the preFeaturizer took place, in the specific model this isn't happening. I might as well not calling it in the correct way.. waiting for your instructions ;]
