### ISSUE TITLE
I don’t understand the analysis on you web page for SSA Time Series

### ISSUE THREAD

**Issue by CBrauer** [dotnet/machinelearning#6598]
I’m trying to get good result from the “SsaForecastingEstimator”, and I am failing to do so. In trying to understand this algorithm better, I went to your documentation at: [TimeSeriesCatalog.ForecastBySsa Method (Microsoft.ML) | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/microsoft.ml.timeseriescatalog.forecastbyssa?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.ML.TimeSeriesCatalog.ForecastBySsa)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=ml-dotnet).

Please answer the following questions:
1.	In the sample code, the input data for a straight line is duplicated three times. Why?
2.	The model is defined under the comment: “// Instantiate the forecasting model”.  There is an argument with the value of 11.  Where in the hell did this number come from?
3.	It seems to me that if you extrapolate (i.e., forecast) the straight line five times, you should get {5, 6, 7, 8, 9}.  You got: [1.977226, 1.020494, 1.760543, 3.437509, 4.266461].  Are you proud of these numbers?

I suggest that you guys come up with better documentation on the “SsaForecastingEstimator”,
Charles

**Comment by CBrauer** [comment]
Thank you very much for taking time to respond to my surly post.  So how do you feel about using "forecastBySSA" if there is no seasonality at all?  Is it the wrong tool?

Thank you very much for the "example" link.  Very nice.  It's a shame that such a valuable resource is buried so deep that a GitHub search cannot find it.

**Comment by LittleLittleCloud** [comment]
Won't be too long will those example being buried as we are improving documents. As for predicting time-series with no seasonality, it'll be a challenge for SSA. However, if your dataset has trend pattern, maybe you can give auto-regression a try.

**Comment by CBrauer** [comment]
ok. Will do and thanks.
