### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by jamesqo** [dotnet/machinelearning#66]
I haven't worked with C# in a while because I've been working on some machine learning projects in Python with Scikit-Learn. It's so awesome to see .NET is getting its own built-in, high performance machine learning package! 🎉 

I have a question about the goals of this project-- how exactly does it relate to existing high-quality frameworks like [Accord.NET](https://github.com/accord-net/framework) or [all of the projects listed here](https://github.com/quozd/awesome-dotnet#machine-learning-and-data-science)? Thanks.

**Comment by GalOshri** [comment]
One of our goals is to provide a unified framework that can integrate other libraries such as Accord.NET and provide consistent APIs for ML. Take a look at [this blog post](https://blogs.msdn.microsoft.com/dotnet/2018/05/07/introducing-ml-net-cross-platform-proven-and-open-source-machine-learning-framework/) which goes into a few more details. 

Let us know if you have a chance to try it out!

**Comment by zeahmed** [comment]
Thanks for the input. This is an open area for contribution.

**Comment by danmosemsft** [comment]
Hello @jamesqo - we meet again. Have you had a chance to try ML.NET? As @GalOshri points out, we'd welcome contributions if you feel interested.

Perhaps we can close this issue?

**Comment by GalOshri** [comment]
I'll close the issue for now, but let us know if there are other questions regarding how this relates to Accord.NET!
