### ISSUE TITLE
How to use Microsoft.ML.ImageAnalytics 2.0.1 to write ModelInput classes

### ISSUE THREAD

**Issue by BigHeadDev** [dotnet/machinelearning#6601]
### System information

- **OS version/distro**: Windows 11
- **.NET Version (eg., dotnet --info)**:  .NET 6

### Issue

- **What did you do?**
I refer to Microsoft documentation and YouTube bloggers to write a program for accessing the onnx model with ML.NET
It is a red wine/Baijiu recognition model
,The following code snippet shows the key errors：
``` C#
public class WineInput {// C# Input Mapping
        [ImageType(ImageSettings.imageWidth, ImageSettings.imageHeight)]
        public Bitmap Image { get; set; }
    }
    public struct ImageSettings {
        public const int imageHeight = 416;
        public const int imageWidth = 416;
    }
```
``` C#
MLContext context = new MLContext();
            var emptyData = new List<WineInput>();
            var data = context.Data.LoadFromEnumerable(emptyData);//Load Empty Data //Error!
``` 

- **What happened?**
I haven't done anything yet, and an error was reported in this line of code.！
However, I found that the code is identical, but an error will be reported
![image](https://user-images.githubusercontent.com/23449064/225888845-22fdb42a-912d-4b03-9963-d717828c3214.png)
I cloned the YouTube blogger's git and found that all nugets used are ML. Net 1.4
So I also downgraded the nuget package
It's actually working properly
No changes to the code

**After my comparison, I found that the dependency of the nuget package Microsoft.ML.ImageAnalytics has changed after upgrading to 2.0**
1.4 Normal works, 2.0 Abnormal works
![image](https://user-images.githubusercontent.com/23449064/225891591-7de8ce8e-8498-471c-a60e-9194e186ecc6.png)
![image](https://user-images.githubusercontent.com/23449064/225891886-c26919a1-29df-4de6-99d0-a6b304c4ae4d.png)

- **What did you expect?**
Starting with 2.0, it no longer rely on System.Drawing.Common,I don't know how to modify the Bitmap in the InputModel to achieve a workable effect
### Source code / logs
Input/Output Model:
```C# 
public class WineInput {
        [ImageType(ImageSettings.imageWidth, ImageSettings.imageHeight)]
        public Bitmap Image { get; set; }
    }
    public struct ImageSettings {
        public const int imageHeight = 416;
        public const int imageWidth = 416;
    }

internal class WineOutPut {
        [ColumnName("model_outputs0")]
        public float[] PredictedLabel { get; set; }

    }
```
PrdictionProcess:
```C#
 public class WinePrediction {
        private string modelFile = "./OnnxModels/RedOrWhiteWine.onnx";
        PredictionEngine<WineInput, WineOutPut> predictionEngine = null;
        public WinePrediction() {
            MLContext context = new MLContext();
            var emptyData = new List<WineInput>();
            var data = context.Data.LoadFromEnumerable(emptyData);

            var pipeline = context.Transforms.ResizeImages(
                resizing: Microsoft.ML.Transforms.Image.ImageResizingEstimator.ResizingKind.Fill,
                outputColumnName: "data",
                imageWidth: ImageSettings.imageWidth,
                imageHeight: ImageSettings.imageHeight,
                inputColumnName: nameof(WineInput.Image)
                )
                .Append(context.Transforms.ExtractPixels(outputColumnName: "data")
                .Append(context.Transforms.ApplyOnnxModel(modelFile: modelFile, outputColumnName: "model_outputs0", inputColumnName: "data")));

            var model = pipeline.Fit(data);

            predictionEngine = context.Model.CreatePredictionEngine<WineInput, WineOutPut>(model);

        }
        public void Prediction(string path) {
            using (var stream = new FileStream(path, FileMode.Open)) {
                using (var bitmap = (Bitmap)Image.FromStream(stream)) {
                    var prediction = predictionEngine.Predict(new WineInput() { Image = bitmap });
                }
            }

        }
    }
```
This is a link to github for my reference study [click here](https://github.com/jwood803/MLNetExamples/tree/master/MLNetExamples/CustomVisionOnnx)
The main problem is that there are some difficulties with Bitmap conversion in 2.0
I hope someone can teach me, thank you all

**Comment by LittleLittleCloud** [comment]
ML.Net 2.* drops dependencies over `System.Drawing` as well as DataViewType loader for Bitmap. You can replace `Bitmap` with `MLImage` in which case should work for most of situations.

**Comment by luisquintanilla** [comment]
Hi @BigHeadDev 

Thanks for your question. Did @LittleLittleCloud suggestion resolve your issue?

**Comment by BigHeadDev** [comment]
> ML.Net 2.* 删除了位图的依赖项以及 DataViewType 加载器。您可以替换为哪种情况应该适用于大多数情况。`System.Drawing``Bitmap``MLImage`
> 
> 有关详细信息，您可以参考此[发行说明](https://github.com/dotnet/machinelearning/blob/4a02a0148d76d63a07c66b8466734c8f34cbcbd4/docs/release-notes/2.0/release-2.0.0.md?plain=1#L48)

Thanks~~~

**Comment by BigHeadDev** [comment]
> 嗨@BigHeadDev
> 
> 谢谢你的提问。@LittleLittleCloud建议是否解决了您的问题？

Sure,Thanks~~~~~
