### ISSUE TITLE
NormalizeMeanVariance uses Population Variance

### ISSUE THREAD

**Issue by DavidMartinOnGitHub** [dotnet/machinelearning#6606]
[Enter feedback here]
It should probably be stated that this estimator uses the Population Variance not the Sample Variance. i.e. it does not apply Bessel's Correction. 

Since we're dealing with a **sample** of data in our ML activities not the entire **population**, a Sample Variance would be more intuitive (for some).

The difference will not be significant on large data sets. But it would be good to be more explicit about the calculation method.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ea15e2fa-1c88-31ea-76f8-5f35a0b002ee
* Version Independent ID: 3b599ef2-e67c-4e93-d0cb-38060f81b20e
* Content: [NormalizationCatalog.NormalizeMeanVariance Method (Microsoft.ML)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.ml.normalizationcatalog.normalizemeanvariance?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML/NormalizationCatalog.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML/NormalizationCatalog.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by luisquintanilla** [comment]
Hi @DavidMartinOnGitHub 

Thanks for raising this issue.
