### ISSUE TITLE
How to offset RGB differently and convert images to CHW？

### ISSUE THREAD

**Issue by BigHeadDev** [dotnet/machinelearning#6616]
### System information

- **OS version/distro**: Windows 11
- **.NET Version (eg., dotnet --info)**: .Net 6.0

### Issue

- **What did you do?**
Transforming a PTH model into an ONNX model and Connect it using ml.net
- **What happened?**
I don't know if there was a problem with my preprocessing,The results are always different from those predicted by Python code

Through Python code, it is generally known that preprocessing needs to go through RGB offset, and then convert HWC to CHW. 
1，However, it seems that the MLContext.Transform.ExtractPixels method can only specify the same offsetImage
2，There seems to be no method in MLContext.Transform to convert HWC to CHW. How should I use it

- **What did you expect?**
I hope someone can teach me how to connect this model
I have been researching for several days, hahaha  

**Here is the Python code：**
```python
        image_path = "./curve/test.jpg"
        img_raw = cv2.imread(image_path, cv2.IMREAD_COLOR)

        img = np.float32(img_raw)

        im_height, im_width, _ = img.shape
        scale = torch.Tensor([img.shape[1], img.shape[0], img.shape[1], img.shape[0]])
        img -= (104, 117, 123)//*
        img = img.transpose(2, 0, 1)//*
        img = torch.from_numpy(img).unsqueeze(0)
        img = img.to(device)
        scale = scale.to(device)

        tic = time.time()
        loc, conf, landms = net(img)  # forward pass
        print('net forward time: {:.4f}'.format(time.time() - tic))

        priorbox = PriorBox(cfg, image_size=(im_height, im_width))
        priors = priorbox.forward()
```
**This is my preprocessing code**
```C#
        var pipeline =
                context.Transforms.ResizeImages(
                resizing: Microsoft.ML.Transforms.Image.ImageResizingEstimator.ResizingKind.Fill,
                outputColumnName: "input0",
                imageWidth: 640,
                imageHeight: 640,
                inputColumnName: nameof(FaceInput.Image))
                .Append(context.Transforms.ExtractPixels(
                        offsetImage: 114f,//???
                        outputColumnName: "input0"))
                .Append(context.Transforms.ApplyOnnxModel(
                    modelFile: modelPath,
                    inputColumnName: "input0",
                    outputColumnName: "output0"));
            return pipeline;
```
**This is the source Python github repository**
[Retinaface](https://github.com/deepConnectionism/Retinaface)

**This is the onnx model**
![image](https://user-images.githubusercontent.com/23449064/230339057-032befa5-d562-416e-ba74-9844f95ecfd0.png)
[ONXX](https://github.com/deepConnectionism/Retinaface/blob/main/FaceDetector.onnx)
### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by BigHeadDev** [comment]
@LittleLittleCloud hello ,DaLao~~Help!

**Comment by LittleLittleCloud** [comment]
@BigHeadDev The easiest way I can think of is you can convert/normalize images color in pytorch if you already have pth model at hand. Extra work needs to be done if you want to do the similar preprocessing in ML.Net

In ML.Net, you will need to create a custome reshapeTransformer using `CustomTransformerMapping`. Here's an example for how to reshape an image with shape [3, 800, 600] to [3*800*600]
https://github.com/LittleLittleCloud/ObjectDetection/blob/master/ObjectDetection/ReshapeTransformer.cs

**Comment by BigHeadDev** [comment]
> @BigHeadDev The easiest way I can think of is you can convert/normalize images color in pytorch if you already have pth model at hand. Extra work needs to be done if you want to do the similar preprocessing in ML.Net
> 
> In ML.Net, you will need to create a custome reshapeTransformer using `CustomTransformerMapping`. Here's an example for how to reshape an image with shape [3, 800, 600] to [3_800_600] https://github.com/LittleLittleCloud/ObjectDetection/blob/master/ObjectDetection/ReshapeTransformer.cs

Thanks~~~
