### ISSUE TITLE
Daily recurring AutoML experiment - losses best Model

### ISSUE THREAD

**Issue by dietrichha** [dotnet/machinelearning#6617]
### Issue

In order to predict best prices, I do an AutoML regression expermient as explained here:

https://learn.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/how-to-use-the-automl-api

And safe the best Model with: 
mlContext.Model.Save(experimentResult.Model, trainDataView.Schema, modelFilePath);

And also print the Model R-Squared from the best found model.

To quickly adapt to new changes, I redo the AutoML expermient on a daily basis at 2 o'clock in the morning.

When I look at the R2s they change daily between 0.7 and 0.95. 

However, I save the model regardless of the last one, i overwrite the 0.95 R2 model with e.g. the 0.7 R2 model. That is perhaps not a good idea, as the 0.95 from yesterday could still be better than the 0.7 model from today. 

Is there a way to load the 0.95 model (yes, that i know and do) and retest it against the 0.7 R2 model's input data (that I do not find how to do)? Then I could compare the R2 of both and save the better one. 

Any ideas how to do this "retest" of the Model?

2. Question: Is there a way to automate this in the API? 
3. Is there a way to give the last model to the auto ml experiment to use it for re-training: https://learn.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/retrain-model-ml-net

**Comment by michaelgsharp** [comment]
@dietrichha is this still something you need help with?

@LittleLittleCloud any thoughts on this?
