### ISSUE TITLE
Unable to load DLL 'CpuMathNative': The specified module could not be found.

### ISSUE THREAD

**Issue by ConfieBlake** [dotnet/machinelearning#6623]
**System Information (please complete the following information):**
 - OS & Version: Windows 11
 - ML.NET Version: 17.15.0.2321402
 - .NET Version: NET Framework 4.8.1

**Describe the bug**
I added a ML model to a Class Library which targets at NET Framework 4.8.1. I could build the dll and run it in vscode notebook. This library is configured to debug on x64. But when I deployed the library on cosmos and run the SCOPE jobs with it, it starts to give the error "Unable to load DLL 'CpuMathNative': The specified module could not be found."
![image](https://user-images.githubusercontent.com/117148909/232797660-b51f0ba2-631a-4e44-a747-d08258b5bffc.png)
![image](https://user-images.githubusercontent.com/117148909/232797810-4096138d-8758-46b9-a53f-c6e0398e4f68.png)

I could not use NET Core, because NET Core needs to load System.Runtime version 6.0.0, which is incompatible with my project.

**And below is my project:**
[ProductNameClassifier.zip](https://github.com/dotnet/machinelearning/files/11262455/ProductNameClassifier.zip)

**Screenshots, Code, Sample Projects**
![image](https://user-images.githubusercontent.com/117148909/232796954-e8323684-0b7b-4105-95f7-f279930cf248.png)

**Comment by LittleLittleCloud** [comment]
`CpuMathNative` is located in runtime folder, try adding hint path like this
```
<Reference Include="CpuMathNative.dll">
   <HintPath>..\packages\microsoft.ml.cpumath\2.0.1\runtimes\win-x64\nativeassets\netstandard2.0\CpuMathNative.dll</HintPath>
</Reference>

```

**Comment by michaelgsharp** [comment]
I am not super familiar with Scope, but when using scope you need to upload the native binaries in a specific way. Closing this issue since its related to scope deployment and not ml.net.
