### ISSUE TITLE
Expected VarVector, got Byte

### ISSUE THREAD

**Issue by VictorBarbosa** [dotnet/machinelearning#6625]
**System Information (please complete the following information):**
 - OS & Version: [e.g. Windows 10] 
 - ML.NET Version: [e.g. ML.NET v2.0]
 - .NET Version: [e.g. .NET 7.0]

**Describe the bug**
I`ve created a model to image classification using visual studio and it works pretty well, but when i try to retrain i got this error, 

How can i fix it, thank you 
![image](https://user-images.githubusercontent.com/6170478/232911866-9996ee9e-dd45-4972-90b2-34deacfee6e6.png)

**Comment by michaelgsharp** [comment]
If this is still an issue for you please create a new one and I'll take a look.
