### ISSUE TITLE
Multiclass Classification AutoML and PFI won't complete

### ISSUE THREAD

**Issue by LanceElCamino** [dotnet/machinelearning#6630]
ML (2.0.1)
ML.AutoML (0.20.1) 

**Describe the bug**
The AutoMl experiment never finishes, just keeps running. No error output. Works fine when running as Binary Classification but now need Multiclass Classification. Have attached a small csv file to reproduce.

**To Reproduce**
Copy and paste code into new console app (Net 6.0). 
Save csv in Solution>Project>bin>Debug>net6.0 folder.
Run.

**Expected behavior**
Should output to console the experiment results and PFI metrics.

**Screenshots, Code, Sample Projects**
![image](https://user-images.githubusercontent.com/122576256/234399319-31d362a8-d60a-4bae-bbc0-5c10a38b99e8.png)

Just shows this and never stops running.

What did I do wrong?
`using System.Collections.Immutable;
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.AutoML;
using System.Data;

namespace PriceActionTestPFI
{
    internal class Program
    {
        //Model Input class
        public class ModelInput
        {
            [ColumnName(@"High"), LoadColumn(0)]
            public float High { get; set; }

            [ColumnName(@"Low"), LoadColumn(1)]
            public float Low { get; set; }

            [ColumnName(@"Close"), LoadColumn(2)]
            public float Close { get; set; }

            [ColumnName(@"MlLabels:Enter"), LoadColumn(3)]
            public float Enter { get; set; }

            [ColumnName(@"BarTimes:BarTime"), LoadColumn(4)]
            public float BarTime { get; set; }

            [ColumnName(@"BarTimes:BarTimeAvg"), LoadColumn(5)]
            public float BarTimeAvg { get; set; }

            [ColumnName(@"SlopeSimple:SlopeLine1"), LoadColumn(6)]
            public float Slope1 { get; set; }

            [ColumnName(@"LeavittConvolutionAcceleration:Acc"), LoadColumn(7)]
            public float Acc { get; set; }

            [ColumnName(@"SlopeSimple:SlopeLine2"), LoadColumn(8)]
            public float Slope2 { get; set; }

            [ColumnName(@"LeavittConvolution:Conv"), LoadColumn(9)]
            public float Conv { get; set; }

            [ColumnName(@"LeavittProjection:LProjection"), LoadColumn(10)]
            public float Projection { get; set; }

            [ColumnName(@"LeavittConvolutionSlope:SlopeValue"), LoadColumn(11)]
            public float Lslope { get; set; }
        }

        //Model Output class
        public class ModelOutput
        {
            // [ColumnName(@"Features")]
            // public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        private static string ModelPath = "PATest3PFI.zip";
        static void Main(string[] args)
        {
            //Create new ML context
            var mlContext = new MLContext();

            //Load data from csv/text file
            IDataView CSAData = mlContext.Data.LoadFromTextFile<ModelInput>(path: "ES Tuesday 922.csv", hasHeader: true, separatorChar: ',');

            //Split data into training and testing sets (80%/20%)
            var split = mlContext.Data.TrainTestSplit(CSAData, testFraction: 0.2);
            var trainData = split.TrainSet;
            var testData = split.TestSet;

            // Create, train, evaluate and save a model
            TransformerChain<ITransformer> trainedModel = BuildTrainEvaluateAndSaveModel(mlContext, trainData, testData);

            // Make a single test prediction loading the model from .ZIP file
            TestSinglePrediction(mlContext);

            // Calculate the Permuation Feature Importance (PFI)
            CalculatePermutationFeatureImportance(mlContext, trainData, trainedModel);

            Console.WriteLine("Press any key to exit..");
            Console.ReadLine();
        }
        private static TransformerChain<ITransformer> BuildTrainEvaluateAndSaveModel(MLContext mlContext, IDataView trainingDataView, IDataView testDataView)
        {
            // Run AutoML Multiclass Classification experiment
            Console.WriteLine("=============== Training the model ===============");
            Console.WriteLine($"Running AutoML experiment for 20 seconds...");
            ExperimentResult<MulticlassClassificationMetrics> experimentResult = mlContext.Auto()
                .CreateMulticlassClassificationExperiment(20)
                .Execute(trainingDataView, labelColumnName: @"MlLabels:Enter");

            // Evaluate the model and print metrics
            Console.WriteLine("===== Evaluating model's accuracy with test data =====");
            RunDetail<MulticlassClassificationMetrics> best = experimentResult.BestRun;
            ITransformer trainedModel = best.Model;
            TransformerChain<ITransformer> trainedModelChain = (TransformerChain<ITransformer>)best.Model;
            IDataView predictions = trainedModel.Transform(testDataView);
            var metrics = mlContext.MulticlassClassification.Evaluate(predictions, labelColumnName: @"MlLabels:Enter", scoreColumnName: "Score", predictedLabelColumnName: "PredictedLabel",
                topKPredictionCount: 1);

            // Print metrics from top model
            Console.WriteLine($"*************************************************");
            Console.WriteLine($"*       Metrics for {best.TrainerName} Multiclass Classification model      ");
            Console.WriteLine($"*------------------------------------------------");
            Console.WriteLine($"*       MicroAccuracy:      {metrics.MicroAccuracy:#.##}");
            Console.WriteLine($"*       MacroAccuracy:      {metrics.MacroAccuracy:#.##}");
            Console.WriteLine($"*       LogLoss:            {metrics.LogLoss:#.##}");
            Console.WriteLine($"*       PerClassLogLoss:    {metrics.PerClassLogLoss:#.##}");
            Console.WriteLine($"*       TopKAccuracy:       {metrics.TopKAccuracy:#.##}");
            Console.WriteLine(metrics.ConfusionMatrix.GetFormattedConfusionTable());
            Console.WriteLine($"*************************************************");

            // Save/persist the trained model to a .ZIP file
            mlContext.Model.Save(trainedModel, trainingDataView.Schema, ModelPath);

            Console.WriteLine("The model is saved to {0}", ModelPath);

            return trainedModelChain;
        }

        private static void TestSinglePrediction(MLContext mlContext)
        {
            Console.WriteLine("=============== Testing prediction engine ===============");

            var Sample = new ModelInput()
            {
                High = 4323.25F,
                Low = 4317.25F,
                Close = 4321.75F,
                BarTime = 1962.559F,
                BarTimeAvg = 1065.821F,
                Slope1 = -0.593749667F,
                Acc = 0.434773016F,
                Slope2 = 0.5404195F,
                Conv = 4312.420398F,
                Projection = 4313.347917F,
                Lslope = -0.393904748F,
            };

            ITransformer trainedModel = mlContext.Model.Load(ModelPath, out var _);

            // Create prediction engine related to the loaded trained model
            var predEngine = mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(trainedModel);

            // Score
            var predictedResult = predEngine.Predict(Sample);

            Console.WriteLine($"**********************************************************************");
            Console.WriteLine($"Predicted Entrance: {predictedResult.PredictedLabel}, actual: -1");
            Console.WriteLine($"Probability: {predictedResult.Score}");
            Console.WriteLine($"**********************************************************************");
        }

        private static void CalculatePermutationFeatureImportance(MLContext mlContext, IDataView trainingDataView, TransformerChain<ITransformer> trainedModel)
        {
            // Extract the trainer (last transformer in the model)
            var linearPredictor = (ISingleFeaturePredictionTransformer<object>)trainedModel.LastTransformer;

            // Transform data (make predictions)
            IDataView transformedData = trainedModel.Transform(trainingDataView);

            // Get labels for feature importance
            VBuffer<ReadOnlyMemory<char>> nameBuffer = default;
            transformedData.Schema["__Features__"].Annotations.GetValue("SlotNames", ref nameBuffer);
            // NOTE: The column name "__Features__" needs to match the featureColumnName used in the trainer, the name "SlotNames" is always the same regardless of trainer. View variable in Debug to find name.

            var featureColumnNames = nameBuffer.DenseValues().ToList();

            // Calculate Feature Permutation
            ImmutableArray<BinaryClassificationMetricsStatistics> permutationMetrics =
                                            mlContext.BinaryClassification.PermutationFeatureImportance(predictionTransformer: linearPredictor,
                                                                                         data: transformedData,
                                                                                         labelColumnName: @"MlLabels:Enter",
                                                                                         numberOfExamplesToUse: 100, permutationCount: 30);

            // Format feature importance output
            Console.WriteLine("Feature\tPFI");

            var featureImportanceMetrics =
                permutationMetrics
                .Select((metric, index) => new { index, metric.Accuracy })
                .OrderByDescending(myFeatures => Math.Abs(myFeatures.Accuracy.Mean));

            var featureNames = new List<string>();
            var featurePFI = new List<double>();
            foreach (var feature in featureImportanceMetrics)
            {
                featureNames.Add($"{featureColumnNames[feature.index],-20}");
                featurePFI.Add(feature.Accuracy.Mean);
                Console.WriteLine($"{featureColumnNames[feature.index],-20}|\t{feature.Accuracy.Mean}");
            }

        }
    }
}`
[ES Tuesday 922.csv](https://github.com/dotnet/machinelearning/files/11326721/ES.Tuesday.922.csv)

**Comment by feiyun0112** [comment]
your csv schema is not match  ModelInput

High is actually in column 3, and so on

```
Date,Time,Open,High,Low,Close,MlLabels:Enter,BarTimes:BarTime,BarTimes:BarTimeAvg,SlopeSimple:SlopeLine,LeavittConvolutionAcceleration:Acc,SlopeSimple:SlopeLine,LeavittConvolution:Conv,LeavittProjection:LProjection,LeavittConvolutionSlope:SlopeValue
8/7/2022,5:21:20 PM,4167.5,4168.5,4153.5,4154,0,0,0,0,0,0,0,0,0
```

```
[ColumnName(@"High"), LoadColumn(0)]
public float High { get; set; }

[ColumnName(@"Low"), LoadColumn(1)]
public float Low { get; set; }

[ColumnName(@"Close"), LoadColumn(2)]
public float Close { get; set; }

[ColumnName(@"MlLabels:Enter"), LoadColumn(3)]
public float Enter { get; set; }
```

**Comment by LanceElCamino** [comment]
Like most issues, it's something simply overlooked, thank you! Now I have another issue on line 264:

`var linearPredictor = (ISingleFeaturePredictionTransformer<object>)trainedModel.LastTransformer;`

Get error "Unable to cast obfect of type ''Microsoft.ML.Transforms.KeyToValueMappingTransformer' to type 'Microsoft.ML.ISingleFeaturePredictionTransformer`1[System.Object]'.'

**Comment by feiyun0112** [comment]
because LastTransformer is not ISingleFeaturePredictionTransformer

```
ISingleFeaturePredictionTransformer<object> linearPredictor = null;
foreach (var transformer in trainedModel)
{
    Console.WriteLine(transformer);
    if (transformer is ISingleFeaturePredictionTransformer<object> transformer1)
    {
        linearPredictor = transformer1;
    }
} 
```

Output:

```
Microsoft.ML.Transforms.MissingValueReplacingTransformer
Microsoft.ML.Data.ColumnConcatenatingTransformer
Microsoft.ML.Transforms.ValueToKeyMappingTransformer
Microsoft.ML.Data.MulticlassPredictionTransformer`1[Microsoft.ML.Trainers.OneVersusAllModelParameters]
Microsoft.ML.Transforms.KeyToValueMappingTransformer
```

**Comment by LanceElCamino** [comment]
Thanks I got it to work. Any idea how to map names to the Confusion Matrix so it isn't just displaying indexed values? My label classes are 0, 1, and -1 but the Confusion Matrix displays 0, 1, 2.

**Comment by JakeRadMSFT** [comment]
Not sure if it's what you're asking but the 

featureColumnNames should map back to your orignal classes.

so it might be something like this

featureColumnNames[0] = 0
featureColumnNames[1] = 1
featureColumnNames[2] = -1

**Comment by JakeRadMSFT** [comment]
Thanks @feiyun0112 for all your help responding!

**Comment by LanceElCamino** [comment]
featureColumnNames is for features not the label so I assume it could have to do with predictedLabelColumnName but where would you define those? This is now a different issue so I will close this one and open another. Thank you!
