### ISSUE TITLE
Propose: Let's expose Bert sentence embedding to public

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning#6635]
**Is your feature request related to a problem? Please describe.**
Using TextEmbedding API from OpenAI is great, but it's not free.

Bert embedding is available in ML.Net (or might be available with minor change), but it's not public available.

We all love free and good stuff, so let's expose bert embedding transformer to public. That would be a useful feature in retrieving relevant corpus when creating prompts

**Describe the solution you'd like**
a transformer that transforms a text to an embedding vector
- input: "text"
- output column: float[768]

**Comment by maheshlokhande** [comment]
When will be this API be made available publicly?

**Comment by LittleLittleCloud** [comment]
@michaelgsharp @luisquintanilla maybe we can start by exposing encoder transformer of NASBert model? We probably need to run a few document retrieval benchmarks to figure out the performance though
