### ISSUE TITLE
[LightGBM]  [Fatal] Unknown importance type error using Ml.Net API

### ISSUE THREAD

**Issue by LanceElCamino** [dotnet/machinelearning#6640]
**System Information (please complete the following information):**
 -  Windows 11 22H2
 - ML.NET 2.0.1
 - Auto.Ml 
 - .NET Framework 4.8

Keep getting this error:
![image](https://user-images.githubusercontent.com/122576256/235521011-0df3eb89-b484-4491-a579-aa44c125d477.png)

`using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.AutoML;
using System;
using System.Collections.Generic;
using System.Linq;

namespace PriceActionTestPFI
{
    internal class Program
    {
        //Model Input class
        public class ModelInput
        {
            [LoadColumn(6)]
            [ColumnName(@"PAF:Range")]
            public float PAF_Range { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"PAF:atr")]
            public float PAF_atr { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"PAF:NormPrice")]
            public float PAF_NormPrice { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"MlLabels:Enter")]
            public float MlLabels_Enter { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"BarTimes:BarTime")]
            public float BarTimes_BarTime { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"BarTimes:TimeVsAvg")]
            public float BarTimes_TimeVsAvg { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"BarTimes:Fast")]
            public bool BarTimes_Fast { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"Lin. reg. slope:Lin. reg. slope3")]
            public float Lin__reg__slope_Lin__reg__slope3 { get; set; }

            [LoadColumn(18)]
            [ColumnName(@"Lin. reg. slope:Lin. reg. slope5")]
            public float Lin__reg__slope_Lin__reg__slope5 { get; set; }

            [LoadColumn(19)]
            [ColumnName(@"Lin. reg. slope:Lin. reg. slope10")]
            public float Lin__reg__slope_Lin__reg__slope10 { get; set; }

            [LoadColumn(20)]
            [ColumnName(@"Lin. reg. slope:Lin. reg. slope20")]
            public float Lin__reg__slope_Lin__reg__slope20 { get; set; }

            [LoadColumn(21)]
            [ColumnName(@"AvgUpDown:AverageGain")]
            public float AvgUpDown_AverageGain { get; set; }

            [LoadColumn(22)]
            [ColumnName(@"AvgUpDown:AverageLoss")]
            public float AvgUpDown_AverageLoss { get; set; }

            [LoadColumn(47)]
            [ColumnName(@"SwingLevels:MajBullBoS")]
            public bool SwingLevels_MajBullBoS { get; set; }

            [LoadColumn(48)]
            [ColumnName(@"SwingLevels:MajBearBoS")]
            public bool SwingLevels_MajBearBoS { get; set; }

            [LoadColumn(49)]
            [ColumnName(@"SwingLevels:MajBullCont")]
            public bool SwingLevels_MajBullCont { get; set; }

            [LoadColumn(50)]
            [ColumnName(@"SwingLevels:MajBearCont")]
            public bool SwingLevels_MajBearCont { get; set; }

            [LoadColumn(51)]
            [ColumnName(@"SwingLevels:MinBullBoS")]
            public bool SwingLevels_MinBullBoS { get; set; }

            [LoadColumn(52)]
            [ColumnName(@"SwingLevels:MinBearBoS")]
            public bool SwingLevels_MinBearBoS { get; set; }

            [LoadColumn(53)]
            [ColumnName(@"SwingLevels:MinBullCont")]
            public bool SwingLevels_MinBullCont { get; set; }

            [LoadColumn(54)]
            [ColumnName(@"SwingLevels:MinBearCont")]
            public bool SwingLevels_MinBearCont { get; set; }

            [LoadColumn(55)]
            [ColumnName(@"SwingLevels:ProxLastSH")]
            public float SwingLevels_ProxLastSH { get; set; }

            [LoadColumn(56)]
            [ColumnName(@"SwingLevels:ProxLastSL")]
            public float SwingLevels_ProxLastSL { get; set; }

            [LoadColumn(57)]
            [ColumnName(@"SwingLevels:ProxLastSH2")]
            public float SwingLevels_ProxLastSH2 { get; set; }

            [LoadColumn(58)]
            [ColumnName(@"SwingLevels:ProxLastSL2")]
            public float SwingLevels_ProxLastSL2 { get; set; }

        }

        //Model Output class
        public class ModelOutput
        {
            //[ColumnName(@"Features")]
            //public float[] __Features__ { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        private static string ModelPath = "PriceActionTestPFImulti.zip";
        static void Main(string[] args)
        {
            //Create new ML context
            var mlContext = new MLContext();

            //Load data from csv/text file
            IDataView CSAData = mlContext.Data.LoadFromTextFile<ModelInput>(path:"ES Friday 1625.csv", hasHeader: true, separatorChar: ',');

            //Split data into training and testing sets (70%/30%)
            var split = mlContext.Data.TrainTestSplit(CSAData, testFraction: 0.3);
            var trainData = split.TrainSet;
            var testData = split.TestSet;

            // Create, train, evaluate and save a model
            TransformerChain<ITransformer> trainedModel = BuildTrainEvaluateAndSaveModel(mlContext, trainData, testData);

            // Make a single test prediction loading the model from .ZIP file
            TestSinglePrediction(mlContext);

            // Calculate the Permuation Feature Importance (PFI)
            CalculatePermutationFeatureImportance(mlContext, trainData, trainedModel);
            //CalculatePFI(mlContext, trainData, trainedModel, labelColumnName: @"MlLabels:Enter");

            Console.WriteLine("Press any key to exit..");
            Console.ReadLine();
        }

        private static TransformerChain<ITransformer> BuildTrainEvaluateAndSaveModel(MLContext mlContext, IDataView trainingDataView, IDataView testDataView)
        {
            // Run AutoML Multiclass Classification experiment
            Console.WriteLine("=============== Training the model ===============");
            Console.WriteLine($"Running AutoML experiment for 600 seconds...");
            ExperimentResult<MulticlassClassificationMetrics> experimentResult = mlContext.Auto()
                .CreateMulticlassClassificationExperiment(600)
                .Execute(trainingDataView, labelColumnName: @"MlLabels:Enter");

            // Evaluate the model and print metrics
            Console.WriteLine("===== Evaluating model's accuracy with test data =====");
            RunDetail<MulticlassClassificationMetrics> best = experimentResult.BestRun;
            ITransformer trainedModel = best.Model;
            TransformerChain<ITransformer> trainedModelChain = (TransformerChain<ITransformer>)best.Model;
            IDataView predictions = trainedModel.Transform(testDataView);
            var metrics = mlContext.MulticlassClassification.Evaluate(predictions, labelColumnName: @"MlLabels:Enter", scoreColumnName: "Score", predictedLabelColumnName: "PredictedLabel",
                topKPredictionCount: 1);

            // Print metrics from top model
            Console.WriteLine($"*************************************************");
            Console.WriteLine($"*       Metrics for {best.TrainerName} Multiclass Classification model      ");
            Console.WriteLine($"*------------------------------------------------");
            Console.WriteLine($"*       MicroAccuracy:      {metrics.MicroAccuracy:#.##}");
            Console.WriteLine($"*       MacroAccuracy:      {metrics.MacroAccuracy:#.##}");
            Console.WriteLine($"*       LogLoss:            {metrics.LogLoss:#.##}");
            Console.WriteLine(metrics.ConfusionMatrix.GetFormattedConfusionTable());
            Console.WriteLine($"*************************************************");

            // Save/persist the trained model to a .ZIP file
            mlContext.Model.Save(trainedModel, trainingDataView.Schema, ModelPath);

            Console.WriteLine("The model is saved to {0}", ModelPath);

            return trainedModelChain;

        }
        private static void TestSinglePrediction(MLContext mlContext)
        {
            Console.WriteLine("=============== Testing prediction engine ===============");

            var Sample = new ModelInput()
            {
                PAF_Range = 2.25F,
                PAF_atr = 2.710295F,
                PAF_NormPrice = 0.7777778F,
                BarTimes_BarTime = 101.461F,
                BarTimes_TimeVsAvg = 100.6064F,
                Lin__reg__slope_Lin__reg__slope3 = -0.875F,
                Lin__reg__slope_Lin__reg__slope5 = 0.275F,
                Lin__reg__slope_Lin__reg__slope10 = 0.2893939F,
                Lin__reg__slope_Lin__reg__slope20 = -0.08139098F,
                AvgUpDown_AverageGain = 0.75F,
                AvgUpDown_AverageLoss = 0.52F,
                SwingLevels_ProxLastSH = 1.002004F,
                SwingLevels_ProxLastSL = 1.006112F,
                SwingLevels_ProxLastSH2 = 0.998963884F,
                SwingLevels_ProxLastSL2 = 1.001261034F,

            };

            ITransformer trainedModel = mlContext.Model.Load(ModelPath, out var _);

            // Create prediction engine related to the loaded trained model
            var predEngine = mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(trainedModel);
          
            // Score
            var predictedResult = predEngine.Predict(Sample);

            Console.WriteLine($"**********************************************************************");
            Console.WriteLine($"Predicted Entrance: {predictedResult.PredictedLabel}, Actual: -1");
            Console.WriteLine($"Probability: {predictedResult.Score.Max()}");
            Console.WriteLine($"**********************************************************************");
        }

        private static void CalculatePermutationFeatureImportance(MLContext mlContext, IDataView trainingDataView, TransformerChain<ITransformer> trainedModel)
        {
            // Transform data (make predictions)
            IDataView transformedData = trainedModel.Transform(trainingDataView);

            // Get labels for feature importance
            VBuffer<ReadOnlyMemory<char>> nameBuffer = default;
            transformedData.Schema["__Features__"].Annotations.GetValue("SlotNames", ref nameBuffer);
            // NOTE: The column name "__Features__" needs to match the featureColumnName used in the trainer, the name "SlotNames" is always the same regardless of trainer. View variable in Debug to find name.

            var featureColumnNames = nameBuffer.DenseValues().ToList();

            // Calculate Feature Permutation
            var permutationMetrics = mlContext.MulticlassClassification.PermutationFeatureImportance(model :trainedModel,
                                                                                                    data: transformedData,
                                                                                                    labelColumnName: @"MlLabels:Enter",
                                                                                                    numberOfExamplesToUse: 10000, permutationCount: 30);

            // Format feature importance output
            Console.WriteLine("Feature\tPFI");

            var featureImportanceMetrics =
                permutationMetrics
                .Select((kvp) => new { kvp.Key, kvp.Value.MicroAccuracy })
                .OrderByDescending(myFeatures => Math.Abs(myFeatures.MicroAccuracy.Mean));

            var featurePFI = new List<Tuple<string, double>>();
            foreach (var feature in featureImportanceMetrics)
            {
                var pfiValue = Math.Abs(feature.MicroAccuracy.Mean);
                featurePFI.Add(new Tuple<string, double>(feature.Key, pfiValue));
            }
            foreach (var tuple in featurePFI)
            { Console.WriteLine($"{tuple.Item1} - {tuple.Item2}"); }

        }
    }
}`
It still completes the experiment but prefer LightGBM to be included.

**Comment by luisquintanilla** [comment]
Hi @LanceElCamino 

Sorry you're running into issues. 

@LittleLittleCloud do you know if AutoML might be causing this?

**Comment by michaelgsharp** [comment]
Closing as we have released a new version of ML.NET with a new version of LightGBM, but if this is still an issue please re-open/create a new one
