### ISSUE TITLE
Should use a different source name for object detection trainer

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning#6650]
![image](https://user-images.githubusercontent.com/16876986/236064448-bc35de01-f066-448a-b9e9-9286c6274608.png)

Should be `ObjectDetectionTrainer` or something

**Comment by JakeRadMSFT** [comment]
Might be resolved already?

https://github.com/dotnet/machinelearning/pull/6646/files

**Comment by michaelgsharp** [comment]
Resolved by #6646
