### ISSUE TITLE
Entry point 'Transforms.CategoricalOneHotVectorizer' not found

### ISSUE THREAD

**Issue by arunrules** [dotnet/machinelearning#666]
I built my first dummy ml.net console app from my dev box and ensured it worked as expected.
 
Then I copied the binaries (console app + a bunch of [136] Micrososft.ML.* and its dependencies) to a windows server machine and I see the following exception.
 
Unhandled Exception: System.InvalidOperationException: Entry point 'Transforms.CategoricalOneHotVectorizer' not found
   at Microsoft.ML.Runtime.EntryPoints.EntryPointNode..ctor(IHostEnvironment env, IChannel ch, ModuleCatalog moduleCatalog, RunContext context, String id, String entryPointName, JObject inputs, JObject outputs, Boolean checkpoint, String stageId, Single cost, String label, String group, String weight, String name)
   at Microsoft.ML.Runtime.EntryPoints.EntryPointNode.ValidateNodes(IHostEnvironment env, RunContext context, JArray nodes, ModuleCatalog moduleCatalog, String label, String group, String weight, String name)
   at Microsoft.ML.Runtime.EntryPoints.EntryPointGraph..ctor(IHostEnvironment env, ModuleCatalog moduleCatalog, JArray nodes)
   at Microsoft.ML.Runtime.Experiment.Compile()
   at Microsoft.ML.LearningPipeline.Train[TInput,TOutput]()
   at MyMLApp2.Program.Train() in E:\ML\MyMLApp2\MyMLApp2\Program.cs:line 111
   at MyMLApp2.Program.Main(String[] args) in E:\ML\MyMLApp2\MyMLApp2\Program.cs:line 64
 
any idea why?

**Comment by sfilipi** [comment]
Did you copy the libraries all in one folder, and in the same folder as your executable/libraries?

Might be similar to #618

**Comment by arunrules** [comment]
Yes, I copied all the libraries in the same folder that had my test exe. Copied the same folder to a Windows Client machine and it worked. Has issue only when running from a Windows Server machine.

Here is the list of binaries that are present in the same folder as my test app. Let me know if i am missing anything here.

CpuMathNative.dll
FactorizationMachineNative.dll
FastTreeNative.dll
LdaNative.dll
Microsoft.ML.Api.dll
Microsoft.ML.Api.xml
Microsoft.ML.Core.dll
Microsoft.ML.Core.xml
Microsoft.ML.CpuMath.dll
Microsoft.ML.CpuMath.xml
Microsoft.ML.Data.dll
Microsoft.ML.Data.xml
Microsoft.ML.dll
Microsoft.ML.FastTree.dll
Microsoft.ML.FastTree.xml
Microsoft.ML.KMeansClustering.dll
Microsoft.ML.KMeansClustering.xml
Microsoft.ML.Maml.dll
Microsoft.ML.Maml.xml
Microsoft.ML.PCA.dll
Microsoft.ML.PCA.xml
Microsoft.ML.PipelineInference.dll
Microsoft.ML.PipelineInference.xml
Microsoft.ML.ResultProcessor.dll
Microsoft.ML.ResultProcessor.xml
Microsoft.ML.StandardLearners.dll
Microsoft.ML.StandardLearners.xml
Microsoft.ML.Sweeper.dll
Microsoft.ML.Sweeper.xml
Microsoft.ML.Transforms.dll
Microsoft.ML.Transforms.xml
Microsoft.ML.xml
Microsoft.Win32.Primitives.dll
netstandard.dll
Newtonsoft.Json.dll
Newtonsoft.Json.xml
System.AppContext.dll
System.CodeDom.dll
System.Collections.Concurrent.dll
System.Collections.dll
System.Collections.NonGeneric.dll
System.Collections.Specialized.dll
System.ComponentModel.dll
System.ComponentModel.EventBasedAsync.dll
System.ComponentModel.Primitives.dll
System.ComponentModel.TypeConverter.dll
System.Console.dll
System.Data.Common.dll
System.Diagnostics.Contracts.dll
System.Diagnostics.Debug.dll
System.Diagnostics.FileVersionInfo.dll
System.Diagnostics.Process.dll
System.Diagnostics.StackTrace.dll
System.Diagnostics.TextWriterTraceListener.dll
System.Diagnostics.Tools.dll
System.Diagnostics.TraceSource.dll
System.Diagnostics.Tracing.dll
System.Drawing.Primitives.dll
System.Dynamic.Runtime.dll
System.Globalization.Calendars.dll
System.Globalization.dll
System.Globalization.Extensions.dll
System.IO.Compression.dll
System.IO.Compression.ZipFile.dll
System.IO.dll
System.IO.FileSystem.dll
System.IO.FileSystem.DriveInfo.dll
System.IO.FileSystem.Primitives.dll
System.IO.FileSystem.Watcher.dll
System.IO.IsolatedStorage.dll
System.IO.MemoryMappedFiles.dll
System.IO.Pipes.dll
System.IO.UnmanagedMemoryStream.dll
System.Linq.dll
System.Linq.Expressions.dll
System.Linq.Parallel.dll
System.Linq.Queryable.dll
System.Net.Http.dll
System.Net.NameResolution.dll
System.Net.NetworkInformation.dll
System.Net.Ping.dll
System.Net.Primitives.dll
System.Net.Requests.dll
System.Net.Security.dll
System.Net.Sockets.dll
System.Net.WebHeaderCollection.dll
System.Net.WebSockets.Client.dll
System.Net.WebSockets.dll
System.ObjectModel.dll
System.Reflection.dll
System.Reflection.Extensions.dll
System.Reflection.Primitives.dll
System.Resources.Reader.dll
System.Resources.ResourceManager.dll
System.Resources.Writer.dll
System.Runtime.CompilerServices.VisualC.dll
System.Runtime.dll
System.Runtime.Extensions.dll
System.Runtime.Handles.dll
System.Runtime.InteropServices.dll
System.Runtime.InteropServices.RuntimeInformation.dll
System.Runtime.Numerics.dll
System.Runtime.Serialization.Formatters.dll
System.Runtime.Serialization.Json.dll
System.Runtime.Serialization.Primitives.dll
System.Runtime.Serialization.Xml.dll
System.Security.Claims.dll
System.Security.Cryptography.Algorithms.dll
System.Security.Cryptography.Csp.dll
System.Security.Cryptography.Encoding.dll
System.Security.Cryptography.Primitives.dll
System.Security.Cryptography.X509Certificates.dll
System.Security.Principal.dll
System.Security.SecureString.dll
System.Text.Encoding.dll
System.Text.Encoding.Extensions.dll
System.Text.RegularExpressions.dll
System.Threading.dll
System.Threading.Overlapped.dll
System.Threading.Tasks.Dataflow.dll
System.Threading.Tasks.Dataflow.xml
System.Threading.Tasks.dll
System.Threading.Tasks.Parallel.dll
System.Threading.Thread.dll
System.Threading.ThreadPool.dll
System.Threading.Timer.dll
System.ValueTuple.dll
System.Xml.ReaderWriter.dll
System.Xml.XDocument.dll
System.Xml.XmlDocument.dll
System.Xml.XmlSerializer.dll
System.Xml.XPath.dll
System.Xml.XPath.XDocument.dll

**Comment by arunrules** [comment]
Regular .Net desktop console app (.Net framework 4.7).
