### ISSUE TITLE
Microsoft.ML.TorchSharp TextClassification trainer throwing System.TypeLoadException

### ISSUE THREAD

**Issue by maheshlokhande** [dotnet/machinelearning#6665]
**System Information (please complete the following information):**
 - OS & Version: Windows Server 2019
 - ML.NET Version: 2.0.1
 - .NET Version: .NET 7

**Describe the bug**
I am trying to use TextClassification trainer which is part of Microsoft.ML.TorchSharp package as per example here: https://devblogs.microsoft.com/dotnet/introducing-the-ml-dotnet-text-classification-api-preview/

I have added all the required packages as per above guide.
Microsoft.ML - 2.0.1
Microsoft.ML.TorchSharp - 0.20.1
TorchSharp-cpu - 0.99.6

On calling Fit method, it is throwing below exception:

System.TypeLoadException
  HResult=0x80131522
  Message=Method 'call' in type 'Microsoft.ML.TorchSharp.NasBert.Models.TransformerEncoder' from assembly 'Microsoft.ML.TorchSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' does not have an implementation.
  Source=Microsoft.ML.TorchSharp
  StackTrace:
   at Microsoft.ML.TorchSharp.NasBert.NasBertTrainer`2.TrainerBase..ctor(NasBertTrainer`2 parent, IChannel ch, IDataView input)
   at Microsoft.ML.TorchSharp.NasBert.TextClassificationTrainer.Trainer..ctor(NasBertTrainer`2 parent, IChannel ch, IDataView input)
   at Microsoft.ML.TorchSharp.NasBert.TextClassificationTrainer.CreateTrainer(NasBertTrainer`2 parent, IChannel ch, IDataView input)
   at Microsoft.ML.TorchSharp.NasBert.NasBertTrainer`2.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)

**To Reproduce**
1. Create pipeline as below and call Fit method on it
`var pipeline = mlContext.Transforms.Conversion.MapValueToKey("Key", "Class")
                .Append(mlContext.MulticlassClassification.Trainers.TextClassification("Key", sentence1ColumnName: "text"))
                .Append(mlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel", "Key"));
				
var transformer = pipeline.Fit(trainSet)`

**Comment by feiyun0112** [comment]
because some interface has changed, you should use matching Nuget version

[https://www.nuget.org/packages/Microsoft.ML.TorchSharp/0.20.0-preview.22313.1#dependencies-body-tab](https://www.nuget.org/packages/Microsoft.ML.TorchSharp/0.20.0-preview.22313.1#dependencies-body-tab)
```
<ItemGroup>
    <PackageReference Include="Microsoft.ML" Version="2.0.0-preview.22313.1" />
    <PackageReference Include="Microsoft.ML.TorchSharp" Version="0.20.0-preview.22313.1" />
    <PackageReference Include="TorchSharp-cpu" Version="0.96.7" />
  </ItemGroup>
```

**Comment by maheshlokhande** [comment]
I upgraded packages as you suggested but still getting same exception. Also, this trainer was released as part of ML.NET 2.0.0. I believe it should work with ML.NET 2.0.1.

![image](https://github.com/dotnet/machinelearning/assets/17777324/eb007f22-3061-4399-9e8c-aecdc2308b66)

On another note, version 2.0.0 is missing from here and 1.7 is shown as latest stable version. What happened to version 2.0?
https://github.com/dotnet/machinelearning/releases

**Comment by feiyun0112** [comment]
> I upgraded packages as you suggested but still getting same exception. Also, this trainer was released as part of ML.NET 2.0.0. I believe it should work with ML.NET 2.0.1.
> 
> ![image](https://user-images.githubusercontent.com/17777324/237294737-eb007f22-3061-4399-9e8c-aecdc2308b66.png)
> 
> On another note, version 2.0.0 is missing from [here](https://github.com/dotnet/machinelearning/releases) and 1.7 is shown as latest stable version. What happened to version 2.0? When is 3.0 expected to be released?

0.98.3

**Comment by luisquintanilla** [comment]
Hi @maheshlokhande 

Sorry to hear you ran into an issue and thank you @feiyun0112 for jumping in to assist. 

@maheshlokhande as @feiyun0112, can you try updating the Torchsharp-cpu package to version 0.98.3. Here is a list of ML.NET Versions and the TorchSharp package versions they target. 

| ML.NET Version | TorchSharp Package Version |
| --- | --- |
| 2.0.0 | 0.98.1 |
| 2.0.1 | 0.98.1 |
| 3.0.0-preview | 0.98.3 | 
| Next preview | 0.99.5 |

We also opened an issue to update our docs with this information. #6669

If this doesn't resolve your issue, please feel free to open another one.

**Comment by maheshlokhande** [comment]
Yes the solution suggested by @feiyun0112 worked. Thank you @feiyun0112 and @luisquintanilla
