### ISSUE TITLE
AutoML: 'System.OperationCanceledException' after upgrade to  AutoML 0.20.1

### ISSUE THREAD

**Issue by NiPersson** [dotnet/machinelearning#6706]
- Windows 10 
 - ML.NET 2.0 AutoML 0.20.1 (NuGet)
 - .NET 7.0
 - Visual Basic

After upgrading to 0.20.1 I get an "Operation was canceled" exception after a while during training. I tried tweaking the code but could not get rid of it and it persisted when I tried a simple example as shown below:   

        ' Create MLContext
        Dim dataPath As String = "C:\taxi-fare-train.csv"
        Dim ctx As MLContext = New MLContext()

        ' Infer column information
        Dim columnInference As ColumnInferenceResults = ctx.Auto().InferColumns(dataPath, labelColumnName:="fare_amount", groupColumns:=False)

        ' Create text loader
        Dim loader As TextLoader = ctx.Data.CreateTextLoader(columnInference.TextLoaderOptions)

        ' Load data into IDataView
        Dim data As IDataView = loader.Load(dataPath)

        ' Split into train (80%), validation (20%) sets
        Dim trainValidationData As TrainTestData = ctx.Data.TrainTestSplit(data, testFraction:=0.2)

        'Define pipeline
        Dim Pipeline As SweepablePipeline = ctx.Auto().Featurizer(data, columnInformation:=columnInference.ColumnInformation).Append(ctx.Auto().Regression(labelColumnName:=columnInference.ColumnInformation.LabelColumnName))

        ' Create AutoML experiment
        Dim experiment As AutoMLExperiment = ctx.Auto().CreateExperiment()

        ' Configure experiment
        experiment.SetPipeline(Pipeline).SetRegressionMetric(RegressionMetric.RSquared, labelColumn:=columnInference.ColumnInformation.LabelColumnName).SetTrainingTimeInSeconds(60).SetDataset(trainValidationData)

        ' Run experiment
        Dim experimentResults As TrialResult = experiment.Run
        Dim model = experimentResults.Model

The exceptions comes at "Dim experimentResults As TrialResult = experiment.Run".

**Comment by LittleLittleCloud** [comment]
Have you tried adding more time or use `SetMaxModelToExplore`?

**Comment by NiPersson** [comment]
Yes, the only difference is that with longer max time to train/more models
to explore, it takes longer time for the exception to occur. Usually close
to the maxed allowed time except for when using only LightGBM. Then the
exception occur with in a few seconds.

Nicklas

Den tis 23 maj 2023 22:41Xiaoyun Zhang ***@***.***> skrev:

**Comment by LittleLittleCloud** [comment]
Your code runs well on my end
<img width="595" alt="image" src="https://github.com/dotnet/machinelearning/assets/16876986/812a4c22-1ece-4dda-bbd9-03c521e19e67">

I'm targeting to the latest AutoML package though
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ConsoleApp1</RootNamespace>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.AutoML" Version="0.21.0-preview.23266.6" />
  </ItemGroup>

</Project>
```

**Comment by NiPersson** [comment]
![image](https://github.com/dotnet/machinelearning/assets/73466853/1c9b27ae-048e-4d59-9899-a127cf791f8f)

**Comment by LittleLittleCloud** [comment]
The stacktrace looks fine. It's the expected stacktrace when time's up.

So the issue you have is no trial can be run til completed no matter how much time you set for `SetTrainingTime`?

**Comment by NiPersson** [comment]
Hi, sorry for the late answer. No matter the time one sets for the training this persists. What we have found is that it seems to be thread related. The sample I supplied above works in a "clean and new project" but not where it is used in our project. In the c# code examples I have seen one usually uses: 

await experiment.RunAsync();

which I guess translates to:

Dim t = experiment.RunAsync()
t.Wait()

 in visual basic. but this still gives the same exception.

**Comment by LittleLittleCloud** [comment]
@NiPersson How many training thread would your project kicks off when starting

**Comment by NiPersson** [comment]
We have only one thread used for training but large and complex project.

**Comment by LittleLittleCloud** [comment]
@NiPersson How about the dataset? Is the dataset still \taxi-fare-train.tsv?

**Comment by LittleLittleCloud** [comment]
@NiPersson And did you dispose or call `MLContext.Cancel` anywhere in your project?

**Comment by NiPersson** [comment]
> @NiPersson How about the dataset? Is the dataset still \taxi-fare-train.tsv?

I have tested with this dataset alongside what we normally use.

**Comment by NiPersson** [comment]
> MLContext.Cancel

Does not  RunAsync call it? 

//
        // Summary:
        //     Run experiment and return the best trial result asynchronizely. The experiment
        //     returns the current best trial result if there's any trial completed when ct
        //     get cancelled, and throws System.TimeoutException with message "Training time
        //     finished without completing a trial run" when no trial has completed. Another
        //     thing needs to notice is that this function won't immediately return after ct
        //     get cancelled. Instead, it will call Microsoft.ML.MLContext.CancelExecution to
        //     cancel all training process and wait all running trials get cancelled or completed.
        public async Task<TrialResult> RunAsync(CancellationToken ct = default(CancellationToken))

Other than that, It does not look like I do.

**Comment by LittleLittleCloud** [comment]
@NiPersson can you try disable `lightGbm` and train again? Looks like the exception was thrown from lightgbm trainer. In AutoML2.0, we add a `CheckAlive` checkpoint in lightGBM trainer, that might be the cause

**Comment by NiPersson** [comment]
Already tested that... All trainers produce this exception

**Comment by LittleLittleCloud** [comment]
Then my best bet without access to your project or minial reproducable example is the exception is caused by time-out. Is your project compute-instense? Have you try setting a super long time budget?

**Comment by NiPersson** [comment]
One thing I recalled now was with a "clean project", if you ran it from a thread, you also got the exception: 

Task.Run(Sub()
' Call example code
End Sub)

**Comment by NiPersson** [comment]
> Then my best bet without access to your project or minial reproducable example is the exception is caused by time-out. Is your project compute-instense? Have you try setting a super long time budget?

I would say it is not computer intense. Before the update I used 60 secs max for training. If I don't recall wrong I tested with max 30 minutes as the longest.

**Comment by LittleLittleCloud** [comment]
> One thing I recalled now was with a "clean project", if you ran it from a thread, you also got the exception:
> 
> Task.Run(Sub() ' Call example code End Sub)

Can you provide a minimal example for it? I'm not quite familiar with vb.net

**Comment by NiPersson** [comment]
I can do that. Hopefully I have time in a few hours.

**Comment by LittleLittleCloud** [comment]
That's an interesting find! @ericstj @JakeRadMSFT @michaelgsharp Do you know who can I reach out to for this issue?

**Comment by ericstj** [comment]
@LittleLittleCloud can you repro as well with the latest example?  If folks are suspecting some threading difference perhaps examining the process at the time the exception is thrown might reveal a stuck thread, or a blocked task?  Those sort of differences can happen machine/machine (or framework/framework) if there is a race condition involved.

**Comment by NiPersson** [comment]
> That's an interesting find! @ericstj @JakeRadMSFT @michaelgsharp Do you know who can I reach out to for this issue?

@LittleLittleCloud Did you manage to reproduce the issue?

**Comment by ericstj** [comment]
@NiPersson -- I just noticed from the above exchange that the stack trace you captured was in the debugger.  Just double checking -- are you able to reproduce this outside the debugger?  Running async/multi-threaded code that depends on timeouts can often have different behavior under the debugger since it can freeze threads.  Just double checking that we're all on the same page here WRT to repro steps.

**Comment by LittleLittleCloud** [comment]
@NiPersson Unfortunately, I still can't reproduce the exception with your latest code.

**Comment by NiPersson** [comment]
> @NiPersson Unfortunately, I still can't reproduce the exception with your latest code.

@LittleLittleCloud Me and a colleague tested this yesterday. For him the exception happened but rarely (2/23) with the .Net7 project and for me every time. The Framework 4.8 also misbehaved. I once got a missing LightGBM dll exception and my colleague got that exception every time. I you use visual studio, here is a visual studio project with the .Net7 project:

https://www.dropbox.com/scl/fi/t0nb9fkr79gfb3ounz0jz/ConsoleApp2.zip?rlkey=x1kzl68zhxj9s8mwwd2e8qum9&dl=0

**Comment by NiPersson** [comment]
> @NiPersson -- I just noticed from the above exchange that the stack trace you captured was in the debugger. Just double checking -- are you able to reproduce this outside the debugger? Running async/multi-threaded code that depends on timeouts can often have different behavior under the debugger since it can freeze threads. Just double checking that we're all on the same page here WRT to repro steps.

@ericstj I now tried it in release and the exception occurs

**Comment by NiPersson** [comment]
I tested "my production code" (not the example code) with a real build on a production server and there it goes better than what I see locally. The first 13 models created had only one exception.

**Comment by LittleLittleCloud** [comment]
@NiPersson I'm using .net 6, let me try on .net 7

**Comment by NiPersson** [comment]
@LittleLittleCloud Did you manage to reproduce it?

**Comment by LittleLittleCloud** [comment]
@NiPersson I tried, still works, no luck with .net7

**Comment by NiPersson** [comment]
@LittleLittleCloud : If I have the visual studio; "Enable Just My Code" setting selected than the exception is masked in most cases for me, could that be the explanation? Also it does not seem to happen all the time for all user, my colleague as stated previously, only had the exception like on average 1/10.

**Comment by NiPersson** [comment]
@LittleLittleCloud Hi again was "DotNetEvolution" the name of the channel? Incase so I did not find you there. But it could just be from lack of experience due to not using Discord :)

**Comment by LittleLittleCloud** [comment]
@NiPersson Sorry should be this one
https://discord.com/invite/Atpktwt8

Once you are in, You can find my id #BigMiao

@luisquintanilla maybe we need to update discord link?

**Comment by michaelgsharp** [comment]
Closing due to stale issue. If its still a problem please re-open/create a new issue.
