### ISSUE TITLE
Microsoft.ML.Model.OnnxConverter- System.InvalidOperationException: 'Unsupported type: Microsoft.ML.Data.MLImage'

### ISSUE THREAD

**Issue by ETG77** [dotnet/machinelearning#6716]
**System Information (please complete the following information):**
 - OS & Version: Win 11 Enterprise
 - .NET Version: .NET 6.0
 - Microsoft.ML v3.0.0-preview.23266.6
 - Microsoft.ML.ImageAnalytics v3.0.0-preview.23266.6
- Microsoft.ML.OnnxConverter v0.21.0-preview.23266.6

**Describe the bug**
Microsoft.ML.Data.MLImage unsupported in Microsoft.ML.Model.OnnxConverter.OnnxUtils.ConvertToTensorProtoType(Type rawType)

**To Reproduce**
1. Generate an (Object Detection) ML.NET model using VS Modelbuilder (Local GPU)
2. Run mlContext.Model.ConvertToOnnx(loadedModel, inputData, stream);
3. OnnxConverter will throw the following error 
Message=Unsupported type: Microsoft.ML.Data.MLImage
  Source=Microsoft.ML.OnnxConverter
  StackTrace:
   at Microsoft.ML.Model.OnnxConverter.OnnxUtils.ConvertToTensorProtoType(Type rawType)

**Expected behavior**
Generate an ONNX model from a .MLNET model

**Comment by michaelgsharp** [comment]
Our ObjectDetection pipeline is not convertable to ONNX at this point in time. It is something we want to look at in the future though.
