### ISSUE TITLE
Retrain existing model issue

### ISSUE THREAD

**Issue by engilas** [dotnet/machinelearning#6740]
**System Information (please complete the following information):**
 - OS & Version: Windows 10
 - ML.NET Version: ML.NET v2.0.1
 - .NET Version: .NET 7.0

**Describe the bug**
I have an existing model with about 500k weights.
When I try to retrain it according to [this ](https://learn.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/retrain-model-ml-net) tutorial, my new model has a vector of zero weights and makes the same prediction for any input data.
I use only new records in for my retrain data, about 100 records. The original train data contains 100k records.

What data should I pass to the Fit method while retraining? Should it contain only new data or the previous set + new data?

Trainer: LbfgsLogisticRegressionBinaryTrainer

**To Reproduce**
I tried to reporoduce it using samples code from [here](https://github.com/dotnet/machinelearning/blob/main/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/LbfgsLogisticRegression.cs)
I created a new small dataset using GenerateRandomDataPoints(10);
Then I created another model using Fit(newSmallData, oldParameters)
Behavior was the same.

**Comment by luisquintanilla** [comment]
Hi @engilas 

Can you add  a sample repro of this issue so we can better help you.
