### ISSUE TITLE
Integration of ML.Net 2.0.1 into Unity 2022.3.2f1 causes "DllNotFoundExeption: CpuMathNative" error

### ISSUE THREAD

**Issue by Mike-CineonTraining** [dotnet/machinelearning#6741]
**System Information (please complete the following information):**
 - Windows 10 Home 22H2
 - ML.Net 2.0.1
 - .NET Standard 2.1 & .NET Framework (Set via Unity's "Project Settings->Player->Api Compatibility Level")

**Describe the bug**
When trying to call 'SentimentModel.Predict(sampleData)' Unity console produces "DllNotFoundException: CpuMathNative <unknown assembly> error.

**To Reproduce**
1. Install Unity 2022.3.2f1.
2. Download the list of dll's in Appendix A (from attached zip or NuGet packages), and place in "\Assets\Plugins" of the Unity project.  A zip of the plugins is included in aforementioned Appendix.
3. Create a "sentiment model" by working through the basic tutorial for ML.Net found [here](https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/intro).
4. Copy the "SentimentModel.consumption.cs" and "SentimentModel.training.cs" files (found under "SentimentModel.mbconfig" in the solution explorer) to the Unity project.
5. Create a test script and call the sentiment model as per the instructions found in the "Consume" step of the models creation.  Please note, you will have to use a 'using' statement at the beginning of your test script, or explicitly use the namespace of the SentimentModel.  Snippet from my test project is in Appendix B.

**Expected behaviour**
The model should provide either a '0' or a '1' to indicate whether the input text contained a negative or positive sentiment (respectively)

**Actual behaviour**
(In Editor)
Error occurs, citing "DllNotFoundExceptionL CpuMathNative <unknown assembly>... " - please see screenshot below for stack trace.

(In standalone build)
Error occurs, contents are as follows:
> WindowsPlayer "[My Computer name]" InvalidOperationException: Can't instantiate loadable class 'IDataTransform' with name 'ValueMappingTransformer'

**Screenshots, Code, Sample Projects**
Error produced in Unity (pasting text might cause a parsing error, so screencapped instead)
![MLNetError](https://github.com/dotnet/machinelearning/assets/104988222/4346950e-cecf-4bf6-96c0-660cef43cca3)

Import settings (same for all DLL's)
![Import1](https://github.com/dotnet/machinelearning/assets/104988222/dc331664-43c2-4e62-9ab9-9c40eeed79f8)
![Import2](https://github.com/dotnet/machinelearning/assets/104988222/f6d53f15-1a4b-4912-b709-b68c6b740934)

**Additional context**
A similar error was reported previously for version 1.4 (issues #3919, #3764 and more).  However, despite building for x64 only, and setting the import settings for all the .DLL's as x64 only (unticking x86, see in second screenshot above) does not change the result.
Trying all combos of "API compatibility Level" and "Scripting Backend" does not change the outcome.

Publishing the C# project into single EXE with embedded model .zip is possible, but still wanting to explore Unity native option (no need for remote application calls).

Full disclosure - my C# knowledge is self taught, and from a Unity perspective.  However I am trying to expand my understanding of the .NET ecosystem in general.  Apologies if I'm missing key fundamentals.

P.S. Yes, I spelt SentimentModel with a capital 'O'.  I fat fingered it, and am living with it for now - please forgive me...

**Appendix A:**
[Plugins.zip](https://github.com/dotnet/machinelearning/files/11832242/Plugins.zip)
Microsoft.Bcl.AsyncInterfaces (2.0.1)
Microsoft.ML (2.0.1)
Microsoft.ML.Core (2.0.1)
Microsoft.ML.CpuMath (2.0.1)
Microsoft.ML.Data (2.0.1)
Microsoft.ML.DataView (2.0.1)
Microsoft.ML.KMeansClustering (2.0.1)
Microsoft.ML.PCA (2.0.1)
Microsoft.ML.StandardTrainers (2.0.1)
Microsoft.ML.Transforms (2.0.1)
System.Collections.Immutable (7.0.0)
System.Runtime.CompilerServices.Unsafe (7.0.0 Preview)
System.Text.Encodings.Web (8.0.0 preview)
System.Text.Json (8.0.0 preview)
System.Threading.Channels (8.0.0 preview)

**Appendix B:**
Snippet of code used to call SentimentModel:
```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using MLCoreTest;

public class MLTest : MonoBehaviour
{
    [ContextMenu("Test the Model")]
    private void Test()
    {
        SentimentMOdel.ModelInput _model = new SentimentMOdel.ModelInput()
        {
            Col0 = "I had a whale of a time",
        };

        Debug.Log($"{SentimentMOdel.Predict(_model).PredictedLabel}");
    }
}
```

Any assistance is greatly appreciated.  If ML.Net just isn't usable with Unity (any version), any pointers for alternative solutions would be greatly appreciated.

Many thanks,

Michael

[Edited 22/06/2023: Removing unnecessary code]

**Comment by luisquintanilla** [comment]
@Mike-CineonTraining thanks for reaching out. I noticed in Appendix A that CPUMathNative.dll isn't there. You can find that in the `Microsoft.ML` [NuGet package](https://www.nuget.org/api/v2/package/Microsoft.ML/2.0.1). Can you try copying it alongside your other DLLs and report back if you're still having issues.
