### ISSUE TITLE
Q: Workflow

### ISSUE THREAD

**Issue by lefig** [dotnet/machinelearning#676]
Hi,

Not an issue defect to report, but more of an expression of appreciation for an excellent project.

In addition, I have a query in terms of process...

My csv files tend to be large and the fields likely to be changing on a frequent basis. However, when building models its just so time intensive having to update the class definitions and keep in sync.

Does anyone have any suggestions please to optimise this process. Can this be done, perhaps by automated template generation. Alternatively break cv files with many fields down to more granular files. I don't know so I would welcome your thoughts.

Ta
Fig

**Comment by Zruty0** [comment]
One thing we are planning to do is to have a 'data file analyzer' that will scan a header of the file and spit out the class definition for reading this file. This would probably serve your purpose of quickly adapting to new file headers.

Another possibility is to read features not as scalars, but as vectors. In this case, you need to update the vector sizes only for your input class definition:
```c#
public class MyData 
{
    [Column("0")]
    public float Label;

    [Column("1-134")]
    public float[] Features; // 134 features in this file.
}
```

**Comment by lefig** [comment]
This sounds very promising and most interesting. Thank you for sharing.

What would be ideal is to be able (dynamically) to parse the headers of a csv file and by reflection build a model. Is there a way to create a model class without having to use the column attribute? 

In other words, at run-time to add feature/labels without having to declare the class structures in advance....

**Comment by Zruty0** [comment]
Internally, we do not rely on class declarations to define schema, so it's definitely possible to have runtime-defined schema only.

In reality, it proved to be rather cumbersome though. 
If you cannot achieve the goal with [schema comprehension](https://github.com/dotnet/machinelearning/blob/master/docs/code/SchemaComprehension.md), then I guess you would have to write your own loader...
