### ISSUE TITLE
Samples for trainers

### ISSUE THREAD

**Issue by ddobric** [dotnet/machinelearning#68]
Looking for samples for supported trainers:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers?view=ml-dotnet

Thanks

**Comment by glebuk** [comment]
Damir (@ddobric),
While we don't yet have a code sample written for every learner, you can start with [scenario samples](https://github.com/dotnet/machinelearning/tree/c023727b76970ab913ec1ce38276508835c17bcf/test/Microsoft.ML.Tests/Scenarios) and replace the learner/estimator/trainer with those of interest.
We plan to add a much more comprehensive documentation soon.
Regards,

**Comment by abgoswam** [comment]
DRI RESPONSE: @sfilipi  can you help us and point to the place in documentation where we have samples for trainers?

**Comment by sfilipi** [comment]
@abgoswam we are building more of those. The cookbook examples are probably the best place to look at now. There are some samples in the [machinelearning-samples repo](https://github.com/dotnet/machinelearning-samples), and we'll place per-trainer examples in the [ml.net samples folder](https://github.com/dotnet/machinelearning/tree/master/docs/samples/Microsoft.ML.Samples)

**Comment by shauheen** [comment]
Hi @ddobric , please take a look at the samples repo and the updated documentation and if you have other samples in mind please feel free to open another issue or update this one.
