### ISSUE TITLE
Predict similar scheme

### ISSUE THREAD

**Issue by adamshakhabov** [dotnet/machinelearning#680]
_Sorry for my English._

### Dataset

There is dataset which contains files which describe scheme:

sample #1.txt
```
3103686, 2590304, 2022230, 838696
5530360, 1916721, 2022230, 430823
3103686, 3807071, 2022230, 430823
5705725, 4022485, 2022230, 975943
8043677, 3697167, 2022230, 430823
8043677, 2761756, 2022230, 430823
```

sample #2.txt
```
2994926, 3072910, 2022230, 1752477
7396944, 3072911, 2022230, 1752476
2994926, 1981531, 5573177, 558310

```
Each row is rectangle element (on scheme) feature vector (x, y, width, height).

### Data to predict

I need train a model which can predict for such input data

input.txt
```
3313321, 3259181, 2022230, 558310
7039277, 3454335, 2022230, 558310
5253403, 4207799, 2022231, 558310
4073770, 2445894, 2022230, 558310
6569923, 2445894, 2022230, 558310
```

similar scheme.

For example, in the above example for input.txt prediction would be quite if model say that sample #1 most similar for input scheme.

### Question

Which algorithm from ML.NET should I use to solve my task? Of cause I do not expect complete solution, just put me right way.
I have a little bit sub-questions to clarify my problem:

- How preparing dataset to train: by feature describe or matrix?

- Before some classifier should I clustering data?

**Comment by Ivanidzo4ka** [comment]
What exactly you want to predict? I'm just looking on your example and I can't connect how sample 1 and sample 2 are connected.
You have your rectangles, what you want to predict from them? Another rectangles? Can you explain your "similar scheme" meaning?

**Comment by adamshakhabov** [comment]
@Ivanidzo4ka, I wanna for input data predict scheme which has most similar layout based its elements, i.e. their elements locations.

**Comment by Ivanidzo4ka** [comment]
Sorry, but I still don't get it.
What is similar layout mean? I mean how you mathematically define similarity of layout? And what is layout? (I can probably draw your rectangles in examples, but considering how big your coordinates, and I don't understand their relationship it feels like potential waste of time for me...)

And is sample 1 your input data and sample 2 your expected results? In this case how exactly you move from 6 examples to 3 prediction? Is it sliding windows with size 4 or you pair your examples first and second, third and fourth, fifth and six?

**Comment by adamshakhabov** [comment]
- Actually **layout is presentation slide**. I want to parse (obtain the necessary feature) from much presentation slides and send to train. And then when user create his own slide and send it to predict, model try say whether such slide created in the last time.

-  **sample 1 and sample 2 data** to train.

- **sample 1 is not 6 examples**. It is one object. Just I do not know how define one object via few objects.

> how you mathematically define similarity of layout

I do not know. I need help to indicate which branch of mathematics can help me.

**Comment by Ivanidzo4ka** [comment]
I can be wrong, but from your description it looks like you just need to implement huge hashset on List of ints or just DB in which you can store all your previous slides. 

If I'm wrong, can you give me example of outputs for your sample 1 and sample 2?

**Comment by adamshakhabov** [comment]
@ivanbasov, attached file has input and output for scheme1
[input-output.pptx](https://github.com/dotnet/machinelearning/files/2291606/input-output.pptx)

**Comment by Ivanidzo4ka** [comment]
Well, thank you, but I don't think it help me in any way, I just don't see any pattern, between input and output and I would suggest you to formulate math behind similarity first.

**Comment by adamshakhabov** [comment]
@Ivanidzo4ka, you helped me. Thanks. Now I see, that my first step: find/define similarity formula.

I thought that I just have to describe my scheme via few object and then some algorithm itself define which similarity formula to apply to specified data.
