### ISSUE TITLE
[Tokenizers] BPE Optional Arguments Required

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#6828]
**System Information (please complete the following information):**
 - OS & Version: Windows 11
 - ML.NET Version: 0.21.0-preview.23266.6
 - .NET Version: .NET 7

**Describe the bug**

The `mergeFile` is set as an optional argument in the BPE model class. 

https://github.com/dotnet/machinelearning/blob/09b80f8a08340dc7d79ac75e13c722313f0845eb/src/Microsoft.ML.Tokenizers/Model/BPE.cs#L91-L138

However, when I initialize the BPE model without a merges file, it throws an error. 

```csharp
var tokenizer = new Tokenizer(new Bpe(@"C:\Dev\torchsharp-playground\assets\vocab\e5-small-v2-vocab.txt"));
```

```text
Error: (1,35): error CS7036: There is no argument given that corresponds to the required parameter 'mergesFile' of 'Bpe.Bpe(string, string?, string?, string?, string?)'
```

Vocab file used: [https://huggingface.co/intfloat/e5-small-v2/raw/main/vocab.txt](https://huggingface.co/intfloat/e5-small-v2/raw/main/vocab.txt)

**Expected behavior**
New tokenizer is created using only vocab file.

**Comment by GeorgeS2019** [comment]
@michaelgsharp
Please add deep-learning label to all TorchSharp/HuggingFace issues
![image](https://github.com/dotnet/machinelearning/assets/49812372/c4a04e8a-73ef-4046-9948-6db34d528b9d)

**Comment by tarekgh** [comment]
@luisquintanilla https://huggingface.co/intfloat/e5-small-v2 is using WordPiece tokenizer and not BPE. I believe we have another issue tracking adding this tokenizer (as part of Berta model) so I am closing this issue. Let me know if you want to re-activate for any reason.

```
  "model": {
    "type": "WordPiece",
```
