### ISSUE TITLE
LightGBM says Microsoft.ML.LightGbm is wrong

### ISSUE THREAD

**Issue by andrewkittredge** [dotnet/machinelearning#6861]
Is this still accurate?  https://github.com/microsoft/LightGBM/issues/5535#issuecomment-1275362917

**Comment by LittleLittleCloud** [comment]
`Microsoft.ML.LightGbm` still targets to LightGBM `2.*`. It's on our roadmap to upgrade `Microsoft.ML.LightGBM` package to support the latest LightGBM though

**Comment by michaelgsharp** [comment]
Thats correct. We can close this issue.
