### ISSUE TITLE
French Named Entity Recognizer

### ISSUE THREAD

**Issue by anrouxel** [dotnet/machinelearning#6883]
Hello,
**Is your feature request related to a problem? Please describe.**
My problem is that the Named Entity Recognizer doesn't support French. And, I'm working on a student project which is the creation of a medical application. And I need to extract information from a prescription (stored in a string) such as the name of the medicine.

**Describe the solution you'd like**
The solution would be for "Named Entity Recognizer" to support French.

**Describe alternatives you've considered**

**Additional context**

Best Regards,

anrouxel

**Comment by luisquintanilla** [comment]
Hi @anrouxel,

Thanks for your suggestion. The model currently only supports English and there are no immediate plans to support other languages in the short-term.
