### ISSUE TITLE
Publish ML.NET 3.0 API Documentation 

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#6902]
Latest API doc version is 2.0. Add 3.0

https://learn.microsoft.com/en-us/dotnet/api/microsoft.ml.textcatalog.applywordembedding?view=ml-dotnet

![image](https://github.com/dotnet/machinelearning/assets/46974588/045f66c0-84f9-4680-ab23-56fe145b4fd4)

**Comment by michaelgsharp** [comment]
This is done.
