### ISSUE TITLE
ML .Net integration with ef core

### ISSUE THREAD

**Issue by SyntaxEvg** [dotnet/machinelearning#6931]
ML .Net integration with ef core for data generation based on msSql, and building models, так как ваш подход с ado net выдает иногда ошибки, котоые котоые котоые не пропустить не исправить, How do you convert what is the system or how do you know about dnSpy?
My friend, how to realize the data of the ef core and train the model, based on this Each connection is more than 10 ml per line

**Comment by SyntaxEvg** [comment]
Stack  Error
=============
   System.Data.SqlClient.SqlBuffer.get_String()
   System.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   Microsoft.ML.Data.DatabaseLoader.Cursor.<>c__DisplayClass38_0.<CreateStringGetterDelegate>b__0(ReadOnlyMemory`1& value)
   Microsoft.ML.Transforms.ValueToKeyMappingTransformer.Trainer.ImplOne`1.ProcessRow()
    Microsoft.ML.Transforms.ValueToKeyMappingTransformer.Train(IHostEnvironment env, IChannel ch, ColInfo[] infos, IDataView keyData, ColumnOptionsBase[] columns, IDataView trainingData, Boolean autoConvert)
   в Microsoft.ML.Transforms.ValueToKeyMappingTransformer..ctor(IHostEnvironment env, IDataView input, ColumnOptionsBase[] columns, IDataView keyData, Boolean autoConvert)
   Microsoft.ML.Transforms.ValueToKeyMappingEstimator.Fit(IDataView input)
   Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   Microsoft.ML.Transforms.OneHotEncodingTransformer..ctor(ValueToKeyMappingEstimator term, IEstimator`1 toVector, IDataView input)
   Microsoft.ML.Transforms.OneHotEncodingEstimator.Fit(IDataView input)
   Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)

**Comment by michaelgsharp** [comment]
Can you please provide a sample project that reproduces your error?
