### ISSUE TITLE
converted onnx model takes much more load time and memory size.

### ISSUE THREAD

**Issue by NofAssiri** [dotnet/machinelearning#6932]
### System information
- processor:
    12th Gen Intel Core i7-12800HX
- chip Type:
    AMD Software: Pro Edition 0x73E1 VRAM 8GB
- Ram:
    32GB

- **OS version/distro**:
- windows  : 11 pro 64-bit build 22621

- **.NET Version (eg., dotnet --info)**: 
  .NET8 

### Issue
i have ml.net model of size 47MB (zipped) it loads in 1 second and takes about 100, 150MB of memory, but when i convert it to onnx format using ConvertToOnnx function and empty list of input data type, 
now the model size 112MB, loads in 6 seconds and takes about 2GB of memory 

- **What did you do?**
- convert it to onnx format using ConvertToOnnx function and empty list of input data type
- **What happened?**
- the model size 112MB, loads in 6 seconds and takes about 2GB of memory
- **What did you expect?**
- expected the onnx model to take less memory and load time than the ml.net model

### Source code / logs
conversion code 
var dummy = new List<InputData>();
var dummyData = _ctx.Data.LoadFromEnumerable(dummy);
using (var onnx = File.Open("C:\\models\\onnModel.onnx", FileMode.OpenOrCreate, FileAccess.ReadWrite))
{
    _ctx.Model.ConvertToOnnx(transformer, dummyData, onnx);
}

load code
var ctx =new MLContext();
var model = ctx.transform.ApplyOnnxModel("C:\\models\\onnxModel.onnx");

**Comment by michaelgsharp** [comment]
Are you able to upload the model/data/repro project so we can take a look at it?
