### ISSUE TITLE
Confusion matrices didn't have enough matrices

### ISSUE THREAD

**Issue by ArieJones** [dotnet/machinelearning#694]
We are running into this error when we try to do a cross validation of a classifier.. 
```
new StochasticDualCoordinateAscentClassifier()
                {
                    Caching = CachingOptions.Memory,
                    MaxIterations = 100,
                    LossFunction = new SmoothedHingeLossSDCAClassificationLossFunction(),
                    NumThreads = System.Environment.ProcessorCount - 1  //We use one less than the number of processors available
                }

```
System.InvalidOperationException: 'Confusion matrices didn't have enough matrices.'

This seems to be thrown only at the very end.. because it seems to be rolling through just fine ..outputting the below on each iteration.. 

`Not training a calibrator because it is not needed.
Automatically adding a MinMax normalization transform, use 'norm=Warn' or 'norm=No' to turn this behavior off.
Using 3 threads to train.
Automatically choosing a check frequency of 3.
Auto-tuning parameters: L2 = 8.341675E-05.
Auto-tuning parameters: L1Threshold (L1/L2) = 1.
Using best model from iteration 33.`

Is there something that we are doing incorrectly such as we need to specify the number of folds to use? 

Thanks,
AJ

**Comment by Ivanidzo4ka** [comment]
Are you just do new CrossValidator.CrossValidate<TIn,TOut>(pipeline)?
Our current cross validator is a bit dumb, and don't check type of your trainer, so you need to tell him which kind of task you use.
For your exact case, you run multiclassification problem, 
```
new CrossValidator() {Kind = MacroUtilsTrainerKinds.SignatureMultiClassClassifierTrainer}.CrossValidate<TIn, TOut>(pipeline)?
```

if it's not the case, we need some more information to give you answer, for example your pipeline code.

**Comment by ArieJones** [comment]
We are using something like this 
`
        public CrossValidationOutput<TInput, TOutput> Evaluate(MacroUtilsTrainerKinds kindofTrainer, int numberoffolds)
        {
            
            var cv = new CrossValidator() { Kind = kindofTrainer, NumFolds = numberoffolds }.CrossValidate<TInput, TOutput>(_pipeline);
            return cv;
        }`


we're currently using K=10

AJ

**Comment by ArieJones** [comment]
Sorry checking back in with this one as it really doesn't make any sense that we are failing...our pipeline is fairly simple 


``` var pipeline = new LearningPipeline();
            pipeline
                .Append(trainingData)
                .Append(new Dictionarizer("Label"));

            pipeline.Append(new CategoricalHashOneHotVectorizer(nameof(DataInput.Features)));
            pipeline.Append(new ColumnConcatenator("Features", nameof(DataInput.Features)));

            pipeline
              .Append(algo)
              .Append(new PredictedLabelColumnOriginalValueConverter { PredictedLabelColumn = "PredictedLabel" });

            return pipeline;```

Would this be related to an uneven distribution of classes(aka Labels)? 


It seems to process through every time and gets to the very last one and then throws this error.

Is there some way in which we could turn this into a warning instead? 

Thanks!

**Comment by Ivanidzo4ka** [comment]
DRI RESPONSE: This is question about our legacy API. 
I intent to close it since we don't plan to support our legacy API.
If it's still occurs with our new API, I suggest to open new issue, and provide a bit more information, so we can debug it on our side.
