### ISSUE TITLE
Simplify Pipeline Initalization with Append() that returns the pipeline

### ISSUE THREAD

**Issue by glebuk** [dotnet/machinelearning#7]
Issue:
Currently we have to use the pipeline instance to append additional items to the pipeline. It looks something like this:
```csharp
var pipeline = new LearningPipeline();
pipeline.Add(new TextLoader<SentimentData>(dataPath, separator: ","));
pipeline.Add(new TextFeaturizer("Features", "SentimentText"));
```
We can add the ability to add a pipeline item in a fluent fashion.  The benefit would be reduction of typing and  cleaner API.  
This would require pipeline to add the following method:
```csharp
public LearningPipeline Append(ILearningPipelineItem item);
```
The user code will look like this:
```csharp
var pipeline = new LearningPipeline()
   .Append(new TextLoader<SentimentData>(dataPath, separator: ","))
   .Append(new TextFeaturizer("Features", "SentimentText"));
```
(optional) with extension methods, this can be simplified even further to:
```csharp
var pipeline = new LearningPipeline()
   .AddTextLoader<SentimentData>(dataPath, separator: ",")
   .AddTextFeaturizer("Features", "SentimentText");
```

**Comment by glebuk** [comment]
It would be also good to make the LearningPipeline a List<ILiearningPipelineItem>  instead of Collection. This way it would be easy to manipulate the pipeline by adding and replacing items in the arbitrary location.
Example of the scenario is sweep of different learners.

**Comment by shauheen** [comment]
closing this issue as the PR has already merged and the API will also be updated in the next release.
