### ISSUE TITLE
ML.Net and Azure ML Relationship

### ISSUE THREAD

**Issue by voltcode** [dotnet/machinelearning#70]
It would be beneficial for potential users to understand the relationship between ml.net and azure ML. 

Is ml.net the lib behind azure ml? Is ml.net going to be a block inside azure ml? How do those things.work together, is it going to be possible to seamlessly move models, flows, etc between the two?

**Comment by sfilipi** [comment]
@GalOshri is there any plans we can share about this?

**Comment by codemzs** [comment]
Currently ML.NET is not a backend for Azure ML.
