### ISSUE TITLE
Can I get an example of simple naive bayes based on ML.NET?

### ISSUE THREAD

**Issue by JeataekRyu** [dotnet/machinelearning#702]
I would like to use NaiveBayesClassifier instead of StochasticDualCoordinateAscentBinaryClassifier, but the example [here ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.naivebayesclassifier?view=ml-dotnet)is not detailed and has limitations.

I want to do various tests with ML.NET, but there are not many examples, I can not find any explanation, and there are many restrictions on learning. In particular, I wonder how to useFeatureColumn, LabelColumn, and TrainingData.

I think it will be improvement in the future, but I want to know when the plan will be.

**Comment by Zruty0** [comment]
@justinormont @GalOshri do you think you can outline the documentation plans?

**Comment by JeataekRyu** [comment]
I have found a reference [here](https://www.codeproject.com/Articles/1249611/Machine-Learning-with-ML-Net-and-Csharp-VB-Net). I hope you will come together. Still, I hope they make more relevant examples in ML.NET.

**Comment by artidoro** [comment]
There is an ongoing effort to improve our documentation with new samples in the samples repo, as well as code references that should be directly available from the ML.NET documentation website.

We are still in an early stage of the project, and started by focusing on stabilizing the API and main abstractions before investing more time in the documentation. But we definitely hear your concerns and are working on improving that.
