### ISSUE TITLE
The Operation will be canceled. The next steps may not contain expected logs.

### ISSUE THREAD

**Issue by tarekgh** [dotnet/machinelearning#7084]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=607853
Build error leg or test failing: Ubuntu_x64_cross_arm_Net60 / Ubuntu_x64_cross_arm_Net60 Debug_Build
Pull request: https://github.com/dotnet/machinelearning/pull/7080

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "The Operation will be canceled. The next steps may not contain expected logs.",
  "ErrorPattern": "The operation was canceled.",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=607853
**Error message validated:** `[The operation was canceled.`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 3/20/2024 12:02:04 AM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[610116](https://dev.azure.com/dnceng-public/public/_build/results?buildId=610116)|dotnet/machinelearning|Build Packages|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/610116/logs/258)||
|[609307](https://dev.azure.com/dnceng-public/public/_build/results?buildId=609307)|dotnet/machinelearning|Run Helix Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/609307/logs/330)|dotnet/machinelearning#7078|
|[607853](https://dev.azure.com/dnceng-public/public/_build/results?buildId=607853)|dotnet/machinelearning|Run Helix Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/607853/logs/440)|dotnet/machinelearning#7080|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|3|3|3|

**Comment by ericstj** [comment]
We shouldn't excuse timeouts.  Closing this as not-planned
