### ISSUE TITLE
Data preprocessing question

### ISSUE THREAD

**Issue by EduardoGarcias** [dotnet/machinelearning#709]
I'd like to ask a few question regarding data preprocessing in ML.NET.

1.) Is there a possibility of getting rid of **outliers** in case of input data?
2.) Is it possible to perform a **normalization** or **standardization** on the input data?

Thank you in advance.

**Comment by GalOshri** [comment]
1) One potential approach is to use one of the normalizers (see below), such as the [`MeanVarianceNormalizer`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.meanvariancenormalizer?view=ml-dotnet) and then the [`RowRangeFilter`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.rowrangefilter?view=ml-dotnet) to remove outliers. ML.NET has anomaly detectors (such as [PCA Anomaly Detector](https://github.com/dotnet/machinelearning/blob/60ae981223e83b174ecaaf528bd51814a6b0835c/src/Microsoft.ML.PCA/PcaTrainer.cs)) but they are not yet exposed through the existing APIs.

2) There are several normalizers that exist as transforms in ML.NET. The [`MinMaxNormalizer`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.minmaxnormalizer?view=ml-dotnet) is quite commonly used. Several other normalizers can be found [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms?view=ml-dotnet).

Let me know if this helps!

**Comment by justinormont** [comment]
To add to @GalOshri's suggestions, tree based learners handle outliers well, and don't require normalization. Try out the LightGBM and FastTree learners. 

Let us know if you find the current offering lacking in this area. Try out pre-cleaning your data and let us know if you're successful w/ external tools/technique. Feed back is always valuable

**Comment by codemzs** [comment]
Seems to have been answered by Gal.
