### ISSUE TITLE
Is there any way to make it the same as the vector created by the TextFeaturizer in ML.NET(ex. korean, chinese) unsupported language?

### ISSUE THREAD

**Issue by JeataekRyu** [dotnet/machinelearning#710]
pipeline.Add(New TextFeaturizer("Features", "Text"))

When  language(like Korean, Chinese) support is not available, it seems that i can create a learning model by using  my own vector(based on the language text). If possible, I hope that the relevant content is shared.

**Comment by GalOshri** [comment]
Could you explain what you mean by "create a learning model by using my own vector"? 

You should be able to bring your own numeric vector as input to the `LearningPipeline`. Additionally, note that the `TextFeaturizer` can run on Chinese text (although functionality is limited in the types of preprocessing that will work).

**Comment by codemzs** [comment]
Please refer to the examples here https://github.com/dotnet/machinelearning/tree/master/docs/samples/Microsoft.ML.Samples/Dynamic
