### ISSUE TITLE
Perf benchmarks for optimization

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#711]
We want to have a couple ML scenarios to be used for tracking performance. We can use it to detect regression from build to build, as well as improve performance.

**Comment by justinormont** [comment]
The first round of performance (speed) benchmark are complete. Thanks to @Anipik for implementing the benchmarks. cc: @Zruty0, @GalOshri 

The benchmarks are chosen to be representative of user tasks and datasets. The components to test were chosen based on component usage number from internal-MSFT, what folks should be using, and tasks commonly performed. 

**Components covered** by these tests:
* **Learners**
  * LightGBM Multiclass & LightGBM Ranking
  * OVA w/ AveragedPerceptron 
  * SDCA Multiclass
  * FastTree Ranking
* **Transforms**
  * Convert
  * CategoricalTransform
  * TextTransform, and its sub-transforms: 
    * WordTokenizeTransform 
    * TextNormalizerTransform 
    * TermTransform 
    * NgramTransform 
    * CharTokenize 
    * GcnTransform 
    * DropColumnsTransform
  * Concat
  * WordEmbeddingsTransform
  * HashTransform
  * NAHandleTransform

Besides model training speed, **bulk prediction**/scoring speed is benchmarked for a text dataset w/ OVA-AveragedPerceptron, and a numeric ranking dataset w/ FastTree.

**Notably absent** components: _(reasonable choices for the next round of benchmarks)_
* **User scenarios** 
  * **Single prediction** (one instance at a time) latency & throughput, and time to first prediction
  * **Component-wise tests** to let devs focus on improving the speed of specific components
  * Very **small datasets** (where the overhead becomes apparent)
  * Scalability to **high number of classes** in multiclass classification (>=2000 classes)
  * **Disk read** & parse perf using a large dataset and disabled caching
  * Very **complex models** w/ heavy featurization and stacked models
  * **Regression** problems
  * **Categorical** datasets
* **Learners**
  * BinaryClassificationGamTrainer
  * SymSGD
  * K-means
  * _(wide variety as they hit this external repo)_
* **Transforms**
  * TrainScore for model stacking
  * PCATransform
  * WordHashBagTransform
  * CategoricalHashTransform
  * KeyToVector
  * BinNormalizer 
  * CountFeatureSelection/LearnerFeatureSelectionTransform/MutualInformationFeatureSelection
  * TreeFeaturizationTransform
  * MinMaxNormalizer/MeanVarNormalizer
  * LdaTransform
  * _(others as they hit this external repo)_


The focus of these benchmarks were on speed; we can also use them to track ML metrics like accuracy across builds. This would require a much larger set of datasets as to not over-fit our improvements towards a specific dataset.
