### ISSUE TITLE
LightGbm does not exist in namespace Microsoft.ML.Trainers

### ISSUE THREAD

**Issue by jiafatom** [dotnet/machinelearning#7117]
**System Information (please complete the following information):**
 - OS & Version: Windows 11
 - ML.NET Version: 3.0.1
 - .NET Version: .Net Framework 4.7.1

**Describe the bug**
Create a console app, in the cs file, try to 
using Microsoft.ML.Trainers.LightGbm;
However, it says LightGbm does not exist in namespace.
![lightgbm](https://github.com/dotnet/machinelearning/assets/30608893/86eb27bc-5131-4619-a4b8-a86aa78b9749)

Thanks.

**Comment by michaelgsharp** [comment]
Did you get the LightGBM nuget? https://www.nuget.org/packages/Microsoft.ML.LightGBM/

**Comment by jiafatom** [comment]
Thanks, got the nuget and worked.
