### ISSUE TITLE
Urgent need for a speech recognition samples

### ISSUE THREAD

**Issue by dfengpo** [dotnet/machinelearning#7119]
Urgent need for a speech recognition case.
Support understanding of environmental sounds, such as glass shattering sounds and knocking sounds.
Supports recognizing profanity, insulting others, and other speech sounds.
Support for identifying anger emotions.

**Comment by luisquintanilla** [comment]
Hi @dfengpo,

I would encourage you to take a look at this [comment](https://github.com/dotnet/machinelearning/issues/5054#issuecomment-618566492) for additional guidance. 

At this time, we have no plans to add speech recognition to ML.NET.
