### ISSUE TITLE
How to analyze speech by tensorflow.Net 

### ISSUE THREAD

**Issue by dfengpo** [dotnet/machinelearning#7120]
The limitation is part of the issue I guess, "we" state we do TF but do we.... 
Doing a search on the internet one can see nice samples using TF to analyse audio, text, price prediction housing  etc. The most interesting I guess as it allows comparison is if we would be able to demonstrate the [Iris sample](https://www.kaggle.com/pierrek20/multiclass-iris-prediction-with-tensorflow-keras)

_Originally posted by @PeterPann23 in https://github.com/dotnet/machinelearning/issues/3770#issuecomment-495492045_

**Comment by luisquintanilla** [comment]
Hi @dfengpo,

I would encourage you to take a look at the samples in the SciSharp repo which use TensorFlow.NET / Keras for additional guidance.

https://github.com/SciSharp/SciSharp-Stack-Examples
