### ISSUE TITLE
trying to carry out the 'ML.NET in ten minutes' project, but the script for creating the machine learning model does not work on my computer

### ISSUE THREAD

**Issue by NohaNLon** [dotnet/machinelearning#7121]
- ML.NET Version: [e.g. ML.NET v1.5.5]
 - .NET Version: [e.g. .NET 5.0]

**Describe the bug**
trying to carry out the 'ML.NET in ten minutes' project, but the script for creating the machine learning model does not work on my computer. I am using a Mac Book, and the error says that the required .NET is not installed in my computer (when I installed it five minutes prior).

**Comment by luisquintanilla** [comment]
Hi @NohaNLon,

I would encourage you to go through this tutorial. Specifically, take a look at the Install instructions which requires you to install .NET 6 SDK.

https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/install
