### ISSUE TITLE
How to gain progress when training for a long time？

### ISSUE THREAD

**Issue by Huochengyan** [dotnet/machinelearning#7124]
`ITransformer trainedModel = trainingPipeline.Fit(trainingData);`
How to obtain progress when the time is particularly long? I see many answers are before 2020. Is it currently supported in version 3.0.1? Or other methods can detect the required duration

**Comment by luisquintanilla** [comment]
Hi @Huochengyan,

One way to do this is to use the [`Log`](https://learn.microsoft.com/dotnet/api/microsoft.ml.mlcontext.log?view=ml-dotnet) event handler in MLContext. 

Here's an example for logging AutoML experiment progress. 

```csharp
// Log experiment trials
ctx.Log += (_, e) => {
    if (e.Source.Equals("AutoMLExperiment"))
    {
        Console.WriteLine(e.RawMessage);
    }
};
```
