### ISSUE TITLE
Regression FairLearn with AutoML?

### ISSUE THREAD

**Issue by 80LevelElf** [dotnet/machinelearning#7127]
At this moment we have a FairLearn extension method only for Binary Classification - SetBinaryClassificationMetricWithFairLearn method.

But during the code ML.net also have Regression Metric FairLearn support - https://github.com/dotnet/machinelearning/blob/main/src/Microsoft.ML.Fairlearn/Metrics/FairlearnMetricCatalog.cs

Is it possible to use FairLearn with regression via AutoML?

**Comment by LittleLittleCloud** [comment]
@80LevelElf Not at this timepoint, binary classification is the only supported scenario as for now

**Comment by 80LevelElf** [comment]
@LittleLittleCloud thanks for the answer (
