### ISSUE TITLE
Dll version of Microsoft.ML.OnnxRuntime.dll is 0.0.0.0

### ISSUE THREAD

**Issue by sportbilly21** [dotnet/machinelearning#7145]
**System Information (please complete the following information):**
 - OS & Version: either Windows 10 or 11 
 - ML.NET Version: versions 1.7 and 3.0
 - .NET Version: .netframework 4.7

**Describe the bug**
After building the solution the version of the Microsoft.ML.OnnxRuntime.dll is 0.0.0.0
This is not causing any issues if you are running the application through the Visual Studio.
But we create an installer with Wix for installation in production PC
When you install the software in Windows, the OS and wix due to the version of the dll being zero, they think the dll is corrupted and the installation cannot continue as the installer tries to recover the corrupted dll. 

We have a work around by changing the version of the above dll but from my understanding dlls should not have 0 as a version

![image](https://github.com/dotnet/machinelearning/assets/60097348/7e596786-3ff8-4750-acf1-51f2a168f3e9)

**Comment by sportbilly21** [comment]
Hi 
Any update regarding this?

**Comment by ericstj** [comment]
@sportbilly21 the correct repo for this issue is https://github.com/microsoft/onnxruntime.  Unfortunately I cannot transfer there, would you mind reopening in that repo?
