### ISSUE TITLE
Support special tokens in sentence piece bpe

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning#7158]
**Is your feature request related to a problem? Please describe.**
The phi-3 uses llama2 tokenizer with a few special tokens like `<|user|>` and `<|system|>`. But currently there is no way to add special tokens to sentence piece bpe (the llama 2 tokenizer) in mlnet
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by luisquintanilla** [comment]
Is this something that could be more widely applicable beyond SentencePiece? 

i.e. See template processing section in this link https://huggingface.co/docs/tokenizers/pipeline#all-together-a-bert-tokenizer-from-scratch
