### ISSUE TITLE
Special Tokens handling seems to be incorrect (at least in my scenario where I'm creating Command R+ tiktoken file from specification)

### ISSUE THREAD

**Issue by alkampfergit** [dotnet/machinelearning#7160]
Windows 11, .NET 8 version of library 0.22.0-preview.24271.1

**Describe the bug**
I'm trying to use tiktoken class to implement Cohere Command R+ tokenizer from the vocabulary file that cohere produces at https://storage.googleapis.com/cohere-public/tokenizers/command-r-plus.json

**To Reproduce**
you can find a playbook here https://github.com/alkampfergit/ai-playground/blob/develop/src/python/langchainVarious/Tokenization/dotnetcohere.dib Actually I downloaded the file, then extract vocabulary node and create tiktoken file, then parse the json file to grab special tokens.

**Expected behavior**
After I've parsed the commandR+ tokenizer specification if I tokenize a special token like <|YES_TOKEN|> it correctly recognize it as a a single token (upper part of the picture), but if I use in a sentence, like good<|YES_TOKEN|>good tokenization does not recognize the special token (lower part of the picture)

Since I've created the .tiktoken file from the specification it is possible that I've done something wrong, other tokens seems to be recognized just good.

**Screenshots, Code, Sample Projects**
![image](https://github.com/dotnet/machinelearning/assets/358545/43ab3c71-0d69-4687-a0bb-736413ad3cb2)

**Comment by ericstj** [comment]
@tarekgh could this be related to us pretokenizing the special tokens? https://github.com/dotnet/machinelearning/issues/7183

**Comment by tarekgh** [comment]
> could this be related to us pretokenizing the special tokens? https://github.com/dotnet/machinelearning/issues/7183

No, this is not related. I'll try to play with the generated vocab files and special tokens and then will report back.

**Comment by tarekgh** [comment]
@alkampfergit the problem you have is you created the tokenizer without passing the pre-tokenizer object. Try the following code:

```C#

// Note: this code is based on the latest tokenizer library version 0.22.0-preview.24378.1

// This is the regex pattern used with Cl100kBase vocab files but it is up to you to choose the pattern suites your purpose. 
string cl100kBaseRegexPattern = /*lang=regex*/ @"'(?i:[sdmt]|re|ve|ll)|(?>[^\r\n\p{L}\p{N}]?)\p{L}+|\p{N}{1,3}| ?(?>[^\s\p{L}\p{N}]+)[\r\n]*|\s*[\r\n]|\s+(?!\S)|\s+";

TiktokenTokenizer tokenizer = TiktokenTokenizer.Create(
    outputFilePath,
    new TiktokenPreTokenizer(new Regex(cl100kBaseRegexPattern, RegexOptions.Compiled), specialTokens), // <<<<< This is the important parameter you need to pass 
    normalizer: null,
    specialTokens);

Console.WriteLine(
    tokenizer.EncodeToIds("<|YES_TOKEN|>")
        .Select(x => x.ToString())
        .Aggregate((x, y) => x + " " + y));
```

This will print:

```
255002
```

I am closing the issue but feel free to send any question you still have.
