### ISSUE TITLE
Cannot cancel AutoML tasks when invoked via .Execute() Same as issue #6878

### ISSUE THREAD

**Issue by acrigney** [dotnet/machinelearning#7185]
**System Information (please complete the following information):**
 - OS & Version: [e.g. Windows 10] 
 - Win 10
 - ML.NET Version: [e.g. ML.NET v1.5.5]
 - All versions including and forward preview versions from versions 0.21.0
 - .NET Version: [e.g. .NET 8.0]

**Describe the bug**
Cancellation does not work even for async calls

**To Reproduce**
Please confirm this works now in your tests?
**Expected behavior**
Cancellation should work

**Screenshots, Code, Sample Projects**
I can provide in private

**Additional context**

**Comment by LittleLittleCloud** [comment]
# 6878

**Comment by LittleLittleCloud** [comment]
@acrigney Which trainer are you using. If you are using one of native trainer (like lgbm/lbfgs), the training won't be interrupt until the current trial completed.

**Comment by acrigney** [comment]
Great yes I found that in the comments in the code, thanks, I will close this now.

**Comment by acrigney** [comment]
Sorry you can close it.
