### ISSUE TITLE
Azure-SMP73 

### ISSUE THREAD

**Issue by smp73** [dotnet/machinelearning#7193]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ea015ee3-bdc4-07c3-18a3-3e91d70abb0e
* Version Independent ID: efbcc9a9-b025-0f0b-0035-6645ef433c0f
* Content: [IPredictionTransformer&lt;TModel&gt;.Model Property (Microsoft.ML)](https://learn.microsoft.com/en-gb/dotnet/api/microsoft.ml.ipredictiontransformer-1.model?view=ml-dotnet-1.1.0)
* Content Source: [dotnet/xml/Microsoft.ML/IPredictionTransformer`1.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML/IPredictionTransformer`1.xml)
* Service: **dotnet-ml-api**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by luisquintanilla** [comment]
Hi @smp73 

Can you please clarify what the ask is here?
