### ISSUE TITLE
Tokenizer.Decode returns a nullable string?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/machinelearning#7199]
Why does Tokenizer.Decode return `string?` rather than `string`? It looks like it's doing so to return `null` when invalid input is provided? Would it not be better to throw an exception in this case and always return non-null?

cc: @tarekgh

**Comment by tarekgh** [comment]
Looking more, all actual concrete implementations we have never return null except one case in Tiktoken. I agree to throw in this case and let Decode return a string instead of nullable string. I'll fix that.

**Comment by stephentoub** [comment]
What do the other implementations do when Decode is passed invalid input?

**Comment by tarekgh** [comment]
Here is example https://github.com/microsoft/Tokenizer/blob/0ac92ff362b58bc60699e7cc862865bd844430f1/Tokenizer_C%23/TokenizerLib/TikTokenizer.cs#L592. This just ignores unrecognized entries. It doesn't throw.

**Comment by stephentoub** [comment]
> This just ignores unrecognized entries. It doesn't throw.

Should it? Seems like we should be consistent across all of our implementations and with consistent recommendations to other implementations, that either invalid input should be skipped/ignored or invalid input should trigger throwing / OperationStatus.InvalidData?

**Comment by tarekgh** [comment]
All our implementations are consistent which ignore the invalid entry. The exception is the Tiktoken which is possible to return null. I didn't see any external implementation throws but this is worth double checking.

**Comment by tarekgh** [comment]
This is done
