### ISSUE TITLE
URL to sample is incorrect in readme.md

### ISSUE THREAD

**Issue by Drout** [dotnet/machinelearning#72]
The correct URL should be https://github.com/dotnet/machinelearning/blob/master/test/Microsoft.ML.Tests/Scenarios/SentimentPredictionTests.cs
 
it changed with the latest pull request but the readme.md hasn't been updated.

**Comment by glebuk** [comment]
Thanks, will fix soon.

**Comment by glebuk** [comment]
Fixed in PR #71
