### ISSUE TITLE
Need documentation to use ML .Net for personalize recommendation 

### ISSUE THREAD

**Issue by ks1990cn** [dotnet/machinelearning#7208]
Hi,

I am looking for documentation to use ML .Net for personalize recommendation with AWS in real time. Iam looking for AWS personalize alternative.

https://aws.amazon.com/blogs/architecture/architecting-near-real-time-personalized-recommendations-with-amazon-personalize/

**Comment by luisquintanilla** [comment]
Hi @ks1990cn,

Here is a tutorial that shows how to build recommender systems with ML.NET 

https://learn.microsoft.com/dotnet/machine-learning/tutorials/movie-recommendation
