### ISSUE TITLE
Main package has MKL dependency

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/machinelearning#721]
Microsoft.ML.Runtime.Data in the main package has WhiteningTransform which uses exports of MKL. If we want to segregate MKL users into Microsoft.ML.HalLearners then WhiteningTransform may need to move into an assembly in that package.

@eerhardt

**Comment by Ivanidzo4ka** [comment]
@eerhardt 
Only slightly related.
Why in our HalLearners package we have runtime folder with win-x64 only binaries?
Why it doesn't contain OSX and Linux binaries?
I've tried to look for documentation, but couldn't find anything.

**Comment by eerhardt** [comment]
>Why in our HalLearners package we have runtime folder with win-x64 only binaries?
Why it doesn't contain OSX and Linux binaries?

I looked at both https://www.nuget.org/packages/Microsoft.ML.HalLearners/0.4.0 and https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.ML.HalLearners/0.5.0-preview-26823-1 and they both have assets under `runtimes\linux-x64` and `runtimes\osx-x64`.

**Comment by Ivanidzo4ka** [comment]
DRI RESPONSE: Still valid. @artidoro  suppose to properly convert Whitening to Estimator/Transformer and maybe he can also move it.

**Comment by eerhardt** [comment]
This isn't fixed yet. The PR to fix it hasn't been merged yet.
