### ISSUE TITLE
CustomStopWordsRemoverTransform shouldn't hard-code its column name

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#725]
See the conversation here:
https://github.com/dotnet/machinelearning/pull/700/files/e30785ff454627c7b74e3b6873d70b9e6de28bdf#r212152727

![image](https://user-images.githubusercontent.com/8291187/44561816-2ff04b00-a71c-11e8-95bf-9f015ab9ce4f.png)

We should consider making the column name configurable instead of hard-coding the column name, which may be hiding an existing column.

/cc @codemzs

**Comment by Zruty0** [comment]
Frankly, this way of loading stopwords doesn't even make sense to me from the API perspective.
The transform allows FOUR separate ways of providing stopwords:
- a string array 
- a comma-separated string
- a column in the training data
- a 'Stopwords' column in the separate file, loaded by the provided loader.

I believe we should trim it down to ONE: a string array.

**Comment by Ivanidzo4ka** [comment]
Since I plan to work on conversion all text transform component to estimators, I'll assign this to myself, I need to touch it anyway.
