### ISSUE TITLE
Microsoft.ML.Tokenizers.Tests.TiktokenTests.TestTokenizerUsingExternalVocab failing to download gpt2.tiktoken

### ISSUE THREAD

**Issue by ericstj** [dotnet/machinelearning#7256]
### Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=823668

### Build leg reported

Microsoft.ML.Tokenizers.Tests.TiktokenTests.TestTokenizerUsingExternalVocab

### Pull Request

https://github.com/dotnet/machinelearning/pull/7252

### Known issue core information

Fill out the known issue JSON section by following the [step by step documentation on how to create a known issue](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step)

```json
 {
    "ErrorMessage" : ["Microsoft.ML.Tokenizers.Tests.TiktokenTests.TestTokenizerUsingExternalVocab", "File not found"],
    "BuildRetry": false,
    "ErrorPattern": "",
    "ExcludeConsoleLog": false
 }
 ```

 @dotnet/dnceng

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Additional information about the issue reported

It looks to me like this file no longer exists:
https://github.com/dotnet/machinelearning/blob/be1e428d41b5936903172855f7f30861ca7eb49a/test/Microsoft.ML.Tokenizers.Tests/TitokenTests.cs#L100C136-L100C149

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=823668
**Error message validated:** `[Microsoft.ML.Tokenizers.Tests.TiktokenTests.TestTokenizerUsingExternalVocab File not found`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 10/4/2024 12:37:23 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[823668](https://dev.azure.com/dnceng-public/public/_build/results?buildId=823668)|dotnet/machinelearning|[Microsoft.ML.Tokenizers.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=823668&view=ms.vss-test-web.build-test-results-tab&runId=21398774&resultId=101001)|dotnet/machinelearning#7252|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|1|

**Comment by tarekgh** [comment]
Should be fixed now by the PR https://github.com/dotnet/machinelearning/pull/7248.
