### ISSUE TITLE
How To use Phi-3.5-mini tokenizer

### ISSUE THREAD

**Issue by mehdihadeli** [dotnet/machinelearning#7257]
Hi,
How can I create a tokenizer based on [microsoft/Phi-3.5-mini-instruct](https://huggingface.co/microsoft/Phi-3.5-mini-instruct) model?
Should I load [tokenzier.model](https://huggingface.co/microsoft/Phi-3.5-mini-instruct/blob/main/tokenizer.model)?

I saw similar approach for llama in the [documentation](https://learn.microsoft.com/en-us/dotnet/machine-learning/whats-new/overview#additional-tokenizer-support):

``` csharp
// Create the Tokenizer.
string modelUrl = @"https://huggingface.co/hf-internal-testing/llama-llamaTokenizer/resolve/main/llamaTokenizer.model";
using Stream remoteStream = File.OpenRead(modelUrl);
Tokenizer llamaTokenizer = Tokenizer.CreateLlama(remoteStream);

```

**Comment by LittleLittleCloud** [comment]
phi-3.5-mini-instruct uses the same tokenizer as llama, so you can load the `tokenzier.model` using `LlamaTokenizer`

```
var modelPath= /path/to/tokenizer.model
var modelStream = File.OpenRead(modelPath);

var llamaTokenizer = LlamaTokenizer.Create(
            modelStream, ...);
```

**Comment by mehdihadeli** [comment]
thanks
