### ISSUE TITLE
Indirect references in ML.NET using Dependency Injection

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#726]
I've found 2 indirect references in our product that I'm not sure how to proceed on.

1. `LearnerFeatureSelectionTransform` depends on `SDCA`, but `ML.Transforms` doesn't have a reference to `ML.StandardLearners`.
2. The 'train' commands in `ML.Data` (`CV`, `Train`, `TrainTest`) all have a default Trainer of `AveragedPerceptron`.  but `AveragedPerceptron` lives in the `ML.StandardLearners` assembly. And `ML.StandardLearners` references `ML.Data`, but this dependency is in the wrong order.

A couple of options:
1. Change these parameters to be 'user required', i.e. they don't have a default and fail if you didn't specify it.
2. Move some code around so the dependencies line up correctly.  For example, we could move our 'train' commands out of `ML.Data` and into a higher assembly.
3. For (1) above, we could move `LearnerFeatureSelectionTransform` into `ML.StandardLearners` instead of being in `ML.Transforms`. Or we could add the dependency from `ML.Transforms` to ML.StandardLearners.
4. Continue to use Dependency Injection and just assume/hope the component is there at runtime.

From an internal conversation with @TomFinley, we are thinking of taking option (1) above - make these parameters required and not have a default.

Thoughts?

cc @TomFinley @Zruty0 @codemzs @Ivanidzo4ka

**Comment by codemzs** [comment]
Closing this issue as I believe this has been addressed with the stable API.
