### ISSUE TITLE
Microsoft.ML.OnnxTransformer asking for wrong Microsoft.ML.OnnxRuntime version

### ISSUE THREAD

**Issue by sportbilly21** [dotnet/machinelearning#7297]
**System Information (please complete the following information):**
 - OS & Version: 10
 - ML.NET Version: 3.01
 - ML.OnnxTransformer 3.01
 - .NET Version: Framework 4.7

**Describe the bug**
I have updated all nuget packages to the latest versions, include Microsoft.ML.OnnxRuntime.Gpu which I now you are not managing version of the package is 1.20 and the version of the produced dll of that package Microsoft.ML.OnnxRuntime is again 1.20.
When I running a unit test I am getting the following error System.IO.FileLoadException: Could not load file or assembly 'Microsoft.ML.OnnxRuntime, Version=0.0.0.0, which comes from the Microsoft.ML.OnnxTransformer nuget package.
 Microsoft.ML.OnnxRuntime.Gpu, before version 1.19, was producing the Microsoft.ML.OnnxRuntime.dll with the version 0.0.0.0 which was a bug from their side, This has been corrected from their side and now it updates the version in the dll. 
The issue is that ML.OnnxTransforme still needs the 0.0.0.0 so it cannot be used with any of the newests  versions of Microsoft.ML.OnnxRuntime.Gpu 
Can you please advise?

**Screenshots, Code, Sample Projects**
![Image](https://github.com/user-attachments/assets/e5115309-5be6-45e1-865c-35c832198e9a)

Many thanks
Vasilis

**Comment by ericstj** [comment]
We reference an older version of the package so as not to require the latest.   So long as their latest package is newer it should work.  On .NET Framework you'd need a bindingRedirect -- which is pretty typical when using nuget packages on .NETFramework.  Normally build tools will provide auto-generated bindingRedirects in this case.

Let us know if you tried this and it still didn't work.

**Comment by sportbilly21** [comment]
Many thanks, for have created the bindingRedicts and is it working. For some weird reason in my solution they are not auto-generated.
