### ISSUE TITLE
Can no longer subclass DataFrameColumn due to internal abstract GetSortIndices method

### ISSUE THREAD

**Issue by charliebone** [dotnet/machinelearning#7323]
Hello,

I'm glad v0.22 is published with some fixes I have been waiting for. However, there is now an issue. 

I inherit from the DataFrameColumn class to build my own DataFrameColumn implementation. The reasons aren't super important but it's used allow for some implementations of extension methods on the DataFrameColumn class that do computations that require certain data types. The class is a public abstract class, which indicated to me as a user of the ml.net library it was fair game to override and to continue writing extension methods that all were based on the DataFrameColumn abstract base class.

Now, we have an internal abstract method present in the base class, making overriding impossible even though every other abstract method and property is either public or protected: https://github.com/dotnet/machinelearning/blob/d4bc05db154b1e3c8513e52b9c476f83b49d4048/src/Microsoft.Data.Analysis/DataFrameColumn.cs#L463

Is there anything that can be done to remedy this?

**Comment by asmirnov82** [comment]
Hi @charliebone. I implemented fix for this. 
You may try to inherit from the PrimitiveDataFrameColumn<T> class as a workaround, if it's possible in your scenario (though T should be a value type)

**Comment by charliebone** [comment]
Hi @asmirnov82, thank you for the prompt reply and fix! Any idea when it'll make it out into the wild?

I have considered inheriting from PrimitiveDataFrame instead, and perhaps I'll go that route in the interim. Thanks again for the fast fix!

**Comment by asmirnov82** [comment]
@charliebone, I created PR  #7331 for including these changes to the 4.0.1 release. I don't have any insights when it may be shipped to production, vut according to previouse years I expect it to happen in the nearest couple of months
