### ISSUE TITLE
NelderMeadSweeper has unmet dependency to "ldrandpl" sweeper

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#733]
The NelderMeadSweeper has a default `FirstBatchSweeper` set to `ldrandpl`.  However, that component is not found in the `dotnet/machinelearning` repo.

https://github.com/dotnet/machinelearning/blob/5e08fa1ea7bfb54f28ed0815cb6413e0068e6dd1/src/Microsoft.ML.Sweeper/Algorithms/NelderMead.cs#L27-L28

https://github.com/dotnet/machinelearning/search?q=ldrandpl&unscoped_q=ldrandpl -- only returns a single result - the reference from NelderMeadSweeper.

We should find another default for this sweeper, or move the `ldrandpl` component to `dotnet/machinelearning`.

/cc @TomFinley

**Comment by codemzs** [comment]
We don;t have sweepers in the repo as of today.
