### ISSUE TITLE
How to get auto tuned parameters to train final model

### ISSUE THREAD

**Issue by rauhs** [dotnet/machinelearning#736]
Hi,

after training many models on time series data (multi class pred) I'd like to train a final model on all available data (including the test set).

Specifically I use SDCA multi class trainers and set some parameters while leaving other to "auto-tune".

Example output:

```
Automatically choosing a check frequency of 4.
Auto-tuning parameters: maxIterations = 104.
Auto-tuning parameters: L2 = 2.719283E-05.
Auto-tuning parameters: L1Threshold (L1/L2) = 0.25.
Using best model from iteration 104.
```

How would I train my final model? I'd like to set the iterations to 104 and the other hyper parameters to their respective values. Is there an API to get the estimated/used parameters?

I can't just read stdout and manually train the model since I dynamically train ML models on our customer's servers.

Thanks for all work!

**Comment by codemzs** [comment]
We will soon have AutoML in the master branch that will allow you to auto train.
