### ISSUE TITLE
Enable specifying order of channels in Pixel Extractor

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#746]
TensorFlow models can have different ordering of the channels. ML.NET currently only supports specifying channel first/last, but not the order.

**Comment by Zruty0** [comment]
Let's wait until #753 is in, then do it.

**Comment by shauheen** [comment]
@yaeldekel can you please provide more details on the solution so that someone can take this. Thanks :)

**Comment by Ivanidzo4ka** [comment]
Closed in #https://github.com/dotnet/machinelearning/pull/2602
