### ISSUE TITLE
Investigate using text and sparse input in TensorFlow

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#747]
We should know how TF handles text inputs, and whether it supports sparse inputs.

**Comment by zeahmed** [comment]
The `TermlookupTransform` does not seem to operate on vectors while `TermTransform` outputs Key type which cannot be used in `TensorflowTransform` currently.

**Comment by asthana86** [comment]
This issue currently blocks the UI tooling for ML.NET. Can this issue be addressed sooner to unblock tooling work.

**Comment by zeahmed** [comment]
@asthana86, This issue cannot be closed currently because it requires a few more features to be developed in ML.Net like padding and trimming transform. Can you please let me know how this is blocking tooling work? I may be helpful in unblocking you then.

**Comment by zeahmed** [comment]
The following example show use-cases for text classification and string input/output. Most of the point raised in this issues are covered now. I am closing it.

https://github.com/dotnet/machinelearning/blob/51b10fc6a004b08b3a07d046db10fa277a8cffac/docs/samples/Microsoft.ML.Samples/Dynamic/TensorFlow/TextClassification.cs#L8

https://github.com/dotnet/machinelearning/blob/51b10fc6a004b08b3a07d046db10fa277a8cffac/test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs#L1088
