### ISSUE TITLE
Move LearningPipeline API to a legacy namespace

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#756]
In order to free up `Microsoft.ML.*` names, we should move the auto-generated components into a different namespace, like `Microsoft.ML.Legacy`.

We also plan to deprecate the LearningPipeline API in 0.6 and remove it in 0.7.

**Comment by markusweimer** [comment]
When this gets addressed, it will be a breaking change. Shall we introduce a label for such issues and PRs? E.g. `breaking`?
