### ISSUE TITLE
Do not duplicate test output where there is no need to.

### ISSUE THREAD

**Issue by codemzs** [dotnet/machinelearning#758]
Often times Debug and Release builds have identical test outputs but we create two seperate baselines for that. We should avoid doing this and instead have a common baseline.

I believe @sfilipi was going to look into this?

**Comment by PKingZombieSpy** [comment]
Speaking of not duplicating, is issue #410 sufficient? Should we close this?

**Comment by Ivanidzo4ka** [comment]
#410 feel free to join discussion

**Comment by TomFinley** [comment]
Ah right. Somewhat ironic since the purpose of the issue is to avoid duplication. Ought we to close this one?

**Comment by codemzs** [comment]
I did have a feeling we had an issue for this but could not find it so I opened this just in case. Glad we found it and now I will close this one.
