### ISSUE TITLE
Rework schema and metadata

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#764]
We wanted to change the following about the schema:
- Formally make it a collection of 'columns'.
- Turn metadata into an instance of `IRow`.
- (maybe) introduce 'global metadata' in addition to 'column metadata'.
Below is the sketch of the new interface for schema: 

```c#
    public interface ISchema : IReadOnlyList<ISchemaColumn>
    {
        /// <summary>
        /// Dataset-wide metadata.
        /// </summary>
        IRow Metadata { get; }
    }

    public interface ISchemaColumn
    {
        /// <summary>
        /// The name of a column. This string should always be non-empty.
        /// </summary>
        string Name { get; }

        /// <summary>
        /// The type of the column.
        /// </summary>
        ColumnType Type { get; }

        /// <summary>
        /// The metadata for a column, or <c>null</c> if this column has no metadata.
        /// </summary>
        IRow Metadata { get; }
    }
```

In addition, we might want to rework `IRow` to not include the notion of 'Row ID' and 'active columns'. Maybe this calls for another interface, like `IMovingRow` that would include these.

/cc @TomFinley

**Comment by TomFinley** [comment]
Thanks @Zruty0 . As some exploratory work which feels like some years ago, I introduced this file:

https://github.com/dotnet/machinelearning/blob/98ac03b7e3210fab970b6983aee7f1fd4e021b7d/src/Microsoft.ML.Data/Data/IColumn.cs#L11

That might serve as a *loose* template for what we might want to do, and at least the work to do this should be aware of that.
