### ISSUE TITLE
Where is SentimentData defined?

### ISSUE THREAD

**Issue by zwcloud** [dotnet/machinelearning#77]
### System information

- **OS version/distro**: Win10
- **.NET Version (eg., dotnet --info)**:  2.1.200

### Issue

- **What did you do?**
I'm try the [examples](https://github.com/dotnet/machinelearning#examples) in the readme.

- **What happened?**

I installed Microsoft.ML package to a newly created .Net core console app.

And in the `Program.cs` file,

```
using System;
using Microsoft.ML;
using Microsoft.ML.Trainers;
using Microsoft.ML.Transforms;

namespace MLTry
{
    class Program
    {
        static void Main(string[] args)
        {
            var pipeline = new LearningPipeline();
            pipeline.Add(new TextLoader<SentimentData>(dataPath, separator: ","));
//...
```

It doesn't compile because `SentimentData` is not defined. And I searched for `SentimentData` in the repo but found nothing related.

- **What did you expect?**
Found the type `SentimentData`.

**Comment by nevoroman** [comment]
SentimentData is just an input dataset class. Create and use a class that fits your data.
You can find the full tutorial for this code sample at docs.microsoft.com (https://docs.microsoft.com/ru-ru/dotnet/machine-learning/tutorials/sentiment-analysis)
