### ISSUE TITLE
Address additional comments on the TensorFlowTransform PR

### ISSUE THREAD

**Issue by abgoswam** [dotnet/machinelearning#779]
Post merge, there are some additional comments that were added to the TensorFlowTransform PR #704 . 
Also, during the bug bash there was a request to update the documentation in a few places. 

Creating an issue to address these asks.  

Listing down the issues being addressed:

1.  Check for number of rows in unit test `TensorFlowTransformCifar` . [comment](https://github.com/dotnet/machinelearning/pull/704#discussion_r214075997)

2.  Fix `TensorFlowTransformCifarLearningPipelineTest` test. [comment](https://github.com/dotnet/machinelearning/pull/704#discussion_r214075714)

3. Update the TensorFlowTransform documentation to include a pointer to the nugets required for running the TensorFlowTransform.

**Comment by TomFinley** [comment]
> There are some additional comments that need to be addressed

Hi @abgoswam . Could we possibly expand on these? It is difficult to review your PR without knowing what the intent of it is.

More generally, it is generally a good idea for issues to be descriptive.

**Comment by abgoswam** [comment]
Hi @TomFinley . I have updated the description
