### ISSUE TITLE
Delete dead code related to AVX

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/machinelearning#780]
Some of the original code relating to AVX and SSE is dead and can be deleted including

* all of avx.cpp and avx.cs
* functions in thunk.cs that exposed avx.cpp functions, eg MatMulDX

I checked in TLC as well and the above were only used by code in NeuralNetworks/*, which will not migrate to ML.NET.

I also notice some functions in sse.cs seem dead eg MeanOfSrc

**Comment by jwood803** [comment]
@danmosemsft Is this still an issue? I looked through the code and I'm not seeing the dead code. I could just be missing it, though, but thought I would double check. 😄

**Comment by Anipik** [comment]
I removed all of the dead code from cpumath library
