### ISSUE TITLE
Documentation fixes for .5 release

### ISSUE THREAD

**Issue by JRAlexander** [dotnet/machinelearning#785]
List of api docs needing revision:
* [ ] - [LearningPipeline](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.learningpipeline?view=ml-dotnet&branch=smoke-test-preview)
* [ ] - [OnnxConverter.Convert(PredictionModel) Method](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.models.onnxconverter.convert?view=ml-dotnet&branch=smoke-test-preview#Microsoft_ML_Models_OnnxConverter_Convert_Microsoft_ML_PredictionModel_)

**Comment by Ivanidzo4ka** [comment]
Do you mind if I close this one? both of your links are dead.

**Comment by JRAlexander** [comment]
@Ivanidzo4ka, fine with me.
