### ISSUE TITLE
Differences in FastTreeBinaryClassifier between versions

### ISSUE THREAD

**Issue by JRAlexander** [dotnet/machinelearning#787]
In the Sentiment Analysis sample, when running 0.3.0 or  0.4.0 you get different results.

**Both results in the console are positive** for 0.4.0. The **first result should be negative** if it is supposed to be the same as 0.3.0, which I'd assume it would.

https://github.com/dotnet/docs/issues/7024

**Comment by codemzs** [comment]
Don't think this is applicable since we have the stable API now. please reopen if you still see this difference.
