### ISSUE TITLE
Add Date Transform/Vectorizers

### ISSUE THREAD

**Issue by dckorben** [dotnet/machinelearning#789]
It naturally makes sense to be able to take a date column and break it into the common sub components used in data analysis. As a very common workflow, it makes sense to build a vectorizer that does this internally effectively adding columns to the dataset from a single source date column which can then be Concatenator to the features.

I was thinking perhaps a vectorizer that takes a flags enum of various types of date transform (e.g. Day, Month, Year, Day of Week, Day of Year, Quarter, ISO Week of Year, etc). Obviously there are many ways to slice a date so maybe ultimately the best option is a builtin user defined formula transform which can solve this but Dates are a very common workflow as lots of real world data is actually time series.

**Comment by zeahmed** [comment]
Yes, there should be a DataTime Transform/Featurizer in ML.Net that will do the jobs listed above. Its simple to implement and open for contribution.

**Comment by Ivanidzo4ka** [comment]
If someone interested in doing this I would recommend to look on https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.ImageAnalytics/ImageLoaderTransform.cs as base example.

https://github.com/dotnet/machinelearning/blob/a285f8d5db15cd8bf77f3c03763bce16642f902b/src/Microsoft.ML.ImageAnalytics/ImageLoaderTransform.cs#L172
this code responsible for converting incoming data into output
other than that
`private readonly ImageType _imageType;`
should be changed to `private readonly ColumnType` and be set to `new VectorType(NumberType.Float,size_of_your_float_vector);`

**Comment by dckorben** [comment]
I will try to pick this up as it is still something I would use.

**Comment by najeeb-kazmi** [comment]
This issue was addressed in #4521
