### ISSUE TITLE
Add a C# API to ML.NET to extract input/output layers information from DNN models

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#791]
We need to add functionality to ML.NET to be able to extract information about the names/types/sizes of the input and output layers in a DNN model (this applies to both TensorFlow and ONNX models).

One possible way to do this is to add to ML.NET an auxiliary console application that can list that information given a model. Another option is to add a utility method that returns this information as a schema object that can be explored by the user.

**Comment by zeahmed** [comment]
Just for the information, there is also a [`saved_model_cli`](https://www.tensorflow.org/guide/saved_model) command in tensorflow that does this job.

I would like to have both; a utility method that is also exposed as CLI for both Tensorflow and ONNX. However, I would like to prefer CLI for quick inspection of models.

**Comment by markusweimer** [comment]
> However, I would prefer CLI for quick inspection of models.

Should we make this a .NET global tool?

**Comment by shauheen** [comment]
with #1093 merged, I am going to close this issue. @markusweimer please open another issue if you think more work is needed. Thanks,.
