### ISSUE TITLE
Enable/increase verbosity for LearningPipeline and its components (like TextFeaturizer)

### ISSUE THREAD

**Issue by GalOshri** [dotnet/machinelearning#8]
Transforms like `TextFeaturizer` do not show sufficient logs. These logs exist but are currently not exposed.

In an experiment where the TextFeaturizer is the first transform, a user might not see any logs for several minutes, which might suggest there is an issue. Increasing verbosity will clarify what is happening.

**Comment by shauheen** [comment]
@GalOshri should we update this issue for new Proposed API?

**Comment by GalOshri** [comment]
I believe this is solved now, as `ConsoleEnvironment` in the new API enables toggling [verbosity](https://github.com/dotnet/machinelearning/blob/160b0dfa8de334c8c6db3e0bf58653def0cea171/src/Microsoft.ML.Core/Environment/ConsoleEnvironment.cs#L365)
