### ISSUE TITLE
CpuMath: Sse code is executed when Avx is available, except on .NET Core 3.0

### ISSUE THREAD

**Issue by helloguo** [dotnet/machinelearning#80]
### System information

- **Windows 10 Enterprise**:
- **dotnet Version: 2.1.105**: 

### Issue

- **What did you do?**
I followed the tutorial https://www.microsoft.com/net/learn/apps/machine-learning-and-ai/ml-dotnet/get-started/windows to install SDK and create the sample app. I ran this example in release mode `dotnet run -c Release` and profiled it.
- **What happened?**
The profiling shows Sse code is executed as shown below.
![capture](https://user-images.githubusercontent.com/18431130/39768870-5cc25096-529f-11e8-942a-366943de137f.PNG)

- **What did you expect?**
Since my machine is Avx capable and `AddScale ` has Avx version https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.CpuMath/Avx.cs#L721, I would expect the Avx version is used.

**Comment by helloguo** [comment]
Thank you for explaining. Closing this issue if there is no other concern,

**Comment by danmosemsft** [comment]
I think it's fine to have the issue open, in case someone has the (considerable) motivation to enable AVX support in the native code. (Starting by undeleting the file, then wiring it up as needed, with perf measurements and tests.)

**Comment by helloguo** [comment]
Adding AVX CPP implementation would benefit Full Framework, which has no C# HW Intrinsic available today. I guess it really depends on the scenarios and how often people use Full Framework vs .NET Core when developing and deploying ML.NET applications.

**Comment by codemzs** [comment]
closing this issue as there is no plan to enable AVX support in the short-term. In the short term our goals are around ONNX, AutoML and DNN training scenarios.
