### ISSUE TITLE
InvalidOperationException: numClasses must be at least 2.

### ISSUE THREAD

**Issue by nilay-kothari** [dotnet/machinelearning#802]
### System information

Ml.Net version : 0.4.0

### Issue

I have written a multi classification code using ml.net 0.4.0. When I run the code, it throws following exception:

InvalidOperationException: numClasses must be at least 2.

### Source code / logs

LearningPipeline pipeline = new LearningPipeline();

			pipeline.Add(new TextLoader(datapath).CreateFrom<WETRelevanceScore>(useHeader: true));

			pipeline.Add(new Dictionarizer("Label"));

			pipeline.Add(new TextFeaturizer("FeaturesA", "SubjectiveAnswer") {
				KeepPunctuations = false, 
				OutputTokens = true, 
				KeepNumbers = false, 
				KeepDiacritics = false, 
				TextCase = TextNormalizerTransformCaseNormalizationMode.Lower, 
				VectorNormalizer = TextTransformTextNormKind.L2, 
				StopWordsRemover = new PredefinedStopWordsRemover(), 
				CharFeatureExtractor = new NGramNgramExtractor() {NgramLength = 3, AllLengths = false}, 
				WordFeatureExtractor = new NGramNgramExtractor() {NgramLength = 3, AllLengths = true},
			});

			pipeline.Add(new WordEmbeddings(("FeaturesA_TransformedText", "FeaturesB")));
			// Combine the features from word embeddings and text featurizer into one column 
			pipeline.Add(new ColumnConcatenator("Features", "FeaturesA", "FeaturesB"));
			pipeline.Add(new StochasticDualCoordinateAscentClassifier());
			pipeline.Add(new PredictedLabelColumnOriginalValueConverter() { PredictedLabelColumn = "PredictedLabel" });

			var model = pipeline.Train<WETRelevanceScore, WETRelevancePredictor>();

the data I am using for training is in following format:

SubjectiveAnswer | Score
-- | --
Being a professional in your chosen field   means much more than wearing a coat and tie or possesing a college degree and   a noted tittle. Professionalism also has to do with how you conduct yourself   during your business affairs. True professionals posses a number of   importance characteristics that can apply to virtually any type of business.  | 9
A corporate professional life we should   be aware of some things : reliability : To come in corporate professional   life first should get job done and responsible to the people and following   through the promises in timely manner. competence: professional strive to   become expert in this field which sets them apart from the rest of the   pack. | 9

**Comment by Zruty0** [comment]
The exception indicates that the label column (I guess "Label" in your dataset) contains fewer than two different values, and therefore you cannot train a multiclass classifier towards that label.

Are you using your 'Score' values as labels? Are you renaming them to 'Label' somewhere? Are there more than one different value of the score in your training set?

**Comment by nilay-kothari** [comment]
I have more than 2 values in score column. here are some more samples.


The term Professional   is thrown around quite a bit these days, perhaps too much.I do it my self but   what exactly does it mean to be a professional ? 1. Put Customer satisfaction   first. 2. Make expertise your specialty. 3. Do make than expected  | 9
-- | --
If we want to grow with the company in   our professional career, we should have some great quality skills which   conclude to our professional career. Here i am writing about technical   professional career. So we should have good aptitude skills, analytical skills,   good reasoning skills, good problem solving skills.  | 7
Being a professional in life is like   something more important than your daily routine . So Being an ideal   corporate professional , you have to must follow some important   characteristics . First characteristics is Appearance that is visible to   everyone and it play a vital role in corporate world.  | 8
A professional must look   professional.He/she should place his work above everything. He/She should   have an attitude of professionalism incorporated deep in his daily life. A   mastery over body language to influence and motivate people around.  | 10
A person with the characteristics of idea   professional is non to be ruled over the world. During student graduation   time lots of things made to make a student ideal as in school time child is   taught to wake-up early in the morning ,brush your teeth, go to school on   time ,do your work on time which makes a child ideal towards his work. | 2

Here is my class that I use for Input

public class WETRelevanceScore {
		[Column(ordinal: "0")] 
		public string SubjectiveAnswer;

		[Column(ordinal: "1", name: "Label")]
		public float Score;
	}

I have named column Score as Label here.
