### ISSUE TITLE
Make IChannel `.Done` Done

### ISSUE THREAD

**Issue by TomFinley** [dotnet/machinelearning#803]
One of the most fun design decisions w.r.t. `IChannel` is that it should have a `.Done()` method, analogous perhaps to things we see in databases like commits and whatnot. The purpose is to indicate that the channel actually reached the end of the code block successfully, in the way that the code writer thought it would, and thus distinguish between the case where the channel was disposed because we reached the end vs. the channel was disposed for some other reason. (Because, I guess, the alternative, an exception being thrown and interrupting the flow of code, wasn't conspicuous enough of a signal.)

That's fine if a little redundant. However, this *does* incur a cost to code. Consider for example this code here:

https://github.com/dotnet/machinelearning/blob/a3b67d393714ebeb873a41af82cd22ea7311e44c/src/Microsoft.ML.Core/Data/IHostEnvironment.cs#L229-L235

Now, it *could* have been written like this:

```csharp
using (var ch = host.Start(channelName))
    return func(ch);
```

But we can't, because, of course, we need to make sure we call `ch.Done()`, which means we have to store the return value somewhere else, etc. etc.

By itself that isn't that bad, except we use channels literally everywhere. So we see this pattern repeated over, and over, and over again. I've done this so often I even have a standard variable name I personally use to work around this thing, `retval`.

Yet, despite being used everywhere in the codebase, over the years I can count the number of times that check has been useful on exactly zero of my hands. In fact it is so useless that we never actually bothered to consider it an error condition, since there are far more examples of people forgetting to do that than examples where it actually signaled a problem -- refer to the example above, the "mistake" is far more obvious than the correct actually implemented pattern -- and again, the alternative, an exception being thrown, was far more obvious anyway. So it just writes an easily ignored warning to the *trace* stream if it's detected (which is a logging layer people by default cannot visibly access anyway).

Maybe we ought to get rid of it, just rely on the fact that the channel is being disposed (which contrary to this `Done` thing does convey very useful information), and simplify a bunch of code.

**Comment by Zruty0** [comment]
Yea, I agree. Frankly, I thought we did away with channels' `Done` before, that's why I didn't care to do it in #798 .
