### ISSUE TITLE
Positive and Negative Values from Binary Classification

### ISSUE THREAD

**Issue by MaxAkbar** [dotnet/machinelearning#805]
Is there any way to get a list of positive vs. negative values from a model if using binary classification? Also, a follow-up question. When getting a prediction on a binary classification can any information be passed as to why the engine selected positive vs. negative?

**Comment by MaxAkbar** [comment]
Looks like I can get Probability and Score as outputs when doing a prediction. Is there any documentation on it by any chance?

**Comment by codemzs** [comment]
please refer to the binary classification samples here https://github.com/dotnet/machinelearning/tree/master/docs/samples/Microsoft.ML.Samples/Dynamic
