### ISSUE TITLE
Improvements on the Gitter channel setup

### ISSUE THREAD

**Issue by veikkoeeva** [dotnet/machinelearning#82]
A few improvement suggestion to the Gitter channel:

It would be really nice if clicking the channel name would open the Github page of this project, an image for that what I mean:
![Channel name](https://user-images.githubusercontent.com/5158694/39770471-c78b0fc8-52f7-11e8-80ef-955ce4659036.png)

It would also be nice to see repository events in the side-panel, commits, issues and so forth, again an image to clarify:

![Repository events](https://user-images.githubusercontent.com/5158694/39770520-ec883c4c-52f7-11e8-83d2-5aa63b6c1502.png)

**Comment by terrajobst** [comment]
@shauheen 

I've registered the necessary web hook which will present the data. The app doesn't need write access to this repo.

Not sure about the link; I suspect the linking from the title works if the room name happens to match a repo name, which isn't the case here.

**Comment by shauheen** [comment]
Thanks @terrajobst . Closing the issue as I believe this is what we can do now. @veikkoeeva please feel free to re-open if you have other suggestions.
