### ISSUE TITLE
CpuMath Enhancement: Rename input arguments of CpuMath SSE/AVX intrinsics

### ISSUE THREAD

**Issue by briancylui** [dotnet/machinelearning#824]
Style changes needed to solve part of https://github.com/dotnet/machinelearning/issues/823

## Details
- Rename input arguments of methods in `src\Microsoft.ML.CpuMath\CpuMathUtils.netcoreapp.cs` and `src\Microsoft.ML.CpuMath\Sse.cs`, to make them more informative, e.g.:
* for `MatTimesSrc`, change `tran` into `transpose`

* for `a` and `b`, change them into `src` and `dst`

**Comment by jwood803** [comment]
Hey, @briancylui. I was going to mess with this issue, as well.

I did notice a few methods have parameter names of `src` as well as a name of `a`. Is there something else to name `a` to in this case?

https://github.com/dotnet/machinelearning/blob/3e53e392bcd4d33b7efc3784c9b58a8a6c3b2602/src/Microsoft.ML.CpuMath/CpuMathUtils.netcoreapp.cs#L267

**Comment by briancylui** [comment]
@jwood803: Thanks for your kind help!  According to previous PR reviews, there were voices to change `a` into `scale`, but not so sure about `src` and `dst`.  Adding @eerhardt and @tannergooding since they also raised new naming suggestions earlier.

**Comment by eerhardt** [comment]
I would just spell the words out - `source` and `destination`.
