### ISSUE TITLE
CpuMath: any plan to use AVX-512 in the native code used when not on .NET Core 3.0?

### ISSUE THREAD

**Issue by helloguo** [dotnet/machinelearning#83]
It seems [CpuMathNative](https://github.com/dotnet/machinelearning/tree/master/src/Native/CpuMathNative) has both Sse version and Avx version. Is there any plan to implement the AVX-512 version?

**Comment by HFadeel** [comment]
Yeah I would like to see support for AVX-512

**Comment by danmosemsft** [comment]
This would be dependent on bringing back AVX support in https://github.com/dotnet/machinelearning/issues/80.
