### ISSUE TITLE
CpuMath Enhancement: Accelerate loops in hardware intrinsics implementation

### ISSUE THREAD

**Issue by briancylui** [dotnet/machinelearning#831]
Style changes needed to solve part of https://github.com/dotnet/machinelearning/issues/823

## Details
-  Make while loops more efficient in `src\Microsoft.ML.CpuMath\SseIntrinsics.cs` and `src\Microsoft.ML.CpuMath\AvxIntrinsics.cs` with modified bound checking:
``` log
var remainder = count % elementsPerIteration;
float* pEnd = pdst + (count - remainder);
while (pDstCurrent < pEnd)
{ … }
```

**Comment by danmosemsft** [comment]
@tannergooding is this still relevant? I am not sure where it applies, after #835

**Comment by tannergooding** [comment]
No, they look like dupes of eachother.
