### ISSUE TITLE
CpuMath Enhancement: Use FusedMultiplyAdd in hardware intrinsics APIs

### ISSUE THREAD

**Issue by briancylui** [dotnet/machinelearning#832]
Style changes needed to solve part of https://github.com/dotnet/machinelearning/issues/823

## Details
-  In `src\Microsoft.ML.CpuMath\SseIntrinsics.cs`, Use `FusedMultiplyAdd` to replace `srcVector = Sse.Multiply(srcVector, scaleVector);` in `AddScaleU`.  It would be part of any AVX related code-work.

**Comment by helloguo** [comment]
@eerhardt @danmosemsft 
Is anyone doing this work? if not, please assign it to me :)
