### ISSUE TITLE
CpuMath Enhancement: Add unit tests for software fallbacks of hardware intrinsics

### ISSUE THREAD

**Issue by briancylui** [dotnet/machinelearning#834]
Style changes needed to solve part of https://github.com/dotnet/machinelearning/issues/823

## Details
-  Add unit tests for software fallback implementations, particularly for `MatTimesSrc`.

Reference:
- The software fallback implementations are in `src\Microsoft.ML.CpuMath\CpuMathUtils.netcoreapp.cs`, encapsulated in the following switching paradigm:
``` log
if (Avx.IsSupported)
{
    // AvxIntrinsics
}
else if (Sse.IsSupported)
{
    // SseIntrinsics
}
else
{
    // Software fallback
}
```

- Unit tests are implemented in `test\Microsoft.ML.CpuMath.UnitTests.netcoreapp/UnitTests.cs`
- To turn on the software fallback implementation in unit tests, you may have to turn off the environment variable `COMPlus_FeatureSimd`.

**Comment by danmosemsft** [comment]
Covered by #1156

**Comment by danmosemsft** [comment]
Covered by #1156
