### ISSUE TITLE
Make TextFeaturizer's extractors etc. configurable again

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#838]
#801 is making the parameters default and hardcoded for the following options of Text featurizer:
- Stop word remover (defaults to none) - Fixed in #2962 
- Custom term dictionary (defaults to none) - This parameter is hidden
- Word feature extractor (defaults to unigrams) - Fixed in #2911 
- Char feature extractor (defaults to 3-char) - Fixed in #2911 

Once individual building blocks become estimators, we should bring these parameters back (in a form of estimator for word/char extractor etc.). 

Or maybe we shouldn't, and instead just demonstrate how to compose your version of text transform from the individual building blocks?

**Comment by eerhardt** [comment]
Is this strictly adding new API? Can this be done without a public API breaking change? If so, I think we can remove it from Project 13, and it can be added after v1.0.

But if this requires a public API breaking change, then it can be left in Project 13.
