### ISSUE TITLE
The file [frozen_model.pb] is missing in the repo

### ISSUE THREAD

**Issue by elbruno** [dotnet/machinelearning#839]
### Issue

- **What did you do?** 
I'm trying to run the test [ machinelearning/test/Microsoft.ML.Tests/Scenarios/TensorflowTests.cs]

- **What happened?** 
It seems that I need the file [var model_location = "cifar_model/frozen_model.pb"] and it's not in the repo.

- **What did you expect?**
I can't train the sample test pipeline without the TensorFlow frozen model.

Any guidance or help?

Thanks

**Comment by elbruno** [comment]
I couldn't find the file because I was missing the package [Microsft.ML.TensorFlow.TestModels] in the test project. All started with the typo in the package name.
![image](https://user-images.githubusercontent.com/3533489/45156173-6366b700-b1ab-11e8-887b-006026e16567.png)

**Comment by CESARDELATORRE** [comment]
@elbruno - Check out the same sample running in a console app, which includes the model file and everything needed, that I have in my repo, here:
https://github.com/CESARDELATORRE/TensorFlowMLNETSamples/tree/master/src/TensorFlowCifarModel 
It is probably less confusing. ;)
