### ISSUE TITLE
Train operation should be cancellable.

### ISSUE THREAD

**Issue by kant2002** [dotnet/machinelearning#844]
### System information

- **OS version/distro**: All supported
- **.NET Version (eg., dotnet --info)**: All supported.

### Issue

- I attempt to write training of the models using API as part of internal pipeline
- After I run `pipeline.Train()` I was not able to stop training using standard .NET CancellationToken API
- Please provide ability to cancel such long running operation as training.

**Comment by Zruty0** [comment]
With the new API we are going to expose `IHostEnvironment` to you (see https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Core/Data/IHostEnvironment.cs).
Here's how you can cancel a process using that:
```c#
var env = new TlcEnvironment(); // Class name subject to change.
var host = env.Register("Cancelable");

var pipeline = ... // create pipeline using 'host'.
pipeline.Fit(data);
```
If you call `host.StopExecution()`, the training process will terminate with an exception.
I am not sure why we discarded the standard `CancellationToken` API. It was definitely considered at that time, but I forgot what was the reason not to use it.

**Comment by kant2002** [comment]
@Zruty0 are the IHostEnvironment could be used in the 0.4.0, or I should use nightlies for accessing this functionality? I'm aware about API change, just do not research on new API yet.

**Comment by klausmh** [comment]
Could you provide an example of "var pipeline = ... // create pipeline using 'host'." in the current version of ML.NET?

**Comment by codemzs** [comment]
Done as part of https://github.com/dotnet/machinelearning/pull/2797

**Comment by kant2002** [comment]
Thanks!
