### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by FIVIL** [dotnet/machinelearning#86]
hi, is there (or will there be) any support for training and doing stuff on gpu using ML.net too or no???

**Comment by glebuk** [comment]
Great question.  GPU is excellent for accelerating DNN training and inference.  Currently we do not offer DNN learners, so at this point of our release we do not have GPU acceleration available.  However, as this is a general-purpose machine learning framework, it does support a variety of machine learning algorithms, including neural nets such as Cognitive Toolkit (CNTK).  Adding support for leading DNN packages within ML.NET is on our roadmap.  As a result, we will likely support GPU training and inference in the future.

**Comment by ashic** [comment]
R has GPU support for a few things besides neural nets: 
http://www.r-tutor.com/gpu-computing

**Comment by turowicz** [comment]
Sorry to say, but 

No GPU support = no real use in production

**Comment by nightgnomes** [comment]
Any progress on adding GPU support?  I agree with the sentiment that without GPU support, this is not a viable solution for serious ML applications.  I wish there were a better .NET based framework for using CNTK which does support GPU.  Seems natural the ML.NET would be exactly that, but wince there is no support for this currently, it's a big problem.

**Comment by isandburn** [comment]
agreed. the recent resurgence of popularity in AI/ML/deep-learning is because today's GPUs are far more accessible than super-computing centers.  if you build it, they will come.

**Comment by deepakkumar1984** [comment]
> @FIVIL
> Great question. GPUs are excellent for accelerating DNN training and inference. Currently we do not offer DNN learners. At this point, we do not have GPU-accelerated components available. However, ML.NET is a general-purpose machine learning framework. It can support a variety of machine learning algorithms, including neural nets such as Cognitive Toolkit (CNTK). Adding support for leading DNN packages within ML.NET is on our roadmap. We will likely support GPU training and inference in the future for specific learners and transforms that can benefit from it.

Working on a high level wrapper to build and execute kernel written in C# on special hardware: https://www.tech-quantum.com/gpu-accelerated-programming-with-amplifier/
https://github.com/tech-quantum/Amplifier.NET

**Comment by codemzs** [comment]
People on this thread asking for GPU support, can you please specify the scenario  where this might be beneficial for you? Please note adding DNN training support is on our roadmap in the coming months and that WILL have GPU support but I want to be sure if there is some other scenario that I might be missing that might benefit from
GPUs?

**Comment by turowicz** [comment]
Realtime footage analysis at 4K resolution and 60 frames per second.

**Comment by Mercurial** [comment]
> People on this thread asking for GPU support, can you please specify the scenario where this might be beneficial for you? Please note adding DNN training support is on our roadmap in the coming months and that WILL have GPU support but I want to be sure if there is some other scenario that I might be missing that might benefit from GPUs?

are you saying we should train models that need GPU in another framework and then consume it in ML.NET

**Comment by ebarsoumMS** [comment]
@Mercurial no, DNN in ML.NET will support training on the GPU. And you can also consume it on the GPU. So you won't need to train on another framework.

**Comment by Mercurial** [comment]
> @Mercurial no, DNN in ML.NET will support training on the GPU. And you can also consume it on the GPU. So you won't need to train on another framework.

ah I see, thanks @ebarsoumMS I guess just needs more understanding on this part!

**Comment by codemzs** [comment]
@Mercurial Where did I suggest you should train models in another framework and then consume in ML.NET? I think I was clear that we plan to add DNN support in the coming month and it WILL have GPU support.

**Comment by ganik** [comment]
closing this as it original question has been answered

**Comment by Mercurial** [comment]
> @Mercurial Where did I suggest you should train models in another framework and then consume in ML.NET? I think I was clear that we plan to add DNN support in the coming month and it WILL have GPU support.

Thanks for the clarification

**Comment by gvashishtha** [comment]
Anyone on this thread looking for GPU acceleration for prediction in a non-DNN-based model? Would be interested in discussing your use case further, if so.

**Comment by maacpiash** [comment]
Any progress on GPU support?

**Comment by turowicz** [comment]
I've migrated to [NVIDIA Triton Server](https://github.com/NVIDIA/triton-inference-server/) for inference. It decouples inferencing my .NET code and is way better for model management, versioning and load-balancing across multiple GPUs. It's also much faster than Tensorflow Serving, should anyone wonder.

**Comment by harishsk** [comment]
closing this as it original question has been answered
