### ISSUE TITLE
F# Samples

### ISSUE THREAD

**Issue by isaacabraham** [dotnet/machinelearning#88]
There should be a sample project (or even just a set of scripts) that illustrate using the library from F#.

**Comment by glebuk** [comment]
We agree!  Would you be interested in creating a PR with a few F# samples? 
It would also be interesting to hear of any feedback on the API form the F# user perspective.

**Comment by isaacabraham** [comment]
I'm having a play around with it right now - there are a few things that spring to mind but I'll put them together in a single place. Whilst what's there now will work in F#, it's possible that to fully take advantage of F# there will need to be an thin wrapper library that adapts the pipeline to take advantage of F# pipelines etc.

**Comment by Ivanidzo4ka** [comment]
DRI RESPONSE: We at least have a test project which runs F# code.
But it uses legacy api, and probably need to be updated.

**Comment by shauheen** [comment]
Legacy API will be removed for the next release, this issue needs to be addressed soon.

**Comment by shauheen** [comment]
@codemzs can you please verify if this issue can be closed now.

**Comment by codemzs** [comment]
We have converted the F# project to use the new API. This issue can be closed.
