### ISSUE TITLE
Update documentation front page

### ISSUE THREAD

**Issue by isaacabraham** [dotnet/machinelearning#89]
On https://www.microsoft.com/net/learn/apps/machine-learning-and-ai/ml-dotnet, please update the text:

> Use your **.NET and C#** skills to easily integrate custom machine learning into your applications without any prior expertise in developing or tuning machine learning models.

to

> Use your **C# or F# on .NET** skills to easily integrate custom machine learning into your applications without any prior expertise in developing or tuning machine learning models.

If you can point me to the repo that contains this documentation I'm happy to submit the PR myself

**Comment by glebuk** [comment]
Before we make this claim we should ensure to have basic tests, samples, and userability validation. Support of additional languages is on our readmap.  It would be interesting to see any feedback on the current API with regards to F# usage.

**Comment by isaacabraham** [comment]
Hi!

I guess it depends on the level of support. The library is .NET compatible, ergo it supports F#. I'm running some code in F# with the library right now - you download the nuget package and start calling out to it, just like in C#. Not putting this in implies that the library doesn't work with F# and is C#-only, which simply isn't the case.

I understand your point but there must be a middle ground that allows you to put F# on the main page - it's ironic that F# is the "maths and science" language on the .NET stack (or at least, that's how MS has historically marketed it) and yet there's zero mention of F# on the ML page.

**Comment by asthana86** [comment]
Thanks Isaac. 

Completely agree. 

Will it help if we change the documentation page (dot.net/ml) to say "Use your .NET skills to easily integrate custom machine learning ... " vs. "Use your .NET and C# skills to easily integrate".

Also we are working on adding examples and samples to this repo #140, will it be possible to work together and and make sure F# is well represented. This will help others get started and help us work towards a good story for F#?

**Comment by asthana86** [comment]
There is also #88 as well.

**Comment by isaacabraham** [comment]
@asthana86 Indeed, that would help (although saying "C# and F#" might be even better!). Regarding samples, yes, I'd be happy (as would others I'm sure) to help build up some F# samples. At the moment I've not even been able to get the basic sample working (there's another issue I've raised on that) but in principle, yes. The important thing for the F# samples should be to keep them script-first (at least to start with) - from a learning point of view, scripts are way, way better than console applications. Hopefully from that we can build up an F# wrapper DSL that would make the library even nicer to play with from an F# point of view.

**Comment by asthana86** [comment]
We will make the change on dot.net/ml. 

+1 on the F# samples.

**Comment by rowanmiller** [comment]
The change is live

**Comment by isaacabraham** [comment]
Closing - thanks @rowanmiller!

**Comment by voronoipotato** [comment]
I was able to write the tutorial in F#. It's a little awkward because no records and everything is mutable but otherwise totally fine.

https://github.com/dotnet/machinelearning/issues/140

**Comment by isaacabraham** [comment]
@voronoipotato it's definitely possible, yes. Scripts require more work, however, because of the use of native dlls, and as you say, it's somehow awkward and certainly not idiomatic for F#.
