### ISSUE TITLE
Native dependencies of ML.NET

### ISSUE THREAD

**Issue by ericstj** [dotnet/machinelearning#895]
We should review and try to unify and document the native dependencies of ML.NET, in particular the VC-runtime.

Ideally we should try and build the native components in the same way that .NET Core does so that we don't impose any new requirements (eg: installing a different / specific version of the VC redist).

I checked a few DLLs using link /dump /imports and noticed a lot of instances of VCRUNTIME140 which we do not depend on for coreclr/clrcompression/clrjit/etc.

I just did this check for Windows but we should also look at a similar thing on linux.

We should also examine binary redists (like TensorFlow) so that we can understand if they are different and at least document their dependencies.

/cc @shauheen @tannergooding @danmosemsft @eerhardt

**Comment by eerhardt** [comment]
Do you know how to eliminate the import of `VCRUNTIME140`? I took the native build code/infrastructure from a mix of core-setup and corefx, but may have missed something in the CMake files.

**Comment by ericstj** [comment]
Here's what we do for CLRCompression.  Looks like we statically link it.
https://github.com/dotnet/corefx/blob/c1788c695d4349c522fc5620eff7d3dd46a0ab5f/src/Native/Windows/CMakeLists.txt#L63-L83

**Comment by eerhardt** [comment]
We’ve started static linking the VC Runtime in #1828. Closing.
