### ISSUE TITLE
Feature Importance with ML.NET

### ISSUE THREAD

**Issue by lefig** [dotnet/machinelearning#902]
Hi all,

I have been revisiting some models recently to deduce feature importance. To remove highly correlated items, features of no importance etc.

And judging from the issues raised so far, this theme has come up already. Such as Feature Importance with ML.NET #599.

Ideally, it should be possible to run a pipeline task not to generate a full model, but to profile the model data using a method such as nearest neighbour or PCA before rather than after the event.

Would it be possible to add such a feature (no pun intended:)) to the release road map?

Thanks
Fig

**Comment by codemzs** [comment]
We have this and you can see samples here https://github.com/dotnet/machinelearning/tree/master/docs/samples/Microsoft.ML.Samples/Dynamic

**Comment by codemzs** [comment]
Need more information but we have samples on PFI here https://github.com/dotnet/machinelearning/tree/master/docs/samples/Microsoft.ML.Samples/Dynamic

feel free to re-open.
