### ISSUE TITLE
Pixel extractor transform needs to have a per-channel offset argument

### ISSUE THREAD

**Issue by yaeldekel** [dotnet/machinelearning#903]
Some TensorFlow models require preprocessing of the image where a different offset is subtracted from every channel. For example: https://github.com/pudae/tensorflow-densenet/blob/master/preprocessing/densenet_preprocessing.py#L39. 
The ML.NET pixel extractor transform only has a global offset parameter, which means that preprocessing would need to be done outside of ML.NET.

**Comment by Zruty0** [comment]
I don't think the suggested solution is very elegant / sustainable. I believe there's more tensor-wide operations that we *should* support to improve the image handling story. Where would we keep them? Bundling it all inside `PixelExtractor` seems counter-intuitive. 

What do you think?

**Comment by Zruty0** [comment]
Also, @yaeldekel , are you currently working on this?

**Comment by codemzs** [comment]
We will do as part of TF.NET integration work.
