### ISSUE TITLE
TensorFlowTransform does not implement IDisposable.

### ISSUE THREAD

**Issue by abgoswam** [dotnet/machinelearning#906]
TensorFlowTransform does not implement IDisposable. 

Instead the Finalizer directly calls the private Dispose() method to free resources. We need to understand the reasoning behind ML.NET Transforms not implementing IDisposable

[Discussion](https://github.com/dotnet/machinelearning/pull/853#issuecomment-423236224)

**Comment by codemzs** [comment]
I don't see this as an issues as the same applies for every other transform. Please add more details to why you believe this is an issue and we can reopen.
