### ISSUE TITLE
How do you load data from an in-memory data set?

### ISSUE THREAD

**Issue by isaacabraham** [dotnet/machinelearning#91]
The only sample I can see uses the `TextLoader` to import data from a CSV file. How do you load in arbitrary data from e.g. a record or array and specify labels etc. on there?

Thanks!

**Comment by Ivanidzo4ka** [comment]
Just as reminder, this is preview, and we will definitely come up with better approach.
For now we have class which is not part of public API (by this, I mean it exist in Microsoft.ML.Runtime namespace other than Microsoft.ML)

**Comment by Ivanidzo4ka** [comment]
Sorry, fat fingered issue.
As part of open API, we currently don't have it, but we working on it.
As part of internals we have ArrayDataViewBuilder and you can see example of it usage here: https://github.com/dotnet/machinelearning/blob/c023727b76970ab913ec1ce38276508835c17bcf/test/Microsoft.ML.Predictor.Tests/TestTransposer.cs#L148

**Comment by Ivanidzo4ka** [comment]
For one who will work on this in future.
we have DataViewConstructionUtils internal class which does desired.

https://github.com/dotnet/machinelearning/blob/c023727b76970ab913ec1ce38276508835c17bcf/src/Microsoft.ML.Api/DataViewConstructionUtils.cs#L17

Maybe we need to add ArrayDataView, and we need to decide should we expose IHostEnvironment or not, and where in new API it belongs.

**Comment by Ivanidzo4ka** [comment]
also copy of #10

**Comment by isaacabraham** [comment]
@Ivanidzo4ka whichever way you go, make it as simple as possible to consume. This means either allowing F# Records / C# Classes, with either attributes or some guidance to specify labels / features etc., or (and this should definitely also be supported) support for naked arrays or sequences of either arrays (so a 2x2 array) or tuple data.

**Comment by danroot** [comment]
Looking for this as well.  A couple use case I can see are:
1) Loaders other than flat files.  SqlLoader, etc
2)Scenarios where the schema is not known at compile time - ie a command line tool that lets users pass in arbitrary csv file.

**Comment by TomFinley** [comment]
Hi @isaacabraham and @danroot , thanks for the feedback. @Ivanidzo4ka introduced an attempt to solve this issue in #106 , though I see that PR did not link to this issue but rather the pre-existing #10 . Is it possible for you to try it, and provide feedback on whether it does what you need?

**Comment by isaacabraham** [comment]
Will give it a bash in the coming days - thanks!
