### ISSUE TITLE
Fix AP and OGD metadata propagation and behavior

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#910]
In the process of writing #909 I discovered that AP is now seemingly uncalibrated, and cannot accept float labels, and OGD throws at training. 

Enable the `OnlineLinearWorkout` test in #909 and fix the resulting bugs.

**Comment by Zruty0** [comment]
Also, the estimators should not take args and use feature/label/weight columns from these args

**Comment by sfilipi** [comment]
Najeeb is seeing that OVA with AP runs x2 times faster. Look on whether it is related to the AP lack of calibration. Dataset WikiDetox160 cleaned.
