### ISSUE TITLE
Trying to left-outer join two datasets using a PK/FK

### ISSUE THREAD

**Issue by ftdube** [dotnet/machinelearning#915]
Is there any way to manipulate the input data in order to join two distinct datasets using a primary key/foreign key?  Is the expectation that the input from the TextLoader is always partially pre-processed?

**Comment by Zruty0** [comment]
Generally, in ML.NET we tried to move away from relational operations, and assume that the input data is already a single 'view' (think SQL view).

The reasoning was that there has been a lot of research and a lot of work already done for relational operations, and we'd rather not make a mediocre effort at that.

So, yes, the expectation is that any JOINs and other relational operations are conducted prior to loading the data into ML.NET

**Comment by ftdube** [comment]
Got it, makes total sense, thank you :)
