### ISSUE TITLE
Categorical Feature and FastTree

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#919]
FastTree has a very powerful mechanism to process categorical features. However, which feature is considered as categorical is not described anywhere in doc. Some questions a data scientist may want to ask:
1. How to make feature categorical if they are stored as floats such as 1.00 and 128.00?
2. How does categorical metadata propagate through the learning pipeline? For example, some transforms may drop those metadata so that categorical features are no longer categorical after them.
3. How to make categorical not considered as categorical in FastTree?

Note that [LightGBM](https://lightgbm.readthedocs.io/en/latest/Python-API.html) has a nice description for how they handle categorical features. Let me just copy it here.
_categorical_feature (list of strings or int, or 'auto', optional (default="auto")) – Categorical features. If list of int, interpreted as indices. If list of strings, interpreted as feature names (need to specify feature_name as well). If ‘auto’ and data is pandas DataFrame, pandas categorical columns are used._ 

Thanks,

**Comment by Zruty0** [comment]
We should have documentation about how FastTree currently takes categorical inputs. 

It is also unfortunate that FastTree and LightGBM both handle categorical inputs, but do so differently :)

**Comment by codemzs** [comment]
You apply categorical transforms before feeding in the features vector to fasttree or lightgbm, this adds metadata to the features that tells what subsets are categorical features. Then you do the training with useCat = true. I believe the current documentation of fasttree does explain what useCat does.
