### ISSUE TITLE
Time series and forecasting

### ISSUE THREAD

**Issue by TestIprel** [dotnet/machinelearning#929]
Ml.net version 0.5
- When you plan to release a versione that include a Time series forecasting trainer ??

**Comment by GalOshri** [comment]
This is on the roadmap but we don't have a concrete date yet. @TestIprel, can you share a few more details about your use case (e.g. what kind of data do you have)? Do you need any particular approach to forecasting?

**Comment by TestIprel** [comment]
I have a simple data that I load from one sensor such as temperature values, or many of them (umidity, pressure, eccc).
This produce a time series model data [time, sensor value], and my goal is to predict/forecasting the future values of sensor.
So, i need to undestand which algorithm is the best solution for me and how to provide my data model to algorithm.

**Comment by paulpce** [comment]
I'm also interested in this for fairly standard sales forecasting based on historical sales, but ideally also including seasonality and other influencing factors such as marketing campaigns, public holidays, new product releases, etc.

**Comment by bbjoern** [comment]
Same for me: I would need standard sales forecasting based on historical sales data

**Comment by Tealons** [comment]
Same here... See [](https://github.com/dotnet/machinelearning/issues/978)

**Comment by veikkoeeva** [comment]
Relational time series, or time series with graph data (sparse data) would be a really interesting. Some examples:
- [https://arxiv.org/abs/1704.06498](Time Series Prediction for Graphs in Kernel and Dissimilarity Spaces)
- [Joint Modeling of Event Sequence and Time Series with Attentional Twin Recurrent Neural Networks](https://arxiv.org/abs/1703.08524)

Broadly speaking the idea here is that events have a causal relationship and they happen (or miss to happen) in some point of time. Some food for thoughts (without going into more concrete examples), it appears many spatio-temporal problems have the characteristics of time series and "graph like" relation.

**Comment by artidoro** [comment]
There is an ongoing project to introduce time series models in ML.NET (with some functionalities already being added), #978 will be used to track this effort. We will be adding documentation and tutorials for the new features as they are implemented. We welcome your thoughts and questions on the development of this new feature. @codemzs, @ganik or @montebhoover  will probably be able to answer them.
