### ISSUE TITLE
ComponentCatalogue: private constructors for estimators

### ISSUE THREAD

**Issue by artidoro** [dotnet/machinelearning#932]
Only one constructor per estimator should be **public** and presented to the end user. The constructor should require the arguments that are needed to initialize the estimator.

We also need to have another constructor with arguments (IHostEnvironment env, Arguments args) for MAML to work. This constructor should be **private**, so that it does not appear as an option to the end user.

Currently the ComponentCatalogue does not recognize any private constructors.

**Comment by Ivanidzo4ka** [comment]
Can you give an example of code in our repo which need to be changed?
And I would disagree with statement
>Only one constructor per estimator should be public and presented to the end user. 
I find useful to have multiple constructors with different granularity in arguments.

**Comment by artidoro** [comment]
I think you made the change that allows internal/private constructors to be picked up by the component catalog, so this issue is no longer relevant.
