### ISSUE TITLE
Release 0.5 feedback

### ISSUE THREAD

**Issue by lefig** [dotnet/machinelearning#934]
Firstly, a very big thank you and congratulations to all involved with the latest release. I am, particularly looking forward to exploring the new API and specifically accessing model feature selection/scores.

In the meantime, we have incomplete MI generated and am not sure if this is related to the changes. ..
Displayng metrics for Momentum Model Regression
Not adding a normalizer.
Making per-feature arrays
Changing data from row-wise to column-wise
Processed 423 instances
Binning and forming Feature objects
Reserved memory for tree learner: 363168 bytes
Starting to train ...
Not training a calibrator because it is not needed.
*************************************************
*       Metrics for Fast Tree
*------------------------------------------------
*       R2 Score: -1.05
*       Absolute loss:
*       Squared loss:
*       RMS loss:
*************************************************
Not adding a normalizer.
Making per-feature arrays
Changing data from row-wise to column-wise
Processed 423 instances
Binning and forming Feature objects
Reserved memory for tree learner: 363168 bytes
Starting to train ...
Not training a calibrator because it is not needed.
*************************************************
*       Metrics for Fast Forest
*------------------------------------------------
*       R2 Score: 0.05
*       Absolute loss:
*       Squared loss:
*       RMS loss:
*************************************************

I have a theory though - that this is related to some data points being not sufficiently linear. Could this be correct?

**Comment by GalOshri** [comment]
Is the issue that some of the metrics are blank? Could you please share the ML.NET code and perhaps some sample data if possible?

**Comment by lefig** [comment]
Sure thing. Yes, the metrics are left blank and that is what has me stumped. The code runs as follows...

 public void FeatureSelection(string trainingDataLocation, string testDataLocation)
        {
            Console.WriteLine("Displayng metrics for Trend Regression model");

            // STEP 1: Create a model            
            var fastTreeModel = new RegressionTrendBuilder(trainingDataLocation, new FastTreeRegressor()).BuildAndTrain();

            // STEP2: Test accuracy
            var modelEvaluator = new RegressionTrendEvaluator();

            var fastTreeMetrics = modelEvaluator.Evaluate(fastTreeModel, testDataLocation);
            Metrics.PrintMetrics("Fast Tree", fastTreeMetrics);

            var fastForestModel = new RegressionTrendBuilder(trainingDataLocation, new FastForestRegressor()).BuildAndTrain();
            var fastForestMetrics = modelEvaluator.Evaluate(fastForestModel, testDataLocation);
            Metrics.PrintMetrics("Fast Forest", fastForestMetrics);

            var poissonModel = new RegressionTrendBuilder(trainingDataLocation, new PoissonRegressor()).BuildAndTrain();
            var poissonMetrics = modelEvaluator.Evaluate(poissonModel, testDataLocation);
            Metrics.PrintMetrics("Poisson", poissonMetrics);

            var gradientDescentModel = new RegressionTrendBuilder(trainingDataLocation, new OnlineGradientDescentRegressor()).BuildAndTrain();
            var gradientDescentMetrics = modelEvaluator.Evaluate(gradientDescentModel, testDataLocation);
            Metrics.PrintMetrics("Online Gradient Descent", gradientDescentMetrics);

            var fastTreeTweedieModel = new RegressionTrendBuilder(trainingDataLocation, new FastTreeTweedieRegressor()).BuildAndTrain();
            var fastTreeTweedieMetrics = modelEvaluator.Evaluate(fastTreeTweedieModel, testDataLocation);
            Metrics.PrintMetrics("Fast Tree Tweedie", fastTreeTweedieMetrics);

            var additiveModel = new RegressionTrendBuilder(trainingDataLocation, new GeneralizedAdditiveModelRegressor()).BuildAndTrain();
            var additiveMetrics = modelEvaluator.Evaluate(additiveModel, testDataLocation);
            Metrics.PrintMetrics("Generalized Additive Model", additiveMetrics);

            var stochasticDualCorordinateAscentModel = new RegressionTrendBuilder(trainingDataLocation, new StochasticDualCoordinateAscentRegressor()).BuildAndTrain();
            var stochasticDualCorordinateAscentMetrics = modelEvaluator.Evaluate(stochasticDualCorordinateAscentModel, testDataLocation);
            Metrics.PrintMetrics("Stochastic Dual Coordinate Ascent", stochasticDualCorordinateAscentMetrics);

            // STEP 3: Make a test prediction
            VisualizeTenPredictionsForTheModel(fastTreeTweedieModel, testDataLocation);
            fastTreeTweedieModel.WriteAsync(@".\Model.zip");

            //STEP 4: Paint regression distribution chart for a number of elements read from a Test DataSet file
            PaintChart(fastTreeTweedieModel, testDataLocation, 100, new string[] { });

            Console.ReadLine();
        }

Thanks for taking the time to look.

**Comment by codemzs** [comment]
please try the stable API.
