### ISSUE TITLE
Public space such as Wiki for accumulating knowledge about ML.NET

### ISSUE THREAD

**Issue by wschin** [dotnet/machinelearning#948]
Do we have any places like a Wiki? I'd like to have a place to share some small knowledge related to ML.NET. Here is an example.
Today, I changed the signature of SaveOnnx and then got two tests failed, TestGeneratedCSharpAPI and EntryPointCatalog. The solution is very straightforward, when you know the answer.

Solution:

1. Open Microsoft.ML.sln under Visual Studio
2. Go to Test Explorer
3. Find the test code of `RegenerateEntryPointCatalog()` in TestEntryPoints.cs and change its `[Fact(Skip = ".....")]` to `[Fact()]`' and then run it. Then, you will see (via `git diff`) core_mainfest.json gets changed. Include those changes into your commit. Note that with the existence of `Skip =`, Test Explorer may not execute your test anyway.
4. Find the test code of `RegenerateCSharpApi()` in CSharpCodeGen.cs and change its `[Fact(skip = ".....")]` to `[Fact()]` and also commit the changes (CSharpApi.cs) induced by running this test.

I personally like GitHub issues with a better tag name such as "knowledge" so that we have one place for all.

**Comment by wschin** [comment]
Another trick when your changes modify the output files produced by some tests and therefore those tests fail. It's pretty annoying when I am trying to locate those touched files. My solution is
1. Go to `BaseTestBaseline.cs` and set up a break point inside `protected bool CheckEqualityCore(string dir, string name, string nameBase, bool normalize, int digitsOfPrecision = DigitsOfPrecision)`
2. In `CheckEqualityCore`, you can find all the paths: `basePath` is the expected output file while `outPath` is the result produced by your code.
3. A broken test can be fixed by copying the `outPath` file to `basePath`.

**Comment by codemzs** [comment]
we have dot.net/ml and docs.
