### ISSUE TITLE
DnnAnalyzer does not work with TensorFlow's SavedModel format

### ISSUE THREAD

**Issue by abgoswam** [dotnet/machinelearning#990]
Currently the DnnAnalyzer only works with frozen models.

We need to fix it so it also works for TensorFlow's SavedModel format

**Comment by Ivanidzo4ka** [comment]
Hi @abgoswam  I believe we added this functionality few releases ago. Is it safe to close this issue?

**Comment by abgoswam** [comment]
Yeah. Thanks Ivan. We can close this -- verified it works with SavedModel format:

dotnet DnnAnalyzer.dll cifar_saved_model
