### ISSUE TITLE
ML.NET 0.5.0 not getting installed on VS2017 

### ISSUE THREAD

**Issue by kjsbedi** [dotnet/machinelearning#995]
### System information

- **OS version/Windows 10**:
- **.NET Version (VS2017)**: 

### Issue

- Trying to Install ML.NET 0.5

-Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Microsoft.ML 0.5.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by pfcnet** [comment]
Hi kjsbedi, first you have to install .NET  Framework v4.5.2(+) and after the .NET Core SDK.
Regards

**Comment by danmosemsft** [comment]
I'm not sure that you have to install the .NET Core SDK, although I don't have a machine without it to confirm. If you do not have it, you will need to be able to at least create and build a .NET Framework app. If that's not the case, please re-run setup and check .NET Framework development.
